### ISSUE TITLE
Package Brave for chocolatey

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1006]
Carried over from https://github.com/brave/browser-laptop/issues/8968See https://chocolatey.org/ for more info about what Chocolatey is

This task would be to package up Brave so that it can be uploaded into the package store for Chocolatey

Here's a link to some docs which have info about how to request ownership for a package (and has links to how to create):
https://chocolatey.org/docs/package-triage-process#package-request-package-missing

**Comment by dimqua** [comment]
I [have added](https://chocolatey.org/packages/bravebrowser) the beta version, but the package is not silent, since it seems that the current installer doesn't support any parameters yet. Can you fix it please?

And should I add developer versions too?I think I will stuck only with release version in the future.

**Comment by JonasDralle** [comment]
I have been using the newest version of Brave via chocolatey. I have uninstalled brave again after being repetitively annoyed at work by the very visual setup process.

Sometimes I update all my software in the night. I fear that Brave might halt the automatic update process due to brave keeping open (sometimes with active dialogue) a process after install.

**Comment by dimqua** [comment]
The release version (0.55.18) [has been added](https://chocolatey.org/packages/bravebrowser/0.55.18).

**Comment by aduh95** [comment]
What is the current status of this? The latest available version on Chocolatey is behind the release channel (currently 0.58.21, which is two months old)...

**Comment by dimqua** [comment]
@aduh95 https://github.com/chocolatey/chocolatey-coreteampackages/pull/1227

**Comment by bsclifton** [comment]
Looks like we're good here!
https://community.chocolatey.org/packages/brave/
