### ISSUE TITLE
Touch UI

### ISSUE THREAD

**Issue by framctr** [brave/brave-browser#10087]
Brave Desktop has good UI, but on my pc I prefer to use a bigger one. I noticed that Brave has a "touch UI" when I enable the (useless) Windows Tablet Mode. It would be great to extend this already present feature to the "normal" mode.

**Comment by rebron** [comment]
@scriptfx Did you want to by pass the OS Windows Tablet mode setting and just allow touch ui to occur in Brave automatically? With future issues, could you fill out the template and add some more specifics as your feature request/issue?

**Comment by scriptfx** [comment]
Yes I would like to have the Tablet Mode's UI also when Tablet Mode is off. I have a Microsoft Surface and I never use Tablet Mode because it is not so good for me. Having bigger controls would end up in a better experience.

I'm sorry. Next time I will follow the available template. I always check them before write, but this time I missed it.

**Comment by rebron** [comment]
@scriptfx If you have Chrome handy, the behavior is the same right and this is not a feature that's there either?
