### ISSUE TITLE
[Publishers] Transferring domain between accounts does not work

### ISSUE THREAD

**Issue by conferno** [brave/brave-browser#10219]
## Description 

Adding domains to another account deadlock them into a transition state.
Brave support does not respond to emails.
https://blog.archive.today/post/619753847471161344/id-love-to-send-you-bat-consider-registering

## Steps to Reproduce

   1. Add domains to an account, verify them by adding TXT records in DNS
   2. Wait few weeks
   3. Add domains to another account, verify them by adding TXT records in DNS (so they become invalid in the first account)
   4. Wait few weeks
   5. See the domains are still in transition state
   6. Wait few weeks
   7. Write to info@basicattentiontoken.org
   8. Wait few weeks
   9. Open this ticket

## Actual result:

![](https://i.imgur.com/cuEmrIf.png)

You see, this "short time" lasts more than 40 days already

**Comment by ybbond** [comment]
I don't quite understand what the content of this is, but I always redirected to here whenever I try opening https://arcive.is or https://archive.today

**Comment by eldarmark** [comment]
For some reason, as of just a few minutes ago, attempting to load archive.today redirects here now.  Archive.is was loading properly until I force-refreshed. 

This includes all archived websites.  Guessing the website owner of Archive.is was attempting to draw attention to the issue but accidentally did a meta-redirect?  Or github detects an iframe and force updates the URL?

**Comment by eldarmark** [comment]
As a brief update, this doesn't occur in Internet Explorer.  Only in Brave.

**Comment by steverusso** [comment]
I also experienced nearly all `archive.*` sites are redirecting here _only when using Brave_. Both Chromium and Firefox worked fine for me, so I checked the page source and found the following:
```
if (navigator.brave || false) document.location.href = 'https://github.com/brave/brave-browser/issues/10219';
```

Gave the issue a :+1:

**Comment by danlexo** [comment]
I'm using Brave on Mobile and Desktop, and I frequently make use of archive.* also.
If this is not resolved, I will be forced to switch browsers ☹

**Comment by Pika227** [comment]
Why are all pages of archive.md redirecting here for Brave users?

Imagine being so unprofessional as to damage the function of your site because you have a beef with Brave.

This is ridiculous.

**Comment by steverusso** [comment]
@Pika227 I don't think it's a beef, I think it's just a way of bringing a pretty important issue to the attention of Brave users and the developers. Not the way I would have gone about it, but I don't think it's malicious.

**Comment by eldarmark** [comment]
@Pika227 The people at Brave have apparently ignored him for over 2 months now.  Meanwhile, people are sending him BAT which is... going into limbo, apparently?

Personally, that worries me as I am very happy to support Brave, BAT, and Archive.is.  If the Brave team was seemingly losing my BAT that I was attempting to send to Archive.is... that's not acceptable.

**Comment by conferno** [comment]
> Imagine being so unprofessional as to damage the function of your site for your users because you have a beef with Brave.

That seems be the only way to survive among _effective professionals_ who put ads to an ad-free website and have disabled the checkbox "allow Brave to serve ads on my website".

**Comment by ybbond** [comment]
@conferno
> > Imagine being so unprofessional as to damage the function of your site for your users because you have a beef with Brave.
>
> That seems be the only way to survive among _effective professionals_ who put ads to an ad-free website and have disabled the checkbox "allow Brave to serve ads on my website".

I might understand your situation and I know how frustrating it is to not be noticed by the authorized part even more when the problem has money involved.

Right now, I only use Brave (ditched Mozilla because of inconvenience in its UI and integration, won't use chrome because many things).

I know my inconvenience cannot be compared to yours, but do you have any idea on how I can access archive.* with Brave?

Regards, Bandung

**Comment by volth** [comment]
> but do you have any idea on how I can access archive.* with Brave?

I see that Brave is superior in many aspects, especially on mobile.

Probably, we have to fork an "unbraved-brave" (akin to [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium)) with all the controversial BAT-coin related code removed.

**Comment by draekko** [comment]
> @conferno
> > Imagine being so unprofessional as to damage the function of your site for your users because you have a beef with Brave. That seems be the only way to survive among _effective professionals_ who put ads to an ad-free website and have disabled the checkbox "allow Brave to serve ads on my website".
> I might understand your situation and I know how frustrating it is to not be noticed by the authorized part even more when the problem has money involved. Right now, I only use Brave (ditched Mozilla because of inconvenience in its UI and integration, won't use chrome because many things). I know my inconvenience cannot be compared to yours, but do you have any idea on how I can access archive.* with Brave?

Try using a user agent switcher extension to spoof another browser.

**Comment by nibber55** [comment]
Please solve this @BrendanEich

**Comment by corymcdonald** [comment]
Hey everyone, this bug is currently being worked on in this PR - https://github.com/brave-intl/publishers/pull/2761

This will be resolved before the week is over. Thanks for your patience.

**Comment by volth** [comment]
> Hey everyone, this bug is currently being worked on in this PR - [brave-intl/publishers#2761](https://github.com/brave-intl/publishers/pull/2761)
> 
> This will be resolved before the week is over. Thanks for your patience.

Digging a bit into the logic, I doubt that adding retries would help. As long as the originating account (which verified domains once and cannot do it anymore, because it was lost or hijacked and the domain owner changed the verification codes) needs to approve the transfer and is able to reject the transfer.

Let's see.

**Comment by fearandtrembling** [comment]
I'm also being redirected from archive.is to here...

**Comment by corymcdonald** [comment]
Hey @conferno, I wanted to discuss what we've done so far to remediate this problem.

1. We have a [pull request in progress](https://github.com/brave-intl/publishers/pull/2761) to fix this from happening again. 
2. Have added alerting around this feature, particularly to detect channels "stuck" in the transfer phase. 

Most importantly we have preemptively kicked off the channel transfer logic with some added exception handling so **your channels have completed transferring**.

—
I wanted to add in that Brave Publisher Ads are opt-in by default, but changing those settings are disabled during channel transfer since another user is claiming ownership of that channel. Additionally we haven't released publisher ads yet, but we will notify users when we do.

**Comment by brianoflondon** [comment]
WTF? Why do I get here instead of Archive.is?

**Comment by y4my4my4m** [comment]
@brianoflondon lmao i dont know either but I had this happen when using dissenter-browser, looks like it's based on brave.

Why do not let chromium browsers in? Is it because they have an embedded "check if this page has an archive" feature when the page isn't found?

**Comment by brianoflondon** [comment]
I wrote up a [fuller explanation and posted it to Hive](https://peakd.com/leofinance/@brianoflondon/here-s-why-archive-today-isn-t-working-in-brave-right-now). If anyone doesn't want to plough through comments here to understand what is going on.

**Comment by conferno** [comment]
>> I wrote up a [fuller explanation and posted it to Hive](https://peakd.com/leofinance/@brianoflondon/here-s-why-archive-today-isn-t-working-in-brave-right-now). 

> "real money is being moved around"

I never withdrew those tokens and unlikely will do that (the required identity verification procedure is insecure and complicated and does not worth those "money").

The idea to verify the domains in the control panel were to opt-out them from Brave program, because people are fooled into thinking that Brave tokens is a legit form one can send donations, putting them in a row with LiberaPay and PayPal.

https://blog.archive.today/post/621541311410995200/like-while-i-understand-there-is-an-issue-i-had

**Comment by brianoflondon** [comment]
> I never withdrew those tokens and unlikely will do that (the required identity verification procedure is insecure and complicated and does not worth those "money").
> 

That is of course up to you but I'm quite happy moving BAT around and have converted most I have earned (not huge sums) into either Bitcoin or Hive.

I'm so lad to see you've opened up Brave because I must tell you I'm in the middle of preparing an enormous law suit and your site is one I adore for saving and capturing documents. I'm so grateful to you for the service!

**Comment by conferno** [comment]
> That is of course up to you but I'm quite happy moving BAT around and have converted most I have earned (not huge sums) into either Bitcoin or Hive.

Withdrawal (even re-donation to another website) requires a risky step of sending biometric data to a shady crypto-exchange, which is a strange complement to privacy-centric ecosystem Brave tries to build. So I do not consider BAT as money or even Bitcoin.

**Comment by brianddk** [comment]
You can still access it in brave from the "Tor Private Tab"

* v2: `archivecaslytosk.onion`
* v3: `archiveiya74codqgiixo33q62qlrqtk​gmcitqx5u2oeqnmn5bpcbiyd.onion`

**Comment by corymcdonald** [comment]
Closing this issue because the fix was merged and released yesterday - https://github.com/brave-intl/publishers/pull/2785

**Comment by volth** [comment]
Follow up:
I transferred the domains to an account of my friend who had Uphold account, and the transfer has passed.
But when it is payment time (8 Aug), that account has been banned no tokens has been paid.
The explanation of Brave employee was: that account has email in `.ru` and that why we have right not to pay.
So, I will block access to my sites for Brave again and encourage all the webmasters to do so (especially those who are already in countries Brave has discriminated: currently it is China, Vietnam, Russia, Ukraine and Indonesia), just not to support this scamy project which even use nationalist discrimination to make money.

**Comment by sysfu** [comment]
Running Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit) on Elementary OS elementary OS 5.1.7 Hera and just ran into this problem today. Thought it wsa

**Comment by hollons** [comment]
These domains have been moved to the new owner. 

The new owner had been suspended incorrectly due a bug in our code. They have been un-suspended and paid out in full. Closing this issue as all topics are now resolved.

**Comment by a-fruity-melon** [comment]
Was blocked again today.

Solution for innocent Brave users:

1. Download Tampermoney from Google Extensions Store
2. Create a new userscript
3. Delete all texts & codes inside the big text box
4. Paste this:

```js
// ==UserScript==
// @name         Hide Brave fingerprints from websites
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Hide Brave fingerprints from websites
// @author       You
// @match        *://*/*
// @run-at       document-start
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    Object.defineProperty(navigator, "brave", { value: 0 });
    (document.head || document.documentElement).insertAdjacentHTML('beforeend',
    '<script>Object.defineProperty(navigator, "brave", { value: 0 });</script>');
})();
```

5. Save by pressing Ctrl-S (or Cmd-S on Macbook), and close Tampermonkey's dashboard page
6. Download `Edit this cookie` to clear all your cookies from archive.* sites ( **yes, the site uses cookies to track you, without asking for your agreement, though it's owner shouts loudly for privacy** )
7. Try visiting arhive.* websites. If not working, repeat Step 6 and then clean all your caches from archive.* in the `History` page of Brave.

---

__To archive.* site owner:__ You have banned Brave before. The first time you are trying to get Brave developers' attention, and truly they did things wrong, so I said nothing. But this (08/31/2020) is the second time, and this time you ban Brave users without any reason. Hence, I'm posting this to provide a workaround.

I know you can add codes to detect `navigator.brave === 0`, and I know you know that I can add more codes to avoid being detected by you (i.e. changing `0` to `undefined`). You may also detect this workaround by `Object.getOwnPropertyDescriptor`, but I can also hook this function. I may also delete my inserted script tag to hide from detection. If you managed to come up with some tricky ways to prevent that, Idk, I can always inject a script to modify your script, and remove that part, unless you perform the test 100% on your server. Sadly, Brave has no significant `User-Agent` so that won't be possible. Even if you (again) find a method, I can still modify my `User-Agent` with browser extensions like `ModHeader`.

So just don't make useless attempts to block this workaround. It's useless.

And ask for user's agreement the next time you want to save cookies in browsers, or EU guys may sue you.

Hope you have a good day. :-)

**Comment by eldarmark** [comment]
But he has a reason.  They apparently stole donations that people sent him, by refusing to pay out once they discovered he was Russian.

**Comment by y4my4my4m** [comment]
@eldarmark yup, 

@a-fruity-melon 
> But this (08/31/2020) is the second time, and this time you ban Brave users without any reason. Hence, I'm posting this to provide a workaround.

It's the same reason, they are stealing donations.
