### ISSUE TITLE
Fingerprinting 2.0: WebGL getParameter handling

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#10214]
This is a sub-issue of the larger fingerprint defense reorganization issue: #8787`

### Debugging Endpoint
Calling `WebGLRenderingContext.getExtension('WEBGL_debug_renderer_info')` returns a [WEBGL_debug_renderer_info](https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_debug_renderer_info) object.  This return value should be treated separately from the above uses of `getExtension` and `getParameter`.

**default protection**: no changes
**max protection**: for each value (`UNMASKED_VENDOR_WEBGL` and `UNMASKED_RENDERER_WEBGL`) return 8 characters [0-9a-zA-Z], randomly determined from eTLD+1 seed

**Comment by pes10k** [comment]
I've added this to the QA pages, noted it as 1.12, and only aggressive mode ("agg")

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Visited https://dev-pages.brave.software/farbling.html and https://dev-pages.bravesoftware.com/farbling.html to run the Fingerprint Values tests on the Farbling pages.

<details>
<summary>Fingerprinting blocked set to Standard</summary>

* Confirmed `WebGL Vendor and Render` is the same on both pages with Standard setting
* Confirmed other FP values behaved as expected
<img width="1288" alt="10214 - Standard" src="https://user-images.githubusercontent.com/28145373/87821005-17700900-c83d-11ea-9a31-49a9d21e274b.png">

</details>

<details>
<summary>Fingerprinting blocked set to Strict</summary>

* Confirmed `WebGL Vendor and Render` is the different on both pages with Strict setting
* Confirmed other FP values behaved as expected except for `WebGL Drawing`, observed already logged issue for this - https://github.com/brave/brave-browser/issues/10675
<img width="1277" alt="10214 - Strict" src="https://user-images.githubusercontent.com/28145373/87820997-13dc8200-c83d-11ea-85d0-de61c1f9762a.png">

</details>

<details>
<summary>Shields down</summary>

* Confirmed `WebGL Vendor and Render` is the same on both pages with shields down
* Confirmed other FP values behaved as expected
* Confirmed closing the browser, relaunching and generating FPs again produced the same ones as previous session since shields are down
<img width="1282" alt="10214 - shields down 1" src="https://user-images.githubusercontent.com/28145373/87820991-1048fb00-c83d-11ea-8341-5e26c07d6f8f.png">

</details>

---------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.111 x64 build

<details>
<summary>Fingerprint set to `Block cross-site fingerprint` (default)</summary>

- Verified `WebGL Vendor` and `Render` is the same on both pages with Standard setting
- Verified other FP values behaved as expected

 https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html 
-- | --
![image](https://user-images.githubusercontent.com/17010094/89868149-3e0a3100-dbaa-11ea-8154-c07e29395b2b.png) | ![image](https://user-images.githubusercontent.com/17010094/89868186-4d897a00-dbaa-11ea-966e-0173ed0e6864.png)

</details>


<details>
<summary>Fingerprint set to `Block all fingerprint`</summary>

- Verified `WebGL Vendor and Render` is different on both pages when setting is set to block all
- Verified other FP values behaved as expected

 https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html 
-- | --
![image](https://user-images.githubusercontent.com/17010094/89868459-bf61c380-dbaa-11ea-8ad7-d51f7928c40c.png) | ![image](https://user-images.githubusercontent.com/17010094/89868245-64c86780-dbaa-11ea-80c3-dcfc9e6e6eba.png)

</details>

<details>
<summary>Shields Off</summary>

- Verified `WebGL Vendor and Render` is the same on both pages with shields down
- Verified other FP values behaved as expected
- Verified closing the browser, relaunching and generating FPs again produced the same values as the previous session since shields are down

 https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html 
-- | --
![image](https://user-images.githubusercontent.com/17010094/89868759-3e56fc00-dbab-11ea-9d72-72cc98839ee8.png) | ![image](https://user-images.githubusercontent.com/17010094/89868721-3008e000-dbab-11ea-920b-1fffd63412b6.png)
</details>

--------------------------

Verification passed on Samsung Tab A with Android 10 running 1.12.111 x64 build

<details>
<summary>Fingerprint set to `Block cross-site fingerprint` (default)</summary>

- Verified `WebGL Vendor` and `Render` is the same on both pages with Standard setting
- Verified other FP values behaved as expected

 https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html 
-- | --
![image](https://user-images.githubusercontent.com/17010094/89869088-c4734280-dbab-11ea-9d61-69118ea60f12.png) | ![image](https://user-images.githubusercontent.com/17010094/89869242-fd131c00-dbab-11ea-8210-04ec0ef0ee5c.png)


</details>


<details>
<summary>Fingerprint set to `Block all fingerprint`</summary>

- Verified `WebGL Vendor and Render` is different on both pages when setting is set to block all
- Verified other FP values behaved as expected

 https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html 
-- | --
![image](https://user-images.githubusercontent.com/17010094/89869594-7b6fbe00-dbac-11ea-85e8-45825cf79c2d.png) | ![image](https://user-images.githubusercontent.com/17010094/89869606-80347200-dbac-11ea-883e-ef134ddd165c.png)


</details>

<details>
<summary>Shields Off</summary>

- Verified `WebGL Vendor and Render` is the same on both pages with shields down
- Verified other FP values behaved as expected
- Verified closing the browser, relaunching and generating FPs again produced the same values as the previous session since shields are down

 https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html 
-- | --
![image](https://user-images.githubusercontent.com/17010094/89869225-f684a480-dbab-11ea-80db-990f5d8e983f.png) | ![image](https://user-images.githubusercontent.com/17010094/89869283-0c926500-dbac-11ea-9b8c-8fca40e923d0.png)
