### ISSUE TITLE
Add "warning/confirmation" dialog when closing a window w/ multiple tabs

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#10430]
## Description 

Several users have requested the option to confirm whether or not they want to close a window when multiple tabs are open in it. This functionality would be similar to what is already implemented in other browsers like Firefox and IE:

![image](https://user-images.githubusercontent.com/3299098/85439869-5498f200-b542-11ea-842b-134ac2a584da.png)

This functionality would prevent users from inadvertently closing a browser window. Also note that this functionality exists when attempting to _Quit_ the application process and even has an option to opt out of the `Press to hold` function:

![image](https://user-images.githubusercontent.com/3299098/85440160-9f1a6e80-b542-11ea-947f-f94d18bab487.png)

## Designs

Add the preference to warn when closing multiple tabs to the `Help tips` section in `brave://settings`. This is off by default.

![image](https://user-images.githubusercontent.com/2388823/123868638-cee21c00-d8e4-11eb-8240-366580c3c657.png)

Move `Show warning before quitting with ⌘Q` out of the Appearance section and to the Help Tips section too.

When toggled on, show a warning dialog when the user when closing multiple tabs.

![image](https://user-images.githubusercontent.com/2388823/123867704-86762e80-d8e3-11eb-91ac-f470ce5200bd.png)

## Assets
Figma: https://www.figma.com/file/pVwKlNQJU9wTVOa9tImKpo/?node-id=318%3A9788

## Miscellaneous Information:

Several users responding to this feature request -- will add additional request threads as I find them:
https://community.brave.com/t/five-years-and-no-progress-warn-before-closing-multiple-tabs/86525/7

**Comment by jonathanurias96** [comment]
I would like to work in this issue

**Comment by srirambv** [comment]
Windows/Linux specific request as this is already available in macOS

**Comment by AmbrocioIsaias2808** [comment]
I think it would be a good feature, sometimes i have to many tabs opened in two or more windows and closing one of them by accident is not very chirfull because i lost the tabs. I know now there is an option to restore them from history, but previous 9 days ago i didn´t know about it and like me there are lots. And well other browsers have this feature like opera, ¿why not brave?, i mean, it´s simple and not intrusive.

![opera](https://user-images.githubusercontent.com/44043979/86392743-91ab6580-bc61-11ea-9102-27efcffd98ed.png)

**Comment by joemamabuckeye** [comment]
I totally agree, this simple confirmation or warn dialog aka beforeunload event (like in a web page) is critical for the browser window that has multiple open tabs.  I do a TON of research and go between 3 brave windows, having 10 or more tabs open on each... accidentally closing one of the browser windows instead of a tab is a real PITA. I cannot just go back to the history because some of the pages hadn't been visited recently enough...and 'recently closed' won't restore because you closed the entire window.  I also use extensions like Flowbar, but I want some tabs open to jump back to in a second, not try to find the right bookmark and load the page, and my reference info. Saving everything to PDF isn't always feasible either.
I left FF because the multiple open tabs dragged my processor, but this is making me think about looking for another browser.  Hoping for a solution!!!

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/warning-to-close-if-multiple-tabs-open/167327

**Comment by ksalhab89** [comment]
+1

**Comment by 9codes** [comment]
+1

**Comment by 9codes** [comment]
Today I lost all of my working tabs just for not being this feature. As the progress was not saved, I lost all the hard work and time. Developers should add this feature in a short time. Maybe it's a minor change for them but it's a major for me. Thanks.

**Comment by bsclifton** [comment]
@9codes it might be a bit late, but you can use a shortcut Ctrl + Shift + T (on macOS: Cmd + Shift + T) to restore your last closed tab / window. You can use this multiple times and you should be able to restore it. This works in Chromium and other browsers too

**Comment by 9codes** [comment]
@bsclifton Thanks for your response Brian. I will wait (for the feature).

**Comment by murad-alm** [comment]
@brave Is there any chance we will get this simple feature anytime soon?
I really don't want to sound rude, but its literally one line of code...
`if opened_tabs > 1: 
    show_confirmation_dialog()
else:
    exit()`

**Comment by pes10k** [comment]
I believe this is already here (inherited from upstream / Chromium). Does this do what you're asking for?
`brave://settings/?search=Show+warning+before+quitting`?

It isn't specific to the "more than one tab" case, but it seems to solve the "whoops i didn't mean close and loose my stuff" problem.

If that doesn't capture whats needed, can you kindly share a bit more about whats further needed?  Thanks!

**Comment by murad-alm** [comment]
> I believe this is already here (inherited from upstream / Chromium). Does this do what you're asking for?
> `brave://settings/?search=Show+warning+before+quitting`?
> 
> It isn't specific to the "more than one tab" case, but it seems to solve the "whoops i didn't mean close and loose my stuff" problem.
> 
> If that doesn't capture whats needed, can you kindly share a bit more about whats further needed? Thanks!

Dear @pes10k, 
I can't find this option (Version 1.20.110 ) anywhere in the settings. 
This functionality should (as described by @Brave-Matt) warn the user before closing the browser whenever more than one tab are open (please check the issue description).
Thanks!

**Comment by pes10k** [comment]
Just to make sure we're on the same page, you don't see the below in your settings?

<img width="718" alt="Screen Shot 2021-02-24 at 4 38 47 PM" src="https://user-images.githubusercontent.com/76526/109075462-c66f9f80-76be-11eb-88d0-b375169eed6c.png">

**Comment by murad-alm** [comment]
> Just to make sure we're on the same page, you don't see the below in your settings?
> 
> <img alt="Screen Shot 2021-02-24 at 4 38 47 PM" width="718" src="https://user-images.githubusercontent.com/76526/109075462-c66f9f80-76be-11eb-88d0-b375169eed6c.png">

I believe this option is only available for macOS (as described by @srirambv ). Linux / Windows users DO NOT have this option.

**Comment by bridiver** [comment]
@murad-alm if you can write this feature in one line of code I would be happy to review the PR

> @brave Is there any chance we will get this simple feature anytime soon?
> I really don't want to sound rude, but its literally one line of code...
> `if opened_tabs > 1: show_confirmation_dialog() else: exit()`

**Comment by murad-alm** [comment]
> @murad-alm if you can write this feature in one line of code I would be happy to review the PR
> 
> > @brave Is there any chance we will get this simple feature anytime soon?
> > I really don't want to sound rude, but its literally one line of code...
> > `if opened_tabs > 1: show_confirmation_dialog() else: exit()`

I apologize if my bad joke offended you. Have a nice day @bridiver !

**Comment by bridiver** [comment]
> > @murad-alm if you can write this feature in one line of code I would be happy to review the PR
> 
> > 
> 
> > > @brave Is there any chance we will get this simple feature anytime soon?
> 
> > > I really don't want to sound rude, but its literally one line of code...
> 
> > > `if opened_tabs > 1: show_confirmation_dialog() else: exit()`
> 
> 
> 
> I apologize if my bad joke offended you. Have a nice day @bridiver !

@murad-alm we get some very interesting responses sometimes so it's not always easy to pick out the jokes ;)

**Comment by zcraber** [comment]
+1 This is a much-needed feature for me.

**Comment by JakubBarta** [comment]
+1 please implement this feature

**Comment by Abelius1** [comment]
You weren't enough time at home since the second wave...?

Fine. Uninstalling.

**Comment by quarterpastsix** [comment]
+1

**Comment by modzahid** [comment]
+1

**Comment by n1n1n3sh4rk** [comment]
today I had more than 10 tabs open in my Brave browser, and in one of them I was typing. in the conclusion somehow stupidly, I closed the browser and lost everything I had typed for 5 hours. similar was already with me in Chrome, so I switched to FF. But I really liked the privacy of Brave, so I urge developers to upgrade their browser to Linux as soon as possible and add the "Show confirmation dialog when closing" option. thank you.

**Comment by relaxedguy** [comment]
+1

**Comment by groslyunderpaid** [comment]
I would literally pay for this change.

**Comment by snowbound** [comment]
I accidentally clicked on the X in Brave today rather than the hamburger menu item and the browser closed down. MS Edge has this option yet Brave still does not. I have lost count of how many times I have closed Brave by accident and had to login to my sites again.

**Comment by jeevanism** [comment]
joining to the queue for this feature. Just closed 11 tabs related to my work accidentally :(

**Comment by UntriexTv** [comment]
Same here. I am often working with two windows because of online school. I ALWAYS accidentally close my primary window first, so i am left only with school tabs. I know i can use menu -> history and revive session, but it would be more easy for me to just get notification, if i tried to close one of the windows.

**Comment by CBMVic20** [comment]
Wondering why this can't be added as other Chromium based browsers like Edge, Firefox, Opera and Vivaldi all have a confirm on exit option. I always have at least three browser sessions open for work, personal and chat / email,  each with several active tabs. Have to clear everything including history on close for work security policy so it's a real pain when I accidently exit Brave and lose everything.

Confirm on exit is the one feature that makes me stick with Edge and Firefox, even though Brave is a much better browser. Surely it can't be that hard to do if several other Chromium based browsers already have the feature?

**Comment by snowbound** [comment]
@CBMVic20 You can for MS Edge get this warning per https://www.onmsft.com/news/microsoft-edge-canary-can-now-warn-users-before-closing-multiple-tabs#:~:text=Navigate%20to%20the%20three%20dots,before%20Closing%20multiple%20tabs%E2%80%9D%20option.


There is no such flag in Brave

**Comment by CBMVic20** [comment]
Thanks @**Snowbound**, yes I have enabled this already for Edge hence my comment. Currently having to use Edge as my main browser because Brave doesn't have this. Firefox, Opera and Vivaldi all have this without any flags.

**Comment by snowbound** [comment]
@CBMVic20 I definitely feel your pain/frustration. Edge etc do some things better than Brave does due to bugs/issues.

**Comment by groslyunderpaid** [comment]
Someone should be embarrassed

**Comment by yacn** [comment]
> Windows/Linux specific request as this is already available in macOS

This is not available in macOS; "Warn before quit" is not what the request is for. "Warn before quit" does not warn if you have multiple windows open and close a window with multiple tabs, which is what the request is for and what Firefox and many other browsers do.

**Comment by rebron** [comment]
Flag edge://flags/#edge-ask-before-closing-multiple-tabs and setting in Edge for inspiration
![Screen Shot 2021-05-25 at 10 13 13 AM](https://user-images.githubusercontent.com/5951041/119540099-de989e80-bd41-11eb-889c-3dadd1c15c0a.png)

**Comment by karenkliu** [comment]
Designs added!

**Comment by groslyunderpaid** [comment]
What does this mean? Option to be available in next release?

**Comment by rebron** [comment]
@groslyunderpaid We've finalized designs and the next part is getting built. Once we're done with the feature, we'll label the milestone that it's in and that will be the version where you'll see it.

**Comment by NuLL3rr0r** [comment]
Linux (home) and Windows (work) user here, also eagerly waiting for this feature to land in Brave. Keep up the good work!

**Comment by ctrl8511** [comment]
excuse me/us 
why this basic feature wasn't available from the first browser release? to prevent any accidental close
also chromium (and then chrome), why they also didn't just add this feature, simply unbelievable..
I still can't use another browser than firefox (and opera) because of this...

**Comment by snowbound** [comment]
@ctrl8511 Actually MS Edge even has this capability via my post here back in May. Growing tired of limitations.

**Comment by simonhong** [comment]
Working on this.
We should hook `Browser::ShouldCloseWindow()` for adding warning dialog.

**Comment by wesam20201** [comment]
This feature still not added guys?

**Comment by kavlito** [comment]
I believe this is built-in to Chromium. Brave must have made a conscious decision to remove it. Please 'uncomment' that line of code. Thank you.

**Comment by groslyunderpaid** [comment]
It's pretty wild that such a basic feature has been on the docket so long.
Disappointing.

**Comment by wesam20201** [comment]
> I really would love to see this feature. I'm not a coder, so easy for me to say, "It would be easy." Maybe not. I don't know. But, I know that sometimes I accidently click "X" by accident. (Sometimes it's my stupid mouse goes beserk and moves there just as I'm clicking.) Yes, tabs re-open when I go back into Brave, but often the video I was watching does not 'know' where I was at in it, and I have to guess. That sort of thing. ARgh!

If you're watching videos on certain website, you can enable cookies on that website so that it remembers where the video was when it reopens, a temporary solution until the feature is added, hopefully.

**Comment by murad-alm** [comment]
Been waiting for 2 years now xD
I just don't think its gonna get added anymore tbh :(

**Comment by snowbound** [comment]
I have given up reporting issues with Brave here and or on their Brave Community. Web 3.0 development seems to have taken over.

**Comment by valsu** [comment]
You would think adding this would be a no-brainer...

**Comment by simonhong** [comment]
This warning dialog should be launched only by window closing request and not by application quit request.

**Comment by simonhong** [comment]
@rebron @rmcfadden3 I feel that current sentence in the above closing dialog seems quite long.
Ex, below is other browser's closing confirm dialog. WDYT?
<img width="327" alt="Screen Shot 2022-04-13 at 5 27 56 PM" src="https://user-images.githubusercontent.com/6786187/163135202-723f13a1-e274-4ca7-8c00-1de9824dd39b.png">
<img width="384" alt="Screen Shot 2022-04-13 at 5 32 36 PM" src="https://user-images.githubusercontent.com/6786187/163135234-c1d87d97-de47-4cc3-8d48-59532ca4a412.png">

**Comment by rmcfadden3** [comment]
@simonhong & @rebron — I could see reducing this body text to just "You have XX tabs open in this browser window."

So we could remove / delete "Closing the window will close these 11 tabs. Do you want to proceed?" Those 2 sentences are redundant.

**Comment by simonhong** [comment]
@rmcfadden3 Thanks for quick check! 👍🏼

**Comment by DutchPete** [comment]
> [General](https://github.com/brave/brave-browser/projects/9) automation moved this from In progress to Completed [3 days ago](https://github.com/brave/brave-browser/issues/10430#event-6536660955)

This is for Windows. What about Linux ???

**Comment by simonhong** [comment]
@DutchPete The fix for this issue (https://github.com/brave/brave-core/pull/13003) is for all platforms.

**Comment by DutchPete** [comment]
@MadhaviSeelam how about for Linux? Simon Hong mentioned on 16 May it would be done for Brave 1.40.

**Comment by MadhaviSeelam** [comment]
@DutchPete Linux will be tested as well in 1.40.x

**Comment by stephendonner** [comment]
Verified `PASSED` using 

<summary>Case 1: `Warn me before closing window with multiple tab` preference is added  in brave://settings/HelpTips and is `disabled`  as a default - PASSED</summary>

<details>

1. Install 1.40.x
2. Launch brave
3. Open brave://settings>>click Additional settings>>click Help tips
4. Verified `Warn me before closing window with multiple tab’ pref is available
5. The toggle is `OFF` by default

dark| light
---|---

</details>

<details>
<summary>Case 2: Basic Test- Show `Close all tabs` warning dialog upon closing multiple tabs, when the pref is `enabled` - PASSED </summary>

1. New profile
2. Launch brave
3. Create new window with multiple tabs
4. Leave the default selection for `Continue where you left off in brave://settings/getStarted`
5. Close the browser window ('x' or alt+f4)
8. Verified warning `Close all tabs` dialog is not launched since pref is `OFF` by default 
10. Enable `Warn me before closing window with multiple tabs` in Help tips section of brave://settings 
11. Close the browser window ('x' or alt+f4)
12. Verified `Close all tabs` dialog displayed with correct text
13. UI matched to figma
14. Click `Cancel` button
15. Warning dialog is dismissed
16. Close the browser window again ('x' or alt+f4)
17. Click `Close all` button in the Warning dialog
18.  Relaunch the browser
19.  All of the tabs are preserved

Step 3&4|Step 7|Step 9|Step 16
---|---|---|---

</details>

<details>
<summary>Case 3: Do not show `Close all tabs` warning dialog when the  pref is `disabled` again OR `Don’t ask me again` check box is checked - PASSED</summary>

1. Continue from Case 2 (Pref is enabled)
2. Open multiple tabs
3. Leave the default selection for `Continue where you left off in brave://settings/getStarted`
4. Disable `Warn me before closing window with multiple tabs` pref in Help tips section of  brave://settings 
5. Close the browser window
6. Verified `Close all tabs` dialog not displayed 
7. Relaunch the browser
8.  All of the tabs are preserved
9. Enable the pref in the Help tips section of  brave://settings 
10. Close the browser window
11. Check the check box for `Don’t ask me again` 
12. Click `Close all` button
13. Relaunch the browser
14. All tabs are preserved
15.  Navigate to Help tips section of brave://settings 
16. Verified `Warn me before closing window with multiple tabs` pref is disabled

Step2&3|Step4|Step11|Step14
---|---|---|---


</details>

<details>
<summary>Case 4: Test with `onbeforeunload` handler -PASSED</summary>

1. Launch Browser and set option is enabled
2. Create window and create more than one NTP tabs
3. Load https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onbeforeunload in one NTP and click `Click here to go to w3schools.com` and check `beforeunload` dialog is launched. Then, dismiss it.
4. Try to close window by clicking close button or window closing shortcut (alt + f4, or cmd+shift+w on macOS)
5. Select `Close all` and check `beforeunload` dialog is launched
6. Cancel `beforeunload` dialog
7.  Repeat step 4 and check window `Close all tabs` is shown again
8.  Select Close all and also Leave from `beforeunload` dialog and check window is closed

Step 1|Step2|Step3|Step4|Step5|Step7|Step8
---|---|---|---|---|---|---

</details>

<details>
<summary>Case 5: Test with download in-progress handler -PASSED</summary>

**Fresh Install**
1. Launch Browser and set option is enabled
2. Create window and create more than one NTP tabs
3. Load https://ubuntu.com/download/desktop/thank-you?version=22.04&architecture=amd64 and start download
   3a. Tested with Acrobat reader download https://get.adobe.com/reader/?promoid=TTGWL47M as this can be tested with any 
 download  
5. Try to close window by clicking close button or window closing shortcut (alt + f4, or cmd+shift+w on macOS)
6. Select Close all from window closing dialog and check Download in-progress warning dialog is launched
9. Select Continue downloading
10. Repeat step 4 and check window closing dialog is launched again
20. Select Close all from window closing dialog and select Exit from Download in-progress warning dialog
21. Check window is closed.

Ex1|Ex2|Ex3
---|---|---


</details>

<details>
<summary>Case 6: Test with onbeforeunload and download in-progress handler - PASSED</summary>
(Note: On macOS, download warning dialog is not shown on normal profile. Private window will have same behavior on macOS with other platform's normal window)

**Fresh Install**
1. Launch Browser and set option is enabled
2. Create window and create more than one NTP tabs
3. Load https://ubuntu.com/download/desktop/thank-you?version=22.04&architecture=amd64 and start download
4. Load https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onbeforeunload in one NTP and click Click here to go to w3schools.com and check beforeunload dialog is launched. Then, dismiss it.
5. Try to close window by clicking close button or window closing shortcut (alt + f4, or cmd+shift+w on macOS)
6. Check download warning or beforeunload dialog is launched one by one after selecting Close all from window closing dialog
7. Verified `beforeunload` dialog is launched after selecting `Close All` dialog

Ex1|Ex2|Ex3|Ex4|Ex5
---|---|---|---|---

</details>

<details>
<summary>Case 7:Test with reboot/restart - PASSED</summary

1. Launch Browser and set option is enabled
2. Create window and create more than one NTP tabs
3. Load `brave://restart` and check window closing dialog is not launched
4. Repeat step 1,2 and load `brave://quit`and check window closing dialog is not launched
5. Verified `Close all` warning dialog is not launched for both `restart` and `quit`

Ex1|Ex2|Ex3
---|---|---


</details>

<details>
<summary>Case 8: Test with update - PASSED</summary>

1. Launch Browser and set option is enabled
2. Create window and more than one tab
3. Load brave://settings/help and waiting relaunch is ready after downloading new update
4. Click relaunch button and check window closing dialog is not launched
5. Verified `Close all` warning dialog is not launched upon update

Step1|Step3|Update
---|---|---


</details>

<details>
<summary>Case 9: Test with profile deletion -PASSED</summary>

1. Launch Browser and set option is enabled
2. Create window with more than one tabs
3. Delete active profile and check window closing confirm dialog is not launched.
4. Verified `Close all` warning dialog is not launched

Ex1|Ex2|Ex3
---|---|--

</details>

<details>
<summary>Case 10: Windows/Linux specific test - PASSED</summary>

1. Launch Browser and set option is enabled
2. Create window and create more than one NTP tabs
3. Repeat step 2 to recreate another window with multiple tabs
4. Do closing all windows from app icon's context menu at Dock(linux) or at Taskbar(Windows)
5. Check each Windows' closing is done separately like above 
6. Verified `Close all` warning dialog is launched for both windows

window1|window2
---|---

</details>

<details>
<summary>Additional scenarios </summary>

- Verified the  `Close all tabs` warning dialog works as expected with `Open the New Tab Page` selection in brave://settings/getStarted
- Verified the `Close all tabs` warning dialog works as expected with `Open a specific page or set of pages` selection in brave://settings/getStarted
- Verified `Close all tabs` warning dialog works as expected with TOR window
- Verified `Close all tabs` warning dialog works as expected with Private window

</details>

Test Case II Upgrade: 
<details>
<summary>Upgrade Test - PASSED</summary

1. Install 1.39.x
2. Create window with than one tab
3. Help tips section in brave://settings do not have `Warn me before closing window with multiple tabs` pref
4. Load brave://settings/help and wait for updates to complete
5. Click to Relaunch the browser
6. Verified `Warn me before closing window with multiple tabs` pref is available and set to `OFF` as a default

Ex1|Ex2|Ex3|Ex4
---|---|---|---

</details>
