### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Nappiie** [brave/brave-browser#10467]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.10.97  Chromium: 83.0.4103.116
Operating System: Mac OS X 10.15.5

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. launch brave browser
2. browsing sites for 1 minute
3. it suddenly crashes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/77b20000-1c55-8704-0000-000000000000

**Comment by bsclifton** [comment]
Thanks for the report @Nappiie - looks like this crash was due to sync being enabled

Can you please visit brave://flags/#brave-sync and disable? This should fix the problem for you

We have a v2 of sync coming which is already live in 1.12.x (Nightly). Thanks for your patience and thanks for reporting 😄
