### ISSUE TITLE
[Desktop] Add brave extension hook to get data synchronously from brave-core

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#10495]
There are several cases where extensions need data from the main chunks of brave-core synchronously to work correctly.  The motivating example here is scriptlet injections in adblock rust.  The extension here needs to be able to inject code into the page before the page loads.  The extension API describes this as [document_start](https://developer.chrome.com/extensions/tabs#method-executeScript).

Currently there are only async ways for brave extensions to request "backend" data, which opens up race conditions.  In some cases page content will load in the window between `document_start` (when the extension made the request to the backend for scriptlet / cosmetic filtering data) and when the content script gets to act on it.  In some of these cases, whatever was supposed to be modified by the scriptlet injection will have finished running, and it'll be too late.

This is related to what caused YouTube ads to start reappearing recently.  Its also the only (known) significant place where Brave lags behind uBO.

**Comment by petemill** [comment]
Sounds like there's 2 things to do. Right now what happens is this:

- content_script loads and sends 'contentScriptsLoaded' message to background script
  -  background script handles message and schedules some redux action
      - sometime later (or possibly immediately), the redux reducer processes the action
      - redux reducer in the background script calls `chrome.braveShields.urlCosmeticResources` (nit: should be prefixed `get...`.
          - On that callback, reducer then calls content_script with the data requested via chrome.tabs.sendMessage(tabId, 'cosmeticFilterConsiderNewSelectors'...)`
              - content_script handles that event and then injects `<script>` element.

The two things to do are:
1. Remove redux spaghetti code (which splits this all up in to about 5 different JS files) and also has potential for action queueing, delaying even further.
2. _Push_ the data to the content script, or pre-fetch the data when the page starts loading.

So what it should ideally change to:

1. Background script listens to `chrome.tabs.onUpdated({ status: 'loading'})`
   - Immediately calls `chrome.braveShields.urlCosmeticResources`
      - in that callback,  sends the result to the content script via `chrome.tabs.sendMessage(tabId,...)`.
      - _or_ if the content script doesn't exist, saves that data for when it does

I'm not sure making calls from the background script to `chrome.braveShields` sync instead of async will change anything, unless the background script has thousands of JS tasks in the queue, delaying when the callback will be handled. Especially since it's a separate process to the page and content script.

**Comment by simonhong** [comment]
@pes10k, I tried to use `chrome.webNavigation.onBeforeNavigate` instead of `chrome.tabs.onUpdated` to call `chrome.braveShields.urlCosmeticResources` as early as possible.(`chrome.webNavigation.onBeforeNavigate` is called more earlier than `chrome.tabs.onUpdated`).
It seems work and I found your below comments :)
```
// Notify the background script as soon as the content script has loaded.
// chrome.tabs.insertCSS may sometimes fail to inject CSS in a newly navigated
// page when using the chrome.webNavigation API.
// See: https://bugs.chromium.org/p/chromium/issues/detail?id=331654#c15
// The RenderView should always be ready when the content script begins, so
// this message is used to trigger CSS insertion instead.
```

**Comment by pes10k** [comment]
@simonhong I'm not sure I can take credit for those words (or that i even know/remember where they're from!), but if they helped, I'm glad they did :)
