### ISSUE TITLE
Implement 1st party storage isolation

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#1053]
Carried over from https://github.com/brave/browser-laptop/issues/3826

> https://twitter.com/rlbarnes/status/773895944031076352, AKA > https://www.torproject.org/projects/torbrowser/design/#identifier-linkability

**Comment by da2x** [comment]
FPI in Firefox also isolates the DNS cache and connections (which became even [more relevant recently](https://www.theregister.co.uk/2018/10/19/tls_handshake_privacy/)).

**Comment by siric1** [comment]
First Party Isolation and Containers would be great additions to the browser.

**Comment by loyl1** [comment]
I'm not sure what this means. Was FPI dropped?

**Comment by ahake** [comment]
any progress on this?

**Comment by diracdeltas** [comment]
@riastradh-brave could you post an update here and answer the q's above? thanks

**Comment by MagsMagnoli** [comment]
- [Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers)
- [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers)

These two extensions for Firefox are preventing me from using Brave as my primary browser. Would love to see something like this implemented!

**Comment by ParaplegicRacehorse** [comment]
Bump. Without some sort of isolation mechanism, especially for cookies and js, Brave will never become my primary browser even though I very like [almost] everything else about it. Private window, blah blah, I want the containerization linked to by @MagsMagnoli, above, or something substantially similar.

**Comment by x7a** [comment]
any progress? it's the only feature that i really miss in brave

**Comment by 12people** [comment]
Firefox now has first-party cookie isolation built in as well, as detailed in Mozilla's recent [blogpost on the feature](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/).

Would love to see something like this in Brave.

**Comment by robinhood018** [comment]
Any update on this?

**Comment by iefremov** [comment]
@robinhood018 The work happens around https://github.com/brave/brave-browser/issues/15906 and https://github.com/brave/brave-browser/issues/19099

@pes10k should we close this issue in favor of 1PES-related ones?

**Comment by pes10k** [comment]
@iefremov i think that sounds great, though can we link to the issue for "expose 1PES as a cookie option in shields" too?

**Comment by iefremov** [comment]
@pes10k I can't find that one, can you please post the link?

Closing for now

**Comment by robinhood018** [comment]
Will this feature be also added to the official release?

**Comment by pes10k** [comment]
@robinhood018 It depends on what you're looking for.  Folks in the issue seem to be discussing different things.

If you're looking for something similar to Firefox's first-party cookie isolation / Total Cookie Protection, Brave has already shipped something like this (but more protective, because Brave lifetimes 3p storage much much shorter than Firefox) since 2021 [1].

If you're looking for something like a "automatically generated, automatically forgetting, automatically stretching temporary storage area", no browser has something like that (though some browsers have a subset of it).  Brave is working on it, and has shipped several incremental steps (see [2] and [3] for some intermediate steps) and hopes to have the final, total solution shipped soon


1: https://brave.com/privacy-updates/14-partitioning-network-state/
2: https://brave.com/privacy-updates/7-ephemeral-storage/
3: https://brave.com/privacy-updates/16-unlinkable-bouncing/

**Comment by robinhood018** [comment]
The only thing I'm looking for is Compartmentalization, just like Firefox has those specific containers for specific links.
