### ISSUE TITLE
Feature request: show bookmarks in a sidebar

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1063]
Carrying over from: https://github.com/brave/browser-laptop/issues/5208

Display bookmarks in a sidebar, similar to Firefox/Safari.

**Comment by rossmoody** [comment]
I think it might help to redefine the scope of what introducing a sidebar component into our layout means for this one. Both Firefox and Safari have sidebars but they provide a lot more value than just a bookmark manager. They seem to also house Reading Lists, Favorites, History, Synced Tabs, etc... 

We also will likely soon have the ability to leverage an [extension like this ](https://chrome.google.com/webstore/detail/bookmark-sidebar/jdbnofccmhefkmjbkkdkfiicjkgofkdh/related?hl=en) which would fulfill this request so if this one is worth pursuing we might need to give more thought to defining a sidebar component for Brave and incorporate bookmark functionality into it.

**Comment by JaneSmith** [comment]
I'd just like to say that this is one of the few major blockers I have preventing me from using Brave instead of Firefox. A horizontal tab bar just doesn't cut it for people with more than a few tabs open - and browsers also tend to suffer performance issues with large numbers of tabs - so my workflow in Firefox is to keep my bookmarks sidebar open at all times and use it as a makeshift vertical tabs bar. I "suspend" tabs by bookmarking them to my sidebar, and the vertical layout makes it very easy for me to navigate.

Brave doesn't offer this, so I'm stuck using horizontal tabs or a separate bookmarks window. It just doesn't work well for me. I also don't want to use a third-party extension, written by some random guy, as it won't work as reliably as a built-in feature, and is yet another source of code I have to audit and decide whether to trust.

I'd very much appreciate it if a sidebar feature could be implemented in Brave. Other Chromium-based browsers like Vivaldi seem to have implemented this beautifully.

**Comment by djagoo** [comment]
Same here, the only thing preventing me from switching from Firefox to Brave is the missing sidebar.

**Comment by rcharif** [comment]
Agreed-- I've been exploring and appreciating Brave, almost ready to switch from Firefox, but not if I have to give up the convenience of being able to display and search many bookmarks without opening a whole new tab. Needless to say the bookmark sidebar display needs to have a search/filter feature as does FF.

**Comment by JOduMonT** [comment]
the sidebar in Firefox and Vivaldi is very useful and I miss it
while I could block ads in Firefox and Vivaldi, I can't add the sidebar in Brave and this really turn me off

I have the habit of using the sidebar for DeepL and BitWarden which save me a lot of time during my days

**Comment by brk114** [comment]
This is a work around from brave community in the meantime the feature releases.
[community workaround](https://community.brave.com/t/turn-on-vertical-tabs/207799/4)
This is how it look once do turn on that flag.
![image](https://user-images.githubusercontent.com/13432828/116804950-80144200-ab40-11eb-8bf7-9cec7e03c078.png)

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/brave-browser/issues/20500
