### ISSUE TITLE
[Desktop] All saved passwords are deleted! All logged-in sessions are logged-out! WTF?!

### ISSUE THREAD

**Issue by Martina-Neumayer** [brave/brave-browser#10672]
## Description 
Updated already the browser from 1.11.91-1 to 1.12.82-1 (beta channel from AUR) and all my saved passwords are deleted. 
Nothing left. Null, nada, zero, niente. 
All my logged-in sessions are also logged-out. Here the problem is that I can't log-in back on some websites anymore, for example Epic Games Store, GOG, Disqus.
And off course this blooody synchronization does not work. I don't have any of my desktop-used passwords on my phone.
If the sync is on browser crashes on start (force close), no errors info, no system logs entry, just fc.

When I downgrade to the previous version, all goes back to normal.

## Steps to Reproduce
Just update the browser

## Actual result:
Very, very, very pissed off Blonde, who instead of working, now has to fight with the "moron-done" browser.

## Expected result:
Normal update without any personal data deletion and such issues

## Brave version (brave://version info)
Version 1.12.82 Chromium: 84.0.4147.68 from AUR
System: Arch Linux

- Can you reproduce this issue with the beta channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No

- Does the issue resolve itself when disabling Brave Rewards?
No

- Is the issue reproducible on the latest version of Chrome? 
How should I know that?! I don't use Chrome.

**Comment by SpicBeanerMower** [comment]
1.11.91-1 = stable
1.12.82-1 = Beta
It is obvious you won't keep any settings because they are saved on different folders since they are different builds. if you go to %localappdata%\BraveSoftware in windows explorer you should have stable and beta folder there. The only way to get stuff from stable to other builds is to copy or move the User Data folder inside any build's folder to the other, in this case from Brave-Browser to Brave-Browser-Beta.
I don't know why you would want to use Beta build, unless you wanted to test the sync v2 which was released today. So you can keep using stable as well, since Brave schedule says next stable build should be released next Tuesday, which hopefully adds sync v2 and fixes all the issues I get with Cosmetic filtering which is the reason I don't use stable today.

But you didn't upgrade, you just installed a different build you were using so you don't get same settings or anything unless you create a Symbolic link/Junction and have the same folder for each build but that means you can't use 2 builds at the same time since they would share same folder.

**Comment by HarnischtheTrue** [comment]
i had to reinstall to have my accounts back

**Comment by bsclifton** [comment]
@Martina-Neumayer sorry for the long response time - I see the issue. It might be a problem with the folks packaging on Arch Linux (we don't support this officially; I believe folks are re-packaging the deb package)

[1.11.19](https://github.com/brave/brave-browser/releases/tag/v1.11.19) is Nightly channel
[1.12.82](https://github.com/brave/brave-browser/releases/tag/v1.12.82) is Beta channel

Beta and Nightly use different profile directories. Specifically:
`~/.config/Brave-Browser-Nightly`
and 
`~/.config/Brave-Browser-Beta`

You can rename your `Nightly` folder as Beta if you wanted to "move" channels. But I'd recommend staying with a particular release channel. If you're upgrading Nightly, the latest version is `1.13.10`

Let me know if you have more questions - and sorry again about the long response time. You definitely didn't lose any data - the channels store their data in different places (so that you can run them side-by-side if you want 😄)

**Comment by Martina-Neumayer** [comment]
@bsclifton Nope.. it is not a deb repack. The sources are taken directly from the brave git releases page.
As you can see in the PKGBuild files here:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=brave-beta-bin

I am not using nightly releases. I am always and only on beta versions.
There's a difference: 1.11.19 vs. 1.11.91 ;)

**Comment by bsclifton** [comment]
ah - you're right; my bad there 😄 [1.11.91](https://github.com/brave/brave-browser/releases/tag/v1.11.91)

Interesting that all channels on arch are using the same profile directory. For the supported Linux builds we do, it should be creating those. Can you try symlinking a folder? like
`ln -s ~/.config/BraveSoftware/Brave-Browser ~/.config/BraveSoftware/Brave-Browser-Beta`

**Comment by Martina-Neumayer** [comment]
@bsclifton Yes. In Arch the path is that same if you install the browser from aur repository.
I can symlinking, off course.. but for what purposes? As for me it can be stored as it is now. I do not mind the existing path.
This is not a problem.
The problem was deletion of the entire passwort database in the time of the upgrade.
I found that in the system logs. The db file was simply deleted and that's why I lost all my previously saved passwords.
Okay.. I upgraded today to newest beta version (1.12.86) and luckily almost everything works fine.
Yes, I have a full backup done now ;)
Almost because I can not log in to my account on Epic Store.
Except this one, everything is good.

**Comment by bsclifton** [comment]
Thanks for elaborating - I wasn't understanding what exactly was lost - it sounded like perhaps none of the data carried over. But it seems you were just having sessions/passwords not being carried over. Thanks for providing more information 😄 

Encrypted information (saved PWs, etc) can get into a state where it's not readable anymore. For example, if you reset your key (used for GNOME Keyring, I think) then the old ones are no longer readable. They'll appear to be deleted as it was encrypted with a key that no longer exists

**Comment by Martina-Neumayer** [comment]
@bsclifton Yeap.. but only if you are using gnome-keyring. I don't use it on my system.
One file got lost from the Brave default profile directory. Is called "Login Data" to be exact.
If this file is removed then you don't have your passwords anymore.
And none of the keyrings helps you with this problem.
Or you have a backup or you are sitting ducks.
There is also a third option.. some external password manager like KeePass which I started using now.

Okay..
How about the second part of the issue?
This strange log out from all loged in pages?

**Comment by bsclifton** [comment]
@Martina-Neumayer the logout from all pages would seem to be a Cookie issue. There are situations where cookies can be lost... For example, when you upgrade and the Cookies database (SQLite) adds a new field, etc it'll upgrade the `Default/Cookies` file in your profile. If you *downgrade* after that, it's possible Chromium doesn't know how to handle this and then cookies are lost. I'd have to test to verify this 100%

**Comment by Martina-Neumayer** [comment]
@bsclifton Ooouu yesss.. on this point I totally agree! Chromium and Chrome are very poorly designed in this (sqlite) topic.
Well, I'll just have to remember to do a bacup copy of my profile before each upgrade. Rsync + cron will do the job ;)

**Comment by bsclifton** [comment]
@Martina-Neumayer 1.12 also introduces a proper version of sync - and this can be used to backup some of your settings (such as saved passwords). You'd just have to track 24 BIP39 keywords and that can be used to restore on any profile that supports the new version of sync

**Comment by Martina-Neumayer** [comment]
@bsclifton Yes in theory should work, but sadly it does not. Sync kills my android Brave ootb if I tap on the synchronisation menu.
I can not set it up at all.

**Comment by bsclifton** [comment]
@Martina-Neumayer ah ok- that makes sense. Sync was broken until 1.12 - the crashes with Sync v1 got more aggressive with Chromium 83

With 1.12 and later (which is on Android Nightly and should be on Android Beta now) Sync v2 is implemented and should be fully featured. It'll be hitting stable ~August 4th; you can sync all the types (passwords, autofill data, bookmarks, extensions, etc) although I think there is a bug for syncing tabs between desktop and android at the moment. We're working to sort that out before the stable date 😄

**Comment by Martina-Neumayer** [comment]
@bsclifton Okay.. then I need to wait for the new android beta update. :)
