### ISSUE TITLE
Follow up of #10737 - purchaseIntentSignalHistory is empty for some sites

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#10771]
## Description 

Follow up of #10737
purchaseIntentSignalHistory is empty for some sites

## Steps to Reproduce

   1. Set OS locale to Japan
   2. Launch brave in staging env
   3. Enable rewards and open `https://fusafusaraifusutairu.blogspot.jp/` in a new tab
   4. Wait until page is loaded fully
   5. Open `client.json` and look for purchaseIntentSignalHistory
   6. purchaseIntentSignalHistory is empty 

## Actual result:

purchaseIntentSignalHistory is empty `"purchaseIntentSignalHistory": {},`

Sites for which purchase intent is empty
https://www.linkedin.com
https://www.angfa.jp/
https://fusafusaraifusutairu.blogspot.jp/

## Expected result:
purchaseIntentSignalHistory should not be empty

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc @brave/legacy_qa @moritzhaller @jsecretan @rebron

Reproduced by @btlechowski

**Comment by tmancey** [comment]
@GeetaSarvadnya could you please retest. Thanks

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.22.53 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Ubuntu 18.04 LTS

Verified test plan from description.

Verified purchase intent for `https://www.angfa.jp/`:
```
"purchaseIntentSignalHistory":{"ANGFA02":[{"timestamp_in_seconds":1615037356,"weight":1}]},"adsUUIDSeen":{"4983dc92-09fd-4e5c-94c3-616a4728c1d9":1}
```
It took a long time though, because the purchase intent is extracted when page is fully loaded (spinner stops spinning)

Failed to extract purchase intent for `https://fusafusaraifusutairu.blogspot.jp/`:
![image](https://user-images.githubusercontent.com/34715963/110208868-dd19b180-7e89-11eb-8648-6bca18aba2e4.png)
Logged as follow up: https://github.com/brave/brave-browser/issues/14528
