### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by oskar15** [brave/brave-browser#10803]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.11.97  Chromium: 84.0.4147.89
Operating System: Windows NT 10.0.18363

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/430c0000-5fc1-c604-0000-000000000000

**Comment by bsclifton** [comment]
@oskar15 thanks for the report! This is due to Sync being enabled. We'll be introducing a completely new version of sync in the next version of Brave (1.12), which is available on Beta. We're no longer supporting the original version - can you please disable it via brave://flags/#brave-sync

That should fix the crash for you - sorry for the inconvenience. When this new version of sync launches, it'll require you to setup the sync group again... BUT it'll have all sync types available for Desktop and Android. iOS is going with bookmarks first
