### ISSUE TITLE
[Desktop] Brave cannot be set as the default browser on Arch Linux

### ISSUE THREAD

**Issue by arch-btw** [brave/brave-browser#11032]
## Description 
~/.local/share/applications/mimeapps.list is depreciated, but brave still uses it.

## Steps to Reproduce

   1.  Install Brave on KDE
   2.  Open Brave

## Actual result:
Brave is not your default browser (when it is).

## Expected result:
Brave should be default browser.

## Reproduces how often: 
Always.

## Brave version (brave://version info)

Brave | 1.14.2 Chromium: 84.0.4147.105 (Official Build) unknown (64-bit)

## Version/Channel Information:
Nightly 

- Can you reproduce this issue with the current release? Not sure
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Don't know

## Miscellaneous Information:
Symlinking fixes this.
ln -s ~/.config/mimeapps.list ~/.local/share/applications/mimeapps.list
As according to:
https://wiki.archlinux.org/index.php/XDG_MIME_Applications#mimeapps.list

**Comment by rebron** [comment]
cc: @fmarier Can you take a look?

**Comment by fmarier** [comment]
It looks like this is coming from the [outdated version of xdg-mime that ships with Chromium](https://source.chromium.org/chromium/chromium/src/+/master:third_party/xdg-utils/scripts/xdg-mime;l=776;drc=55dfec5814ddb0f4f3f1cd67b673fc1325667a5a). For comparison, the [one that ships in Debian](https://salsa.debian.org/freedesktop-team/xdg-utils/-/blob/78376681edca4cb1197fc286212b0caaca1d8324/scripts/xdg-mime.in#L247) as part of the `xdg-utils` package uses `.config/mimeapps.list`.

In the official packages, that's not an issue because there is a dependency on the system `xdg-utils` package both in the [`.deb`](https://source.chromium.org/chromium/chromium/src/+/master:chrome/installer/linux/debian/additional_deps;l=21;drc=b084040bfe45a33c827090b40a3f1ee28d640b62) and the [`.rpm`](https://source.chromium.org/chromium/chromium/src/+/master:chrome/installer/linux/rpm/additional_deps;l=32;drc=b084040bfe45a33c827090b40a3f1ee28d640b62). I don't see that in the [Arch `brave-bin` package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=brave-bin#n18) though.

I would suggest you reach out to the maintainer of the Arch package. We can leave this issue open until the extra dependency gets added there.

**Comment by fmarier** [comment]
Actually, we already have a bug tracking this problem: https://github.com/brave/brave-browser/issues/2377

I added the work-around that you discovered. It would be great to get the Arch maintainer to add the extra dependency to see whether that resolves the issue.
