### ISSUE TITLE
[Desktop] [Android] consider to enable by default, if not, these flags #treat-unsafe-downloads-as-active-content to increase security #enable-heavy-ad-intervention to increase performance in certain cases

### ISSUE THREAD

**Issue by sviluppoSoftware** [brave/brave-browser#11108]
## Description 

I noticed these falgs:
#treat-unsafe-download-as-active-content flag after some research it seems to be very useful to increase security while browsing because it disables the download of executable code from unsafe websites, here is the description:
Disallows downloads of unsafe files (files that can potentially execute code), where the final download origin or any origin in the redirect chain is insecure if the originating page is secure. – Mac, Windows, Linux, Chrome OS, Android

#enable-heavy-ad-intervention
unloads Ads that consume a disproportionate amount of resources on a device negatively impact the user’s experience—from the obvious effects of degrading performance to less visible consequences such as draining the battery or eating up bandwidth allowances. These ads range from the actively malicious, such as cryptocurrency miners, through to genuine content with inadvertent bugs or performance issues.

source:  https://developers.google.com/web/updates/2020/05/heavy-ad-interventions

## Steps to Reproduce

   1. type brave://flags/ in adress bar
   2. search treat-unsafe-downloads-as-active-content and enable-heavy-ad-intervention
   3. enable both then restart brave

## Actual result:

i don't know if these flags are enable by default on latest stable version for desktop and android i think no

## Expected result:
enable by default for stable version desktop and android

## Brave version (brave://version info)

desktop version: 1.11.104 maybe earlier support this flag
android vesion: 1.11.105 maybe earlier support this flag

**Comment by bbondy** [comment]
should this be closed @rebron ?

**Comment by fmarier** [comment]
Thanks for bringing these flags to our attention @sviluppoSoftware .

> #treat-unsafe-download-as-active-content flag after some research it seems to be very useful to increase security while browsing because it disables the download of executable code from unsafe websites, here is the description: Disallows downloads of unsafe files (files that can potentially execute code), where the final download origin or any origin in the redirect chain is insecure if the originating page is secure. – Mac, Windows, Linux, Chrome OS, Android

This is one that we are tracking and looking forward to Chrome finishing their experiments and enabling by default. It's kind of a tricky one to enable for a smaller browser like Brave because it breaks functionality on some websites, intentionally of course. While this is good for security, websites aren't going to fix their download pages until Chrome enables this by default though. Brave can't really be first enabling these kinds of "moving the web to a more secure place" features without significant impact on  our users who may not understand what's happening and may just conclude that "Brave is broken".

> #enable-heavy-ad-intervention
> unloads Ads that consume a disproportionate amount of resources on a device negatively impact the user’s experience—from the obvious effects of degrading performance to less visible consequences such as draining the battery or eating up bandwidth allowances. These ads range from the actively malicious, such as cryptocurrency miners, through to genuine content with inadvertent bugs or performance issues.

This one should be unnecessary on Brave since we already block all ads (in fact we use a bigger ad list than Chrome). If you find any ads that aren't blocked, we consider that a bug and will happily add the missing entries onto EasyList.
