### ISSUE TITLE
NTP Settings Design follow up

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#11103]
Related issue: https://github.com/brave/brave-browser/issues/10318

Feedback should be implemented as described here: https://github.com/brave/brave-browser/issues/10318#issuecomment-669375261 and here: https://github.com/brave/brave-core/pull/6015#issuecomment-669478687

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.13.80 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | `94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}`
OS | Linux

- Verified focus ring is using the correct colour when clicked or focused by the keyboard tab

Light | Dark
-- | -- 
![image](https://user-images.githubusercontent.com/17010094/91281747-5ff5dd00-e780-11ea-83d0-f5d92b8e56e7.png) | ![image](https://user-images.githubusercontent.com/17010094/91281695-51a7c100-e780-11ea-837e-79732f201f25.png)

- Logged follow up issue #11439 for dark theme issue 
- Verified opening dashboard settings creates an overlay wrapper which has  `rgba(33, 37, 41, 0.32)`
![image](https://user-images.githubusercontent.com/17010094/91282242-00e49800-e781-11ea-92c0-a213702e7929.png)

- Verified clicking outside the dashboard closes the dashboard setting 

With overlay (Light) | Without overlay (Light)
-- | --
![image](https://user-images.githubusercontent.com/17010094/91282908-d941ff80-e781-11ea-941a-4ecad4a3f94f.png) | ![image](https://user-images.githubusercontent.com/17010094/91282930-df37e080-e781-11ea-8031-a8397a392a1e.png)

With overlay (Dark) | Without Overlay (Dark)
-- | --
![image](https://user-images.githubusercontent.com/17010094/91283006-f971be80-e781-11ea-9850-1d17d83ba494.png) | ![image](https://user-images.githubusercontent.com/17010094/91282981-f1198380-e781-11ea-8049-cf2d5c55f804.png)

- Verified description is using Poppins font but set at 13px (known issue) instead of 17px as per spec 
- Verified bottom margin is also removed 

Light | Dark 
-- | -- 
![image](https://user-images.githubusercontent.com/17010094/91284671-21622180-e784-11ea-88c3-581d788435bd.png) | ![image](https://user-images.githubusercontent.com/17010094/91284634-14453280-e784-11ea-853b-36e24d6235ec.png)

- Verified content area is of width 360px(known issues) instead of 390px as per sepc 

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/91284830-566e7400-e784-11ea-8f71-82c5b1fe83f4.png) | ![image](https://user-images.githubusercontent.com/17010094/91284881-6423f980-e784-11ea-9daf-970f291c34a8.png)

- Verified Card stack has the rgba values as per spec. Only verified for 3 as Brave Together is not available on release channel only available on nightly. Nightly check can be found in https://github.com/brave/brave-core/pull/6351#issuecomment-675076904

Add card | Background card 2 | Background card 1 | 
-- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/91285616-5ae75c80-e785-11ea-934f-821d2fa140b9.png) | ![image](https://user-images.githubusercontent.com/17010094/91286165-02fd2580-e786-11ea-8549-4d3bf11d75ae.png) | ![image](https://user-images.githubusercontent.com/17010094/91286252-1f00c700-e786-11ea-802a-ead88304cf43.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.13.80 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | `94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)

- Verified focus ring is using the correct colour when clicked or focused by the keyboard tab

Light | Dark
-- | -- 
<img width="1440" alt="Screenshot 2020-08-26 at 11 29 42 a m" src="https://user-images.githubusercontent.com/17010094/91293942-68690a80-e7b6-11ea-9da4-cfacad85b44a.png"> | <img width="1440" alt="Screenshot 2020-08-26 at 11 38 06 a m" src="https://user-images.githubusercontent.com/17010094/91293955-6f901880-e7b6-11ea-96fd-471d2603abfa.png">

- Encountered #11439 for dark theme issue 
- Verified opening dashboard settings creates an overlay wrapper which has  `rgba(33, 37, 41, 0.32)`
<img width="1440" alt="Screenshot 2020-08-26 at 11 31 43 a m" src="https://user-images.githubusercontent.com/17010094/91294032-8898c980-e7b6-11ea-928d-5282eaad8495.png">

- Verified clicking outside the dashboard closes the dashboard setting 

With overlay (Light) | Without overlay (Light)
-- | --
<img width="1440" alt="Screenshot 2020-08-26 at 11 29 42 a m" src="https://user-images.githubusercontent.com/17010094/91294130-ae25d300-e7b6-11ea-963b-95185a91d3c3.png"> | <img width="1440" alt="Screenshot 2020-08-26 at 11 40 29 a m" src="https://user-images.githubusercontent.com/17010094/91294148-b4b44a80-e7b6-11ea-966e-0cd24d6cadf1.png">

With overlay (Dark) | Without Overlay (Dark)
-- | --
<img width="1440" alt="Screenshot 2020-08-26 at 11 30 57 a m" src="https://user-images.githubusercontent.com/17010094/91294202-c8f84780-e7b6-11ea-99d5-fbe840224bd8.png"> | <img width="1440" alt="Screenshot 2020-08-26 at 11 31 59 a m" src="https://user-images.githubusercontent.com/17010094/91294225-cf86bf00-e7b6-11ea-92ef-b164388f5338.png">

- Verified description is using Poppins font but set at 13px (known issue) instead of 17px as per spec 
- Verified bottom margin is also removed 

Light | Dark 
-- | -- 
<img width="1440" alt="Screenshot 2020-08-26 at 11 32 42 a m" src="https://user-images.githubusercontent.com/17010094/91294353-01982100-e7b7-11ea-8948-c3ed1e9600f3.png"> | <img width="1440" alt="Screenshot 2020-08-26 at 11 33 12 a m" src="https://user-images.githubusercontent.com/17010094/91294379-0a88f280-e7b7-11ea-8e9a-ed5ebfe6a8a5.png">

- Verified content area is of width 360px(known issues) instead of 390px as per sepc 

Light | Dark
-- | --
<img width="1440" alt="Screenshot 2020-08-26 at 11 33 43 a m" src="https://user-images.githubusercontent.com/17010094/91294431-1c6a9580-e7b7-11ea-9dc6-db2c090cc5e2.png"> | <img width="1440" alt="Screenshot 2020-08-26 at 11 33 29 a m" src="https://user-images.githubusercontent.com/17010094/91294445-2391a380-e7b7-11ea-93c3-705ae823ee71.png">

- Verified Card stack has the rgba values as per spec. Only verified for 3 as Brave Together is not available on release channel only available on nightly. Nightly check can be found in https://github.com/brave/brave-core/pull/6351#issuecomment-675076904


Add card | Background card 2 | Background card 1 | 
-- | -- | -- 
<img width="1440" alt="Screenshot 2020-08-26 at 11 34 04 a m" src="https://user-images.githubusercontent.com/17010094/91293666-fbee0b80-e7b5-11ea-809c-55d1dbe17448.png"> | <img width="1440" alt="Screenshot 2020-08-26 at 11 34 21 a m" src="https://user-images.githubusercontent.com/17010094/91293690-03adb000-e7b6-11ea-9b25-c34bddf560f4.png"> | <img width="1440" alt="Screenshot 2020-08-26 at 11 34 47 a m" src="https://user-images.githubusercontent.com/17010094/91293700-07d9cd80-e7b6-11ea-8602-f99cbb6f0742.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.13.80 Chromium: 85.0.4183.83 (Official Build) (64-bit)
-- | --
Revision | `94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}`
OS | Windows 10 OS Version 1809 (Build 17763.1397)

- Verified focus ring is using the correct colour when clicked or focused by the keyboard tab

Light | Dark
-- | -- 
<img width="1552" alt="Screenshot 2020-08-26 at 11 47 17 a m" src="https://user-images.githubusercontent.com/17010094/91295897-62285d80-e7b9-11ea-85a9-b3e8bf43e707.png"> | <img width="1552" alt="Screenshot 2020-08-26 at 11 47 00 a m" src="https://user-images.githubusercontent.com/17010094/91295934-6f454c80-e7b9-11ea-8ee4-69f242be78da.png">

- Encountered #11439 for dark theme issue 
- Verified opening dashboard settings creates an overlay wrapper which has  `rgba(33, 37, 41, 0.32)`
<img width="1552" alt="Screenshot 2020-08-26 at 11 47 43 a m" src="https://user-images.githubusercontent.com/17010094/91295834-4d4bca00-e7b9-11ea-8882-bfab95dd0581.png">

- Verified clicking outside the dashboard closes the dashboard setting 

With overlay (Light) | Without overlay (Light)
-- | --
<img width="1552" alt="Screenshot 2020-08-26 at 11 47 17 a m" src="https://user-images.githubusercontent.com/17010094/91295630-ff36c680-e7b8-11ea-82af-7e9fcafb947e.png"> | <img width="1552" alt="Screenshot 2020-08-26 at 11 48 02 a m" src="https://user-images.githubusercontent.com/17010094/91295682-11186980-e7b9-11ea-8997-811c07aacbcc.png">

With overlay (Dark) | Without Overlay (Dark)
-- | --
<img width="1552" alt="Screenshot 2020-08-26 at 11 47 00 a m" src="https://user-images.githubusercontent.com/17010094/91295530-d9a9bd00-e7b8-11ea-8b11-730150d95092.png"> | <img width="1552" alt="Screenshot 2020-08-26 at 11 48 20 a m" src="https://user-images.githubusercontent.com/17010094/91295558-e6c6ac00-e7b8-11ea-888f-47b98c1573fa.png">

- Verified description is using Poppins font but set at 13px (known issue) instead of 17px as per spec 
- Verified bottom margin is also removed 

Light | Dark 
-- | -- 
<img width="1552" alt="Screenshot 2020-08-26 at 11 49 27 a m" src="https://user-images.githubusercontent.com/17010094/91295414-ae26d280-e7b8-11ea-804d-cfa8d4921354.png"> | <img width="1552" alt="Screenshot 2020-08-26 at 11 49 35 a m" src="https://user-images.githubusercontent.com/17010094/91295434-b5e67700-e7b8-11ea-8fc0-a4cfab5ab056.png">

- Verified content area is of width 360px(known issues) instead of 390px as per sepc 

Light | Dark
-- | --
<img width="1552" alt="Screenshot 2020-08-26 at 11 49 57 a m" src="https://user-images.githubusercontent.com/17010094/91295346-8f284080-e7b8-11ea-93b7-7c322349f31d.png"> | <img width="1552" alt="Screenshot 2020-08-26 at 11 49 46 a m" src="https://user-images.githubusercontent.com/17010094/91295364-97807b80-e7b8-11ea-9bef-8a4b9cf5962a.png">

- Verified Card stack has the rgba values as per spec. Only verified for 3 as Brave Together is not available on release channel only available on nightly. Nightly check can be found in https://github.com/brave/brave-core/pull/6351#issuecomment-675076904


Add card | Background card 2 | Background card 1 | 
-- | -- | -- 
<img width="1552" alt="Screenshot 2020-08-26 at 11 50 10 a m" src="https://user-images.githubusercontent.com/17010094/91295216-5b4d1b00-e7b8-11ea-88cf-14997ef3ad8d.png"> | <img width="1552" alt="Screenshot 2020-08-26 at 11 50 27 a m" src="https://user-images.githubusercontent.com/17010094/91295245-6738dd00-e7b8-11ea-913d-0e999c2572bc.png"> | <img width="1552" alt="Screenshot 2020-08-26 at 11 50 35 a m" src="https://user-images.githubusercontent.com/17010094/91295264-6d2ebe00-e7b8-11ea-84d8-57395a83f28e.png">

**Comment by srirambv** [comment]
Follow up issue https://github.com/brave/brave-browser/issues/11441
