### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by serlokiyo** [brave/brave-browser#11148]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.11.104  Chromium: 84.0.4147.105
Operating System: Windows NT 10.0.19041

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.A mention on brave upgrade
2. blue screen
3. it opens 10 sec then closes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/e1480000-45d5-d704-0000-000000000000

**Comment by bsclifton** [comment]
@serlokiyo thanks for the report! This is due to the OLD version of Sync being enabled

We did a release today which features the new Sync v2. After updating, you should notice this problem is completely gone 😄 You can either update in-app or if that gives you trouble grab the latest version from https://brave.com/download
