### ISSUE TITLE
[Android] [Follow up #9865] Upgrading to 1.12.x doesn't reintroduce rewards onboarding if ads is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#11199]
## Description 
[Follow up #9865] Upgrading to 1.12.x doesn't reintroduce rewards onboarding if ads is disabled

## Steps to reproduce 

   1. Install 1.11.105
   2. Enable rewards and disable ads settings
   3. Upgrade to 1.12.112
   4. Quit browser
   5. Rewards doesn't show `?` after upgrade 
   6. Follow steps from https://user-images.githubusercontent.com/2388823/81741066-cdd8fb80-9452-11ea-8a80-265b4f0810d9.png for clicking rewards button
   6. No rewards onboarding is shown when the browser is launched 

## Actual result 
Upgrading to 1.12.x doesn't reintroduce rewards onboarding if ads is disabled

## Expected result
As per spec user should be shown rewards onboarding to enable ads and show a sample ad notification when enabled

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.12.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @karenkliu

**Comment by deeppandya** [comment]
@srirambv we decided not to show any onboarding for existing users. @karenkliu specs need to be updated.

**Comment by karenkliu** [comment]
@srirambv @deeppandya Since we're not doing BRE with this onboarding update, we will not show Rewards onboarding to existing users. For new users, we're still doing the new onboarding flows but instead of saying "Turn on Earn & Give" we say "Turn on Rewards" just like before:

![image](https://user-images.githubusercontent.com/2388823/90050416-032bfa00-dc8b-11ea-88e1-e699d2df302d.png)

Previously we closed this issue https://github.com/brave/brave-browser/issues/8360 which got rid of "Get paid" verbiage in the sponsored image messages and updated the text with BRE changes. We are keeping the text changes done there, except anywhere you see "Earn & Give" should be replaced with "Brave Ads". Also the terms should say `By turning on Rewards...` just like before, instead of saying `By turning on Earn & Give...` Lastly, since we don't have BRE we need to keep the Brave Rewards off states:

![image](https://user-images.githubusercontent.com/2388823/90048743-c65f0380-dc88-11ea-8ce0-4a6aebe8dd92.png)

**Comment by deeppandya** [comment]
@karenkliu we decided to remove path for user when we show SI NTP and BR off. so above change is irrelevant. ref . https://github.com/brave/brave-browser/issues/8360

**Comment by deeppandya** [comment]
@srirambv i think we should close this issue as it's irrelevant at this time.

**Comment by srirambv** [comment]
Yeah closing it as invalid
