### ISSUE TITLE
In-browser drip campaign introducing features

### ISSUE THREAD

**Issue by tildelowengrimm** [brave/brave-browser#1126]
Browsers have a lot of features. Brave has even more. Many of our features are brand new — they don't really exist in other browsers, and some are brand new concepts for the Web in general. It would be unreasonable to expect folks who start using Brave to immediately understand everything that's available to them. An onboarding experience which explains all of Rewards and Shields and the rest would be too long and get in the way of just using Brave to browse the web.

Instead, we could introduce features slowly over time. If someone hasn't changed shields settings or turned on payments or tried private browsing or what have you, we could use an unobtrusive indicator to let them know that there's something to learn. Features like shields are a lot more powerful for people who understand the underlying tech — so there's a great opportunity to empower folks to get the most out of their browser.

C.f: #805

**Comment by bbondy** [comment]
This is a little too vague for github, could you be more specific here? Or else maybe we should post this in higher level tracking like asana?

**Comment by bbondy** [comment]
I started a new wiki here to describe at what level we should track here:
https://github.com/brave/brave-browser/wiki/Creating-an-issue

But mainly the problem is just that an issue should be specific enough to be actionable.  Otherwise it can't be closed. 

One example is I could create an issue that says "Developers should be delighted and happy to use Brave", but it is so vague that there's no clear way to know when that is fully actually achieved, so it just remains deadweight and open forever, and complicates triage.

**Comment by tomlowenthal** [comment]
The proposal here is to add indicators for our features which are displayed over time as someone starts out with Brave. I agree that this is a description of a large bundled cluster project, on the same order of complexity as "support Tor for private browsing", "add an Ethereum wallet", or "refresh overall design".
