### ISSUE TITLE
[Desktop] Uphold server url handling

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11286]
Ref: #10987

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.15.56 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
Revision	ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/6511

<details>
<summary>Using a wallet funded only via Uphold KYC'd BAT, confirmed able to do 1 time tips, recurring tips, and AC using KYC'd Uphold wallet (staging env)</summary>

<img width="412" alt="Uphold1" src="https://user-images.githubusercontent.com/28145373/93929558-097daf00-fcea-11ea-9b28-5ce33d6eeb50.png">
<img width="947" alt="Uphold2" src="https://user-images.githubusercontent.com/28145373/93929561-0aaedc00-fcea-11ea-8649-658f4efff5d0.png">
<img width="949" alt="Uphold3" src="https://user-images.githubusercontent.com/28145373/93929566-0be00900-fcea-11ea-93cd-7d7ca0759f29.png">
<img width="946" alt="Uphold4" src="https://user-images.githubusercontent.com/28145373/93929569-0c789f80-fcea-11ea-832c-a4440c321b15.png">
<img width="944" alt="Uphold5" src="https://user-images.githubusercontent.com/28145373/93929579-10a4bd00-fcea-11ea-9f37-32ef13e1a22c.png">

</details>

<details>
<summary>Confirmed brave://rewards-internals showed data from above Uphold contributions (1 time tips, recurring tips, AC) as expected</summary>

<img width="1000" alt="Uphold6" src="https://user-images.githubusercontent.com/28145373/93929595-16020780-fcea-11ea-8518-32dab5420231.png">

</details>

<details>
<summary>Connect brand new KYC</summary>

1. Clean profile, staging, enabled rewards
2. Confirmed able to restore a wallet with an ad grant waiting and claim ad grant. 
3. Due to required balance needed, claimed UGP grant also.

<img width="409" alt="Uphold7" src="https://user-images.githubusercontent.com/28145373/93929614-1bf7e880-fcea-11ea-9df8-038a8019d3ad.png">

4. Clicked Verify Wallet and signed up for Uphold account. Began KYC process.

<img width="395" alt="Uphold8" src="https://user-images.githubusercontent.com/28145373/93929627-1f8b6f80-fcea-11ea-9ddb-ca7505030c6e.png">

5. After account was KYC'd, confirmed Ad grant BAT only moved to Uphold. UGP grant BAT did not move to Uphold as expected.

<img width="395" alt="Uphold9" src="https://user-images.githubusercontent.com/28145373/93929642-23b78d00-fcea-11ea-8961-4ae943351542.png">
<img width="399" alt="Uphold10" src="https://user-images.githubusercontent.com/28145373/93929643-24e8ba00-fcea-11ea-8e5f-81bb305f3d4f.png">

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/........./claim
> Method: UrlMethod::POST
> Content: {"signedLinkingRequest":"eyJib..........
> Content Type: application/json; charset=utf-8
[12965:775:0922/143029.524692:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/.........../claim
> Result: Success
> HTTP Code: 200
> Body: null

[12965:775:0922/143029.542070:VERBOSE5:ledger_impl.cc(128)] 
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v1/suggestions/claim
> Method: UrlMethod::POST
> Content: {"credentials":[{"publicKey":"dui7F.................
[12965:775:0922/143030.070848:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v1/suggestions/claim
> Result: Success
> HTTP Code: 200
> Body: 
```
<img width="394" alt="Uphold11" src="https://user-images.githubusercontent.com/28145373/93929677-2f0ab880-fcea-11ea-83e1-48bafdd69d74.png">
<img width="1179" alt="Uphold12" src="https://user-images.githubusercontent.com/28145373/93929681-303be580-fcea-11ea-840b-5f68e3306bd2.png">
<img width="409" alt="Uphold13" src="https://user-images.githubusercontent.com/28145373/93929689-316d1280-fcea-11ea-8306-a5af85bf10ef.png">

</details>

<details>
<summary>Connect existing KYC</summary>

1. Clean profile, staging, enabled rewards
2. Confirmed able to restore a wallet with an ad grant waiting and claim ad grant. 

<img width="402" alt="Uphold14" src="https://user-images.githubusercontent.com/28145373/93929701-3631c680-fcea-11ea-8f67-dc8255b39b82.png">

3. Clicked Verify Wallet and connected an already KYC'd Uphold account
4. Confirmed ad grant was transferred to Uphold

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/............/claim
> Method: UrlMethod::POST
> Content: {"signedLinkingRequest":"eyJ...........
> Content Type: application/json; charset=utf-8
[13232:775:0922/153648.614576:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/............/claim
> Result: Success
> HTTP Code: 200
> Body: null

[13232:775:0922/153648.630579:VERBOSE5:ledger_impl.cc(128)] 
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v1/suggestions/claim
> Method: UrlMethod::POST
> Content: {"credentials":[{"publicKey":"dui7FOe................
[13232:775:0922/153649.230570:VERBOSE6:logging_util.cc(136)] 
[ RESPONSE - OnRequest ]
> Url: https://grant.rewards.bravesoftware.com/v1/suggestions/claim
> Result: Success
> HTTP Code: 200
> Body: 
```

<img width="1165" alt="Uphold15" src="https://user-images.githubusercontent.com/28145373/93929712-3b8f1100-fcea-11ea-8a43-4fc7d9fb7744.png">
<img width="417" alt="Uphold16" src="https://user-images.githubusercontent.com/28145373/93929716-3cc03e00-fcea-11ea-80e4-6669f90b94de.png">



</details>

-------------
