### ISSUE TITLE
[Desktop] OpenSuSE: repomd.xml signed with unknown GnuPG key

### ISSUE THREAD

**Issue by RBauglir** [brave/brave-browser#11295]
## Description 
On OpenSuSE Leap 15.2: When adding Brave release channel repo with YaST Software, after importing Brave core key (fingerprint:
D8BAD4DE7EE17AF52A834B2D0BB75829C2D4E821), it happens to appear an error message telling repomd.xml is signed with an unknown GnuPG key, with ID: A8580BDC82D3DC6C.

## Steps to Reproduce

   1. Import "https://brave-browser-rpm-release.s3.brave.com/brave-core.asc" key into YaST Software's GPG Key Manager.
   2. Add a new repo and introduce the URL: "https://brave-browser-rpm-release.s3.brave.com/x86_64/".
   3. Press "Continue" to add the repo, and then appears the error window.

## Actual result:
Error message telling repomd.xml is signed with an unknown GPG key.

## Expected result:
repomd.xml signed with the correct GPG key, and consequently no error message.

## Version/Channel Information:
Have tried with Beta and Nightly channels, with their respective GPG key, with the same result (with different key IDs).

**Comment by srirambv** [comment]
Closing in favour of #11279

**Comment by RBauglir** [comment]
@srirambv I don't understand why you closed this issue: it has no relationship with #11279 ... I'm perfectly able to install the browser: the problem is that the wrong signature makes the binaries untrustworthy.

**Comment by jlturriff** [comment]
The issue of the GnuPG key has nothing to do with this issue.  zypper cannot retrieve the metadata for the repository, so it cannot download repomd.xml to even look at the signing key.  I retried the zypper install brave-browser command and got the same results:

█ zypper install brave-browser
**Timeout exceeded** when accessing 'https://brave-browser-rpm-release.s3.brave.com/x86_64/repodata/repomd.xml'.
Abort, retry, ignore? [a/r/i] (r):
Trying again...
**Timeout exceeded** when accessing 'https://brave-browser-rpm-release.s3.brave.com/x86_64/repodata/repomd.xml'.
Abort, retry, ignore? [a/r/i] (r):
Trying again...
**Timeout exceeded** when accessing 'https://brave-browser-rpm-release.s3.brave.com/x86_64/repodata/repomd.xml'.
Abort, retry, ignore? [a/r/i] (r):
Trying again...
**Timeout exceeded** when accessing 'https://brave-browser-rpm-release.s3.brave.com/x86_64/repodata/repomd.xml'.
Abort, retry, ignore? [a/r/i] (a):
Trying again...
Error building the cache:
[brave-browser|https://brave-browser-rpm-release.s3.brave.com/x86_64/] Valid metadata not found at specified URL
History:
 - Unknown error reading from 'https://brave-browser-rpm-release.s3.brave.com/x86_64/'
 - ABORT request: Aborting requested by user
 - **Timeout exceeded when accessing** 'https://brave-browser-rpm-release.s3.brave.com/x86_64/repodata/repomd.xml'.

Warning: Skipping repository 'brave-browser' because of the above error.
Retrieving repository 'packman' metadata ...............................................................................................[done]
Building repository 'packman' cache ....................................................................................................[done]
Retrieving repository 'packman' metadata ...............................................................................................[done]
Building repository 'packman' cache ....................................................................................................[done]
Some of the repositories have not been refreshed because of an error.
Loading repository data...
Reading installed packages...
'brave-browser' not found in package names. Trying capabilities.
No provider of 'brave-browser' found.
Resolving package dependencies...

Nothing to do.

So even if the GnuPG key gets fixed, without being able to retrieve data from the repository, which seems to be offline, that won't help me.
I also tried <traceroute brave-browser-rpm-release.s3.brave.com> and got this result:

█ traceroute brave-browser-rpm-release.s3.brave.com
traceroute to brave-browser-rpm-release.s3.brave.com (199.232.74.217), 30 hops max, 60 byte packets
 1  grey.sixys.site (192.168.1.1)  0.747 ms  0.680 ms  0.641 ms
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *^C

So the repository doesn't seem to be responding to requests.

**Comment by jlturriff** [comment]
If there is a place from which I can download the source code for the stable version, I can build it myself? But this GitHub site only seems to provide unstable versions.
