### ISSUE TITLE
[Desktop] Mute On a Per Tab Basis.

### ISSUE THREAD

**Issue by RobertH1999** [brave/brave-browser#11314]
## Description 
Right now, the functionality of the mute is the same as Chrome / Chromium where you can only mute per SITE. I hope that users can mute tabs on a per tab basis. 

## Steps to Reproduce

   1. Right click on a tab.
   2. 
![image](https://user-images.githubusercontent.com/32373877/90582488-d781a600-e19b-11ea-9217-33cc5b782939.png)

## Expected result:

![image](https://user-images.githubusercontent.com/32373877/90582572-0c8df880-e19c-11ea-8b76-aca668365c94.png)

## Reproduces how often: 

Easily reproduced. 

## Brave version (brave://version info)

Brave | 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Don't know, most likely yes.
- Can you reproduce this issue with the nightly channel? Don't know, most likely yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No. 
- Is the issue reproducible on the latest version of Chrome? No.

## Miscellaneous Information:

Hopefully this feature can be implemented in future builds.

**Comment by rebron** [comment]
hi @RobertH1999 You can mute per tab by selecting the sound icon or use the media controls icon that appears on the toolbar menu. We're likely not going to add a third way to mute a tab but can leave this issue open if others disagree.

**Comment by TheGreatMcPain** [comment]
I know this might be pretty niche, but I'm currently working as a Technical Assistant for a week long conference that's online.

I have to monitor two video-chats at the same time which are on separate browser windows. I'm able to toggle my microphone on a per-tab basis, but I can't mute the audio on a per-tab basis due to the lack of the "sound icon". So, if I need to mute the audio on one of the video-chats I have to leave it which sometimes kills the audio on the other video-chat.

Having a mute-tab context menu would help greatly.

**Comment by bsclifton** [comment]
I'm not sure when this was resolved - but we did resolve this 😄 
![image](https://user-images.githubusercontent.com/4733304/215687403-62c316ff-71e2-4d52-bdd8-ab42cedf5c0b.png)

**Comment by RobertH1999** [comment]
I think it's been resolved a few versions ago. Thanks!
