### ISSUE TITLE
Fingerprinting Protections v2: Workers

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#11368]
This is a sub-issue of the larger fingerprint defense reorganization issue: #8787 

Currently farbling protections are not applied in workers.  Brave should apply farbling protections in workers.

**Comment by abrahamjuliot** [comment]
@pilgrim-brave 
@pes10k
Hardware concurrency appears consistent in workers now. Per #9186, should this fix include offscreen canvas rendering contexts? Webgl vendor and renderer are still exposed via workers. I presume shaders precisions and max constants are also exposed.

**Comment by pes10k** [comment]
@abrahamjuliot thank you for the comment / catch.  This is suprising, and is being into looked into now.  Thanks for the help!

**Comment by LaurenWags** [comment]
@pes10k @pilgrim-brave could you guys help out with the test plan for this one?

I thought maybe it would be to go to the QA pages @pes10k set up and confirm the "Worker" column but on a clean profile with below build not everything is acting as expected. Is this because the test plan should be different? or is there an issue here?


Brave | 1.16.52 Chromium: 86.0.4240.68 (Official Build) dev (x86_64)
-- | --
Revision | ad72ee9aa8e15ed300df1238e76c7a8f4d686f97-refs/branch-heads/4240@{#1097}
OS | macOS Version 10.14.6 (Build 18G3020)


<img width="1201" alt="standard shields" src="https://user-images.githubusercontent.com/28145373/95099004-5eafbc80-06fd-11eb-988e-258d5f3a3206.png">

labeling as `QA/Blocked` until this is sorted.

**Comment by pes10k** [comment]
I'm not seeing this on nightly currently (see below screenshot) so maybe this is just something that needs to be uplifted? (cc @pilgrim-brave )
<img width="1143" alt="Screen Shot 2020-10-05 at 8 25 25 PM" src="https://user-images.githubusercontent.com/76526/95145329-ef5fba00-0748-11eb-9322-364c402c2d77.png">

**Comment by LaurenWags** [comment]
@pes10k what is your shield setting here? also it might be worth looking at both pages. I'm definitely seeing some inconsistencies/unexpected results. Please see below screenshots/notes. Once you get to review to confirm that the error is with FP code and not the testing page, I'm happy to log any follow up issues needed.

<details>
<summary>1.16.x</summary>

Standard shield setting for FP

<img width="1205" alt="11368 std both pages 1 16" src="https://user-images.githubusercontent.com/28145373/95363185-1d561300-089d-11eb-9fb5-24a9887894d2.png">

For both pages, the `Worker` column for `WebGL Drawing` has a different value than the other columns. Since this `WebGL Drawing` is only in standard (per the `Mode` column), I expected the `Worker` value to match the other column values.

For both pages, the `Worker` column for `Canvas` has a different value than the other columns. Since `Canvas` is available in both standard and strict (per the `Mode` column), I expected the `Worker` value to match the other column values. **Additionally, note that the `Worker` value from the top page matches the `This Page`, `Local Frame` and `Remote Frame` values for the lower page. Seems odd, no?


Strict shield setting for FP

<img width="1203" alt="11368 strict both pages 1 16" src="https://user-images.githubusercontent.com/28145373/95363195-21823080-089d-11eb-9033-fa550de246b0.png">


For both pages, the `Worker` column for `WebGL Drawing` matches the other columns and is different between the two pages. Since this `WebGL Drawing` is only in standard (per the `Mode` column), I expected the values to be the same as when shields = standard. Am I misunderstanding this?

</details>




<details>
<summary>1.17.x</summary>

Standard shield setting for FP

<img width="1196" alt="11368 std both pages 1 17" src="https://user-images.githubusercontent.com/28145373/95363207-25ae4e00-089d-11eb-8626-e69a845d4d5b.png">


For both pages, the `Worker` column for `WebGL Drawing` has a different value than the other columns. Since this `WebGL Drawing` is only in standard (per the `Mode` column), I expected the `Worker` value to match the other column values.

For top page (dev-pages.bravesoftware.com/farbling.html), the `Worker` column for `Canvas` has a different value than the other columns. 
For the bottom page, (dev-pages.brave.software/farbling.html), the `Worker` column for `Canvas` is the same across all columns. Not sure why he two pages are acting differently?


Strict shield setting for FP

<img width="1199" alt="11368 strict both pages 1 17" src="https://user-images.githubusercontent.com/28145373/95363221-2941d500-089d-11eb-8d22-1cbaa944e26f.png">


For both pages, the `Worker` column for `WebGL Drawing` matches the other columns and is different between the two pages. Since this `WebGL Drawing` is only in standard (per the `Mode` column), I expected the values to be the same as when shields = standard. Am I misunderstanding this?

For top page (dev-pages.bravesoftware.com/farbling.html), the `Worker` column for `Canvas` has a different value than the other columns. 
For the bottom page, (dev-pages.brave.software/farbling.html), the `Worker` column for `Canvas` is the same across all columns. Not sure why he two pages are acting differently?

Note - shield settings aren't pictured because they cover the table, however, if you look at `WebGL Vendor and Render` and `User Agent` you can see that they are behaving as expected for std/strict so I am positive that the shield settings are accurate, I just don't know why these two aren't working as expected. 


</details>

**Comment by pes10k** [comment]
Hmm, my shield settings are all default, and im on `1.17.17 Chromium: 86.0.4240.72 (Official Build) nightly (x86_64)`.  I dont have a good explanation for this.  I believe @pilgrim-brave is working on an issue related to this, but would be best if he can confirm.

<img width="1175" alt="Screen Shot 2020-10-07 at 8 10 50 PM" src="https://user-images.githubusercontent.com/76526/95400677-341a5b00-08d9-11eb-8f4c-5653d951449e.png">

**Comment by LaurenWags** [comment]
@pes10k @rebron logged some follow up issues here since it seems like there's still some work to be done in this area. They are:
- https://github.com/brave/brave-browser/issues/12098
- https://github.com/brave/brave-browser/issues/12099

Going to mark this issue as `QA/No` and `release-notes/exclude` since it's not fully completed and testing should be done with the above logged issues. Please let me know if there are any objections to this.
