### ISSUE TITLE
[Desktop] Implement design for tipping banner

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#11393]
You can find designs in https://www.figma.com/file/EDGI52tfWG1ggC9ZYFguXy/tipping-banner-revamp-copy.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.17.63 Chromium: 87.0.4280.49 (Official Build) unknown (x86_64)
Revision	f77f85899646b42a1d3c8ff36794e00becab9171-refs/branch-heads/4280@{#1115}
OS	macOS Version 10.14.6 (Build 18G6032)
```

Verified test plan from https://github.com/brave/brave-core/pull/6626

<details>
<summary>Case 1: One-time tipping - Unverified publisher</summary>

Confirmed banner matches designs for one time tipping without credit card option.
Confirmed default values of 1, 10, 100 BAT are displayed as tipping options.
Confirmed "add funds" link is displayed if there is not sufficient BAT in the wallet. Confirmed clicking on this link opens brave://rewards page, modal is not opened as per note in PR.
Confirmed able to select an amount and send tip. Since publisher is unverified, confirmed tip went to Pending list. 
Confirmed clicking on the tweet button opened a new tab and drafted a tweet with expected wording.

<img width="1191" alt="1 time tip - unverified" src="https://user-images.githubusercontent.com/28145373/98552932-0ffdc100-226d-11eb-9c99-d47be4d60602.png">
<img width="1195" alt="1 time tip - unverified - add funds link" src="https://user-images.githubusercontent.com/28145373/98552940-112eee00-226d-11eb-8c72-48a2d0dded7f.png">
<img width="1191" alt="1 time tip - unverified - successful tip" src="https://user-images.githubusercontent.com/28145373/98552944-12601b00-226d-11eb-8b93-487d96ca8b82.png">
<img width="617" alt="1 time tip - unverified - tweet" src="https://user-images.githubusercontent.com/28145373/98552947-12f8b180-226d-11eb-8389-debed2449b95.png">
<img width="952" alt="1 time tip - unverified - pending list" src="https://user-images.githubusercontent.com/28145373/98552951-13914800-226d-11eb-9255-c636400cd68b.png">


</details>
