### ISSUE TITLE
[Desktop] webtorrent .torrent file detection security issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#11488]
https://hackerone.com/reports/963155

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.15.50 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6531
- Verified that file is not a torrent alert message is displayed upone click on save torrent file

![image](https://user-images.githubusercontent.com/38657976/93227374-e73bdc80-f791-11ea-933e-15f048d700e0.png)

**Comment by GeetaSarvadnya** [comment]
@feross select `https://php-demo-app-shibli.cfapps.io/test-driver.php` link in URL bar and enter displays save .bat file window. Is this expected?

![image](https://user-images.githubusercontent.com/38657976/93230319-2b7cac00-f795-11ea-9683-1e7cdaa2b409.png)

**Comment by kjozwiak** [comment]
@diracdeltas as per @GeetaSarvadnya's comment above, you can still download the POC if you paste the following URL into the omnibox rather than clicking on `Save .torrent file`. Assuming that's expected as we're not doing the check for `.torrent` files via the omnibox. Please let us know if we need to file a follow up to address the above.

**Comment by diracdeltas** [comment]
@kjozwiak that's fine. thank you!
