### ISSUE TITLE
[Android] acrhive.is domain shows unsupported browser

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#11517]
## Description 
archive.is domain shows unsupported browser
![archive_is_error](https://user-images.githubusercontent.com/12011303/91668382-5c44bc00-eada-11ea-89f0-62160805ba05.jpeg)

## Steps to reproduce 

   1. Go to archive.is
   2. Observe the picture above

## Actual result 
An unsupported browser message

## Expected result
archive.is should work

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
Reopened as it's broken again due to changes on the original host.

**Comment by elvey** [comment]
FYI, my experience, on MacOS:  Archive.today and archive.vn started displaying this block a few weeks before archive.is did.  FYI.

Any educated guesses as to what's going on here on archive.today's side?  ((Technically and/or politically?). Is my WAG likely to be right?  My WAG (wild ass guess) is that they're intentionally blocking Brave users because of its stance on ads, and I guess Sergey is adding workarounds likely to work, on Android, in the short term, per https://www.ctrl.blog/entry/brave-user-agent-detection.html, which I appreciate Sergey for, but a stable fix/situation is far from assured.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.84 x64 build
- Verified site is blocked on `1.13.83`
- Verified upgrading to `1.13.84` doesn't block the site 
--------
Verification passed on Samsung Tab A with Android 10 running 1.13.84 x64 build
- Verified site is blocked on `1.13.83`
- Verified upgrading to `1.13.84` doesn't block the site

**Comment by ryanbr** [comment]
Have re-opened this,  reported by a user on https://twitter.com/ArthurFrDent/status/1340883521661898753

Can confirm in Brave Release and Nightly for Android

**Comment by kjozwiak** [comment]
Closing as this was closed a long time ago. We don't re-open issues once they've landed/released. Created https://github.com/brave/brave-browser/issues/13304.
