### ISSUE TITLE
Support automatic redirection of IPFS gateway resources

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11564]
When a gateway URL is detected, redirect it to the local node instead .

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.20.87 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
Revision	68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS	macOS Version 10.15.7 (Build 19H15)
```

Verified test plan from https://github.com/brave/brave-core/pull/7299

<details>
<summary>Navigated to https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/ and confirmed link loaded without any redirect</summary>

<img width="1035" alt="1" src="https://user-images.githubusercontent.com/28145373/105507197-e8799a80-5c98-11eb-8258-358f0c83748d.png">

</details>

<details>
<summary>Enabled "Redirect IPFS resources to the configured IPFS gateway" setting in brave://settings/extensions</summary>

<img width="704" alt="2" src="https://user-images.githubusercontent.com/28145373/105507209-eb748b00-5c98-11eb-8ed9-c96f8ba44f8b.png">

</details>

<details>
<summary>Navigated to https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/ in a new tab and confirmed link loaded with redirect to configured gateway</summary>

<img width="1034" alt="3" src="https://user-images.githubusercontent.com/28145373/105507222-ee6f7b80-5c98-11eb-9ee0-6a518faa10d3.png">
<img width="1034" alt="4" src="https://user-images.githubusercontent.com/28145373/105507227-efa0a880-5c98-11eb-992e-9088a86d6f93.png">

</details>

<details>
<summary>Modified "IPFS public gateway address" setting in brave://settings/extensions</summary>

<img width="542" alt="5" src="https://user-images.githubusercontent.com/28145373/105507240-f4fdf300-5c98-11eb-8c2d-9a17d045ceba.png">
<img width="728" alt="6" src="https://user-images.githubusercontent.com/28145373/105507246-f62f2000-5c98-11eb-97f0-f0b311d91ff2.png">

</details>

<details>
<summary>Navigated to https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/ in a new tab and confirmed link loaded with redirect to the changed gateway</summary>

<img width="1036" alt="8" src="https://user-images.githubusercontent.com/28145373/105507263-fa5b3d80-5c98-11eb-9a0a-7f9a02ec05ec.png">

</details>

<details>
<summary>Installed IPFS from infobar. Confirmed "Method to resolve IPFS resources" was set to Local node in brave://settings/extensions</summary>

Note - had to refresh page due to https://github.com/brave/brave-browser/issues/13171.

<img width="732" alt="9" src="https://user-images.githubusercontent.com/28145373/105507276-fd562e00-5c98-11eb-8c54-da88803533c4.png">

</details>

<details>
<summary>Navigated to https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/ in a new tab and confirmed link loaded with local node</summary>

<img width="1033" alt="11" src="https://user-images.githubusercontent.com/28145373/105507284-01824b80-5c99-11eb-8f1f-d038f4696710.png">

</details>
