### ISSUE TITLE
Dapp detection should now use window.ethereum and not window.web3

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#11698]
## Description 

On November 16, 2020 MetaMask plans to remove window.web3 https://github.com/MetaMask/metamask-extension/issues/8077 in favor of window.ethereum

We should remove our Dapp detection for window.web3 and use window.ethereum instead. 

# QA test plan

1. Fresh profile
2. Go to cryptokitties.co
3. Ensure the dapp detection prompt still comes up

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.16.55 Chromium: 86.0.4240.72 (Official Build) dev (64-bit)
-- | --
Revision | 581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified the info bar is shown. Verified that the injected script uses `window.ethereum`
![image](https://user-images.githubusercontent.com/34715963/95362875-07f9dc80-08cf-11eb-8194-b2ea34da3498.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (x86_64)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified dapp detection script uses `window.ethereum` instead of `window.web3`
![image](https://user-images.githubusercontent.com/17010094/95853919-0ce6e200-0d4e-11eb-9663-b5f1ae715ea8.png)

---------
Verification passed on 

Brave | 1.16.59 Chromium: 86.0.4240.75 (Official Build) beta (64-bit)
-- | --
Revision | `c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}`
OS | Windows 10 OS Version 1809 (Build 17763.1490)

- Verified dapp detection script uses `window.ethereum` instead of `window.web3`
![image](https://user-images.githubusercontent.com/17010094/95854154-78c94a80-0d4e-11eb-80e8-062da80e1a19.png)
