### ISSUE TITLE
Sentry.io is blocked now

### ISSUE THREAD

**Issue by AoDev** [brave/brave-browser#11736]
## Description 
We are using `https://sentry.io` to track errors in our apps. Until now it worked fine. I've noticed recently that it's blocked by Brave. I don't know if it's due to the last update or an older one.

## Steps to Reproduce
You can visit `https://battletraders.io` with shield up and shield down. You'll see an error in the console because Sentry is blocked by Brave now. 

## Actual result:
Sentry is blocked.

## Expected result:
I wish Sentry wasn't blocked. It's not really meant to spy on users, just pick up issues.

## Brave version (brave://version info)

OSX Mojave | Version 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-bit)

**Comment by rebron** [comment]
cc: @ryanbr Any thoughts on `https://sentry.io`?

**Comment by ryanbr** [comment]
Hey @AoDev  It's blocked in Easyprivacy. The sentry filter is not recent.

Due to privacy issues, we block other 3rd-party monitoring/performance checks, and event trackers.  Sentry isn't treated any differently. Having less third-party servers being loaded (regardless how helpful it is) always improves privacy for the end user.

**Comment by AoDev** [comment]
@ryanbr What is "Easyprivacy"? 

On the other hand, I'm fine with the principle, that's why I am myself a Brave user.
But as a developer, I'd like an alternative to be able to improve my apps by catching user bugs. Sentry has been very useful for that, especially for bugs on mobiles. What could we do instead? I'd rather not build my own sentry.

**Comment by ryanbr** [comment]
@AoDev 

Easylist and Easyprivacy are lists used by Brave, and the popular adblockers (uBlock Origin, Adblock plus, Adblock and Adguard), and other web browsers.

I understand it can be helpful for web development, but it still privacy issue for the enduser which is why it's blocked.

**Comment by AoDev** [comment]
Would it be possible to detect, ask user permission and allow a particular tracker like Sentry?
A bit like the (horrible) cookies consent we are having everywhere now. (UX is a different matter)

**Comment by ryanbr** [comment]
The block on sentry is treated like any other tracker/analytics, not treated any differently. Having a prompt for selective domains would become an annoyance (and also question why its added if we're having to prompt the user). There is already enough prompts on the web, to not add more.

Having a user to decide on privacy, via a prompt wouldn't be a good idea.

**Comment by AoDev** [comment]
How and when the user permission is asked is for product managers to decide. I was asking for the possibility to enable certain filters to be available for developers.
On the other hand, I am still asking for an effective alternative that would respect users privacy.

**Comment by ryanbr** [comment]
It would be out of the scope of this report, but you're free to create a new Github issue report regarding tracking notifications in Brave. Just note, the user or developer are free to disable ads/tracking in shields on a per-site basis or even globally.

I'm closing this report, since it's already been stated why its sentry is blocked.
