### ISSUE TITLE
RANDOMIZE TIMEZONE

### ISSUE THREAD

**Issue by Dev-i-l** [brave/brave-browser#11866]
I HAVE SEARCHED AND BROMITE RECENTLY ADDED THIS FEATURE, HERE IS THE PATCH https://github.com/bromite/bromite/commit/23485dc259aedca142e62eb9daadb8f663dd712f 

RANDOMIZING TIMEZONE IS A PRIVACY RELATED FEATURE, WHICH CAN HELP ONE TO BROWSE ANONYMOUSLY.

**Comment by pes10k** [comment]
We've been considering timezones as fingerprinting-surface a bit here https://github.com/brave/brave-browser/issues/8574 (that issue is another way we've discussed addressing).

FWIW, its appealing, but seems very likely to have non-trivial web-comapt cost, and so we're not sure how / if we'll proceed.  

To keep # issues manageable, im going to close this issue, but add this option as another for consideration in https://github.com/brave/brave-browser/issues/8574

its very helpful to know what the Bromite folks are doing though. Thanks much for the link and for the suggestion!

**Comment by Dev-i-l** [comment]
your reply is much appreciated

> 
> 
> We've been considering timezones as fingerprinting-surface a bit here #8574 (that issue is another way we've discussed addressing).
> 
> FWIW, its appealing, but seems very likely to have non-trivial web-comapt cost, and so we're not sure how / if we'll proceed.
> 
> To keep # issues manageable, im going to close this issue, but add this option as another for consideration in #8574
> 
> its very helpful to know what the Bromite folks are doing though. Thanks much for the link and for the suggestion!
