### ISSUE TITLE
chrome://crashes not working under Win 7

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#1188]
## Test plan
See https://github.com/brave/brave-core/pull/1292

## Description
Copying from https://github.com/brave/browser-laptop/issues/12910 as this is still an issue with `brave-core`. If we want crash reports for our Win 7 user base before we release 1.0 so we can see how stable the product is before the major release, we'll need to fix this. We usually get a good percentage of companies from users via the community that are running Win 7. If we decide to not support Win 7, we can close this off.

Example of `chrome://crashes` not working under Win 7:

![crashreporting](https://user-images.githubusercontent.com/2602313/45724352-b5ccae00-bb83-11e8-9f81-516da7f90543.gif)

STR are exactly the same as mentioned below.

> 
> 
> ### Description
> 
> 
> Crashes under Win 7 don't seem to be submittable and don't have `Crash Report ID's`.
> 
> ### Steps to Reproduce
> 
> 
>   1. under a Win 7 machine, launch `0.19.147`
>   2. open a tab and visit `chrome://crash`
>   3. once the tab has crashes, load `chrome://crashes`
>   4. select "Send" and restart the browser
>   5. once the browser has been restarted, load `chrome://crashes`
> 
> **Actual result:**
> 
> 
> Crashes under Win 7 are only displaying `Local Crash ID's` and are not being submitted when selecting `Send` under `chrome://crashes`.
> 
> ![win7crashes](https://user-images.githubusercontent.com/2602313/35530750-fe73d04e-0502-11e8-9d4a-80d295a458f2.gif)
> 
> **Expected result:**
> 
> Crashes should include `Crash Report ID` and should be submittable.
> 
> **Reproduces how often:**
> 
> 
> 100% reproducible when using the above STR.
> 
> ### Brave Version
> 
> **about:brave info:**
> 
> 
> > Brave: 0.19.147 
> > rev: f1b90a31643cad8f4d76a4f729939d4f303b9a00 
> > Muon: 4.7.6 
> > libchromiumcontent: 64.0.3282.119 
> > V8: 6.4.388.40 
> > Node.js: 7.9.0 
> > Update Channel: Release 
> > OS Platform: Microsoft Windows 
> > OS Release: 6.1.7601 
> > OS Architecture: x64
> 
> **Reproducible on current live release:**
> 
> 
> Yes, currently reproducible under `0.19.147` which is the current live release.
> 
> ### Additional Information
>

**Comment by emerick** [comment]
I believe that crash reporting is disabled by default; you need to enable it in chrome://settings/. I think that's why chrome://crashes is saying "Crash reporting is disabled".

**Comment by kjozwiak** [comment]
@emerick the main issue here is that manually or automatically sending reports on Win 7 doesn't work. Examples with STR:

**Manually sending reports:** - Fails under Win 7

* launch the latest version of b-c on a clean profile and create a crash report via `chrome://crash`
* open a new tab and view the crash under `chrome://crashes`
* click on `Send` and you'll notice that the crash will become "greyed" and will display `Crash report captured on Wednesday, September 26, 2018 at 4:44:22 PM (upload requested by user, not yet uploaded)`
* restart the browser and revisit `chrome://crashes` and you'll notice that the above report was never sent

**Automatically sending reports** - Fails under Win 7

* launch the latest version of b-c on a clean profile and create a crash via `chrome://crash`
* enable `Automatically send crash reports to Brave` via `chrome://settings`
* create a few crash reports using `chrome://crash`
* open a new tab and view the crash reports under `chrome://crashes`
* restart the browser (as many times as you want)

Both of these cases are working on macOS, Win 10 & Win 8.1.

**Comment by mkarolin** [comment]
The issue here appears to be the inability of crashpad to establish a secure connection with our crash reporting service.

The crash reporting service is configured to only accept TLS 1.2:
<pre>
$ nmap -Pn -p 443 --script=ssl-enum-ciphers laptop-updates.brave.com

Starting Nmap 7.60 ( https://nmap.org ) at 2019-01-08 20:53 EST
Nmap scan report for laptop-updates.brave.com (151.101.117.7)
Host is up (0.026s latency).

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|     compressors: 
|       NULL
|     cipher preference: server
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 2.03 seconds
</pre>

Windows 7 and 8.0, however, by default use TLS 1.0 (and SSL 3.0). To use TLS 1.1 or 1.2 an additional option needs to be set in WinHttp (WINHTTP_OPTION_SECURE_PROTOCOLS with WINHTTP_FLAG_SECURE_PROTOCOL_ALL | WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_1 | WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_2) in the code.

For comparison, Google's crash reporting endpoint, accepts TLS 1.0, 1.1, and 1.2 which is why there is no problem reporting Chrome's crashes.

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

![crashes](https://user-images.githubusercontent.com/34715963/53202281-64d74f00-3626-11e9-8edc-7d4feef6efab.png)

`Uploaded Crash Report ID 1de6626df5c368d3 (Local Crash ID: 34962795-112b-472a-979a-28b0cd05b091)`
`Uploaded Crash Report ID d3b405a93b5499b6 (Local Crash ID: b124c7df-c0ae-4b08-858b-f030c6eac6c2)`

Also verified by @LaurenWags and @kjozwiak on their Win 7 VMs.
