### ISSUE TITLE
[Feature Request] Mass removal of history entries

### ISSUE THREAD

**Issue by pitsi** [brave/brave-browser#11886]
## Description 
Please allow the mass removal of history entries. In my situation, github recently deleted the account of a user I used to read daily. Now, when I write "github" on brave's address bar, 90% of the suggestions below were from his repositories, issues, gists etc, so I wanted to remove all of them, since that they all lead to 404. There must be tens, if not hundreds, of pages that need to be deleted!

## Steps to Reproduce
   1. Open brave's history page (ctrl+h or menu button > history > history).
   2. Search for something, e.g "github pitsi" and notice brave filtering the results.
   3. Select some, by clicking each box on the left side, or all of them with ctrl+a.
4. Click on the small 3-dot menu on the right side of one entry and select "remove from history"

## Actual result:
Although more than one entry is selected, only one is deleted, the one that was selected in step 4 above.

## Expected result:
All the selected entries should be deleted.

## Reproduces how often: 
Easily and everytime.

## Brave version (brave://version info)
Brave	1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
Revision	a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{# 1864}

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Probably
- Can you reproduce this issue with the nightly channel? Probably

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No idea

## Miscellaneous Information:
Doing the same procedure for bookmarks (ctrl+shift+o or menu > bookmarks > boormark manager) works as it should! Select the ones you want, right click on one, select delete, all gone!

**Comment by pitsi** [comment]
A small correction on the above. This
## Other Additional Information:
Is the issue reproducible on the latest version of Chrome? **Yes**

I installed chrome, imported firefox's history there (because there is no option to import brave's) and it does the exact same thing, so the above is probably not a brave issue but a chromium one.

**Comment by mariospr** [comment]
This seems to be a Brave-specific issue now, because I can reproduce it in Brave 1.19.86, based on Chromium 88.0.4324.96, while I can't reproduce it in Chrome 88.0.4324.96 (Linux / Desktop in both cases).

To me it seems like an UI bug in Brave, because if you check what Chrome is doing, you'll see that the "Search History" entry widget above the results gets replaced with a `<n> selected   [Cancel] [Delete]` panel as soon as you start selecting items from the filtered list (identical to what happens when selecting items from an unfilitered list), allowing you to delete multiple items at once:
![chrome-history-removal](https://user-images.githubusercontent.com/2197259/105988938-af7a6500-60a0-11eb-866a-6f0f7727e84a.gif)

However, in the case of Brave that `<n> selected   [Cancel] [Delete]` panel is only shown when selecting history items from an unfiltered list. However, using the "Search history" entry widget to filter the history results and then starting to select items from the filtered list won't get the `<n> selected   [Cancel] [Delete]` panel showing up (i.e. only the "Search history" panel remains visible all the time),  making it impossible to remove multiple items at once:
![brave-history-removal](https://user-images.githubusercontent.com/2197259/105989100-ecdef280-60a0-11eb-8c42-59e7527c6640.gif)

@rebron @srirambv Seems like worth removing the `repros-on-chrome` and `Chromium/waiting upstream` tags?

**Comment by pitsi** [comment]
I can confirm that it is now doable in chrome. I tested it on chrome 89, which, as of today, is in the dev channel.

**Comment by pitsi** [comment]
The issue seems to have been fixed. I have no idea when it was fixed, but I just checked on brave 1.29 (based on chromium 93) and it works as it should, so I am closing this.
