### ISSUE TITLE
Add Crypto.com widget to the NTP

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#12074]
## Design
<img width="1196" alt="Screen Shot 2020-09-25 at 12 04 01 PM" src="https://user-images.githubusercontent.com/1199820/94289792-3ff43d80-ff27-11ea-828d-131302e2dbed.png">

https://www.figma.com/file/VcjAJx6ij0pb3zxASg30b5/Crypto.com-Widget?node-id=53%3A2

Specification for testing:
https://docs.google.com/document/d/1IILOjZjE6KxaV1IFQRBFF9cO2by0qgvJDiJMWrIVsf4/edit#heading=h.gzlrh4sgxpw1

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64-bit) 
-- | -- 
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}` | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}` | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | **`Linux`** / **`Windows 10 OS Version 1809 (Build 17763.1518)`** / **`macOS Version 10.15.7 (Build 19H2)`**

<details>
<summary>Verified Crypto.com widget is added to the stack by default on a clean profile</summary>

Linux | Windows | macOS
-- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/96992625-0f9dc000-1522-11eb-9374-f34b38bc759a.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/96991739-d0bb3a80-1520-11eb-9e64-4c350c25b8bf.png> | <img width=450 src=https://user-images.githubusercontent.com/17010094/96996324-92754980-1527-11eb-88f9-5e4b8a2fd8ad.png> 

</details>

<details>
<summary>Verified selecting `Crypto.com` widget shows opt-in state with BTC as default listed currency</summary>

Linux | Windows | macOS
-- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/96992680-22b09000-1522-11eb-88da-ebec6ac627e4.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/96992087-4aebbf00-1521-11eb-8bda-81a5fc3a5e9b.png> | <img width="450" src="https://user-images.githubusercontent.com/17010094/96996643-1c251700-1528-11eb-8c19-613ac978de6e.png">

</details>

<details>
<summary>Verified clicking on show price in opt-in view shows the current market price and 24hr % change for BTC</summary>

Linux | Windows | macOS
-- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/96992994-9488d980-1522-11eb-9446-bf641d84cd78.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/96992138-5e972580-1521-11eb-8175-901f939eaff7.png> | <img width="450" src="https://user-images.githubusercontent.com/17010094/96996696-38c14f00-1528-11eb-8e97-97749d077e68.png">
 
</details>

<details>
<summary>Verified clicking on `Buy` button or `Buy Bitcoin` button in opt-in view opens up the landing page in a new tab</summary>

```
https://auth.crypto.com/users/sign_up?utm_campaign=Brave%3AWW-en%3ATrading-Widget_MVP_InitialWidgetState_BuyButton_Top&utm_content=MVP_InitialWidgetState_BuyButton_Top&utm_medium=Trading+Widget&utm_source=Brave
```
</details>

<details>
<summary>Verified clicking on `View Crypto.com Markets` open up the top movers (assets view)</summary>

Linux | Windows | macOS
-- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/96993088-b5e9c580-1522-11eb-9cf0-c2cb9eb99b5e.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/96992195-6fe03200-1521-11eb-94fd-16434fde953a.png> | <img width="450" src="https://user-images.githubusercontent.com/17010094/96997250-53e08e80-1529-11eb-9aa2-aba2c95cf0c7.png"> 

</details>

<details>
<summary>Verified clicking on any of the listed tokens, opens up individual tokens 7d graph and lists 24hr volume in USD and supported trading pairs for individual asset</summary>

Linux | Windows | macOS
-- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/96993165-d44fc100-1522-11eb-8d75-06700f738c6a.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/96991958-20016b00-1521-11eb-81da-db7d5bdee3be.png> | <img width="450" src="https://user-images.githubusercontent.com/17010094/96997307-71adf380-1529-11eb-9846-212b7cb88989.png">

</details>

<details>
<summary>Verified clicking on any of the trading pairs on any of the asset opens a landing page in a new tab and loads </summary>

```
https://auth.crypto.com/users/sign_up?utm_campaign=Brave%3AWW-en%3ATrading-Widget_MVP_InitialWidgetState_BuyButton_Top&utm_content=MVP_InitialWidgetState_BuyButton_Top&utm_medium=Trading+Widget&utm_source=Brave
```
</details>

<details>
<summary>Verified `Crypto.com` widget can be disabled via either of the following ways</summary>

Linux (Widget menu) | Windows (Widget menu) | macOS (Widget menu)
-- | -- | -- 
<img width=400 src=https://user-images.githubusercontent.com/17010094/96993235-e9c4eb00-1522-11eb-8240-7f3e23995b7c.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/96991879-06602380-1521-11eb-89b3-262942607ccd.png> |  <img width="450" src="https://user-images.githubusercontent.com/17010094/96997410-a1f59200-1529-11eb-9cfd-39c0856f89ff.png">

Linux (Add cards in dashboard) | Windows (Add cards in dashboard) | macOS (Add cards in dashboard)
-- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/96993298-03fec900-1523-11eb-8f6e-85abffd9dafe.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/96991833-f34d5380-1520-11eb-88da-c393352b88a3.png> | <img width="450"  src="https://user-images.githubusercontent.com/17010094/96997450-b5a0f880-1529-11eb-812e-b95f1888ef2c.png">

Linux (New Tab page settings) | Windows (New Tab page settings) | macOS (New Tab page settings)
-- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/96993374-22fd5b00-1523-11eb-8407-958a4bd8a4db.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/96992051-3d363980-1521-11eb-9607-abf36de0bdf9.png> | <img width="450" src="https://user-images.githubusercontent.com/17010094/96997575-eaad4b00-1529-11eb-9709-ee15ed21c6f5.png">

</details>

- Verified widget retains the state between disable and enabled
  - If the widget is in opt-in state and then disabled, re-adding the widget still shows it in opt-in state
  - If the widget is already in the market view (tokens), disable and re-adding the widget doesn't go back to opt-in state but retains the market view

- Verified the price value is updated every 30 secs because of which value will always be a little off compared to the market value shown on website
![image](https://user-images.githubusercontent.com/17010094/95829198-db5e1e80-0d2d-11eb-9218-49428381d80e.png)

<details>
<summary>Verified when the network is disconnected/disrupted, balance and price chart is removed. Re-connecting to network updates the trade value and chart after 30sec</summary>

Linux | Windows | macOS
-- | -- | -- 
<img width=400 src=https://user-images.githubusercontent.com/17010094/96993517-5344f980-1523-11eb-9600-5eb4d7588a39.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/96992012-31e30e00-1521-11eb-95c6-466802f4c3c1.png> | <img width="450" src="https://user-images.githubusercontent.com/17010094/96997677-221bf780-152a-11eb-9d4b-4ab1cd97e4fc.png">

</details>

- Verified upgrading from an older build in supported regions widget is automatically added to the stack 
<details>
<summary>Verified for unsupported regions, there is no `Crypto.com` widget shown on a clean install or on upgrade</summary>

Linux (Japanese) | Windows (Nepali) | macOS (Vietnamese)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/96994472-acf9f380-1524-11eb-94f9-b3ea7c055be9.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/96994073-13cadd00-1524-11eb-88e6-6f6f5debce35.png> | <img width="450" src="https://user-images.githubusercontent.com/17010094/96997779-542d5980-152a-11eb-871b-3df531903467.png">

Linux (Add cards in dashboard) | Windows (Add cards in dashboard) | macOS (Add cards in dashboard)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/96994525-c0a55a00-1524-11eb-97bb-a8e484638987.png> |  <img width=300 src=https://user-images.githubusercontent.com/17010094/96994122-22b18f80-1524-11eb-8c49-5025944d7122.png> | <img width="450" src="https://user-images.githubusercontent.com/17010094/96997853-7626dc00-152a-11eb-9f6c-368e0595ec3a.png">

Linux (New Tab page settings) | Windows (New Tab page settings) | macOS (New Tab page settings)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/96994588-d6b31a80-1524-11eb-9e0f-15ab50e438e8.png>  |  <img width=300 src=https://user-images.githubusercontent.com/17010094/96994140-2e9d5180-1524-11eb-91e0-812aa8af4775.png> | <img width="450" src="https://user-images.githubusercontent.com/17010094/96997904-8e96f680-152a-11eb-8298-1fcc57a51d60.png">

</details>

- Verified widget is English only even for non-EN locales 
- Verified widget is not available on Private windows/Guest/Tor windows
- Verified clearing data doesn't reset widget state to opt-in state
