### ISSUE TITLE
Linux: Switching Desktop Environment forgets half the user data

### ISSUE THREAD

**Issue by ff2000** [brave/brave-browser#12088]
## Description 
I first started brave from within kde plasma. I imported my firefox data (history, bookmarks, form data, passwords).
Then I started to use it, filled new forms, added new passwords.
I today wanted to use it from within gnome-shell - same PC which means with the same user containing all the browser data as when using kde plasma.
But now brave doesnt know my github and gmail logins anymore! Having a look at the stored passwords it seems part of them are still there, I suspect it's from the point I imported them.
I then switched back to kde plasma. Passwords are there, again! But it seems the user data got messed up! Starting gmail it didn't know which email addresses were used (luckily with the form data it was easy to recover it). I halso got the "Cooky prompt", so there things were lost, too. Youtube still uses the black theme (which is not the default!), but it turned on autoplay again, so youtube cookies also got messed up. I didn't check any further, but I guess that a lot more user data is missing.

I switched Desktop Environments several times and it is reproducable.

**Comment by fmarier** [comment]
That odd behaviour is due to the fact that Brave/Chromium use different password/data stores depending on what is available in your session.

There is code to automatically detect and pick the most secure one, but you can also [specify the one you want to use on the command line](https://peter.sh/experiments/chromium-command-line-switches/#password-store), for example:

    brave-browser-stable --password-store=basic

or:

    brave-browser-stable --password-store=gnome

(the former being the [insecure fallback](https://source.chromium.org/chromium/chromium/src/+/master:components/os_crypt/os_crypt_posix.cc;l=40-44;drc=f8cd6a025322603d033e18c032c4bc25b53d853e)).

So while this implementation is unfortunate for people who switch between desktop environments, it looks like the behavior you are seeing is expected.
