### ISSUE TITLE
Consider Integrating Badger-Sett and DuckDuckGo's Tracker Radar 'Lists' into Brave's Shields

### ISSUE THREAD

**Issue by ACodingGenie** [brave/brave-browser#12120]
My original idea was to propose the implementation of a feature into Brave shields that works really well from an extension called “Privacy Badger” from Electronic Frontier Foundation. Privacy Badger locally learns to block trackers using the “three strikes and you’re out” technique as I’m sure some of y’all already know. There are times when Brave shields doesn’t block all the trackers on a page, including their cookies, but Badger will notice and block them. However, it turns out that this technique may impose security and privacy issues as pointed out by Google’s security team to EFF, Read more here: https://www.eff.org/deeplinks/2020/10/privacy-badger-changing-protect-you-better

So, my proposal now is to use EFF’s “Badger-set” tracker list (which is how Privacy Badger learns now) in conjunction with DuckDuckGo’s Privacy Radar, both found here: https://github.com/efforg/badger-sett and here: https://github.com/duckduckgo/tracker-radar 1 respectively, in order to strengthen and block invisible trackers across the web. Both 'lists" utilize web crawlers to find new tracking domains daily, and both are open-source. It would be nice to see perhaps a fork of the two projects and their capabilities implemented into Brave Shields somehow.

Edit Example: 
![image](https://user-images.githubusercontent.com/68975831/96454194-84eb5700-11e9-11eb-9517-f6fa79576163.png)
Note how Brave shields doesn't block anything but Privacy Badger blocks trackers. Adobe, CloudFlare, some of the big trackers are being blocked. The shield behavior is unchanged whether I disable or enable Privacy Badger. This is just one small example.

Some possible benefits as a result:
Increased privacy and security by blocking more invisible trackers and possible fingerprinting domains.
Increased performance (maybe) since you don’t have to install those extensions to see the same benefits.
Idk maybe there are more, y’all think :)

Thoughts about this?

**Comment by ACodingGenie** [comment]
:(

**Comment by bsclifton** [comment]
cc: @pes10k @diracdeltas

**Comment by pes10k** [comment]
@ACodingGenie i think there is some misunderstanding here.  For the examples you gave above, PrivacyBadger isn't blocking any requests; its just not sending cookies with those requests.  Brave already does a much stronger version of this.  Brave doesn't send cookies on any 3rd party requests.  So, in all the examples in your image, Brave is already doing what PrivacyBadger does.  Brave shields are also blocking 3p cookies on other requests too that PrivacyBadger doesn't target.

You might also find this twitter thread of interest.  The short of it though is that Brave already does everything PrivacyBadger does (and much more).  Adding PrivayBadger to Brave will not result in any privacy improvement (and it in fact might slightly reduce your privacy, since installing browser extensions can make your browser fingerprint more unique).

https://twitter.com/pes10k/status/1329242705927438336

Regarding DDG's lists, that list is generally much more conservative than what Brave uses (EasyList + EasyPrivacy + uBlock Origin's lists, among others), so there would be little to no privacy improvement to also use DDG's list (and there would be some performance lost from having to consider more rules, though tbh that performance difference is very likely not much).  Additionally, the EasyList / EasyPrivacy etc folks also pull in things from DDG's list, in the cases that DDG finds something new.

All that is to say that Brave already does everything PrivacyBadger does (and much more), blocks far more than DDG's list, and in the (uncommon) case that DDG's lists find something that the lists Brave users has missed, it'll be temporary until the EasyList + EasyPrivacy + etc folks pull the new rules in anyway.

Hope that helps explain Brave's choices, and why we're confident that pulling from PB and DDG would not improve privacy in Brave.  Thanks for taking the time to file the issue and follow up!

**Comment by ACodingGenie** [comment]
Makes sense brother. Shanks!
