### ISSUE TITLE
Sync breaks (I get a new code) after I close the browser for a while

### ISSUE THREAD

**Issue by cyjambo** [brave/brave-browser#12186]
![sync bug](https://user-images.githubusercontent.com/1847407/96331454-9d2e6b00-105d-11eb-8280-2e8e717f6670.PNG)

## Description 

I am using profiles. I have 3 profiles and I am using Sync for all of them. Unfortunately the sync code changes after a while. I thought it was after a laptop reboot but two days ago I just closed two browser windows (with two different profiles) and when I now open them again my sync is gone. This is a problem because all my saved things are gone (passwords, bookmarks, etc..).
After this happens it is not possible to leave the sync chain, if I click on that button nothing happens.
The only way to solve the issue is to delete the existing profile and create a new profile with the old sync code. This then works until the next time the laptop is rebooted or after I don't use the browser for a while.
This issue doesn't seem to happen on another machine with this same sync chain.

The sync chain contains this problematic machine multiple times, so it seems it's always added new to the sycn chain (see attached screenshot, "jambo-laptop" is there multiple times, each time I add it back to the sync chain).

I am using multiple VPN connections, not sure if this has anything to do with the problem.

## Steps to Reproduce

   1. Create a new profile
   2. Start a sync chain
   3. On another machine create a new profile and join the sync chain from before
   4. After restarting the second machine or just closing the browser and not using it for a while the issue should appear.
## Actual result:

The actual results vary, it's not easy to reproduce on purpose but it happens all the time.

## Expected result:
The sync code should never change.

## Reproduces how often: 

I am now constantly having this issue, pretty much every time I open the browser. I am having to leave it open an never close it otherwise the problem happens.

## Brave version (brave://version info)

Brave | 1.15.75 Chromium: 86.0.4240.99 (Hivatalos verzió) (64 bites)
-- | --
Ellenőrzés | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Windows 10 OS Version 2004 (Build 19041.572)

Hungarian OS version.

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Did not try
- Can you reproduce this issue with the dev channel?
Did not try
- Can you reproduce this issue with the nightly channel?
Did not try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
Yes

## Miscellaneous Information:

The problem is not too easy to reproduce, it only happens on my laptop. I don't get why it doesn't happen on another machine with the same sync code (the sync code on the other machine is alway ok).

BTW this happens to all profiles on this laptop.

**Comment by Ritsket** [comment]
Hello Cyjambo,
I think your problem is caused by a WIN10 issue.
A bug in Windows 10 can create a conflict with scheduled tasks that are configured in a certain way.
This also causes Brave to flush all it's passwords and sync settings each time these tasks are executed.
The problem  is not yet solved but there is a workaround. 

Run the following command:
**Get-ScheduledTask | foreach { If (([xml](Export-ScheduledTask -TaskName $_.TaskName -TaskPath $_.TaskPath)).GetElementsByTagName("LogonType").'#text' -eq "S4U") { $_.TaskName } }** 
in Windows PowerShell. 

This will produce a list of one or more scheduled tasks that cause this conflict.
Disable all the listed tasks in the Windows Task Scheduler and the problem is gone.

You can also check this link:
https://www.forbes.com/sites/daveywinder/2020/11/14/microsoft-confirms-serious-windows-10-password-problem-heres-the-5-step-fix/?sh=4ed0bf3a5fcc

**Comment by cyjambo** [comment]
Thanks for the suggestion Ritsket, I'll check if this works and let you know.

**Comment by cyjambo** [comment]
Hi everyone,

Happy to share that this helped. I had to restart my machine twice but after that no more issues :) Thanks Ritsket for the suggestion, I can finally use Brave again and get rid of Chrome :)
