### ISSUE TITLE
update appearance section in settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1222]
## Description 

- [ ] Style Appearance section with Brave styling.
- [ ] Keep label section 'Appearance' and sidebar navigation label 'Appearance'.
- [ ] Create 'Themes' section at the top with drop down display for light and dark themes. [This is currently labeled 'Brave colors']. 
- [ ] Drop down list for themes should display 'Light', and 'Dark'
- [ ] Remove 'Theme' section that points to Chrome Web Store.
- [ ] Add Address bar size section label 'Address bar size' with drop down menu with these two options 1) default to 'Centered' and 2) 'Full width'
- [ ] No change other than styling for Show home button, Show bookmarks, Font size, Customize fonts, and Page zoom.
- [ ] Replace text 'Pressing Tab on a webpage highlights links, as well as form fields' to 'Highlight links and form fields by pressing tabs'

## Design
![screen shot 2018-10-03 at 1 48 13 pm](https://user-images.githubusercontent.com/5951041/46438584-2393e080-c713-11e8-8978-32c32ddac023.png)

I'll update the mock with appropriate labels currently labeled 'User interface colors' and 'Url Bar style' but should be 'Themes' and 'Address bar size'

**Comment by rebron** [comment]
@rossmoody and @petemill. Mock has the Themes section pointer to Chrome Web Store removed. Possibly need to special case if a user installs a theme from the Chrome Web Store, having the setting show in order to 'Reset to Default'. I'm inclined to hide and revisit post 1.0 to decide how to support CWS themes.
<img width="714" alt="screen shot 2018-09-20 at 9 40 26 pm" src="https://user-images.githubusercontent.com/5951041/45860758-cf096200-bd1d-11e8-8c12-530231cda30d.png">

**Comment by petemill** [comment]
Not sure we can remove the 'theme' section here @rebron - this is the only way to remove a theme if someone installs a theme from the extensions store. This is why we differentiated the title Brave Colors with Themes - so that you can choose a theme from the store and have the rest of the non-theme colors be light or dark.

We may also want to remove the option for Dark / Light considering that Chromium has followed many other popular apps patterns by supporting OS-specified light / dark mode. Though we can revisit that decision when we implement chromium's dark mode properly in Brave, and see how easy it is to keep both mechanisms (OS-provided as well as user-provided settings).

**Comment by rebron** [comment]
@rossmoody we need an updated mock, this one is a bit stale especially since we introduced Rewards button setting and chromium added the warning with command+Q.

**Comment by rebron** [comment]
This issue is stale. Closing in favor of https://github.com/brave/brave-browser/issues/4508
