### ISSUE TITLE
Browsing history appears in address bar

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#12292]
## Description 

Today I noticed that after a Google search, whatever I searched for appears in the address bar after I open a new tab and click on the address bar. Here is a community thread: https://community.brave.com/t/unable-to-turn-off-search-history-in-address-bar/172626

## Steps to Reproduce

   1.  Search something on Google
   2.  Open a new tab
   3.  Click the address bar
## Actual result:

Your search will appear, regardless of your settings.

## Expected result:
Your search shouldn't appear, unless you have enabled the autocomplete options. That's how it was until the latest update.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Windows 7 Service Pack 1 (Build 7601)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

https://community.brave.com/t/unable-to-turn-off-search-history-in-address-bar/172626

**Comment by srirambv** [comment]
Related to #12188 on Android. Issue seems across the board

cc: @bsclifton @SergeyZhukovsky @jumde @simonhong

**Comment by rebron** [comment]
This is related to history results in general showing up in the url bar and not necessarily related to search history and it's independent of search engine preference. We do have a setting to fully to turn off autocomplete but not one to turn off pulling from history.

The other search autocomplete setting that we have default off isn't related to this because that pulls autocomplete results from a service (live results as if performing a search) and not pulling from history.

**Comment by manikandancode** [comment]
Really Painful!

Need to use private mode or clear browsing history brave://settings/clearBrowserData every time

**Comment by BobT36** [comment]
I'm amazed this hasn't been fixed yet, in a so-called privacy browser..

This shows up only on the New Tab page, on clicking in the Address bar. Bang, all my recent searches (even if made directly through Google.com) appear in the drop-down! See how dangerous this could be?
![image](https://user-images.githubusercontent.com/14024619/126725853-5467751f-e509-424f-9a93-fd252650facd.png)
Does NOT do this on any page other than New Tab. So this is obviously an unintended issue. 

Someone's wife or husband is going to stab them one day, due to them walking passed while the other accidentally clicks in the address bar on a new tab page...

Detailed here: https://community.brave.com/t/stop-new-tab-page-displaying-google-search-history/170154

**Comment by BobT36** [comment]
GF sat next to me while I was going to show her something, of course as I pulled up the new tab page and began typing, it displayed my search history for engagement stuff in the pop-down. Fortunately, I think she was looking away at the time.

Come on guys, shouldn't this one be upped in the priority list a bit? This is supposed to be a PRIVACY browser!

**Comment by reddyshyam** [comment]
Yes, this needs to be addressed guys. Please bump up the priority. 🙏

**Comment by bhanuunrivalled** [comment]
quitting  brave till this is solved

**Comment by LeuschkeTressa** [comment]
@rebron @bsclifton @bbondy @mrose17, would it be possible with a comment on why a privacy-breaching bug like this has not been fixed in one year, and why it has been given a priority of P4?

A few of us are quiet invested in Brave and are advocating it to friends and our networks. You are of course free to prioritize the way you wish, but I think a few of us feel that the non-action on this issue isn't in line with our perception of how the Brave team is communicating around its privacy focus. Therefore it would be great if you could clarify your position so we can make an informed decision about whether to continue to use and advocate for Brave.

The _existence_ of this bug is worse enough for Braves privacy credibility in my eyes, but worse still is the inability to fix it for one year and the P4 priority.

(Except for this bug, I do love Brave. However, for me, this is about credibility.)

There are at least three threads on the Brave forums on this:
https://community.brave.com/t/stop-new-tab-page-displaying-google-search-history/170154
https://community.brave.com/t/unable-to-turn-off-search-history-in-address-bar/172626
https://community.brave.com/t/new-tab-page-still-displaying-google-search-history/250132

...and at least seven threads on Reddit:
https://www.reddit.com/r/brave_browser/comments/kou1v0/how_to_prevent_brave_from_saving_my_google/
https://www.reddit.com/r/brave_browser/comments/qdawbl/is_there_a_way_to_keep_brave_from_saving_my/
https://www.reddit.com/r/brave_browser/comments/oixmuf/how_to_stop_brave_from_saving_things_i_searched/
https://www.reddit.com/r/brave_browser/comments/elgz3l/is_there_a_way_to_stop_search_history_recording/
https://www.reddit.com/r/brave_browser/comments/euiofy/prevent_brave_from_storing_history/
https://www.reddit.com/r/brave_browser/comments/jfnnp3/brave_has_started_saving_and_showing_all_previous/
https://www.reddit.com/r/brave_browser/comments/qhtsm4/what_is_braves_problem_with_saving_brave_search/

Some excerpts from the threads above and this GitHub issue:

> Brave as a Privacy Browser really needs to address this one. 

> Unacceptable for a so-called "privacy-protecting" browser

> Yeah, this is my only real sticking point with the browser so far.

> Brave as a Privacy Browser really needs to address this one. 

> I absolutely abhor this feature for the case that another individual may use my browser.

> What happened to PRIVACY, [...] Started using Brave as an alternative to Chrome but it’s just as invasive/busted. Will be looking for another browser - one where I can actually CONTROL what I want it to do. Apologies for the rant, but enough is enough.

> Every update for this browser seems to bring a new, strange erosion of privacy and/or new defaults that no one wants to be opted in to. Constantly disrespecting your own ethos is an awful look.

> This is very dodgy for a “Privacy Browser”

> As mentioned for a “privacy browser”, this should be quite high up on the list of things to fix.

> I'm amazed this hasn't been fixed yet, in a so-called privacy browser..

> Come on guys, shouldn't this one be upped in the priority list a bit? This is supposed to be a PRIVACY browser!

> Yes, this needs to be addressed guys. Please bump up the priority. 

> quitting brave till this is solved

**Comment by akhilpsoman2010** [comment]
This has not been fixed even after one year. For a browser invested in privacy, is this the best they can offer?

**Comment by manikandancode** [comment]
Brave's primary focus is now crypto only and shifting away from privacy, security and other features. for proof just check Brave V1.35.100 (Feb 2, 2022) release note 

https://brave.com/latest/

**Comment by reddyshyam** [comment]
It has always been the case as far as I can remember. All that's fixed is wallet related issues and nothing more.

**Comment by anilakkose** [comment]
I have been using **Cloak** plugin since the issue marked as P4 priorty. Dropping the link below.

https://chrome.google.com/webstore/detail/cloak/pcclknndfjjmcojfkjdnmapigogbpfhn

**Comment by BobT36** [comment]
Over the last few days, it's now showing NO search history on the new tab page. 
Has there been an update or something to fix this issue? Couldn't see anything in the patch notes.

Now fixed for everyone else too?

**Comment by prateek-parashar** [comment]
Nah, not fixed, still face the same problem, and it's really frustrating.

**Comment by BobT36** [comment]
Hmm how strange. I'm on: [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)](https://brave.com/latest/)
Haven't changed a thing in my settings, and the New Tab window (as well as others) shows NO search history pop-down now. As expected / wanted.

**Comment by git-webmaster** [comment]
> I'm on: [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)](https://brave.com/latest/), NO search history pop-down now. As expected / wanted.

I am using the exact same version, and i still have that problem. Win10x64, btw.
Also i made a switch to Brave few days ago and was shocked that this issue even exists.

Since it was not fixed in **487 days** as of today, it is clearly required to be a higher priority, in my opinion.

**Comment by BobT36** [comment]
> Hmm how strange. I'm on: [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)](https://brave.com/latest/) Haven't changed a thing in my settings, and the New Tab window (as well as others) shows NO search history pop-down now. As expected / wanted.

So, turns out this ISN'T fixed. As of today it's now back displaying my search history in the new tab drop-down again, for all to see. What changed today?

**Comment by BobT36** [comment]
And now (as of yesterday or the day before?) it's NOT showing again. I had to manually clear a few old entries though, but it's now not showing new searches at least. 

Brave devs, are you doing something here or what? I haven't changed any of my settings.

**Comment by Excigma** [comment]
Could it also be considered to add toggles for finer control? For example, to disable suggestions from browsing history instead of just search history? I'm aware that this isn't completely exactly what [Tonev](https://github.com/Tonev) and other people are asking for, but I believe it is relevant.

FWIW Mozilla Firefox has implemented this at (about:preferences#privacy) like:
![image](https://user-images.githubusercontent.com/30280397/165505837-406c7275-55a4-45ee-a336-29e66108454a.png)

**Comment by BobT36** [comment]
More configuration and customisation is great! Just please no more of this: 
![image](https://user-images.githubusercontent.com/14024619/165590461-d8aa2b41-d0b3-41bb-a17a-26d94473ec21.png)
(It's been fine since my last message).

**Comment by Excigma** [comment]
> Not sure if we should differentiate search history against all other browsing history and if that difference would make sense to people.

Interestingly, most people only bring up search history and not general browsing history in the posts that [LeuschkeTressa](https://github.com/LeuschkeTressa) sent above. I'm not sure if general browsing history is what they mean? As [BobT36](https://github.com/BobT36) mentioned, "more configuration and customisation is great!", following this, it would be nice to have separate toggles for search history and browsing history.

That said, most other browsers don't implement this (but having extra features sets things apart!), I'm not sure how difficult it would be to implement/maintain and if many people would actually utilise it.

**Comment by Tonev** [comment]
@rebron 

Updated. Let me know if you would like further updates, will apply upon request 👍

**Comment by waldyrious** [comment]
> Not sure if we should differentiate search history against all other browsing history

I definitely would want to keep actually visited URLs in my autocomplete dropdown (manually removable via <kbd>Shift</kbd>+<kbd>Del</kbd>), as opposed to previously searched terms. That has been specifically asked for in #9926, by the way.

**Comment by BobT36** [comment]
Sure, just make sure there's an option to turn that off. 
A privacy browser should NOT expose it's user's browsing habits with no way to disable that. 
(Currently the history pop-down is NOT showing on New tabs anymore still. Hope it stays that way unless it's optional).

**Comment by LeuschkeTressa** [comment]
Great to see that things are moving on this one!
