### ISSUE TITLE
Origin isolation for ipfs and ipns

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#12367]
Test page:
ipfs://bafkreifik2tbj5esf74sf2qwft2x3vuxaqmthwh3d2qx6abpcroirqpt7i

We currently expose values for window.location of:

```
href = http://127.0.0.1:48080/ipfs/bafkreifik2tbj5esf74sf2qwft2x3vuxaqmthwh3d2qx6abpcroirqpt7i
origin= http://127.0.0.1:48080
protocol= http:
For reference, expected values for ipfs://{cid} URLs are:
```

I think we should ideally expose like so:
```
href = ipfs://bafyfoobar/origin-check.html
origin= ipfs://bafyfoobar
protocol= ipfs:
```

**Comment by lidel** [comment]
gateway loaded via raw IP does not support subdomains (can't have subdomain on IP), use `localhost`  name instead, you will get redirected to proper Origin:

http://localhost:48080/ipfs/bafkreifik2tbj5esf74sf2qwft2x3vuxaqmthwh3d2qx6abpcroirqpt7i →  http://bafkreifik2tbj5esf74sf2qwft2x3vuxaqmthwh3d2qx6abpcroirqpt7i.ipfs.localhost:48080

**Comment by lidel** [comment]
oh, and if you find yourself unable to resolve `*.localhost` on some OSes, use IPFS gateway port as HTTP proxy – that will remove the need for DNS lookup (go-ipfs will read Host header and extract conten root)

**Comment by diracdeltas** [comment]
@lidel i'm not sure that using `({cid}.ipfs.localhost:48080` as the origin fully solves the security issue since subdomains of a domain can share cookies with each other. 

the public suffix list addresses this, but `ipfs.localhost` is not on the list: https://publicsuffix.org/list/public_suffix_list.dat. we could do a chromium patch to add it to the list in Brave.

another way might be to create a new TLD (.ipfs for instance), similar to how Tor windows have .onion

**Comment by lidel** [comment]
@diracdeltas in practice neither `ipfs.localhost:48080` nor `localhost:48080` can be used for loading and executing  arbitrary JS because go-ipfs will redirect root domain to the proper subdomain. iiuc not an issue, but yes, adding it to the public suffix list would not hurt and protect against any future bugs/regressions in go-ipfs (our public gateway at `dweb.link` is already on the list).

Doing the TLD is also a possibility, and quite easy to set up actually.
We can't use `dweb.link` name because of HSTS in production, but `dweb` alone makes a nice TLS-free TLD.

First, enable subdomain gateway for `dweb` hostname:

```console
$ ipfs config --json Gateway.PublicGateways '{                                                                                                                                                                 
    "dweb": {                                                                                 
      "UseSubdomains": true,
      "Paths": ["/ipfs", "/ipns"]
    }
  }'
```

Then, set up gateway port (`48080`) as HTTP proxy for `*.dweb`. That is all we need to have this virtual TLD.

To illustrate:

- `bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am` is a text file saying `hello`
-  http://dweb/ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am will redirect to http://bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am.ipfs.dweb


```
$ curl -x http://127.0.0.1:48080 -sD - "http://dweb/ipfs/bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am" | grep Location
Location: http://bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am.ipfs.dweb/
```

```console
$ curl -x http://127.0.0.1:48080 -s "http://bafkreicysg23kiwv34eg2d7qweipxwosdo2py4ldv42nbauguluen5v6am.ipfs.dweb"
hello
```

It also looks pretty nice.

**Comment by diracdeltas** [comment]
> in practice neither `ipfs.localhost:48080` nor `localhost:48080` can be used for loading and executing arbitrary JS because go-ipfs will redirect root domain to the proper subdomain

I'm not sure what this means. IIUC any HTML page can be served over IPFS, and Brave will render it and execute the JS in the file when it loads it. 

let's say alice sets up `ipfs://alice` and bob sets up `ipfs://bob`. alice's HTML page has a form which collects some private value from the user (like a password) and then runs some javascript which sets `document.cookie` to be that private value. alice can of course set a cookie that is only scoped to `domain=alice.ipfs.localhost`, but she can also set a cookie that is scoped to `domain=ipfs.localhost`. my understanding is that in the latter case, other subdomains can read the cookie [1]. 

bob's HTML page reads `document.cookie` and sends it via an XHR to bob's server. now bob knows the private value that the user entered on alice's page.

[1] https://serverfault.com/questions/153409/can-subdomain-example-com-set-a-cookie-that-can-be-read-by-example-com

**Comment by lidel** [comment]
@diracdeltas I meant that JS can only execute from `{cid}.ipfs.localhost:48080`, which means cookies/storage/etc are bound to that specific origin by default.

Indeed, if `.ipfs.localhost` is not marked as Public Suffix a `{cid}.ipfs.localhost` website can choose to save a cookie to the parent origin at `ipfs.localhost`, but "leaking private data" is not possible because cookie sharing requires both `alice.ipfs.locahost` and `bob.ipfs.localhost` to mutually agree that they will store cookies on  `ipfs.localhost`. 

IIUC there is no way for `bob` to "force" `alice` to save cookies  to the parent domain, so no surface for malicious activity. 

(but yes, if we use origins based on those hostnames, we should set up Public Suffix, just to be safe)

-----

Anyway, my understanding of available options is: 

- The ideal scenario is if  a page loaded from `ipfs://bafkqaaa`  has `origin`  and other attributes on `window.location` and `document` based on the `ipfs://bafkqaaa` URI (just like @bbondy suggested in https://github.com/brave/brave-browser/issues/12367#issue-731669904).
  - This provides unique Origin per content root, but may have some unexpected side-effects, because browser code may not account for scheme other than `https?`.  (I am not familiar with Chromium internals, this is just a hunch)

- If keeping the URI as Origin is not possible, and we need to use the `http://` URLs in `window.location` and `document`, then we need to use `localhost` instead of IP + manually mark `ipns.localhost:48080` and `ipfs.localhost:48080` as Public Suffix
  - This also provides unique Origin per content root, but has some downsides:
    - `window.location.origin` is `bafkqaaa.ipfs.localhost:8080` instead of `ipfs://bafkqaaa` 
    - If gateway port ever changes, origin of every IPFS site will change, and users will lose old cookies/storage. I don't believe it is a big deal (port change won't happen for most of the users), but mentioning here for completeness.
     - Workaround is to use `.dweb` TLD described in https://github.com/brave/brave-browser/issues/12367#issuecomment-719051174. 
       When set up, it will produces stable origins (`http://bafkqaaa.ipfs.dweb` instead of  `http://bafkqaaa.ipfs.localhost:8080`) but we do this, need to mark `*.ipfs.dweb` and `*.ipns.dweb` as both Public Suffix and Secure Context (`localhost` was SC already, `dweb` is not).

**Comment by diracdeltas** [comment]
> IIUC there is no way for `bob` to "force" `alice` to save cookies to the parent domain, so no surface for malicious activity.

I would instead phrase this as "alice can prevent malicious cross-domain activity if she is careful." Web developers are generally not used to an environment in which their app runs in the same parent domain as another app, so they may not be aware of all the security risks. For instance:

1. SameSite cookie rules would consider Alice and Bob's subdomains as SameSite. This may not be obvious to developers when their apps get deployed on IPFS. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
2. Let's say Alice writes a web app deployed on `www.alice.com` which uses cookies for the base domain `alice.com` (which is determined at runtime, for instance using window.location.origin). If she deploys this to IPFS without changing the code, then Bob can read and write to her cookies.

If we use regular hostnames for the origins, it's a security-blocking issue to consider `ipfs.localhost` a public suffix. If we instead use `ipfs://bafkqaaa`, we should make these are recognized as unique origins internally by Brave. We may also need to do some changes to recognize `ipfs:` as a scheme which behaves like HTTP, for instance:

1. all the stuff in https://source.chromium.org/chromium/chromium/src/+/master:url/url_util.cc;l=32-101;drc=5b8933e94139a0ab5be46141666fdfcce0f624f6
2. making sure it's a scheme which extension webRequests have access to (https://developer.chrome.com/extensions/webRequest)

**Comment by yrliou** [comment]
test plan specified in linked https://github.com/brave/brave-core/pull/7046

**Comment by nschwermann** [comment]
What does this message even mean? What is wrong with my gateway?
