### ISSUE TITLE
enabling flag for enhanced security does not enable it 

### ISSUE THREAD

**Issue by joejoejo** [brave/brave-browser#12373]
Description
Enhanced security is not listed in the safe browsing section of the Privacy and Security section of the settings after enabling it.

Steps to reproduce
   1. Enter chrome://flags/#safe-browsing-security-section-ui-android
   2. Enable it
   3. Enter chrome://flags/#safe-browsing-enhanced-protection-android
   4. enable it
   5. Restart brave
   6. Go to settings
   7. Click on Privacy and Security
   8. Click on Safe Browsing

Actual result
![Screenshot_20201028-175955](https://user-images.githubusercontent.com/5640119/97502033-b631f880-1948-11eb-981c-a096499f1545.png)

Expected result
![Screenshot_20201028-175950](https://user-images.githubusercontent.com/5640119/97502008-a7e3dc80-1948-11eb-9341-4d2b0b4a81fe.png)

Issue reproduces how often
all the time

Version/Channel Information:
- Can you reproduce this issue with the current Play Store version?  Have a newer version of the release channel than on the play store
- Can you reproduce this issue with the current Play Store Beta version? Did not test
- Can you reproduce this issue with the current Play Store Nightly version? Did not test

Device details
   - Install type (ARM, x86): arm64
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 11
   
Brave version
     1.16.68

Website problems only
- Does the issue resolve itself when disabling Brave Shields?  This does not apply
- Does the issue resolve itself when disabling Brave Rewards? This does not apply
- Is the issue reproducible on the latest version of Chrome? No, enabling the flag in chrome for Android does what it is intended to do

Additional information
https://www.androidpolice.com/2020/10/28/surf-the-web-more-securely-on-chrome-for-android-by-activating-enhanced-safe-browsing/

**Comment by diracdeltas** [comment]
cc @jumde @fmarier

**Comment by fmarier** [comment]
This is actually working as intended. We don't enable the extended protection mode for Safe Browsing because it requires sending full URLs to Google.

Also the password breach protection requires that a user signs into Chrome with their Google Accounts, something that Brave doesn't offer. We are hoping to offer a similar feature without the Google Account requirement, see #12001 .

**Comment by JnTon** [comment]
> This is actually working as intended. We don't enable the extended protection mode for Safe Browsing because it requires sending full URLs to Google.

Why not give users the freedom to choose? There are some users who are just fine with giving Google this kind of data to reduce their risk of stumbling on malicious website/files, but they want to enjoy all the other features and benefits that Brave offers (this feature has been requested on Brave's forum too).

Perhaps a banner could be added warning that some data will be sent to Google, so that the user can consciously accept or reject this trade-off.

@fmarier @bsclifton

**Comment by fmarier** [comment]
@JnTon I agree that it would be a reasonable option to offer to Brave users (default OFF like in Chrome), but this is not currently something that Google offers to users of third-party browsers. So right now, it's not an option we can offer.
