### ISSUE TITLE
Hulu doesn't work in brave-core

### ISSUE THREAD

**Issue by tylerl0706** [brave/brave-browser#1242]
## Test Plan
See https://github.com/brave/brave-core/pull/498

## Description 

I can't seem to load any videos on Hulu in Brave Core but I can do it in Chrome.

## Steps to Reproduce

   1. Login to Hulu
   2. Load a video

## Actual result:

![image](https://user-images.githubusercontent.com/2644648/45913474-0ac92800-be01-11e8-95e4-7ae8f9611403.png)

## Expected result:
The video loads.

## Reproduces how often: 
Easily reproduced

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X

### Reproducible on current release:

Not sure

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by bsclifton** [comment]
Widevine is manually installable via a work-around (we're still working on a better integration) and @mkarolin verified that hulu.com does work once Widevine is installed

The problem is: hulu.com should be showing a notification that Widevine is required. It should look something like this:
![image](https://user-images.githubusercontent.com/4733304/46036212-d16f1180-c0b9-11e8-8ceb-1cc8c96835d9.png)

This should be easily fixable by adding `hulu.com` to the list of exceptions here:
https://github.com/brave/brave-core/blob/fcefe04006057f53e986bcd028846398077db8ac/common/shield_exceptions.cc#L125-L139

**Comment by kjozwiak** [comment]
@bsclifton confirmed that `b-c` doesn't display the above notification via the URL when visiting `hulu.com`. I tried with @mihaiplesa's custom build that I used to check Netflix and used the latest `0.55.6 Chromium: 70.0.3538.22`.

Unfortunately I can't check if the work around works due to `hulu.com` being an American service which requires an CC from the US :( I tried signing up for a trial account but they require a US CC.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

Using test plan steps 1-6, I was able to play a video without the manual install described in steps 7-10.

**Comment by tylerl0706** [comment]
confirmed 🎉

**Comment by kjozwiak** [comment]
@tylerl0706 awesome, appreciate the check/confirmation! Mind sharing which platform you used to verify?
