### ISSUE TITLE
incognito_used_timestamp is not recorded correctly

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#12452]

**Comment by simonhong** [comment]
FYI - `Issues only get assigned to a milestone once they are completed and merged into that milestone.`
https://github.com/brave/brave-browser/wiki/Triage-Guidelines

**Comment by GeetaSarvadnya** [comment]
@iefremov Could you please link the test plan in the issue?

**Comment by iefremov** [comment]
@GeetaSarvadnya done, thanks for reminding me

**Comment by GeetaSarvadnya** [comment]
@francois Thanks for linking the test plan in the issue https://github.com/brave/brave-browser/issues/12452
I would need few clarifications apart from the test plan, please correct me if I am wrong.
1. Is this question is not added in the P3A wiki https://github.com/brave/brave-browser/wiki/P3A - do we need to just verify the stats `incognito_used_timestamp` display along with timestamp? I mean why other parameters not shown like P3A metrics like Flag, timestamp, value? how do we know whether value is sent to server or not, if there is no flag value True
2. Stats `incognito_used_timestamp` is displayed under  core_p3a_metrics  in local state file not under P3A what is the difference between normal `P3A metric` and `core_p3a_metrics`
3. The timestamp of the `metric incognito_used_timestamp` returning value like `13250691366672711` `13250691719052242` - If I check these values in https://www.epochconverter.com/ which says 50 yrs ago instead of current timestamp?

**Comment by iefremov** [comment]
@GeetaSarvadnya 
1. Sorry I probably confused use - `incognito_used_timestamp` is not a metric, but rather a value that is used to generate other metric (i.e. Brave.Core.LastTimeIncognitoUsed). So there are no other parameters.
2.  This comes from the previous answer - this is not a metric, but just an utility value
3. this is "microsoft" timestamp - can be checked at https://www.epochconverter.com/ldap (enter a value and add an extra trailing zero)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.68 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the description from https://github.com/brave/brave-browser/issues/12452#issue-734310145
- Logged https://github.com/brave/brave-browser/issues/12990
- Verified that the `incognito_used_timestamp` value is updated when a PT is opened

```
   "core_p3a_metrics": {
      "incognito_used_timestamp": "13251385145264325"
   },
```
