### ISSUE TITLE
[Desktop] Implement rewards onboarding tour

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#12459]
Additional requirements:

- For existing rewards users that have not been presented with the onboarding experience, there should be a card or other UI element that allows them to initiate the tour.
- Modals that do not require user input should be closed when the user clicks on the overlay background.

**Comment by LaurenWags** [comment]
Note for @brave/legacy_qa when testing this one, check a couple languages for the onboarding text/slides.

**Comment by LaurenWags** [comment]
Pending clarifications on onboarding tour slide content - https://bravesoftware.slack.com/archives/CKNHM4RTK/p1611867123012400?thread_ts=1611709603.005500&cid=CKNHM4RTK

Labeling as `QA/Blocked` for now

**Comment by LaurenWags** [comment]
Verification in progress using

```
Brave	1.20.96 Chromium: 88.0.4324.96 (Official Build) beta (x86_64)
Revision	68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS	macOS Version 10.15.7 (Build 19H15)
```

Verified test plan from https://github.com/brave/brave-core/pull/7170
Verified using designs from https://www.figma.com/file/0dbMYs8Wp8W3RgrG1yTdki/RE-1.0?node-id=2236%3A30931


<details>
<summary>Join Rewards from brave://welcome</summary>

- Confirmed able to join Rewards via brave://welcome. 
- Confirmed when joining this way, a new tab is opened with brave://rewards and the wide view of the onboarding tour is displayed. 
- Confirmed able to navigate through the tour slides.
- Confirmed selecting "Skip" takes you directly to the final slide.
- Confirmed "Done" closes the tour.
- Confirmed clicking on the "x" closes the tour.

</details>

<details>
<summary>Join Rewards from brave://rewards</summary>

- Confirmed brave://rewards does not show opt-in modal, but rather is a box displayed in place of the individual panels/settings. Note, text does not match figma designs exactly, logged https://github.com/brave/brave-browser/issues/13896:

<img width="1264" alt="rewards page pre-opt-in" src="https://user-images.githubusercontent.com/28145373/106644660-5fe0e100-6559-11eb-858c-031ced37d559.png">

- Confirmed clicking on "Terms of Service" opened a new tab navigated to https://basicattentiontoken.org/user-terms-of-service/.
- Confirmed clicking on "Privacy Policy" opened a new tab navigated to https://brave.com/privacy/browser/#rewards.
- Confirmed clicking on "learn more" opened a new tab navigated to https://basicattentiontoken.org/.
- Confirmed clicking on "Take a quick tour" opened the wide view of the onboarding tour.
- Confirmed able to navigate through the tour.
- Confirmed selecting "Skip" closed the onboarding tour (expected per the PR since I did not opt-in to Rewards yet).
- Confirmed clicking on the "x" closed the onboarding tour.
- Confirmed clicking on "Done" closed the onboarding tour.

- Confirmed clicking on "Start using Brave Rewards" button the wide view of the onboarding tour is displayed:

<img width="1264" alt="rewards page post-opt-in" src="https://user-images.githubusercontent.com/28145373/106644677-64a59500-6559-11eb-816d-1a993d41f237.png">

- Confirmed able to navigate through the tour.
- Confirmed selecting "Skip" takes you to the last slide (expected since I opted into Rewards).
- Confirmed clicking on the "x" closed the onboarding tour.
- Confirmed clicking on "Done" closed the onboarding tour.
- Confirmed both Ads and AC were enabled after joining.
- Confirmed able to see all expected panes on brave://rewards

- Confirmed if Ads are disabled, a rewards tour promo link is displayed:

<img width="1262" alt="Screen Shot 2021-02-02 at 1 03 47 PM" src="https://user-images.githubusercontent.com/28145373/106644690-68391c00-6559-11eb-9210-b8c860280cf0.png">

- Confirmed reloading the page after disabling ads does not show the onboarding box.
- Confirmed close/relaunch of the browser after disabling ads does not show the onboarding box.
- Confirmed clicking on the "x" closes the tour promo card.
- Confirmed clicking on the "Take a quick tour" button shows the wide view of the onboarding tour.

<img width="1263" alt="Screen Shot 2021-02-02 at 1 18 26 PM" src="https://user-images.githubusercontent.com/28145373/106644702-6cfdd000-6559-11eb-8478-1a749b1d871b.png">

</details>


TBD:
<details>
<summary>Onboarding Tour - Wide View</summary>


</details>

<details>
<summary>Onboarding Tour - Narrow View</summary>


</details>
