### ISSUE TITLE
Import only history is adding duplicated entries 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1247]
## Description 
Import only history from b-l is adding history records trice in Brave Core

## Steps to Reproduce

   1.  Launch b-l with clean profile
   2.  Add two sites to b-l and close browser laptop
   3.  Launch b-c with clean profile from CLI 
   4.  Click on Book marks>import bookmarks and settings
   5.  Select Brave from import drop down
   6.  Un check all the check boxes except history
   7. Click on import and done

## Actual result:
Press ctrl+h to check the history, history page shows the imported sites trice
![import only history to b-c is adding history records trice](https://user-images.githubusercontent.com/38657976/45952926-25c8b180-c026-11e8-8b4f-c901142cf1ff.gif)

## Expected result:
Imported history sites should display only once in b-c

## Reproduces how often: 
Always

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows

### Reproducible on current release:
NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? -NO
- Is the issue reproducible on the latest version of Chrome?  - NO

### Additional Information
@kjozwiak @LaurenWags @btlechowski @srirambv

**Comment by kjozwiak** [comment]
Also reproducible under `macOS 10.13.6 x64 using the following build:

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

However, not always getting three copies, sometimes it's just duplicates. Either way, it's always three or two copies of the same history entry that's imported into b-c.

**Comment by garrettr** [comment]
The browser-laptop importer only appears to be triplicating or duplicating history entries: actually, it's importing all of the history entries from the Chromium/Muon history backend, which is a superset of the history entries that are listed in `session-store-1` and thus are shown in browser-laptop's "Show History" view.

For example:
 - Launch b-l using an empty/new user data directory: `mkdir bl-test-udd && CHROME_USER_DATA_DIR=$(pwd)/bl-test-udd /Applications/Brave.app/Contents/MacOS/Brave`.
- Type `google.com` in the address bar and press return/Enter.
- Open the history (`about:history`, Cmd-Y, etc.).
- You should see a single entry with title "Google" and domain "www.google.com"
- Quit b-l
- `sqlite3 bl-test-udd/History "select * from urls where url glob '*google*';"`
    - You will see at least 3 URLs containing google, each of which is part of the redirect chain from `http://google.com` --> `https://google.com` --> `https://www.google.com`.
- `jq ".about.history.entries[] | .location" bl-test-udd/session-store-1`
    - You will see one entry, for `"https://www.google.com"`.

As we can see, only the final URL in the redirect chain is stored in `session-store-1` and shown in "Show History," although every navigated URL is stored in the history db. The browser-laptop importer is currently importing every URL from the history db, including URLs that are usually hidden (because they are navigated from redirects, subframes, etc.).

Chromium similarly stores every navigated URL in the History db, but filters visits into "visible visits" ([VisitDatabase::GetVisibleVisitsForURL](https://cs.chromium.org/chromium/src/components/history/core/browser/visit_database.h?l=60-68&rcl=dca811434bb545bacf057c4caf0312aab379c1d6)) when displaying the history to the user. I did some further testing and confirmed that this issue also affects `ChromeImporter`, which is not surprising because `BraveImporter` inherits from `ChromeImporter` and their `ImportHistory` implementations are nearly identical.

Amusingly, since the original Muon implementation of `ChromeImporter::ImportHistory` appears to have been based on [Firefox's implementation](https://dxr.mozilla.org/mozilla-central/rev/17c314f6930d2b8d6e456aa9e9d41407a45c3008/browser/components/migration/ChromeProfileMigrator.js#252-307), I tested and confirmed that Firefox has this issue as well.

**Comment by garrettr** [comment]
I have considered the following potential fixes:

1. BraveImporter could import history entries from `session-store-1`, where they have already been filtered, instead of from the `History` sqlite db.
2. Follow the example of [FirefoxImporter::ImportHistory](https://cs.chromium.org/chromium/src/chrome/utility/importer/firefox_importer.cc?l=181-191&rcl=59d29f03a7664edd6976121c476573da33bdf9fc), which filters the sqlite query to only import URLs that are "visible" in the importee's history.

I prefer the second proposal, because it should fix the issue for both ChromeImporter and BraveImporter. I think the fixes are probably equivalent, but have not yet dug into the browser-laptop source to confirm.

**Comment by kjozwiak** [comment]
> I prefer the second proposal, because it should fix the issue for both ChromeImporter and BraveImporter.

I would agree as well regarding using the second method. In the past, we've seen `session-store-1` files become corrupted or get into a strange state that caused other issues, particularly in `Payments`. If someone with `session-store-1` that's corrupted or in a bad state, we might run into issues when attempting to import history.

CCing @bsclifton as he has a lot of experience dealing with `session-store-1` files.

**Comment by garrettr** [comment]
After chatting with @bsclifton on Slack, it seems it would be best to import history for browser-laptop from `session-store-1`'s `historySites`, since it's the data source for the "Show History"/`about:history` view.

**Comment by GeetaSarvadnya** [comment]
Verification Passed on


Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Windows
