### ISSUE TITLE
All the import options are not shown for Brave

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1248]
## Description 
When user navigates to Book marks>Import book marks and settings. After selecting Brave from import drop down, all the import options are not shown.

## Steps to Reproduce

   1. Launch b-l and add few sites and close the browser
   2. Launch b-c with clean profile from CLI
   3. Navigate to Bookmarks>Import book marks and settings
   4. Select 'Brave' option from drop down

## Actual result:
All the import options are not shown for Brave
![brave - all import options are not shown](https://user-images.githubusercontent.com/38657976/45954277-3418cc80-c02a-11e8-8110-8b7e48f698ec.gif)

## Expected result:
All the options should be displayed

## Reproduces how often: 
Always

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows

### Reproducible on current release:
NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - No
- Is the issue reproducible on the latest version of Chrome? - No

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by vdbm** [comment]
Moreover, none of the Brave bookmarks are imported.

**Comment by kjozwiak** [comment]
I managed to reproduce this on `macOS 10.13.6 x64` as well but this only happens when you initially install b-l. Example:

* ensure that you have `0.55.10 Chromium: 70.0.3538.22` opened/running
* install & open b-l `0.24.0`
* load `chrome://settings/importData` under `0.55.10 Chromium: 70.0.3538.22` and select `Brave`

You'll notice that `Favourites/Bookmarks` & `Stats` are missing:

<img width="624" alt="screen shot 2018-10-03 at 9 55 41 pm" src="https://user-images.githubusercontent.com/2602313/46448917-58c22200-c757-11e8-9eb6-970d65296f98.png">

* restart `0.24.0`
* once `0.24.0` has been relaunched, load `chrome://settings/importData` under `0.55.10 Chromium: 70.0.3538.22` and select `Brave`

You'll notice that `Favourites/Bookmarks` & `Stats` is now appearing under `Import bookmarks and settings`.

**Comment by srirambv** [comment]
Looks like until the session file is created on b-l the other options doesn't get listed in the importer

**Comment by kjozwiak** [comment]
> Looks like until the session file is created on b-l the other options doesn't get listed in the importer

yup, looks like that's definitely the case 👍

**Comment by garrettr** [comment]
Yup, this is intentional. `BraveImporterCanImport` [checks](https://github.com/brave/brave-core/blob/8eec7507e47487d54c1286267fd2c5e80cd955d2/common/importer/brave_importer_utils.cc#L31-L32) to see what b-l state files are available and only offers the option to import state types if the corresponding state files exist.

**Comment by garrettr** [comment]
@vdbm Can you open a separate issue for https://github.com/brave/brave-browser/issues/1248#issuecomment-425517171? I cannot reproduce, but would be happy to investigate further if I had some more information to work with.
