### ISSUE TITLE
reopen Ticket

### ISSUE THREAD

**Issue by xstable** [brave/brave-browser#12673]
Could you please re-open (or answer to my last request after the ticket was closed) in this ticket?
Don't see why it was closed.

https://github.com/brave/brave-browser/issues/12613
Thanks.

**Comment by diracdeltas** [comment]
sorry it may not have been clear from https://github.com/brave/brave-browser/issues/12613#issuecomment-725010042, but this is a builtin part of Brave and is necessary for implementing some of our adblocking features. as such, we don't want to generally disable it for users in incognito mode.

if you want to test a site without this script getting injected, you can turn off adblocking in brave shields.

**Comment by xstable** [comment]
@diracdeltas please don't close all the tickets directly, but let me reply before you close.
I've disabled the adblocking, and that's why I've open this issue... because at least after disabling this feature, it shouldn't appear in the incognito-mode... or am I wrong?!?

**Comment by xstable** [comment]
@bsclifton @diracdeltas 
![image](https://user-images.githubusercontent.com/1778068/99691033-0f450600-2a89-11eb-95c2-425f6a3fc150.png)

**Comment by diracdeltas** [comment]
@pes10k is this expected?

**Comment by pes10k** [comment]
Hi @xstable , just to explain a bit more about what you're seeing, that code is extension script that gets loaded for each page.  That ~3ms you're seeing reflects that the script is quite small.  However, it doesn't actually interact with the page in anyway when shields is off.  You can see this in the [pre-bundled script source](https://github.com/brave/brave-core/blob/master/components/brave_extension/extension/brave_extension/content_cosmetic.ts).  

However, the script doesn't do anything until it receives messages from brave-core (mostly from the adblock-engine in brave-core).  You can see this [here](https://github.com/brave/brave-core/blob/master/components/brave_extension/extension/brave_extension/content_cosmetic.ts#L558), where the message callbacks are handled.

Anyway, TL;DR; the script is part of Brave, and loads no matter what.  However, it only is used or modifies the page if shields are enabled.

Hope that clarifies the whats that code is doing, why it runs on all pages, and how it interacts with shields.

To clarify / reanswer your question from the previous issue, this is not related to Tor functionality, and is best understood as just fixed overhead in Brave.  That this is implemented in JS and injected in the page is just an implementation decision, but conceptually is no different than if we implemented in C++ so that it wasn't visible in devtools.

I hope that helps explain.  I'm going to close this issue.  If you have any questions or further comments though, please do not open another issue; please leave a comment below.  Thanks!
