### ISSUE TITLE
Google login button on Figma.com

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#12707]
## Description 
Blocking Google login does not work on figma.com

## Actual result:
![image](https://user-images.githubusercontent.com/19390797/99187914-ac3a3300-2759-11eb-81c3-c1c35c045832.png)
![image](https://user-images.githubusercontent.com/19390797/99187921-b65c3180-2759-11eb-8b2c-61a66aa43f02.png)

## Expected result:
Google login button should be blocked.

## Reproduces how often: 
100%

## Brave version (brave://version info)
Version 1.18.41 Chromium: 87.0.4280.49 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? ✔
- Can you reproduce this issue with the beta channel? ✔
- Can you reproduce this issue with the nightly channel? ✔

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? ❌
- Does the issue resolve itself when disabling Brave Rewards? ❌
- Is the issue reproducible on the latest version of Chrome? ✔

**Comment by fmarier** [comment]
Indeed, Google logins do work on Figma.com with that option disabled. However, they don't work on Expensify.com unless:
- the above option is enabled, or
- I "allow all cookies" in the Shields settings for Expensify

I think the problem here is that the option is somewhat misleading. This toggle is not about breaking logins, it's about blocking third-party cookies that are sometimes (but not always) needed for these logins to work.
