### ISSUE TITLE
Implement onboarding for P3A on Android

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#12723]
## Description

The follow up issue for https://github.com/brave/brave-browser/issues/6176 . It is required to implement notification about P3A during onboarding as it is done for desktop.

## Designs

For new users, show an initial welcome screen with P3A checkbox before the privacy onboarding experience:

![loadingP3A](https://user-images.githubusercontent.com/2388823/99302230-f2e46780-2803-11eb-951a-c7a12f147a99.gif)

(This has the same Brave logo animation as in the first version of onboarding.)

![image](https://user-images.githubusercontent.com/2388823/99301360-b401e200-2802-11eb-9c7d-4341fa52048d.png)

For new users who viewed the onboarding message `p3a.enabled` should be `true`, `p3a.notice_acknowledged` should be `true`

For existing users, show the P3A checkbox modal on next app launch: 

![image](https://user-images.githubusercontent.com/2388823/103948440-a116da00-50ee-11eb-967c-5d5d7e547353.png)

The P3A checkbox modal takes priority over any other modals that might be in queue (for example, set Brave as default browser).

For the existing users who don't have P3A enabled, infobar about P3A should be shown. Infobar is done with https://github.com/brave/brave-core/pull/7016, to enable it for existing users, code should be changed around https://github.com/brave/brave-core/pull/7016/files#diff-448df90d6aa5a20513ca5dba42a4e428dfd22f05577b904f8fe7986c40ab90faR278 

"Private product analytics" links to `https://brave.com/p3a`

## Assets
Figma: https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/?node-id=1511%3A24317

**Comment by karenkliu** [comment]
Designs added!

**Comment by AlexeyBarabash** [comment]
awesome, thanks @karenkliu

**Comment by deeppandya** [comment]
@karenkliu is the checkbox is clickable here ? if it is, then what should happen when user unselect the check box ?

**Comment by karenkliu** [comment]
@deeppandya The user can tap on the checkbox to unselect it. If unselected, `p3a.enabled` should be `false`, `p3a.notice_acknowledged` should be `true`

Checkbox spec is here: https://www.figma.com/file/z9wmg2FCwuXx9FLbDo5avJ/Platform-UI-Brave-desktop?node-id=105%3A244

**Comment by bsclifton** [comment]
@deeppandya can we close https://github.com/brave/brave-browser/issues/6688 as a duplicate? This has more details

Basically, we need to cover the onboarding case - but also the case where user is already an existing user. If you want, you can edit/use https://github.com/brave/brave-browser/issues/6688 to cover the existing user case

**Comment by deeppandya** [comment]
@bsclifton I think this issue has covered both scenarios. I will close the other issue

**Comment by karenkliu** [comment]
In case it wasn't clear - this set of designs should replace the current P3A banner:

![image](https://user-images.githubusercontent.com/2388823/104489650-bb383880-5584-11eb-86af-db01462fde4e.png)

The new designs use a full screen format because:

- For new users, it shows up at the beginning of the app so we have their consent to gather P3A during the following onboarding screens. Also, it's a similar treatment as competing apps that ask for usage analytics and agreement to terms before the user starts using their product

- The banner on the NTP, while very effective on its own, competes with a ton of other UI elements that we want to put in the same place. It's not as simple as plopping a banner on that spot on the NTP - we'll also have to do the extra work of figuring out the logic so it doesn't compete with other messages that appear in the same spot, like the sponsored image messages regarding Brave Rewards, the message that shows up on any NTP to claim ad grants, the actual sponsored image logo, the rate Brave prompt? It's just cleaner to keep the P3A message as a separate screen that grabs attention so we have informed consent and it doesn't get lost in all the other UI elements on our main screen.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.20.100 x64 build
- Verified P3A onboarding is shown on a clean install
- Verified opt-in or opt-out on a clean install shows privacy stats onboarding immediately after P3A is dismissed
- Verified onboarding is shown on an upgrade profile
- Verified P3A metrics are captured based and sets value based on `https://github.com/brave/brave-browser/wiki/P3A`

---------
Verification passed on Samsung Tab A with Android 10 running 1.20.100 x64 build
- Verified P3A onboarding is shown on a clean install
- Verified opt-in or opt-out on a clean install shows privacy stats onboarding immediately after P3A is dismissed
- Verified onboarding is shown on an upgrade profile
- Verified P3A metrics are captured based and sets value based on `https://github.com/brave/brave-browser/wiki/P3A`

**Comment by newuser-web** [comment]
How can I change this setting again?

**Comment by deeppandya** [comment]
> How can I change this setting again? 

@newuser-web you can change it from settings-> Privacy. ![Screenshot_20210214-222739.png](https://user-images.githubusercontent.com/5146988/107902277-f75c1180-6f13-11eb-8dc7-3c8cbf467b80.png)
