### ISSUE TITLE
URL bar notifications are invisible with Light theme

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1273]
## Steps to Reproduce

   1. Clean developer build install (make sure Dark theme is used)
   2. Change the theme to Light in chrome://settings/
   3. Go to http://homestarrunner.com/
   4. (optional) The 'Plugin blocked' message is briefly shown so reload if needed

![1273_fail](https://user-images.githubusercontent.com/34715963/46231913-da880900-c36d-11e8-867f-0627ce0ce2f0.gif)

## Actual result:

Briefly 'Plugin blocked' text in URL bar is shown
The 'Plugin blocked' message is invisible in with URL bar 
mouseover, click does not change the state
![image](https://user-images.githubusercontent.com/34715963/46039144-47e92f00-c10d-11e8-8e14-959a7cb9f0eb.png)

## Expected result:
'Plugin blocked' message is visible

## Reproduces how often: 

always

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

### Reproducible on current release:

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Reproduced by @srirambv on Linux
Reproduced by @kjozwiak on Mac

cc @LaurenWags @GeetaSarvadnya

**Comment by kjozwiak** [comment]
Happens with Widevine, autoplay & plugin blocked notifications.

**Comment by petemill** [comment]
I cannot reproduce on mac FYI. Can you confirm on that platform @kjozwiak 
![image](https://user-images.githubusercontent.com/741836/46095340-1c982b80-c171-11e8-9b03-ec4f51dc87a0.png)

**Comment by petemill** [comment]
Can also confirm that this is when starting the browser that is _already_ in light mode, and not changing from dark to light before running the steps?

**Comment by kjozwiak** [comment]
@petemill I can still reproduce the issue on macOS 10.13.6 x64 using the following:

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

STR:

* launch `0.55.6 Chromium: 70.0.3538.16` with a brand new profile, should start with the dark theme
* go into `chrome://settings` and change the theme from `Default` -> `Light`
* open a new tab and load netflix.com and you'll notice that the `Widevine` message won't be visible

**Example:**

![themeissue](https://user-images.githubusercontent.com/2602313/46120944-864f1e80-c1df-11e8-8d15-9f6996f82239.gif)

> Can also confirm that this is when starting the browser that is already in light mode, and not changing from dark to light before running the steps?

Confirmed, this only happens when you start with the `Dark` theme and switch over to the `Light` theme. The following case works as expected:

* launch `0.55.6 Chromium: 70.0.3538.16` with a brand new profile, should start with the dark theme
* go into `chrome://settings` and change the theme from `Default` -> `Light`
* restart the browser
* open a new tab and load netflix.com and you'll see the message as expected

**Comment by btlechowski** [comment]
@petemill Apologies.  I have just checked my notes and for some reason first two steps are not in the bug report. I updated the issue.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

* Works fine on light theme
* Logged #1528 for dark theme that's messed up now

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified with STR from description
* Verified Plugin, Widevine, and Autoplay notifications
* Verified for dark -> light theme and light -> dark theme changes
