### ISSUE TITLE
Add Brave's `Shields` setting to brave://settings/content

### ISSUE THREAD

**Issue by ashutoshsaboo** [brave/brave-browser#12782]
## Description (edited by @bsclifton)
brave://settings/content currently shows **Permissions** and **Content settings**. 

We should also show **Shield settings**:
- Shield status (`up` / `down` or `enabled` / `disabled`)
- Upgrade connections to HTTPS (`true` / `false`)

![image](https://user-images.githubusercontent.com/4733304/184256401-9c28a6a9-f3c7-4a39-aff8-7f8bc8c40e65.png)

When showing these, folks would be able to go to a details page for each type of shield setting. For example:
- brave://settings/content/shieldsStatus
- brave://settings/content/shieldsUpgrade
- etc

On that page, folks could view / edit / manually add a domain (including wildcard). Something that looks like this (this is an example taken from `Pop-ups and redirects`)
![image](https://user-images.githubusercontent.com/4733304/184257895-6413b1bd-f304-4fd1-adc6-ae41c68b1eb5.png)
![image](https://user-images.githubusercontent.com/4733304/184257807-e888b90d-e6b7-426b-bf5e-ae6b2ddf661f.png)

### Excluded scope
1. Shields up/down should NOT have a default setting that can be toggled (ex: global scope). This should require a pattern to be added
2. For some of the shield settings are going to require more thought. For example, it might make sense to consolidate with the existing Chromium UI
    - Cookies (`Allow all cookies` / `Block cross-site cookies` / `Block all cookies`). We may update brave://settings/cookies to cover the Shields's cookie settings
    - Block scripts (`true` / `false`). We may update brave://settings/content/javascript to cover the Shield's `Block scripts` setting
    - Adblock (`Aggressively block trackers & ads`, `Block trackers & ads`, `Allow all trackers & ads`) and Fingerprinting (`Allow fingerprinting` / `Block fingerprinting` / `Aggressively block fingerprinting`) - we may want to treat this specially (ex: use ASK for standard mode instead of DEFAULT. That means we can add them to settings, but only after that change is made)

## Original issue description 

Currently on brave the only way to change site specific shield settings is by going to the domain, and going over the shield icon and changing to desired domain-level privacy settings. However if a domain X does a temporary 302 redirect automatically to Y, then with such a setting users can only change privacy settings for Y (because X would only be momentarily be there in the browser address bar). Similar to site settings page URL pattern - `brave://settings/content/siteDetails?site=https%3A%2F%2Fgithub.com` - can we include a feature to modify brave domain level shield settings also over there? That'd be an additional ingress point, which can be very easily accessed here - `brave://settings/content/siteDetails?site=<HTML encoded domain url>`. 

Or is there any alternative currently to modify domain level shield settings for the domain X in the above use-case (I couldn't find one)?

**Comment by Dryader** [comment]
Are you talking about setting a shield setting for 1 domain and then any redirects after will have the same shield setting?
Such as [https://coveryourtracks.eff.org/](url) if you set the shield setting for that domain and as it redirects you through other websites (In this case it is testing how well your browser can be fingerprinted) they will all have the same shield setting as well?
Since domain X is only there for a second and will have your global shield settings enabled anyways on that domain as well as domain Y will as well, I don't see the point of such a feature.

**Comment by ashutoshsaboo** [comment]
I'm talking about a 302 temporary redirect here. So let's say if domain X does a 302 redirect to domain Y for authentication/SSO and to view Y in the first place it requires that shields need to be turned off for domain X. In that case how would you achieve that? 

My organization has some internal sites which require the shields to be disabled for authentication to work correctly as it relies on cross domain cookies. This is not a problem with the sites, and it's just how the authentication works for us internally. It's something like you go to domain X, it checks if you're already authenticated then lets you view the webpage ; and if not it does a 302 temporary redirect to domain Y where you can authenticate yourself. Now this redirection is super quick, and you can't really freeze the browser at domain X easily to change shield settings. I believe this to be a common use-case for several other organizations' internal websites as well. 

I wouldn't want to relax my global shield settings just for these specific internal sites to work correctly so in this case just relaxing for domain X via some ingress point would help solve this problem. Alternatively, as you mention for 302 redirection from X to Y, if I want to have stricter shield settings for X (more stricter than my global as a override) but less stricter for Y - all kinds of these cases how would you achieve without a proper ingress point? 

I'm not sure if there's any alternative to achieve this already currently, so feel free to provide alternatives if any! :)

**Comment by bsclifton** [comment]
Updated issue title - this is a great feature request. We may also want to consider allowing all subdomains on a domain (see https://github.com/brave/brave-browser/issues/5290 for more info)

**Comment by davidylin** [comment]
Partial workaround on some domains is to enter a request on the domain for a specific file, ex: "sub.domain.com/test.html" - often results in a 404 on the domain and you can then set the shields settings. Not great, but sometimes workable.

**Comment by ashutoshsaboo** [comment]
Any updates on this for a proper solution?

**Comment by bsclifton** [comment]
Updated the root post (keeping your original ask; just pre-pending what I believe we want) - how does this sound @ashutoshsaboo?
https://github.com/brave/brave-browser/issues/12782#issue-746483780

I'm reviewing with team to make sure I have this captured properly before we take a next step

**Comment by bayazidbh** [comment]
Question: would it be possible to add a temporary allow/turn-off for the Brave Shield/Permission and Content Settings, similar to the temporary notifications permission? I think that could solve the Redirect to a dozen different domain/sub-domain, as well as well as making it easier when you want to, say, temporary allow scripts for one domain/sub-domain.

In addition, I think it's been a waste that the Brave section in the context menu only has Block Element and Manage Custom Filters, so maybe we can add Temporarily Allow and/or some sort of "Change Shield Setting > [X] Script > For this domain forever / For this domain for X hours / For this domain and sub-domain..." so on and so forth.

If that isn't too complicated to implement, of course.

**Comment by rebron** [comment]
cc: @aguscruiz

**Comment by foufrix** [comment]
🍾

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.46.83 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

### Clean Profile
<details>

</details>


### Upgraded Profile
<details>

</details>

### Additional Testing
<details>

</details>

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.117 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Ubuntu 18.04 LTS

### Clean Profile


#### UI and basic-functionality check - `PASSED`
<details>

- Confirmed that the Shield settings are added in the content settings `brave://settings/content`
- Confirmed that Shield status are added in `brave://settings/content/braveShields`
- Confirmed that `Shields Down` and `Shields Up` blocks are added in the Shields status
- Confirmed that domains can be added in the `Shields Down` and `Shields Up` blocks
- Confirmed that added domains can be `Edit`ed/`Remove`d via Shield status page
- Confirmed that Shields are down for the domains which are added in the `Shields Down` blocks
- Confirmed that Shields are up for the domains which are added in the `Shields Up` blocks
- Confirmed that local Shields settings are updated via `Shields` panel
- Confirmed that removing a domain from the `Shields Down` block enables the shield on the site
- Confirmed that the Shields state is retained after the browser restarts once the site is added to the `Shields Down` block

![image](https://user-images.githubusercontent.com/34715963/202713592-07e50793-71bc-4a40-992c-4f2e5175e448.png)


Add `www.theverge.com` to `Shields Down` block
![image](https://user-images.githubusercontent.com/34715963/202713700-90e731d8-5021-40f2-804b-d4f6c2d57866.png)




Remove `www.theverge.com` from `Shields Down` block

![image](https://user-images.githubusercontent.com/34715963/202713827-c902105b-ccb6-42cf-b107-a24f5f2e1713.png)


</details>

#### Clean profile, open a site and add it to `Shields Down` - `PASSED`
<details>

1. clean profile `1.46.x`
2. open `nytimes.com` site in an NTP
3. add `nytimes` to `Shields Down` block in `brave://settings/content/braveShields`
4. make sure shield is down for `nytimes.com`
5. enable the shield manually for the site `nytimes.com`
6. make sure shield is enabled in `brave://settings/content/braveShields`

![image](https://user-images.githubusercontent.com/34715963/202714345-00e882cd-7e74-43e6-bbd0-4d23b7b4ff9c.png)
![image](https://user-images.githubusercontent.com/34715963/202714433-7695a7d6-4c6e-4f46-8464-9ff495f233c6.png)
![image](https://user-images.githubusercontent.com/34715963/202714490-1134ecbf-4fc5-4f28-b81d-8898b891e2a4.png)
![image](https://user-images.githubusercontent.com/34715963/202714514-1c024ded-21b8-4459-9115-e52bc9358087.png)






</details>

#### Clean profile, add a site to `Shields Down` block, and then open site - `FAIL`
<details>

1. clean profile `1.46.x`
2. add `nytimes.com` in `Shields Down` block under `brave://settings/content/braveShields`
3. open `nytimes.com` in an NTP and ensure that shield is down
4. remove the blocked site `nytimes.com` from `brave://settings/content/braveShields`
5. open `nytimes.com` tab and ensure shield is enabled and default shield settings are retained on `nytimes.com`
6. change the global shield settings (`Trackers and ads = Aggressive`, `FP= Strict, may break sites` and `cookies = Disabled`)
7. ensured that the updated global shield settings are retained for `nytimes`
8. add `nytimes` to `Shields Down` block in content settings
9. ensured `nytimes` shield is down
10. enable the shield for `nytimes.com` manually
11. ensured shield is enabled and default shield settings are retained on `nytimes` (steps 6 shield settings are retained)
12. change the global shield settings (`Trackers and ads = Standard`, `FP= Standard` and `cookies = All`)
13. open `nytimes`, the updated shield settings are not retained for cookies, `Allow all cookies` is shown in cookies dropdown instead of `Block all cookies`

![image](https://user-images.githubusercontent.com/34715963/202714345-00e882cd-7e74-43e6-bbd0-4d23b7b4ff9c.png)
![image](https://user-images.githubusercontent.com/34715963/202714433-7695a7d6-4c6e-4f46-8464-9ff495f233c6.png)
![image](https://user-images.githubusercontent.com/34715963/202714883-940f2648-42da-4bce-8a51-3355c5d99ab8.png)
![image](https://user-images.githubusercontent.com/34715963/202715022-d55ac9b9-2e14-464f-84bd-882f1322c1f1.png)
![image](https://user-images.githubusercontent.com/34715963/202715426-a96c4aa9-9651-41f5-87f0-e80efc43f9c2.png)
![image](https://user-images.githubusercontent.com/34715963/202715670-dcfa8aca-7d91-40ab-9dfc-351da94dfd6b.png)
![image](https://user-images.githubusercontent.com/34715963/202719743-9ece1e93-4b5a-4c10-86a4-60ea0abf0a29.png)
![image](https://user-images.githubusercontent.com/34715963/202719795-c849c700-5b8b-4187-9411-5ec1121d811b.png)
![image](https://user-images.githubusercontent.com/34715963/202720027-563c96a9-6cec-4c0e-aaed-3d7684a85709.png)
![image](https://user-images.githubusercontent.com/34715963/202720099-5b40b4be-ccf8-494c-909e-20fc2424970a.png)
![image](https://user-images.githubusercontent.com/34715963/202720158-65be0065-f2e4-4535-b3a2-c1b746a10557.png)


Encountered:
* https://github.com/brave/brave-browser/issues/26288

</details>

#### Clean profile, open a site, disable/enable Shields and then change Shields settings - `PASSED`

<details>

1. Clean profile `1.46.x`
2. Open `cnn.com`
3. Click on the Shields panel and disable the shield
4. Open the content shield setting `brave://settings/content/braveShields` and ensured that `cnn.com` is added to `Shields Down` list
5. Open the `Shields` settings for `cnn.com` and enable the shield
6. Open the content shield setting `brave://settings/content/braveShields` and ensured that `cnn.com` is added to `Shields Up` list
7. Go to global shield settings `brave://settings/shields`
8. Change the global shield settings and ensure that the shield settings are retained for `cnn.com`
9. Open `cnn.com`
10. Change the local shield settings 
11. Restart the browser and ensure that the shield settings are retained for `cnn.com`

![image](https://user-images.githubusercontent.com/34715963/202723270-c9387e6f-0227-400d-afc1-59098173bc92.png)
![image](https://user-images.githubusercontent.com/34715963/202723310-be40539a-0010-45e7-99c3-d80a93ce8da9.png)
![image](https://user-images.githubusercontent.com/34715963/202723437-550dd431-25f4-4e6a-9f9e-e28cc4751d9e.png)
![image](https://user-images.githubusercontent.com/34715963/202723467-ebe68150-de0a-48f9-b9a9-72d701cc1e70.png)
![image](https://user-images.githubusercontent.com/34715963/202723853-b1894663-d15f-467b-bdbc-ab3f69f7be1b.png)
![image](https://user-images.githubusercontent.com/34715963/202724034-b148a770-d4c7-40a9-a242-afd215026125.png)


</details>



### Upgraded Profile - `PASSED`
#### Install `1.43.x` beta build, open a few sites, disable Shields, then upgrade to `1.46.x` beta build
<details>

1. Clean profile `1.43.x` beta build
2. Open `cnn.com` and `nytimes.com`
3. Open the Shields panel and disable the shield
4. Upgrade the profile to `1.46.x` beta build
5. Open the `brave://settings/content/braveShields`
6. Ensured that the sites `cnn.com` and `nytimes.com` are added to the `Shields Down` list
7. Open `cnn.com` and `nytimes.com` sites and enable the shields
8. Open the `brave://settings/content/braveShields`
9. Ensured that the sites `cnn.com` and `nytimes.com` are added to the `Shields Up` list
10. Change the global shields settings via `brave://settings/shields`
12. Ensure that the global shield settings are retained for the sites `cnn.com` and `nytimes.com`
13. Change the local Shields settings for the sites and ensured site settings are retained





</details>


### Additional Testing - `PASSED`
<details>

- Change local Shields settings for cookies and restart the browser and ensured that cookies settings are retained
- Change local Shields settings for trackers and ads and restart the browser and ensured that trackers and ads settings are retained
- Change local Shields settings for fingerprint and restart the browser and ensured that fingerprint settings are retained
- Verified that existing/updated global shield settings are retained for the opened sites
- Confirmed that updated local/global shield settings are retained in an upgraded profile

</details>
