### ISSUE TITLE
Follow up of #5720 - favicon for verified vimeo publisher is incorrect in auto-contribution table

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#12781]
## Description 

Follow up of #5720 - favicon for verified vimeo publisher is incorrect

## Steps to Reproduce

   1. Follow the steps/STR from #5720 
  
## Actual result:

AC table - Vimeo pubs are not gettig added just domain is getting added into AC table
![image](https://user-images.githubusercontent.com/38657976/99654588-8e820c00-2a80-11eb-9c5f-caaeec0f64b7.png)

Tipping Banner - There is no publisher favicon
![image](https://user-images.githubusercontent.com/38657976/99654525-76aa8800-2a80-11eb-8fb8-34c4d6ecc938.png)

Monthly tips: Generic Vimeo favicon is shown instead of pubs favicon
![image](https://user-images.githubusercontent.com/38657976/99654670-ac4f7100-2a80-11eb-9b74-00d01afcb157.png)

One time tips: Generic Vimeo favicon is shown instead of pubs favicon
![image](https://user-images.githubusercontent.com/38657976/99654764-cee18a00-2a80-11eb-823b-8e3c6880df6f.png)

## Expected result:
Correct vimeo favicon on panel, ac, and tips tables.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.18.57 Chromium: 87.0.4280.66 (Official Build) beta (64-bit)
-- | --
Revision | fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}
OS | Windows 10 OS Version 2004 (Build 19041.572)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @emerick @rebron

**Comment by GeetaSarvadnya** [comment]
@emerick Do i need to install the GS script inorder to test issue #5720 in Beta channel `1.18.57`? Please let me know.

**Comment by emerick** [comment]
@GeetaSarvadnya No, you just have to verify in brave://components that you have the latest version of the `Brave Local Data Updater` (it should be `1.0.38` currently).

**Comment by LaurenWags** [comment]
Reproduced on macOS

```
Brave | 1.18.62 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | macOS Version 10.14.6 (Build 18G6042)
```

`Brave Local Data Updater` component version is `1.0.38` as per https://github.com/brave/brave-browser/issues/12781#issuecomment-730435089

Using Staging env, visited vimeo.com/bravelaurenwags
Opened the panel and saw generic vimeo favicon even though I have a custom one set on the publishers site for myself:
<img width="406" alt="Screen Shot 2020-11-25 at 9 21 36 AM" src="https://user-images.githubusercontent.com/28145373/100239796-d16c3580-2eff-11eb-8169-ac85ff9ab0e5.png">
<img width="548" alt="Screen Shot 2020-11-25 at 9 21 46 AM" src="https://user-images.githubusercontent.com/28145373/100239800-d204cc00-2eff-11eb-9685-f659b5dd6788.png">

**Comment by emerick** [comment]
Good find, it's due to this line in the Vimeo script:

https://github.com/brave/brave-site-specific-scripts/blob/1308b083ea7565693ca3655d02950e62614f3e7e/scripts/brave_rewards/publisher/vimeo/publisherInfo.ts#L126

Should be set via something like this instead, I think:

```
favIconUrl: utils.buildFavIconUrl(userId)
```

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.19.76 Chromium: 87.0.4280.101 (Official Build) dev (x86_64)
Revision	9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS	macOS Version 10.15.7 (Build 19H15)
```

Used dev component version 1.0.40:
<img width="355" alt="Component" src="https://user-images.githubusercontent.com/28145373/103774943-5c5e4680-4ffb-11eb-8d4f-dab1b293644d.png">

Note - per https://github.com/brave/brave-browser/issues/12968#issuecomment-743193079, Vimeo will only be added to AC table with 1.19.x, this is why this issue was tested with dev 1.19.x listed above and not release 1.18.x.

Using `Staging` env and `vimeo.com/bravelaurenwags` (verified creator), confirmed expected (custom) favicon:

Panel | One-Time Tip | Monthly Tip | AC
----- | ----- | ----- | -----
<img width="393" alt="Screen Shot 2021-01-06 at 8 34 02 AM" src="https://user-images.githubusercontent.com/28145373/103774959-61bb9100-4ffb-11eb-8674-97ff60d32286.png"> | <img width="646" alt="Screen Shot 2021-01-06 at 8 34 45 AM" src="https://user-images.githubusercontent.com/28145373/103774968-641deb00-4ffb-11eb-9002-dacd2c60efd8.png"> | <img width="637" alt="Screen Shot 2021-01-06 at 8 34 51 AM" src="https://user-images.githubusercontent.com/28145373/103774972-654f1800-4ffb-11eb-98f3-514af1befe9b.png"> | <img width="637" alt="Screen Shot 2021-01-06 at 8 34 57 AM" src="https://user-images.githubusercontent.com/28145373/103774979-66804500-4ffb-11eb-9ba1-1ed5e042a52b.png">


Using `Production` env and `vimeo.com/willchristiansen` (verified creator), confirmed expected (custom) favicon:

Panel | Monthly Tip | AC
----- | ----- | -----
<img width="396" alt="Screen Shot 2021-01-06 at 8 37 46 AM" src="https://user-images.githubusercontent.com/28145373/103775038-7dbf3280-4ffb-11eb-8a25-2e7e55152b27.png"> | <img width="652" alt="Screen Shot 2021-01-06 at 8 38 59 AM" src="https://user-images.githubusercontent.com/28145373/103775043-7f88f600-4ffb-11eb-8575-ad1ea0ce24cb.png"> | <img width="652" alt="Screen Shot 2021-01-06 at 8 39 04 AM" src="https://user-images.githubusercontent.com/28145373/103775045-80ba2300-4ffb-11eb-9660-1a6ef381662a.png">

Using `Production` env and `https://vimeo.com/jonathangurvit` (verified creator), confirmed expected (Vimeo) favicon:

Panel | Monthly Tip | AC
----- | ----- | -----
<img width="412" alt="Screen Shot 2021-01-06 at 8 41 16 AM" src="https://user-images.githubusercontent.com/28145373/103775070-8ca5e500-4ffb-11eb-9db7-2cbd0c20f937.png"> | <img width="646" alt="Screen Shot 2021-01-06 at 8 41 30 AM" src="https://user-images.githubusercontent.com/28145373/103775075-8e6fa880-4ffb-11eb-9855-a9c62b7d675a.png"> | <img width="640" alt="Screen Shot 2021-01-06 at 8 41 36 AM" src="https://user-images.githubusercontent.com/28145373/103775077-8f083f00-4ffb-11eb-8de3-ea578656a946.png">

Using `Production` env and `https://vimeo.com/ponysmasher` (not verified creator), confirmed expected (generic Vimeo) favicon:

Panel | Monthly Tip | AC
----- | ----- | -----
<img width="389" alt="Screen Shot 2021-01-06 at 8 43 29 AM" src="https://user-images.githubusercontent.com/28145373/103775176-b101c180-4ffb-11eb-94b8-e544db1b658e.png"> | <img width="652" alt="Screen Shot 2021-01-06 at 8 43 36 AM" src="https://user-images.githubusercontent.com/28145373/103775178-b232ee80-4ffb-11eb-905b-11d1721b0b1c.png"> | <img width="642" alt="Screen Shot 2021-01-06 at 8 43 41 AM" src="https://user-images.githubusercontent.com/28145373/103775183-b3641b80-4ffb-11eb-94f5-48d975816e17.png">
