### ISSUE TITLE
Third party cookies blocked in an Chrome extension Iframe

### ISSUE THREAD

**Issue by anisg** [brave/brave-browser#12791]
## Description 
Brave Shield is blocking third-party cookies to prevent user-tracking, it's great but there is a small corner case: 

I have a Chrome Extension that inject an html iframe inside a web page.
<img src="https://user-images.githubusercontent.com/17178399/99690754-c68d4d00-2a88-11eb-86cb-b013fbc2f402.png" width="40%">
(here on top right is the iframe)

The iframe have as source (src): chrome-extension://[EXTENSION_ID]/index.html  (html file of the Chrome Extension)

The issue is that when the iframe do an https request, Brave Shield will not pass cookies as it will consider it to be 3rd party cookies, thus my extension won't work as expected.

I believe this is a bug.

Would it be possible to disabled the Brave Shield in an iframe with a chrome-extension as a source? 

## Other Additional Information:

- the issue resolve itself when disabling Brave Shield

**Comment by diracdeltas** [comment]
cc @pes10k. seems reasonable to allow 3p cookies from a `chrome-extension://` frame

**Comment by pes10k** [comment]
Im not sure I understand what the privacy model would be here.  Is it that `chrome-extension://[EXTENSION_ID]` should be treated as its own origin, but should get to read / set storage?  that `chrome-extension://[EXTENSION_ID]` should always be treated as 1p relative to the top level frame?  The embedding frame?

Any of these make me a bit nervous, but maybe there is something we can work out that would not expose privacy risk.

@anisg can you say more about whats needed in your case?

**Comment by anisg** [comment]
What is needed in my case is to completely isolate `chrome-extension://[EXTENSION_ID]` iframe from its parent, and allow it to use 3p cookies. I don't know what kind of privacy risk this can expose that said.

Please note that I fixed this issue on my extension by moving all the cross-origin http requests from the iframe to the extension background script 

But maybe other extensions in the future might want this.

**Comment by pes10k** [comment]
Thanks @anisg, but Im not sure I fully understand whats needed here still.  I understand that the iframes your injecting need access to 3p storage, but Im not sure what origin / party would "own" that storage.  Do you expect all the frames injected, into different 1ps, to see the same storage?  

Apologies for all the questions, but just want to make sure I understand whats needed before we start trying to come up with a solution (or, potentially, even have the good news of something already in development fixing)

**Comment by anisg** [comment]
hmmm yeah it would be nice if multiple frames shared the same storage. I didn't check but that might be how Chrome already is doing it.

When doing http calls in a chrome extension, the origin is `chrome-extension://[EXTENSION_ID]`. and not `chrome-extension://[EXTENSION_ID]/index.html`.

**Comment by pes10k** [comment]
Thanks @anisg, just one last question:

does your extension rely on DOM storage APIs persisting their values across sessions. Or would it be sufficient to just have the values last for a session.  Asking because we're getting _very_ close to landing https://github.com/brave/brave-browser/issues/8514, and that would give all embedded frames dual-keyed storage.  If your extension doesn't expect all frames to see the same storage, than we might have a fix already underworks and about to land.

If the extension / frame expects long term persisted, global (i.e., not dual keyed) storage though, our upcoming change won't solve that use case.  I think at that point though, probably the best thing we can do is encourage extensions to handle long term, global, extension stored using the extension API, or in the background script in general.

Otherwise, if we allowed extension URLs to have global, non-dual-keyed, long-term storage, we'd actually allow sites to cross site track again (by injecting the extension URL frame themselves, flag it non-sandboxed, and then use that as a way of doing cross site tracking).

Anyway, thank you for being so helpful and humoring all the questions.  Hope we can figure something out that both makes things easier for privacy-respecting developers like yourself, w/o harming the privacy guarantees we want in Brave!

**Comment by pes10k** [comment]
I'm going to close this issue now, but please feel free to follow up if your problem hasn't been addressed
