### ISSUE TITLE
I have been using the Desktop app for a 6 months now but after an update I was not able to sent tip anymore.

### ISSUE THREAD

**Issue by BroJenuel** [brave/brave-browser#12822]
## Description 

Hi! I have been using the browser for almost 8 to 9 months now, and recently the new update, I just realize I cant send tip anymore.

## Steps to Reproduce

   1.  Click The Brave icon just beside the input bar. 
![image](https://user-images.githubusercontent.com/31676163/99865552-7d064480-2be5-11eb-9d20-c494215e4bf4.png)
   2.  And after I click it, it zeros bat
![image](https://user-images.githubusercontent.com/31676163/99865562-9e673080-2be5-11eb-9dc6-3219e038d211.png)
   3.  But if I open a new tab, it says estimated earnings for this month is 7.745. But when I try to send a tip it says zero bat. Auto Contributing is off by the way.
![image](https://user-images.githubusercontent.com/31676163/99865593-dbcbbe00-2be5-11eb-8a7c-e1340bf7206f.png)

## Actual result:

![image](https://user-images.githubusercontent.com/31676163/99865605-f00fbb00-2be5-11eb-852b-a0896b452ab8.png)

## Expected result:
at least I have a bat of like 6 to 7 Bat

## Reproduces how often: 

I'm waiting for an update if this will be fixed but not fixed.

## Brave version (brave://version info)

Brave	1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
Revision	0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS	Windows 10 OS Version 2009 (Build 19042.630)
JavaScript	V8 8.7.220.25
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
Command Line	"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --enable-features=LegacyTLSEnforced,WebUIDarkMode,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges,AutoupgradeMixedContent,WinrtGeolocationImplementation --disable-features=AutofillEnableAccountWalletStorage,TextFragmentAnchor,SmsReceiver,NotificationTriggers,VideoPlaybackQuality,AllowPopupsDuringPageUnload,PrivacySettingsRedesign,TabHoverCards,AutofillServerCommunication,PasswordCheck,IdleDetection,SignedExchangeSubresourcePrefetch,SafeBrowsingEnhancedProtection --flag-switches-begin --flag-switches-end
Executable Path	C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\jenue\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	5e3a236d-4113a79e

## Version/Channel Information:

- Can you reproduce this issue with the current release?  I'm using the current release
- Can you reproduce this issue with the beta channel?  I'm not using beta
- Can you reproduce this issue with the nightly channel?  I'm not using nightly

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? yes, I updated the chrome version but still

**Comment by 141** [comment]
There's no bug, what you are seeing is expected, unless you saying you lost already claimed BAT.

For each month you accrue BAT for the ads you interact with. For some reason this is shown as an estimated amount. Whatever the amount turns out to be, it gets paid out the next month, usually after the fifth. 

So I expect you spent all your BAT and will have to wait more than two weeks to get that next pending BAT.

**Comment by Miyayes** [comment]
Hello @BroJenuel, it looks like you are trying to send "estimated pending rewards" rather than actual BAT you have. Estimated pending rewards is the BAT you will be paid in the next payment period; it does not represent your current BAT balance. If you've had this "estimated pending rewards" amount for awhile, please go into your brave://rewards (Brave Rewards settings) and see if there are buttons to "claim your ad earnings". You will need to click that to claim your BAT and put it into your actual BAT balance.

Here is what you should expect to see:

1. You enable Brave Ads in your browser via the triangular BAT icon on the right of your URL bar (brave://rewards on desktop).
2. You begin seeing ads in the form of notifications every so often during your browsing experience, based on your frequency settings and whether there is an available match.
3. Each ad you see increases the **Ad notifications received this month** counter in the Brave Ads component in your Rewards settings. (On mobile, this information may be under "view details".)
4. Each ad notification received increases your **Estimated pending rewards** count, in BAT. **(Note: BAT does** ***not*** **immediately appear in your main balance.)**
5. On the **Payment Date** (the 5th of the month), you will see a button that says "Claim Ad Earnings". When you click this button, your earned BAT (in "Estimated pending rewards") will be deposited into your Brave Rewards wallet and  reflected in the main balance. The BAT you earn by viewing ads will *only* show up in your main wallet balance once it is claimed on or after the 5th. However:
6. If you have a **verified wallet**, then you will not need to click "Claim Ad Earnings". Instead, ad earnings will be deposited automatically into your verified wallet (and linked Uphold account) on the payment date.

**Comment by BroJenuel** [comment]
@Miyayes thanks, Ill be observing my browser from now on. If the issue still persists Ill go back here. Thanks a lot for the answer :)
