### ISSUE TITLE
Double extensions in task manager even though only one window open

### ISSUE THREAD

**Issue by specter78** [brave/brave-browser#12839]
## Description 
I have only 1 private window open. Still I see two copy of each extension - one normal and other for private window.

## Steps to Reproduce
Open private window only and look at task manager.

## Actual result:
<details>
<summary>Screenshot</summary>
<br>
<img width="484" alt="Screenshot" src="https://user-images.githubusercontent.com/40606342/99900617-a18e1980-2cd6-11eb-9a80-54d2fc2a6d9d.png">
</details>

## Expected result:
Only one instance should be there.

## Reproduces how often: 
Every time

## Brave version (brave://version info)
Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64)
OS: macOS 11.0.1

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

**Comment by specter78** [comment]
Also, why is there a brave extension? I have disabled Brave shields.

**Comment by Dryader** [comment]
I assume the reason there is 2 tasks is because opening a private window requires Brave itself to run as well as a separate instance from your regular brave instance. Disabling Brave Shields I assume will not end the task as Shields is built in to Brave. You have not mentioned how this is an issue or how it affects you.

**Comment by NumDeP** [comment]
@Dryader Considering that the window/s and or application are closed, they still appear in the manager and they still look like they're taking memory. I actually asked the same thing a while ago and was simply told it was working as intended and then I suggested a UX enhancement and was blanked - [1 Task Manager Bug and 1 Task Manager enhancement]([#1913)

**Comment by bsclifton** [comment]
Sorry for not responding sooner - this is intended (just now saw screenshot). The user profile will always be running and in scope (where the first extension is running). The private window instance is created because it's using a separate (off the record) profile

The Brave shields extension is the core functionality of Brave. I don't know what will happen if you disable this. You can launch via command line flag `--show-component-extension-options` if you really wanted to try disabling core functionality but then you're entering unsupported territory
