### ISSUE TITLE
[Desktop] sometimes in-line tip button shows "twitterTipsIconLabel" text instead of "Tip" - follow up to 12350

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12900]
## Description 

Per https://github.com/brave/brave-browser/issues/12350#issuecomment-733979030, issue reported with https://github.com/brave/brave-browser/issues/12350 is still occurring with 1.17.73.

## Steps to Reproduce

TBD

## Actual result:

Content level/in-line tip text reads something like "twitterTipsIconLabel" 

## Expected result:
Should say "Tip"

## Reproduces how often: 

intermittent

## Brave version (brave://version info)

1.17.73

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? unsure, probably
- Can you reproduce this issue with the nightly channel? unsure, probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @emerick @cryptojennie @brave/legacy_qa

**Comment by marshall** [comment]
@emerick new issue filed for the repro

**Comment by emerick** [comment]
Chatted about this with @zenparsing and he helped me realize what's going on here. It's most likely that the user has a Twitter page open while the component updater upgrades the Greaselion extension. When the extension is updated, the old content script remains resident but loses access to the port and also `chrome.runtime`. The end result is that the content script can no longer communicate with the extension and it can no longer load translations.

In order to work around this, we can check at the top of `tipping.configure` if `chrome.runtime` is undefined. If it is undefined, we'll remove the inserted tipping elements from the DOM and then make the script a no-op.

**Comment by jonathansampson** [comment]
I ran into this today when I updated from 1.0.40 to 1.0.41 and then Tweeted:

Steps to reproduce:
1. Load twitter.com with early version of Greaselion
2. Open new tab to about:components and apply update for Brave Local Data Updater
3. In still-open Twitter tab, create a new Tweet

When the tweet is added to the feed, it will show the `twitterTipsIconLabel` text. I suspect this is the case because the original `locale` object was garbage-collected when the Greaselion component was updated.

**Comment by kjozwiak** [comment]
Reproduced the a above issue via https://github.com/brave/brave-browser/issues/13470#issuecomment-768045064. STR used:

* download `1.19.86 CR: 88.0.4324.96` and login into GH
* open https://github.com/brave/brave-browser/issues/13785 and leave it as an active tab
* re-launch Brave using `--use-dev-goupdater-url` and update to a newer `Brave Local Data Updater` component
* start checking/unchecking boxes without refreshing the page that was restored when re-launching Brave

You'll get the following:

![image](https://user-images.githubusercontent.com/2602313/105947864-f08a5f00-6037-11eb-91a8-20466a2af592.png)

**Comment by LaurenWags** [comment]
+1 from @kkarikos via https://bravesoftware.slack.com/archives/CNH9Q6REV/p1641970122012400

**Comment by LeandroSuarez** [comment]
+1 in the last stable release (V1.34.80)
![image](https://user-images.githubusercontent.com/11996170/149546504-ce260ece-5ad5-4d15-b059-1c13b4423d8c.png)

**Comment by LaurenWags** [comment]
+1 from @wknapik via https://bravesoftware.slack.com/archives/CB0KCRCQN/p1645546088811579

**Comment by zenparsing** [comment]
We may be able to detect when the extension context is invalid before (or during) calls the the extension APIs and respond accordingly.  Also, in `locale.ts` we might want to return the empty string if `chrome.i18n` is unavailable.

**Comment by LaurenWags** [comment]
Verification in progress using

```
Brave | 1.37.116 Chromium: 100.0.4896.127 (Official Build) (x86_64)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | macOS Version 12.3.1 (Build 21E258)
```

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit) 
Revision	ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS	Linux
```

<details>
<summary>Twitter - InProgress</summary>

Using above build and below production component version, ran STR from https://github.com/brave/brave-browser/issues/12900#issue-751231498 to reproduce the issue:

Example | Production Component
----- | -----


Using above build and below development component version, ran STR from https://github.com/brave/brave-site-specific-scripts/pull/69#issue-1173573677 to confirm that
- inline tip buttons are not displayed on new content when scrolling down the page
- tip buttons that are currently displayed on the page will no longer work (clicking on them does not bring up the tip banner)

Example | Dev Component 
----- | -----


Confirmed that after a page reload, the in-line tip buttons display as expected (show "Tips" as the label) and clicking on them opens the tip banner:

Example | Example
----- | -----


</details>
