### ISSUE TITLE
[Desktop] Brave Today intro card should dismiss

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#12960]
## Test plan

   1. View Brave Today
   2. Ensure Intro card is on screen for at least 4 seconds
    -> Observe Intro card stays visible
   3. View Brave Today on another tab (or refresh current tab)
    -> Observe Intro card is not visible

**Comment by petemill** [comment]
Closed by https://github.com/brave/brave-core/pull/7111

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using the following builds:

```
Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2009 (Build 19042.685)
```

* verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/12960#issue-754157722
* scrolled through the `Brave Today` feed quickly so that the intro card wasn't visible for more than 4s and ensured that it was still being displayed in other `brave://newtab` tabs.
* viewed the intro card for more than 4s and refreshed the tab, ensured it was removed from the feed
  * ensured that opening new  `brave://newtab` tabs didn't display the intro card
* ensured that the intro card doesn't re-appear after Brave has been restarted
* ensured that the intro card doesn't re-appear after toggling `Show Brave Today` via `Customize Dashboard`
* ensured that the intro card doesn't re-appear after clicking on `Reset Brave Today Sources` via `Customize Dashboard`
