### ISSUE TITLE
Change gaia URL to be no-thanks.invalid

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#1312]
We don't want gaia requests going to Google, so we should change the request endpoint from accounts.google.com to `https://no-thanks.invalid`

**Comment by RyanJarv** [comment]
Got a notice from little snitch that a request was being made to no-thanks.invalid just now. Seems like this domain shouldn't exist but was resolving to `23.195.69.106` and `23.202.231.166` on my computer. I'm guessing this was due to my providers DNS resolving invalid domains. Unsure if this is an issue but wanted to make note of it at least.

```
$ host no-thanks.invalid
no-thanks.invalid has address 23.202.231.166
no-thanks.invalid has address 23.195.69.106
Host no-thanks.invalid not found: 3(NXDOMAIN)
```

(Bit confused why I get a few IP's here and a NXDOMAIN but this was copy/pasted.)

**Comment by knightwolfjk** [comment]
@RyanJarv FWIW here's my output of same

```
# host no-thanks.invalid
Host no-thanks.invalid not found: 3(NXDOMAIN)
```

**Comment by RyanJarv** [comment]
@knightwolfjk 

NXDOMAIN behavior is DNS provider dependent, I would say it's best not to rely on NXDOMAIN being returned if initiating the request is a concern.

cc: @bbondy
