### ISSUE TITLE
Make network throttle wait if IPFS node is in the process of being installed

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#13177]
Currently it's possible to install and get an interstitial page or page not load error after you install IPFS local node.  During that period we should use the network throttle to continue loading .

**Comment by lidel** [comment]
Would this just look like page load? That creates a perception of "IPFS being slow" when in fact its Brave fetching and installing go-ipfs behind the scenes for the most of  the time?

**Comment by LaurenWags** [comment]
@spylogsster or @bbondy could one of you help with a test plan for this one since it's marked `QA/Yes`?

**Comment by spylogsster** [comment]
@LaurenWags try next:
1) Setup IPFS method as public gateway
2) Block requests to [gateway domain]/api/v0/swarm/peers in sniffer (wireshark/fiddler/any other). 
3) Start browser with several IPFS tabs
4) Tabs navigations should wait until you unblock requests

**Comment by stephendonner** [comment]
I tried to test this today, but I haven't yet been able to see the swarm traffic noted above, using either Charles Proxy or Fiddler Everywhere; I posted a question in #brave-core on Slack to see if anyone might have pointers on how to see -- and then be able to block -- that traffic.

**Comment by spylogsster** [comment]
I use older version of Fiddler and it works well out of the box for me:
![image](https://user-images.githubusercontent.com/2965009/110617105-5b39c900-81a6-11eb-8813-40f1dc2a801d.png)
I added ipfs tabs to start pages and just started the browser, my hosts file is empty. @stephendonner

**Comment by srirambv** [comment]
I am able to verify the issue on Windows with Fiddler

![image](https://user-images.githubusercontent.com/17010094/111119316-e2e65580-8561-11eb-872a-f099acf58380.png) | ![image](https://user-images.githubusercontent.com/17010094/111119344-eda0ea80-8561-11eb-99af-0f0e9cc41cd7.png)
-- | --

However on macOS, I run into the same issue as @stephendonner as mentioned in https://github.com/brave/brave-browser/issues/13177#issuecomment-793258103

Unable to get 200 for swam peers or for status
<img width="1552" alt="Screenshot 2021-03-15 at 05 41 17" src="https://user-images.githubusercontent.com/17010094/111119405-01e4e780-8562-11eb-8b13-95308eabb70e.png"> | <img width="1552" alt="Screenshot 2021-03-15 at 05 41 23" src="https://user-images.githubusercontent.com/17010094/111119422-07423200-8562-11eb-8d9e-c4b462de2ed2.png">
-- | --

Peers show up when using `localhost` but the moment its switched to `ipv4.fiddler` redirect it automatically redirects to `ipfs://` which fails to load the peers list 

<img width="1440" alt="Screenshot 2021-03-15 at 05 41 56" src="https://user-images.githubusercontent.com/17010094/111119446-0dd0a980-8562-11eb-9ed2-ca96e8db867f.png"> | <img width="1440" alt="Screenshot 2021-03-15 at 05 42 10" src="https://user-images.githubusercontent.com/17010094/111119461-11fcc700-8562-11eb-839a-bd2dc4bb8be1.png">
-- | --

I gives unable to resolve method. Even when I try to manually change the config path to use `ipv4.fiddler` instead of `127.0.0.1` so that fiddler can capture it still doesn't work and says unable to resolve method. 
<img width="1440" alt="Screenshot 2021-03-15 at 05 42 38" src="https://user-images.githubusercontent.com/17010094/111119471-14f7b780-8562-11eb-8079-ab6d3b772f6e.png">

Tried with Charles proxy as well but ran into the same issue. Maybe we are missing a specific setting for macOS which is causing the issue. 

cc: @lidel or @autonome may have some pointers on this one

**Comment by stephendonner** [comment]
Verified `PASSED` on `beta` using build 


Brave | 1.22.58 Chromium: 89.0.4389.86 (Official Build) beta (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)

Steps used to verify were:

1. clean profile
2. started browser, set a bunch of `ipfs` and `ipns` URLs as tabs; used were: `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`, `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/`, `ipns://brantly.eth`, and `ipns://en.wikipedia-on-ipfs.org`
3. connected to Ethernet
4. clicked `Use a local node` on one of the tabs, which installed and configured the local `ipfs` node
5. once it got to `Waiting for peers`, unplugged Ethernet cable; waited at least 10 seconds or so
6. saw `Try again` button with `We have exceeded the limit of attempts.  Try again later.` message text, below it
7. plugged Ethernet cable back in
8. waited until tabs automatically reloaded their content

The DNS-lookup failures seen in two of the tabs in my animated-gif screencast are unrelated "failures," which is just a timing issue - the real verification is *after* the DNS-lookup happens, when we connect to peers, which I conferred and verified with @spylogsster 👍 

Thanks again to Sergey, @LaurenWags and @srirambv for help and verification attempts!

![ipfs-retry](https://user-images.githubusercontent.com/387249/111227215-77bb7400-859f-11eb-9a8b-9c79d64ba7d8.gif)
