### ISSUE TITLE
Improve "Sorry, that page is missing" Wayback Machine detection prompt for Single Page Applications (appears even when page loads correctly)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#13188]
## Description 

When visiting many single page applications (SPAs), the "Sorry, that page is missing" (Wayback machine) prompt appears very frequently. This is easily reproducible on sites like https://app.coverprotocol.com/app/marketplace and quite frequently on new https://reddit.com. 

Related previous issue (closed): https://github.com/brave/brave-browser/issues/8716

![image](https://user-images.githubusercontent.com/11497541/102119789-aa729680-3e0f-11eb-9e7e-6861c86a7f5f.png)

## Steps to Reproduce

   1. Visit an SPA, like https://app.coverprotocol.com/app/marketplace
   2. Note the message bar at the top.

## Version

Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64)

## Community reports

https://www.reddit.com/r/brave_browser/comments/kbofg8/sorry_that_page_is_missing_all_the_time_for/gfqcya7/?context=3

**Comment by bsclifton** [comment]
When inspecting with Network tab in dev tools, it does look like the original resource fetched is receiving an HTTP response code of 404. This is why the dialog is shown
![image](https://user-images.githubusercontent.com/4733304/102177026-83d84e00-3e57-11eb-82cd-ffaf52ac6848.png)

It seems the page served real content even though it sent a 404

Since it's working as expected, I'd just suggest to visit brave://settings/braveHelpTips and disable `Show Wayback Machine prompt on 404 pages`

**Comment by ksnyde** [comment]
some VERY popular sites produce this result; are you sure you don't want to provide an option to whitelist certain sites?

**Comment by valtism** [comment]
I don't know if a whitelist is the best solution here. Our SPA triggers this (which I guess is a bug on our end), but still loads correctly after an SPA "refresh" where there are no 404s.
