### ISSUE TITLE
Token Revocation Not Needed When Hiding Unused Widgets

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#13235]
We should not make a network request unless there is a token to be revoked. For users who just installed Brave, hiding these widgets (without ever having used them) results in a _token revocation_ request being made. These requests do not contain a token, since the user never actually used the widget.

_Originally posted by @jonathansampson in https://github.com/brave/brave-browser/issues/9244#issuecomment-747497807_

## Test Plan
(Do for both Gemini and Binance)
1. Clean profile
2. Go to hide the widget immediately
3. Ensure via networking tools that `https://api.gemini.com/v1/oauth/revokeByToken` and `https://accounts.binance.com//oauth-api/v1/revoke-token` are not touched.
4. Clean profile
5. Authenticate via the widget
6. Hide the widget
7. Ensure via networking tools that `https://api.gemini.com/v1/oauth/revokeByToken` and `https://accounts.binance.com//oauth-api/v1/revoke-token` are called out to appropriately.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Linux

- Verified on a clean profile, no calls are made to `https://api.gemini.com/v1/oauth/revokeByToken`  when widget is removed 
- Verified on a connected profile, call to `https://api.gemini.com/v1/oauth/revokeByToken` is made 
---------
Verification passed on 

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (64-bit)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | Windows 10 OS Version 2009 (Build 19042.746)

- Verified on a clean profile, no calls are made to `https://api.gemini.com/v1/oauth/revokeByToken`  when widget is removed 
- Verified on a connected profile, call to `https://api.gemini.com/v1/oauth/revokeByToken` is made 
----------
Verification passed on 

Brave | 1.20.100 Chromium: 88.0.4324.146 (Official Build) (x86_64)
-- | --
Revision | `406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}`
OS | macOS Version 10.15.7 (Build 19H114)

- Verified on a clean profile, no calls are made to `https://api.gemini.com/v1/oauth/revokeByToken`  when widget is removed 
- Verified on a connected profile, call to `https://api.gemini.com/v1/oauth/revokeByToken` is made 

**Note:** Unable to test it on Binance due to outage https://twitter.com/binance/status/1358762715448299521
