### ISSUE TITLE
HTTPS upgrades are applied when HTTPS Everywhere is turned off

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#13232]
This is a regression. Not reproducible in  v1.18.73 (Chr 87).

## Steps to reproduce 

   1. Open `http://https-everywhere.badssl.com/`
   2. Turn off HTTPS Everywhere 
       OR turn off Shields
   3. Reload the page

## Actual result 
HTTPS upgrades are applied even when Shields are off
![Screenshot_20201217-103044_Brave - Nightly](https://user-images.githubusercontent.com/34715963/102469406-01b47900-4053-11eb-8152-042c0e72b41e.jpg)

## Expected result
HTTPS upgrades are not applied

## Issue reproduces how often 
Easily reproduced

## Brave version
Reproduced on v1.20.33 (Chr 88.0.4315.5) on Samsung Galaxy Tab S5e (Android 9.0)
Not reproducible on v1.18.73 on Samsung Galaxy Tab S5e (Android 9.0)

cc @mkarolin @deeppandya @SergeyZhukovsky @bsclifton @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
It's Reproducible in Desktop as well.

```

Brave | 1.20.31 Chromium: 88.0.4315.5 (Official Build) nightly (64-bit)
-- | --
Revision | d2abe4588adaeb0d66aa0a0106675be1dff12c64-refs/branch-heads/4315@{#11}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```

**Comment by LaurenWags** [comment]
I believe this is due to https://github.com/brave/brave-browser/issues/10190 so might be expected. cc @diracdeltas @fmarier

**Comment by fmarier** [comment]
It works fine for me. I suspect the problem is with the test plan: step 3 should *not* be "reload the page" because at that point, the URL is not http://https-everywhere.badssl.com/ anymore, it has been upgraded to https://https-everywhere.badssl.com/ (HTTPS).

So the test steps should be:

1. Open `http://https-everywhere.badssl.com/`
2. Turn off HTTPS Everywhere OR turn off Shields
3. Delete the URL from the URL bar and type `http://https-everywhere.badssl.com/` again. Do not just reload the page.

**Comment by diracdeltas** [comment]
i think this is working as intended. another test page is http://www.cafepharma.com/. confusingly the URL bar shows the site as not secure (which is a different issue) even if it has been updated. but if you copy-paste the url from the urlbar, you should see that it has HTTPS with shields on and HTTP without.

note that you have to navigate directly to the http page, as Francois said.
