### ISSUE TITLE
Take steps to have Brave's Snap package show as "Verified"

### ISSUE THREAD

**Issue by geekley** [brave/brave-browser#13253]
I'd like to know if the [Brave snap](https://snapcraft.io/brave) is official.
Although the publisher is listed as "Brave Software", it doesn't have a verified checkmark.
Also, I see no mention of snap in the official site: https://brave.com/linux/
If you have an official snap (or flatpak/appimage), I think you should add the link to the store from brave.com, and try to get the verified checkmark if possible.

**Comment by diracdeltas** [comment]
it used to be community maintained but now we are updating it. @w0ts0n may still have contact with snap.

**Comment by iKarith** [comment]
My understanding is that a request for Flatpak support was closed as wontfix.

Something you should really be considering is that Canonical, at its sole discretion, determines who is and who is not allowed to be a snap package developer. I'm commenting on this in early January 2021 where we just saw the entire tech industry collude to unperson anyone who so much as expresses that they don't hate and despise a single man, and believe he should be arrested/shot/whatever.

For decades, we said that the Internet was for everyone, and we wrote the tools and technologies underlying it so that if some evil fascist bastard ever held a gun to our heads and demanded that we control who could and could not have access to it, we couldn't do it if we wanted to.

In recent years, apparently, we discovered that the developers were in fact the evil fascist bastards they were previously trying to protect the Internet from. And even if they weren't, most of them did not have the testicular fortitude to resist a few dozen brigading SJWs and their TikTok followers making threats.

I for one will never install snapd. And Brave's rejection of an open standard that cannot be abused in this manner in favor of a closed standard designed to be controlled by a single company that has demonstrated a willingness to do whatever it takes to somehow "control" a corner of Linux … it doesn't bode well.

If Brave is not available in a standard format for my system, I'm inclined to skip it. Or I would be if "privacy focused" Mozilla were not now calling not only for unpersoning people, but **TRACKING THEM SO THAT THEY CAN BE FURTHER "PUNISHED" FOR SUPPORTING THE WRONG IDIOT IN A SUIT** … yeah, okay there Nazilla!

**Comment by geekley** [comment]
> Something you should really be considering is that Canonical, at its sole discretion, determines who is and who is not allowed to be a snap package developer.

Yea, I also don't like that snap only works with their official store, unlike flatpak and apt. I mean, even Android allows installing apks from outside the Play Store with just a warning!
Yet having an official snap is better than not having it I think.

> My understanding is that a request for Flatpak support was closed as wontfix.

That's a bummer, I hope they reconsider it. Flatpak seems to me (in my limited understanding) better on privacy / sandboxing than snap (judging by the lack of a "classic" permissions mode, for example). I'm starting to prefer it over snap.

**Comment by fmarier** [comment]
> My understanding is that a request for Flatpak support was closed as wontfix.

There is a community-supported beta Flatpak for Brave: https://github.com/brave/brave-browser/issues/1000#issuecomment-707194621

It's not yet official as it's still relatively new and has [a few issues](https://github.com/flathub/com.brave.Browser/issues), but we'd like to eventually make it official and maintain it ourselves.

**Comment by mihaiplesa** [comment]
Closing this as the Snapcraft store verifies publishers manually and there are no steps for applying. 

Have added `official` to our Snap listing and this is already included in https://brave.com/linux/
