### ISSUE TITLE
[Android] Youtube creator name not shown in Rewards Panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#13277]
This is a regression, but it is also reproducible in release

## Steps to reproduce 

   1. Clean install
   2. Enable rewards on staging
   3. Open `https://www.youtube.com/channel/UCCs7AQEDwrHEc86r0NNXE_A`
   4. Open Rewards Panel

## Actual result 
Youtube's creator is not pulled.
![Screenshot_20201217-122907_Brave - Nightly](https://user-images.githubusercontent.com/34715963/102874903-61d86000-4443-11eb-960d-36d159b8366d.jpg)

## Expected result
Creator name not shown

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? yes 
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):Tablet
   - Android version:9.0.0
   
## Brave version
Reproduced on Brave v1.18.75 on Samsung Galaxy Tab S5e (Android 9.0)
Reproduced on Brave v1.20.40 on Samsung Galaxy Tab S5e (Android 9.0)

cc @SergeyZhukovsky @brave/legacy_qa @deeppandya

**Comment by btlechowski** [comment]
Still reproducible Brave v1.19.86 on Samsung Galaxy Tab S5e (Android 9.0)

![Screenshot_20210119-120039_Brave](https://user-images.githubusercontent.com/34715963/105033133-fe4c4d00-5a57-11eb-85d7-77b68fd426a5.jpg)


The issue is reproducible on production. It is only reproducible for verified creators. Unverified creators work fine.
![Screenshot_20210119-122435_Brave](https://user-images.githubusercontent.com/34715963/105033164-07d5b500-5a58-11eb-8443-2313312444b8.jpg)

**Comment by Miyayes** [comment]
@deeppandya @LaurenWags Is this still an issue as of, say, 1.50.x?

**Comment by LaurenWags** [comment]
I haven't done much work on Android lately, perhaps @GeetaSarvadnya can check.

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible. Verified on `Vivo x70 Pro version 12` running `Bravemonoarm64.apk_1.51.114`

**Comment by GeetaSarvadnya** [comment]
@Miyayes The issue is NOT reproducible. Verified on `Vivo x70 Pro version 12` running `Bravemonoarm64.apk_1.51.114`

cc: @LaurenWags 

Example | Example
-----|-----
![Screenshot_20230517_212651](https://github.com/brave/brave-browser/assets/38657976/441c966a-2e1b-4927-95ad-379f9766fca2) | ![Screenshot_20230517_212733](https://github.com/brave/brave-browser/assets/38657976/f1c2f13e-9fd0-459b-af44-daf2da53a1aa)



Example | Example
-----|-----
![Screenshot_20230517_212803](https://github.com/brave/brave-browser/assets/38657976/09b1dcbb-fd8e-4258-a195-3d6f560f31d3) | ![Screenshot_20230517_212749](https://github.com/brave/brave-browser/assets/38657976/afe663b0-dd6d-4124-a140-5ee5d9493aa1)
