### ISSUE TITLE
Update User-Agent passed to Secure DNS provider (currently "Chrome")

### ISSUE THREAD

**Issue by romaincointepas** [brave/brave-browser#13344]
When using the Secure DNS (DNS-over-HTTPS) feature in Brave (see https://github.com/brave/brave-browser/issues/11312), the User-Agent header is currently set to `Chrome`.

Shouldn't this be set to `Brave` (or something more specific)?

**Comment by bsclifton** [comment]
@romaincointepas we intentionally use the same user-agent as Chromium. There are ways to detect differences in JavaScript for the websites; not sure what the sue case would be for passing along a custom UA for DoH?

Closing as expected - but want to copy @fmarier in case I missed something?

**Comment by romaincointepas** [comment]
@bsclifton I'm one of the founder of NextDNS, and we use the UA (when available) to detect and display the client used for the DNS queries.

We currently identify `Chrome` as Google Chrome (not Chromium), and we felt it would make more sense for Brave to send a Brave-specific UA instead of `Chrome`, which feels ambiguous.

Does this make sense?

**Comment by fmarier** [comment]
We were planning on gradually exposing Brave via the user agent string (see https://github.com/brave/brave-browser/issues/1052), but that plan has stalled due to web compatibility concerns and the fact that Chromium is working on freezing and deprecating that API.

If we decided again to do it (potentially obsoleting https://github.com/brave/brave-browser/issues/8216 in the process), then DoH would be a good place to start since it's very unlikely to break anything.
