### ISSUE TITLE
Nightly builds published as latest release 

### ISSUE THREAD

**Issue by adithyasunil26** [brave/brave-browser#13493]
## Description 
Currently, the unstable nightly builds are published as "Latest release" on GitHub releases. Wouldnt it be a better practice to publish these as "Pre-release"? This way the last stable version remains the "Latest release" and avoids all unnecessary confusion.

**Comment by srirambv** [comment]
Latest release is not specific to any channel (Release/Beta/Dev/Nightly). Whatever is the last/latest build that gets uploaded to the GH is marked as `Latest Release`. To get the latest stable/release channel, easiest way to get it via the release notes/changelog (https://github.com/brave/brave-browser/blob/master/CHANGELOG_DESKTOP.md) 

Closing the issue for now but we can discuss more in the issue and reopen if required
cc: @rebron @bsclifton

**Comment by coolaj86** [comment]
I'd like to reopen this for discussion.

The builds that are titled "Release" are labeled as "Pre-Release", yet none of Nightly, Dev, or Beta are tagged as such.

What's the actual release?

I'm one of the maintainers of of Webi ([webinstall.dev](https://webinstall.dev)) and we'd love to add Brave, but I need to know how to interpret the GitHub Release API so that we label channels correctly, and people get what they're expecting.
