### ISSUE TITLE
Brave.Rewards.TipsState.2 is returning an invalid value when a one-time tip is sent

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13549]
## Description 

Found while testing https://github.com/brave/brave-core/pull/7566#issuecomment-759483440
Brave.Rewards.TipsState.2 is returning an invalid value when a one-time tip is sent

## Steps to Reproduce

   1. Clean profile `1.20.74` staging env
   2. Enable rewards
   3. Open local-state file and ensure `Brave.Rewards.TipsState` response value is `2` (Wallet created, no tips sent)
   4. Claim grants and send a one-time tip to a verified pubs
   5. Open local-state file `Brave.Rewards.TipsState` response value is `2` instead of `4`

## Actual result:

`Brave.Rewards.TipsState` response value is `2` instead of  `4` when a one time tip is sent

## Expected result:
`Brave.Rewards.TipsState` response value should be `4` when a one time tip is sent

## Reproduces how often: 

Easy

## Desktop Brave version:

1.20.74 (both), 1.18.78 (desktop)
## Android Device details:
   - Install type (ARM, x86): NA
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @bsclifton @SergeyZhukovsky

**Comment by emerick** [comment]
@GeetaSarvadnya I'm working on fixing this bug, but I believe there's a small mistake in the STR and expected/actual results. Specifically, after sending a tip the value should be `3` not `4` (here is the list of values, but note that in the code they are 0-based not 1-based: https://github.com/brave/brave-browser/wiki/P3A#q14-have-you-made-use-of-tips-within-brave-rewards-broken). I'll let you update the issue if you agree, just let me know!

**Comment by chewy917** [comment]
@underdeveloped

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.25.19 Chromium: 90.0.4430.72 (Official Build) nightly (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:
1. clean profile
2. launched using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=4`
3. loaded `brave://local-state` and searched for `Brave.Rewards.TipsState`; verified its value was `2`
4. claimed UGP BAT grants
5. tipped `brave.com` verified publisher 10.000 BAT
6. loaded `brave://local-state` again and searched for `Brave.Rewards.TipsState`; verified its value was now `3`, which -- as @emerick points out -- is a 0-based index, so is actually `3`, rather than `4`, due to the Wiki page not starting at `0`: https://github.com/brave/brave-browser/wiki/P3A#q14-have-you-made-use-of-tips-within-brave-rewards-broken (classic "off-by-one" error 😄 )

@GeetaSarvadnya @emerick I've fixed it also in the original comment; please re-correct if I'm wrong! 🙏 

example | example | example
---------|---------|----------
<img width="1312" alt="Screen Shot 2021-04-15 at 4 56 48 PM" src="https://user-images.githubusercontent.com/387249/114953166-a92c9700-9e0c-11eb-9160-2fd835d8ea96.png"> | <img width="966" alt="Screen Shot 2021-04-15 at 4 57 28 PM" src="https://user-images.githubusercontent.com/387249/114953185-b053a500-9e0c-11eb-8b17-8840e4bd3ab4.png"> | <img width="966" alt="Screen Shot 2021-04-15 at 4 59 55 PM" src="https://user-images.githubusercontent.com/387249/114953196-b6498600-9e0c-11eb-945b-2eb069a173b8.png">

**Comment by GeetaSarvadnya** [comment]
@emerick Thanks for pointing it out! Updated the STR and actual result. @StephenBass thanks for updating the expected result.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.25.60 x64 Beta Build
- Verified steps from issue description

OnePlus 6T (Android 10) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/118482883-40875180-b70d-11eb-9a57-c6972812ddec.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/118483293-bf7c8a00-b70d-11eb-8a8a-4a0e3552e05a.png>
