### ISSUE TITLE
Add topsites UI similar to IOS

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#13714]
Recently we added a fallout UI when users wants to see more sites on NTP. This issue is to capture the changes, we should make to have similar UI as we have in ios application. 

CC. @jamesmudgett @karenkliu @anthonypkeane @bsclifton

**Comment by sum800** [comment]
Why are you guys hacking my account. My ex John Davis Wiley sold my administrator and third party rights to build programs and this one.
My ex did closed all my accounts and now has his name on my Facebook recovery page with out my permission or knowledge I'm in hiding but he still closed https://www.facebook.com/simone.sutton.758. this is just one of the facebook accounts my ex hacked. I'm in a alias because my name social security number birthday phone credit cards ALL ACCOUNTS ARE FLAGGED FOR ACTIVITIES. HE IMPERSONATED ME TOOK MY ADMINISTRATOR AND THIRD PARTY RIGHTS WITHOUT MY CONSENT OR PERMISSION. He donated my info to build programs his emails on my recovery pages with fake emails for me. His phone number on my status page and I am in hiding but can't because of the constant harassing bullying stalking controlling my info. https://www.facebook.com/simone.sutton1 this another page and https://www.facebook.com/simone.sutton1 another.five phones since Feb eighty seven Gmail's twenty numbers sometimes can't connect 911

**Comment by sum800** [comment]
> Recently we added a fallout UI when users wants to see more sites on NTP. This issue is to capture the changes, we should make to have similar UI as we have in ios application.
> 
> CC. @jamesmudgett @karenkliu @anthonypkeane @bsclifton

Please LEAVE MY ACCOUNTS ALONG THIS ONE MY FACEBOOK GOOGLE GMAIL FOXFIRE FINANCES PERSONAL INFORMATION

**Comment by sum800** [comment]
This is what y'all keep doing to my accounts
My ex did closed all my accounts and now has his name on my Facebook recovery page with out my permission or knowledge I'm in hiding but he still closed https://www.facebook.com/simone.sutton.758. this is just one of the facebook accounts my ex hacked. I'm in a alias because my name social security number birthday phone credit cards ALL ACCOUNTS ARE FLAGGED FOR ACTIVITIES. HE IMPERSONATED ME TOOK MY ADMINISTRATOR AND THIRD PARTY RIGHTS WITHOUT MY CONSENT OR PERMISSION. He donated my info to build programs his emails on my recovery pages with fake emails for me. His phone number on my status page and I am in hiding but can't because of the constant harassing bullying stalking controlling my info. https://www.facebook.com/simone.sutton1 this another page and https://www.facebook.com/simone.sutton1 another.five phones since Feb eighty seven Gmail's twenty numbers sometimes can't connect 911

**Comment by sum800** [comment]
This is sickening

If you're the owner of this website:

Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources. Additional troubleshooting information here.

Cloudflare Ray ID: 612bc55edaf4f236Your IP: 107.77.161.19Performance & security

**Comment by bsclifton** [comment]
This can be a follow up to https://github.com/brave/brave-browser/issues/21826

After we implement that, we can have a `Show more` "pill" similar to iOS where you can press to see all of the top sites (hides the background when you press this). Design TBD

**Comment by mattmcalister** [comment]
Am removing this issue from the Brave News project board

**Comment by SlowNicoFish** [comment]
https://github.com/brave/brave-browser/issues/16821

**Comment by deeppandya** [comment]
Closing this issue as we are planning to work on favorites on NTP soon.
