### ISSUE TITLE
[IPFS] Secure context for `ipfs:`-Scheme

### ISSUE THREAD

**Issue by RubenKelevra** [brave/brave-browser#13727]
Similar to https://github.com/brave/brave-browser/issues/13706 which is about the `ipns:` scheme, the `ipfs:` scheme is currently not considered 'safe' by the browser:

![Screenshot_20210122_192517-1](https://user-images.githubusercontent.com/614929/105530276-da069f80-5ce7-11eb-9b5a-4944379f7183.png)

**This is not true.**

Brave should give the user information about what exactly is safe in this context via the context menu, and show that this content is indeed secure when using the build-in ipfs node.

## Brave version (brave://version info)

Brave: 1.19.86 Chromium: 88.0.4324.96 (Official Build) unknown (64-bit)
Revision: 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{# 1784}
OS: Linux

CC: @lidel

**Comment by lidel** [comment]
This is "only" a cosmetic issue :-)

- :green_heart:  `ipfs://` is marked as [Secure Context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), you can test by opening console and reading the `window.isSecureContext` flag
- :broken_heart: the error on your screenshot comes from the UI related to security model based TLS certs from HTTPS (which we don't use in IPFS) – it is something we indeed need to fix 
   - MVP fix could be replacing popup body with info that content was loaded from IPFS node managed by brave and "Learn more" would open`brave://ipfs`

**Comment by diracdeltas** [comment]
this is also discussed in https://github.com/brave/brave-browser/issues/13303#issuecomment-752774048

**Comment by jbaicoianu** [comment]
@lidel I'm not so sure that this is purely cosmetic - it seems that despite `window.isSecureContext` being `true`, certain features,like WebXR appear to be restricted when loading an ipfs:// url directly.  

![image](https://user-images.githubusercontent.com/251610/109340941-845d6f80-781e-11eb-9d7c-1f7b11f0a0d2.png)

Compare this with the same page loaded via https://ipfs.io/:
![image](https://user-images.githubusercontent.com/251610/109341070-bbcc1c00-781e-11eb-83bc-7811de6a3f4a.png)

**Comment by lidel** [comment]
@jbaicoianu if a Web API is available on `https://` but missing on `ipfs://` or `http://*.localhost` then it is a bug. 
Do you mind providing a link that demonstrates the issue with XR? Which Web APIs are missing?

**Comment by stephendonner** [comment]
@lidel looks like the XR secure vs insecure difference @jbaicoianu is pointing out is:

1) `https://ipfs.io/ipfs/bafybeifpwdufzh64uhx64ewij52sswmurqh2ufbldx2khwptvgaxap6i4a/`
`Connection is secure` message when clicking on favicon/padlock

<img width="1162" alt="Screen Shot 2021-03-22 at 2 13 59 PM" src="https://user-images.githubusercontent.com/387249/112059314-edcc5780-8b18-11eb-8653-c563b2371a1c.png"> 

2) `ipfs://bafybeifpwdufzh64uhx64ewij52sswmurqh2ufbldx2khwptvgaxap6i4a/`
`Your connection to this site is not secure` message when clicking on `IPFS` icon

<img width="1162" alt="Screen Shot 2021-03-22 at 2 13 33 PM" src="https://user-images.githubusercontent.com/387249/112059306-ead16700-8b18-11eb-9e08-5a35d84b00fb.png">

Hope that helps!  I can't yet answer the specific question of which APIs are missing/labeled as insecure, though.

**Comment by lidel** [comment]
The popup label will be fixed in https://github.com/brave/brave-browser/issues/14889
What remains to be done here is to check if/which WebXR APIs  are missing when loaded via `ipfs://`

**Comment by jbaicoianu** [comment]
Hi, sorry I missed the notification for the reply asking for clarification.  As far as I can tell, the WebXR API is present as expected when loaded via ipfs, but requests to activate an XR session are being rejected because WebXR is specced to only allow sessions in secure contexts.

So I guess the real question is, "should ipfs be considered a secure context, and if yes, is there some check somewhere in the WebXR code which is failing for ipfs:// urls even though `window.isSecureContext` returns true?"

**Comment by spylogsster** [comment]
@jbaicoianu can you share some examples to reproduce?

**Comment by jbaicoianu** [comment]
@spylogsster sure.  My original example is a bit complex, so I've hosted a copy of the official Immersive Web WebXR examples on IPFS, these should be much easier to work with.

## Observed Behavior: ipfs://bafybeihtmlwd67upnydc7zibr6zzx7hjeajniuiz6rdgeczxsokqkallqm/

Main page loaded directly from IPFS, showing that the browser does implement WebXR:
![image](https://user-images.githubusercontent.com/251610/114283954-90ce0e00-9a01-11eb-9688-cdcce3cf9a8a.png)

First example (ipfs://bafybeihtmlwd67upnydc7zibr6zzx7hjeajniuiz6rdgeczxsokqkallqm/immersive-vr-session.html) showing that WebXR reports that a device that supports `immersive-vr` was detected (button is not disabled, `navigator.xr.isSessionSupported('immersive-vr')` resolves to `true`):
![image](https://user-images.githubusercontent.com/251610/114284038-04701b00-9a02-11eb-9f62-20d4813eca34.png)

Clicking "Enter VR" button results in error:
```
Could not create a session because: The user denied some part of the requested configuration
XRSession creation failed: The specified session configuration is not supported.
```
![image](https://user-images.githubusercontent.com/251610/114284061-223d8000-9a02-11eb-8cc9-a79c168b9c21.png)


## Expected behavior: https://ipfs.io/ipfs/bafybeihtmlwd67upnydc7zibr6zzx7hjeajniuiz6rdgeczxsokqkallqm/
When the same button is clicked when loaded via https://ipfs.io/ the button text changes to "Exit VR", and (after some delay to load the assets) the headset displays the expected scene in the VR headset (not shown in screenshot)
![image](https://user-images.githubusercontent.com/251610/114284140-b1e32e80-9a02-11eb-984c-dc2da2cb2ffd.png)

**Comment by spylogsster** [comment]
@jbaicoianu I see many errors on this page
![image](https://user-images.githubusercontent.com/2965009/123279606-ac30bb80-d510-11eb-8194-4e365db55446.png)

**Comment by n4ru** [comment]
Is the cosmetic issue still present?

**Comment by lidel** [comment]
Now, I think this issue can be closed, no longer relevant due to https://github.com/brave/brave-browser/issues/37735 

(big chunk of [feature/web3/ipfs](https://github.com/brave/brave-browser/labels/feature%2Fweb3%2Fipfs) likely can be closed too)
