### ISSUE TITLE
Disable Web Serial API

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#13902]
Chromium 89 enables [Web Serial API ](https://www.chromestatus.com/feature/6577673212002304). 

Per security team, this API should be disabled in Brave. cc: @jumde @fmarier

**Comment by mmiscool** [comment]
The implementation of the web serial API requires user interaction to enable and select the serial device. What are the security concerns about this API?

**Comment by fmarier** [comment]
In a nutshell, we share the concerns expressed by [Mozilla](https://mozilla.github.io/standards-positions/#webserial) and [Apple](https://webkit.org/tracking-prevention/).

**Comment by stylesuxx** [comment]
@fmarier Mozilla says: 

> Exposing that sort of capability to the web without adequate safeguards presents a significant threat to those devices.

and as @mmiscool states, it requires user interaction to allow access to serial devices, so I am not entirely sure what would be considered an "adequate safeguard"...

Anyway, the Web Serial API is not working with Brave as of now (_Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)_
). I am not sure if this issues has been addressed by now, or if it is a bug. If it has been addressed, I would also recommend to remove the relevant settings.

I am running a PWA which uses the Web Serial API and am posting here since one of my users reported it not to work with Brave Browser, although all his permissions are set up correctly.

**Comment by drewgates** [comment]
Would love to see a compromise found allowing this to be implemented in the future.

**Comment by flywire** [comment]
It's reasonable to disable Web Serial API by default but user should be able to enable it rather than forcing users to Chrome.

**Comment by mmiscool** [comment]
It works in Microsoft edge

**Comment by pjv** [comment]
Another happy Brave user here that would like to have a toggle to flip on support for the web serial API.

**Comment by mmiscool** [comment]
I would defiantly have to say that the "Brave" folks seem to tooo scared to enable this feature. That's not very brave is it?

**Comment by nebbles** [comment]
I too have run into this issue expecting Brave (as based on Chromium) to support features working there. I've been reading a lot of the discussion here and particularly in Mozilla's threads as to why they chose not to support it. I understand their concerns, however I still think its possible to ship these features with enough sanity-check roadblocks for the average/low-technical users. I really hope that Brave considers a path to allow users to access it, even if it's in a very explicit way (see my post below):

My suggestion posted in https://github.com/brave/brave-browser/issues/15637

> FWIW it would be great if Brave could restore some choice to the user. I personally use Brave because of its focus on reducing arbitrary tracking but whilst retaining close compatibility with Chrome by being based on Chromium. I respect the concern the team may have for features implemented in Chromium, but still believe this choice should be put in a users hands. My use case has been for the Web Serial API.
> 
> I'd suggest a mixture of suggestions above. 
> 
> 1. Instead of using `brave://flags` however, which is some really low-level/technical/raw functionality, adding an option (possibly even a section) to the standard Brave settings for advanced features achieves a bit of the pro whist minimising the con of suggestion 1. 
> 2. In addition, strengthening the permission prompt with a stern warning, whilst also informing the user that they still need to go to the settings to initially turn on this feature on.
> 3. And finally, what I think would be a real Brave-esque move, allow users to enable this feature on a per-site basis, which further tightens up the risk exposure.

**Comment by RubenKelevra** [comment]
Actually, we could just use "disabled" by default instead of asking for the site settings. This way it would get denied, except if the user is going into the site settings below the HTTPS 🔒.

I feel that's a pretty good failsafe. :)

**Comment by ShivanKaul** [comment]
Looks like this was fixed in https://github.com/brave/brave-core/commit/7e0dbdff8438ccff5453bacc8b6a3324bc48ab84, closing

**Comment by pattyland** [comment]
@ShivanKaul I'm not sure I understand your comment correctly. Will this feature be user-activatable on demand in the future like #18979?

**Comment by ShivanKaul** [comment]
@pattyland we still have some work to do to figure out which APIs we should set as "disabled but enable-able by user". This is tricky because it increases implementation and maintenance burden on us (for e.g. if Chromium changes implementation) and we really want to make sure that we're not allowing privacy abuses even if the website convinces the user to enable the API (in the general case).

**Comment by JamesB7** [comment]
"You have to select the serial device to connect to" sounds like the user wants to enable it.

**Comment by ocdtrekkie** [comment]
Very glad to see not all Chromium browsers are just rolling over and implementing Google's security holes. Another vote of confidence for Brave here for siding with Apple and Mozilla against an increasingly belligerent foe.

**Comment by stylesuxx** [comment]
> Very glad to see not all Chromium browsers are just rolling over and implementing Google's security holes.

A functionality that explicitly asks the user for a permission for a specific device on a specific website. Stripping this functionality at best shows that Brave does not trust their users to make informed decisions on their own.

I understand that there is risk involved in sharing your serial device with a website, one could for example add another screen educating the user what he is about to do. It's really a shame that this functionality is not more wide spread, there are a couple of great projects that use this feature in a very responsible manner - in fact, I don't know of any that are exploiting this feature.

Also, if it would at least be consistent: How is `webusb` allowed and `webserial` not - it makes no sense to me.

This topic just triggers me so hard since I wasted countless hours explaining to users that although Brave is a Chromium based browser and yes, the Serial settings **ARE THERE**, no - you can't use this on Brave.

**Comment by ocdtrekkie** [comment]
@stylesuxx So, the issue that Google engineers don't understand, which is why they ship so much malware, is that *people click on everything*.

> Stripping this functionality at best shows that Brave does not trust their users to make informed decisions on their own.

The problem here is your very incorrect belief that Brave users making decisions are necessarily "informed". Most web users, are, in fact, completely uninformed about the risks they take, and "adding another screen educating the user" also fails to recognize that *people don't read stuff either*. (I assume you read every EULA line-by-line too?)

> How is webusb allowed and webserial not - it makes no sense to me.

I agree, and I'll happily support your request to have WebUSB removed from Brave, because that's an excellent idea.

> there are a couple of great projects that use this feature in a very responsible manner

And here's the crux of why enabling such functionality is such an incredibly stupid idea: There's "a couple projects" that use it legitimately. One of the things Google engineers again woefully fail to comprehend is cost/benefit analysis. The huge attack surface of allowing websites to attack USB and serial device hardware, because it enables a couple cool projects is one of the most amazingly irresponsible actions ever undertaken in software engineering.

When you dump a feature like this into a browser, you have to acknowledge that yes, some engineers who like to tinker with crud are going to be delighted and build some little toy app they use once that uses the feature. However, you *also* have to acknowledge that the bad actors are going to find a way to use the feature to exploit 86-year-old seniors who use AOL.com for email and pay for Norton Antivirus. And those people are just going to click stuff, because that's what they do. And then when you add that Brave targets the crypto crowd, you've now potentially widened the attack surface to steal people's digital money.

These are egregiously irresponsible features to enable. You *could* still include them but disable them by default and bury the flags to turn them on so deep you'd need a tunnel-boring machine to find them, sure. That's okay, and if browsers want to do that, fine. But then what's the point of shipping all this additional code complexity into the web platform for a handful of Arduino users?

This is an area it is *absolutely* fine to hand off to native applications, and plenty of enterprise software with web-based interfaces exist that are well-versed in handling hardware interaction for web-based applications. It's way too niche to justify the security risk and the platform complexity to include it, and Google should be *ashamed* their proprietary extensions of the web have gotten this far, but we all know that Google has no shame at this point.

**Comment by JamesB7** [comment]
WebUSB requires that the device has a WebUSB endpoint. That is to say, the device is /designed/ to be used with WebUSB. I am designing such devices myself right now, and combined with Mono WASM, I have so far been able to port a .NET native application onto the web. WebUSB is very useful.

As far as WebSerial, most people don't have anything on a serial port. Those that do are going to know what they're doing. You could make the same argument to disallow downloading files altogether, disallow uploading, disallow anything and everything. I'm sure you think you are better than all the people you want to inconvenience.

At any rate, for either of these, you have to specifically click your (supported) device. It's not something you can just click through. The guys who came up with WebUSB, WebSerial, etc. aren't likely getting bribes as you are suggesting. They're meeting real needs of real developers and real end users.

**Comment by ocdtrekkie** [comment]
> aren't likely getting bribes as you are suggesting

I definitely did not suggest (or intend) to suggest "bribes", but it's well known Google engineers' promotional process is heavily driven by shipping new features or products, as opposed to improving existing ones. Which is to say, shipping bad web specs is extremely good for their careers, even if it's a net negative for the Internet, and even Google itself. (This particular perverse incentive is why Google has shipped over a dozen messaging apps in like the last five years... making a messaging app is straightforward and you're launching a Google product, and you don't really care what happens to it after you get your promotion anyways.)

> I have so far been able to port a .NET native application onto the web.

How many users do you expect to use this application? And to be clear, you ported a .NET native application to Chrome, not the web. WebUSB doesn't become "the web" just because Google says it is.

**Comment by JamesB7** [comment]
It's not a bad spec. It's a very useful spec for embedded hardware.

I expect some thousands to use it. It's a great feature add for our product, and will help our customers. It means a mobile version independent of app stores entirely. It's not ported to Chrome -- WebUSB works on Brave right now as well. The only thing missing will be Safari. "The web" isn't what the W3C says it is, never was and never will be, and I don't care to engage in pedantry because I have actual work to do. I am grateful for WebUSB support, and hope the Brave team will be sensible about WebSerial as well.

**Comment by ocdtrekkie** [comment]
You know what, decided this needs to be addressed:

> You could make the same argument to disallow downloading files altogether, disallow uploading, disallow anything and everything.

This is called a "strawman", where you make an absolutely ridiculous caricature of the opposing argument, and then criticize that, instead of the actual discussion. I specifically cited the importance of doing a _cost/benefit analysis_ when introducing a major security risk, and obviously, any reasonable person who agree that being able to download files is critical for the vast majority of Internet users, as opposed to an incredibly niche group (as you yourself admit) like WebUSB or WebSerial.

> I'm sure you think you are better than all the people you want to inconvenience.

And pretty sure this is just straight personal attack territory. But it's the responsibility of software developers to consider the people who will use their software and how changes to that software might cause real harm. Google's lack of understanding of userspace security has cost people billions of dollars in damage.

**Comment by ocdtrekkie** [comment]
> I expect some thousands to use it.

Some thousands is a justification for developing a browser extension or plugin. It's absolutely not a justification for introducing a major hole in the web platform.

> The only thing missing will be Safari.

And any other browser that isn't a Chrome fork. Forget about Firefox, I guess, right? It's supported in a *single browser engine*.

https://developer.mozilla.org/en-US/docs/Web/API/USB

**Comment by stylesuxx** [comment]
> How many users do you expect to use this application? And to be clear, you ported a .NET native application to Chrome, not the web. WebUSB doesn't become "the web" just because Google says it is.

Not only to Chrome. To Chromium based browsers. Also works fine with Edge, Opera, Vivaldi, Chromium...

One of the application I use web serial for has around 500 unique users a day. I'd say that's not the odd tinker project that nobody is ever going to look at - so there is real world application for such a technology.

It running straight from the browser is a **HUGE** benefit, everyone has a browser installed, no need to install any native stuff, no messing around with 3rd party software, no need to roll out native applications for Windows, Max, Linux, Android - one target.

> Most web users, are, in fact, completely uninformed about the risks they take, and "adding another screen educating the user" also fails to recognize that people don't read stuff either. (I assume you read every EULA line-by-line too?)

So because of that, all other users can't have nice things? Makes no sense to me.
And reading EULAs vs. having a Screen with a big, fat Warning that what you are doing might have some security implications are two different things...

**Comment by ocdtrekkie** [comment]
> So because of that, all other users can't have nice things?

Flip that around: For your personal convenience, you want the 99% of browser users who are non-technical to suffer significantly higher security risks? I can think of a few ways I'd describe a person holding that position.

It's really important that folks understand the web platform is used by somewhere around 5 billion people, and the number of people who even _know what a serial port is_ is probably less than a couple million. The sheer self-entitlement you'd need to believe that the web should be built for the latter over the former is... significant.

The web is for everyone, and it should be built for everyone.

**Comment by stylesuxx** [comment]
> Flip that around: For your personal convenience, you want the 99% of browser users who are non-technical to suffer significantly higher security risks? I can think of a few ways I'd describe a person holding that position.

It's not my personal convenience, it is also for the convenience of anyone using the application developed on this technology.

> It's really important that folks understand the web platform is used by somewhere around 5 billion people, and the number of people who even _know what a serial port is_ is probably less than a couple million. The sheer self-entitlement you'd need to believe that the web should be built for the latter over the former is... significant.

If they don't know what it is, they don't need to click it, and will probably never see the selection screen. With me it would be totally OK for this to be a feature that would need to be explicitly enabled with an additional checkbox somewhere.

> The web is for everyone, and it should be built for everyone.

OK, but obviously it should not be built for people that want to use their serial/USB devices from withing a browser? Like me and the users of my app. So the web should be built for everyone but us.

I am interested: Do you also have a problem with webcams and microphones being used from within the browser?

**Comment by JamesB7** [comment]
Have you actually *used* this API?
You have to *have* a serial port, and you have to *choose* it. Nobody without these things "suffers". At all.
Similarly, on WebUSB, the *developer* has to have put in a *specific interface* for WebUSB, meaning the developer *wants* it to be used from the web. And then the user has to *have* that device, and they have to *choose* it.
As for "thousands of people", not everybody is Facebook. There's a long tail of many manufacturers, all of whom have use for such a feature, and all of whose users benefit from it.

**Comment by ocdtrekkie** [comment]
@stylesuxx I'll refer you back up to the same thing I pointed out now twice: Cost/benefit analysis. How many users (especially in the pandemic era) use a webcam and microphone within the browser? Thousands of times more users benefit from that functionality than something like WebSerial, even though it's also a risk.

Location in the browser is something I find extremely uncomfortable, but again, it's useful to a massively widespread number of (not particularly privacy conscious) users, so I'd acknowledge that it has a place as a web API. Like 100% of browser users might have a use case where letting a website see their location might be appealing to them.

Notifications API? Absolutely garbage, and every browser that supports it should be embarrassed that they do. It's literally the new popup ad API, and thanks to the wonders of "people just click stuff", it's why people think their browser is hacked when they start getting adult content ads everywhere they go. ...But again, in theory, a very large percentage of web users are likely to find this feature useful.

Then we turn to "hackers who play with microcontrollers might use this", and that's where we're at with WebSerial and WebUSB. These should never have been introduced, and they are not standards: They remain explicitly Chrome code, which is thankfully, where they will stay. I mean, while we're at it, let's just start lamenting the lack of support for WebMIDI, because six people who both program JavaScript and have an electric keyboard want to play with it.

**Comment by JamesB7** [comment]
Have you actually used WebUSB or WebSerial at all? For what application? Do you even do embedded development?

**Comment by stylesuxx** [comment]
> ..."hackers who play with microcontrollers might use this"...

Alright, my initial thought when you posted your first message was, you might be flame baiting - thought long about answering you.

But yeah, this confirms it. Labeling a whole group of users with a legitimate use case as "hackers who play with micorcontrollers" is hilarious.

**Comment by ocdtrekkie** [comment]
> Have you actually used WebUSB or WebSerial at all?

I definitely would not waste effort writing for Chrome.

> Do you even do embedded development?

A bit here and there, but again, the fact that you only care about embedded developers emphasizes how wrong your position is for the Internet as a whole.

**Comment by proffalken** [comment]
Over 2,000 hackers and makers at EMFCamp 2022 got badges today that are updated and programmed via WebSerial.

None of us can hack on these badges as a result of this decision without switching to a browser that many of us deliberately switched away from some years ago over privacy concerns.

Whilst this thread appears to have descended into entrenched positions based opinion, perhaps the developers could look to the wider community who are likely to adopt Brave in future and at least have this as a "debug" flag that is badly documented and that you can only use if you stumble upon it by accident or know where to look?

I know I'm a sample count of one, but the lack of something like this based purely on what seems to be personal bias rather than world experience seems crazy to me and exactly the behaviour I'd expect of someone working for a large corporate rather than a community project.

Kind regards,

A Hacker, currently sat in a field playing with microcontrollers...

**Comment by ocdtrekkie** [comment]
@proffalken Why would you deploy 2,000 devices that are solely dependent on nonstandard Google-proprietary code?

WebSerial isn't a standard. Nobody but Google has written an implementation and almost every other browser developer considers it actively harmful.

**Comment by mmiscool** [comment]
@ocdtrekkie It works just fine in edge.

**Comment by ocdtrekkie** [comment]
> @ocdtrekkie It works just fine in edge.

Which is simply Google's implementation. The fact that a copy paste of Chrome also supports proprietary Chrome code doesn't make it a web standard.

**Comment by pattyland** [comment]
Another great example of WebSerial used by thousands of people: https://my.flipp.dev/

It would be nice if I could finally uninstall Chrome....

**Comment by proffalken** [comment]
> @proffalken Why would you deploy 2,000 devices that are solely dependent on nonstandard Google-proprietary code?
> 
> WebSerial isn't a standard. Nobody but Google has written an implementation and almost every other browser developer considers it actively harmful.
> 
> It sounds like you made a bad decision, and then want browsers to implement known vulnerabilities to cover for your mistakes.

@ocdtrekkie - I keep coming back to this comment and I genuinely don't know how to reply to it without being rude, so here's an attempt and we'll see how it goes.

It wasn't *my* decision to use this approach - I was one of the attendees - however, this does not detract from the fact that Microsoft use this for the BBC Microbit, Arduino use it for their online IDE, ESPHome.io uses it to program devices that are helping thousands of people save money on building home automation sensors, and yet it is *me* who is in the wrong?

Your tone is breathtakingly arrogant and reflects the attitudes of Google, Microsoft, and others that the Brave community was set up to get away from.

I get it.  WebSerial can be abused for evil as well as good, but it is *not* a "vulnerability" and to claim otherwise (as you do in your comment) is entirely disingenuous. 

It's up to us, the users, to choose if we want to use WebSerial - isn't that what Brave is all about? Choice?

In all the other browsers it's already only available if you go into the debug settings, so why not put it behind a feature flag that says "OK, look, you can use this if you want to, but we really recommend against it and here's why", rather than allowing us to enable all the boxes in the settings but still find that it is broken.  And WebSerial **is** _broken_ in Brave.  If I can enable something in a UI, but it still doesn't work, then that's a bug.

As far as your point on "Web Standards" is concerned, "Web Standards" were invented to stop MS, Mosaic, and Netscape from building walled gardens as AOL and Compuserv did.  Now that almost every browser runs on either Chromium or WebKit, the "standards" are becoming more and more irrelevant because we've settled on a common base.  It really wouldn't surprise me if Apple dropped WebKit in favour of Chrome in the next few years - like it or not, Chromium *is* the web standard.  It must be, otherwise, you and the other developers would have chosen to build this on top of something else.

Your argument is flawed.  Your personal position is so firmly entrenched that you would rather your userbase are unable to interact with common services and products on the internet than step back from the precipice of your own self-absorption.

Listen to the community, look at where this technology is being used, enable WebSerial and trust your users to know what they are doing.

**Comment by ocdtrekkie** [comment]
I don't understand how your unbridled arrogance would lead you to decide the needs of "thousands" justify the compromise of billions. Your comment reinforces and reiterated the threat of Google's abusive and malicious attitude towards web standards, and the toxic environment they leave in their wake. And your attitude is just that we should accept it as the de facto standard, because Google said so.

Someone might as well just delete the whole repo then, if Brave isn't going to block harmful proposals from Google, why exist? BAT I guess? I think mine is worth a couple bucks now.

**Comment by ocdtrekkie** [comment]
Also, note that Brave users aren't "my userbase", I have no affiliation with Brave, and I'm unsure how you seemed to insinuate I did.

I simply support Brave's position, and the position of Brave's *security team*. Who are well aware that Google would like the FLoC/Topics API to also be considered a "web standard".

**Comment by mmiscool** [comment]
There are not billions being compromised by the existence of the web serial API as it requires the same amount of user interaction that is required for the microphone or camera. The brave folks are just not brave enough to admit the initial reaction was wrong and reverse course on what was obviously a mistake.

> I don't understand how your unbridled arrogance would lead you to decide the needs of "thousands" justify the compromise of billions. Your comment reinforces and reiterated the threat of Google's abusive and malicious attitude towards web standards, and the toxic environment they leave in their wake. And your attitude is just that we should accept it as the de facto standard, because Google said so.
> 
> Someone might as well just delete the whole repo then, if Brave isn't going to block harmful proposals from Google, why exist? BAT I guess? I think mine is worth a couple bucks now.

**Comment by ocdtrekkie** [comment]
Nothing about it was a mistake. Every principled browser developer has passed on this one. Here's Mozilla's position: HARMFUL. https://mozilla.github.io/standards-positions/#webserial

It's time to look at your own biases, and accept that just because you personally want it, doesn't mean it's the right thing for the web.

**Comment by mmiscool** [comment]
@ocdtrekkie The statement that "Every principled browser developer has passed on this one" is completely incorrect and implies a nefarious motive to those who support the inclusion of this API. Not only does it presume to apply a level of virtue to opposing implementation but also calls in to question the ethics and principals of those who do not share your extremest views about what APIs to include. One might say you are biased about what can be considered for inclusion in the browser technology stack.

**Comment by ocdtrekkie** [comment]
@mmiscool Can you cite a single example of a browser doing more than a git pull from Chromium, having an actual discussion about this API, and deciding to include it?

This antifeature is solely written by Google, and is considered harmful by the developers of the two other major browser engines, and Brave has also declined to include it for security reasons.

**Comment by mmiscool** [comment]
By "actual discussion" do you mean something other than dinging in the heels and crying about how much of a security risk a conscious user has to do to enable such an API. It seems there has been no discussion about allowing the API to work at all. Only discussion about how scary serial devices are. It is also clear to me that installing exclusively the brave browser is not possible and you must fall back to one of the major browsers like Microsoft edge or chrome to get any real work done.

**Comment by ocdtrekkie** [comment]
@mmiscool So you don't have one. Cool.

**Comment by mmiscool** [comment]
> @mmiscool So you don't have one. Cool.

Is webUSB supported and why is webserial more scary?

**Comment by ocdtrekkie** [comment]
Mozilla and Apple both consider Web USB equally harmful. Brave looks like it did as well, but a search suggests they may have added some limited support back for hardware crypto wallets? Having a hard time finding any actual statement they were adding it back. Maybe if they pivot away from crypto at some point that'll go back away too?

**Comment by arch-user-france1** [comment]
> @ocdtrekkie It works just fine in edge.

Just to be clear... Edge is Chrome(ium). They don't care about old people. It's Microsoft.

**Comment by bugs181** [comment]
Whatever your stance on the security implications, it comes down to personal choice. I as a user, need this feature due to reasons already listed (ESPHome). This is the ONLY reason I have Google Chrome installed besides Brave. 

As for ESPhome, there are no simple-to-use UI alternatives. I create a "new" device in esphome (which lives on a NAS server), plug my device into a remote computer, click flash over browser and it's done. I now have a Home Automation device within MY control, rather than using a "cloud connected" device, doing who knows what on my network AND privacy. Yes, there are other "programming" tools, primarily CLI like esphome.py flasher. I as a user, do not want to use the CLI. It's a major hurdle to onboarding others into the locally hosted home automation ecosystem.

So, as we stated there is a NEED for this feature whatever your other opinions may hold. Put this feature behind a checkbox flag in settings if you're worried about the Brave userbase attack surface. It simply won't be enabled for people who don't know what they're doing.

Also stated, the attack surface isn't very large as others have also mentioned. Multiple steps need to be taken before anything even happens. You NEED to have a serial device, you NEED to select the device, you NEED to accept your selection. Adding a feature flag adds a FOURTH safety parameter. That's plenty.

**Comment by ocdtrekkie** [comment]
@bugs181 I think the problem there is ESPhome. They should not be building on Google-proprietary protocols. It's well within technical capabilities to build a cross-platform application which uses HTML/JS as the UI front end, that doesn't run in Chrome-only scenarios.

**Comment by bugs181** [comment]
So your solution is that the Web SHOULDN'T be a standard and ESPHome should instead build a cross platform applications which then users must install? Why even program for the Web to begin with? Why not just dump Brave browser and use only mobile apps for EVERYTHING? Strawman argument there bud, sorry.

**Comment by ocdtrekkie** [comment]
@bugs You'll note at your link "It is not a W3C Standard nor is it on the W3C Standards Track." It has not been implemented by anyone but Google, and remains solely a proprietary API which every other major browser developer, like Mozilla and Apple, have defined as "harmful". The fact that Google does it doesn't make it a standard, they do not own the web.

> where the students receive Chrome books

FWIW, these are almost certainly illegal in almost every jurisdiction, so... probably not a long-lived problem.

**Comment by bugs181** [comment]
Well buddy ole pal, I AM a software engineer. Probably more experience than you in that sector. You're a consultant. Whatever the community deems valuable usually ends up upstream. We're early adopters. I can guarantee this tech will only get better and isn't going to be dropped. New use cases are popping up every day. You can stick your head in the sand and yell from the rooftops that this feature is worthless, but you're ONE voice in an endless sea of people who would find great value in this feature. As you can see here on this thread, you've been HIGHLY downvoted. That means YOU are in the minority. Enjoy.

**Comment by bugs181** [comment]
> > @mmiscool Can you cite a single example of a browser doing more than a git pull from Chromium, having an actual discussion about this API, and deciding to include it?
> > This antifeature is solely written by Google, and is considered harmful by the developers of the two other major browser engines, and Brave has also declined to include it for security reasons.
> 
> That's exactly what's happening. Don't see any problem, issue should be closed. Wasn't even about that, the issue.

Because Browsers have NEVER gotten anything wrong. Should we look at the history of how Javascript was executed thus a need for a standards committee there too? I fail to see the security implications of ASKING a user to connect to a device. Since when is ASKING for permission ever been a bad thing?

**Comment by arch-user-france1** [comment]
> Whatever your stance on the security implications, it comes down to personal choice. I as a user, need this feature due to reasons already listed (ESPHome). This is the ONLY reason I have Google Chrome installed besides Brave.
> 
> As for ESPhome, there are no simple-to-use UI alternatives. I create a "new" device in esphome (which lives on a NAS server), plug my device into a remote computer, click flash over browser and it's done. I now have a Home Automation device within MY control, rather than using a "cloud connected" device, doing who knows what on my network AND privacy. Yes, there are other "programming" tools, primarily CLI like esphome.py flasher. I as a user, do not want to use the CLI. It's a major hurdle to onboarding others into the locally hosted home automation ecosystem.
> 
> So, as we stated there is a NEED for this feature whatever your other opinions may hold. Put this feature behind a checkbox flag in settings if you're worried about the Brave userbase attack surface. It simply won't be enabled for people who don't know what they're doing.
> 
> Also stated, the attack surface isn't very large as others have also mentioned. Multiple steps need to be taken before anything even happens. You NEED to have a serial device, you NEED to select the device, you NEED to accept your selection. Adding a feature flag adds a FOURTH safety parameter. That's plenty.

Brave doesn't allow enabling it in the flags. A proper warning could have done it, I agree. But I don't understand why one creates a GitHub issue for making pressure only and ranting about the devs.

**Comment by ocdtrekkie** [comment]
I went ahead and put bugs181 on my block list. The extremely ranty behavior combined with the denigrating superiority of deciding that since I am a consultant and he is an "engineer", he knows more, and that I'm in the minority based on issue votes on GitHub.

As a reminder to everyone, web browsers cater to everyone. They need to weigh decisions for the majority of *all humans on this planet*, not the majority of GitHub users, or majority of users who tinker with home automation systems. It's really important to consider the safety and security that we, as the technical community, put on average users when we engineer solutions that everyone will have to deal with.

**Comment by arch-user-france1** [comment]
> > > @mmiscool Can you cite a single example of a browser doing more than a git pull from Chromium, having an actual discussion about this API, and deciding to include it?
> > > This antifeature is solely written by Google, and is considered harmful by the developers of the two other major browser engines, and Brave has also declined to include it for security reasons.
> > 
> > 
> > That's exactly what's happening. Don't see any problem, issue should be closed. Wasn't even about that, the issue.
> 
> Because Browsers have NEVER gotten anything wrong. Should we look at the history of how Javascript was executed thus a need for a standards committee there too? I fail to see the security implications of ASKING a user to connect to a device. Since when is ASKING for permission ever been a bad thing?

If you read that conversation you would have known. It's because they deem older people to clock anything because some scammer is saying them what to do and they don't realize.

**Comment by bugs181** [comment]
> But I don't understand why one creates a GitHub issue for making pressure only and ranting about the devs.

The issue is because IT is a flag that you can "enable" it, but yet Brave realistically does NOT enable it. Even trying to over-ride it and enable it in settings. I think that's a bug. If this feature doesn't exist, then it should either A. Allow users to enable it or B. remove the feature flag from the browser entirely.

**Comment by arch-user-france1** [comment]
You cannot call me a consultant. I did already develop websites.

And I am very sure that since you are a website developer most probably need a second browser because of caching, caching https etc. (but maybe web devs don't need it, I do both, nginx and web). And having two browsers installed is not a problem. You could also remove chrome and use Chromium instead. Chrome is propietary, I'm sure you know.

**Comment by bugs181** [comment]
> You cannot call me a consultant. I did already develop websites.

Where did I call you a consultant and what does this have ANYTHING to do with what I said? Please use quotes if referring to something I said.

**Comment by arch-user-france1** [comment]
> > You cannot call me a consultant. I did already develop websites.
> 
> Where did I call you a consultant and what does this have ANYTHING to do with what I said? Please use quotes if referring to something I said. If you're referring to what I said about the other person, nothing was factually incorrect nor meant to be an insult. They're just facts and he got upset about what I said. It's NOT my responsibility to help other's with their emotions.
> 
> The ONLY person in this thread with "denigrating superiority" has been [ocdtrekkie](https://github.com/ocdtrekkie) about telling people how much WE don't need this feature. Rather than seeking an actual solution which offers security AND freedom of choice. Which myself and others have given.
> 
> To reiterate, even starting from the bottom; the liklihood of this feature being "abused" is a relatively small attack surface to begin with. Even that said, assuming it was (a worst case scenario) and enabled by default on EVERY browser. The hacker would have to use social engineering to convince a person to CLICK on the serial device, ENABLE it via selection, and THEN connect to it gaining access to what exactly? Remember, the API REQUIRES user interaction to even work. And that would give an attacker access to a few serial devices at most?
> 
> I'm fairly confident most attackers would look for better rewards, like infecting their system with malware and convincing them to buy gift cards to "unlock" their system by removing said malware. After all, the "consumer" would believe anything the attacker said, correct? We can assume that the person would be willing to download ANY piece of software the attacker said to. So it's not really a great argument to begin with. It's called a strawman argument.

Firefox and Safari which are the two largest browsers don't have that feature implemented yet. Only Chrome- and Chromium-based browser support it at the moment.
I don't see any reason to enable it *now* because there are not many use cases.

And probably some people get taught that they should not download random stuff, however some message explaining some trash could easily do it - "Children and people without much knowledge will click it in that case. They don't even know what Serial is." - france1 2022

**Comment by arch-user-france1** [comment]
I found a nice list, a summary of which browsers support it (only Google-Browsers).

![Screenshot_20220801-194649_Brave](https://user-images.githubusercontent.com/72965843/182210734-dff58ecd-2945-44bf-bdca-b8933168d00f.png)

**Comment by bsclifton** [comment]
Thanks for the comments folks - I did some cleanup here of some off-topic conversations. I'm going to lock this issue

Let's please create a new issue if we'd like to make a suggestion. I personally think having a flag or way to enable would be nice (and keeping off by default). Or asking first time it's used. But other folks would need to weigh in. Let's have that discussion in a new feature request issue. Thanks!

**Comment by fmarier** [comment]
Update on this issue: we are planning to re-enable this API: https://github.com/brave/brave-browser/issues/38791
