### ISSUE TITLE
Passwords are being erased after restarting computer

### ISSUE THREAD

**Issue by aaronsantamaria** [brave/brave-browser#13937]
## Description 

Users on multiple OS are claiming that passwords are not saving in Brave. It is often hard to tell whether or not these issues are rooted in user error or an issue with the browser itself. For some of them, users are still able to see their saved passwords when looking in User data directory but Brave is not reading them, sometimes passwords are not saved at all, sometimes a PC restart causes users to lose their passwords sometimes it’s when they close the browser (without having anything set to be cleared on exit). Note that we have tired to exclude cases where it appears to be a macOS keychain issue, as those can be solved on the users end by simply granting Brave access to the keychain. 

## Steps to Reproduce

Hard to reproduce, doesn't affect everyone
   1. Save passwords 
   2. Restart the computer 
   3. 

## Actual result:

Passwords are erased or not saved.   

## Expected result:
Passwords to be saved and not erased. 

## Reproduces how often: 

Hard to tell.

## Brave version (info found on brave://version)

Multiple

## Version/Channel Information:

- Can you reproduce this issue with the current release? - Yes
- Can you reproduce this issue with the beta channel? - Haven't tested, will ask the user
- Can you reproduce this issue with the nightly channel? - Haven't tested, will ask the user

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - NA
- Does the issue resolve itself when disabling Brave Rewards? - NA 
- Is the issue reproducible on the latest version of Chrome? - No

### Submitted on Zendesk:
David-85094
Version: 1.19.88
>I keep having to resave my passwords. If I save the password to a site and then leave it and come back to it, it works okay. If I close the browser and reopen it, I am prompted to input the password and save it again.

Gayle-85379
1.19.88
>All of a sudden Brave is no longer saving my passwords. Was working fine and now nothing?

Séverine-85297
1.19.88
>Hello, Here is my problem: When I put my computer to sleep or turn it off, Brave automatically logs me out from websites. And when I return to the sites, I have to reconnect each time and re-type my passwords, while each time I click on "save". They appear fine in Brave's settings, but this list gets deleted I don't know how after a short time. What should I do so that this list of passwords remains in memory, and so that I am not systematically disconnected from all the sites? Thank you !

### Submitted on Community:
https://community.brave.com/t/saved-passwords-lost-after-brave-software-update/187248
https://community.brave.com/t/brave-not-keeping-saved-passwords/199724
https://community.brave.com/t/i-am-unable-to-save-my-password-on-my-brave-browser/189046/9
https://community.brave.com/t/all-of-my-saved-passwords-are-gone/190089
https://community.brave.com/t/all-my-saved-passwords-are-gone-and-logged-out-on-every-website/189925
https://community.brave.com/t/losing-saved-passwords/192145/4
https://community.brave.com/t/updated-brave-and-now-all-saved-passwords-are-gone/179145/11
https://community.brave.com/t/password-save-not-saving/191871/7
https://community.brave.com/t/updated-brave-and-now-all-saved-passwords-are-gone/179145/8
https://community.brave.com/t/passwords-not-saving/184149
https://community.brave.com/t/10-31-2020-all-saved-passwords-disappeared-x2/175476/3

**Comment by Brave-Matt** [comment]
Another user seeing similar behavior -- note that user also seems to be unable to leave Sync chain now that they're in this state:
https://community.brave.com/t/i-lost-all-my-passwords-and-default-profile/255296

**Comment by Brave-Matt** [comment]
Another Community +1:
https://community.brave.com/t/passwords-lost-after-updating-to-version-1-25-68/253946/4

**Comment by Brave-Matt** [comment]
Two more reports from users:
https://community.brave.com/t/password-got-completely-erased-after-mac-restart/257096

**Comment by danallendotcom** [comment]
Passwords in Brave Browser Nightly have been working perfectly for months.  In the last 36 hours, I have lost all passwords twice.  I just did an experiment. Steps of Test:

1. Took screenshot of saved passwords.
2. Quit Brave Browser Nightly.
3. Started Brave Browser Nightly - passwords still there.

I cannot say for certain what conditions or events are connected with the disappearance of passwords.

Running Macos.  Brave Browser Nightly
Version 1.27.45 Chromium: 91.0.4472.88 (Official Build) nightly (x86_64)

**Comment by danallendotcom** [comment]
This problem is affecting only one of my two installations of Brave Browser Nightly (BBN).  

**### Only BBN on Android phone is affected.**

BBN on macOS is saving passwords normally.

To observe this, I had to remove the phone from the synch chain.  When the phone was on a sync chain with the desktop, passwords were disappearing from both devices.  I suspect the failed password saving on the phone was removing the passwords from the desktop via sync.

Now, basically, nothing is sync'd and only the phone is losing passwords.

I hope this helps.

Thank you.

**Comment by jsecretan** [comment]
@danallendotcom can you tell me what version of Brave you had/have on Android?  We've done some investigation and we believe this might have been related to a problem with the clear on exit setting in some of the nightyly/beta versions.

**Comment by danallendotcom** [comment]
> @danallendotcom can you tell me what version of Brave you had/have on Android? We've done some investigation and we believe this might have been related to a problem with the clear on exit setting in some of the nightyly/beta versions.

![Screenshot_20210803-171319](https://user-images.githubusercontent.com/6373767/128093152-4dc2d2a4-ba44-4ca4-a3b9-2fd56569a1d1.png)

On Android, I have been running Brave Browser Nightly for months. Updates are applied automatically.

Regarding clearing on exit, that might well have been the crucial trigger in my loss of passwords. I am certain 'Clear data on exit' was enabled on both macOS and Android, which are my only devices. When I first set this up, there was no problem. The sync chain was initiated on the Mac, the Android was added by scanning a Qr code generated on the Mac. Data preferences were set to sync everything, including settings. Settings on macOS Brave Nightly were set to clear cookies & other site data and cached images, but NOT passwords. My recollection is settings in Brave Nightly on Android do not include all the settings available in Brave Nightly on macOS.  Specifically, Brave Nightly on Android had no settings for clearing data on exit when I setup my sync chain early this year. Now, clear data on exit is on Android Brave Nightly, but it does not have the same granularity for selecting which data is cleared. 

Is it possible the problem was created when clearing data on exit was added to Android Brave Nightly, in cases where settings were being sync'd, causing Brave Nightly on Android to clear passwords, even though passwords were not selected for clearing on macOS, because Brave Nightly on Android lacked the granularity for deleting only certain data?

**Comment by danallendotcom** [comment]
@jsecretan 

> @danallendotcom can you tell me what version of Brave you had/have on Android? We've done some investigation and we believe this might have been related to a problem with the clear on exit setting in some of the nightyly/beta versions.

This is a screenshot showing About Brave on Android. 

![Screenshot_20210803_175753](https://user-images.githubusercontent.com/6373767/128098596-56202688-3c22-41fc-98ce-82d36c8dea2b.png)



On Android, I have been running Brave Browser Nightly for months. Updates are applied automatically.

Regarding clearing on exit, that might well have been the crucial trigger in my loss of passwords. I am certain 'Clear data on exit' was enabled on both macOS and Android, which are my only devices. When I first set this up, there was no problem. The sync chain was initiated on the Mac, the Android was added by scanning a Qr code generated on the Mac. Data preferences were set to sync everything, including settings. Settings on macOS Brave Nightly were set to clear cookies & other site data and cached images, but NOT passwords. My recollection is settings in Brave Nightly on Android do not include all the settings available in Brave Nightly on macOS.  Specifically, Brave Nightly on Android had no settings for clearing data on exit when I setup my sync chain early this year. Now, clear data on exit is on Android Brave Nightly, but it does not have the same granularity for selecting which data is cleared. 

Is it possible the problem was created when clearing data on exit was added to Android Brave Nightly, in cases where settings were being sync'd, causing Brave Nightly on Android to clear passwords, even though passwords were not selected for clearing on macOS, because Brave Nightly on Android lacked the granularity for deleting only certain data?

**Comment by danallendotcom** [comment]
The problems I was experiencing have not recurred.  I cannot remember exactly, but at least part of the problem I had was caused by a flaw in settings in Brave for Android vs. Brave on a desktop Mac.  The problem was in the setting related to clearing browser data when exiting Brave and then syncing those settings across devices.  On the desktop, it was possible to select which browser data would be deleted on exit, but on Android, the only choice was either delete all browser data or none.  When the settings from the desktop sync'd to Android, the settings on Android do  not have the granularity to be set to remove only cached files and cookies.  I doubt this was planned behavior, so it might have been that Android could have ignored settings on deleting browser data when syncing settings.,  Instead, when it got the settings for deleting browser data, it set itself to delete all browser data, thereby deleting passords and history.  What really hurt was after deleting passwords from Brave on Android, it sync'd passwords back to my desktop, which meant deleting all my passwords from my desktop and another device.

The corrective action on my part is I do not sync settings.

Sorry if that is irrelevant.  Cheers.

**Comment by bsclifton** [comment]
Unfortunately, there is just not enough information here to reproduce the issue. It also hasn't received a comment in 1.5 years. We do have some existing known issues where logins get lost when the OS crypt changes (due to admin changing password or other event). More information about that here:
https://community.brave.com/t/notice-unexplained-data-loss-issue/485498
