### ISSUE TITLE
Overrides the UI for the download page and history page

### ISSUE THREAD

**Issue by a-ditucalan** [brave/brave-browser#13992]
hello i succesfully override the files in settings page. its easy to me to override it because the override file is existing for settings. its already setup. currently i want to override the ui of the history and download page. how can i add like settings_resources.grd and build.gn for history? it should be coded in c++?? right now i just copy the file in chrome for history_resources.grd but it now working

![image](https://user-images.githubusercontent.com/58244709/107011514-b4db5c00-67d2-11eb-99ee-7dc90dc5870a.png)

**Comment by a-ditucalan** [comment]
-

**Comment by a-ditucalan** [comment]
I tried to copy the files from the chrome folder likes the file history_resources.grd and register it in resources_ids but it wont work

**Comment by bsclifton** [comment]
Sorry it's taken a while to respond. It's not an easy question to answer. You can't just add a grd without linking it up in GN. I think most of the changes we make to history at the moment are done via patching. You'd need to create a patch in Chromium to get Brave using your version of the history page (if you're intending to clone all the resources) and setup the dependencies so that it gets compiled

If you're just wanting to make changes to how it's rendering, I'd check out this file and the usage we have:
[polymer_overriding.js](https://github.com/brave/brave-core/blob/master/ui/webui/resources/polymer_overriding.js)

You can search the `brave-core` repo for `polymer_overriding` and you'll find some great examples
