### ISSUE TITLE
release channel sign_pkg action fails on Mac create_dist step

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#1412]
Tried running a Mac release channel build, and got the following:

```
12:49:19 [297/310] ACTION //brave/build/mac:sign_pkg(//build/toolchain/mac:clang_x64)
12:49:19 FAILED: signing/Brave Browser.pkg 
12:49:19 python ../../build/gn_run_binary.py ../../brave/build/mac/sign_pkg.sh /Users/jenkins/jenkins/workspace/brave-browser-build-darwin/src/out/Release/unsigned/Brave\ Browser.pkg /Users/jenkins/jenkins/workspace/brave-browser-build-darwin/src/out/Release/Brave\ Browser.pkg /Users/jenkins/Library/Keychains/signing.keychain-db 392F0BA65B348B1FA2FA028AA11752A01B8481A5
12:49:19 productsign: error: Could not find appropriate signing identity for “392F0BA65B348B1FA2FA028AA11752A01B8481A5” in keychain at “/Users/jenkins/Library/Keychains/signing.keychain-db”.
12:49:19 [ERROR] ./../../brave/build/mac/sign_pkg.sh failed
12:49:19 ../../brave/build/mac/sign_pkg.sh failed with exit code 1
12:55:06 [298/310] ACTION //chrome:chrome_dsym_archive(//build/toolcha
```

The keychain has the correct signing key, so we need to understand why the `productsign` command fails.

**Comment by bbondy** [comment]
Is this resolved now? I think I was given a build yesterday that works.

**Comment by mbacchi** [comment]
No this is still open, I created the build for you by removing this ACTION from the create_dist step. @emerick do you know how to test this and what the `productsign` command needs?

**Comment by emerick** [comment]
@mbacchi @RyanJarv From what I'm reading online, it sounds like we have to use an *installer* signing identity rather than an *application* signing identity. Are we sure that we have that specific key in the keychain? It would show up when running `security find-identity -v` (note: that adding `-p codesigning` will find application signing identities - not what we want). Heading out at the moment, but I can dig into this with you in the morning.

BTW, the package signing is based on what browser-laptop does. For example see:

https://github.com/brave/browser-laptop/blob/8692beec44ff4a0a7c56b5ba004bc6ea75365ccf/tools/buildInstaller.js#L149
