### ISSUE TITLE
Click on Rewards settings from BAT drop down resets to zero on chrome://rewards

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#1427]
## Description 
Click on Rewards settings from BAT drop down resets to zero on chrome://rewards
## Steps to Reproduce

   1. Open brave with clean profile
  2. Enable Rewards from welcome page
  3. Claim grants
  4. Click on "Brave Rewards" triangle icon (displayed next to shield icon)
  5. Click on Rewards settings
## Actual result:
Click on Rewards settings from BAT drop down resets to zero

![0 5 11_rewards](https://user-images.githubusercontent.com/38657976/46489932-42ce6300-c824-11e8-963a-5b6e6c7db9cd.gif)
## Expected result:
Wallet BAT value should not reset

## Reproduces how often: 
100%

## Brave version (chrome://version info)
Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? - No
- Does it reproduce on browser-laptop? - No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by kjozwiak** [comment]
Reproduced on macOS 10.13.6 x64 using the above STR. I think it's due to having two `chrome://rewards` opened. Example:

* make sure you only have one `chrome://rewards/` tab opened
* within the same tab, click on the BAT icon in the URL bar and select `Rewards Settings`
* a new `chrome://rewards/ opens with `00.00` (attempt refreshing this tab, you'll still get `00.00`
* switch over to the first tab and you'll see the correct amount even after refreshing
* close the first tab that is correctly displaying the right BAT value and now refresh the second `chrome://rewards/` tab. You'll finally see the correct BAT amount listed.

The above is reproducible whenever you have a balance, doesn't necessarily have to be a grant.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta (64-bit)  
-- | -- 
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Linux

* Verified Wallet balance showed correctly on two instances of `chrome://rewards` page
