### ISSUE TITLE
Fix failure to apply cosmetic filters added via right-click context menu

### ISSUE THREAD

**Issue by wooque** [brave/brave-browser#14458]
## Description 
Cosmetic filters are not persisted, after refresh elements are back

## Steps to Reproduce

   1. Go to github.com
   2. Right click on logo (top left) -> Brave -> Block element via selector (it should be .mt-n1 > .Header-link > .octicon > path)
   3. Refresh
   4. Icon is back

## Actual result:
Icon is not hidden after refresh

## Expected result:
Icon is hidden after refresh

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? /
- Can you reproduce this issue with the nightly channel? /

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? /
- Is the issue reproducible on the latest version of Chrome? /

**Comment by antonok-edm** [comment]
cc @SergeyZhukovsky - looks like the legacy `Right Click -> Brave` cosmetic filtering implementation may have broken as a result of the Android changes.

**Comment by antonok-edm** [comment]
@ugultopu @wooque and anyone else who may be affected by this - the temporary workaround would be to add ABP-formatted rules to the `Custom filters` section in `brave://adblock`.

For example, to block elements matching the CSS selector `.advertisement` on `https://example.com`, you'd add the following on a new line:
```
example.com##.advertisement
```

**Comment by stephendonner** [comment]
Verified `FIXED` on `nightly` with build 

Brave | 1.23.21 Chromium: 89.0.4389.72 (Official Build) nightly (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

Verified using the inline testcase (while logged in, since the markup changes):

1. Go to `github.com` (_**and log in**_)
2. Right click on logo (top left) -> Brave -> Block element via selector (it should be .mt-n1 > .Header-link > .octicon > path)
3. Refresh
4. Look for the GitHub Octocat icon

Confirmed it's gone and stays that way between refreshes.

![github-css](https://user-images.githubusercontent.com/387249/110176953-fef73380-7db8-11eb-919d-e1de23258a3e.gif)

**Comment by kjozwiak** [comment]
Moving this into the `1.21.x` milestone as @SergeyZhukovsky included https://github.com/brave/brave-core/pull/8126 in https://github.com/brave/brave-core/pull/8160 & https://github.com/brave/brave-core/pull/8159.

**Comment by LaurenWags** [comment]
Removing `QA Pass-macOS` label since this is being uplifted to 1.21.x.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)
Revision	3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS	Linux
```

Verified test plan from https://github.com/brave/brave-core/pull/8126
Confirmed able to block elements using "Block element via selector".
Confirmed "Clear CSS rules for this site" worked as expected (element is returned after page refresh).
Confirmed "Clear CSS rules for all sites" worked as expected (elements are returned after page refresh).

-----------------
