### ISSUE TITLE
Brave shields are not working properly

### ISSUE THREAD

**Issue by JohnnyX071** [brave/brave-browser#14471]
Since the last brave update, YouTube ads started showing up even though shields are on. I even tried putting them on aggressive but still. There are no steps to reproduce, it always happens. You can see some screenshots
![Screenshot_6](https://user-images.githubusercontent.com/63922728/109995700-331a1800-7d17-11eb-88bd-e8fc2e83c2bf.png)
![Screenshot_7](https://user-images.githubusercontent.com/63922728/109995714-36ad9f00-7d17-11eb-8f24-f50b45602b83.png)

I am using brave Version 1.21.73

**Comment by FoxMcloud5655** [comment]
I have this same issue.  Likely, Google found a way to bypass it and Brave will have to find another way of blocking it.  Unfortunately an endless cycle...

I tried blocking the entire element directly and it works until the page is refreshed.

**Comment by alekny** [comment]
For me custom filters stopped working completely. You can add objects via rightclick->block and after a page refresh they are all back.

**Comment by ff2000** [comment]
Same issue here.
Firefox with uBlock origin blocks the ads with no issue.

**Comment by ryanbr** [comment]
The above screenshot is just cosmetic issue, see https://github.com/brave/brave-browser/issues/11955 @JohnnyX071 

Unless it's another issue with youtube?

**Comment by JohnnyX071** [comment]
> The above screenshot is just cosmetic issue, see #11955 @JohnnyX071
> 
> Unless it's another issue with youtube?

It's not just that, I get ads on some videos too but I don't have screenshot for that

**Comment by ff2000** [comment]
Ad in a video:
![Screenshot_20210305_135710](https://user-images.githubusercontent.com/1973708/110112659-b5a7e380-7dba-11eb-9e58-ae0b793edeb8.png)
And when the video starts an ad pops on top of the video list:
![Screenshot_20210305_135740](https://user-images.githubusercontent.com/1973708/110112721-c8bab380-7dba-11eb-8a2a-4a89ab8eef88.png)
I have set aggressive blocking.

**Comment by tnup** [comment]
same as @ff2000 said. 

Version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit)

**Comment by stephendonner** [comment]
A good repro case to see the Skip Ads overlay— at least on nightly (and 1.21.73) — is to:

1. sign in with a non-Premium account
2. load a video
3. click a video on the right from the suggested list
4. click back
5. now click forward

**Comment by LaurenWags** [comment]
Able to reproduce issue from https://github.com/brave/brave-browser/issues/14471#issue-822292330 a few times using the below steps, but it was not consistent:

1. Clean profile
2. Navigate to youtube.com
3. Login
4. View a couple of videos (either in the same tab or open video in a new tab)
5. Go back to youtube.com
6. Right click on tab and select "Duplicate"
7. Do step 6 a few times, one of the times you will get an "Ad" video in the first slot, other times it is blank

<img width="1198" alt="Screen Shot 2021-03-05 at 10 58 30" src="https://user-images.githubusercontent.com/28145373/110141188-e845e200-7da2-11eb-950b-37b51d30aab6.png">

```
Brave | 1.21.73 Chromium: 89.0.4389.72 (Official Build) (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 10.15.7 (Build 19H512)
```

**Comment by FoxMcloud5655** [comment]
That's because YouTube doesn't show an ad every single time, but yes, this is reproducible; can confirm.

**Comment by stephendonner** [comment]
With both `nightly` and `1.21.73`: I should also mention another use-case, where, instead of ads, I see a blank/empty region (where others are seeing the ad, as already mentioned).

1. log in to non-Premium account
2. load youtube.com

I see a placeholder on the top-left spot, instead:
<img width="1377" alt="Screen Shot 2021-03-05 at 8 57 41 AM" src="https://user-images.githubusercontent.com/387249/110147863-00ad0100-7d91-11eb-875e-c62b56371571.png">

**Comment by stephendonner** [comment]
There's also ads on `nightly` in the search-results page, where I don't see them using `1.19.88`:

1. log in to non-Premium account on `youtube.com
2. search for, e.g. a car (`lexus is 350`): `https://www.youtube.com/results?search_query=lexus+is+350`
3. look at the results page

| `1.19.98` | `nightly` |
|----------|-----------|
<img width="1312" alt="Screen Shot 2021-03-05 at 9 46 02 AM" src="https://user-images.githubusercontent.com/387249/110153781-576a0900-7d98-11eb-9547-50c133b1fd72.png"> | <img width="1377" alt="Screen Shot 2021-03-05 at 9 46 07 AM" src="https://user-images.githubusercontent.com/387249/110153790-5a64f980-7d98-11eb-9dd6-1f50aeb2cf03.png">

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)
Revision	3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS	Linux
```

Reproduced issue originally reported under https://github.com/brave/brave-browser/issues/14471#issue-822292330 with `1.21.73`. Was unable to reproduce using `1.21.74` after fix was applied using steps from https://github.com/brave/brave-browser/issues/14471#issuecomment-791517102.

`1.21.73` | `1.21.74`
----- | -----
<img width="1333" alt="1 21 73 corner ad" src="https://user-images.githubusercontent.com/28145373/110227225-1ec74e00-7ec4-11eb-8078-d7afeec3599a.png"> | <img width="1336" alt="1 21 74 corner ad" src="https://user-images.githubusercontent.com/28145373/110227227-1ff87b00-7ec4-11eb-8ab6-45fed2ce9da1.png">

**Comment by stephendonner** [comment]
Verified `PASSED` with 

Brave | 1.21.74 Chromium: 89.0.4389.72 (Official Build) (x86_64)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | macOS Version 11.2.2 (Build 20D80)

Used the steps to reproduce in https://github.com/brave/brave-browser/issues/14471#issuecomment-791517102 and was able to see the issue using `1.21.73`; updating to `1.21.74`, I was no longer able to reproduce the original issue either.

**Comment by beatschubser** [comment]
spiegel.de was full of ads with 1.21.73. Looks good again on 1.21.74. Thank you!

**Comment by ff2000** [comment]
Just updated to 1.21.77 and ads are back.

**Comment by kjozwiak** [comment]
@ff2000 which website where you seeing ads on? Would it be possible for you to add a screenshot? There's a few issues that we're aware of regarding a race condition in the cosmetic filter where sometimes ads will get through due to the script loading either too late or too early. Refreshing usually removes them. We're close to having a fix which will be deployed in Nightly first.

However, if you're seeing something different and the ads appearing all the time, let us know the website and we'll take a look/address it 👍

**Comment by ScamCast** [comment]
This is somewhat still an issue. The ad is blocked but leaves an empty space because of the parent "ytd-rich-item-renderer" element styling. That element would need to be hidden if it  contains the "ytd-display-ad-renderer" element.

![image](https://user-images.githubusercontent.com/56202326/111926403-514f7a00-8a72-11eb-985e-82db6ab7eaf2.png)
![image](https://user-images.githubusercontent.com/56202326/111926510-ab503f80-8a72-11eb-9801-1537fd141ef2.png)
![image](https://user-images.githubusercontent.com/56202326/111926482-94115200-8a72-11eb-929c-c710bae9df56.png)

**Comment by ff2000** [comment]
> @ff2000 which website where you seeing ads on? Would it be possible for you to add a screenshot? There's a few issues that we're aware of regarding a race condition in the cosmetic filter where sometimes ads will get through due to the script loading either too late or too early. Refreshing usually removes them. We're close to having a fix which will be deployed in Nightly first.
> 
> However, if you're seeing something different and the ads appearing all the time, let us know the website and we'll take a look/address it

Today came another update. After restarting I got ads again. I didn't respond earlier because I wanted to wait for this update to verify my suspicion.
* I closed brave with youtube being the active tab.
* I updated brave
* I restarted brave
* The youtube tab loads and immediately shows an ad overlay - sometimes with an ad running, sometimes just a plain white overlay.
* For some time I get in-video ads and the ad in the top left box on the youtube home page.
* At some point ad blocking works again. I can't say ATM what exactly fixed the ad blocker.

So my issue might be unrelated but connected to updating brave.
