### ISSUE TITLE
There is an ad on https://www.reuters.com/ 

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#14483]
## Description 

There is an ad on top when you visit https://www.reuters.com/ . It started to appear in 1.21.x.

## Steps to Reproduce

   1. Visit https://www.reuters.com/ 

## Actual result:

Observe an ad on top 
![Screenshot from 2021-03-04 22-56-15](https://user-images.githubusercontent.com/12011303/110065303-d9c4df80-7d3c-11eb-85d6-77fd94ed4f86.png)

## Expected result:
There is no ad
![Screenshot from 2021-03-04 23-02-55](https://user-images.githubusercontent.com/12011303/110065720-cebe7f00-7d3d-11eb-8f7e-c3be7b11f6dc.png)

## Reproduces how often: 

Always

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes, starting from 1.21.x
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@SergeyZhukovsky we're going to include this one in `1.21.x - Release #2` which will also have the revert for https://github.com/brave/brave-browser/issues/14471. Should we add the `OS/Android` label? Assuming this also affected `Android`? Even with https://github.com/brave/brave-browser/issues/14471 reverted, we can still take a look at the above case and at least make sure that it was fixed with the revert.

**Comment by kjozwiak** [comment]
@brave/legacy_qa spoke with @SergeyZhukovsky. We'll need to do the following for this issue:

* verify that the above doesn't occur anymore once we revert the cosmetic filtering changes from desktop via https://github.com/brave/brave-browser/issues/14471
* check and ensure that the above case doesn't happen on Android when viewing pages in `Desktop` mode rather than mobile.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 10` using the following build:

```
1.21.74 CR: 89.0.4389.72
```

**`1.21.73 CR: 89.0.4389.72`** | **`1.21.74 CR: 89.0.4389.72`**
--------------------------------|------------------------------------
![Screenshot_20210306-173938_Brave](https://user-images.githubusercontent.com/2602313/110223942-7efac780-7ea5-11eb-8cfd-d2bc34e134d0.jpg)  | ![Screenshot_20210306-174342_Brave](https://user-images.githubusercontent.com/2602313/110223944-81f5b800-7ea5-11eb-92a6-9e246514a22c.jpg)

**Comment by kjozwiak** [comment]
Looks the issue still happens after you refresh the page multiple times. Quickly talked to @SergeyZhukovsky and this appears t be the same issue that the `Skip Ads` issue TY is experiencing. Seems like some type of race condition where the script either loads to early or to late and the ad gets through. Exampe:

* `1.21.74 CR: 89.0.4389.72` - Reproduced
* `1.21.73 CR: 89.0.4389.72` - Reproduced
* `1.20.108 CR: 88.0.4324.182` - Reproduced

![image](https://user-images.githubusercontent.com/2602313/110225616-45ca5380-7eb5-11eb-8ad0-47389acf8fc1.png)

I'll file an issue re: the cosmetic filtering race conditions that Brave seems to experience.

**Comment by ryanbr** [comment]
I got a whitespace issue in Beta/Nightly @SergeyZhukovsky   (unfortantly my Brave nightly was having issues with extensions, so just tested in Chrome). From my screenshot below `##+js(acis,..)` was called/inited a few times (6) on the home page. Is our code doing the same?

![reuters-ads-issue](https://user-images.githubusercontent.com/1659004/110226383-82e52300-7f53-11eb-8000-d733ead6042e.png)
