### ISSUE TITLE
Add support for Gemini for rewards external wallets

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#14629]
Refer to https://github.com/brave/security/issues/494 -

- For Spec
- Security Model

**Comment by LaurenWags** [comment]
Logged https://github.com/brave/brave-browser/issues/17161 for follow up. Per discussion with @jumde and @Miyayes I have marked this issue `release-notes/exclude`, and the new follow up issue is `release-notes/include`.

@brave/legacy_qa the test plan for this issue is a general sanity check/quick regression of Rewards functionality. Gemini specific functionality will be tested as part of the above follow up issue.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.28.92 Chromium: 92.0.4515.107 (Official Build) beta (64-bit)
-- | --
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | Windows 10 OS Version 2004 (Build 19041.1110)

```
Performed regression check on Rewards as per the https://github.com/brave/brave-browser/issues/14629#issuecomment-886636736
- Confirmed AC is working as expected
- Confirmed one-time tips and recurring Tips are working as expected
- Confirmed verified checkmark is shown in BR panel for verified pubs
- Confirmed `This creator is currently not configured to receive tips from your wallet` message is shown in BR panel and tipping banner for nonverified pubs
- Confirmed tips sent to non-verified pubs are listed in the Pending contributions list
- Confirmed `Token Grants Claimed`, `Auto-Contribute`, `Monthly Contributions` and `One-time Tips` are shown correctly in the Rewards summary section
- Confirmed `General info`, `Promotions`, `Contributions`, and `Event logs` are shown in brave://rewards-internals/
- Confirmed `Transactions`, `Monthly Contributions`, `Auto-Contribute` and `One-time Tips` are shown correctly in the monthly statement
