### ISSUE TITLE
Import local files to ipfs

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#15078]
![image](https://user-images.githubusercontent.com/2965009/113345745-8d6cbf80-933b-11eb-8c36-4c666bcbd31a.png)

## Description 

Add IPFS submenu to the main app menu and add an item to import local file to ipfs. 
Copy sharable link if import successful

## Expected result:

File accessable by public gateway sharable link

**Comment by lidel** [comment]
- Shareable link should use Gateway selected by user or `dweb.link` if no choice was made.
- If a single file was imported, copy direct link that looks like this: `https://dweb.link/ipfs/{fileCid}?filename={filename}`
- If you want to support import of multiple files at the same time, then you copy the CID of the root directory  `https://dweb.link/ipfs/{dirCid}`
- Prewarm shared gateway  link
  - Initial load of shared link may take time (gateway needs to find content first, and fetch it), so sending asynchronous HTTP HEAD to the gateway speeds things up (eg. `https://dweb.link/ipfs/{cid}`)
  - It is acceptable because it only triggers content lookup that would happen anyway after other person opens shared link, and no privacy is decreased, because gateway will find the IP of original provider anyway.

**Comment by rebron** [comment]
cc: @karenkliu

**Comment by stephendonner** [comment]
Verified `PASSED` using https://github.com/brave/brave-core/pull/8423 with build

Brave | 1.25.28 Chromium: 90.0.4430.72 (Official Build) nightly (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:
1. loaded `ipns://en.wikipedia-on-ipfs.org`
2. clicked on `Use a local node`
3. waited until installation and configuration finished
4. loaded `https://archive.org/details/spellbound1945_202001`
5. context-clicked on the `MPEG4` link and chose `Save link as...`
6. saved `Spellbound (1945, USA) Director Alfred Hitchcock Starring Ingrid Bergman, Gregory Peck - Film Noir.mp4` to desktop
7. clicked the hamburger menu, chose top-level `IPFS > Share Local File using IPFS`
8. chose `Spellbound (1945, USA) Director Alfred Hitchcock Starring Ingrid Bergman, Gregory Peck - Film Noir.mp4`
9. waited
10. once I got the system notification for the shared IPFS-content link, I pasted it from clipboard into Slack
11. on my Windows 10 machine, using `nightly`, clicked on the `https://dweb.link/ipfs/QmfRpQsfixeYHbJF2vqQH4ZBJ8DWmVTXX8oKpoYGZLT2qJ?filename=Spellbound+(1945%2C+USA)+Director+Alfred+Hitchcock+Starring+Ingrid+Bergman%2C+Gregory+Peck+-+Film+Noir.mp4` link and waited
12. it took around 10 minutes (as @spylogsster said) for the link to resolve and then it quickly downloaded and started playing on my Windows 10 machine

example | example | example | example
---------|----------|---------|----------
<img width="1312" alt="Screen Shot 2021-04-21 at 9 04 44 AM" src="https://user-images.githubusercontent.com/387249/115587514-a1447b00-a282-11eb-8303-4890360af8e9.png"> | <img width="1591" alt="Screen Shot 2021-04-21 at 8 55 15 AM" src="https://user-images.githubusercontent.com/387249/115587508-a0134e00-a282-11eb-9f05-2a8d094a0f41.png"> | <img width="1680" alt="Screen Shot 2021-04-21 at 9 18 02 AM" src="https://user-images.githubusercontent.com/387249/115587521-a1dd1180-a282-11eb-84c3-9e2391ce891a.png"> | ![spellbound](https://user-images.githubusercontent.com/387249/115587890-05ffd580-a283-11eb-8e7f-75b145c9405e.png)
