### ISSUE TITLE
Incorporate "debouncing" lists as part of top-level domain blocking

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#15090]
Follow up / related to top level domain blocking: https://github.com/brave/brave-browser/issues/14134

For some of the bounce tracking cases top level domain blocking is trying to guard against, we can solve them without bothering users by automatically following the bounce to URLs for them.  For example, common pattern:

1. User clicks link, intending to go to destination.org
2. They are instead taken to an intermediate bounce-tracking URL like track.org?id=<click_id>&dest=destination.org
2. track.org records the click event and then forwards to destination.org

@fmarier and @diracdeltas have found several lists that identify the above cases and allow for them to be automatically skipped.

It would be neat to incorporate these lists into (or along side) the top-level domain blocking feature, so that we could warp users past the well-know trackers, while having domain blocking still in place to protect against the more sophisticated or less well known cases.

**Comment by fmarier** [comment]
Here are the three lists I mentioned on https://github.com/brave/security/issues/316#issuecomment-812278055:

- https://github.com/newhouse/url-tracking-stripper/blob/master/assets/js/redirects.js
- https://github.com/apiraino/link_cleaner/blob/a44eba9202c76ef562bf354bd5267cd71548427a/background.js#L194-L300
- https://github.com/jkehler/unshortenit/tree/master/unshortenit/modules

**Comment by Dryader** [comment]
Hi there. Just out of curiosity, I've seen this extension being recommended, would that incorporate the same features you guys are planning to implement into brave? (Not extremely knowledgeable on the topic just curious.) [https://github.com/ClearURLs/Addon](url)

**Comment by fmarier** [comment]
Thanks for that @Dryader . There are indeed some more usable rules in that extension: https://github.com/ClearURLs/Rules/blob/master/data.json (see `redirections`)

**Comment by fmarier** [comment]
@antonok-edm found another one: https://github.com/Sainan/Universal-Bypass/blob/master/rules.json

**Comment by kjozwiak** [comment]
@brave/legacy_qa the above changes are already live as we enabled debouncing via Griffin. I went through verifications via https://github.com/brave/brave-variations/pull/195#issuecomment-1014872639 on Nightly but it's worth going through a quick check to make sure it's working on the release channel.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.34.81 Chromium: 97.0.4692.99 (Official Build) (x86_64)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | macOS Version 11.6.1 (Build 20G224)

Followed the verification steps from https://github.com/brave/brave-variations/pull/195#issuecomment-1014872639.

`Enabled`

Launched Brave using `--enable-logging=stderr --v=1 --variations-server-url=https://variations.bravesoftware.com/seed` and verified the following:

* ensured that `Brave Local Data Updater` > `Brave Local Data Updater - Version: 1.0.45` which was the version that wasn't working when initially running through the above. Most recent version appears to be `Brave Local Data Updater - Version: 1.0.52` which has the latest debounce list
* ensured that `BraveDebounceStudy:Enabled` under `brave://version` (after restarting twice due to a Griffin limitation)

example | example
---------|---------
<img width="859" alt="Screen Shot 2022-01-20 at 2 04 32 PM" src="https://user-images.githubusercontent.com/387249/150431001-204649ee-7b8e-4a9e-97e7-fdfd0f30e0fe.png"> | <img width="859" alt="Screen Shot 2022-01-20 at 2 05 13 PM" src="https://user-images.githubusercontent.com/387249/150431019-c051b989-2388-48eb-9df1-492c79841076.png">



Went through the cases under `https://dev-pages.brave.software/navigation-tracking/debouncing.html` and ensured the following:

`YT`

* ensured that clicking on `Run` returned to the test page and `Observed Referrer --> dev-pages.brave.software`

```
[7296:259:0120/140556.291001:VERBOSE1:debounce_throttle.cc(51)] SiteForCookies: {site=https://youtube.com; schemefully_same=true}
[7296:259:0120/140556.291095:VERBOSE1:debounce_throttle.cc(60)] Debouncing rule applied: https://www.youtube.com/redirect?q=https%3A%2F%2Fdev-pages.brave.software%2Fnavigation-tracking%2Fdebouncing.html%3Fcomplete -> https://dev-pages.brave.software/navigation-tracking/debouncing.html?complete
[7296:259:0120/140556.291165:VERBOSE1:debounce_throttle.cc(76)] SiteForCookies: {site=https://brave.software; schemefully_same=true}
```

`Reddit`

 * ensured that clicking on `Run` returned to the test page and `Observed Referrer --> dev-pages.brave.software`

```
[7296:259:0120/140620.161242:VERBOSE1:debounce_throttle.cc(51)] SiteForCookies: {site=https://reddit.com; schemefully_same=true}
[7296:259:0120/140620.161318:VERBOSE1:debounce_throttle.cc(60)] Debouncing rule applied: https://out.reddit.com/test?url=https%3A%2F%2Fdev-pages.brave.software%2Fnavigation-tracking%2Fdebouncing.html%3Fcomplete -> https://dev-pages.brave.software/navigation-tracking/debouncing.html?complete
[7296:259:0120/140620.161365:VERBOSE1:debounce_throttle.cc(76)] SiteForCookies: {site=https://brave.software; schemefully_same=true}
```

`Disabled`

Launched Brave using `--enable-logging=stderr --v=1 --variations-server-url=https://variations.bravesoftware.com/seed` and ensured the following:

`YT`

 * ensured that clicking on `Run` didn't return to the test page and `Observed Referrer --> https://www.youtube.com` when clicking on GO TO SITE
 * went through the logs and ensured that Debouncing rule applied wasn't visible as no rules are being applied

`Reddit`

 * ensured that clicking on Run didn't return to the test page (no debouncing occurring)
 * went through the logs and ensured that Debouncing rule applied wasn't visible as no rules are being applied

**Comment by kjozwiak** [comment]
Labelled as `QA/Blocked` till we get https://github.com/brave/brave-variations/pull/195 pushed into `production` via https://github.com/brave/brave-variations/blob/production/seed/seed.json.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-variations/pull/212 was uplifted into `production`.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.34.81 Chromium: 97.0.4692.99 (Official Build) (x86_64)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | macOS Version 11.6.1 (Build 20G224)

Followed the verification steps from https://github.com/brave/brave-variations/pull/195#issuecomment-1014872639.

`Enabled` - the default now for `PRODUCTION`

Launched Brave using only `--enable-logging=stderr --v=1 ` and ensured the following::

* ensured that `Brave Local Data Updater` > `Brave Local Data Updater - Version: 1.0.45` which was the version that wasn't working when initially running through the above. Most recent version appears to be `Brave Local Data Updater - Version: 1.0.53` which has the latest debounce list
* ensured that `BraveDebounceStudy:Enabled` under `brave://version` (after restarting twice due to a Griffin limitation)

`brave://components` | `brave://version
---------|---------
<img width="985" alt="Screen Shot 2022-01-20 at 10 09 49 PM" src="https://user-images.githubusercontent.com/387249/150476142-ebed6b46-28ef-483a-a651-f5d8dcacd92b.png"> | <img width="985" alt="Screen Shot 2022-01-20 at 10 08 51 PM" src="https://user-images.githubusercontent.com/387249/150476165-f8246884-5bb3-46b6-933b-65539ef75235.png">




Went through the cases under `https://dev-pages.brave.software/navigation-tracking/debouncing.html` and ensured the following:

`YT`

* ensured that clicking on `Run` returned to the test page and `Observed Referrer --> dev-pages.brave.software`

```
[7265:259:0120/221416.456714:VERBOSE1:debounce_throttle.cc(51)] SiteForCookies: {site=https://youtube.com; schemefully_same=true}
[7265:259:0120/221416.456771:VERBOSE1:debounce_throttle.cc(60)] Debouncing rule applied: https://www.youtube.com/redirect?q=https%3A%2F%2Fdev-pages.brave.software%2Fnavigation-tracking%2Fdebouncing.html%3Fcomplete -> https://dev-pages.brave.software/navigation-tracking/debouncing.html?complete
[7265:259:0120/221416.456810:VERBOSE1:debounce_throttle.cc(76)] SiteForCookies: {site=https://brave.software; schemefully_same=true}

```

`Reddit`

 * ensured that clicking on `Run` returned to the test page and `Observed Referrer --> dev-pages.brave.software`

```
[7265:259:0120/221524.353302:VERBOSE1:debounce_throttle.cc(51)] SiteForCookies: {site=https://reddit.com; schemefully_same=true}
[7265:259:0120/221524.353357:VERBOSE1:debounce_throttle.cc(60)] Debouncing rule applied: https://out.reddit.com/test?url=https%3A%2F%2Fdev-pages.brave.software%2Fnavigation-tracking%2Fdebouncing.html%3Fcomplete -> https://dev-pages.brave.software/navigation-tracking/debouncing.html?complete
[7265:259:0120/221524.353395:VERBOSE1:debounce_throttle.cc(76)] SiteForCookies: {site=https://brave.software; schemefully_same=true}
```
