### ISSUE TITLE
Add an exception for Fathom and Plausible

### ISSUE THREAD

**Issue by bcye** [brave/brave-browser#15129]
[Fathom](https://usefathom.com) and [Plausible](https://plausible.io) are currently blocked by Brave as trackers. There have been exceptions added for Yandex ([brave/adblock-lists#490](https://github.com/brave/adblock-lists/pull/490)), so I don't see a reason to block analytics tool that put their effort into preserving the privacy of users.

**Comment by ryanbr** [comment]
cc; @pes10k

**Comment by pes10k** [comment]
Hi @bcye , there are two differences here between the examples you mention, and Yandex.

1) Brave has a contractual agreement with Yandex that restricts what Yandex can do to Brave users.  That contractual agreement allows us to be less (though not zero) concerned about Yandex scripts switching out from underneath us (in privacy relevant ways)
2) In general, we try to make exceptions as narrow as possible (as you can see on the [startpage exception](https://github.com/brave/adblock-lists/pull/490/files#diff-8c5c45946309d357cce0d8e9a11d1a0ee5013d8ae01fe4f45c1da5bc7b92406dR21)).  We originally did the same for yandex, but since yandex operates under a large number of tlds we weren't able to easily.  We're exploring adding filter list syntax in adblock-rust that'd allow us to limit an exception / rule to a domain under any TLD (instead of having to exhaustively list all TLDs), and once we've sorted that out will similarly limit the yandex rules.

But, TL;DR; we are extremely cautious about making exceptions, since even if we audit scripts when deciding those exceptions, scripts can (and do) change underneath us.  So, we try to limit those exceptions to cases where we have contractual agreements, or those exceptions are needed to unbreak sites.

Hope that helps explain our policy.  Thank you for your comment!

**Comment by bcye** [comment]
Hi @pes10k thanks for your reply, didn't know about the backstory with Yandex. What's the difference between aggressive and standard tracker blocking? I was wondering, because maybe this could be a choice offered to the user. (e.g. "do you want to add an exception for privacy-preserving analytics?")

**Comment by pes10k** [comment]
Right now the only difference between standard and aggressive blocking is how we treat first party cosmetic blocking.  In standard blocking mode we try to only hide 3p ads, in aggressive blocking mode we don't worry about the distinction.  More information here: https://brave.com/privacy-updates-2/

I understand the appeal of an "add an exception for privacy-preserving analytics?" feature, but the reason we're hesitant to add such a feature is that i) we don't have a way to easily distinguish privacy-preserving analytics from other analytics, ii) there have been cases of folks hiding bad code behind "good", excepted resources, and iii) there have been cases of companies that were privacy respecting at one point, changing their code to be privacy harming.  So, unless we have a legal commitment from a company (usually a partner) we're hesitant to add exceptions.

That said, we have suggested (and received some positive reception) from upstream list curators (that Brave draws on) to label filter lists with such information, which would open up some options for Brave users.  We've also considered extending adblock-rust support to allow audited code, locked down by SRI hash, but thats difficult to do for technical reasons (that information is not easily available to the network process in chromium).  Anyway, all that is to say, we're considering different things, but we don't have any easy solutions that don't risk harming / biting brave users at the moment, and most of our engineering time at the moment is being spent adding new privacy protections and blocking capabilities. So, most i can say at the moment is we're looking into it.

One last thing I can share is that many folks like Brave's blocking for performance improvements, in addition to privacy improvements.  So, we're hesitant (not hard against it, but hesitant) to make changes that would reduce Brave's performance to load scripts that don't primarily benefit the user.

Anyway, none of that is a clear answer, but i hope it better explains the trade offs and why we're cautious about adding exceptions
