### ISSUE TITLE
remove Google's sign-in workaround

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#1516]
## Test plan
See https://github.com/brave/brave-core/pull/629

## Description 
Google added a new pref for sign-in with Chromium: 70.0.3538.45
<img width="698" alt="screen shot 2018-10-10 at 10 46 16 pm" src="https://user-images.githubusercontent.com/5951041/46783312-9d613680-ccde-11e8-969e-7c891fbcef76.png">

Remove/hide from UI, default off to account for issues.

**Comment by petemill** [comment]
@rebron I don't think we want to remove the Prediction service settings. That was added back in to enable users to have autocomplete for search terms in the Location Bar. If we remove that (opt-in for Brave) then we won't be offering an autocomplete search term feature.

That at least would give us feature parity with muon.

"Allow Brave sign-in" - since that doesn't do anything then we should for sure remove it (and default to off in case of side-effects)

"Use a prediction service to load pages more quickly"
"Allow sites to check if you have payment methods saved"
- We don't provide these features in muon, but are we sure we don't want to offer them to our users?

**Comment by bbondy** [comment]
Agree with @petemill on everything, I think we just want to remove the allow Brave sign-in

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

https://github.com/brave/brave-core/pull/629
