### ISSUE TITLE
Tame Brave Rewards when there are multiple user profiles

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#15363]
## Description

When a user has multiple user profiles with Brave Rewards enabled in the same Brave installation, unexpected or strange behaviors may occur (and have been frequently observed). Presumably, this is because certain parts of Rewards run globally, while other parts operate at the user profile level, leading to various unexpected behaviors or conflicts. 

## Solution

Requires investigation to clearly map out and demarcate how Brave Rewards should function when there are multiple user profiles.

**Comment by Miyayes** [comment]
@brave/rewards-client and @tmancey, would you be able to chime in here for `needs-investigation`? If we can clearly separate what is global vs. what is profile-specific, we can move forward with a plan :).

**Comment by tmancey** [comment]
Due to privacy, the state has to be stored in a profile. We could limit how many profiles can run ads at any one time with rewards or just limit rewards to the main profile. However, many users share their computer and have separate profiles.

**Comment by tmancey** [comment]
cc @bridiver just incase i've misunderstood previous conversations we have both had

**Comment by bridiver** [comment]
@Miyayes can you give specific examples of unexpected or strange behavior?

**Comment by Brave-Matt** [comment]
@bridiver I can try and dig some of these cases up but may take a while. That said, based on your asking, is the expected behavior such that each profile _should_ function the same way as each browser instance?

**Comment by bridiver** [comment]
@Brave-Matt I'm not sure I'm understanding what you're asking, but each profile should be considered as a separate entity, otherwise it defeats the entire purpose of having multiple profiles. They are meant to be used by different people and so sharing rewards across them wouldn't make sense imo. If people are using them differently, that is an edge case. In Chrome the menu item is "People" and I think we only changed it to "Profile" for Tor and should probably change it back now cc @darkdh

**Comment by Miyayes** [comment]
Closing and will file something more specific the next time this comes up.
