### ISSUE TITLE
Toned down interstitial text and icon for top-level blocking.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#15433]
This is a sub-issue to partially address https://github.com/brave/brave-browser/issues/15189

Only fix text and icon, but do not change the styling.

**Comment by kjozwiak** [comment]
Removing the `OS/Android` label due to `aggressive` mode currently missing from shields on Android. I tried enabling it via `#brave-domain-block` but that didn't seem to work. Without `aggressive` mode, there doesn't seem to be a way to trigger the needed interstitial page. @srirambv let me know if `#brave-domain-block` works for you re: seeing the interstitial page when enabled. If it works for you, please re-add the `OS/Android` label. CCing @pes10k @fmarier

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.24.81 Chromium: 90.0.4430.93 (Official Build) (x86_64)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}

1. Started Brave
2. Went to `Settings` > `Shields`
3. Changed `Trackers & ads blocked` setting to `Aggressive`
4. Navigated to `https://adcash.com`
5. Verified that the interstitial page that shows up has the updated text, icon, and that the `Proceed` button is the default
6. Verified that `Go back` and `Proceed` buttons worked correctly

Checked both light and dark themes

light | dark
-----|-----
<img width="1752" alt="Screen Shot 2021-04-29 at 9 48 56 PM" src="https://user-images.githubusercontent.com/387249/116650010-2be94200-a935-11eb-99cd-df09f28799c3.png"> | <img width="1752" alt="Screen Shot 2021-04-29 at 9 49 06 PM" src="https://user-images.githubusercontent.com/387249/116650016-2e4b9c00-a935-11eb-979c-f46c1ce9f371.png">
