### ISSUE TITLE
Brave Rewards - BAT disappeared

### ISSUE THREAD

**Issue by Cristy94** [brave/brave-browser#15451]
## Description 

My BAT is gone. I had 1.5 BAT and now it was reset. I did not update or modify the browser in any way. It still shows all the ads seen, but the estimated pending rewards are gone.

![image](https://user-images.githubusercontent.com/1384885/115749270-3afd4c80-a397-11eb-9f87-1a6b7c6cfe6e.png)

![image](https://user-images.githubusercontent.com/1384885/115749324-45b7e180-a397-11eb-9464-9f50d887354c.png)

I tried restarting the browser and rebooting the PC but the problem persists.
## Steps to Reproduce

   1. Open browser
   2. Open brave rewards 

## Actual result:

Previously earned BAT is gone.

## Expected result:

BAT persists and is not reset.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | Windows 10 OS Version 2009 (Build 19042.928)
JavaScript | V8 9.0.257.17

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes

**Comment by Cristy94** [comment]
Strange, after creating this issue the BAT is showing again in the rewards ads panel, but not in the address bar pop-up:

![image](https://user-images.githubusercontent.com/1384885/115750104-19509500-a398-11eb-9fd1-855318a1701d.png)
![image](https://user-images.githubusercontent.com/1384885/115750137-2077a300-a398-11eb-983b-6da7762d31c1.png)

**Comment by JorikSonneveld** [comment]
I have the same problem:
![image](https://user-images.githubusercontent.com/26434356/115755617-d2659e00-a39d-11eb-835c-bbc10ed420a7.png)
This always automatically recovers for me but the time differs, sometimes it is fixed in just a few seconds and sometimes it stays for hours.
In this time I can get notification ads but new tab background ads do not count.

**Comment by Miyayes** [comment]
To clarify, the "address bar popup" (aka the bluish purple) is **not** your estimated earnings. That's your finalized balance (which is different). The estimated earnings in the ads panel in brave://rewards is calculated server-side, so if there are connectivity issues, it'll report incorrectly. (This is fixed with https://github.com/brave/brave-browser/issues/15460.)
