### ISSUE TITLE
Return constant result for navigator.mimeTypes and navigator.plugins

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#1549]
Navigator.mimeTypes and Navigator.plugins increases fingerprinting risk. It is disabled in `browser-laptop`

See here: https://trac.torproject.org/projects/tor/ticket/17207

**Comment by jumde** [comment]
Looks like I rushed on this one. We don't return constant result for mimeTypes and plugins in `browser-laptop`. This might cause `web-compat` issues.

May be we can put this behind the fingerprinting flag like firefox? cc: @tomlowenthal @diracdeltas 

https://web.archive.org/web/20170204172033/https://bugzilla.mozilla.org/show_bug.cgi?id=1281963

**Comment by diracdeltas** [comment]
We do return empty (or at least are supposed to) in browser-laptop for plugins and mimeTypes until Flash is explicitly allowed. The purpose of this is to trigger HTML5 fallback on sites that would otherwise require Flash. We should try to copy that behavior here.

(Plugins and mimeTypes should always return empty in Tor windows though. cc @riastradh-brave )

**Comment by jumde** [comment]
Sounds good, I'll update the PR.

**Comment by jumde** [comment]
Checking!

**Comment by srirambv** [comment]
Verification passed on

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/50590317-72871880-0eb0-11e9-846c-2949c2dbb936.png)
*  Verified only non flash test steps for Linux
