### ISSUE TITLE
Closing and reopening the browser resets cookie settings.

### ISSUE THREAD

**Issue by NotRexButCaesar** [brave/brave-browser#15588]
## Description 
Closing and reopening the browser resets cookie settings.

## Steps to Reproduce
 1. change settings>additional settings>privacy and security>cookies and other site data to "block all cookies"
 2. exit the browser
 3. open the browser
 4. settings are reset

## Actual result:
settings are reset

## Expected result:
settings persist across restart.

## Reproduces how often: 
occurs 100% of the time

## Brave version (brave://version info)

Brave | 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)
-- | --
Revision | 4df112c29cfe9a2c69b14195c0275faed4e997a7-refs/branch-heads/4430@{#1348}
OS | Windows 10 OS Version 2009 (Build 19042.928)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
no
- Does the issue resolve itself when disabling Brave Rewards? 
no
- Is the issue reproducible on the latest version of Chrome? 
n

**Comment by rebron** [comment]
![Screen Shot 2021-05-03 at 8 34 33 AM](https://user-images.githubusercontent.com/5951041/116897775-852dcb80-abea-11eb-881b-c74a9e88d5ea.png)

I tested on 1.23.75 on Windows and macOS and saw that this setting remained and didn't reset on restart. @NotRexButCaesar Do you have settings set to clear on exit as option? Shouldn't reset settings otherwise.

![Screen Shot 2021-05-03 at 8 36 38 AM](https://user-images.githubusercontent.com/5951041/116898019-c1f9c280-abea-11eb-9c6b-8d7cbcc766ab.png)

**Comment by NotRexButCaesar** [comment]
I do.  I guess the error was in the chair.
