### ISSUE TITLE
What's the right flow to watch for changes 

### ISSUE THREAD

**Issue by DaveLomber** [brave/brave-browser#15828]
Hi everyone, 

I'm trying to understand the flow regarding how to develop the brave-browser, 
mainly  - how to apply changes and get them immediately w/o waiting form complete rebuild 

It's not clear at all from the readme, could someone shed more light how to properly do it.

should it be like this?:
- `npm run build -- Debug`
- `npm start Debug` so then it will watch for changes automatically
- and then once the development is done, we just create a release build `npm run build Release`

Is this a correct flow?

**Comment by bsclifton** [comment]
Hi there - sorry for the long delay in responding

Basically, any changes to C++ will require a build. In your example above, you'll need to do `npm run build -- Debug` each time there is a change. The build will be incremental, meaning it won't compile everything (only what is needed because of the change). The initial compile is what takes the most time

You don't need to do a Release build unless you're wanting to specifically test that case. I would personally omit any build type (ex: don't specify Debug or Release) and it will default to "Component". More info about that here:
https://github.com/brave/brave-browser/blob/master/README.md#build-brave

Hope this helps answer your question!

**Comment by DaveLomber** [comment]
Thanks @bsclifton for the detailed explanation.

I already came up to the same process you described, anyway thanks for the guide
