### ISSUE TITLE
Fail to Protect Privacy from Fingerprintjs

### ISSUE THREAD

**Issue by BRAVERaaa** [brave/brave-browser#15825]
## Description 

Fail to Protect Privacy from Fingerprintjs

## Steps to Reproduce

   1. Open https://fingerprintjs.com/
   2. Clear all cookies and cache
   2. Close all tabs and close browser
   3. Restart and open https://fingerprintjs.com/

## Actual result:

![image](https://user-images.githubusercontent.com/84130904/118118478-91522e00-b41f-11eb-95e7-8a1af5b87bb6.png)
(I may be tracked)

## Expected result:
Every time I clean cookies and cache then restart browser, the ID shown should be different.

## Reproduces how often: 

Every time.

## Desktop Brave version:

Brave	1.24.84 Chromium: 90.0.4430.93 (x64)

## Android Device details:
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet):Phone
   - Android version:Android 11 Brave 1.24.84 Chromium 90.0.4430.93 (x64)

## Version/Channel Information:

Release
- Can you reproduce this issue with the current release? 
- Yes
- Can you reproduce this issue with the beta channel? 
- Yes
- Can you reproduce this issue with the nightly channel? 
- Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- Yes (This should be protected by Brave)

**Comment by srirambv** [comment]
cc: @pes10k

**Comment by pes10k** [comment]
Thank you for raising this issue @BRAVERaaa! I'm going to close the issue though, for the same reasons this previous issue was closed https://github.com/brave/brave-browser/issues/14031

The short of it is that the page you're referencing plays a whole bunch of games that aren't related to fingerprinting, so that their commercial product looks more impressive.  For Brave users their tracking is basically just IP at this point.  I expect if you visit in the same browser, but from different profiles and IPs (say in Tor mode and standard mode) you'll see they're not actually able to fingerprint you (and that they're not actually using fingerprinting values in the first place, but other unrelated identifiers like IP) 

Hope that helps, and feel free to reopen the issue if you see anything different than the above!

**Comment by BRAVERaaa** [comment]
@pes10k 
Sorry for disturbing, but something different happens.
Few weeks ago, every time I clean cookies and cache then restart browser, the ID shown was different, and the IDs between normal window and incognito window were different as well.
But now, I try it again, the IDs between normal window and incognito window are the same!!! It is amazing!!!
I even have tried to change my ip, but the ID is always the same.
![PNG1](https://user-images.githubusercontent.com/84130904/118241431-b5b91380-b4ce-11eb-93cc-4f4db2770e4e.png)
![PNG2](https://user-images.githubusercontent.com/84130904/118241453-bd78b800-b4ce-11eb-960d-513ee92cb159.png)



Fingerprintjs seems to have updated. Maybe this is the cause.
![PNG3](https://user-images.githubusercontent.com/84130904/118241694-07fa3480-b4cf-11eb-80cc-8bcc9206bbb3.png)

**Comment by pes10k** [comment]
Hi @BRAVERaaa , thanks for the heads up!  I expect it might be related to this https://github.com/brave/brave-browser/issues/15875, in which case, we're on the case and hope to be able to share an expected solution in the next day or three.

cc: @ShivanKaul

**Comment by Andromeda606** [comment]
same. 
Despite the hash changes on this site, there is no change in software that provides really high protection like gologin. The site records everything down to audio data.
