### ISSUE TITLE
APKs no longer available outside of Google play store

### ISSUE THREAD

**Issue by sheddup** [brave/brave-browser#15878]
Please release APKs for users that don't want to use Google Play store including third party play store clients like AuroraStore.

**Comment by Tobi823** [comment]
Hi, I'm the maintainer of the app FFUpdater on F-Droid (https://f-droid.org/en/packages/de.marmaro.krt.ffupdater/) - an updater for privacy friendly browsers. I want to support the usage of Brave, Firefox etc. on ungoogled Android smartphones.

Can you publish the APK files on GitHub again? FFUpdater needs these files to install/update Brave. The solution with "bundletool install-apks" does not work for FFUpdater because:
- I don't want to compile and upload the APK files to a filehoster because of security, work and costs.
- I don't have the signing keys -> the generated APK files can't be used to update an older version of Brave
- Bundling "bundletool" with FFUpdater is a really bad idea because of the size (25MB) and missing a dedicated version for Android

I know that the budget is limited and that many users use the Google Play Store. Nevertheless, would it be possible to publish the APK files back on GitHub?

**Comment by sheddup** [comment]
appears to be fixed

**Comment by AeOeAa** [comment]
Fixed? I don't see an APK under [Release v1.24.86](https://github.com/brave/brave-browser/releases/tag/v1.24.86)

**Comment by AeOeAa** [comment]
Fixed? I don't see an APK under [Release v1.24.86](https://github.com/brave/brave-browser/releases/tag/v1.24.86)

**Comment by bsclifton** [comment]
@AeOeAa it may not be there for the 1.24 release you shared, but it should be in the next release (and it's already there for Beta / Nightly builds)

**Comment by marcdw1289** [comment]
I can confirm, things are back to normal. Release Versions 1.25.66 and 1.25.68 install and run just fine. Good.

**Comment by bsclifton** [comment]
@androidacy-user can you share an example of where it's missing? I'm seeing them on https://github.com/brave/brave-browser/releases

**Comment by bsclifton** [comment]
@androidacy-user OK great - thanks for sharing, RE: `latest` tag 👍 I reported to our devops team as this was not intentional. The build job may have failed to upload the binaries (service outage, etc) and it didn't get restarted
