### ISSUE TITLE
BAT --> USD oddities with custom tipping

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#15908]
## Description 

I noticed two odd things when clicking on the double arrow to change from entering BAT to USD for the custom tipping amount:

1. After I enter a value (in BAT) and switch to USD for custom tip entry, the USD is showing 5 decimal places. 
2. Additionally, when you take focus away from the USD selection after doing the above, the value changes

## Steps to Reproduce

   1. Clean profile 1.25.x, staging env
   2. Enable Rewards, claim UGP grant
   3. Navigate to a site and open either one time or monthly tip banner
   4. Click on Custom Tip Amount 
   5. Enter a value in BAT (ex. 2.75 BAT)
 
<img width="342" alt="1" src="https://user-images.githubusercontent.com/28145373/118560147-03d05000-b737-11eb-80b8-13863075642e.png">

   6. Click the double arrow between BAT and USD values
   ---> Notice that USD has 5 decimal places, BAT value still retains 2.75

<img width="349" alt="2" src="https://user-images.githubusercontent.com/28145373/118560155-08950400-b737-11eb-9b8f-0b11afb32318.png">

   7. Click elsewhere to take focus away from the USD field
   ---> Note that the USD value has changed, as has the BAT value

<img width="340" alt="3" src="https://user-images.githubusercontent.com/28145373/118560214-21051e80-b737-11eb-969c-444dd7331d08.png">

## Actual result:

See above

## Expected result:

I expected USD field to only have 2 decimal values and for the BAT field not to change

## Reproduces how often: 

100% (although you may need to use different BAT values depending on conversion rates)

## Brave version (brave://version info)

```
Brave | 1.25.60 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;beta&nbsp;(x86_64)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | macOS Version 10.15.7 (Build 19H1030)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?  n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @zenparsing @Miyayes @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Windows 10 x64 - Brave version 1.25.60` - The issue is reproducible even if you just switch between the windows (using ALT+TAB shortcut keys), which decreases the USD value. With respect to USD value, the BAT value is also decreased from 2.75 BAT to 1.75 BAT which looks really odd.

Step1: Enter `2.75 BAT` and swap USD and BAT
![image](https://user-images.githubusercontent.com/38657976/118620023-c0cbb680-b7e2-11eb-83c1-7db608f61b3a.png)

![image](https://user-images.githubusercontent.com/38657976/118619044-d8ef0600-b7e1-11eb-9388-958065902138.png)

Step2:  Used `ALT+TAB` to switch between windows
![image](https://user-images.githubusercontent.com/38657976/118619187-fb811f00-b7e1-11eb-8725-8143d0658865.png)

Step3: Used `ALT+TAB` to switch between windows
![image](https://user-images.githubusercontent.com/38657976/118619380-29fefa00-b7e2-11eb-94ca-25fbe36fce29.png)

Step4: Used `ALT+TAB` to switch between windows
![image](https://user-images.githubusercontent.com/38657976/118619529-4e5ad680-b7e2-11eb-9970-ecb50bebb206.png)
