### ISSUE TITLE
Recurring custom tips allows exponential values

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#15931]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/15006
Recurring custom tips allows exponential values

## Steps to Reproduce

   1. Clean profile 1.25.x
   2. Enable rewards and claim UGP grants
   3. Open a verified publisher 
   4. Open tipping banner  
   5. Click on Custom tip amount
   6. Enter a random whole number in BAT text field for recurring tips
   7. Entered value isn't truncate to 2 decimal places even after clicking away from the field (inside/outside the banner)

## Actual result:

Recurring custom tips allows exponential values
![Custom recurring tip](https://user-images.githubusercontent.com/38657976/118650533-2f6c3c80-b802-11eb-9c30-056fc0ebf796.gif)

## Expected result:

Values should be truncated to 2 decimal places

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.25.62 Chromium: 90.0.4430.212&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @zenparsing @rebron

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.25.66 Chromium: 91.0.4472.70&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | fe095368270a32c92959403754bf6fd357dd9953-refs/branch-heads/4472@{#1172}
OS | macOS Version 10.15.7 (Build 19H1030)
```

Verified STR from description.

Example | Example | Example
----- | ----- | -----
<img width="1193" alt="1" src="https://user-images.githubusercontent.com/28145373/119515302-be69df00-bd43-11eb-9c0d-6627e64c15f3.png"> | <img width="1196" alt="2" src="https://user-images.githubusercontent.com/28145373/119515306-bf9b0c00-bd43-11eb-928a-0a6dd55cd0c2.png"> | <img width="1194" alt="3" src="https://user-images.githubusercontent.com/28145373/119515316-c0cc3900-bd43-11eb-9801-4e6f79e9c097.png">

Verified that if you attempt to enter a very large USD amount (instead of entering BAT as above), you are still limited to 100 BAT:

Example | Example | Example
----- | ----- | -----
<img width="1196" alt="4" src="https://user-images.githubusercontent.com/28145373/119515345-c6c21a00-bd43-11eb-9639-f50a2f725ef7.png"> | <img width="1193" alt="5" src="https://user-images.githubusercontent.com/28145373/119515356-c7f34700-bd43-11eb-88ac-2e4f2f0013bc.png"> | <img width="1195" alt="6" src="https://user-images.githubusercontent.com/28145373/119515362-c9247400-bd43-11eb-801c-16b38185075e.png">
