### ISSUE TITLE
Get rid of protobufs in P3A pings

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#15967]
For now, a P3A pings consists of a base64-encoded protobuf. 
```
message RawP3AValue {
  fixed64 metric_id = 1;
  bytes p3a_info = 2;
}
```
given that pings are small  we can get rid of protobuf and replace it with simple json.
```
{
  "metric_id" : "hex-encoded-metric-id-string",
  "p3a_info" : "p3a info string" 
}
```

It is suggested to keep p3a string as is, because the current plan is to resurrect prochlo soon, presumbaly prochlo will utilize this format (of everything packed into `p3a_info`) somehow.

**Comment by iefremov** [comment]
cc @aekeus @porteron

**Comment by porteron** [comment]
This will be great for us on the stats side. @iefremov once you have data writing in the new format to the bucket let us know so we can update our aggregator to no longer attempt to decode the data.

**Comment by iefremov** [comment]
since we removed PROCHLO, nothing stops us from killing the "ugly string" (aka `p3a_info`) and making a normal json. I'll update the description with more details.

**Comment by iefremov** [comment]
I'm not sure about release notes for this change, @mattmcalister what do you think?

**Comment by mattmcalister** [comment]
@iefremov just say what it is... `Migrate ping data to json format` or something like that

**Comment by iefremov** [comment]
@mattmcalister I mean, I'm not sure whether this is release-notes/include or /exclude

**Comment by mattmcalister** [comment]
@rebron ...up to you.

**Comment by LaurenWags** [comment]
@iefremov @rillian since this is `QA/Yes`, could we get a test plan for this one? Thanks! cc @GeetaSarvadnya

**Comment by rillian** [comment]
I've added a brief test plan to brave/brave-core#11600.

Sorry about that, and please let me know if you need more details.

**Comment by LaurenWags** [comment]
thanks @rillian! I'll defer to @GeetaSarvadnya to determine if more info is needed. This looks like a good starting point 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.36.87 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1503)

```

**Comment by Uni-verse** [comment]
Verification **Completed** using `1.36.108 Chromium 99.0.4844.51`
OS: `Android ARM`
Device: `Samsung GS 21 `
Firmware: `Android 12`

**PASSED** - Confirm packets to the https://p3a-json.brave.com/ endpoint are in [json format]
**PASSED** - Transmitted values should match what's listed in brave://local-state under p3a.logs.
**PASSED** - Confirm packets to the https://p3a.brave.com/ and https://p2a.brave.com/ endpoints are similar to what sent before the change, encoded as a binary protocol buffer, instead of in a human-readable strings like the json endpoint receives.

![Screen Shot 2022-03-01 at 2 29 26 PM](https://user-images.githubusercontent.com/17885425/156259899-7e7eb227-58fe-4d48-9f6c-582ccec1a7a8.png)
![Screen Shot 2022-03-01 at 2 29 03 PM](https://user-images.githubusercontent.com/17885425/156259982-9c87caa2-4f99-4498-b391-dd6e9df68209.png)
