### ISSUE TITLE
Calculate account statement from locally persisted state

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#16028]

**Comment by jsecretan** [comment]
Sizing at 2 points

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.35.77 Chromium: 97.0.4692.71 (Official Build) beta (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Windows 10 Version 21H2 (Build 19044.1415)

```
Verified the test plan from https://github.com/brave/brave-core/pull/10956

**Comment by GeetaSarvadnya** [comment]
No idea how to test the `Case 26- Verify day parting frequency cap is working as expected`, discussed with @btlechowski he mentioned this got landed without QA involvement. Hence I am skipping the case 26. 

cc: @tmancey @LaurenWags

**Comment by tmancey** [comment]
@GeetaSarvadnya see original day part ticket https://github.com/brave/brave-core/pull/6893 with tests (day  parting is part of the catalog)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.35.98 x64 build

<details>
<summary>Case 1: Confirm user is only rewarded if ads are enabled - <b>Passed</b></summary>

- Verified ads are served only when Ads is enabled 
- Verified users are rewarded for viewing ads
- Verified `Current months earning (estimated)` is shown in `brave://rewards` and in panel
- Verified `Ads received this month` is shown correctly and increments as and when an ad is shown
- Verified disabling ads doesn't reset `Ads received` and `Current month earnings`
</details>

<details>
<summary>Case 2: Confirm users are rewarded after viewing an ad - <b>Passed</b></summary>

- Verified `x amount of BAT` is assigned after view/click/landed or dismissing an Ad

View
```
2022-01-31 03:13:12.319 23064-23064/? V/chromium: [VERBOSE3:ads_impl.cc(762)] Successfully deposited funds for ad_notification with creative instance id c6a6b939-4167-41fb-8a84-1edde6c12250 and view valued at 0.01
2022-01-31 03:13:12.319 23064-23064/? V/chromium: [VERBOSE1:confirmations.cc(69)] Confirming view for ad_notification with transaction id 9300f808-a925-4c4e-8b88-c0c43d0d14f9 and creative instance id c6a6b939-4167-41fb-8a84-1edde6c12250
```
Click
```
2022-01-31 03:13:18.395 23064-23064/? V/chromium: [VERBOSE3:ads_impl.cc(762)] Successfully deposited funds for ad_notification with creative instance id c6a6b939-4167-41fb-8a84-1edde6c12250 and click valued at 0
2022-01-31 03:13:18.395 23064-23064/? V/chromium: [VERBOSE1:confirmations.cc(69)] Confirming click for ad_notification with transaction id 36ef3f09-3942-41d7-95a0-ddbdb0768023 and creative instance id c6a6b939-4167-41fb-8a84-1edde6c12250
```
Landed
```
2022-01-31 03:13:30.870 23064-23064/? V/chromium: [VERBOSE3:ads_impl.cc(762)] Successfully deposited funds for ad_notification with creative instance id c6a6b939-4167-41fb-8a84-1edde6c12250 and landed valued at 0
2022-01-31 03:13:30.870 23064-23064/? V/chromium: [VERBOSE1:confirmations.cc(69)] Confirming landed for ad_notification with transaction id c79db5c5-bebd-491d-8ddc-d8232e99402f and creative instance id c6a6b939-4167-41fb-8a84-1edde6c12250
```
Dismiss
```
2022-01-31 03:20:29.828 24230-24230/? V/chromium: [VERBOSE3:ads_impl.cc(762)] Successfully deposited funds for ad_notification with creative instance id 4cda3ae7-1f70-4bca-b361-ca01d6a8f1ed and dismiss valued at 0
2022-01-31 03:20:29.828 24230-24230/? V/chromium: [VERBOSE1:confirmations.cc(69)] Confirming dismiss for ad_notification with transaction id 86fb20d6-3c6e-4cf2-aefb-ef2490e1adef and creative instance id 4cda3ae7-1f70-4bca-b361-ca01d6a8f1ed

```

</details>
<details>
<Summary>Case 3: Confirm confirmations are sent to the backend <b>Not testable on Android</b></summary>

- Can't verify it on the db as there is no access to db files
</details>
<details>
<Summary>Case 4: Confirm ads are added to 30-day Ads History - <b>Not testable on Android</b>  </summary>
</details>
<details>
<Summary>Case 5: Confirm 30-day Ads History is showing ads for the last 30-days - <b>Not testable on Android</b></summary>
</details>
<details>
<Summary>Case 6: Confirm brave://rewards "Current earnings this month (estimated)" has the correct value - <b>Passed</b></summary>

- Verified `Current earning this month (estimated)` shows correct values based on the number of ads seen
Note: there is no way to verify this by cross-checking the transaction tables in db as Android doesn't provide access to it

Ads settings | Panel 
-- | --
![image](https://user-images.githubusercontent.com/17010094/151761750-1a63e213-eb23-4579-bf1d-d7c1c95b2560.png) | ![image](https://user-images.githubusercontent.com/17010094/151761873-f1818c42-0311-457a-a814-7bdc4b270942.png)

</details>
<details>
<summary>Case 7: Confirm brave://rewards "Current earnings this month (estimated)" is updated when a user resets Rewards - <b>Failed</b></summary>

- Verification failed as reset rewards on Android doesn't work correctly which is a known issue [#8776](https://github.com/brave/brave-browser/issues/8776)
</details>
<details>
<summary>Case 8: Confirm brave://rewards "Next payment date" shows the correct value - <b>Passed</b></summary>

- Verified `Next payment date` shows the correct value (next payment date is shown based on the griffin configuration)
- Browser restart is required to pick the correct next payment date from the griffin service which is known
  <img width=400 src=https://user-images.githubusercontent.com/17010094/151762937-268ce9e9-7655-48d1-a0ae-746d28e431c0.png>

</details>
<details>
<summary>Case 9: Confirm brave://rewards "Next payment date" is updated when a user resets Rewards - <b>Failed</b></summary>

- Verification failed as reset rewards on Android doesn't work correctly which is a known issue [#8776](https://github.com/brave/brave-browser/8776)

</details>
<details>
<summary>Case 10: Confirm brave://rewards "Ads received this month" has the correct value - <b>Passed</b></summary>

- Verified `Ads received this month` shows the correct values based on ads received
  <img width=400 src=https://user-images.githubusercontent.com/17010094/151773838-8ea9d1c9-b19c-4bf3-afae-2438b1eafe80.png>

</details>
<details>
<summary>Case 11: Confirm brave://rewards "Ads received this month" is updated when a user resets Rewards - <b>Failed</b></summary>

- Verification failed as reset rewards on Android doesn't work correctly which is a known issue [#8776](https://github.com/brave/brave-browser/issues/8776)
</details>
<details>
<summary>Case 12: Confirm Rewards widget "Earnings" has the correct value - <b>Not Applicable for Android</b></summary>

</details>
<details>
<summary>Case 13: Confirm Rewards widget "Earnings" is updated when a user resets Rewards - <b>Failed on reset and Not Applicable on Android for widget</b></summary>

</details>
<details>
<summary>Case 14: Confirm Rewards panel "Estimated Earnings" has the correct value - <b>Passed</b></summary>

- Verified as part of Case 1 & Case 2
</details>
<details>
<summary>Case 15: Confirm Rewards panel "Estimated Earnings" is updated when a user resets Rewards - <b>Failed</b></summary>

- Verification failed as reset rewards on Android doesn't work correctly which is a known issue [#8776](https://github.com/brave/brave-browser/issues/8776)
</details>
<details>
<summary>Case 16: Confirm Rewards are reset at midnight on the 1st of each month based on the users local time to the total amount of unreconciled transactions for previous months (i.e. carried over) - <b>Partial Passed</b></summary>

- Verified rewards is reset on midnight of the 1st of each month
- Set Date to 31st Jan and viewed 5 ads (4NTP SI ads and 1 ad notification) totalling to 0.022 BAT
- Removed brave from memory and set device time to 31 Jan 11.59 PM
- Waited for the device to move past 12.00 AM of Feb 1
- Rewards balance was retained but ads viewed this month was reset to 0
- Waited for an ad notification to show up 
- Ads viewed this month increased by 1 and balance from Jan was carried forward 

31st Jan | 1st Feb
-- | -- 
![image](https://user-images.githubusercontent.com/17010094/151786937-75145b44-6981-49b7-8422-d9ff70c87b8b.png) | ![image](https://user-images.githubusercontent.com/17010094/151786949-6668de08-dfab-43bb-9b22-2aabf8b2d504.png)

Encountered [#20795](https://github.com/brave/brave-browser/issues/20795)
</details>
<details>
<summary>Case 17: Confirm "Your +#.# BAT payout will begin processing in # day." is working as expected- <b>Passed</b></summary>

- Verified rewards is reset on midnight of the 1st of each month
- Set Date to 31st Jan and viewed 5 ads (4NTP SI ads and 1 ad notification) totalling to 0.022 BAT
- Removed brave from memory and set device time to 31 Jan 11.59 PM
- Waited for the device to move past 12.00 AM of Feb 1
- Restarted the browser and closed it again
- Moved date forward to Feb 3
- Restarted the browser and opened ads details page and saw the `Your # BAT payout will begin processing in # days` message

Light Theme | Dark Theme
-- | -- 
![image](https://user-images.githubusercontent.com/17010094/151779494-09673257-569a-4ebc-8c25-625c937fc1de.png) | ![image](https://user-images.githubusercontent.com/17010094/151779513-41eaa887-6b32-45c5-9c03-250bd235840f.png)

</details>
<details>
<summary>Case 18: Confirm unblinded payment tokens are removed from confirmations.json when a user resets Rewards - <b>Not testable on Android</b></summary>
</details>
<details>
<summary>Case 19: Confirm failed confirmations are removed from confirmations.json when a user resets Rewards - <b>Not testable on Android</b></summary>

- Can't update/view confirmations.json file on Android but did confirm `Successfully redeemed unblinded token...` logs are shown for both View/Click/Landed and Dismissed events as mentioned in Case 2
</details>
<details>
<summary>Case 20: Confirm transactions are removed from database.sqlite when a user resets Rewards  - <b>Not testable on Android</b></summary>

- Can't view transactions table in db and rewards reset fails due to  [#8776](https://github.com/brave/brave-browser/issues/8776)
</details>
<details>
<summary>Case 21: Confirm transactions are migrated from confirmations.json to a new transactions table in database.sqlite  - <b>Not testable on Android</b></summary>

- Can't view transactions table in db 
</details>
<details>
<summary>Case 22: Confirm transactions are added to transactions table in database.sqlite  - <b>Not testable on Android</b></summary>

- Can't view transactions table in db 
</details>
<details>
<summary>Case 23: Confirm redeemed_at column for the 'transactions' table in database.sqlite is updated for cashed-out tokens  - <b>Not testable on Android</b></summary>

- Can't view transactions table in db 
</details>
<details>
<summary>Case 24: Confirm next_token_redemption_date_in_seconds is migrated from confirmations.json to brave.brave_ads.rewards.next_time_redemption_at pref  - <b>Not testable on Android</b></summary>

</details>
<details>
<summary>Case 25: Confirm next token redemption date is working as expected - <b>Not testable on Android</b></summary>

- Can't edit preferences file 
</details>
<details>
<summary>Case 26: Confirm day parting frequency cap is working as expected - <b>Not testable on Android</b></summary>

</details>
<details>
<summary>Case 27: Confirm upgrade path from 1.34.x to 1.35.x is working as expected - <b>Partial Passed</b></summary>

<b>Case 1: Ads switch OFF and then Upgrade to 1.35.x -PASSED</b>
- Installed 1.34.81 and viewed a few ads
- Turned off Ads 
- Upgraded to 1.35.98 and ensured Ads remained turned off
- Verified when enabled, estimated ads earnings was retained

https://user-images.githubusercontent.com/17010094/151786715-474d5ffa-6308-40bf-8042-290ec73a29c7.mp4


<b>Case 2: View a couple of Ads and then Upgrade to 1.35.x - PASSED</b>
- Installed 1.34.81 and viewed a few ads
- Upgraded to 1.35.98 
- Verified estimated ads earnings and total viewed ads are retained
- Verified new BR panel shows the estimated earnings and match with rewards page

https://user-images.githubusercontent.com/17010094/151786741-2925de37-91c4-48b6-ac1e-c3f0adedd4f2.mp4


<b>Case 3: View an NTP SI and confirm users are rewarded for viewing an NTPSI and ad notification count increased and then upgrade the profile to 1.35.x  -PASSED</b>
- Verified opening a new tab page with SI is both served and viewed events are captured
```
2022-01-31 06:20:50.769 6443-6443/? V/chromium: [VERBOSE3:new_tab_page_ad_event_viewed.cc(23)] Viewed new tab page ad with uuid cfacb757-416c-4042-b90e-20cbb0f93a42 and creative instance id 415254ef-6ced-40bd-8f5e-e202c69511ca
2022-01-31 06:20:50.770 6443-6443/? V/chromium: [VERBOSE1:confirmations.cc(93)] Confirming view for creative instance id 415254ef-6ced-40bd-8f5e-e202c69511ca
2022-01-31 06:20:50.798 6443-6443/? V/chromium: [VERBOSE1:redeem_unblinded_token.cc(53)] Redeem unblinded token
2022-01-31 06:20:50.799 6443-6443/? V/chromium: [VERBOSE1:redeem_unblinded_token.cc(67)] CreateConfirmation
2022-01-31 06:20:50.799 6443-6443/? V/chromium: [VERBOSE2:redeem_unblinded_token.cc(68)] POST /v1/confirmation/{confirmation_id}/{credential}
2022-01-31 06:20:50.799 6443-6443/? V/chromium: [VERBOSE6:redeem_unblinded_token.cc(72)] URL Request:
      URL: https://ads-serve.brave.com/v1/confirmation/282f3c22-9108-4cfd-87ed-117081bc61c7/eyJwYXlsb2FkIjoie1wiYmxpbmRlZFBheW1lbnRUb2tlblwiOlwiZEhqTVU0RFRySHF0WUttUHhoOHVvbmoyTElNckJBeEV0eFJsMnRzZ0V3Yz1cIixcImJ1aWxkQ2hhbm5lbFwiOlwicmVsZWFzZVwiLFwiY291bnRyeUNvZGVcIjpcIklOXCIsXCJjcmVhdGl2ZUluc3RhbmNlSWRcIjpcIjQxNTI1NGVmLTZjZWQtNDBiZC04ZjVlLWUyMDJjNjk1MTFjYVwiLFwicGF5bG9hZFwiOnt9LFwicGxhdGZvcm1cIjpcImFuZHJvaWRcIixcInN0dWRpZXNcIjpbXSxcInR5cGVcIjpcInZpZXdcIn0iLCJzaWduYXR1cmUiOiJQOUVyTC9kVXVYZTh1Y1VqcXVzWldoSGZseFFVUEJ2cGF3elVpbitEZzlVY040dVozVFVPZll3WXQxMXhLL2hQSmMzVEMxVVhkaWJxVGREVU1LNWtUUT09IiwidCI6IkNXcWk2cUhpaEhLTUxZQkFkTTNMaGhxVThYQVprT3EyUkxXemtQSVZEd0pnOUQ3NDEzOGdMTi8xbytycXh4UlFlZG1LUGFkL3F5OE4zV2hiSjRoeDRRPT0ifQ==
      Content: {"blindedPaymentToken":"dHjMU4DTrHqtYKmPxh8uonj2LIMrBAxEtxRl2tsgEwc=","buildChannel":"release","countryCode":"IN","creativeInstanceId":"415254ef-6ced-40bd-8f5e-e202c69511ca","payload":{},"platform":"android","studies":[],"type":"view"}
      Content Type: application/json
      Method: kPost
2022-01-31 06:20:50.800 6443-6443/? V/chromium: [VERBOSE6:new_tab_page_ad_event_viewed.cc(31)] Successfully logged new tab page ad viewed event
2022-01-31 06:20:50.806 6443-6443/? V/chromium: [VERBOSE3:new_tab_page_ad_event_served.cc(23)] Served new tab page ad with uuid cfacb757-416c-4042-b90e-20cbb0f93a42 and creative instance id 415254ef-6ced-40bd-8f5e-e202c69511ca
2022-01-31 06:20:50.819 6443-6443/? V/chromium: [VERBOSE6:new_tab_page_ad_event_served.cc(31)] Successfully logged new tab page ad served event
2022-01-31 06:20:51.128 6443-6443/? V/chromium: [VERBOSE1:redeem_unblinded_token.cc(83)] OnCreateConfirmation
2022-01-31 06:20:51.128 6443-6443/? V/chromium: [VERBOSE6:redeem_unblinded_token.cc(85)] URL Response:
      URL: https://ads-serve.brave.com/v1/confirmation/282f3c22-9108-4cfd-87ed-117081bc61c7/eyJwYXlsb2FkIjoie1wiYmxpbmRlZFBheW1lbnRUb2tlblwiOlwiZEhqTVU0RFRySHF0WUttUHhoOHVvbmoyTElNckJBeEV0eFJsMnRzZ0V3Yz1cIixcImJ1aWxkQ2hhbm5lbFwiOlwicmVsZWFzZVwiLFwiY291bnRyeUNvZGVcIjpcIklOXCIsXCJjcmVhdGl2ZUluc3RhbmNlSWRcIjpcIjQxNTI1NGVmLTZjZWQtNDBiZC04ZjVlLWUyMDJjNjk1MTFjYVwiLFwicGF5bG9hZFwiOnt9LFwicGxhdGZvcm1cIjpcImFuZHJvaWRcIixcInN0dWRpZXNcIjpbXSxcInR5cGVcIjpcInZpZXdcIn0iLCJzaWduYXR1cmUiOiJQOUVyTC9kVXVYZTh1Y1VqcXVzWldoSGZseFFVUEJ2cGF3elVpbitEZzlVY040dVozVFVPZll3WXQxMXhLL2hQSmMzVEMxVVhkaWJxVGREVU1LNWtUUT09IiwidCI6IkNXcWk2cUhpaEhLTUxZQkFkTTNMaGhxVThYQVprT3EyUkxXemtQSVZEd0pnOUQ3NDEzOGdMTi8xbytycXh4UlFlZG1LUGFkL3F5OE4zV2hiSjRoeDRRPT0ifQ==
      Response Status Code: 201
      Response: {"id":"282f3c22-9108-4cfd-87ed-117081bc61c7","payload":{},"createdAt":"2022-01-31T11:20:50.936Z","type":"view","modifiedAt":"2022-01-31T11:20:50.936Z","creativeInstanceId":"415254ef-6ced-40bd-8f5e-e202c69511ca"}
```

<b>Case 4: View ads and then reset rewards and then upgrade profile to 1.35.x - Failed</b>
- Failed due to known issue with reset rewards  [#8776](https://github.com/brave/brave-browser/issues/8776)


</details>

**Comment by GeetaSarvadnya** [comment]
Verification is **Inprogress** on Vivo X70 Pro with Android 11 running 1.35.98 x64 build

**Comment by aman-m1** [comment]
The counter Current earnings this month (estimated) is showing only the Ads not-reconciled. It should also include Ads reconciled in this month (Feb).

**Comment by tmancey** [comment]
@aman-m1 I have checked and the values are correct for me. Please email me at terry@brave.com with your findings so I can check.

**Comment by aman-m1** [comment]
I have sent. Please check.
