### ISSUE TITLE
Unable to pin extensions to menu bar

### ISSUE THREAD

**Issue by snowbound** [brave/brave-browser#16047]
## Description 
User is unable to pin extensions to menu bar via puzzle piece

## Steps to Reproduce

   1. click on puzzle piece icon on menu bar
   2.  click on push pin
   3.  extension whose push pin you click on should appear in menu bar

## Actual result:
Puhs pins are dead nothing happens when you click on any of them

## Reproduces how often: 
Easily

## Brave version (brave://version info)
Version 1.26.34 Chromium: 91.0.4472.57 (Official Build) beta (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  NO
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by snowbound** [comment]
![Brave Extension issue](https://user-images.githubusercontent.com/596147/119375181-222ad400-bc80-11eb-9749-c8d99f697a66.jpg)

None of the pushpins in this screen shot work. When one clicks on any of them the extension DOES NOT show up in the menu bar. It does not matter what extension is clicked on.

**Comment by snowbound** [comment]
This seemingly is working now on the computer. I shut down Brave. Clicked on the shortcut for the profile and when Brave started up the extensions were on the menu bar as they should which meant their corresponding pushpins under the puzzle piece were selected as they should be. I have no idea why this never worked before. I tried using numerous profiles and closing Brave down.

**Comment by snowbound** [comment]
Sorry to say but this issue has re presented itself. The machine in question apparently has 2 profiles. One is the one I always use and a Profile 1. I do not want profile 1 so I go in and delete it so that there is only one profile the one with all my extensions. The problem is  none of the extensions are showing up on the Menu Bar and the push pins in the Puzzle Piece icon are unselectable i.e. they do not turn red nor does the corresponding extension icon appear on the menu bar.

Remember I said I deleted Profile 1? Well if Brave is restarted or closed down, the next time Brave starts up Profile 1 is loaded first and I have to select the profile I want to use. Profile 1 can not be killed.

**Comment by snowbound** [comment]
This is getting dam frustrating not having the ability to pin extensions to the menu bar.

**Comment by mariospr** [comment]
I just tested this on the Beta channel on Linux (`Brave: 1.26.43 Chromium: 91.0.4472.77 (Official Build) (64-bit)`, as from brave://version) and this works for me just fine at least with the extensions I tested (some of them taken from your screenshot):

  * LastPass: https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd/related
  * Tab Pinner: https://chrome.google.com/webstore/detail/tab-pinner-keyboard-short/mbcjcnomlakhkechnbhmfjhnnllpbmlh
  * 1Password: https://chrome.google.com/webstore/detail/1password-%E2%80%93-password-mana/aeblfdkhhhdcdjpifhhbdiojplfjncoa/related
  * Better TweetDeck: https://chrome.google.com/webstore/detail/better-tweetdeck/micblkellenpbfapmcpcfhcoeohhnpob/related

About the profiles related problem (btw, could you file a separate GH issue for that one?) I can't reproduce it either on the beta channel: I also have a main profile that I normally use and then I created another one ("Test Profile"), used it for a bit, then switched back to the main one and deleted the secondary one ("Test Profile") without issues.

I'll try later on the same experiments on my Windows machine, maybe it's Windows-specific somehow...

**Comment by mariospr** [comment]
> I just tested this on the Beta channel on Linux (`Brave: 1.26.43 Chromium: 91.0.4472.77 (Official Build) (64-bit)`, as from brave://version) and this works for me just fine at least with the extensions I tested (some of them taken from your screenshot):
> 
> * LastPass: https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd/related
> * Tab Pinner: https://chrome.google.com/webstore/detail/tab-pinner-keyboard-short/mbcjcnomlakhkechnbhmfjhnnllpbmlh
> * 1Password: https://chrome.google.com/webstore/detail/1password-%E2%80%93-password-mana/aeblfdkhhhdcdjpifhhbdiojplfjncoa/related
> * Better TweetDeck: https://chrome.google.com/webstore/detail/better-tweetdeck/micblkellenpbfapmcpcfhcoeohhnpob/related
>
> [...]
>
> I'll try later on the same experiments on my Windows machine, maybe it's Windows-specific somehow...

I've just downloaded and installed Brave Beta from https://brave.com/download-beta, and I can **confirm that extensions pinning work well for me on Windows** with the same set of extensions I mentioned above, see for yourself:

![Screenshot (2)](https://user-images.githubusercontent.com/2197259/120620436-43987680-c45d-11eb-9ea7-e7c2f4fc66ad.png)

I see you're on Brave 1.26.43, while I'm on Brave 1.26.47... maybe worth a shot upgrading?

**Comment by mariospr** [comment]
> [...]
> About the profiles related problem (btw, could you file a separate GH issue for that one?) I can't reproduce it either on the beta channel: I also have a main profile that I normally use and then I created another one ("Test Profile"), used it for a bit, then switched back to the main one and deleted the secondary one ("Test Profile") without issues.
> 
> I'll try later on the same experiments on my Windows machine, maybe it's Windows-specific somehow...

Hmmm... I think I managed to reproduce this in the end, but doing something else that was not entirely clear from your comment: trying to **remove the ORIGINAL profile**.

Basically, **this works fine** (on Linux and Windows):
  1. Open Brave with the original profile (the one created by default, named "Person 1" or "Profile 1")
  2. Create a second profile named "Test Profile", for instance -> The profile gets created
  3. Restart Brave -> The two profiles are still available
  4. Delete the newly created profile ("Test Profile") -> profile gets deleted and back to the original profile
  5. Restart Brave -> Only the original profile exists now

Now, **this FAILS** (on both Linux and Windows):
  1. Open Brave with the original profile (the one created by default, named "Person 1" or "Profile 1")
  2. Create a second profile named "Test Profile", for instance -> The profile gets created
  3. Restart Brave -> The two profiles are still available
  4. Make sure you're on the new profile ("Test Profile") and delete the original one ("Person/Profile 1") -> profile gets deleted
  5. Restart Brave -> The original profile is restored once again, and you're back to having two profiles

FWIW, I **managed to reproduce that with both Release and Beta versions** of Brave on Windows/Linux, while I **can't reproduce on the latest Chrome release**, so it looks like a bug.

However, I've also observed that the latest Chrome release uses the new design for the profile menu, so this was not an exact 1:1 comparison, strictly speaking, and it's possible (not sure how likely, though) that this issue will get fixed once Brave switches to the new design as well.

@snowbound In any case, I think you're correct and it looks like there's currently a bug regarding the deletion of the **original profile**, which is currently not possible. Now, just to confirm, it would be great if you could check whether you can delete other profiles than the original one (e.g. create a third profile, delete it and restart -> check it remains deleted). And if we confirm that the problem is just with the original one... would you mind to file a new bug for it?

Thanks again!

**Comment by snowbound** [comment]
@mariospr on the laptop that has the extension pinning issue I was able to create a test profile then delete it without any issue. Brace 1.26.5

**Comment by mariospr** [comment]
> That still is the case for the main profile which has all my configuration and extensions installed. I do not understand what you meant by "would you mind to file a new bug for it?"

You seem to be mixing two different bugs into this GH issue:

1. Being **unable to pin extensions to the menu bar**:
  - This what this GH issue (#16047) is about, strictly speaking, and which I can **not** reproduce neither on Windows nor Linux, see my comment at https://github.com/brave/brave-browser/issues/16047#issuecomment-853722819
2. Being **unable to remove the ORIGINAL profile**:
  - This has nothing to do with the extensions pinning problem, and until your most recent comment (https://github.com/brave/brave-browser/issues/16047#issuecomment-854229485) it was not clear to me whether the original profile was the key or not, but now that seems to be the case (as you could remove a testing profile).

So, my request was about creating a separate GH issue for the problem described at (2), as there doesn't seem to be one for it at the moment (just some comments mentioning the problem in this issue).

**Comment by snowbound** [comment]
@mariospr Ok so right now I am experiencing the 1) issue. I have no desire to delete the profile under which all my extensions and settings are used from. If I do and can not delete the profile I certainly will file a separate bug report on that issue.

**Comment by snowbound** [comment]
This issue seems to be related to using passing the parameter "--disable-features=ExtensionsToolbarMenu"  to Brave when launching it. It causes the puzzle piece not to allow pinning at all of any extensions. If this parameter is not used then there is no pinning problem. Personally, I hate the puzzle piece. All it does is hide the extensions from the end user. The extensions are still consuming resources. If there are too many extensions then the end user should pare them down. Hiding the extensions does nothing to reduce the resources being used. It just makes using extensions more cumbersome and requiring more mouse clicks!

**Comment by mariospr** [comment]
@snowbound I might be wrong but I think you might be experiencing the expected behaviour then, as using that parameter would imply (as you point out) that you can't pin extensions, and I believe this is also the case with Chrome (not just Brave).

If that (this happening with Chrome as well) is the case, then I'd suggest you file a request to change the expected behaviour in https://bugs.chromium.org, since that would be something that would need to be changed upstream, not specific to Brave.

**Comment by snowbound** [comment]
@mariospr It is exhibiting the same behavior in Chrome as well. Up until recently using that parameter at least in Brave disabled the extension/puzzle piece and the extension icon hiding behavior and forced the extensions to show in the toolbar. It seems we have to now have to put up with this due to upstream changes.
