### ISSUE TITLE
Temporarily revert U2F sig check for Ledger U2F transport support

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#16204]
https://github.com/chromium/chromium/commit/07ef8d73c7b010a549c9bb960c6f7c73f1346fe5 breaks the U2F support of Ledger.

This is a problem with the transport being used to send arbitrary data, our wallet and other wallets still use the Ledger U2F transport though. So this issue is to track a temporary revert as we work out how to communicate over webhid instead.

**Comment by bbondy** [comment]
Re-opening until it's landed on 1.25.x

**Comment by kjozwiak** [comment]
@bbondy assuming the following STR/Cases are sufficient enough?

* ensure that you can create a new wallet via `brave://wallet`
* ensure that you can connect a Nano Ledger via `brave://wallet` without any issues

Anything else that QA should run through?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.25.70 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;(x86_64)
-- | --
Revision | `1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}`
OS | macOS Version 10.15.7(Build 19H114)

- Verified able to create wallet on `brave://wallet`
- Verified able to successfully connect Ledger Nano S via `brave://wallet` and unlock the address 
----------------
Verification passed on 

Brave | 1.25.70 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;(64 bit)
-- | --
Revision | `1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}`
OS | Windows 10 OS Version 2009 (Build 19042.985)

- Verified able to create wallet on `brave://wallet`
- Verified able to successfully connect Ledger Nano S via `brave://wallet` and unlock the wallet 
Note: Had an issue with the Windows connection popup going in loop when trying to connect the wallet. Dismissing the prompt did allow to connect the h/w and unlock the address
----------------
Verification partially passed on 

Brave | 1.25.70 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | `1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}`
OS | Linux

- Verified able to create wallet on `brave://wallet`
- Unable to connect Ledger Nano due to `TransportError: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE`
![Linux Wallet](https://user-images.githubusercontent.com/17010094/120689061-9b55d280-c49b-11eb-96b0-c4bc6ebb09f0.png)
