### ISSUE TITLE
Spellcheck dictionaries downloaded via crlsets.brave.com

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#16380]
Brave will fetch the following file on first run when using an English locale:
```
   GET https://crlsets.brave.com/edgedl/chrome/dict/en-gb-9-0.bdic HTTP/2.0
       ← 200 application/octet-stream 441.06k 171ms
```
which is a misleading endpoint name.

We should probably create a new proxy (alias) for `dl.google.com`.

**Comment by jumde** [comment]
We updated `crlsets.brave.com` to `redirector.brave.com` - https://github.com/brave/brave-browser/issues/4634 - I haven't had a chance to update the code yet

**Comment by fmarier** [comment]
This is actually set in `patches/chrome-browser-spellchecker-spellcheck_hunspell_dictionary.cc.patch` and not in `browser/net/brave_static_redirect_network_delegate_helper.cc` like all of the other users of `crlsets.brave.com`.

Also, [`redirector.brave.com` doesn't seem to be working as expected](https://github.com/brave/devops/issues/1079#issuecomment-903037922).

**Comment by fmarier** [comment]
The fix is to include the Brave Service Key in requests to `redirector.brave.com`.

**Comment by fmarier** [comment]
This might be useful: https://github.com/brave/brave-core/pull/9255

**Comment by fmarier** [comment]
Moved to `dict.brave.com` in https://github.com/brave/brave-core/pull/11917.

**Comment by stephendonner** [comment]
I gave this a verification attempt on macOS (only place I've got a fully-working `mitmproxy` setup) using the following:
* `Charles Proxy 3`
* `Wireshark`
* `mitmproxy`

Can confirm none of the above tools see a call to fetch `hunspell` from `dict.brave.com`.

Perhaps due to Chrome dropping Hunspell on at least Windows (and looks like it's baked into macOS, so perhaps not needed to be fetched, either?) https://www.theverge.com/2020/5/28/21273934/microsoft-google-chrome-edge-chromium-spellcheck-improvements

As the patch author, it probably shouldn't be @fmarier verifying the issue -- anybody else in @brave/legacy_qa have a working Linux setup and can test this?

I see all the others (`p3a.`, `redirector.`, `go-updater.` etc.). As I haven't seen this show up yet on macOS (and have yet to get a working Windows install), should we:

1) drop the `QA/Test-All-Platforms` and put `OS/Linux`
2) get someone from development with a working Linux setup (any of the above tools should work) to help us verify?
3) label it `QA Pass - Linux` since @fmarier has seen it working post-land and post-devops-config, and move on?

Note there's more extensive verification work related to the backend for this, over in https://github.com/brave/brave-browser/issues/20609, which should help with coverage confidence.

cc @rebron so he's aware, too

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.36.85 Chromium: 98.0.4758.87 (Official Build) beta (64-bit) 
--|--
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Linux

### Steps:
1. installed `mitmproxy` on `Ubuntu` `20.04 LTS` `64-bit` via: `sudo apt install mitmproxy`[0]
2. installed Brave `1.36.85` (`.deb` from `github`)
3. imported `~/.mitmproxy/mitmproxy-ca.pem` via `brave://settings/certificates`, on the `Authorities` tab
4. launched the mitmproxy SOCKS5-proxy instance using `mitmproxy --mode socks5 --listen-port 9000` on port `9000`
5. launched Brave using `brave-browser-beta --proxy-server="socks5://localhost:9000"`
7. examined network traffic in the `mitmproxy` window

## Confirmed (see screenshots):
* successful `GET` to host `dict.brave.com`  for the dictionary
* other requests were as expected and returned the appropriate `HTTP` response code; typically `200 OK`

example | example | example | example | example | example
---------|---------|----------|---------|-----------|---------
<img width="1652" alt="Screenshot 2022-02-05 at 00 06 46" src="https://user-images.githubusercontent.com/387249/152634498-8f0cec74-4d5a-4817-8176-2adfe670ab45.png"> | <img width="1652" alt="Screenshot 2022-02-05 at 00 04 27" src="https://user-images.githubusercontent.com/387249/152634525-11b38e60-6744-4619-80c6-f6bd0984568c.png"> | <img width="1652" alt="Screenshot 2022-02-05 at 00 00 34" src="https://user-images.githubusercontent.com/387249/152634559-b5d3836e-9616-426f-8820-9853666c0ed7.png"> | <img width="1652" alt="Screenshot 2022-02-05 at 00 01 43" src="https://user-images.githubusercontent.com/387249/152634577-f59cc24f-b551-4178-89c6-90ec77bd089c.png"> | <img width="1652" alt="Screenshot 2022-02-05 at 00 02 38" src="https://user-images.githubusercontent.com/387249/152634585-05e69919-6073-4677-ae6e-ed1b6893d7b1.png"> | <img width="1652" alt="Screenshot 2022-02-05 at 00 02 44" src="https://user-images.githubusercontent.com/387249/152634594-29b92f40-7446-47c8-8f4b-b870b80eb300.png"> | <img width="1652" alt="Screenshot 2022-02-05 at 00 02 53" src="https://user-images.githubusercontent.com/387249/152634610-fe333341-19d5-496b-9537-df752a69f564.png">








[0]:
```
stephendonner@stephendonner-virtual-machine:~/Downloads$ mitmproxy --version
Mitmproxy: 4.0.4
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Linux-5.13.0-28-generic-x86_64-with-glibc2.29
```
