### ISSUE TITLE
Rewards wallet is reset on upgrade from very old version

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#16449]
A migration from JSON files containing Rewards settings to using the browser's Prefs file was introduced in version 1.11. In 1.16 that initial migration was broken for users upgrading from 1.10, resulting in a "fresh restart" of Rewards on upgrade from 1.10 (or older) to 1.16.

**Comment by stephendonner** [comment]
We're going to need a testplan here; @zenparsing are you able to provide one for us?  Marking as `QA/Blocked` until we have that; thanks!

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.28.95 Chromium: 92.0.4515.115 (Official Build) beta (x86_64)
-- | --
Revision | 48cb2f4029b84b003719740a6cf9ca73f374a857-refs/branch-heads/4515_105@{#4}
OS | macOS Version 10.15.7 (Build 19H1217)
```

Verified test plan from https://github.com/brave/brave-core/pull/9143.

<details>
<summary>Scenario 1: Upgrade from 1.10.x</summary>

Pre-req: have `ledger_state` and `publisher_state` JSON files handy.
1. Start the browser version 1.10.90 with a clean profile to create a profile directory. 
2. Close the browser.
3. Copy `ledger_state` and `publisher_state` JSON files into the `Default` profile directory. Note, you cannot use this version to create a wallet any longer, so best we can do is use fake data.
4. Rename the profile to `Brave-Browser-Beta`
5. Launch the beta version (1.28.x).
6. Navigate to `brave://rewards-internals`.
7. Verify that the displayed payment ID matches the payment ID from the `ledger_state` file.

Note, since we're faking data nothing will really work with the server, but confirming that the paymentId is imported is good enough for this case.

</details>

<details>
<summary>Scenario 2: Only using 1.28.x</summary>

Pre-req: have `ledger_state` and `publisher_state` JSON files handy.
1. Start the browser 1.28.x with a clean profile to create a profile directory. .
2. Close the browser.
3. Copy `ledger_state` and `publisher_state` JSON files into the `Default` profile directory. 
4. Launch the browser.
5. Navigate to `brave://rewards-internals`.
6. Verify that the displayed payment ID matches the payment ID from the `ledger_state` file.

Note, as with the previous scenario, since we're faking data nothing will really work with the server, but confirming that the paymentId is imported is good enough for this case.

brave://rewards-internals before import | brave://rewards-internals after import | ledger_state file
----- | ----- | -----
<img width="348" alt="before" src="https://user-images.githubusercontent.com/28145373/127344014-6e59c80e-20c5-430d-b430-c2065e58d8cd.png"> | <img width="480" alt="after" src="https://user-images.githubusercontent.com/28145373/127344018-fbc69808-f631-4c74-8875-4707c9580ab9.png"> | <img width="653" alt="ledger_state" src="https://user-images.githubusercontent.com/28145373/127344028-95ac5b45-6d15-4963-b06c-bef756b36a29.png">


</details>

**Comment by srirambv** [comment]
Verification passed on Oppo R5 with Android 11 running 1.28.99 x64 Beta build
- Verified wallet is not reset upon upgrade from an older version
------------
Verification passed on Samsung Tab A with Android 10 running 1.28.99 x64 Beta build
- Verified wallet is not reset upon upgrade from an older version
