### ISSUE TITLE
Fixes Brave News Ads issues

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#16452]
General issues which should be tested as part of Brave News ads

**Comment by LaurenWags** [comment]
@jsecretan @tmancey could QA get a test plan for this issue? It's very broad. Or is this one covered under the same test plan as https://github.com/brave/brave-browser/issues/16008 (which generally lists a regression test of Ads in https://github.com/brave/brave-core/pull/8886)? 

I think we had discussed marking some issue(s) `QA/No` due to the regression test plan for #16008 but I am unsure what the final decision was.

**Comment by tmancey** [comment]
@LaurenWags This should be tested with Brave News. Thanks

**Comment by LaurenWags** [comment]
@tmancey So what kind of test plan are we looking at for this one? Is there one somewhere for Brave News ads that I'm not aware of?
