### ISSUE TITLE
Offer a way to hide the Brave Shields button, just like hiding Brave Rewards

### ISSUE THREAD

**Issue by ducheng0** [brave/brave-browser#16778]
## Description 
Allowing users to hide the brave shields would be a nice change on small screens, and would let users remove the features they don't like from brave.

## Expected result:
There should be an option to disable the shields icon in settings.

## Desktop Brave version:
1.26.74 Chromium: 91.0.4472.124 Official Build 64-bit

## Version/Channel Information:
- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  Yes

**Comment by srirambv** [comment]
This would be a wontfix issue. Closing as we don't intend to hide shields in any possible way. 

cc: @rebron @anthonypkeane

**Comment by Aravisian** [comment]
> 

Typical of developers being out of touch with the users. Much like Blizzards Doom Immortal, you are so wrapped in trying to control the users, you forget that without the users, you have Nothing. let's face a small reality about your recalcitrance, here... You are deceiving yourselves, more than us.
Your reason for not wanting the Shield Icon to be hidden is that you Protect it as a Brand Image. Do you really believe... for even one moment... that as a person is sitting at their laptop at the cafe, a passerby asks, what is that Beautiful Lion icon in 16px size I spotted from across the room? I Must have that on MY computer.
NOPE.
Brave, as a browser, gets its brand image from Word of Mouth Advertising like many things. From USERS promoting it due to the browser development team listening to feedback and implementing a design that works for the user, not for the developer pushing and forcing Their Own Wants onto others.
If you disagree - you and Rebron, who is as stubborn and closed-off to Real Feedback as Leonart Poettering, need to get thee selves to Microsoft and put in applications - that is where you belong.

**Comment by ducheng0** [comment]
@Aravisian 
I'm working on a custom browser with annoying things removed, and absolutely no telemetry (no server connections that weren't initiated by users visiting a website). It also has a neat tab management system that's super fast... oh and it's written in Flutter :)

**Comment by ducheng0** [comment]
Brave Shields is kinda useless against Google Ads. I just install Ublock Origin and forget about Brave's gimmicky ads and other ventures that they're constantly promoting.

**Comment by Aravisian** [comment]
@ducheng0, when ready for testing, please share a link to source or where we can follow a roadmap of progress. I understand - developers Need to Be Paid. The problem with Free is that it usually Isn't. A browser is the most used application, these days, on any desktop. And Browser devs know this. More time is spent validating and justifying poor decisions than time is spent on making Good decisions. I have tried a lot of browsers. Some you may have never heard of. And where one browser solves one problem, you find that problem neglected in another, but it solves a different problem that is neglected in the original you tried.  Part of the trouble with browsers is that the webpages must be willing to play ball - so you end up with iterations of the same browser, all making promises and all based on Gecko or Blink.
Firefox doesn't render Menus properly. Chromium based do - but lack a menubar. Firefox has a menubar. Vivaldi renders menus properly and has a menubar... but is a resource hog and has myriads of strange little performance problems. Brave has Good performance, but has questionable Brave Rewards Business practices and places far too much emphasis on securing itself as a brand, instead of as a good product. I mean, at least Robin Hood stole from the rich to give to the poor... Brave takes from Both in its strange method of advertising.
Money is not Made. You don't make money. Money is taken. When you say you want to "make money," what you actually mean is you want to Take Money. You can get away with just taking it for a while as people have a pretty high degree of tolerance. But the only way to successfully take money long term is to take it fairly, honorably and honestly.
I would rather pay for a good browser - than have one offered for free that Takes what it wants when it thinks I am not looking.
I have wiped Brave Browser off my machine with a nuclear warhead and am currently testing BadWolf Browser.

**Comment by du64** [comment]
@Aravisian The browser project has been a work in progress for a while now, since it's not easy to recreate things from the ground up, especially since Brave doesn't make it easy to implement their updates server software, and the crypto crap is deeply embedded into Brave now.

I don't have anything against crypto, I use it daily, but I don't need crypto to be in every aspect of my life. It has its uses, and it should be left that way, just like money.

**Comment by rthfhgyhy567** [comment]
> > 
> 
> Typical of developers being out of touch with the users. Much like Blizzards Doom Immortal, you are so wrapped in trying to control the users, you forget that without the users, you have Nothing. let's face a small reality about your recalcitrance, here... You are deceiving yourselves, more than us. Your reason for not wanting the Shield Icon to be hidden is that you Protect it as a Brand Image. Do you really believe... for even one moment... that as a person is sitting at their laptop at the cafe, a passerby asks, what is that Beautiful Lion icon in 16px size I spotted from across the room? I Must have that on MY computer. NOPE. Brave, as a browser, gets its brand image from Word of Mouth Advertising like many things. From USERS promoting it due to the browser development team listening to feedback and implementing a design that works for the user, not for the developer pushing and forcing Their Own Wants onto others. If you disagree - you and Rebron, who is as stubborn and closed-off to Real Feedback as Leonart Poettering, need to get thee selves to Microsoft and put in applications - that is where you belong.

Couldn't have said it any better.  The brave shields feature is unnessessary when a third party addon like ublock is installed.  Ublock and adblock both do the same things as brave shields, so its redundant to have these bright orange icon on my screen that I can't hide.  All because the developers are complacent and smug about their ideas.  Such a shame.

**Comment by michaelskyba** [comment]
![0](https://github.com/brave/brave-browser/assets/57649592/d6998b56-edac-4e12-9a0a-418367c30433)
Not sure if this is any better but if you delete ``/opt/brave-bin/brave_resources.pak`` (back it up first) then it disables some features and replaces the Shields icon with a yellow square

**Comment by michaelskyba** [comment]
![0](https://github.com/brave/brave-browser/assets/57649592/10739bf0-981f-4d02-acfc-313cd6a83367)
If you use Chromium's grit tool, you can extract the pak file, modify the images, and then repack it

**Comment by tinncdev** [comment]
at least make it monochrome to blend in the address bar content instead of shinning out bright the whole website bellow.
too much of a hassel for a small but annoy thing.
can't trust to have all the online credential in the handle of the people who doesn't even listen.

**Comment by du82** [comment]
Brave has been going down the shitter for years now. First its sponsored news articles, next it's crypto, now AI, what other BS will they force on users?

**Comment by istituzionealsole** [comment]
I mean to be fair, I got to know brave thanks to a live streamers that was using the browser, and I probably wouldn't have seen that they were using it if not for the brave shields icon. Although I agree, it is ugly

**Comment by friedegg796** [comment]
> ![0](https://github.com/brave/brave-browser/assets/57649592/10739bf0-981f-4d02-acfc-313cd6a83367) If you use Chromium's grit tool, you can extract the pak file, modify the images, and then repack it

For us, less technical folk, is there any simpler way to do this? (I do not know how to get the grit tool)
