### ISSUE TITLE
Incompatibility with W3 spec:  Insecure content coming from 127.0.0.1:<port> is being blocked

### ISSUE THREAD

**Issue by pbadenski** [brave/brave-browser#16917]
This was already reported in https://github.com/brave/brave-browser/issues/13606

This behaviour is incompatible with W3 spec, where 127.0.0.1 is considered secure (https://www.w3.org/TR/secure-contexts/#is-origin-trustworthy). Could you elaborate more about the reasoning of blocking this traffic considering it goes against the specification?

**Comment by ryanbr** [comment]
We block 3rd-party localhost requests due to security. Should be no reason why a localhost needs access to a website, we've taken more of a proactive approach here.  cc: @pes10k

**Comment by pbadenski** [comment]
For context - this mechanism is essential for running our platform. We use it in order to access locally running data server.  Data in question cannot be accessed any other way as it cannot leave user's PC for contractual reasons.

**Comment by pes10k** [comment]
As mentioned above, allowing websites to arbitrarily access local services is an unacceptable privacy risk for Brave users, which is why we block it.

We plan on providing a permission-dialog style option for sites that need access to local resources, but i dont have any timeline to share for when that might be available or complete.  In the meantime, your visitors / users can enable connections to local services by disabling tracking protections in Brave in shields. Hope this helps explain the current implementation choices and expected path forward in Brave

**Comment by ShivanKaul** [comment]
@pbadenski is this still something you're interested in? If yes, please give me a website where you want to be connecting to localhost resources from.

**Comment by pbadenski** [comment]
It would be nice - it's not a priority since we only have a small number of users on Brave, but it does help us to smoothen the experience: https://pricingmonkey.com
