### ISSUE TITLE
Require IPFS Gateways with Origin isolation

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#16999]
When a public IPFS gateway is used in a browser context, it should ALWAYS provide origin isolation.

Brave allows user to customize public gateway address via settings:

> ![2021-07-16--15-47-53](https://user-images.githubusercontent.com/157609/125958204-82b48fa8-cbbf-460d-acb1-f4f6bce44e17.png)

We need to add validation when user submits alternative URL of the gateway:

> ![2021-07-16--15-49-14](https://user-images.githubusercontent.com/157609/125958399-4a7e798e-797d-4051-9b6c-78a495208737.png)

Brave must validate it is safe for use in browsers and correctly resolves CIDs:

- Make HTTP request to `{protocol}://{URL.host}/ipfs/bafkqae2xmvwgg33nmuqhi3zajfiemuzahiwss`
  - Confirm that user is redirected and ends up on `{protocol}://bafkqae2xmvwgg33nmuqhi3zajfiemuzahiwss.ipfs.{URL.host}` 
  - Confirm the above subdomain returned `Welcome to IPFS :-)` 

cc @diracdeltas @bbondy @spylogsster – I feel this is pretty important to add, protects BRave and IPFS from bad security+PR incidents due to people using insecure gateways.

## Test cases
- allow only gateways that provide subdomain isolation. For example:
  - `http://localhost:{any port}/` is a subdomain gateway  from  a local IPFS node
  - `https://dweb.link/` is a subdomain gateway  from Protocol Labs
  - `https://cf-ipfs.com/` is a subdomain gateway  from Cloudflare 
- refuse to use gateways that share origin across all CIDs. For example:
  - `http://127.0.0.1:{any port}/` is a path gateway from  a local IPFS node (no origin isolation)
  - `https://ipfs.io` is a legacy path gateway  from Protocol Labs
  - `https://cloudflare-ipfs.com`  is a legacy path gateway from Cloudflare

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


Brave | 1.30.42 Chromium: 93.0.4577.51 (Official Build) nightly (x86_64)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | macOS Version 11.5.2 (Build 20G95)

### Steps:
1. new profile
2. launched Brave
3. opened `brave://settings/ipfs`
4. input the following expected allowed values and confirmed they were accepted
   * `https://localhost:48081`
   * `https://dweb.link/`
   * ~`https://cf-ipfs.com/`~ - filed https://github.com/brave/brave-browser/issues/17648
5. input the following disallowed values and confirmed they were rejected
   * `http://127.0.0.1:48081`
   * `https://ipfs.io`
   * `https://cloudflare-ipfs.com`


### Allowed values
`https://localhost:48081` | `https://dweb.link/` | `https://cf-ipfs.com/`
---------|----------|---------
<img width="1149" alt="Screen Shot 2021-08-23 at 4 56 55 PM" src="https://user-images.githubusercontent.com/387249/130534534-deb7e870-b4eb-4e70-b3c8-f8f5da983481.png"> | <img width="1149" alt="Screen Shot 2021-08-23 at 4 57 59 PM" src="https://user-images.githubusercontent.com/387249/130534477-6129d22e-1625-439a-ae5e-29d3c077eb94.png"> | N/A; see https://github.com/brave/brave-browser/issues/17648

### Disallowed values
`http://127.0.0.1:48081` | `https://ipfs.io` | `https://cloudflare-ipfs.com`
--------|----------|----------
<img width="1149" alt="Screen Shot 2021-08-23 at 4 55 37 PM" src="https://user-images.githubusercontent.com/387249/130534610-f107b4b0-09b8-40bd-8e4f-6c4e8ad09f76.png"> | <img width="1149" alt="Screen Shot 2021-08-23 at 4 56 31 PM" src="https://user-images.githubusercontent.com/387249/130534637-815bc256-4b18-4f2f-a07a-08b63d606e56.png"> | <img width="1149" alt="Screen Shot 2021-08-23 at 4 56 18 PM" src="https://user-images.githubusercontent.com/387249/130534653-469fab82-f8df-43de-9429-2b3340392da2.png">

**Comment by srirambv** [comment]
Removing Android label from this one as Android only uses public gateway as of now. Can create a new issue when Android supports custom gateways

**Comment by markg85** [comment]
Not sure if this issue should be reopened or if i should report a new one.

I'm in the position where i want to run a local IPFS node in my local network but not on my local machine. The reason here is multiple pc's in the same network and i want them all to use the same single IPFS node in the network.
So say:
127.0.0.1 = local machine (10.0.0.1)
10.0.0.2 = local **network** machine running IPFS

Currently brave forbids setting my local network machine as gateway.
Brave also forbids me to use "127.0.0.1" whereas "localhost" does work. These checks are too strict imho.

In my case i can easily work around it by just making an ssh tunnel: `ssh -L 8080:127.0.0.1:8080 user@<network node>` which makes both `localhost:8080` and `127.0.0.1:8080` work just fine and thereby satisfying the brave requirements.

But is this really necessary? Do i really have to go through these hoops to get a local node working where for example dweb.link just works?

**Comment by lidel** [comment]
Yes, this is necessary.

What you are describing is not limitation of IPFS or Brave, but the basic security limitation of the web platform.  Origin isolation is required in Brave, so you need to use `localhost` subdomain gateway. 

`localhost`  works without TLS because it is explicitly marked as Secure context:
https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

Running plaintext Gateway in your LAN means it will have non-localhost address, so you need to set up self-signed TLS to ensure your browsing history can't be monitored or spoofed by malicious device in your LAN.  

If you have `https://gw.local` then it should pass the test and will work fine.

**Comment by friedemannf** [comment]
Depending on the gateway implementation this check seems a bit too strict:

We have set up our IPFS gateway using a subdomain `ipfs.example.com` as other applications are hosted on the same domain. In this case this means that `https://ipfs.example.com/ipfs/{cid}` will be redirected to `https://{cid}.ipfs.example.com` but Brave expects a redirect to `https://{cid}.ipfs.ipfs.example.com`.

afaict this isn't in violation of the [Subdomain Gateway Specification](https://github.com/ipfs/specs/blob/main/http-gateways/SUBDOMAIN_GATEWAY.md#migrating-from-path-to-subdomain-gateway) and should therefore be allowed. Please correct me if otherwise.

**Comment by MysticRyuujin** [comment]
I have the same problem as @friedemannf - If I put https://ipfs.my.network I get the Origin Isolation error and I can see the request come in as `ipfs.ipfs.my.network`
