### ISSUE TITLE
Disable remote debugging

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#1736]
Developer Tools window has support for "remote debugging" feature when you plug in a mobile phone.

Google's public feature documentation: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

The feature requires downloading files from Google servers.

At a minimum, the download should be blocked. Better if we can disable the entire feature altogether. Even better if we can remove the files from the build.

**Comment by Moulde** [comment]
FYI: Remote debugging can also be used to debug javascript in visual studio code or most other editors i guess. So is's not only used for mobile devices.

**Comment by ahrherrera** [comment]
This feature is needed if developer who works with apps, so Brave is not developer friendly.

I am changing back to Google Chrome because of this.

**Comment by IanBoyte** [comment]
This is a critical tool and an absolute dealbreaker.

**Comment by neuronetio** [comment]
Please bring back this feature :cry:

**Comment by nicholasengleman** [comment]
This is also breaks the Lighthouse Audit in dev tools. Perhaps do some research on a integral component of dev tools before removing it?

**Comment by salmankhilji** [comment]
Show stopper for me.  Please bring this feature back.

**Comment by linearza** [comment]
Just ran into this as well, what is the motivation behind this move? Will have to switch to Chrome because of this as well

**Comment by bsclifton** [comment]
@linearza I believe because when enabled, it does reach out to Google services

**Comment by kitsunekyo** [comment]
the only but deal-breaking feature that prevents me (and all other devs i know) to use brave as main browser. let the user decide for an opt-in instead.

**Comment by bsclifton** [comment]
@kitsunekyo it is now enable-able in versions 1.2 and higher. Per [our release schedule](https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates), 1.2 is scheduled to ship today on Release channel

You can find the `Enable remote debugging` option under brave://settings/privacy

**Comment by patrikniebur** [comment]
Would be useful to have message on the devtool if it's not enabled. Currently I get 404 page when I try to access remote development and it's not enabled. 
OSX:  
```Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)```

**Comment by bsclifton** [comment]
@patrikniebur thanks to work by @jumde this will be enabled by default in versions 1.10 and later (currently on Beta). This should make a big difference for folks 😄

**Comment by slashwhatever** [comment]
> @kitsunekyo it is now enable-able in versions 1.2 and higher. Per [our release schedule](https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates), 1.2 is scheduled to ship today on Release channel
> 
> You can find the `Enable remote debugging` option under brave://settings/privacy

Any idea why I don't see this flag in my privacy settings?

Brave: v1.44.112

**Comment by szofar** [comment]
Also missing for me. How am I supposed to gather HAR files to help a site fix their Brave compatibility?

**Comment by agzam** [comment]
Wah... that is so stupid to disable this feature completely and not even let people to enable it through the hidden flags or whatever. What a shame. Even fucking Opera has it. My guess is that Brave developers themselves don't even use their own fucking browser. I'm honestly so tired of these kind of "improvements", this might be finally the last straw that makes me abandon it for good.

**Comment by bsclifton** [comment]
@agzam this feature was temporarily disabled with https://github.com/brave/brave-core/pull/790 on 2 Nov 2018, then a flag was added (25 Nov 2019) with https://github.com/brave/brave-core/pull/4044.

This the feature was permanently re-enabled in a safe way with https://github.com/brave/brave-core/pull/5500 on 9 May 2020. So basically it was only disabled a short while and then was re-enabled and has been re-enabled for over 4 years.

If you're using a build from 2018 where it was disabled please update your binary. It should 100% be working if you have a new version. I'll update the original post here to add the history so others are aware of what happened after this issue was closed.

**Comment by kemora13conf** [comment]
@bsclifton I have installed the latest version of brave just right now from the offecial site but i do inspect from my pc i get blank devtools windows that says: "HTTP/1.1 404 Not Found"

**Comment by bsclifton** [comment]
@kemora13conf what OS are you using? How did you install Brave (ex: are you using Linux and installed via snap?) How are you opening the dev tools?

Basically, you should be able to press F12 or Shift + Ctrl + I (or hamburger menu > More tools > Developer tools). That is not something we're changing at all with Brave.

The only thing this issue was tracking was the behavior around the fetching of sources (if you went to the `Sources` tab). Our code has since been updated to proxy the call.

**Comment by kemora13conf** [comment]
@bsclifton 
I am using windows and i have installed brave on my android device i am trying to access it via chrome devtools.

**Comment by bsclifton** [comment]
@kemora13conf that should work just fine - you do need to use a USB connection between your phone and the Windows machine. Besides that, you'll of course need to have developer mode enabled on the Android device. On the Windows machine, you might need to have the driver installed (I installed USB driver via Android Studio)

**Comment by agzam** [comment]
> [@agzam](https://github.com/agzam) this feature was temporarily disabled with [brave/brave-core#790]

@bsclifton Brian, I owe you guys a sincere apology for my senseless and unfounded outburst. I should have recognized that my own clumsy handling was to blame - after my initial attempts have failed, I started googling and wrongfully came to the conclusion that this incredibly important feature was disabled for security considerations. As an early adopter and longtime user of the browser, I recall past instances when essential features broke (seemingly out of blue), and this episode felt reminiscent of those frustrating times. I should have chosen my words more carefully instead allowing my emotions to take over.

**Comment by bsclifton** [comment]
Hi @agzam - thanks for circling back. No worries - being upset is understandable.  This issue was probably top of search for `remote debugging in Brave not working` (or similar).

While it's good to have content found by search engine crawlers, the old articles / issues / pages (like this one) don't always have updates that describe the current behavior😄 I'm happy to help capture that so that the next person who encounters a problem might know it should be working

If you have more information about how you solved the issue definitely capture here
