### ISSUE TITLE
YouTube's User Menu Won't Open

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#17459]
## Description 

From time to time, YouTube's user-menu (the menu presented when clicking on the user profile image/avatar at the top-right of the page) fails to open when clicked. This does not happen all the time, but often enough that the issue is fairly easy to reproduce.

## Steps to Reproduce

1. Go to youtube.com
2. Click on the account image at the top-right of the page

## Actual result:

No menu is presented.

## Expected result:

A menu is presented.

## Reproduces how often: 

Often/easily.

## Brave version (brave://version info)

1.28.105 Chromium: 92.0.4515.131

## Version/Channel Information:

Release.

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes.
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No.

## Miscellaneous Information:

This issue was reported on Twitter, and confirmed by @jonathansampson.

https://twitter.com/umumcuyilmaz/status/1425808754357018627

**Comment by Tonev** [comment]
@jonathansampson 

It's related to https://github.com/brave/adblock-lists/pull/632 which @ryanbr later reverted https://github.com/brave/adblock-lists/pull/633.

The workaround until the component server updates the filter lists is adding `youtube.com#@#.ytd-popup-container` in the `Custom Filters` textbox at `brave://adblock`.

The real issue is that the custom filter simply won't work all the time. It works once, twice, and then users have to reload YouTube a couple of times to bring the custom filter back to life.

If you can, please force an update for the filter lists, that should resolve the issue for everyone.

**Comment by Miyayes** [comment]
Does going into brave://components and then updating your Brave Ad Block Updater to Version: 1.0.1030 resolve the issue?  (Refresh YouTube or restart browser afterward.)

**Comment by ryanbr** [comment]
Safe to close this, fix has rolled out automatically, if not follow: #17465 (comment)
