### ISSUE TITLE
Fix icons for Bookmark Bar Folders

### ISSUE THREAD

**Issue by SmokeyLlama** [brave/brave-browser#17463]
## Description 
Update bookmark folder icon to increase legibility and align better to user preferences.

Original description:

> I am a web developer, and I manage different clients in my bookmark folders.
> - The new update, changed all the bookmark folder icons to be: ![image|33x26](https://aws1.discourse-cdn.com/brave/original/3X/c/d/cdd3a06b1658042a1b8632a2a5c87cd2e2b9f132.png)
> - This has made it a little more bland and hard to separate the folders at a glance
> - Since the icon are the same color as the text now, everything kind of blends together
> - This wasn't the case prior, when a very visible yellow folder separated them

CURRENT:
![image|243x27](https://aws1.discourse-cdn.com/brave/original/3X/0/f/0f1d6090760ae7c041c3289a8e5230a1a42ab364.png)

OLD:
![image|244x28](https://aws1.discourse-cdn.com/brave/original/3X/8/f/8ff236f79314b9442deb1a723b933b89d8a00e43.png)

## Design

MacOS + Linux
![image](https://user-images.githubusercontent.com/2388823/132382003-c1347b73-9ddf-4f03-b8e5-7654f5ea56b3.png)
![image](https://user-images.githubusercontent.com/2388823/132382019-023332e7-7eaa-4017-8945-656bc7290ea4.png)

Windows
![image](https://user-images.githubusercontent.com/2388823/132381975-034c0ba6-de3c-4053-b195-337fffb221ad.png)
![image](https://user-images.githubusercontent.com/2388823/132381988-918758b2-172f-4021-9bfc-6b60a14cea0d.png)

## Assets
Figma: https://www.figma.com/file/sS3l8tqUFxt54MEiBTalUI/?node-id=9%3A5824

**Comment by worthdesigning** [comment]
I prefer the yellow folders as well. The new folders are not visually useful. I noticed something wasn't right and then saw the new icons - not good.

**Comment by bravo86** [comment]
I much prefer the yellow folders. It makes me think my brave browser is broken. Can we have a least an option to go back to yellow folder pls?

**Comment by srirambv** [comment]
cc: @karenkliu @simonhong @rebron

**Comment by KDD777** [comment]
I hope Brave changes the bookmark folders back to yellow. Unfortunately, I am going to use my Chrome browser until they do.

**Comment by bman00311** [comment]
Please change bookmark folder icons back to yellow

**Comment by BararQ** [comment]
They look like the icons did not load properly or I am playing some old 8-bit game. Especially when all my other icons have color. Making it a option I can change so I can opt out of it, or bring back the old folder icon Please.

**Comment by davidmreid** [comment]
It's obviously a big time screw-up by the brave developers at Brave--as changing the icons doesn't make sense--unless you made a big boo-boo. Get this fixed already my Brave peeps.

**Comment by bobd64** [comment]
The change to grey/transparent folders icons in the latest update of Brave browser has made it difficult to use Brave.
I use the Bookmark bar with folders to find my regularly used sites. This is now annoying to my eyes as there are no differentiation along the bar. I now have to scan back and forth to find the folder I need. The more I use it the more it irritates my eyes. I hope you allow the option of returning to the yellow folders. Somehow the change in colors is soothing to my eyes.
![image](https://user-images.githubusercontent.com/88920132/129434974-097266df-ad05-43dc-9c1d-c1333c69148b.png)

**Comment by gregeeh** [comment]
I agree, please either change the bookmark folder back to yellow or give us a choice.

**Comment by phempshall** [comment]
I thought all my folders were empty. Here's a UI/UX thought...

Solid icons = has contents
Outlined icons = empty

**Comment by KDD777** [comment]
The UI/UX argument is win hands down argument for yellow-colored folders rather than clear folders. I don't know why the UI/UX people have such little power at Brave.

**Comment by Johann999** [comment]
The previous yellow icon made sense. It corresponded to the Windows folder icon, which is also yellow.
For years, users have gotten used to this icon.
There was absolutely no need to change this icon.
Please undo this change, asap. Thank you.

**Comment by Tramplr** [comment]
Don't like the grey outline folder icons.  Spent a bunch of time trying to "fix" this since I didn't realize it was a change.  As the previous posters have said, please put it back or make a choice to opt in or out. I always say "if it ain't broke don't fix it".

**Comment by KDD777** [comment]
I just found these free Chrome bookmark separators which makes the Brave Browser folder color screwup more bearable: https://www.chromebookmarkseparator.co.uk/

Now at least there is some visual separation between the "sea of greyness" by not having the browsers be yellow and instead clear/grey.

**Comment by bravo86** [comment]
Is there a way to roll back to an old version manually?

**Comment by bsclifton** [comment]
Thanks for the feedback folks! 😄 I've shared with the appropriate people - we should have a response soon

As for work-arounds, I took a look and unfortunately it doesn't seem the icons are overridable by extensions or themes ☹️

**Comment by 831Digital** [comment]
+1. Bring the old icons back or at least give us a choice.

**Comment by pHROZEN-gHOST** [comment]
Wow.
Please wake up.
Imagine what would happen if COVID-19 vaccination were mandatory.

If you want the option to turf the yellow folders, make it just that ... an option so people have a choice.
Leave the yellow folders as a default. Is that really too much to ask?
Even the current version of Google Chrome allows yellow folders again.

**Comment by JeffreyStevens** [comment]
I thought my Brave was broken when the folder icons were no longer yellow. I kept trying to change the appearance to make them revert to the old icon. Colorless folder icons next to colored bookmark icons is awful. It's ok to admit you made a bad call here, just give us the option to go back.

**Comment by thebigMoose** [comment]
I thought I lost my bookmarks with this change.  Totally missed the outline folder.  PLEASE give us back the yellow folder

**Comment by 831Digital** [comment]
Still nothing? I am about to ditch brave over this. I hate the way this looks.

**Comment by bravo86** [comment]
tempted to move over to Edge where it also has ad blocks and the verticle tab that is natively supported.

**Comment by karenkliu** [comment]
Hi all, product design team here. Thanks for all the feedback so far! We hear you and are working on a fix. It's important to us that we have a bookmark folder icon that works for everyone, and clearly some considerations were missed in the initial update. Please be patient as we get a fix into the queue.

**Comment by pHROZEN-gHOST** [comment]
Hi Karen,

Thanks for the feedback.
I may be wrong. But I believe that Chromium was where the change occurred. Google Chrome also has the same backlash when this happened. 

I think the change should have been an optional one which people could have selected in settings. People don't generally like forced changes.

The new folder icons look terrible on my theme which has not changed and probably never will. Many of us use themes. So I can imagine that this would have similar impact to others.

I appreciate the attention to this item.
    On Wednesday, August 18, 2021, 01:35:10 p.m. EDT, Karen ***@***.***> wrote:  
 
 


Hi all, product design team here. Thanks for all the feedback so far! We hear you and are working on a fix. It's important to us that we have a bookmark folder icon that works for everyone, and clearly some considerations were missed in the initial update. Please be patient as we get a fix into the queue.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bsclifton** [comment]
@pHROZEN-gHOST the new icons are ones we had made actually - this happened with https://github.com/brave/brave-core/pull/9424. If we reverted that pull request / patch, it would go back to the old look and feel

Do you have a screenshot of your theme that you would be willing to share? (so we can see contrast / other problems)

**Comment by pHROZEN-gHOST** [comment]
This is current...



This is what it used to look like (taken from Chrome as it is now)...



The new icons are not consistent with what is in the bookmark manager. PLEASE don't change this too :-o


    On Wednesday, August 18, 2021, 02:32:15 p.m. EDT, Brian Clifton ***@***.***> wrote:  
 
 


@pHROZEN-gHOST the new icons are ones we had made actually - this happened with brave/brave-core#9424. If we reverted that pull request / patch, it would go back to the old look and feel

Do you have a screenshot of your theme that you would be willing to share? (so we can see contrast / other problems)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bsclifton** [comment]
@pHROZEN-gHOST dang - looks like the screenshots didn't post ☹️ If you're not able to get them, you can send over to clifton@brave.com and I can share w/ @karenkliu and design team

**Comment by Johann999** [comment]
Please revert to the old yellow icons. Asap. Thank you.

**Comment by raphaellueckl** [comment]
Suggestion: Remove the icon for folders completely. It's using space for nothing and they all look the same.

**Comment by pHROZEN-gHOST** [comment]
Um no!

That would be like ... Remove clothes entirely. They are just taking space.
    On Thursday, August 19, 2021, 08:40:10 a.m. EDT, Raphael Lückl ***@***.***> wrote:  
 
 


Suggestion: Remove the icon for folders completely. It's using space for nothing and they all look the same.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by worthdesigning** [comment]
> Suggestion: Remove the icon for folders completely. It's using space for nothing and they all look the same.

My car won't start - it's out of petrol. Oh well - better throw it out.

**Comment by Johann999** [comment]
Removing the icon is complete nonsense.
Please do not do any further experiments.
Just replace the current icon with the previous icon.
I wait for the solution every hour ...

**Comment by Cache22** [comment]
Like others this change has been difficult for me to adapt to. I have the bookmarks toolbar visible, and have thousands of bookmarks organized into multiple folder tiers (as I've done since the days of Netscape Navigator). 

With the latest update changing the folder icon into just an outline, it is not only more difficult on my eyes when finding bookmarks, it also just looks really strange and out of place, since the basic outline style for the folder doesn't match the style of any of the favicons. (Not even a few I found that have wireframe-ish favicons look good next to the folder outline icons.)

I have been trying to adapt to the change, since often just using something different for a while goes a long way towards making new changes flow just as well (or better) than what came before. But for this particular folder design change, I'm still actively getting annoyed every time I use bookmarks, and it's still slowing down my workflow as badly as it did when the change was first introduced. (And most of the time I just start typing parts of the URL and use autocomplete, so for it's rather telling that I am noticing and getting annoyed by this as frequently as I am.)

I'm not against changes, in fact I'm the type of person that enjoys installing software updates (whether UX/UI changes, security, or anything else, something about watching software evolve a bit at a time is enjoyable). So I do like seeing new changes, and always keep an open mind since often adjusting to changes can also be difficult at first.

Unfortunately this particular change is just significantly UX breaking for me, and I have yet to be able to even begin adapting. I would really like to see the previous folder icon returned in the short term, but would still look forward to changes in the bookmark folder design, so long as it is something customizable. (I don't mean customizable per-folder, but just overall. ) Per-folder options as some have suggested would also be a nice to have, like the ability to drag a favicon.ico file onto a bookmark folder, however I think the best move in the short term is to simply reverse this particular change and discuss the possibility of additional future changes at a later time.

**Comment by greenspeace** [comment]
I'm going to add my complaint about this issue. With poor eyesight I now find it difficult to identify the Bookmarks Folders easily. This is a retrograde step in my opinion. The system wasn't broken so why was there a need to 'fix' it?

**Comment by DeeCalf** [comment]
Please revert Brave back to its previous yellow folders ASAP -- the current 'blank ones' look like folders a five year old would have to use in kindergarten.

In the meantime, what version of Brave would be best to revert back to, to avoid the current-version's blank folders? If you could provide a link for downloading the older version that would be great?

**Comment by Fgrassano** [comment]
Adding my voice to the rest, please put the yellow folders back :D

**Comment by teasider** [comment]
Please, this looks so bad. Please give an option to change the bookmark folder icon to something else or atleast back to the "full" one.
thanks!

**Comment by challo202** [comment]
Adding my voice to the list.
The new blank icons suck.

**Comment by karenkliu** [comment]
Hi all, Brave design team here - we are currently working on a "full" icon, which will be yellow for Windows. Thanks for all your patience!

**Comment by Johann999** [comment]
You don't have to create a new icon.
You just have to go back to the old icon.

**Comment by wwwutz** [comment]
> You just have to go back to the old icon.
As far as I understood that's not possible. The 'new' icons are monocolor-vector graphics. Some dev deep inside decided that the UI now has to be flawlessly resizable. Pixel-icons would end up in 8-bit game style graphics on these new stylish Retina 6K displays almost everybody uses today.

The only solution I would see is to supply multicolor svg icons to mimic pixel bases icons. but hey... that'll be a lot of work. I don't even think multi color is supported.

Thunderbird > 68.12 also did this move to svg icons. I didn't even dare  creating an issue there.

+1 for the brave devs and designer who at least react! Thanks for that!

**Comment by JeffreyStevens** [comment]
@karenkliu you will only fix Windows and not Mac?

**Comment by bsclifton** [comment]
@JeffreyStevens fix planned for all platforms 😄

**Comment by petecom** [comment]
26 days and nothing has happened ?!!

Where are the favorites toolbar folder icons located in Windws 10/Brave browser ? Give me the full path and I'll change it back to yellow, or is it even possible ?

I just now updated to Version 1.28.105 Chromium: 92.0.4515.131 (32-bit) to my Windows 10 Pro laptop, but yellow folders in question are NOT back !!

THIS IS UNBELIEVABLE !!

**Comment by pHROZEN-gHOST** [comment]
Even Google allowed users to revert to the yellow icons ... long long ago.
    On Tuesday, September 7, 2021, 08:25:01 a.m. EDT, Pete Comwest ***@***.***> wrote:  
 
 


26 days and nothing has happened ?!!

Where are the favorites toolbar folder icons located in Windws 10/Brave browser ? Give me the full path and I'll change it back to yellow, or is it even possible ?

I just now updated to Version 1.28.105 Chromium: 92.0.4515.131 (32-bit) to my Windows 10 Pro laptop, but yellow folders in question are NOT back !!

THIS IS UNBELIEVABLE !!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bsclifton** [comment]
OK folks - we got the icons (@karenkliu updated in the top post). Here's what they look like:
![image](https://user-images.githubusercontent.com/4733304/132458203-0c2c4db5-dbc2-4a26-80c4-8a0607092075.png)

I'll try to knock this out this week 😄

**Comment by thebigMoose** [comment]
Good, good, that will do for us windows users.

**Comment by petecom** [comment]
You "gt the icons"?

Why it took so long, why didn't you call me as I have had those icons for decades ?

How abut to change you WOKE  stuff to some ones who really can d something ?

**Comment by bsclifton** [comment]
OK folks - got a pull request open. Should be able to close this out tomorrow
https://github.com/brave/brave-core/pull/10037

**Comment by bsclifton** [comment]
Code is merged; next Nightly will feature the icons. We're planning to uplift to release channel - so this will be in our next release

Thanks for the feedback all 😄

**Comment by pHROZEN-gHOST** [comment]
EXCELLENT!
    On Wednesday, September 8, 2021, 02:33:54 a.m. EDT, Brian Clifton ***@***.***> wrote:  
 
 


OK folks - we got the icons ***@***.*** updated in the top post). Here's what they look like:


I'll try to knock this out this week 😄
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pHROZEN-gHOST** [comment]
Thanks for the great news.
    On Saturday, September 11, 2021, 04:53:07 a.m. EDT, Brian Clifton ***@***.***> wrote:  
 
 


Code is merged; next Nightly will feature the icons. We're planning to uplift to release channel - so this will be in our next release

Thanks for the feedback all 😄
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.29.80 Chromium: 93.0.4577.63 (Official Build) (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

```

- Verified the test plan from https://github.com/brave/brave-core/pull/10037

**_Regular window - Light theme_**
![image](https://user-images.githubusercontent.com/38657976/133055343-3d0b05e3-0787-4157-b967-0d22232975ce.png)

**_Regular window - Dark theme_**
![image](https://user-images.githubusercontent.com/38657976/133055543-4a6a126b-50a6-4437-a97b-a35e1da7e7a6.png)

**_Private window - Light theme_**
![image](https://user-images.githubusercontent.com/38657976/133055761-c4d6b17e-f524-42f1-9b7a-81974e71ca20.png)

**_Private window - Dark theme_**
![image](https://user-images.githubusercontent.com/38657976/133055907-ef9afb46-b821-4360-b5bb-bbb192ebf2f6.png)

**_Tor window - Light theme_**
![image](https://user-images.githubusercontent.com/38657976/133056026-1596970f-77f0-4d11-9edb-dfcedc5b24ce.png)

**_Tor window - Dark theme_**
![image](https://user-images.githubusercontent.com/38657976/133056132-51669e70-32b3-449f-9334-6dd41d6ba22c.png)

**Comment by pHROZEN-gHOST** [comment]
I hope this is released soon.
    On Monday, September 13, 2021, 05:50:48 a.m. EDT, GeetaSarvadnya ***@***.***> wrote:  
 
 


Verification passed on
Brave | 1.29.80 Chromium: 93.0.4577.63 (Official Build) (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

   
   - Verified the test plan from brave/brave-core#10037

Regular window - Light theme


Regular window - Dark theme


Private window - Light theme


Private window - Dark theme


Tor window - Light theme


Tor window - Dark theme


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kjozwiak** [comment]
> I hope this is released soon.

Planning on getting this out sometime today 👍 QA us running through verification's/reduced manual passes, You can follow the progress via https://github.com/brave/brave-browser/milestone/234.

**Comment by timchan96** [comment]
Honestly, I like the old icon.  It subtle yet noticeable and blends in with the dark theme.

**Comment by pHROZEN-gHOST** [comment]
I have it now.
Thanks to everyone involved in reversing this mess!!!!!!
    On Monday, September 13, 2021, 12:51:44 p.m. EDT, Kamil Jozwiak ***@***.***> wrote:  
 
 



I hope this is released soon.


Planning on getting this out sometime today 👍 QA us running through verification's/reduced manual passes, You can follow the progress via https://github.com/brave/brave-browser/milestone/234.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by preIdiot** [comment]
totally agree with @timchan96, previous icons blend completely with my theme. Can you add a setting for the previous icon theme?

**Comment by leventh** [comment]
> ## Test plan
> See [brave/brave-core#10037](https://github.com/brave/brave-core/pull/10037)
> 
> ## Description
> Update bookmark folder icon to increase legibility and align better to user preferences.
> 
> Original description:
> 
> > I am a web developer, and I manage different clients in my bookmark folders.
> > 
> > * The new update, changed all the bookmark folder icons to be: ![image|33x26](https://camo.githubusercontent.com/850b4c118c9346bde3857117932a452e236e435c005babc2a1142008ce56ddaa/68747470733a2f2f617773312e646973636f757273652d63646e2e636f6d2f62726176652f6f726967696e616c2f33582f632f642f636464336130366231363538303432613162383633326132613563383763643265326239663133322e706e67)
> > * This has made it a little more bland and hard to separate the folders at a glance
> > * Since the icon are the same color as the text now, everything kind of blends together
> > * This wasn't the case prior, when a very visible yellow folder separated them
> 
> CURRENT:
> ![image|243x27](https://camo.githubusercontent.com/f3fa13d6d953ea52de1e8b8491a323d76256c3d0a6933142573f9675f77d786e/68747470733a2f2f617773312e646973636f757273652d63646e2e636f6d2f62726176652f6f726967696e616c2f33582f302f662f306631643630393037363061653763303431633332383961386535323330613161343261623336342e706e67)
> 
> OLD:
> ![image|244x28](https://camo.githubusercontent.com/d4b3cb552a4e886332703d7f7114c3bf868f77411cb4619e26eb5f163439cdd2/68747470733a2f2f617773312e646973636f757273652d63646e2e636f6d2f62726176652f6f726967696e616c2f33582f382f662f386666323336663739333134623934343264656231613732336239333362383964386130306534332e706e67)
> 
> ## Design
> MacOS + Linux
> ![image](https://user-images.githubusercontent.com/2388823/132382003-c1347b73-9ddf-4f03-b8e5-7654f5ea56b3.png)
> ![image](https://user-images.githubusercontent.com/2388823/132382019-023332e7-7eaa-4017-8945-656bc7290ea4.png)
> 
> Windows
> ![image](https://user-images.githubusercontent.com/2388823/132381975-034c0ba6-de3c-4053-b195-337fffb221ad.png)
> ![image](https://user-images.githubusercontent.com/2388823/132381988-918758b2-172f-4021-9bfc-6b60a14cea0d.png)
> 
> ## Assets
> Figma: https://www.figma.com/file/sS3l8tqUFxt54MEiBTalUI/?node-id=9%3A5824

I think it looks pretty good, especially on macOSX

**Comment by challo202** [comment]
thanks for reverting these icons back to yellow. As a researcher, I must have, literally, thousands of bookmarks.
The yellow icons are a life saver for me.
Now, can you do blue, pink, purple, .   .   .   .   ;)

**Comment by Vizorous** [comment]
Is this change reversible? Any options for it? I sorta loved the white icons.

**Comment by SingerGuy** [comment]
> Is this change reversible? Any options for it? I sorta loved the white icons.

Sorry, the tribe has spoken. ;)

**Comment by 831Digital** [comment]
THANK YOU FOR REVERTING TO YELLOW!!!!!!!!!!!!!!!!!!

**Comment by challo202** [comment]
If my icons had been white perhaps I wouldn't have minded.
They were not white. They were clear and not even noticeable.
from a "tribe"  member .  .  .

**Comment by InternetDownloader** [comment]
Long time Brave user here (and long time Brave lover!). Part of the "Yellow Folder Tribe"

I noticed the icons are not only yellow again, but they're beautiful! 😍 Way to go!

**Comment by thebigMoose** [comment]
Thank you the new icons look good and fulfill their purpose.  Please try to
restrain change for change sake going forward.

**Comment by ahmed1smael** [comment]
unpopular opinion, I want the grey folders back :) either way works for me but is it now an option that I can change ?

**Comment by zevrix** [comment]
> OK folks - we got the icons (@karenkliu updated in the top post). Here's what they look like:

why macOS icons are still gray?? please don't follow Apple's lead of introducing constant new ugly changes to their UI. please restore yellow icons on Mac - thanks!

**Comment by zevrix** [comment]
> thanks for reverting these icons back to yellow. As a researcher, I must have, literally, thousands of bookmarks. The yellow icons are a life saver for me. Now, can you do blue, pink, purple, . . . . ;)

hmm... the icons are still gray here on Mac. we need yellow icons back!

**Comment by davidmreid** [comment]
Hi Metehan,
Mine started working again all of sudden without any help from me. Go figure!
-David

---------------------------David ***@***.*** 

    On Monday, January 30, 2023 at 01:10:02 PM PST, Metehan Karabiber ***@***.***> wrote:  
 
 


I am a Mac user just b/c of the ugly bookmark icons, I switched to Firefox. Please fix.

**Comment by IBTS90** [comment]
yoooo mate, what happen with this Icon style, it's disgusting and hurting my eyes, GIVE ME BACK THE OLD FASHION YELLOW FOLDER!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by djphoenix974** [comment]
Please bring back the classic yellow folder icons 🙏 The new white ones hurt the eyes and lack personality.

**Comment by yayaya12004** [comment]
I left Chrome for messing with the interface and changing the folder colors. All who are claiming to go to Chrome, this won't work. It may be time to explore Firefox again. Fix it Brave, I was so happy to find you.

**Comment by Conqueror933** [comment]
Give me back my yellow folders ffs, this is literally the reason I switched from chrome to brave. Stop changing the fucking UI for no goddamn reason.
If you want to give more options for UI, great. Make them opt-in features and don't just change existing things.

**Comment by gregeeh** [comment]
Bring back the yellow folder icons.

**Comment by scotto88** [comment]
I prefer the yellow option. Give us a choice to toggle which color we want.

**Comment by smokeyllama** [comment]
> https://github.com/brave/brave-core/pull/32154#issuecomment-3506038637/

Anyone needing the solution; its already been added:
`Address Bar` > `brave://flags/#brave-filled-bookmark-folder-icon` > `Enabled`
