### ISSUE TITLE
TorDisabled key doesn't appear to disable Tor in MacOS

### ISSUE THREAD

**Issue by 3jdp** [brave/brave-browser#17530]
## Description 
Hi- 
Per [this](https://github.com/brave/brave-browser/issues/15202) and other issue listings, the following should disable Tor in MacOS.

`defaults write com.brave.Browser TorDisabled -integer 1`

but it has no visible effect.

We are disallowing usage of Brave on Mac systems until we can disable this. 

## Steps to Reproduce

   1. Install Brave post-1.3
   2.  Use defaults command above
   3.  Launch Brave, choose File -> and examine items in that menu.

## Actual result:
"New Private Window with Tor" is still there, and choosing that option opens a Tor window.

## Expected result:
"New Private Window with Tor" should either not be present or greyed out.

## Reproduces how often: 
Easily reproduced in 1.28.105 (latest). 

## Brave version (brave://version info)
Brave	1.28.105 Chromium: 92.0.4515.131 (Official Build) (x86_64)
Revision	6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS	macOS Version 10.15.7 (Build 19H1030)
JavaScript	V8 9.2.230.22
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --user-data-dir=/Users/MyUsername/Library/Application Support/BraveSoftware/Brave-Browser --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,LegacyTLSEnforced,AutoupgradeMixedContent,SafetyTip,PasswordImport,ReducedReferrerGranularity,PrefetchPrivacyChanges --disable-features=SignedExchangeSubresourcePrefetch,IdleDetection,FledgeInterestGroups,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,DirectSockets,TrustTokens,InterestCohortFeaturePolicy,WebOTP,NotificationTriggers,InterestCohortAPIOriginTrial,FledgeInterestGroupAPI,AutofillEnableAccountWalletStorage,FirstPartySets,FederatedLearningOfCohorts,PrivacySandboxSettings,SignedExchangePrefetchCacheForNavigations,NetworkTimeServiceQuerying,SubresourceWebBundles,HandwritingRecognitionWebPlatformApi,AutofillServerCommunication,LiveCaption,LangClientHintHeader,EnableProfilePickerOnStartup,TextFragmentAnchor,EnablePasswordsAccountStorage --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/MyUsername/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations	AdRewardsStudy:NextPaymentDay
AdServingStudy:MaximumAdNotificationsPerDay=100
AdvertiserSplitTestStudy:GroupA
BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0h
BraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5
EphemeralStorageStudy:Enabled
MacCoreLocationBackendStudy:Enabled
NativeCosmeticFilteringStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
SpeedreaderReleaseStudy:Disabled

## Version/Channel Information:
Seems to have been an issue for a while. I also went back and downloaded a 'Nightly' version 1.3.4 to see if this is a regression and it doesn't work there.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  n/a
- Does the issue resolve itself when disabling Brave Rewards?  n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
We tested this on Windows using steps in this article https://support.brave.com/hc/en-us/articles/360039248271 and that worked fine. 

This also occurs using macOS Big Sur 11.5.

Using the steps to disable Incognito from the same 15202 issue (`defaults write com.brave.Browser IncognitoModeAvailability -integer 1`) works fine.

**Comment by yrliou** [comment]
We currently only support Tor policy on Windows (https://github.com/brave/brave-core/blob/master/script/policy_source_helper.py#L19), we should consider support all platforms,  cc @simonhong

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.30.38 Chromium: 93.0.4577.51 (Official Build) nightly (x86_64)
-- | --
Revision | 762d21050e2da59930c784c09b134d0b0b148188-refs/branch-heads/4577@{#915}
OS | macOS Version 11.5.2 (Build 20G95)


Steps:
1. wrote `defaults write com.brave.Browser TorDisabled -integer 1` into a `Terminal.app` window and pressed `enter`
2. new profile
3. launched Brave
4. clicked on the "hamburger" menu and confirmed there's no `New Private Window with Tor` option
5. clicked on the File menu and confirmed `New Private Window with Tor` is ghosted out
6. loaded `brave://policy` and confirm `TorDisabled` is set to `true`

Note: filed https://github.com/brave/brave-browser/issues/17609 since the `Private Window with Tor` Settings menu item should be disabled.

example | example | example
---------|---------|---------
<img width="1461" alt="Screen Shot 2021-08-20 at 8 55 01 AM" src="https://user-images.githubusercontent.com/387249/130287741-992eaac2-6c27-4a63-87ed-0b2d02e5031a.png"> | <img width="1262" alt="Screen Shot 2021-08-20 at 11 50 11 AM" src="https://user-images.githubusercontent.com/387249/130287545-acdb27c4-59ae-4d41-89bc-c8dab4d15656.png"> | <img width="1461" alt="Screen Shot 2021-08-20 at 8 56 27 AM" src="https://user-images.githubusercontent.com/387249/130287467-1d288456-e194-42a2-983c-23d478d9e438.png"> |

**Comment by 3jdp** [comment]
Thanks for implementing this so quickly! 

FYI For documentation purposes, it looks like the previous command mentioned `defaults write com.brave.Browser TorDisabled -integer 1` errors out when I tried with Nightly build 1.30.48/93.0.4577.51, but `defaults write com.brave.Browser TorDisabled -bool true` does the trick.
