### ISSUE TITLE
When bitFlyer access token has expired or reauth is required from user, make sure wallet goes into "Disconnected" state

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#17678]
## Description

In several cases, the user's bitFlyer access token will be expired and the user will need to reauth. 

The UI does not seem to detect this, and does not move the user into a `Disconnected` state so that they know to reauth. As a result, some requests to bitFlyer (such as sending a tip) can fail silently in the background, and there is no indication to user that they will need to reauth. 

Message @A-t-s-u-s-h-i and @Miyayes for more specifics.

**Comment by zenparsing** [comment]
We should audit all calls to the bitFlyer API endpoints to make sure that:

* we are correctly detecting responses that indicate an expired access token, and
* callers are then putting the wallet into the disconnected state when that happens.

We might want to take a look at the transfer API endpoint(s) in particular.

**Comment by zenparsing** [comment]
We may be able to address both #17692 and this in the same PR.

**Comment by szilardszaloki** [comment]
The "tipping endpoint" (`POST api/link/v1/coin/withdraw-to-deposit-id/request`) has an extra timeout condition, which doesn't have anything to do with how frequently the access token expires (`HTTP 401 (Unauthorized)`). Basically, if it's been more than seven days since the last authentication, this endpoint returns `HTTP 409 (Conflict)` with `"transfer_status": "SESSION_TIME_OUT"`, regardless of how old your access token is. The problem is that currently this is not implemented on our end.

**Comment by LaurenWags** [comment]
labelling as `QA/Blocked` until there is a test plan added to https://github.com/brave/brave-core/pull/9962

**Comment by szilardszaloki** [comment]
Sending the `Test Plan` via Slack DM.

**Comment by LaurenWags** [comment]
@brave/legacy_qa the test plan is available under https://github.com/brave/internal/issues/803. All verification notes can be added to that internal issue as well.
