### ISSUE TITLE
Generic cosmetic filtering should not be applied to html/body elements

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#17695]
uBlock Origin has added a change to avoid matching generic cosmetic filters to `html` and `body` elements. This would be a good webcompat improvement to take up as well.

More context in https://github.com/uBlockOrigin/uBlock-issues/issues/1692.

**Comment by ryanbr** [comment]
Tested https://github.com/easylist/easylist/commit/d43697677a69ef8b40a81f73d88d0f9f879217fb  (which was removed since .consent-modal was applied to body).

`<body dir="ltr" data-klarna-placements="true" class="modal-open modal-fade consent-modal" style="padding-right: 17px;">`

Working fine in Brave Nightly.

Will leave the existing filters alone since other adblock extensions (ABP) still apply to body/html.
