### ISSUE TITLE
Wallet payment ID information lost error in version 1.28.106

### ISSUE THREAD

**Issue by Tcm997** [brave/brave-browser#17718]
## Description
about 2-3 days i lost my Wallet payment ID in Wallet info !
Wallet info says that the wallet address has not been created while I was still using it before!

## Steps to Reproduce

   1. use more than 5 hours per
   2. check Wallet info and log
   3. error Wallet not created 

## Actual result:
![240405059_3090122261265514_4359133961530182024_n](https://user-images.githubusercontent.com/89618263/131056653-9c0b307d-2cf5-4a03-a72a-5574f8888d9f.png)
![240606340_206366574880149_7732929799713713741_n](https://user-images.githubusercontent.com/89618263/131056655-7036e9ba-503c-45c4-926d-3ac235513cd4.png)
![240610490_1308295436240144_29163541644967550_n](https://user-images.githubusercontent.com/89618263/131056658-a0161ec6-e052-4516-bbfc-b1ccb7539b4c.png)

## Version/Channel Information:
- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
Hi, thanks. Can you let us know how much BAT you had before this happened? Also, you can reach out on community.brave.com, and they'll be able to help you there. You can let them know bat-chriscat sent you :)

In short, your Brave Browser.app doesn't have permission to your Windows encryption/decryption module, so we're unable to decrypt your wallet.  

Also, make sure you're updated now to v1.29.x+ of the browser, since we introduced some guards to avoid making your situation more complicated.

**Comment by srirambv** [comment]
This may be similar to #13489. @Tcm997 does toggling Ads switch fix it for you?

**Comment by zenparsing** [comment]
Note: wallet encryption/decryption is removed in as of https://github.com/brave/brave-browser/issues/17571.

**Comment by Miyayes** [comment]
Your Brave Browser app doesn't have permissions to access the crypto module in your OS, so it can't decrypt your wallet, leading to this error. This should be resolved with #17571. I recommend you updating your browser immediately to v1.29.x as well in the meantime.
