### ISSUE TITLE
Fingerprint doesn't gets changed on Browser Restart

### ISSUE THREAD

**Issue by Nihal247** [brave/brave-browser#17818]
## Description 
I know Brave provides protection to fingerprinting, and I've seen tests in which my fingerprint changes with every Brave browser's restart , whereas other browsers don't have the same scenario.

But when tested on https://fingerprintjs.com, my  unique fingerprint ID doesn't gets changed!

## Steps to Reproduce

   1. Go to https://fingerprintjs.com
   2. Mark your unique ID.
   3. Restart Brave, you'll still see the unique ID.
   4.  Delete all Brave data, you'll still see the same unique ID.

## Actual result:
The unique fingerprint ID should change.

## Expected result:
The unique fingerprint ID doesn't changes.

## Reproduces how often: 
Easily reproduced

## Desktop Brave version:
1.29.76

## Android Device details:
   - Install type (ARM, x86): x86
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 7.0

## Version/Channel Information:
All other channels.

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by pes10k** [comment]
Hi @Nihal247, thanks for the issue. I'm going to close this out bc the underlying issues a duplicates of other issues, but wanted to explain a bit about whats going on here.

The short of it is that whats going on here isn’t actually browser fingerprinting, its a site that sells a commercial fingerprinting product doing things that are unrelated to browser fingerprinting (and wouldn’t work in a third party context) to sell their trash.

They’re doing a combination of standard browser storage, IP matching, and cache polluting to re-identify visitors to the same 1p, none of which are browser fingerprinting.

You can confirm the same by varying all the below at the same time, but not varying signals used for browser fingerprinting, and revisiting the site.  Specifically:

1. Create a browser profile and run the fingerprintjs demo
2. Create a new browser profile, change your IP address (tor tab, VPN, whatever) and revisit the fingerprintjs demo

You should consistently get a new ID each time.

This might seem like splitting hairs, but its important because Brave currently offers, or is preparing to release defenses for whats really going with the fingerprintjs site:

Re standard browser storage: Brave is working on something we call “ephemeral first party storage” which would allow users to visit a 1p site, w/o the 1p being able to persist any storage.  We expect this to roll this out very soon

Re: IP matching, Brave already offers Tor tabs and (on iOS) VPN for this

Re Cache polluting, upstream / chromium is very close to solving this problem through their NetworkIsolationKey approach to partitioning caches by 1p (you can experiment with this now too if you go to brave://flags and enable the relevant network isolation key features). We expect to enable this by default shortly too.

Hope that all helps explain what you’re seeing, why its not related to brave’s fingerprinting defenses, why fingerprintjs is selling everyone (particularly their customers) a bill of goods, and some of Brave’s upcoming privacy improving features!

**Comment by pes10k** [comment]
here btw is the 1p ephemeral storage issue mentioned above, just to name one of the issues.  https://github.com/brave/brave-browser/issues/15906

For the cache polluting issue, here is the tracking issue Brave has for enabling NetworkIsolationKey support https://github.com/brave/brave-browser/issues/11816

**Comment by Nihal247** [comment]
I am not getting the same ID with different profiles also. What am I doing wrong?

**Comment by naox** [comment]
@pes10kSorry, but that explanation is bs. You got defensive because you can't handle truth that something might be leaking from Brave which it is.

Since https://fingerprintjs.com/demo/ gives you only one "your id" value computed from many elements than obiously chaning one like IP will change it. Thats not a point. Point it that it should be diffrent every time on same IP.

Firefox browser with extension "Canvas Blocker - Fingerprint Protect" (+ cleaning cookies, data, storage) gives on ttps://fingerprintjs.com/demo/ diffrent "your id" every time (same IP).

Brave with cleaning cookkied, data, storage (same IP) gives same "your id" on ttps://fingerprintjs.com/demo/ every time
