### ISSUE TITLE
Remove Brave ads dev environment

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#17812]

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.31.66 Chromium: 94.0.4606.61 (Official Build) beta (x86_64)
-- | --
Revision | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS | macOS Version 11.6 (Build 20G165)

### Staging (`--brave-ads-staging --rewards=staging=true`)

#### Steps:

1. new profile
2. launched Brave `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=3`
3. open a new-tab page
4. click the `Start using Rewards` button
5. scrolled down on the new-tab page
6. clicked on `Show Brave News`
7. scrolled down to find an inline-content ad
8. viewed the ad
9. opened `brave://rewards` and the new-tab page
10. confirmed I was paid for viewing the ad
11. waited
12. resumed activity on computer after some time
13. viewed system-notification ad
14. confirmed via the NTP and `brave://rewards` I was rewarded for viewing it
15. viewed a promoted-content ad in Brave News, but wasn't rewarded for it
16. viewed a NTP sponsored image, but wasn't rewarded for it

|              ad type         | `brave://rewards` / actual ad | NTP widget / error |
|----------------------|-----------------|------------|
| system notification  | <img width="1526" alt="Screen Shot 2021-09-28 at 10 39 47 PM" src="https://user-images.githubusercontent.com/387249/135360411-14ea0693-6e89-4ff2-a90d-2e346977540b.png"> | <img width="294" alt="Screen Shot 2021-09-28 at 10 42 45 PM" src="https://user-images.githubusercontent.com/387249/135360415-124d0878-edf0-437f-8ba8-387b2a29dea2.png"> |
| NTP SI                       |   <img width="260" alt="Screen Shot 2021-09-29 at 4 33 25 PM" src="https://user-images.githubusercontent.com/387249/135362631-a4c40df7-a325-48c7-87ea-7a8b74d233b9.png"> | [`4989:259:0929/163219.627191:VERBOSE1:new_tab_page_ad.cc(64)] Failed to fire new tab page ad event due to missing creative instance id 5a6770ec-79b3-4adf-82ba-c087dfcb65ad` |
| inline content             |   <img width="1332" alt="Screen Shot 2021-09-28 at 10 29 44 PM" src="https://user-images.githubusercontent.com/387249/135360063-a342194a-ce62-433d-99dd-974920109c29.png"> | <img width="241" alt="Screen Shot 2021-09-29 at 4 04 21 PM" src="https://user-images.githubusercontent.com/387249/135360293-7f187d7a-8d82-447e-bd8f-cb4c701e974d.png"> | 
| promoted content     |  <img width="713" alt="Screen Shot 2021-09-29 at 4 23 13 PM" src="https://user-images.githubusercontent.com/387249/135362138-4e9533fa-ebdb-433a-a04d-7775cb35d42e.png"> | `[4989:259:0929/162116.024770:VERBOSE1:promoted_content_ad.cc(64)] Failed to fire promoted content ad event due to missing creative instance id d2d506aa-5531-4069-8f85-7d9052f1b640` |                    |

### Production

#### Steps:

1. new profile
2. launched Brave `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6`
3. opened a new-tab page with a sponsored image
4. confirmed I was paid for viewing the ad
5. waited a while
6. started typing
7. viewed a system-notification ad
8. confirmed I was paid for viewing the ad
9. opened a new-tab page
10. viewed a sponsored-image ad, but wasn't rewarded
11. wasn't able to view any inline-content ads
12. viewed a promoted-content ad, but wasn't rewarded for it


|                      ad type   | `brave://rewards` / ad | NTP widget / error|
|----------------------|-----------------|------------|
| system notifications  | <img width="1312" alt="Screen Shot 2021-09-28 at 11 06 14 PM" src="https://user-images.githubusercontent.com/387249/135361036-824fdd96-5af8-47ad-aa76-5a659c1340b0.png"> | <img width="308" alt="Screen Shot 2021-09-28 at 11 06 35 PM" src="https://user-images.githubusercontent.com/387249/135361068-566acd87-0f98-44c3-9223-cf6aa1fcced0.png"> |
| NTP SI                          |  <img width="1695" alt="Screen Shot 2021-09-28 at 10 53 17 PM" src="https://user-images.githubusercontent.com/387249/135360672-86603703-0d16-4142-95e5-3abbb7b50c54.png"> | <img width="296" alt="Screen Shot 2021-09-28 at 10 53 27 PM" src="https://user-images.githubusercontent.com/387249/135360707-f9ffe32d-f2f6-4724-8616-73e50c2fa4a7.png"> | 
| inline content             |          unavailable at time of testing (did not appear)  |        unavailable at time of testing (did not appear)   |
| promoted content     |  <img width="696" alt="Screen Shot 2021-09-29 at 4 51 13 PM" src="https://user-images.githubusercontent.com/387249/135363951-76fa2eb2-17cb-4009-b496-e5defdadd359.png"> | | `[5280:259:0929/165049.368080:VERBOSE1:promoted_content_ad.cc(64)] Failed to fire promoted content ad event due to missing creative instance id d2d506aa-5531-4069-8f85-7d9052f1b640`          |

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.31.86 x64 build
- Verified ads work fine on production environment
- Verified ads work fine on staging environment
------------
Verification passed on Samsung Tab A with Android 10 running 1.31.86 x64 build
- Verified ads work fine on production environment
- Verified ads work fine on staging environment
