### ISSUE TITLE
Add a sleeping tab feature in Brave like it is present in Microsoft Edge

### ISSUE THREAD

**Issue by clicky6** [brave/brave-browser#17827]
![image](https://user-images.githubusercontent.com/89839714/131794888-339cbb7b-5cb1-4939-9b6c-679a2608074c.png)

Add a **sleeping tab** feature in Brave like it is present in Microsoft Edge. It helps to reduce consumption of system resources by putting tabs to sleep after a certain amount of time described by the user.

**Comment by Tonev** [comment]
I've never used `Microsoft Edge` but your suggestion sounds like a duplicate of https://github.com/brave/brave-browser/issues/17453, is that correct?

**Comment by clicky6** [comment]
Yes.

**Comment by Tonev** [comment]
CC: @bsclifton

**Comment by clicky6** [comment]
@Tonev How to do find duplicate issues?🤔

**Comment by Tonev** [comment]
Well, I like Brave so I browse Github on a regular basis (mostly daily basis) to stay in touch with upcoming changes, etc, also I'm a regular `Brave Community` user which is also helping me. I remembered seeing a very similar issue to yours, searched for it and it turned out your issue is a duplicate. But to answer your question - you should use the search functionality of Github before opening an issue, although sometimes you might be given tons of random issues, it heavily depends on what you're searching for.

**Comment by clicky6** [comment]
Thank You very much Sir.

**Comment by bsclifton** [comment]
Thanks for the assist, @Tonev 😄 

Closing as a duplicate of https://github.com/brave/brave-browser/issues/17453 - you can subscribe there for updates 😄 (I shared your screenshot there too!)
