### ISSUE TITLE
Unable to exit Speedreader mode/disable Speedreader

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#17949]
## Description 

Unable to exit Speedreader mode/disable Speedreader

## Steps to Reproduce

1. new profile
2. launch Brave
3. load `https://www.reuters.com/technology/cryptocurrencies-selloff-widens-bitcoin-down-nearly-4-ether-6-2021-09-07/`
4. click on the `Reader Mode` icon in the URL bar
5. click to enable Speedreader
6. now, click on the Speedreader icon again

## Expected:
The page exits Speedreader/Reader Mode, and returns to “full” HTML mode rendering

<img width="1312" alt="Screen Shot 2021-09-07 at 6 14 17 PM" src="https://user-images.githubusercontent.com/387249/132561580-3f0cd386-02b3-4733-a968-8b7a185b303b.png">

## Actual:
Even though it appears I’ve toggled reader mode to `Off`/`Disabled`, it persists for this tab

<img width="1312" alt="Screen Shot 2021-09-07 at 6 13 48 PM" src="https://user-images.githubusercontent.com/387249/132561643-2316b913-4e43-456d-8777-c5aeb82403cf.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.31.27 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.5.2 (Build 20G95)

/cc @keur

**Comment by keur** [comment]
Added `release-notes/exclude` since this bug hasn't made it out of nightly.

**Comment by keur** [comment]
## Test Plan

Ensure the per-site toggle works as expected. Thanks @stephendonner !

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.31.44 Chromium: 94.0.4606.41 (Official Build) nightly (x86_64)
-- | --
Revision | 333e85df3c9b656b518b5f1add5ff246365b6c24-refs/branch-heads/4606@{#845}
OS | macOS Version 11.6 (Build 20G165)

Steps:

1. load `https://www.reuters.com/technology/cryptocurrencies-selloff-widens-bitcoin-down-nearly-4-ether-6-2021-09-07/`
2. click on the Reader Mode icon in the URL bar
3. click to enable Speedreader
4. now, click on the Speedreader icon again

Confirmed I was able to toggle Speedreader on/off at will

example | example
---------|---------
<img width="1312" alt="Screen Shot 2021-09-15 at 8 51 39 AM" src="https://user-images.githubusercontent.com/387249/133466975-43f0a25c-3e0b-4e4a-a505-b966e8354568.png"> | <img width="1312" alt="Screen Shot 2021-09-15 at 8 51 43 AM" src="https://user-images.githubusercontent.com/387249/133466982-7aebf6ee-6423-4513-92af-e93cdd544ba0.png">

**Comment by Tonev** [comment]
@keur @stephendonner 

Sorry for disturbing you, folks, I just wanted to ask if the fix for this is available in:

<html>
<body>


Brave | 1.31.51 Chromium: 94.0.4606.50 (Official Build) nightly (64-bit)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | Windows 7 Service Pack 1 (Build 7601)
JavaScript | V8 9.4.146.16
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.50 Safari/537.36


</body>
</html>

I can reproduce the bug, described by @stephendonner, so thought I would ask. I'm not aware how `Brave Nightly` versions are released on macOS, compared to Windows, and it looked like the issue is still present in `Brave Nightly`.

**Comment by stephendonner** [comment]
@Tonev thanks; I think this is a related, but distinct, issue (which I still should've found while testing this issue's fix).  Please file a new issue?  Thanks!
