### ISSUE TITLE
Been facing this issue for atleast twice a month.

### ISSUE THREAD

**Issue by grey1631** [brave/brave-browser#18002]
![Untitled1111111](https://user-images.githubusercontent.com/90464055/132870514-29bee945-98a7-411f-834f-a41b49a6edef.png)
only happens when I switch to widescreen on youtube.

**Comment by Tonev** [comment]
Looks like an issue caused by `Hardware Acceleration`. 

Please, check whether disabling `Hardware Acceleration` via `brave://settings/system` resolves the issue.

**Comment by Miyayes** [comment]
This issue is also associated with `fingerprinting blocked (strict)` in Shields settings.

**Comment by Tonev** [comment]
That's very unlikely. I've been using `Brave Shields` with `aggressive` ads & trackers blocking, and `strict` fingerprinting protection since the beginning - have never experienced a similar issue. Furthermore, we get similar reports in `Brave Community` now and then, the usual fix is disabling `Hardware Acceleration`.

**Comment by PegHorse** [comment]
Try to use OpenGL on video renderer instead of D3D11
