### ISSUE TITLE
sync stops working and password data loss, cr94 related

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#18138]
## Description 

On update to 1.31.41 chromium 94.0.4606.41, lost my passwords and noticed that sync is no longer working.

## Steps to Reproduce

   1. Have sync enabled for several clients. Have passwords and other data types synced.
   2. Upgrade nightly from 1.31.x cr 93 version to 1.31.41 and above.
   3. Notice passwords are wiped out, sync internals aren't working, and brave://settings/braveSync/setup doesn't toggle.

## Actual result:

Will provide sync-internals.

## Expected result:
Sync should continue to be working and no data loss on passwords.

## Reproduces how often: 

Maybe difficult to reproduce.

## Brave version (brave://version info)

This is arm64 macOS only. Windows continues to Sync and passwords are intact. 
macOS 12.0 beta Monterey

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by AlexeyBarabash** [comment]
Just reproduced this immediately, even after giving the keychain access

**Comment by AlexeyBarabash** [comment]
cc @jsecretan , @darkdh

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.30.80 Chromium: 94.0.4606.50 (Official Build) beta (x86_64)
-- | --
Revision | 0c1ac2c4842a4746c27c937c1a0453f98da1a972-refs/branch-heads/4606@{#1049}
OS | macOS Version 11.6 (Build 20G165)



### Check keychain access

1. Open `Keychain Access.app`
2. Under `Local Items`->`All Items` and find `Chromium Safe Storage` and `Brave Safe Storage`
3. Open them separately and delete all items in access control list
4. Launch Brave with this fix
5. Brave should prompt asking for access to `Brave Safe Storage` instead of `Chromium Safe Storage`

<img width="546" alt="Screen Shot 2021-09-17 at 11 09 05" src="https://user-images.githubusercontent.com/387249/133841414-9315a9c8-9e12-46e0-99ba-ec4b5f306306.png">


### Import

1. Make sure chrome have stored passwords
2. Open Brave and import passwords from chrome
3. Allow access to chrome safe storage
4. passwords should be successfully imported
5. change chrome to chromium and repeat step 1-4

Confirmed passwords were imported

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2021-09-17 at 11 10 38 AM" src="https://user-images.githubusercontent.com/387249/133842012-9f5e529c-4dfc-4e55-9260-10e5be927f45.png"> | <img width="1312" alt="Screen Shot 2021-09-17 at 12 16 59 PM" src="https://user-images.githubusercontent.com/387249/133842233-d2548748-74b5-4ee6-b5db-a859fb0121ff.png"> | <img width="1312" alt="Screen Shot 2021-09-17 at 12 16 27 PM" src="https://user-images.githubusercontent.com/387249/133842082-308f1809-2cc6-47f3-8a8f-d7e8ac1b1548.png">


### Migration

1. Stored passwords, credit cards and setup sync in pre C94 Brave (`1.31.37`)
2. Upgraded to C94 Brave (`1.31.41`)
3. Checked passwords, credit cards are gone and sync is not working
4. Upgraded to Brave with this fix (`1.30.80`)
5. Confirmed passwords & credit cards in step 1 are back, and sync works

example | example | example | example
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2021-09-17 at 12 16 27 PM" src="https://user-images.githubusercontent.com/387249/133844788-a7ca6936-b2f2-4c0a-9967-4d133652534e.png"> | <img width="1312" alt="Screen Shot 2021-09-17 at 12 44 51 PM" src="https://user-images.githubusercontent.com/387249/133845119-a6d21d7c-2666-49bd-b2ac-88e47e5c7b91.png"> | <img width="1312" alt="Screen Shot 2021-09-17 at 12 43 17 PM" src="https://user-images.githubusercontent.com/387249/133844912-77dd1283-9e64-42c9-ac01-27b65080d138.png"> | ![Screenshot_20210917-124033](https://user-images.githubusercontent.com/387249/133844997-27c77dec-9e8c-4572-a5df-1019fdc20c57.png)
