### ISSUE TITLE
Create wallet P3A questions

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#18254]
`Brave.Wallet.UsageDaily`
Have you used the Brave Wallet in the last calendar day?

```
0 - No
1 - Yes
```

`Brave.Wallet.UsageWeekly`
Have you used the Brave Wallet in the last calendar week (starting on Monday)?

```
0 - No
1 - Yes
```

`Brave.Wallet.UsageMonthly`
Have you use the Brave Wallet in the last calendar Month (starting on the 1st)?

```
0 - No
1 - Yes
```

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```

Brave | 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)
-- | --
Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
OS | Windows 10 Version 21H1 (Build 19043.1348)

```

**Comment by GeetaSarvadnya** [comment]
@rillian and @iefremov @porteron I am done with the verification on the above issue.  Can any of you review the scenarios and let me know if I have missed anything?

**Comment by porteron** [comment]
@GeetaSarvadnya The metrics are collected irrespective of which wallet they have used. This question reflects data for general wallet usage.

**Comment by rillian** [comment]
@GeetaSarvadnya Test plan looks good. If wallets can be destroyed, it's worth checking whether that resets the usage values to `0`.

**Comment by GeetaSarvadnya** [comment]
@porteron Thanks for the clarification!

@rillian Thanks for your feedback. Reset wallet scenarios are added in https://github.com/brave/brave-browser/issues/18254#issuecomment-970536397

We just need a clarification on the Reset wallet scenario mentioned below:

1. Set the system date to 29th Nov
2. Clean profile `1.32.106`
3. Create a brave wallet
4. Open brave://local-state file
5. Confirmed `Brave.Wallet.UsageDaily`, `Brave.Wallet.UsageWeekly` and `Brave.Wallet.UsageMonthly` stats values are `1` as expected
6. Reset the wallet via brave://settings/wallet and close the browser
7. Set the system date to 1st Dec
8. Restart the browser and confirmed  `Brave.Wallet.UsageDaily` = `0`, `Brave.Wallet.UsageWeekly`= `0` and  `Brave.Wallet.UsageMonthly` = `0`
![image](https://user-images.githubusercontent.com/38657976/142375600-1b5d0a20-0b4c-4152-8659-a16551c3b625.png)

**Actual**: `Brave.Wallet.UsageWeekly`= `0` - weekly usage value is zero which is creating confusion, as we are expecting usage value as `1` because weekly stats collection starts from Monday, here the week is already started before the start of the month, so weekly stats should be collected from 29th Nov to 5th Dec according to the logic. We would like to know how the week stats are calculated for the week where two months overlap and wallet reset and month rollover happens in the same week.

**Comment by rillian** [comment]
I think it's less surprising for users if resetting the wallet also resets the stats to zero; so I'm fine with it working the way you describe. It does mean we'll miss some short-duration use, but I expect deleting the wallet will be a rare event.
