### ISSUE TITLE
HTTP download links don't work from an HTTPS location

### ISSUE THREAD

**Issue by Maxime-J** [brave/brave-browser#18308]
From an https location, an http link who triggers a download (for example exe on desktop, or pdf in mobile) doesn't work : nothing happens.
Even if we try to open it in a new tab.

The only way is to put the url in the address bar.

And that's very problematic with Google on mobile, because we can't have the direct link.
The Google redirection link doesn't do nothing, for the same reason as this issue.

## Quick ways to Reproduce

- On Google, search doc sample and find an http link
- Every download link here https://pomarede.fr/versions-anterieures-logiciels-ebp/gamme-2014-des-logiciels-ebp/

## Expected result:
The file should be downloaded

## Actual result:
Nothing happens

## Version/Channel:

Desktop and Android latest current releases

## Information:

This occurs independently of the Shield and the HTTPS upgrader states,
and it seems to be Brave specific => no problem with Edge.

**Comment by Tonev** [comment]
That's because insecure content is blocked by default on secure sites (`brave://settings/content/insecureContent`). I don't know how Microsoft Edge deals with insecure content, so I won't comment on that aspect of your ticket.

- For desktop:

1. Open `https://pomarede.fr/versions-anterieures-logiciels-ebp/gamme-2014-des-logiciels-ebp/`.
2. Click on the padlock icon in the address bar.
3. Click on `Site settings`.
4. Find and allow `Insecure content`.
5. Reload the page.

**Comment by Maxime-J** [comment]
Thanks for your answer @Tonev , should have thought about that..
Blocked insecure content has been around for quite some time now, but didn't it know it also applies to downloads now :
https://blog.chromium.org/2020/02/protecting-users-from-insecure.html

Weird that we are not warned though

And yes, Edge obviously didn't follow that change.
