### ISSUE TITLE
Tab mute and context menu mute do not reflect each other state

### ISSUE THREAD

**Issue by jardous** [brave/brave-browser#18428]
## Description 

Tab mute and context menu mute do not reflect each other state. Need to select "Mute tab" after that "Unmute tab" disabling the audio by clicking the mute tab icon to get it in sync.

## Steps to Reproduce

   1. Open new tab and go to any site that is playing audio (youtube for example)
   2. Click the speaker icon on the tab to mute the sound
   3. Right-click the tab

## Actual result:

"Mute tab" item present in the context menu

## Expected result:
"Unmute tab" item present in the context menu

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.29.81 Chromium: 93.0.4577.82 (Official Build) unknown (64-bit)
Revision | e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by rebron** [comment]
Mute tab icon and Mute/unmute sites are two different functions. 

The ux confusion is understandable but clicking on an icon to mute a tab, it's reasonable to expect folks to select that icon again to unmute versus using a right click action to an undo what they just did.

**Comment by jardous** [comment]
> Mute tab icon and Mute/unmute sites are two different functions.
From the user point of view I do not agree

**Comment by rebron** [comment]
If you open up 5 youtube tabs and play each tab, they will all play at the same time. You can mute each tab with the icon or you can right click one tab and mute the site and all of the youtube tabs will be muted.

It's not a matter of point of view or agreeing/disagreeing. 

There's two functions. One is to mute a tab and one is to mute a site. 

What it sounds like is you'd like us to add another context menu item for mute/unmute a tab.

As it is now, the speaker/mute icon wouldn't reflect the context menu because it's not same functionality.

**Comment by jardous** [comment]
Fair enough - this makes sense. Thanks for explaining the difference.
