### ISSUE TITLE
URL/Address Bar Really Laggy

### ISSUE THREAD

**Issue by Latias4Ever** [brave/brave-browser#18447]
## Description 
When doing anything on the Address Bar (typing, deleting), it seems to lag and take a while for anything to happen. It's especially worse when there's a relatively large URL on the bar. Right-clicking on the bar makes it take at least half a second for the menu to open. Even pressing enter to head to the URL takes a bit to work. This is only for the Address Bar, everything else is working as normal.

## Steps to Reproduce

   1. Doing anything on the URL bar.

## Actual result:
Unable to show in screenshot. URL/Address bar is laggy and really slow when typing, deleting, and even right-clicking it.

## Expected result:
Fast typing/deleting and instant opening of the right-click menu.

## Reproduces how often: 
Happens all the time.

## Brave version (brave://version info)
<html>
<body>

Brave | 1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit)
-- | --
Revision | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
OS | Windows 8.1 (Build 9600.18822)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? It's happening in current release.
- Can you reproduce this issue with the beta channel? Not using beta channel.
- Can you reproduce this issue with the nightly channel? Not using nightly channel.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No, issue remains.
- Does the issue resolve itself when disabling Brave Rewards? Not using Brave Rewards.
- Is the issue reproducible on the latest version of Chrome? Don't have Chrome installed.

## Miscellaneous Information:
This began today, and I believe it was with the update to 1.30.86. It was working fine while using 1.29.
Additionally, my issue #17987 is still happening. And this URL Bar issue seems to happen even with Hardware Acceleration disabled.

**Comment by dusty-1** [comment]
I am also seeing a serious lag problem on Linux (openSUSE 15.1) since updating from 1.29 to 1.30.86+ (approx last week).  Currently running "1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit)" and the lag issue remains.  This is a serious issue since the window UI can be frozen for minutes at a time.  

After investigation, I have learned the following:
 - "lag" means window UI is frozen (CPU 100%), window is not responsive to mouse or keyboard input during lag period
 - initially, there is no lag if alpha characters are typed; lag appears to be triggered by typing a period followed by anything other than a space.
 - lag time is dependent on number of characters after each period typed; for example, 20+ characters can freeze for minutes!
 - after a lag period ends, typing backspace will trigger a new lag period for each backspace typed
 - issue occurs in either non-private or private windows of the same Profile
 - issue is Profile dependent -- lag does not occur in a Guest window of same browser invocation
 - issue is Profile dependent -- created new Profile and could not reproduce lag issue; I then exited, copied contents of "Default" profile to the new profile, then restarted Brave; after switching to new profile, the lag issue was replicated
 -  issue occurs with all autocomplete related settings turned OFF
 -  no Extensions are installed
 -  hardware acceleration ON/OFF makes no difference
 -  curiously, pasting a long URL into the Address bar does not cause a lag; but trying to backspace after the paste does cause a lag
 - browser command line included:  --process-per-site

**Comment by dusty-1** [comment]
I have attached a crude screen capture video showing the lag problem on my linux laptop.  Forgive all the mouse cursor movements, but I did that to show that I was waiting for queued characters to be displayed in the Address bar after the lag.  I have included some timestamps here,  in case you want to jump forward in the video:
00:00   begin in a New Tab of my Default profile; demonstrate that the lags start after typing a period
01:09   end of first demonstrated lag period and show that backspaces cause lagging as well
01:50   open a Guest window and show that no lags occur there
02:20   switch back to my profile's Tab and show that lagging still occurs there
03:25   end of lag demonstration
03:30   scroll through Brave settings (I tried to turn all features off)

https://user-images.githubusercontent.com/91861910/136114968-a51c4247-95cc-4fdc-b1dc-db59715c89cc.mp4

**Comment by umoltrop** [comment]
I am experiencing the same problem on both Desktop and Android. Was not a problem before 1.30 as far as I can remember (I would have noticed) so it likely has something to do with the upgrade to Chromium 94. Typing certain things causes the address bar to lag for a substantial amount of time.

**Comment by dusty-1** [comment]
I updated to the version listed below and the Lagging Address Bar issue appears "resolved". Thanks for the fix! 
[That said,  now I am seeing frequent "Pages Unresponsive" popups on ebay.com pages as well as two browser crashes after simply selecting a pull-down on an ebay.com page. Don't know if this new behavior is in any way related to the Lag fix.]

Brave | 1.31.87 Chromium: 95.0.4638.54 (Official Build) (64-bit)
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Linux
JavaScript | V8 9.5.172.21

**Comment by bsclifton** [comment]
Thanks for the confirmation all! 😄

**Comment by alexklann** [comment]
This is still an issue for me.
On the newest Brave version on Arch Linux with KDE on Wayland...

**Comment by tfrum** [comment]
Can also confirm that this has become a problem again recently on Brave and X11.
Brave: 1.81.137 
Chromium: 139.0.7258.158
