### ISSUE TITLE
Add restore from brave crypto wallets checkbox for 24-word mnemonic  

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#18459]
We should support import from Brave crypto wallets with legacy 24-word mnemonic into new Brave wallet on Android.

Needs checkbox similar to desktop.
![Screenshot_20210921-105655](https://user-images.githubusercontent.com/318119/135375009-b98c67fd-9edb-486d-acd9-bc30d371403b.png)

Desktop
![Brave Wallet - My Crypto - account recovery](https://user-images.githubusercontent.com/318119/135375073-8bc84178-a106-4120-a363-3179b77fa181.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.36.85 x64 Beta build
- Verified able to import 24-word mnemonic
- Verified when 24-word seed is typed in shows a checkbox for importing from legacy wallet
- Verified selecting the checkbox restores the same wallet 
- Verified unselecting the checkbox and restoring creates a new wallet instead of restoring the wallet
- Encountered [#20884](https://github.com/brave/brave-browser/issues/20884) & [#20885](https://github.com/brave/brave-browser/issues/20885)

Oppo Reno 5 (Android 11) | Samsung Tab A (Android 10) 
-- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/152505778-8bad3c80-c9e9-494d-8506-2bb569a5e7eb.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/152505864-9487dfb4-a1bd-4720-b62b-f5c66e77476b.png>
