### ISSUE TITLE
UI bug on GitHub Organization page

### ISSUE THREAD

**Issue by princeelector** [brave/brave-browser#18494]
## Description 
Tip feature breaks UI on organization's member list

## Steps to Reproduce
 1. Go to your organization page or create one
 2. Go to "People" section
 3. Take a look at members list

## Actual result:
![Screen Shot 2021-10-01 at 3 52 33 PM](https://user-images.githubusercontent.com/46070006/135631803-afda1a6c-a252-40a2-8b21-cbcfbac900d2.png)

## Expected result:
![Screen Shot 2021-10-01 at 3 52 41 PM](https://user-images.githubusercontent.com/46070006/135631845-8db6eed0-b60f-429c-baab-7cf98da75340.png)

## Reproduces how often: 
All the time

## Brave version (brave://version info)
Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (x86_64)

## Version/Channel Information:
- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Yes, after disabling tips on GitHub
- Is the issue reproducible on the latest version of Chrome? No

**Comment by princeelector** [comment]
In an expected result, there should obviously be a tip button as well, one that does not break the whole thing haha

**Comment by srirambv** [comment]
Possibly related to #18106

cc: @emerick

**Comment by princeelector** [comment]
@srirambv I also use mac, but changing display settings for more space (as in #18106 thread) doesn't solve the issue unfortunately

**Comment by LaurenWags** [comment]
cc @Miyayes @emerick

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.93 Chromium: 105.0.5195.127 (Official Build) (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 11.7 (Build 20G817)

Reproduced the issue using component version `1.0.199`:

<img width="1435" alt="Screen Shot 2022-09-22 at 9 02 13 AM" src="https://user-images.githubusercontent.com/387249/191796941-0424c3c6-26f9-4be1-8158-37b4cefad477.png">

Launched `1.43.93` using `--use-dev-goupdater-url` and ensured issue is fixed with the component 1.0.649, the Tip button is aligned correctly in `https://github.com/orgs/brave/people` and click on `Tip` button opens up the tipping banner

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-09-22 at 9 03 03 AM" src="https://user-images.githubusercontent.com/387249/191797064-01bdf503-1e37-4864-89fd-b8801da354e0.png"> | <img width="1312" alt="Screen Shot 2022-09-22 at 9 03 11 AM" src="https://user-images.githubusercontent.com/387249/191797069-826712ba-9df7-4560-ae72-ed7d80c48c14.png">

**Comment by mkarolin** [comment]
Fixed via https://github.com/brave/brave-site-specific-scripts/pull/87 (https://github.com/brave/brave-core-crx-packager/pull/489)

**Comment by ShivanKaul** [comment]
There's a similar issue here: https://github.com/brave/brave-browser/issues/26174
