### ISSUE TITLE
New ISSUE is lack of support for OLD ISSUES that haven't been resolved or even acknowledged for FOUR YEARS.

### ISSUE THREAD

**Issue by justing1216** [brave/brave-browser#18569]
Anyone who uses Google's incredibly popular feature; Voice Search (myself included)have a "NEW" Issue with Brave Browser. Our issue is that EVERY SINGLE request for this feature(that has probably been broken since launch), to be fixed spanning a total of FOUR YEARS NOW, has continued to be IGNORED by the Brave Development Team.

@arismelachroinos said it 100% correct in the original support request: "I thought Brave was serious"
Well I agree, and I am just ONE of the MANY people who have been led to believe that Brave was to be taken seriously...

But are you kidding me? This has been an ongoing issue for FOUR YEARS NOW?! With no UPDATED response from an actual Brave Dev or Moderator since the original submission? I HAD thought they were serious too. If they can't fix or even bother to CONTINUE to reply to a simple but ONGOING issue such as this, imagine the kinds of major issues that are ignored and withheld from us... i.e. ANY SECURITY ISSUE or DATA BREACH in the past FOUR FREAKING YEARS. This makes me incredibly nervous and weary of Brave., and I am incredibly sad to say I will be considering my alternatives.

Reproducing the Issue: 
1. Https://github.com/brave/brave-browser/issues/2690
![1st Brave Issue REQ](https://user-images.githubusercontent.com/74791750/136097664-6bf8436e-75e5-429c-913d-1b913e885e3c.JPG)

2. https://github.com/brave/brave-browser/issues/3725
![2nd Brave Issue REQ](https://user-images.githubusercontent.com/74791750/136097686-f2b376f6-6c71-43ae-a54e-29106d0f28bb.JPG)

Above is not ONE but TWO Requests for a simple fix that span four years, neither has been fixed or even warranted an UPDATED response from an actual Brave DEV.

PLEASE DO SOMETHING ABOUT THIS, SHOW YOUR LOYAL SUPPORTERS THAT YOU ACTUALLY SUPPORT THEIR BROWSER OF CHOICE, OR I'M SURE THEY WILL CHOOSE ANOTHER ONE.

**Comment by Brave-Matt** [comment]
@justing1216,
I understand your (and everyone's) frustration here -- I _truly do_. The issue has been reported hundreds of times and has been on the boards and updated for years at this point and to see that it continues to go unaddressed must seem maddening. 

Now I need you (and everyone) to understand the reason this issue is still around. A former employee actually [addressed this in great detail](https://github.com/brave/brave-browser/issues/3725#issuecomment-555694620) previously -- I've highlighted in bold the most relevant bits from his comment below:
> Hi folks, sorry for the lack of update here. It's a bit of a gnarly issue, and it gets me hopping mad.
> 
> First of all: this isn't a problem with the microphone — it's a **speech recognition** API. Chrome ships with a non-standard API used for speech recognition. Websites which call the API are asking the browser to transcribe audio on behalf of the website and send the site the transcribed text (not the audio). When a site calls this API in Chrome, Chrome sends the raw audio to a Google server for transcription. The Google server parses the raw audio, and send the transcribed text back to Chrome. Chrome then passes the text to the website.
> 
> **There are two problems with this. The simple straightforward problem is that Brave doesn't have access to that Google transcription service. It's a paid service from Google which Chrome gets to use for free. If Brave wanted to use it, we'd have to pay Google for the privilege. The second and much more substantial issue is that I don't think that anyone reasonably expects _clicking a microphone icon on Duolingo_ to result in Brave _sending their audio to Google_.**
> 
> Honestly, I think that this design in Chrome is absolutely ridiculous and I was completely flabbergasted when I learned how it worked. We've had some conversations with Google about it, and the outcome is more or less (1) that they don't see what the issue is, and (2) they won't give us access to this online transcription service unless we pay for it.
> 
> **So the upshot here is that Google has built speech recognition on Google sites like Google.com and Google Translate so that they depend on a non-standard API in Google's web browser which actually just calls back to a Google transcription service. You may be wondering why Google.com and Google Translate don't just take the audio and use that Google transcription service behind the scenes rather than doing this elaborate approach involving the browser. Reader, I have exactly the same question. But the outcome is that speech recognition on these Google sites only works in Google's browser, which might be all the answer you need.**
> 
> Unfortunately, I don't think there's any way forward here. Our current plan is to disable things so that the microphone icon doesn't show up. Obviously, that's not a great solution: it's more like hiding the problem. But I don't know what else to do. And this is all Google's fault.

This is a good nutshell explanation of what's happening -- this issue is not something we "refuse to address" but rather an issue where are hands are tied. If there were some solution for this one (singular - amongst a litany of high priority tasks/issues we have to handle daily) issue, it would be _costly_ and _non-trivial at best_. No amount of threats and/or all CAPS sentences is going to change the facts of the matter. This is something that we would absolutely love to see resolved and you can absolutely bet that we would consider a feasible solution if one were to be discovered. 

If you would like to continue posting/reporting here or on any of our socials, we ask you to keep it civil and respectful.

**Comment by guettli** [comment]
Now with locall (onnx) models, this could be changed. Offline, without the need for a service.

**Comment by mayrsascha** [comment]
+1 for adding a local model approach
