### ISSUE TITLE
[Secure flag Cookies transmitted over HTTP] BrowserAudit reports a critical security issue (Android)

### ISSUE THREAD

**Issue by m0rpheas** [brave/brave-browser#18576]
Check:

https://browseraudit.com/results/99656/2fb34e89cd9c036601384e2a9ea8654fd71a8fc1

A cookie with a Secure flag set by Javascript is not supposed to be transmitted over unencrypted HTTP.

This could be a major issue if a man-in-the-middle attack is in progress.

I hope this can be fixed swiftly.

**Comment by diracdeltas** [comment]
```
function() {
  var thisTest = this;
  $.cookie("sessionSecureCookie", "910", {
    secure: true,
    path: "/",
    domain: ".browseraudit.com"
  });
  $("<img>", {
    src: "http://browseraudit.com/set_session_secure_cookie"
  }).load(function() {
    $.get("/get_session_secure_cookie", function(data) {
      if (data === "nil") {
        thisTest.PASS("The cookie was not sent to the server.");
      } else {
        thisTest.CRITICAL("The cookie was sent to the server.");
      }
    });
  });
}
```

i think this probably fails because the HTTP image link is auto-upgraded to HTTPS in recent versions of chromium

**Comment by goodnight573** [comment]
"So turns out this is a test bug. Chromium automatically upgrades the request to HTTPS, which causes the cookie to be sent (bc its now HTTPS) which confuses the test (which doesn't expect the upgrade and so doesn't expect the cookie). Firefox seems to not upgrade the request, which is what causes the test to be green for them." - @pes10k
https://github.com/brave/brave-browser/issues/14149

I'm assuming this is why it fails the referer header test in browseraudit.com as well? Anyone able to confirm? 
<html><body>


Block | should not be sent over non-secure request if the referring page was transferred with a secure protocol
-- | --



</body>
</html>

**Comment by pes10k** [comment]
Closing out since this isn't a brave bug.  

> I'm assuming this is why Brave fails the referer header test in browseraudit.com as well? Anyone able to confirm?

Yep, @goodnight573 i think thats exactly right :)
