### ISSUE TITLE
Can't dismiss grant notification

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#1878]
@bbondy noticed that he can't dismiss grant notifications on the latest release / test channel. His grant was made on 10/23/2018, which means it's using the old version of the notification ID which had a prepended "n". We'll need to support dismissing notifications formatted like this, for backwards compatability purposes.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified test plan in https://github.com/brave/brave-core/pull/755 but also cc-ing @kjozwiak to try with the profile he has as well.

**Comment by GeetaSarvadnya** [comment]
As per the test plan mentioned in #755 PR, we need to upgrade the profile in order to dismiss/remove the grant notification. We will not be able to test this defect for Windows as we don't have offline installer. Don't have option to install older version and upgrade it to the latest version.
@kjozwiak Please suggest if there are any ways i can test this defect on windows.

**Comment by kjozwiak** [comment]
@emerick running through https://github.com/brave/brave-core/pull/755 and https://github.com/brave/brave-core/pull/812 works fine but I have a profile that's affected by this and I still can't dismiss the notifications by clicking on `OK`. I do move the profile around between `dev`, `beta` and `release` so it's entirely possible that I might have bricked it into an unrecoverable state.

I can provide you with the profile if you want to take a look and see what's happening. Or I can send over the `Preferences` file of the affected profile.

**Comment by emerick** [comment]
@kjozwiak Yes, please provide the profile. Also, if you could tell me what the `brave.rewards.notifications` key looks like in the profile's `Preferences` file that would be great.

**Comment by kjozwiak** [comment]
@emerick it looks like this:

```
"brave":{"rewards":{"notifications":"[{\"args\":[],\"id\":\"0\",\"timestamp\":1540535645,\"type\":2},{\"args\":[],\"id\":\"rewards_notification_grant\",\"timestamp\":1541471477,\"type\":2}]"}
```

I'll send you the profile in a DM on Slack 👍

**Comment by kjozwiak** [comment]
This is going to be really hard to test on Windows due to not having the capability of downloading `0.55.20` & `0.55.22` as we don't have offline installers yet. The sub installers are pointing to the latest released version and the custom stub installers on the test channel are pointing to `0.56.10` (RC2).
