### ISSUE TITLE
Show correct transaction info in transaction confirmation screen for ERC721TransferFrom transactions

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#18804]
<img width="321" alt="Screen Shot 2021-10-15 at 11 43 13 AM" src="https://user-images.githubusercontent.com/4730197/137541188-5e8f293c-0603-4d53-9350-85452c6af42d.png">

Currently it looks like this, which is wrong, we should show the correct info for from, to, tokenID, instead of showing a 0 amount here.

**Comment by onyb** [comment]
I think the warning will scare off most users since there's nothing they can do other than not use Brave wallet for ERC721 transfers.

cc: @jamesmudgett If you have inputs on the UX, please let us know. The issue we're talking about is that some ERC-721 contracts do not implement `safeTransferFrom` and only provide a potentially unsafe `transferFrom`. For now, we'll use `transferFrom` for all tokens as a first implementation, so the question is if we need a warning until the proper implementation is done.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.32.99 Chromium: 96.0.4664.35 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <td colspan="3"><code>8df3babf8da8faa8aacb78f4848ef66a93b4944b-refs/branch-heads/4664@{#680}</code></td>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.318)
      </th>
      <th>:ballot_box_with_check: macOS Version 11.5.2
         <br/> (Build 20G95)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/10798>brave/brave-core#10798</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141446044-4042a709-920a-4e9c-9037-2a766dafdc83.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141446802-90e917d4-2ace-46f0-a519-9e2393b5bbd1.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/141446263-ebe16533-3631-414b-b719-04bd835f7fa8.mov>
      </td>
   </tr>
</table>
