### ISSUE TITLE
Background images not changing when SI is not active

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#18800]
## Description 
Background images are not changing if SI is not active.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Actual result 
Only the first background image is shown.

## Expected result
Background images change for each NTP.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@brave/legacy_qa some more context/information as the above is pretty limited on information. If you're in a region that doesn't have an active `SI` campaign, you'll get the same NTP background every single time due to not being able to pull the remaining via the CRX component. STR:

* ensure the device is using the `German` locale (this locale doesn't have any active SI at the moment)
* download/install `1.33.10 Chromium: 95.0.4638.50`
* skip all the onboarding and open several tabs (notice the same background being used)

Example:

![Screenshot_20211016-232738_Brave - Nightly](https://user-images.githubusercontent.com/2602313/137609809-238bafac-07f1-4cf7-84ce-4678825bc9a1.jpg)
