### ISSUE TITLE
Users seeing `ERR_CERT_DATE_INVALID` during Rewards wallet generation and userdrain (HTTP Code: -1)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#18975]
## Description

Some users are seeing the following error in rewards-internals > logs:

```
Result: Error (net::ERR_CERT_DATE_INVALID)
HTTP Code: -1
```

Happens during wallet generation and during userdrain.

## Notes

One user is on Windows 7. Could be a cached, old certificate problem on user's machine side.

**Comment by zenparsing** [comment]
We should look into whether the "extra" error info is logged at the default rewards logging level (errors-only).

**Comment by jonathansampson** [comment]
Almost certainly caused by [DST Root CA X3 expiration](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) in (September, 2021). Some users (such as those on older devices, and no longer receiving crucial updates) may need to manually import the new certificate (ISRG Root X1) from https://letsencrypt.org/certificates/. For assistance with Windows, see https://community.letsencrypt.org/t/fixing-windows-installs-that-dont-receive-updates-to-their-trusted-roots/161162.
