### ISSUE TITLE
Create Linux packages and repos for Linux

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19]

**Comment by mbacchi** [comment]
The apt/rpm repositories are ready in the staging environment, with proxy front ends so that we won't have to change the names of the repositories even after we move to the production environment. These repositories are available at the following locations(you can't browse there because the s3 buckets are private, but the files inside are marked public, so you'd have to get a single file from there to verify, such as https://brave-browser-rpm-dev.s3.brave.com/brave-core-nightly.asc): 

https://brave-browser-rpm-dev.s3.brave.com/
https://brave-browser-apt-dev.s3.brave.com/

Installation instructions (bare bones) are available here: https://brave-browser.readthedocs.io/en/latest/installing-brave.html

**Comment by bbondy** [comment]
Great work!  Closing.
