### ISSUE TITLE
Wallet recovery should be blocked when funds are present

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#1907]
## Description 

If a user has funds in a Brave wallet, restoring over the wallet should be blocked

## Steps to Reproduce

   1. Open Brave and add funds
   2. Restore with a previously saved wallet

## Actual result:

Previously saved wallet is restored and current wallet with funds is possibly discarded (unless a backup was made)

## Expected result:
Need discussion on blocking/warning/confirmation.

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc @davidtemkin @mandar-brave @NejcZdovc

**Comment by mandar-brave** [comment]
@bradleyrichter i would like to call out that the restore process needs a confirmation to the user that 

a) their attention/sites will be cleared 
b) current grants from existing wallet will be lost

cc @NejcZdovc @jasonrsadler

**Comment by jenn-rhim** [comment]
@mandar-brave I didn't expect that we would clear the data table under each feature component, Ads, Auto-contribute and Tips if the wallet is changed. I'd argue that the wallet and the user's rewards activities on the browser should be completely orthogonal, not tied. More importantly, it introduces a big usability concerns and user's understanding of the mechanics of the system: having to re-establish the recurring tips, unsettled support for the sites, inability to re-access the ads that the user may want to click-through. 

As far as the warning, my recommendation for the timing is actually before the user commits to restoring. This is **to prevent** the wasted / unnecessary work, instead of making them to retract if the backup is in fact desired. To restore, the user has to copy the wallet key and paste before clicking 'Restore' button, steps which can be avoided if they are made aware of the need of backup in advance.
@NejcZdovc 

*Note: this warning box should be placed **only when there's a balance in their existing wallet**.

![screen shot 2018-10-31 at 2 48 26 pm](https://user-images.githubusercontent.com/4369856/47820879-10792e00-dd1c-11e8-8b2a-13e79100e9cf.png)

**Comment by NejcZdovc** [comment]
I wouldn't clear table when you are recovering. This two things are not connected. I would just clear reports and update wallet data

**Comment by NejcZdovc** [comment]
closing as restore doesn't work like that anymore
