### ISSUE TITLE
Custom generic cosmetic filters not force-applied in Standard Shields blocking mode

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#19085]
Followup for https://github.com/brave/brave-browser/issues/17013#issuecomment-954098629

## Steps to reproduce

From an EU IP (the cookie banner does not show up in the US):

> 1. go to `brave://adblock`
> 1. Set the Custom Filters textarea to just `###cookiebanner` (and nothing else)
> 1. Go to https://www.circleci.com
> 1. Obnoxious cookiebanner is displayed (the element containing it is a div with id `cookiebanner`)

The cookie banner should be hidden; any cosmetic filters entered in brave://adblock's "Custom filters" box should not be subject to first-party exemption heuristics.

**Comment by JakobJingleheimer** [comment]
Bump. Any chance of a fix for this? It was a great feature 😀

**Comment by ceejay2k** [comment]
Same Issue for. You can use right-click on content -> brave -> block element to block a certain element. it only works once (the element is blocked, the rule is added to custom rules, but after reload/restart/new page it is not applied). 

i just tried this filter to get an annoying empty space on top of the page gone, obviously its only empty because the ad itself was blocked already:

arstechnica.com##.ad.ad_crown

will not work. now use the context menu to block the same element (the rule was actually created by this) and see what happens (see above).

**Comment by antonok-edm** [comment]
Finally got a chance to look into this one. It appears to be related to https://github.com/brave/brave-browser/issues/20177 - i.e., not working in cases where there's an `!important` added to the `display` style of the element in question. Not sure how we let this one regress, but I will be working on the fix shortly and making sure there's adequate testing to prevent it from happening again.

**Comment by antonok-edm** [comment]
Ok, this should be fixed by https://github.com/brave/brave-core/pull/12038 in the next Nightly build - please let me know if you see any other issues!
