### ISSUE TITLE
Allow users to pin NFTs to user's local IPFS node

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19283]
When viewing an NFT in Brave Wallet, detect if it is hosted on IPFS. If so, allow the user to pin it. If the user does not have a local node then allow the user to turn on a local node.

Follow up work: We can layer on things like auto-publish to nft.storage or other pinning service

**Comment by autonome** [comment]
Depending on how the features are implemented, these docs may be relevant: https://docs.ipfs.io/how-to/best-practices-for-nft-data/

Some possible feature avenues:

* Adding an "NFT" type to browser history, recording there
* Once you have NFT as a history type, can build cross-nft-platform/chain/wallet features
* Such as faves/bookmarks category, which pins locally
* NFT "backpack" that's cross platform/chain/wallet

Might be interesting to take an approach like http://microformats.org/ - define a web content markup convention which NFT platforms could opt-in to in order to enable easy access by Brave users.

**Comment by lidel** [comment]
Low-tech solution would be to maintain `NFT` directory in MFS with items from user's wallet, ensuring that local node keeps an implicit pin for a copy of owned items.
