### ISSUE TITLE
is there any security issue if i still using Brave  0.25.2 Muon    8.1.8 version?

### ISSUE THREAD

**Issue by H1-N1** [brave/brave-browser#1939]
is there any security issue if i still using this version?
Brave    0.25.2
V8    6.9.427.23
rev    8ea2a9c
Muon    8.1.8
OS Release    6.1.7601
Update Channel    Release
OS Architecture    ia32
OS Platform    Microsoft Windows
Node.js    7.9.0
Brave Sync    v1.4.2
libchromiumcontent    69.0.3497.100

 i like more , i can have a private tab  side by side with tor and session ,that was the main purpose that make me choose brave browser and delete all other
now it just a chrome clone with less option ...

**Comment by NumDeP** [comment]
Though I do agree with your suggestion and liked it for the side-by-side feature, I'm sure they'll have that Muon aspect of Tor in Core as well. Perhaps edit the title to 'Can I still use Moun-Brave up until Tor tabs alongside normal tabs is implemented', unless there's an open issue for it already.  

It's a little harsh to call it just a Chrome clone. They've worked terribly hard on forking the Chromium aspect of Chrome which is separate to Chrome but still maintains some, if not many Chrome behind the scene features unfortunately attached to it and might I say they've done a wicked job so far removing what they have and I really don't want to go through finding all the open and closed issues pertaining to Chromium calling home to Google but be rest assured they have this covered like you won't believe.

A note to the team. After all calls home to google and un-googled Chromium is fully furnished for v1.0, perhaps the team could maintain a pinned issue listing those aspects so anything sophisticated that was missed or cleverly implemented by Google can be acquiesced and maybe even improved by a couple of Google engineers themselves for Brave. Funny I know but I've read in the past where engineers from Google have actually worked/advised on areas for different products other than Googles.

**Comment by srirambv** [comment]
@H1-N1  Like mentioned in the https://github.com/brave/brave-browser/issues/1877#issuecomment-433891066, Muon is deprecated and there won't be any updates available on that platform. Even if you don't upgrade right now soon there will be a migration update on muon which will replace it with the new version. Since no development work happens on muon, Yes it would be wise from a security point of view to use the one which is being actively developed. 

You can see what all is planned [here](https://github.com/brave/brave-browser/wiki/roadmap)  which will be implemented. Tab previews/Tab pages/Private Tabs is all planned but not a priority for now. 

Closing the issue as no action. You can still respond to the thread here.
