### ISSUE TITLE
Cannot Tip Some Verified Properties

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#19458]
## Description 

Some properties are decorated as _verified_, but cannot be tipped. (The reason seems to be that the Uphold card address is empty.)

## Steps to Reproduce
1. Visit https://getusppe.org/
2. Attempt to issue a tip to the property

## Actual result:
Note that the property is identified, but cannot receive a tip

## Expected result:
If a tip cannot be processed, the UI should not lead the user to believe otherwise.

## Reproduces how often: 
Easily

## Desktop Brave version:
1.31.91

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Unrelated

## Miscellaneous Information:
The following is the property state from the CDN:

```json
{
    "url": "https://pcdn.brave.com/publishers/prefixes/be4d",
    "channelInfo": {
        "wallets": [
            {
                "upholdWallet": {
                    "walletState": "UPHOLD_ACCOUNT_KYC",
                    "address": ""
                },
                "provider": "upholdWallet"
            }
        ],
        "channelIdentifier": "getusppe.org",
        "siteBannerDetails": {
            "donationAmounts": [],
            "title": "",
            "description": "",
            "backgroundUrl": "",
            "logoUrl": "",
            "socialLinks": null
        }
    }
}
```

**Comment by LaurenWags** [comment]
@zenparsing test plan mentions a production Uphold site, what could we use on staging?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.34.63 Chromium: 96.0.4664.110 (Official Build) beta (x86_64)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | macOS Version 11.6.1 (Build 20G224)
```

Verified test plan from https://github.com/brave/brave-core/pull/11129#issue-1056275550 on staging. Per https://bravesoftware.slack.com/archives/CNH9Q6REV/p1638821312113700 this condition was created in staging for us to test.

Example | Example | Example | Example
----- | ----- | ----- | -----
<img width="425" alt="Screen Shot 2021-12-15 at 9 58 21 AM" src="https://user-images.githubusercontent.com/28145373/146210469-89bdfb68-3bd0-4aa5-bdbf-e9a27c59b718.png"> | <img width="1189" alt="Screen Shot 2021-12-15 at 9 58 30 AM" src="https://user-images.githubusercontent.com/28145373/146210482-6e70a9a7-8830-4dd7-9f52-decd282bd2da.png"> | <img width="396" alt="Screen Shot 2021-12-15 at 10 01 21 AM" src="https://user-images.githubusercontent.com/28145373/146210492-ed1bfa48-04ee-4485-ab5b-7245857888e9.png"> | <img width="946" alt="Screen Shot 2021-12-15 at 10 01 28 AM" src="https://user-images.githubusercontent.com/28145373/146210497-187bcf20-411f-4977-90fc-897e5241525d.png">

Also confirmed able to tip a truly Uphold verified creator:

Example | Example
----- | -----
<img width="410" alt="Screen Shot 2021-12-15 at 10 04 49 AM" src="https://user-images.githubusercontent.com/28145373/146211159-47315c44-97a8-4734-a781-e6f8c46d6cee.png"> | <img width="651" alt="Screen Shot 2021-12-15 at 10 05 00 AM" src="https://user-images.githubusercontent.com/28145373/146211167-7383f8b0-2151-4bb8-b5cd-138f568a7489.png">

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using Brave `1.34.70, Chromium 97.0.4692.56` on a `Google Pixel XL` running `Android 9.0`.

(Ongoing thread, here: `https://bravesoftware.slack.com/archives/CNH9Q6REV/p1638821312113700`.)

### Uphold Verified Creator (empty card address)

### Uphold Verified Creator

Steps:
1. install `1.34.70`
2. skip onboarding
3. enable Rewards staging via the sekret `QA Preferences` menu in `Developer options`, under `Settings`
4. restart Brave
5. claim UGP grant
6. load `laurenwags.github.io`
7. tap on the BAT icon
8. confirm no `Note:` text present
9. tip 1.000 BAT
10. load `brave://rewards`
11. at the bottom, under `Tips`, tap on `View Details >`
12. confirm a 1.000 BAT tip to `laurenwags.github.io` went through

(NOTE: the times in the screenshots below are out of order, due to me redoing tests for a screenshot only when necessary, rather than retaking them all.)

Example | Example | Example | Example
---------|----------|----------|---------
![Screenshot_20211222-161746](https://user-images.githubusercontent.com/387249/147169310-90216484-3b72-4af2-a722-4090a8441dab.png) | ![Screenshot_20211222-161438](https://user-images.githubusercontent.com/387249/147169326-113506c6-fae9-4857-94bb-79a01a131803.png) | ![Screenshot_20211222-155313](https://user-images.githubusercontent.com/387249/147169349-ef371776-ba35-45f7-8e18-d1a0265a6521.png) | ![Screenshot_20211222-161642](https://user-images.githubusercontent.com/387249/147169353-00193115-a821-47ff-a6de-b87e47bddfb3.png)

**Comment by stephendonner** [comment]
We cannot verify the 1st testcase, `Uphold Verified Creator (empty card address)`, until https://github.com/brave/brave-browser/issues/20250 is addressed, and we have specific messaging/UX implemented (starting from 1.35.x onward).

**Comment by stephendonner** [comment]
Removed my errant `QA Pass - Android ARM` label since only the regression test was able to run, and PASSED 👍

**Comment by stephendonner** [comment]
Marking as `QA Pass - Android ARM` since we regression-tested and there is https://github.com/brave/brave-browser/issues/20250 which is pre-existing, and will take care of that missing case right now.
