### ISSUE TITLE
Implement swaps in Solana

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19474]
Possibly with https://docs.jup.ag/jupiter-api-beta/using-the-api-v1

**Comment by aman-m1** [comment]
Any update/progress here @bbondy?

**Comment by bbondy** [comment]
Finishing up on Dapps then I believe this is the next biggest Solana item.

**Comment by onyb** [comment]
### Technical spec

#### Define mojom structs to model the following jup.ag response

<img width="640" src="https://user-images.githubusercontent.com/3684187/171098580-639a86d3-4fb0-4902-9c7f-825041315655.png">

Unlike 0x, Jupiter returns several routes in the `data` array, instead of a single route. The route object in the first index is the most cost-effective one, but we can expose all the other routes for presentational purpose.

⚠️ Amounts and prices in Jupiter are not represented as strings in the JSON response.

#### API to fetch a quote

This is equivalent to the `/swap/v1/price` endpoint of 0x API.

| Example | [`SOL -> USDC`](https://quote-api.jup.ag/v1/quote?inputMint=So11111111111111111111111111111111111111112&outputMint=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&amount=10000&slippage=1&feeBps=87) |
-|-

#### API to build a transaction from a quote

This is equivalent to the `/swap/v1/quote` endpoint of 0x API.

```
POST https://quote-api.jup.ag/v1/swap
{
  route: routes[0],  // the route object to use
  userPublicKey: "foo" ,  // user public key to be used for the swap
  feeAccount: "xxxx"  // fees will be collected here
}
```
Response:
Depending on the route, the API will return between 1 to 3 transaction objects. At minimumm, `swapTransaction` will always be in the JSON response. The transactions must be signed and settled sequentially.

```
{
  setupTransaction: {...},
  swapTransaction: {...},
  cleanupTransaction: {...},
}
```

**Comment by onyb** [comment]
## Test plan

1. Test the swap flow on Solana network => demo video in https://github.com/brave/brave-core/pull/14298.
2. Check whether fees are received in https://solscan.io/account/8eekKfUAGSJbq3CdA2TmHb8tKuyzd5gtEas3MYAtXzrT.
3. Check whether slippage settings can be changed.
4. Check if UI displays "Insufficient liquidity" error for illiquid pairs. Ex, `SOL -> wBAT`

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.44.97 Chromium: 106.0.5249.55 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified test plan from [#19474 (comment)](https://github.com/brave/brave-browser/issues/19474#issuecomment-1211948114)
- Verified Swap flow works as shown in PR
- Verified able to successfully submit transaction for `SOL -> USDC` with <code><a href=https://explorer.solana.com/tx/5JtLcmFQUPZmXHv7ZZmFjugtNraySghAszRzjJARJEBfhbQdVoEZSdXn3LtuthwVWtr2HtcYPifyqBWQWMJcA2hM>Transaction 1/3</a></code> ,<code><a href=https://explorer.solana.com/tx/5JtLcmFQUPZmXHv7ZZmFjugtNraySghAszRzjJARJEBfhbQdVoEZSdXn3LtuthwVWtr2HtcYPifyqBWQWMJcA2hM>Transaction 2/3</a></code><code><a href=https://explorer.solana.com/tx/2CYX543naFtA4RzhPv7M7sABxGkQ3B6MUoCaMRx743JTkErd3iAP9otXJkxz6uVGKgofmwy8T8RWmR2yLj78cnvJ>Transaction 3/3</a></code>
- Verified able to change slippage charge 
- Verified UI displays "Insufficient liquidity" error for illiquid pair `SOL -> wBBTC`
- Verified able to Swap with 0x without issues <code><a href=https://etherscan.io/tx/0xc205180e58e9ef375303bbd92f12f6516a401f0d58ec5b82055f7bd18063b9cb>BAT -> USDC</a></code>

Confirmation | Insufficient liquidity
-- | --
![image](https://user-images.githubusercontent.com/17010094/191716780-ffeca0a9-e3f0-436c-ad47-14456f69ad80.png) | ![image](https://user-images.githubusercontent.com/17010094/191716916-ab0c87ba-3e35-4bcd-859e-fcfeb304d5ce.png)
