### ISSUE TITLE
Browser crash while using Brave wallet on https://market.x.immutable.com/

### ISSUE THREAD

**Issue by saimkaan** [brave/brave-browser#19512]
## Description 
Can not use the new wallet to login to https://market.x.immutable.com/. Always crashes the browser (it closes when I try to connect my wallet).

## Steps to Reproduce
   1. Open https://market.x.immutable.com/
   2. connect wallet
   3. browser crashes / closes when the wallet popup opens

## Expected result:
My wallet should just connect.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.32.106
Windows

**Comment by rebron** [comment]
@saimkaan When you get a chance can you go to brave://crashes/ send the report and post the crash id here.

**Comment by saimkaan** [comment]
Status:	Upload requested by user
Local Crash Context:	46c529db-f2f9-4ab8-8bde-115dc4b29853

Is this the ID or do I have to wait?

**Comment by bbondy** [comment]
Crash is fixed already here and will be in the hotfix early this coming week:
https://github.com/brave/brave-core/pull/11156

Note that the site in question still won't work after that crash fix due to us not having support for this yet:
https://github.com/brave/brave-browser/issues/19274 
It's a Draft proposal that MetaMask implemented so it's not really finalized yet. But it seems they are using it already. 
We'll get that added. 

Since this all being tracked by different issues I'll close this issue as a duplicate. 
But you'll want to track: https://github.com/brave/brave-browser/issues/19274  for when the site will work.

Thanks for the report!
