### ISSUE TITLE
Changes to sync QR code

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#19550]
### Description: 
See https://github.com/brave/internal/issues/832

**Comment by LaurenWags** [comment]
`QA/Blocked` until uplifted to 1.33.x

**Comment by AlexeyBarabash** [comment]
Verified on https://github.com/brave/brave-browser/releases/tag/v1.35.1, preparing uplift to 1.33.x

**Comment by AlexeyBarabash** [comment]
Uplift PR created https://github.com/brave/brave-core/pull/11358

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` as `1.33.99` is available

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS`


### Cross-timezone tests
<details>

1. set up a desktop on the Los Angeles timezone
2. set up an Android phone on the Auckland (NZ) timezone.
3. create a Sync chain on Desktop
4. attempt to join the Sync chain on Android (it should WORK). :white_check_mark:
5. reset both browser profiles.
6. change desktop computer to the Auckland (NZ) timezone.
7. change Android phone to the Los Angeles timezone.
8. create Sync chain on Desktop.
9. attempt to join the Sync chain on Android (it should WORK). :white_check_mark:
10. repeat these steps with two Android phones and no Desktop.
    1. unable to test; only have a single Android test device
11. repeat these steps with a Desktop and an iOS phone. :white_check_mark:
12. repeat these steps with an iOS phone as the Sync chain creator and an Android phone as the Sync chain joiner. :white_check_mark:


</details>

### Normal expiration test

<details>
1. create a Sync chain on Desktop and keep it open until Step 6 is done.
2. wait 20 minutes.
3. attempt to join Sync chain on Android (it should WORK).
4. reset Android profile.
5. wait 11 minutes (so that it’s > 30 minutes since generating the code).
6. attempt to join Sync chain on Android (it should FAIL). :x:
7. repeat these steps with two Android phones and no Desktop.
   1. unable to test; only have a single Android test device
8. repeat these steps with a Desktop and an iOS phone.
9. repeat these steps with an iOS phone as the Sync chain creator and an Android phone as the Sync chain joiner

</details>

### Code expiring too far into the future

<details>
1. set up a desktop computer and change the date to 1 day into the future.
2. set up an Android phone with the correct date and time.
3. create a Sync chain on Desktop.
4. attempt to join the Sync chain on Android (it should FAIL). :white_check_mark:
5. attempt to join the same Sync chain on iOS (it should FAIL). :white_check_mark:

</details>

### Old-style QR codes

<details>

1. set up a desktop computer with an earlier version of Brave (with the old-style QR codes).
2. set up an Android phone with support for updated QR codes.
3. create a Sync chain on Desktop.
4. attempt to join the Sync chain on Android (it should WORK).
5. reset both browser profiles.
6. change time on desktop computer to January 2nd 2022.
7. change time on Android phone to January 2nd 2022.
8. create a Sync chain on Desktop.
9. attempt to join the Sync chain on Android (it should FAIL).
10. repeat these steps with an iOS phone instead of an Android one.

</details>

### Malformed QR codes (Android & desktop)

<details>

See https://docs.google.com/document/d/1w7tEPNj4GaTCEekmj4Ala0BiDSFQxSAA1V7_uOQ4ZTo/edit#heading=h.s3gs7lo74s43 for steps.

| malformed JSON | unsupported version (too small) | unsupported version (too recent) | sync_code_hex (too short) | sync_code_hex (too long) | sync_code_hex (invalid hex) | missing sync_code_hex | missing version | missing expirary |
| -------------- | ------------------------------- | -------------------------------- | ------------------------- | ------------------------ | --------------------------- | --------------------- | --------------- | ---------------- |

</details>

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.33.100 Chromium: 96.0.4664.55 (Official Build) (x86_64)
-- | --
Revision | 38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}
OS | macOS Version 11.6.1 (Build 20G224)

Verification notes over in https://github.com/brave/internal/issues/832#issuecomment-988116911

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.33.100 Chromium: 96.0.4664.55 (Official Build) (x86_64)
-- | --
Revision | 38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}
OS | macOS Version 11.6.1 (Build 20G224)

Verification notes over in https://github.com/brave/internal/issues/832#issuecomment-988116911

**Comment by LaurenWags** [comment]
Verification in progress using `1.33.100` on the below two devices for Android <--> Android tests.

Android 1 - Google Pixel (Android 11)
Android 2 - Samsung JNeo (Android 7)

Verified cases listed in doc from https://github.com/brave/internal/issues/832#issuecomment-973471650 for Android <--> Android sync.

### Cross-timezone tests - PASSED
1. Setup Android 1 on the Los Angeles timezone.
2. Setup Android 2 on the Auckland (NZ) timezone.
3. Create a Sync chain on Android 1.
4. Attempt to join the Sync chain on Android 2 (it should WORK).
5. Reset both Android profiles.
6. Create Sync chain on Android 2.
7. Attempt to join the Sync chain on Android 1 (it should WORK).

Confirmed able to join sync chains as expected in steps 4 and 7.

Android 1 - LA | Android 2 - Auckland
----- | -----
![1](https://user-images.githubusercontent.com/28145373/145068378-2aab3fb9-9a5f-470f-8e91-f7a51feef283.png) | ![2](https://user-images.githubusercontent.com/28145373/145068386-524390f7-9b96-4c69-834b-cfbfd9381885.png)

Step 3 | Step 4
----- | -----
![3](https://user-images.githubusercontent.com/28145373/145068433-444b4e7d-8ef8-45d2-8c51-ff71a10d311e.png) | ![4](https://user-images.githubusercontent.com/28145373/145068441-909435fd-b0a9-4b14-83a4-3d049346aeed.png)

Step 6 | Step 7
----- | -----
![5](https://user-images.githubusercontent.com/28145373/145068470-24c606b8-5d98-4884-905a-df23a3de1741.png) | ![6](https://user-images.githubusercontent.com/28145373/145068479-8968e42f-cb0c-4f9d-a09c-1f60252b0443.png)

### Normal expiration test - PASSED
1. Create a Sync chain on Android 1 and keep it open until Step 6 is done.
2. Wait 20 minutes.
3. Attempt to join Sync chain on Android 2 (it should WORK).
4. Reset Android 2 profile.
5. Wait 11 minutes (so that it’s > 30 minutes since generating the code).
6. Attempt to join Sync chain on Android 2 (it should FAIL).

Step 1 | Step 3 | Step 6
----- | ----- | -----
![step1](https://user-images.githubusercontent.com/28145373/145072622-6e92c4c9-6eb8-496f-9825-19d845d69aa1.png) | ![step3](https://user-images.githubusercontent.com/28145373/145072629-84e2b3ca-c9dd-4805-b09a-57eb86a142a8.png) | ![step6](https://user-images.githubusercontent.com/28145373/145072638-692e34e6-d7b2-4d40-9ff1-1603457f50f7.png)

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 


Brave | 1.33.100 Chromium: 96.0.4664.55 (Official Build) (64-bit)
-- | --
Revision | 38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}
OS | Windows 10 Version 20H2 (Build 19042.1348)


### Cross-timezone tests - `PASSED`

<details>

1. set up a desktop on the Los Angeles timezone
2. set up an Android phone on the Auckland (NZ) timezone.
3. create a Sync chain on Desktop
4. attempt to join the Sync chain on Android (it should WORK)
5. reset both browser profiles.
6. change desktop computer to the Auckland (NZ) timezone.
7. change Android phone to the Los Angeles timezone.
8. create Sync chain on Desktop.
9. attempt to join the Sync chain on Android (it should WORK)
10. repeat these steps with two Android phones and no Desktop.
    1. unable to test; only have a single Android test device
11. repeat these steps with a Desktop and an iOS phone
12. repeat these steps with an iOS phone as the Sync chain creator and an Android phone as the Sync chain joiner

Desktop & Android - `PASSED`

example | example | example | example
---------|---------|-----------|--------


Desktop & iOS - `PASSED`

example | example | example | example | example | example
---------|---------|----------|----------|----------|---------


iOS & Android - `PASSED`

example | example | example | example | example | example
---------|---------|----------|----------|----------|--------




</details>

### Normal expiration test - `PASSED`

<details>

1. create a Sync chain on Desktop and keep it open until Step 6 is done.
2. wait 50 minutes.
3. attempt to join Sync chain on Android (it should WORK).
4. reset Android profile.
5. wait 11 minutes (so that it’s > 60 minutes since generating the code).
6. attempt to join Sync chain on Android (it should FAIL)
7. repeat these steps with two Android phones and no Desktop (NOTE: unable to test; only have a single Android test device)
8. repeat these steps with a Desktop and an iOS phone.
9. repeat these steps with an iOS phone as the Sync chain creator and an Android phone as the Sync chain joiner

Desktop & Android - `PASSED`

example | example | example
---------|----------|--------


Desktop & iOS - `PASSED`

example | example | example
---------|---------|---------



iOS & Android - `PASSED`

example | example | example
---------|----------|---------





</details>

### Code expiring too far into the future - `PASSED`

<details>

1. set up a desktop computer and change the date to 1 day into the future.
2. set up an Android phone with the correct date and time.
3. create a Sync chain on Desktop.
4. attempt to join the Sync chain on Android (it should FAIL)
5. attempt to join the same Sync chain on iOS (it should FAIL)

example | example | example
---------|---------|----------




</details>

### Old-style QR codes - `PASSED`

<details>

1. set up a desktop computer with an earlier version of Brave (with the old-style QR codes).
2. set up an Android phone with support for updated QR codes.
3. create a Sync chain on Desktop.
4. attempt to join the Sync chain on Android (it should WORK).
5. reset both browser profiles.
6. change time on desktop computer to January 2nd 2022.
7. change time on Android phone to January 2nd 2022.
8. create a Sync chain on Desktop.
9. attempt to join the Sync chain on Android (it should FAIL).
10. repeat these steps with an iOS phone instead of an Android one.

Desktop & Android - `PASSED`

example | example | example | example
---------|----------|---------|------------




Desktop & iOS - `PASSED`

example | example | example | example
---------|----------|----------|--------



</details>


</details>

**Comment by stephendonner** [comment]
Going to re-do the macOS section; also fixed the testcase for `Normal expiration test` to have the correct 20 and 11-minute values, respectively, for the join-success and join-fail cases.

**Comment by stephendonner** [comment]
NOTE: Also added another test, `Android (Sync-chain creator)` `->` `iOS (joiner)`, since we have the other creator/joined case already covered under `iOS & Android`, above.

### Normal expiration test

<details>

Android & iOS - `PASSED`


example | example | example
---------|----------|---------
![Screenshot_20211209-142753](https://user-images.githubusercontent.com/387249/145488692-a58014b7-6b84-4f40-8dae-f4d447875ae6.png) | ![Image from iOS (4)](https://user-images.githubusercontent.com/387249/145488766-6c502fdb-d4b5-4cf7-9d39-a48f8b54e848.png) | ![Image from iOS (5)](https://user-images.githubusercontent.com/387249/145489279-408be530-9eb1-4ba6-87b7-4b13ba20a415.png)


</details>

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.33.105 Chromium: 96.0.4664.93 (Official Build) (64-bit)
-- | --
Revision | 17531e0a70b4f8108f2418e8b5117f465077710b-refs/branch-heads/4664@{#1229}
OS | Ubuntu 18.04 LTS


### Cross-timezone tests - `PASSED`

<details>

1. set up a desktop on the Los Angeles timezone
2. set up an Android phone on the Auckland (NZ) timezone.
3. create a Sync chain on Desktop
4. attempt to join the Sync chain on Android (it should WORK)
5. reset both browser profiles.
6. change desktop computer to the Auckland (NZ) timezone.
7. change Android phone to the Los Angeles timezone.
8. create Sync chain on Desktop.
9. attempt to join the Sync chain on Android (it should WORK)
10. repeat these steps with two Android phones and no Desktop.
    1. unable to test; only have a single Android test device
11. repeat these steps with a Desktop and an iOS phone
12. repeat these steps with an iOS phone as the Sync chain creator and an Android phone as the Sync chain joiner

Desktop & Android - `PASSED`

![image](https://user-images.githubusercontent.com/34715963/145890657-a013d98e-a81e-4efb-b486-2d6373bf2cb1.png)|![image](https://user-images.githubusercontent.com/34715963/145890676-4c36bcf2-6d2c-4708-9636-00cabace3a21.png)|![image](https://user-images.githubusercontent.com/34715963/145890691-5bd1277d-0df8-4010-b954-575057fe0a30.png)|![Screenshot_20211214-093144_Settings](https://user-images.githubusercontent.com/34715963/145890994-5d4ddf38-b5ef-4940-8ed2-272c56aac3c0.jpg)|![Screenshot_20211214-093516_Brave](https://user-images.githubusercontent.com/34715963/145890996-36dff74e-64b3-4399-8c3a-ac964f0212dd.jpg)|![Screenshot_20211214-093537_Brave](https://user-images.githubusercontent.com/34715963/145890997-5f3de9b1-9788-4bd9-bcfa-a1d5d86ea79d.jpg)
--|--|--|--|--|--


![image](https://user-images.githubusercontent.com/34715963/145890723-0096909d-7163-4493-8997-bab0090ce7ef.png)|![image](https://user-images.githubusercontent.com/34715963/145890760-6d3696c0-e3ec-4587-8a05-3f7a91290268.png)|![Screenshot_20211213-124146_Settings](https://user-images.githubusercontent.com/34715963/145890987-ee75a5b8-62d7-4d3a-9189-d141ec1d5485.jpg)|![Screenshot_20211213-125308_Brave](https://user-images.githubusercontent.com/34715963/145890993-5fd3750a-c00b-4316-8161-0ac96ffb69f0.jpg)
--|--|--|--

Desktop & iOS - `PASSED`

![image](https://user-images.githubusercontent.com/34715963/145902087-fc56ad97-f258-49f7-8b6f-fa48bf385343.png)|![IMG_0070](https://user-images.githubusercontent.com/34715963/145902129-78d3988d-c681-4de4-bef5-6bf79b614b3c.PNG)|![IMG_0071](https://user-images.githubusercontent.com/34715963/145902130-92fbde7d-f447-44aa-8a6a-837b6a820d76.PNG)
--|--|--

![IMG_0072](https://user-images.githubusercontent.com/34715963/145902186-01d353c3-138f-4f47-a94a-1c76c02d9d1e.PNG)|![IMG_0073](https://user-images.githubusercontent.com/34715963/145902189-be6e0ccf-2173-4828-aa81-967f6cf6cea5.PNG)
--|--


</details>

### Normal expiration test - `PASSED`

<details>

1. create a Sync chain on Desktop and keep it open until Step 6 is done.
2. wait 20 minutes.
3. attempt to join Sync chain on Android (it should WORK).
4. reset Android profile.
5. wait 11 minutes (so that it’s > 30 minutes since generating the code).
6. attempt to join Sync chain on Android (it should FAIL)
7. repeat these steps with two Android phones and no Desktop (NOTE: unable to test; only have a single Android test device)
8. repeat these steps with a Desktop and an iOS phone.
9. repeat these steps with an iOS phone as the Sync chain creator and an Android phone as the Sync chain joiner

Desktop & Android - `PASSED`

![Screenshot_20211214-093537_Brave](https://user-images.githubusercontent.com/34715963/145904859-11c37544-a4b1-461d-9e9a-3c2ff9b5be80.jpg)|![Screenshot_20220102-230959_Brave](https://user-images.githubusercontent.com/34715963/145904860-9b34a650-e881-4afc-8986-d1ac8a76f1d8.jpg)
--|--


Desktop & iOS - `PASSED`

![IMG_0078](https://user-images.githubusercontent.com/34715963/145905381-85d91439-1df4-4fdf-836d-f20c7219ca53.PNG)



</details>

### Code expiring too far into the future - `PASSED`

<details>

1. set up a desktop computer and change the date to 1 day into the future.
2. set up an Android phone with the correct date and time.
3. create a Sync chain on Desktop.
4. attempt to join the Sync chain on Android (it should FAIL)
5. attempt to join the same Sync chain on iOS (it should FAIL)

Desktop & Android - `PASSED`
![Screenshot_20211213-224610_Brave](https://user-images.githubusercontent.com/34715963/145894533-c4386388-fb30-4ca4-b1f4-ee5d8aa132a8.jpg)


Desktop & iOS - `PASSED`
![IMG_0074](https://user-images.githubusercontent.com/34715963/145902718-4cbc7e76-c70f-4231-85b7-a6607153cf02.PNG)


</details>

### Old-style QR codes - `PASSED`

<details>

1. set up a desktop computer with an earlier version of Brave (with the old-style QR codes).
2. set up an Android phone with support for updated QR codes.
3. create a Sync chain on Desktop.
4. attempt to join the Sync chain on Android (it should WORK).
5. reset both browser profiles.
6. change time on desktop computer to January 2nd 2022.
7. change time on Android phone to January 2nd 2022.
8. create a Sync chain on Desktop.
9. attempt to join the Sync chain on Android (it should FAIL).
10. repeat these steps with an iOS phone instead of an Android one.

Desktop & Android - `PASSED`

![image](https://user-images.githubusercontent.com/34715963/145896042-2cc3e1c9-23db-4a87-b5a1-ba12ac0e2164.png)|![image](https://user-images.githubusercontent.com/34715963/145896066-35ba73d1-5a65-4521-af9f-d8e93a1b7199.png)|![Screenshot_20211213-230041_Brave](https://user-images.githubusercontent.com/34715963/145895973-41ec56f8-2a15-4646-aa9b-6f46f9fe2545.jpg)|![Screenshot_20220102-230959_Brave](https://user-images.githubusercontent.com/34715963/145897038-e701e1b4-92e5-40d1-a157-785c28bc8cc3.jpg)
--|--|--|--

Desktop & iOS - `PASSED`

![IMG_0075](https://user-images.githubusercontent.com/34715963/145905284-9fc96137-b265-41f5-b73a-67a1eb36f4d9.PNG)|![IMG_0076](https://user-images.githubusercontent.com/34715963/145905302-5d6d4377-1e65-4b95-948a-72e155087d73.PNG)|![IMG_0077](https://user-images.githubusercontent.com/34715963/145905305-9ac97d40-ffc5-4d48-b5ad-b874871fcb3a.PNG)
--|--|--

</details>
