### ISSUE TITLE
Apostrophe not being unescaped in YouTube channel name

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19594]
## Description

Apostrophe is appearing as `#39;` instead of an apostrophe `'` in YouTube channel name.

Example: https://www.youtube.com/c/LolasLifeLessons

![image](https://user-images.githubusercontent.com/11497541/142649519-01203250-1cb8-44ff-a8f3-020fc7abc442.png)

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.35.101 Chromium: 98.0.4758.87 (Official Build) (x86_64)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | macOS Version 12.2.1 (Build 21D62)
```

and the below dev component:

```
Brave Local Data Updater - Version: 1.0.196
```

For a new profile only, confirmed the apostrophe is showing correctly on panel for above creator:

<img width="435" alt="Screen Shot 2022-02-11 at 3 22 14 PM" src="https://user-images.githubusercontent.com/28145373/153665078-5023ee58-f6dd-4272-b9e2-fef9a740efdb.png">

Note, existing profiles will still show the unescaped apostrophe due to https://github.com/brave/brave-browser/issues/20980.

Additionally, spot checked a few other creators panels (on new profile) to confirm they showed ok:

Example | Example | Example | Example
----- | ----- | ----- | -----
<img width="433" alt="1" src="https://user-images.githubusercontent.com/28145373/153666404-2969d86c-6e63-40d5-841c-61725c3bf41b.png"> | <img width="438" alt="2" src="https://user-images.githubusercontent.com/28145373/153666414-cce63036-88d0-4b46-bd3b-e309987d9724.png"> | <img width="434" alt="3" src="https://user-images.githubusercontent.com/28145373/153666419-1af8bd77-d37d-4600-989e-95ace27f095b.png"> | <img width="434" alt="4" src="https://user-images.githubusercontent.com/28145373/153666428-4cee0dbf-28e5-4499-8842-33f919459884.png">

Note, found sites for production using `bravebat.info`.
Encountered and logged https://github.com/brave/brave-browser/issues/21062 for other characters not being handled properly on the panel.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 11 Version 21H2 (Build 22000.493)
```

Went through the following verification using `Brave Local Data Updater - Version: 1.0.71` as per the following:

![image](https://user-images.githubusercontent.com/2602313/153799940-48f8ee37-bd6c-485d-b9d8-fa61b180ad22.png)

For a new profile only, confirmed the apostrophe is showing correctly on panel for above creator:

![image](https://user-images.githubusercontent.com/2602313/153799749-1df9975c-ba79-42e3-8465-a36b80a63154.png)

**`Example`** | **`Example`** | **`Example`**
---------------|---------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/153800150-727310f5-a901-4ff9-bd82-33f5b804c879.png) | ![image](https://user-images.githubusercontent.com/2602313/153800202-bebf4df5-9e11-478d-9800-5561f978766d.png) | ![image](https://user-images.githubusercontent.com/2602313/153800244-3bbc1110-caf5-45cf-8b7d-47689e213782.png)  | ![image](https://user-images.githubusercontent.com/2602313/153800369-5fa29a0b-9dd6-472c-9d16-668e3df21956.png)
