### ISSUE TITLE
Show market cap with price for charts

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#19607]
> When you click on an asset’s chart, you see the market cap moving in conjunction with the price.

**Comment by jamesmudgett** [comment]
Have it show when hovering only, hide if not hovering on graph since we should show current market cap in the asset data at the bottom of the page. ![Screen Shot 2022-02-08 at 12 27 17 PM](https://user-images.githubusercontent.com/318119/153052326-cea62964-8d23-442d-ad35-5c2b7e6d7dc3.png)

**Comment by muliswilliam** [comment]
@bbondy We are not in a position to add market cap as requested above because frontend does not receive market cap data from the backend or data points we can use to calculate it on the frontent i.e., circulating supply of coin/token. We have the fiat value so the missing datapoint here is circulating supply of coin/token at each price point.

**Comment by jamesmudgett** [comment]
@muliswilliam you could probably take the current price sent and marketcap then divide marketcap/price == total supply, then calculate on the client.

**Comment by muliswilliam** [comment]
@jamesmudgett Currently we are getting the data to calculate this on the client. we can explore this further when we start fetching market data for the new market tab.
