### ISSUE TITLE
Detecting creator info (including verification status) requires tab reload or switching away and back into tab

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#19650]
## Description

Often, when visiting a new channel, the creator info will not be picked up by the Rewards panel, and for verified channels, no blue checkmark will appear over the BAT icon in the URL bar either. Even after 10 seconds or so and after closing and reopening the panel, the creator info will not be populated. (For example, if a YouTube channel, it might just show youtube.com.)

However, if you refresh the tab, or perhaps switch to another tab and back, then the panel will start to detect and parse the creator info quickly (e.g., within a second).

@emerick has observed this before as well.

**Comment by emerick** [comment]
@Miyayes Do you have a semi-reliable repro for this? I'm having trouble making it happen now.

**Comment by Saoiray** [comment]
@szilardszaloki where do I look to share the logs you needed to see? I know recently we've had people such as [https://www.youtube.com/user/crownrahulmehra](https://www.youtube.com/user/crownrahulmehra) who mentioned. When I clicked on that link, it showed as YouTube.com with unverified creator. Yet when I clicked on Videos or somehow navigated within, it suddenly showed Pure Gaming as Verified Creator. There's been plenty of others, but it's trying to figure out why it's not populating. 

The main time I see this reproduce is when clicking on links that take us directly to their pages. Whether it be on Reddit or YouTube. Yet once we navigate further, it falls in place as it should. I'm confident I can reproduce it myself as I just did it yet again a moment ago. Big issue is the only Logs I'm aware of is at brave://rewards-internals and I don't see it there. If I know where to look to let you know what is changing, I'll post for you.

**Comment by Miyayes** [comment]
**Some potentially helpful investigation from a user:**

>I just noticed this behaviour only happens when Brave Rewards is enabled, and Auto-Contribute is disabled. With Auto-Contribute enabled the issue resolves itself. It would be nice if this same behaviour happened with auto-contribute disabled.
>
>For example, there could be a website/person that isn't currently verified with Brave and you'd like to know when they do become verified so that you can tip them. With the current behaviour you have to click the BAT icon everytime you're on their website/channel to check; it would be a lot nicer to simply just glance at the BAT icon to check if they've verified since your last visit to their website/channel e.t.c.

From: https://github.com/brave/brave-browser/issues/14986#issuecomment-812910428 // cc: @emerick

**Comment by wavesurf432** [comment]
Hey, I've noticed this behaviour with YouTube for sometime now as well - it seems to only happen with YouTube. To fix it I usually open and close the Brave Rewards drop down GUI once or twice, and refresh the page a couple times. Brave then picks up and shows what channel you're viewing (in the drop down GUI), and if they're verified (by showing the blue tick beside the Brave Rewards icon and under their name in the drop down GUI). The bugged behaviour reappears after closing Brave.

Also, the little blue tick not displaying on any website is still happening (with my configuration of Brave Rewards enabled, and Auto-Contribute disabled as mentioned in the above comment). Clicking the BAT/Brave Rewards icon, then refreshing the tab, fixes the issue while Brave remains open. It resets to the previous behaviour after closing Brave.

Hope this helps!

**Comment by wavesurf432** [comment]
Looks to be fixed with the latest update. Also, the little blue tick is now showing with the Brave Rewards enabled, and Auto-Contribute disabled - thanks!

**Comment by Saoiray** [comment]
@emerick This was recently brought up by someone again but only on Android. Their Creators over at https://www.twitch.tv/lego11as 

If open on Desktop, it shows them as a Verified Creator. When that same site is visited on Android, it only shows as Twitch rather than the Creator and, as a result, shows Twitch as the Unverified Creator. 

Didn't matter if I refreshed, different page/tab of their Twitch, if opened in Private tab, or anything. I even went to the hamburger menu and toggled Desktop Mode, but that didn't resolve. 

Then on Desktop, typed in mobile address. https://m.twitch.tv/lego11as/home  
On that, it resulted in the same issue as on Android. Just showing Twitch as the Creator and Unverified. Pulled up console and this is what I'm seeing:

o278969.ingest.sentry.io/api/5214452/envelope/?sentry_key=c3cb7773390246c98fb8348076b26b25&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/lego11as:1 Access to font at 'moz-extension://mfaedmjlefifhnhpgipjjiiekchaimpk/fonts/museo-500.woff2' from origin 'https://m.twitch.tv' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, https, isolated-app, brave, chrome-untrusted, data, chrome, chrome-extension.
museo-500.woff2:1          Failed to load resource: net::ERR_FAILED
o278969.ingest.sentry.io/api/5214452/envelope/?sentry_key=c3cb7773390246c98fb8348076b26b25&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o278969.ingest.sentry.io/api/5214452/envelope/?sentry_key=c3cb7773390246c98fb8348076b26b25&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o278969.ingest.sentry.io/api/5214452/envelope/?sentry_key=c3cb7773390246c98fb8348076b26b25&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o278969.ingest.sentry.io/api/5214452/envelope/?sentry_key=c3cb7773390246c98fb8348076b26b25&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o278969.ingest.sentry.io/api/5214452/envelope/?sentry_key=c3cb7773390246c98fb8348076b26b25&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o278969.ingest.sentry.io/api/5214452/envelope/?sentry_key=c3cb7773390246c98fb8348076b26b25&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o278969.ingest.sentry.io/api/5214452/envelope/?sentry_key=c3cb7773390246c98fb8348076b26b25&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o278969.ingest.sentry.io/api/5214452/envelope/?sentry_key=c3cb7773390246c98fb8348076b26b25&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o278969.ingest.sentry.io/api/5214452/envelope/?sentry_key=c3cb7773390246c98fb8348076b26b25&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://cofdbpoegempjloogbagkncekinflcnj/build/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

I kind of wish I knew how to do the equivalent on Android.

**Comment by Miyayes** [comment]
>If open on Desktop, it shows them as a Verified Creator. When that same site is visited on Android, it only shows as Twitch rather than the Creator and, as a result, shows Twitch as the Unverified Creator.
>
>Didn't matter if I refreshed, different page/tab of their Twitch, if opened in Private tab, or anything. I even went to the hamburger menu and toggled Desktop Mode, but that didn't resolve. @Saoiray 

I think this is just because Twitch is not supported on Android.

**Comment by Saoiray** [comment]
> > If open on Desktop, it shows them as a Verified Creator. When that same site is visited on Android, it only shows as Twitch rather than the Creator and, as a result, shows Twitch as the Unverified Creator.
> > Didn't matter if I refreshed, different page/tab of their Twitch, if opened in Private tab, or anything. I even went to the hamburger menu and toggled Desktop Mode, but that didn't resolve. @Saoiray
> 
> I think this is just because Twitch is not yet supported on Android.

Yeah, I've learned it's intentional. I didn't ever pay attention to tipping on Android. Uncertain why we don't allow tipping to people on Reddit, Twitter, or Twitch from Android and that it's a Desktop only thing for the moment. Not sure whose idea that is or even when it will be adjusted so tipping works on all platforms. But I guess that's going to be a different issue.

**Comment by Miyayes** [comment]
Difficult to reproduce. Haven't seen it as much recently.

**Comment by Miyayes** [comment]
Lauren: Longstanding issue where this happens for media publishers.

**Comment by Miyayes** [comment]
We no longer use Greaselion.
