### ISSUE TITLE
Copying brave:// results in pasting chrome://

### ISSUE THREAD

**Issue by kirkins** [brave/brave-browser#1973]
## Description 

Copying the url for brave:// in settings results in having chrome:// in clipboard.

## Steps to Reproduce

   1. Go to brave://settings/help
   2. Copy the url
   3. paste the url

## Expected result:
Paste brave://

## Reproduces how often: 

All times

## Brave version (brave://version info)

Version 0.57.3 Chromium: 70.0.3538.67 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
The editing portion of this was addressed when fixing https://github.com/brave/brave-browser/issues/1616 (with https://github.com/brave/brave-core/pull/1385)

Copy to clipboard not fixed though

**Comment by kjozwiak** [comment]
Verification **PASSED** on **`macOS 10.15.3 x64 Catalina`** using the following build:

```
Brave | 1.7.64 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.15.3 (Build 19D76)
```

* ensured that copying/pasting the following URLs correctly used `brave://` instead of `chrome://`
   * `brave://version`, `brave://rewards`, `brave://help`, `brave://wallet`, `brave://crashes`,  `brave://bookmarks`, `brave://components`, `brave://downloads`, `brave://extensions`, `brave://flags`, `brave://gpu`, `brave://local-state
* ensured that the above worked on PB, Tor and Guest windows/instances as well.
* ensured that `chrome://` still resolved to `brave://` without any issues
