### ISSUE TITLE
retire Binance widget rather than completely removing

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#19888]
## Description 

As per discussions, we'll be reverting https://github.com/brave/brave-core/pull/11148 from `1.35.x` & `1.34.x` and will implement the following which aligns closer to what desktop did via https://github.com/brave/brave-core/pull/11266.

As per @bbondy, we'll do the following:

```
* Retire it to the Edit stack screen (i.e. equivalent to gallery on Desktop) for new users or if a user hasn't used it.
* Keep it there for users that have connected to it
```

## Steps to reproduce 

**`Test Case #1`**

   1. install `1.34.34 Chromium: 96.0.4664.45` which has Binance as a widget
   2. upgrade to `1.35.4 Chromium: 96.0.4664.55` and it will be completely removed (even if you're authenticated)

## Actual result 

Binance is being completely removed even if users are authenticated when upgrading to a version with https://github.com/brave/brave-core/pull/11148.

## Expected result

```
* Retire it to the Edit stack screen (i.e. equivalent to gallery on Desktop) for new users or if a user hasn't used it.
* Keep it there for users that have connected to it
```

## Issue reproduces how often 

100% reproducible using the STR/Cases mentioned above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 12`
   
## Brave version

```
1.35.4 Chromium: 96.0.4664.55
```

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @rebron @srirambv @bbondy @deeppandya

**Comment by deeppandya** [comment]
@kjozwiak I would assume that the conditions would apply only for release channel as for beta and nightly we have already removed the widget. So those users would be treated as new users.

**Comment by kjozwiak** [comment]
@deeppandya yup, that makes sense 👍 Just double checking though, once `1.34.x` makes it into release, will we run into the above again? Assuming not as we'll revert the above code correct and as you mentioned, treat users in `1.35.x` & `1.34.x` as new users.

**Comment by deeppandya** [comment]
I will revert the changes on all channels but doing that may affect the users on beta and nightly as I removed the prefs which was saving the information for those users. I think we should be okay, because we haven't heard any complaints yet from the users on beta and nightly.

**Comment by bbondy** [comment]
> I will revert the changes on all channels but doing that may affect the users on beta and nightly as I removed the prefs which was saving the information for those users. I think we should be okay, because we haven't heard any complaints yet from the users on beta and nightly.

Sounds fine

**Comment by kjozwiak** [comment]
Waiting on https://github.com/brave/brave-browser/issues/20331 to get addressed before we uplift https://github.com/brave/brave-core/pull/11551 into `1.34.x`.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.34.80 x64 build


**`Clean Install - Open NTP`**

   1. Install `1.34.80`
   2. Verified no Binance widget is shown on NTP
   3. Open a new tab still no Binance widget in the stack

**`Clean Install - Open Tab Manager`**

   1. Install `1.34.80`
   2. Verified no Binance widget is shown on NTP
   3. Open tab manager and return to the same NTP no Binance widget is shown
   4. Open tab manager and open a new tab via `+`, no Binance widget is shown

**`Upgrade - Open NTP`**

   1. Install `1.34.106`
   2. Ensure Binance is available
   3. Upgrade to `1.34.80`
   4. Verified Binance is removed from the widget list
   5. Open a new tab, no Binance widget is shown

**`Upgrade - Tab Manager`**

   1. Install `1.34.106`
   2. Ensure Binance is available
   3. Upgrade to `1.34.80`
   4. Verified Binance is removed from the widget list
   5. Open tab tray and return to the same tab, no Binance widget is shown 

**`Upgrade - Binance Authenticated`**

   1. Install `1.34.106`
   2. Ensure Binance is available
   3. Authenticate Binance and move to the widget to the top of stack
   3. Upgrade to `1.34.80`
   4. Verified Binance is retained in the same position before upgrade

Note: If you remove the widget on NTP and open tab tray it will still show the widget on stack but it actually isn't this is an issue with the app taking tab snapshot to show in tab tray. Same thing happens when you try to swipe tabs
