### ISSUE TITLE
About QA Code

### ISSUE THREAD

**Issue by s1204IT** [brave/brave-browser#19932]
![Screenshot_20211206-203447_Brave](https://user-images.githubusercontent.com/52069677/144839325-d4c270e2-dd43-4899-85b0-1593e2eaddf4.png)<br>
**What '***QA Code***' is?**
I want it.

**Comment by thefallofbecause** [comment]
If you were meant to have it you already would. It is for Brave's testing team only.

**Comment by s1204IT** [comment]
How can I get on that ***team***?

**Comment by srirambv** [comment]
This is for internal testing only. Its not publicly available. You can continue testing and report issues on GH.

**Comment by xBZZZZ** [comment]
<blockquote cite="https://github.com/brave/brave-browser/issues/19932#issuecomment-986756271">Its not publicly available.</blockquote>qa code is publicly avaiable somewhere inside apk because:<ul><li><a href="https://github.com/brave/brave-core/blob/65f8e6ca5faa2acddbc7a1fa6b871f3510688554/android/java/org/chromium/chrome/browser/settings/developer/BraveQAPreferences.java#L326"><code>Enter QA code</code> modal checks entered string by comparing it to <code>BraveConfig.DEVELOPER_OPTIONS_CODE</code></a></li><li><a href="https://github.com/brave/brave-core/blob/65f8e6ca5faa2acddbc7a1fa6b871f3510688554/build/android/java/templates/BraveConfig.template#L12"><code>public static final String DEVELOPER_OPTIONS_CODE = BRAVE_ANDROID_DEVELOPER_OPTIONS_CODE;</code></a></li><li><a href="https://github.com/brave/brave-core/blob/65f8e6ca5faa2acddbc7a1fa6b871f3510688554/android/BUILD.gn#L27"><code>"BRAVE_ANDROID_DEVELOPER_OPTIONS_CODE=\"$brave_android_developer_options_code\"",</code></a></li><li><a href="https://github.com/brave/brave-core/blob/65f8e6ca5faa2acddbc7a1fa6b871f3510688554/build/commands/lib/config.js#L608"><code>args.brave_android_developer_options_code = this.braveAndroidDeveloperOptionsCode</code></a></li><li><a href="https://github.com/brave/brave-core/blob/65f8e6ca5faa2acddbc7a1fa6b871f3510688554/build/commands/lib/config.js#L259"><code>this.braveAndroidDeveloperOptionsCode = getNPMConfig(['brave_android_developer_options_code']) || ''</code></a></li><li>qa code seems hard coded from build configuration</li></ul>

**Comment by Steveantor** [comment]
> This is for internal testing only. Its not publicly available. You can continue testing and report issues on GH. 

And you claim it to be open sourced while having some secret codes only known by the teams? Are non-team members discouraged to contribute and test those features??

**Comment by xBZZZZ** [comment]
qa code is `bbqkdk` (found by decompiling `classes.dex` inside [apk](https://github.com/brave/brave-browser/releases/download/v1.64.122/BraveMonoarm.apk))

**Comment by Steveantor** [comment]
> qa code is `bbqkdk` (found by decompiling `classes.dex` inside [apk](https://github.com/brave/brave-browser/releases/download/v1.64.122/BraveMonoarm.apk))

Yeah, but we shouldn't even  need to decompile it

**Comment by s1204IT** [comment]
> > qa code is `bbqkdk` (found by decompiling `classes.dex` inside [apk](https://github.com/brave/brave-browser/releases/download/v1.64.122/BraveMonoarm.apk))
> 
> Yeah, but we shouldn't even need to decompile it

I have checked and it appears that the QA code has never been changed since its creation.  
(From **1.0.97**, as far as I know.)
