### ISSUE TITLE
Autoplay allow text is missing in content setting

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#20018]
## Steps to Reproduce

   1.  Navigate to brave://settings/content/autoplay
   2
## Actual result:

Allow text is missing in allow section
<img width="695" alt="Screen Shot 2021-12-09 at 13 21 53" src="https://user-images.githubusercontent.com/11330831/145477749-64fd0524-98af-4e9e-854d-8260dc9db583.png">

## Expected result:
Allow text should be there just like other context settings
<img width="684" alt="Screen Shot 2021-12-09 at 13 24 43" src="https://user-images.githubusercontent.com/11330831/145478006-d0480beb-fac0-4797-ac7e-c85a1a711b51.png">

## Brave version (brave://version info)

1.35.10 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.43.55 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.795)
```
#### Confirmed the text `Allow` is displayed above site names in `Sites listed below follow a custom setting instead of the default` section
Also confirmed `Autoplay` displayed `Allow` for permissions
Ex1|Ex2
---|----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/182487065-ab3e2059-6608-4054-99fb-ff5d5ad6de41.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/182487223-310c1269-fb73-4c8f-9b13-4955fba153b0.png">
