### ISSUE TITLE
[Q] Will manifest V2 extensions be supported in Brave after their removal from Chrome?

### ISSUE THREAD

**Issue by NightMachinary** [brave/brave-browser#20059]
See, e.g., https://news.ycombinator.com/item?id=29521258 .

**Comment by bsclifton** [comment]
Yes - this will be supported 👍 We'll be taking steps as V2 is sunset by Chromium team (https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/)

During the deprecation period, we can keep this functionality via patch (since it's there for Enterprise). After V2 is pulled from store, we'll need to stand up our own extension store for manifest v2

cc: @rebron

**Comment by NSExceptional** [comment]
@bsclifton Can you elaborate on the "enterprise" part? Is the Chromium team maintaining an official patch with V2 in it for enterprise browsers?

**Comment by bsclifton** [comment]
@NSExceptional basically the group policy templates will allow for support of this. You won't need those for Brave, but we can leverage the code that's there (since the code still exists in Chromium)
