### ISSUE TITLE
Users make the case for having 2FA built in 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#20133]
This thread makes the case that they'd find it useful to have 2FA. I mentioned that if someone has your original seed phrase you can have any amount of user approval and it won't help. But they'd still find it useful. 

https://community.brave.com/t/2fa-for-every-transaction-in-brave-wallet/314553/4?u=brian

Thinking about it more, if you assume a user has a secure backup stashed away, it still does make sense to be able to protect the hot wallet more with 2FA.

**Comment by BirdInFire** [comment]
i have a proposition for 2FA with the actual system.
Use an encrypted key who leave the device only by encrypted transfert.

So to resume
<Encryption key> Is encrypted by <another key> specially generated for this "direct (or via relay) transfert".
And this <another key> (who is differents each time you connect a new device (since generated for the transferts) is the 2FA) since you must copy it from the host (who share the key) to the new device (who receive it) (as BIP39 or QR code).

With this little change, you can "securely" transfert de key by adding this "2FA" since if you don't use another device you cannot rejoin de chain.

With this new security you can even transfert the <KEY> from the wallet the same way and remove the possibility someone just see the key and use it to connetect himself (to the wallet or the sync feature).

Hope this little change is actually implementable to brave because i'm not at ease with the fact that if someone found my bip39 mnemonic he have accès to my account (and if i don't check my "sync" menu) he can see all my data without having any warning on my end.
