### ISSUE TITLE
Can't install extensions

### ISSUE THREAD

**Issue by wildcard-f8** [brave/brave-browser#20168]
## Description 

Can't add extensions.

## Steps to Reproduce

   1. Go to extension store
   2. Install extension
   3. ?

## Actual result:

![Screenshot from 2021-12-20 06-37-10](https://user-images.githubusercontent.com/51791246/146693434-247cc306-3085-485d-8fc4-8d5b44184b8a.png)

## Expected result:

Be able to install extension?

## Reproduces how often: 

?

## Brave version (brave://version info)

Dissenter	1.5.114 Chromium: 80.0.3987.149 (Official Build) (64-bit)
Revision	5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS	Linux
JavaScript	V8 8.0.426.27
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Command Line	/opt/dissenter.com/dissenter/dissenter --class=dissenter-browser --class=dissenter-browser --disable-domain-reliability --no-pings --disable-sync --disable-machine-id --disable-breakpad --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,WebXR,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	/opt/dissenter.com/dissenter/dissenter
Profile Path	/home/magicpotion/.config/GabAI/Dissenter-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by shaunhaney** [comment]
I just tried this on Windows 10 after a fresh download of the Brave browser and was able to install the AdBlock extension (at least up to the point it asked for payment).  This likely means that the problem installing is due to system configuration or your network.  More information is needed to address your issue. 

You don't state whether you tried extensions other than the AdBlock extension.  Your image has a good clue as to the reason for the failure, though.  The download item on the bottom left corner shows "https://go-updater.....  403 Forbidden".   When trying to download the extension, it looks like you're running into an error 403.  If you go to the top right menu with three horizontal bars , then go to "More Tools", and then Developer Tools and choose the "Console" tab, you can probably find the full address of the URL you were not able to get to.  Posting the rejected URL might tell us more about what's going on. 

I wasn't able to reproduce this issue, but we might have a good chance of knowing why it's happening to you if you post the URL you're getting a 403 on.   Thanks!

**Comment by shaunhaney** [comment]
Just tested to make sure logging out of my Google account does not cause the 403.  It does not.

**Comment by kjozwiak** [comment]
@wildcard-f8 it's because you're on a really old version of Brave. From the information that you've provided, looks like you're on `1.5.114 Chromium: 80.0.3987.149 (Official Build) (64-bit)` is is pretty old. We're actually on Chromium `96.0.4664.110` so you're behind at least 16 major versions. I would recommend upgrading as you're leaving yourself vulnerable as there's been a lot of security issues fixed between `80` and `96`.

The reason you're seeing the issue is because the `go-updater` has been keyed which means certain components, in this example extensions, need to be keyed to be able to communicate with `go-updater`. The version you're using is missing that.

You'll need to update to the latest version of Brave to fix the above. Going to close this issue as it's not a real problem and expected behaviour. As mentioned above, a simple upgrade will fix the above.

**Comment by wildcard-f8** [comment]
Thanks! I guess Dissenter isn't being updated.
