### ISSUE TITLE
Improve asset registry for multi-chain wallet

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#20184]
### Background

The current `ERCTokenRegistry` controller was designed only for Ethereum, and not a multi-chain wallet. In this issue, we try to spec an asset registry that works for all chains.

### Goals

- Define an abstraction for network ID / chain ID, since these concepts are not found on all blockchains.

  EVM chains have chain ID, Bitcoin has network bytes, etc.

  We define the abstraction **`blockchain`**, which contains **name of the currency** AND a **human-readable name of the network**. Examples:
    - `bitcoin_testnet3`
    - `polygon_mainnet`
    - ...
- Maintain a network-specific asset registry that can be queried based on the `blockchain` defined above.
- Define a schema for representing tokens under various blockchains (Ethereum, Solana, EVM rollups, etc).
- Serve asset logos namespaced by a reliable ID like contract address. More on this later.

### Proposed API

```ts
enum Blockchain {
  EthereumMainnet = "ethereum_mainnet",
  EthereumRopsten = "ethereum_ropsten",
  BitcoinMainnet  = "bitcoin_mainnet",
  PolygonMainnet  = "polygon_mainnet",
  ZKSyncMainnet   = "zksync_mainnet",
  SolanaMainnet   = "solana_mainnet"
}

interface AssetRegistry {
  // Get full token list of the desired blockchain
  GetBlockchainAssetsConfig (blockchain: Blockchain) {}

  // Get the chain configuration of the desired blockchains (excludes token list)
  GetBlockchainConfig (blockchain: Blockchain) {}

  // Get all blockchain configs (excludes token list)
  GetAllBlockchainConfigs () {}
}
```

* **Bitcoin**
  ```js
  GetBlockchainAssets(BitcoinTestnet3)
  {
    symbol: "tBTC",
    name: "Bitcoin Testnet",
    net: 0x0709110b,
    hdCoinType: 1,
    decimals: 8,
    logo: "...",
    coingeckoId: "bitcoin",
    includeInPortfolioTotal: false,
    tokens: []
  }
  ```

* **Solana**
  ```js
  GetBlockchainAssets(SolanaMainnet)
  {
    symbol: "SOL",
    name: "Solana",
    chainId: 101,
    decimals: 18,
    logo: "...",
    coingeckoId: "solana",
    includeInPortfolioTotal: true,
    tokens: [
      {
        address: "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs",
        symbol: "ETH",
        name: "Wrapped Ether (Wormhole)",
        decimals: 8,
        logo: "...",
        coingeckoId: "ethereum"
      },
      ...
    ]
  }
  ```
* **Polygon**
  ```js
  GetBlockchainAssets(PolygonMainnet)
  {
    symbol: "MATIC",
    name: "Polygon",
    chainId: 137,
    decimals: 18,
    logo: "...",
    coingeckoId: "polygon",
    includeInPortfolioTotal: true,
    tokens: [
      {
        address: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
        symbol: "DAI",
        name: "(PoS) Dai Stablecoin",
        decimals: 18,
        logo: "...",
        coingeckoId: "dai"
      },
      ...
    ]
  }
  ```
* **Optimism**
  ```js
  GetBlockchainAssets(OptimismMainnet)
  {
    symbol: "OETH",
    name: "Optimistic Ethereum",
    chainId: 10,
    decimals: 18,
    logo: "...",
    coingeckoId: "ethereum",
    includeInPortfolioTotal: true,
    tokens: [
      {
        address: "0x8700dAec35aF8Ff88c16BdF0418774CB3D7599B4",
        symbol: "SNX",
        name: "Synthetix Network",
        decimals: 18,
        logo: "...",
        coingeckoId: "havven"
      },
      ...
    ]
  }
  ```

### Price information

We recently switched to using contract addresses for querying asset prices from CoinGecko (see https://github.com/brave/brave-browser/issues/19574). This may not work for other chains due to the way coingecko API works. We define a `coingeckoId` that remains fixed for ETH/WETH across multiple chains.

If, however, the current method works for all chains, we'll keep using that until there's a reason to migrate.

### Logos

We currently serve logos at `chrome://erc-token-images/dai.png`, where `dai` is the asset symbol. This is not a reliable way to associate a logo with an asset, because the same symbol may have different logos on different chains. Example 👇.

  | Ethereum - ETH | Solana - ETH |
  -|-
  |<img width="100px" src="https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/info/logo.png">|<img width="75px" src="https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs/logo.png">|

#### Proposed method 1

Serve logos at:
- `chrome://assets-registry/blockchains/polygon_mainnet/logo.svg` for native asset.
- `chrome://assets-registry/blockchains/polygon_mainnet/0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063/logo.svg` for tokens.

#### Proposed method 2

Serve logos at `chrome://wallet-asset-logos/dai.svg`, where `dai` is the `coingeckoId`. The images could be prefetched through a script and made available in the user data, or proxied directly to Coingecko CDN.

### Portfolio

We maintain a `includeInPortfolioTotal` field in the blockchain config to decide whether to include it in the total portfolio value.

### Faster lookups

In order to lookup a token config with `O(1)` complexity, we could have an object instead of a list.

**Before:**
```js
[
  {
    address: "0xDEADBEEF",
    symbol: "DOG"
  },
  ...
]
```

**After:**
```js
{
  "0xDEADBEEF": {
    symbol: "DOG"
  },
  ...
}
```

### Resources

We'll pull the assets list from various sources into a super registry that allows us to:
1. easily update from upstream sources and make it available to users without a browser update.
2. add custom tokens before they are available in upstream sources. 

Here's a list of sources that are actively maintaining assets list for various blockchains:
- https://github.com/solana-labs/token-list
- https://github.com/trustwallet/assets
- https://github.com/MetaMask/contract-metadata  (we currently use this)
- https://tokenlists.org

**Comment by bbondy** [comment]
Thanks for getting this conversation going and sorry for the delay in reviewing (hit PTO).

I realized that we can simply use special strings for chain_ids of other chains like Bitcoin and Solana. 

For example if it is of the form "0x36" then it is an EVM chain ID. If it is "solana" then it is the special chain id for Solana.  I describe that here: 
https://github.com/brave/brave-browser/issues/20342

This issue is mixing network info and asset info. We currently manage networks in `JsonRpcService` with `AddEthereumChain` taking in an `EthereumChain`

```
struct EthereumChain {
  string chain_id;
  string chain_name;
  array<string> block_explorer_urls;
  array<string> icon_urls;
  array<string> rpc_urls;
  string symbol;
  string symbol_name;
  int32 decimals;
  bool is_eip1559;
};
```

I don't think we should try to move over the chain info into the token registry.  Both because it would involve more changes than are needed and because I think it fits better where it is.

I agree with `coingeckoId` but we can treat that separately from the rest of this. I posted this issue to track that.  When that field is present, we should use it for price lookups in CoinGecko.
https://github.com/brave/brave-browser/issues/20344

I agree with `includeInPortfolioTotal` but we can treat that separately from the rest of this. I posted this issue to track that. Also note that I believe this is not related to the token but related to the network level
https://github.com/brave/brave-browser/issues/20345


```
struct ERCToken {
  string contract_address;
  string name;
  string logo;
  bool is_erc20;
  bool is_erc721;
  string symbol;
  int32 decimals;
  bool visible = true;
  string token_id = "";  // Non-empty for ERC721 tokens.
};
```


I think we can pass on the logos work for now but we can defer that to a cleanup later. We already have a separate logo field so we can define different assets or use the same if we want to.


Re faster lookups, we do already store things in `~/Library/Application\ Support/BraveSoftware/Brave-Browser/BraveWallet/1.0.11/contract-map.json` with address first. We just don't define our API that way to access it currently. We can change that but I think it can be treated separately.


> We'll pull the assets list from various sources into a super registry that allows us to:
> 1. easily update from upstream sources and make it available to users without a browser update.
> 2. add custom tokens before they are available in upstream sources.

We do this already in `brave-core-crx-package` and we can define our own there and do updates without browser updates. We do some post processing here:  https://github.com/brave/brave-core-crx-packager/blob/754fd639628e84ecce507bf769a76e484ee51d15/scripts/packageComponent.js#L63 But we only use the contract-map json file for now.
Solana tokens are being tracked here: https://github.com/brave/brave-browser/issues/19459
Not sure yet if there's value in the trust wallet assets and token lists.org


Related:
https://github.com/brave/brave-browser/issues/20342
https://github.com/brave/brave-browser/issues/20343
https://github.com/brave/brave-browser/issues/20344
https://github.com/brave/brave-browser/issues/20345
https://github.com/brave/brave-browser/issues/19459

**Comment by bbondy** [comment]
Closing in favor of the above 5 issues.
