### ISSUE TITLE
Sync forces rebuilds even when there are no code changes

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#20316]
Locally (linux; ext4 rw,relatime; no git cache), using latest master, running `git pull && npm install && npm run sync && npm run build -- Release --channel=nightly` multiple times causes a rebuild of 2.5k objects every time, including linking which takes forever.

With no changes in brave-browser and brave-core and with everything already built, this should not trigger rebuilds of anything.

A build without a sync does not rebuild anything.

Slack thread: https://bravesoftware.slack.com/archives/C02QCQCH1RA/p1641294255081800?thread_ts=1639533451.044400&cid=C02QCQCH1RA

This came in the context of incremental builds https://github.com/brave/devops/issues/4944.

**Comment by wknapik** [comment]
Files touched by sync/build:
* https://gist.github.com/wknapik/cf4e01d4952b774df16628af48db0770 (all file types)
* https://gist.github.com/wknapik/7d5f33fc63689f4e8a958e43fed2e5e0 (just regular files)

**Comment by mihaiplesa** [comment]
This was observed in https://github.com/brave/brave-core/pull/11543 and https://github.com/brave/brave-browser/pull/20020

**Comment by mherrmann** [comment]
This also seems related: https://github.com/brave/brave-core/pull/9283

**Comment by mherrmann** [comment]
The main culprit seems to be the folder `src/third_party/devtools-frontend/src/inspector_overlay`. Changing the modification time of `common.css` or `resources.grd` in this directory causes 653 files to be re-built, following a re-linking of the browser. I suspect that it is the same for any other file in that folder.

A secondary culprit is `src/third_party/icu/common/icudtl.dat`. Changing its modification time causes ~2350 to be re-built. However, there is no re-linking.

One thing I don't understand @mihaiplesa @wknapik is the severity of this issue. The re-linking step takes 3-4 minutes on my admittedly beefy machine. But is that such a big issue? Or am I missing something? (Asking not to question the validity of the issue, of course, but to better understand the context in pursuit of an appropriate fix.)

**Comment by mihaiplesa** [comment]
What we want to achieve is to not have rebuilds when sync runs and there are no code changes. On the other platforms this works as expected, it's just Linux that seems to behave differently.

**Comment by wknapik** [comment]
Yes, in the long run, we want zero rebuilds when there are no code changes. For now there's a few on all platforms and we can accept that for the time being, but on Linux there's more. So let's get Linux in line with the other platforms and then we can get them all to 0.

**Comment by mherrmann** [comment]
I'm in the process of trying to find out why the files in `inspector_overlay/` get their modification date changed. A difficulty is that it is not always reproducible. I.e. `npm run sync` often stops changing them for me at some point.

**Comment by mherrmann** [comment]
`gclient sync --reset --nohooks` also reproduces the issue instead of `npm run sync`. `npm run sync` internally calls the former command.

**Comment by mherrmann** [comment]
Furthermore, as I mentioned, the issue sometimes stops appearing for me. It appears that calling `npm run build -- Release --channel=nightly` once makes it re-appear.

**Comment by mherrmann** [comment]
`rc/third_party/devtools-frontend/src/inspector_overlay/BUILD.gn` has the following code:

```
action("build_inspector_overlay") {
  ...
  public_deps = [
    ":copy_css_to_gen",
    ":copy_resources",
    ":inspector_overlay",
  ]
}

copy("copy_resources") {
  sources = [ "resources.grd" ]
  outputs = [ "$resources_out_dir/inspector_overlay_resources.grd" ]
}

copy("copy_css_to_gen") {
  sources = [
    "common.css",
    "tool_grid.css",
    "tool_highlight.css",
    "tool_paused.css",
    "tool_screenshot.css",
    "tool_source_order.css",
  ]
  outputs = [ "$target_gen_dir/{{source_file_part}}" ]
}

ts_library("inspector_overlay") {
  sources = [
    "common.ts",
    "css_grid_label_helpers.ts",
    "drag_resize_handler.ts",
    "highlight_common.ts",
    "highlight_container_query.ts",
    "highlight_flex_common.ts",
    "highlight_grid_common.ts",
    "highlight_isolated_element.ts",
    "highlight_scroll_snap.ts",
    "main.ts",
    "tool_distances.ts",
    "tool_highlight.ts",
    "tool_paused.ts",
    "tool_persistent.ts",
    "tool_screenshot.ts",
    "tool_source_order.ts",
    "tool_viewport_size.ts",
  ]

  deps = [ "../front_end/core/common:ColorUtils" ]
}
```

Note how the changing files - `common.css`, `tool_grid.css` etc. - appear in the `sources` arrays of targets mentioned as `public_deps`. The entries from `ts_library("inspector_overlay")` mostly do not change. Perhaps because this is `ts_library(...)` and not `copy(...)`.

**Comment by mherrmann** [comment]
I finally found the reason for the expensive re-linking.

`npm run sync` calls `gclient sync --reset --nohooks`, which in turn calls `git reset --hard HEAD` in `src/third_party/devtools-frontend/src`. This changes the modification timestamp of `common.css`, which leads to the re-build.

Now you may ask "why does the modification time of `common.css` change?". It's not because the file has changed. Instead (!), it is because there is a hardlink that points to this file. You read this right: If there is a hardlink to a file in a Git repo then `git reset --hard` _breaks_ the hardlink and Git creates its own copy of the file. This has a new modification timestamp.

The following example can be used to replicate the problem on Debian 11 and Git 2.30.2:

```
❯ git --version
git version 2.30.2
❯ mkdir git-test
❯ cd git-test
❯ git init
Initialized empty Git repository in .../git-test/.git/
❯ echo "test" > file.txt
❯ git add file.txt
❯ git commit -m "Import"
[main (root-commit) f73709f] Import
 1 file changed, 1 insertion(+)
 create mode 100644 file.txt
❯ stat -c '%y' file.txt
2022-01-19 18:43:52.147781748 +0100
❯ ls -i file.txt
74458979 file.txt
❯ ln file.txt ../file.txt
❯ git reset --hard
HEAD is now at f73709f Import
❯ stat -c '%y' file.txt
2022-01-19 18:44:47.013167127 +0100
❯ ls -i file.txt
74458995 file.txt
```

Note how the modification time and inode of the file changed as a result of `reset`. The hardlink is now broken, so the problem no longer occurs when we do `git reset --hard` again:

```
❯ git reset --hard
HEAD is now at f73709f Import
❯ stat -c '%y' file.txt
2022-01-19 18:44:47.013167127 +0100
❯ ls -i file.txt
74458995 file.txt
```

The problem does not occur for me on Debian 10 and 2.20.1.

I will now look for a way to use this knowledge to prevent the problem.

**Comment by mherrmann** [comment]
I asked on the Git mailing list whether the behavior can be avoided. http://public-inbox.org/git/CABrKpmDseZkPCpRb8KmBJaxDp24sySJay5ffZrxqgSMGKyj5qQ@mail.gmail.com/T/#u

**Comment by mherrmann** [comment]
There have been some responses on the mailing list, however none so far were helpful.

### Possible solution 1: Downgrade Git

@mihaiplesa brought up the idea of downgrading Git. I checked and `gclient sync --reset` takes `git` from the `PATH`. So this would likely be an option. Its pros and cons are:

Pros:
 * Relatively easy to implement
 * Would fix the problem on CI

Cons:
 * May break in the future if Chromium / Brave requires a newer git version
 * Won't fix the problem on developer machines unless we somehow ship Git with brave-core

There is a copy of `git` in `depot_tools`. However, it is on an even more recent version (2.33 in my case) and also exhibits the problem. Downgrading this copy (if even possible) might break things with Chromium so is probably not a good approach.

### Possible solution 2: Create a `git` wrapper

Because `gclient sync` takes `git` from the `PATH`, we could create our own wrapper of `git` for this one call. The wrapper would check if it is called with arguments `reset --hard`. If yes, then it would perform this operation more carefully than `git`, and not break hard links for unmodified files.

Pros:
 * Fixes the problem for developers and CI alike
 * Creates a uniform environment on CI and dev machines

Cons:
 * More effort to implement (I'd estimate a day's work)
 * Adds complexity to our code base

### Other ideas

 * `gclient recurse` lets us recurse into dependencies. Maybe we could use this to remove the hard links before `gclient sync --reset`. But it would likely incur an overhead, would potentially be brittle and also add extra complexity.
 * We could find out exactly which change between Git 2.20 and 2.30 introduced the unwanted behavior to get an idea what can be done to avoid it.

I'm still hoping for a better solution from Git's mailing list and have asked again there. I don't think it is likely that we will get one.

**Comment by mherrmann** [comment]
The reply on the Git mailing list (I don't know how authorative) is that the behavior can't be avoided. I'm kicking off a build locally with Git downgraded to 2.20, to see if that fixes the issue.

**Comment by mherrmann** [comment]
@mihaiplesa told me that downgrading Git may not always be feasible on CI. I'll investigate solution 2 above.

**Comment by wknapik** [comment]
@mherrmann and what about getting rid of the hardlinks, instead of trying to fix the git behavior around them? Is that an option?

**Comment by mherrmann** [comment]
The hard links are created by Chromium's build. We could write a script that removes them before `gclient sync --reset` and then restores them. But I don't see a way of doing it in a way that 1) is performant and 2) isn't brittle because it hard-codes specific paths.

**Comment by mherrmann** [comment]
I'm actually unable to set up Brave's build with Git 2.20.1. `npm run init` gives me:

```
RuntimeError: ("Command 'npm install --no-save' failed", "npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated\nnpm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated\nnpm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated\nnpm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated\nnpm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added\nnpm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.\nnpm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\nnpm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained\nnpm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.\nnpm WARN deprecated har-validator@5.1.5: this library is no longer supported\nnpm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained\nnpm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'\nnpm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained\nnpm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'\nnpm WARN deprecated source-map-url@0.3.0: See https://github.com/lydell/source-map-url#deprecated\nnpm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.\nnpm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.\nnpm WARN deprecated event-to-promise@0.8.0: Use promise-toolbox/fromEvent instead\nnpm ERR! code 128\nnpm ERR! An unknown git error occurred\nnpm ERR! command git --no-replace-objects clone -b v0.0.8 ssh://git@github.com/mahdyar/ansi-html-community.git /home/michael/.npm/_cacache/tmp/git-clonexRnP3V --recurse-submodules --depth=1\nnpm ERR! fatal: destination path '/home/michael/.npm/_cacache/tmp/git-clonexRnP3V' already exists and is not an empty directory.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/michael/.npm/_logs/2022-01-21T13_06_39_241Z-debug.log\n")
```

**Comment by mherrmann** [comment]
The problem is also somewhat time related. If almost no time passes between `git commit` and the creation of the hard link, then the problem does not occur. This can be tested with the script below.

<details>
<summary>Test script</summary>

```
#!/bin/bash

set -e

SLEEP_TIME_SECS=1

rm -rf git-test test.txt

mkdir git-test
cd git-test
git init > /dev/null
echo test > test.txt
git add test.txt
git commit -m Import > /dev/null
ls -i test.txt
sleep $SLEEP_TIME_SECS
ln test.txt ../test.txt
git reset --hard > /dev/null
ls -i test.txt
cd ..
```
</details>

With a delay of 1 second, the script prints two different inode numbers, indicating that Git broke the hardlink.

The above can easily be tried with Docker after the setup steps below.

<details>
<summary>Docker steps</summary>

```
docker run -it debian:bullseye /bin/bash
apt-get update > /dev/null
apt-get install git -y >/dev/null
git config --global user.email "me@test.com"
git config --global user.name "me"
git config --global init.defaultBranch main
```

</details>

**Comment by mherrmann** [comment]
With the above test script, I am now also able to reproduce the problem with Git 2.20.1 on Debian 10.

**Comment by mherrmann** [comment]
(I'm working on solution 2. above and observed the above while writing a Python-based `git` wrapper and associated automated test cases.)

**Comment by mherrmann** [comment]
Doing a `git status` between the creation of the hard link and `reset --hard` also fixes the problem.

<details>
<summary>Updated test script</summary>

```
#!/bin/bash

set -e

SLEEP_TIME_SECS=1

rm -rf git-test test.txt

mkdir git-test
cd git-test
git init > /dev/null
echo test > test.txt
git add test.txt
git commit -m Import > /dev/null
ls -i test.txt
sleep $SLEEP_TIME_SECS
ln test.txt ../test.txt

# This line fixes the broken hard link problem:
git status > /dev/null

git reset --hard > /dev/null
ls -i test.txt
cd ..
```

</details>

**Comment by mherrmann** [comment]
I've now created a [PR](https://github.com/brave/brave-core/pull/11970) that (in my tests) fixes the issue by calling `gclient recurse git status` before `gclient sync --reset`.

**Comment by mherrmann** [comment]
Another possible solution that was just recommended on the [Git mailing list](http://public-inbox.org/git/CABrKpmDseZkPCpRb8KmBJaxDp24sySJay5ffZrxqgSMGKyj5qQ@mail.gmail.com/T/#u) would be to set `git config core.trustctime false`. It fixes the problem in the simple "Test script" above. However, I'll pause investigation for now until some open questions in https://github.com/brave/brave-core/pull/11970 are resolved.
