### ISSUE TITLE
binance widget not being removed until a new NTP is opened  - follow up to #19888

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#20331]
## Description 

The Binance widget isn't being removed unless open a NTP or open the tab manager. If users are not authenticated, the Binance widget should be removed without users interacting with the NTP. This is a follow up to the work completed via https://github.com/brave/brave-core/pull/11485.

## Steps to reproduce 

**`Clean Install - Open NTP`**

   1. install `1.36.16 Chromium: 97.0.4692.71`
   2. notice that the Binance widget is still visible under the NTP
   3. open a new NTP and notice that the widget was removed

**`Clean Install - Open Tab Manager`**

   1. install `1.36.16 Chromium: 97.0.4692.71`
   2. notice that the Binance widget is still visible under the NTP
   3. open the `tab manager` and return to the same NTP and notice that the widget was removed

**`Upgrade - Open NTP`**

   1. install `1.34.34 Chromium: 96.0.4664.45`
   2. upgrade to `1.36.16 Chromium: 97.0.4692.71`
   3. notice that the Binance widget is still visible under the NTP
   4. open a new NTP and notice that the widget was removed

**`Upgrade - Tab Manager`**

   1. install `1.34.34 Chromium: 96.0.4664.45`
   2. upgrade to `1.36.16 Chromium: 97.0.4692.71`
   3. notice that the Binance widget is still visible under the NTP
   4. open the `tab manager` and return to the same NTP and notice that the widget was removed

## Actual result 

Binance widget isn't being removed until a NTP is opened or the tab manager is opened and a user returns to the same NTP.

## Expected result

Binance widget should be removed and shouldn't require interaction with the NTP (only for non-authenticated users)

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `N/A`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 12`
   
## Brave version

* `1.36.16 Chromium: 97.0.4692.71`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.34.80 x64 build


**`Clean Install - Open NTP`**

   1. Install `1.34.80`
   2. Verified no Binance widget is shown on NTP
   3. Open a new tab still no Binance widget in the stack

**`Clean Install - Open Tab Manager`**

   1. Install `1.34.80`
   2. Verified no Binance widget is shown on NTP
   3. Open tab manager and return to the same NTP no Binance widget is shown
   4. Open tab manager and open a new tab via `+`, no Binance widget is shown

**`Upgrade - Open NTP`**

   1. Install `1.34.106`
   2. Ensure Binance is available
   3. Upgrade to `1.34.80`
   4. Verified Binance is removed from the widget list
   5. Open a new tab, no Binance widget is shown

**`Upgrade - Tab Manager`**

   1. Install `1.34.106`
   2. Ensure Binance is available
   3. Upgrade to `1.34.80`
   4. Verified Binance is removed from the widget list
   5. Open tab tray and return to the same tab, no Binance widget is shown 

**`Upgrade - Binance Authenticated`**

   1. Install `1.34.106`
   2. Ensure Binance is available
   3. Authenticate Binance and move to the widget to the top of stack
   3. Upgrade to `1.34.80`
   4. Verified Binance is retained in the same position before upgrade

Note: If you remove the widget on NTP and open tab tray it will still show the widget on stack but it actually isn't this is an issue with the app taking tab snapshot to show in tab tray. Same thing happens when you try to swipe tabs
