### ISSUE TITLE
Fake brave browser

### ISSUE THREAD

**Issue by AdamK222** [brave/brave-browser#20371]
![image](https://user-images.githubusercontent.com/66825147/148464543-70f96602-2a88-4010-b8f7-a349a782f627.png)

Lots of people are experiencing issues because of fake brave version in Ubuntu store. Deleting it might be a good way. I also had some because I didn't It won't be updated in future.

**Comment by DemigodKushal** [comment]
Ubuntu store user detected
Opinion invalid.

I use arch btw.

**Comment by kjozwiak** [comment]
hmmmm I installed a new/fresh copy of `Ubuntu 21.10 x64` on a VM and only see the `brave` entry and not the `Brave Browser` entry. Example:

![image](https://user-images.githubusercontent.com/2602313/148590338-c20ca0ce-9785-4d29-b5f1-dcb39eca340f.png)

@AdamK222 did you happen to add a repository accidently that wasn't officially Brave's? Did you do anything specific to see that `Brave Browser` entry? I'm also only seeing one entry of `brave` via https://snapcraft.io/search?q=brave.

![image](https://user-images.githubusercontent.com/2602313/148590746-5e975c78-dd61-41f6-b26e-6f5403e0a15e.png)

**Comment by wknapik** [comment]
Can't reproduce this. Please update your system and check again.

![image](https://user-images.githubusercontent.com/1129003/148591032-9bea30a1-4ffb-4eee-850e-ae71dc0c408d.png)

**Comment by wknapik** [comment]
The first instance of Brave in [the screenshot](https://user-images.githubusercontent.com/66825147/148464543-70f96602-2a88-4010-b8f7-a349a782f627.png) is called `brave`, the name and description [match our snap package](https://github.com/brave/brave-browser-snap/blob/stable/snapcraft.yaml#L6). The second one is called `Brave Browser`, the name and description match our [regular package](https://github.com/brave/brave-core/blob/master/chromium_src/chrome/installer/linux/common/brave-browser/chromium-browser.appdata.xml).

What we're likely seeing here is two legitimate installations of the browser.

In my screenshot, even though both packages are installed, the "Ubuntu Software" app is showing only one match. This may be because I installed the package from the command line, following instructions from brave.com/linux. Maybe the app has it's own way of adding/detecting repos/packages?

**Comment by mihaiplesa** [comment]
That sounds like it and we can close if everyone agrees.

**Comment by AdamK222** [comment]
Yep, its fixed now, old brave browser somehow disappeared from ubuntu software by itself.
