### ISSUE TITLE
Opening a new tab automatically loads the feed view rather than loading the NTP view with widgets

### ISSUE THREAD

**Issue by nonetrix** [brave/brave-browser#20413]
## Description 

Brave news feed on mobile automatically loads without scrolling this means it sends requests to Brave without the user wanting it to

## Steps to Reproduce

   1. Enable brave news feed
   2. Restart open new tab etc
   3. See that image is loaded

## Actual result:

News feed loads without scrolling unlike desktop client

## Expected result:
News feed loads only when scrolling down maybe also add a hint to tell the user that they can scroll just like the desktop version

## Reproduces how often: 

A monkey could do it

## Brave version (info found on brave://version)

Brave nightly from Google Play 1.36.23 Chromium: 97.0.4692.71 (Official Build) canary (64-bit)

## Version/Channel Information:

Nightly

- Can you reproduce this issue with the current release?
Feed doesn't work
- Can you reproduce this issue with the beta channel?
haven't tested
- Can you reproduce this issue with the dev channel?
Haven't tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

![Screenshot_20220110-011427](https://user-images.githubusercontent.com/45698918/148729623-84b66544-2946-489b-823d-0da641f80e89.png)

**Comment by srirambv** [comment]
@nonetrix This is expected behaviour to show the top of the card when news is enabled. Basically to indicate that Brave News is enabled and scrollable. You only get the cards from feed when you scroll 

However there is an issue when you scroll down the feed and open a new tab it still retains the news view rather than just opening the NTP and showing the card (like in your screenshot). I've updated the issue title 


https://user-images.githubusercontent.com/17010094/148730254-5a579ec6-968f-4824-8155-8d73f725e818.mp4

**Comment by mattmcalister** [comment]
yes, in response to the original issue, this is the way the service works when a user opts in to Brave News. it fetches the feed and shows the first card peeking up on the NTP. 

but we need to address the bug you've identified, @srirambv. am assigning it to @alexsafe.

**Comment by Uni-verse** [comment]
Verification **PASSED** on `Samsung Galaxy S21` running `Android 12` using build version `1.36.90, Chromium 98.0.4758.87`

- Verified opening a new tab loads NTP view
