### ISSUE TITLE
De-AMPing Feature: Redirect an AMP page to its canonical non-AMP version

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#20458]
We’d like to redirect Brave users from AMP pages to the canonical/non-AMP version of the page.

A complete De-AMPing solution is laid out in https://docs.google.com/document/d/1kvHbQMdE_vxmRWRz0LfAHzf6XoTT_pQXSwxth5rVhsk/edit#, this issue captures only the first part i.e. if the user tries to clicks on a link/tries to load a page that has AMP markup and contains a canonical link, then load the canonical link instead.

The plan is for this to be opt-out with a new setting in Security & Privacy section in brave://settings, controlled by Griffin.

**Comment by anthonypkeane** [comment]
Linked to https://github.com/brave/brave-browser/issues/18321

**Comment by anthonypkeane** [comment]
Text for this setting

**Header:** Auto-redirect AMP pages
**Body:** Always visit original (non-AMP) page URLs, instead of Google's Accelerated Mobile Page versions.

On Android, please this setting under

**Brave Shields & privacy**

Default = On

**Comment by LaurenWags** [comment]
@ShivanKaul could you provide a bit more detail for the test plan from https://github.com/brave/brave-core/pull/11750#issue-1094407255? Particularly examples, etc. I'm not familiar with all of the items listed, so more information, steps, example sites, etc would be welcomed. Thanks!

**Comment by ShivanKaul** [comment]
@LaurenWags I'll try to spin up a couple of test pages to address those test cases. But for a simple example, here's an AMP page: https://www.buzzfeed.com/ryanschocket2/snl-spoofs-will-smith-chris-rock-slap

**Comment by LaurenWags** [comment]
Removed `QA/Blocked` per https://github.com/brave/brave-browser/issues/20458#issuecomment-1088092754 as https://github.com/brave/brave-core/pull/11750#issue-1094407255 has been updated with more details. Thanks @ShivanKaul!

**Comment by MadhaviSeelam** [comment]
Verified `In-progress` using

Brave | 1.38.80 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 11 Version 21H2 (Build 22000.593)

**Comment by stephendonner** [comment]
Verified `IN-PROGRESS` using 

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)

Shared steps:
1. install `1.38.83`
2. launch Brave

<summary>Testcase 1: Inspected the element AMP pages</summary>
<details>

1. Disable `Auto-redirect AMP pages`in`brave://settings/privacy`
2. Disable Enable De-AMP flag - `brave://flags/#brave-de-amp`
4. Relaunch Brave
5. Visit AMP page `https://shivankaul.com/brave/de-amp/test-small-amp.html`.
    - Inspected element  and  `amp` attribute will be shown in the top level `<html amp>` tag for the AMP page  and has canonical link that redirects to html <link rel="canonical" href="https://brave.com/">
6. Close the tab and visit another AMP page `https://shivankaul.com/brave/de-amp/test-small-amp-with-lightning.html`
    - Inspected element and it contains lightning symbol in  the top-level `<html ⚡>` tag for the AMP page and has canonical link that redirects to html <link rel="canonical" href="https://brave.com/">
7. Close the tab and visit `https://shivankaul.com/brave/de-amp/test-no-canonical-link.html` 
    - Inspected element and it doesn't contain any canonical links or top-level tags
8. Close the tab and visit  `https://shivankaul.com/brave/de-amp/test-wrong-scheme.html` 
    - Inspected element for canonical link that is non-HTTP(s) - `<link rel="canonical" href="ipfs://QmcniBv7UQ4gGPQQW2BwbD4ZZHzN3o3tPuNLZCbBchd1zh">`
9. Close the tab and visit `https://shivankaul.com/brave/de-amp/test-small-amp-same-canonical.html`
    - Inspected the element and it has canonical link that is pointed to original/same URL
10. Close the tab and visit `https://www.buzzfeed.com/amphtml/ryanschocket2/snl-spoofs-will-smith-chris-rock-slap`
    - Inspected the element and it has canonical link that is pointed `https://www.buzzfeed.com/ryanschocket2/snl-spoofs-will-smith-chris-rock-slap`

s1|s2|s4|s5|s6|s7|s8|s9
---|---|---|---|---|---|---|---
<img width="1229" alt="Screen Shot 2022-04-07 at 6 46 24 PM" src="https://user-images.githubusercontent.com/387249/162347791-8a2aa9fa-b48c-4dd1-a2b7-052c2ff25408.png"> | <img width="1177" alt="Screen Shot 2022-04-07 at 6 47 13 PM" src="https://user-images.githubusercontent.com/387249/162347803-42ad0bc2-932e-4f25-8944-e4dfb9b13302.png"> | <img width="1085" alt="Screen Shot 2022-04-07 at 6 48 31 PM" src="https://user-images.githubusercontent.com/387249/162348044-6acafb02-25ef-4cf6-b754-c937feab4992.png"> | <img width="1085" alt="Screen Shot 2022-04-07 at 6 49 06 PM" src="https://user-images.githubusercontent.com/387249/162348051-08e43204-f01f-4ad0-b366-3d660ff4cbff.png"> | <img width="1085" alt="Screen Shot 2022-04-07 at 6 49 28 PM" src="https://user-images.githubusercontent.com/387249/162348056-4d271fc2-e542-4b3e-901d-fdc89bfca4b9.png"> | <img width="1312" alt="Screen Shot 2022-04-07 at 7 02 24 PM" src="https://user-images.githubusercontent.com/387249/162348801-633264d1-6a6d-4c5b-9a47-d679022bef38.png"> | <img width="1085" alt="Screen Shot 2022-04-07 at 6 49 55 PM" src="https://user-images.githubusercontent.com/387249/162348060-80d2f908-de52-4854-a568-0c349b5dc0e5.png"> | <img width="1085" alt="Screen Shot 2022-04-07 at 6 52 19 PM" src="https://user-images.githubusercontent.com/387249/162348061-67c19b26-052a-43cc-9539-2a0f69ff41ee.png">



</details>

**Comment by LaurenWags** [comment]
Added `OS/Android` based on issues uplifted to 1.38.x. If this does not need to be tested on Android please remove.

**Comment by kjozwiak** [comment]
> Added `OS/Android` based on issues uplifted to 1.38.x. If this does not need to be tested on Android please remove.
> 
> See discussion here: https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1650626855897409?thread_ts=1650384586.357469&cid=CHGKGMHDJ.

@LaurenWags `Android` we'll be checked via https://github.com/brave/brave-browser/issues/21643 👍

**Comment by btlechowski** [comment]
## Verified `PASSED` using 

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Ubuntu 18.04 LTS

### Shared steps:
1. install `1.38.x`
2. launch Brave

<summary>Testcase 1: Inspected the element AMP pages</summary>
<details>

1. Disable `Auto-redirect AMP pages`in`brave://settings/privacy`
2. Disable Enable De-AMP flag - `brave://flags/#brave-de-amp`
4. Relaunch Brave
5. Visit AMP page `https://shivankaul.com/brave/de-amp/test-small-amp.html`.
    - Inspected element  and  `amp` attribute will be shown in the top level `<html amp>` tag for the AMP page  and has canonical link that redirects to html <link rel="canonical" href="https://brave.com/">
6. Close the tab and visit another AMP page `https://shivankaul.com/brave/de-amp/test-small-amp-with-lightning.html`
    - Inspected element and it contains lightning symbol in  the top-level `<html ⚡>` tag for the AMP page and has canonical link that redirects to html <link rel="canonical" href="https://brave.com/">
7. Close the tab and visit `https://shivankaul.com/brave/de-amp/test-no-canonical-link.html` 
    - Inspected element and it doesn't contain any canonical links or top-level tags
8. Close the tab and visit  `https://shivankaul.com/brave/de-amp/test-wrong-scheme.html` 
    - Inspected element for canonical link that is non-HTTP(s) - `<link rel="canonical" href="ipfs://QmcniBv7UQ4gGPQQW2BwbD4ZZHzN3o3tPuNLZCbBchd1zh">`
9. Close the tab and visit `https://shivankaul.com/brave/de-amp/test-small-amp-same-canonical.html`
    - Inspected the element and it has canonical link that is pointed to original/same URL
10. Close the tab and visit `https://www.buzzfeed.com/amphtml/ryanschocket2/snl-spoofs-will-smith-chris-rock-slap`
    - Inspected the element and it has canonical link that is pointed `https://www.buzzfeed.com/ryanschocket2/snl-spoofs-will-smith-chris-rock-slap`


![image](https://user-images.githubusercontent.com/34715963/165192337-072ace50-91c5-4821-bfac-c8d6df902fe3.png)
![image](https://user-images.githubusercontent.com/34715963/165192410-fa8cceb3-c5ee-4e18-8222-83271767857b.png)
![image](https://user-images.githubusercontent.com/34715963/165192489-8bfcfd0d-a5be-4db1-a079-4e9cb3d12635.png)
![image](https://user-images.githubusercontent.com/34715963/165192542-49c69c90-321c-49a1-91ce-d7db1d3fd7e7.png)
![image](https://user-images.githubusercontent.com/34715963/165192587-3225e234-cb62-44ad-ac67-43251bff7a99.png)
![image](https://user-images.githubusercontent.com/34715963/165192611-f2ad60f6-1f94-48d1-a610-55f33e7873e3.png)
![image](https://user-images.githubusercontent.com/34715963/165192631-eff55a94-2d5e-403f-a60e-57613007916a.png)
![image](https://user-images.githubusercontent.com/34715963/165192805-b61a1139-ad89-437a-9608-d8bbcea3cf95.png)


</details>


<summary>Testcase 2: Verified AMP page will not be redirected, if `De-AMP` flag and `Auto-redirect AMP page` pref are disabled</summary>
<details>

1. Disable `Auto-redirect AMP pages`in`brave://settings/privacy`
2. Disable `#brave-de-amp` flag in `brave://flags/`
3. Relaunch the browser
4. Visit  `https://shivankaul.com/brave/de-amp/test-small-amp.html`
5.  Inspect the page and it showed`amp` as attribute
6. Contains `canonical` in the tag <link rel="canonical" href="https://brave.com/">
7. AMP Page is not redirected to `brave.com`

![image](https://user-images.githubusercontent.com/34715963/165192938-d1c32537-c4c6-4989-8fe3-c39fc9489d4f.png)
![image](https://user-images.githubusercontent.com/34715963/165192943-00bd7f5c-4d4e-41d6-9e4d-3780483203a0.png)
![image](https://user-images.githubusercontent.com/34715963/165192991-428d666b-7509-41a8-a249-4c3cc78f1edf.png)


</details>

### Prerequisites for the following testcases:
1. Verified `brave://settings/privacy`: `Auto-redirect AMP pages` is enabled by default
2. Verified `Enable De-AMP` is enabled by default in `brave://flags/#brave-de-amp` 

<summary>Testcase 3: Verified de-AMPing works as expected i.e redirects to brave.com with default settings </summary>
<details>

1. Visit `https://shivankaul.com/brave/de-amp/test-small-amp.html`
2. `De-AMPing` worked  i.e AMP page is redirected to `brave.com`, as it contained the markup for top-level `<html amp>`
3. The markup was verified in Testcase 1 for the above AMP page and  `amp` attribute will be shown in the top level `<html amp>` tag for the AMP page and has `canonical link` that redirects to html <link rel="canonical" href="https://brave.com/">

![image](https://user-images.githubusercontent.com/34715963/165193124-1dc36779-47c8-4c5e-8f60-6317f48cec64.png)
![image](https://user-images.githubusercontent.com/34715963/165193140-69781157-2c96-49c8-960a-5f03e072ba52.png)
![image](https://user-images.githubusercontent.com/34715963/165193194-aa6a94c0-34db-4f33-ba0c-d5110d6b6557.png)



</details>

<summary>Testcase 4: Verified de-AMPing works if the AMP page contains emoji `lightning symbol` instead of "amp" as attribute</summary>
<details>

1. Visit `https://shivankaul.com/brave/de-amp/test-small-amp-with-lightning.html`
2. `De-AMPing` worked  i.e AMP page is redirected to `brave.com` as it contained markup for top-level <html ⚡> tag
3.  The markup was verified in Testcase 1 for the above AMP page has `lightning` <html ⚡> tag and contains `canonical` in the tag for redirect 

![image](https://user-images.githubusercontent.com/34715963/165193241-c58a5b0a-c43f-4466-aa66-49181d24e898.png)

</details>

<summary>Testcase 5: Verified de-AMPing will not work for AMP page with no canonical link</summary>
<details>

1. Visit `https://shivankaul.com/brave/de-amp/test-no-canonical-link.html`
2. `De-AMPing` did not work i.e AMP page is not redirected since there is no `canonical link` tag
3. The markup was verified in Testcase 1, for the above AMP page has no `canonical link` tag hence no redirect available

![image](https://user-images.githubusercontent.com/34715963/165193285-207f2082-6b87-4eb4-9b04-27e49d7f8cb4.png)


</details>

<summary>Testcase 6: Verified de-AMPing will not work for AMP page that includes canonical link with scheme != HTTP(S)</summary>
<details>

1. Visit `https://shivankaul.com/brave/de-amp/test-wrong-scheme.html`
2. De-AMPing did not work i.e AMP page is not redirected since the AMP page has canonical link with scheme non HTTP(S)
3. Verified in Testcase 1, Step 8, that the above AMP page has canonical link with scheme non HTTP(S)


![image](https://user-images.githubusercontent.com/34715963/165193329-9a87ab0e-44bb-4be5-8eb3-6ec5bf18955b.png)



</details>

<summary>Testcase 7: Verified de-AMPing will not work for AMP page with canonical link same as original URL</summary>
<details>

1. Visit `https://shivankaul.com/brave/de-amp/test-small-amp-same-canonical.html`
2. "De-AMPing did not work i.e AMP page is not redirected since the AMP page has canonical link same as original URL
3. Verified in Testcase 1, Step 9, that the above AMP page has canonical link same as original URL <link rel="canonical" href="https://shivankaul.com/brave/de-amp/test-small-amp-same-canonical.html">

![image](https://user-images.githubusercontent.com/34715963/165193386-05a7ab3f-147c-48ab-b290-d17038d702b5.png)


</details>

<summary>Testcase 8: Verified navigating backward and forward ignores the AMP page in history</summary>
<details>

1. Visited `example.com`
2. Visited AMP page in the same tab- `https://shivankaul.com/brave/de-amp/test-small-amp.html` 
3. Page is redirected to `brave.com`
4. Visited `https://basicattentiontoken.org` in the same tab 
5. clicked back in the browser
6. Returned to `brave.com`
7. Clicked back again
8.  AMP page `https://shivankaul.com/brave/de-amp/test-small-amp.html` is ignored and is not listed in history
10. Clicked forward
11. User is taken `brave.com`
12. Clicked forward again
13. Returned to `https://basicattentiontoken.org`
14. AMP page `https://shivankaul.com/brave/de-amp/test-small-amp.html` is ignored and is not listed in history
15. Verified the history lists `example.com`, `brave.com`, and `basicattentiontoken.org`


![image](https://user-images.githubusercontent.com/34715963/165193849-b68aa47f-2500-4b4c-a4f2-c2826ab603df.png)
![image](https://user-images.githubusercontent.com/34715963/165193880-e838cd31-8b18-41d7-9b9d-343079f2459b.png)
![image](https://user-images.githubusercontent.com/34715963/165193948-378d7364-a498-441e-b452-2dca8a6bdbb2.png)
![image](https://user-images.githubusercontent.com/34715963/165193977-29176dd4-4d2e-4bc0-8373-8088d848b876.png)
![image](https://user-images.githubusercontent.com/34715963/165193994-be692a58-306b-4316-beb6-6a5ec7905be8.png)
![image](https://user-images.githubusercontent.com/34715963/165194024-75d992a1-01e7-41e3-bb3e-93a39b8f5337.png)
![image](https://user-images.githubusercontent.com/34715963/165194034-8dfa5071-8b79-44a1-9ec0-449e1d39bb76.png)
![image](https://user-images.githubusercontent.com/34715963/165194080-dabf61d1-4b41-4081-9e32-cdad603f676c.png)


</details>

<summary>Testcase 9: Verified restore de-AMPed page</summary>
<details>

1. Visit `https://shivankaul.com/brave/de-amp/test-small-amp.html`
2. Page should be redirected to `brave.com`
3. Opened a few tabs
4. Close `brave.com` tab
5. Restore the tab
6. De-AMPed page loaded

![image](https://user-images.githubusercontent.com/34715963/165194159-272e6dc8-f4de-44d5-b928-a4f2899aa37d.png)
![image](https://user-images.githubusercontent.com/34715963/165194196-b68ad6a8-dc0b-41d4-8f0e-ab17331cf06a.png)
![image](https://user-images.githubusercontent.com/34715963/165194223-0e8c7883-b9aa-4e19-8363-f54268a84438.png)
![image](https://user-images.githubusercontent.com/34715963/165194382-27802b8c-db17-45bd-9fc8-5ff6bb65fb1f.png)


</details>

<summary>Testcase 10: Verified de-AMPing works well with small pages < 64 K works expected</summary>
<details>

1. Visit `https://shivankaul.com/brave/de-amp/test-small-amp.html`
2. `De-AMPing` worked  i.e AMP page is redirected to `brave.com`

![image](https://user-images.githubusercontent.com/34715963/165194438-9761f0b6-8a52-4d8b-97cd-0e6402dfe213.png)


</details>

<summary>Testcase 11: Verified large AMP page (> 64K) works as expected</summary>
<details>

1. Visit `https://www.buzzfeed.com/amphtml/ryanschocket2/snl-spoofs-will-smith-chris-rock-slap`
2. `De-AMP ing` worked i.e AMP page is redirected to `https://www.buzzfeed.com/ryanschocket2/snl-spoofs-will-smith-chris-rock-slap`
3. The markup was verified in Testcase 1 for the above AMP page has canonical link to `https://www.buzzfeed.com/ryanschocket2/snl-spoofs-will-smith-chris-rock-slap`

![image](https://user-images.githubusercontent.com/34715963/165194480-5d530373-335a-4f04-aac0-569c74e5b153.png)


</details>

<summary>Testcase 12: Verified de-AMPing will not work with Auto-redirect AMP pages ON and de-AMPing feature flag ON (default)</summary>
<details>

1. Disable `Auto-redirect AMP pages`in`brave://settings/privacy`
2. Keep `Enable De-AMP` flag as a default in `brave://flags/#brave-de-amp`
4. Visit AMP page `https://shivankaul.com/brave/de-amp/test-small-amp.html`
5. Page is not redirected to `brave.com`

![image](https://user-images.githubusercontent.com/34715963/165194540-9313598b-97a4-4883-a9fa-f63720191786.png)
![image](https://user-images.githubusercontent.com/34715963/165194623-e53355da-e65e-4057-a5f6-88d18527d4e0.png)


</details>

<summary>Testcase 13: Verified de-AMPing will not work with Auto-redirect AMP pages ON and de-AMPing feature flag OFF</summary>
<details>

1. Enable`Auto-redirect AMP pages`in`brave://settings/privacy`
2. Disable `Enable De-AMP` flag in `brave://flags/#brave-de-amp`
4. Visit AMP page `https://shivankaul.com/brave/de-amp/test-small-amp.html`
5. Page is not redirected to `brave.com`

![image](https://user-images.githubusercontent.com/34715963/165194697-45cf12c7-f247-44be-9849-f0318c962e2e.png)
![image](https://user-images.githubusercontent.com/34715963/165194706-2e755c50-0cbe-4968-bbe3-e0583e597b00.png)
![image](https://user-images.githubusercontent.com/34715963/165195066-6891350f-d0ac-44da-8e61-ad904e14c365.png)


</details>
