### ISSUE TITLE
Remove FindX from list of search providers

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#2047]
[FindX is shutting down.](https://privacore.github.io/) Search already doesn't work.

It should be removed from the list of built-in search engines.

**Comment by mkarolin** [comment]
For the upgrade scenario, if the engine was not set as the default it will get removed on upgrade. If, however, FindX was set as the default search engine, it wouldn't be removed on upgrade and will stay on the list until removed manually. Assuming it's not a concern since the engine has already been shut down, so most/all of those who had it set as the default would have changed to a different default by now.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta(64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Mac OS X

* Verified test plan in https://github.com/brave/brave-core/pull/907
