### ISSUE TITLE
Brave now no longer allow users to remove or delete default search engines

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#20530]
Browsers based on Chromium will no longer allow users to delete default search engines (that comes with default installation) from the settings.

brave://settings/searchEngines

![brave_search](https://user-images.githubusercontent.com/46480489/149784296-26bd066a-9cfa-4e38-8021-e3c2f28f6651.png)

https://bugs.chromium.org/p/chromium/issues/detail?id=1263679

Brave: 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
Revision: adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS: Windows 10 Version 21H1 (Build 19043.1466)

**Comment by rebron** [comment]
Closing as invalid. Brave has always allowed users to remove or delete search engines from the default list. In the screenshot you showed, you have to chose a different default search engine before deleting the entry. Otherwise, we would need to guess what search engine you would want instead.

The chromium bug cited was never fixed and looks like the solution in the bug is going to turn into a confirmation dialog versus disabling deleting of search engines in the defaulted list.

**Comment by rebron** [comment]
@manikandancode Thanks for filing. It was good to see how they were thinking about fixing `https://bugs.chromium.org/p/chromium/issues/detail?id=1263679`
