### ISSUE TITLE
Send P3A json metric names as strings

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#20548]
## Description 

It's more transparent to send P3A metrics as strings instead of hashes, now that we're going with json for the reporting format and no longer concerned about length. This will introduce more variance into the packet lengths, but we weren't controlling that previously.

Follow-up to #15967

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.36.87 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1503)

```

**Comment by GeetaSarvadnya** [comment]
@rillian @porteron  P3A wiki has `41 metrics` and the brave://local-state file is showing up `33 metrics` and I could see 37 requests for p3a.brave.com and p3a.json.brave.com endpoints in Charles, sometimes if I wait for a long time around 2 hours or so. Is there a specific time to see all the metrics? 

Also, could you please review case 2 (Update the metric status at the client-side and verify metrics response value is updated in Charles) and let me know if this is the right way to test the updated response value received from the server-side?

**Comment by Uni-verse** [comment]
Verification IN-PROGRESS on Samsung Galaxy S21 / Android 12 using 1.36.93, Chromium 98.0.4758.87


- Verified the test plan from https://github.com/brave/brave-core/pull/11888
- Confirmed that packets to the https://p3a-json.brave.com/ endpoint have a metric_name key instead of a metric_hash key
- Confirmed that response value for each metric is a human-readable string matching with the P3A wiki metrics and response values

![p3a_brave_com](https://user-images.githubusercontent.com/17885425/153970577-b2111b51-6d2e-46bf-832a-b35be9d340b7.png)

<details>
<summary>1. Brave.Core.BookmarksCountOnProfileLoad.2</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![BookmarksCountOnProfileLoad](https://user-images.githubusercontent.com/17885425/153969814-2e4404f5-2fc4-4da2-9a4b-e4392a3be31b.png)

</details>

<details>
<summary>2. Brave.Search.DefaultEngine.4</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![brave_search_defaultEngine](https://user-images.githubusercontent.com/17885425/153969856-8009b5ae-a2a7-4109-b538-2a229f17b719.png)

</details>

<details>
<summary>3. Brave.IPFS.GatewaySetting</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![IPFS_GatewaySettings](https://user-images.githubusercontent.com/17885425/153969866-f9a54cff-bd79-46bd-aa9a-f323e33b98f0.png)

</details>

<details>
<summary>4. Brave.NTP.CustomizeUsageStatus</summary>

N/A 

brave://local-state | metrics_name with value
----|------

</details>

<details>
<summary>5. Brave.Core.NumberOfExtensions</summary>

N/A 

brave://local-state | metrics_name with value
----|------


</details>

<details>
<summary>6. Brave.Core.TorEverUsed</summary>

N/A

brave://local-state | metrics_name with value
----|------


</details>

<details>
<summary>7. Brave.Core.WindowCount.2</summary>

N/A

brave://local-state | metrics_name with value
----|------


</details>

<details>
<summary>8. Brave.Core.CrashReportsEnabled</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![CrashReportsEnabled](https://user-images.githubusercontent.com/17885425/153970026-ab2e3dc7-36f9-4249-850e-ee4828d9ff89.png)

</details>

<details>
<summary>9. Brave.Wallet.UsageDaily</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![walletUsageDaily](https://user-images.githubusercontent.com/17885425/153969952-16f5e42e-4da9-4271-8eb7-69c01522ab27.png)


</details>

<details>
<summary>10. Brave.Shields.UsageStatus</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![ShieldsUsageStatus](https://user-images.githubusercontent.com/17885425/153970014-3ba561b2-5e3b-4d12-bc49-4cfd49de93bf.png)

</details>

<details>
<summary>11. Brave.Search.SwitchEngine</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![SwitchEngine](https://user-images.githubusercontent.com/17885425/153971365-f6216651-949d-4d27-9b59-1434c6d622aa.png)

</details>

<details>
<summary>12. Brave.Wallet.UsageMonthly</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![WalletUsageMonthly](https://user-images.githubusercontent.com/17885425/153970081-09b572d3-321b-473f-9251-da5d8a470fb8.png)

</details>

<details>
<summary>13. Brave.Wallet.UsageWeekly</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![Wallet_weeklyusage](https://user-images.githubusercontent.com/17885425/153970098-090f8336-2dd3-40b2-80a8-80bfe9d87e39.png)

</details>

<details>
<summary>14. Brave.Wallet.UsageWeekly</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
Dup*
</details>

<details>
<summary>15. Brave.Welcome.InteractionStatus</summary>

N/A 

brave://local-state | metrics_name with value
----|------


</details>

<details>
<summary>16. Brave.Rewards.AutoContributionsState.2</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![AutoContributionsState](https://user-images.githubusercontent.com/17885425/153970353-4f4a4639-1339-4d90-9750-a7f589c0a0d8.png)

</details>

<details>
<summary>17. Brave.Rewards.WalletBalance</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![Rewards_WalletBalance](https://user-images.githubusercontent.com/17885425/153970136-3b920c8b-e7a4-4e67-926e-d9c5b07eedba.png)

</details>

<details>
<summary>18. Brave.NTP.SponsoredImagesEnabled</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![NTP_SponsoredImagesEnabled](https://user-images.githubusercontent.com/17885425/153970336-b39ae2dd-e502-47d0-934e-5ce01a9e3d56.png)

</details>

<details>
<summary>19. Brave.Uptime.BrowserOpenMinutes</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------


</details>

<details>
<summary>20. Brave.NTP.NewTabsCreated</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------

</details>

<details>
<summary>21. Brave.Rewards.TipsState.2</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![Rewards_TipsState](https://user-images.githubusercontent.com/17885425/153970190-c497a61d-19af-41d9-b775-963d887f460d.png)


</details>

<details>
<summary>22. Brave.IPFS.IPFSCompanionInstalled</summary>

N/A

brave://local-state | metrics_name with value
----|------


</details>

<details>
<summary>23. Brave.Omnibox.SearchCount</summary>

N/A

brave://local-state | metrics_name with value
----|------

</details>

<details>
<summary>24. Brave.P3A.SentAnswersCount</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------


</details>

<details>
<summary>25. Brave.Core.LastTimeIncognitoUsed</summary>

N/A

brave://local-state | metrics_name with value
----|------


</details>

<details>
<summary>26. Brave.Rewards.EnabledDuration</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------

</details>

<details>
<summary>27. Brave.Core.TabCount</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![TabCount](https://user-images.githubusercontent.com/17885425/153971706-3b4bd478-8872-43ff-95cb-f5ec82a8938e.png)

</details>

<details>
<summary>28. Brave.Rewards.AdsState.2</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![rewards_adState](https://user-images.githubusercontent.com/17885425/153971686-e6f8e1d8-a3db-4722-bb30-ed2fc48de332.png)

</details>

<details>
<summary>29. Brave.IPFS.DetectionPromptCount</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![IPFS_DetectionPromptCount](https://user-images.githubusercontent.com/17885425/153970319-bd75557c-e322-4846-a01f-33c7cf3f81fa.png)

</details>

<details>
<summary>30. Brave.Rewards.WalletState</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![WalletState](https://user-images.githubusercontent.com/17885425/153971449-22c22808-2aa5-40e8-9827-590ccc866c3b.png)

</details>

<details>
<summary>31. Brave.Sync.Status</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------
![SyncStatus](https://user-images.githubusercontent.com/17885425/153971471-c0837e35-0984-4b16-8d92-2b0475883a47.png)

</details>

<details>
<summary>32. Brave.NTP.SponsoredNewTabsCreated</summary>

- Confirmed metric_name is in the form of a human-readable string
- Confirmed response value of the metrics is the same as the local-state metrics response value

brave://local-state | metrics_name with value
----|------

![NTP_SponsoredNewTabsCreated](https://user-images.githubusercontent.com/17885425/153970289-baa5be22-0867-4116-ab4a-0881cec99dee.png)

</details>

<details>
<summary>33. Brave.Importer.ImporterSource</summary>

N/A

brave://local-state | metrics_name with value
----|------
</details>

**Comment by rillian** [comment]
> @rillian @porteron P3A wiki has `41 metrics` and the brave://local-state file is showing up `33 metrics` sometimes I could see `37 metrics` requests for p3a.brave.com and p3a.json.brave.com endpoints in Charles if I wait for a long time around 2 hours or so. Is there a specific time to see all the metrics?

There's no specific time to wait. It's interesting to hear some don't show after more than two hours, but I am also not surprised. Some metrics may only be recorded when specific actions are taken. The nightly profile I use regularly shows 42 metrics in brave://local-state, all marked as sent.

Every recorded metric is sent the same way, so I don't think it's important to exhaustively verify every possible measurement. If a reasonable number are all sent correctly over the first ~10 minutes that's sufficient for testing this change.

> Also, could you please review case 2 (Update the metric status at the client-side and verify metrics response value is updated in Charles) and let me know if this is the right way to test the updated response value received from the server-side?

Seems like that should work. I don't think you need to wait for the clock rollover past midnight in case 2, steps 11-12. If the browser is not running it will not notice the difference and will still begin sending fresh data once if it's started some time past midnight regardless.

Have you seen the 1-minute delay make a difference in the past?

**Comment by GeetaSarvadnya** [comment]
@rillian Thanks for the clarification on metrics!

Reg, case2 Yes, I did see the difference after forwarding the clock. I forwarded the clock to 1 week ahead i.e on Monday, because metrics responses are sent to the server every Monday. The response value in Charles was not getting updated before clock the forward, once I move the clock to next Monday, the updated response from the server is sent to Charles and I could see the updated response in Charles as expected. The clock forward is done only to test whether the updated response is sent from the server to Charles.
