### ISSUE TITLE
Change DNSLink url resolution to <gateway>/ipns/<dnslink-domain>

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#20567]
Check when both redirect options are enabled in Brave – https://docs.ipfs.io/?foo=bar redirects to https://bafybeifpyppkishqjofl6ahn6ky7udxuo5gn7s7fuzegrncfkm2ltevac4.ipfs.dweb.link/ instead of https://docs-ipfs-io.ipns.dweb.link/?foo=bar – Automatically redirect to IPFS pages via DNSLink when possible" should have precedence over "Redirect IPFS resources to the configured IPFS gateway", but it looks like it is the other way

**Update:** Currently we take value from DNSLink header and resolve it to urls like  `/ipfs/{cid}/path → ipfs://{cid}/path`. Brave should not resolve DNSlink in address bar – it is losing human-readable name and it is replacing permanent address with CID of a snapshot in time – not what users want.

Brave should only check if a valid DNSLink is present, and redirect to <gateway>/ipns/<dnslink-domain>

**Comment by markg85** [comment]
That looks weird to me.
Shouldn't:
`https://docs.ipfs.io/?foo=bar`
redirect to:
`https://bafybeifpyppkishqjofl6ahn6ky7udxuo5gn7s7fuzegrncfkm2ltevac4.ipfs.dweb.link/?foo=bar`
as opposed to what you said:
`https://bafybeifpyppkishqjofl6ahn6ky7udxuo5gn7s7fuzegrncfkm2ltevac4.ipfs.dweb.link/`

I do agree that it should not redirect to `https://docs-ipfs-io.ipns.dweb.link/?foo=bar`

But imho the query parameters should **always** be preserved.
Note that in the issue i made under #18367 (and fixed by https://github.com/brave/brave-core/pull/10694) that my very example url's are backed by DNSLink. So if the pull request fixes **exactly**  my reported issue then it does what i'm stating above with the redirects (aka, it redirects to `https://bafybeifpyppkishqjofl6ahn6ky7udxuo5gn7s7fuzegrncfkm2ltevac4.ipfs.dweb.link/?foo=bar`). But i'm not able to test a brave build to confirm this.

Anyhow, we have some assumptions here so if you could provide some clarity on your case?

**Comment by lidel** [comment]
@markg85 the  bug discussed here was detected in version of Brave before fix from https://github.com/brave/brave-core/pull/10694), which is why bug report uses URL without params.
You are correct, query parameters should always be preserved.

**Comment by spylogsster** [comment]
as discussed in slack with @lidel:
```
Brave should not resolve DNSlink in address bar – it is losing human-readable name and it is replacing permanent address with CID of a snapshot in time – not what users want.
- if someone bookmarks or shares the resolved address, they won't see future updates of the website
- /ipns/ is for mutable pointers, and user agent like Brave should keep them in GUI, inless user requests CID of the snapshot frozen in time
Brave should only check if a valid DNSLink is present, and redirect to <gateway>/ipns/<dnslink-domain>
- in case above, it should redirect to https://dweb.link/ipns/docs.ipfs.io (it is up to Gateway to verify CID, and redirect to URL-safe subdomain.
```

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.37.23 Chromium: 98.0.4758.87 (Official Build) nightly (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1466)

Steps:
1. fresh profile
2. loaded `http://docs.ipfs.io`
3. loaded `brave://settings/ipfs`
4. set `Method to resolve IPFS resources` to `Gateway`
5. toggled both `Redirect IPFS resources to the configured IPFS gateway` and `Automatically redirect to IPFS pages via DNSLink when possible` to `ON` 
6. reloaded the tab with `https://docs.ipfs.io` in the URL bar
7. waited for the redirect

 
Confirmed I was redirected to `https://docs-ipfs-io.ipns.dweb.link/`.


example | example | example
----------|-----------|----------
![20567-1](https://user-images.githubusercontent.com/387249/152501388-51c666cb-83ac-4850-b1aa-ae3bb3fd2c0a.png) | ![20567-2](https://user-images.githubusercontent.com/387249/152501415-4032fda1-8dfc-43b7-aac7-44a8ed37af4c.png) | ![20567-3](https://user-images.githubusercontent.com/387249/152501437-8d924237-8042-42e7-b6e2-582970a4715d.png)
