### ISSUE TITLE
Needed NFT Metadata API from Etherscan or Opensea

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#20604]
## Description 
Consider the best option for querying NFT meta data, either by `Etherscan` or `Opensea`

Needed information:
`Floor Price`: Average Value
`Project Name`: Name of the project/collection
`Project Logo`: Logo of the project/collection
`Projects Social Info`: Twitter, Facebook, Website
`Projects Description` Description of the project/collection
`Tokens URI`: The ERC721's unique image based on `contractAddress` and `tokenId`

![Screen Shot 2022-01-20 at 9 45 59 PM](https://user-images.githubusercontent.com/40611140/150467439-22d4c84f-00d2-47b2-bf5d-767c131f72e0.png)

Etherscan:

We currently have a method `getTokenInfo` that is able to return basic token info

example:
``
"payload": { "status": "1", "message": "OK", "result": [{ "contractAddress": "0xc3f733ca98e0dad0386979eb96fb1722a1a05e69", "tokenName": "Acclimated​MoonCats", "symbol": "😺", "divisor": "0", "tokenType": "ERC721", "totalSupply": "18625", "blueCheckmark": "true", "description": "After a whirlwind adventure four years in the making the MoonCats have been rescued and are acclimating to their life on the blockchain.", "website": "https://mooncat.community/", "email": "", "blog": "", "reddit": "", "slack": "", "facebook": "", "twitter": "https://twitter.com/ponderware", "bitcointalk": "", "github": "", "telegram": "", "wechat": "", "linkedin": "", "discord": "https://discord.com/invite/7c7HDAdt2S", "whitepaper": "", "tokenPriceUSD": "0.000000000000000000" }] }, "lastUpdated": "2022-01-11T18:18:06.189Z
``

What we are missing is 
`Project Logo`: Logo of the project/collection
`Tokens URI`: The ERC721's unique image based on `contractAddress` and `tokenId`

There are ways to query `Token URI`'s with `Etherscan`
example: https://etherscan.io/token/0xc3f733ca98e0dad0386979eb96fb1722a1a05e69?a=0x73A29A1da97149722eB09c526E4eAd698895bDCf#readContract

Downsides: 
It is not always accurate and sometimes returns another api that we would then need to parse individually per project.
We are limited to `Ethereum`

Opensea:

Opensea's api will return all need information 

example: https://api.opensea.io/api/v1/asset/0xc3f733ca98e0dad0386979eb96fb1722a1a05e69/17061/

**Comment by nvonpentz** [comment]
Talked with @Douglashdaniel about this.
* We can use the RPC API instead of Etherscan so we don't need to add another API.  It also supports more EVM chains. However it shares some of the downsides of Etherscan, namely the challenges with non standard tokenURI responses (more on that later) and the inability to get the project logo (I think those are uploaded to OpenSea directly and are not available on chain generally).
* It's not clear whether the OpenSea API supports other EVM chains.  I couldn't find anything on their [docs](https://docs.opensea.io/reference/getting-assets) that suggest they do.  Some people have raised this in an [issue](https://github.com/ProjectOpenSea/opensea-js/issues/72) and the discussion suggests there may be some undocumented functionality, but I haven't tested.

If we use the RPC API and call tokenURI on contracts directly, we will need to parse the results (which have varied formats) to get the resource (which also have varied formats).  These are some tokenURI responses that I know of
* JSON blob with image property that is either an IPFS or HTTP URL
* IPFS or HTTP URL that leads to the JSON blob (e.g. [Bored Apes](https://etherscan.io/address/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d#readContract) or [InvisibleFriends](https://etherscan.io/address/0x59468516a8259058bad1ca5f8f4bff190d30e066#readContract))
* Base64 encoded JSON, that when decoded has a field called image that is itself base64 encoded SVG URI (e.g [Shields](https://etherscan.io/address/0x0747118c9f44c7a23365b2476dcd05e03114c747#readContract))

And I'm sure there are many combinations of the above.

I should also note that there are NFTs that rely on the `animation_url` property that OpenSea [supports](https://docs.opensea.io/docs/metadata-standards).  Those can be videos of various formats, or even HTML documents complete with javascript.
