### ISSUE TITLE
"Disconnect from {{custodian}}" text shows `$1` string and is not being interpolated in Rewards panel

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#20661]
![image](https://user-images.githubusercontent.com/11497541/150876943-26a32a61-3765-4951-81a2-408a5ad948aa.png)

@A-t-s-u-s-h-i

**Comment by emerick** [comment]
Is this nightly?

**Comment by emerick** [comment]
This is happening because the original string was `Disconnect from Brave Rewards` (with no substitutions) and the new string is `Disconnect from $1` (with a substitution for the provider name).

The release version of Brave received the updated strings when l10n was uplifted from `master`, but it doesn't have the code to handle the provider name substitution.

cc: @Miyayes Let me know if you want to uplift the associated code. Alternatively, it is fixed in nightly and will ride the trains shortly.

**Comment by Miyayes** [comment]
Resolved in 1.35.

**Comment by stephendonner** [comment]
This is what I see in `1.36.75`

BAT icon | `brave://rewards`
---------|---------
<img width="1312" alt="スクリーンショット 2022-01-27 15 14 18" src="https://user-images.githubusercontent.com/387249/151458998-1a5f306a-9d9b-4576-b52a-6f90b4f71e61.png"> | <img width="1312" alt="スクリーンショット 2022-01-27 15 14 29" src="https://user-images.githubusercontent.com/387249/151459069-25f6774b-f9da-47e1-b268-b99724e08b4d.png">

@emerick what are the differences in strings here between the BAT icon and the `brave://rewards` page?
