### ISSUE TITLE
Fix building dist on MacOS on 1.35.x branch.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#20756]
https://github.com/brave/brave-core/pull/11919 uplift from https://github.com/brave/brave-core/pull/11838 has an extra condition that's not supposed to be there.

**Comment by goodov** [comment]
Because https://github.com/brave/brave-core/pull/11549 was not uplifted to `1.35.x`, I had to change the code to not skip dSYMs when signing is off thinking that our true `release` builds has always-enabled signing flag, but as turned out, `npm run build` skips signing, but `npm run create_dist` doesn't skip it (both of these are done in the same build process).
