### ISSUE TITLE
Add new Brave Talk Calendar Scheduling extension to the safe extension list

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#20826]
## Description 
The newly built Brave Talk scheduling extension should be added to the safe extension list, because our security teams have independently vetted our code.

https://chrome.google.com/webstore/detail/brave-talk-for-google-cal/nimfmkdcckklbkhjjkmbjfcpaiifgamg

id: nimfmkdcckklbkhjjkmbjfcpaiifgamg
description: Brave Talk for Google Calendar

https://github.com/brave/extension-whitelist/blob/master/data/whitelist.json

**Comment by fmarier** [comment]
I'd suggest fixing a few quick things on the [Chrome Store page](https://chrome.google.com/webstore/detail/brave-talk-for-google-cal/nimfmkdcckklbkhjjkmbjfcpaiifgamg) (or in the manifest) before we make this more public than it already is:

- *Contact the developer* is currently gtackley@brave.com and it should probably be an alias like brave-talk-extension@brave.com or something similar.
- *Website* links to <https://brave.com/talk/> whereas it should probably link to <https://github.com/brave/brave-talk-gcalendar-extension> so that people can more easily file issues. (I do see that the link to the source code is in the description already, but it's not clickable there.)

Also, the *Overview* currently says:
> The source code for this extension can be found at https://github.com/brave/brave-talk-gcalendar-extension.

and I was thinking we may as well advertise the fact that it's Open Source:
> This extension is Open Source and the source code can be found at https://github.com/brave/brave-talk-gcalendar-extension.

**Comment by tackley** [comment]
Thanks for the store listing suggestions @fmarier!

1. I'm working on updating the email to chrome-web-store-developers@brave.com - we need to update that group to be able to receive external emails first, once that's done I'll complete the verification step to update.
2. Website and overview updated as you suggest. The changes will be live once the google review is completed. I've also raised https://github.com/brave/brave-talk-gcalendar-extension/pull/7 to update the readme to make the github repo a better dropping off point.
3. The icon uploaded to the webstore _is_ transparent. Is the white background coming from somewhere else?

**Comment by fmarier** [comment]
> The icon uploaded to the webstore is transparent. Is the white background coming from somewhere else?

Good question, I'd have to look at the code to figure it out. Maybe @petemill already knows.

**Comment by fmarier** [comment]
As of Brave Local Data Updater - Version: 1.0.62, the warning is gone:
![Screenshot from 2022-02-03 16-24-21](https://user-images.githubusercontent.com/167821/152451614-7348eac4-a5c0-4676-a8eb-714881338fe9.png)

**Comment by fmarier** [comment]
This is now done. Follow-up work at:

- https://github.com/brave/brave-talk-gcalendar-extension/issues/8
- https://github.com/brave/extension-whitelist/pull/47
