### ISSUE TITLE
Fix monthly/weekly wallet P3A

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#21063]
## Description 
The current P3A questions for wallet usage (`Brave.Wallet.UsageDaily`, `Brave.Wallet.UsageWeekly`, `Brave.Wallet.UsageMonthly`) must be replaced with new questions: `Brave.Wallet.UsageMonthly.2` and `Brave.Wallet.UsageDaysInWeek`.

`UsageMonthly` is set to true if the wallet has been used in the current month. If the user opens the wallet for the first time in the middle of the month, P3A could transmit two weeks of `UsageMonthly=0` reports and two weeks of `UsageMonthly=1` reports. This makes it difficult to approximate MAU, if MAU is calculated by dividing the total amount of `UsageMonthly=1` reports by four weeks. `Brave.Wallet.UsageMonthly.2` will be set to true if the wallet has been used in the previous month. This will ensure four weeks of P3A reports with the same value.

`UsageDaily` is set to true if the wallet has been used during the current day. Since P3A reports are sent once per week, only wallet usages during the day of the P3A report will be reported. `Brave.Wallet.UsageDaysInWeek` will report the number of days the wallet has been used within the past 7 days. Since WAU can be inferred by this new question, `UsageWeekly` can be removed. Reports for this question will not be sent less than one week from the first run of the browser.

## Desktop Brave version:
Building from source.

Brave: 1.37.30 Chromium: 98.0.4758.87 (Developer Build) (64-bit)
Revision: e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758
OS: Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:

Will raise PR soon.

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/20956#issuecomment-1055919713, this should be checked alongside https://github.com/brave/brave-browser/issues/20956 using `1.36.109` or higher.

We'll be running through a subset of the cases as this was already thoroughly verified/QA'd via `1.38.x`.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Windows 10 Version 21H2 (Build 19044.1526)


```

**Comment by srirambv** [comment]
Verification partially passed on Samsung Tab A with Android 10 running 1.36.109 x64 build
- Verified test plan from [brave/brave-core#12277](https://github.com/brave/brave-core/pull/12277)
- Logged follow up issue []()for `Brave.Wallet.UsageDaysInWeek=0` & `Brave.Wallet.UsageMonthly.2=0`

<details>
<summary>Case 1: <code>Brave.Wallet.UsageDaysInWeek=0</code> - <b>Failed</b></summary>
<br>

- Set device date to March 1st
- Clean install and enable walelt
- Move device date ahead by 1 week
- Relaunch browser and check local-state, doesn't list `Brave.Wallet.UsageDaysInWeek`
- Quit browser and move device date ahead by 1 day
- Relaunch browser and check local-state, shows `Brave.Wallet.UsageDaysInWeek=1`
- Quit browser and move device date ahead to next Monday
- Relaunch browser and check local-state, still shows `Brave.Wallet.UsageDaysInWeek=1`
- Quit browser and move device date ahead to next Tuesday
- Relaunch browser and check local-state, still shows `Brave.Wallet.UsageDaysInWeek=1` instead of `Brave.Wallet.UsageDaysInWeek=0` when there was no wallet usage in the past week for any day

</details>

<details>
<summary>Case 2: <code>Brave.Wallet.UsageDaysInWeek=1</code> - <b>Passed</b></summary>
<br>

- Set device date to February 28th 
- Clean install and enabled wallet
- Moved device date ahead to March 1
- Launch browser and unlock wallet
- Verified local-state has the value `Brave.Wallet.UsageDaysInWeek=1`
![image](https://user-images.githubusercontent.com/17010094/156581904-de2d1cdf-88e4-4868-a9bf-6e75bf68b999.png)

</details>

<details>
<summary>Case 3: <code>Brave.Wallet.UsageDaysInWeek=2</code> - <b>Passed</b></summary>
<br>

- Set device date to February 28th 
- Clean install and enabled wallet
- Moved device date ahead to March 1
- Launch browser and unlock wallet
- Moved device date ahead to March 2
- Launch browser and unlock wallet
- Verified local-state has the value `Brave.Wallet.UsageDaysInWeek=2`
![image](https://user-images.githubusercontent.com/17010094/156581929-79a508a7-ab9f-412e-9a5f-a9a8f5d62287.png)

</details>

<details>
<summary>Case 4: <code>Brave.Wallet.UsageDaysInWeek=3</code> - <b>Passed</b></summary>
<br>

- Set device date to February 28th 
- Clean install and enabled wallet
- Moved device date ahead to March 1
- Launch browser and unlock wallet
- Moved device date ahead to March 2
- Launch browser and unlock wallet
- Moved device date ahead to March 3
- Launch browser and unlock wallet
- Verified local-state has the value `Brave.Wallet.UsageDaysInWeek=3`
![image](https://user-images.githubusercontent.com/17010094/156581952-f20bedba-703e-4caf-91a5-b8cea7ed96b4.png)

</details>

<details>
<summary>Case 5: <code>Brave.Wallet.UsageDaysInWeek=4</code> - <b>Passed</b></summary>
<br>

- Set device date to February 28th 
- Clean install and enabled wallet
- Moved device date ahead to March 1
- Launch browser and unlock wallet
- Moved device date ahead to March 2
- Launch browser and unlock wallet
- Moved device date ahead to March 3
- Launch browser and unlock wallet
- Moved device date ahead to March 4
- Launch browser and unlock wallet
- Verified local-state has the value `Brave.Wallet.UsageDaysInWeek=4`
![image](https://user-images.githubusercontent.com/17010094/156581972-893be87e-dc15-48d4-a9c4-ebe133e708c8.png)

</details>

<details>
<summary>Case 6: <code>Brave.Wallet.UsageDaysInWeek=5</code> - <b>Passed</b></summary>
<br>

- Set device date to February 28th 
- Clean install and enabled wallet
- Moved device date ahead to March 1
- Launch browser and unlock wallet
- Moved device date ahead to March 2
- Launch browser and unlock wallet
- Moved device date ahead to March 3
- Launch browser and unlock wallet
- Moved device date ahead to March 4
- Launch browser and unlock wallet
- Moved device date ahead to March 5
- Launch browser and unlock wallet
- Verified local-state has the value `Brave.Wallet.UsageDaysInWeek=5`
![image](https://user-images.githubusercontent.com/17010094/156581992-02a7c6a6-d98d-4fb2-9463-460dc766b602.png)

</details>

<details>
<summary>Case 7: <code>Brave.Wallet.UsageDaysInWeek=6</code> - <b>Passed</b></summary>
<br>

- Set device date to February 28th 
- Clean install and enabled wallet
- Moved device date ahead to March 1
- Launch browser and unlock wallet
- Moved device date ahead to March 2
- Launch browser and unlock wallet
- Moved device date ahead to March 3
- Launch browser and unlock wallet
- Moved device date ahead to March 4
- Launch browser and unlock wallet
- Moved device date ahead to March 5
- Launch browser and unlock wallet
- Moved device date ahead to March 6
- Launch browser and unlock wallet
- Verified local-state has the value `Brave.Wallet.UsageDaysInWeek=6`
![image](https://user-images.githubusercontent.com/17010094/156582014-b0ad0108-2f77-4f25-a79d-9b78ee2a2b06.png)

</details>

<details>
<summary>Case 8: <code>Brave.Wallet.UsageDaysInWeek=7</code> - <b>Passed</b></summary>
<br>

- Set device date to February 28th 
- Clean install and enabled wallet
- Moved device date ahead to March 1
- Launch browser and unlock wallet
- Moved device date ahead to March 2
- Launch browser and unlock wallet
- Moved device date ahead to March 3
- Launch browser and unlock wallet
- Moved device date ahead to March 4
- Launch browser and unlock wallet
- Moved device date ahead to March 5
- Launch browser and unlock wallet
- Moved device date ahead to March 6
- Launch browser and unlock wallet
- Moved device date ahead to March 7
- Launch browser and unlock wallet
- Verified local-state has the value `Brave.Wallet.UsageDaysInWeek=7`
![image](https://user-images.githubusercontent.com/17010094/156582030-1af4f535-0560-4320-b33d-027a60cb8e62.png)

</details>

<details>
<summary>Case 9: <code>Brave.Wallet.UsageMonthly.2=0</code> - <b>Failed</b></summary>
<br>

- Set device date to March 1st
- Clean install and enable wallet
- Quit browser and move device date ahead by 1 month April 1st
- Relaunch browser
- Refresh local-state, shows `Brave.Wallet.UsageMonthly.2=1`
- Quit browser and move device date ahead by 1 month May 1st
- Relaunch browser
- Refresh local-state, still shows `Brave.Wallet.UsageMonthly.2=1` when it should update it to `Brave.Wallet.UsageMonthly.2=0`
- Quit browser and move device date ahead by a week to May 8th
- Relaunch browser
- Refresh local-state still shows `Brave.Wallet.UsageMonthly.2=1` instead of `Brave.Wallet.UsageMonthly.2=0`

</details>

<details>
<summary>Case 10: <code>Brave.Wallet.UsageMonthly.2=1</code> - <b>Passed</b></summary>
<br>

- Set device date to February 28th 
- Clean install and enabled wallet
- Moved device date ahead to March 1
- Launch browser and unlock wallet
- Verified local-state has the value `Brave.Wallet.UsageMonthly.2=1` 
![image](https://user-images.githubusercontent.com/17010094/156582194-92f37bd4-95f0-4ae2-91a0-5b09fcb90c17.png)

</details>
