### ISSUE TITLE
optional updates

### ISSUE THREAD

**Issue by tommycarstensen** [brave/brave-browser#211]
I was just forced to install the latest update and was unable to continue my browsing session before doing so. Could you please make the upgrades optional unless they are security updates? Thanks!

**Comment by srirambv** [comment]
You can follow the steps mentioned [here](https://github.com/brave/browser-laptop/issues/1877#issuecomment-390339713). This is applicable for browser-laptop and not on brave-browser.

**Comment by cbehan** [comment]
All of the discussions about auto-updating don't even define what that is.
1. I have brave installed to a directory that is only writeable by root.
2. Setuid bit on the brave executable is off.
3. I run brave as an unprivileged user which is how a browser should always be run.
Now you can't honestly tell me that Brave has a team working round the clock to find kernel exploits that allow updates to still be installed in the above setup. Updates must *already* be enabled only for specific use cases. Can you be please be transparent about what those are for the benefit of people like me who are considering switching to Brave? Thanks.

**Comment by bsclifton** [comment]
@cbehan the original post was by a user of the old Electron based browser (accidentally posted here instead of the `browser-laptop` repo)

For Linux, auto-updates aren't happening. You'll have to do this yourself via apt/rpm/dnf/etc

For other platforms, updates will happen. It may be possible to disable updates, but that is not something we support

All of this said, what exactly are you asking, @cbehan? (having trouble understanding what is the question or ask)

**Comment by cbehan** [comment]
I'm asking what the conditions are for Brave to download an update. You have answered much of the question by saying that on Linux it never will (regardless of how many privileges the user has).

But are there other checks besides the OS and CPU? Right now, I'm imagining a Windows or Mac user who compiles his or her own executable. Is Brave smart enough to detect that the compilation flags were not the official ones and that therefore this custom build should not be replaced by the Windows or Mac updates online?

I'm sure there is a better place for discussing this. But the concern is fundamental enough that it should probably be on one of the wiki pages.

**Comment by bsclifton** [comment]
@cbehan 
- compiled builds won't check for updates. 

- Updates on Windows or macOS require an official executable (release/beta/dev/nightly channel) and they know an update is present because a request is sent to Brave. Upon receiving the response, Brave will start to update itself... but requires the user to exit/relaunch (green icon shown in hamburger button, restart button also shown in chrome://settings/help) to finalize the process
