### ISSUE TITLE
Contribution notifications

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#2114]
1. 

Success notification is not working correctly.

2.  Add more detailed error notifications

- auto contribute table is empty
- not enough funds

**Comment by LaurenWags** [comment]
@NejcZdovc Test Plan in PR (https://github.com/brave/brave-core/pull/896) covers:
- Notification for successful tip
- Notification for unsuccessful auto-contribution (when there is not enough funds)

Per description above, with this issue should we also be testing the following?
- Notification for successful auto-contribution
- Notification for unsuccessful auto-contribution (when the auto-contribute table is empty)

cc @kjozwiak

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.57.8 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

* Verified notification for unsuccessful contribution (when there are not enough funds). Note, while a notification occurs, this notification does not match image in PR. Confirmed in slack that this is expected.
![screen shot 2018-11-29 at 2 01 57 pm](https://user-images.githubusercontent.com/28145373/49250183-3d3c6600-f3ec-11e8-99a1-93135bd44b31.png)

* Verified notification for successful contribution
![screen shot 2018-11-29 at 2 01 41 pm](https://user-images.githubusercontent.com/28145373/49250203-44fc0a80-f3ec-11e8-9bd1-eee8f0881958.png)

Logged these follow-up issues:
- No notification for successful tip: https://github.com/brave/brave-browser/issues/2275
- Per comment above (link), I’m unsure if this PR should cover a notification for unsuccessful contribution (when auto-contribute table is empty) since it was mentioned in original issue description. Anyhow, since no notification is generated, logged https://github.com/brave/brave-browser/issues/2294
