### ISSUE TITLE
Add RSS support for Brave News on Android

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#21272]
## Description 
Brave News should support custom sources from RSS feeds.
Original specs found here https://docs.google.com/document/d/1X9lA00zHa8pKol63i0O23LA4UcSHDYoagIOH2DqwljI/edit#heading=h.pu0c9s6h0f0z

## Steps to reproduce 

1. Go to Brave News settings and activate it
2.  Notice the Your Sources / Add source added to the list of preferences
3. ![Screenshot_20220223-120247](https://user-images.githubusercontent.com/5214149/155373655-4c65459d-1aeb-4c1a-8d44-ef1efedfdf13.png)
4.  Tap on Add source and type an Rss feed URL - ex. https://www.theguardian.com/uk/sport/rss
   For more feed examples you can search in the slack news channel if needed. There are some examples given there
 (has to be the exact feed, multiple feed support will be added in a different issue)
5. Hit Search and the feed should be added to the Your Sources section 
![Screenshot_20220223-122609](https://user-images.githubusercontent.com/5214149/155374277-128d0c11-571c-43de-9aea-66e2a7299c80.png)
6. Close the settings and hit the Load more content button that should be there
7. Scroll until you find a source having the publisher as Sport|The Guardian (in the example above), obviously smth similar in case of other sources (I had to scroll a bit for it to appear sometimes but it's usually there within the first 20 cards or so)
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by aman-m1** [comment]
In Nightly v1.38.6 Android 11 if I toggle off all the sources Brave News never completes loading/circle keeps spinning. And RSS feed from this site doesn't load- https://www.thehindu.com/rssfeeds/

**Comment by Uni-verse** [comment]
Verification in Progress..

Test Plan: 

- [ ] Add custom RSS source
- [ ] Add multiple sources
- [ ] Disable custom source from main settings
- [ ] Disable custom source in All Sources
- [ ] Disable source from Brave News context menu
- [ ] Reload Content Button appears after modifying sources
- [ ] Clicking on custom post loads source webpage
- [ ] Able to open custom post in New Tab via context menu
- [ ] Able to open custom post in Private Tab via context menu

**Comment by Uni-verse** [comment]
Verification in Progress using Night 1.38.53, Chromium 99.0.4844.74 on Samsung Galaxy Tab S7 running Android 11

Test Plan:

- [ ] Add custom RSS source
- [ ]  Add multiple sources
- [ ]  Disable custom source from main settings - https://github.com/brave/brave-browser/issues/21348
- [ ]  Disable custom source in All Sources
- [ ]  Disable source from Brave News context menu
- [ ]  Reload Content Button appears after modifying sources
- [ ]  Clicking on custom post loads source webpage
- [ ]  Able to open custom post in New Tab via context menu
- [ ]  Able to open custom post in Private Tab via context menu
- [ ]  Custom source shows via Brave news settings bar
- [ ]  Brave News Settings bar is displayed when scrolling - https://github.com/brave/brave-browser/issues/21725

Notes:
This issue is still observed - https://github.com/brave/brave-browser/issues/21272#issuecomment-1051926678
STR : Disable all sources and refresh news feed - https://github.com/brave/brave-browser/issues/21158

**Comment by Uni-verse** [comment]
@anthonypkeane We may want to triage some of these issues as they are pretty major for this feature in general. I will follow up in the weekly triage/planning meeting.

cc: @SergeyZhukovsky  @kjozwiak
