### ISSUE TITLE
IPFS badge should open native protocol scheme when  local node is used

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#21306]
## Problem

When IPFS resolution is set to "Brave local node", opening https://en.wikipedia-on-ipfs.org/wiki/Wikipedia/ show "IPFS" badge in address bar:

> ![2022-02-24_20-48](https://user-images.githubusercontent.com/157609/155596841-bfbf8d4f-f921-4b62-8a60-d5a930ed4497.png)

but clicking on it does not open `ipns://en.wikipedia-on-ipfs.org/wiki/Wikipedia/` 
it opens  `http://ipns://en.wikipedia-on-ipfs.org.ipns.localhost:48080/wiki/Wikipedia/` 

> ![2022-02-24_20-48_1](https://user-images.githubusercontent.com/157609/155597116-72d815df-2ba2-49ba-b999-d7e7978a4f5e.png)

## Expected bahavior

Brave should open native `ipfs://` or `ipns://`

In this specific case, it should open `ipns://en.wikipedia-on-ipfs.org/wiki/Wikipedia/`

## Other notes

Sounds like we tested "gateway" scenario, but did not check "local node" one when testing fix for https://github.com/brave/brave-browser/issues/20567

**Comment by BigLep** [comment]
Good catch @lidel .  Did you manually find this?  I realize this is a question for Brave, but is there a way to have an automated test for this or manual test in a Brave release checklist?

**Comment by lidel** [comment]
QA does manual verification before release (e.g. https://github.com/brave/brave-browser/issues/21462) 

afaik there is no way to automate addressbar checks like this one, right @stephendonner?

**Comment by srirambv** [comment]
@lidel this seems to be fixed (mostly) for the original steps with `Kubo 0.17.0`. Loading `https://en.wikipedia-on-ipfs.org/wiki/Wikipedia/` and clicking on the IPFS button loads `ipns://en.wikipedia-on-ipfs.org/wiki/Wikipedia/`, however https://github.com/brave/brave-browser/issues/21306#issuecomment-1058587291 also seems to work but fails to resolve both `ipfs://` or `ipns://`. Are we good to close this issue as fixed with Kubo update? 

https://user-images.githubusercontent.com/17010094/205680829-90ae7bf6-fc0f-4903-b2b3-e6ae802e6006.mov

**Comment by lidel** [comment]
`ipfs://{domain-name}` is invalid ([DNSLink](https://dnslink.dev/) works only with `ipns://`), so that last error is nothing weird.

Ok to close.
