### ISSUE TITLE
Bring back Card Tab Layout! (Non-grid tab layout)

### ISSUE THREAD

**Issue by gogodee** [brave/brave-browser#21556]
## Description 
The latest Brave update has followed google's footsteps and introduced yet another feature that many users despise and it's the grid layout.
Earlier you could have the card layout which is much more efficient when switching between tabs by disabling "Enable Tab Groups" in appearance settings but not anymore.

## Steps to reproduce 

   1. Just use the latest Brave Android update.

## Actual result 
![Screenshot_20220309-181045153](https://user-images.githubusercontent.com/62397838/157444449-4f3ea318-4cda-46dc-a118-8ee6918b91ae.jpg)
![Screenshot_20220309-181621660](https://user-images.githubusercontent.com/62397838/157444510-037c4393-1a51-42b4-9d1e-5998f247b262.jpg)

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes 
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version

1.36.111

**Comment by vlad2305m** [comment]
Solution: 
1. Download brave beta with chromium 98. This way play market will hopefully not sneak an autoupdate on you.
2. Endure pain of losing the session.

**Comment by CpazR** [comment]
Just wanted to echo this, as this view was the reason I dropped Chrome and moved to brave to begin with.

**Comment by stu-code** [comment]
I find this mode much easier to use than the tab grid layout. When I select the tab viewer on my phone, my hand is at the bottom of my phone. When the tab grid layout opens, all my tabs are on the top of my phone. 

Even if the tabs grew from the bottom, they'll still be hard to access at the top. It is also generally more difficult to select tabs opposite of where your hand is.

It is harder to use the grid layout overall. I do not recommend changing the layout from the previous version. It's something that, while old, works very effectively.

**Comment by jonathanray** [comment]
There is a feature flag in brave://flags named Tab Grid Layout but setting it to Disabled appears to have no effect.

![20220313_101906](https://user-images.githubusercontent.com/6164433/158066668-2d9b7cb1-21d1-4823-9199-887752e153dd.jpg)

**Comment by vlad2305m** [comment]
> Solution:
> 
> 1. Download brave (beta) with chromium 98.
https://github.com/brave/brave-browser/releases/tag/v1.36.104
https://github.com/brave/brave-browser/releases/tag/v1.35.104

Nothing else works because it was removed from chromium completely.

**Comment by gogodee** [comment]
> There is a feature flag in brave://flags named Tab Grid Layout but setting it to Disabled appears to have no effect.
> 
> ![20220313_101906](https://user-images.githubusercontent.com/6164433/158066668-2d9b7cb1-21d1-4823-9199-887752e153dd.jpg)

It didn't work sadly

**Comment by opr** [comment]
Please bring back the stacked view! The grid layout is difficult to use. Or at least please let the flags work to disable this feature.

**Comment by Taomyn** [comment]
This needs to come back, the grid view is dreadful

**Comment by LiteraryWho** [comment]
Is it necessary for me to make this complaint in multiple places?  No.

Am I going to do it anyway? Apparently.

**Comment by saythethingchief** [comment]
Yep, completely unnecessary and frustrating change. My face sunk when I opened Brave and saw that my tabs had been switched over to this cumbersome weird grid thing that Chrome shoved down our throats.

Please undo this.

**Comment by Extremezhazha** [comment]
Logged in to upvote this. This was indeed the primary reason I quit using chrome.

**Comment by tpbedford** [comment]
Agreed, removing the cascading card layout is an unwelcome regression and smacks of arrogance. Bring the option back, please.

**Comment by Relvees** [comment]
My dislike of the Tab Grid feature was the exact reason I opted to use brave browser over standard chrome

I appreciate that one of the main core devs feels this is technical debt as noted in #21005 (browser) and #12201 (core)

But could this not be readded as an unsupported opt-in fesrure instead?

**Comment by ianhealy91** [comment]
Like others, I have tried reverting to the stack view with flags but had no luck. If I'm forced to use the grid, I'll just switch browsers again. Please revert to giving us an option for stack view.

**Comment by A2-P2** [comment]
Adding my name to the list of people who are unhappy with the changes made to Tab Groups.

I have a large screened phone and this update makes Brave uncomfortable to use one-handed. I don’t normally have many tabs open and when they are grouped at the top of the screen, I am having to change grip as my thumbs just aren’t long enough to reach them.

Please fix the option to switch it off in flags or if they do insist on keeping Tab Groups, have an option to reverse the layout and the tabs gather at the bottom of the screen.

**Comment by DrWhargoul** [comment]
I signed up here just to note that the grid view is the reason I left chrome and started using brave. If brave is now going to take away the stacked view I will no longer use it.

**Comment by futurejohn** [comment]
Please bring back the classic tab cards, Brave. The new grid makes it more time consuming when scrolling through a lot of tabs because my eyes have to bounce left and right to read the tab name. Plus there isn't as much room for a description so it's even harder to tell what the tab is for.

**Comment by Paleogirl2003** [comment]
Please please please bring back the cards I hate the grid so much, it's harder to use especially one handed

**Comment by CallistoNTG** [comment]
I absolutely hate the grid-based design, which feels like it entirely missed the point of how a person like me uses tabs. I don't want to group tabs. I want to open tabs and be able to scroll down through them as I please. Preferably being able to see what is on the tab in the vertical card.

**Comment by small3687** [comment]
Adding myself to the list of people that left chrome over this garbage.

**Comment by Kafkas98** [comment]
My first ever comment on Github is to show support on this matter, I hate tab groups and want the option to turn them off and have cascade view back as an option.

**Comment by senthilvigneshkumar** [comment]
+1 for cascade view. -10000 for dump grid layout. Please bring back the cascade layout.

**Comment by NayamAmarshe** [comment]
I support this! If Brave wants to establish itself as a Chrome alternative that is better, they have to step away from UI decisions made by Google. If Brave can't do that, I don't think Brave will ever be able to distinguish themselves from all other Chromium clones. Uniqueness matters, At the very least Brave should handle its UI on its own.

**Comment by derekmorr** [comment]
@opr No, these comments do not contribute to the discussion. Github issues are not the appropriate forum for this. Typically, when this happens on GH issues, the admins lock the comments.

**Comment by bsclifton** [comment]
Thanks for the feedback folks - we're discussing internally. There unfortunately isn't just a flag and we'd need to keep and maintain a bunch of patches to keep this functionality (and each Chromium upgrade we'd need to maintain those patches)

We'll share once we have more information. Thanks for your patience

**Comment by milochristiansen** [comment]
I honestly don't care if it is "just a flag" or not. The new way sucks, has sucked for a long time. If Chrome jumps off a bridge must you as well? Revert the commits that removed it.

**Comment by bsclifton** [comment]
@milochristiansen well, the code was removed entirely with Chromium 99. We'll need to evaluate how difficult it would be to pull that code into our codebase. We'll keep folks updated as we discuss more

**Comment by Abscissa** [comment]
Tab grid is one of the biggest reasons I don't use Chrome. Forced, unwelcome UI changes is another reason. This is a deal-breaker for Brave for me. If I can't find an alternative browser that keeps the stack style, then in all honestly, I'd rather deal with the security risks of downgrading Brave and disabling updates. Usability is essential for anything I'm going to use.

**Comment by LiteraryWho** [comment]
@bsclifton I hope you guys can get it done.  An annoying UI change in Chrome is why I switched to Brave in the first place (possibly this one), and I don't like the irony at all.

**Comment by tuomastiainen** [comment]
Yeah, changes like this are truely horrible. Many people use their browsers so much that the UI is operated with muscle memory.

The core UI elements should not be moved around without very heavy justification. This happened once before with the bottom toolbar.

**Comment by Vizorous** [comment]
I think all of us can agree that deva behind chromium /chrome mobile versions aren't the best at making user and usability centric decisions. They somehow removed the bottom bar which is AMAZING and you guys retained it because it's much easier to use. It's as same as this, top two tabs are incredibly hard to reach even with two hand operation. Then with one hand operation, top two are impossible to reach and one side of the grid is really hard to reach again. Why can't developers understand how user unfriendly this design is? And the grid doesn't even show a lot of information about the tab. Please go back to the previous layout because this layout is just annoying and very hard to use. I myself am downgrading to a previous version and gonna hold fort there till you guys come to your senses

**Comment by robinvandernoord** [comment]
I agree, the choice for tab view should be with the users.

**Comment by Timcj123** [comment]
Yeah. This new layout sucks.

**Comment by AnthonyRossi1** [comment]
You know your users love stacked tabs and yet this..

**Comment by martinlanger90** [comment]
Saw that today in the morning. Instantly thought: No, not again this sh...

**Comment by TheEskir** [comment]
+1 from me.
This is one of the main reasons I dropped chrome like a hot potato. If it isn't fixable within a reasonable amount of effort, I might look towards going back to Firefox or even try Vivaldi.

**Comment by KHfailure** [comment]
Made an account just to agree with this.

Finding another browser until this returns.

Ttfn

**Comment by Vizorous** [comment]
Anyone who wants to downgrade without losing the data, you can use adb to install the previous version, I downgraded to v1.35.103. I'm not sure if its ok to put here how to do it with the code but basically just push the apk to **/data/local/tmp** folder. then install from there. Make sure to stop auto updates from Play store.

**Comment by dpippenger** [comment]
Please bring back cascade view.

**Comment by Boothy99** [comment]
Grid view is just horrid - minimalistic information on view (2 to 3 words in view from the title + ant writing) ; needs clumsy two-handed interaction on a phone to reach top tabs.

**Comment by milochristiansen** [comment]
I'm testing Kiwi browser right now as an alternative. It supports way more options *and* desktop extensions (*cough* UBlock Origin *cough*). Chances are, if Chrome removed a feature you liked in the recentish past Kiwi will have it.

I'm not 100% sure I'm going to like it enough to do a full switch, but right now it is looking awfully tempting.

**Comment by adrianoats** [comment]
Also hated... and I want to have the feeling they will realize that it was the wrong thing to do and provide ir back soon enough

**Comment by RowanSkie** [comment]
You know, whoever decided to do this for Chromium needs to get their eyes pulled out. Holy crap. 

People are aware that all mobile phones don't have the same screen size, right? And finger size.

Like, at this rate, sure Brave Browser has to reimplement and code all of it back, but at least you guys make a difference besides the built-in AdBlock and getting paid for ads via BAT.

**Comment by Psion05** [comment]
Please bring back the ability to switch between stack and grid view. On phones with medium screen, stack view makes it easier to navigate between tabs, grid view makes it too cumbersome to use.

**Comment by bsclifton** [comment]
Quick update - we're working through the evaluation effort now. The commit removing this in Chromium can be seen here https://github.com/chromium/chromium/commit/94a231f90d89f9af2996172fae508f9472d573cb ([here's a link to the Chromium CL](https://chromium-review.googlesource.com/c/chromium/src/+/3387522))

It may take several days to work through this (we'll need to re-home portions of this code and find clean ways to patch it in). We'll keep you all updated

**Comment by jrussellnj** [comment]
I see this was a decision by Chromium to remove the tab cards in favor of the grid view, but I want to add my voice to the calls to somehow bring it back. The grid view is just unnecessary and slower to navigate.

**Comment by Jusix** [comment]
Grid is useless bring back the list.

**Comment by LEPratt** [comment]
Bring back cascade view. Grid view is horrible.

**Comment by Brave-Matt** [comment]
Another Community +1:
https://community.brave.com/t/latest-update-has-jacked-up-my-brave-browser-and-uphold-settings/359446/3

**Comment by JordyValentine** [comment]
The grid makes the browser basically useless for me, I keep a lot of tabs in my browser. Unfortunately I'll be going back to Firefox if the grid system is permanent.

**Comment by mattspew** [comment]
Another user that hates this change!

I don’t understand why Google force this crap on everyone; what is so hard about giving users the option to choose their preferred view! It's stupid changes by Google that originally got me into Brave.

I really hope Brave can restore stacked view.

**Comment by RowanSkie** [comment]
Hey guys, we got a PR now. Hopefully, it pushes through. The grid tab layout is actually annoying to look at and reminds me of Internet Explorer, now that I see of it.

**Comment by bsclifton** [comment]
+1 from @JoaoHamerski via https://github.com/brave/brave-browser/issues/21814

**Comment by JetRandom** [comment]
It's not the fact that they made this change that bothers me so much, it's why it was made.
Go to any browser forum and you will find requests in recent times for a grid layout. It's always a half dozen or so power users who are sure this would rock their world. So along the way the people in charge buckle, and make the call for change, all the while ignoring the millions of users who are perfectly fine with tabs just the way they are.
And it's not just Brave, it's everywhere. Microsoft is probably the worst offender, where any change is seen as a good thing. 
And this is the reason i'm probably on my last Windows machine, and last Android device, never to return.

**Comment by BringBackCardTabs** [comment]
Created this account just to say that I'm going to another browser if stack layouts are still gone after an update or two. Grid is terrible.

**Comment by bw4518** [comment]
Same here, I might just keep using the old version with a stacked layout.

**Comment by RowanSkie** [comment]
btw @bsclifton, on https://github.com/brave/brave-core/pull/12684, apparently you were requested for review?

I know I'm being impatient at this rate, but well there's a growing number of new Github accounts moving here just to complain about this.

**Comment by scrilla7** [comment]
Please remove Grid view if possible and return the Stack view. Maybe you could create a hybrid of the two, 100 stacks in a grid or 50 stacks. Nah... Just bring back stacks view, thanks.

**Comment by FusionDragon** [comment]
I wanted to say that I understand keeping up older and unmaintained code can be difficult going forward with updates and patches, I would like to express my gratitude that it's being considered and that it makes me very happy as a brave user to know that our concerns are taken into account. 

Brave is my favorite browser and even if these changes don't go through it will remain my favorite browser because you guys listen, Google doesn't and forced this on a bunch of us that didn't want it. Thank you again for looking into this and putting effort into making your browser comfortable and customizable.

**Comment by Brave-Matt** [comment]
+1 from Community
https://community.brave.com/t/tabs-ordering-and-overview-messed-up-since-about-a-month-ago/363913/2

**Comment by picks-1** [comment]
Is there an official update on this?
Just need to know if I should find a different browser to use of if they're planning on reimplementing the cascade tab view.

**Comment by bsclifton** [comment]
Thanks for your patience everybody. This is clearly a change a lot of people want and we’re hearing that loud and clear: In the Google Play Store reviews, here on GitHub, and I’ve even had folks DM me on LinkedIn and Twitter asking “What’s happening?” **This might be a long post - but I want to be as transparent as possible.**

**Quick summary**: Chromium used to have “Stack View” (also referred to as “Card View” here) and then they replaced it with Grid view. In order to keep offering “Stack View” to our users, we added a toggle for this in Brave version 1.23 (released April 29, 2021). With Chromium 99, the underlying code was finally removed. This meant it got removed in Brave also when we updated our Chromium version in Brave 1.36 (released March 8, 2022).

Our teammate @samartnik did a great job putting together a pull request for adding back this functionality removed in Chromium. 
https://github.com/brave/brave-core/pull/12684

For context, @samartnik is a member of our Chromium upgrade team and spends most of his time making sure the Android part of the upgrade is in great shape (functionality works, patches are under control). He was originally the person who added the option to keep “Stack View” (see https://github.com/brave/brave-core/pull/8614) back in version 1.23. He spent about a week preparing this pull request (for re-adding “Stack View”). His work involved identifying and moving the code that used to live in Chromium and pulling this into the `brave-core` code-base. Reviewers have tested and it does work well.


There are a few problems though:
1. This re-adds 7,101 lines of code into our code-base. This is a huge amount of code and we’re going to run into conflicts as new Chromium versions become available (Chromium 101, 102, 103, etc). This code would eventually stabilize after several upgrades.
2. Before the remaining code was removed in Chromium 99, our app had a crash/ANR (application not responding) rate of more than 2% on Android 12 (which grew as Android 12 continues to be adopted). After merging Chromium 99 which removed the rest of this feature, our crash rate for Android 12 fell to below 1%. Examining the commits that Chromium team did (where the code was removed) helped shed some light. 

For example, https://github.com/chromium/chromium/commit/0d0895af67ad844e5292c4640a3b0fffbdf44839 mentions removal of `LayerTitleCache` which may have been causing startup “jank” (hanging, unexpected behavior). Removing this code may have helped stabilize the build.

**It’s tempting to just add this feature back in, but we really need to consider the long term ownership of this and define some acceptance criteria. If we are going to add this feature back in, I believe we should do it properly, which will take some time.** 

To do that, I believe we need to:
1. Make this feature “ours” (consider the design of it). Make it a first class feature.
2. Minimize the impact for Chromium upgrades. We’ve been able to stay current on Chromium with a relatively small number of staff. We need to be clever about our patching strategies and picky about what we accept. Not only for this but for everything we merge.
3. Properly investigate the crashes/ANR on Android 12 and make sure the patch does not make this worse. We’d need to let the fix sit on Nightly for a while, migrate to Beta, then Release.

These are some pretty big asks. At the moment on Android, we’re already committed to other high-priority work and don’t have bandwidth to properly dig into this. Our team is limited in size and we’d need to drop something in order to pick this up.

I’ve created a new issue to track this feature request:
https://github.com/brave/brave-browser/issues/22028

We understand the importance of this feature for many of our users, so we’ll be prioritizing this alongside our existing work. Although we don’t have a date for this yet, you can subscribe there for updates.
