### ISSUE TITLE
fix users who already restored wallets but UI displays incorrect addresses

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2172]
## Description 

We originally fixed https://github.com/brave/brave-browser/issues/1831 but didn't fix the case when a user has already restored but still has the incorrect address appearing in their UI. We've gotten several more reports from users who sent BAT to their address but never received it as it was sent to the incorrect address as they previously restored. @jonathansampson was also affected by this.

@evq mentioned that the deposit addresses are in the wallet info response and we should be able to compare those values to the locally stored values and fix the issue automatically.

## Steps to Reproduce

STR would be similar to https://github.com/brave/brave-browser/issues/1831. Requires you to get the wallet into the broken state where it shows the incorrect addresses in the UI after restoring a previous wallet. Updating to a new version should automatically fix these users as well.

## Actual result:

https://github.com/brave/brave-browser/issues/1831 addressed new installs but didn't address users who might have already restored wallets. Users who update to a new version should be fixed automatically.

## Expected result:

Users affected by this issue should be automatically fixed and the correct addresses should be displayed in the UI so they don't send funds to the incorrect addresses.

## Reproduces how often: 

100% reproducible when you have an account affected by this issue.

## Brave version (brave://version info)

Brave | 0.57.4 Chromium: 71.0.3578.31 (Official Build) dev (64-bit)
-- | --
Revision | c88fdf2a4ce19a713615ca4fbde7a0d0b5fe2363-refs/branch-heads/3578@{#427}
OS | Mac OS X

### Additional Information

@jonathansampson @evq please add anymore information if I've missed something!

**Comment by NejcZdovc** [comment]
@evq which endpoint should we use to get this data? can we just do it as part of balance check?

**Comment by kjozwiak** [comment]
@evq @NejcZdovc any news on this one? We should really try getting this into `0.57.x` as there's a few folks still affected by this 😢

**Comment by btlechowski** [comment]
@brave/legacy_qa To get the wallet into broken state, version 0.56.6 of Brave is required. Unfortunately there are no Windows standalone installers for that version https://github.com/brave/brave-browser/releases/tag/v0.56.6. Any ideas how we could verify this issue on Windows?

**Comment by srirambv** [comment]
Doesn't editing the seed values corrupt the wallet ? @NejcZdovc  thoguhts

**Comment by NejcZdovc** [comment]
@btlechowski why would you get corrupted wallet if you do wallet recovery in step 8?

**Comment by LaurenWags** [comment]
Issue does not appear to be resolved on macOS either. These were the steps I used to test (adapted from #1831):
1. Install 0.56.6 dmg (this is a Beta version)
2. Launch with clean profile and enable rewards.
3. Note backup words.
4. Note addresses displayed in Add Funds. 
5. Note paymentId, addresses, and CARD_ID from `ledger_state`.
6. Use restore functionality to Restore a wallet.
7. Note backup words (they updated to the words from the restored wallet and are different than step 3).
8. Note addresses in Add Funds (still the same as step 4). 
9. Open `ledger_state` and note paymentId (this was updated, so it's different than step 5) addresses and CARD_ID (all still the same as step 5).
10. Go to brave://settings/help to trigger update check.
11. Relaunch or close/launch manually. You will now have `0.59.26`
12. Backup words for wallet match step 7 and paymentId matches step 9 as expected.
13. Addresses in Add Funds are still the same as step 4/8 - FAIL 
14. Addresses and CARD_ID are still the same as step 5/9 - FAIL


Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Mac OS X

**Comment by btlechowski** [comment]
@NejcZdovc because 0.56.6 don't have the fix from https://github.com/brave/brave-browser/issues/1831. So if you recover wallet on 0.56.6, you will get a corrupt one.
To my understanding the whole point of this issue is to fix users who recovered the wallet before https://github.com/brave/brave-browser/issues/1831, so their corrupted wallets are fixed.

**Comment by LaurenWags** [comment]
@NejcZdovc when I follow the test plan from https://github.com/brave/brave-core/pull/1173, after modifying the addresses in ledger_state and launching Brave, I get this message about a corrupted wallet, so I can't check via the test plan.
![screen shot 2019-01-23 at 3 55 01 pm](https://user-images.githubusercontent.com/28145373/51636638-c0c78e80-1f27-11e9-9926-9f3c118ab64d.png)

**Comment by LaurenWags** [comment]
For https://github.com/brave/brave-browser/issues/2172#issuecomment-456826171 I logged a follow up issue: https://github.com/brave/brave-browser/issues/3060

Since I am unable to test this issue per the test plan (https://github.com/brave/brave-browser/issues/2172#issuecomment-456963603), I came across a different set of steps that allowed me to verify the fix for this issue. Here are the steps I used:

1. Install muon (probably 0.25.304 or whatever the last released version we did). Set up data for import (a few bookmarks, history, and definitely enable Payments. Fund wallet as well). Note backup words, wallet addresses, and address/paymentId/CARD_ID from ledger-state file.
2. Install 0.57.18 (Release version) and enable rewards. Note Addresses and backup words as displayed in the UI. Close Rewards page. Close this version. Navigate to ledger_state file and note addresses, paymentID, Card_ID.
3. Reopen On 0.57.18, import muon data from Brave > Import Bookmarks and Settings in menu (note, I could only get this problem by importing this way. Importing a different way i.e. from brave://welcome or hamburger menu did not produce the issue).
4. Go to Rewards and verify that UI still shows addresses and backup words from step 2
5. Go to ledger_state and verify it shows same values for addresses/paymentId/CARD_ID from muon (step 1)
6. Update 0.57.18 to current released version 0.58.21 by going to chrome://settings/help to trigger the update.
7. Once updated, relaunch Brave to verify update, then close Brave.
8. Rename your profile to be a Beta profile. 
9. Launch 0.59.28 Beta version. Navigate to Rewards page. 
10. Verify that the UI shows the addresses that are in ledger_state and match muon. 
NOTE - backup words are still incorrect. I have logged a separate issue for this: #3061


Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Mac OS X
