### ISSUE TITLE
Some strings on webcompat reporter are not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#21801]
Follow up to https://github.com/brave/brave-browser/issues/20095

## Steps to Reproduce

1. Run Brave in Polish PL locale
1. Open a page
1. Click hamburger menu
1. Click `Zgłoś uszkodzoną stronę`

## Actual result:

Some strings are not translated:
![image](https://user-images.githubusercontent.com/34715963/159381499-f41e1efa-0840-4602-a5e8-1de228cf0166.png)

## Expected result:
All strings are translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.37.100 Chromium: 99.0.4844.83 (Oficjalna wersja) beta (64-bitowa)
-- | --
Revision | b11086e62d7c1a44b0942ac5568d22a425c7ae35-refs/branch-heads/4844_74@{#5}
OS | Ubuntu 18.04 LTS

cc @brave/qa-team @rebron @mkarolin @pes10k @DJAndries

**Comment by kjozwiak** [comment]
Removing as this isn't labelled as `release/blocking`. @rebron looks like this was moved into `in progress` via the `General` board. If this is going to be fixed with the l10n order, than the issue should be mentioned during uplift at which point, it will be moved into `1.37.x`. If it needs a PR/uplift, it will go through the normal uplift process and moved into `1.37.x` once uplifted.

**Comment by mkarolin** [comment]
All these string have translations on Transifex, so they should come down with the next pull.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.37.109 Chromium: 100.0.4896.60 (Official Build) beta (64-bit) 
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/160823524-d9cf7dbf-0b67-4070-b938-99907572a15a.png)
