### ISSUE TITLE
Remove widget from Android new tab page

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#21826]
## Description 
Let's revert to what we had before the widget. Basically:
- stats shows at top (not as a widget)
- 4 top site tiles show by default
- If you disable backgrounds, 8 top sites will show

This is already partially implemented; you can see that code branch if you remove ALL widgets and disable backgrounds. It will show the stats at top and 8 tiles.

Removing the widget will solve the following issues:
- [Fast/Hard scroll on widgets brings up the news feed rather than scrolling through the widget](https://github.com/brave/brave-browser/issues/21166)
- [scroll on NTP widget doesn't work well](https://github.com/brave/brave-browser/issues/21511)

As a follow up, we can then do https://github.com/brave/brave-browser/issues/13714 (maybe showing a `Show more` similar to iOS)

**Comment by alexsafe** [comment]
This is how it looks rn:

![Screenshot_20220323-160228](https://user-images.githubusercontent.com/5214149/159792060-f7a9e817-c554-4d83-b7ba-8fba0b6ac42f.png)
![Screenshot_20220323-160215](https://user-images.githubusercontent.com/5214149/159792063-e585cd72-ce7e-4818-9006-eb4754ff5bac.png)

The translucent background is based on the Slack convos and the referenced [figma](https://www.figma.com/file/irDJRP35FUwsRu60Wp9fM6/iOS-onboarding?node-id=489%3A50527). Obviously there is no frost glass effect since it's on iOS thing (it CAN be done Android too, but it's custom)

Opinions?

cc @anthonypkeane @bradleyrichter @bsclifton

**Comment by bradleyrichter** [comment]
perfect @alexsafe !

**Comment by kjozwiak** [comment]
The above will require `1.38.105` or higher for `1.38.x` verification 👍

**Comment by Uni-verse** [comment]
Verified using `1.38.105, Chromium 101.0.4951.41`

Devices: 
Samsung Galaxy S21 | Android 12
Samsung Galaxy Tab S7 | Android 12

- Confirmed widget is removed from new tab page.
- Performed upgrade scenario 1.37.116 -> 1.38.105 to ensure the widget is gone. 

Tablet | Mobile
-|-
![Screen Shot 2022-04-22 at 2 20 12 PM](https://user-images.githubusercontent.com/17885425/164796257-988aca03-5906-4273-a92d-5cdcd2ec8547.png) | ![Screen Shot 2022-04-22 at 2 06 15 PM](https://user-images.githubusercontent.com/17885425/164796241-988948b1-cfcf-4c97-8731-3067d8794203.png)
