### ISSUE TITLE
unable to copy/paste

### ISSUE THREAD

**Issue by tommycarstensen** [brave/brave-browser#219]
Often I cannot copy/paste within and from Brave to another application. I'm on version 0.22.714, but I'm unable to provide further information, because copy/paste is broken most of the time. I'm on MacOS 10.11.6.

I absolutely love the idea of Brave, but I will switch back to Chrome and Firefox for now. I want a browser that doesn't fail at the simply/basic stuff. Best of luck with the project!

**Comment by srirambv** [comment]
This issue is being tracked here https://github.com/brave/browser-laptop/issues/14197#issuecomment-391230718. This repository is not for the current release version. I've added +1 on your behalf on the issue. Please use https://github.com/brave/browser-laptop/issues/14197#issuecomment-391230718 for tracking progress
