### ISSUE TITLE
Can ads and trackers be separated (If they're not inherently linked on that page)?

### ISSUE THREAD

**Issue by ChildishGiant** [brave/brave-browser#2191]
I'd love an option to turn on ads while keeping trackers off. I posted this idea on the subreddit and it seems I'm not the only one (https://www.reddit.com/r/brave_browser/comments/9w6m2l/can_ads_and_trackers_be_separated_if_theyre_not/)

**Comment by tomlowenthal** [comment]
Blocking trackers will block most ads. I'd rather spend time working on other improvements to Shields rather than working to disentangle some ads from near-ubiquitous tracking. And I really don't want to think about the maintenance load for ensuring that ads show even when blocking all tracking — if that's even possible, which it mostly isn't.

**Comment by cjwijtmans** [comment]
> ensuring that ads show even when blocking all tracking

what makes you think its necessary?
My use case is to allow ads on a website while keeping the famous "google traffic analyzer" blocked.
