### ISSUE TITLE
update brave://settings/shields to support Shields v2

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#21926]
## Description 

Update brave://settings/shields to support Shields v2. 
Update settings/text/drop down labels to match Shields v2.
Remove Default view section which no longer applies. 
Reorder cookie and fingerprint blocking so that fingerprint blocking is before (or on top) of cookie blocking to match Shields v2.

## Actual result:

<img width="744" alt="Screen Shot 2022-03-28 at 8 37 04 AM" src="https://user-images.githubusercontent.com/5951041/160438266-3e6333d2-c72c-47f9-b2e2-ec951b7d5d13.png">

## Expected result:
[placeholder design]

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by aguscruiz** [comment]
Updated design here:
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=1532%3A34473

**Comment by kjozwiak** [comment]
Above requires `1.38.85` or higher for `1.38.x` verification.

**Comment by LaurenWags** [comment]
@brave/legacy_qa we should also confirm that setting global shield options propagates to sites where site specific shield options have not already been set as well as confirm global shield settings are retained after upgrade.

**Comment by MadhaviSeelam** [comment]
Verification `In-Progress` 

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta  #(64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 11 Version 21H2 (Build 22000.593)


Currently Shields UI for global settings page do not match with Figma
Filed a bug #22382

**Comment by stephendonner** [comment]
Verification `In-Progress` 



Brave | 1.38.105 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.4 (Build 21F5058e)

- Install 1.38.103
- Launch brave

<summary>Test Case 1: Verify Shields settings page UI match to `Figma` </summary>
<details>

- Navigate to `brave://settings/shields`
- `Shields` icon is inactive and grayed out in the URL bar
- Shields settings page shields labels match to V2 Shields panel shields labels
- Shields settings page shields drop down options text is different from V2 Shields drop down options but this is by design. 
- Clicked on `Global defaults` link in the `Advanced controls` view on the Shields panel to navigate to `brave://settings/shields` page
- `Show the number of blocked items on the Shields icon` option is enabled by default
- User will be able to toggle `OFF`
- `Trackers & ads blocking` setting is `Standard` by default
- `Upgrade connections to HTTP` setting  is enabled by default
- `Block Scripts is enabled` setting by default
- `Block fingerprinting` setting is  `Standard` by default
- `Block cookies` setting is `Only cross-site` by default

settings_page|trackers_ads|fingerprinting|cookies
---|---|---|---

</details>

<summary>Test Case 2: Verify blocked count displayed if `Show the number of blocked items on the Shields icon` is `ON` for all tabs
<details>

- Verified `Show the number of blocked items on the Shields icon` is enabled by default in the brave://settings/shields
- Visit a site "www.usatoday.com"
- Shields V2 badge show number of blocked items 
- Open new tabs for two more sites "twitch.tv" and "youtube.com"
- Shields V2 badge show number of blocked items 
- Switch between all 3 sites and all 3 sites rendered block count on the Shields icon

</details>

<summary>Test Case 3: Verify no blocked count displayed if `Show the number of blocked items on the Shields icon` is 'OFF'  for all tabs
<details>

- Launch a new profile
- Navigate to brave://settings/shields
- Disable `Show the number of blocked items on the Shields icon`
- open "www.usatoday.com" in a new tab
- Return to site and verify no blocked count displayed on the Shields V2 badge
- Clicked the Shields badge to open Shields panel
- Blocked count displayed in the Shields panel as expected
  - `Trackers, ads and more blocked` 
  -  `Block trackers & ads` drop down in Advanced controls view 
- Open multiple tabs and repeat above steps for different sites "twitch.tv", "youtube.com", "gulfnews. com"
- No blocked count displayed on the Shields V2 badge for the sites
- Return to settings page and enable `Show the number of blocked items on the Shields icon` entry 
- All 3 sites displayed blocked count on the Shields icon as expected

Global_setting_OFF|singlesite|mutliplesites
---|---|---

</details>

<summary>Test Case 4: Verify Shields icon appearance when `Show the number of blocked items on the Shields icon` is enabled and disabled</summary>
<details>

- Launch a new profile
- Navigate to brave://settings/shields
- Disable `Show the number of blocked items on the Shields icon`
- Visit a site www.theverge.com"
- No blocked count should be displayed in the Shields icon
- Toggle `OFF` Shields in the Shields panel
-  Shields icon appears inactive, gray color
- Enable `Show the number of blocked items on the Shields icon`, while Shields is Down
- Return to the site 
- Shields icon still appear up as inactive

ex1|ex2|ex3|ex4|ex5
---|---|---|---|---


</details>
<summary>Test Case 5: Verify if Trackers & ads blocking is switched to `Aggressive` in `brave://settings/shields`, the setting will be propagated and display in site specific shield panel in all tabs </summary>
<details>

- Launch a new profile
- Navigate to brave://settings/shields
- Switch to `Aggressive` in `Trackers & ads blocking` option 
- - Visit www.shutterstock.com (site 1)
- Click Shields icon to view Shields panel and click `Advance controls`
- Verify correct option is reflected in the Shields panel `Aggressively block trackers & ads`
- Open another site www.buzzfeed.com (site 2)
- Verify `Aggressively block trackers & ads` displayed in the Shields panel
- Close and relaunch the browser
- Shields panel for each site preserved setting `Aggressively block trackers & ads`
- Close tabs and reopen 
- Shields panel for each site preserved the setting `Aggressively block trackers & ads`

Aggressive|site1|site2
---|---|---


</details>

<summary>Test Case 7: If a setting is manually changed in site specific shields panel from initial setting, and change to different option in global defaults page will not be propagated and will not override manually changed option in the shields panel for all tabs</summary>
<details>

- Continue from above testcase: Test Case 6
- Navigate to site 1 and change setting to `Block all trackers & ads` in the Shields panel from `Aggressively block trackers & ads`
- Verified site 2 still shows original setting `Aggressively block trackers & ads` in the shields panel
- Navigate to brave://settings/shields and switch to `disabled` for `Trackers & ads blocking` option 
- Global default option is not propagated to site 1 and still shows `Block all trackers & ads`
- Global default option is propagated to site 2 and displayed 'Allow all trackers & ads` 
- Open another site in a different tab www.cnn.com' (site 3)
- Global default option is propagated to site 3 'Allow all trackers & ads`
- Blocked counts on the Shield panel rendered as expected

site1|site2|site3changed|ex4|ex5
---|---|---|---|---


</details>

<summary>Test Case 7: Verify disabling `Upgrade connections to HTTPS' in global defaults page should propagate for all tabs</summary>
<details>

- Launch a new profile
- Navigate to brave://settings/shields
- Enable `Upgrade connections to HTTPS` should work as expected
- Disable `Upgrade connections to HTTPS` option
- Navigate to https://www.france24.com/en/ (site 1)
- Click Shields panel>>Advance controls to view `Upgrade connections to HTTPS` option
- `Upgrade connections to HTTPS` setting should be disabled
- Blocked count should be displayed correctly on the Shields panel
- Visit non-https site http://faqs.org/faqs in a new tab (site 2)
- Global setting should be propagated and `Upgrade connections to HTTPS` setting still should be disabled
- Enable and disable `Upgrade connections to HTTPS` option for site specific setting in `site 1'
- Enable `Upgrade connections to HTTPS` in global defaults settings page
- Global defaults setting is not propagated to site 1 as it is manually changed
- Global defaults setting is propagated to site 2 and now enabled
- Visted site 3 and global defaults setting is propagated and `Upgrade connections to HTTPS` enabled in shields panel
- 
ex1|ex2|ex3|ex4|ex5
---|---|---|---|---

</details>
