### ISSUE TITLE
Selecting a pinned tab with sound playing mutes the audio

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#22108]
## Description 

When a pinned tab is playing audio content, if you navigate away from that tab, then back again, selecting the pinned tab mutes the audio. This is likely due to the "speaker" icon being (or at least being detected as) clicked when trying to select the pinned tab with small real estate. 

Further, clicking the speaker icon on the pinned tab again to _unmute_  does not work (its unresponsive). Right-clicking on the pinned tab shows the `Mute tab` option even though the tab is already muted. If `Mute tab` is selected from the context menu, the tab remains muted. If you right-click again after, the context menu _now_ says `Unmute tab` — however, selecting this option _still does not unmute the tab_. 
![image](https://user-images.githubusercontent.com/3299098/161833697-b7554f0a-95c6-4a48-ba02-4ac902eea186.png)
![image](https://user-images.githubusercontent.com/3299098/161833820-332ad7eb-aee2-4476-b11b-ab8416ac1d37.png)

The only way to actually unmute the pinned tab is to unpin the tab, then click the speaker icon (which works without issue). 

## Steps to Reproduce

1. Pin a tab
2. Play audio in that tab
3. Select another tab
4. Click on the pinned tab to select it

## Actual result:

Observe audio from the pinned tab is muted and cannot be easily unmuted, as described above. 

## Expected result:
Tab should be selected, not muted

## Reproduces how often: 

Always

## Brave version (brave://version info)

1.37.111 Chromium: 100.0.4896.79 (Official Build) (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:

User report here:
https://community.brave.com/t/pinned-tab-mutes-on-click-and-cant-be-unmuted/365423

**Comment by georapbox** [comment]
As a workaround until it's fixed, you can disable **Tab audio muting UI control** from flags under **brave://flags/#enable-tab-audio-muting**. You can still mute/unmute by right clicking on the tab and selecting Mute/Unmute site from the context menu.

![Screenshot 2022-04-14 at 10 34 28 AM](https://user-images.githubusercontent.com/6596039/163336777-2421f963-9612-49a5-8d59-158ee098630f.png)

**Comment by osc86** [comment]
thank you, great solution!

**Comment by tdritsas** [comment]
Thanks but except from classic  Mute/Unmute site from menu, the disable Tab audio muting UI control does not work so as to mute individual tab while hovering over.

thanks by the way.

Hope to be fixed soon as it was so much useful.

**Comment by strobelight** [comment]
go to [brave://flags](brave://flags) and disable **Tab audio muting UI control**.

**Comment by tdritsas** [comment]
with this solution as i mention does not make any difference so as to mute/unmute individual tab while hovering over.

**Comment by georapbox** [comment]
> 

The workaround is to disable muting by clicking the icon on a pinned tab because as the issue describes, when the tab is pinned if you mute the site you cannot unmute it unless you unpin the tab and then click the icon again. So, yes, this workaround disables the feature until the bug described is fixed. If you don't pin video or audio tabs then you don't really need to disable this flag.

**Comment by tdritsas** [comment]
Sorry but the issue that Brave has is that, you can not anymore  mute/unmute  the icon of a specific tab just hovering over. If you need  to mute/unmute, you need to click the tab so as to do it and necessarily leave the other tab that you have open.

Is that big issue fixed, because as i check there is not solution.

**Comment by georapbox** [comment]
> Sorry but the issue that Brave has is that, you can not anymore mute/unmute the icon of a specific tab just hovering over. If you need to mute/unmute, you need to click the tab so as to do it and necessarily leave the other tab that you have open.
> 
> Is that big issue fixed, because as i check there is not solution.

OK, I see what you mean but I don't think that muting on hover was ever a thing. To be honest if I hovered over a tab and it muted the site, this is something I would consider as a bug because it would cause to mute sites by accident.

**Comment by tdritsas** [comment]
Sorry misunderstanding,  i mean click on mute/unmute icon of a tab that plays audio without changing your current tab. Cause when i click on mute/unmute icon then accidently i go that tab and loose focus of the tab i was before.

That bug i talked about.

Does anyone else face this issue.

Regards

**Comment by rebron** [comment]
cc: @mkarolin To see if this repros in chrome.

**Comment by mkarolin** [comment]
@rebron In Chrome, you'd have to enable the `#enable-tab-audio-muting` feature for the button to mute/unmute audio in the first place. However, with the feature enabled Chrome suffers from the same behavior as described in STR. This has been reported upstream https://bugs.chromium.org/p/chromium/issues/detail?id=1261913, but ended up merged into the general muting issue (https://bugs.chromium.org/p/chromium/issues/detail?id=360372) which has been open since 2014. I would imagine a timely upstream fix here would be unlikely.

**Comment by outluch** [comment]
brave://flags

![image](https://user-images.githubusercontent.com/1479468/165293898-87df4655-e1f3-4c44-a296-934f71212646.png)

**Comment by DevilEars** [comment]
Please do not put audio or media controls on a tab like lesser browsers do. At the very least, there should be a way for users to disable this abomination

**Comment by Brave-Matt** [comment]
+1s from Community:
https://community.brave.com/t/mute-tab-broken-for-pinned-tabs/381055/4

**Comment by ddrochers** [comment]
I'm on [Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)] and the issue seems to be resolved. I am the only one?

**Comment by bsclifton** [comment]
This should be fixed now 😄
