### ISSUE TITLE
I cannot watch videos on simultaneous websites

### ISSUE THREAD

**Issue by nuzzesick** [brave/brave-browser#22143]
## Description 
I'm trying to watch videos on different platforms like Netflix, Udemy (not always), HBO Max (probably could happens on other video platforms, I tried YouTube but works fine on it) and I can only see a white or black screen instead of the video. Sound works fine.

## Steps to Reproduce

   1. Enter to Netflix or HBO Max
   2. Play a video

## Actual result:

Udemy
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/27747658/162101225-78657a06-1acd-4b05-a116-7ce0e98a820c.png">
Netflix
<img width="1914" alt="image" src="https://user-images.githubusercontent.com/27747658/162101328-5bdf4959-d0e4-498f-ab16-1e5ce4395cf6.png">
HBO Max
<img width="1901" alt="image" src="https://user-images.githubusercontent.com/27747658/162101450-e3928ed2-e5b1-48d4-8331-e0206543a240.png">

## Expected result:
Video should appear

## Reproduces how often: 
At least for me, is easily reproduced

## Brave version (brave://version info)

Brave | 1.37.111 Chromium: 100.0.4896.79 (Build oficial) (arm64)
Revisión | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
SO | macOS Versión 12.3 (Fase 21E230)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? IDK
- Can you reproduce this issue with the nightly channel? IDK

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? IDK

**Comment by Brave-Matt** [comment]
@nuzzesick,
Can you tell me if disabling `Hardware Acceleration` in the browser (`Settings --> Additional —> System --> Hardware Acceleration`) has any effect here? I'm also curious if you can test this behavior in another browser that uses the Chromium engine (Chrome, Opera, MS edge, etc) to see if we get the same behavior there. 

On my end (using the same OS on Brave stable) I cannot reproduce this issue. I can see content correctly on Netflix, HBOMax and any other streaming service so I suspect the issue is isolated to your setup in some way. If toggling off `Hardware Acceleration` doesn't work, can you try creating a new, temp profile and testing to see if you get the same results there?

**Comment by nuzzesick** [comment]
@rebron Hello! I deactivated Widevine setting, then I restart, then I played a random movie on Netflix, it throws me an alert to activate Widevine, so I activated, and I could see the video perfectly. Then I went to Udemy and I could see a video course so I think the issue was fixed. If I go to brave://settings/extensions I can see that Widevine is again turned on (because of Netflix's alert probably)
