### ISSUE TITLE
Rewards didn't received

### ISSUE THREAD

**Issue by prashasth-nair** [brave/brave-browser#22207]
## Description 
I have claimed my rewards and rewards claimed message is also showing but my rewards balance didn't got updated. Its still showing 0.000 Bat.

![Screenshot 2022-04-11 211702](https://user-images.githubusercontent.com/79904168/162779781-532d2255-fcd9-41f3-b780-123e7d23ea92.png)

**Comment by 424344** [comment]
I'm in the same situation: the  balance wasn't updated.

**Comment by Miyayes** [comment]
Hi @prashasth-nair and @424344 , this was due to an error this month for the payout (April 2022 payout for ads seen in March). We disabled the payout on the server-side, which is why you did not receive it. We are re-doing the payout and sending it out very soon, so you should see your ad earnings claim button by end of this week. Keep an eye out, thanks.
