### ISSUE TITLE
Fix rounding issue on Send, Swap

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#22257]
The problem is: If you have for example `0.069884707965941494 ETH` on your account and go to Send and hit `ALL` to send all the amount, you will observer that: `0.069885`, which is wrong as it's an insufficient balance. It has to show `0.06988470`. So basically we should truncate everything that is more than 8 digits after the dot.
To test that, ideally an account should have a balance with more than 8 digits after a dot:
1. Go to send screen
2. Pick an account with a balance
3. Select an asset and click `ALL` under the From edit box.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 12` using the following build:

```
Brave | 1.39.53 Chromium: 100.0.4896.88 (Official Build) canary (32-bit)
--- | ---
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | Android 12; Build/SP2A.220405.004
```

Using this as the verification to get the above uplifted into [`1.38.x`](https://github.com/brave/brave-core/pull/12995) & [`1.37.x`](https://github.com/brave/brave-core/pull/12996) as these are being directly uplifted. Believe this isn't an issue on `1.39.x` but I'll let @SergeyZhukovsky comment.

**Comment by kjozwiak** [comment]
Above requires `1.37.114` or higher for `1.37.x` verification.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 12` using the following build(s):

```
Brave | 1.37.114 chromium: 100.0.4896.88 (official build) (32-bit)
```

Ran through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/22257#issue-1202334664 & https://github.com/brave/brave-browser/issues/22257#issuecomment-1097545401. Also confirmed with @SergeyZhukovsky that it's working on his production wallet with a balance of `0.069884707965941494 ETH` 👍 

Example of now seeing `0.00000000` (8 digits) rather than seeing `0.000000` which was the original issue. Example:

![Screenshot_20220413-150455](https://user-images.githubusercontent.com/2602313/163252100-5278fe5b-e9e8-4e84-bdbc-533c85b8e7d4.png)
