### ISSUE TITLE
[Issue closed due to negative responses]

### ISSUE THREAD

**Issue by Johan-Mi** [brave/brave-browser#22307]
[Issue closed due to negative responses]

**Comment by Sa-Ja-Di** [comment]
What you think is pointless is great for others. So not expecting that features are added is pretty ridiculous.

But what should be present is an option to disable the new features, regarding the side bar you don't need to use it, but don't expect Brave team to remove it as a whole just because you don't like additional customization features - because... others like them perhaps

**Comment by 424344** [comment]
I *want* the ui to be ehnanced and changed! 
Your request makes no sense.
