### ISSUE TITLE
Brave 0.22.714 is a faulty upgrade

### ISSUE THREAD

**Issue by tommycarstensen** [brave/brave-browser#224]
I can't copy/paste from the Brave browser, but I just updated to the latest version. It froze prior to suggesting the upgrade and is now still frozen after the upgrade. I'm on MacOS 10.11.6, Brave 0.22.714.

**Comment by tommycarstensen** [comment]
It asked for another upgrade, and now everything works.

Brave | 0.22.721
-- | --
V8 | 6.6.346.32
rev | bfe7cdd
Muon | 6.0.12
OS Release | 15.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

**Comment by bsclifton** [comment]
Hi @tommycarstensen - I noticed you had created another issue in this repo 

`brave-browser` is for the next version of Brave which will be coming soon (there are no downloads available). This will feature a UI that is forked from Chromium instead of the Electron/Muon core that we have currently in our live product.

`browser-laptop` is our current live product and can be found here: https://github.com/brave/browser-laptop
