### ISSUE TITLE
Adaptive captcha panel should remain active until solved

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#22417]
If you receive an adaptive captcha notification and then accidentally close the Rewards panel before solving the captcha, the captcha is no longer displayed and you must wait for the next notification to solve it.

cc: @fmarier

**Comment by LaurenWags** [comment]
Can be unblocked once https://bravesoftware.slack.com/archives/CB0KCRCQN/p1653423259020869 has an answer as this case needs to be checked as well.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

### Successful captcha
<details>

1. Schedule a new captcha
2. Start the browser with --brave-ads-staging
3. When captcha notification appears, click Solve
4. Verify that adaptive captcha displays as overlay in Rewards panel
5. Close Rewards panel
6. Reopen Rewards panel and verify that adaptive captcha still displays
7. Solve Captcha
8. Verify that success modal overlay displays in Rewards panel
9. Dismiss success modal
10. Close Rewards panel
11. Reopen Rewards panel and verify that no adaptive captcha-related overlay displays

Confirmed no adaptive captcha displayed on restart

example | example | example | example | example
---------|----------|---------|----------|----------
<img width="1680" alt="Screen Shot 2022-05-31 at 2 54 04 PM" src="https://user-images.githubusercontent.com/387249/171291262-679c3de6-75f2-4291-ae74-d0f5187180d6.png"> | <img width="1312" alt="Screen Shot 2022-05-31 at 2 52 30 PM" src="https://user-images.githubusercontent.com/387249/171291418-65059161-ba5e-4c11-b04c-00a82c40d77d.png"> | <img width="1055" alt="Screen Shot 2022-05-31 at 2 54 16 PM" src="https://user-images.githubusercontent.com/387249/171291271-05d91de5-d078-409d-96e6-3fb4998c0d8d.png"> | <img width="1055" alt="Screen Shot 2022-05-31 at 2 54 19 PM" src="https://user-images.githubusercontent.com/387249/171291272-1be718aa-7281-4706-b4a8-bda80c750cde.png"> | <img width="1055" alt="Screen Shot 2022-05-31 at 2 54 38 PM" src="https://user-images.githubusercontent.com/387249/171291274-f46c4afe-9a5f-443d-a53f-ad9b00e93b2d.png">



</details>

### Exceeding max attempts
<details>

1. Schedule a new captcha
2. Start the browser with --brave-ads-staging
3. When captcha notification appears, click Solve
4. Verify that adaptive captcha displays as overlay in Rewards panel
5. Close Rewards panel
6. Reopen Rewards panel and verify that adaptive captcha still displays
7. Fail to solve captcha until "exceeded max attempts" error message displays
8. Dismiss error modal (will display support page in new tab)
9. Close Rewards panel
10. Reopen Rewards panel and verify that no adaptive captcha-related overlay displays
11. Captchas are now paused until you reset failed_attempts and paused settings in Preferences file (support would typically do this, however)

Confirmed...

</details>

**Comment by MadhaviSeelam** [comment]
Verification `In-progress`
```
Brave | 1.40.83 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```

### Successful captcha - `PASSED`
<details>

1. Schedule a new captcha
2. Start the browser with `--brave-ads-staging`
3. When captcha notification appears, click Solve
4. Verify that adaptive captcha displays as overlay in Rewards panel
5. Close Rewards panel
6. Reopen Rewards panel and verify that adaptive captcha still displays
7. Solve Captcha
8. Verify that success modal overlay displays in Rewards panel
9. Dismiss success modal
10. Close Rewards panel
11. Reopen Rewards panel and verify that no adaptive captcha-related overlay displays

#### Confirmed no adaptive captcha displayed on restart

Step3|Step7|Step7|Step8
---|---|---|---
<img width="956" alt="Step 3" src="https://user-images.githubusercontent.com/98358127/171761139-e9ad9df6-ff57-40a4-9ad7-deac8543a59d.png">|<img width="956" alt="Step 7" src="https://user-images.githubusercontent.com/98358127/171761211-500eaf3d-9e79-49f7-82c8-d6937001d96b.png">|<img width="962" alt="Step 7" src="https://user-images.githubusercontent.com/98358127/171761232-2e0721f0-a288-451a-8f66-0fda56d0e290.png">|<img width="958" alt="Step 8" src="https://user-images.githubusercontent.com/98358127/171761272-e34ba1e7-f2ab-48d4-8b80-abf41ece0513.png">


</details>

### Rewards-icon disabled - `PASSED`
<details>

1. installed `1.40.83 `
2. launched Brave
3. opened `brave://settings/appearance`
4. toggled `Show Brave Rewards icon in address bar` to `OFF`/`Disabled`
5. opened `brave://rewards/` and clicked on `Start using Rewards`
6. scheduled a captcha
7. dwindled unblinded payment tokens
8. waited for refill of tokens
9. restarted Brave due to https://github.com/brave/brave-browser/issues/20131
10. confirmed I saw the `Solve` / `Later` captcha dialog
11. clicked on `Later`
12. dwindled tokens to trigger refill
13. restarted
14. confirmed captcha reappeared
15. clicked on `Solve`
16. purposefully failed the captcha
17. dwindled tokens
18. restarted
19. confirmed captcha reappeared
20. successfully solved it
21. dwindled tokens for refill
22. scheduled a new captcha
23. confirmed I got a new captcha

Step4 | Step10 | Step15| Step19 | Step20| Step21
---|---|---|---|---|---
<img width="750" alt="Step4" src = "https://user-images.githubusercontent.com/98358127/171765144-7970c182-cae1-44a1-9572-1f1bd5dc97cb.png">|<img width="750" alt="Step10"  src="https://user-images.githubusercontent.com/98358127/171764707-62149368-7fed-4506-9ec1-1465e2fdcfb2.png">|<img width="750" alt="Step15" src="https://user-images.githubusercontent.com/98358127/171764911-69639cce-3970-414c-b803-76a39e06de1d.png">|<img width="750" alt="Step19" src="https://user-images.githubusercontent.com/98358127/171764465-9644531d-3b11-4b88-b119-b240490892f4.png">|<img width="750" alt="Step20" src="https://user-images.githubusercontent.com/98358127/171764261-68d6251e-6de0-430b-8522-2bf879a609e6.png">|<img width="750" alt="Step23" src="https://user-images.githubusercontent.com/98358127/171764049-51b764b4-0f8e-4e88-83bb-ec38fc9cbad3.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.40.87 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Ubuntu 18.04 LTS

### Successful captcha - `PASSED`
<details>

1. Schedule a new captcha
2. Start the browser with `--brave-ads-staging`
3. When captcha notification appears, click Solve
4. Verify that adaptive captcha displays as overlay in Rewards panel
5. Close Rewards panel
6. Reopen Rewards panel and verify that adaptive captcha still displays
7. Solve Captcha
8. Verify that success modal overlay displays in Rewards panel
9. Dismiss success modal
10. Close Rewards panel
11. Reopen Rewards panel and verify that no adaptive captcha-related overlay displays

#### Confirmed no adaptive captcha displayed on restart

![image](https://user-images.githubusercontent.com/34715963/172736414-5a77d71c-1f60-4121-8fa2-a7f180501f8d.png)
![image](https://user-images.githubusercontent.com/34715963/172736566-8f36224b-feb6-480b-b850-5135716d600d.png)
![image](https://user-images.githubusercontent.com/34715963/172736575-e3c13eec-73e1-4fae-bcdf-9b73b71fc65f.png)
![image](https://user-images.githubusercontent.com/34715963/172736590-15c48e70-00e3-4e5e-83fa-69af5e3e5809.png)
![image](https://user-images.githubusercontent.com/34715963/172736619-08503178-8a9e-4613-97c5-a6569d1d605b.png)
![image](https://user-images.githubusercontent.com/34715963/172736635-b2acc11f-6169-483f-b0c3-9a383a598841.png)



</details>

### Rewards-icon disabled - `PASSED`
<details>

1. installed `1.40.x`
2. launched Brave
3. opened `brave://settings/appearance`
4. toggled `Show Brave Rewards icon in address bar` to `OFF`/`Disabled`
5. opened `brave://rewards/` and clicked on `Start using Rewards`
6. scheduled a captcha
7. dwindled unblinded payment tokens
8. waited for refill of tokens
9. restarted Brave due to https://github.com/brave/brave-browser/issues/20131
10. confirmed I saw the `Solve` / `Later` captcha dialog
11. clicked on `Later`
12. dwindled tokens to trigger refill
13. restarted
14. confirmed captcha reappeared
15. clicked on `Solve`
16. purposefully failed the captcha
17. dwindled tokens
18. restarted
19. confirmed captcha reappeared
20. successfully solved it
21. dwindled tokens for refill
22. scheduled a new captcha
23. confirmed I got a new captcha

![image](https://user-images.githubusercontent.com/34715963/172736826-db58e88c-4c32-4ad7-8e7f-470f289f127c.png)
![image](https://user-images.githubusercontent.com/34715963/172736842-95ce8f2a-2e64-4fcc-91fd-10adc3773a1d.png)
![image](https://user-images.githubusercontent.com/34715963/172736858-15da3839-3f91-4475-827d-746a3b14797f.png)
![image](https://user-images.githubusercontent.com/34715963/172736869-60ecae32-eb90-4e04-ad6f-f69bfaa3cc41.png)


</details>

### Exceeding max attempts - `PASSED`
<details>

1. Schedule a new captcha
25. Start the browser with `--brave-ads-staging`
26. When captcha notification appears, click `Solve`
27. Verify that adaptive captcha displays as overlay in Rewards panel
28. Close Rewards panel
29. Reopen Rewards panel and verify that adaptive captcha still displays
30. Fail to solve captcha until "exceeded max attempts" error message displays
31. Dismiss error modal (will display support page in new tab)
32. Close Rewards panel
33. Reopen Rewards panel and verify that no adaptive captcha-related overlay displays
34. Captchas are now paused until you reset `failed_attempts` and `paused` settings in `Preferences` file (support would typically do this, however)

![image](https://user-images.githubusercontent.com/34715963/172737815-e90cf384-7984-4c48-9785-16e2f9b12c84.png)
![image](https://user-images.githubusercontent.com/34715963/172737831-ef6d9366-7be0-4d2d-bf18-5f18d8301967.png)
![image](https://user-images.githubusercontent.com/34715963/172737850-08f22d8d-1cb9-40c2-a72c-bee08e3d9c76.png)
![image](https://user-images.githubusercontent.com/34715963/172737909-509e2215-9d79-4d61-981a-1ceae327ab5e.png)
![image](https://user-images.githubusercontent.com/34715963/172737927-0d33af1b-a2aa-4aac-bbd7-52932ce93540.png)
![image](https://user-images.githubusercontent.com/34715963/172737961-3579bf01-58b6-4a19-bfbb-22a4aff683de.png)


#### Confirmed:
* captchas were paused
* `Preferences` file contained `failed_attempts` count of `10` and `paused` `true` status

![image](https://user-images.githubusercontent.com/34715963/172738106-42fc2b41-691e-45b0-9aed-0b9ddf75daed.png)

#### Changed `failed_attempts` to `0` and `paused` to `false` in `Preferences, restarted, and re-issued a challenge

![image](https://user-images.githubusercontent.com/34715963/172738710-53ac74c3-8ff6-4cfe-89e8-98fedadbe5b5.png)


#### Confirmed I received an adaptive-captcha challenge again:

![image](https://user-images.githubusercontent.com/34715963/172738763-0f748efa-3924-4610-a1e1-f371c9baf2ad.png)


</details>
