### ISSUE TITLE
Smashing Magazine doesn't work - ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by limonte** [brave/brave-browser#2251]
## Description 
https://www.smashingmagazine.com/ shows ERR_TOO_MANY_REDIRECTS 

## Steps to Reproduce
   1. Google "smashing magazine"
   2. click the first search result

![image](https://user-images.githubusercontent.com/6059356/49085118-f0288a80-f259-11e8-9bee-8518182f31f1.png)

## Actual result:
ERR_TOO_MANY_REDIRECTS

## Expected result:
It should show Smashing Magazine :)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)
OS | Windows

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

### Additional information

It shows ERR_TOO_MANY_REDIRECTS also when I hit the "refresh" button.
If I focus the url bar and hit <kbd>Enter</kbd> it will show Smashing Magazine.

**Comment by kirkins** [comment]
This website is using client side forwarding instead of DNS based forwarding.

It can be fixed by turning of shileds for the website.

**Additional info**

These URLs are 301 redirects and work on Brave

http://www.smashingmagazine.com
http://smashingmagazine.com
https://smashingmagazine.com

They all forward to https://www.smashingmagazine.com/ which normally returns 200 but doesn't work on Brave.

Running `dig` on both versions of the url returns the same DNS:

```
; <<>> DiG 9.11.3-1ubuntu1.3-Ubuntu <<>> smashingmagazine.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7203
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;smashingmagazine.com.		IN	A

;; ANSWER SECTION:
smashingmagazine.com.	5696	IN	A	178.128.239.221

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Dec 05 13:41:39 EST 2018
;; MSG SIZE  rcvd: 65
```

As mentioned above turning off shields fixes the issue.

**Comment by bsclifton** [comment]
In the year that's passed, this looks to have been resolved 😄 We are looking at fixes related to user agent when doing redirect, which may be causing an issue
