### ISSUE TITLE
Browser setting doesn't reflect on shield extension

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#226]
## Description 
Browser setting doesn't reflect on shield extension

## Steps to Reproduce

   1. Settings->Content Setting->Cookies-> Disable `Allow sites to save and read cookie data ` switch setting it to block cookies
   2. Open a new tab and visit jsfiddle.net, page opens correctly 
   3. Open shields, Cookie control is set to `Block 3rd party cookies` (default setting)
   4. Change cookie setting to Block all cookies in shield
   5. Page doesn't load because cookies not set

 ## Actual result:
Browser setting doesn't reflect on shield extension

## Expected result:
Cookie settings in shields should match if it is changed at browser level

**Comment by bbondy** [comment]
cc @bradleyrichter

**Comment by bbondy** [comment]
I think since we already have global shield settings we can just hide the option that is conflicting. Do you agree @srirambv ?

**Comment by rebron** [comment]
This setting should be hidden Settings->Content Setting->Cookies-> Allow sites to save and read cookie data 
since it's redundant with Shield Settings-> Cookies Blocked
See: https://github.com/brave/brave-browser/issues/606#issuecomment-419319215 
I'll get an updated design screenshot specific for Cookies

**Comment by srirambv** [comment]
@bbondy @rebron agree `Allow sites to save and read cookie` option should be disabled. It should only have the following sections
1. Keep local data only until you quit your browser
2. Block
3. Clear on exit (not shown on https://github.com/brave/brave-browser/issues/606#issuecomment-419319215 but should be part of it since user can set the cookies to be deleted upon exit or for a session only)
4. Allow

**Comment by bbondy** [comment]
This one is probably not the end of the world even know it is inconsistent, so I'll move to 1.x and put as p2.

**Comment by LaurenWags** [comment]
+1 from me - encountered this and it was very confusing when trying to trouble shoot why a site wouldn't work properly. Having Cookies set to 'Blocked' here overrode my shield settings of 'Block 3rd party cookies' but that wasn't evident when trying to resolve an issue. 
![screen shot 2018-10-15 at 10 04 04 am](https://user-images.githubusercontent.com/28145373/46956573-a26a1100-d063-11e8-87b3-f124b02999a8.png)

**Comment by cezaraugusto** [comment]
I don't know exactly what we expect here. should we remove the setting from the settings page?

**Comment by rebron** [comment]
Still need a decision here whether we need to hide general browser cookie pref in favor of shields pref due to conflicts. Label has changed over time and now reads 'Allow sites to save and read cookie data (recommended).

![Screen Shot 2020-01-23 at 12 55 00 PM](https://user-images.githubusercontent.com/5951041/73023048-967d0b00-3ddf-11ea-8024-01ec1f63dc70.png)

**Comment by bridiver** [comment]
this is not relevant anymore because the settings have changed, but there is a new ticket to cover a UI update issue https://github.com/brave/brave-browser/issues/20856
