### ISSUE TITLE
Increase base fee from 12.5% higher than last block to 33%

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#22640]
Vitalik recommends going to 33% instead of 12.5%.
Note that this doesn't make actual fees higher because the excess not needed is returned to the user. 

Test plan: 
Just do a transaction and make sure it goes smoothly and fast.
The base fee should be higher than the previous version.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.38.118 Chromium: 101.0.4951.67 (Official Build) (arm64)
-- | --
Revision | `8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}`
OS | Windows 11 Version 22H2 (Build 22621.1) 

- Verified test plan from original issue description
- Verified transaction is faster 

https://user-images.githubusercontent.com/17010094/168530255-54d13aff-ccb6-4f4b-aa11-17a9bf4d7ea1.mov


---------------

Verification passed on Oppo Reno 5 with Android 12 running 1.38.118 x64 build
- Verified test plan from original issue description
- Verified transaction is faster

https://user-images.githubusercontent.com/17010094/168529153-e6a16815-1220-406b-8127-3e8459690ff0.mp4

**Comment by timbeiko** [comment]
@bbondy just stumbled here with little context, but something seems wrong with either this approach or internal naming. 

> Vitalik recommends going to 33% instead of 12.5%.

The `base fee per gas` value is set by the protocol itself and can't be "set" in a transaction by users. It's part of the block header and can only go up/down by +/- 1/8 per block, based on how much gas is used. The exact update formula can be found [here](https://eips.ethereum.org/EIPS/eip-1559) (see the `# check if the base fee is correct` comment). 

In other words, the oracle should be able to calculate this exactly by just looking at the `gas used` of the parent block. 

So, I imagine that this is about increasing the `max fee per gas` (maximum a user can be charged for their transaction, in wei, set in the transaction) or the `max priority fee per gas` (maximum a user's transaction will send in a transaction, in wei, set in the transaction), in that case, it's just a renaming problem. 

I just want to highlight the difference in case the 12.5% limit is somehow used across both, because it's impossible for the `base fee` to go up/down by more than that, block to block, but totally fine for you to bump the `max fee` or `max priority fee` by whatever % by default.

**Comment by bbondy** [comment]
> The base fee per gas value is set by the protocol itself and can't be "set" in a transaction by users. It's part of the block header and can only go up/down by +/- 1/8 per block, based on how much gas is used. The exact update formula can be found [here](https://eips.ethereum.org/EIPS/eip-1559) (see the # check if the base fee is correct comment).

Yes I know, that's why I used the 12.5% originally as our internal value.
By increasing this value it increases our max fee per gas value internally.
