### ISSUE TITLE
Dark mode on text content - feature or bug?

### ISSUE THREAD

**Issue by maarsson** [brave/brave-browser#22718]
## Description 
Simple text contents appears on black background with white text, if the dark mode is on. That decreases the readability of the text dramatically. (In the meantime, of course, I want to keep dark mode on the UI, but not on the content.)
Is it a feature, or a bug?

## Steps to Reproduce
   1. For example: https://www.bbc.com/robots.txt

## Brave version (brave://version info)
Version 1.38.111 Chromium: 101.0.4951.54 (Officiell version) (arm64)

**Comment by adventurist** [comment]
I am also seeing the same on `V1.38.111` Linux

**Comment by AlbertoFDR** [comment]
I think that the Dark content feature is implemented in the Chromium project, which is why Brave also has it. The issue is that it uses your system's color scheme (dark or light). If you want to disable it, go to _brave://flags/_  and search for "Auto Dark Mode for Web Contents". 
[Take a look the chromium thread.](https://bugs.chromium.org/p/chromium/issues/detail?id=1046660)

**Comment by maarsson** [comment]
Thank you for the tips. It does not help at all.
I close this issue.
