### ISSUE TITLE
Speed up Wallet Panel Load Time

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22714]
## Description 
Currently the `Wallet Panel` can takes a long time to `render`, the panel should be snappy and load instantly. We should investigate possible performance issues and ways to speed up the panel's load time by maybe lazy loading data so the panel can load instantly.

https://user-images.githubusercontent.com/40611140/167055340-a9b042df-1478-4252-a5eb-e3aa0b5263f1.mov

**Comment by onyb** [comment]
Fixed in https://github.com/brave/brave-core/pull/18735. I created 10 EVM + 10 SVM accounts and the panel now pops up almost instantly. Closing this, but we'll keep working actively on more such improvements.

https://github.com/brave/brave-browser/assets/3684187/3645ff56-db2d-433b-b44b-2070c1acb6e5
