### ISSUE TITLE
blogspot.com URLs not being debounced

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#22894]
Test case: `https://example.blogspot.com/a/b/c/?url=https://brave.com` should redirect to `https://brave.com`

**Comment by LaurenWags** [comment]
https://github.com/brave/brave-core/commits/master?after=3f255de8a52b3457df76b084698d4eb5cb5125ff+419&branch=master&qualified_name=refs%2Fheads%2Fmaster

**Comment by stephendonner** [comment]
Hi @pilgrim-brave using:

Brave | 1.41.50 Chromium: 102.0.5005.99 (Official Build) nightly (x86_64)
-- | --
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | macOS Version 12.5 (Build 21G5037d)

I tried to reproduce and verify using `https://example.blogspot.com/a/b/c/?url=https://brave.com` from https://github.com/brave/brave-browser/issues/22894#issue-1238875409, but it returns a `404` (trying to find that URL on `blogspot.com`, rather than redirecting to the `brave.com` URL):

<img width="1504" alt="Screen Shot 2022-06-09 at 3 48 59 PM" src="https://user-images.githubusercontent.com/387249/172958119-b27fc1bf-ffd4-42ed-a3a0-8ad55b49a618.png">

Mind trying and letting me know if the test plan needs changing?  Thanks!

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` until the above is resolved.

**Comment by pilgrim-brave** [comment]
Ah, the debounce rules have changed. New test URL is `https://example.blogspot.com/a/b/c?url=aHR0cHM6Ly93d3cuYnJhdmUuY29t`

**Comment by pilgrim-brave** [comment]
which should navigate to `brave.com`

**Comment by stephendonner** [comment]
## Verified `PASSED`

Not sure why I wasn't seeing it working, above, but am now, using 

Brave | 1.41.74 Chromium: 103.0.5060.53 (Official Build) beta (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.7 (Build 20G630)

### Steps:
1. install `1.41.74`
2. launch Brave
3. load `https://example.blogspot.com/a/b/c?url=aHR0cHM6Ly93d3cuYnJhdmUuY29t` with the `Network` panel from `Developers Tools` open, with `Preserve log` selected

<img width="1312" alt="Screen Shot 2022-06-21 at 1 12 10 PM" src="https://user-images.githubusercontent.com/387249/174889087-b39368c5-91ce-4386-9909-f5c120b32cbb.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.41.82 Chromium: 103.0.5060.66 (Official Build) beta (32-bit)
--- | ---
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Android 13;
```

* downloaded/installed `1.41.82 Chromium: 103.0.5060.66`
* restarted the browser and ensured that the Griffin studies have been pulled/downloaded via `brave://version`
* loaded `https://example.blogspot.com/a/b/c?url=aHR0cHM6Ly93d3cuYnJhdmUuY29t` and ensured it was redirected to `brave.com`

![image](https://user-images.githubusercontent.com/2602313/176250030-7f7a4750-0184-41ef-8069-c391b56fb93b.png)
