### ISSUE TITLE
[Android] Updates to Onboarding Welcome Screens

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#22946]
**Product Spec:**
https://docs.google.com/document/d/12Yd98rnfn6cPEowr96v4bbgwD2pbYsZw8awH10n7VPg/edit

**Comment by kjozwiak** [comment]
Adding missing labels. Specifically missing the `QA/Yes` label.

**Comment by Uni-verse** [comment]
Verification in progress on `Samsung GS 21` using 

```
Brave	1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) 
Revision	20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS	Android 12; Build/SP1A.210812.016
```
<details>
<summary>Welcome Animation</summary> 

- Animation includes initial brave logo > welcome text > set to default phase
- UI matches the spec designs 

1 | 2 | 3
-|-|-
![screenshot-1656629751910](https://user-images.githubusercontent.com/17885425/176795417-eec46e78-0aa9-48fa-a923-aa13d16fe8d5.png) | ![screenshot-1656629756081](https://user-images.githubusercontent.com/17885425/176795423-c749da6b-3704-4d60-97dc-78649a915b3f.png) | ![screenshot-1656629763716](https://user-images.githubusercontent.com/17885425/176795434-42385848-cc66-4177-92a5-22faf8d129a5.png)

</details>

<details>
<summary>Set Default</summary>

- User able to select `Set as default browser` which will show option prompt
- User able to select `Not now`
- User able to proceed to the next onboarding screen after selecting skipping default screen

1 | 2
-|-
![screenshot-1656628665908](https://user-images.githubusercontent.com/17885425/176795560-c51df0e6-bf3b-484b-9e7b-6eca577c0d22.png) | ![screenshot-1656628677489](https://user-images.githubusercontent.com/17885425/176795564-57035089-1bb3-49aa-b23c-44d616c194ec.png)

</details>

<details>
<summary>P3A</summary>

- Checkboxes on the P3A screen are selectable and user is able to successfully complete onboarding when opting-out from P3A.
- Confirmed P3A settings under privacy setting will reflect the selection made in the onboarding screen.

1 | 2 | 3
-|-|-
![screenshot-1656629793987](https://user-images.githubusercontent.com/17885425/176795664-aa6a3f72-5fb9-4f50-adad-29ad696d5e4b.png) | ![screenshot-1656629969473](https://user-images.githubusercontent.com/17885425/176795695-d3024375-1387-4959-a2d0-29dc26886bae.png) | ![screenshot-1656630083897](https://user-images.githubusercontent.com/17885425/176795767-81325399-e24a-427b-8c34-80ecb0f1fa28.png)

</details>

<details>
<summary>Shields</summary>

- Confirmed shields explainer modal is displayed when `user enters domain`
- Confirmed shields explainer modal is displayed when `user selects result from search`
- Confirmed where trackers from `Google`, `Facebook` or `Amazon` include names of these companies in the modal text, otherwise only display `X ads & trackers blocked.`


1 | 2 | 3 | 4
-|-|-|-
![screenshot-1656629827369](https://user-images.githubusercontent.com/17885425/176795869-f971d2de-65d4-4044-aa42-643112a7da17.png) | ![screenshot-1656630986015](https://user-images.githubusercontent.com/17885425/176795889-c210ea3f-8fb3-445c-b06e-941147c0d748.png) | ![screenshot-1656631277503](https://user-images.githubusercontent.com/17885425/176795892-3f14b20e-cf17-43ec-84e3-4432a9dc776b.png) | ![screenshot-1656631380472](https://user-images.githubusercontent.com/17885425/176795895-2e72aa3a-98f3-48eb-b31d-c97fa24fec0c.png)

</details>
