### ISSUE TITLE
Block script doesn't show all blocked items at once and lists irrelevant items blocked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#230]
## Description 
Block script doesn't show all blocked items at once and lists irrelevant items blocked

## Steps to Reproduce

   1. Build from source (2e9c470)
   2. Visit brianbondy.com in a new tab
   3. Block scripts from shields, shows one entry for blocked item
   4. Disable the blocked item and click apply 
   5. Two more blocked items show up which are not relevant 

 ## Actual result:
![block script](https://user-images.githubusercontent.com/17010094/40586954-f89ce822-6196-11e8-94e5-2d63f6a00b4a.gif)

Blocked scripts on current muon browser for comparison
![image](https://user-images.githubusercontent.com/17010094/40586944-d486c584-6196-11e8-8864-169296ad3339.png)

## Expected result:
Should show all blocked items when block script is enabled and only block relevant items

## Reproduces how often: 
Easy

## Brave version (about:brave info)

2e9c470

cc: @bbondy

**Comment by yrliou** [comment]
<img width="285" alt="screen shot 2018-09-24 at 9 15 25 pm" src="https://user-images.githubusercontent.com/4730197/45992478-fffbd680-c03e-11e8-97bf-8b4418ca0634.png">
Above is the screenshot for the current result.
The youtube.com entry won't be shown before we unblock script on brianbondy.com because it won't be loaded at all if script on brianbondy.com is blocked.
So not showing brianbondy.com & youtube.com at once seems to be the expected result to me.

<img width="1280" alt="screen shot 2018-09-24 at 9 27 22 pm" src="https://user-images.githubusercontent.com/4730197/45992888-e3f93480-c040-11e8-8a63-b5e91e66acbb.png">
The two youtube scripts blocked also seem to be valid for me judging from the above screenshot of devtool.

**Comment by bbondy** [comment]
I think maybe just the UI is confusing because if I re-block on brianbondy.com scripts, then I expect for youtube to not show up in that case again, but the radio button is still there.

**Comment by yrliou** [comment]
QA note: Please see the test plan specified in https://github.com/brave/brave-core/pull/494, thanks!

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

- Using test plan from https://github.com/brave/brave-core/pull/494
