### ISSUE TITLE
Warn users if DnsOverHttpsMode is disabled by policy for BraveVPN on Windows

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#23123]
## Description 

Follow up from https://github.com/brave/security/issues/874#issuecomment-1138845005

if we have https://chromeenterprise.google/policies/#DnsOverHttpsMode policy set as off. We have DNS leak. (The settings page blocks access to the option in this case). The user isn't fully in control of their browser in those cases and so the best we can do is warn them.

## Steps to Reproduce

   1. Disable DnsOverHttpsMode policy
   2. Enable BraveVPN
   3. Should see the message

## Actual result:

- no warning message

## Expected result:

- the warning message is shown to user

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
@spylogsster 

Validated in `1.40.70 Chromium: 102.0.5005.50 (Official Build) beta`
Followed test plan from:  https://github.com/brave/brave-core/pull/13524#issue-1251963009.  
When VPN enabled, `Can't connect to server` message displayed instead of the `Secure DNS...` modal 

ex|ex|ex
---|---|---
<img width="934" alt="image" src="https://user-images.githubusercontent.com/98358127/178081020-7951873e-b3cb-401a-b254-4b3ed10aebcf.png">|<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/178081034-2ffe1700-f8f9-487c-9e30-b641308f0d1f.png">|<img width="920" alt="image" src="https://user-images.githubusercontent.com/98358127/178081045-4a3e3749-07fd-4f38-aa7b-2e422e1a4d19.png">

cc: @stephendonner

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 11 Version 21H2 (Build 22000.739)
```


Followed test plan from https://github.com/brave/brave-core/pull/13524#issue-1251963009

1. Install 1.41.91
2. Disable `DnsOverHttpsMode` in the registry 
        - go to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Policies\BraveSoftware\Brave
        - create new string value>>`DnsOverHttpsMode`
        - set to `off`
3. Launch Brave
4. Verify policy is disabled via brave://policy/
5. Purchase and Setup Brave VPN
6. Click VPN button and enable 
7. Correct alert modal is displayed


Step 2|Step 4|Step 7 (Light)|Step 7(Dark)
---|---|---|---
<img width="816" alt="image" src="https://user-images.githubusercontent.com/98358127/178362483-f0102232-6106-4d60-8d06-a577eae5c0f8.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/178363959-80e08119-79d8-41d5-83bf-cd89dfe5a700.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/178364070-529b8199-087f-4cf3-ba0b-7bede1c7e8a0.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/178364322-4ca69e12-e535-4a97-9e66-19e3beb8ae14.png">
