### ISSUE TITLE
fingerprinting screen coordinates

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#23170]
## Description 

Most browsers leak information about the user's display outside the content viewport, including screen width and height, the position of a browser window in the screen, and the difference between viewport and window dimensions. This information constitutes a fingerprinting vectors that is exposed to content JS and CSS. APIs that leak this information include:

`window.screen` object leaks information about the screen size:
- `window.screen.width`
- `window.screen.height`
- `window.screen.availWidth`
- `window.screen.availHeight`
- `window.screen.availLeft`
- `window.screen.availTop`
- `window.screen.isExtended` (leaks whether the user has multiple monitors) 

Media queries also leak screen dimensions:
- `device-width`
- `device-height`

`window` properties leak absolute coordinates of the position and outer boundary of the browser window:
- `window.screenX`
- `window.screenY`
- `window.outerWidth`
- `window.outerHeight`

Pointing event screen coordinates (`MouseEvent`, `TouchEvent`, `DragEvent`, `PointerEvent`) can also be used to computed the window's position on the screen:
- `event.screenX`
- `event.screenY`

We want to hide this information from visited websites. The plan is to farble all of these APIs, meaning we spoof the values and also add a domain/session-keyed pseudorandom component to each of them.

We plan to enable the protection under standard (default) and aggressive fingerprinting modes, so that the user can disable them by lowering shields or setting "allow fingerprinting". In addition, we bind the protections to a flag so that they can be remotely disabled using griffin.

## Steps to Reproduce
Visit https://arthuredelstein.github.io/tracking_demos/screen.html to see how screen size is revealed.
 
## Actual result:
Example: ![image](https://user-images.githubusercontent.com/355566/171301953-97bf5919-e103-4d79-aecf-da96bea18023.png)

Also: 
![image](https://user-images.githubusercontent.com/355566/171302000-01417b74-975e-45e0-a549-28b80ef8eb3e.png)

## Desired result:

Content should not be given true information about screen dimensions or window position.

## Reproduces how often: 

Always

## Brave version:

All versions

**Comment by arthuredelstein** [comment]
Re-opening because commit was reverted because of a crash.

**Comment by kjozwiak** [comment]
@brave/qa-team can probably use https://github.com/brave/brave-variations/pull/362#issuecomment-1250523212 as a template of what should be checked. However, remember that this is being enabled via Griffin so enabling the feature via `brave://flags` might not be necessary depending what channels have `BraveScreenFingerprintingBlockerStudy` enabled and what percentage.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

### Default/1st-run

### Griffin-enabled/2nd-run

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.84 Chromium: 106.0.5249.91 (Official Build) beta (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

### Case 1: 1st launch, no Griffin - `PASSED`
<details>

Steps:
1. installed `1.45.85`
2. launched Brave
3. opened `brave://version`
4. confirmed no Griffin studies listed
5. loaded `https://dev-pages.brave.software/fingerprinting/farbling.html`
6. clicked on `Generate fingerprints`
7. confirmed the `This Page`, `Local Frame`, and `Remote Frame` values were the same for each of the following:
- `Screen resolution`
- `Screen resolution media query`
- `Available screen resolution`
8. loaded `https://arthuredelstein.github.io/tracking_demos/screen.html`
9. moved the mouse around and examined the tracked events

#### Confirmed there was no farbling of the screen/window coordinates shown in the screenshot

`step 3` | `step 5` | `step 8`
------|------|------
<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/194124249-499dbdbd-d674-46cb-9857-b909a33f1599.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/194130009-dd578215-3999-43d4-9338-269a2dbb7bca.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/194170644-b8910027-c3bd-49b6-83d3-a3a6edc12856.png">

</details>

### Case 2: 2nd launch, Griffin-enabled study (50%) with Shields enabled- `PASSED`
<details>

(Continued from `1st launch, no Griffin` test, above)
10. restarted Brave
11. opened `brave://version`
12. confirmed in the 50%-chance case you get `BraveScreenFingerprintingBlockerStudy:Enabled`
13. loaded `https://dev-pages.brave.software/fingerprinting/farbling.html`
14. clicked on `Generate fingerprints`
16. loaded `https://arthuredelstein.github.io/tracking_demos/screen.html`
17. moved the mouse around and examined the tracked coordinates

#### Confirmed the values for `This Page` were different from `Local Frame` and `Remote Frame` (which were both the same); the only four (4) trackable events were the `mouseEvent.client(X/Y) coordinates`

step 11-12 | `step 13` | `step 16`
------|-----|-----
<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/194133004-c517164b-33b7-4e70-9b65-c5b84db41e01.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/194168601-47a2732d-9930-4814-bf54-81a4023159b4.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/194165133-57fe3dc1-c3a9-48c3-889e-3c03fd0c6761.png">
</details>

### Case 3: 2nd launch, Griffin-enabled study (50%)  with Shields disabled- `PASSED`
<details>

1. continued from Case 2
2. disable Shields in the Shields panel
3. reload the https://dev-pages.brave.software/fingerprinting/farbling.html
4. clicked on `Generate fingerprints` 
5. loaded https://arthuredelstein.github.io/tracking_demos/screen.html
6.  moved the mouse around and examined the tracked coordinates

`brave://version`|shields down`|`farbling.html`|`screen.html`
-----|-----|-----|-----
<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/194164841-769ed247-94c4-4ec0-9232-05768c29f625.png">|<img width="762" alt="image" src="https://user-images.githubusercontent.com/98358127/194164717-af0639e4-1e85-4fe2-ae6b-c781b6776c29.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/194169387-9ccdd238-d7d9-423e-b80a-8e09676ea397.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/194165037-af6f15af-0dc0-4c82-80fe-8eddcd32c835.png">

### Confirmed all values were the same; no farbling was applied
</details>

### Case 4: 3rd launch, default/no study (50%) - `PASSED`
<details>

(Continued from `1st launch, no Griffin` test, above)
10. restarted Brave
12. opened `brave://version`
13. confirmed in the *other* 50%-chance case I got `BraveScreenFingerprintingBlockerStudy:Default`
14. loaded `https://dev-pages.brave.software/fingerprinting/farbling.html`
15. clicked on `Generate fingerprints`
16. loaded `https://arthuredelstein.github.io/tracking_demos/screen.html`
17. moved the mouse around and examined the tracked coordinates

#### Confirmed all values were the same; no farbling was applied

`step 11` | `step 13` | `step 15`
------|-------|---------
<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/194171160-ed3b23b4-1c97-4fa3-8655-aa0b4abf9e60.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/194171355-962ad524-8d2d-4edd-9454-f27d68336be0.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/194171528-1488220b-babc-48b3-93b4-77a91b6080f0.png">

**Comment by kjozwiak** [comment]
Because `BraveScreenFingerprintingBlockerStudy` hasn't been rolled out via the `release` channel, verification on `Android` was done by enabling `brave://flags#brave-block-screen-fingerprinting` to ensure the feature was working as expected.

Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.45.111 Chromium: 107.0.5304.62 (Official Build) (32-bit)
--- | ---
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Android 12; Build/SP1A.210812.016
```


### Case 1: BraveBlockScreenFingerprinting disabled - `PASSED`
<details>

1. installed `1.45.111 Chromium: 107.0.5304.62`
2. launched Brave
3. opened `brave://version`
4. confirmed no Griffin studies listed
5. loaded `https://dev-pages.brave.software/fingerprinting/farbling.html`
6. clicked on `Generate fingerprints`
7. confirmed the `This Page`, `Local Frame`, and `Remote Frame` values were the same for each of the following:

- `Screen resolution`
- `Screen resolution media query`
- `Available screen resolution`

8. loaded `https://arthuredelstein.github.io/tracking_demos/screen.html`

#### Initial values before restarting the browser

**`Example`** | **`Example`**
---------------|------------------
![Screenshot_20221024-121700_Brave](https://user-images.githubusercontent.com/2602313/197575823-a81f021f-fe8e-4399-9dd2-9d6dab0fb02e.jpg) | ![Screenshot_20221024-121746_Brave](https://user-images.githubusercontent.com/2602313/197575833-dd2bf82e-463d-4688-a652-0eed7965d06a.jpg)

#### Confirmed there was no farbling of the screen/window coordinates shown after the browser was restarted

**`Example`** | **`Example`**
---------------|------------------
![Screenshot_20221024-121819_Brave](https://user-images.githubusercontent.com/2602313/197575992-f0fe612b-1925-4b3b-9b2b-9a2fb40b80aa.jpg) | ![Screenshot_20221024-121829_Brave](https://user-images.githubusercontent.com/2602313/197576020-3a79fae3-118c-48fa-b5af-89d7f249bab1.jpg)

</details>

### Case 2: BraveBlockScreenFingerprinting enabled - Shields Enabled - `PASSED`
<details>

1. installed `1.45.111 Chromium: 107.0.5304.62`
2. launched Brave
3. opened `brave://version`
4. confirmed no Griffin studies listed
5. enable `brave://flags#brave-block-screen-fingerprinting` via `brave://flags`
6. loaded `https://dev-pages.brave.software/fingerprinting/farbling.html`
7. clicked on `Generate fingerprints`
7. note the `This Page`, `Local Frame`, and `Remote Frame` values for the following:

- `Screen resolution`
- `Screen resolution media query`
- `Available screen resolution`

7. load `https://arthuredelstein.github.io/tracking_demos/screen.html` and note the values being used
8. restart the browser and load`https://dev-pages.brave.software/fingerprinting/farbling.html` & `https://arthuredelstein.github.io/tracking_demos/screen.html`
9. note that the values should be different from the first time as `Block Screen Fingerprinting` has been enabled

#### Initial values before restarting the browser

**`Example`** | **`Example`**
---------------|------------------
![Screenshot_20221024-131453_Brave](https://user-images.githubusercontent.com/2602313/197586584-2d8ee89d-cd01-4e0a-81a9-e415a41486b1.jpg) | ![Screenshot_20221024-131508_Brave](https://user-images.githubusercontent.com/2602313/197586588-2daf5b9a-0496-49af-a071-a336d4a9ef59.jpg)

#### Confirmed that the values are different due to FP farbling

**`Example`** | **`Example`**
---------------|------------------
![Screenshot_20221024-131525_Brave](https://user-images.githubusercontent.com/2602313/197586708-c70c8a7f-35b7-4090-955b-411767938e6b.jpg) | ![Screenshot_20221024-131534_Brave](https://user-images.githubusercontent.com/2602313/197586719-60b93174-93eb-4568-9b31-ef6d19c08810.jpg)


</details>

### Case 3: BraveBlockScreenFingerprinting enabled - Shields Disabled - `PASSED`
<details>

1. installed `1.45.111 Chromium: 107.0.5304.62`
2. launched Brave
3. opened `brave://version`
4. confirmed no Griffin studies listed
5. enable `brave://flags#brave-block-screen-fingerprinting` via `brave://flags`
6. loaded `https://dev-pages.brave.software/fingerprinting/farbling.html` and disabled shields
7. clicked on `Generate fingerprints`
7. note the `This Page`, `Local Frame`, and `Remote Frame` values for the following:

- `Screen resolution`
- `Screen resolution media query`
- `Available screen resolution`

7. load `https://arthuredelstein.github.io/tracking_demos/screen.html` and note the values being used (disabled shields)
8. restart the browser and load`https://dev-pages.brave.software/fingerprinting/farbling.html` & `https://arthuredelstein.github.io/tracking_demos/screen.html`
9. note that the values should be the same due to `Brave Shields` being disabled on both websites
10. enable `Brave Shields` on both load`https://dev-pages.brave.software/fingerprinting/farbling.html` & `https://arthuredelstein.github.io/tracking_demos/screen.html`
11. note that the values should now be different as `Brave Shields` are enabled and FB farbling is occurring

#### Initial values before restarting the browser (Shields Disabled)

**`Example`** | **`Example`**
---------------|------------------
![Screenshot_20221024-132256_Brave](https://user-images.githubusercontent.com/2602313/197587948-1dec21f3-1539-43bb-bcc3-b9081d7f5803.jpg) | ![Screenshot_20221024-132302_Brave](https://user-images.githubusercontent.com/2602313/197587954-d125eb65-9d53-4403-b07e-e3ed367fdfcc.jpg)

#### Confirmed there was no farbling of the screen/window coordinates shown after the browser was restarted

**`Example`** | **`Example`**
---------------|------------------
![Screenshot_20221024-132319_Brave](https://user-images.githubusercontent.com/2602313/197588103-c15755de-e327-4e3c-a234-ecd9065203de.jpg) | ![Screenshot_20221024-132330_Brave](https://user-images.githubusercontent.com/2602313/197588111-c729ccd2-e892-4cb3-85ee-157a46527277.jpg)

#### Confirmed that the values are different due to FP farbling (Shields Enabled)

**`Example`** | **`Example`**
---------------|------------------
![Screenshot_20221024-132632_Brave](https://user-images.githubusercontent.com/2602313/197588542-63278b70-02c5-4895-9247-82d724bb3841.jpg) | ![Screenshot_20221024-132650_Brave](https://user-images.githubusercontent.com/2602313/197588549-a7e00c6d-0c8a-4969-b1c3-e983f8bb3972.jpg)

</details>
