### ISSUE TITLE
DApps: remove beta from a Wallet item menu

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#23238]
just leave `Wallet` there.

**Comment by kjozwiak** [comment]
The above requires `1.40.88` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
This seems broken on 1.40.101 build 
![image](https://user-images.githubusercontent.com/17010094/174281880-e73768a0-ab6d-49a2-9d89-12bb44b960e4.png)

**Comment by srirambv** [comment]
This seems to be an issue with non-US regions. With device locale set to US, it shows correctly

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.105 x64 build
- Verified the word `(beta)` is removed from menu entry for Wallet
- Verified changing locale to non-US region also show `Wallet` instead of `Wallet (beta)`

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/174617756-29343d8c-12d5-49e9-91cf-68971e4d31d9.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/174617898-16f792eb-61bd-407e-b6ed-6d72c40d6e90.png>
