### ISSUE TITLE
Update VPN support page

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#23290]
This issue is to update vpn support page as below, 

1. Other issues should be expanded by default
2. Currently other issues are checkbox so user can select multiple options which is not correct conceptually. We should add radio buttons which would give single selection for the issues. 
3. By default none of the other issues should be selected and in that case `Continue to email` should be disabled but as soon as user selects any issue `Continue to email`  should be enabled.

**Comment by kjozwiak** [comment]
The above will require `1.40.96` or higher for `1.40.x` verification 👍

**Comment by Uni-verse** [comment]
Verified in progress using

```
Brave	1.40.96 Chromium: 102.0.5005.115 (Official Build) beta (64-bit) 
Revision	174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS	Android 12; Build/SP1A.210812.016 
```

Acceptance Criteria: https://github.com/brave/brave-browser/issues/23290#issue-1262938740

- [x] Other issues is expanded by default.
- [x]  Other issues represented by `radio buttons` instead of checkboxes.
- [x] `- User is only able to make single issue selection. 
- [x]  None of the issues under `Other` should be selected by default.
- [x]  `Continue to Email` CTA is inactive until user selects an issue other than the issues under `Other`
- [x] Selecting `Other` issues will not enable `Continue to Email` CTA
- [x] User is able to expand/collapse the radio button group.
- [x] User is able to tap on the `Continue to Email` CTA to launch the email selection prompt.
- [x] Navigating back and re-entering support page will load default state. 

1 | 2
-|-
![screenshot-1655328063724](https://user-images.githubusercontent.com/17885425/173932446-2fb8472d-7d78-4f3e-83f1-877d6e50f036.png) | ![screenshot-1655328092270](https://user-images.githubusercontent.com/17885425/173932454-fd9bfe1b-94f9-4ae4-8b1e-5087aff91a0b.png)
