### ISSUE TITLE
Top sites like firefox

### ISSUE THREAD

**Issue by Arthur111** [brave/brave-browser#2330]
Hello,

Can you manage "Top Sites" page like Firefox ?

- Number of row in preferences.
- "Add Top Sites" in top site window
- "Pin", "Edit" etcc in each top site icons.

Thanks

**Comment by Arthur111** [comment]
In fact if you want "Top sites" being usable, just do as Firefox do and it will be nice because right now is unusable.

**Comment by bsclifton** [comment]
Closing as the issue is stale (no new information, etc) and there are similar reports which can be found in https://github.com/brave/brave-browser/issues/353

Specifically:
* Number of row in preferences https://github.com/brave/brave-browser/issues/6619
* Add / Edit top sites https://github.com/brave/brave-browser/issues/7493

"Pin" for existing top site tiles is already present and should be working
