### ISSUE TITLE
Rewards Summary section is showing incorrect Redeemed tip amount

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2332]
## Description 
Rewards Summary section is showing incorrect Redeemed tip amount

## Steps to Reproduce

1.    Launch brave with Clean profile
2.    Enable rewards through welcome page
3.    Restore a wallet
4.    Tip few sites (I have added 2 sites, tip amount is 1BAT for my test)
5.    Make sure redeemed tip amount is displayed correctly in `Rewards Summary` section
6.    Restart the browser
7.    Open any site and tip it (Tip amount is 1 BAT)
8.    Refresh the `Rewards` page
9.    Rewards summary section is showing the tip amount as `-1.0 BAT` instead of `-3.0 BAT`
  
## Actual result:
Rewards Summary section is showing incorrect Redeemed tip amount
![1- tipping issue](https://user-images.githubusercontent.com/38657976/49372760-b526cb00-f721-11e8-9b2c-3db93c9781c7.gif)

## Expected result:
Rewards Summary section should show correct Redeemed tip amount

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
-- | --
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

After step 6. Rewards summery is empty and shows proper wallet amount in contrast to what happened in original issue where Rewards summery was showing previous session.

After step 8. The Rewards summery shows -1, which is expected since Rewards summery was empty at step 6.

Reported https://github.com/brave/brave-browser/issues/3055 for Rewards summery not being retained between browser restarts.
