### ISSUE TITLE
Fix credentials fetching from prefs for VPN

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#23450]
## Description 

we have few lists in prefs and current code do not pass through all of them.  During work on https://github.com/brave/brave-browser/issues/20984 this became more important because 2 subsequent requests from web page and from vpn service have different results, for example request from page got credentials from server and next requests from vpn service cannot find it because the code takes only top of the list and do not go through the entire list of creds in prefs.

## Steps to Reproduce

   1. Connect/Disconnect few times
   2. Check prefs, there will be unexpired items in prefs
   3. In logs we will see requests to fetch new items

## Actual result:

VPN is not authorized

## Expected result:

Unexpired credentials will be taken from prefs

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
@spylogsster can you help us nail down what exactly we're looking for, for the unexpired credentials in the `Preferences` file and the UI?

Do we have to compare/validate timestamps in the `Preferences` file, or will this error show up in the UI, too?

And re: `in log we will see request to fetch new items` - are we talking here about the huge blob which starts like this?

`
[27548:259:0713/115639.471716:VERBOSE1:kv.rs(296)]   skus::storage::kv: got credentials, credentials: TimeLimitedCredentials { item_id: "bb7af46f-bda1-43db-92e2-526e7bd44b4c", creds: [TimeLimitedCredential...
`

Thanks!

**Comment by stephendonner** [comment]
Conferred with @spylogsster and we agreed that since this is now covered extensively by unittests, testing VPN end-to-end flows on our three environments would suffice.

**Comment by stephendonner** [comment]
## Verified `PASSED*` (see note for staging, below) using

Brave | 1.42.62 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
--|--
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 13.0 (Build 22A5295i)

### Shared steps:
1. install `1.42.62`
2. launch Brave
3. load `brave://flags`
4. set `brave://flags/#brave-vpn` to `Enabled`
5. set `brave://flags/#skus-sdk` to `Enabled`
6. click on the `restart` button
7. load `account.brave.software` for `development`, or `account.bravesoftware.com` for `staging`
8. enter the basic-auth credentials
9. enter a test email address and click `Get login link`
10. click on the link in the email
11. click on the `Browse plans` button
12. scroll down and click on `Buy now`, beneath the `Brave VPN Subscription` section
13. enter test credit-card details
14. finish checkout
15. click on the `VPN` button
16. click `allow` when prompted to add the `BraveVPN` config by macOS
17. click again on the `VPN` button
18. confirmed logged-in status



### `development` - `account.brave.software` - `PASSED`



`brave://flags` | `plan page` | `post-purchase` | `VPN button`
-|-|-|-|
<img width="1312" alt="Screenshot 2022-07-13 at 4 22 52 PM" src="https://user-images.githubusercontent.com/387249/178853605-74c13c2f-561a-40b7-a70a-3aec8be08c85.png"> | <img width="1312" alt="Screenshot 2022-07-13 at 4 23 31 PM" src="https://user-images.githubusercontent.com/387249/178853609-7b46ae28-60e1-4899-9e83-fe0d5c6db8f4.png"> | <img width="1312" alt="Screenshot 2022-07-13 at 4 24 13 PM" src="https://user-images.githubusercontent.com/387249/178853616-399c15ab-d3dc-4d03-8170-365ac5eb8a07.png"> | <img width="1312" alt="Screenshot 2022-07-13 at 4 24 35 PM" src="https://user-images.githubusercontent.com/387249/178853619-1704df78-cad3-471a-8009-04a9c9e71597.png">

### `staging` - `account.bravesoftware.com` - `FAILED*`

**NOTE:** staging is temporarily an expected `FAIL` due to the incorrect signing key being used on an endpoint, which should be fixed from tomorrow onward.  Details here: https://bravesoftware.slack.com/archives/C02ML9R5P1R/p1657119006580889.

`brave://flags` | `plan page` | `post-purchase` | `VPN button`
--|--|--|--
<img width="997" alt="Screenshot 2022-07-13 at 4 08 54 PM" src="https://user-images.githubusercontent.com/387249/178854346-7e1a44f6-f7c5-43e5-a183-c0b027424e11.png"> | <img width="1312" alt="Screenshot 2022-07-13 at 4 35 39 PM" src="https://user-images.githubusercontent.com/387249/178854711-8eeabc68-f9bf-49af-8214-8c898e882423.png"> | <img width="1312" alt="Screenshot 2022-07-13 at 4 36 40 PM" src="https://user-images.githubusercontent.com/387249/178854717-01f6a395-13f9-43f8-90e0-f4561fe5a541.png"> | <img width="1312" alt="Screenshot 2022-07-13 at 4 36 45 PM" src="https://user-images.githubusercontent.com/387249/178854722-4be5abcd-aa6f-439d-8857-bbbe1eb4e5d3.png">

**Comment by MadhaviSeelam** [comment]
Verification `In progress`

Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 11 Version 21H2 (Build 22000.795)


### Shared steps:
1. install `1.42.62`
2. launch Brave
3. load `brave://flags`
4. set `brave://flags/#brave-vpn` to `Enabled`
5. set `brave://flags/#skus-sdk` to `Enabled`
6. click on the `Relaunch` button
7. load `account.brave.software` for `development`, or `account.bravesoftware.com` for `staging`
8. enter the basic-auth credentials
9. enter a test email address and click `Get login link`
10. click on the link in the email
11. click on the `Browse plans` button
12. scroll down and click on `Buy now`, beneath the `Brave VPN Subscription` section
13. enter test credit-card details
14. finish checkout
15. click on the `VPN` button
16. click `allow` when prompted to add the `BraveVPN` config by macOS
17. click again on the `VPN` button
18. confirmed logged-in status


Step 6|
![image](https://user-images.githubusercontent.com/98358127/181792298-c734daae-290e-49f3-84ba-b74244eb0b88.png)
