### ISSUE TITLE
Brave extension keeps closed tabs' shields data in memory

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#23559]
This will allow memory to grow for this specific process (brave extension), unchecked.

STR:
- Open and close many tabs
- Observe brave extension memory growing for each opened tab (even if it is now closed)

**Comment by petemill** [comment]
Possibly related:
- https://github.com/brave/brave-browser/issues/9896
- https://github.com/brave/brave-browser/issues/21753
-

**Comment by kjozwiak** [comment]
The above will require `1.41.85` or higher for `1.41.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In-progress` using

Brave | 1.41.88 Chromium: 103.0.5060.70 (Official Build) beta (64-bit)
-- | --
Revision | 1543faf9f70e61c6f6e9c01ff20a2e3cf2ad55dc-refs/branch-heads/5060_53@{#4}
OS | Windows 11 Version 21H2 (Build 22000.739)

Verifying with testplan from https://github.com/brave/brave-core/pull/13872#issuecomment-1169570098

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 11.6.7 (Build 20G630)

### Steps
Followed @MadhaviSeelam's adaptation (above) of the original testplan: https://github.com/brave/brave-core/pull/13872#issuecomment-1169570098

Reproduced the original issue using `1.31.115.`. The only modification I did to https://github.com/brave/brave-browser/issues/23559#issuecomment-1172789201 was to run `20x`, instead of `45x+`.


### Max `Extension: Brave` memory usage (in MB):

`1.41.91` | `1.36.115`
---------|----------
`46.4` | `61.5`

`1.41.91` | `1.36.115`
------|----------
<img width="1680" alt="Screen Shot 2022-07-05 at 5 12 25 PM" src="https://user-images.githubusercontent.com/387249/177437437-3cdfa521-a2cf-4536-9ede-17b6c8fede58.png"> | <img width="1680" alt="Screen Shot 2022-07-05 at 5 15 46 PM" src="https://user-images.githubusercontent.com/387249/177437465-ef840dc7-38e1-4383-ab21-a323da30c236.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.93 Chromium: 103.0.5060.114 (Official Build) (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Linux

## Verified `PASSED` using 

Brave | 1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 11.6.7 (Build 20G630)

### Steps
Followed @MadhaviSeelam's adaptation (above) of the original testplan: https://github.com/brave/brave-core/pull/13872#issuecomment-1169570098

Reproduced the original issue using `1.36.115.`. The only modification I did to https://github.com/brave/brave-browser/issues/23559#issuecomment-1172789201 was to run `20x`, instead of `45x+`.


### Max `Extension: Brave` memory usage (in MB):

`1.41.91` | `1.36.115`
---------|----------


`1.41.91` | `1.36.115`
------|----------
