### ISSUE TITLE
Search engine option for Private shows invalid when current private search provider is deleted

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#23596]
## Steps to Reproduce

   1. Launch Brave
   2. Load brave://settings/search
   3. Set `Brave` as a Normal Window provider
   4. Set `Bing` as a Private Window provider
   5. Delete `Bing` by using Manage search engines and site search(brave://settings/searchEngines) page
   6. Check `Custom` is visible in Private Window option
   7. Open Private window and check normal window's search provider is used for private window
   8. After changing private window search option, it's configured to private window properly

## Actual result:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/6786187/174939128-ef8d5d80-4607-4a2e-84b7-095bb006520e.png">

## Expected result:
Private Window option should display Normal Window's provider by default

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.49 Chromium: 103.0.5060.70 (Official Build) nightly (x86_64)
-- | --
Revision | 1543faf9f70e61c6f6e9c01ff20a2e3cf2ad55dc-refs/branch-heads/5060_53@{#4}
OS | macOS Version 11.6.7 (Build 20G630)

Followed the original steps to reproduce.

### Confirmed after step 5, that deleting the `Bing` custom search engine restores it to `Brave`, rather than `Custom`.

example | example | example | example
---------|---------|----------|---------
<img width="1203" alt="Screen Shot 2022-07-01 at 10 48 40 AM" src="https://user-images.githubusercontent.com/387249/176945925-c91b08e6-cd42-45e0-9bbc-3c3edae42cef.png"> | <img width="1203" alt="Screen Shot 2022-07-01 at 10 48 48 AM" src="https://user-images.githubusercontent.com/387249/176945933-636e4ed3-f23a-4a5a-97a3-fe57e03e95e8.png"> | <img width="1203" alt="Screen Shot 2022-07-01 at 10 48 51 AM" src="https://user-images.githubusercontent.com/387249/176945942-c37dc0ab-89fb-4ee0-ae86-8e9779713237.png"> | <img width="965" alt="Screen Shot 2022-07-01 at 10 49 32 AM" src="https://user-images.githubusercontent.com/387249/176945945-7cd9a7f7-6fa1-4c52-a6f0-a6c86cbabc13.png">
