### ISSUE TITLE
Missed account address on Decrypt message screen and eTLD+1 isn't in bold

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#23651]
We are missing an account address on Decrypt message screen and `skiff.com` isn't in bold:
![Screenshot_20220623-160148_Brave - Debug](https://user-images.githubusercontent.com/12011303/175387214-2160cd9b-fc52-4f06-8b44-b072135ac8df.jpg)

**Comment by SergeyZhukovsky** [comment]
@diracdeltas not sure, @StephenHeaps and @nuo-xu to verify, that's the new screen related to skiff.org.
We recently added it on Android in that PR https://github.com/brave/brave-core/pull/13868. It's been uplifted to beta channel only, so it's not released like that in stable. I'm going to uplift the fix to beta as well.

**Comment by nuo-xu** [comment]
@diracdeltas iOS bolds eTLD+1 in those new requests. however, we are displaying account name instead of account address.
![sign message](https://user-images.githubusercontent.com/1187676/175405439-e8330e64-a88c-45f7-8005-a7e3c7a73dbe.png)
![decrypt message](https://user-images.githubusercontent.com/1187676/175405463-d7e2c1d0-dc04-4bb8-ac17-234e855f0f5a.png)
![add token](https://user-images.githubusercontent.com/1187676/175405504-a8114325-d7d6-4800-b8ba-1493040fae12.png)

I believe the design is displaying account name.

**Comment by SergeyZhukovsky** [comment]
We had a comment on Android sec review that every single screen has to have an account address visible. That issue is to align it for every other screen we have on Android. I see iOS doesn't have it for sign message screen as well. Anyways, let's open another issue for iOS if it's needed. @diracdeltas to confirm.

**Comment by StephenHeaps** [comment]
Yeah we can definitely update to include the full address on sign message, decrypt and get public encryption key requests too. Do you show the account address for Add Suggested Token request too, or just the token contract address?

**Comment by SergeyZhukovsky** [comment]
@StephenHeaps no Android doesn't show it for Add token, Add or switch network as they are not dependent on any account.

**Comment by StephenHeaps** [comment]
@SergeyZhukovsky thanks. 

We are currently showing the currently selected account address on Add/Switch Network, but not on the Add Suggested Token. It might make sense for us to remove the account / address here since they are not dependant on any account. cc @diracdeltas 

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-24 at 11 09 51](https://user-images.githubusercontent.com/5314553/175564415-da6926f8-cbce-47d2-a7cc-ee3c4ce1c4d8.png) | ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-06-24 at 11 09 53](https://user-images.githubusercontent.com/5314553/175564424-2a31ab00-0570-4bfc-a2ca-cf5e960dc204.png)
--|--
(this view is shared for add and switch network requests)

**Comment by kjozwiak** [comment]
The above will require `1.41.80` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.41.91 x64 build

- Verified steps from PR
- Verified account address is listed on decrypt screen
- Verified eTLD+1 is shown in bold on decrypt screen
- Verified Account name and address is below the eTLD+1 

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/177363679-d0a51b38-894c-4631-b2f4-93a70abf2b3a.mp4> | <video src=https://user-images.githubusercontent.com/17010094/177363707-ce995527-de0a-4d46-905a-7f81f4b5e817.mp4>
