### ISSUE TITLE
`verify_url` should be removed.

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#23682]
## Description

https://github.com/brave/internal/issues/829

**Comment by Uni-verse** [comment]
Verification in progress on Android ARM 

<details>
<summary>Uphold - PASSED</summary>

<details>
<summary>Scenario 1 - Verify from brave://rewards - PASSED</summary>

1. Clean profile, staging env
2. Enable Rewards
3. Navigate to brave://rewards
4. Select "Unverified"
5. Follow prompts and verify with custodian

Confirmed able to verify with Uphold from brave://rewards page:

1 | 2 | 3
-|-|-
![screenshot-1658869971881](https://user-images.githubusercontent.com/17885425/181115298-54e6997b-05b6-4686-944e-9b1603d75b6b.png) | ![screenshot-1658869795030](https://user-images.githubusercontent.com/17885425/181115955-2f38c76a-ecb3-47cb-9a64-f88ac8562e72.png) | ![screenshot-1658869857486](https://user-images.githubusercontent.com/17885425/181115992-20dababd-2144-435a-bff4-29b1e90fbd08.png)





</details>

<details>
<summary>Scenario 2 - Verify from rewards panel - PASSED</summary>

1. Clean profile, staging env
2. Enable Rewards
3. Open panel from BAT logo
4. Select "Unverified"
5. Follow prompts and verify with custodian

Confirmed able to verify with Uphold from panel:



</details>

<details>
<summary>Scenario 3 - Verify from brave://rewards after getting naturally disconnected - PASSED</summary>

1. Follow steps from scenario 1
2. Navigate to Uphold site and revoke integration for Brave Browser
3. Navigate back to brave://rewards and refresh if necessary to see the "Logged out" status
4. Click on "Logged out" and select "Login to your Uphold account"
5. Confirm able to reauthorize



Repeat steps 1-5, but in step 4 click on "Log in to Uphold to see your balance" blue box



</details>

<details>
<summary>Scenario 4 - Verify from rewards panel after getting naturally disconnected - FAILED</summary>

1. Follow steps from scenario 2
2. Navigate to Uphold site and revoke integration for Brave Browser
3. Open the panel to see the "Logged out" status
4. Click on "Logged out" and select "Login to your Uphold account"
5. Confirm able to reauthorize



Repeat steps 1-5, but in step 4 click on "Log in to Uphold to see your balance" blue box from panel



Repeat steps 1-5, but in step 4 click on "Reconnect" button from notification in panel



</details>

</details>

**Comment by Uni-verse** [comment]
Verification in progress on Android ARM Tablet using

```
Brave	1.42.65 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Android 12; Build/SP1A.210812.016
```

<details>
<summary>Uphold - in progress</summary>

<details>
<summary>Scenario 1 - Verify from brave://rewards - PASSED</summary>

1. Clean profile, staging env
2. Enable Rewards
3. Navigate to brave://rewards
4. Select "Unverified"
5. Follow prompts and verify with custodian

Confirmed able to verify with Uphold from brave://rewards page:

1 | 2 | 3


</details>

<details>
<summary>Scenario 2 - Verify from rewards panel - PASSED</summary>

1. Clean profile, staging env
2. Enable Rewards
3. Open panel from BAT logo
4. Select "Unverified"
5. Follow prompts and verify with custodian

Confirmed able to verify with Uphold from panel:
1 | 2 | 3

</details>

<details>
<summary>Scenario 3 - Verify from brave://rewards after getting naturally disconnected - PASSED</summary>

1. Follow steps from scenario 1
2. Navigate to Uphold site and revoke integration for Brave Browser
3. Navigate back to brave://rewards and refresh if necessary to see the "Logged out" status
4. Click on "Logged out" and select "Login to your Uphold account"
5. Confirm able to reauthorize

Repeat steps 1-5, but in step 4 click on "Log in to Uphold to see your balance" blue box

1 | 2
-|-


<details>
<summary>Scenario 4 - Verify from rewards panel after getting naturally disconnected - FAILED</summary>

1. Follow steps from scenario 2
2. Navigate to Uphold site and revoke integration for Brave Browser
3. Open the panel to see the "Logged out" status
4. Click on "Logged out" and select "Login to your Uphold account"
5. Confirm able to reauthorize

Repeat steps 1-5, but in step 4 click on "Log in to Uphold to see your balance" blue box from panel - FAILED

Repeat steps 1-5, but in step 4 click on "Reconnect" button from notification in panel - FAILED








</details>

</details>

<details>
<summary>Gemini - in progress</summary>

<details>
<summary>Scenario 1 - Verify from brave://rewards - PASSED</summary>

1. Clean profile, staging env
2. Enable Rewards
3. Navigate to brave://rewards
4. Select "Unverified"
5. Follow prompts and verify with custodian

Confirmed able to verify with Gemini from brave://rewards page:


</details>

<details>
<summary>Scenario 2 - Verify from rewards panel - PASSED</summary>

1. Clean profile, staging env
2. Enable Rewards
3. Open panel from BAT logo
4. Select "Unverified"
5. Follow prompts and verify with custodian

Confirmed able to verify with Gemini from panel:




</details>


<details>
<summary>Scenario 3 - Verify from brave://rewards after getting naturally disconnected - PASSED</summary>

1. Follow steps from scenario 1
2. Navigate to Gemini site and revoke integration for Brave Browser
3. Navigate back to brave://rewards and refresh if necessary to see the "Logged out" status (due to timing with Gemini, may have to wait up to 10 min)
4. Click on "Logged out" and select "Login to your Gemini account"
5. Confirm able to reauthorize

Repeat steps 1-5, but in step 4 click on "Log in to Gemini to see your balance" blue box

1 | 2 | 3





</details>

<details>
<summary>Scenario 4 - Verify from rewards panel after getting naturally disconnected - FAILED</summary>

1. Follow steps from scenario 2
2. Navigate to Gemini site and revoke integration for Brave Browser
3. Open the panel to see the "Logged out" status (may have to wait up to 10 min to see this due to timing with Gemini)
4. Click on "Logged out" and select "Login to your Gemini account"
5. Confirm able to reauthorize

Repeat steps 1-5, but in step 4 click on "Log in to Gemini to see your balance" blue box from panel - FAILED

Repeat steps 1-5, but in step 4 click on "Reconnect" button from notification in panel - FAILED

1 | 2
-|-





</details>

</details>

<details>
<summary>bitFlyer - in progress</summary>

Pre-req: Have region set to Japan

<details>
<summary>Scenario 1 - Verify from brave://rewards - PASSED</summary>

1. Clean profile, staging env
2. Enable Rewards
3. Navigate to brave://rewards
4. Select "Unverified"
5. Follow prompts and verify with custodian

PASS - Confirmed able to verify with bitFlyer from brave://rewards page:

PASS - Repeat steps 1-5  but select "Verify Brave Rewards" from brave://rewards onboarding:

1 | 2 
-|-

</details>

<details>
<summary>Scenario 2 - Verify from rewards panel - PASSED</summary>

1. Clean profile, staging env
2. Enable Rewards
3. Open panel from BAT logo
4. Select "Unverified"
5. Follow prompts and verify with custodian

PASS - Confirmed able to verify with bitFlyer from panel:

PASS - Repeat steps 1-5 but select "Verify Brave Rewards" from panel onboarding:

1 | 2
-|-

</details>

<details>
<summary>Scenario 3 - Verify from brave://rewards after getting naturally disconnected - PASSED</summary>

1. Follow steps from scenario 1
2. Wait at least 7 minutes, then attempt to tip a bitFlyer verified creator
3. Confirm you see "Logged out" status 
4. Click on "Logged out" and select "Login to your bitFlyer account"
5. Confirm able to reauthorize

PASSED - Repeat steps 1-5, but in step 4 click on "Log in to bitFlyer to see your balance" blue box

1 | 2 | 3
-|-|-



</details>

<details>
<summary>Scenario 4 - Verify from rewards panel after getting naturally disconnected - PASSED</summary>

1. Follow steps from scenario 2
2. Wait at least 7 minutes, then attempt to tip a bitFlyer verified creator
3. Confirm you see "Logged out" status 
4. Click on "Logged out" and select "Login to your bitFlyer account"
5. Confirm able to reauthorize

FAILED - Repeat steps 1-5, but in step 4 click on "Log in to bitFlyer to see your balance" blue box from panel

FAILED - Repeat steps 1-5, but in step 4 click on "Reconnect" button from notification in panel

1 | 2
-|-

</details>

</details>

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit)
-- | --
Revision | 212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```
