### ISSUE TITLE
[Android] Rewards settings `brave://rewards` page blank (v1.39.x and higher)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#23951]
## Description

https://community.brave.com/t/blank-page-in-brave-rewards/406301/3

This was fixed in the past here: https://github.com/brave/brave-browser/issues/21649 But it looks like the issue may be back.

**Comment by Saoiray** [comment]
Seems to be affecting other Users as well. 

https://community.brave.com/t/rewards-page-is-blank-so-unable-to-verify-phone/408645

https://community.brave.com/t/unable-to-access-brave-rewards-page/410991

https://community.brave.com/t/my-bat-disappeared-and-i-cant-view-my-reward-page/405238

**Comment by Miyayes** [comment]
Looks like it is repro'ing in 1.40.x+ as well, per reports above.

**Comment by Saoiray** [comment]
@Miyayes sorry for small delay. They said it persists even after restarting phone, force closing Brave, clearing cache, etc. Their devices pass SafetyNet.

One is/was using Android 6 on a Android vivo Y55s
Other is using Android 9 on Samsung galaxy S8+

There are others I should grab data from. Such as https://community.brave.com/t/cannot-reconnect-to-gemini-on-nightly-and-beta/414348 who said been having the issue since May. 

There was one Mattches was helping, so I don't know status, but Android 11 with issues. https://community.brave.com/t/blank-page-in-brave-rewards/406301?u=saoiray  (though they claimed leaving Brave anyway, so not sure if they'd respond)

**Comment by Miyayes** [comment]
Related to: https://github.com/brave/brave-browser/issues/16619

**Comment by Miyayes** [comment]
Hopefully will be resolved with https://github.com/brave/brave-browser/issues/24570, or at least more scrutable. cc: @zenparsing

**Comment by Areckleh** [comment]
+1 Community 
https://community.brave.com/t/error-configuracion-brave-rewards/425607/10
Issue persist on Brave 1.42.97
Issue does not persist on Nightly or Beta

**Comment by Miyayes** [comment]
https://github.com/brave/brave-browser/issues/24570 coming soon, which will expose error logs/console in brave://rewards settings page when React fails to load and page is blank.

**Comment by Miyayes** [comment]
Haven't heard this in awhile. Will close as stale and open a new issue.
