### ISSUE TITLE
[hackerone] wallet API freezing issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#23973]
https://hackerone.com/reports/1631867

**Comment by kjozwiak** [comment]
The above requires `1.42.81` or higher for `1.42.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
-- | --
Revision | `7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}`
OS | Linux

- Verified steps from issue description
- Verified permission prompt is shown instead of logging the value

https://user-images.githubusercontent.com/17010094/182080392-32817db4-2b49-4e37-ae75-555a5f30af5e.mp4



------------------------
Verification passed on

Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
-- | --
Revision | `7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from issue description
- Verified permission prompt is shown instead of logging the value


https://user-images.githubusercontent.com/17010094/182080002-48cb2b57-66b7-4123-9bc0-de0dc675efe8.mp4



------------------------
Verification passed on

Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (arm64) 
-- | --
Revision | `7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description
- Verified permission prompt is shown instead of logging the value

https://user-images.githubusercontent.com/17010094/182079733-42126634-cf41-4fd7-b561-32cafd2be4a8.mov
