### ISSUE TITLE
Remove `Get image description from Brave` context menu option

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24047]
## Description 

Remove `Get image description from Brave` context menu option

## Steps to Reproduce

   1. Enable On screen Narator
   2. Open any page and right click
   3. Shows option for `Get image description from Brave`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/178780718-d5fa5522-f664-40b2-ace6-a13756427c32.png)

## Expected result:
No such option.

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mkarolin @rebron

**Comment by kjozwiak** [comment]
The above will require `1.42.69` or higher for `1.42.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 10 Version 21H2 (Build 19044.1826)

Reproduced in 1.41.x
![image](https://user-images.githubusercontent.com/34715963/181002874-ca4fc6f9-9e28-457b-b456-091a914406c0.png)

Verified fixed in 1.42.x
![image](https://user-images.githubusercontent.com/34715963/181003005-8923d989-62e5-46d2-a351-6e7a140800f8.png)

**Comment by AndroidDeveloperLB** [comment]
I think it's also possible to remove it from the context menu by using this:

1. Go to chrome://flags/ 
2. disable " Use alternative route for image descriptions."
