### ISSUE TITLE
Facebook URL Tracking Parameters

### ISSUE THREAD

**Issue by manikandancode** [brave/brave-browser#24099]
Facebook has started to encrypt links to counter URL Stripping

Source: [GHack](https://www.ghacks.net/2022/07/17/facebook-has-started-to-encrypt-links-to-counter-privacy-improving-url-stripping/)

**Comment by pes10k** [comment]
After some initial exploration, it’s not clear to us whether what Facebook is doing is actually a privacy threat, or an implementation decision that does not meaningfully affect or threaten user privacy.
 
The core of the uncertainty is whether these encrypted (or possibly just opaque) values are used to transfer information (including likely user identifiers) between different pages and services on Facebook, or whether Facebook uses this information to re-identify users on non-Facebook sites (similar to the existing fbclid parameter that Brave has removed since 2020). If the former is the case, then this is not a new privacy concern; Facebook can already link user behavior across its own Facebook properties.
 
We’ll continue looking into it, but as mentioned, after half a day of looking into it, it appears that the former is the case, and that this is link decoration used for intra-Facebook navigation, and not a circumvention technique (at least in its current form). It is possible that the story has been semi-misreported by various sources. That said, we’re continuing to look into this and if we do identify a privacy harm, we will take whatever steps available to protect our users.

For now though, I'm going to close this as not-a-bug since everything we've found looking into this over the last month or two suggests that this does not allow Facebook to learn about Brave users when Brave users are not on Facebook.com. 

Thank you very much for taking the time to report!
