### ISSUE TITLE
[Android] India retention - swap VPN card for Ad Free Streaming card

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#24113]
**Summary**
Swap out the VPN promotion card with a card promoting Braves ad-free video streaming capabilities.

_VPN Card_
![image](https://user-images.githubusercontent.com/28269287/179565694-5497bbef-7754-4528-8443-78afee14707c.png)

**Why**
@anthonypkeane @timchilds @srirambv @tapanmodh @deeppandya @Pavneet-Sing met recently to discuss what we can do to improve our user retention rates in India. One of the changes agreed is that the VPN is currently way too expensive for the India market. Therefore we should not be promoting the VPN to new users so aggressively in India. On the flip side - the majority of users in India are using Brave to watch ad-free videos on streaming websites (e.g. YouTube). So we should promote the ad blocking / ad free videos feature instead.

**Comment by rmcfadden3** [comment]
@timchilds — if they're already using Brave, wouldn't they kinda get the ad-blocking value prop already? (Stop me if not.)

Wondering about a Playlist card here instead. I heard Petamber recently mention the phrase "downloader" or "offline downloader," so we could experiment with that.

Alternatively, we could test both cards?

**Comment by bradleyrichter** [comment]
We need to avoid any connections to "youtube downloader". They are banned from the play store.

**Comment by bradleyrichter** [comment]
Playlist is for offline playback, not downloading. It may not even be possible to get the cache off of your device.

**Comment by rmcfadden3** [comment]
@timchilds @bradleyrichter — these landing at all?

- Header: Brave Playlist
- Value prop 1: Ad-free videos, YouTube & more
- Value prop 2: Save for offline playback
- Value prop 3: Faster load on WiFi or data
- Value prop 4: Play in the background
- CTA: Make a playlist

- Header: Stream videos. Ad free.
- Value prop 1: No pre-roll ads
- Value prop 2: No mid-roll ads
- Value prop 3: No on-page ads
- Value prop 4: No interruptions
- CTA: Go to YouTube

**Comment by bradleyrichter** [comment]
We should bring @Sam-Sibley into this convo since he has been working on the new playlist intro screens.

**Comment by Sam-Sibley** [comment]
@rmcfadden3 Great i will do up a design based on this. The feedback i currently have is that for iOs I havent seen the terminology of "playback". I think we currently say "Offline use". Maybe thats because its shorter and less repetition of the word 'play'? But if you want to update that we can as the new Android Playlist feature will be coming your way shortly for copywriting, (along with Shared Playlist for iOS), so you can look at it all with fresh eyes when it does.

Should we target the 2nd option even further to only Youtube users (seeing as that is the vast majority of use case here) and make second heading be "Ad-free YouTube? seeing as our CTA is specific only for Youtube. Just feels slightly disconnected to me to be generic in the heading and specific in the CTA. 

And last minor point only - do users understand/know "pre-roll and mid-roll" terms? - are there more lay term for these? If not, ok, as i do like the repetition of the points you have to highlight how many different types of ads you get served. So there may not be a better way to say this.

**Comment by rmcfadden3** [comment]
@timchilds — yeah, that's a fair comment. But I don't think "pre-content" or "mid-content" hits the mark, either.

What about:

Header: Stream videos. Ad free.
Value prop 1: No ads _before_ your video
Value prop 2: No ads _during_ your video
Value prop 3: No ads on the page
Value prop 4: No interruptions
CTA: Go to YouTube

**Comment by Sam-Sibley** [comment]
@timchilds @rmcfadden3 @bradleyrichter  Just thinking through the logic here for when these will show. Not sure what logic the VPN currently uses and if youre looking to change that logic, but for these I suggest 

1.Ad-free version.
This could come after N days AND/OR visits to youtube is one or less than N. 
Have it appear early will minimise users getting a popup that isn't relevant to them as they're already streaming ad-free. 

And It should only appear on NTP so that use doesn't get it while actually on Youtube itself. As that would be annoying getting a popup directing you to youtube when already on youtube. Or alternatively we do a different CTA if they get it when on youtube. Also good to keep in mind in future the proposal is we will have Playlist onboarding on first load of youtube, so this has to work with that. 
 
 2. Playlist
 The CTA is make a Playlist, so this will need to be after user has added media but hasn't made a playlist. Or if user hasn't used playlist at all, can we have logic that displays a different CTA e.g. "open playlist" which takes them to playlist for first time so they experience its onboarding.

**Comment by rmcfadden3** [comment]
LMK once y'all confirm card logic and I can help with new copy as needed.

**Comment by Sam-Sibley** [comment]
<img width="861" alt="VPN popup replacement for india" src="https://user-images.githubusercontent.com/99699532/181689359-303fc821-4f86-4b39-92c9-02e130f83671.png">
@timchilds This is how the callout should look. And attached are the svg assets. 

And here is the fimga link in case its needed:
https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/Android-onboarding?node-id=4308%3A55243

![check-normal](https://user-images.githubusercontent.com/99699532/181689860-bb20d9da-2a54-4f1d-9249-473bdecfee50.svg)
![Confetti-light](https://user-images.githubusercontent.com/99699532/181689863-68bad3d6-90bf-4cd7-b515-fe0f47d3b452.svg)

We can sort out the logic and any button label as we go.

**Comment by deeppandya** [comment]
> @Sam-Sibley good point, I agree we should if possible change the card show logic. Especially if the VPN card logic does not make sense for this new ad-free streaming card.
> 
> @deeppandya please confirm the logic for when we show the VPN card? We can then decide if the logic needs changing for the India locale.
> 
> @Sam-Sibley let's take the playlist card discussion offline. That work will not be done as part of this ticket.

@timchilds @Sam-Sibley we show the vpn callout dialog when user doesn't have vpn subscription and opened the application 7 times.

**Comment by deeppandya** [comment]
@timchilds @Sam-Sibley what if we show the dialog on next app open if user has visited youtube on previous session and hasn't opened the app 7 times
because some users are not even aware that brave is doing something and that's why they are not seeing the ads on YouTube. 

So logic i have in my mind is : 
we should show the dialog for user on the next session if they have visited youtube on the previous session. and if user doesn't visit youtube till 7 app open event, we show the dialog anyway to notify them.

**Comment by Sam-Sibley** [comment]
@rmcfadden3 Re: the CTA, we are no longer directing users to Youtube because we have been removed the Play Store for previous similar things. I suggest changing the CTA to something generic like "Nice!", "Got it!" or "Awesome" etc. Let me know what you want in there and i will add it into the design.

FYI @timchilds

**Comment by rmcfadden3** [comment]
@Sam-Sibley — sorry for the delayed reply. Was on PTO all last week.

Anyways, yeah, fair point. So what if the CTA button instead said either "Start browsing" or "Start streaming" or "Start watching" and just directed the user into NTP? That's slightly more actionable than a "Got it!" or similar, which is kind of a dead end.

Also, side note. I saw in [the mocks you pasted in 11 days ago](https://github.com/brave/brave-browser/issues/24113#issuecomment-1198898940), that the 3rd and 4th bullets are repeated (with "No ads on the page" shown twice). Note that per the copy I dropped [earlier in this thread](https://github.com/brave/brave-browser/issues/24113#issuecomment-1196158119), the 3rd should be "No ads on the page" while the 4th should be "No interruptions" …

**Comment by rmcfadden3** [comment]
@Sam-Sibley and I just discussed via Slack… We're rolling with "Search for videos" as actionable CTA button copy, which opens new tab and autofocuses there.

**Comment by Sam-Sibley** [comment]
@tapanmodh @anthonypkeane @timchilds 

As per Ryans comment above, here is the updated designs.

<img width="794" alt="VPN popup replacement for india_updated" src="https://user-images.githubusercontent.com/99699532/184053044-5287f793-d450-401b-be7b-9b26af84f36d.png">
.

**Comment by Sam-Sibley** [comment]
And here is the final figma file:

https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/Android-onboarding?node-id=4308%3A55243

**Comment by rmcfadden3** [comment]
YES! These look great, @Sam-Sibley !

**Comment by Sam-Sibley** [comment]
As per discussion with @rmcfadden3 and @tapanmodh updating headline in mockup to match what Ryan has written. New screens attached.
<img width="837" alt="VPN popup replacement for india_updated_Android" src="https://user-images.githubusercontent.com/99699532/185019388-23308ac2-6043-4911-9d65-1fbd7ac17ecf.png">
.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `vivo x70 Pro` version 12 running `Bravemonoarm64.1pk_1.45.108`

- Verified the test plan from https://github.com/brave/brave-core/pull/14437

Light theme | Dark theme
-- | --
![Screenshot_20221021_155123](https://user-images.githubusercontent.com/38657976/197174757-eb6522d0-4a45-44e7-94c9-f539c496b304.jpg) | ![Screenshot_20221021_155307](https://user-images.githubusercontent.com/38657976/197174788-c52fd603-2dde-4c6a-a965-2aee06633f80.jpg)
