### ISSUE TITLE
Farbled HTTP Accept-Language header does not have a q value

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#24126]
The initial design of Accept-Language farbling specified that, in aggressive anti-fingerprinting mode, the value should always be "en-US,en". However, webcompat testing has since revealed that some frameworks react poorly to the lack of a q value.

Suggest we change the aggressive value to "en-US,en;q=0.9" which matches a Chromium's default behavior for en-US users.

**Comment by kjozwiak** [comment]
The above requires `1.42.81` or higher for `1.42.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (x86_64)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | macOS Version 12.5 (Build 21G72)
```

**Comment by Uni-verse** [comment]
Verification in progress on `Samsung Galaxy S21` & `Samsung Tab S7` using

```
Brave	1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
Revision	7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS	Android 12; Build/SP1A.210812.016
```

**Comment by Uni-verse** [comment]
Verification in progress on `Samsung Galaxy Tab S7` using

```
Brave	1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
Revision	7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS	Android 12; Build/SP1A.210812.016
```
Refered to Testing Plan in https://github.com/brave/brave-core/pull/14235#issuecomment-1197362624

Went through the STR/Cases outlined via https://github.com/brave/brave-core/pull/14235#issue-1309718872 and ensured that all the cases via https://dev-pages.brave.software/fingerprinting/headers.html were working as per the following:

**brave://version**

<img width="250" alt="0" src="https://user-images.githubusercontent.com/17885425/181626044-796be0bd-5036-438b-854c-1acc8d9de10a.png">

Language FP enabled & Block fingerprinting (Default)

<details>

ensured that the value under Headers matches the first language set via brave://settings/languages

Example | Example | Example 
-|-|-



</details>

Language FP enabled & Allow fingerprint (Disabled)

<details>

ensured that the value under Headers matches the first language set via brave://settings/languages

Example | Example | Example 
-|-|-


</details>

Language FP enabled & Block fingerprinting (Aggressive)

<details>

ensured that the value under Headers always displays en despite the languages listed under brave://settings/languages

Example | Example | Example 
-|-|-


</details>

<hr>

Because Android doesn't have the Prevent sites from fingerprinting me based on my language preferences toggle implemented like desktop, went through the below after disabling brave://flags#brave-reduce-language.

<img width="250" alt="0" src="https://user-images.githubusercontent.com/17885425/181629079-cbae6279-0705-4c4f-845e-b63d9cc1aeef.png">

Language FP disabled & Block fingerprinting (Default)

<details>

ensured that all the languages are being displayed via the Header as Accept-Language has been disabled

Example | Example | Example 
-|-|-



</details>

Language FP disabled & Allow fingerprint (Disabled)

<details>

ensured that all the languages are being displayed via the Header as Accept-Language has been disabled

Example | Example | Example 
-|-|-


</details>

Language FP disabled & Block fingerprinting (Aggressive)

<details>

ensured that all the languages are being displayed via the Header as Accept-Language has been disabled

Example | Example | Example 
-|-|-


</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.42.84 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
Revision	7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS	Linux
```
