### ISSUE TITLE
Support dynamic P3A metric names

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#24318]
## Description 

We'd like to be able to use the P3A reporting channel for ephemeral metrics. Currently we use a static list of histogram names to determine which measurements to report.

This should be replaced by a dynamic list, initialized from (or overlaid on) the current static list, offering methods to register and retire new metrics at runtime:
```c++
bool BraveP3AService::RegisterMetric(base::StringPiece metric_name, base::Time expires);
void BraveP3AService::RemoveMetric(base::StringPiece metric_name);
```
Metrics names would be stored in the permission list with an expiration date and automatically stop reporting after that. This gives us more control of the reporting window and better protects users from unnecessary reports.

## Motivation

We'd like to use this feature to report usage of various dynamic elements of the New Tab Page, so we need to be able to generate unique metric names at runtime. Since dynamic metric names are a requirement only for this project, and will likely be routed to a different analysis path, the registration code should also apply a policy limiting registered network names to a particular prefix, e.g. `Brave.NTP.*`.

**Comment by rillian** [comment]
Related to #13068. cc @jsecretan, @mattmcalister, @DJAndries, @iefremov

**Comment by iefremov** [comment]
Initially the static list was only intended for manual setting histogram change callbacks. We probably can simplify by setting a callback for every histogram that name starts with `Brave.` or something like that. And keep the list only for original chromium histograms if we use any

**Comment by rillian** [comment]
Ah, thanks. That's an excellent downscope from what I proposed.

Do we need to be concerned about duplicate observer registrations?

**Comment by DJAndries** [comment]
> Do we need to be concerned about duplicate observer registrations?
We currently register one callback per histogram (see `BraveP3AService::InitCallbacks`).

The tricky part with @iefremov 's suggested approach: Generating a list of Brave metrics at runtime. I haven't found any Chromium function that could help us with this. It seems that even Chromium keeps a static list for histograms, i.e. https://source.chromium.org/chromium/chromium/src/+/main:tools/metrics/histograms/metadata/others/histograms.xml

Here are some modified methods we could consider for metric suspension/expiration, if we do happen to take this approach.

```
void BraveP3AService::SetMetricExpiry(base::StringPiece metric_name, base::Time expiry_time);
void BraveP3AService::RemoveMetric(base::StringPiece metric_name);
```

If this approach is not possible, @rillian 's approach seems sensible. I suggest that we keep the static list so that we don't need to keep a reference to `BraveP3AService` throughout all the various components.

**Comment by rillian** [comment]
This seems to work for enumerating histograms at runtime:
```c++
  for (base::HistogramBase* item: base::StatisticsRecorder::GetHistograms()) {       
      DLOG(INFO) << item->histogram_name();                                            
    }  
```
But only 28 `Brave.*` names show up at BraveP3AService::Init() time, so looks like we'd have to re-run the enumeration every time we generate the log. And convert BraveP3AService::histogram_sample_callbacks_ to a map so we don't register duplicates. Also means we'd miss events and need to explicitly pole when generating a new log?

**Comment by DJAndries** [comment]
Yes, good find. I found that method as well but hit the same problem. Wondering if this approach is worth the hassle, compared to having a static list + `RegisterMetric`/`RemoveMetric` functions.
