### ISSUE TITLE
Brave News Popular Sources Recommendations

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#24324]
- Each item in sources.json will have a `rank` field (different from today’s `score` field (although I don’t know what that’s for as it isn’t used by the client).
- In the new “Customize” dialog, there are 2 ways these items surface
  - When clicking the Popular Sources”“card”, a screen will be shown with all sources in order of popularity. This will always be the same list and not hide items that the user is already subscribed to (via directly or via a channel).
  - A carousel of 3 Popular Sources will be shown, offering the user to subscribe. These will also not hide if the user is already subscribed to them.

**Comment by fallaciousreasoning** [comment]
FYI pete, just starting on this now.

**Comment by kjozwiak** [comment]
The above will require `1.46.100` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.100 Chromium: 107.0.5304.91 (Official Build) dev (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:

1. installed `1.46.100`
2. launched Brave
3. clicked on `Skip welcome tour`
4. opened `brave://flags`
5. set `brave://flags/#brave-news-v2` to `Enabled`
6. clicked on `Relaunch`
7. opened a new-tab page
8. clicked on `Customize`
9. clicked on `Brave News`
10. clicked on `Turn on Brave News`
11. clicked on `View All` just above the last `Popular` card

#### Confirmed clicking on `View All` on the Popular sources section expanded to show me them all

`Light` | `Dark`
--------|-------
<img width="1312" alt="Screen Shot 2022-11-08 at 9 32 49 AM" src="https://user-images.githubusercontent.com/387249/200635193-915a6968-54fd-4467-bc11-676f5d02aa6d.png"> | <img width="1312" alt="Screen Shot 2022-11-08 at 9 32 30 AM" src="https://user-images.githubusercontent.com/387249/200635259-3aae960b-2eaa-4794-9f0d-660ddaed6407.png">

**Comment by Uni-verse** [comment]
Verification in progress on Android ARM using the following version(s):

Brave	1.46.110 Chromium: 107.0.5304.110 (Official Build) beta (64-bit) 
Revision	2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS	Android 12; Build/SP1A.210812.016

Since News V2 is targeted for 1.48 on Android and the flag will not be enabled for 1.46.x, just making sure the News feature is working as expected is sufficient. 

- Ensured Brave News onboarding is shown on
- Ensured Enabling Brave News will show feed on NTP
- Ensured user is able to add and remove custom sources
- Ensured user is able to enabled/disable news sources 
- Ensured user can disable content from the feed cards via the context menu > Disable content from {source}
- Ensured that scrolling through the news feed is smooth and maintains feed position when switching tabs

Example | Example | Example
-|-|-
![screenshot-1668798261654](https://user-images.githubusercontent.com/17885425/202786570-378c0a5d-edb2-4899-ab28-6bf2ef477dce.png) | ![screenshot-1668799617718](https://user-images.githubusercontent.com/17885425/202786525-a0e9c144-4d5b-418d-bcda-a78e01c28ded.png) | ![screenshot-1668798319729](https://user-images.githubusercontent.com/17885425/202786573-fb4d8c9f-0ec4-452b-ab32-6f4c82704ba9.png)
