### ISSUE TITLE
Braver - a braver Brave fork

### ISSUE THREAD

**Issue by flywire** [brave/brave-browser#24346]
The enthusiasm for Brave soon wanes when a user realises the functionality they rely on in other browsers has been removed. Not just turned off by default to disable it, but totally removed so it can't be used in Brave. For example:

1. #208
2. #13902 

**Braver**, _real_ brave, all the functionality of Brave keeping the features users need.

**Comment by IronMaltese** [comment]
Do you just want these features in brave?

**Comment by flywire** [comment]
No, I can see translation will eventually be delivered. My concern is features users rely on are just removed so I can't trust Brave.

**Comment by arch-user-france1** [comment]
You're basically advertising "braver"

**Comment by proffalken** [comment]
I mean, I'm all for getting these features enabled, but the last update for Braver looks like it was a README change two years ago.

If Braver is going to give me Brave without disabling features that are becoming part of the web's standard way of working (regardless of whether the developers oppose them or not) then I'm happy to switch, but it has to provide security updates as part of that work as well!

**Comment by arch-user-france1** [comment]
Brave does not disable web-standard features at all, what are you talking about. Do you know what you are talking about?
The web serial API was disabled because it is a huge security problem. Every standard human does not need this feature anyway! It also is not enabled in Safari and Firefox. Only google has it enabled. It's a stupid idea to enable users to have that by default. 
Having this disabled won't harm your use experience.

And #208 is already supported.

You're advertising a project in a GitHub issue.

**Comment by proffalken** [comment]
I've got nothing to do with braver, didn't even know it existed until today, just wondered if it was still actively maintained.

Apparently questioning the choices of those who maintain a browser that's supposed to be all about choice is not allowed.

Shame.

I'll wend my merry way off to another browser.

So long brave, it's been fun...

**Comment by arch-user-france1** [comment]
> I've got nothing to do with braver, didn't even know it existed until today, just wondered if it was still actively maintained.
> 
> Apparently questioning the choices of those who maintain a browser that's supposed to be all about choice is not allowed.
> 
> Shame.
> 
> I'll wend my merry way off to another browser.
> 
> So long brave, it's been fun...

Oh okay well then, have fun trying to search for an open source browser that supports webusb and webserial.
You won't find any good one. The propietary stuff might support it because usually, they only want profit, control and popularity.

So you can now close this issue. You're not using brave anymore, no reason making pressure.

**Comment by arch-user-france1** [comment]
> No, I can see translation will eventually be delivered. My concern is features users rely on are just removed so I can't trust Brave.

There are none removed on which users rely on.

**Comment by flywire** [comment]
@arch-user-france1, Can you troll somewhere else? I'd appreciate you deleting your comments too.

Some alternative browsers: [ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium), [Otter Browser](https://otter-browser.org/), [LibreWolf](https://librewolf.net/).

**Comment by arch-user-france1** [comment]
You're not achieving anything with this.
By the way, LibreWolf does NOT support WebSerial! You could just close your "issue" - this is not an issue at all, just something trying to get users away from Brave. Do that in a youtube video or whatever but not to disturb developers trying to figure out where your nonexistent issue is.
