### ISSUE TITLE
Is dark mode real?

### ISSUE THREAD

**Issue by gisselacornejocastellano** [brave/brave-browser#24371]
In Brave's page, it says that Brave browser has a Dark Mode that "Protect[s] against eye strain by **setting web pages to automatically load with a darkened background**" and that it is available on desktop, Android, and iOS. However, I am using Brave Browser in Windows and it only has a option named "Brave colors", but when set to "Dark" it does not set any web page with a darkened background. Are we missing something?

**Comment by UjCbFwtBayFM** [comment]
Could you provide an URL that does not switch to dark mode?

**Comment by faandg** [comment]
Correct me if I'm wrong but I think that, even if it is your preference, the website still needs to support it also by having a dark theme and leveraging your browser preference setting.
There are websites, like Jira, which only have a paid dark mode (are you kidding me...) or none at all because they don't feel like maintaining it.

If, like me, staring at white pages all day gives you headaches :( , you can browse to `brave://flags/`, search for `Auto Dark Mode for Web Contents` and set it to `enabled`.
Note that this will invert colors and some images and text displays poorly, but most is OK.

Alternatively, there are extensions which have community maintained custom CSS theme sets for specific popular websites which can also be leveraged.

**Comment by rebron** [comment]
Hi @gisselacornejocastellano That describes the dark mode options we have for Brave Browser on Android. We have a dark mode theme for Brave Browser on Desktop (Windows, macOS, and Linux) and @faandg described the flags available that are experimental in the previous comment.
