### ISSUE TITLE
Put webserial functionality behind a flag

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#24404]
As mentioned in #15637 WebSerial was disabled (in https://github.com/brave/brave-browser/issues/13902). It seems that a lot of users would like to be able to enable this in their browser in order to update the firmware of some devices.

Right now, there is an option which claims to enable this functionality (e.g. `brave://settings/content/siteDetails?site=https%3A%2F%2Fgithub.com`):
![Screenshot from 2022-08-02 18-20-53](https://user-images.githubusercontent.com/167821/182503952-d5cafb56-b4dc-4770-9587-271c4c02014a.png)

but it doesn't do anything because it's [fully disabled](https://github.com/brave/brave-core/blob/084c5b1d8fa534192501e874098d1b70503cfe6b/renderer/brave_content_renderer_client.cc#L51).

We should provide a flag in `brave://flags` (default off) to allow users who need it to enable it. When that flag is off, it should remove the *Ask* and *Ask (default)* options in `brave://settings/content/siteDetails`, as we [plan to do for all disabled features](https://github.com/brave/brave-browser/issues/18417).

**Comment by 7ombie** [comment]
Regular users should not need to dig through `chrome://flags` to enable a powerful webapp. A persistent, per-domain, opt-in would be cool, and seems manageable, given that very few sites need it.

It may be enough to have a (per-domain) catch-all permission for powerful APIs, given that the dangers of enabling one powerful API are generally the same as the enabling the others. A user will either trust the site (and enable everything it requests) or not trust it (and reject everything), in the same way that users either install an app or don't install it.

P.S. I'm personally using Safari to browse, and Chrome for hacking, and would love to consolidate and just use Brave.

**Comment by 7ombie** [comment]
If it was possible to reliably know when an app tried to use a power-API and failed, those specific exceptions could trigger a dialog, which could then refresh the page with the APIs enabled, assuming the user wanted to enable them for that origin.

The problem is that a lot of apps feature test, so if the API is not defined, they will not try to use it (instead prompting the user to switch browser). However, if the APIs were defined, but just threw (dialog-triggering) exceptions as soon as you tried to use them, that would only require Brave-specific exceptions.

Brave-specific exceptions would not create any issue (in this context), if the user grants the permission during the dialog, as the page is refreshed with the APIs available. However, if the user rejects the request, then a completely unexpected, non-standard exception will be raised in otherwise perfectly valid code. The result of that would be unpredictable.

The dialog could *always* refresh the page, either with the APIs fully enabled (as in Chrome) or completely unavailable (as in FireFox and Safari).

Users would only see the dialog the first time they visit the app, and there could be a little UI element in Brave to indicate whenever a page is privileged or expressly unprivileged (allowing users to change the setting).

Note: Users who don't want these APIs enabled at all could disable them globally in the settings, and they would not get any dialogs, as the relevant APIs would always appear unimplemented. This should be the default setting for as long as these APIs remain Chrome-specific.

**Comment by nicoandmee** [comment]
> Deep-sixing Brave and moving to Opera. It allows the use of webserial. Since the Brave developers aren't brave enough to trust the user to make an informed decision it's good-bye to Brave. This issue is years old and the continued resistance to allow the user to make the decision shows the cowardice of Brave.

I love Brave for the good parts but have to agree. It's similar to how there's no way to disable the `This file can harm your computer` message. 

I am not five years old
