### ISSUE TITLE
Remove support for legacy anonymous Uphold cards

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#24464]

**Comment by LaurenWags** [comment]
Discussed the following with @szilardszaloki and @GeetaSarvadnya re: test plan:

<details>
<summary>Desktop</summary>

Using [description from PR](https://github.com/brave/brave-core/pull/14536#issue-1332182729) as a guide:

Backup/Restore Modal:
- confirm the anon user funded specific-variant for backup tab of backup/restore modal does not show on upgraded or clean profiles (pictured on PR)
- confirm the regular backup tab of backup/restore modal does display as expected

Backup Notification:
- skip as this has been dead code for some time (will not be able to trigger) 

P3A:
- confirm 1.43.x does have these questions
- using a new profile, confirm 1.44.x does not have these questions
- not necessary to test upgraded profiles for P3A 

Prefs:
- skip, unable to test 

Anonymous wallet/user funds processor references in the contribution engine:
- check 1 time tips, monthly tips, and AC all contribute/work as expected for anon vBAT funded and applicable custodians (ex. bF does not have AC)

`POST /v1/orders/{order_id}/transactions/anonymousCard` endpoint implementation
- skip, unable to test

`GET /v3/wallet/uphold/{payment_id}` endpoint implementation
- check tipping, covered above

Balance fetch
- confirm balances from anon vBAT funded and custodians are displayed appropriately, can be checked as part of `Anonymous wallet/user funds processor references in the contribution engine`

Uphold linking
- confirm able to link Uphold, can be checked as part of `Anonymous wallet/user funds processor references in the contribution engine`

Wallet creation
- confirm able to join rewards and get a valid paymentID, can be checked as part of `Anonymous wallet/user funds processor references in the contribution engine`

Wallet recovery
- confirm unable to restore an old anon, user funded wallet using restore words, can be checked as part of `Backup/Restore Modal` above

</details>

<details>
<summary>Android</summary>

Using [description from PR](https://github.com/brave/brave-core/pull/14536#issue-1332182729) as a guide:

Backup/Restore Modal:
- I don't believe backup/restore is generally available on Android outside of QA Prefs, so for that confirm unable to restore an old anon, user funded rewards wallet using restore words

Backup Notification:
- skip as this has been dead code for some time (will not be able to trigger) 

P3A:
- confirm 1.43.x does have these questions
- using a new profile, confirm 1.44.x does not have these questions
- not necessary to test upgraded profiles for P3A 

Prefs:
- skip, unable to test 

Anonymous wallet/user funds processor references in the contribution engine:
- check 1 time tips, monthly tips, and AC all contribute/work as expected for anon vBAT funded and applicable custodians (ex. bF does not have AC)

`POST /v1/orders/{order_id}/transactions/anonymousCard` endpoint implementation
- skip, unable to test

`GET /v3/wallet/uphold/{payment_id}` endpoint implementation
- check tipping, covered above

Balance fetch
- confirm balances from anon vBAT funded and custodians are displayed appropriately, can be checked as part of `Anonymous wallet/user funds processor references in the contribution engine`

Uphold linking
- confirm able to link Uphold, can be checked as part of `Anonymous wallet/user funds processor references in the contribution engine`

Wallet creation
- confirm able to join rewards and get a valid paymentID, can be checked as part of `Anonymous wallet/user funds processor references in the contribution engine`

Wallet recovery
- confirm unable to restore an old anon, user funded wallet using restore words, can be checked as part of `Backup/Restore Modal` above

</details>

<details>
<summary>iOS</summary>

Since Rewards is scaled back on iOS, using a clean profile confirm able to join Rewards/opt-in to viewing ads. Use the QA page to confirm paymentID is created as expected. Confirm able to view ads and be rewarded for them.

On upgrade profile, confirm opt-in status for Rewards/Ads (check both opted-in and not opted-in). Confirm if opt-ed in, your paymentID is the same before and after upgrade. Confirm you can still view ads after upgrade.

</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 12.5.1 (Build 21G83)
```

**Comment by Uni-verse** [comment]
@kylehickinson

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo x70 pro with android version 12` running `Bravemonoarm64.apk_1.45.44`
