### ISSUE TITLE
Brave Wallet shouldn't write properties from ethereum provider object

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#24531]
Currently Brave would write **ALL** properties of `window.ethereum` multiple times even default wallet setting is "Prefer Extensions"
1. when page loaded
2. when users change network on Brave wallet or account changed.
3. when uses triggered [`accountsChanged`](https://wallet-docs.brave.com/ethereum/provider-api/events#accountschanged)

Note that 1st scenario doesn't require users action, here is an example that it interferes with extensions like MetaMask
1. Set default wallet setting to "Prefer Extensions"
2. Set network on Brave Wallet to Polygon(0x89) and set network on MetaMask to Mainnet(0x1)
3. Load simple page like https://example.com/
4. Open console and type `ethereum.chainId`
5. We would see `0x89` instead of `0x1`

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [brave/brave-core#14539](https://github.com/brave/brave-core/pull/14539) & regression test
- Verified chainid is `0x1` instead of `0x89`

https://user-images.githubusercontent.com/17010094/186739996-755fad58-1cbe-4431-82aa-2a8f2606fdcf.mp4

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14539](https://github.com/brave/brave-core/pull/14539) & regression test
- Verified chainid is `0x1` instead of `0x89`

https://user-images.githubusercontent.com/17010094/186741518-0b5f6f96-46e9-4691-b56b-65f0b82f1fa0.mp4

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (arm64)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14539](https://github.com/brave/brave-core/pull/14539) & regression test
- Verified chainid is `0x1` instead of `0x89`

https://user-images.githubusercontent.com/17010094/186741005-9a5df02c-6092-490a-a3ad-ba7921099047.mov
