### ISSUE TITLE
Always show Dylan Malval's image as a first background image after launch

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#24583]
## Description 

Set Dylan Malval's image as a first background image after launch

## Steps to Reproduce

   1. Launch Brave and make sure there is no opened NTP
   2. Open first NTP
   3. Check its background image is `Dylan Malval`'s image

## Actual result:

<img width="400" alt="Screen Shot 2022-08-11 at 1 28 55 PM" src="https://user-images.githubusercontent.com/6786187/184064867-04adfcab-532d-40b7-948e-47a88ae0964a.png">

## Expected result:
<img width="400" alt="Screen Shot 2022-08-11 at 1 27 54 PM" src="https://user-images.githubusercontent.com/6786187/184064805-74ac9023-2318-4789-b3a5-115c2858ade2.png">

**Comment by simonhong** [comment]
Verified with dev component with `--dev-go-updater-url`.

**Comment by simonhong** [comment]
Fixed with `NTP Background Images - Version: 1.0.7`

**Comment by simonhong** [comment]
I set this milestone to currently available release milestone (1.42.x - Release #3) as background images component update is applied to all channels.

**Comment by kjozwiak** [comment]
@simonhong quickly went through the above and noticed the following two things:

### `Case #1` - NTP SI being opened second rather than 4th

From what I remember, NTP SI should always be opened on the 4th tab. I don't exactly remember if the second tab should always be a NTP SI when launching a new profile. If that's the case, then this isn't an issue/problem 👍 

https://user-images.githubusercontent.com/2602313/184278972-e0e5e81b-9f16-4a2c-907f-db8861ba75be.mp4

### `Case #2` - Opening several NTP quickly right after launch will use the same tab

When you open a few NTP right away once the browser launches, it opens the same tab several times. However, I think it's probably related due to the images still not being pulled/downloaded via the component, hence using the image from `Dylan Malval` as the default until the new images are downloaded/ready to use. So pretty sure this isn't any issue.

https://user-images.githubusercontent.com/2602313/184279109-f558dfdb-7c37-4304-a884-875cbda281cf.mp4

@simonhong I guess we just need calcification in the first case. Second case is expected behaviour 👍

**Comment by simonhong** [comment]
@kjozwiak Thanks for checking! I think above both cases are all expected behavior.
For case 1, second NTP can show NTP SI with fresh profile.
For case 2, it's possible if background images component is not ready.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.42.95 Chromium: 104.0.5112.81 (Official Build) (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```
- Verified the STR from the decsription and ensured `Dylan Malval's` is displayed as the first backgroung image when 1st NTP is opened after the browser launch
- If I wait for enough time (until component load) the oder of NTP ST is shown in the order (2th NTP, 4 NTP, 8NTP etc...)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.42.95 Chromium: 104.0.5112.81 (Official Build) (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Ubuntu 18.04 LTS

Verified the Dylan Malval image is default after launch
![image](https://user-images.githubusercontent.com/34715963/184642079-73b8776b-bba9-4a5c-ae1c-b81da9dd3388.png)

Verified NTPSI is shown on 2nd 6th 10th etc NTP
