### ISSUE TITLE
[hackerone] performance.now and other timing APIs are fingerprinting vectors

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#24681]
## Description 
From [joe12387](https://hackerone.com/joe12387):

> performance.now() can be used to create a persistent cross-site tracking fingerprint...

> This code allows you to track a user from site to site, it does not detect if a user is using Brave. My fingerprint is [0.09999990463256836, 0.10000014305114746], while other machines will have a different value. 

> This is very easy to fix, all you have to do is round the output of performance.now() into an integer and the script will always return [1,1].

## Steps to Reproduce

See https://github.com/Joe12387/OP-Fingerprinting-Script/blob/b4b196f5a6196bacf2dc041b064f877dafafface/opfs.js#L443

See also: #2952

**Comment by arthuredelstein** [comment]
cc: @diracdeltas @pes10k

**Comment by arthuredelstein** [comment]
What I have learned so far:
performance.now() and related high-resolution timers are clamped to 100-us resolution in Chrome EXCEPT where 
```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```
in which case the timing values are clamped to 5-us resolution.

These two resolutions are [specified in Chrome](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/timing/time_clamper.h;l=21;drc=25519cd7fed2a72ae858cc79fd66c69e350e4c2b) by two constants:
```
static constexpr int kCoarseResolutionMicroseconds = 100;
static constexpr int kFineResolutionMicroseconds = 5;
``` 
(These constants are used in only two places in the source code currently.)

**Comment by arthuredelstein** [comment]
The plan is:
1. When shields are up, we will apply 1000-us rounding to all high-resolution timers, regardless of header values.
2. When shields are down, we revert to the Chrome behavior in the previous comment.

**Comment by LaurenWags** [comment]
@arthuredelstein @diracdeltas 

1. Since this is labelled as `QA/Yes`, we will need a manual test plan. https://github.com/brave/brave-browser/issues/24681#issue-1339600216 links to some code that isn't clear to me what I need to do in order to test this one. Labelling as `QA/Blocked` until we have this.
2. Does this issue need the `security` label?

cc @kjozwiak @rebron

**Comment by pes10k** [comment]
I'll create a test for this one.  Should be done in an hour or so

**Comment by pes10k** [comment]
https://dev-pages.brave.software/dom-properties/performance.html

**Comment by kjozwiak** [comment]
Removed the `QA/Blocked` as @pes10k created a test under `https://dev-pages.brave.software/dom-properties/performance.html` as per https://github.com/brave/brave-browser/issues/24681#issuecomment-1335851091.

**Comment by GeetaSarvadnya** [comment]
Verified the issue in `Windows 10 x64 - 1.47.126 Chromium: 108.0.5359.99`

Verified the test instructions from https://dev-pages.brave.software/dom-properties/performance.html
>When Shields are down, they should be a mix of integers and float values.

I am not getting the mix of integers and float values when shields are down
![image](https://user-images.githubusercontent.com/38657976/207647720-77d65af2-82fa-4a44-bfbb-fdd171d2ae49.png)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.47.129 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

Steps: 

Install 1.47.129 
launch Brave          

#### Case 1:   Enable `#brave-round-time-stamps` feature flag
<details>

1. open `brave://flags`
2. set `Enabled` for `#brave-round-time-stamps`
3. click Relaunch Brave
4. visit https://dev-pages.bravesoftware.com/dom-properties/performance.html in a new-tab
5. toggle `Off` `Shields` toggle 
6. click `Run test` button

#### Confirmed integers are rendered as expected.

step 2|step 5|result
----|----|-----
<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/207909247-158b0d07-6850-41b2-a929-bba0d3daf359.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/207909779-8f555a62-3343-4015-8dbc-f40c16789718.png">|<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/207909641-1580550e-56bd-410c-9ab9-19b299319a77.png">

</details>

#### Case 2:   Disable `#brave-round-time-stamps` feature flag
<details>

1. open `brave://flags`
2. set `Disabled` for `#brave-round-time-stamps`
3. click Relaunch Brave
4. visit https://dev-pages.bravesoftware.com/dom-properties/performance.html in a new-tab
5. toggle `Off` `Shields`  
6. click `Run test` button

#### Confirmed integers & float values are rendered as expected since the flag is disabled

step 2|step 5|result|result
----|----|-----|----
<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/207910324-f3e0b599-3feb-4f14-b4c7-c71fda3c16d7.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/207910434-9d8f6668-0651-4569-bfe0-1f020fc0320d.png">|<img width="512" alt="image" src="https://user-images.githubusercontent.com/98358127/207910792-0f5f282c-acbd-474d-a31c-35ee5f5e178c.png">|<img width="518" alt="image" src="https://user-images.githubusercontent.com/98358127/207910859-5e9d058b-10a8-49e9-a181-b3df59965b20.png">

</details>

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.135 Chromium: 108.0.5359.128 (Official Build) beta (x86_64)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 11.7.2 (Build 20G1020)


Case 1: Enable `#brave-round-time-stamps` feature flag
<details>

1. installed `1.47.135`
2. opened `brave://flags`
3. set `Enabled` for `#brave-round-time-stamps`
4. clicked `Relaunch` button
5. loaded `https://dev-pages.bravesoftware.com/dom-properties/performance.html` in a new tab
6. toggled Shields `Off`
7. clicked `Run test` button

#### Confirmed all integers returned were rounded

`brave://flags` | `Test succeeded`
---------------|---------
<img width="1048" alt="Screen Shot 2022-12-19 at 7 18 49 PM" src="https://user-images.githubusercontent.com/387249/208582700-c2f69c2d-f7d0-4990-b626-263cf7ab06ec.png"> | <img width="1048" alt="Screen Shot 2022-12-19 at 7 18 58 PM" src="https://user-images.githubusercontent.com/387249/208582544-bf2f6332-19e1-497d-b706-251beb774db4.png">

</details>

Case 2: Disable `#brave-round-time-stamps` feature flags
<details>

1. installed `1.47.135`
2. opened `brave://flags`
3. set `Disabled` for `#brave-round-time-stamps`
4. clicked on `Relaunch`
5. loaded `https://dev-pages.bravesoftware.com/dom-properties/performance.html` in a new tab
6. toggled Shields to `Off`
7. clicked `Run test` button

#### Confirmed integers & float values returned as expected since the flag is disabled

`brave://flags` | `Output - "Test failed"`
---------------|-----------------------
<img width="1048" alt="Screen Shot 2022-12-19 at 8 54 44 PM" src="https://user-images.githubusercontent.com/387249/208586867-4a151adb-103e-4451-a056-1e9f0901e2fc.png"> | <img width="1048" alt="Screen Shot 2022-12-19 at 8 54 52 PM" src="https://user-images.githubusercontent.com/387249/208586874-60032e0a-f415-4d7f-9738-2d70f13ee7cb.png">

*Note: The wording on the buttons show Test failed is incorrect. Should have been Test Succeeded. Confirmed with @arthuredelstein and above tests are correct.
`https://bravesoftware.slack.com/archives/C7VLGSR55/p1671119340076209?thread_ts=1671036126.362999&cid=C7VLGSR55`

</details>

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` running `Android 12` using version: 

```
Brave	1.47.165 Chromium: 109.0.5414.80 (Official Build) (64-bit) 
Revision	0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS	Android 12; Build/SP1A.210812.016
```
**Case: Flag enabled**

1. Enabled for `brave://flags#brave-round-time-stamps`
2. Open test page - https://dev-pages.bravesoftware.com/dom-properties/performance.html
3. Disable Shields
4. Run Test

- Ensured that test results for all frames show as `test succeeded` and all values are `integers`

Shields ON |  Shields OFF | Feature Flag
-|-|-
![screenshot-1673281991099](https://user-images.githubusercontent.com/17885425/211361293-419b43eb-16aa-4fee-b098-6ffbda3f5ee4.png) | ![screenshot-1673281964790](https://user-images.githubusercontent.com/17885425/211361337-f885a608-6fde-45ce-955e-5064c6cc5b71.png) | ![screenshot-1673282072477](https://user-images.githubusercontent.com/17885425/211361355-bb6c031d-bbf4-4841-90fc-5d5a8da88ddc.png)

**Case: Flag disabled**

1. Enabled for `brave://flags#brave-round-time-stamps`
2. Open test page - https://dev-pages.bravesoftware.com/dom-properties/performance.html
3. Disable Shields
4. Run Test

- Ensured that tests fail and values are mix of integers and floats when `brave://flags#brave-round-time-stamps` is disabled

Feature Flag | Performance Test
-|-
![screenshot-1673282106528](https://user-images.githubusercontent.com/17885425/211361612-eb77be79-c43c-44b9-94ce-a224b2170107.png) | ![screenshot-1673282122710](https://user-images.githubusercontent.com/17885425/211361613-2188f10c-2534-4981-8cf0-98fa8444444f.png)

**Comment by jdknox** [comment]
> ## Description
> From [joe12387](https://hackerone.com/joe12387):
> 
> > performance.now() can be used to create a persistent cross-site tracking fingerprint...
> 
> > This code allows you to track a user from site to site, it does not detect if a user is using Brave. My fingerprint is [0.09999990463256836, 0.10000014305114746], while other machines will have a different value.
> 

I just want to note that I get the exact same values as the fingerprint results above:
```
...

> [valueA, valueB]
(2) [0.09999990463256836, 0.10000014305114746]
> valueA - 0.09999990463256836
0
> valueB - 0.10000014305114746
0
```

Is this actually a useful fingerprinting technique if the values are the same across machines?

**Comment by abrahamjuliot** [comment]
If you restart your machine or device, it should change.
