### ISSUE TITLE
Add Learn More link for De-AMP setting

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#24871]
- Add De-AMP support page link to https://support.brave.com/hc/en-us/articles/8611298579981 in brave://settings/shields
- Update description to read "Prefer publisher page URLs, instead of AMP and similar versions"

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.44.70 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

Steps: 

1. Install 1.44.70
2. launch Brave
3. open `brave://settings/shields`
4. verify updated description for `Auto-redirect AMP pages` entry
5. confirmed correct description  "Prefer publisher page URLs, instead of AMP and similar versions"
6. click `Learn more` link to redirect to support page - https://support.brave.com/hc/en-us/articles/8611298579981

step 3-4|step 6
----|----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187789521-2c780c52-b77e-4a8a-b12c-71dad27fc353.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187790104-9b09e964-262d-4d8b-97a4-538a3bd9e1a6.png">
