### ISSUE TITLE
Change link color to blue of "Learn more text"

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24890]

**Comment by kjozwiak** [comment]
The above will require `1.44.72` or higher for `1.42.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.44.75 x64 Beta build
- Verified learn more links are in blue similar to desktop
![image](https://user-images.githubusercontent.com/17010094/188583145-3ae325b8-96b3-4fb0-b460-f8c167ad3a50.png)
-------
Verification failed on Oppo Reno 5 due to https://github.com/brave/brave-browser/issues/25224

**Comment by kjozwiak** [comment]
Removing the `QA/Pass` labels as this was uplifted into `1.43.x` so we'll need to recheck it quickly. The above requires `1.43.92` or higher for `1.43.x` verification.

**Comment by srirambv** [comment]
Verification passed as part of https://github.com/brave/brave-browser/issues/24446#issuecomment-1243799456. Encountered #25224 for light theme
