### ISSUE TITLE
Jan. 2023+ Chrome seems to no longer allow Adblock-Extensions (tech: Manifest 2 > 3): will apply to Brave?

### ISSUE THREAD

**Issue by slynobody** [brave/brave-browser#24969]
## Description 
people building addons for Chrome are using a set of tools that Google supplies called Manifest Version 2. In 2023 Google will choose sunset Manifest Version 2 in favour of Manifest Version 3 which has different tools that do not support everything Manifest Version 2 does anymore - esp. the ability to remove ads the way adblocks do today. Thinkable scenarios: uBlock & uMatrix will not be usable / removed from webstore.

https://tedd.it/r/AdviceAnimals/comments/wwnxxd/chrome_says_that_theyre_no_longer_allowing/
https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

Is this information is correct and if yes, how will it apply to brave? Do you have any plans? Do you plan to offer an ongoing Manifest 2-version fork (or intervene in Manifest 3 development) while building and maintaining your own webstore for brave-extensions?

## Steps to Reproduce

   1. start Brave
   2. install extensions like uBlock (or turn on internal adblocking mechanisms through brave://flags/)
   3. browse the web

## Actual result:
in 2023: (1) some extensions, including adblockers are not installed anymore (2) internal adblocking mechanisms do not work anymore (3) some ads are not blocked anymore.

## Expected result:
in 2023: ads get blocked like today, ad-blocking-extensions like uBlock can be installed.

## Reproduces how often: 
does not apply (currently), future scenario according to development plans.

## Brave version (info found on brave://version)
all

## Version/Channel Information:
all

**Comment by Pjolt** [comment]
https://github.com/brave/brave-browser/issues/20059#issuecomment-992720832

**Comment by slynobody** [comment]
Thank you for the insight
maybe of interest here also: https://github.com/uBlockOrigin/uBlock-issues/issues/338

**Comment by pes10k** [comment]
Hi @slynobody 
1. chrome’s change does not affect Brave’s built in blocking capabilities at all.  Brave will still offer the same, best in class content blocking.  Brave heavily modifies Chromium for reasons just like this
2. Google isn’t limiting *all* adblockers with Mv3, though it is reducing the capabilities of adblocking and content filtering extensions.  Its bad, but its not _quite_ as bad as the press has made it sound
3. Brave will support the Mv2 API past the Google deadline, and is thinking through what other ways Brave can support blocking extensions (In brave or otherwise) generally
