### ISSUE TITLE
[Android] Long tap of bookmark button

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#25015]
**Summary**
In Brave users always need to navigate to the bookmarks feature to edit bookmarks. Most other browsers allow users to edit an already bookmarked page from the main menu (when that page is currently open). Brave should do the same.

A community user had the good idea to use long tap to edit bookmarks.

https://community.brave.com/t/option-to-have-the-edit-bookmark-button-actually-edit-the-bookmark-instead-of-just-removing-it/259250/4

@Sam-Sibley suggested to take it one step further to instead bring up contextual actions like long pressing on the Tab icon does. It's an extra tap to edit but will align our patterns and also allows us to do more.

**Requirements**
When a user is on a page that is already bookmarked:

On tap of bookmark button: remove bookmark (existing behavior).
On **long tap** of bookmark button: display contextual menu for the page (new behavior).
- Remove bookmark
- Edit bookmark (brings edit page as sheet to edit without going to settings)
- View bookmarks

When a user is on a page that is NOT already bookmarked:

On tap of bookmark button: add bookmark (existing behavior).
On **long tap** of bookmark button: display contextual menu for the page (new behavior).
- Add bookmark
- View bookmarks

**Comment by Sam-Sibley** [comment]
@timchilds @deeppandya I think the long press is a good idea, but instead of long press going straight to edit screen, long press could instead bring up contextual actions like long pressing on the Tab icon does. Its an extra tap to edit but will align our patterns and also allows us to do more.

 So if site is bookmarked already, I see the following would appear in that contextual menu:
 
-Remove bookmark
-Edit bookmark (brings edit page as sheet to edit without going to settings)
-View bookmarks

And if long press on the bookmark icon when page is not bookmarked:
-Add bookmark
-View bookmarks

**Comment by deeppandya** [comment]
@Sam-Sibley can you add figma spec here ?

**Comment by Sam-Sibley** [comment]
@deeppandya Here is the figma file:
https://www.figma.com/file/OM4s5mEYi3ZMKhLuHYQJfs/Android-NTP?node-id=1044%3A15319

**Comment by Sam-Sibley** [comment]
Here is a screenshot for reference:
<img width="858" alt="long press bookmark icon" src="https://user-images.githubusercontent.com/99699532/192563307-7b6462db-a7c4-40a7-9527-850df9054b85.png">

Also remember as discussed in the slack thread, we should remove the tooltips for the other toolbar icons that don't have functionality.

**Comment by Uni-verse** [comment]
In progress on the following devices using version `1.49.118 Chromium: 111.0.5563.50`

Samsung GS 21 5G, Android 13
Samsung Galaxy Tab S7, Android 12
