### ISSUE TITLE
Failed to Add Extension

### ISSUE THREAD

**Issue by poreverything** [brave/brave-browser#25022]
I am using the latest version of Brave but I cannot install any extension.

[Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)](https://brave.com/latest/)

https://www.awesomescreenshot.com/image/31811631?key=7dc03315e46e84aaae0911bcd87d68b3

**Comment by whatistime** [comment]
I can't install extensions either, when the file tries to download it has 'Failed - Forbidden'.   Supposedly this has happened before and it was due to Braves servers, but I cannot confirm if that is the case this time.  Only work around for this issue was to download the .crx file and then drag and drop into Brave to install.  I'm guessing that would work for this situation too?

**Comment by poreverything** [comment]
Great! I manually download the CRX file and add to brave extension and it works. Thank you :)
