### ISSUE TITLE
Fedora-29 repo new signing key reported missing

### ISSUE THREAD

**Issue by mossy-nw** [brave/brave-browser#2506]
## Description 

attempting to follow install instructions (with new signing key fingerprint `D8BA D4DE 7EE1 7AF5 2A83  4B2D 0BB7 5829 C2D4 E821`) gives the following error:

~~~
9c02b48/packages/brave-browser-0.57.18-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 6a8a26f9: NOKEY
Public key for brave-browser-0.57.18-1.x86_64.rpm is not installed
Public key for brave-keyring-1.0-1.fc30.noarch.rpm is not installed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
~~~

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

not sure if related #2405

**Comment by bkero** [comment]
Hi there. Sorry about that. A release was signed with the wrong signing key. You were right in that it was related to #2405. I've since made sure that all of the recent releases are signed with the expected signing key.

Additionally to keep this from happening again I've revised our release docs. Short-to-medium term this will be automated and tested so that there's even more certainty that it will not happen again.

**Comment by GrayGhost93** [comment]
I have also the same issue like @jukatu . Can you reopen that issue please.

**Comment by ewolf** [comment]
Same here. I suspect it is the repo that needs updating.

**Comment by qtlin** [comment]
I am observing the same error right now:
brave-keyring-1.13-1.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 6a8a26f9: NOKEY
