### ISSUE TITLE
Use https://api.testnet.solana.com for Solana testnet

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#25142]
The node we are using is unreliable so we decide to use public endpoint without proxy (to avoid rate-limiting) for now.

**Comment by kjozwiak** [comment]
Labelling as `QA/No` for `1.43.x` after discussing with @yrliou. The above is a basic endpoint change which was already checked and verified on `master` via https://github.com/brave/brave-core/pull/14949#issuecomment-1235184166. The change is low risk and shouldn't cause any problems/regressions.

Because https://github.com/brave/brave-browser/issues/25173 includes ` CVE-2022-3075` which is being exploited in the wild, we want to make sure it gets released ASAP and because it's late in the evening, we don't want to waste time verifying a trivial change.
