### ISSUE TITLE
crash on startup on android 6

### ISSUE THREAD

**Issue by lazymonkey2** [brave/brave-browser#25204]
## Description 

On and old device with android 6 brave 1.43.88 crashes as soon as I start It. 
Previoius version was running correctly.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by dfoot1** [comment]
Having the same problem. Since Brave version 1.43.90, it crashes on start up every time. Unable to use it. I use Android Samsung Note4.

**Comment by 424344** [comment]
I have just upgraded to Brave v1.43.93 from play store, but it still crashes.
I had to install Vivaldi to browse the web.
When do you plan to fix this issue? 
Thanks.

**Comment by 424344** [comment]
another brave update from play store, this time v1.43.94, and still it crashes.
I have a little BAT's in this browser, and I cannot get them.
Please fix it.

**Comment by kjozwiak** [comment]
> another brave update from play store, this time v1.43.94, and still it crashes. I have a little BAT's in this browser, and I cannot get them. Please fix it.

@424344 are you still crashing? We've had a few releases since `1.43.94` that fixed a few known crashes. Are you experiencing crashes on startup? Or after using Brave for `[x]` amount of time? Believe you mentioned you're using `Android 6`? Could you also give us some more detailed information on the exact device you're using?

I know the Google is dropping Chromium support on `Android 6` starting at `C106` as per https://groups.google.com/a/chromium.org/g/chromium-dev/c/z_RvoPoIeoM/m/w_ys3ieOAgAJ but `1.43.94` is on `C105` so I don't think that's related.

**Comment by 424344** [comment]
latest version is not crashing anumore. thank for the fix.
device is an old oneplus one phone.
