### ISSUE TITLE
Looking for devices seems to be a dead UI on sync page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2528]
## Description 

Looking for devices seems to be a dead UI on sync page

## Steps to Reproduce

   1. Enable sync on 0.58.12
   2. Add a computer or mobile
   3. Start wondering where is it looking for 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/49938227-460a5d00-feff-11e8-9c43-065a0a7ad358.png)
![image](https://user-images.githubusercontent.com/17010094/49938242-57ec0000-feff-11e8-9f3d-8b1713c3f2e1.png)

## Expected result:
Since the button doesn't do anything seems to be a dead ui to me that can be removed. It stays from the time the modal is shown until a device is added

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
N/A
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bradleyrichter @karenkliu @cezaraugusto @rebron @bbondy

**Comment by bradleyrichter** [comment]
@rossmoody Can we add the loading indicator to this button?

**Comment by rossmoody** [comment]
I think the scope of this issue is related to not giving the user a progress indicator of some kind when setting up new computers to the sync chain. The below screens are before and after design specs for updated direction on this front. The main thing is putting the loading indicator on the button.

![image](https://user-images.githubusercontent.com/29072694/50313967-fdecbc80-0461-11e9-9465-194f7fab2d23.png)
![image](https://user-images.githubusercontent.com/29072694/50313985-0a711500-0462-11e9-8e05-49b437cce63a.png)
![image](https://user-images.githubusercontent.com/29072694/50314055-3f7d6780-0462-11e9-9166-a3c5260b8abb.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

* Verified `Looking for device` has spinner icon while sync chain is being created via QR code/code words
