### ISSUE TITLE
DNSLink redirects to unreachable url

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#25281]
https://pin.ski/3TNzYjz fails to load because of DNSLink redirect.
There is DNS record for the url, but nodes fail to resolve it.

## Steps to Reproduce

   1. Enable IPFS local or remote node and DNSLink redirects
   2. Open https://pin.ski/3TNzYjz

## Actual result:
`ipfs resolve -r /ipns/unstoppabledomains.mypinata.cloud/ipfs/QmPFY3HuzddkKBuZUJ5gQ2REoKQSpECk84nmzs1594suir/: could not resolve name: "unstoppabledomains.mypinata.cloud" is missing a DNSLink record (https://docs.ipfs.io/concepts/dnslink/)`

## Expected result:
Site opens

## Reproduces how often: 
100%

## Brave version (brave://version info)
1.45

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by rillian** [comment]
> There is DNS record for the url, but nodes fail to resolve it.

To be clear, there is no DNSLink record for either the unstoppable domains gateway or pin.ski.
```sh
$ dig +short txt _dnslink.unstoppabledomains.mypinata.cloud
<empty response>
```
So the question is, what is triggering Brave to check for a DNSLink, and why is it requiring that to resolve instead of loading the domain normally? Cloudflare does set `x-ipfs-path: /ipfs/QmTZ4vvV926DN2HwZpd8djLyovFptqk3Xbct71YwJxt28A` on the http response, so I'd expect the page to load through the redirected mypinata url and then decorate it with an "Open in IPFS" button.

**Comment by lidel** [comment]
- `pin.ski` domain does not have DNSLink set up
- HTTP response  for `https://pin.ski/3TNzYjz` has `x-ipfs-path` HTTP header with CID 
  - hypothesis: probably because someone mounted `https://127.0.0.1:8080/ipfs/QmTZ4vvV926DN2HwZpd8djLyovFptqk3Xbct71YwJxt28A` at `/ using Nginx, and did not use [DNSLink support in Gateway](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#gateway-recipes)
- seems that that is happening is this: Brave does the redirect using the first feature, and not the second (DNSLink) one (assuming both are enabled):
  > ![2022-09-08_17-19](https://user-images.githubusercontent.com/157609/189161164-1d705bf1-f843-4c31-8f55-38504c468f08.png)

It is not a bug per se, everything works as expected (IPFS resource identified by a CID is detected, and redirected to local gateway), but the UX is confusing when DNSLink is missing and website is mis-configured like this.  
  
I think this is the same problem as one described in https://github.com/ipfs/ipfs-companion/issues/1052 – I proposed fix there where we only redirect  URLS that follow Public Gateway convention.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.24 Chromium: 106.0.5249.65 (Official Build) nightly (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)


### `Case One` - `Gateway`
<details>

#### Steps:
1. installed `1.46.24`
2. launched Brave
3. opened `brave://settings/ipfs`
4. set `Method to resolve IPFS resources` to `Gateway`
5. toggled `Automatically redirect to IPFS pages via DNSLink when possible` to `Enabled`
6. loaded `https://pin.ski/3TNzYjz`
7. confirmed `https://unstoppabledomains.mypinata.cloud/ipfs/QmTZ4vvV926DN2HwZpd8djLyovFptqk3Xbct71YwJxt28A` loaded, with an `IPFS` button in the URL bar
8. clicked on `IPFS`
9. confirmed `https://bafybeicnpdfiiozubqar2plzkqvfuygrmm6n7y4zqi4efzppkdycrxrzzm.ipfs.dweb.link/` loaded

`brave://settings/ipfs` | initial load | `IPFS` link
-----------|-----------|-----------------
<img width="1312" alt="Screen Shot 2022-10-01 at 11 16 02 PM" src="https://user-images.githubusercontent.com/387249/193436347-a0312dfb-01d3-4e71-8162-f1cdc71b0d7d.png"> | <img width="1322" alt="Screen Shot 2022-10-01 at 10 41 58 PM" src="https://user-images.githubusercontent.com/387249/193436076-69f64b5c-e1b7-4d11-9820-707ecb53d6c8.png"> | <img width="1322" alt="Screen Shot 2022-10-01 at 10 44 21 PM" src="https://user-images.githubusercontent.com/387249/193436089-2ecdee7c-1923-4f4a-b5c2-5108285af2ff.png">



</details>

### `Case Two` - `Brave local IPFS node`
<details>

#### Steps:
1. installed `1.46.24`
2. launched Brave
3. opened `brave://settings/ipfs`
4. set `Method to resolve IPFS resources` to `Brave local IPFS node`
5. toggled `Automatically redirect to IPFS pages via DNSLink when possible` to `Enabled`
6. loaded `https://pin.ski/3TNzYjz`
7. clicked on `IPFS` in the URL bar
8. confirmed `http://bafybeicnpdfiiozubqar2plzkqvfuygrmm6n7y4zqi4efzppkdycrxrzzm.ipfs.localhost:48081/` loaded



`brave://settings/ipfs` | initial load | `IPFS` link
-----------|------------|--------------
<img width="1152" alt="Screen Shot 2022-10-01 at 11 09 51 PM" src="https://user-images.githubusercontent.com/387249/193436286-d13b94a4-6760-42f8-915c-19a743467928.png"> | <img width="1152" alt="Screen Shot 2022-10-01 at 11 11 31 PM" src="https://user-images.githubusercontent.com/387249/193436263-b610f91f-b95e-45db-ab77-1da8fe708af8.png"> | <img width="1152" alt="Screen Shot 2022-10-01 at 11 11 05 PM" src="https://user-images.githubusercontent.com/387249/193436262-376448d3-3338-4c02-9ab0-8cbe6116f48f.png">



</details>
