### ISSUE TITLE
Incorrect address for ENS domains without eth address record.

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#25308]
If ens domain does not have eth wallet address we report it is as 0x000...00, but should report as no address.

https://app.ens.domains/name/haimoura.eth/details

![image](https://user-images.githubusercontent.com/168356/189339550-455bc783-aee5-45b2-b0fd-642a95f32cd1.png)

![image](https://user-images.githubusercontent.com/168356/189339616-aa953bff-b99c-43f7-8ee6-44623014fc24.png)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Linux

- Verified steps from [brave/brave-core#15169](https://github.com/brave/brave-core/pull/15169)
- Verified entering `haimoura.eth` in Send to on wallet panel shows Domain `haimoura.eth` is not registered message instead of zero address
- Verified on both Panel and widget

https://user-images.githubusercontent.com/17010094/192274201-bbbcf39d-71e5-46a8-b150-25c0f57542ac.mp4


------------------------
Verification passed on

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#15169](https://github.com/brave/brave-core/pull/15169)
- Verified entering `haimoura.eth` in Send to on wallet panel shows Domain `haimoura.eth` is not registered message instead of zero address
- Verified on both Panel and widget

https://user-images.githubusercontent.com/17010094/192273912-2119ba5b-6584-4e15-a209-266202ab6012.mp4


------------------------
Verification passed on

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (arm64)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#15169](https://github.com/brave/brave-core/pull/15169)
- Verified entering `haimoura.eth` in Send to on wallet panel shows Domain `haimoura.eth` is not registered message instead of zero address
- Verified on both Panel and widget

https://user-images.githubusercontent.com/17010094/192273756-5fe74e7a-2b6c-4a0c-a694-cbc97411cfc0.mov
