### ISSUE TITLE
Update l10n for greaselion

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#25359]
Download the latest l10n from Transifex for Greaselion.

**Test plan**:
Spot check tip button hover text on tipping websites.

**Comment by GeetaSarvadnya** [comment]
Verified using dev component for:

```
Brave Local Data Updater - Version: 1.0.649
```
Launched `1.44.95` using `--use-dev-goupdater-url` and ensured issue is fixed with the component `1.0.649`, the `Send a tip` hover text is translated in other locales

Germany | Kannada | France | Hindi
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/38657976/191712407-8646c6d1-e55c-4578-a3a6-e38f843cc0cb.png) | ![image](https://user-images.githubusercontent.com/38657976/191712610-9b00f429-093c-4c0d-ba71-055a8ef6db8d.png) | ![image](https://user-images.githubusercontent.com/38657976/191713236-7ae0a993-3b2c-4ac3-9a32-d2310c21debc.png) | ![image](https://user-images.githubusercontent.com/38657976/191713927-ff33b1fe-835a-4914-8650-b96f64755d44.png)


**_GH pages in Germany locale:_**
spot check on `send a tip` hover text translation in various GH pages 

Example | Example | Example | Example | Example
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/38657976/191708571-cb44ddc5-71fd-4ad0-b1cf-250949237ba3.png) | ![image](https://user-images.githubusercontent.com/38657976/191709759-deda16d6-1bd5-4208-8e08-689130623e4d.png) | ![image](https://user-images.githubusercontent.com/38657976/191709909-5b3e345e-9a7a-4ffa-8559-427da7a7be5a.png) | ![image](https://user-images.githubusercontent.com/38657976/191710277-4d72a2c7-1019-41fe-a729-501bf8f98df4.png) | ![image](https://user-images.githubusercontent.com/38657976/191712248-a06beb7a-9721-4887-9be6-469341668eb3.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

Brave | 1.43.93 Chromium: 105.0.5195.127 (Official Build) (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 11.7 (Build 20G817)

`Russian` | `Spanish` | `Italian` | `Korean`
-----------|-----------|---------|---------
<img width="1312" alt="Снимок экрана 2022-09-22 в 9 42 38 AM" src="https://user-images.githubusercontent.com/387249/191807552-f924e6a8-751c-419e-85bc-726c9e8f853d.png"> | <img width="1312" alt="Captura de pantalla 2022-09-22 a las 9 38 20" src="https://user-images.githubusercontent.com/387249/191807644-46a09b95-b20a-4534-bb10-1c1c5674b079.png"> | <img width="1312" alt="Schermata 2022-09-22 alle 9 47 48 AM" src="https://user-images.githubusercontent.com/387249/191807706-3463ade8-ca3d-4aaa-9639-3a27ed300754.png"> | Korean

**Comment by mkarolin** [comment]
Fixed via https://github.com/brave/brave-site-specific-scripts/pull/86
