### ISSUE TITLE
Crash when options dictionary is null in SignAndSendTransaction Request

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#25374]
## Description 

A crash occurs when the `"options"` dictionary for a Sign And Send Transaction request is given to the Solana Provider.

## Steps to Reproduce
   1.  Use test solana dapp site: https://github.com/darkdh/solana-provider-test
       - Occurs because we are expecting `"options"` key but receiving ["option"](https://github.com/darkdh/solana-provider-test/blob/main/src/App.tsx#L172) so the options are null.
   2. Click 'Sign and Send Transaction (Request)
   3. Unlock wallet if locked, observe crash 

## Actual result:
Crashes

## Expected result:
Handles the request

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Version 1.45.41 Chromium: 105.0.5195.102 (Official Build) nightly (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

https://github.com/brave/brave-core/pull/14052/files#diff-072a34f5cbcd051507b00f9df51f345c6c4ab01d4381cb90ba3820708cf5e82eR395

**Comment by darkdh** [comment]
It is caused by https://github.com/brave/brave-core/pull/14052/files#diff-072a34f5cbcd051507b00f9df51f345c6c4ab01d4381cb90ba3820708cf5e82eR395

**Comment by kjozwiak** [comment]
The above requires `1.43.93` or higher for `1.43.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Windows 11 Version 21H2 (Build 22000.856)

- Verified steps from issue description
- Verified no crash when selecting `Sign and Send Transaction (Request)`

Crash in 1.43.89 | Fixed in 1.43.93
-- | --
<video src=https://user-images.githubusercontent.com/17010094/190158391-58c80d8b-d588-446c-965e-58709700a914.mp4> | <video src=https://user-images.githubusercontent.com/17010094/190158310-689c2dbb-6505-4da7-82dd-68911f82f916.mp4>
