### ISSUE TITLE
IsNotificationsAvailable always returns true from Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#2548]
IsNotificationsAvailable always returns true from Brave Ads irrespective if they are enabled or disabled on the operating system

**Comment by bridiver** [comment]
we don't have reliable access to additional information on at least some supported OSes (macos in particular). I thought the decision was that `IsNotificationsAvailable` would return whether or not the OS supported notifications in which case no changes are needed because all platforms we build for support notifications.

**Comment by tmancey** [comment]
Agreed with @mrose17 that we will revisit this ticket after 1.0

**Comment by tmancey** [comment]
This is possible on iOS/macOS using `getNotificationSettingsWithCompletionHandler:`, for further information see https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649524-getnotificationsettingswithcompl?language=objc

**Comment by jonathansampson** [comment]
Note that this issue presently means users are able to earn BAT without viewing ads, per #3651.

**Comment by tmancey** [comment]
Closing as a duplicate of https://github.com/brave/brave-browser/issues/3651
