### ISSUE TITLE
Implement OpenVPN style DNS resolving 

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#25489]
## Description 
Basically, Windows can leak your ISP due to `Smart Multi-Homed Name Resolution` (even when you're on VPN). This is a feature of Windows and is expected behavior. See https://github.com/brave/brave-browser/issues/22163 for full details.

We had attempted a solution using DNS over HTTP (see https://github.com/brave/brave-core/pull/13434) but there were a few issues. See https://github.com/brave/brave-browser/issues/25488 where we want to back this pull request and logic out.

The example shared by @bridiver can be found here:
https://github.com/OpenVPN/openvpn/blob/d92075e0ae6dba84a2e30e4ec12ca29250945371/src/openvpn/block_dns.c

This will block the other adapters (that Smart Multi-Homed Name Resolution would dispatch to) while Brave is open - meaning it will apply to all programs running on the device (instead of only queries made within Brave). A good test would be to hit https://browserleaks.com/dns from another browser when connected using the OpenVPN work-around

More context and details available to Brave employees by reading the security re-review here:
https://github.com/brave/security/issues/1029

## Test cases

Start Brave, check browserleaks.com/dns shows your real location in any browser
- Connect VPN
   - check browserleaks.com/dns shows only VPN country locations, in all browsers
   - check TaskManager or Windows services should show `brave_vpn_helper.exe` and launched service
- Disconnect VPN and check browserleaks.com/dns
   - check TaskManager Details tab should not show `brave_vpn_helper.exe` launched
   - `browserleaks.com/dns` works and shows your real location in all browsers

Start Brave, check browserleaks.com/dns shows your real location in any browser
- Connect VPN
    - check `browserleaks.com/dns` shows VPN’s country locations only in all browsers
- Close Brave
   - check `browserleaks.com/dns` shows VPN’s country locations only in all browsers
- Start Brave it should show connected VPN
- Disconnect VPN and check browserleaks.com/dns
   - check TaskManager Details tab should not show `brave_vpn_helper.exe` launched after 10 seconds
   - `browserleaks.com/dns` works and shows your real location in all browsers

Install Brave without admin permissions,
   - check the helper vpn service was not registered (check list of services in the system)
   - setup and connect Brave VPN
   - check `browserleaks.com/dns` in Brave, it should not show the DNS leak because the browser should fallback to DoH overriding.

Install Brave as admin
   - setup and connect Brave VPN
   - check the helper service is launched..
   - kill helperservice executable in TaskManager
   - check the service automatically restarted after crash
   - repeat few times to kill it again and check the service will be restarted 3 times in total
   - after killing the service 4 time it should not be restarted again.
   - disconnect/Connect VPN again from Brave Browser and check it uses overridden DoH instead of VPN service. DNS leak should not happen. 

Install Brave as admin
   - setup and connect Brave VPN
   - check the helper service is launched..
   - disconnect and connect vpn quickly
   - check the helper service is launched and dns data protected.

IPv6 test:
   VPN OFF
      - Navigate to https://test-ipv6.com/
      - IPv6 should be ON
   VPN ON
      - Navigate to https://test-ipv6.com/
      - IPv6 should be OFF
   Through test
      - VPN OFF
         - Ping the ip 2001:470:1:18::223:250 it should respond without packet loss
      - VPN ON
         - Ping the ip 2001:470:1:18::223:250, it should not trasmit any response
      - VPN OFF
         - Ping the ip 2001:470:1:18::223:250 it should respond without packet loss

- Install Brave as admin
  - Setup and connect Brave VPN
  - check the helper service is launched..
  - crash service and check crash reports from the service created inside `BraveSoftware\%channel%\User Data\Crashpad\reports` 
  - check the service will be uninstalled with the browser

**Comment by tutacat** [comment]
OVPN solved this by setting all adapters to the custom DNS. Additionally, there are registry values to disable the feature in win 8.1+

https://www.ovpn.com/en/blog/deactivate-smart-multi-homed-name-resolution-in-windows-8-8-1-and-10/

**Comment by bsclifton** [comment]
Needs discussion; marking as blocked for now

This is not a blocker for the release though

**Comment by stephendonner** [comment]
Removing `blocked` label as it's implemented, with `QA/Yes` and a provided testplan.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 10 Version 22H2 (Build 19045.2728)

Admin-installed Brave

Non-admin installed Brave

IPv6

**Comment by spylogsster** [comment]
one more PR for crashes autoupload https://github.com/brave/brave-core/pull/17074

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

**Comment by stephendonner** [comment]
Removing `QA Pass-Win64` as this also needs to be verified on Windows 11.

**Comment by stephendonner** [comment]
@MadhaviSeelam do you have bandwidth to take this, since my personal `Windows 11` installation is neither true `release` (it's a `preview release`) nor acting right, per the above issue?  Thanks!

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

### Admin-installed Brave - `PENDING`

#### Brave VPN Helper-service dynamic launching - `PENDING`
<details>

Steps:
1. (with Brave VPN installed as Admin, and configured)
2. launch Brave
3. click on the `VPN` button
4. toggle VPN to `Connected`
5. press `ctrl` + `alt` + `del`
6. click on `Task Manager`
7. confirm the presence of `Brave VPN Helper` service processes
8. disconnect and reconnect `Brave VPN`
9. confirm you see the processes disappear and then re-appear

`Brave VPN` `ON` | `Brave VPN` `OFF`| `Brave VPN` `ON`
----------|-----------|---------
<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/229602423-2c6da68f-0bd1-4e6f-b6cb-43a687ba5b1b.png">
<img width="794" alt="image" src="https://user-images.githubusercontent.com/98358127/229602609-460e1f59-803a-43ee-90c8-06d5f9745d66.png">
<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/229602721-49572809-d76a-476c-8ac6-463eaa781d98.png">

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.50.114 Chromium: 112.0.5615.49 (Official Build) (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

### Admin-installed Brave - `PENDING`

#### Brave VPN Helper-service dynamic launching - `PASSED`
<details>

Steps:
1. (with Brave VPN installed as Admin, and configured)
2. launch Brave
3. click on the `VPN` button
4. toggle VPN to `Connected`
5. press `ctrl` + `alt` + `del`
6. click on `Task Manager`
7. confirm the presence of `Brave VPN Helper` service processes
8. disconnect and reconnect `Brave VPN`
9. confirm you see the processes disappear and then re-appear

**_VPN ON_**

Brave VPN service | Brave VPN helper process | VPN ON 
---------------------|-----------|---------
![image](https://user-images.githubusercontent.com/38657976/230116300-df352103-e4cf-49d0-9b16-c694f39da845.png) | ![image](https://user-images.githubusercontent.com/38657976/230116499-4e0b830c-3b47-42b7-99fe-a2c23c57be3b.png) | ![image](https://user-images.githubusercontent.com/38657976/230117994-bf741859-e1ac-423d-ba4d-c1e367e587e4.png)


**_VPN OFF_**

VPN OFF | Brave VPN service 
---------------------|-----------
![image](https://user-images.githubusercontent.com/38657976/230117554-b54f20bb-49fc-44a8-a88d-12d2d82ad3d4.png) | ![image](https://user-images.githubusercontent.com/38657976/230117683-7a390986-2500-4d10-b830-de59378b1b49.png)


</details>

#### Brave VPN Helper-service process kill & respawn - `PENDING`
<details>

Steps:
1. (with Brave VPN installed as Admin, and configured)
2. launch Brave
3. connect to `BraveVPN`
4. open the `Task Manager` via `ctrl` + `alt` + `del`
5. look for the `Brave Beta Vpn Service` process
6. kill the helper service executable by clicking `End task` in `Task Manager`
7. confirm the service automatically restarts after crash
8. repeat a few times to kill it again and check the service will be restarted 3 times in total
9. after killing the service the 4th time, it should not be restarted again
10. disconnect/Connect VPN again from Brave Browser and check it uses overridden DoH instead of VPN service. DNS leak should not happen.

`screencast` | `browserleaks.com/dns` | `brave://settings/security`
------------|--------------------------|-----------------------------

</details>
