### ISSUE TITLE
Add active wallet count P3A metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#25504]
## Description 

Add active wallet count P3A metrics, broken out by chain:

As an active ETH/SOL/FIL user (that currently has an active account, or previously has had one), how many accounts do you have with a non-zero balance?
`Brave.Wallet.ActiveEthAccounts`, `Brave.Wallet.ActiveSolAccounts` and `Brave.Wallet.ActiveFilAccounts`

1) 1 account
2) 2 accounts
3) 3 accounts
4) 4-7 accounts
5) 8+ accounts

**Comment by GeetaSarvadnya** [comment]
Verification inprogress

```
Brave | 1.47.121 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/15145

**Comment by GeetaSarvadnya** [comment]
@DJAndries Could you enable the code with `TESTNET` so that it would be easier for QA to play around the wallets with non zero funds. Currently, if I transfer the SOL fund (non zero) to a SOLONA account in the TESTNET/DEVNET, the balance is shown in the target SOLONA account/wallet, but the metrics `Brave.Wallet.ActiveSolAccounts` is not shown in the brave://local-state. If I transfer the funds in the `MAINNET` only then the metrics is shown in the brave://local-state file. It's hard to create multiple accounts and trasfer the fund via mainnet to each wallet.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 10 Version 21H2 (Build 19044.2364)

```
<details>
<summary>Case 1: Brave.Wallet.ActiveSolAccounts = 0_PASSED</summary>

1. Clean profile 1.47.x
2. Create a wallet
3. Create a Solana account
4. Open brave://local-state file and ensured that the metrics `Brave.Wallet.ActiveSolAccounts` response value is `0` as expected

</details>

<details>
<summary>Case 2: Brave.Wallet.ActiveSolAccounts = 1_PASSED</summary>

1. Clean profile 1.47.x
2. Create a wallet
3. Create a Solana account
4. Select the `Solana Devnet` via brave://settings/wallet/networks 
5. Send a SOL to Solana account via https://solfaucet.com/ DEVNET
6. Ensured that the 1 SOL appeared in the Solana account
7. Open brave://local-state file and ensured that the metrics `Brave.Wallet.ActiveSolAccounts` response value is `1` as expected

![image](https://user-images.githubusercontent.com/38657976/210089543-fa8e7253-59fc-46bd-9178-5f531f07f8f3.png)

</details>

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` runing `Bravemonoarmx64.apk_1.4.161`
