### ISSUE TITLE
Tip button on GitHub org people page doesn't work

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#25528]
**STR:**
1. Navigate to a GitHub org people page, e.g. github.com/orgs/brave/people
2. Click on a Tip button next to any of the members

Expected result:
The tipping banner (or join rewards panel if haven't joined) shows up

Actual result:
Nothing happens.

Reproducible in 1.43.x, 1.44.x, 1.45.x

**Comment by GeetaSarvadnya** [comment]
Verified using dev component for:

```
Brave Local Data Updater - Version: 1.0.649
```
Launched `1.44.95` using `--use-dev-goupdater-url` and ensured issue is fixed with the component `1.0.649`, the Tip button is aligned correctly in https://github.com/orgs/brave/people and click on `Send a tip` button opens up the tipping banner

Example | Example
-- | -- 
![image](https://user-images.githubusercontent.com/38657976/191691441-91cab1a6-065a-4479-aaa8-2979ea64240e.png) | ![image](https://user-images.githubusercontent.com/38657976/191691522-8a498712-22db-488b-8c45-49ddfc5cf917.png)

Spot checked following github pages and ensured inline tip is aligned correctly and click on `Send a tip` inline tip button opens up the tipping banner for the user to send a tip

https://github.com/brave/brave-browser/commits/master?after=05749476419ca759df8d5f7873bec79f58d2f624+69&branch=master&qualified_name=refs%2Fheads%2Fmaster
https://github.com/brave/brave-core/pull/8852
https://github.com/brave/brave-browser/issues/15005
https://github.com/emerick?tab=stars
https://gist.github.com/darkdh/85fed2542190510aaee0f3ad91091818

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.93 Chromium: 105.0.5195.127 (Official Build) (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 11.7 (Build 20G817)

#### Launched `1.43.93` using `--use-dev-goupdater-url` and ensured issue is fixed with the component `1.0.649`, the Tip button is aligned correctly in https://github.com/orgs/brave/people and click on Send a tip button opens up the tipping banner

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-09-22 at 8 55 22 AM" src="https://user-images.githubusercontent.com/387249/191794967-6eeb5abf-ca73-4874-b37b-0e33acd1208f.png"> | <img width="1312" alt="Screen Shot 2022-09-22 at 8 55 27 AM" src="https://user-images.githubusercontent.com/387249/191794970-0df561fc-e968-49f9-9db3-e57653445aa3.png">

Spot checked following github pages and ensured inline tip is aligned correctly and click on Send a tip button opens up the tipping banner for the user to send a tip:


https://github.com/brave/brave-browser/commits/master?after=05749476419ca759df8d5f7873bec79f58d2f624+69&branch=master&qualified_name=refs%2Fheads%2Fmaster

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-09-22 at 8 53 52 AM" src="https://user-images.githubusercontent.com/387249/191794687-a0df84b1-4685-4f07-a034-bacc68660a8e.png"> | <img width="1312" alt="Screen Shot 2022-09-22 at 8 53 55 AM" src="https://user-images.githubusercontent.com/387249/191794703-a9944ec2-ef43-4a16-b388-d6515c3d66da.png">

**Comment by mkarolin** [comment]
Fixed via https://github.com/brave/brave-site-specific-scripts/pull/87 (https://github.com/brave/brave-core-crx-packager/pull/489)
