### ISSUE TITLE
Revert Virtualized tokens list in portfolio page

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25565]
Removing the virtualized tokens list from the portfolio page (performance experiment). The list items will now render within the main page body and utilize the main page scrollbar.

## Actual result:

https://user-images.githubusercontent.com/30185185/191825034-eae9174d-cd3a-42bf-9c50-2b170f205f8d.mov

## Expected result:

https://user-images.githubusercontent.com/30185185/191824872-450913d2-c8c1-41c6-b24e-7eca38f5d50d.mov

**Comment by kjozwiak** [comment]
The above requires `1.45.77` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Linux

- Verified steps from [brave/brave-core#15181](https://github.com/brave/brave-core/pull/15181)
- Verified the entire page is scrollable instead of just the token list

------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15181](https://github.com/brave/brave-core/pull/15181)
- Verified the entire page is scrollable instead of just the token list

------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (arm64)
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#15181](https://github.com/brave/brave-core/pull/15181)
- Verified the entire page is scrollable instead of just the token list
