### ISSUE TITLE
Flash per site permissions are not remembered across sessions

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2561]
## Steps to Reproduce

1.  Clean profile
2.  Go to `http://homestarrunner.com/`
3.  Allow permissions and play the flash game
4.  Check `chrome://settings/content/flash`
5.  Restart browser
6.  Check `chrome://settings/content/flash`

## Actual result:

Flash per site permissions are not remembered across sessions

## Expected result:
Flash per site permissions are remembered across sessions

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

### Reproducible on current release:
yes, 0.56.15

cc @brave/legacy_qa

**Comment by btlechowski** [comment]
First reported by community: https://community.brave.com/t/flash-settings-not-being-remembered/38556/11

**Comment by simonhong** [comment]
This is expected behavior. Chrome also doesn't store user's flash permission change.
We followed chrome's policy.

**Comment by bershanskiy** [comment]
@btlechowski Here is some additional information:
"Non-persistent" Flash activation is the default behavior since Chrome 69. Chromium Project [Flash Roadmap](https://sites.google.com/a/chromium.org/dev/flash-roadmap#TOC-Non-Persisted-HTML5-by-Default-Target:-Chrome-69---September-2018-) states:

> #### Non-Persisted HTML5 by Default (Target: Chrome 69 - September 2018)
> ##### Summary
> Sites using Flash will require explicit permission to run, every time the user restarts the browser.
> ##### Rationale
> Require affirmative user choice to run Flash Player content, without that choice persisting across multiple sessions.

**Comment by bershanskiy** [comment]
Since this issue is labeled "needs-discussion", I'd like to sum up arguments against Flash:
* This is default behavior of upstream and deviation from upstream requires some amount of resources.
* Brave ships without Flash (at least on my system), and if I ever go through the hassle of instaling Flash, I wouldn't mind activating it manually every time I need it.
* [Firefox ships without Flash](https://support.mozilla.org/en-US/kb/install-flash-plugin-view-videos-animations-games) by default, and it's in click-to-play mode as well.
* Edge has Flash in [click-to-play](https://arstechnica.com/information-technology/2016/04/edge-to-follow-chromes-lead-make-flash-ads-click-to-play/) mode
*  The site in question, [homestarrunner.com](https://homestarrunner.com/), is being ported to HTML5
    > Since Flash is deader than two doornails (and officially ends in 2020), we are working on redesigning the site so the toons, games, and characters can live on!
* [4.0% of sites use Flash](https://w3techs.com/technologies/details/cp-flash/all/all), but very few actually need it to operate. Also, the percentage is falling at 1.5%/year.
* Flash is a notorious security hole.
* A lot of Flash content is used for tracking and advertisement anyway, so explicit activation every time is in line with Brave's mission.

@btlechowski Is one more click every time you reload the browser and go to that specific site worth the compromise if reduced privacy and security?

**Comment by rebron** [comment]
Closing, expected behavior.
