### ISSUE TITLE
100% Disk Usage

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2563]
## Description 
(Carried over from https://community.brave.com/t/100-disk-usage-problem/39742)

**Description of the issue:**
Brave Causing 100% Disk Usage

**System and Brave Specs**
Version : 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
OS : Windows 10

**What Happens?**
Brave uses Hard Disk actively and writes data to some directory

**How long does it last?**
It keeps writing data until Brave is completely closed from Task Manager. It doesn’t matter if I am browsing Youtube or Twitter or any other website. Even closing all websites and just opening new tab page causes same disk usage.

**Things I have tried**
Disabling extensions, removing extensions, disabling Brave Shields, restarting computer, restarting Brave

**Story**
Hello everyone. I have been happily using Brave browser for a long time now and other than couple websites, I did not have any problem with Brave. However, it was until today.

Today I was browsing Youtube, then wanted to play some games and my game lagged for more than 45 seconds. Since I have a high end CPU and GPU, I thought it could be about my HDD. As I have opened the Task Manager, I have seen that my disk activity time was 100%. I have tried checking what was causing the issue and I’ve found that Brave browser was actively using the disk, for writing data.

I tried getting more details and I found that “brave.exe” has write activity on directory “C:$LogFile (NTFS Volume Log)”. I first thought it could be a problem related to my hard drive but after checking it for over 6 hours, I made sure it was the Brave.

Now I don’t know how to fix that problem. I’ve tried many things yet no solution.

![image](https://user-images.githubusercontent.com/815158/49975461-af8c6a80-ff03-11e8-8375-56af4f6c260b.png)

On the right, I have sorted the applications in descending order according to their writing.
Oku (B/sn) stands for Read (B/s)
Yaz (B/sn) stands for Write (B/s)
Toplam (B/sn) stands for Total (B/s)

## Brave version (brave://version info)
0.57.18 / Windows 10

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/a5i4de/youtube_causes_insane_cpu_usage_on_brave/

**Comment by nithronium** [comment]
Hi,

Thanks a lot for carrying it from Community page to Github. I am the original poster at Community page. Just couple more things to add for better understanding, as you can see at the screenshots above, I do not have any problem with CPU, RAM or second HDD's usage. They all work fine, no lagging. Problem is only on one HDD. (I have 2 physical HDDs). 

As I have debugged the issue more, I have realized that this behavior is starting when Brave Browser is trying to load a page with dynamic content. For example, if I open Brave from zero, it has this "disk usage" issue for 20 seconds and then everything becomes normal. Later, if I try to open a simple HTML website, or an image, or forum, it doesn't have such problem.

However, if I try to open Facebook, Youtube or any other video & audio & dynamic content website, it starts going crazy and my "active time" on HDD becomes 100%. Later closing these websites are also not solving the problem. I mean, if I open Youtube, watch a video for 30 seconds and close the brave browser, I still keep having 100% disk active time. It stops only if I end the process from task manager manually. At first it was not that big of a problem, last 2 days it became worse and this morning I was not able to watch a video on Youtube due to that problem. Video kept buffering & freezing.

**Comment by nithronium** [comment]
I have run more tests on my hard drive as some people suggest it might be due to hard drive problems on other forums. (I haven't seen anyone having such problem with Brave but seen people having problems with other apps). So I have run the check disk and fix errors programs on command prompt, it took 2-3 hours to finish and told me there were no problems on the hard drive and nothing to fix. I have also repaired the boot files (in case they were causing it) with an USB windows repair tool, but problem still exists.

**Comment by srirambv** [comment]
@nithronium does disabling hardware acceleration in advance settings bring down the CPU usage? This is just a check to see if it has any impact.

**Comment by rblaine95** [comment]
Just noticed I had this issue as well.
Turning off Brave Rewards fixed this problem for me as well.

I had an issue where I was having 100% Disk Activity on my 860 Evo as long as I was on a page (for example: this GitHub Issue Page)  and the 100% Disk Activity would persist a couple of minutes after closing Brave.

**Comment by NejcZdovc** [comment]
closing this one as we moved big state files in db. Please reopen if this is still a problem

**Comment by groshreez** [comment]
I'm having this same problem. It seems to happen randomly, more often when playing a browsing a video site like youtube, vimeo, etc but it can also happen on other websites with no videos. I've tried disabling brave rewards as some have recommended but that hasn't solved the problem. I've had to stop using brave because it makes my computer unusable.
