### ISSUE TITLE
when user starts a new sync chain the modal needs to prevent cancelation

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2564]
1. Clear profile
2. Click "start a new sync chain"
3. Click "tablet or phone"
4. Try to cancel the modal
5. A new modal appears asking if you are sure about closing it

**Comment by LaurenWags** [comment]
@cezaraugusto does this refer to the following scenario:
Start sync chain on device A
Enter code words on device B
Device B "completes" joining the sync chain (meaning, the screen where words were entered closes automatically to show the page which lists devices).
Device A still hasn't completed (recognized the chain has been created?) and the screen showing the words is still displayed.
User thinks they have to close this window manually on Device A, so they do and now the chain is seemingly lost?

....asking because I just did this.

**Comment by cezaraugusto** [comment]
moving to 0.59 per last sync meeting

**Comment by cezaraugusto** [comment]
changing to QA/yes as it has valid steps to check the new feature

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/50810190-434c2d80-132e-11e9-9a14-b28f0bec0423.png)
