### ISSUE TITLE
Clear browsing data

### ISSUE THREAD

**Issue by broros** [brave/brave-browser#2581]
why does it take one hour to Clear browsing data?
unless I restart the browser.

**Comment by tomlowenthal** [comment]
Clicking "Clear data" here shouldn't take an hour. Can you share a screenshot of this dialog?
<img width="512" alt="screen shot 2018-12-19 at 11 17 45 am" src="https://user-images.githubusercontent.com/639937/50242600-bc83e080-037f-11e9-9a22-957ff50ff4f7.png">

**Comment by broros** [comment]
looks like you already provided one, my settings are Advanced, Time range: everything.
The data does not delete when visiting some big sites, yahoo etc, after having many windows open for a while

**Comment by tomlowenthal** [comment]
I assume that there's something in your profile which is especially gnarley, and needs to be tracked down. I wanted a screenshot because I'm specifically interested in the size listed in the "Cached images and files" section. 

One way to track down the offending object that would be to send us a copy of your Brave profile and let our QA folks go at it. Or you could do it yourself — but we're probably going to need to look at the troublesome file or whatnot if we're going to fix the underlying bug.
