### ISSUE TITLE
Crash reports are not getting through in some cases

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#25842]
![Screenshot_20221006-130557](https://user-images.githubusercontent.com/12011303/194382892-a1008533-eb19-436c-ae98-849736f763e9.png)
We see that sometimes crash reports are not getting uploaded. Need to figure out why.

**Comment by AlexeyBarabash** [comment]
To send crash reports, there should be two conditions met:
1. option should be enabled in privacy settings
2. device must have enabled feature of `PostFREFixMetricsReporting`/`MetricsReporting`

Issue happened because since https://source.chromium.org/chromium/chromium/src/+/edcd589912d488901e38f8feafcc2d8cb32b4cc2   for the `Stable` channel probability is 19% (https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/metrics/chrome_browser_sampling_trials.cc;drc=796d9f7be35cc8f766fabc6e84df424046460890;bpv=1;bpt=1;l=130 )

So crash dumps had not been sent in most cases.

PR https://github.com/brave/brave-variations/pull/394 must fix it

**Comment by AlexeyBarabash** [comment]
Uplift to variation server production was created
https://github.com/brave/brave-variations/pull/395

**Comment by AlexeyBarabash** [comment]
Closing as https://github.com/brave/brave-variations/pull/395 was merged.
