### ISSUE TITLE
set kDesktopSharingHubEnabled to true but hide/remove Share link to section

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#26019]
## Description 

Add Desktop sharing hub but hide or remove share link section

## Actual result:

If full flag is enabled -

<img width="359" alt="Screenshot 2022-10-13 at 7 18 18 PM" src="https://user-images.githubusercontent.com/5951041/195746934-3bdcb245-64a7-4140-80fc-c8951f0ce99c.png">

In current release - 
Shows only QR code icon
<img width="153" alt="Screenshot 2022-10-13 at 7 19 01 PM" src="https://user-images.githubusercontent.com/5951041/195747021-05340190-5edc-4b3b-bd36-9cbc831aa6c5.png">

## Expected result:
<img width="359" alt="Screenshot 2022-10-13 at 7 18 18 PM" src="https://user-images.githubusercontent.com/5951041/195746918-52a4bd82-fe23-414b-88bd-13e25ee0b7bc.png">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

Target release 1.45.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related issues:
https://github.com/brave/brave-browser/issues/20757
https://github.com/brave/brave-browser/issues/25621

**Comment by kjozwiak** [comment]
The above requires `1.45.112` or higher for `1.45.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.45.112 Chromium: 107.0.5304.62 (Official Build) (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.45.112 Chromium: 107.0.5304.62 (Official Build) (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7 (Build 20G817)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.113 Chromium: 107.0.5304.62 (Official Build) (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Ubuntu 18.04 LTS




### Case 1: New profile - `PASSED`
<details>

1. installed `1.45.113`
2. launched Brave
3. loaded `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing1=foo&brave_testing2=bar&brave_testing3=keep&&;b&d&utm_content=removethis&e=&f=g&=end`
4. clicked on the `Share this page` icon in the URL bar
5. ensured each of the following options worked:
 - `Copy link`
 - `Copy clean link`
 - `Create QR Code`
 - `Save page as...`

### `Copy link`

#### Chose `Copy link` and confirmed I got the full URL:

`https://dev-pages.bravesoftware.com/clean-urls/?brave_testing1=foo&brave_testing2=bar&brave_testing3=keep&&;b&d&utm_content=removethis&e=&f=g&=end`

### `Copy clean link`

#### Chose `Copy clean link` and confirmed I got the cleaned URL:

`https://dev-pages.bravesoftware.com/clean-urls/?brave_testing3=keep&&;b&d&e=&f=g&=end`

### `Create QR Code`

#### Chose `Create QR Code` and confirmed I could scan & load `brave.com` on iphone:

QR Code | `brave.com` loaded
---------|---------------------
![image](https://user-images.githubusercontent.com/34715963/197769179-799fa88a-a8dc-4bfe-bcec-37196eac9ac9.png)|![IMG_1251](https://user-images.githubusercontent.com/34715963/197769935-dff1afe2-134b-463a-afbd-e77e513105b3.PNG)


### `Save page as...`

#### Chose `Save page as...` and confirmed I could open the saved contents (without relative-pathed images)
![image](https://user-images.githubusercontent.com/34715963/197770081-ffe4c7e2-041b-42b8-bd08-ed9f37ba4e5f.png)
![image](https://user-images.githubusercontent.com/34715963/197770140-83ac9559-9739-4a0f-85a5-8f074669f5ce.png)



</details>

### Case 2: Profile with Sync enabled - `PASSED`
<details>

1. installed `1.45.113`
2. launched Brave
3. opened `brave://sync`
4. set up a sync chain
5. joined the sync chain from Android
6. back on desktop, loaded `brave.com`
7. clicked on the `Share this page` icon in the URL bar
8. selected `Send to Your devices`
9. chose `iphone`
10. checked my `iphone` 

#### Confirmed my iphone received a notification about the sent `brave.com` link

![image](https://user-images.githubusercontent.com/34715963/197771993-df9ba6c8-ba13-4abb-b348-795778c51f1e.png)
![image](https://user-images.githubusercontent.com/34715963/197772115-78992aef-bffc-4617-a34a-58eafc9b14c9.png)
![image](https://user-images.githubusercontent.com/34715963/197772234-0300a7a4-f904-4f88-a35b-1575dfeb9b06.png)
![IMG_1252](https://user-images.githubusercontent.com/34715963/197772585-693f3fa3-5976-4382-8f51-aac548b16686.PNG)
![IMG_1253](https://user-images.githubusercontent.com/34715963/197772591-7a96e71e-283f-44e3-b5f5-d0fa17639196.PNG)




</details>

### Case 3: Profile with Cast enabled - `PASSED`
<details>

installed `1.45.113`
loaded `youtube.com`
clicked on the `Share this page` icon in the URL bar
looked at the list of devices

#### Confirmed I was able to list all of my (otherwise?) `Cast`-enabled devices

![image](https://user-images.githubusercontent.com/34715963/197773060-5c24c1c9-082d-4837-bd04-653eea1ef6cf.png)
![image](https://user-images.githubusercontent.com/34715963/197773311-8db21663-8f6f-4dbd-9aa7-ef7f607d1cfe.png)


</details>

### Case 4: Profile with Sync and Cast enabled - `PASSED`
<details>

![image](https://user-images.githubusercontent.com/34715963/197773165-c14e387b-251f-4ba2-9109-a4d49506dae2.png)

</details>

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.45.113 Chromium: 107.0.5304.62 (Official Build) (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Windows 11 Version 22H2 (Build 22621.675)
```

Verified that `Cast` was working without any issues via the new enabled `Share` hub by casting from my PC running `1.45.113 Chromium: 107.0.5304.62` to a TV downstairs that's connected to an Nvidia Shield that has casting enabled:

* installed `1.45.113 Chromium: 107.0.5304.62`
* enabled `Media Router` via `brave://settings/extensions`
* once enabled, visited https://www.yoursoccerdose.com/matches/18535289/west-ham-united-vs-afc-bournemouth
* clicked on a video and ensured that `Cast` appeared under the `Share` hub via the URL bar
* ensured that clicking on `Cast` opened the `Cast` menu with all the available devices on the network that can cast
* picked the Nvidia shield in the living room and ensured you can cast both the `Window` & `Tab`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|---------------
![cast1](https://user-images.githubusercontent.com/2602313/197805678-3de3a3f6-e4df-41e5-9e84-fcdd23fb62de.png) | ![cast2](https://user-images.githubusercontent.com/2602313/197805694-4e2de52a-e9e0-41d3-b559-2d4095d8f2bc.png) | ![cast3](https://user-images.githubusercontent.com/2602313/197805711-1ce7d115-cd42-4813-a85d-782e013f37c7.png) | ![cast4](https://user-images.githubusercontent.com/2602313/197805719-7082ba32-f47e-499b-abb9-8972523bf2b0.png) | ![image](https://user-images.githubusercontent.com/2602313/197806471-bf6f2cc2-e766-4058-a4ac-3c172e438f33.png)
