### ISSUE TITLE
"Copy clean link" feature

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#26013]
## Description 
https://github.com/brave/brave-browser/issues/23315

We should implement this feature on Android also. 

@fmarier given mobile UI constraints, could clean copy be the default and only option?

**Comment by fmarier** [comment]
@fmarier I'd say that should remain an opt-in feature because it's important that users be able to copy the original URL too. There are lots of reasons for wanting to copy what's currently in the URL bar, and it could be very frustrating for users if they can't copy what they see on the screen.

If we don't want to have a separate menu item like on desktop, then perhaps we could have a new setting (off-by-default) to de-clutter copied URLs?

**Comment by bsclifton** [comment]
Naming is `Copy clean link`
(see https://github.com/brave/brave-browser/issues/26106)

**Comment by fmarier** [comment]
Since we will be [changing the default on desktop](https://github.com/brave/brave-browser/issues/26761) based on user feedback, we can make this feature opt-out on mobile. There should be a way for people to copy the URL displayed in the URL bar (e.g. for web developers), but it doesn't have to be the default.

**Comment by anthonypkeane** [comment]
Clean copy can be enabled by default, pasting a URL in the normal way should paste it without the tracking code

@timchilds for users that want the tracking code, how about we provide an option on the long press URL bar?

**Comment by TokuTrex** [comment]
Someone changed this in the desktop version and now I'm unable to copy text in google docs, emails, and in almost every other use case. Please change this back or at least make a hot key for regular copying functions

**Comment by lendioDan** [comment]
> Someone changed this in the desktop version and now I'm unable to copy text in google docs, emails, and in almost every other use case. Please change this back or at least make a hot key for regular copying functions

Me too and its driving me freaking crazy. How do I turn this off as the default?

**Comment by lendioDan** [comment]
> We're aware of some bad bugs in this feature and are working to get them fixed in the release version of Brave (see [#29074 (comment)](https://github.com/brave/brave-browser/issues/29074#issuecomment-1472397725)). In the meantime, note that all of these are fixed in the [nightly version of Brave](https://brave.com/download-nightly/).

Any timeline or date? It's so distracting I'm considering going to Chrome and I really don't want to do that.

**Comment by fmarier** [comment]
We're aiming for a hotfix early next week.  If you'd like to help ensure that the bugs you're seeing are the ones we're currently testing and getting ready for release, there are two things can would help:
1. [Download Nightly](https://brave.com/download-nightly/) and see whether or not it's fixed.
2. If it's not fixed, then please describe the exact steps we can take to reproduce (including what OS you're using) on https://github.com/brave/brave-browser/issues/29074.

**Comment by lendioDan** [comment]
The issue I have is that cmd+C on Mac OS 13.2.1 in the brave browser is by default selecting "copy clean link". I don't want this for 2 reasons:
1. When copying anything across the web it won't copy the text, it copies a link. I'm talking about Jira, google docs, google sheets, etc. I don't want a link copied, I want the selected text. 
2. I don't want "copy clean link" as the default. I work in experimentation and my job revolves around custom parameters for testing specific user flows, so having copy clean link as the default makes it very difficult to copy and paste the correct url with the appropriate parameters. I would prefer an option that lets me select which I want. Or a separate hot key for copy clean url, I think its a clever idea, but in practice it makes my life more difficult.

**Comment by fmarier** [comment]
> If it's not fixed, then please describe the exact steps we can take to reproduce (including what OS you're using)

In particular, for the Google Docs case, we haven't been able to reproduce, so if it's happening on Nightly, please be as specific as possible on https://github.com/brave/brave-browser/issues/29074. And if you'd rather not install Nightly, we'd still like the specific steps and environment so that we can try to reproduce on our own.

**Comment by massimosam** [comment]
Was there ever the possibility to copy a clean link for the page currently open? Because this is quite far from clean:

<img width="1224" height="1907" alt="Image" src="https://github.com/user-attachments/assets/3a3ed5be-879e-41ce-9fab-cb1518e28b54" />
