### ISSUE TITLE
Update show bookmarks setting

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#26072]
## Description 

The `Show bookmarks` setting and `Always show bookmarks on the new tab page` are related and work together as there are four states (with one broken state). Users don't know that they do work together and often want to hide bookmarks completely and yet still see the bookmarks bar on the new tab page when they've explicitly wanted to hide bookmarks. Further, these two settings are not placed close together and therefore don't look to be related.

Current settings
1. Default. Show bookmarks [off], Always show bookmarks on the new tab [on]. Matches Chrome default.
2. Show bookmarks [on]. Always show bookmarks on the new tab [on]. Bookmarks bar on for all tab pages
3. Show bookmarks [off]. Always show bookmarks on the new tab [off]. Bookmarks bar all off for all tab pages.
4. Show bookmarks [on]. Always show bookmarks on the new tab [off]. Broken setting but wontfix.

Updated `Show bookmarks` setting will delete `Always show bookmarks on the new tab page` setting and make `Show bookmarks` a drop down choice of three options:

1. Always (default)
2. Never
3. Only on the new tab page

New users should have `Only on the new tab page` as their default.

Existing users will carry their setting from previous versions which in most cases will be Show bookmarks [off] and Always show bookmarks on the new tab page [on].

To be discussed
Note that on macOS with the View menu, the options `Always show bookmarks` is a checkbox. We will keep that checkbox to be `Always` and `Never`. Users will need to go into Settings to change to Only in the new tab page and. If users select Only in the new tab page in settings, the View menu will be reflected as `Always`. 

## Expected Design
![image](https://user-images.githubusercontent.com/5951041/196209667-f4d4d36d-c3d8-4fea-b8f1-819a6b8af82e.png)

## Currently in release for reference
<img width="701" alt="Screenshot 2022-10-17 at 7 53 39 AM" src="https://user-images.githubusercontent.com/5951041/196211003-18e905af-29f8-409c-bed2-7f73387ed5a1.png">

## Brave version (brave://version info)

Targeted for 1.47

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related issue: https://github.com/brave/brave-browser/issues/25834

**Comment by LaurenWags** [comment]
@brave/qa-team when verifying this issue please be thorough with upgrade cases to ensure that all upgrade scenarios/permutations are covered (can reference https://github.com/brave/brave-browser/issues/26072#issue-1411724988 to help determine this)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.49.100 Chromium: 110.0.5481.100 (Official Build) beta (x86_64)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | macOS Version 11.7.4 (Build 20G1120)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.49.106 Chromium: 110.0.5481.104 (Official Build) beta (64-bit)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Windows 11 Version 21H2 (Build 22000.1574)
```

New Install 

Details

Case 1: : Show bookmarks pref set to `Only on the new tab page`  in the `brave://settings/appearance -  PASSED
<Details>

1. installed `1.49.106` 
2. launched Brave 
3. Skip >> Skip >> Finish
4. bookmarks are not imported
5. opened `brave://settings/appearance` in a new tab page
6. leave default option  `Only on the new tab page` in the `Show bookmarks` drop down menu
7. opened a `new tab page`, `New window`, `Private Window` and `Tor Window`

Confirmed Show bookmarks drop down menu has three options `Only on the new tab`, `Never` and `Always` in the `brave://settings/appearance`
Confirmed `Bookmarks bar` is visible for `new tab page`, `New window`, `Private Window` and `Tor Window`.  `Guest window` will not have the link as expected

step 6 | New tab page | New window | Private window | Tor window | Guest window
------- | ------- | --------- | ---------- | -------- | ----------
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/220465326-27efea4b-b4c6-48be-9dc9-bbb219ea11a2.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/220481117-6c20181c-6a44-4b85-a21e-2e752ebb0026.png">|<img width="448" alt="image" src="https://user-images.githubusercontent.com/98358127/220467035-ebbe82cf-e59c-4e1d-8efc-37d3ae9697cd.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/220467062-6c8e6d80-8fc2-4b61-8fac-755234926da1.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/220467100-96a3e98b-f8d6-4c97-bb1f-ccaa32d6322c.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/220483752-33736d8b-c0a7-4635-8a95-3abd7f0fae18.png">

</Details>

Case 2:  Show bookmarks pref  set to `Never`  - PASSED
<Details>

1. continue from Case 1
      - default option `Only on the new tab page` is selected in in the `Show bookmarks` drop down list
2. opened `brave://settings/appearance` on a new tab page
3. select  `Never` option in the `Show bookmarks` drop down menu
4. opened a new-tab page

Confirmed `Bookmarks bar` is not visible on the bookmarks bar on a new tab page, New window, Private Window and Tor Window.  Guest window will not have the link as expected

step 1 | step 3 | New tab page | New window | Private window | Tor window 
------- | --------| --------- | -------- | ----------- |--------------- 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/220480222-2cab910d-d70b-4060-8b3f-52611b55c13f.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/220480725-fb5aa1f7-30b5-40e9-aa3d-ff7b536bb995.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/220480471-778fdf5e-a1e8-4cc7-89b2-763353c802b4.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/220480501-c459ee3e-6a51-4bea-aca3-1842a3f37dc3.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/220480532-4c17f1fc-6ed1-415a-a327-2b944e361d36.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/220480609-9e9d18b9-6ea5-487e-bfe9-6bd6194001f5.png">
</Details>

Case 3:  Show bookmarks pref  set to `Always`  - PASSED
<Details>

1. continue from Case 2
      - default option `Never` is selected in in the `Show bookmarks` drop down list
2. opened `brave://settings/appearance` on a new tab page
3. select  `Always` option in the `Show bookmarks` drop down menu
4. opened a new-tab page

Confirmed `Bookmarks bar` is not visible on the bookmarks bar on a new tab page, New window, Private Window and Tor Window.  Guest window will not have the link as expected

step 1 | step 3 | New tab page | New window | Private window | Tor window |  Guest window
------- | --------| --------- | -------- | ----------- | --------------- | -------
<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/220484180-9ed8a3be-ca6f-417a-a678-ff77a6c9bc47.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/220484205-1729b937-7c86-44a5-9b09-1db9a6dc2ccb.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/220484234-09d1d30b-e3eb-42ea-ab80-3ae23ea7a9b5.png">|<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/220484254-135d72d5-1984-48c8-a4c1-08530b9fcc5a.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/220484284-0a476007-fdbc-4663-a1a6-924395ddf640.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/220484325-a7baa797-4b4f-4776-87c1-cf81695872cb.png">
</Details>

Case 4: : Show bookmarks pref set to `Never`  via Context menu -  PASSED
<Details>

1. continue from Case  4
    - `Always` option is selected and bookmarks bar is shown on the new tab page
2. open context menu and click `Show bookmarks` menu 
3. select   `Never ` in the `Show bookmarks` drop down menu

Confirmed `Show bookmarks bar` in the context menu shows all 3 options `Always, Never,  `Only on the new tab page`.  
Confirmed `Bookbar` is not visible in the new tab page
Confirmed  `Never` option is selected in  `brave://settings/appearance`

step 1 | example | example
------- | ------- | --------
<img width="948" alt="image" src="https://user-images.githubusercontent.com/98358127/220494227-c2896720-4b38-4699-9faf-ac50dbbda8e5.png">|<img width="942" alt="image" src="https://user-images.githubusercontent.com/98358127/220494775-25f4d5eb-a985-4ac4-a1d4-968139fb5c0b.png">|<img width="948" alt="image" src="https://user-images.githubusercontent.com/98358127/220494602-445e6d88-fbd7-4d15-ba0d-302991887e0f.png">
</Details>

Case 5: : Show bookmarks pref set to `Only on the new tab page` via `Hamburger` menu  -  PASSED
<Details>

1. continued from Case 4
      - Bookmarks bar is not shown and  `Never` is selected in the `Show bookmarks` menu
2. clicked `Hamburger menu` >> `Bookmarks` >> `Show bookmarks` flyout menu
3. selected `Only on the new tab page` 
4. opened a `new tab page`

Confirmed `Show bookmarks bar`  menu shows all 3 options `Always, Never', `Only on the new tab page`.  
Confirmed `Only on the new tab page` is selected in the Hamburger menu and in `brave://settings/appearance

step 1 | context menu on the new tab page | brave://settings/appearance
------- | ------- | -----
<img width="946" alt="image" src="https://user-images.githubusercontent.com/98358127/220495045-18224f85-e6d1-4653-ae2b-e032e0643324.png">|<img width="944" alt="image" src="https://user-images.githubusercontent.com/98358127/220495230-cf1b2a77-8242-4d2a-a63b-22c0d0fb368c.png">|<img width="948" alt="image" src="https://user-images.githubusercontent.com/98358127/220495314-486511a4-66f6-4569-b810-56c5dafa3ec9.png">

</Details>

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | Linux
```
### New Install 

#### <summary> Case 1: Default option set `Only on the new tab page` when no bookmarks imported via `brave://welcome` - `PASSED` </summary>
<Details>

1. installed `1.49.106` 
2. launched Brave 
3. Skip >> Skip >> Finish
4. opened `brave://settings/appearance` in a new tab page
5. opened a `new tab page`, `New window`, `Private Window` and `Tor Window` & `Guest window` 

- Confirmed `Show bookmarks` setting has three options `Only on the new tab`, `Never` and `Always` in the `brave://settings/appearance`
- Confirmed `Only on the new tab` is shown as default in the drop down menu for `Show bookmarks` setting
- Confirmed `Always show bookmarks on new tab page` setting is no longer available.
- Confirmed the `brave://settings/appearance` page did NOT have the `bookmarks bar`
- Confirmed `bookmarks bar` is visible for `new tab page`, `New window`, `Private Window` and `Tor Window`.  
- Verified `Guest window` will not have the bookmarks bar as the behavior is expected
- Confirmed `Always show bookmarks on the new tab page` setting will be removed

step 5 | Default | New tab page | New window | Private window | Tor window | Guest window
------- | ------- | --------- | ---------- | -------- | ---------- | ----------
<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222848650-94b00fb2-6acd-4d5e-945b-b90b06f3df88.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222851769-7298844f-5891-4d18-94c6-a11c5a56eea3.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222849404-e446399c-c351-4350-90f4-7e82282352ce.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222851199-e20e79aa-5692-46aa-8e6c-6dcb99e3730b.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222849510-e9b93753-bd62-47ed-9454-2ffbbdcd3d12.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222849901-a39179fd-7064-401f-8246-4402276f6753.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222849986-5d1910f4-c628-4b0c-bb01-3c0d8662afa1.png">
</Details>

#### <summary> Case 2:  `Always` option was set when bookmarks imported via `brave://welcome` - `PASSED` </summary>
<Details>

1. new profile 
2. launched Brave 
3. click `Set Brave as default browser`
4. select `Vivaldi` >> Import
5. click `Finish` 
6. opened `brave://settings/appearance` in a new tab page

 - Confirmed `Show bookmarks` setting is set to `Always` in the `brave://settings/appearance` and it is expected behavior. 
 - Confirmed `bookmarks bar` is visible with imported bookmarks shown on a `new tab page` 
 - Confirmed the `bookmarks bar` is shown in the `brave://settings/appearance` page 

step 4 | result | result 
------- | --------| --------- 
<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222852591-d57dfae1-3af8-40d7-a109-6a5edc7d5a18.png">|<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222852805-2853df00-9cd5-4bce-ba55-33cdff060652.png">|<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222853512-0579c739-e19c-433c-b431-0dbcbd8cfc3a.png">

</Details>

#### <summary> Case 3: `Never` option selected via `Context menu` - `PASSED` </summary>
<Details>

1. new profile 
2. Skip >> Skip >> Finish
3. verified `bookmarks bar` is visible in the new tab page 
4. open `context menu` in the `bookmarks bar`
5.  click `Show bookmarks` flyout menu to confirm `only new tab page` option is selected as expected
6.  select `Never ` 
7. open a new tab page

- Confirmed `Show bookmarks bar` in the context menu shows all 3 options `Always`, `Never`, `Only on the new tab page`.  
- Confirmed `Never` option was selected in the `context menu` and correct option is shown in `brave://settings/appearance`
- Confirmed `Bookbar` is not visible in the new tab page
- Confirmed the `brave://settings/appearance` page did NOT have the `bookmarks bar`

step 5| result | result 
------- | ------- | -------- 
<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222854456-622719c9-4d65-432f-843b-744844b32af5.png">|<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222854502-f8734f56-167c-4d79-98fa-b6b15998140c.png">|<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222854555-190a9e32-bf4a-4977-b683-def277858a1a.png">
</Details>

#### <summary> Case 4: `Only on the new tab page` option selected via `Hamburger` menu - `PASSED` </summary>
<Details>

1. continued from Case 3
      - Bookmarks bar is not shown and `Never` was selected in the `Show bookmarks` setting
2. clicked `Hamburger menu` >> `Bookmarks` >> `Show bookmarks` flyout menu
3. selected `Only on the new tab page` 
4. open a new tab page

  - Confirmed `Show bookmarks bar` flyout menu shows all 3 options `Always`, `Never`, `Only on the new tab page`
  - Confirmed `Only on the new tab page` is selected in the `Hamburger` menu and is shown in `brave://settings/appearance`
   - Confirmed the `brave://settings/appearance` page did NOT have the `bookmarks bar`

step 1 | result| result | result
------- | ------- | ----- | ------
<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222854739-56b4d3e9-00af-42b4-9e9c-ab42235bd1a4.png">|<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222855345-ebcd784e-4d73-450a-a8ce-4fa75bd5829f.png">|<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222854890-228d6411-f4c3-48bf-939e-e1c74b6d2c3f.png">|

</Details>

#### <summary> Case 5: Select `Never` via `brave://settings/appearance` and import bookmarks via `brave://settings/importData` - `PASSED` </summary>

<Details>

1. new profile 
2. launched Brave 
3. Skip >> Skip >> Finish 
4. opened `brave://settings/appearance` on a new tab page
6. select `Never` option in the `Show bookmarks` drop down menu
7. opened `brave://settings/importData` in a new tab page
8. selected `Yandex User `1 - Apple ` >> `Import`
9. verified `Show bookmarks` setting is enabled
10. click `Done` 
11. opened a new tab page

- Confirmed bookmarks bar is visible with bookmarks shown.  Overriding setting from `brave://settings/appearance` which is the expected behavior. 

step 4 - 5 | step 6 -7 | step 8 - 9 | result 
------- | --------| --------- | ----- 
<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222856253-54826da0-6d25-4915-931b-97c96719ff1e.png">|<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222856296-64845fce-4bde-46be-b7f3-4e5059c31c6c.png">|<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222856313-dd408cdd-4517-4609-8790-2ab1f0712f7b.png">|<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/222856343-0d6f0236-a7ed-4d99-ab69-bf713ac0f702.png">
</Details>

## Upgrade  

#### <summary>Case 1: Default - `Show bookmarks` [`Off`], `Always show bookmarks on new tab page` [`On`] and when no bookmarks imported before upgrade -   `PASSED` </summary>

<Details>

1. installed `1.48.171` 
2. launched Brave 
3. Skip >> Skip >> Finish
4. opened `brave://settings/appearance` in a new tab page
5. leave the default option `Show bookmarks` setting to `Off`
6. leave the default option `Always show bookmarks on new tab page` setting to `On`
7. open a new tab page 
8. installed `1.49.107`
9. renamed Brave-Browser profile to Brave-Browser-Beta
10. re launched Brave 
11. opened a new tab page, New window, Private Window and Tor Window, `Guest window`

- Confirmed `Show bookmarks` setting has a drop down menu with three options `Only on the new tab`, `Never` and `Always` in the `brave://settings/appearance`
- Confirmed `Always show bookmarks on new tab page` setting is no longer available.
- Confirmed `bookmarks bar` is shown on the `new tab page` 
- Confirmed `Only on the new tab` is shown as default in the drop down menu for `Show bookmarks` setting
- Confirmed the `brave://settings/appearance` page did NOT have the `bookmarks bar`
- Confirmed `bookmarks bar` is visible for `New window`, `Private Window` and `Tor Window`.  
- Verified `Guest window` will not have the bookmarks bar as the behavior is expected

step 1 | step 3-4(1.48.171) | step 6| result (1.49.107) | result | New Window | Private window | Tor window | Guest window
-------- | ------ | ------- | -------- | ------- | ------ | ------- | -------- | -------
<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222857388-7066ec9d-5a53-489c-8d9a-44de1ed5a62d.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222857475-d1c6d92f-931a-4b0b-97e7-7cd07ca64582.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222857498-07e01c70-1581-4940-b9b7-7b67288a67e5.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222857932-65616129-7571-45bb-8b25-5f641223da4c.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222858468-61565059-716f-4173-b164-06e63f5e8cb5.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222858478-5f2d39fb-18ae-46fc-b146-2bf58e31a3ad.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222858510-ce33e05b-02eb-4b7b-80d0-7a69a25bb735.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222858526-45662d4c-17cf-47da-b3b8-33e0931d727d.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222858551-b654798a-2911-4ff4-b61c-6cf365f50c7e.png">|<image width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/222858590-d4439a2d-5606-4087-bd22-030b339354b4.png">
