### ISSUE TITLE
Fix casing for context menu entries on MacOS

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#26163]
## Description 
In https://github.com/brave/brave-browser/issues/25532 we had a discussion on the correct casing on macOS. The conclusion was that context menus should be `Title Case`.

We should update the
`Hide Brave Rewards icon` text to be `Hide Brave Rewards Icon`
`Hide Brave Wallet icon` text to be `Hide Brave Wallet Icon`

Anything else @stephendonner @sangwoo108 @aguscruiz

**Comment by stephendonner** [comment]
> Anything else @stephendonner @sangwoo108 @aguscruiz

I believe that covers them; thanks, @fallaciousreasoning 👍

**Comment by fallaciousreasoning** [comment]
Also, @sangwoo108 made a good point - we could just show hide on these context menus. What do you think?

**Comment by stephendonner** [comment]
> Also, @sangwoo108 made a good point - we could just show hide on these context menus. What do you think?

e.g. `Hide` for both Windows/Linux and macOS - that works, though I'm not familiar with any best practices re: labeling of UI elements for screenreaders.

**Comment by rebron** [comment]
Wallet icon also needs updating.
Currently `Hide Brave Wallet icon`
To `Hide Brave Wallet Icon`

**Comment by sangwoo108** [comment]
> that works, though I'm not familiar with any best practices

https://developer.apple.com/design/human-interface-guidelines/components/system-experiences/the-menu-bar/

> Prefer short, one-word menu titles. Various factors


This line is what I referred to. 


---


> re: labeling of UI elements for screenreaders.

Wow, this is a very good point. I've played with Voice Over on Mac, and find that it could be confusing. Voice over lets me know that I'm in the menu, but I can't know for which this menu is. But in order to trigger a menu item for a button, the button should be focused and Voice Over let us know what button is focused now. So the flow is like

* Focus button
<img width="300" alt="image" src="https://user-images.githubusercontent.com/5474642/197307198-c16e1b9b-acfc-4d2e-b730-1c7b022fdb86.png">

* Open menu
<img width="300" alt="image" src="https://user-images.githubusercontent.com/5474642/197307220-b20e322a-7631-48ab-81f2-f93f336380b0.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/5474642/197307222-bf4cec7b-4ae9-4546-9ebb-afa4955d2b8f.png">

* Navigate to the item
<img width="300" alt="image" src="https://user-images.githubusercontent.com/5474642/197307270-e459cddc-e23e-429c-a141-f893e4178457.png">

---

Maybe context menus for bookmarks could be an analog for this. They have random item title but doesn't show it on the context menu. I think it could be okay because they're literally "contextual" so users could be aware of what they're interacting with. 

---

Then I noticed that could be why Chromium folks put an extension name on the top of extension menu while it's disabled. When using Voice Over and navigating items with keyboard, the name of an extension will be read out.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/5474642/197306840-b23370f5-7b6e-4b7c-953f-39c0cbdc99a0.png">

But this strategy could be too much for our purpose.

**Comment by fallaciousreasoning** [comment]
@rebron what do you think? At the moment, I'm leaning towards just changing the casing, as I don't feel like I know enough about accessibility to make a call on `Hide`

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```


Confirmed casing in the context menu on non-macOS (`Windows`) is as expected.

- Hide Brave Rewards icon
- Hide side panel icon
- Hide Brave Wallet icon

Brave Rewards|side panel|Brave Wallet
----|--------|-----------
<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/207696599-a8954158-fa11-4156-899b-267b0624c707.png">|<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/207696561-f8a9050b-6369-4327-a072-d260bd0086fa.png">|<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/207696520-caa42227-7d76-45c2-867d-4b5fdcd829d7.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.136 Chromium: 108.0.5359.128 (Official Build) beta (x86_64)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 11.7.2 (Build 20G1020)

### Confirmed the strings are:
* `Hide Brave Rewards Icon`
* `Hide Side Panel Icon`
* `Hide Brave Wallet Icon`
* `Hide Brave VPN icon`

`Brave Rewards` | `side panel` | `Brave Wallet` | `Brave VPN`
------------------|-------------|----------------|-------------
<img width="1312" alt="Screen Shot 2022-12-23 at 11 42 52 AM" src="https://user-images.githubusercontent.com/387249/209400131-2c653860-7f8f-4b61-b5e8-96590f65256d.png"> | <img width="1495" alt="Screen Shot 2022-12-23 at 11 43 10 AM" src="https://user-images.githubusercontent.com/387249/209400138-f594600e-6d3e-47ea-969e-90151699c67b.png"> | <img width="1527" alt="Screen Shot 2022-12-23 at 11 43 17 AM" src="https://user-images.githubusercontent.com/387249/209400143-4e02e2f0-dc27-46b3-9c5c-fff8cd0a355c.png"> | <img width="1510" alt="Screen Shot 2022-12-23 at 11 45 47 AM" src="https://user-images.githubusercontent.com/387249/209400146-148ba32e-4231-453a-888c-a25623d35f8a.png">
