### ISSUE TITLE
[Adblock] Custom Filter lists don't get updated automatically.

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#26176]
![image](https://user-images.githubusercontent.com/116318198/197266047-ed2cdc70-ccc8-4516-ae09-afdaa7486589.png)

List added as custom lists in brave://settings/shields/filters have to be manually updated, because they don't do it automatically, even if they sit there for 20 years.

**Local State** is the one responsible for telling the information about it with `last_update_attempt` and `last_successful_update_attempt`, and once they have the same date, then they will never get updated unless the updates are manually pushed.

The function to update the list works though, I know that because if you set `last_update_attempt` to a later date (will throw an error, which has to be ignored), when that time is reached, then the `last_successful_update_attempt` gets updated, and the filter lists gets updated correctly as it should, but after that, never again, they don't get updated automatically like Default or Regional lists do.

![image](https://user-images.githubusercontent.com/116318198/197266341-40fd3d52-349b-4d43-b8e2-c7c9fc2d0f61.png)

Thank you and have a nice day.

**Comment by antonok-edm** [comment]
You might have to be patient... currently all lists are configured to update after 7 days have passed since the last successful update. Even so, they won't update _immediately_; the browser has some heuristics to attempt to identify a good time to schedule the update task based on current activity load, and also potentially network/battery status on mobile. They probably won't be triggered too soon after the browser starts because there's a lot going on in the background.

Some lists have a header specifying they should be updated more frequently than that - we do currently read that information but it's not used yet. See #17909.

**Comment by TheVampireInLoveWithTheCorpsesBlood** [comment]
Thanks for the information @antonok-edm. 
Believe me, this was a valid issue many days ago, but I tested it today and 7 days worked (even tested it with 1000). So, I don't know what happened, but it is good it is working.

But weeks ago, someone in the Community reported "When I opened the settings it said the last update was 17 days ago."
I update my personal lists immediately after editing it, so never noticed this issue, but in my last test the list didn't update for 30+ days, first I modified the time in the Local State and then wait some days for it to update and nothing.

The screenshot was my fault, I didn't post the correct one with 15+ days later, and didn't realize that, I made many tests, so this was really early. Didn't want to seem impatient waiting for lists to update immediately, I tested for 3 weeks this issue.

Anyway, I just wanted to say thanks for telling it is 7 days, the default number.

I appreciate the information, because never got an answer in the community we only got a "all lists update" but not how often the lists are updated or anything, so it was hard to test and know how long I had to wait, how many days to use as a test, of course 15+ days seemed a lot, and never go an update, so I thought something wrong was going on.

But whatever happened, it is working now. 👍

Take care and have a good day, and thanks for your words full of wisdom.
Thanks for all your work.
