### ISSUE TITLE
C72 content setting security review check

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2620]
This issue is to track a security check that's needed for Chromium 72.  It should be closed if everything is OK, or it should be used to track the work if there are needs from the security team. 

bbondy [8:46 AM]
could you let me know if these 2 changes are ok?
https://github.com/brave/brave-core/pull/1117/commits/314a9e26872ed959acb923eb4fb1f95607198eda
an extra new param for chromium 72

bbondy [9:02 AM]
https://chromium.googlesource.com/chromium/src.git/+/f2027f0a91ac0128f9a61c472ca7e518898a8729%5E%21/

As far as I can tell I think it works same as 71 btw.

Related code:

```
diff --git a/components/content_settings/core/browser/content_settings_info.h b/components/content_setti
ngs/core/browser/content_settings_info.h
index a7f691b39e57..834913d7ecc9 100644
--- a/components/content_settings/core/browser/content_settings_info.h
+++ b/components/content_settings/core/browser/content_settings_info.h
@@ -39,12 +39,22 @@ class ContentSettingsInfo {
EPHEMERAL,
};

enum OriginRestriction {
// This flag indicates content types that only allow exceptions to be set
// on secure origins.
EXCEPTIONS_ON_SECURE_ORIGINS_ONLY,
// This flag indicates content types that allow exceptions to be set on
// secure and insecure origins.
EXCEPTIONS_ON_SECURE_AND_INSECURE_ORIGINS,
};
```

from https://chromium.googlesource.com/chromium/src.git/+/f2027f0a91ac0128f9a61c472ca7e518898a8729%5E%21/

**Comment by diracdeltas** [comment]
It appears the purpose of the chromium change was to prevent users from setting exceptions to content settings that wouldn't take effect because certain "powerful" features are being deprecated on insecure origins. For instance chrome [removed the Geolocation API from insecure origins](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only) a few years ago, which means that a user-created content setting for geolocation on an HTTP origin would do nothing.

I don't think the change in question has security implications because even if a feature should be restricted to secure origins and the user is able to set an exception for it, the exception would not take effect on insecure origins. 

From https://chromium.googlesource.com/chromium/src.git/+/f2027f0a91ac0128f9a61c472ca7e518898a8729%5E%21/, it appears Chrome allows plugins/autoplay exceptions to be set on both secure and insecure origins, so https://github.com/brave/brave-core/commit/314a9e26872ed959acb923eb4fb1f95607198eda is in line with that.
