### ISSUE TITLE
Global cookies settings are not retained when a site is added/removed from the `shields down` block 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26288]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/12782
Cookies settings are not retained when a site is added/removed from the `shields down` block 

## Steps to Reproduce

Case 1:

1. clean profile 1.46.x
2. open nytimes.com site in an NTP
3. add nytimes to shield down block in brave://settings/content/braveShields
4. make sure shield is `Down` for nytimes.com
5. click on the shield icon for nytimes.com and make the shields `Up` 
6. make sure shield is `Up` for nytimes.com
7. expand the advanced controls shield settings and look for the cookies settings 
8. cookies settings is `Allow all cookies` but the global shield cookies settings is `Block cross site cookies`
9. global cookies settings are not retained 

Case 2:

1. clean profile 1.46.x
2. add `nytimes.com` in shields down block under `brave://settings/content/braveShields`
3. open `nytimes.com` in an NTP and ensure that shield is down
4. remove the blocked site `nytimes.com` from `brave://settings/content/braveShields`
5. open nytimes.com tab and ensure shield is enabled and default shield settings are retained on nytimes.com
6. change the global shield settings (Trackers and ads = `Aggressive`, FF= `Strict, may break sites` and cookies = `Disabled`)
7. ensured that the updated global shield settings are retained for nytimes
8. add nytimes to shields down block in content settings
10. ensured nytimes shield is down
11. enable the shield for nytimes.com manually
12. ensured shield is enabled and default shield settings are retained on nytimes (steps 6 shield settings are retained)
13. change the global shield settings (Trackers and ads = `Standard`, FF= `Standard` and cookies = `All`)
14. open nytimes, the updated shield settings are not retained for cookies

## Actual result:

Cookies settings are not retained when a site is added/removed from the `shields down` block 

https://drive.google.com/file/d/1ZHYz488-D-nOKpITsRguIhwxNAJ4aSzk/view?usp=sharing
## Expected result:
Cookies settings should be retained when a site is added/removed from the `shields down` block 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 10 Version 21H2 (Build 19044.2130)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @spylogsster

**Comment by btlechowski** [comment]
Reproduced on Linux

Brave | 1.46.117 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Ubuntu 18.04 LTS

**Comment by bridiver** [comment]
@GeetaSarvadnya please use shields up/down terminology because "block" is confusing in this context. Also I assume "enable the shield manually" - means in the UI? Can you please update it to reflect that?

**Comment by bridiver** [comment]
@GeetaSarvadnya if you enable/disable with the shields panel, it will be www.nytimes.com, but in this ticket you specific nytimes.com in `brave://settings/content/braveShields`

**Comment by bridiver** [comment]
If I do [*.][nytimes.com](http://nytimes.com/) then I get shields down, but that is a different setting than what the shields panel controls

If I then re-enable nytimes.com in the shields panel, it shows shields up (because the more specific match is shields up), but cookies are still (incorrectly) applied based on the [*.][nytimes.com] entry

So… there are two bugs here:
1. We’re still showing the effective setting in the UI and that can be broken in all kinds of different ways. That change was supposed to be reverted
2. We’re applying [*.][nytimes.com] to the effective cookies setting even though there’s a more specific setting www.nytimes.com that should take precedence

**Comment by bridiver** [comment]
if I just enter `nytimes.com` in `brave://settings/content/braveShields` then it has no effect on nytimes.com as expected because it's actually `www.nytimes.com` (chromium hides the `www.` by default when you're not editing the url

**Comment by bridiver** [comment]
based on the actual problem I think @boocmp would be the right person for this.

**Comment by GeetaSarvadnya** [comment]
>@GeetaSarvadnya please use shields up/down terminology because "block" is confusing in this context. Also I assume "enable the shield manually" - means in the shields panel? Can you please update it to reflect that?

@bridiver Yes, in the shields panel, I will update the steps. Thanks!

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.48.125 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

1. Install 1.48.125
2. launch Brave
3. visit nytimes.com site in a new-tab page
4. open `brave://settings/content/braveShields`
5. click `Add` button in the `Shields Down` section under `Sites listed below...`
6. add  [*]nytimes.com in the dialog
7. confirmed `Wildcards are not allowed for Brave Shields.` message displayed
8. click Cancel and add `www.nytimes.com`   (enter `www` in order to disable Shields)
9. return to nytimes.com tab 
10. confirmed `Shields Down` in the Shields panel 
11. enable Shields in the Shields panel 
12. return to brave://settings/content/braveShields 
13. confirmed `www.nytimes.com` was removed from the `Shields Down` section
14. expanded the `Advanced controls` in the Shields panel
15. confirmed `Block cross-site cookies` settings shown  
16. cookies settings is Allow all cookies but the global shield cookies settings is Block cross site cookies
17. open brave://settings/shields 
18. confirmed `Block cookies` settings show `Only cross-site`

#### Confirmed wildcard entries are blocked  for Shields in `brave://settings/content/braveShields`
#### Confirmed cookie settings Per site and Global settings have `Cross-site`

step 3|step 6-7|step 8|step 10|step 11|step 12|step 15|step 18
------|----------|--------|--------|-------|----------|-------|-------
<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/212414924-4721c0b2-4f00-4be3-b5ee-2488bf8f0642.png">|<img width="476" alt="image" src="https://user-images.githubusercontent.com/98358127/212413888-92ddd5dc-bc30-424a-9167-d3651cbec0c0.png">|<img width="477" alt="image" src="https://user-images.githubusercontent.com/98358127/212412416-c089bfdb-6d74-45a3-8858-0e54ac9a7f92.png">|<img width="479" alt="image" src="https://user-images.githubusercontent.com/98358127/212412398-d5c10a95-36f5-4442-bd69-b87c847d2264.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/212412493-2b34311b-cf7e-43ba-b1e2-506bff1e1ee3.png">|<img width="471" alt="image" src="https://user-images.githubusercontent.com/98358127/212417491-ee43200e-04cd-43db-a7c2-4b3dcd81ad57.png">|<img width="469" alt="image" src="https://user-images.githubusercontent.com/98358127/212412723-0306aeb0-cd2e-4622-b6bb-e5a3d8813cc0.png">|<img width="473" alt="image" src="https://user-images.githubusercontent.com/98358127/212415674-8ebe1481-ba2a-4001-ab79-13808d084fc5.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.48.131 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

### Case 1: Block wildcard entry for Shields - (Do not update Shields settings) - `PENDING`
<details>

</details>


### Case 2: Block wildcard entry for Shields - (Update Global Shields settings) - `PENDING`
<details>

</details>


### Case 3: Allow wildcard entry for non-Shields content settings - `PENDING`
<details>

</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.48.140 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | Linux
```
#### Case 1:  Block wildcard entry for Shields - (Do not update Shields settings) - `PASSED`

<details>

1. Install 1.48.140
2. launch Brave
3. visit `nytimes.com` site in a new-tab page
4. open `brave://settings/content/braveShields`
5. click `Add` button in the `Shields Down` section under `Sites listed below...`
6. add  `[*]nytimes.com` in the dialog
7. confirmed `Wildcards are not allowed for Brave Shields.` message displayed
8. click Cancel and add `www.nytimes.com`   (enter `www` in order to disable Shields)
9. return to nytimes.com tab 
10. confirmed `Shields are Down` in the Shields panel 
11. enable Shields in the Shields panel 
12. expanded the `Advanced controls` in the Shields panel
13. confirmed `Block cross-site cookies` settings shown  
14. return to brave://settings/content/braveShields 
15. confirmed `www.nytimes.com` was removed from the `Shields Down` section
16. open brave://settings/shields 
17. confirmed `Block cookies` settings show `Only cross-site` as expected

#### Confirmed wildcard entries are blocked  for Shields in `brave://settings/content/braveShields`
#### Confirmed cookie settings per site and Global settings show `cross-site`

step 3|step 6-7|step 8|step 10|step 11|step 13|step 15|step 18
------|----------|--------|--------|-------|----------|-------|-------
