### ISSUE TITLE
Performance issues in web audio getChannelData

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#26507]
https://linxin2020.github.io/hls_live/js_performance.html

Per Slack discussion, this is likely related to our web audio farbling. HOWEVER "allow all fingerprinting" does not noticeably improve performance, suggesting the problem lies in the checks/callback mechanism rather than the actual data farbling routine.

**Comment by fde31** [comment]
We've run into this issue in an Audi application when creating interleaved versions of AudioBuffers for further processing.

Iterating over the data and copying it over using `AudioBuffer.getChannelData` stalls Brave. It does it but given the performance hit it basically becomes unusable for the end user, mimicking the behaviour of an infinite loop.

One can get around this using `AudioBuffer.copyFromChannel` for each channel previously and then creating the interleaved Float32Array from the channel data but I'm not certain that's ideal.

I've created a simple test case for comparison of both methods:
https://gist.github.com/fde31/12a770030c06edf5213992925289acf4

Note that the example uses a very short 4 channel AudioBuffer with length 1000. However, running this on my machine I see Brave reporting ~65 ms when using `AudioBuffer.getChannelData` vs ~0.4 ms when previously copying the contents using `AudioBuffer.copyFromChannel`.

**Comment by cowwoc** [comment]
Thanks for pointing out this issue @fde31.

@pilgrim-brave We've got at least 2 potential issues impacted by this bug:

https://github.com/brave/brave-browser/issues/22178
https://github.com/brave/brave-browser/issues/25135

There may be more.

**Comment by LaurenWags** [comment]
@pes10k @pilgrim-brave since this has `QA/Yes`, a test plan is needed. 

Marking as `QA/Blocked` until there is one.

cc @kjozwiak @rebron

**Comment by pes10k** [comment]
@pilgrim-brave can you link to a site that was causing the issue in the wild?  That'd probably be enough for this QA wise

**Comment by pilgrim-brave** [comment]
https://linxin2020.github.io/hls_live/js_performance.html

test with shields up (default settings) and down

before this PR, both shields up and down caused "unresponsive page" dialog

after this PR, shields down should return a result in a reasonable time (page will report it in ms)

**Comment by kjozwiak** [comment]
> https://linxin2020.github.io/hls_live/js_performance.html
> 
> test with shields up (default settings) and down
> 
> before this PR, both shields up and down caused "unresponsive page" dialog
> 
> after this PR, shields down should return a result in a reasonable time (page will report it in ms)

Thanks for the information @pilgrim-brave 👍 As discussed, lets label this as `QA/No` as this will be hard to verify. Some users might not run into the `Unresponsive` issue. I added some notes via https://github.com/brave/brave-core/pull/15894#issuecomment-1339877430. Also adding the `OS/Android` label as this code change also affects `Android`.

**Comment by fde31** [comment]
I'm not that insightful into the QA process and decision process here but I think while the test case at https://linxin2020.github.io/hls_live/js_performance.html is a useful benchmark one think that t might have gone missing is the fact that it operates on based on AudioBuffer with a length of 1s (44100 samples).

Such short buffer length might not represent a real world use-case (especially not for Audio related programming) with potentially bigger buffer sizes and therefore not trigger the "unresponsive issue" originally described here although it does show much slower performance in contrast to other browser. In order to help showcasing this I've set up a test site here https://www.fde31.com/tests/brave_channeldata_perf.html

The test environment creates an `AudioBuffer` with a length of `60 x 44100` (60s * 44100 samples) and then copies data from it into an interleaved format in a `Float32Array`. For comparison it does that using `getChannelData` and `copyFromChannel`.

If I load this up in the latest Brave Nightly builds I'm experiencing the same behaviour / issue that basically stalls the tab, similar to the behaviour of an infinite loop, forcing me to restart Brave eventually to resolve it.

**Comment by goodov** [comment]
@fde31 thank you, that's very helpful! We are on the way to optimise one more call, and I've mentioned your comment there https://github.com/brave/brave-core/pull/16264

**Comment by bluenoah1991** [comment]
Why is Chromium so much slower than Chrome on this test page?

https://linxin2020.github.io/hls_live/js_performance.html

Chromium for Windows x64 117.0.5938.0 : 2528.199999809265 ms
Official Chrome for Windows x64 117.0.5938.134 : 16 ms

**Comment by pes10k** [comment]
Because, in order to randomize the WebAudio fingerprint, we need to copy and alter the audio buffer.  The performance has been improved significantly because of the work described in this issue, but at root there is unavoidably more work happening. Given that i. the vast majority of the use of this API on the Web is from fingerprinting scripts, and ii. at least a fair amount of the benign use of this API on the Web is not in a perf-critical point (e.g., export file to disk) we're comfortable with this trade off (even if we're still exploring and open to additional optimizations)
