### ISSUE TITLE
Unresponsive webpage on td.com (with shields disabled)

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#26562]
## Description 
With shields disabled, td.com has delay, or lag during the login progress.

## Steps to Reproduce

(May need a CA IP)

   1. Open `https://www.td.com/ca/en/personal-banking/`
   2. Click on EasyWeb login
   3. Hovering over the register button, notice delay in clicking on the button

## Actual result:
Page delay when loading the site.  (this error may/may not show, but it mostly just slow with shields disabled)

<img width="346" alt="screen_shot_2022-11-04_at_08 57 01" src="https://user-images.githubusercontent.com/1659004/200094554-52de95f8-16d7-4d68-ac47-4ed875355f93.png">

## Expected result:
No delay clicking on Register button

## Reproduces how often: 
Easily reproduced, may need a CA IP for testing. Page delay.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
We have a fix in shields, but with shields disabled it will lag. We should have similar results with Chrome (with no adblock)
Site is using threatmetrix causing this.

Doesn't affect Ungoggled Chromium

**Comment by ryanbr** [comment]
![dedicated-workers-brave](https://user-images.githubusercontent.com/1659004/200095646-72a0cc0b-03fe-48dc-993e-344c764a9fa4.png)

Compared to chrome, these multiple dedicated workers expired much quickly. In Brave they delayed in closing causing the CPU

**Comment by goodov** [comment]
related: https://github.com/brave/brave-browser/issues/26507

@pilgrim-brave The issue is in the way we farble data via `base::RepeatingCallback` - it contains a ref ptr which is incremented/decremented during each `Run()` call, which is atomic and is actually slow when we're talking about hundreds-thousands of calls during each frame.

We need to remove this callback and just make it as a function in `BraveSessionCache` which receives the whole audio buffer and does the farbling in one for-loop. I strongly suggest to remove `base::RepeatingCallback` in other farbling-related parts.

note: with this latest fix https://github.com/brave/brave-core/pull/15917 the farbling is properly disabled on `td.com` and the page is fine, but this is not the real solution.

some profiler data:
![image](https://user-images.githubusercontent.com/5928869/205269678-3ce819e3-a0ac-4248-a535-0669bfe6e539.png)

**Comment by dkoo761** [comment]
Thank you guys so much for fixing this so quickly! I'm a TD customer and it was driving me bonkers every time I tried to log in 🤪
