### ISSUE TITLE
Show account creation panel for dapp's account creation request 

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#26637]
## Description 
Show account creation panel for dapp's account creation request. It is triggered when user has no corresponding account for the dapps request type.  (Solana account for Solana dapps)

**Comment by srirambv** [comment]
Moving this out of milestone for now. Since Dapp support is disabled on release channel via #26804, this issue can't be checked/verified. This will need to be checked again when Solana Dapp support is enabled. Moving this to 1.47.x where this can be verified.


cc: @Pavneet-Sing @SergeyZhukovsky @jamesmudgett @brave/sec-team
