### ISSUE TITLE
Whitespace at the beginning or end of the recovery key prevents wallet recovery

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2665]
## Steps to Reproduce

   1. Go to `brave://rewards/`
   2. In `Manage You Wallet` use a recovery key with whitespace at the end/beginning of the key (tried `Space` and `Enter`)
   3. Restore the wallet

## Actual result:

![image](https://user-images.githubusercontent.com/34715963/50257984-f4ca0400-03fd-11e9-815f-b408eaa97702.png)

User may get the wrong impression that wallet recovery does not work even though recovery key is correct.

## Expected result:
Whitespace is trimmed from the beginning and the end of the recovery key

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

cc @NejcZdovc @brave/legacy_qa

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1169

**Comment by Christy930** [comment]
Due to the high rate of binary option scam, I will advise that we be even more cautious when dealing with digital assets (BTC/ETH). If you have already been a victim of a binary option scam, as I once was, and wish to recover your lost investments, you must enlist the assistance of a highly qualified private investigator and a reputable recovery expert.
Adrian Lamo would be the best choice if that were the case for very effective and professional recovery and hacking services. With the aid of this amazing tech whiz, I was able to recover everything I lost to a phony binary broker in just three days after contacting them via their official website. At (HACK WITH ADRIAN LAMO @ Gmail . com)
