### ISSUE TITLE
Change title text to "Monthly contribution failed" in Auto-Contribute + Monthly Tip error toast notification

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#26719]
## Description

![image](https://user-images.githubusercontent.com/11497541/201497717-0969859d-1f2a-44ef-a0af-cd258c2b8e01.png)

- [ ] Change to "Monthly contribution failed"

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.129 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 12.6.2 (Build 21G320)
```

Note - need to have a balance of less than 0.25 BAT, otherwise AC and/or monthly tip will succeed. I used Uphold to have a balance of 0.15, so my AC and monthly tip would fail.

1.47.171 | 1.48.129
---- | ----
<img width="422" alt="Screen Shot 2023-01-18 at 3 11 28 PM" src="https://user-images.githubusercontent.com/28145373/213288252-249e32d4-845e-4287-b28b-e8f5e409ff40.png"> | <img width="433" alt="Screen Shot 2023-01-18 at 3 20 18 PM" src="https://user-images.githubusercontent.com/28145373/213288253-04a8c336-4215-4525-8191-ca0f48319133.png">
