### ISSUE TITLE
enable SpeedreaderPanelV2 and remove flag

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#26777]
## Description 

Enable Speedreader Panel v2 by default and remove "SpeedreaderPanelV2"

## Brave version (brave://version info)

Target 1.47.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

https://github.com/brave/brave-browser/issues/24528
https://github.com/brave/brave-browser/issues/26117

**Comment by LaurenWags** [comment]
@nullhook @petemill could we please get a test plan for this one since it is marked `QA/Yes`? The linked issues in the description are `QA/No`, not sure if there's anything from them that needs to be verified? Didn't see any other issues in this milestone (that are `QA/Yes`) which would cover testing of any new UI or functionality.

Labelling as `QA/Blocked` until this is sorted out.

cc @rebron for additional help here

**Comment by nullhook** [comment]
Added a test plan

**Comment by LaurenWags** [comment]
per discussion in today's QA overview with @rebron - waiting on some changes to be uplifted, so keeping this `QA/Blocked` for now.

**Comment by stephendonner** [comment]
Also, need to ensure https://github.com/brave/brave-browser/issues/27291 is fixed before we test the rest.

**Comment by LaurenWags** [comment]
Per discussion with @rebron, this will be reverted via https://github.com/brave/brave-browser/issues/27675.

Once reverted we can mark this one as `QA/No`, but leaving it as-is for now, so it doesn't get lost/forgotten about.
