### ISSUE TITLE
Linux build instructions could be simplified

### ISSUE THREAD

**Issue by bkero** [brave/brave-browser#2679]
## Steps to Reproduce

   1. View documentation at https://github.com/brave/brave-browser/blob/master/docs/source/installing-brave.rst
   2. Attempt to follow directions for Ubuntu or Mint

## Actual result:

Slightly longer process

## Expected result:
Simpler documentation

## Reproduces how often: 

Always

## Brave version (brave://version info)

Release

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Smooey** [comment]
Is it just me or is Brave almost impossible to install on a non-systemd Linux Distro? I tried various non-systemd distros lately and I couldn't install it properly into any of them. Not with snap, not with pacman, not with AUR/Yaourt etc... wtf. 

Is brave browser dependent on "systemd"? I have Artix linux installed in virtual box and package manager, and see Chromium there, Firefox, etc... Isn't Brave now using Chromium as well? They don't list Brave any where though. Just like Void linux and some other non-systemd distros. And I don't want to or shouldn't have to do the 30 to 45 minute git clone thing just to get brave on a desktop... LOL

**Comment by btwiusegentoo** [comment]
When you extract Brave, you'll have to include the directory that contains it in your $PATH. Something like:

`export PATH="${HOME}/Brave:${PATH}"`

should work if you replace Brave with the directory that you extracted it to. This allows you to execute brave from a program launcher (dmenu, rofi) and without specifying or changing to the extracted directory. Since you mentioned under "Internet", a *.desktop file isn't included and it won't show up as a desktop icon or under menus.

As for the deb package, I'd highly recommend against installing another package manager on your system.

**Comment by Smooey** [comment]
Not sure what you're meaning but was wondering if I could just download the .zip archive of it to downloads folder and move (mv) it to /home directory. Then in terminal use "unzip" to unzip it into like "Brave" or "Brave-Browser" folder. Then use "make" command on it in terminal? Arch Linux uses Make etc for package building...

**Comment by btwiusegentoo** [comment]
(I've never used Artix so I'm only assuming Arch tools are included)

The problem with just running make inside of the unzipped folder is that there's no makefile or PKGBUILD. After researching Artix a bit, it seems that you can use the AUR.

```
git clone https://aur.archlinux.org/brave-bin.git ~/Brave
cd ~/Brave
makepkg -sirc
```

There's also `brave-beta-bin` and `brave-dev-bin` if you're interested. This is a pretty minimal way of handling AUR packages so to update Brave without an AUR-specific package manager, you'll have to:

```
cd ~/Brave
git pull
makepkg -sirc
```

**Comment by Smooey** [comment]
Reporting back, I managed to get it "installed" with yaourt -S brave-bin ... and built the package or whatever in yaourt after having "base-devel" installed which contains "make" and so forth. It shows up in "internet" part of menu.. but doesn't launch. Trying to run it in terminal gives message about namespaces being disabled etc. So ran it as "sudo brave" and then get warning and so forth about "User namespaces aren't detected as enabled on your system, brave will run with the sandbox disabled". But it don't run without "sudo" in terminal and won't run by clicking on it in menu... >_>.. always something... can't win. Lol

**Comment by Smooey** [comment]
Thanks for reply, will try that then too. :)

**Comment by btwiusegentoo** [comment]
Ah, yeah. Don't run your browser with sudo. You can pass the `--no-sandbox` flag and it should run. You can try to contact the Artix devs to ask about user namespace support in the kernel.

**Comment by btwiusegentoo** [comment]
yaourt is a package manager for the AUR so definitely stick with that. As for the complexity, it depends on the distro you use and the maintainers. Brave isn't currently packaged for many distros because of lower demand and being rather new. 

Could you try this?

`sudo echo 1 > /proc/sys/kernel/unprivileged_userns_clone`

and then try to run Brave from your menu.

**Comment by Smooey** [comment]
Yeah true. 

I tried that as sudo and got permission denied. So I logged in terminal as "root" and it ran it. But Brave still doesn't open from menu. Running just "brave" in terminal, doesn't give username space message... but still gives that ""trace/breakpoint trap" message.. and doesn't run Brave at all. LOL

**Comment by btwiusegentoo** [comment]
Hmm. Can you provide that message? I've been unable to reproduce but may have seen a similar problem to the one you're having.

**Comment by Smooey** [comment]
Not sure how to provide it? But in terminal at command line, I just type: 
brave
then next line it says:
Trace/breakpoint trap

Then get a new line with blinking cursor. Unless I'm missing 32Bit related stuff or something? But Brave is 64Bit... but maybe the OS is missing some dependencies for 32bit to run Brave properly.. I dunno. Cause this isn't systemd, this is "runit" not OpenRc.

**Comment by btwiusegentoo** [comment]
It definitely has nothing to do with multilib and it shouldn't have a problem with the init system since it doesn't depend on anything specific to either one. At this point, you should open a new issue and mention this so people with more experience can help you out as that's not normal and I'm not familiar enough with Artix or runit to be any help.

**Comment by Smooey** [comment]
Updating you, after a reboot, those kernel adjustments were set back to default again and got that message again about namespaces. But found someone else's comment about doing this to make it permanent. 

> However in my opinion the easiest workaround for now is sudo sysctl kernel.unprivileged_userns_clone=1 and to make it permanent echo kernel.unprivileged_userns_clone = 1 | sudo tee /etc/sysctl.d/00-local-userns.conf

But the same issue with Trace/breakpoint trap still remains. I think I seen in a Red Hat Bug tracker site, someone had that in regards to "headless chromium" and using "headless chromium". 
https://bugs.chromium.org/p/chromium/issues/detail?id=782161

**Comment by Smooey** [comment]
> (I've never used Artix so I'm only assuming Arch tools are included)
> 
> The problem with just running make inside of the unzipped folder is that there's no makefile or PKGBUILD. After researching Artix a bit, it seems that you can use the AUR.
> 
> ```
> git clone https://aur.archlinux.org/brave-bin.git ~/Brave
> cd ~/Brave
> makepkg -sirc
> ```
> There's also `brave-beta-bin` and `brave-dev-bin` if you're interested. This is a pretty minimal way of handling AUR packages so to update Brave without an AUR-specific package manager, you'll have to:
> 
> ```
> cd ~/Brave
> git pull
> makepkg -sirc
> ```

I'm trying this again but in Void linux this time. I got as far as the cd ~/Brave and tried doing "makepkg -sirc" but it didn't work. I did "cd" to get into the /Brave folder and noticed the "brave-bin.sh" script there and tried running it as root or sudo.. and it won't run get error.. 

Syntax error: "(" unexpected (expecting "then") 

So tried "dos2unix" after installing it, still same error. Tried `sed -i 's/\r$//' ` brave-bin.sh and still didn't work. Lol. I have "make" installed on Void Linux.. but can't run "makepkg" or whatever and can't run that "sirc" either.

**Comment by btwiusegentoo** [comment]
makepkg is a tool for installing packages on Arch (and Arch-based). The `brave-bin.sh` file is managed by the PKGBUILD, which is of no use to you (every step I listed is only doable on distros that handle Arch packages). I checked Void's packages and I don't see Brave, so the only thing you could do is download the zip from releases.

I had to do that here on Gentoo, and it goes something like:

```
# download the desired brave-{version}-linux-x64.zip
unzip brave*.zip -d Brave
cd Brave
./brave
```

If you get any messages about libX* or similar, it means you're missing dependencies. `make` and anything else will be of no use to you since you have to deal with it manually on distros that don't have Brave packaged. You may be better off using a distro where it is packaged since you shouldn't see any problems with it and there'll be no doubt that it is installed and works properly.

**Comment by Smooey** [comment]
Thanks for your reply. :) That makes sense then why "makepkg" wasn't working in Void linux... Lol! Where it did "Artix" cause Artix was built from Arch linux. Okay, I think I did download that zip file I wanted... and I believe it's in the /Downloads folder. Should I move it to /home or /home/username folder before unzipping it. Or run the unzip command above no matter where it's located.. then just run "./brave" from the Brave folder each time? 

I probably will end up having to use another distro though, but I love challenges and trying to get things working anyway. Lol! I also don't mind learn new distros of course, just sucks sometimes when takes so long to get a single browser installed in order to "learn" something. Lmao

**Comment by btwiusegentoo** [comment]
You can extract it wherever you'd like. If you use unzip, the `-d` flag can be used with absolute paths so it could be `unzip brave*.zip -d ~/Brave` (`~` will be expanded by your shell so `/home/user/Brave` is the result). From there, yes, you run `./brave` from inside the Brave folder. You can also run`~/Brave/brave` if you don't want to cd each time.

**Comment by Smooey** [comment]
Thanks, I did your first unzip command above there just to test it out and got it working now. Logged in and posting from VirtualBox of Void Linux Lol! Yeah I did get some errors from terminal... maybe I could find those dependencies and install them.. unless they don't have them in their repos. 

` ./brave
[1442:1442:1222/235703.489575:ERROR:platform_thread_posix.cc(128)] pthread_create: Invalid argument (22)
[1442:1442:1222/235703.490253:ERROR:shutdown_signal_handlers_posix.cc(199)] Failed to create shutdown detector task.
[1442:1442:1222/235703.544359:ERROR:browser_dm_token_storage_linux.cc(93)] Error: /etc/machine-id contains 0 characters (32 were expected).
[1474:1474:1222/235703.996375:ERROR:gl_implementation.cc(281)] Failed to load /home/dt/Downloads/Brave/swiftshader/libGLESv2.so: /home/dt/Downloads/Brave/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1474:1474:1222/235704.029356:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[1539:1539:1222/235704.705156:ERROR:gl_implementation.cc(281)] Failed to load /home/dt/Downloads/Brave/swiftshader/libGLESv2.so: /home/dt/Downloads/Brave/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1539:1539:1222/235704.728983:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
[1442:1462:1222/235704.810625:ERROR:rewards_service_impl.cc(141)] Failed to read file: /home/dt/.config/BraveSoftware/Brave-Browser/Default/ledger_state
[1442:1450:1222/235704.837316:ERROR:browser_gpu_channel_host_factory.cc(139)] Failed to launch GPU process.
[1442:1442:1222/235705.278021:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.
[1442:1442:1222/235705.627649:ERROR:x11_input_method_context_impl_gtk.cc(144)] Not implemented reached in virtual void libgtkui::X11InputMethodContextImplGtk::SetSurroundingText(const base::string16 &, const gfx::Range &)
`

**Comment by Smooey** [comment]
Hm, nope.. still gives those errors in terminal. Even unzipped it into the /home/dt/Brave location. And running ~/Brave/brave works in terminal like you said. It ain't greatest though, but at least "works" in away. Cause after while, the web page goes blank/black or whatever after while. I'll probably have no choice but stick to distros that package it. Which sucks, cause seems like only distros that do have it are "systemd" init based distros. >_<

**Comment by Smooey** [comment]
I'll probably give MX Linux a try again... they just release version 18.00 12/20/2018.. they use SysV for their Init and it's Debian Stable based. 

https://distrowatch.com/table.php?distribution=mx
DistroTube review
https://www.youtube.com/watch?v=nsd3cXRJ_bs

**Comment by btwiusegentoo** [comment]
The binary doesn't require swiftshader, that's just caused by it trying to load OpenGL ES but I'm not sure if that's a fallback in the chromium source as I've never actually seen that (not experienced enough with that so this may be wrong). As for MX, it's a pretty nice distro and a good choice. Hope it works out better!

**Comment by Smooey** [comment]
Thanks for all your help though. I might get frisky and reinstall Artix and Void again in future in virtual box and try those new installation steps of Brave. Well, I tried it in Artix the same installation method I last did in Void, but it wouldn't work cause of not having write permissions to that directory /home/dt/Brave or whatever. So I just said screw it and deleted the VM for both Artix and Void. After a while it gets tiresome trying to get thing working. I like figuring out issues etc.. but at same time I'm wasting too much time diagnosing errors and issues and installing Brave. It shouldn't be so complex. Lol! I had MX 17 installed before, but not sure WHY I removed it in VM before... There must have been something I didn't like or whatever... just can't remember it. I have MX 18 ISO downloaded already, so will try installing it after I watch DistroTube's review video. :) Hope it works out too! LOL! I liked Arch linux in the past, I like building own distro from the ground up so I know what's installed or not. But at same time disliking the systemd anymore. I was looking at Slackware or Gentoo, but read up a little how Gentoo can take days to compile everything and I don't want to spend days compiling in a VM ... or main computer LOL. I like having things installed fairly quickly to use them. If I install Artix or Void again, I'll report back with the output of that command you gave above there...

**Comment by Smooey** [comment]
Alright, installed MX 18, it's beautiful. Downloaded the right DEB file from here and installed it easy peasy in MX Linux. But it still didn't launch right cause needing username spaces enabled in kernel. Which to me is odd and seems like possible security risk... 

This fixes it: https://community.brave.com/t/solved-brave-not-launching-on-debian-linux/3255/4
https://forum.mxlinux.org/viewtopic.php?f=108&t=45003&p=445148&hilit=brave+browser#p445146

But at least it's installed and working now in MX Linux. :D I'll have to experiment a little more with MX Linux and see how things go.

**Comment by srirambv** [comment]
@mihaiplesa  Could you please link the PR which closes the issue and update the milestone accordingly? Also please add `QA/Yes` or `QA/No` labels.
