### ISSUE TITLE
Unable to add CRYPTOPUNKS as NFT

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27037]
## Description 

Unable to add CRYPTOPUNKS NFT https://etherscan.io/token/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb

## Steps to Reproduce

[nft-eth.webm](https://user-images.githubusercontent.com/11755381/204555548-d2dd611a-0e5e-4bfe-80ec-2c4d8638e652.webm)

## Reproduces how often: 

easy

## Brave version (brave://version info)

Version 1.48.5 Chromium: 108.0.5359.48 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by muliswilliam** [comment]
The issue is that a user is unable to add CryptoPunk NFTs in the wallet because when they add contract address and select network, the form changes tab to Token tab. This behaviour is as expected. The main reason is that in out token list CryptoPunk token(contract address: 0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB ) has isErc20 set to true . This is also okay because the contract does not implement ERC721 standard. Cryptopunks were released before ERC721 standard. A way to fix this is to treat Cryptopunk tokens as a special case. From my conversation with @nvonpentz this effort is not worth it at the moment because it benefits a limited number of users

**Comment by Pavneet-Sing** [comment]
@muliswilliam Cool, Thank you for the details and efforts.
BTW, I think we should keep this open until this is fixed as other may experience this issue or we may come back to this later? (then probably update the label as backend issue)
