### ISSUE TITLE
Some URLs appear to trigger SpeedReader, without actually showing the icon in the address bar to disable the feature

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#27085]
## Description 

Some URLs appear to trigger SpeedReader, without actually showing the icon in the address bar to disable the feature:

I guess there is a race condition.

@jonathansampson reproduced it on stackoverflow (https://bravesoftware.slack.com/archives/CLX7EV42Z/p1665259070985259)

## Steps to Reproduce

Navigate to https://usathrill.com/news/us/amazon-has-teamed-up-with-grubhub-to-provide-free-food-delivery/

## Actual result:

Page redirected to https://usathrill.com/amazon-has-teamed-up-with-grubhub-to-provide-free-food-delivery/
Content distilled but speedreader button doesn't appear.

## Expected result:
Page should not be distilled because redirected url not eligible for distilling.

## Reproduces how often: 

Easy/100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.119 Chromium: 109.0.5414.80 (Official Build) beta (x86_64)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed `1.48.119`
2. launched Brave
3. loaded `https://usathrill.com/news/us/amazon-has-teamed-up-with-grubhub-to-provide-free-food-delivery/`
4. confirmed URL redirected to `https://usathrill.com/amazon-has-teamed-up-with-grubhub-to-provide-free-food-delivery/`

#### Confirmed page was *not* distilled by Speedreader, nor did I see the icon in the URL bar (since it's unable to be distilled)

<img width="1428" alt="Screen Shot 2023-01-10 at 1 55 44 PM" src="https://user-images.githubusercontent.com/387249/211671256-9d559456-d1c7-4187-8747-2e73409003ee.png">
