### ISSUE TITLE
Filecoin tweaks for the new wallet UI

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#27182]
1) When new filecoin acc is created "Testnet" word should be added if testnet\localhost network is used

2) On the select sender acc screen, testnet instead of localhost word should be used:
![image](https://user-images.githubusercontent.com/106654560/205953799-52bad249-0681-49a8-b842-1784992b6bc7.png)

3) Filecoin testnet accs are not shown if testnet is selected, they are shown only if localhost is selected
![image](https://user-images.githubusercontent.com/106654560/205953928-017f1549-28c6-47e3-b94c-bd115cd8394e.png)

4) If sender is testnet acc i am still able to choose mainnet acc as the recepient
![image](https://user-images.githubusercontent.com/106654560/205954373-7b89e705-b62c-45d4-9f1a-8c2c0c66c2ea.png)

5) Accs has different addr length on previous screen

6) Sender acc addr is not shown if there is no funds
![image](https://user-images.githubusercontent.com/106654560/205955121-2bfdb82a-da9a-4bab-91b2-e2b7265e638d.png)

7) Current network is not mentioned after acc is selected
![image](https://user-images.githubusercontent.com/106654560/206501510-21aff456-da68-494c-a491-a0084aa77104.png)

**Comment by cypt4** [comment]
CC @srirambv

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.48.151 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.1105)

- Verified step from issue description
- Verified Mainnet/Testnet is shown when creating Filecoin account
- Verified on the select sender account screen, mainnet/testnet is shown instead of localhost 
- Verified Filecoin Testnet accounts are shown when Filecoin Testnet is filtered in the network selector
- Verified only able to select testnet accounts in receiver account dropdown. Can't select Mainnet accounts
- Verified address shows different length based on selection. Testnet/Mainnet addresses length is the same


https://user-images.githubusercontent.com/17010094/216261836-45cc352f-a4c9-47b7-9ae2-bb1fda4f2629.mp4
