### ISSUE TITLE
PageGraph (or PageGraph-crawl) crash when visiting certain url (e.g. www.youtube.com)

### ISSUE THREAD

**Issue by syx1031** [brave/brave-browser#27448]
## Description 

When I run PageGraph-crawl for generating a pagegraph, brave crashed without any useful information.
visit https://www.youtube.com and  https://twitter.com will lead to this problem but https://www.google.com or many other webpage will not.
![LQ1~F3X%76MXQYD43RWTU3K](https://user-images.githubusercontent.com/71998982/208421574-4fd365e6-c7c9-4bd9-a60d-76b0baecfecf.png)
I comment codes in PageGraph-crawl about PG (several lines) like above and then brave can rightly close after 30 seconds,but when I release these codes, the problem appear like this:
![$B8_OO4MEFFN96FP10R)PT5](https://user-images.githubusercontent.com/71998982/208422074-7e15786e-b9d2-4bae-a4c3-c7cf52ac389d.png)
and brave will crash down at the same time.

## Steps to Reproduce

   1. git clone PageGraph-crawl
   2. 
![image](https://user-images.githubusercontent.com/71998982/208422514-f142b5ad-422a-40d1-b782-f3d2b75d7049.png)

## Actual result:

just like above

## Expected result:
crawl 30s and brave close rightly.

## Reproduces how often: 

everytime

## Brave version (brave://version info)

![image](https://user-images.githubusercontent.com/71998982/208423485-8dd29714-90e1-405c-b09a-248b50ba3729.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  no(release now doesn't include PageGraph in its core)
- Can you reproduce this issue with the beta channel?  maybe
- Can you reproduce this issue with the nightly channel?  yes

**Comment by syx1031** [comment]
What's more, I'd like to know that how can I participate in developing brave and debugging PageGraph's code, it seems that there isn't any developer document in github and so I don't know how to start with thousand of files.

**Comment by naifmeh** [comment]
Hi !

I've been facing the same problem with Pagegraph: 
* On some websites such as https://eurosport.com or https://bbc.com, the issue arise only after interacting with the cookie banner
* I could reproduce your issue with youtube without any interaction with the cookie banner whatsoever but could not get Twitter to crash
* Note that the crash does not happen when the shields are up for Eurosport and BBC

This seemed to indicate that the issue is coming from a script that Pagegraph can't handle (most probably from Google). Checking Pagegraph's verbose logs showed that a script (verbose shows its content) was loaded right before it crashed: it's obfuscated code except for the first bunch of characters which seemed to be fixed. Using this, I intercepted network requests coming after interacting with the cookie banner on BBC and found that one URL contained this script. I then checked for the same URL and found it on Eurosport as well (after interacting with the cookie banner). 
The same script was loaded by default to Youtube but under a different URL.

If you don't mind discarding these requests, the websites stop crashing after blocking them directly in Puppeteer. Can be done by adding these few lines to 'crawl.ts' after the CDP session is created:


```typescript
await client.send('Fetch.enable', {
   patterns: [
          {
            urlPattern: '*',
            requestStage: "Request"
          },
        ],
});

client.on('Fetch.requestPaused', (requestObj: any) => {
    if(requestObj.request.url in ["https://pagead2.googlesyndication.com/bg/GC5M5N_VN3lVd7ErmxmldCKoshgV9d2S74rLP9hyoZw.js", 
"https://www.google.com/js/th/YkfklCtf3s5-_1quWHAnTHHVaBZ-i7ToAeXFpu3i2Ro.js"]) 
            return;

    client.send('Fetch.continueRequest', {requestId: requestObj.requestId});
});
```

This isn't a good solution though:
* I'm fairly certain these URLs are not fixed and keep changing so a better solution for you might be to block every request where you find the content of the first line of this script. 
* Also, this script might initiate other requests, so by blocking it, it might prevent a bunch of other requests. Depending on what you are trying to do/analyze, this isn't ideal.

The best solution would be to find what is causing this issue and fix it in Pagegraph. However, I couldn't figure yet what this script does, so I'm not sure what causes Pagegraph to crash.
I can investigate potential ideas if there are any !

**Comment by naifmeh** [comment]
I expected this solution to not last long, as these URLs tend to be very volatile. Here is a more robust approach, as long as the script's fixed line doesn't change:

```javascript
await client.send('Fetch.enable', {
    patterns: [{
            urlPattern: '*',
            requestStage: "Request"
        },
        {
            urlPattern: '*',
            requestStage: "Response"
        }
    ],
});


client.on('Fetch.requestPaused', async (requestObj: any) => {
    if (requestObj.responseStatusCode) {
        try {
            let bodyObj = await client.send('Fetch.getResponseBody', {
                requestId: requestObj.requestId
            });
            let body = bodyObj.body;

            if (bodyObj.base64Encoded) {
                body = Buffer.from(body, 'base64').toString('ascii');
            }
            if (body.includes("eyJ2ZXJzaW9uIjogMywic291")) {
                await client.send('Fetch.failRequest', {
                    requestId: requestObj.requestId,
                    errorReason: 'Aborted'
                });
                return;
            }
        } catch (e) {
            console.error(e);
        }
    }

    await client.send('Fetch.continueRequest', {
        requestId: requestObj.requestId
    });
});
```

Upon changing the code, don't forget to run `npm build` so that the changes are taken into account.

Logs can be displayed by adding the --debug option (possible values seem to be 'debug' or 'verbose').

Cookie banners refer to those little popups that ask whether you accept or no the cookies being set by the website (for GRPD compliance - if you're outside Europe, you're probably less likely to meet those as often). You don't have to deal with them if you don't want to (that's a not so easy task to automate): what I was stating in my previous response is that PageGraph might crash upon interacting with said cookie banners as the script is being introduced right after. That's not the case on Youtube as the problematic script is introduced right at the start of the loading. In both cases, the previous code snippet should take care of blocking the script for now.

I still haven't figured what this script does and why it seems to crash PageGraph though. 

@pes10k: Have you ever faced these crashes during your usage of PageGraph ? Maybe this would be interesting to investigate since I'm seeing that the script in question is present on a good bunch of websites. It's especially impacting PageGraph when shields are down but not only.

**Comment by syx1031** [comment]
Thanks for providing useful method for us! @naifmeh 

I have experimented these days and tried to find out what happened when visiting www.youtube.com, and I'm describing how to solve this problem below as clearly as I can for beginners like me.

situation: a page has been navigated, and crashed when "waiting for 30s"

method:

- modify pupeteer.ts like this:
![image](https://user-images.githubusercontent.com/71998982/211299628-7fdeae83-67e1-4674-b761-2e7b7d2c7d33.png)
namely adding "--v=1" then chromium will write informatic logs in file "$(your user directory of brave)/chrome_debug.txt"
- read chrome_debug.txt, and find out which script/url is requested lastly.
![image](https://user-images.githubusercontent.com/71998982/211300643-f7dc53a8-c3d3-44da-97dc-bb659cf83155.png)
then PageGraph may crash when loading this script(sometimes not, so you should pay attention to several request just just before the last request).
- modify crawl.ts like this:
```javascript
      await client.send('Fetch.enable', {
        patterns: [
          {
            urlPattern: '*',
            requestStage: "Request"
          },
        ],
      });


      client.on('Fetch.requestPaused', (requestObj: any) => {
        console.log(requestObj.request.url)
        if([
            "https://www.google.com/js/th/_mW_2QmsfiHfHQzuwJJjeV3lvrJQS7bChqYqZLie29Q.js",
            "https://www.google.com/js/th/G-wi0KRrIjmTWIDOn44AFVMvZ_aKLO1c96DfwAE3d4M.js",
            "https://www.google.com/js/th/YkfklCtf3s5-_1quWHAnTHHVaBZ-i7ToAeXFpu3i2Ro.js",
            "https://www.google.com/js/th/98eZ1SvQKncrIy_uxRv1pSvbmSGZ50EV24E3eut_s2o.js",
            "https://www.google.com/js/th/ayf-ZXn06Q-bf2kvL7HvZn-6GmgIdMcaNWCzb_-s5mI.js",
            "https://googleads.g.doubleclick.net/pagead/id?slf_rd=1",
        ].indexOf(requestObj.request.url) != -1 ||
        requestObj.request.url.match(/https:\/\/jnn-pa.googleapis.com\//)) {
          console.log(requestObj.request.url + ' is bad script, dropped!')
          return;
        }
        client.send('Fetch.continueRequest', {requestId: requestObj.requestId});
      });
```
after
```javascript
      const page = await browser.newPage()
      const client = await page.target().createCDPSession()
```
Specific to "www.youtube.com"，you can refer to urls above. Although naifmeh said script's url may change with time, and urls above seems to be generated randomly, I found these urls didn't change in several days, and "YkfklCtf3s5-_1quWHAnTHHVaBZ-i7ToAeXFpu3i2Ro.js"(in naifmeh's script) also appears in my experiment, so I confirmed that these urls will not change frequently.
- Now let's think about intercepting request by script's fixed line, neifmeh's script detects request with Fetch.responseStatusCode, but I can't get any request with this field. Searching on https://chromedevtools.github.io/devtools-protocol , you will find this field's appearance stands for having gotten response for this request, and only then you can use getResponseBody method. I'm now working on figuring out why I can't get any request with response.
- What's more, I compared all scripts with url prefix "https://www.google.com/js/th/", and I found the same content been annotated at the first line. naifmeh's script also use the same feature, so I'm sure that filtering script by this line, PageGraph will work.
![image](https://user-images.githubusercontent.com/71998982/211312937-8e36b399-0582-4e07-8701-ead37d606bd3.png)
![image](https://user-images.githubusercontent.com/71998982/211313643-2b3774e4-3308-468e-8fa3-f04a549fffdb.png)

**Comment by naifmeh** [comment]
@syx1031 : Have you added the "Response" pattern on Fetch.enable ? It might be the reason you're not receiving any response.

```
await client.send('Fetch.enable', {
    patterns: [
        {
            urlPattern: '*',
            requestStage: "Request"
        }, {
            urlPattern: '*',
            requestStage: "Response"
        }
    ],
});
```

**Comment by syx1031** [comment]
yeah, I add this pattern and then it really works, nice!

**Comment by goodov** [comment]
thanks for detailed reports guys! I think I was able to resolve all issues that are currently present. The PR is opened, so pls wait for it to merge.
https://github.com/brave/brave-core/pull/17104

There're currently some critical issues in `nightly` that fully break PageGraph. Please don't use latest `nightly`. It happened after recent migration from `std::` types to blink-specific types (like `WTF::String`, `WTF::HashMap`).

**Comment by naifmeh** [comment]
@goodov: Thank you for taking the time to fix this !

**Comment by goodov** [comment]
Latest `nightly` includes all fixes. Please give it a try.

**Comment by naifmeh** [comment]
Tested on `nighly` 1.50.26 with the (previously) problematic websites: all working as expected and no failure so far.

The script that induced the crashes is present but doesn't cause issues with PageGraph anymore. 
Thanks for the great work !
