### ISSUE TITLE
Brave leaks WebRTC IP

### ISSUE THREAD

**Issue by xKushGene** [brave/brave-browser#2755]
## Steps to Reproduce

   1. Set up VPN (PrivateInternetAccess)
   2. Checking ipleak test websites: 
     - https://browserleaks.com/webrtc
     - https://ipleak.net/

## Actual result:
Local IP / Public IP (VPN IP) / IPv6 (my real ip [I dont have a IPv4 IP without VPN]) is shown.

## Expected result:
No IPs should be shown.

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.58.17 Chromium: 71.0.3578.98 (Offizieller Build) (64-Bit)
Windows 10

**Comment by NumDeP** [comment]
/Firstly did you enable 'Disable non-proxied UDP' under WebRTC IP Handling Policy?

Secondly, how do you know your OS isn't responsible for the issue?

Third, did you test whtether it leaks under New Private Window with Tor?

**Comment by xKushGene** [comment]
> Firstly did you enable 'Disable non-proxied UDP' under WebRTC IP Handling Policy?

No, now It works. Should be default option because no one with basic "i use VPN and i am save" knowledge will come to this point I guess.
Thanks for that.

**Comment by NumDeP** [comment]
@xKushGene can you check https://hidester.com/webrtc-ip-leak-test/ because I just doubled checked and I noticed the same issue where as before I'm certain it was blocked. 

WebRTC Support Detection
--
RTCPeerConnection | ✔True
RTCDataChannel | ✔True
ORTC (Microsoft Edge) | ×False (on hidester.com/webrtc-ip-leak-test/ it shows Yes)
IP Address Detection
Local IP Address | n/a
Public IP Address | n/a
IPv6 Address | n/a
WebRTC Media Devices
Device Enumeration | ✔True
Has Microphone | ×False
Has Camera | ×False

**Comment by srirambv** [comment]
Support detection showing _True_ doesn't mean its leaking. Its just a way to ensure WebRTC is supported or not. As long as your IP isn't shown on the test result, its working as expected(blocking WebRTC requests)

cc: @jumde @tomlowenthal

**Comment by NumDeP** [comment]
Yeah I was under that assumption, though I didn't have proof to provide to the above user and the reason as to why ORTC (Microsoft Edge) displays as False on one site and True on another. He seems to have a handle of it now so to speak.

One other thing, wasn't there just one more thing to do regarding WebRTC which led to Brenden mentioning it in Github from a Reddit conversation?

**Comment by tomlowenthal** [comment]
Doesn't actually seem to be anything here we need to fix.
