### ISSUE TITLE
Page load degradation on v1.48.80

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#27590]
The dashboard shows a significant degradation in page load timing.
For slow PC first paint  & load time have increased 2 times on all test sites.

The bisecting has shown that the issue comes with v1.48.80.
The difference with https://github.com/brave/brave-core/compare/v1.48.79...v1.48.80

<img width="517" alt="image" src="https://user-images.githubusercontent.com/45488748/210104479-39891765-7aaf-41f9-8299-25c0015523c3.png">

High power PC compare of the near revisions:
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/45488748/210104505-b446020a-36a6-4072-a990-c920d6899340.png">

**Comment by steveluscher** [comment]
Copying thoughts from another chat…

This looks pretty much like 100% parse, JIT, and module factory work (require, require, require, require…).
Without having actually looked at [the code](https://github.com/brave/brave-core/pull/16412/files#diff-379773afbd518d0a41b29aa69376d1aa22fdc7c342d8feac103ea3a16d4afb1d), I wonder if:

1. we could strategically inline some requires so that they only run when actually hit, or
2. Brave could just delay injecting the provider until the first time the thread is idle

The real meat of this problem is that `@solana/web3.js` – upon which you depend – is not tree-shakeable; you need only `Transaction` and `VersionedTransaction` from there, but you get the whole thing.

Do you think there's some merit to a really quick and dirty fix like this (pseudocode):

```ts
function signAndSendTransaction(...) {
  require('@solana/web3.js').Transaction.from(...);
}
```
Instead of this:
```ts
import { Transaction } from '@solana/web3.js';
function signAndSendTransaction(...) {
  Transaction.from(...);
}
```
That might let you defer the expensive JIT of the web3.js library until the moment someone actually invokes a signing method. Could maybe achieve this with a Webpack plugin like https://www.npmjs.com/package/inline-require-webpack-plugin
