### ISSUE TITLE
`Scroll for Brave News` is NOT shown in NTP for users in OFAC list countries

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#27630]
## Description 

`Scroll for Brave News` is NOT shown in NTP for users in OFAC list countries

## Steps to Reproduce

   1. Follow the steps 1 to 10 from Test case 1 in https://docs.google.com/document/d/1zlWGAhk0X5nFM5vwwZ21LpDfgPX-6m0-oGcCilsGtXk/edit#
   2. `Scroll for Brave News` is NOT shown in NTP for users in OFAC list countries
   
**Note:** User can enable Brave news via `Customize` in NTP
## Actual result:

`Scroll for Brave News` is NOT shown in NTP for users in OFAC list countries

## Expected result:

`Scroll for Brave News` should be shown in NTP for users in OFAC list countries
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave	1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit) 
Revision	846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS	Windows 10 Version 21H2 (Build 19044.1826)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc : @brave/qa-team @mkarolin @Miyayes

**Comment by rebron** [comment]
The expected behavior is that the Brave News opt-in card and/or the Scroll for Brave News button on the NTP only shows by default for supported regions/languages:
device system lang=English
- Japan
- Mexico
- Spain
- Brazil

Else, the opt-in card and/or Scroll for Brave News does NOT appear by default.
also, all users, regardless of lang/region, can turn on Brave News from the Customize modal on NTP. if Brave News has been enabled then the Scroll for Brave News button should always appear on NTP.

We can mark this as invalid.
