### ISSUE TITLE
CVE-2018-20483 aka user.xdg.origin.url

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#2766]
## Description 
Carried over from https://github.com/brave/browser-laptop/issues/15344

Downloaded files are saving URLs from which are downloaded into «user.xdg.origin.url» or «user.xdg.referrer.url»

## Steps to Reproduce

  1. Download file
  2. Read with getfattr
  3. Check if file contain location from which was downloaded

## Brave version (brave://version info)

Version 0.58.17 Chromium: 71.0.3578.98 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by raisty** [comment]
I want add to discussion - this is very important especially for TOR in Brave browser.

**Comment by diracdeltas** [comment]
Has anyone verified this issue repros in the new version of Brave?

**Comment by fmarier** [comment]
It looks pretty easy to patch out.

The extended attributes are [defined here](https://cs.chromium.org/chromium/src/components/download/quarantine/common_linux.cc?l=9&rcl=788a8bf8cabb0fcfb83da1970f4331f2b616e7ed) and then [set in this function](https://cs.chromium.org/chromium/src/components/download/quarantine/quarantine_linux.cc?l=21-38&rcl=788a8bf8cabb0fcfb83da1970f4331f2b616e7ed).

**Comment by fmarier** [comment]
The URL and referrer are [explicitly omitted when the user is in an off-the-record window](https://cs.chromium.org/chromium/src/components/download/internal/common/download_item_impl.cc?l=1683-1684&rcl=a9732ef3287c87789832e6ba5cd74c4193750551).

This is apparently from a Windows feature called the [Mark of the Web](https://textslashplain.com/2016/04/04/downloads-and-the-mark-of-the-web/) which allows some software (e.g. MS Office, Windows Explorer) to treat these files are less trustworthy and display extra warnings or apply extra restrictions when they are opened.

**Comment by fmarier** [comment]
@diracdeltas suggested looking into spoofing the value of the URL to see if we can get the benefits of the Mark of the Web without having the exact URL in there.

We could try setting the URL to `http://example.com` and then remove the referrer.

**Comment by fmarier** [comment]
I discussed this bug with someone who works on Windows Defender and he told me that the Mark of the Web is very important since A/V products will treat files from the Web as suspicious and do extra checks on them.

Having the real URL and referrer means that these products can do additional reputation checks against the URLs that are included, however, they will still scan the files if the original URL has been scrubbed and replaced with a bogus one.

What I therefore propose is to:
- remove the referrer URL
- replace the URL with a hard-coded one

In addition, since we would no longer be leaking the original URL, we could also mark files that are downloaded in Private Browsing, which would be a security win.

**Comment by fmarier** [comment]
I did some more testing on **Firefox for Windows** and found that they add the alternate NTFS data stream with the same content in normal and private modes (and in Tor Browser Bundle):

```
[ZoneTransfer]
ZoneId=3
```

Therefore they never leak the URLs at all.

In contrast, **Brave/Chromium on Windows** will put the following in the NTFS data stream in normal windows:

```
[ZoneTransfer]
ZoneId=3
ReferrerUrl=https://files.pythonhosted.org/
HostUrl=https://files.pythonhosted.org/packages/d9/0a/d3d1290794660b7e49efe1339a3dc57e3c9b82ac7641595a485691f51ee2/canadian-ham-exam-0.2.0.tar.gz
 ```

and the following in Private and Tor windows:

```
[ZoneTransfer]
ZoneId=3
HostUrl=about:internet
```

**Comment by fmarier** [comment]
It turns out that this metadata has been [removed from Linux builds](https://chromium.googlesource.com/chromium/src/+/a9b4fb70b4318b220deee0da7b1693d16b8ed071) in [Chromium 74.0.3691.0](https://storage.googleapis.com/chromium-find-releases-static/a9b.html#a9b4fb70b4318b220deee0da7b1693d16b8ed071). Therefore the only platforms that need to be fixed (in normal mode) are Windows and macOS.

**Comment by fmarier** [comment]
I tested the fix for this on Windows, Mac and Linux using Nightly 0.65.16 and following the test plan in https://github.com/brave/brave-core/pull/2100#issue-265129370.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.95 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan for macOS from https://github.com/brave/brave-core/pull/2100#issue-265129370
![Screen Shot 2019-05-17 at 11 55 03 AM](https://user-images.githubusercontent.com/28145373/57940591-c6603000-789a-11e9-8aa1-5ae3340d8f80.png)
