### ISSUE TITLE
Import extensions to target profiles during multiple import 

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#27733]
## Description 

**Important**: This issue should be solved after https://github.com/brave/brave-browser/issues/27591

In issue https://github.com/brave/brave-browser/issues/27591 we changed how the import works. If a user imports multiple profiles we will create new profiles (if no existing with same name) and import data from source browser to that profiles.
This issue us to add support of importing extensions to target profle instead of default.

## Steps to Reproduce

   1. Create multiple profiles in Chrome with extensions.
   2. Use multiple import to import data from that profiles
   3. Check if extenions have been imported to target profiles.

## Actual result:

Extensions imported only for default profile.

## Expected result:

Extensions imported to target profile.

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by spylogsster** [comment]
cc @bsclifton @rebron

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.49.97 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

Import extensions from MS Edge mutliple profiles via onboarding process 
<details>

Pre requisites: 


Download  MS Edge browser and install extensions for Profile 2 & Profile 3
Profile 2: 

- Install ChatGPT for Google extension from Chrome Web Store
- Install  PayPal Honey and Awesome and Screenrecorder from Microsoft Edge Add-ons store

Profile 3: 

- Install MetaMask via Chrome Web Store
- Install LastPass and Alto JPG to PDF converter

Profile 2 | Profile 3
-----|-----
<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/218859218-5de407d2-f325-4c1f-83a3-ebbe52c41d69.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/218859241-e1c77059-d754-411e-bb27-2da998540676.png">
</details> 

1.  Install 1.49.89
2.  launch Brave
3.  click `Set Brave as default browser
4.  select Edge
5.  click import
6.  select Microsoft Edge Profile 2 & Profile 3
7.  click Import Profiles
8.  click Finish

step 3 | step 4 | step 6 | step 8 | new-tab | Profile 2 | Profile 3
----- | ----- | ------ | ------ | ------- | ------- | ------
<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/218854778-a00533d2-fa3a-471d-b8b5-3497873955f3.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/218854825-97b85017-b083-447c-82a1-b259dc900713.png">|<img width="467" alt="image" src="https://user-images.githubusercontent.com/98358127/218854864-cd35049d-3479-4cfe-91aa-17c00876a099.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/218854929-ba84f00e-1eec-457e-97c3-db2ef1643423.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/218855004-f0d2adcd-b59a-45e5-9c0e-b9adb2bc8562.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/218855068-b713b73a-6c73-4c99-809c-1b3e7482dce1.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/218855123-784ad9fc-71e1-4047-8f86-3c3997354590.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.49.100 Chromium: 110.0.5481.100 (Official Build) beta (x86_64)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | macOS Version 11.7.4 (Build 20G1120)

`Profile 1` | `Profile 2` | `Profile 3`
-----------|-----------|-----------
<img width="1738" alt="Screen Shot 2023-02-17 at 10 30 52 PM" src="https://user-images.githubusercontent.com/387249/219845217-51a5e638-97f5-4edf-a024-173bafb0bd3b.png"> | <img width="1738" alt="Screen Shot 2023-02-17 at 10 31 05 PM" src="https://user-images.githubusercontent.com/387249/219845221-0976631d-4f7d-457d-bbc7-18da32549dac.png"> | <img width="1738" alt="Screen Shot 2023-02-17 at 10 31 23 PM" src="https://user-images.githubusercontent.com/387249/219845223-caee56ee-2421-4e17-a0df-e4741482c357.png">

### Steps:
install 1.49.100
launch Brave
click `Set Brave as default browser`
select `Google Chrome`
click `Import`
select all profiles
click `Import Profiles`
click `Finish`

Confirmed extensions added to Edge via Chrome Web Store are imported into Brave successfully

step 3 | step 4 | step 6 | step 8
-------|--------|-------|-------

new tab page | profile 2 | profile 3
--------------|---------|----------

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.49.116 Chromium: 110.0.5481.177 (Official Build) beta (64-bit) 
Revision	f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS	Linux
```
Chrome with multiples profiles and installed extensions 
<details> 

Profile 1 & 2: Extensions installed
Profile 3: No extensions installed

Person 1 | Person 2 | Person 3
------ | ------ |--------
<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222272425-b2d58556-a075-4da2-bef6-4f6e08ac2223.png">|<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222272455-18739955-5f87-4059-981b-477e334cf818.png">|<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222272678-614d1b08-3958-4fe8-b9c7-1e71cf588627.png">
</details> 

1.  Install 1.49.116
2.  launch Brave
3.  click `Set Brave as default browser
4.  select Chrome
5.  click import
6.  select Chrome Person 1, Person 2, & Person 3
7.  click Import Profiles
8.  click Finish

#### Confirmed extensions added to Chrome  via Chrome Web Store are imported into Brave successfully. 
Note:  Default Google Docs Offline extension is not imported as it's expected behavior
Note: Person 3 have no data/extensions but still is shown in the Brave profile manager

step 3 | step 4-5 | step 6 -7 | step 8
-------- | ----- | ------- | ----------
<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222273451-21726a81-f812-47eb-8223-af442a26eae3.png">|<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222273470-6da78a8a-3228-4a4a-9d88-2c37d8a23d8c.png">|<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222273546-f3d2db24-f11e-4308-bd34-56388c7f67d8.png">|<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222273775-37f948b8-858a-4f06-b142-f0cb96f43d73.png">

new tab page | Person 1 | Person 2 | Person 3
---- | ------ | ----- | -----
<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222274158-9b909169-1cea-42ea-acd6-349ef8b540c7.png">|<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222274169-0e8a5961-dbc6-44c4-9c6e-7209b9a37dc1.png">|<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222274176-d2d0938a-1fc1-4be1-9507-54aae17576e5.png">|<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222274182-8c282db8-00f7-4296-a676-3c018b93f389.png">|
