### ISSUE TITLE
Make Android test enviorment can run browser tests with mojom bound to frames.

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#27837]
```
[ERROR:render_process_host_impl.cc(5236)] Terminating render process for bad Mojo message: Received bad user message: No binder found for interface cosmetic_filters.mojom.CosmeticFiltersResources for the frame/document scope
I  326.832s run_tests_on_device(192.168.0.13:5555)  [ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 123
```

content::SetBrowserClientForTesting() didn't work for Android. We might have to override [TestContentBrowserClient.](https://source.chromium.org/chromium/chromium/src/+/main:content/test/test_content_browser_client.h?q=TestContentBrowserClient&ss=chromium)

**Comment by arthuredelstein** [comment]
Here's an approach I took to fix this problem for one test: https://github.com/brave/brave-core/commit/67293ebf7ed6d9a405a746f18c753b2b4e943a48. The key was to use `BraveContentBrowserClient` because it registers a binder for `CosmeticFiltersResources`. Perhaps this approach can inspire a general solution?

**Comment by sangwoo108** [comment]
Hum, I thought It hadn't worked at the time. Let me check out again.

**Comment by bridiver** [comment]
@arthuredelstein @sangwoo108 yes, the problem is that cosmetic filters applies to every frame so no matter what you navigate to, it will try to register the browser interface and fail. Setting the test content browser client to `BraveContentBrowserClient` is the fix, but what we may want to do is create `BravePlatformBrowserTest` that is `BraveAndroidBrowserTest` on android and `BraveInProcessBrowserTest` on desktop and automatically sets the content browser client to `BraveContentBrowserClient`

**Comment by bridiver** [comment]
https://github.com/brave/brave-core/pull/20825/files#diff-12d073f3a7b2147b2fcffec0a1531beec283db0aa6236495f8397d5f68743664

**Comment by bridiver** [comment]
just looking at some of the upstream browser tests that are now failing to make sure they all should be failing or move them to a follow-up
