### ISSUE TITLE
[iOS] - Allow AdblockService to use legacy component updater

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#27841]
## Description 
- Export a callback and a parameter to allow adblock services to use legacy component for dat files.
   
## Brave version
1.49.x

**Comment by kjozwiak** [comment]
@Brandon-T going to remove this from the `1.49.x` milestone as https://github.com/brave/brave-core/pull/16693 is still opened and hasn't been merged into `master`. Once that PR has been merged, we can move the associated issue into that milestone. So for example, if it lands in `1.51.x` which is the current `master`, we'll move this into `1.51.x` and change the milestone if the issue is uplifted.
