### ISSUE TITLE
Stub installer to first run conversion

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2784]
## Description

We currently have stub installer download vs first run mismatch.  This issue is to investigate how to improve that with a ping for stub installer successfully run, base installer downloaded, and installer run.

## Test Plan

Tests require running a packet sniffer like Fiddler or coordinating with @aekeus to view server logs. You can set the `BRAVE_UPDATE_SERVER` to point to the staging server for testing purposes.

### Testing with No Referral Code

- Download a stub installer with no referral code
- Run the installer to completion
- Verify that we successfully sent a `startup`, `download-complete`, and `installer-run` ping to the update server
- Verify that all 3 pings include `ref=none`

### Testing with Unwhitelisted Referral Code

- Download a stub installer with a referral code not appearing on our referral code whitelist
- Run the installer to completion
- Verify that we successfully sent a `startup`, `download-complete`, and `installer-run` ping to the update server
- Verify that all 3 pings include `ref=none`

### Testing with Unwhitelisted Referral Code

- Download a stub installer with a referral code appearing on our referral code whitelist
- Run the installer to completion
- Verify that we successfully sent a `startup`, `download-complete`, and `installer-run` ping to the update server
- Verify that all 3 pings include `ref=XXXYYY`, where `XXXYYY` is a whitelisted referral code

CC @aekeus

**Comment by emerick** [comment]
@mbacchi Still working on finalizing this change, but wanted to give you a heads up that this is planned for Hotfix 2 and will require a new build of Omaha when it lands.

**Comment by btlechowski** [comment]
Big thanks to @emerick for helping out with the setup!

### Fiddler Setup 
In Fiddler go `Tools` -> `Options` -> `HTTPS`
Check `Decrypt HTTPS traffic` and install all the certificates.

### Configuring WinHTTP’s Proxy
#### On Windows 8/10 x86 x64, Stub Installer 32 and 64 bit:
In cmd.exe with administrative privileges, run
```
cd C:\Windows\system32
netsh winhttp set proxy 127.0.0.1:8888 "<-loopback>"
```

#### On Windows 7 x64, Stub Installer 64 bit; On Windows 7 x86, Stub Installer 32 bit:
In cmd.exe with administrative privileges, run
```
cd C:\Windows\system32
netsh winhttp set proxy 127.0.0.1:8888 "<-loopback>"
```

#### On Windows 7 x64, Stub Installer 32 bit:
In cmd.exe with administrative privileges, run
```
cd c:\Windows\SysWOW64
netsh winhttp set proxy 127.0.0.1:8888 "<-loopback>"
```

Important: The server code is not on production yet, it will be 11-01-2019. So all the pings will have 404.
Use env var: `BRAVE_UPDATE_SERVER=laptop-updates-pre.brave.com` to change server to preproduction

This is how it should look when everything is fine:
![fiddler_stub](https://user-images.githubusercontent.com/34715963/51003380-c8099800-1536-11e9-9b45-6755b6181078.png)


Notes:
- There are two types of stub installers(silent: `BraveBrowserSilentSetup` and normal `BraveBrowserSetup`). When it comes to pings, both should behave the same according to @emerick 
- Currently the stub installer downloads 0.58.18 version of brave, but this doesn't matter because all the pings are done by stub installer and helper process(braveupdate.exe). Info verified by @emerick .

**Comment by btlechowski** [comment]
Verification Passed for BraveBrowserSilentSetup.exe v0.58.20 on Windows 7 x64.
No referral code:
![image](https://user-images.githubusercontent.com/34715963/51004702-1705fc00-153c-11e9-93f0-a25978c78b47.png)

Unwhitelisted Referral Code (used BAR421):
![image](https://user-images.githubusercontent.com/34715963/51005113-d0b19c80-153d-11e9-8617-0cb8b78519dd.png)

Whitelisted Referral Code (used ZTT758)
![image](https://user-images.githubusercontent.com/34715963/51005377-d5c31b80-153e-11e9-9d42-85b4bee849dc.png)

**Comment by btlechowski** [comment]
Verification Passed for BraveBrowserSilentSetup.exe v0.58.20 on Windows 10 x64.

No referral code - clean install:
![stub_silent_noref](https://user-images.githubusercontent.com/34715963/51048657-e1105880-15cb-11e9-8f80-3d6c31b9b127.png)

Unwhitelisted Referral Code (used BLE342) - clean install:
![stub_silent_ble342_ref](https://user-images.githubusercontent.com/34715963/51048687-f08fa180-15cb-11e9-8306-de6b9f0d0b46.png)

Whitelisted Referral Code (used MTS962) - clean install
![stub_silent_mts962_ref](https://user-images.githubusercontent.com/34715963/51048698-f8e7dc80-15cb-11e9-91d2-9445e66187b8.png)

**Comment by kjozwiak** [comment]
Thanks for gathering all the info and going through this issue @btlechowski 👍
