### ISSUE TITLE
Implement vBAT notices and sunset

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27882]
## Description

Implement vBAT notices and sunsetting related to https://brave.com/rewards-changes.

**Comment by LaurenWags** [comment]
@brave/qa-team we should verify this one on all platforms, run full checks on Windows and macOS with reduced testing (TBD) on Linux.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.92 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.49.97 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit) 
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Ubuntu 18.04 LTS


<details>
<summary>Case 3: vbatDeadline is in the future (custodian available → connected → reset into non-connected) - PASSED</summary>

3.1. In older version of Brave, create a Rewards profile in staging (ideally select a country with a supported custodian and that you have a matching account for, such as US but do not connect to custodian)

1.47.x rewards settings | 1.47.x BR panel | 1.47.x NTP widget
--------------------------|------------------|--------------------
![image](https://user-images.githubusercontent.com/34715963/224084471-25ceff20-8a71-4afe-8fbd-89e62a4af8fe.png)|![image](https://user-images.githubusercontent.com/34715963/224084604-0472820e-e2d3-490d-8bba-356780a589ef.png)|![image](https://user-images.githubusercontent.com/34715963/224084701-ea33f538-85c2-455b-9326-78257a6c323d.png)


3.2. Update parameters endpoint (or set up a proxy) so that vbatDeadline is in the future. Note that vbatDeadline is a UTC date.
3.3. Update to 1.49.x. You should now be in the grandfathered-unverified state.
3.4. Make sure the right values are coming from /parameters.

```
[ RESPONSE - OnResponse ]
> Url: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.303048,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","GB","US"],"block":[]},"uphold":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","GB","US","IN"],"block":[]}},"payoutStatus":{"bitflyer":"complete","gemini":"complete","payoutDate":"","unverified":"complete","uphold":"complete"},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatDeadline":"2023-03-10T07:00:00Z","vbatExpired":false}
```

3.5. Go to NTP Rewards widget, brave://rewards, and Rewards dropdown panel and check for notices. They SHOULD appear 
(compare with Figma, row “Countdown to feature removal notification”). Make sure the “Connect account” and “Learn more” buttons work in all of them (open up relevant pages or modals, but do not connect to custodian yet).

 - Confirmed that the content of  “Countdown to feature removal notification” message is as per the Figma spec
 - Confirmed that click on “Learn more” (verified all the 3 places) redirects to `https://brave.com/rewards-changes/`
 - Confirmed that click on “Connect account” opens up the connect account modal popup

brave://rewards | NTP Rewards widget | Rewards panel
------------------|-------------------------|-------------
![image](https://user-images.githubusercontent.com/34715963/224089719-52c91818-afdf-4f94-944d-87f3c7573ae2.png)|![image](https://user-images.githubusercontent.com/34715963/224089766-77134e8b-4b87-4217-8436-b9083bde6ccc.png)|![image](https://user-images.githubusercontent.com/34715963/224089816-f323fe88-7e77-46b6-83dc-d61095bc69f3.png)


3.6. Inside each of the notices, make sure the date and time correspond with what’s at the /parameters endpoint. The parameters endpoint is in UTC, and the value shown in notices should be translated into your local device time.

 - The date and time at the /parameters endpoint is in UTC `"2023-03-10T07:00:00Z"`
 - Ensured that the time is translated into local device time (CET) `10 marca 2023 8:00` (CET = UTC+1)

 
3.7. In the NTP Rewards widget, close the vBAT expiry notice. Then, refresh the NTP and it should appear again.

Close vBAT expiry notice in NTP | Refresh NTP
---------------------------|-------------
![image](https://user-images.githubusercontent.com/34715963/224090047-b0f1a7d4-b472-41c0-83bf-480be13af630.png)|![image](https://user-images.githubusercontent.com/34715963/224090114-b92fcf22-fed1-4771-a62c-771139b56e5c.png)


3.8. In the Rewards dropdown panel, close the vBAT expiry notice. Then, close and open the dropdown panel again. It should reappear again.

Close vBAT expiry notice in BR panel | Refresh BR panel
---------------------------|-------------
![image](https://user-images.githubusercontent.com/34715963/224090548-d7512c76-7142-4955-bd43-c2b1186e4114.png)|![image](https://user-images.githubusercontent.com/34715963/224090614-4e356eb4-60e3-46ac-98ad-d1e98dbc63b1.png)


3.9. Connect a custodian.
3.10. Once connected, look around for vBAT expiry notices on NTP, brave://rewards, and Rewards dropdown panel. Now that you’re in the connected state, NO vBAT expiry notices should appear anywhere.

Example | Example | Example
----------|----------|----------
![image](https://user-images.githubusercontent.com/34715963/224091140-8c34488f-1a55-4a98-8f74-d15257e40435.png)|![image](https://user-images.githubusercontent.com/34715963/224091401-9344f8a9-6d9b-4ba6-99fd-523cc1511b8f.png)|![image](https://user-images.githubusercontent.com/34715963/224091472-80274cdf-0572-48c7-9f01-e9893510c032.png)


3.11. Reset Brave Rewards and enable Brave Rewards. You’re now in the non-connected state. Check NTP, brave://rewards and Rewards dropdown panel. NO vBAT expiry notices should appear anywhere.


</details>
