### ISSUE TITLE
[Android] Implement vBAT notices and sunset

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27883]
## Description

Implement vBAT notices and sunsetting related to https://brave.com/rewards-changes.

**Comment by kjozwiak** [comment]
We'll try getting this verified/checked on an older device like `Android 8` via the emulators, however, most of the time the emulators are `x86` which doesn't work on rewards due to use disabling rewards on `x86`. If we can't manage to get a `x64` emulator running on an older device, we'll at least ensure that it's working fine on `mobile` & `tablet`.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy version 12` running `Bravemonoarm64.aok_1.49.108`

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.49.118`

Verified the scenarios from https://docs.google.com/document/d/1YVa6Wx4kMd90Q7mfx29iW--xa4tPNl7YXc486CkYQAI/edit#heading=h.t2vdk6dnw3tr

**Note**: Reset rewards cases are NOT verified, thread about the discussion https://bravesoftware.slack.com/archives/CNH9Q6REV/p1675080664239119?thread_ts=1675061489.249839&cid=CNH9Q6REV 

 (Logged https://github.com/brave/brave-browser/issues/28817)
Encountered https://github.com/brave/brave-browser/issues/28816

<details>
<summary>Case 3: vbatDeadline is in the future (custodian available → connected → reset into non-connected)_FAILED_encountered #28816</summary>

3.1. In older version of Brave, create a Rewards profile in staging (ideally select a country with a supported custodian and that you have a matching account for, such as UK)

1.47.x rewards settings 
![Screenshot_20230307-222113_Brave](https://user-images.githubusercontent.com/38657976/223496970-e0fc24e0-a1de-42c3-9f51-5f9644148317.jpg)

3.2. Update parameters endpoint (or set up a proxy) so that vbatDeadline is in the future. Note that vbatDeadline is a UTC date.
3.3. Update to 1.49.x. You should now be in the grandfathered-unverified state.
3.4. Make sure the right values are coming from /parameters.

```
   [ REQUEST ]
    > URL: https://api.rewards.bravesoftware.com/v1/parameters
    > Method: GET
2023-03-07 22:20:52.358 25033-25033/? V/chromium: [VERBOSE1:recovery.cc(22)] Running empty balance check...
....
    [ RESPONSE - OnResponse ]
    > Url: https://api.rewards.bravesoftware.com/v1/parameters
    > Result: Success
    > HTTP Code: 200
    > Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.262301,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","US","GB"],"block":[]},"uphold":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","US","GB","IN"],"block":[]}},"payoutStatus":{"bitflyer":"complete","gemini":"complete","payoutDate":"","unverified":"processing","uphold":"complete"},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatDeadline":"2023-03-25T04:00:00Z","vbatExpired":false}
2023-03-07 22:22:51.661 25990-25990/? V/chromium: [VERBOSE1:api_parameters.cc(90)] Params timer set for 11553 s

```
3.5. Go to NTP Rewards widget, brave://rewards, and Rewards dropdown panel and check for notices. They SHOULD appear 
(compare with Figma, row “Countdown to feature removal notification”). Make sure the “Connect account” and “Learn more” buttons work in all of them (open up relevant pages or modals, but do not connect to custodian yet).

 - Confirmed that the content of  “Countdown to feature removal notification” message is as per the Figma spec
 - Confirmed that click on “Learn more” (verified all the 2 places) redirects to `https://brave.com/rewards-changes/`
 - Confirmed that click on “Connect account” in rewards settings page opens up the connect account modal popup
 - Click on “Connect account” via BR panel doesn't open the connect account modal popup, encountered https://github.com/brave/brave-browser/issues/28816

brave://rewards | Rewards panel
------------------|------------------------
![Screenshot_20230307-224558_Brave](https://user-images.githubusercontent.com/38657976/223498699-1ad3cd5a-0479-453c-8804-5981c619e755.jpg) | ![Screenshot_20230307-222841_Brave](https://user-images.githubusercontent.com/38657976/223498741-86f32b7c-4f22-45f2-be2f-34429d932f38.jpg)


3.6. Inside each of the notices, make sure the date and time correspond with what’s at the /parameters endpoint. The parameters endpoint is in UTC, and the value shown in notices should be translated into your local device time.

 - The date and time at the /parameters endpoint is in UTC `"2023-03-25T04:00:00Z"`
 - Ensured that the time is translated into local device time (IST) `March 25, 2023 at 9:30  AM` (IST = UTC + 5.30)
 
3.7. In the NTP Rewards widget, close the vBAT expiry notice. Then, refresh the NTP and it should appear again. (NA)
3.8. In the Rewards dropdown panel, close the vBAT expiry notice. Then, close and open the dropdown panel again. It should reappear again.

Close vBAT expiry notice in BR panel | Refresh BR panel
---------------------------|-------------
![Screenshot_20230307-223036_Brave](https://user-images.githubusercontent.com/38657976/223498899-ce7ccc18-4905-4e25-9826-8d7d9b0cc1a1.jpg) | ![Screenshot_20230307-223100_Brave](https://user-images.githubusercontent.com/38657976/223498946-a6ef6947-c317-4f76-bee5-3553b0f664d2.jpg)


3.9. Connect a custodian.
3.10. Once connected, look around for vBAT expiry notices on NTP, brave://rewards, and Rewards dropdown panel. Now that you’re in the connected state, NO vBAT expiry notices should appear anywhere.

Example | Example 
----------|----------
![Screenshot_20230307-223443_Brave](https://user-images.githubusercontent.com/38657976/223499108-b1ed9864-ebf1-4163-a82f-01e8506ac88e.jpg) | ![Screenshot_20230307-223624_Brave](https://user-images.githubusercontent.com/38657976/223499153-b0620ec8-6b57-4799-b5b1-955f39c1e6a1.jpg)


3.11. Reset Brave Rewards and enable Brave Rewards. You’re now in the non-connected state. Check NTP, brave://rewards and Rewards dropdown panel. NO vBAT expiry notices should appear anywhere. (NA see comments)


</details>
