### ISSUE TITLE
News ads viewed P3A metric is being overcounted

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#27897]
## Description 

The `Brave.Today.WeeklyDisplayAdsViewedCount` metric is being overcounted.

## Steps to Reproduce

   1. Launch browser with fresh profile, access news.
   2. Scroll down, view at least one ad, and many regular cards

## Actual result:

Metric value is way higher than what was actually viewed.

## Expected result:

Metric value should be accurate.

## Reproduces how often: 

Easily

## Brave version:

1.49.x and earlier

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.49.89 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries I need a clarification on a scenario, please review and let me know your inputs.

1. Clean profile 1.49.x
2. Open a NTP and enabled Brave News
3. View a NTP Ad
4. Open brave://local-state file and ensured that the metrics `Brave.Today.WeeklyDisplayAdsViewedCount` response value is `1`
5. Close the browser
6. Set the sys time ahead by one hour
7. Relaunch the browser and view the same Ad in an already opened NTP
8. Reload brave://local-state file and ensured that the metrics `Brave.Today.WeeklyDisplayAdsViewedCount` response value is `2`
9. Close the browser
10. Set the sys time ahead by one hour
11. Relaunch the browser and view the same Ad in an already opened NTP
12. Reload brave://local-state file and ensured that the metrics `Brave.Today.WeeklyDisplayAdsViewedCount` response value is `2` instead of `3`

**Comment by btlechowski** [comment]
I was able to reproduce with 1.49.91 Chromium: 110.0.5481.77 (Official Build) beta (64-bit) 

On first view I get `2`. Subsequent views don't increase the counter. 
By views I mean the ad `view` event in the logs
```[9846:9846:0209/181439.153017:VERBOSE6:inline_content_ad_event_viewed.cc(28)] Successfully logged inline content ad viewed event```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk_1.49.100`
