### ISSUE TITLE
Remove more BravePrefServiceBridge functions in privacy settings

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#27909]
Remove the remaining usages of BravePrefServiceBridge in privacy settings.

**Comment by kjozwiak** [comment]
We'll check the above on a single device rather than labelling this as `QA/Test-All-Platforms`. We're going to get a lot of overlap when we run through the manual passes on various devices as we basically check all the sections outlined via https://github.com/brave/brave-core/pull/16752#issue-1549815893.
