### ISSUE TITLE
Tab switch order is random using keyboard shortcuts.

### ISSUE THREAD

**Issue by ecormaksin** [brave/brave-browser#27953]
## Description 

According to [this page], when we use Ctrl + Tab or Ctrl + PgDn, Jump to the next open tab,
and Ctrl + Shift + Tab or Ctrl + PgUp, Jump to the previous open tab.

However, target tab seems to random.

## Steps to Reproduce

   1. Open multiple tabs.
   2. Use Ctrl + Tab or Ctrl + PgDn / Ctrl + Shift + Tab or Ctrl + PgUp.

## Actual result:

Target tab order is random.

## Expected result:

As [keyboard shortcuts page](https://support.brave.com/hc/en-us/articles/360032272171-What-keyboard-shortcuts-can-I-use-in-Brave-) says, when we use Ctrl + Tab or Ctrl + PgDn, Jump to the next open tab,
and Ctrl + Shift + Tab or Ctrl + PgUp, Jump to the previous open tab.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

v1.47.171

## Version/Channel Information:

- Can you reproduce this issue with the current release? : yes.
- Can you reproduce this issue with the beta channel? : I don't know.
- Can you reproduce this issue with the nightly channel?  : I don't know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? : no.
- Does the issue resolve itself when disabling Brave Rewards?  : no.
- Is the issue reproducible on the latest version of Chrome?  : no.

## Miscellaneous Information:

Nothing.

**Comment by fallaciousreasoning** [comment]
In the `Appearance` settings (brave://settings/appearance) can you check if you have `Cycle through the most recently used tabs with Ctrl-Tab` turned on or off?

If you have it on, pressing `Ctrl+Tab` will take you to the last tab you had open, rather than the next tab in the tab strip

![image](https://user-images.githubusercontent.com/7678024/228106858-1df5ab1e-840e-40e1-b761-78c3912a2ec8.png)
