### ISSUE TITLE
Fallback to HTTP when an upgraded site sees 404 etc

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#28013]
As an improvement to https://github.com/brave/brave-browser/issues/27141, can we detect when a site that has been upgraded to HTTPS from HTTP shows a top-level error code such as `404`? In that case, we should fall back to HTTP again.

**Comment by pes10k** [comment]
cc @goodov @iefremov @bridiver we might need your help or guidance in how to do this in a chromium-friendly way

**Comment by goodov** [comment]
I think in most cases the connection will just fail. We can detect this by expecting an error page (in a throttle?), check if the `http->https` change was made by us and reverse it.

We can also add some info/button to the error page to return to `http` if a user wants this explicitly, i.e. not do this automatically.

**Comment by kjozwiak** [comment]
The above requires `1.51.107` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.107 Chromium: 113.0.5672.63 (Official Build) (x86_64)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | macOS Version 13.4 (Build 22F5049e)

### Steps:
1. installed `1.51.107`
2. launched Brave
3. loaded `http://upgradable.arthuredelstein.net/nonexistent.html`
4. clicked on the Shields icon to note the settings
6. confirmed I got an `HTTP 404` error
7. confirmed I remained on `http://upgradable.arthuredelstein.net/nonexistent.html`
8. clicked to toggle `Upgrade connections to HTTPS` to `Only connect with HTTPS`
9. confirmed I remained on `http://upgradable.arthuredelstein.net/nonexistent.html`
10. confirmed `Continue to site` and `Go back` buttons, which worked

example | example | example | example
---------|----------|---------|---------
<img width="1832" alt="Screenshot 2023-04-29 at 3 18 40 AM" src="https://user-images.githubusercontent.com/387249/235297815-54472439-d210-4817-8c15-b620a3334d3e.png"> | <img width="2007" alt="Screenshot 2023-04-29 at 3 19 11 AM" src="https://user-images.githubusercontent.com/387249/235297816-ce352028-d578-425a-b622-1de564929881.png"> | <img width="2007" alt="Screenshot 2023-04-29 at 3 20 13 AM" src="https://user-images.githubusercontent.com/387249/235297817-f25da0a0-b561-4706-ae3e-d20887fb09bb.png"> | <img width="2007" alt="Screenshot 2023-04-29 at 3 30 45 AM" src="https://user-images.githubusercontent.com/387249/235298144-2fee02ec-f578-40c3-b5e5-b86d2684955d.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.51.107 Chromium: 113.0.5672.63 (Official Build) (32-bit)
--- | ---
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Android 13; Build/UPB1.230309.014; 33; UpsideDownCake
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/28013#issue-1555554172 and ensured everything was working as expected:

* ensured that loading http://upgradable.arthuredelstein.net/nonexistent.html falls back to `HTTP://` due to the `404`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|-----------------|--------------
![Screenshot_20230501-012428](https://user-images.githubusercontent.com/2602313/235411113-dfe92150-8c4b-43b5-9043-f044adef2277.png) | ![Screenshot_20230501-012441](https://user-images.githubusercontent.com/2602313/235411119-06fbc443-638c-4528-a68d-b0514f8882e0.png) | ![Screenshot_20230501-012505](https://user-images.githubusercontent.com/2602313/235411122-d7fb1dc0-fb2c-4d70-943a-8052aca18470.png) | ![Screenshot_20230501-012510](https://user-images.githubusercontent.com/2602313/235411131-0812aa01-a07d-40e8-8010-3404899bb10f.png) | ![Screenshot_20230501-012543](https://user-images.githubusercontent.com/2602313/235411134-c6848edb-a6ab-4839-b5e4-cfe5d37c04e8.png)
