### ISSUE TITLE
Only allow auto contribute for verified publishers

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#2803]
We need to remove allow ac to non-verified option from UI and code.

**Comment by LaurenWags** [comment]
Since payments info can be imported from muon (including this 'Allow contribution to non-verified sites' setting) - does that need to be taken into consideration with this issue? i.e. can a user get around this option being removed from UI by importing payments info?
![screen shot 2019-01-04 at 11 12 53 am](https://user-images.githubusercontent.com/28145373/50698304-8480cc80-1012-11e9-8e81-0c0229465b06.png)

**Comment by NejcZdovc** [comment]
@LaurenWags this setting was removed, we now only query verified publishers in all lists

**Comment by NejcZdovc** [comment]
closing as this is not what we want anymore
