### ISSUE TITLE
Able to install `C110` on both `Windows 7` & `Win 8.1`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#28045]
Brave, just like Chrome ends support for Windows 7 and Windows 8

## Steps to Reproduce

1. Install C110 using standalone build

## Actual result:

Able to install the build without issue
Running Brave fails:
![image](https://user-images.githubusercontent.com/34715963/214665355-08821c5b-6ed5-49e4-9d83-0367dceb8451.png)

## Expected result:
unable to install Brave. Show message that Windows 10 and higher is needed 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

BraveBrowserNightlySetup_110_1_49_59.exe on Windows 7 x64

cc @kjozwiak @LaurenWags @rebron @mihaiplesa @wknapik

**Comment by btlechowski** [comment]
Chrome says in the installer: `No available updates`. User is not able to update.
But I used stab installer.

![image](https://user-images.githubusercontent.com/34715963/214700658-90cefa84-f367-4a43-8ce2-279c77bd330b.png)

**Comment by kjozwiak** [comment]
Basically got the same results as @btlechowski on `Win 8.1`. The only difference is that I didn't received any errors/messages about missing `dll` files. On `Win 8.1`, Brave opens and then closes right away (please see attached video example). As @btlechowski pointed out, looks like Chrome presents a warning via the stub install whenever attempting to install `C110` or higher. Chrome only offers stub installs so that should be easy to deny installations on `Win 7` & `Win 8.1`. However, we need to figure out a way to block installations of Brave using executables on the affected platforms.

**`Example video of the crash occurring`**

https://user-images.githubusercontent.com/2602313/214792173-06314510-441e-409c-9e23-f7cd844a1b26.mov

**`Example screenshots of Brave being installed using the executable`**

**`Example`** | **`Example`**
---------------|---------------
<img width="608" alt="Screenshot 2023-01-26 at 3 18 37 AM" src="https://user-images.githubusercontent.com/2602313/214792403-30e96212-4bae-4df6-a52c-69d897a393e2.png"> | <img width="790" alt="Screenshot 2023-01-26 at 3 19 01 AM" src="https://user-images.githubusercontent.com/2602313/214792411-094d5532-c203-47f1-912a-7f74fb649ed4.png">

**`Example screenshots of Chrome being installed using the stub installer`**

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
<img width="1235" alt="Screenshot 2023-01-26 at 3 21 06 AM" src="https://user-images.githubusercontent.com/2602313/214792486-8d0f8f1d-e8a2-4e0d-86cb-7a9c299a9576.png"> | <img width="548" alt="Screenshot 2023-01-26 at 3 23 29 AM" src="https://user-images.githubusercontent.com/2602313/214792519-20b83a5a-c297-440d-bd83-69357dfe9cc2.png"> | <img width="739" alt="Screenshot 2023-01-26 at 3 27 29 AM" src="https://user-images.githubusercontent.com/2602313/214792536-b5240cf1-fb05-41fd-8411-9b1e33d042b0.png">

**Comment by mihaiplesa** [comment]
Any ideas here @mherrmann?

**Comment by mherrmann** [comment]
We're still on CR109 with Nightly. Once we're on 110, our stub installer (i.e. the 1MB online installer) will give the same message as Chrome's: "No update is available".

Regarding the other installers: I expect the behavior reported by @btlechowski and @kjozwiak to continue until we provide a fix. That is, our offline installers will continue to work* in the sense that they will install Brave. But Brave will not launch.

*: Until we change our installer. This can happen when we upgrade from Omaha 3 to 4.

Regarding ideas: I wonder what Chrome will do. Their official offline installer is still on CR 110. My hope is that they will implement a solution we can reuse. I'd be surprised if they just let Chrome crash the way CR 110 seems to be doing now.

**Comment by mherrmann** [comment]
(Actually I think our stub installer will install the latest CR109 version until we - at some point in the future - remove it from the update server.)

**Comment by kjozwiak** [comment]
> We're still on CR109 with Nightly. Once we're on 110, our stub installer (i.e. the 1MB online installer) will give the same message as Chrome's: "No update is available".
> 
> Regarding the other installers: I expect the behavior reported by @btlechowski and @kjozwiak to continue until we provide a fix. That is, our offline installers will continue to work* in the sense that they will install Brave. But Brave will not launch.
> 
> *: Until we change our installer. This can happen when we upgrade from Omaha 3 to 4.
> 
> Regarding ideas: I wonder what Chrome will do. Their official offline installer is still on CR 109. My hope is that they will implement a solution we can reuse. I'd be surprised if they just let Chrome crash the way CR 110 seems to be doing now.

@mherrmann there's some examples above of what Chrome does with it's stub installers. But I could never find their offline installers. Mind linking me? I'll download one for Canary and see what happens on `Win 8.1`. I didn't think Google provided offline executables. Only stub installers. Searched for a bit before and could never find anything other than offline installers that  archive websites host which I'm always worried about download/using.

**Comment by mherrmann** [comment]
@kjozwiak I couldn't find offline installers for other channels. But for stable, I searched for "chrome offline installer", which took me [here](https://support.google.com/chrome/answer/95346?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cwindows), which under "How to install Chrome" has a section "Install Chrome offline" with a [download link](https://www.google.com/intl/en/chrome/browser/desktop/index.html?standalone=1).

**Comment by btlechowski** [comment]
Verified on Nightly 1.49.x on Windows 7 x64

stub installer installs `1.49.60 Chromium: 109.0.5414.119 (Official Build) nightly (64-bit)`. `c110` is not installed.
The `c110` is installed on Windows 10 x64

![image](https://user-images.githubusercontent.com/34715963/215119238-45aa8f15-5a90-4771-a3c1-b2e596ce89bd.png)

Update to c110 is no offered for `1.49.60 Chromium: 109.0.5414.119 (Official Build) nightly (64-bit)` 

![image](https://user-images.githubusercontent.com/34715963/215103711-d1bdacb8-9cfd-49dd-8eda-a0996262854b.png)

**Comment by btlechowski** [comment]
Verified on Nightly 1.49.x on Windows 7 x86

stub installer installs `1.49.60 Chromium: 109.0.5414.119 (Official Build) nightly (32-bit) `. `c110` is not installed.

![image](https://user-images.githubusercontent.com/34715963/215144594-71fa29e0-f285-47ec-8b21-78b68ecddfcf.png)

**Comment by kjozwiak** [comment]
@btlechowski mind checking the above again? I think this was resolved with the latest `C110` chromium. For example, I received a warning regarding not being able to install Brave as per https://github.com/brave/brave-browser/issues/28511. The warning is incorrect and should say `Win 10` or higher, but Brave didn't install like it did before as reported above.

**Comment by btlechowski** [comment]
Verified fixed 1.48.164 c110

I get a message from standalone installer. Also reproduced https://github.com/brave/brave-browser/issues/28511

![image](https://user-images.githubusercontent.com/34715963/219113282-177f721e-24f3-4c4d-995f-8ac623e78ef5.png)
