### ISSUE TITLE
Expose navigator.brave in workers

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#28101]
We recommend `navigator.brave.*` as the correct way for sites to detect brave browsers.  However, currently `navigator.brave` is not available in workers.  We should enable it in workers too, especially bc Mv3 extensions are service workers, and we should provide an easy way for Mv3 extensions to detect Brave

**Comment by goodov** [comment]
QA test page https://dev-pages.brave.software/dom-properties/controlled.html

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.76 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 22H2 (Build 19045.2788)

### Steps:
1. installed `1.51.76`
2. launched Brave
3. loaded `https://dev-pages.brave.software/dom-properties/controlled.html`
4. clicked `Run tests`
5. examined the results

#### Confirmed we now return `true`, instead of `null`, for the `Web` and `Service Workers`


`1.51.76`

set 1 | set 2
------|-------
![image (1)](https://user-images.githubusercontent.com/387249/229653109-6e99a2e8-5477-4be6-9782-94d7c785ee48.png) | ![image](https://user-images.githubusercontent.com/387249/229653111-6b593e2e-8843-485f-bd9c-6f79bdf5dd76.png)

`1.50.112`

set 1 | set 2
------|-------
![image (3)](https://user-images.githubusercontent.com/387249/229653257-6b8382b2-a366-404d-a2a7-189aa9d8608a.png) | ![image (2)](https://user-images.githubusercontent.com/387249/229653259-9875b729-f0e1-4d16-b93e-e92dc7ff4b44.png)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.51.105`


### Steps:
1. installed `1.51.x`
2. launched Brave
3. loaded `https://dev-pages.brave.software/dom-properties/controlled.html`
4. clicked `Run tests`
5. examined the results

#### Confirmed we now return `true`, instead of `null`, for the `Web` and `Service Workers`

### Shields Up - `PASSED`
<details>

`1.51.x`

set 1 | set 2
------|-------
![Screenshot_20230427_225215](https://user-images.githubusercontent.com/38657976/234943604-a5e5689d-a5a9-4e97-93b6-940a795292b3.jpg) | ![Screenshot_20230427_225320](https://user-images.githubusercontent.com/38657976/234943636-018c274d-dfa5-4d6c-8095-9e687527d340.jpg)



</details>

### Shields Down - `PASSED`
<details>

`1.51.x`

set 1 | set 2
------|-------
![Screenshot_20230427_230403](https://user-images.githubusercontent.com/38657976/234943751-b59da211-3674-4812-b2fc-93eac541b7e3.jpg) | ![Screenshot_20230427_230324](https://user-images.githubusercontent.com/38657976/234943724-020b382e-8b8a-4cf1-8c25-f7a125162d6a.jpg)








</details>

**Comment by vlad-hoff** [comment]
Verified on `Galaxy Tab S8` using version(s):

```
Device/OS: SM-X700 Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
Brave build: 1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit)
```
---------------------------
**Steps:**
1. Install 1.51.109
2. Launch Brave
3. Open https://dev-pages.brave.software/dom-properties/controlled.html
4. Tap "Run test"
5.  Verify results

<details>
<summary> Shields ON - PASS </summary>

**ACTUAL RESULTS:**
- Verified that we now return `true`, instead of `null`, for the `Web` and `Service Workers`

|1|2|
|:-:|:-:|
| ![1](https://user-images.githubusercontent.com/128532965/235764981-d4f01a3e-3922-434b-90db-57f46e684812.png) | ![2](https://user-images.githubusercontent.com/128532965/235764989-9b4f71b3-6a23-42fe-a98e-d1b438ebc541.png) |
</details>

<details>
<summary> Shields OFF - PASS </summary>

**ACTUAL RESULTS:**
- Verified that we now return `true`, instead of `null`, for the `Web` and `Service Workers`

|1|2|
|:-:|:-:|
| ![1](https://user-images.githubusercontent.com/128532965/235766306-411677d5-f223-4603-a759-8722d6b58dd4.png) | ![2](https://user-images.githubusercontent.com/128532965/235766372-4cd75d27-cbdd-4ba2-a6ad-636ce6c8f95c.png) |
</details>
