### ISSUE TITLE
[Android] In country selection list for declared geo, place OS region/locale country at top of list

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28320]
## Description

For better UX, we should place the user's device/OS region/locale at the top of the country dropdown list for ease.

![image](https://user-images.githubusercontent.com/11497541/217039612-91a02658-c043-41a7-8dc8-7d5ce9e27ce6.png)

**Comment by GeetaSarvadnya** [comment]
This issue is not working as expected in some devices where we have both `Languages` and `Region` settings. Looks like the country is shown at the top of the list based on the `Language` not based on the `Region`

In the below example, In `Vivo X70 Pro` device we have both `Languages` and `Region` settings, I have set the region as `India` and `Language` as English (United states), the country is shown at the top of the list based on the `Language` not based on the `Region`

Example | Example
----------|----------
![Screenshot_20230414_221236](https://user-images.githubusercontent.com/38657976/232109007-09215755-3a68-4d2b-b51e-91fb11174177.jpg) | ![Screenshot_20230414_221214](https://user-images.githubusercontent.com/38657976/232109072-3d62c4e2-faea-4f83-bef0-529f0bcad9a7.jpg)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.51,80`

OS Laguage is **_US_**

langauge settings `US` | Country at the top of the list is `US`
------------------------|----------------------------------------
![Screenshot_20230414-221614_Settings](https://user-images.githubusercontent.com/38657976/232111971-3e7f1819-5e4e-4f40-bcd8-95b10ed0af85.jpg) | ![Screenshot_20230414-221552_Brave - Beta](https://user-images.githubusercontent.com/38657976/232112012-5f3b575b-f09f-4118-9b2b-ca50f40a6170.jpg)

 OS Laguage is **_IN_**

langauge settings `IN` | Country at the top of the list is `IN`
------------------------|----------------------------------------
![Screenshot_20230414-221750_Settings](https://user-images.githubusercontent.com/38657976/232112256-f7d60ec3-186f-4966-8b03-75fdc0eb3133.jpg) | ![Screenshot_20230414-221737_Brave - Beta](https://user-images.githubusercontent.com/38657976/232112319-5cb01cce-8c7a-4b55-93c3-3ba746d413fd.jpg)

OS Laguage is **_Dutchland_**

langauge settings `_Dutchland_` | Country at the top of the list is `_Dutchland_`
------------------------------------|----------------------------------------
![Screenshot_20230414-221911_Settings](https://user-images.githubusercontent.com/38657976/232112514-a8891452-f025-4716-8811-dff4bcf789b6.jpg) | ![Screenshot_20230414-221902_Brave - Beta](https://user-images.githubusercontent.com/38657976/232112543-b82f1bf4-e757-4538-a347-c5e91966e13e.jpg)

**Comment by Miyayes** [comment]
@GeetaSarvadnya Do only some android devices have a region vs. language setting? Some of them only have language setting?

**Comment by GeetaSarvadnya** [comment]
@Miyayes That's correct. Most of the devices have only `Language` settings in that case this issue works fine. Only few devices like VIvo X70 Pro have both Region and Language settings.
