### ISSUE TITLE
Consider hiding inline search ads even in Standard blocking

### ISSUE THREAD

**Issue by Yuki2718** [brave/brave-browser#28387]
As in https://github.com/brave/adblock-rust/issues/258#issuecomment-1413443457, and now `https://www.pcworld.com/article/1502809/you-cant-trust-google-results-for-software-downloads-right-now.html` too, Google ads have been a popular source of scam and malware. You can't claim to be a secure browser while is endangering majority of user by that. Vivaldi hides at least Google search ads by default (bing not as their partner tho). This should be an exception for the 1p vs 3p policy of Brave simply because of the risk, but as most of scam/malware are inserted to inline search results, maybe only these inline ads can be targeted. Safe browsing has *not* been blocking most of these malware sites.

**Comment by antonok-edm** [comment]
I think this policy is unlikely to change, for a few reasons:
- a surprising number of non-technical users find those results to be useful and expect them to be there. Personally, I'm wary of search ads too and always use Aggressive mode, but making privacy accessible by default to a wide audience involves some tradeoffs.
- Brave runs a search engine as well. The same "ads shown by default, hidden in aggressive mode" policy is applied across all search engines; specifically blocking competitors is not a great move in the spirit of healthy competition.
- https://search.brave.com has been the default search engine for new Brave users for a while now, so even if Google is particularly bad at filtering out malicious content in their SERP ads, it'd have to be an explicit choice by the user to be viewing those instead.

(fwiw, `adblock-rust` is built as a general-purpose adblocking engine and doesn't have any special logic built-in for this kind of purpose, which is why I've moved it to the `brave-browser` repo)

**Comment by Yuki2718** [comment]
> https://search.brave.com/ has been the default search engine for new Brave users for a while now

Oh, I forgot this. Okay.

**Comment by Yuki2718** [comment]
> https://search.brave.com/ has been the default search engine for new Brave users for a while now, so even if Google is particularly bad at filtering out malicious content in their SERP ads, it'd have to be an explicit choice by the user to be viewing those instead.

This is not true, on v1.62.162 I see Google is still default search except for incognito window.

**Comment by Yuki2718** [comment]
Maybe this should be reconsidered as now Yahoo-JP is default search engine for Japanese: https://github.com/brave/brave-core/pull/28154
Complaint (though the claim is inaccurate): https://community.brave.com/t/yahoo-japan/609669
