### ISSUE TITLE
Show title for custom filter list subscriptions

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#28416]
The `Title` field of custom adblock filter list subscriptions was previously exposed to the browser (https://github.com/brave/brave-browser/issues/17910), but never shown in the UI. It should be displayed instead of the subscription URL, if it is available.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.50.90 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

New profile: 

1. Install 1.50.90
2. launch Brave
3. open a new-tab
4. visited `brave://settings/shields/filters` 
5. added `https://filters.adtidy.org/extension/chromium/filters/17.txt` to the `Add custom filter lists` section
6. confirmed that the title of the first column in the table displayed as `List title`
7. confirmed that the entry under List title is `AdGuard URL Tracking filter`
8. added `https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/TrackParamFilter/sections/general_url.txt` as second custom filter list
9. confirmed that the title is just the URL of the list (truncated as necessary to fit on-screen)
10. confirmed when hovered over each of the titles, mouseover text shows the full original URLs used to subscribe to each

step 5 | step 6-7 | step 9 | step 10a | step 10b
-------- | -------- | -------- | ------- | --------
<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/224751028-283c54bf-9ac7-484b-9ea9-33e0137708d2.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/224751098-f2e28cec-8b36-47d3-81b9-2f3a5f41ce45.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/224753269-c5ee6838-ac8c-4967-94d6-238ff171fe3e.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/224753396-3ce81c11-e753-40a8-9075-5227fe4b330e.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/224753529-12ddf1f6-4d51-414f-9347-518b7cfdb6f2.png">

Upgrade: 

1. Install 1.49.120
2. launch Brave
3. open a new-tab
4. visited `brave://settings/shields/filters` 
5. added `https://filters.adtidy.org/extension/chromium/filters/17.txt` to the `Add custom filter lists` section
6. verified that the title of the first column in the table is displayed as `List URL` and full URL is displayed
7. added `https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/TrackParamFilter/sections/general_url.txt` as second custom filter list
8. close the browser
9. install 1.50.90
10. rename the Brave-Browser profile as Brave-Browser-Beta
11. launch Brave 
12. got to `brave://settings/shields/filters` 

- Confirmed that the title of the first column in the table displayed as `List title` instead of `List URL`
- Confirmed the first entry under `List title` in the `Custom lists` table is `AdGuard URL Tracking filter` instead of full URL
- Confirmed the second entry in the `Custom lists` table is displayed as URL and is truncated 
- Confirmed when hovered over each of the titles, mouseover text shows the full original URLs used to subscribe to each

step 1 | step 4-7 | result | result
------ | ------ | ------ | -------
<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/224756918-416c8573-9b17-4064-95c6-b7486c1d5e0f.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/224762105-7ee066a6-5703-4847-946f-b9346fa160d3.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/224764922-c12b0278-8fea-4c02-91bc-c91624ec8cc9.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/224764975-b4c03889-8f6a-415c-af1b-cb4f5f208661.png">
