### ISSUE TITLE
Tor settings not fully isolated in HTTPS by Default

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#28540]
HTTPS by Default is leaking some fallback settings into Tor Mode. We should fix this to ensure that if a fallback occurs in a normal window, it doesn't occur in the Tor Window.

**Comment by stephendonner** [comment]
@arthuredelstein should this be `QA/Yes`?  If so, please add it and a test plan.  Thanks!

**Comment by stephendonner** [comment]
Thanks for adding `QA/Yes`, @arthuredelstein - mind putting in a test plan, too?  🙏

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` until we have a test plan, thanks!

**Comment by LaurenWags** [comment]
@kjozwiak provided additional information to @brave/qa-team via:
- https://bravesoftware.slack.com/archives/GAA4017R7/p1679978545140059?thread_ts=1679926805.216109&cid=GAA4017R7
- https://bravesoftware.slack.com/archives/GAA4017R7/p1679978617998959?thread_ts=1679926805.216109&cid=GAA4017R7

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.5 (Build 20G1225)

### Normal window
<details>

insecure.arthuredelstein.net

upgradable.arthuredelstein.net

</details>

### Private window with Tor
<details>

insecure.arthuredelstein.net

upgradable.arthuredelstein.net

</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Ubuntu 18.04 LTS

Testcase:  Set Global settings for Https Default   - `PASSED`

#### Case 1: `Upgrade connections to HTTPS` - `Standard`; default setting via Normal window - `PASSED`
<details>

1. Install 1.50.x
2. launched Brave
3. enabled `#Use HTTPS by Default` in `brave://flags`
4. visited brave://settings/shields 
5. loaded http://insecure.arthuredelstein.net
6. loaded http://http.badssl.com
7. loaded http://upgradable.arthuredelstein.net
8. confirmed Upgrade connections to HTTPS option is displayed as default in the Normal window
9. opened a `New private window with Tor` for above sites

#### Confirmed since Tor windows always use `Strict mode` and Normal window setting is `Standard`
- confirmed Shields panel do not show HTTPS Upgrade connections dropdown in the Advanced controls 
- confirmed `insecure connection` interstitial page displayed for `http://insecure.arthuredelstein.net/`
- confirmed when clicked on interstitial page, http://insecure.arthuredelstein.net/ loads without any issues
- confirmed `insecure connection` interstitial page displayed for http://http.badssl.com/ 
- confirmed when clicked on interstitial page, http://http.badssl.com/ loads without any issues
- confirmed that http://upgradable.arthuredelstein.net/ -> https://upgradable.arthuredelstein.net/ (connection upgraded)

step 3| step 4|step `insecure.arthuredelstein.net` | `http://http.badssl.com/` | `upgradable.arthuredelstein.net`
----------|---------|-------------------|--------------------|-------------
![image](https://user-images.githubusercontent.com/34715963/229825236-0fa1b241-0eb1-49c7-bab9-a86bd5ff6d55.png)|![image](https://user-images.githubusercontent.com/34715963/229824614-120f6559-4797-4e34-b25f-460a97b4351c.png)|![image](https://user-images.githubusercontent.com/34715963/229826470-bffc35da-1e6c-4afa-8b14-645f32d737f1.png)|![image](https://user-images.githubusercontent.com/34715963/229826668-419339fd-4f7a-480e-8973-a6f75c7980b1.png)|![image](https://user-images.githubusercontent.com/34715963/229827348-18154e69-bb1f-4c99-a0a4-1ce381752398.png)


</details>

#### Case 2: `Upgrade connections to HTTPS` - Strict - `PASSED` via Normal window - 
<details>

1. new profile
2. launched Brave
3. enabled `#Use HTTPS by Default` in `brave://flags`
4. visited `brave://settings/shields`
5. selected `Strict` in the `Upgrade connections to HTTPS` 
6. loaded http://insecure.arthuredelstein.net
5. loaded http://http.badssl.com
6. loaded http://upgradable.arthuredelstein.net
7. opened a `New private window with Tor` for above sites

#### Confirmed following since Tor windows always use `Strict mode` and Normal window setting is `Strict`

- confirmed Shields panel do not show HTTPS Upgrade connections dropdown in the Advanced controls 
- confirmed `insecure connection` interstitial page displayed for `http://insecure.arthuredelstein.net/`
- confirmed when clicked on interstitial page, http://insecure.arthuredelstein.net/ loads without any issues
- confirmed `insecure connection` interstitial page displayed for http://http.badssl.com/ 
- confirmed when clicked on interstitial page, http://http.badssl.com/ loads without any issues
- confirmed that http://upgradable.arthuredelstein.net/ -> https://upgradable.arthuredelstein.net/ (connection upgraded)

step 3| step 4|step `insecure.arthuredelstein.net` | `http://http.badssl.com/` | `upgradable.arthuredelstein.net`
----------|---------|-------------------|--------------------|-------------
![image](https://user-images.githubusercontent.com/34715963/229828119-06661521-bd24-428a-b6cb-a70c5db52a9e.png)|![image](https://user-images.githubusercontent.com/34715963/229828209-67149165-636a-4685-a4aa-efecb069acc1.png)|![image](https://user-images.githubusercontent.com/34715963/229828533-2b4c40e6-a0d1-4789-9a54-0eb913c1cd63.png)|![image](https://user-images.githubusercontent.com/34715963/229828688-99ff580c-cd2b-4033-b7b8-02c56a413865.png)|![image](https://user-images.githubusercontent.com/34715963/229829171-366575dc-ec26-4328-bc35-2d0da11cf983.png)



</details>

#### Case 3: `Upgrade connections to HTTPS` - Disabled - `PASSED`
<details>

1. new profile
2. launched Brave
3. enabled `#Use HTTPS by Default` in `brave://flags`
4. visited `brave://settings/shields`
5. selected `Disabled` in the `Upgrade connections to HTTPS` 
6. loaded http://insecure.arthuredelstein.net
5. loaded http://http.badssl.com
6. loaded http://upgradable.arthuredelstein.net
7. opened a `New private window with Tor` for above sites

Confirmed since Tor windows always use `Strict mode` and global setting is `Disabled`
- confirmed Shields panel do not show HTTPS Upgrade connections dropdown in the Advanced controls 
- confirmed `insecure connection` interstitial page displayed for `http://insecure.arthuredelstein.net/
- confirmed when clicked on interstitial page, http://insecure.arthuredelstein.net/ loads without any issues
- confirmed `insecure connection` interstitial page displayed for http://http.badssl.com/ 
- confirmed when clicked on interstitial page, http://insecure.arthuredelstein.net/ loads without any issues
- confirmed that http://upgradable.arthuredelstein.net/ -> https://upgradable.arthuredelstein.net/ (connection upgraded)

step 3| step 4|step `insecure.arthuredelstein.net` | `http://http.badssl.com/` | `upgradable.arthuredelstein.net`
----------|---------|-------------------|--------------------|-------------




</details>
