### ISSUE TITLE
Enable download-bubble feature by default

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#28562]
Chromium has two features for download bubble
* download-bubble
* download-bubble-v2

When it's enabled, user can see download status from bubble in toolbar instead of download shelf.

<img width="470" alt="Screenshot 2023-02-16 at 5 05 34 PM" src="https://user-images.githubusercontent.com/6786187/219304764-c4c04f75-11da-468a-9841-82577bd7f18b.png">
<img width="422" alt="Screenshot 2023-02-16 at 5 05 49 PM" src="https://user-images.githubusercontent.com/6786187/219304782-957fa6ac-40e7-4f2e-b1a4-8dddda0ffcb8.png">

STR
1. Launch brave and download any files
2. Check download bubble is shown when downloads start
3. Check download bubble shows each item's download status

cc @rebron

**Comment by simonhong** [comment]
Can we enable this now from security point of view? cc @diracdeltas @fmarier

**Comment by simonhong** [comment]
It's enabled on my Chrome Win11 but not on macOS.
It's disabled by default - https://source.chromium.org/chromium/chromium/src/+/main:components/safe_browsing/core/common/features.cc;l=77
Maybe it would be enabled by finch on Win11.

and our download page doesn't fit well with download bubble UI.
<img width="716" alt="Screenshot 2023-02-16 at 5 14 27 PM" src="https://user-images.githubusercontent.com/6786187/219307252-7d8bfaf0-2b5c-45a2-adb0-6a2ac9d38265.png">

**Comment by stephendonner** [comment]
> It's enabled on my Chrome Win11 but not on macOS. It's disabled by default - https://source.chromium.org/chromium/chromium/src/+/main:components/safe_browsing/core/common/features.cc;l=77 Maybe it would be enabled by finch on Win11.
> 
> and our download page doesn't fit well with download bubble UI. (macOS) <img alt="Screenshot 2023-02-16 at 5 14 27 PM" width="716" src="https://user-images.githubusercontent.com/6786187/219307252-7d8bfaf0-2b5c-45a2-adb0-6a2ac9d38265.png">

This is already being fixed, thankfully 👍 https://github.com/brave/brave-com-resources/issues/668

**Comment by fmarier** [comment]
That sounds good to me.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.90 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

### Steps:
1. installed `1.50.90`
2. launched Brave
3. loaded `https://www.thinkbroadband.com/download`
4. context-clicked on `http://ipv4.download.thinkbroadband.com:8080/1GB.zip`
5. chose `Save Link As...`
6. clicked `Save`
7. confirmed download was initially blocked, due to being an `http://` resource on an `https://` site
8. clicked on the blocked notification
9. clicked on the `Continue download` button
10. confirmed download resumed
11. confirmed download progress was reflected in the `Downloads` button
12. clicked on the above button
13. confirmed double-click and context-menu options work as expected

example | example | example | example
--|--|--|--
<img width="1335" alt="Screen Shot 2023-03-13 at 4 29 00 PM" src="https://user-images.githubusercontent.com/387249/224854937-b3cb2b3d-f2d2-49d8-84cb-bf23e6497369.png"> | <img width="1452" alt="Screen Shot 2023-03-13 at 4 29 12 PM" src="https://user-images.githubusercontent.com/387249/224854940-cf97739c-9816-4b96-b731-8057251e4fb4.png"> | <img width="1452" alt="Screen Shot 2023-03-13 at 4 29 21 PM" src="https://user-images.githubusercontent.com/387249/224854941-5f1c2e64-a05c-443f-931b-6e1cde633d7f.png"> | <img width="1452" alt="Screen Shot 2023-03-13 at 4 29 29 PM" src="https://user-images.githubusercontent.com/387249/224854943-f82f6a81-55e3-4c5e-8f3b-4598cf12ef26.png">

example | example | example | example
--|--|--|--
<img width="1452" alt="Screen Shot 2023-03-13 at 4 29 33 PM" src="https://user-images.githubusercontent.com/387249/224854945-2ad8a621-42c7-4cc1-a012-c59696e04f80.png"> | <img width="1452" alt="Screen Shot 2023-03-13 at 4 29 38 PM" src="https://user-images.githubusercontent.com/387249/224854949-7f9daa96-aaf5-4c8d-9249-763388e438a0.png"> | <img width="1452" alt="Screen Shot 2023-03-13 at 4 30 53 PM" src="https://user-images.githubusercontent.com/387249/224854951-04c0b26c-3736-4fa5-84a0-2e3f7a9ddbc0.png"> | <img width="1452" alt="Screen Shot 2023-03-13 at 4 31 04 PM" src="https://user-images.githubusercontent.com/387249/224854952-9ebd1369-30ba-462d-b2fe-7e021e4d3404.png">

Also confirmed that both `Enable download bubble...` flags are set to `Default`, in `brave://flags`

<img width="1967" alt="Screen Shot 2023-03-13 at 4 41 40 PM" src="https://user-images.githubusercontent.com/387249/224856050-38b01571-dba7-4475-8cf5-e7d0f96c932c.png">

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.50.99 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```
Case 1: `New Window`
<details>

### Steps:
1. installed `1.50.99`
2. launched Brave
3. loaded `https://www.thinkbroadband.com/download`
4. context-clicked on `http://ipv4.download.thinkbroadband.com:8080/1GB.zip`
5. chose `Save Link As...`
6. clicked `Save`
7. confirmed download was initially blocked, due to being an `http://` resource on an `https://` site
8. clicked on the blocked notification
9. clicked on the `Continue download` button
10. confirmed download resumed
11. confirmed download progress was reflected in the `Downloads` button
12. clicked on the above button
13. confirmed context-menu options work as expected and successfully completed download
14. confirmed double-click option work as expected

step 4|step 5-6|step 7|step 8|step 9|step 10|step 11|step13
----|----|----|---|----|---|----|----
<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/227259202-f5c665bf-6fcc-40df-9e86-a602ad049296.png">|<img width="946" alt="image" src="https://user-images.githubusercontent.com/98358127/227260506-dd1f8ecb-35c0-4755-beb2-b9c46481bfc2.png">|<img width="943" alt="image" src="https://user-images.githubusercontent.com/98358127/227260654-8063f182-0ae5-41ea-aa60-a46b14fe3d5a.png">|<img width="946" alt="image" src="https://user-images.githubusercontent.com/98358127/227260864-c3eea67d-a9ca-4cde-a2c0-bdee84af0556.png">|<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/227261011-8a0f4610-0979-4bc7-b493-ba82018b4c9e.png">|<img width="943" alt="image" src="https://user-images.githubusercontent.com/98358127/227263568-ec3286e5-b675-4602-992a-3e5d6a89a473.png">|<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/227263612-637d9a8e-690d-4611-90e1-b9628071bfe4.png">|<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/227267794-c8f54b11-0bdf-481e-b4e6-244040a994be.png">


`brave://flags`

Also confirmed that both Enable download bubble... flags are set to Default, in brave://flags
<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/227264895-c3ecd0a8-7b20-462e-a497-a331518ca07c.png">

</details>

Case 2: Private Window 
<details>

### Steps:

1. new profile
2. launched Brave
3. click Hamburger menu > New private window
4. loaded `https://www.thinkbroadband.com/download`
5. context-clicked on `http://ipv4.download.thinkbroadband.com:8080/1GB.zip`
6. chose `Save Link As...`
7. clicked `Save`
8. confirmed download was initially blocked, due to being an `http://` resource on an `https://` site
9. clicked on the blocked notification
10. clicked on the `Continue download` button
11. confirmed download resumed
12. confirmed download progress was reflected in the `Downloads` button
13. clicked on the above button
14. confirmed context-menu options work as expected and successfully completed download
15. confirmed double-click option work as expected


step 5|step 7 
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/227315909-d1fa6773-62c0-4067-b7d6-9e7a058829ac.png">
<img width="951" alt="image" src="https://user-images.githubusercontent.com/98358127/227316081-8d1884a7-4fa4-415c-9c58-a7f54eab15bc.png">
<img width="940" alt="image" src="https://user-images.githubusercontent.com/98358127/227304548-49e3bb3f-d404-4ce5-82f3-a83abaf6e22f.png">
<img width="951" alt="image" src="https://user-images.githubusercontent.com/98358127/227304631-bacf5409-2698-46f6-8877-04c7b3d78a74.png">
<img width="949" alt="image" src="https://user-images.githubusercontent.com/98358127/227304685-31ba6848-4b32-4cbd-a0f7-79b52e27d9d0.png">
<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/227304975-05d80eb9-1e80-4d96-b33a-11f7f099102a.png">
<img width="942" alt="image" src="https://user-images.githubusercontent.com/98358127/227305415-387a0c5d-0308-47ad-9181-c5085e474385.png">

</details>

Case 3: Private window with Tor 
<details>
1. new profile
2. launched Brave
3. click Hamburger menu > New private with Tor window
4. loaded `https://www.thinkbroadband.com/download`
5. checked `Verify you are human` checkbox
5. context-clicked on `http://ipv4.download.thinkbroadband.com:8080/200GB.zip`


<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/227318706-0ee7f052-f6a8-4fc8-a45c-e1655d82043c.png">
<img width="944" alt="image" src="https://user-images.githubusercontent.com/98358127/227319318-54159a37-48e0-435f-ac15-fafc8408a8c7.png">
<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/227319449-403aea04-bfc8-4665-a975-d94f1f7ac37b.png">
<img width="934" alt="image" src="https://user-images.githubusercontent.com/98358127/227319517-d02bdd30-96a5-4f92-a4b9-07428040d4c7.png">
<img width="948" alt="image" src="https://user-images.githubusercontent.com/98358127/227319878-12c6cb50-eca3-4a9c-a3b1-b4d63b17d304.png">
<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/227320219-c8e7ffaa-14e1-454c-ba40-65ba4cc3da4b.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/98358127/227320444-204aef03-d263-4d73-932d-a72b2e082a11.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/98358127/227320638-25bf2f5c-e51b-4ea0-b2fb-1a4b2904ddce.png">
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/227316758-b0ece267-de37-49c7-ba63-e6a91643459e.png">

</details>

**Comment by ArkadiuszNiemiec** [comment]
The `Ask where to save each file before downloading` option is ignored in incognito. Is that intended? If yes, then can we get a flag for it? Before the bubble change, it was auto downloading in incognito for me.
@stephendonner

**Comment by diracdeltas** [comment]
> The `Ask where to save each file before downloading` option is ignored in incognito. Is that intended? If yes, then can we get a flag for it? Before the bubble change, it was auto downloading in incognito for me.

this sounds like a bug. cc @mkarolin

**Comment by ArkadiuszNiemiec** [comment]
> @ArkadiuszNiemiec, I wasn't able to reproduce. Is there a specific webpage you could point me to where you encountered this behavior? Thanks.

I just use the link from top: http://ipv4.download.thinkbroadband.com:8080/1GB.zip

Maybe there's something wrong on my setup, but I did not change anything other than update the Brave. I recorded it:

https://user-images.githubusercontent.com/12136404/232829193-9868abde-5dfa-46f4-8d15-9e1b2081dd02.mp4

**Comment by mkarolin** [comment]
@ArkadiuszNiemiec Thank you for the additional info and the video. I initially thought it wasn't asking with the option turned on, but the problem is it still asks in the private window when the option is toggled to off. Created a new issue for this: https://github.com/brave/brave-browser/issues/29823

**Comment by cyfra80** [comment]
This option is very annoying, the previous way of downloading was much friendlier. 
Such changes should not be forced, it should be an option in the settings at most.
This is a very bad move.

**Comment by second2falcon** [comment]
@cyfra80 I agree, but the problem is that Google beinh Google has decided the faith of modern internet browsers yet again. Google changed the Chromium code base which is used by Brave (and a lot of other browsers).

If I saw the Git commits in the Chromium repo correctly it shouldn't be too much work to add it back though (could be wrong as I don't know a lot about programming).

See [Chromium GIT](https://chromium-review.googlesource.com/c/chromium/src/+/4851411) for the mentioned file changes.
