### ISSUE TITLE
Hover card for vertical tabs should be aligned next to the tab

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#28594]
## Description 

Currently in vertical tabs mode, the hover card (default) or hover card preview show below and centered on mouseover. The hover card or hover card preview should show next to tab.

## Steps to Reproduce

   1.  Enable vertical tabs mode in nightly 1.50.x or higher
   2. Open several tabs in vertical tabs.
   3. Ensure brave://settings/appearance Tab hover mode Card or Card preview are enabled.
   4. Notice screenshot in actual result below where Card/Card preview are centered below the tab.

## Actual result:

<img width="318" alt="Screenshot 2023-02-17 at 1 07 40 PM" src="https://user-images.githubusercontent.com/5951041/219794835-bc2b22ca-0e1a-4379-8a4b-6c5b1582f711.png">

## Expected result:
Proposed
![screen_shot_2023-02-17_at_4 13 07_pm_720](https://user-images.githubusercontent.com/5951041/219794848-2b2ce875-041d-4692-8c04-aff33e313a33.png)

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.48.x and higher with vertical tabs flag enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes w/ flag enabled
- Can you reproduce this issue with the beta channel? yes w/ flag enabled
- Can you reproduce this issue with the nightly channel? yes w/ flag enabled

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc: @zenparsing

**Comment by sangwoo108** [comment]
TabSearch should be aligned in the same way.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

### Steps:
1. installed `1.50.91`
2. launched Brave
3. opened `brave://flags`
4. set `Vertical Tabs` to `Enabled`
5. clicked `RELAUNCH` button
6. loaded `cbsnews.com`
7. context-clicked on the tab and selected `Use Vertical Tabs`
8. hovered over the tab's title on the left

#### Confirmed we now show the preview/hover card to the right, rather than below it


`1.50.91` | `1.49.120`
----------|----------
<img width="629" alt="Screen Shot 2023-03-14 at 3 59 06 PM" src="https://user-images.githubusercontent.com/387249/225161040-fe895a8d-b5c4-4577-8329-7c2770ec59ad.png"> | <img width="690" alt="Screen Shot 2023-03-14 at 4 00 09 PM" src="https://user-images.githubusercontent.com/387249/225160912-18d44c97-8412-42ff-a860-0d3070ee16d6.png">
