### ISSUE TITLE
Temporary workaround for "brave scheme is loaded from js"

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2861]
This is to track a temporary fix for this issue: 
https://github.com/brave/brave-browser/issues/2777

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.20 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/1196
Test case 1 PASS - `brave://settings` is not loaded after 2.5 seconds 
Test case 2 is invalid for 0.58.x, because there is no `Change your search engine page` in welcome page. Used other link in the welcome page and they work as expected
Test case 3 is invalid for 0.58.x, because sync is disabled

Verification passed on

Brave | 0.59.21 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/1196
All TCs PASSED
