### ISSUE TITLE
Create an .aab bundle for Brave

### ISSUE THREAD

**Issue by roushanraj** [brave/brave-browser#28771]
## Description 
I am fairly new to brave browser project, I want to generate a bundle along with the signing feature, and I can't find any command for same in readme files.

## Actual result 
.apk file using the build commands

## Expected result
.aab file with self signed certificate

**Comment by bsclifton** [comment]
Hi @roushanraj 

Just to share notes, when running a signed build, I run like this:
```
npm run create_dist -- Release --channel=nightly --target_os=android --target_arch=arm --target_android_output_format=apk
```

This will do a full build and create APK. Since you want AAB, you can change to be:
```
npm run create_dist -- Release --channel=nightly --target_os=android --target_arch=arm --target_android_output_format=apk
```

However, there are going to be a lot of things that fail during the build. You'll need to edit your `.npmrc` file and provide values. During the build, GN should fail assertions when there are missing values and you can provide them.

We can't share our certificate and signing info - so you'll have to generate that yourself
