### ISSUE TITLE
Enable NFT pinning flag

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#29017]
Figma: https://www.figma.com/file/4e7rsWzBUKv3dCdxCqB6CR/NFT-IPFS?t=afIihL0uQG3FO3gV-0
Related issues:

https://github.com/brave/brave-browser/issues/19283
https://github.com/brave/brave-browser/issues/26828
https://github.com/brave/brave-browser/issues/28304
https://github.com/brave/brave-browser/issues/28775
https://github.com/brave/brave-browser/issues/28928
https://github.com/brave/brave-browser/issues/28233
https://github.com/brave/brave-browser/issues/28073
https://github.com/brave/brave-browser/issues/28169
https://github.com/brave/brave-browser/issues/28986

Related description(sec review):

Testing plan:
**Enabling the feature**
1) Enable the NFT pinnig feature flag at chrome://flags
2) Open brave wallet, add some pinnable NFTs.
Pinnable NFTs are NFTs which have ipfs:// scheme for metadata and for image.
For example BAYC tokens are pinnable https://opensea.io/assets/ethereum/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/4352
Also metadata and image may have gateway-like url format. Such tokens are also pinnable
https://opensea.io/assets/ethereum/0x9401518f4ebba857baa879d9f76e1cc8b31ed197/400
3) Check onboarding flow by clicking "Learn more button" on the wallet page
![image](https://user-images.githubusercontent.com/106654560/224719707-22fbd2df-2ebd-41a0-bcfa-3825772333ac.png)
Flow is described here : https://www.figma.com/file/4e7rsWzBUKv3dCdxCqB6CR/NFT-IPFS?node-id=1660%3A95153&t=CAsaMQ99tSq1M9NW-0
4) After NFT pinning is enabled from the onboarding flow check settings page, this setting should be enabled:
![image](https://user-images.githubusercontent.com/106654560/224727459-0d0cb3c5-23b9-448d-8990-c5dd59e8a472.png)

**Pinning**

5) Check pinnable NFTs for pinning status according this design 
https://www.figma.com/file/4e7rsWzBUKv3dCdxCqB6CR/NFT-IPFS?node-id=1044%3A102005&t=CAsaMQ99tSq1M9NW-0
6) If token is pinned, check pins manually by calling
`curl http://127.0.0.1:<api port could be viewed at chrome://ipfs-internal>/api/v0/pin/ls?type=recursive`
while running the Kubo daemon.
Result should contain metadata CIDs and image CIDs of the pinned tokens.

**Unpinning**

7) Remove a pinned NFT and wait for a while.
8) Check pin was really removed by calling  
`curl http://127.0.0.1:<api port could be viewed at chrome://ipfs-internal>/api/v0/pin/ls?type=recursive`
NOTE: Some of NFTs may share CIDs, so CID won't be unpinned until all related NFTs are removed.

**Pins validation**

9) Pin several tokens and check they are actually pinned. Delete brave_ipfs folder in the browser profile folder.
10) Change current date to 3 days forward and relaunch the browser. This should activate validation task.
11) After several time pins should be restored, so 
`curl http://127.0.0.1:<api port could be viewed at chrome://ipfs-internal>/api/v0/pin/ls?type=recursive` should contain them.

**Disabling the feature**
12) Disabling the feature should lead to hiding pinning status or pinning-related UI on the wallet page.
13) Tokens are not unpinned unless manually cleaned up.

**Cleanup**
14) After feature is disabled in the settings, there should be an option to remove all pinned items. Cleanup should be verified using `curl http://127.0.0.1:<api port could be viewed at chrome://ipfs-internal>/api/v0/pin/ls?type=recursive`.

**Local node behaviour**
15) Check whether local node is automatically started after browser starts if the NFT pinning setting is enabled and not started otherwise.

**Errors handling**
16) Content type of NFT's image url should be "image/*". Request is made to https://<nft gateway>/ipfs/CID and metadata field content-type or mime-type is read. You can test behavior by sniffing such requests as described here https://github.com/brave/brave-core/pull/17392#issue-1601409979
17) Pinning may fail due some reasons. It would be restarted after a time or on the next browser start. You can fail pinning by turning internet off while pinning is in progress and then test if it is continued after restart.

**Comment by yrliou** [comment]
Security & privacy review done in https://github.com/brave/security/issues/1182

**Comment by kjozwiak** [comment]
The above requires `1.51.80` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Linux

<details>
<summary>Verified steps from issue description</summary>
<br>

<details>
<summary>Enabling the feature - <b>Passed</b></summary>
<br>

- Verified `brave://flags/#enable-nft-pinning` is set to `Default` 
- Verified adding an NFT to visible asset list, automatically shows the NFT pinning banner 
- Verified clicking on `Learn more` on the banner loads interstitial page `brave://wallet/crypto/local-ipfs-node`
- Verified clicking on `Check which NFT's of mine can be pinned` loads second interstitial page `brave://wallet/crypto/inspect-nfts`
- Verified clicking on `Keep my NFTs always online` starts IPFS on localhost and start pinning the available NFT's
- Verified when `Keep my NFTs always online` is selected, setting `Automatically pin NFT's` is enabled, default is disabled

</details>
<details>
<summary>Pinning - <b>Passed</b></summary>
<br>

- Verified able to pin NFTs
- Verified when pinning is in process, shows message banner message about being pinned in local node
- Verified when successfully pinned, show message about number of NFTs that are pinned
- Additional verification notes for [banner messages](https://github.com/brave/brave-browser/issues/28986#issuecomment-1501609557) and [pinning data recursively](https://github.com/brave/brave-browser/issues/29230#issuecomment-1501547620) 

</details>
<details>
<summary>Unpinning - <b>Passed</b></summary>
<br>

- Verified after removing an NFT and running `curl http://127.0.0.1:<api port could be viewed at chrome://ipfs-internal>/api/v0/pin/ls?type=recursive`, shows `{"Keys":{}}` message 
![image](https://user-images.githubusercontent.com/17010094/230881406-f7717550-4eb3-4db5-b914-fd17ba9c028d.png)

</details>
<details>
<summary>Pins Validation - <b>Passed</b></summary>
<br>

- Verified deleting `brave_ifps` folder and moving date ahead and restarting the browser restores `brave_ipfs` folder again
- Verified resetting device date back to current date after restart starts to pin the NFT's again.
- Running `curl http://127.0.0.1:<api port could be viewed at chrome://ipfs-internal>/api/v0/pin/ls?type=recursive` continues to show the pinned NFT details

</details>
<details>
<summary>Disable feature - <b>Passed</b></summary>
<br>

- Verified disabling `Automatically pin NFTs` setting and reloading the NFT tab shows the onboarding banner message
- Verified manually deleting the NFT's from visible asset list also removes the onboarding banner message

</details>
<details>
<summary>Cleanup - <b>Passed</b></summary>
<br>

- Verified disabling `Automatically pin NFTs` setting, a new setting for `Clear pinned NFTs` is shown
- Verified clicking that clears the NFTs pinned state and shows onboarding banner message
- Encountered [#29553](https://github.com/brave/brave-browser/issues/29553) & [#29554](https://github.com/brave/brave-browser/issues/29554)

</details>
<details>
<summary>Local node behaviour - <b>Passed</b></summary>
<br>

- Verified when user click on `Get started with IPFS` from interstitial page, IPFS local node is installed and started.

</details>
<details>
<summary>Error handling - <b>Passed</b></summary>
<br>

- Verified if NFT's `content-type` is not of the format `image/*`, NFT pinning fails. Verified as part of [brave-browser#28775 (comment)](https://github.com/brave/brave-browser/issues/28775#issuecomment-1475924572)
- Verified due to network issues NFT pinning fails, it starts the pinning process again when browser is restarted

</details>
</details>

---------------------

**Verification passed on**

Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

<details>
<summary>Verified steps from issue description</summary>
<br>

<details>
<summary>Enabling the feature - <b>Passed</b></summary>
<br>

- Verified `brave://flags/#enable-nft-pinning` is set to `Default` 
- Verified adding an NFT to visible asset list, automatically shows the NFT pinning banner 
- Verified clicking on `Learn more` on the banner loads interstitial page `brave://wallet/crypto/local-ipfs-node`
- Verified clicking on `Check which NFT's of mine can be pinned` loads second interstitial page `brave://wallet/crypto/inspect-nfts`
- Verified clicking on `Keep my NFTs always online` starts IPFS on localhost and start pinning the available NFT's
- Verified when `Keep my NFTs always online` is selected, setting `Automatically pin NFT's` is enabled, default is disabled

</details>
<details>
<summary>Pinning - <b>Passed</b></summary>
<br>

- Verified able to pin NFTs
- Verified when pinning is in process, shows message banner message about being pinned in local node
- Verified when successfully pinned, show message about number of NFTs that are pinned
- Additional verification notes for [banner messages](https://github.com/brave/brave-browser/issues/28986#issuecomment-1501609557) and [pinning data recursively](https://github.com/brave/brave-browser/issues/29230#issuecomment-1501547620) 

</details>
<details>
<summary>Unpinning - <b>Passed</b></summary>
<br>

- Verified after removing an NFT and running `curl http://127.0.0.1:<api port could be viewed at chrome://ipfs-internal>/api/v0/pin/ls?type=recursive`, shows `{"Keys":{}}` message 
![WindowsTerminal_OQhWi4wCC9](https://user-images.githubusercontent.com/17010094/230879048-9102c354-3c84-40b2-84e7-b9a007058f6f.png)

</details>
<details>
<summary>Pins Validation - <b>Passed</b></summary>
<br>

- Verified deleting `brave_ifps` folder and moving date ahead and restarting the browser restores `brave_ipfs` folder again
- Verified resetting device date back to current date after restart starts to pin the NFT's again.
- Running `curl http://127.0.0.1:<api port could be viewed at chrome://ipfs-internal>/api/v0/pin/ls?type=recursive` continues to show the pinned NFT details

</details>
<details>
<summary>Disable feature - <b>Passed</b></summary>
<br>

- Verified disabling `Automatically pin NFTs` setting and reloading the NFT tab shows the onboarding banner message
- Verified manually deleting the NFT's from visible asset list also removes the onboarding banner message

</details>
<details>
<summary>Cleanup - <b>Passed</b></summary>
<br>

- Verified disabling `Automatically pin NFTs` setting, a new setting for `Clear pinned NFTs` is shown
- Verified clicking that clears the NFTs pinned state and shows onboarding banner message
- Encountered [#29553](https://github.com/brave/brave-browser/issues/29553) & [#29554](https://github.com/brave/brave-browser/issues/29554)

</details>
<details>
<summary>Local node behaviour - <b>Passed</b></summary>
<br>

- Verified when user click on `Get started with IPFS` from interstitial page, IPFS local node is installed and started.

</details>
<details>
<summary>Error handling - <b>Passed</b></summary>
<br>

- Verified if NFT's `content-type` is not of the format `image/*`, NFT pinning fails. Verified as part of [brave-browser#28775 (comment)](https://github.com/brave/brave-browser/issues/28775#issuecomment-1475924572)
- Verified due to network issues NFT pinning fails, it starts the pinning process again when browser is restarted

</details>
</details>

---------------------

**Verification passed on**

Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (arm64)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | macOS Version 13.0 (Build 22A380)

<details>
<summary>Verified steps from issue description</summary>
<br>

<details>
<summary>Enabling the feature - <b>Passed</b></summary>
<br>

- Verified `brave://flags/#enable-nft-pinning` is set to `Default` 
- Verified adding an NFT to visible asset list, automatically shows the NFT pinning banner 
- Verified clicking on `Learn more` on the banner loads interstitial page `brave://wallet/crypto/local-ipfs-node`
- Verified clicking on `Check which NFT's of mine can be pinned` loads second interstitial page `brave://wallet/crypto/inspect-nfts`
- Verified clicking on `Keep my NFTs always online` starts IPFS on localhost and start pinning the available NFT's
- Verified when `Keep my NFTs always online` is selected, setting `Automatically pin NFT's` is enabled, default is disabled

</details>
<details>
<summary>Pinning - <b>Passed</b></summary>
<br>

- Verified able to pin NFTs
- Verified when pinning is in process, shows message banner message about being pinned in local node
- Verified when successfully pinned, show message about number of NFTs that are pinned
- Additional verification notes for [banner messages](https://github.com/brave/brave-browser/issues/28986#issuecomment-1501609557) and [pinning data recursively](https://github.com/brave/brave-browser/issues/29230#issuecomment-1501547620) 

</details>
<details>
<summary>Unpinning - <b>Passed</b></summary>
<br>

- Verified after removing an NFT and running `curl http://127.0.0.1:<api port could be viewed at chrome://ipfs-internal>/api/v0/pin/ls?type=recursive`, shows `{"Keys":{}}` message 
![image](https://user-images.githubusercontent.com/17010094/230878175-f75e8509-b87e-4259-92dd-84ec8b02dac2.png)
</details>
<details>
<summary>Pins Validation - <b>Passed</b></summary>
<br>

- Verified deleting `brave_ifps` folder and moving date ahead and restarting the browser restores `brave_ipfs` folder again
- Verified resetting device date back to current date after restart starts to pin the NFT's again.
- Running `curl http://127.0.0.1:<api port could be viewed at chrome://ipfs-internal>/api/v0/pin/ls?type=recursive` continues to show the pinned NFT details

</details>
<details>
<summary>Disable feature - <b>Passed</b></summary>
<br>

- Verified disabling `Automatically pin NFTs` setting and reloading the NFT tab shows the onboarding banner message
- Verified manually deleting the NFT's from visible asset list also removes the onboarding banner message

</details>
<details>
<summary>Cleanup - <b>Passed</b></summary>
<br>

- Verified disabling `Automatically pin NFTs` setting, a new setting for `Clear pinned NFTs` is shown
- Verified clicking that clears the NFTs pinned state and shows onboarding banner message
- Encountered [#29553](https://github.com/brave/brave-browser/issues/29553) & [#29554](https://github.com/brave/brave-browser/issues/29554)

</details>
<details>
<summary>Local node behaviour - <b>Passed</b></summary>
<br>

- Verified when user click on `Get started with IPFS` from interstitial page, IPFS local node is installed and started.

</details>
<details>
<summary>Error handling - <b>Passed</b></summary>
<br>

- Verified if NFT's `content-type` is not of the format `image/*`, NFT pinning fails. Verified as part of [brave-browser#28775 (comment)](https://github.com/brave/brave-browser/issues/28775#issuecomment-1475924572)
- Verified due to network issues NFT pinning fails, it starts the pinning process again when browser is restarted

</details>
</details>
