### ISSUE TITLE
Investigate crash with MojoIpcz feature enabled

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#29021]
## Description 
In `cr112` they enabled MojoIpcz feature which causes crash on startup. We need to investigate the exact reason and make it work with feature enabled.

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4451e6c
2023-03-13 09:38:53.829 13470-13470 DEBUG                   pid-13470                            A      x0  0000000004451e60  x1  0000000000000001  x2  0000000000000000  x3  0000007fd8b23b68
2023-03-13 09:38:53.829 13470-13470 DEBUG                   pid-13470                            A      x4  0000006a049643c0  x5  0000000000000000  x6  0000006ddbb662d4  x7  0000007fd8b23f40
2023-03-13 09:38:53.829 13470-13470 DEBUG                   pid-13470                            A      x8  0000000000000028  x9  0000006a018ee900  x10 0000006ddbb41d68  x11 0000000000000000
2023-03-13 09:38:53.829 13470-13470 DEBUG                   pid-13470                            A      x12 0000000000001f20  x13 0000007fd8b22910  x14 0000000000000008  x15 00000000ebad6a89
2023-03-13 09:38:53.829 13470-13470 DEBUG                   pid-13470                            A      x16 0000000000000001  x17 000000711413c42c  x18 000000711d318000  x19 0000000004451e60
2023-03-13 09:38:53.829 13470-13470 DEBUG                   pid-13470                            A      x20 0000000004451e60  x21 0000000000000001  x22 0000000000000001  x23 0000000000000001
2023-03-13 09:38:53.829 13470-13470 DEBUG                   pid-13470                            A      x24 0000006a049643c0  x25 0000006a04966c80  x26 0000000004451e60  x27 0000000000000001
2023-03-13 09:38:53.829 13470-13470 DEBUG                   pid-13470                            A      x28 0000006dd993d6b3  x29 0000007fd8b23b40
2023-03-13 09:38:53.829 13470-13470 DEBUG                   pid-13470                            A      lr  0000006ddbb70d60  sp  0000007fd8b23b40  pc  0000006ddbb409a4  pst 0000000060000000
Stack Trace:
  RELADDR   FUNCTION                                                                          FILE:LINE
  v------>  ipcz::APIObject::object_type() const                                              ../../third_party/ipcz/src/ipcz/api_object.h:32:43
  v------>  ipcz::APIObjectImpl<ipcz::Box, (ipcz::APIObject::ObjectType)2>::FromObject(ipcz::APIObject*)  ../../third_party/ipcz/src/ipcz/api_object.h:78:27
  v------>  ipcz::APIObjectImpl<ipcz::Box, (ipcz::APIObject::ObjectType)2>::FromHandle(unsigned long)  ../../third_party/ipcz/src/ipcz/api_object.h:85:12
  v------>  ipcz::APIObjectImpl<ipcz::Box, (ipcz::APIObject::ObjectType)2>::TakeFromHandle(unsigned long)  ../../third_party/ipcz/src/ipcz/api_object.h:90:21
  00000000026629a4  Unbox                                                                             ../../third_party/ipcz/src/api.cc:374:30
  0000000002692d5c  mojo::core::ipcz_driver::ObjectBase::PeekBox(unsigned long)                       ../../mojo/core/ipcz_driver/object.cc:54:3
  0000000002687444  mojo::core::ipcz_driver::Object<mojo::core::ipcz_driver::DataPipe>::FromBox(unsigned long)  ../../mojo/core/ipcz_driver/object.h:171:57
  0000000002691710  mojo::core::ipcz_driver::MojoTrap::AddTrigger(unsigned long, unsigned int, unsigned int, unsigned long)  ../../mojo/core/ipcz_driver/mojo_trap.cc:205:21
  v------>  mojo::SimpleWatcher::Context::Create(base::WeakPtr<mojo::SimpleWatcher>, scoped_refptr<base::SequencedTaskRunner>, mojo::TrapHandle, mojo::Handle, unsigned int, unsigned int, int, unsigned int*, char const*)  ../../mojo/public/cpp/system/simple_watcher.cc:45:15
  0000000004966de0  mojo::SimpleWatcher::Watch(mojo::Handle, unsigned int, unsigned int, base::RepeatingCallback<void (unsigned int, mojo::HandleSignalsState const&)>)  ../../mojo/public/cpp/system/simple_watcher.cc:152:14
  0000000002fcb5ec  mojo::SimpleWatcher::Watch(mojo::Handle, unsigned int, base::RepeatingCallback<void (unsigned int)>)  ../../mojo/public/cpp/system/simple_watcher.h:137:12
  v------>  mojo::android::(anonymous namespace)::WatcherImpl::Start(_JNIEnv*, base::android::JavaParamRef<_jobject*> const&, long, int)  ../../mojo/public/java/system/watcher_impl.cc:45:18
  v------>  mojo::android::JNI_WatcherImpl_Start(_JNIEnv*, base::android::JavaParamRef<_jobject*> const&, long, long, int)  ../../mojo/public/java/system/watcher_impl.cc:90:19
  00000000042f9a48  Java_J_N_MOmBVeTt                                                                 gen/jni_headers/mojo/public/java/system/system_impl_java_jni_headers/WatcherImpl_jni.h:65:10
```

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
For QA: generally it should be enough to check if browser doesn't crash on start on version 1.52.15 or higher

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.51.84 x64 Beta build
- Verified steps from [#29021 (comment)](https://github.com/brave/brave-browser/issues/29021#issuecomment-1494950215)
- Verified no crash on a clean install or on upgrade
- Verified no crash when enabling Brave News via NTP 
- Verified no crash when enabling Brave news via settings
- Verified no crash when scrolling through Brave News 
- Verified no crash when loading an article from Brave News
- Verified no crash when opening Brave Wallet
- Verified no crash when using Brave Wallet
- Verified no crash when connecting to a Dapp using Brave Wallet
- Verified no crash when disabling/enabling Shields on a web page
- Verified no crash when changing shields settings on a page 
- Verified no crash when changing global shields settings and visiting a new page
----------------------------
Verification passed on Lenovo Tab with Android 12 running 1.51.84 x64 Beta build
- Verified steps from [#29021 (comment)](https://github.com/brave/brave-browser/issues/29021#issuecomment-1494950215)
- Verified no crash on a clean install or on upgrade
- Verified no crash when enabling Brave News via NTP 
- Verified no crash when enabling Brave news via settings
- Verified no crash when scrolling through Brave News 
- Verified no crash when loading an article from Brave News
- Verified no crash when opening Brave Wallet
- Verified no crash when using Brave Wallet
- Verified no crash when connecting to a Dapp using Brave Wallet
- Verified no crash when disabling/enabling Shields on a web page
- Verified no crash when changing shields settings on a page 
- Verified no crash when changing global shields settings and visiting a new page


### Note: Playlist flag is only available on nightly as of now and not in Beta so that check is skipped for Beta
