### ISSUE TITLE
Brave always crashes when switching/closing a floated DevTools window

### ISSUE THREAD

**Issue by mickeyjohn** [brave/brave-browser#29057]
## Description 
Brave crashes when closing DevTools windows when switching between windows docking modes or closing a floated DevTools windows. 

## Steps to Reproduce
   1. Within a tab, Press F12 to open the DevTools windows
   2. Click on 'Undock into a separated window' to open the DevTools as a separated window
   3. Click on the Close (x) to close the DevTools or click on any button within Dock side panel (after clicking on the there dots menu on the right corner)
   4. Brave crashes and causes every current apps and logs out of Ubuntu. To continue using, It requires to login Ubuntu again.
    
## Expected result:
Should never crash on these normal operations.

## Reproduces how often: 
All the time. I could not use Brave for Web Development because of this.

## Brave version
Brave: 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)
Revision: c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS: Linux - Ubuntu 22.04 LTS

Is there any work-around to avoid this? Thanks a lot.

**Comment by DocteurFlashbios** [comment]
I have similar issues since months, currently on Version 1.57.62 Chromium: 116.0.5845.180(Official Build) Arch Linux (64-bit) and found that it crashes better (ever) in private mode... (don't know how related)

Found several similar issues, all closed as "dupplicates", but I think this has never been fixed.
https://github.com/brave/brave-browser/issues/20971
https://github.com/brave/brave-browser/issues/21154

are these related ?
https://github.com/brave/brave-browser/issues/32686
https://github.com/brave/brave-browser/issues/32031
https://bugs.chromium.org/p/chromium/issues/detail?id=1470877
have no idea...

I'm considering to abandon Brave for developpements :(

**Comment by iefremov** [comment]
fixed upstream https://issues.chromium.org/issues/40068985
