### ISSUE TITLE
Add android_deps libraries to the license checker

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#29106]
`brave/third_party/android_deps/libs/*` contains third-party libraries that need to be added to the license checker script so that they are included in `brave://credits`.

**Comment by vlad-hoff** [comment]
Verified, the issue is not reproducible in build 1.51.x.

------------------

```
Device/OS: Pixel 6 [oriole-user 13 TQ2A.230405.003.E1 release-keys]
Brave build: 1.51.105 [Beta]
```

Screenshot/Screencast:

|1|2|3|
|-|-|-|
| ![1](https://user-images.githubusercontent.com/128532965/234710720-ee1b1c45-81e2-49e8-a886-08a741896fae.png) | ![2](https://user-images.githubusercontent.com/128532965/234710761-6785b771-c754-42ab-98f0-d9976dc9328a.png) | ![3](https://user-images.githubusercontent.com/128532965/234710775-b34d27b8-8ce6-4a37-a0db-9d8a12da8c0a.png) |
