### ISSUE TITLE
Brave only syncs TYPED URL’s between devices.

### ISSUE THREAD

**Issue by egvandell** [brave/brave-browser#29285]
Full description here:

https://community.brave.com/t/is-there-anyway-to-sync-all-history-between-devices/433073

**Comment by bsclifton** [comment]
Hi @egvandell - this is a known limitation

There is a flag you can enable  on Android and Desktop:
brave://flags/#brave-sync-send-all-history

This should sync all of the history items. Can you give this a try please?

**Comment by bsclifton** [comment]
cc: @AlexeyBarabash - not sure if we plan to expose this setting on the sync page?

**Comment by egvandell** [comment]
I don't use Android, need iOS support.  Also, would rather wait for a RTM / full release.

**Comment by egvandell** [comment]
So I'm assuming this feature is DOA?

**Comment by AlexeyBarabash** [comment]
> not sure if we plan to expose this setting on the sync page?

@bsclifton 
I think, no. I enabled this flag for myself since it apepared in Nightly - the number of objects in my TypedUrls section is already > 10k, server limit is 50k. Another reason is that Chromium has work in progress on the [HistorySyncBridge](https://source.chromium.org/chromium/chromium/src/+/main:components/history/core/browser/sync/history_sync_bridge.h;drc=8ce391bed5ee336e59ccd87b8869760c30e2aad7;bpv=1;bpt=1;l=31?gsn=HistorySyncBridge&gs=kythe%3A%2F%2Fchromium.googlesource.com%2Fchromium%2Fsrc%3Flang%3Dc%252B%252B%3Fpath%3Dcomponents%2Fhistory%2Fcore%2Fbrowser%2Fsync%2Fhistory_sync_bridge.h%23HistorySyncBridge%253Ahistory%2523c%2523j0IXYBaJT%25245&gs=kythe%3A%2F%2Fchromium.googlesource.com%2Fchromium%2Fsrc%3Flang%3Dc%252B%252B%3Fpath%3Dcomponents%2Fhistory%2Fcore%2Fbrowser%2Fsync%2Fhistory_sync_bridge.h%23HistorySyncBridge%253Ahistory%2523c%2523iePlX0H4eRd) 
so eventually this will be inherited.

**Comment by bsclifton** [comment]
More history is now synced - not just typed URLs. This should be fixed

Worth noting if there are too many, it can cause problems where commit to sync chain fails. See https://github.com/brave/brave-browser/issues/35042
