### ISSUE TITLE
Implement `Brave.Rewards.TipsSent` P3A question

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29302]
## Description

If you have Brave Rewards enabled with a custodial account connected, and you made at least one tip, how many tips did you make in the past month?

0. 1 tip
1. 2-3 tips
2. 4+ tips

**Comment by DJAndries** [comment]
edited description and title above

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.52.85 Chromium: 113.0.5672.63 (Official Build) beta (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 10 Version 21H2 (Build 19044.2846)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk_1.52.112`


### Brave.Rewards.TipsSent

<details>
<summary>Metrics not shown case_PASSED</summary>

1. Clean profile 1.52.x
2. Open brave://local-state file
3. Look for the metrics `Brave.Rewards.TipsSent`
4. Confirmed that the metrics is not shown in a clean profile 
![image](https://user-images.githubusercontent.com/38657976/236123984-3e962ace-1aef-448a-a393-13e427d40a0f.png)


</details>

<details>
<summary>Brave.Rewards.TipsSent = 0_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards and connect to a custodian
3. Open a verified pubs laurenwags.github.io
4. Send a one-time tip to a pubs
5. Open brave://local-state file
6. Looks for the metrics `Brave.Rewards.TipsSent`
7. Confirmed that the metrics `Brave.Rewards.TipsSent` is displayed with the response value `0` as expected

Tip sent | brave://local-state
----------|-------------------
![image](https://user-images.githubusercontent.com/38657976/236127277-98736549-b614-4977-8940-354472bff8d8.png) | ![image](https://user-images.githubusercontent.com/38657976/236127220-0ca7bbde-b139-4a75-b8d7-ea12ef836a20.png)

</details>

<details>
<summary>Brave.Rewards.TipsSent = 1_PASSED(4 -PASSED)</summary>

<details>
<summary>Case 1: Sent two one-time tips_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards and connect to a custodian
3. Open a verified pubs laurenwags.github.io
4. Send two one-time tips to a pubs
5. Open brave://local-state file
6. Looks for the metrics `Brave.Rewards.TipsSent`
7. Confirmed that the metrics `Brave.Rewards.TipsSent` is displayed with the response value `1` as expected

Tip sent | brave://local-state
----------|-------------------
![image](https://user-images.githubusercontent.com/38657976/236127857-050b987f-a69e-4aae-aa52-cbf46a11b125.png) | ![image](https://user-images.githubusercontent.com/38657976/236127818-d6c4ff41-b966-4f8f-87ee-f55755f25365.png)


</details>

<details>
<summary>Case 2: Sent three one-time tips_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards and connect to a custodian
3. Open a verified pubs laurenwags.github.io
4. Send three one-time tips to a pubs
5. Open brave://local-state file
6. Looks for the metrics `Brave.Rewards.TipsSent`
7. Confirmed that the metrics `Brave.Rewards.TipsSent` is displayed with the response value `1` as expected

Tip sent | brave://local-state
----------|-------------------
![image](https://user-images.githubusercontent.com/38657976/236128092-ae340276-b873-4bf5-936f-9d9bec133a6f.png) | ![image](https://user-images.githubusercontent.com/38657976/236128258-a2386d03-8699-4e99-a6a8-472471fea4f3.png)


</details>

<details>
<summary>Case 3: Sent 1 - one-time tip and 1 - monthy tip_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards and connect to a custodian
3. Open a verified pubs laurenwags.github.io
4. Send 1 one-time tip and 1 monthly tip to a pubs
5. Open brave://local-state file
6. Looks for the metrics `Brave.Rewards.TipsSent`
7. Confirmed that the metrics `Brave.Rewards.TipsSent` is displayed with the response value `1` as expected

Tip sent | brave://local-state
----------|-------------------
![image](https://user-images.githubusercontent.com/38657976/236130359-7c31abe5-c1bd-4314-8b3e-f1f31307ec68.png) | ![image](https://user-images.githubusercontent.com/38657976/236130535-f0b6cf2e-97ae-40f1-936c-63e65aa7e028.png)


</details>

<details>
<summary>Case 4: Sent 2 - one-time tip and 1 - monthy tip_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards and connect to a custodian
3. Open a verified pubs laurenwags.github.io
4. Send 2 one-time tip and 1 monthly tip to a pubs
5. Open brave://local-state file
6. Looks for the metrics `Brave.Rewards.TipsSent`
7. Confirmed that the metrics `Brave.Rewards.TipsSent` is displayed with the response value `1` as expected

Tip sent | brave://local-state
----------|-------------------
![image](https://user-images.githubusercontent.com/38657976/236131133-babb9476-9103-44f9-9368-0dc165e48d7e.png) | ![image](https://user-images.githubusercontent.com/38657976/236131175-f3f98ab2-64d1-4096-850c-9c98b21c0d9b.png)

</details>
</details>

<details>
<summary>Brave.Rewards.TipsSent = 2 (1-FAILED, 4 PASSED)</summary>

<details>
<summary>Case 1: Sent 2 - one-time tip and 2 - monthy tip_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards and connect to a custodian
3. Open a verified pubs laurenwags.github.io
4. Send 2 one-time tip and 2 monthly tip to a pubs
5. Open brave://local-state file
6. Looks for the metrics `Brave.Rewards.TipsSent`
7. Confirmed that the metrics `Brave.Rewards.TipsSent` is displayed with the response value `2` as expected

Tip sent | brave://local-state
----------|-------------------
![image](https://user-images.githubusercontent.com/38657976/236156552-7855acfa-b3b0-447d-931a-534f3466346b.png) | ![image](https://user-images.githubusercontent.com/38657976/236156686-181cac6d-1359-42a2-bece-abc7cfd980aa.png)


</details>

<details>
<summary>Case 2: Sent 3 - one-time tip and 1 - monthy tip_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards and connect to a custodian
3. Open a verified pubs laurenwags.github.io
4. Send 3 one-time tip and 1 monthly tip to a pubs
5. Open brave://local-state file
6. Looks for the metrics `Brave.Rewards.TipsSent`
7. Confirmed that the metrics `Brave.Rewards.TipsSent` is displayed with the response value `2` as expected

Tip sent | brave://local-state
----------|-------------------
![image](https://user-images.githubusercontent.com/38657976/236158123-a1382a2d-5112-4642-b7e7-5d09272c7c69.png) | ![image](https://user-images.githubusercontent.com/38657976/236158208-8cbd40e5-c6ad-4902-8740-0f366cc06829.png)


</details>

<details>
<summary>Case 3: Sent 3 - one-time tip and 2 - monthy tip_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards and connect to a custodian
3. Open a verified pubs laurenwags.github.io
4. Send 3 one-time tip and 2 monthly tip to a pubs
5. Open brave://local-state file
6. Looks for the metrics `Brave.Rewards.TipsSent`
7. Confirmed that the metrics `Brave.Rewards.TipsSent` is displayed with the response value `2` as expected

Tip sent | brave://local-state
----------|-------------------
![image](https://user-images.githubusercontent.com/38657976/236162242-fe863384-7480-4e02-b9d9-65be36e1982d.png) | ![image](https://user-images.githubusercontent.com/38657976/236162287-20f06dc2-864f-4b9c-b866-d215b8f8bfff.png)



</details>

<details>
<summary>Case 4: Sent 1 - one-time tip and 3 - monthy tip_FAILED_#30132</summary>

(**NOTE**: If we send 3 monthly tips, 3 one-time tips are sent automatically which is bug, due to this unable to test this case, this will be retested once the issue # is fixed)

1. Clean profile 1.52.x
2. Enable rewards and connect to a custodian
3. Open a verified pubs laurenwags.github.io
4. Send 3 one-time tip and 2 monthly tip to a pubs
5. Open brave://local-state file
6. Looks for the metrics `Brave.Rewards.TipsSent`
7. Confirmed that the metrics `Brave.Rewards.TipsSent` is displayed with the response value `2` as expected

Tip sent | brave://local-state
----------|-------------------

</details>

<details>
<summary>Case 5: Sent 3 - one-time tip and 3 - monthy tip_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards and connect to a custodian
3. Open a verified pubs laurenwags.github.io
4. Send 3 one-time tip and 3 monthly tip to a pubs
5. Open brave://local-state file
6. Looks for the metrics `Brave.Rewards.TipsSent`
7. Confirmed that the metrics `Brave.Rewards.TipsSent` is displayed with the response value `2` as expected

Tip sent | brave://local-state
----------|-------------------
![image](https://user-images.githubusercontent.com/38657976/236159541-f1ff8fdb-d769-4c3d-9626-21b1a5fb8334.png) | ![image](https://user-images.githubusercontent.com/38657976/236159631-74127f73-fd40-49c3-83f6-46451e21f622.png)

</details>

</details>


### Brave.Rewards.AutoContributionsState.3

<details>
<summary>Metrics not shown case_PASSED</summary>

1. Clean profile 1.52.x
8. Open brave://local-state file
9. Look for the metrics `Brave.Rewards.AutoContributionsState.3`
10. Confirmed that the metrics is not shown in a clean profile 
![image](https://user-images.githubusercontent.com/38657976/236124084-e0625739-a557-44fb-a642-f015639b432c.png)

</details>

<details>
<summary>Brave.Rewards.AutoContributionsState.3 = 1_PASSED</summary>

1. Clean profile 1.52.x
2. Open brave://local-state file
3. Enable rewards
4. Look for the metrics `Brave.Rewards.AutoContributionsState.3`
11. Confirmed that the metrics is not shown 
12. Connect to a custodian
13. Reload the brave://local-state file
14. Confirmed that the metrics `Brave.Rewards.AutoContributionsState.3` is displayed with the response value `1`

AC switch ON be default | brave://local-state
----------------------------|--------------------
![image](https://user-images.githubusercontent.com/38657976/236125385-420444bb-d9aa-4870-8a9a-b39b7c215919.png) | ![image](https://user-images.githubusercontent.com/38657976/236125243-2372a12e-7340-4ef2-bd0c-895cb7166a3b.png)

</details>

<details>
<summary>Brave.Rewards.AutoContributionsState.3 = 0_PASSED</summary>

1. Clean profile 1.52.x
2. Open brave://local-state file
3. Enable rewards
4. Look for the metrics `Brave.Rewards.AutoContributionsState.3`
5. Confirmed that the metrics is not shown 
6. Connect to a custodian
7. Turn OFF the AC switch
8. Reload the brave://local-state file
15. Confirmed that the metrics `Brave.Rewards.AutoContributionsState.3` is displayed with the response value `0`

AC switch turned OFF | brave://local-state
------------------------|--------------------
![image](https://user-images.githubusercontent.com/38657976/236125509-e95b7bb6-9de3-4fb8-a316-983d63adbfcb.png) | ![image](https://user-images.githubusercontent.com/38657976/236125572-84869a64-a314-45d6-ae5d-7713a57a364f.png)


</details>

---------------

### Regression Testing 

Ensure Brave.Rewards.TipsState.2 and Brave.Rewards.AutoContributionsState.2 no longer exist. Regression testing of Brave.Rewards.AdsState.2 is recommended.

- Confirmed that the metrics `Brave.Rewards.TipsState.2` and `Brave.Rewards.AutoContributionsState.2` no longer exist in the brave://local-state file.
- Done regression testing on the metrcs `Brave.Rewards.AdsState.2` and logged https://github.com/brave/brave-browser/issues/30134
