### ISSUE TITLE
Improve back button behaviour on block explorer

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#29421]
## Description 
If you press back after transaction info is open on block explorer from the wallet, the browser closes.

## Steps to reproduce 

   1. Make a tx.
   2. Open tx info.
   3. Click Back button.

## Actual result 
The browser closes

## Expected result
It would be cool to bring the wallet Activity back.

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.52.84  x64 build
- Verified steps from [brave/brave-core#18018](https://github.com/brave/brave-core/pull/18018)
- Verified selecting back button from transaction details on block explorer, navigates back to Wallet rather than going back to browser tab
- Encountered [#30198](https://github.com/brave/brave-browser/issues/30198)

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/236830207-333922aa-95e4-4736-b0e5-5674f1c97dd7.mp4> | <video src=https://user-images.githubusercontent.com/17010094/236830224-0ff77b05-a353-47be-93e3-99b36f63af21.mp4>
