### ISSUE TITLE
unable to exclude sites from the a-c table

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2943]
## Description 

We're still getting reports from the community that even after https://github.com/brave/brave-browser/issues/1693 being released in `0.58.21` which was the `hotfx 3`, users are still having issues excluding websites from the a-c.

## Steps to Reproduce

N/A... We currently don't really have any STR. We should try working with some users that are experiencing this to see if we can either get their profiles or see if they're receiving an errors in the browser console.

## Actual result:

Users can't exclude websites from the `a-c` table under `Rewards`.

## Expected result:

Users should be able to exclude publishers from the `a-c` table under `Rewards`

## Reproduces how often: 

I'm not sure as we don't really have STR yet.

## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?

I'm not sure as we don't really have STR yet. We'll need more information from the users that are still experiencing this issue.

### Additional Information

CCing @brave/legacy_qa @NejcZdovc

**Comment by kjozwiak** [comment]
We fixed one of the cases in https://github.com/brave/brave-browser/issues/1693 but it appears that some users are still experiencing this issue.

**Comment by glawrence** [comment]
I have "Version 0.58.21 Chromium 71.0.3578.98 (Official Build) (64-bit)" on "mac OS Mojave 10.14.2" and still see this problem. However some sites I can exclude, others I can't, it seems that the recently added ones can be removed, not older ones. Also my "Next contribution date" is still on 18/11/2018, which suggests another problem

**Comment by GeetaSarvadnya** [comment]
1+https://community.brave.com/t/auto-contribute-bat-issues/42406/2

**Comment by glawrence** [comment]
No, nothing

**Comment by MrRobboto** [comment]
@kjozwiak 

To provide what I'm experiencing:

I'm noticing the same behavior people are reporting still happening in 0.58.21. After messing around with it though, I see now the behavior is latency, not complete failure.

If you just click around, it looks like nothing is happening but if you wait a few seconds you'll see it works. There's just very bad latency and no spinner to show the user something is happening in the background.

I have no console errors and consistently I can hit the "X" next to these and it works - but it takes a varying amount of time to work. Some sites it's instant, some sites it takes nearly 10 seconds to work. It's averaging around 3-4 seconds for me on ~100mbps up/down.

Hope this helps...

**Comment by scmart** [comment]
@kjozwiak I also see the latency issue, but that is seperate from the issue of not being able to exclude most sites, or having sites show up twice.

**Comment by LaurenWags** [comment]
I wonder if sites showing up twice is due to this issue https://github.com/brave/brave-browser/issues/2911

**Comment by MrRobboto** [comment]
@scmart is there a reason you believe these are separate?

The latency I'm seeing varies depending on the site you are trying to exclude so my point was that even though people are reporting they "can't exclude some sites", that very well could be the latency issue still and they either aren't waiting long enough to see it or the latency could possibly be so bad for some sites it times out. There are several plausible ways these behaviors could be related to the same issue so with the information we have I would be hesitant to say they are separate...

**Comment by MrRobboto** [comment]
@LaurenWags looks plausible! In any case, the showing up twice does seem unrelated to this issue. I tested the latency issue quite a bit and all the sites I tried to exclude worked perfectly fine and the UI updated perfectly as you'd expect - just really bad latency, 10+ seconds on some, not as bad on others. I could imagine it timing out on some sites causing it to fail completely for some people but I did not observe this...

**Comment by scmart** [comment]
@MrRobboto No, it's separate.  It's not latency, it's just an inefficient sorting algorithm I assume (its all local, no network use).

**Comment by MrRobboto** [comment]
@scmart so your reason is because you have an assumption that there's a sorting algorithm, and it's inefficient? It's just a list sorted by percentage, updating the DOM after excluding is stupid simple. This doesn't seem to be UI or JS related, it's on the C++ side and there is async processing (background) causing latency. I'm not sure if it's local or if any network comm is required, you would need to be more familiar with the code base to know that (I'm guessing you are not).

When they fixed the bug with the JS exclude list not being initialized #1693, you can see they check it now in the new release and then it uses a message callback to invoke code on the C++ side. That then appears to be interacting with a bat ledger. I don't know if that is some local ledger or what but I don't think you would see network comm on that side in chrome dev tools, this is under-the-hood stuff - although I do not know for sure.

So I'll admit I'm speculating and not familiar with the code but I did take the time to look at it and tried to come up with a more reasonable hypothesis for why people are still reporting this. I did the same exact thing myself, I thought it just wasn't working for weeks and finally came around that it's a delay, whether network latency, or just slow async processing (still considered latency btw).

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/9t6m09/how_to_clear_brave_rewards_site_historylist/ee7gcvq

**Comment by MrRobboto** [comment]
@Brave-Matt @kjozwiak 

Just an update on my observations - I was just playing around with this more and stepping through the code when I noticed there does seem to be a problem excluding sub-domains when you have already excluded the domain. This does appear to be separate from the latency issue I'm also seeing.

My guess is this is from the check on publisherKey, instead of url:

`if (!state.excluded.includes(publisherKey)) {
    chrome.send('brave_rewards.excludePublisher', [publisherKey])
    state.excluded.push(publisherKey)
    state = {
        ...state,
        excluded: state.excluded
    }
}`

For instance - I took a look at the exclude list as it's saved to localStorage and I see it's just publisherKey, which is only the main domain. At some point I excluded google.com successfully but in my publisher list I have mail.google.com showing up as just "google.com" (twice, different bug). So that check I'm guessing fails since it only checks the publisher key which looks to be the same across subdomains...

Exclude list in localStorage:
![image](https://user-images.githubusercontent.com/14045888/51347721-dc85ed00-1a6e-11e9-98c1-92ec59c9deb2.png)

Top of my A-C Table:
![image](https://user-images.githubusercontent.com/14045888/51347818-240c7900-1a6f-11e9-9ab7-38d9f6630427.png)

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/cant-remove-sites-from-contribution-list/41375?u=eljuno

**Comment by scmart** [comment]
This seems to be finally working correctly for me.

**Comment by MJae** [comment]
Still experiencing the issue. Using Version 0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified test plan from https://github.com/brave/brave-core/pull/1760
- Encountered https://github.com/brave/brave-browser/issues/3783 while testing
- Verified able to remove sites from auto contribute table and restore them
