### ISSUE TITLE
New uBlock Origin scriptlets need a `scriptletGlobals` object

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#29435]
As of https://github.com/gorhill/uBlock/commit/5c9c87e485308cb2dc6da102a0e20d8fce84124e (and renamed in https://github.com/gorhill/uBlock/commit/b5d78a07bfac8cc9812bb9f0947175e831317997), there is a new `scriptletGlobals` map object used by some scriptlet resources. We'll need this in the Brave scriptlet injection template to ensure full compatibility.

We'll want to uplift this change to Release, since we don't currently support release-channel-specific filters.

**Comment by kjozwiak** [comment]
@brave/qa-team can use https://github.com/brave/brave-core/pull/17858#issuecomment-1496874095 as a template for verifications which basically uses the websites that @antonok-edm mentioned via https://github.com/brave/brave-core/pull/17858#issue-1649984413.

**Comment by kjozwiak** [comment]
The above requires `1.50.114` or higher for `1.50.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk_1.50.114`



Went through the following STR/Cases using the websites mentioned via https://github.com/brave/brave-core/pull/17858#issue-1649984413:

* launched `1.50.114 Chromium: 112.0.5615.49` using `brave.exe --enable-logging=stderr --use-dev-goupdater-url`
* checked `brave://components` and ensured that `Brave Ad Block Resources Library - Version: 1.0.20`
* opened https://yesmangas1.com and ensured that there was no anti-blocking messaging being displayed (leave tab opened)
* closed Brave and removed `mfddibmblmbccpadfndgakiopmmhebop` from `AppData\Local\BraveSoftware\Brave-Browser-Nightly\User Data`
* relaunched using `brave.exe --enable-logging=stderr --use-dev-goupdater-url`
* ensured that https://yesmangas1.com was displaying anti-blocking messages as the `Brave Ad Block Resources Library` was still being downloaded/applied while the browser was launched
* refresh https://yesmangas1.com the anti-blocking messaging should be removed due to `Brave Ad Block Resources Library` being pulled and applied. Double check `brave://components`.

Using the same exact STR/Cases, I went through the following websites and ensured everything was working as expected:

* https://explorecams.com/photos/model/canon-eos-5d-mark-ii
* https://waves4you.com

When I was running through verifications on Nightly, https://cryptoearnfaucet.com/offer/ was under maintenance.

**`Example`** | **`Example`**
----------------|-----------------
![image](https://user-images.githubusercontent.com/38657976/230079878-697cc0b5-5dec-4a26-9c7e-c46a96be6134.png) | ![image](https://user-images.githubusercontent.com/38657976/230080244-c477530d-e59d-4aed-87c4-99cf3ef0e011.png)


**`Example`** | **`Example`**
----------------|-----------------
![image](https://user-images.githubusercontent.com/38657976/230081590-ba3c23f8-f13c-4608-940f-dd3a42e98b11.png) | ![image](https://user-images.githubusercontent.com/38657976/230081483-07458725-9b79-4e49-9f74-d49172a6858d.png)


**`Example`** | **`Example`**
----------------|-----------------
![image](https://user-images.githubusercontent.com/38657976/230082411-0882748e-276f-436a-b46e-e2d9af0c1c42.png) | ![image](https://user-images.githubusercontent.com/38657976/230082254-e9b6aea3-e874-4c60-9ae1-e68126589926.png)
