### ISSUE TITLE
expand static HPKP list

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#2949]
currently we only pin a small set of brave domains (the rationale being that Chrome advised us against pinning sites for which we don't have a point of contact): https://github.com/brave/brave-core/blob/74fb2a164cdd780a8f074597aabae3eecaf45a24/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc#L311

there are more brave domains that should be added to this list, such as go-updater and the various proxy services.

**Comment by diracdeltas** [comment]
to add:
- [ ] ads endpoints
- [ ] publishers.basicattentiontoken.org
- [ ] all the proxy services we run

**Comment by fmarier** [comment]
Here's the current list of hosts that's missing from brave-core and https://github.com/brave/devops/wiki/Mappings-for-proxied-URLs.

These hosts are missing:

- adblock-data.s3.brave.com
- ads-serve.brave.com
- ads-static.brave.com
- brave-core-ext.s3.brave.com
- brave-today-cdn.brave.com
- clients4.brave.com
- componentupdater.brave.com
- crlsets.brave.com
- crxdownload.brave.com
- devtools.brave.com
- extensionupdater.brave.com
- gaia.brave.com
- goerli-infura.brave.com
- kovan-infura.brave.com
- mainnet-infura.brave.com
- mobile-data.s3.brave.com
- p2a.brave.com
- pcdn.brave.com
- redirector.brave.com
- rewards.brave.com
- rinkeby-infura.brave.com
- ropsten-infura.brave.com
- safebrowsing.brave.com
- safebrowsing2.brave.com
- sb-ssl.brave.com
- static.brave.com
- static1.brave.com
- translate.brave.com
- translate-static.brave.com
- variations.brave.com

We probably don't need/want to do these ones:

- community.brave.com
- support.brave.com

but we might want to do these ones:

- together.brave.com
- search.brave.com
- search-dev.brave.com

**Comment by fmarier** [comment]
I remember an incident where Firefox updates broke because of some middleboxes tampering with TLS. The consequences were pretty severe: these users were lost forever because they **could no longer talk to the update server that would deliver the fix**. I couldn't find the original blog post, but I did find was [this discussion](https://bugzilla.mozilla.org/show_bug.cgi?id=1321783) around the roll-out of TLS 1.3 where the [`beConservative` channel flag](https://searchfox.org/mozilla-central/rev/cecdac0aa5733fee515a166b6e31e38cc58abf32/netwerk/protocol/http/nsIHttpChannelInternal.idl#244-249
) was added.

Even today, pinning is in "test mode" only for the Firefox [update](https://searchfox.org/mozilla-central/rev/cecdac0aa5733fee515a166b6e31e38cc58abf32/security/manager/ssl/StaticHPKPins.h#666-667
) and [telemetry](https://searchfox.org/mozilla-central/rev/cecdac0aa5733fee515a166b6e31e38cc58abf32/security/manager/ssl/StaticHPKPins.h#1088) servers due these [middle box concerns](https://bugzilla.mozilla.org/show_bug.cgi?id=1063111#c3) but is enabled for [addon updates](https://searchfox.org/mozilla-central/rev/cecdac0aa5733fee515a166b6e31e38cc58abf32/security/manager/ssl/StaticHPKPins.h#654-655) and [sync accounts](https://searchfox.org/mozilla-central/rev/cecdac0aa5733fee515a166b6e31e38cc58abf32/security/manager/ssl/StaticHPKPins.h#652).

For Brave, the equivalent hosts we should exempt from pinning are:

- `laptop-updates.brave.com` for stats/referrals
- `updates.bravesoftware.com` and `updates-cdn.bravesoftware.com` for Omaha/Sparkle

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` after consulting with @diracdeltas 

cc @rebron @kjozwiak
