### ISSUE TITLE
Connect failed with `Failed to write the VPN config`

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#29512]
## Description 

There was crash when creating os vpn entry with emtpy hostname at `brave_vpn::internal::CreateEntry()`.
With https://github.com/brave/brave-core/pull/17917, crash doesn't happen anymore.
But still have connect failed issue with `Failed to write the VPN config` due to empty hostname.

backtrace links for crash
https://brave.sp.backtrace.io/p/brave/explore?time=month&aggregations=((callstack%2Chead))&fingerprint=329b1f29ef943e90d7cd52d791d30d622dbfba3f61034ca1e359831cb6a6ff65&
https://brave.sp.backtrace.io/p/brave/explore?time=month&aggregations=((callstack%2Chead))&fingerprint=115990e2619af1f1ac806aec7400f1ebb70b68b3f0932a6a8eacb9fa3c70aa24&

## Steps to Reproduce

See https://github.com/brave/brave-browser/issues/28940 for the STR

## Actual result:
Recording from @MadhaviSeelam 

https://user-images.githubusercontent.com/6786187/229956680-3f76bc94-a78f-48b9-9412-8cda3a4755bc.mp4

No more crash but connect failed.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
Reopened as https://github.com/brave/brave-core/pull/17927 doesn't fix this issue.

**Comment by stephendonner** [comment]
<3

**Comment by bsclifton** [comment]
Latest code changes did help narrow it down completely 😄 Huge thanks to @MadhaviSeelam for testing

Here's the behavior we ultimately saw
- Now, the path is set and it'll try to write the config
- Call to `RasSetEntryProperties` was happening... but this generated a 0 byte file at `%APPDATA%\Microsoft\Network\Connections\Pbk\rasphone.pbk`
- The next call (`SetCredentials`) fails because the entry (`BraveVPN-Nightly`) was not there (because the file is empty)

At that point, @MadhaviSeelam checked and the folder is read-only and this is what seems to be preventing the file from being written.
![image](https://user-images.githubusercontent.com/4733304/230651480-58546086-58f3-48b7-a506-2bad5e4feaca.png)

She changed this to NOT be read-only (unticking, clicking `Apply`) but retrying did not work.
I remembered an incident we had before - where deleting the last entry would do something similar and rebooting helped. I asked @MadhaviSeelam to reboot and that fixed the issue.

**Comment by MadhaviSeelam** [comment]
Verified using
```
Brave | 1.52.26 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

#### Confirmed connected to VPN successfully and `Failed to write config` error no longer shown

<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/230654137-23f637df-50c5-4502-8fce-30538b4ad635.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 


## First, attempted to reproduce the issue using `1.49.118`.
<details>

### Steps:
1. installed `1.49.118`
2. launched Brave
3. restarted (to get Griffin changes)
4. purchased, configured, and connected to `Brave VPN`
5. disconnected from `Brave VPN`
6. closed Brave
7. set `rasphone.pbk` in  `C:\Users\steph\AppData\Roaming\Microsoft\Network\Connections\Pbk` to `Read-only`
8. tried to reconnect
9. confirmed I got the `Failed to write the VPN config.` error

No crashes, however.

example | example
---------|---------
![image (1)](https://github.com/brave/brave-browser/assets/387249/8d64e32c-afd9-4ecb-816b-99541fc552ba) | ![image (2)](https://github.com/brave/brave-browser/assets/387249/802f8306-b504-4092-a891-78db3c97b48a)



</details>

## Steps:
<details>

</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.52.93 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```
Installed 1.52.93
launched Brave
connected Brave VPN via existing prod credentials

*Still seeing `Failed to write the VPN config` message 


https://github.com/brave/brave-browser/assets/98358127/5c47daee-5b2d-444b-8866-332921d6ba41

**Comment by MadhaviSeelam** [comment]
QA passing this issue since https://github.com/brave/brave-browser/issues/30291 filed as a follow up.
