### ISSUE TITLE
Alias performance.now to date.now

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#2952]
## Description 
HR-Timers have been implemented in various browsers to provide higher precision timing information for various tasks like script execution and resource fetches. Opening the issue to investigate the fingerprinting risk associated with this API. 

https://w3c.github.io/hr-time/#sec-privacy-security
https://www.w3.org/TR/navigation-timing-2/#security

cc: @snyderp

**Comment by snyderp** [comment]
https://core.ac.uk/download/pdf/80792157.pdf

Possibly of interest

**Comment by tomlowenthal** [comment]
It seems like HR timers don't provide very much value at all. We should probably disable them, or at least substantially decrease their granularity.

**Comment by tomlowenthal** [comment]
Plan of record: disable.

**Comment by pes10k** [comment]
I'm going to close this.  I think HR timers are probably more bad than good for the web platform, but we dont have any serious plans to actually remove these, and FF is re-enabling, and there are definitely much bigger priorities for us privacy / security wise.  Since this is all but guaranteed to never be acted on, im going to pull-the-bandaid-off and just close it
