### ISSUE TITLE
0.00 BAT showing in Rewards panel, even though user is logged in with custodian, and `rewards-internals` shows `Loading...`

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29627]
## Description

Based on investigation with a user on Uphold, this was due to `brave.rewards.external_wallet_type` missing from `Preferences`. 

Now received a report of the same on bitFlyer.

cc: @A-t-s-u-s-h-i

**Comment by kjozwiak** [comment]
The above requires `1.50.121` or higher for `1.50.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.50.121 Chromium: 112.0.5615.138 (Official Build) (64-bit)
-- | --
Revision | 2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}
OS | Windows 10 Version 21H2 (Build 19044.2846)
```
Per https://github.com/brave/brave-core/pull/18105#issue-1671729741, verified the test plan from https://github.com/brave/brave-core/pull/17480#issue-1610700367

<details>
<summary>Uphold - </summary>

<details>
<summary>1. Before enabling rewards - PASSED</summary>

- Confirmed that there is no `Balance info` displayed on the brave://rewards-internals page before enabling the rewards

<img width="1194" alt="Screenshot 2023-04-18 at 12 52 06 PM" src="https://user-images.githubusercontent.com/28145373/232848671-042c0ee3-362e-477f-8670-59ef82e1b1a1.png">

</details>

<details>
<summary>2. After enabling rewards - PASSED</summary>

- Confirmed that after enabling the rewards the vBAT balance is shown on the Rewards Internals page
- Confirmed that the `Connect account` is shown on the brave://rewards settings page, BR panel and rewards NTP widget

Example | Example | Example | Example
---- | ---- | ---- | ----
<img width="1189" alt="Screenshot 2023-04-18 at 12 52 50 PM" src="https://user-images.githubusercontent.com/28145373/232848979-8b30804b-c0d3-4f01-8357-842523889cc1.png"> | <img width="1190" alt="Screenshot 2023-04-18 at 12 52 58 PM" src="https://user-images.githubusercontent.com/28145373/232848982-8dfdb0a8-8fa1-44a7-a0b6-44f01d20f41b.png"> | <img width="1189" alt="Screenshot 2023-04-18 at 12 53 14 PM" src="https://user-images.githubusercontent.com/28145373/232848984-31776439-9c3d-487b-acae-8325415fdf52.png"> | <img width="1189" alt="Screenshot 2023-04-18 at 12 53 20 PM" src="https://user-images.githubusercontent.com/28145373/232848987-4799b087-54e3-4fb8-99cf-080c5cb54fe3.png">

</details>

<details>
<summary>3. After connecting a custodial wallet - PASSED</summary>

- Confirmed that after connecting custodian wallet, both the vBAT/external wallet balance is displayed on the Rewards Internals page
- Confirmed that after connecting custodian wallet, total balance is displayed on the Rewards page, Rewards panel and Rewards NTP widget

Example | Example | Example | Example
---- | ---- | ---- | ----
<img width="1192" alt="Screenshot 2023-04-18 at 12 57 45 PM" src="https://user-images.githubusercontent.com/28145373/232850379-2c25aa63-b67c-4edc-beb1-19ff4d051a3c.png"> | <img width="1191" alt="Screenshot 2023-04-18 at 12 57 56 PM" src="https://user-images.githubusercontent.com/28145373/232850382-b72e11b9-7e13-4b35-942b-6dad1f4b1543.png"> | <img width="1192" alt="Screenshot 2023-04-18 at 12 58 03 PM" src="https://user-images.githubusercontent.com/28145373/232850384-d006f21a-c95d-4898-a2e3-0fab1b3d2240.png"> | <img width="1193" alt="Screenshot 2023-04-18 at 12 58 20 PM" src="https://user-images.githubusercontent.com/28145373/232850386-6c6d25ae-7430-4d90-896c-a446c31d0bcf.png">

</details>

<details>
<summary>4. Logged out state - PASSED</summary>

- Confirmed that in the logged out state, the vBAT balance (zero) is shown only on the Rewards Internals page
- Confirmed that `Logged out UI` is shown on the brave://rewards, BR panel, Rewards NTP and Tipping banner
- Confirmed that `: ( You are currently logged out` text message is shown on the tipping banner
   - Note, tipping banner on Nightly 1.52.x will differ from 1.50.x and 1.51.x, this is because new design for tipping banner was merged to Nightly

Example | Example | Example | Example | Example
---- | ---- | ---- | ---- | ----
<img width="1189" alt="Screenshot 2023-04-18 at 1 00 34 PM" src="https://user-images.githubusercontent.com/28145373/232851122-253fd141-cb36-40e1-b1a4-c81d1cda047d.png"> | <img width="1188" alt="Screenshot 2023-04-18 at 1 00 43 PM" src="https://user-images.githubusercontent.com/28145373/232851125-b885c913-0346-4ed4-b5ab-10f75d2ec242.png"> | <img width="1186" alt="Screenshot 2023-04-18 at 1 00 53 PM" src="https://user-images.githubusercontent.com/28145373/232851129-edf595de-9493-42a8-8c76-0724efe78e42.png"> | <img width="1189" alt="Screenshot 2023-04-18 at 1 01 00 PM" src="https://user-images.githubusercontent.com/28145373/232851133-53606519-d93a-4242-8d75-0a7831249b0b.png"> | <img width="1190" alt="Screenshot 2023-04-18 at 1 01 19 PM" src="https://user-images.githubusercontent.com/28145373/232851137-6ddd4b95-2ff2-4372-be34-c3c199df5346.png">

</details>

<details>
<summary>5. Fail the fetch balance request - PASSED</summary>

- Uphold wallet (pre-req: have Charles Proxy set up to return 500 error for the endpoint (https://api-sandbox.uphold.com/v0/me/cards/*))
- Confirmed that spinner animation is shown for both the Rewards BAT (vBAT) and external wallet balance on brave://rewards-internals page

Example | Example | Example | Example
---- | ---- | ---- | ----
<img width="1190" alt="Screenshot 2023-04-18 at 1 11 00 PM" src="https://user-images.githubusercontent.com/28145373/232854140-a4ed0e3f-6980-4516-a732-aab6ec4adf49.png"> | <img width="1192" alt="Screenshot 2023-04-18 at 1 11 11 PM" src="https://user-images.githubusercontent.com/28145373/232853955-52852e3e-e40c-4223-b4ae-f91e83454e71.png"> | <img width="1189" alt="Screenshot 2023-04-18 at 1 11 22 PM" src="https://user-images.githubusercontent.com/28145373/232853957-bd278ce4-e9d9-4904-8952-4cb5a361fe20.png"> | <img width="1190" alt="Screenshot 2023-04-18 at 1 11 29 PM" src="https://user-images.githubusercontent.com/28145373/232853959-cf427d5a-540f-4ae9-8c99-2cfa593de81e.png">

</details>

<details>
<summary>6. Reset rewards - PASSED</summary>

- Confirmed that after `Reset rewards` the wallet balance info is not displayed on the brave://rewards-internals page

<img width="1196" alt="Screenshot 2023-04-18 at 1 30 39 PM" src="https://user-images.githubusercontent.com/28145373/232857490-95af22c1-d6c5-4689-b0d6-f0ef8a16f90f.png">

</details>

</details>

<details>
<summary>Gemini - </summary>

<details>
<summary>1. Before enabling rewards - PASSED</summary>

- Confirmed that there is no `Balance info` displayed on the brave://rewards-internals page before enabling the rewards

<img width="1257" alt="Screenshot 2023-04-18 at 3 07 40 PM" src="https://user-images.githubusercontent.com/28145373/232880169-c57c8ebe-f431-4776-9a29-4a84ea8e728a.png">

</details>

<details>
<summary>2. After enabling rewards - PASSED</summary>

- Confirmed that after enabling the rewards the vBAT balance is shown on the Rewards Internals page
- Confirmed that the `Connect account` is shown on the brave://rewards settings page, BR panel and rewards NTP widget

Example | Example | Example | Example
---- | ---- | ---- | ----
<img width="1249" alt="Screenshot 2023-04-18 at 3 44 22 PM" src="https://user-images.githubusercontent.com/28145373/232888477-0e1f10a3-388c-4935-bc9f-7e59611dab71.png"> | <img width="1245" alt="Screenshot 2023-04-18 at 3 44 34 PM" src="https://user-images.githubusercontent.com/28145373/232888479-add819b9-c7e0-4890-b60b-706935d10050.png"> | <img width="1250" alt="Screenshot 2023-04-18 at 3 44 41 PM" src="https://user-images.githubusercontent.com/28145373/232888481-994565c6-73a3-4ebb-9462-6ff32c4c2bb8.png"> | <img width="1247" alt="Screenshot 2023-04-18 at 3 44 49 PM" src="https://user-images.githubusercontent.com/28145373/232888483-4afed61f-9a84-4576-ac65-4f55fea33168.png">

</details>

<details>
<summary>3. After connecting a custodial wallet - PASSED</summary>

- Confirmed that after connecting custodian wallet, both the vBAT/external wallet balance is displayed on the Rewards Internals page
- Confirmed that after connecting custodian wallet, total balance is displayed on the Rewards page, Rewards panel and Rewards NTP widget

Example | Example | Example | Example
---- | ---- | ---- | ----
<img width="1248" alt="Screenshot 2023-04-18 at 3 32 37 PM" src="https://user-images.githubusercontent.com/28145373/232885841-f98e08d9-a3e7-44d7-9754-a8682cd33407.png"> | <img width="1249" alt="Screenshot 2023-04-18 at 3 32 52 PM" src="https://user-images.githubusercontent.com/28145373/232885843-80cea07a-fd22-4f18-8953-12004da089f0.png"> | <img width="1253" alt="Screenshot 2023-04-18 at 3 32 59 PM" src="https://user-images.githubusercontent.com/28145373/232885847-fd55f63b-c285-49ea-91a8-0c2cbfe3bb01.png"> | <img width="1252" alt="Screenshot 2023-04-18 at 3 33 17 PM" src="https://user-images.githubusercontent.com/28145373/232885850-547a206a-8487-4a23-b651-46f9e00e070c.png">

</details>

<details>
<summary>4. Logged out state - PASSED</summary>

- Confirmed that in the logged out state, the vBAT balance (zero) is shown only on the Rewards Internals page
- Confirmed that `Logged out UI` is shown on the brave://rewards, BR panel, Rewards NTP and Tipping banner
- Confirmed that `: ( You are currently logged out` text message is shown on the tipping banner
   - Note, tipping banner on Nightly 1.52.x will differ from 1.50.x and 1.51.x, this is because new design for tipping banner was merged to Nightly

Example | Example | Example | Example | Example
---- | ---- | ---- | ---- | ----
<img width="1251" alt="Screenshot 2023-04-18 at 3 37 52 PM" src="https://user-images.githubusercontent.com/28145373/232887303-c590f0cd-ddb3-4bd7-9473-0e749bd7ffbd.png"> | <img width="1250" alt="Screenshot 2023-04-18 at 3 38 04 PM" src="https://user-images.githubusercontent.com/28145373/232887306-5856eeba-8c62-4b51-a33e-be458a52d6f7.png"> | <img width="1252" alt="Screenshot 2023-04-18 at 3 38 16 PM" src="https://user-images.githubusercontent.com/28145373/232887309-ef36f7a9-cd30-49b9-b922-04aa2569a1b2.png"> | <img width="1251" alt="Screenshot 2023-04-18 at 3 39 11 PM" src="https://user-images.githubusercontent.com/28145373/232887311-6d46b4a7-acd6-4eba-b808-ba440566c246.png"> | <img width="1242" alt="Screenshot 2023-04-18 at 3 39 32 PM" src="https://user-images.githubusercontent.com/28145373/232887316-7861065c-51cf-44f7-ad49-50397f00d14c.png">

</details>

<details>
<summary>5. Fail the fetch balance request - PASSED</summary>

- Gemini wallet (pre-req: have Charles Proxy set up to return 500 error for the endpoint (https://api.sandbox.gemini.com/v1/balances))
- Confirmed that spinner animation is shown for both the Rewards BAT (vBAT) and external wallet balance on brave://rewards-internals page

Example | Example | Example | Example
---- | ---- | ---- | ----
<img width="1248" alt="Screenshot 2023-04-18 at 3 41 48 PM" src="https://user-images.githubusercontent.com/28145373/232887930-cda2b0bd-b9f2-4731-bc59-306b7a61fd72.png"> | <img width="1246" alt="Screenshot 2023-04-18 at 3 41 57 PM" src="https://user-images.githubusercontent.com/28145373/232887931-f48e6ff5-dbb0-4b2e-a6cf-bf20aa06bf1e.png"> | <img width="1254" alt="Screenshot 2023-04-18 at 3 42 06 PM" src="https://user-images.githubusercontent.com/28145373/232887933-5429da63-deb6-430e-a386-cc332580c23e.png"> | <img width="1250" alt="Screenshot 2023-04-18 at 3 42 11 PM" src="https://user-images.githubusercontent.com/28145373/232887935-6d87dc17-4ffe-4b1d-9c4c-56a61a887e06.png">

</details>

<details>
<summary>6. Reset rewards - PASSED</summary>

- Confirmed that after `Reset rewards` the wallet balance info is not displayed on the brave://rewards-internals page

<img width="1258" alt="Screenshot 2023-04-18 at 3 43 43 PM" src="https://user-images.githubusercontent.com/28145373/232888239-9bb01980-5cb1-473c-ae83-22c7ff9256a0.png">

</details>

</details>


<details>
<summary>bitFlyer - </summary>

<details>
<summary>1. Before enabling rewards - PASSED</summary>

- Confirmed that there is no `Balance info` displayed on the brave://rewards-internals page before enabling the rewards

<img width="1192" alt="Screenshot 2023-04-18 at 3 56 25 PM" src="https://user-images.githubusercontent.com/28145373/232890942-7fa5a569-cc66-4055-8717-ca3fa887cb48.png">

</details>

<details>
<summary>2. After enabling rewards - PASSED</summary>

- Confirmed that after enabling the rewards the vBAT balance is shown on the Rewards Internals page
- Confirmed that the `Connect account` is shown on the brave://rewards settings page, BR panel and rewards NTP widget

Example | Example | Example | Example
---- | ---- | ---- | ----
<img width="1189" alt="Screenshot 2023-04-18 at 3 57 18 PM" src="https://user-images.githubusercontent.com/28145373/232891240-06908286-3081-45f8-88e9-9877327c520c.png"> | <img width="1190" alt="Screenshot 2023-04-18 at 3 57 26 PM" src="https://user-images.githubusercontent.com/28145373/232891243-2fb79b64-d2e7-4425-9bc1-ee6f1c6620dc.png"> | <img width="1189" alt="Screenshot 2023-04-18 at 3 57 41 PM" src="https://user-images.githubusercontent.com/28145373/232891248-770a63ca-833f-4de1-ba62-20395f4fdacd.png"> | <img width="1195" alt="Screenshot 2023-04-18 at 3 57 48 PM" src="https://user-images.githubusercontent.com/28145373/232891252-b0cae4f2-aa93-44c0-abb5-8a81c34e6c5d.png">

</details>

<details>
<summary>3. After connecting a custodial wallet - PASSED</summary>

- Confirmed that after connecting custodian wallet, both the vBAT/external wallet balance is displayed on the Rewards Internals page
- Confirmed that after connecting custodian wallet, total balance is displayed on the Rewards page, Rewards panel and Rewards NTP widget

Example | Example | Example | Example
---- | ---- | ---- | ----
<img width="1184" alt="Screenshot 2023-04-18 at 3 59 50 PM" src="https://user-images.githubusercontent.com/28145373/232891823-c271bfce-e20f-44a6-b90f-bb175732b4a6.png"> | <img width="1188" alt="Screenshot 2023-04-18 at 4 00 03 PM" src="https://user-images.githubusercontent.com/28145373/232891824-7420f65a-0178-4775-aa73-b94354148517.png"> | <img width="1192" alt="Screenshot 2023-04-18 at 4 00 11 PM" src="https://user-images.githubusercontent.com/28145373/232891827-93e281ad-fb6c-4875-bf89-b164a5552c21.png"> | <img width="1190" alt="Screenshot 2023-04-18 at 4 00 29 PM" src="https://user-images.githubusercontent.com/28145373/232891828-c91fd958-e829-4b69-b17f-cfbd0a70b4d4.png">

</details>

<details>
<summary>4. Logged out state - PASSED</summary>

- Confirmed that in the logged out state, the vBAT balance (zero) is shown only on the Rewards Internals page
- Confirmed that `Logged out UI` is shown on the brave://rewards, BR panel, Rewards NTP and Tipping banner
- Confirmed that `: ( You are currently logged out` text message is shown on the tipping banner
   - Note, tipping banner on Nightly 1.52.x will differ from 1.50.x and 1.51.x, this is because new design for tipping banner was merged to Nightly

Example | Example | Example | Example | Example
---- | ---- | ---- | ---- | ----
<img width="1189" alt="Screenshot 2023-04-18 at 4 10 11 PM" src="https://user-images.githubusercontent.com/28145373/232893866-7609a788-34c1-48e1-8fb7-70ba3b8503e6.png"> | <img width="1190" alt="Screenshot 2023-04-18 at 4 10 23 PM" src="https://user-images.githubusercontent.com/28145373/232893872-5a3205ee-21db-43d1-9cb0-8df3e2c52461.png"> | <img width="1191" alt="Screenshot 2023-04-18 at 4 10 31 PM" src="https://user-images.githubusercontent.com/28145373/232893874-76d06a26-7891-4a6b-b089-6baaf8fb8420.png"> | <img width="1188" alt="Screenshot 2023-04-18 at 4 10 38 PM" src="https://user-images.githubusercontent.com/28145373/232893875-6d20b829-2165-4fa1-bb48-3cebcb41534c.png"> | <img width="1188" alt="Screenshot 2023-04-18 at 4 10 49 PM" src="https://user-images.githubusercontent.com/28145373/232893881-79d454ad-3fa4-47d4-be34-681719a7ad6d.png">

</details>

<details>
<summary>5. Fail the fetch balance request - PASSED</summary>

- bitflyer wallet (pre-req: have Charles Proxy set up to return "500 Internal Server Error" error for the endpoint (https://demo24kiuw4dcyncsy3qlud8u8.azurewebsites.net/api/link/v1/account/inventory)) - note, this differs from Uphold and Gemini sandbox environments where just returning 500 for the response status is enough
- Confirmed that spinner animation is shown for both the Rewards BAT (vBAT) and external wallet balance on brave://rewards-internals page

Example | Example | Example | Example
---- | ---- | ---- | ----
<img width="1186" alt="Screenshot 2023-04-18 at 5 06 53 PM" src="https://user-images.githubusercontent.com/28145373/232905540-c3112e6d-c230-4134-b2fa-534a754fa2e4.png"> | <img width="1182" alt="Screenshot 2023-04-18 at 5 07 29 PM" src="https://user-images.githubusercontent.com/28145373/232905543-68b24937-900d-4faa-abda-fef5f4afbb5f.png"> | <img width="1189" alt="Screenshot 2023-04-18 at 5 07 35 PM" src="https://user-images.githubusercontent.com/28145373/232905546-ffe68ac8-e16a-4379-a6ff-ba0512b72bfe.png"> | <img width="1190" alt="Screenshot 2023-04-18 at 5 07 42 PM" src="https://user-images.githubusercontent.com/28145373/232905549-2e43af1f-0df7-4310-85f0-59a7a7ef7a16.png">

</details>

<details>
<summary>6. Reset rewards - PASSED</summary>

- Confirmed that after `Reset rewards` the wallet balance info is not displayed on the brave://rewards-internals page

<img width="1184" alt="Screenshot 2023-04-18 at 5 09 53 PM" src="https://user-images.githubusercontent.com/28145373/232905798-2ff45b91-2dc7-4cf7-8e53-aeb046ed78e1.png">

</details>

</details>
