### ISSUE TITLE
refactor new tab top sites

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2971]
* Improve drag n drop;
* Simplify top sites logic;
* Fix bad re-ordering while pinning -- sometimes pinning a site makes it jump to the wrong position;
* Fix bookmarking top sites not showing the correct state.

Test Plan:

## Only if you have an existing profile

1. Other areas in NTP such as stats and rewards should not be affected by this change
2. Your current top sites should still be there

## Actual test plan

1.  New sites visited should be added first in the tiles grid. Note that timing for that may vary. 
2. You should be able to re-order tiles by drag and drop
3. Tiles re-ordered should persist position upon browser refresh
4. Pinned tiles can not be moved. Attempts to move sibling tiles should not change the pinned tile position
5. Pinned tiles can not be excluded
6. Tiles excluded should pop up a notification bar on top of the page asking if you want to un-do the operation
7. Un-do a site removal should show back the tile in the first position or the first position next to the pinned site
8. Bookmarking a tile should add a bookmark in the bookmark toolbar. Toggling it should remove the bookmark

**Comment by Brave-Matt** [comment]
I have several Community users reporting that top-sites aren't functioning correctly:
https://community.brave.com/t/cant-remove-some-top-sites-on-brave/92194/26

**Comment by bsclifton** [comment]
Reverted https://github.com/brave/brave-core/pull/4325 with https://github.com/brave/brave-core/pull/4996 because pinned items were lost
(see https://github.com/brave/brave-browser/issues/8781)

Per @cezaraugusto:
> 1. pinned sites were lost because I split storage data in NTP to avoid bugs in unrelated fields such as rewards. The fix for this is to grab current pinned sites data and migrate to the new storage
> 2. the site removal bug Rafael mentioned will be addressed by changing the field name. This is the only part where I kept the same. This is a strong guess since I'm not able to repro

**Comment by bsclifton** [comment]
Potential fix can also include fix for https://github.com/brave/brave-core/pull/4987

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.85 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified using a mix of 1.8.82 (Dev), 1.8.84 (Release), and build above (1.8.85).
* Verified items from description
* Verified items from https://github.com/brave/brave-core/pull/5097

Clean profile:
- Confirmed top site tiles are populated
   - Confirmed new sites are added first in the grid
- Confirmed able to delete tiles
   - Confirmed able to "Undo" delete of a single or all tiles.
- Confirmed able to drag and drop to reorder tiles
   - Confirmed reorder is persisted on browser re-launch
- Confirmed able to pin/unpin tiles
   - Confirmed unable to drag/drop pinned tiles
   - Confirmed unable to exclude pinned tiles
- Confirmed able to bookmark/unbookmark sites from tiles

Upgrade profile:
- Confirmed top site tiles still populated as expected
- Confirmed tiles still in pinned positions as expected
- Issue with bookmark icon (noted below)
- Confirmed other areas (clock, stats, BR widget) are unaffected
- Confirmed able to delete a tile, but issue when tile delete is "Undone" (noted below)
- Pinned sites not duplicated initially, but do get duplicated in a few scenarios (fixed with issue noted below)
- Confirmed able to bookmark/unbookmark sites from tiles on upgraded profile
- Confirmed able to drag and drop to reorder tiles on upgraded profile
   - Confirmed reorder is persisted on browser re-launch for upgraded profile
- Confirmed as I visited sites on the upgraded profile new sites were added to the tiles
   - Confirmed new sites are added first in the grid on upgrade profile
- Confirmed able to pin/unpin tiles on upgraded profile
   - Confirmed unable to drag/drop pinned tiles on upgraded profile
   - Confirmed unable to exclude pinned tiles on upgraded profile

1.7.98:
<img width="1170" alt="1 7 98" src="https://user-images.githubusercontent.com/28145373/80496555-5a55cb00-8937-11ea-84bd-0d61000ca64b.png">

1.8.85:
<img width="1191" alt="1 8 85" src="https://user-images.githubusercontent.com/28145373/80496543-56c24400-8937-11ea-8da4-62b93a2de0f7.png">


- Encountered/logged the following issues:
   - https://github.com/brave/brave-browser/issues/9457 (undo delete issue)
   - https://github.com/brave/brave-browser/issues/9459 (bookmark icon issue)
   - https://github.com/brave/brave-browser/issues/9008 (duplicate pinned sites issue)
