### ISSUE TITLE
Adjust CTA on desktop VPN modal 

### ISSUE THREAD

**Issue by rmcfadden3** [brave/brave-browser#29838]
## Description 
Per [this Slack thread](https://bravesoftware.slack.com/archives/CC5SA8CCB/p1681240830491559), we'd like to adjust the CTA on the desktop VPN modal (currently, this button just says "Buy") to instead say "Start free trial" … or we could just do "Start trial" if "Start free trial" is too many characters.

CC @mattmcalister @vinny-brave @rebron @bsclifton 

## Steps to Reproduce
   1. Open Brave
   2. Click "VPN" pill in address bar
   3. See "Buy" button in this modal

## Expected result:

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.53.52 Chromium: 114.0.5735.26 (Official Build) nightly (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Windows 10 Version 22H2 (Build 19045.2965)

### Steps:
1. installed `1.53.52`
2. launched Brave
3. clicked on the `VPN` button on the browser toolbar

### Confirmed it now reads `Start free trial`, rather than `Buy`

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/2114248f-6686-4421-9bb7-3906f5ef5529) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/8ce0b180-743a-4336-bb1b-56f400ee8296)

**Comment by kjozwiak** [comment]
The above needs to be re-verified due to https://github.com/brave/brave-core/pull/18524 being uplifted into `1.52.x` via https://github.com/brave/brave-core/pull/18573. Used https://github.com/brave/brave-browser/issues/29838#issuecomment-1553989735 as the needed verification on Nightly to uplift into `1.52.x` as per  https://github.com/brave/brave-core/pull/18573#pullrequestreview-1440161121.

**Comment by kjozwiak** [comment]
The above requires `1.52.110` or higher for `1.52.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (64-bit)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Windows 10 Version 22H2 (Build 19045.2965)

### Steps:
1. installed `1.52.112`
2. launched Brave
3. clicked on the `VPN` button in the browser toolbar

### Confirmed the text change of the button label to `Start free trial`, from the stark `Buy`

![image](https://github.com/brave/brave-browser/assets/387249/ca180436-f48c-4231-9445-425f0aeb93a5)
