### ISSUE TITLE
Brave can't open ubuntu.com page

### ISSUE THREAD

**Issue by wooque** [brave/brave-browser#29877]
## Description 

Brave can't open ubuntu.com page. I can see page flashing for a fraction of a second before I get "Can't open this page" error

## Steps to Reproduce

   1. Open ubuntu.com

## Actual result:

Can't open this page error
![20230420_05h00m30s_grim](https://user-images.githubusercontent.com/1936195/233247227-3b3097f3-f93f-4454-846f-f4cb1d7577e4.png)

## Expected result:
Page opens normally 

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.50.121 Chromium: 112.0.5615.138 (Official Build) (64-bit)
-- | --
Revision | 2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? /
- Can you reproduce this issue with the nightly channel? / 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by tocic** [comment]
After the upgrade to Version 1.50.121 Chromium: 112.0.5615.138 I'm getting the same message for GitHub and GitLab too. <kbd>Ctrl</kbd>+<kbd>F5</kbd> helps.

**Comment by pitsi** [comment]
I just got this message when browsing a forum. Then I tested ubuntu.com and gitlab and it happens there as well. Thankfully it does not happen on github. Ctrl + f5 (= forced refresh without using the browser's cache) did not help at all here :(

**Comment by kjozwiak** [comment]
Firstly, I would like to apologies to anyone who's experiencing the above issues and appreciate all the reports and information. It looks like `112.0.5615.138` is causing issues on `Linux` and we suspect it might be due to https://bugs.chromium.org/p/chromium/issues/detail?id=1434194. What usually happens is when we get a chromium bump as per https://chromereleases.googleblog.com/2023/04/stable-channel-update-for-desktop_18.html, we update all our branches and then push the release on the targeted platforms. So for `112.0.5615.138`, both `macOS` & `Windows` were targeted. The update mentions that a `Linux` update will be coming soon. However, when we usually get bumps with zero-day vulnerabilities, we try to update all of our platforms ASAP. So we ended up pushing `112.0.5615.138` on `Linux` as well to help protect our users. However, in hindsight, we probably should have waited.

We're preparing a new update that will basically bump the version from `1.50.121` and revert users to `1.50.119` which was using `112.0.5615.121`. We've received a bunch of confirmations spanning various threads on both reddit and GitHub that reverting to `112.0.5615.121` fixes the issues. We've also took a look at the difference between `112.0.5615.138` & `112.0.5615.121` and see nothing that would cause any issues when reverting. We should have an update available within ~2-3hrs. In the meantime, I would advice `Linux` users not to update to `112.0.5615.138` and wait for the next chromium bump.

We'll also update the various Brave communication channels including reddit and http://community.brave.com to let users know what happened and let them know that an update is on the way that should restore functionality back to normal.

**Comment by wooque** [comment]
@kjozwiak 112.0.5615.165 is already released for Linux, I don't know why they wrote it's coming, I just checked Chrome on my machine and it's on version 112.0.5615.165, There are no crashes there.

**Comment by kjozwiak** [comment]
> @kjozwiak 112.0.5615.165 is already released for Linux, I don't know why they wrote it's coming, I just checked Chrome on my machine and it's on version 112.0.5615.165, There are no crashes there.

Thanks! Just noticed it via https://chromiumdash.appspot.com/releases?platform=Linux. We're preparing an update ASAP.

**Comment by wooque** [comment]
Version 1.50.125 Chromium: 112.0.5615.165 fixed the issue :+1:

**Comment by kjozwiak** [comment]
> Version 1.50.125 Chromium: 112.0.5615.165 fixed the issue 👍

awesome, thanks for the confirmation. Wanted to update the issue but you beat me it  :) So we pushed out `1.50.125 Chromium: 112.0.5615.165` which should fix the issue for everyone. If you were having issues, please let us know if the above release fixed your issue. Can also download the `deb` files manually via https://github.com/brave/brave-browser/releases/tag/v1.50.125.
