### ISSUE TITLE
Absent critical client hints cause some sites to get into infinite loop redirects.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#29875]
When `Allow certain request client hints` feature is turned on some sites end up in an infinite loop redirects because they request critical client hints which we don't send.

STR:
1. Start Brave
2. Navigate to brave://flags
3. Enable `Allow certain request client hints` feature and restart the browser
4. Navigate to one of the symptomatic sites (for example: [this link](https://rsci.app.link/syPp8BMP4yb?_p=c71729c39d0a7af2e11590f8ec) or [this link](https://strava-web.app.link/3p?$3p=e_it&$original_url=https%3A%2F%2Fsupport%2Estrava%2Ecom%2Fhc%2Farticles%2F13013167258381%2DSubscription%2DPricing%2DFAQ%3F%24web%5Fonly%3Dtrue))

**Observe:**
`This page is not working` error is shown with `ERR_TOO_MANY_REDIRECTS`

**Expected result:**
The page loads normally

The issue is caused by the sites expecting client hints (in this case `sec-ch-ua-model` and `sec-ch-ua-platform-version`) to be sent over when they are requested in Critical-CH header. However, Brave currently doesn't send those client hints.

To fix the issue we will be sending those 2 clients hints. The `sec-ch-ua-model` value will always be an empty string.

cc: @pes10k

**Comment by pes10k** [comment]
@mkarolin does this also include the clamped version of the OS version (on platforms where the version number is clamped)?

**Comment by mkarolin** [comment]
@pes10k I don't see that we currently modify OS version info. Which platforms need to be clamped and how?

**Comment by pes10k** [comment]
I know at one point we clamped the MacOS version, and I thought Chrome clamped the windows version too, though if you say that’s not the case I’m sure you’re right. As long as the version number shared in the client header matches exactly the version number shared in User-Agent, that’s perfect.

**Comment by fatphil2001** [comment]
It seems this option is Enabled by default in [Version 1.50.121 Chromium: 112.0.5615.138 (Official Build) (64-bit)](https://brave.com/latest/)

By disabling it I can now access Strava.com links that are used in emails.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
```
- Verified the STR from the description. The issue is Reproducible in `1.50.120`, upgraded the profile to 1.51.109 and ensured that the both links are loaded redirected properly.

**`1.50.120`**

Example | Example
----------|---------
![image](https://user-images.githubusercontent.com/38657976/235478757-f9ddd077-32fc-4265-8462-faebaed6da84.png) | ![image](https://user-images.githubusercontent.com/38657976/235478778-4f764c5c-5a55-4420-a1e4-22fd742544e6.png)

**`1.51.109`**

Example | Example
----------|---------
![image](https://user-images.githubusercontent.com/38657976/235479199-267d5544-239d-4263-a322-b84684540c23.png) | ![image](https://user-images.githubusercontent.com/38657976/235479225-b91c4538-e26c-435a-9d29-0509771a1b7b.png)
