### ISSUE TITLE
Brave SIGILL error on (almost) every webpage since `112.1.50.121`

### ISSUE THREAD

**Issue by moedn** [brave/brave-browser#29887]
## Description 

Did an update last night on version `112.1.50.121` and since then I'm getting the following error on almost every webpage:

![image](https://user-images.githubusercontent.com/45949491/233388316-8f720c3e-bec0-4ac6-b2b0-c276777581b9.png)

found 2 exceptions that work (total coincidence):

- <https://www.linguee.com/>
- a nextcloud form

## Steps to Reproduce

   1. open Brave
   2. try visiting any webpage

## Actual result:

SIGILL error message

## Expected result:

site to show up

## Reproduces how often: 

every time (except for the above mentioned exceptions)

## Brave version (info found on brave://version)

 `112.1.50.121`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
  > no options to disable shields since the page is not loaded in the first place
- Does the issue resolve itself when disabling Brave Rewards?
  > nope
- Is the issue reproducible on the latest version of Chrome? 
  > `Google Chrome 112.0.5615.165` works fine, no other version installed (it seems to be the latest on official Fedora 37 sources)

## Miscellaneous Information:

System information:

- Fedora 37
- kernel `6.2.10-200.fc37.x86_64`

**Comment by CodeDead** [comment]
Known issue on Linux, see:
https://github.com/brave/brave-browser/issues/29871

**Comment by moedn** [comment]
blazingly fast, thank you!

should I close this issue (as it seems to be included in #29871 already)?

**Comment by kjozwiak** [comment]
We pushed out `1.50.125 Chromium: 112.0.5615.165` which should fix the issue for everyone. If you were having issues, please let us know if the above release fixed your issue. You can also download the `deb` files manually via https://github.com/brave/brave-browser/releases/tag/v1.50.125. Just for some context, the above was fixed by upgrading chromium from `112.0.5615.138` to `112.0.5615.165`.

You can also find some context of what happened via https://github.com/brave/brave-browser/issues/29871#issuecomment-1516644603.

**Comment by moedn** [comment]
awesome, THANK YOU! just upgraded and I'm writing this response from Brave → everything fixed :tada: (and is was already in the F37 sources, so I didn't need to manually update anything :) )

have a wonderful day!
