### ISSUE TITLE
Aw snap on every page

### ISSUE THREAD

**Issue by Heikrana** [brave/brave-browser#29909]
## Description 
Updated brave-browser installed using the given method on brave's website for fedora/dnf. Since the update, I'm getting "aw snap" error on every page (event on settings page).

## Steps to Reproduce

   1. Update to/Install brave browser version `1.50.121`
   2. Open/Reopen the browser

## Actual result:

![Screenshot from 2023-04-21 01-19-17](https://user-images.githubusercontent.com/49754221/233472893-55a07fe4-5301-4b9a-91f7-e820e2003977.png)
Even after removing the config folder

## Reproduces how often: 
Everytime

## Brave version (brave://version info)
1.50.121 on Fedora37, kernel 6.2.10-200.fc37.x86_64

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not checked
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
Installed brave using flatpak and it works perfectly. Copied the config files to flatpak director (.var) and all the data is back and usable.

**Comment by kjozwiak** [comment]
We pushed out `1.50.125 Chromium: 112.0.5615.165` which should fix the issue for everyone. If you were having issues, please let us know if the above release fixed your issue. You can also download the `deb` files manually via https://github.com/brave/brave-browser/releases/tag/v1.50.125. Just for some context, the above was fixed by upgrading chromium from `112.0.5615.138` to `112.0.5615.165`.
