### ISSUE TITLE
Uplift #17856 and #18141 fixes to our HTTPS Upgrades feature in 1.51.x

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#29914]
There are two recent PRs merged into `master` (1.52.x) that we would like to uplift into `1.51.x`:

In https://github.com/brave/brave-core/pull/17856, we migrated our fixes to Chrome's HTTPS First Mode v2. Using v2 also incidentally fixes the referrer problem reported in https://github.com/brave/brave-browser/issues/28809.

In https://github.com/brave/brave-core/pull/18141, we enhanced our HTTPS Upgrades feature to fall back when an HTTP response returns an HTTPS error code (>= 400).

(QA testing plans are described in https://github.com/brave/brave-browser/issues/28935 and https://github.com/brave/brave-browser/issues/28013)

**Comment by kjozwiak** [comment]
Closing and labelling as `QA/No` & `release-notes/exclude` as https://github.com/brave/brave-browser/issues/28935, https://github.com/brave/brave-browser/issues/28013 & https://github.com/brave/brave-browser/issues/28809 will be used for verifications by QA. The mentioned issues will also be used for notes rather than the above.
