### ISSUE TITLE
Detect if third party cookies are blocked by Brave shields in an iframe

### ISSUE THREAD

**Issue by vardhman-singh-glean** [brave/brave-browser#29948]
## Description 
When Brave shields are enabled, third party cookies are blocked for any embedded frames with a different origin.
However, there are legitimate use-cases where a site would embed a third party widget which needs cookie access. 

For these cases, within our embedded widget we'd like to show the user instructions to allow cookie access for the site from the Brave shields menu or simply show messaging as to why the widget isn't working.

**However there's no reliable way to check if third party cookies are blocked by Brave shields currently using Javascript.**

Going over some general approaches that don't work with Brave:
- Using `document.hasStorageAccess` - this API isn't currently supported by Brave
- `navigator.cookieEnabled` shows true even if shields are blocking cookie access
- Trying to create a cookie using `document.cookie` actually works even if third party cookies are blocked so this cannot be relied upon.

## Expected behaviour
There should be some way to reflect that third party cookies are blocked using Javascript so that third party embedded frames can show appropriate messaging to the user.

## Desktop Brave version:
1.49.132

**Comment by diracdeltas** [comment]
cc @pes10k

**Comment by pes10k** [comment]
Hello @vardhman-singh-glean , as you noted, Brave by default partitions and clears 3p cookies (i.e. the cookie /storage APIs work as normal, but all 3p state is partitioned under the 1p, and cleared when the user navigates away from the 1p).

We considered but do not plan on adding an API to explicitly allow sites to learn the current shields state for a site for a range of reasons (mostly though bc we want to avoid cases where sites ask users to lower shields and brave's privacy protections).

Here are some suggestions though for solving your use case:
1. more tightly integrate with the first-party site, by storing needed persistant state in the 1p storage area, and passing values to the 3p frame through `postMessage`
2. otherwise, if you still need to check the status of cookie blocking in shields, you could set a HTTP cookie in your 3p frame, send a request that'd include that cookie, and then see if the cookie was sent.  The cookie will be sent if the user has selected "allow all cookies", and otherwise will not be sent

I'm going to close this issue since we do not plan on changing or adding any APIs, but i hope the above help, and I'm happy to continue discussing here if it'd be helpful
