### ISSUE TITLE
Clicking Back on Empty Tab should open previous tab instead of Closing Browser

### ISSUE THREAD

**Issue by tathastu871** [brave/brave-browser#29945]
## Description 
**Ease of Going to Previous tab after opening new tab. As currently it requires Clicking tab button and select previous tab. When several tabs are opened It takes several seconds to minute to go to previous tab**

## Steps to reproduce 

   1. Open Tab 1 Search Anything
   2. Open New Tab 2 Search Anything
   3. Click Back Button -> Goes to Empty Tab
   4. Click Back Button -> Closes Browser

## Actual result 

https://user-images.githubusercontent.com/65007212/233847906-b88a46b9-ed01-4164-91dd-b35ee47f3df7.mp4

**See above video how slow it is**
## Expected result

On clicking back button Previous Tab should opem
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): Arm
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
Latest

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by NikharPandya** [comment]
### Current Feature to scroll through tabs with a swipe

For going to the previous tab you could simply swipe right or left at this moment (will only not work on the first page right swipe and last page left swipe) but otherwise will smoothly scroll through tabs. 

### This feature is not a good UX
Meanwhile using back for guiding through tabs will not be a good user experience as they are just for web pages inside a single tab)

### Add a left swipe at the last page to open a new tab

I suggest we add one more left swipe on the last tab to open a new tab page instead of doing nothing for now.
Just made an issue for  it #30086 follow through if interested

**Comment by tathastu871** [comment]
Left swipe doesnt take to previous tab it closes browser

**Comment by NikharPandya** [comment]
@tathastu871,  did you swipe on the tab count icon located in the bottom toolbar?

**Comment by NikharPandya** [comment]
No worries, Can you close the issue from your side?
