### ISSUE TITLE
Add P3A metrics for News opt-in, daily & monthly usage

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#30154]
Add new ephemeral P3A metrics for News opt-in, daily & monthly usage:

If you changed your News opt-in status today, what did you change it to?
`Brave.Today.IsEnabled`

0. Disabled
1. Enabled

Did you use Brave News this month?
`Brave.Today.UsageMonthly`

1. Yes

Did you use Brave News today?
`Brave.Today.UsageDaily`

1. Yes

**Comment by petemill** [comment]
@DJAndries On Desktop, this pref can never be set to `false` after it has been set to `true`. According to [the NTP code](https://github.com/brave/brave-core/blob/master/components/brave_new_tab_ui/components/default/braveNews/customize/Context.tsx#L111-L118):
```
    if (shouldEnable) {
      setOptInPrefEnabled(true)
      setShowOnNTPPrefEnabled(true)
      return
    }
    setShowOnNTPPrefEnabled(false)
```
This is because the opt-in pref is purely for recording that the user has seen the policy.

Perhaps a more accurate name for this metric is `Brave.Today.IsEnabled`?

**Comment by DJAndries** [comment]
> Perhaps a more accurate name for this metric is Brave.Today.IsEnabled? 

agreed, renamed

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.53.74 Chromium: 114.0.5735.53 (Official Build) beta (64-bit)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Windows 10 Version 22H2 (Build 19045.2965)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo x70 Pro version 12` running `Bravemonoarm64.apk_1.53.84`
