### ISSUE TITLE
Reset skus from brave://skus-internals

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#30191]
Add reset button brave://skus-internals and reset skus state from local state

When reset button is pressed, `skus.state` should be reverted to default.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.53.50 Chromium: 114.0.5735.26 (Official Build) nightly (x86_64)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | macOS Version 13.4 (Build 22F66)

**Comment by kjozwiak** [comment]
The above needs to be re-verified due to https://github.com/brave/brave-core/pull/18356, https://github.com/brave/brave-core/pull/18403 & https://github.com/brave/brave-core/pull/18527 being uplifted into `1.52.x` via https://github.com/brave/brave-core/pull/18538. Used https://github.com/brave/brave-browser/issues/30191#issuecomment-1553364334 as the needed verification on Nightly to uplift into `1.52.x` as per https://github.com/brave/brave-core/pull/18538#pullrequestreview-1440491114.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (x86_64)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | macOS Version 13.5 (Build 22G5027e)


### Steps:

1. installed `1.52.112`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN` using `account.bravesoftware.com` (staging)
4. opened `brave://skus-internals`
5. clicked on `Fetch SKUs state`
6. confirmed JSON nested-tree blob
7. disconnected from `Brave VPN`
8. clicked on `Reset SKUs state`
9. confirmed was prompted to confirm, with warning
10. clicked `OK`
11. confirmed JSON view was cleared of its values (but still had its top-level fields)
12. waited some time for VPN-session credentials to time out/expire
13. clicked on the `VPN` button in the toolbar

example | example | example | example | example | example
---------|----------|--------|-----------|---------|---------
