### ISSUE TITLE
Add character limit to inputbox

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#30233]
As AIChat is designed to answer context-related questions, we need to add a character limit to the input box. This will help prevent users from submitting lengthy queries, resulting in a better user experience.

**Comment by nullhook** [comment]
I'm curious if you have an optimal number in mind here. 

Not sure if we should consider the following but just keeping it in one place:

- Claude's new context window has a limit of ~75,000 words / ~100,000 tokens / ~340,000 Unicode characters
- The extracted article from our distiller has a limit of ~18k chars / ~4k tokens

cc @petemill @LorenzoMinto

**Comment by petemill** [comment]
Since the limits are so absurdly big, maybe we should just not have any meaningful limits? Or stick to my initial guess which is:
- Limit an individual entry to ~80% of the context window limit
- Limit a conversation to ~95% of the context window limit (i.e. don't allow further human messages).

However, maybe cost plays a factor in this decision, as does internal model efforts which might have smaller window.

**Comment by LorenzoMinto** [comment]
I think we should have an input limit, regardless of the context limit of the model. Aria has a 3,000 chars input limit, Bing AI 2,000. A full context input Claude request will be very expensive, in my opinion we shouldn't allow these requests unless the use case and the subscription state calls for it (e.g. pdf summarisation, premium users). Also, LLaMA and LongLLaMa versions supports 8k/16k context sizes. I think a 2,000 characters input limit should be more than enough to enforce initially.
