### ISSUE TITLE
Remove hyphen(`-`) from os vpn entry

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#30295]
We're seeing weird config write failure(https://github.com/brave/brave-browser/issues/30291) on Windows.
Interestingly, it seems not happen on Stable.
One difference we found is non-stable's os entry name has hyphen(`-`), `BraveVPN-Beta` or `BraveVPN-Nightly` vs `BraveVPN`.
This is another test to check os entry name could affect config write failure or not.

STR
* Check that os entry name doesn't have hyphen like `BraveVPNNightly`, `BraveVPNBeta`

**Comment by kjozwiak** [comment]
The above requires `1.52.102` or higher for `1.52.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | Windows 10 Version 22H2 (Build 19045.2965)

### Steps:

1. installed `1.52.102` (`beta`)
2. launched Brave
3. purchased, configured, and tried to connect to `Brave VPN`
4. however, it fails to write out the config (due to https://github.com/brave/brave-browser/issues/30291)
5. shut down Brave `beta`
6. launched Brave `release`
7. purchased, configured, and connected to Brave VPN
8. confirmed a `BraveVPN` entry was written to Windows' VPN settings page
9. disconnected from `Brave VPN`
10. relaunched `1.52.102`
11. connected to `Brave VPN`

### Confirmed...

**Comment by stephendonner** [comment]
Leaving final `QA Pass-Win64` label for when @MadhaviSeelam gets a chance to verify on `Windows 11` 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (x86_64)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | macOS Version 13.4 (Build 22F66)

1. installed `1.52.102`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN`
4. opened `Apple` -> `System Settings...` -> `VPN`
5. confirmed entry of `BraveVPNBeta`

`1.52.102` | `1.52.102` | `1.52.101`
-----------|------------|----------
<img width="1920" alt="Screenshot 2023-05-18 at 10 52 35 AM" src="https://github.com/brave/brave-browser/assets/387249/312c0dae-ecaa-41ef-9bf9-fd58b71c4305"> | <img width="827" alt="Screenshot 2023-05-18 at 10 51 40 AM" src="https://github.com/brave/brave-browser/assets/387249/a9597a42-19a4-49d2-aea1-b8ee13535b09"> | <img width="827" alt="Screenshot 2023-05-18 at 9 34 27 AM" src="https://github.com/brave/brave-browser/assets/387249/41f23a70-d3ae-4812-a783-01c12dd4c358">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```


### Steps:

1. installed `1.52.102` (`beta`)
2. launched Brave
3. purchased, configured, and tried to connect to `Brave VPN`
4. however, it fails to write out the config (due to https://github.com/brave/brave-browser/issues/30291)
5. confirmed VPN entry is not shown in OS settings
6. shut down Brave `beta`
7. launched Brave `release`
8. purchased, configured, and connected to `Brave VPN`
9. confirmed a `BraveVPN` entry was written to Windows' `VPN` settings page
10. disconnected from `Brave VPN`
11. relaunched `1.52.102`
12. connected to `Brave VPN`


### Confirmed I could connect to `Brave VPN` and an entry named `BraveVPNBeta` was written to the `VPN` settings page

step 4 | step 5 | step 8 | step 9 | step 12 | os settings/vpn panel
-------|--------|--------|----------|------------|------
<image width="600" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9bfe837b-a8a3-420f-9ff0-870b838304c4">|<image width="600" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bf5165a4-f6c6-4434-8d8c-ffaea697a9de">|<image width="600" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1ce4a8fa-365f-4954-8b8c-12b342e55f23">|<image width="600" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e9ae8eff-92fc-4dc4-b979-98b5f070e9fc">|<image width="600" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d9104249-c6d8-4d3a-bb94-9c0bb96b1239">|<image width="600" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9110f56f-0ef3-4ae9-ae3d-ad5e4451c00a">
