### ISSUE TITLE
Update Portfolio Settings to use Toggles

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30422]
## Description 

We need to update the `Portfolio` settings to use `toggle` switches instead of `checkboxes`

![Screenshot 59](https://github.com/brave/brave-browser/assets/40611140/3c3cb0b5-7cf7-4580-9d85-19765571f9b1)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | Linux

- Verified steps from [brave/brave-core#18540](https://github.com/brave/brave-core/pull/18540)
- Verified Portfolio settings use checkbox instead of switch

https://github.com/brave/brave-browser/assets/17010094/c253fab9-55ac-4313-96a5-2aece848fc67

---------------------

**Verification passed on**

Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18540](https://github.com/brave/brave-core/pull/18540)
- Verified Portfolio settings use checkbox instead of switch

https://github.com/brave/brave-browser/assets/17010094/11f8246d-e441-4d01-8b2f-098980aaf6ea

---------------------

**Verification passed on**

Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18540](https://github.com/brave/brave-core/pull/18540)
- Verified Portfolio settings use checkbox instead of switch

https://github.com/brave/brave-browser/assets/17010094/ccfb4818-96d7-401f-b509-dde9b3d8432c
