### ISSUE TITLE
Rewards summary is not retained between browser restarts.

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3055]
Follow up from https://github.com/brave/brave-browser/issues/2332

## Steps to Reproduce

   1. Clean install
   2. Tip a verified publisher
   3. Check `Rewards summery` in `brave://rewards`
4. Restart browser
5. Check `Rewards summery` in `brave://rewards`

## Actual result:

Rewards summery is empty
Rewards summery is shown for given month (January on the screen shot), which indicates that all transactions are included.
![image](https://user-images.githubusercontent.com/34715963/51578199-07cc6a00-1ebd-11e9-8a3b-77018eb77710.png)

Note: Tips table retains the data.

## Expected result:
Rewards summery is retained

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

cc @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
@btlechowski can you test this on 0.60 please. I couldn't reproduce it

**Comment by GeetaSarvadnya** [comment]
Reproducible on Windows 10 x64 - 0.59.26. After browser restart `Total tips this month` value is also getting cleared from Tips panel.

![image](https://user-images.githubusercontent.com/38657976/51590662-bf3e9c00-1f10-11e9-9ab0-420d06096f0c.png)

**Comment by kjozwiak** [comment]
Jumped on a quick call with @NejcZdovc and narrowed down the issue. This only happens when there's only a tip being listed under `Summary` no other entries. Example:

Case that's **reproducible**:

* launch Brave with a new profile and restore a wallet (no entries in the summary)
* tip a verified publisher and a tip entry appears in the summary (only entry)
* restart the browser and you'll notice that the tip entry is removed

Case that's **not reproducible**:

* launch Brave with a new profile and accept a grant (now there's a grant entry in the summary)
* tip a verified publisher and a tip entry appears in the summary (now there's two entries)
* restart the browser and you'll notice that the tip doesn't disappear from the summary this time

**Comment by kjozwiak** [comment]
@bbondy @rebron what do you guys think about uplifting this into `0.59.x`? As mentioned in https://github.com/brave/brave-browser/issues/3055#issuecomment-456702996, this only happens when you only have tip entries in the summary and nothing else. Users that restore wallets are more prone to run into this. Users who accept grants (majority of our users) won't see this.

I'm fine leaving this in `0.60.x` but wanted to see what you guys thought about a possible uplift.

**Comment by bbondy** [comment]
I'm fine with whatever you think is best.

**Comment by srirambv** [comment]
@kjozwiak @bbondy I'd just leave it for 0.60.x. Its not like we are losing the actual tip, restart workaround just works fine.

**Comment by kjozwiak** [comment]
Lets leave it for `0.60.x` 👍

**Comment by NejcZdovc** [comment]
@srirambv restart will not work as if you have negative total, we don't load reports and because of that you will lose summary data. If you restore wallet, do a tip, restart browser, do a tip, restart browser, do a tip, at the end in summary you will only see the last tip, not sum.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1423
