### ISSUE TITLE
What do we do about the sidebar chat pane on a brave://chat page?

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#30562]
It looks really weird when you have the sidebar open and you're on the brave://chat page. Should we do something or just allow it?

**Comment by petemill** [comment]
We can have it not do anything when trying to open it on a Tab that is at brave://chat, and close itself when opening brave://chat via address bar (or the "show this conversation in a full Tab" button in the sidebar AI Chat). When https://github.com/brave/brave-core/pull/17895 lands, this will be possible since the panel will be open per-Tab and not globally.

**Comment by bbondy** [comment]
Sounds reasonable as a starting point!

**Comment by nullhook** [comment]
is this still relevant?

**Comment by bbondy** [comment]
We probably don't really need to do anything in particular once we have the full page. Closing for now.
