### ISSUE TITLE
Update Asset Details Settings Dropdown Icon

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30616]
## Description 

We need to change the `Asset Details` settings dropdown icon from `tune` to `more-vertical`

![Screenshot 18](https://github.com/brave/brave-browser/assets/40611140/3d947329-7b7f-4f19-a025-af8c14a214fb)

![Screenshot 19](https://github.com/brave/brave-browser/assets/40611140/b8a3f170-556a-4b68-a2a7-553563c8a7ac)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#18637](https://github.com/brave/brave-core/pull/18637)
- Verified `Asset Details` settings icon is `vertical icon` instead of the `tune icon`

https://github.com/brave/brave-browser/assets/17010094/6bdc12ae-ca3d-40a7-a4d8-87ef8d56b495

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18637](https://github.com/brave/brave-core/pull/18637)
- Verified `Asset Details` settings icon is `vertical icon` instead of the `tune icon`

https://github.com/brave/brave-browser/assets/17010094/9a63ff68-17cf-4cab-9ff1-13549e968f79


---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18637](https://github.com/brave/brave-core/pull/18637)
- Verified `Asset Details` settings icon is `vertical icon` instead of the `tune icon`

https://github.com/brave/brave-browser/assets/17010094/e3103700-020b-4224-8c6f-574c81ca45a5
