### ISSUE TITLE
Add vertical tabs P3A metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#30928]
Add tab count metrics for vertical tab users.

As a user with vertical tabs enabled, what is the max amount of open tabs this week?
`Brave.VerticalTabs.OpenTabs`

0. 1
1. 2-5
2. 6-10
3. 11-50
4. 51+

As a user with vertical tabs enabled and had at least one pinned tab this week, what is the max amount of pinned tabs this week?
`Brave.VerticalTabs.PinnedTabs`

0. 1-2
1. 3-5
2. 6+

As a user with vertical tabs mode enabled and had at least one tab group this week, what is the max amount of tab groups this week?
`Brave.VerticalTabs.GroupTabs`

0. 1-2
1. 3-5
2. 6+

**Comment by kjozwiak** [comment]
The above requires `1.56.1` or higher for `1.56.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.56.1 Chromium: 115.0.5790.75 (Official Build) (64-bit)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | Windows 10 Version 22H2 (Build 19045.3086)

```
### Brave.VerticalTabs.OpenTabs
<details>
<summary>Case 0: Brave.VerticalTabs.OpenTabs = 0_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs via `brave://settings/appearance`
3. Open brave://local-state
4. Make sure that there is only 1 tab is opened 
5. Look for the metrics `Brave.VerticalTabs.OpenTabs`
6. Confirmed that the metrics `Brave.VerticalTabs.OpenTabs` response value is `0`

![image](https://github.com/brave/brave-core/assets/38657976/7f491fd4-5641-4704-8b51-c1511c9bb1c4)

</details>

<details>
<summary>Case 1: Brave.VerticalTabs.OpenTabs = 1_PASSED</summary>

<details>
<summary>Case 1.1: no of tabs opened = 2_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs via `brave://settings/appearance`
3. Open brave://local-state
4. Make sure that 2 tabs are opened 
5. Look for the metrics `Brave.VerticalTabs.OpenTabs`
6. Confirmed that the metrics `Brave.VerticalTabs.OpenTabs` response value is `1`
![image](https://github.com/brave/brave-core/assets/38657976/c9f05cfc-3ca6-4aa8-b983-4ffd2b3d6cb5)

</details>

<details>
<summary>Case 1.2: no of tabs opened = 5_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs via `brave://settings/appearance`
3. Open brave://local-state
4. Make sure that 5 tabs are opened 
5. Look for the metrics `Brave.VerticalTabs.OpenTabs`
6. Confirmed that the metrics `Brave.VerticalTabs.OpenTabs` response value is `1`

![image](https://github.com/brave/brave-core/assets/38657976/040a0f4b-76a6-41c7-8560-143f3d0dd36d)

</details>

<details>
<summary>Case 1.3: no of tabs opened < 5_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs via `brave://settings/appearance`
3. Open brave://local-state
4. Make sure that 3 tabs are opened 
5. Look for the metrics `Brave.VerticalTabs.OpenTabs`
6. Confirmed that the metrics `Brave.VerticalTabs.OpenTabs` response value is `1`

![image](https://github.com/brave/brave-core/assets/38657976/f52b1ca1-5d46-4f64-9cca-decf627f906e)

</details>

</details>

<details>
<summary>Case 2: Brave.VerticalTabs.OpenTabs = 2_PASSED</summary>

<details>
<summary>Case 2.1: no of tabs opened = 6_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs via `brave://settings/appearance`
3. Open brave://local-state
4. Make sure that 6 tabs are opened 
5. Look for the metrics `Brave.VerticalTabs.OpenTabs`
6. Confirmed that the metrics `Brave.VerticalTabs.OpenTabs` response value is `2` as expected

![image](https://github.com/brave/brave-core/assets/38657976/20dd6988-28eb-47e8-995e-3d3f2435e843)

</details>

<details>
<summary>Case 2.2: no of tabs opened = 10_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs via `brave://settings/appearance`
3. Open brave://local-state
4. Make sure that 10 tabs are opened 
5. Look for the metrics `Brave.VerticalTabs.OpenTabs`
6. Confirmed that the metrics `Brave.VerticalTabs.OpenTabs` response value is `2` as expected

![image](https://github.com/brave/brave-core/assets/38657976/ed1e98df-538f-4d7b-b9f7-0122686e0f72)


</details>

<details>
<summary>Case 2.3: no of tabs opened < 10_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs via `brave://settings/appearance`
3. Open brave://local-state
4. Make sure that 9 tabs are opened 
5. Look for the metrics `Brave.VerticalTabs.OpenTabs`
6. Confirmed that the metrics `Brave.VerticalTabs.OpenTabs` response value is `2` as expected

![image](https://github.com/brave/brave-core/assets/38657976/738d9a17-361f-408a-8b73-d3f94b032f23)

</details>


</details>

<details>
<summary>Case 3: Brave.VerticalTabs.OpenTabs = 3_PASSED</summary>


<details>
<summary>Case 3.1: no of tabs opened = 11_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs via `brave://settings/appearance`
3. Open brave://local-state
4. Make sure that 11 tabs are opened 
5. Look for the metrics `Brave.VerticalTabs.OpenTabs`
6. Confirmed that the metrics `Brave.VerticalTabs.OpenTabs` response value is `3` as expected

![image](https://github.com/brave/brave-core/assets/38657976/0cb48905-24da-4cbb-a25c-f073f290f1c7)

</details>

<details>
<summary>Case 3.2: no of tabs opened = 50_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs via `brave://settings/appearance`
3. Open brave://local-state
4. Make sure that 50 tabs are opened 
5. Look for the metrics `Brave.VerticalTabs.OpenTabs`
6. Confirmed that the metrics `Brave.VerticalTabs.OpenTabs` response value is `3` as expected

![image](https://github.com/brave/brave-core/assets/38657976/f2c25b8f-7ece-44d6-a3f9-8209b91b5913)

</details>

</details>

<details>
<summary>Case 4: Brave.VerticalTabs.OpenTabs = 4_PASSED</summary>

<details>
<summary>Case 4.1: no of tabs opened = 11_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs via `brave://settings/appearance`
3. Open brave://local-state
4. Make sure that 51+ tabs are opened 
5. Look for the metrics `Brave.VerticalTabs.OpenTabs`
6. Confirmed that the metrics `Brave.VerticalTabs.OpenTabs` response value is `4` as expected

![image](https://github.com/brave/brave-core/assets/38657976/9925dec4-eb52-4310-b0f6-07e060224e35)

</details>


</details>

### Brave.VerticalTabs.PinnedTabs

<details>
<summary>Case 1: Brave.VerticalTabs.PinnedTabs = 0_PASSED</summary>

<details>
<summary>Case 1.1: Brave.VerticalTabs.PinnedTabs = 0_PASSED</summary>

1. Clean profile `1.55.17`
2. Open brave://local-state
3. Right click on the brave://local-state tab, select `Use vertical tabs` context menu option
4. Make sure these is only one tab in the vertical tab view
5. Pin the tab on the vertical tab view
6. Reload brave://local-state file 
7. Restart the browser
8. Look for the metrics `Brave.VerticalTabs.PinnedTabs` 
9. Confirmed that the metrics `Brave.VerticalTabs.PinnedTabs` response value is `0` as expected

![image](https://github.com/brave/brave-core/assets/38657976/5dce4a3c-f48c-41c8-8ad8-db39ceadde7a)

</details>


<details>
<summary>Case 1.1: Brave.VerticalTabs.PinnedTabs = 0_PASSED</summary>

1. Clean profile `1.55.17`
2. Open brave://local-state
3. Right click on the brave://local-state tab, select `Use vertical tabs` context menu option
4. Pin the tab on the vertical tab view
5. Open another tab and Pin the tab and make sure there are 2 tabs pinned
6. Reload brave://local-state file 
7. Restart the browser
8. Look for the metrics `Brave.VerticalTabs.PinnedTabs` 
9. Confirmed that the metrics `Brave.VerticalTabs.PinnedTabs` response value is `0` as expected

![image](https://github.com/brave/brave-core/assets/38657976/9fc7ffd0-ff8e-45d2-82cb-a82a662efc07)

</details>
</details>

<details>
<summary>Case 2: Brave.VerticalTabs.PinnedTabs = 1_PASSED</summary>

<details>
<summary>Case 2.1: Brave.VerticalTabs.PinnedTabs = 1_PASSED</summary>

1. Clean profile `1.55.17`
2. Open brave://local-state
3. Right click on the brave://local-state tab, select `Use vertical tabs` context menu option
4. Pin the tab on the vertical tab view
5. Open another 2 tabs and Pin the tabs and make sure there are 3 tabs pinned
6. Reload brave://local-state file 
7. Restart the browser
8. Look for the metrics `Brave.VerticalTabs.PinnedTabs` 
9. Confirmed that the metrics `Brave.VerticalTabs.PinnedTabs` response value is `1` as expected

![image](https://github.com/brave/brave-core/assets/38657976/42502bf9-ca37-454d-bbce-411cda100197)

</details>

<details>
<summary>Case 2.2: Brave.VerticalTabs.PinnedTabs = 1_PASSED</summary>

1. Clean profile `1.55.17`
2. Open brave://local-state
3. Right click on the brave://local-state tab, select `Use vertical tabs` context menu option
4. Pin the tab on the vertical tab view
5. Open another 3 tabs and Pin the tabs and make sure there are 4 tabs pinned
6. Reload brave://local-state file 
7. Restart the browser
8. Look for the metrics `Brave.VerticalTabs.PinnedTabs` 
9. Confirmed that the metrics `Brave.VerticalTabs.PinnedTabs` response value is `1` as expected

![image](https://github.com/brave/brave-core/assets/38657976/063a441d-3caa-4012-b609-53bd10c5b7d3)


</details>

<details>
<summary>Case 2.3: Brave.VerticalTabs.PinnedTabs = 1_PASSED</summary>

1. Clean profile `1.55.17`
2. Open brave://local-state
3. Right click on the brave://local-state tab, select `Use vertical tabs` context menu option
4. Pin the tab on the vertical tab view
5. Open another 4 tabs and Pin the tabs and make sure there are 5 tabs pinned
6. Reload brave://local-state file 
7. Restart the browser
8. Look for the metrics `Brave.VerticalTabs.PinnedTabs` 
9. Confirmed that the metrics `Brave.VerticalTabs.PinnedTabs` response value is `1` as expected

![image](https://github.com/brave/brave-core/assets/38657976/b3ac558f-54ed-410b-a79c-b4e8d4674423)


</details>
</details>

<details>
<summary>Case 3: Brave.VerticalTabs.PinnedTabs = 2_PASSED</summary>

1. Clean profile `1.55.17`
2. Open brave://local-state
3. Right click on the brave://local-state tab, select `Use vertical tabs` context menu option
4. Pin the tab on the vertical tab view
5. Open another 5 tabs and Pin the tabs and make sure there are 6 tabs pinned
6. Reload brave://local-state file 
7. Restart the browser
8. Look for the metrics `Brave.VerticalTabs.PinnedTabs` 
9. Confirmed that the metrics `Brave.VerticalTabs.PinnedTabs` response value is `2` as expected

![image](https://github.com/brave/brave-core/assets/38657976/577bd8eb-b0d3-40be-840a-558a4cd20d46)

</details>

### Brave.VerticalTabs.GroupTabs

<details>
<summary>Case 1: Brave.VerticalTabs.GroupTabs = 0_PASSED</summary>

<details>
<summary>Case 1.1: Brave.VerticalTabs.GroupTabs = 0_PASSED</summary>

1. Clean profile `1.55.17` and enable vertical tabs
2. Open few tabs with sites opened in tabs
3. Create a tab group 1
4. Open brave://local-state file
5. Look for the metrics `Brave.VerticalTabs.GroupTabs`
6. Confirm that the metrics `Brave.VerticalTabs.GroupTabs` response value is `0` as expected

![image](https://github.com/brave/brave-core/assets/38657976/bb37a4f9-7dcb-4911-aedc-d8418eb413c7)

</details>

<details>
<summary>Case 1.2: Brave.VerticalTabs.GroupTabs = 0_PASSED</summary>

1. Clean profile `1.55.17` and enable vertical tabs
2. Open few tabs with sites opened in tabs
3. Create two tab groups
4. Open brave://local-state file
5. Look for the metrics `Brave.VerticalTabs.GroupTabs`
6. Confirm that the metrics `Brave.VerticalTabs.GroupTabs` response value is `0` as expected

![image](https://github.com/brave/brave-core/assets/38657976/9439274d-f765-40b9-9391-c9224c2bb0af)


</details>

</details>

<details>
<summary>Case 2: Brave.VerticalTabs.GroupTabs = 1_PASSED</summary>

<details>
<summary>Case 2.1: Brave.VerticalTabs.GroupTabs = 1_PASSED</summary>

1. Clean profile `1.55.17` and enable vertical tabs
2. Open few tabs with sites opened in tabs
3. Create 3 tab groups
4. Open brave://local-state file
5. Look for the metrics `Brave.VerticalTabs.GroupTabs`
6. Confirm that the metrics `Brave.VerticalTabs.GroupTabs` response value is `1` as expected

![image](https://github.com/brave/brave-core/assets/38657976/224eb1ed-0419-4e48-8efe-6a76f5389487)


</details>

<details>
<summary>Case 2.2: Brave.VerticalTabs.GroupTabs = 1_PASSED</summary>

1. Clean profile `1.55.17` and enable vertical tabs
2. Open few tabs with sites opened in tabs
3. Create 4 tab groups
4. Open brave://local-state file
5. Look for the metrics `Brave.VerticalTabs.GroupTabs`
6. Confirm that the metrics `Brave.VerticalTabs.GroupTabs` response value is `1` as expected

![image](https://github.com/brave/brave-core/assets/38657976/f2ce87ef-e602-4c29-bc21-6e5b7cc2205f)


</details>

<details>
<summary>Case 2.3: Brave.VerticalTabs.GroupTabs = 1_PASSED</summary>

1. Clean profile `1.55.17` and enable vertical tabs
2. Open few tabs with sites opened in tabs
3. Create 5 tab groups
4. Open brave://local-state file
5. Look for the metrics `Brave.VerticalTabs.GroupTabs`
6. Confirm that the metrics `Brave.VerticalTabs.GroupTabs` response value is `1` as expected

![image](https://github.com/brave/brave-core/assets/38657976/c4faf5e8-252c-4138-878e-2236a095451a)


</details>

</details>

<details>
<summary>Brave.VerticalTabs.GroupTabs = 2_PASSED</summary>

1. Clean profile `1.55.17`
2. Open few tabs with sites opened in tabs
3. Create 6 tab groups
4. Open brave://local-state file
5. Look for the metrics `Brave.VerticalTabs.GroupTabs`
6. Confirm that the metrics `Brave.VerticalTabs.GroupTabs` response value is `2` as expected

![image](https://github.com/brave/brave-core/assets/38657976/d5161ca8-1ced-4ecc-983e-a956d926553e)

</details>

---------------

### Additional scenarios

<details>
<summary>Case 1: Tabs added via PT/TOR/Guest_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs view
3. Add 7 sites in 7 tabs
4. Confirm that the metrics `Brave.VerticalTabs.OpenTabs` response value is `2` as expected
5. Open a PT window and add two tabs with sites loaded
6. Open a TOR window and add two tabs with sites loaded
7. Number tabs in all the 3 window types (normal, PT and TOR window) is 11
8. Reload brave://local-state file
9. The metrics `Brave.VerticalTabs.OpenTabs` response value is `2` instead of `3`
10. If we look at the metrics `Brave.Core.TabCount` it gives the correct reponse when tab count is `7` and `11`

</details>

<details>
<summary>Case 2: Move Tabs to new window_PASSED</summary>

<details>
<summary>Case 2.1: Move Tabs to new window_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs view
3. Add 5 sites in 5 tabs
4. Confirm that the metrics `Brave.VerticalTabs.OpenTabs` response value is `1` as expected
5. Right click on any tab in vertical tav view and select the `Move tab to another window` context menu
6. Confirm that the tab is moved to the new window
7. Add second tab in new window (step 6 window)
8. Confirm that the total tabs opened in the original window and new window is 6
9. Reload brave://local-state file
10. Confirm that the metrics `Brave.VerticalTabs.OpenTabs` response value is `2` as expected

![image](https://github.com/brave/brave-core/assets/38657976/ac5fd6a0-3348-43b1-b32e-ff558fbcb03b)

</details>

<details>
<summary>Case 2.2: Move pinned Tabs to new window_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs view
3. Add 2 sites in 2 tabs
4. Pin both the tabs 
5. Confirm that the metrics `Brave.VerticalTabs.PinnedTabs` response value is `0` as expected
6. Right click on any pinned tab in vertical tab view and select the `Move tab to another window` context menu
7. Confirm that the pinned tab is moved to the new window
8. Add second tab in new window and pin it (step 6 window)
9. Confirm that the total tabs pinned in the original window and new window is 3
10. Reload brave://local-state file
11. the metrics `Brave.VerticalTabs.PinnedTabs` response value is `0` instead of `1`

</details>

<details>
<summary>Case 2.3: Move Tab group to new window_PASSED</summary>

1. Clean profile `1.55.17`
2. Enable vertical tabs view
3. Add 2 sites in 2 tabs
4. Create two tab groups (Group 1 and Group 2)
5. Confirm that the metrics `Brave.VerticalTabs.GroupTabs` response value is `0` as expected
6. Right click on any tabgroup in vertical tab view and select the `Move tab to another window` context menu
7. Confirm that the tabgroup is moved to the new window
8. Add second tab in new window and create a 3rd tab gropu (step 6 window)
9. Confirm that the total tabgroups in the original window and new window is 3
10. Reload brave://local-state file
11. the metrics `Brave.VerticalTabs.PinnedTabs` response value is `0` instead of `1`

![image](https://github.com/brave/brave-core/assets/38657976/d248187e-3911-436f-8144-32c655bd5874)

</details>

</details>

<details>
<summary>Case 3: Brave.VerticalTabs.OpenTabs_PASSED</summary>


   1. Set sys date to 19th June, clean profile `1.55.17`
   2. Open brave://local-state
   3. Enable vertical tabs via brave://settings/appearance
   4. Ensure that there are two tabs on the vertical tab view
   5. Look for the metrics `Brave.VerticalTabs.OpenTabs`
   6. Confirmed that the metrics `Brave.VerticalTabs.OpenTabs` response value is `1` as expected
   7. Close one tab and make sure there is only one tab on the vertical tab view
   8. Reload brave://local-state file
   9. Wait for 1 minute and restart the browser
   10. The metrics `Brave.VerticalTabs.OpenTabs` response value is `1` for the 1st week
   11. Fwd the sys clock ahead by 8 days (i.e 26th June in my case) [If I fwd the sys clock to 25th June the value `1` remains same]
   12. Reload brave://local-state file
   13. The metrics `Brave.VerticalTabs.PinnedTabs` response value is `0` as expected in the 2nd week


</details>

<details>
<summary>Case 4: Brave.VerticalTabs.PinnedTabs_PASSED</summary>

1. Set sys date to 19th June
2. Clean profile `1.55.17`
3. Open brave://local-state file, right click on the tab and select `Use vertical tabs` context menu
4. Open 5 more tabs and pin all the tabs including brave://local-state file, total pinned tabs count is 6
5. Reload brave://local-state file
6. The metrics `Brave.VerticalTabs.PinnedTabs` response value is `2` as expected
7. Unpin 3 tabs and reload brave://local-state file and enured metrics response value is still `2` for the 1st week
8. Fwd the sys clock ahead by 8 days (i.e 26th June in my case) [If I fwd the sys clock to 25th June the value `2` remains same]
9. Reload brave://local-state file
10. The metrics `Brave.VerticalTabs.PinnedTabs` response value is `1` as expected in the 2nd week

</details>

<details>
<summary>Case 5: Brave.VerticalTabs.GroupTabs_PASSED</summary>

   1. Set sys date to 19th June
   2. Clean profile 1.55.17
   3. Open brave://local-state file, right click on the tab and select `Use vertical tabs` context menu
   4. Open a bunch of sites 
   5. Create 6 tab groups 
   6. Reload the bave://local-state file 
   7. Look for the metrics `Brave.VerticalTabs.GroupTabs`
   8. Confirmed that the metrics `Brave.VerticalTabs.GroupTabs` response value is `2` as expected
   9. Remove 6th tab group
   10. Reload the bave://local-state file 
   15. The metrics `Brave.VerticalTabs.GroupTabs` response value is `2`  in the 1st week
   16. Close the browser
   17. Fwd the sys clock ahead by 8 days (i.e 26th June in my case) [If I fwd the sys clock to 25th June the value `2` remains same]
   18. Reload brave://local-state file
   19. Confirmed that the metrics `Brave.VerticalTabs.GroupTabs` response value is `1` as expected in the 2nd week


</details>
