### ISSUE TITLE
ABPVN `protruyen.com##+js(acs, Object, $._Eu)` - maximum call stack size exceeded

### ISSUE THREAD

**Issue by tachibana-shin** [brave/brave-browser#31098]
## Description 

Sorry I don't have time to investigate further. Specific problems are as follows:

In the ABPVN filter there is a filter rule as follows:
```
protruyen.com#%#//scriptlet("abort-current-inline-script", "Object", "$._Eu")
```
after i enabled the filter and went to protruyen.com i noticed that a code was forwarded to the site calling `max stack call`
![image](https://github.com/brave/adblock-rust/assets/45375496/88cb7472-9616-46cf-84de-17cfd3a7e8cb)
or
![image](https://github.com/brave/adblock-rust/assets/45375496/f77954d3-7598-4982-9bf9-546195310e6c)
i checked and found a code injected:

Code brave inject to website:
```js
(function() {
    const scriptletGlobals = new Map();
    let deAmpEnabled = true;

    try {
        (function() {
            const target = 'Object';
            if (target === '' || target === '{{1}}') {
                return;
            }
            const reRegexEscape = /[.*+?^${}()|[\]\\]/g;
            const needle = '$._Eu';
            const reNeedle = (()=>{
                if (needle === '' || needle === '{{2}}') {
                    return /^/;
                }
                if (/^\/.+\/$/.test(needle)) {
                    return new RegExp(needle.slice(1, -1));
                }
                return new RegExp(needle.replace(reRegexEscape, '\\$&'));
            }
            )();
            const context = '{{3}}';
            const reContext = (()=>{
                if (context === '' || context === '{{3}}') {
                    return;
                }
                if (/^\/.+\/$/.test(context)) {
                    return new RegExp(context.slice(1, -1));
                }
                return new RegExp(context.replace(reRegexEscape, '\\$&'));
            }
            )();
            const thisScript = document.currentScript;
            const chain = target.split('.');
            let owner = window;
            let prop;
            for (; ; ) {
                prop = chain.shift();
                if (chain.length === 0) {
                    break;
                }
                owner = owner[prop];
                if (owner instanceof Object === false) {
                    return;
                }
            }
            let value;
            let desc = Object.getOwnPropertyDescriptor(owner, prop);
            if (desc instanceof Object === false || desc.get instanceof Function === false) {
                value = owner[prop];
                desc = undefined;
            }
            const magic = String.fromCharCode(Date.now() % 26 + 97) + Math.floor(Math.random() * 982451653 + 982451653).toString(36);
            const scriptTexts = new WeakMap();
            const getScriptText = elem=>{
                let text = elem.textContent;
                if (text.trim() !== '') {
                    return text;
                }
                if (scriptTexts.has(elem)) {
                    return scriptTexts.get(elem);
                }
                const [,mime,content] = /^data:([^,]*),(.+)$/.exec(elem.src.trim()) || ['', '', ''];
                try {
                    switch (true) {
                    case mime.endsWith(';base64'):
                        text = self.atob(content);
                        break;
                    default:
                        text = self.decodeURIComponent(content);
                        break;
                    }
                } catch (ex) {}
                scriptTexts.set(elem, text);
                return text;
            }
            ;
            const validate = ()=>{
                const e = document.currentScript;
                if (e instanceof HTMLScriptElement === false) {
                    return;
                }
                if (e === thisScript) {
                    return;
                }
                if (reContext !== undefined && reContext.test(e.src) === false) {
                    return;
                }
                if (reNeedle.test(getScriptText(e)) === false) {
                    return;
                }
                throw new ReferenceError(magic);
            }
            ; // owner = Window, prop = "Object", desc = undefined, value = Object // owner[prop]
            Object.defineProperty(owner, prop, {
                get: function() {
                    validate(); // VM8:82 Uncaught RangeError: Maximum call stack size exceeded
                    return desc instanceof Object ? desc.get.call(owner) : value; // or this
                    // because desc is undefined. But `Object` is `window.Object` -> call this function recursive
                },
                set: function(a) {
                    validate();
                    if (desc instanceof Object) {
                        desc.set.call(owner, a);
                    } else {
                        value = a;
                    }
                }
            });
            const oe = window.onerror;
            window.onerror = function(msg) {
                if (typeof msg === 'string' && msg.includes(magic)) {
                    return true;
                }
                if (oe instanceof Function) {
                    return oe.apply(this, arguments);
                }
            }
            .bind();
        }
        )();

    } catch (e) {}
}
)()
```

and i try accessing anything from `Object` same error happens. And I conclude that this is due to the code that `adblock-rust` injected

### Solution
My suggestion is that instead of using general-purpose test `instanceof Object` will store `Object` to check primitive value:
```js
(function() {
    const scriptletGlobals = new Map();
    let deAmpEnabled = true;

    try {
        (function() {
            const target = 'Object';
            if (target === '' || target === '{{1}}') {
                return;
            }
            const reRegexEscape = /[.*+?^${}()|[\]\\]/g;
            const needle = '$._Eu';
            const reNeedle = (()=>{
                if (needle === '' || needle === '{{2}}') {
                    return /^/;
                }
                if (/^\/.+\/$/.test(needle)) {
                    return new RegExp(needle.slice(1, -1));
                }
                return new RegExp(needle.replace(reRegexEscape, '\\$&'));
            }
            )();
            const context = '{{3}}';
            const reContext = (()=>{
                if (context === '' || context === '{{3}}') {
                    return;
                }
                if (/^\/.+\/$/.test(context)) {
                    return new RegExp(context.slice(1, -1));
                }
                return new RegExp(context.replace(reRegexEscape, '\\$&'));
            }
            )();
            const thisScript = document.currentScript;
            const chain = target.split('.');
            let owner = window;
            let prop;
            for (; ; ) {
                prop = chain.shift();
                if (chain.length === 0) {
                    break;
                }
                owner = owner[prop];
                if (owner instanceof Object === false) {
                    return;
                }
            }
            let value;
            let desc = Object.getOwnPropertyDescriptor(owner, prop);
            if (desc instanceof Object === false || desc.get instanceof Function === false) {
                value = owner[prop];
                desc = undefined;
            }
            const magic = String.fromCharCode(Date.now() % 26 + 97) + Math.floor(Math.random() * 982451653 + 982451653).toString(36);
            const scriptTexts = new WeakMap();
            const getScriptText = elem=>{
                let text = elem.textContent;
                if (text.trim() !== '') {
                    return text;
                }
                if (scriptTexts.has(elem)) {
                    return scriptTexts.get(elem);
                }
                const [,mime,content] = /^data:([^,]*),(.+)$/.exec(elem.src.trim()) || ['', '', ''];
                try {
                    switch (true) {
                    case mime.endsWith(';base64'):
                        text = self.atob(content);
                        break;
                    default:
                        text = self.decodeURIComponent(content);
                        break;
                    }
                } catch (ex) {}
                scriptTexts.set(elem, text);
                return text;
            }
            ;
            const validate = ()=>{
                const e = document.currentScript;
                if (e instanceof HTMLScriptElement === false) {
                    return;
                }
                if (e === thisScript) {
                    return;
                }
                if (reContext !== undefined && reContext.test(e.src) === false) {
                    return;
                }
                if (reNeedle.test(getScriptText(e)) === false) {
                    return;
                }
                throw new ReferenceError(magic);
            }
            ; // owner = Window, prop = "Object", desc = undefined, value = Object // owner[prop]
+         const rawObj = Object
            Object.defineProperty(owner, prop, {
                get: function() {
                    validate(); // VM8:82 Uncaught RangeError: Maximum call stack size exceeded
-                   return desc instanceof Object ? desc.get.call(owner) : value; // or this
+                  return desc instanceof rawObj ? desc.get.call(owner) : value; // or this
                    // because desc is undefined. But `Object` is `window.Object` -> call this function recursive
                },
                set: function(a) {
                    validate();
                    if (desc instanceof Object) {
                        desc.set.call(owner, a);
                    } else {
                        value = a;
                    }
                }
            });
            const oe = window.onerror;
            window.onerror = function(msg) {
                if (typeof msg === 'string' && msg.includes(magic)) {
                    return true;
                }
                if (oe instanceof Function) {
                    return oe.apply(this, arguments);
                }
            }
            .bind();
        }
        )();

    } catch (e) {}
}
)()
```

## Steps to Reproduce

   1. Enable any filter include `#%#//scriptlet("abort-current-inline-script", "Object", "$._Eu")` (Example ABPVN)
   2. Enter to website (I take for example ABPVN filter https://protruyen.com)
   3. Crash `Object.defineProperty`, `Object.entries`... Enable devtools and see log

## Actual result:

![image](https://github.com/brave/brave-browser/assets/45375496/462a4a68-bab3-4b63-81a2-1b012e1abad0)

## Expected result:
Website work

## Desktop Brave version:

Version 1.52.126 Chromium: 114.0.5735.133 (Stable)  (64 bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? i have not tested
- Can you reproduce this issue with the nightly channel? i have not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? yes
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

This is a clone of https://github.com/brave/adblock-rust/issues/296 I believe I should make a copy of issuses here because the repo `brave/adblock-rust` has issues that persist every day years without return

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
Well, you should have researched the easiest thing:

"Is this rule compatible with Brave?"

Because it is not, that's an Adguard syntax, and Brave only supports uBlock syntaxes, uBlock resources, and Brave is usually implementing features based/inspired on uBlock, so, it is impossible Brave even does anything by having that filter, so the problem might be another one if that's the case.
There are rare ocasions where Brave gets alias for some features like `:has()` got the ABP alias `:-abp-has()` to be compatible with more rules but not everything in Brave has alias, since it is usually based on the uBlock lists.

For Brave to try to do anything the rule should be `protruyen.com##+js(abort-current-inline-script, Object, $._Eu)`

You need to understand, Brave doesn't have control on the Resources - Scriptlets like `abort-current-inline-script`, they are imported from uBlock code, https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js

Saying that, what you are seeing is the de-amp feature, not ACIS scriptlet, in action. The de-amp is a scriptlet made by Brave. https://github.com/brave/adblock-resources/blob/master/resources/de-amp.js 
Which means it is affected and being done by the `Auto-redirect AMP pages` setting in Shields.

And if that is causing issues, then it should be reported properly, the best way to do it is not on Github but on Brave Community, you make a post with the adblocking category and eventually Brave Team member (FanboyNZ) will fix it whatever it is the issue why the site is not loading, because if it is an issue with the ABPVN  list, then it should be addressed either by fixing the list or creating a rule to workaround the issue in the Brave Unbreak list. BUt this is not an adblocker issue, Adblock-Rust is doing what it is told to do, and there are so many issues for many different things that reporting a site compatibility issue here is not going to be the best to get it fixed.

**Comment by tachibana-shin** [comment]
> Well, you should have researched the easiest thing:
> 
> "Is this rule compatible with Brave?"
> 
> Because it is not, that's an Adguard syntax, and Brave only supports uBlock syntaxes, uBlock resources, and Brave is usually implementing features based/inspired on uBlock, so, it is impossible Brave even does anything by having that filter, so the problem might be another one if that's the case. There are rare ocasions where Brave gets alias for some features like `:has()` got the ABP alias `:-abp-has()` to be compatible with more rules but not everything in Brave has alias, since it is usually based on the uBlock lists.
> 
> For Brave to try to do anything the rule should be `protruyen.com##+js(abort-current-inline-script, Object, $._Eu)`
> 
> You need to understand, Brave doesn't have control on the Resources - Scriptlets like `abort-current-inline-script`, they are imported from uBlock code, https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js
> 
> Saying that, what you are seeing is the de-amp feature, not ACIS scriptlet, in action. The de-amp is a scriptlet made by Brave. https://github.com/brave/adblock-resources/blob/master/resources/de-amp.js Which means it is affected and being done by the `Auto-redirect AMP pages` setting in Shields.
> 
> And if that is causing issues, then it should be reported properly, the best way to do it is not on Github but on Brave Community, you make a post with the adblocking category and eventually Brave Team member (FanboyNZ) will fix it whatever it is the issue why the site is not loading, because if it is an issue with the ABPVN list, then it should be addressed either by fixing the list or creating a rule to workaround the issue in the Brave Unbreak list. BUt this is not an adblocker issue, Adblock-Rust is doing what it is told to do, and there are so many issues for many different things that reporting a site compatibility issue here is not going to be the best to get it fixed.

iI don't think this is a `de-amp` problem i looked at the link you mentioned it compiles to a completely different code. i believe this is a problem of `adblock-rust` handler or `scriptlet`

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
The problem is you are giving wrong information, so it is hard to help based on your information.
I had to do the work myself and see, without taking into account any of your information, because then I would have given the proper answer, of course, I was the one who came to comment... but I thought you did 'proper' research as you stated.

1. the rule in ABPVN is `protruyen.com##+js(acs, Object, $._Eu)` and not `protruyen.com#%#//scriptlet("abort-current-inline-script", "Object", "$._Eu")` which matters, and that's the reason I got mislead, that was my mistake. That was the biggest piece of information though, because if the rule was the one you said, it wasn't going to work, but based on looking at the list, it does because it is the uBlock syntax being used for the rule, so Brave reads it.

2. The website doesn't load, not even in uBlock. So it is a ABPVN list issue, which should be fixed by its maintainer, not Brave, and not even uBlock because their scriptlets work, the rule is the one that is bad, probably outdated and needs to be fixed by them. But yes, the `max stack call` error happens in uBlock as well.

3. You should report it to ABPVN https://github.com/abpvn/abpvn people to fix the rule, not Brave or uBlock. The problem is uBlock at least allows scriptlet exceptions, while Brave doesn't, so Brave will not stop loading that rule, unless it is removed or well, fixed.

4. What you can do is disable the list, go to the website and enable the list. That way the checking of the website will not happen anymore since it is stored in a cookie or something.

I will delete my comment, anyway, this is the one that I should have posted if I made, myself, the proper research and tested things. Good thing for the future to just test everything myself.
The deAmp was me just trying to understand the issue anyway, because I thought the rule was Adguard syntax as you said, but now it makes sense, and you are right, it is the rule the problem, but not a Brave Browser issue, or Adblock-Rust and not even uBlock ACS issue, everything is working as intended, it is just ABPVN with a terrible rule.

**Comment by antonok-edm** [comment]
> the rule in ABPVN is `protruyen.com##+js(acs, Object, $._Eu)` and not `protruyen.com#%#//scriptlet("abort-current-inline-script", "Object", "$._Eu")` which matters, and that's the reason I got mislead, that was my mistake. That was the biggest piece of information though, because if the rule was the one you said, it wasn't going to work, but based on looking at the list, it does because it is the uBlock syntax being used for the rule, so Brave reads it.

cc @ryanbr - let's try to get this fixed upstream in ABPVN

**Comment by tachibana-shin** [comment]
> > the rule in ABPVN is `protruyen.com##+js(acs, Object, $._Eu)` and not `protruyen.com#%#//scriptlet("abort-current-inline-script", "Object", "$._Eu")` which matters, and that's the reason I got mislead, that was my mistake. That was the biggest piece of information though, because if the rule was the one you said, it wasn't going to work, but based on looking at the list, it does because it is the uBlock syntax being used for the rule, so Brave reads it.
> 
> cc @ryanbr - let's try to get this fixed upstream in ABPVN

anyway `scriptlet` handling of this rule is dangerous and it breaks some things like `Function`, `Object` (everything involved in test leads to regression)

**Comment by ryanbr** [comment]
Notifed list authors, and fixed.

https://github.com/abpvn/abpvn/commit/ee92635ad8a9a5ec51404a7e191ed5376d459c1d

Give it 24hrs to roll out.

**Comment by ryanbr** [comment]
Resolved? @tachibana-shin

**Comment by tachibana-shin** [comment]
> Resolved? @tachibana-shin

Yes. Thanks for the support!
