### ISSUE TITLE
Activity Route does not get Persisted after Unlock

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31111]
## Description 

The `Activity` route does not get persisted after unlocking the wallet

## Steps to Reproduce

   1. Open the `Wallet` and go to the `Activity` tab
   2. Lock the `Wallet`
   3. Unlock the `Wallet`, it goes to the `Portfolio` tab

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/66ff0e3d-d319-4fdb-8789-bdb1ce4fdd17

## Expected result:
`Activity` route should be persisted in the `sessionRoute` state to allow persisting after unlocking the `Wallet`.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from issue description
- Verified unlocking wallet from Activity page routes it back to Activity page instead of Portfolio page
- Encountered [#31153](https://github.com/brave/brave-browser/issues/31153)

https://github.com/brave/brave-browser/assets/17010094/a9dd6303-7acc-4de3-b75f-bcc0c5390a0b


---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified unlocking wallet from Activity page routes it back to Activity page instead of Portfolio page
- Encountered [#31153](https://github.com/brave/brave-browser/issues/31153)

https://github.com/brave/brave-browser/assets/17010094/b399d7a5-c58e-4215-9f7e-75413c6b4e6f


---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from issue description
- Verified unlocking wallet from Activity page routes it back to Activity page instead of Portfolio page

https://github.com/brave/brave-browser/assets/17010094/fa27e560-4621-4267-b7ac-171d2df97c04
