### ISSUE TITLE
VPN error state background colour isn't contained within the button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31190]
## Description 

VPN error state background colour isn't contained within the button

## Steps to Reproduce

   1. Trigger error state for VPN 
   2. Red background colour isn't contained within the button edges
   

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/5eab3477-3a8e-4546-9aed-8c4762d21b5d)

## Expected result:
![image](https://user-images.githubusercontent.com/6786187/240800018-ac4de1df-d7f2-4605-8892-457e210805f0.png)

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not checked
- Can you reproduce this issue with the beta channel? Not checked 
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @simonhong @sangwoo108 @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.54.89` or higher for `1.54.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.54.89 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 10 Version 22H2 (Build 19045.3155)
```

### Steps:
1. installed `1.54.89`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN`
4. turned `Airplane mode` on via `Windows 10`'s `Network` panel
5. waited
6. tried to switch servers
7. dismissed error messages
8. examined the state and color of the `VPN` button on the browser toolbar

### Confirmed when disconnected (due to network-interface issues such as disabling Wi-Fi, etc.), the `VPN` button changes to red, with a red warning-triangle icon

example | example | example | example
----------|----------|-----------|---------
![image](https://github.com/brave/brave-browser/assets/387249/ee1a8d9e-bf1a-4901-8c12-894a4b28ce3d) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/dbab8fb4-6217-4a77-b4f9-617b649ed681) | ![image](https://github.com/brave/brave-browser/assets/387249/64331e7f-7c2f-4e8f-8168-3d98e6d69054) | ![image](https://github.com/brave/brave-browser/assets/387249/8bf2ebf1-cf42-4542-90f7-dd62059cd881)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.54.90 Chromium: 115.0.5790.56 (Official Build) beta (x86_64)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | macOS Version 14.0 (Build 23A5276g)
```

example | example | example
---------|----------|--------
<img width="1707" alt="Screenshot 2023-07-03 at 2 25 47 PM" src="https://github.com/brave/brave-browser/assets/387249/dc7a496f-b260-48e4-95fb-2c1c380f9c11"> | <img width="109" alt="Screenshot 2023-07-03 at 2 24 21 PM" src="https://github.com/brave/brave-browser/assets/387249/1e8a3440-1a64-48de-a28b-e8cc6ea7fffd"> | <img width="109" alt="Screenshot 2023-07-03 at 2 24 32 PM" src="https://github.com/brave/brave-browser/assets/387249/a3215193-889f-4aa6-b811-b1cbe323d43c">
