### ISSUE TITLE
Using "Command + <" shortcut on macOS opens the Preferences tab

### ISSUE THREAD

**Issue by floze** [brave/brave-browser#31758]
## Description 

I'm using the "Command + <" shortcut on macOS to move focus between windows, which is an OS-level setting (the default would be "Command + ´"). Brave Browser 1.56.9 introduced the issue that it opens the Preferences / Settings tab when hitting that shortcut, no matter what. It can't even be overridden by OS-level app-specific shortcuts, which seems very strange.

## Steps to Reproduce

   1. Assign "Move focus to next window" macOS keyboard shortcut to "Command + <"
   2. Press "Command + <" in Brave Browser Desktop
   3. 

## Actual result:

Brave Browser preferences tab opens up

## Expected result:
Window focus should change to next window

## Reproduces how often: 

Always

## Brave version (brave://version info)

All versions _after_ 1.56.8 Release it seems

## Version/Channel Information:

Release, Beta and Nightly

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 
3x Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by fallaciousreasoning** [comment]
Hey @floze, thanks for filing! Do you know what keyboard layout you have?

**Comment by fallaciousreasoning** [comment]
Also, can you remove that shortcut from the page at `brave://settings/system/shortcuts`?

If not, you can disable the new shortcuts by turning of the `Brave Commands` flag at `brave://flags/#brave-commands` and restarting - hopefully that puts things back to normal :smile:

Would you mind helping me out trying to work out the root cause? If you could answer any of the following questions, it might help me track down the cause:
1. What language is your OS in?
2. What keyboard layout?
3. Do you have any custom shortcuts assigned via the system shortcuts manager for Brave?
4. Are any other shortcuts in Brave a bit weird?

**Comment by floze** [comment]
> 1. What language is your OS in?
macOS Big Sur version 11.7.8 (20G1351)

> 2. What keyboard layout?
ABC - QWERTZ / German (the "<" key is right next to "Left Shift")

> 3. Do you have any custom shortcuts assigned via the system shortcuts manager for Brave?
No custom shortcuts, all extensions disabled

> 4. Are any other shortcuts in Brave a bit weird?
No, this seems to be the only one for me

NB: Disabling the `Brave Commands` flag did indeed eliminate the behavior, thank you very much, Sir!

**Comment by fallaciousreasoning** [comment]
Okay, I'm glad you've got a workaround for now. I have a suspicion this is the same root issue as #31770

**Comment by jpuris** [comment]
Can reproduce this, but differently..


I use `cmd + shift + D` to trigger menu item "_Tab > Move Tab to New Window_" via macOS's

```
System Settings > Keyboard > Keyboard Shortcuts... > App Shortcuts
```

It used to function as expected as in activating the mentioned key combination, it would move the current tab to new window, but since last update, this is broken!

![CleanShot 2023-07-24 at 12 58 59@2x](https://github.com/brave/brave-browser/assets/4112811/230c98a5-9925-41e8-a84c-fb28cdb73620)

`cmd + shift + D` now triggers "bookmark all tabs" instead.

<img width="322" alt="CleanShot 2023-07-24 at 12 59 52@2x" src="https://github.com/brave/brave-browser/assets/4112811/5ed5eeb2-933a-4957-8ac6-a66fd7d0a7fa">

❗️ Not sure if relevant, but while Brave is the active app and I have selected the macOS menubar, it works as before the update.


✅️ Can confirm that currently the workaround is to disable _**Brave Commands**_ in brave://flags/#brave-commands.

**Comment by fallaciousreasoning** [comment]
@jpuris out of interest, does it work if you remove/change the `Bookmark All Tabs..` shortcut in System settings?

**Comment by jpuris** [comment]
> @jpuris out of interest, does it work if you remove/change the `Bookmark All Tabs..` shortcut in System settings?

Hi @fallaciousreasoning 

I've tested this on Brave Beta. No change.

```
[Version 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (arm64)](https://brave.com/latest/)
```

1. Assign `cmd + shift + D` to Brave Browser's `Move Tab to New Window` (No default)
2. Assign `cmd + shift + E` to Brave Browser's `Bookmark All Tabs..` (Default is `cmd + shift + D`)

<img width="422" alt="CleanShot 2023-07-25 at 10 02 43@2x" src="https://github.com/brave/brave-browser/assets/4112811/06f4b5e5-758e-4579-8f3a-56de5b1461f4">

<img width="699" alt="CleanShot 2023-07-25 at 10 00 15@2x" src="https://github.com/brave/brave-browser/assets/4112811/f394e14e-abe0-4c70-a261-5d979cae7ebb">

<img width="258" alt="CleanShot 2023-07-25 at 10 03 30@2x" src="https://github.com/brave/brave-browser/assets/4112811/748ecf5a-5035-4c23-b322-cce32c912de7">


When focusing Brave Browser's active window

- activating `cmd+shift+E` will run `Bookmark All Tabs..`
- activating `cmd+shift+D` will run `Bookmark All Tabs..`

When active _app_ is Brave Browser but focus is on macOS's menu bar, it will 

- activating `cmd+shift+E` will run `Bookmark All Tabs..`
- activating `cmd+shift+D` will run `Move Tab to New Window` _as expected_

**Comment by fallaciousreasoning** [comment]
Okay @jpuris, I think I know what's causing this. I'm working on a fix at the moment, but it might take a while to test/verify :smile: Thanks for your help!

**Comment by include** [comment]
had the same issue. disabling brave://flags/#brave-commands solved.

**Comment by jimmywarting** [comment]
This was a bit annoying for me as well. 
glad the workaround works with the `brave-commands` flag.
however, i would like do enable it again once there is a fix and it's released into a stable version. so i would like to get notified  when that happens.

seems like brave/brave-core#19464  have already fixed this issue? so it should just be a matter of a waiting game?

**Comment by fallaciousreasoning** [comment]
@jimmywarting you should be able to test it in Nightly. Mind letting me know if it works for your use case?

**Comment by jimmywarting** [comment]
Don't have Nightly, don't think i want to download it either, 
i'm just going to wait for it to hit stable. 
I'm not in a hurry

**Comment by fallaciousreasoning** [comment]
I've made an uplift for stable, so hopefully it'll be there in a week or so :smile:

**Comment by kjozwiak** [comment]
The above requires `1.57.57` or higher for `1.57.x` verification 👍
