### ISSUE TITLE
Guest window settings page background is in Dark theme by default

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31952]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/30747
Guest window settings page background is in Dark theme by default
## Steps to Reproduce

   1. Clean profile 1.58.51 CR 115
   2. Open a Guest window via hamburger menu
   3. Open brave://settings/ in Guest window
   4. Click on each settings page
   5. `Settings`, `History`, `Bookmarks` and `Download` page background is in Dark theme by default
   6. The page background should be light theme by default

## Actual result:

Guest window settings page background is in Dark theme by default
![image](https://github.com/brave/brave-browser/assets/38657976/2d169188-021d-435f-82ef-1e1b9698b171)

## Expected result:
The page background should be in light theme by default

![image](https://github.com/brave/brave-browser/assets/38657976/ffc8efaf-89e9-48c7-b2d9-6683c7b8562a)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.58.55 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)
-- | --
Revision | 34193c8918bf9f572cebc0ac8bf4a5ba1a102483
OS | Windows 10 Version 22H2 (Build 19045.3208)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by mkarolin** [comment]
This appears to be intentional. We set Private, Private with Tor, and Guest profiles to have `dark` color scheme on Windows and MacOS. See https://github.com/brave/brave-core/blob/master/browser/ui/views/frame/brave_browser_frame.cc#L29

<pre>
#if BUILDFLAG(IS_WIN) || BUILDFLAG(IS_MAC)
// Tor/Guest profile should use DarkAura. If not, their native ui is affected by
// normal windows theme change.
const ui::NativeTheme* BraveBrowserFrame::GetNativeTheme() const {
  if ((view_->browser()->profile()->IsIncognitoProfile() ||
       view_->browser()->profile()->IsTor() ||
       brave::IsGuestProfile(view_->browser()->profile())) &&
      ThemeServiceFactory::GetForProfile(view_->browser()->profile())
          ->UsingDefaultTheme()) {
    return ui::NativeTheme::GetInstanceForDarkUI();
  }
  return views::Widget::GetNativeTheme();
}
#endif

However, WebUI wasn't following this setting until the fix introduced in `Chromium 116` https://source.chromium.org/chromium/chromium/src/+/c6b1f22dbe7db922f5064272de4447bf4d5b777f, so now WebUI will follow our color scheme setting for Guest profile.
