### ISSUE TITLE
F6 focuses first tab instead of omnibox/address bar

### ISSUE THREAD

**Issue by joel0** [brave/brave-browser#3204]
## Description 
The F6 keyboard shortcut should focus the omnibox/address bar to be consistent with Chome, Firefox, Edge, and IE.  Instead, it is focusing the first tab.

## Steps to Reproduce
   1. Navigate to any website.
   2. Press F6.
   3. Notice the focus selection is not in the omnibox.

## Actual result:
There's a selection rectangle around the first tab.
![image](https://user-images.githubusercontent.com/8691351/52180974-11ee4280-27b2-11e9-9929-fbf5c17ca209.png)

## Expected result:
All the text in the omnibox should be selected.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)

Brave | 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit)
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Have not tried on any other version or OS.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
No

### Additional Information
There were some similar issues in 2017/2018, but it looks like their symptoms were slightly different (no result instead of tab selection): https://github.com/brave/browser-laptop/issues?q=is%3Aissue+f6+is%3Aclosed

**Comment by srirambv** [comment]
Are you sure its not the same on Chrome becuase I see the same behaviour on `Google Chrome | 72.0.3626.81 (Official Build) (64-bit)`. So I don't think its a Brave bug. Here's what I see on Chrome and Brave
1. First F6 press focuses on first tab
2. Second F6 focuses on omnibar
3. Third F6 focuses on bookmarks bar 
4. Fourth F6 focuses on active frame 

Don't think this is a bug on our end. Might be a upstream bug that should get fixed on Chromium unless its expected behaviour on Chromium.

Closing the issue but feel free to discuss and we can reopen if it is something that we can fix 

cc: @bbondy @rebron

**Comment by joel0** [comment]
Looks like a new feature in Chrome 72.  I'm pretty sure I tested in Chrome 71 earlier today before I got the update.  Thanks for the quick response.

**Comment by pabrams** [comment]
It's not a feature, it's a bug.  F6 is for address bar.

**Comment by joel0** [comment]
I agree with you that it's a bug, and so do the Chrome(ium) developers (the upstream project of Brave).  The good news is that Chrome has been fixed in the beta version (74).  In about 18 days (April 23), that version of Chrome will be stable and I assume Brave will quickly switch to that version, also fixing the bug.
