### ISSUE TITLE
Redesign Brave Wallet main layout introducing latest material 2 components

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#32197]
<img width="500" alt="Screenshot 2023-08-11 at 11 06 59 AM" src="https://github.com/brave/brave-browser/assets/3308503/f5f89b96-6046-46f9-83ae-22fcd1d480e9">

## Description

[Figma design](https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=5164-359379&mode=design&t=RNnDCszUgOh6cXjt-0)

Remove tab layout in favor of [bottom navigation view](https://m2.material.io/components/bottom-navigation).
Introduce gradient indicator with transition animation when tapped.

Add [app bar layout](https://m2.material.io/components/app-bars-top) and rewrite layout to scroll correctly.

Show and hide bottom navigation view with proper animation.

Tweak FAB behavior and animation on scrolling.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.59.102 x64 beta build
- Verified steps from [brave/brave-core#19650](https://github.com/brave/brave-core/pull/19650)
- Verified new bottom navigation bar is shown instead of old tabs at top
- Verified scrolling through tokens list auto-hides the bottom navigation bar
- Verified banner is shown with bottom margin and separator line
- Verified switch between items on the bottom navigation bar has a smooth transition 
- Verified FAB button follows navigation bar when auto-hides or auto-shows
- Verified app bar is shown as a sticky header when scrolling through the token list
- Encountered [#33312](https://github.com/brave/brave-browser/issues/33312)

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/a73f6b96-c3b6-4771-9091-db1b231df03a> | <video src=https://github.com/brave/brave-browser/assets/17010094/cd3e6923-5241-400f-a212-c1ad72cdad13>
<video src=https://github.com/brave/brave-browser/assets/17010094/1e141e77-26a8-4594-86fb-aebc84edff16> | <video src=https://github.com/brave/brave-browser/assets/17010094/847198de-632c-4644-9917-b679e90245e8>
