### ISSUE TITLE
[hackerone] #492048 - .onion domains leaks

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3249]
https://hackerone.com/bugs?report_id=492048

Test Plan (windows only):

* Go to a non-existent site like dklfjdkafjdkafj.com in a regular tab
* You should see a link that says 'Running Windows Network Diagnostics'
* Repeat in a private tab; you should not see this link
* Repeat in a tor tab; you should not see this link

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1605

Regular Window
![image](https://user-images.githubusercontent.com/34715963/53379168-ca01ac00-3968-11e9-8b37-ef4c8bbb9d74.png)

Private Window
![image](https://user-images.githubusercontent.com/34715963/53379175-d6860480-3968-11e9-9cf3-3815d0119663.png)

Private Window with Tor
![image](https://user-images.githubusercontent.com/34715963/53379211-06cda300-3969-11e9-8ae1-b491467c893e.png)

Guest Window
![image](https://user-images.githubusercontent.com/34715963/53379270-409ea980-3969-11e9-8f11-94b2fce91e01.png)
@jumde confirmed this is expected behavior for Guest Window.
