### ISSUE TITLE
WireGuard VPN  doesn't reconnect after crash

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#32520]
## Description 

If Wireguard service was killed or crashed and restarted by the system it will not be reconnected to vpn. There is an error 
"requested GUID is already in use" in wireguard logs. Looks like known problem with releasing interfaces and there are many complains in the internet around it.

## Steps to Reproduce

   1. Connect to Wireguard
   2. Kill `brave_vpn_wireguard_service.exe` with `--connect` command line by task manager
   3. See `brave_vpn_wireguard_service.exe` is restarted.

## Actual result:

- VPN is not connected and the service stopped after few seconds.

## Expected result:

- VPN reconnected after restart.

## Reproduces how often: 

100% 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave	1.59.94 Chromium: 117.0.5938.88 (Official Build) beta (64-bit) 
Revision	2dca22d0a20096c32df5af4c88700a0b31acb55c
OS	Windows 10 Version 22H2 (Build 19045.3448)
```

### Steps:
1. installed `1.59.94`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN` using `account.bravesoftware.com`
4. opened `Task Manager` with `ctrl` + `alt` + `del`
5. confirmed `brave_vpn_wireguard_service.exe` was running
6. selected the process
7. clicked `End Task`
8. noticed a "blip" in the list of processes as the service restarted
9. confirmed I was still connected to `Brave VPN`
10. changed servers/region

### Confirmed brave_vpn_wireguard_service.exe auto-restarted after killing the individual processes, without interrupting my `Brave VPN` connection (until I hit `IKEv2 fallback` dialog, see bottom)

`service running` | `service killed` | `during service restart` | `service running, auto-restarted`
---------|----------|---------|---------
 ![image](https://github.com/brave/brave-browser/assets/387249/8e1bc175-6e58-4806-95c2-ac62310b7071) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/3c95625e-afc5-42f8-88a4-0f62b544b2f7) | ![image (2)](https://github.com/brave/brave-browser/assets/387249/e5b5090d-6a3d-4764-be4a-783383c39b8e) | ![image (3)](https://github.com/brave/brave-browser/assets/387249/1c5fc0bf-b8f3-4eba-919a-8a08ffa4fc79)

In the course of testing, I also triggered the `IKEv2` fallback dialog, because I killed `brave_vpn_wireguard_service.exe` one too many times 👍

**Comment by GeetaSarvadnya** [comment]
## Verified `INPROGRESS` using 

```

```

### Steps:
1. installed `1.59.94`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN` using `account.bravesoftware.com`
4. opened `Task Manager` with `ctrl` + `alt` + `del`
5. confirmed `brave_vpn_wireguard_service.exe` was running
6. selected the process
7. clicked `End Task`
8. noticed a "blip" in the list of processes as the service restarted
9. confirmed I was still connected to `Brave VPN`
10. changed servers/region

### Confirmed brave_vpn_wireguard_service.exe auto-restarted after killing the individual processes, without interrupting my `Brave VPN` connection (until I hit `IKEv2 fallback` dialog, see bottom)

`service running` | `service killed` | `during service restart` | `service running, auto-restarted`
---------|----------|---------|---------
