### ISSUE TITLE
Install Arm64 Brave from x64 online installer on Arm64 Windows

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#32598]
This is a sub-task of #29112. It is completed when running Brave's standard 1 MB online installer (which is x64) installs Arm64 (not x64) Brave on Arm64 Windows.

A simple test shows that if the update server just returns the Arm64 installer in response to an update request from Arm64 Windows, then the goal of this issue can be achieved.

We should likely not migrate existing users on x64 Brave on Arm64 Windows. The reason for this is that it breaks Widevine.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.61.58 Chromium: 119.0.6045.59 (Official Build) beta (64-bit)
-- | --
Revision | 5ea3c79ab0ac624e35d544390d30af2666b09048
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

- uninstalled all of the brave channels (Release, Beta and Nightly) via Control panel
- downloaded `BraveBrowserStandaloneBetaSetup.exe` from https://github.com/brave/brave-browser/releases/download/v1.61.58
- Installed Brave with Admin rights
- opened `brave://version`

### Confirmed correct architecture: since this is `x64 windows` - `64-bit` is shown on the page




![image](https://github.com/brave/brave-browser/assets/98358127/0069391b-f300-44e2-b8ad-451b77a3408b)

**Comment by MadhaviSeelam** [comment]
### Win arm64

Verification `In progress` using
```
Brave | 1.61.58 Chromium: 119.0.6045.59 (Official Build) beta (64-bit emulated)
-- | --
Revision | 5ea3c79ab0ac624e35d544390d30af2666b09048
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

- uninstalled all of the brave channels (Release, Beta and Nightly) via Control panel
- downloaded `BraveBrowserStandaloneBetaSetup.exe` from https://github.com/brave/brave-browser/releases/download/v1.61.58
- Installed Brave with Admin rights
- opened `brave://version`

Actual results:  Got `64-bit` instead of `arm64`

<img width="430" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/18e4f5d0-eb72-4965-8438-554195aa6302">

**Comment by MadhaviSeelam** [comment]
Not adding `QA Pass-Win 64` yet as the `x86` testing is remaining.  
@LaurenWags @kjozwiak

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.61.67 Chromium: 119.0.6045.105 (Official Build) beta (32-bit) 
Revision	09cc687dc27ccd8acafeebf5af1dc620b4d9cb22
OS	Windows 10 Version 22H2 (Build 19045.3570)
```

**Comment by LaurenWags** [comment]
@brave/qa-team added `QA/Blocked` just so we check this one more time once 1.61.x moves to the Release Channel 👍🏻

**Comment by kjozwiak** [comment]
@LaurenWags removing `QA/Blocked` as `1.61.93` is currently building which is the first `1.61.x` RC 👍

**Comment by LaurenWags** [comment]
Verification on hold (pending confirmation):

- Started with a clean Win 10 x86 VM (Brave never installed)
- Downloaded `BraveBrowserSetup.exe` from https://github.com/brave/brave-browser/releases/download/v1.61.93 (used Edge)
- Installed Brave with Admin rights, confirmed no errors shown while installing
- Opened `brave://version`, confirmed expected architecture - `32-bit` was shown
- Closed and relaunched, confirmed griffin seed was fetched
- Closed and relaunched a couple more times to ensure no errors

### Confirmed correct architecture on `x86 windows` - `32-bit` is shown

Note, since stub installer pulls latest released version, even though I grabbed the stub from 1.61.93, I got the release channel version 1.60.125:

<img width="1035" alt="Screenshot 2023-11-30 at 1 51 56 PM" src="https://github.com/brave/brave-browser/assets/28145373/7e99135c-64ca-48f3-b4b0-59173b17bfdc">

**Comment by MadhaviSeelam** [comment]
Verified on Win 11 arm64 (Physical machine)


- Started with a clean Win 11 arm64 (All Brave versions are uninstalled via Brave Manager)
- Downloaded `BraveBrowserSetupArm64.exe` from https://github.com/brave/brave-browser/releases/download/v1.61.93/BraveBrowserSetupArm64.exe (used Edge)
- Installed Brave with Admin rights, confirmed no errors shown while installing
- Opened `brave://version`, confirmed expected architecture - `arm64` was shown
- Closed and relaunched, confirmed griffin seed was fetched
- Closed and relaunched a couple more times to ensure no errors

### Confirmed correct architecture on `arm64 windows` - `arm64` is shown

Note, since stub installer pulls the latest released version, even though I grabbed the stub from 1.61.93, I got the release channel version 1.60.125:


![image](https://github.com/brave/brave-browser/assets/98358127/4b1fa36e-916a-4154-a912-045513b29aab)

**Comment by MadhaviSeelam** [comment]
Verified on Win 11 x64 (Physical machine)


- Started with a clean Win 11 x64 (All Brave versions are uninstalled via Brave Manager)
- Downloaded `BraveBrowserSetup.exe` from https://github.com/brave/brave-browser/releases/download/v1.61.93/BraveBrowserSetup.exe (used Edge)
- Installed Brave with Admin rights, confirmed no errors shown while installing
- Opened `brave://version`, confirmed expected architecture - `64-bit` was shown
- Closed and relaunched, confirmed griffin seed was fetched
- Closed and relaunched a couple more times to ensure no errors

### Confirmed correct architecture on `x64 windows` - `64-bit` is shown

Note, since stub installer pulls the latest released version, even though I grabbed the stub from 1.61.93, I got the release channel version 1.60.125:


<img width="444" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5eba630d-dc81-4fcd-b768-89b4f0180930">

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.61.100 Chromium: 120.0.6099.62 (Official Build) (arm64)
-- | --
Revision | 63d361b4e5fd163e032192aa8e033cf85f846575
OS | Windows 11 Version 23H2 (Build 22631.2792)
```

Scenario 1:  Download via Github

1. uninstalled all of the brave channels (Release, Beta and Nightly) via Control panel
2. downloaded `BraveBrowserSetup.exe` from https://github.com/brave/brave-browser/releases/download/v1.61.100/BraveBrowserSetup.exe
3. Installed Brave with Admin rights
4. opened brave://version

#### Confirmed correct architecture on arm64 windows - arm64 is shown

<img width ="400" alt="Image" src="https://github.com/brave/brave-browser/assets/98358127/49d679e2-fb05-452b-a44e-58d5d7f16ba9">

Scenario 2:  Download via website on Edge (brave.com/download)

1. uninstalled all of the brave channels (Release, Beta and Nightly) via Control panel
2. downloaded `BraveBrowserSetup-BRV002.exe` from brave.com/download via Edge
3. Installed Brave with Admin rights
4. opened brave://version

Actual results:  shown `(64-bit emulated)` on arm64 windows

<img width ="400" alt="Image" src="https://github.com/brave/brave-browser/assets/98358127/5b7c0427-a4af-4293-aa2b-6716cfb72dff">

**Comment by MadhaviSeelam** [comment]
@mherrmann since `1.61.100` is released officially an hour ago, verified the issue by downloading and installing `Brave` via website & github on both `Win 11 x64` & `Win 11 arm64`.

 `Win 11 x64` shows correct architecture in brave://version page - ✅ 
 
`Win 11 arm64`, when downloaded and installed `Brave` via website (brave.com/download on Edge), I see 64-bit emulated) on arm64 windows on brave://version page.  - (PS: please see scenario 2 of https://github.com/brave/brave-browser/issues/32598#issuecomment-1843791943) 

However, when downloaded and installed via github page, correct architecture is shown on brave://version  page, i.e. `arm64`

**Comment by mherrmann** [comment]
Great catch @MadhaviSeelam. Thank you! I will look into updating the installer on the web site.

**Comment by mherrmann** [comment]
This should be fixed @MadhaviSeelam. Can you try again?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.61.101 Chromium: 120.0.6099.71 (Official Build) (arm64)
-- | --
Revision | a2125180c183a2b5775b45c2138fda37d240b773
OS | Windows 11 Version 23H2 (Build 22631.2792)
```


1. uninstalled all of the brave channels (Release, Beta and Nightly) via Control panel
2. downloaded BraveBrowserSetup-BRV002.exe from brave.com/download via Edge
3. Installed Brave with Admin rights
4. opened brave://version

#### Confirmed correct text shown i.e. arm64 on brave://version page for Win 11 arm64 


![image](https://github.com/brave/brave-browser/assets/98358127/43069d2c-5d47-4161-89ba-b7f395d50d06)

**Comment by LaurenWags** [comment]
@MadhaviSeelam @GeetaSarvadnya thanks for checking now that 1.61.x is released 👍🏻 

I'll still have to check x86, but won't be able to do that until we have x86 builds for 1.61.x.

**Comment by LaurenWags** [comment]
Verified on Win 10 x86 (VM):

- Started with a clean Win 10 x86 VM (Brave never installed)
- Downloaded `BraveBrowserSetup32-BRV002.exe` from brave.com (used Edge)
- Installed Brave with Admin rights, confirmed no errors shown while installing
- Opened `brave://version`, confirmed expected architecture - `32-bit` was shown
- Closed and relaunched, confirmed griffin seed was fetched
- Closed and relaunched a couple more times to ensure no errors

### Confirmed expected architecture on `x86 windows` - `32-bit` is shown

<img width="1174" alt="Screenshot 2023-12-18 at 9 08 27 AM" src="https://github.com/brave/brave-browser/assets/28145373/5a17ad12-33b7-45dd-8789-a2877a64e80e">
