### ISSUE TITLE
Account selection is not available in V2 panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32643]
## Description 

Account selection is not available in V2 panel

## Steps to Reproduce

   1. Enable V2 panel flag 
   2. Connect wallet to a Dapp
   3. Open Panel, active account details are not listed for switching

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/3018643e-e959-4e03-a5ea-eb33b9ed288a

## Expected result:
Should show account selection option similar to V1 panel

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @darkdh @Douglashdaniel

**Comment by darkdh** [comment]
after meeting, we conclude that missing that flow is not a blocker but we need some improvements
1. A indicator showing current active account
2. Whenever users click connect, show permission duration confirmation (currently if users click it, we just set it forever)

If you want to do something like just switch without giving permission you can connect that account and disconnect it to get it selected. Because there is no good use case that users switching account on a dApp but don’t want to give it permission.

**Comment by Douglashdaniel** [comment]
New design to implement the `UI Improvements` mentioned by @darkdh 

![Screenshot 54](https://github.com/brave/brave-browser/assets/40611140/7922c40c-73b8-4e39-8769-0704b7f7be46)

**Comment by darkdh** [comment]
> whenever users click connect, show permission duration confirmation (currently if users click it, it just set it forever)

This needs core work so we can support permission duration for panel connect
When we connect from panel, we directly write into content settings directly but in order to set duration we need to have a request first like dApp initiated one and our provider implementation will generate request into chromium permission system.
The tracking mechanism is embedded into permission system not content settings. (When it checks duration expired, system removes it from content settings)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.61.85 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | 5e2736df90772dd1b66ca5013e47c1fc467c9762
OS | Windows 11 Version 23H2 (Build 22631.2715)

- Verified steps from [brave/brave-core#20008](https://github.com/brave/brave-core/pull/20008)
- Verified permission prompt is shown when connecting to an account
- Verified closing the dapp/window removes the connection under `brave://settings/content/ethereum` and `brave://settings/content/solana` after 30sec of closing the Dapp
- Verified `Active` indicator is shown on connected account

https://github.com/brave/brave-browser/assets/17010094/b94f9cad-b31e-4f2d-99cc-e5bae6249158
