### ISSUE TITLE
My old sync phrase has expired

### ISSUE THREAD

**Issue by KavyanshJain** [brave/brave-browser#32674]
Rectenly my pc run into some serious problems and I brought a new one and complete setup on it and while I was starting brave the sync code which I stored for a long time is now showing expired and I cannot make any other code because no access to old login brave
Is there any solution like reusing the expired sync code

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
Brave only changes 25th word daily, but the first 24 words stay the same.
You can use https://alexeybarabash.github.io/25th-brave-sync-word/ to get the daily word.

**Comment by KavyanshJain** [comment]
Thanks bro you saved my day

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
Well, this is not a forum, you need to close the issue.
Also, anything like this would be better in community.brave.com, where you could have searched and find the same information and where these type of questions would be better placed since there is support that can help you with it, since Github is seen mostly for the development, bug reports, some feature requests and more development type of things.
