### ISSUE TITLE
Unable to import JSON file from panel or connect HW wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32748]
## Description 

Unable to import JSON file from panel or connect HW wallet

## Steps to Reproduce

JSON Import
   1. Enable V2 panel flag
   2. Select accounts tab
   3. Select menu and click on `Import account`
   4. Select Eth and select JSON file import
   5. Click on `Choose file`
   6. File explorer is not loaded 

Hardware Wallet Import
   1. Enable V2 panel flag
   2. Select accounts tab
   3. Connect Ledger and select menu and click on `Connect a hardware wallet`
   4. Select ETH and select Ledger
   5. Click on `Authorize`, doesn't show up the webconnect modal
   6. Connect Trezor and select `Trezor`
   7. Doesn't load the Trezor connect approval screen

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/6bff884a-2e56-432d-8539-739762ae00ff

## Expected result:
Should be able to open import file window and able to connect hardware wallets via panel

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | 21631edab5a70964c2f5817bfa4d06c32b4ab314
OS | Windows 11 Version 22H2 (Build 22621.2215)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No, it opens the wallet page for import

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard

**Comment by Douglashdaniel** [comment]
- Import with `JSON` file was fixed by: https://github.com/brave/brave-core/pull/19871
- Connect Hardware Wallet was addressed by: https://github.com/brave/brave-core/pull/19882 and was decided to just expand to full view for now. We have a follow up issue to not have to expand here https://github.com/brave/brave-browser/issues/31837

Both of these are in `1.59.x` which is also where `Enable Panel V2 by Default`: https://github.com/brave/brave-core/pull/19751 landed, so these do not need to be fixed in `1.58.x` Beta 

Closing as `Duplicate` and `Invalid`
