### ISSUE TITLE
Remove `Hide VPN button in toolbar` and `Hide VPN try icon` vpn menu entries 

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#33027]
We'll only have `Show VPN button in toolbar` and `Show VPN try icon` in vpn app menu as user can hide from their UI.

**Comment by kjozwiak** [comment]
The above requires `1.59.100` or higher for `1.59.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.59.100 Chromium: 117.0.5938.92 (Official Build) beta (x86_64)
-- | --
Revision | 3243fffc43431ab8677e8139859670b4cd2df843
OS | macOS Version 14.0 (Build 23A344)
```

### Steps:
1. installed `1.59.100`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN`
4. clicked on the "hamburger" menu -> `Brave VPN` flyout
5. examined the menu items


### Confirmed
*  removal of the `Hide VPN button in toolbar` menu item
 * `Show VPN tray icon` is now dynamic

### _`1.59.100`_ - `Brave VPN` tray icon hidden

#### **_with_** `Show VPN tray icon` 

`Light` | `Dark`
-------|-------

### _`1.59.100`_ - `Brave VPN` tray icon shown

#### **_WITHOUT_** `Show VPN tray icon`  (because it's showing in the system-tray)


To remove the above icon, click on `Remove icon` after context-clicking it

`Light` | `Dark`
-------|-------



### _`1.69.99`_

`Light` | `Dark`
-------|-------

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.59.100 Chromium: 117.0.5938.92 (Official Build) beta (64-bit)
-- | --
Revision | 3243fffc43431ab8677e8139859670b4cd2df843
OS | Windows 10 Version 22H2 (Build 19045.3448)
```

### Steps:
1. installed `1.59.100`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN`
4. clicked on the "hamburger" menu -> `Brave VPN` flyout
5. examined the menu items


### Confirmed
*  removal of the `Hide VPN button in toolbar` menu item
 * `Show VPN tray icon` is now dynamic

### _`1.59.100`_ - `Brave VPN` tray icon hidden

#### **_with_** `Show VPN tray icon` 

`Light` | `Dark`
-------|-------
![image](https://github.com/brave/brave-core/assets/387249/565a0465-b693-422a-a249-a7e3735356fd) | ![image](https://github.com/brave/brave-core/assets/387249/182d4e30-f64b-4416-9f9f-d4a780c71462)

### _`1.59.100`_ - `Brave VPN` tray icon shown

#### **_WITHOUT_** `Show VPN tray icon`  (because it's showing in the system-tray)

![image](https://github.com/brave/brave-browser/assets/387249/f0258056-7c22-447b-b770-c23672af866b)


To remove the above icon, click on `Remove icon` after context-clicking it

`Light` | `Dark`
-------|-------


### _`1.69.99`_

`Light` | `Dark`
-------|-------

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.59.101 Chromium: 117.0.5938.92 (Official Build) beta (64-bit)
-- | --
Revision | 81840f55490b042e3c7a75e0cba633580ed5a1b6
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

### Steps:
1. installed `1.59.101`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN`
4. clicked on the "hamburger" menu -> `Brave VPN` flyout
5. examined the menu items

### Confirmed
*  removal of the `Hide VPN button in toolbar` menu item
 * `Show VPN tray icon` is now dynamic

### _`1.59.101`_ - `Brave VPN` tray icon hidden

#### **_with_** `Show VPN tray icon` 

`Light` | `Dark`
-------|-------
<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9807f08d-e998-432d-a8ee-052eec6006f7">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e12f9610-aff5-4233-9bcc-3fba205826a7">

### _`1.59.101`_ - `Brave VPN` tray icon shown

#### **_WITHOUT_** `Show VPN tray icon`  (because it's showing in the system-tray)

`Light` | `Dark`
-------|-------
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/271eb711-915c-463f-8d9a-4242da400ad6">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f987ba59-10b8-41b9-acfc-b64b1607cd95">

To remove the above icon, click on `Remove icon` after context-clicking it

`Light` | `Dark`
-------|-------
<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a0c6cf28-867b-439b-a873-89037a9a0ca2">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b343b8d9-4d0f-458f-8eb1-a19c86c8fa47">
