### ISSUE TITLE
Intrusive calls to /feed and /comments/feed, without any request to call them

### ISSUE THREAD

**Issue by crankedguy** [brave/brave-browser#33062]
## Description 
Every time I call a page on my Wordpress website Brave adds 2 additional and intrusive calls under the hood to https://domain.com/feed and https://domain.com/comments/feed. Please see detailed explanation and analysis below

## Steps to Reproduce
request a page from the website in the browser (standard window, not incognito)

## Actual result:
one request to open the requested page, and 2 additional requests to /feed and /comment/feed
reproducible every single time, please see detailed explanation in "other information"

## Expected result:
Exactly one call, namely to open the requested page, and not 2 additional calls to /feed and /comments/feed

## Reproduces how often: 
Always, just call a (any) single page of the website

## Brave version (brave://version info)
Revision	5c0e98018fb16948401122cb9af1a5a0a6b40865
OS	Windows 10 Version 22H2 (Build 19045.3324)

## Other Additional Information:
This happens for every page as said, is reproducible with every single call. 
Not only does this spam my server logs, but also messes up my analytics logs completely. 
These calls happen completely under the hood and cannot even be seen by developer tools/network recording. 
You can only see it in the server and analytics logs. It is cross-tested with several other browsers where this clearly does not happen (Chrome, 2 different Chromium versions and builds, and Firefox). 
This is highly intrusive in my eyes and has to be fixed. 
Or, if you know from which setting this comes from, tell me how to turn it off please. I do not want to go the lengths now and record this in Wireshark as it can be clearly seen in the server logs that this is client-triggered, where it does not happen in any other browser. My logfiles are completely cluttered.
I tested this further. 
It does not happen in Incognito mode. 
So in incognito it works as supposed to, like from any other browser.
The indication that these are in fact under-the-hood calls is even more clear because both of these calls always receive a 401 (the site is under basic_auth currently). 
So they are not seen from developer tools (ofc, they are not user triggered and are nowhere in any of the website code) and they receive a 401 although basic_auth is done in the browser window itself. 
Meaning if you directly call them (/feed or /comments/feed) from the address line they are returned with a 200, as supposed to.

I suppose that this might be some rogue code from your (Speed)reader functionality, which is turned off in fact in the settings.
Anyways,, this is not ok.

Please get back to us on that matter.

**Comment by rebron** [comment]
cc: @fallaciousreasoning Brave News?

**Comment by crankedguy** [comment]
Is it possible to get a reaction to that please? We cannot write a banner to users please don't use Brave without private mode because in normal mode it does things you don't know about which a normal browser shouldn't.
No offense but even if this is not strictly a privacy issue it leaves a somehow sour aftertaste. This is something Google would do under the hood but not a privacy browser.

There has to be a possibility to switch that off.

**Comment by petemill** [comment]
@crankedguy We can assume that those URLs are being advertised from your site as RSS feed urls via `<link rel="alternate">` elements. Brave treats these elements as a resource since it has a built-in RSS Reader (called "Brave News"). Your browser is downloading them in order to find out whether the feed is valid and what the titles are. It then offers you to subscribe to them via the button in the Location Bar:
![image](https://github.com/brave/brave-browser/assets/741836/854372aa-b7d9-4169-b13c-5de8248268da)

There is an option available to you with the current version of Brave:
- Prevent your website from containing the `<link rel="alternate"` elements if you don't wish users to discover your RSS feeds.

At the same time, there are a couple more options coming up in a future Brave version:
- Turn off Brave News _(New Tab Page -> Customize -> Brave News -> Toggle it off)_ https://github.com/brave/brave-browser/issues/31019
- An optimization where we don't download the linked feeds until the user clicks on the location bar button. We'll use the existance of the `<link rel="alternate">` elements to determine whether the icon should show, but won't process then until the icon is clicked. https://github.com/brave/brave-browser/issues/33246

**Comment by crankedguy** [comment]
@petemill Thanks for your reply on that. Yes they are on the page with rel="alternate", although it is not to be considered standard behavior as said that these are just accessed without a user asking for it (e.g. plugin, dedicated installed reader etc.)

If something is toggled off I expect it to not having any under-the-hood behavior.
That is why #31019 you mentioned is what one can consider "standard" from our point of view.

Thanks for clarifying that there are options for that coming up that access these resources only at users settings/wish.
