### ISSUE TITLE
No system wide silent installer

### ISSUE THREAD

**Issue by ydfdas1f546g1df** [brave/brave-browser#33084]
## Description

The standalone silent installer dont install it to all users

## Steps to Reproduce

   1.  Open cmd as Administrator
   2.  Input path to BraveBrowserStandaloneSilentSetup.exe
   3.  Wait

## Expected result:

installed systemwide

## Reproduces how often: 

every time

## Brave version (brave://version info)
Installer for 1.58.127

## Version/Channel Information:
not tested

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
This would be terrible if that was the case, especially since Winget will use the SilentSetup for its thing... imagine depending on if you opened terminal with or without admin rights.

Brave doesn't have msi, which would make deploying better, but if you want to silently install Brave systemwide, use the normal Standalone version as `BraveBrowserStandaloneSetup /silent /install` and done.
It will only only work if you start terminal as admin the terminal, as well.

**Comment by mherrmann** [comment]
I believe this is a duplicate of #18711 and am closing this issue.

**Comment by Adhjie** [comment]
@ydfdas1f546g1df 
Old I know but here's a solution for you and future readers:
https://github.com/brave/brave-browser/issues/18711#issuecomment-2993703577
