### ISSUE TITLE
[ads] Filter eligible ads that do not match top segments

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#33123]

**Comment by tmancey** [comment]
We get this for free if you disable exploration based on the current v2 serving pipelines, however if we plan to keep exploration (which would be needed for other signals in the future) then we need to implement this to improve the quality of ads served to users.

**Comment by tmancey** [comment]
We get this for free if you disable exploration based on the current v2 serving pipelines; however, if we plan to allow the serving scoring function to incorporate any other input variables outside of segment matches, then we need to implement this to improve the quality of ads served to users.

**Comment by tmancey** [comment]
@ptjames @iambrianfung blocking as unless we decide to add additional input variables this can be achieved by setting the Griffin params to 0.0 as discussed above.

**Comment by tmancey** [comment]
@iambrianfung to discuss with stakeholders

**Comment by ptjames** [comment]
This could be important down the line, but it’s not priority 1. For now we can use Griffin as @tmancey described above; however, if the November test shows that exploration is undesirable, we should probably not rely on the ads serving function coefficients via Griffin to disable exploration. This because we will want to eventually add other features to the ads serving function, which could have the effect of enabling exploration again, if no explicit filtering is incorporated in the eligible ads set creation.

**Comment by tmancey** [comment]
Closing issue as discussed with @ptjames and this can be achieved with prediction weights
