### ISSUE TITLE
Ad block doesn't work

### ISSUE THREAD

**Issue by tech5588** [brave/brave-browser#33452]
The Ad block doesn't work when I build the app from source code.

[Version 1.60.77 Chromium: 118.0.5993.32 (Developer Build) (arm64)](https://brave.com/latest/)

![image](https://github.com/brave/brave-browser/assets/147116112/1ea1fdac-b9f1-4aba-9aa1-df9bc487972c)
![image](https://github.com/brave/brave-browser/assets/147116112/1a2934f9-e080-4a83-917a-467877d110cb)

**Comment by dpthegrey** [comment]
does setting it to `Aggressively block trackers & ads` work?

**Comment by tech5588** [comment]
It doesn't work either.

![image](https://github.com/brave/brave-browser/assets/147116112/6469c174-d6a0-462c-a25c-859bac311c65)

**Comment by tech5588** [comment]
Filter lists are empty in Content Filters.
Does it cause any problems to block ads?

![image](https://github.com/brave/brave-browser/assets/147116112/094b7b70-e83d-4a0d-9d96-386bb77fa71d)

**Comment by tech5588** [comment]
Ad blocking doesn't work even if I created custom filters.
I added below one as the custom filters.
https://secure.fanboy.co.nz/fanboy-cookiemonster_ubo.txt
![image](https://github.com/brave/brave-browser/assets/147116112/ec4cb1af-fcda-4f39-bad4-c69a08fd1a3b)

**Comment by Emi-HoloGhostRevisionist88** [comment]
When you build from source you don't get access to the lists, because you don't have access to Brave servers.
You have to manually add the lists, you can take a look at the https://github.com/brave/adblock-resources/blob/master/filter_lists/list_catalog.json anything in `"url":` in the Default section is what matters the most.

Where are you testing your 'custom adblocking rules'? only because you are copying and pasting the Easylist Cookie list, doesn't mean you are actually using the list, plus, Cosmetics, which are mostly in the Cookie list, don't count for the adblocking counter, only Network Request filters = `||example.com^`, anything else, cosmetics, action operators, scriptlet injections are not going to be added to the count.
Pretty much Brave Shields will count what Devtools Network tab blocks, but only once, same URLs don't get re-counted.

Make a proper test, if you are going to say "Adblocker doesn't work" then make a simple test ||brave.com^ and go to brave.com and then the whole thing should be blocked, if you go to Brave.com.
You can also use pages like this https://testpages.adblockplus.org to test the adblocker, since it gives you rules and tells you what you have to say.
It is good if you understand the principles of adblocking like 1p vs 3p and how it matters for rules, like `||brave.com^` would only block 1p network connections but not any other 3p, because the left part of a rule will pretty much see the URL of the network connection, any right side part of the rule will change things around like using .com$3p will block any third party connection that has .com in any part of the URL. If you do a `*$domain=brave.com` will block all connections from brave.com

Also, Aggressive mode doesn't matter when you are adding Custom filters or Custom lists, it only matters for Default lists which you can't use for building from source.

So make simple changes, or are proper Custom Filters to the adblocker, and don't use lists that have tons of cosmetics, because cosmetics in Brave adblocker are not easy to know when it is applied unless you know the rules. All cosmetics do is add `display: none !important` to the HTML elements, they don't get blocked or anything, Brave doesn't have a logger like uBlock, but that shouldn't matter in most cases.

I mean, do you even get the resources?? like if you add `whatismybrowser.com##+js(brave-fix)` and go to that page, does it still say you are using Brave? or just Chrome? because if not you have another layer of issue, since you are not going to have any scriptlet injection or $redirect/$redirect-rule in place, and any page that identifies Brave will block you.

You can use uBlock, it will make things easier but you won't have brave-fix, so any website can block you, and you won't have CNAME uncloaking or you anything Brave adblocker offers. These are the cons of building from source, but I am sure Adblocker works fine.

**Comment by PythonicBoat** [comment]
> It doesn't work either. Does this require any key such as brave_services_key?
> 
> ![image](https://user-images.githubusercontent.com/147116112/273287205-6469c174-d6a0-462c-a25c-859bac311c65.png)

Brave Ad-blocker failing for youtube, as mentioned in #33493

**Comment by bsclifton** [comment]
@tech5588 yes - it requires the brave_services_key. Building from source, it's expected that you don't have the key

cc: @antonok-edm who had some ideas about how adblock can still happen for local builds

**Comment by tech5588** [comment]
Then I can only use custom filters to use ad blocking when building from source code?

**Comment by bsclifton** [comment]
@tech5588 definitely you can use custom filters - but you might also make use of the filter lists too. @antonok-edm had a suggestion which I'm forgetting at the moment - maybe he can share that info here
