### ISSUE TITLE
No Tor in a Tor window

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3349]
![screen shot 2019-02-13 at 1 34 53 pm](https://user-images.githubusercontent.com/639937/52745631-62288a00-2f94-11e9-8e45-e9bb3d21c9b9.png)

Version 0.61.22 Chromium: 72.0.3626.81 (Official Build) dev (64-bit) on MacOS.

**Comment by kjozwiak** [comment]
Possibly related to https://github.com/brave/brave-browser/issues/3058? With my personal `dev` profile running `0.61.22 Chromium: 72.0.3626.81`, I went through the following:

* opened a Tor window and loaded https://check.torproject.org - Couldn't reproduce

Seems to be working for me. I also tried it with a brand new profile several times and couldn't reproduce. @btlechowski did mention that there's a race condition with Tor where sometimes you can get into a situation where you load a website too fast before Tor can initialize, which will leave you in a state where Tor isn't being used.

**Comment by riastradh-brave** [comment]
This seems to happen if the _extension directory_ for the tor component (which is where the tor daemon executable lives) is owned by another user.  This is a very weird state of affairs, but investigating why that happens under these circumstances, because even if it's a weird circumstance it shouldn't cause this.

**Comment by riastradh-brave** [comment]
Here's a hypothesis about how this might happen and how to fix it.  Waiting for a build to confirm this and test a fix.

### Diagnosis

1. `BraveExtensionManagement::RegisterBraveExtensions()` calls `g_brave_browser_process->tor_client_updater()->Register()`, to create a `TorClientUpdater` if necessary and register the extension:
   - https://github.com/brave/brave-core/blob/1c6608efa1d63297a3ac9b29233d1e7a8e2730e2/browser/extensions/brave_extension_management.cc#L32
   - https://github.com/brave/brave-core/blob/1c6608efa1d63297a3ac9b29233d1e7a8e2730e2/browser/brave_browser_process_impl.cc#L135-L142

   **Initially, a `BraveTorClientUpdater` has an _empty_ `executable_path_`:**
   - https://github.com/brave/brave-core/blob/1c6608efa1d63297a3ac9b29233d1e7a8e2730e2/browser/extensions/brave_tor_client_updater.h#L78
   - https://github.com/brave/brave-core/blob/1c6608efa1d63297a3ac9b29233d1e7a8e2730e2/browser/extensions/brave_tor_client_updater.cc#L20-L24

2. `BraveTorClientUpdater::Register()` calls `BraveComponentExtension::Register(kTorClientComponentName, ...)` to load the extension:
   - https://github.com/brave/brave-core/blob/1c6608efa1d63297a3ac9b29233d1e7a8e2730e2/browser/extensions/brave_tor_client_updater.cc#L29-L37

3. Once the extension is loaded, presumably `BraveTorClientUpdater::OnComponentReady` is _supposed_ to be called -- **unless something goes wrong, in which case it isn't called.**

   For example, making the extension directory nonwritable makes the component updater fail:

   ```
   [32176:32203:0214/000824.758570:ERROR:component_installer.cc(327)] Failed to read manifest or verify installation for Brave Tor Client Updater (Linux) (/tmp/user/1000/lose/biahpgbdmdkfgndcmfiipgcebobojjkp/1.0.4).: Permission denied (13)
   ```

4. `BraveTorClientUpdater::OnComponentReady` finds an appropriate executable file and sets `executable_path_` to its path -- **unless it can't find one, in which case it leaves `executable_path_` empty:**
   - https://github.com/brave/brave-core/blob/1c6608efa1d63297a3ac9b29233d1e7a8e2730e2/browser/extensions/brave_tor_client_updater.cc#L59-L76

   For example, `chmod -x tor-0.3.4.9-linux-brave-0 && chown nobody tor-0.3.4.9-linux-brave-0` will make it fail:

   ```
   [10989:11003:0214/033329.365733:ERROR:brave_tor_client_updater.cc(70)] Failed to set executable permission on /tmp/user/1000/lose/biahpgbdmdkfgndcmfiipgcebobojjkp/1.0.4/tor-0.3.4.9-linux-brave-0
   ```

5. When you open a window with Tor, `BraveProfileManager::LaunchTorProcess(profile)` to launch the tor daemon and set up the proxy config, using the executable path from `g_brave_browser_process->tor_client_updater()->GetExecutablePath()`, which may be empty if anything went wrong as in the bold print above:
   - https://github.com/brave/brave-core/blob/1c6608efa1d63297a3ac9b29233d1e7a8e2730e2/browser/profiles/brave_profile_manager.cc#L109-L114

6. When you make a connection in a Tor profile, `OnBeforeURLRequest_TorWork` calls `TorProfileService::SetProxy` to set up the proxy config for making the connection through the SOCKS proxy to the tor daemon:
   - https://github.com/brave/brave-core/blob/1c6608efa1d63297a3ac9b29233d1e7a8e2730e2/browser/net/brave_tor_network_delegate_helper.cc#L51

6. `TorProfileService::SetProxy` has no effect if the tor config is 'empty':
   - https://github.com/brave/brave-core/blob/master/browser/tor/tor_profile_service_impl.cc#L98-L101

7. A tor config with an empty executable path is considered 'empty':
   - https://github.com/brave/brave-core/blob/1c6608efa1d63297a3ac9b29233d1e7a8e2730e2/common/tor/tor_common.cc#L53-L57

### Remedies

- Find some way to block connections altogether in if the tor config is not initialized.  It looks like `OnBeforeURLRequest_TorWork` can return an error code -- perhaps we can just have `TorProfileService::SetProxy` return an error code rather than nothing.
- Find some way to noisily report failure if the component is not ready yet so that we can more easily diagnose the problem that Tom had of weird permissions on the directory.

Will propose a patch tomorrow if nobody else has beaten me to it.

cc @darkdh @bridiver

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1679
Verified that tor executable is not launched.
Verified that error is shown when attempt is made to open a page.
