### ISSUE TITLE
Unexplained data loss issue

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#33548]
## Description 

Please note that this issue has been ongoing for sometime now.

We have noticed a significant uptick in user reports concerning a random/unexplained loss of data in the browser. Based on these reports, it appears that the data in question can be anything stored locally/in the browser — from passwords, to bookmarks, to all browser profile data. This issue occurs across all [desktop] platforms.

We started tracking individual instances of this issue occurring in a document here: https://docs.google.com/spreadsheets/d/1Caau3LFaktSXv4vmecmTkQjr7XOtuaQK9G2ozol43_Q/edit?pli=1#gid=0

Please also note that the above document is not representative of all the reports received and that particular document is not quite up to date at this time. We do however have an ongoing Community thread where we have been collecting Community user reports, along with additional instructions for these users to follow and extra steps they can take to get us the data we need:
https://community.brave.com/t/notice-unexplained-data-loss-issue/485498

I don't want this issue to continue to get pushed back and eventually get lost in the shuffle. Happy to assist and provide any additional data that might be helpful in resolving this. 

cc @bsclifton @rebron

**Comment by Brave-Matt** [comment]
These reports are still coming in:
https://community.brave.com/t/saved-passwords-missing-please-help/514428

**Comment by Brave-Matt** [comment]
More reports — not sure if I should keep adding threads here (I have not been doing so thus far):
https://community.brave.com/t/lost-everything-when-i-updated-browser/544719

**Comment by LaurenWags** [comment]
```
Brave | 1.69.88 Chromium: 127.0.6533.26 (Official Build) nightly (x86_64)
-- | --
Revision | d60303973dc3604d9d348b981322a8a04dcbb86d
OS | macOS Version 13.6.7 (Build 22G720)
```

Today I noticed that it appears as though my passwords are gone, but they can still be used. The short version is that `brave://password-manager/passwords` isn't showing my saved passwords on one profile, but the passwords still exist/are saved somewhere because I am offered them when I visit a site where I had previously saved them.

My general setup is that I have multiple profiles on my Nightly installation - but only 2 I really use. Of these two, both have a decent amount of usernames and passwords saved. One doesn't display any saved info on `brave://password-manager/passwords`, the other displays saved info on this page just fine. I have no idea how long this has been happening, I don't use the page itself much. So it's possible that this has been a problem for awhile. Other information: I don't have sync enabled for the profile with the problem, no errors are displayed in devtools, and don't have any extensions installed.

Below is an example of a site where I had previously saved username/password info to the profile, but then when I visit `brave://password-manager/passwords` the info isn't shown:

<img width="1300" alt="Screenshot 2024-07-11 at 11 07 11 AM" src="https://github.com/brave/brave-browser/assets/28145373/095f89ae-2f3f-43c7-8700-833a1d1b3f28"> | <img width="1301" alt="Screenshot 2024-07-11 at 11 06 43 AM" src="https://github.com/brave/brave-browser/assets/28145373/5d62a0bf-ba66-43e6-bb32-1905ab8cb8ee">
-- | --

**Comment by bsclifton** [comment]
Quick note - @LaurenWags was able to fix the issue by launching from command line and appending `–enable-features=SkipUndecryptablePasswords`

**Comment by LaurenWags** [comment]
My general setup is covered under https://github.com/brave/brave-browser/issues/33548#issuecomment-2223246611 but can confirm, when using `1.70.18` if I launch with `-–enable-features=SkipUndecryptablePasswords` from the terminal I can see my passwords under `brave://password-manager/passwords` on macOS. If I don't use that when launching via the terminal, then then my passwords are not visible on that page.

Without extra flag | With extra flag
--- | ---
<img width="1534" alt="without" src="https://github.com/user-attachments/assets/93fba7ed-49b0-4c60-bcb7-bd8c9768ec97"> | <img width="1508" alt="with" src="https://github.com/user-attachments/assets/c004e5a3-7f47-4758-9e0f-6a5dbb4e5cb1">

Note, my experience was limited to password loss - not tabs, bookmarks, etc.

```
Brave | 1.70.18 Chromium: 127.0.6533.73 (Official Build) nightly (x86_64)
-- | --
Revision | 433cfac052117c021a9f8d29e52afbdc91de7a00
OS | macOS Version 13.6.7 (Build 22G720)
```

**Comment by szilardszaloki** [comment]
@Brave-Matt @bsclifton @LaurenWags By default (on most platforms), the password manager hides all the passwords if there's at least one that's undecryptable. `SkipUndecryptablePasswords` just skips the passwords for which the encryption service fails and makes the decryptable ones available in the password manager, so passing `--enable-features=SkipUndecryptablePasswords` doesn't actually solve the problem, it just gives you a partial view — there must be at least one password that's corrupted. That's easily reproducible if, say, you save two passwords in the manager, and then manually corrupt one of them. Without `SkipUndecryptablePasswords`, none of the two shows up, but if you launch the browser with the feature flag, you get back the non-corrupted one.

@LaurenWags Can we jump on a call to find out which one of your passwords is corrupted? If we find the faulty one, we might be able to infer how it got corrupted exactly.

**Comment by mario-grgic** [comment]
I have encountered the same problem (macOS 14.6 and Brave Version 1.68.134 Chromium: 127.0.6533.88 (Official Build) (arm64)) where password manager would not display any passwords. I inspected the SQLite3 DB `Login Data` and the passwords were all there.

What I did to work around the problem is to launch Brave with `--enable-features=SkipUndecryptablePasswords` which allowed me to export the passwords as CSV. 

I then made backup of the `Login Data` database, deleted it, launched Brave normally and imported the CSV that I exported above. I now have passwords in the  password manager.

Consequently, I now have DB with undecryptable passwords and working one. The original DB with undecryptable passwords has 155 passwords, the fixed one has 113. A lot of rows in the "corrupted" DB are duplicates with only a few unique rows.

Not sure what to try next and how would I find undecryptable passwords in the "corrupted" DB?

**Comment by szilardszaloki** [comment]
Thanks for reporting the above @mario-grgic.
Would you be able to:
1. go to the `Keychain Access` app,
2. search for `Brave Safe Storage`, and
3. check when your entry was last modified?

**Comment by szilardszaloki** [comment]
@mario-grgic That's very helpful, thanks!

Narrowing down your passwords to only the faulty ones is not impossible, but a bit elaborate.

Basically, after doing a backup (`!`) of your original `Login Data` database, try to identify a range of rows in the `logins` table for which your passwords show in `brave://password-manager/passwords` (without passing `--enable-features=SkipUndecryptablePasswords`) — in other words, keep the range of your choice and remove everything else from `logins`. Now, if you can see your passwords showing in the `Password Manager`, it means that all your faulty passwords are among the rows you removed from the `logins` table, otherwise you'll have to pick another range and redo this step — the algorithm itself is linear in the number of passwords, but the wider the range of rows you start out with is, the less time it'll take to complete the rest of the steps.

Now you want to try to reduce the set of rows that you remove from `logins` and extend the one that you keep, row by row. Whenever you see that your passwords disappeared from `brave://password-manager/passwords`, it means that you added back a faulty password. Take a note of it and make sure you exclude it from further processing. If you keep on doing this until the set you remove from `logins` becomes empty, the passwords you've taken note of will be the ones the Encryption service in Chrome has trouble decrypting.

**Comment by mario-grgic** [comment]
I have a hypothesis on how I may have gotten into this state. When I setup the new computer, I used `rsync` to copy my Brave data in `~/Library/Application\ Support/BraveSoftware` to the new computer. When launching the Browser on the new computer I noticed passwords and possibly (if memory serves me right) bookmarks were missing, so I exported both on the old computer and imported on the new one. 

This may explain the duplicate saved passwords I see and would also explain two different passwords encrypted with different keychains. 

Come to think of it, users that use Timemachine backups to restore their profile on different computers would run into similar issue and this is probably a fairly common use case for macOS users.


@szilardszaloki I have found a few URLs for which I have two different hex encoded passwords. One is decryptable on new machine, the other is not.

**Comment by szilardszaloki** [comment]
Migrating profiles that way would definitely be problematic, since the `Brave Safe Storage` password on the new machine wouldn't match the one on the old one. But then you've already experienced this issue before when launching Brave on the new machine for the first time, correct? When you exported/imported your passwords, did you remove `Login Data` on the new machine first, and just then did the import?

Also, I suspect not, but asking anyway — do you still have the old machine by any chance?

**Comment by mario-grgic** [comment]
@szilardszaloki I definitely did not remove `Login Data` DB on the new machine before importing data. 

Unfortunately, I got rid of the old machine a few months back.

**Comment by szilardszaloki** [comment]
The curious thing is that importing the passwords from the exported CSV on top of the corrupted `Login Data` shouldn't have fixed anything for you back then. Temporarily it does seem that the issue goes away when doing the import, but only until the next launch, as `logins` in `Login Data` is not overwritten — passwords are appended.

**Comment by mario-grgic** [comment]
@szilardszaloki All I can say is that Brave had my passwords (undecryptable and decryptable) in the `Login Data` up until today and it all worked as is until 2 minor releases back and then suddenly stopped working in Brave
Version 1.68.128 Chromium: 127.0.6533.73. 

There are a lot of users that started reporting the same problem in this support thread:

https://community.brave.com/t/aggregate-topic-lost-passwords-in-july-2024-update/560154/1

**Comment by szilardszaloki** [comment]
@mario-grgic In case you still have the `Login Data` with the corrupted `logins` table: would you be able to check if autofill is still working okay — even for corrupted items?

**Comment by mario-grgic** [comment]
I do still have the old `Login Data` and when using it autofill works for some sites (e.g. Hacker News), it autofills my user name for my bank account but not the password, and just username for a few other sites I tried but not password.

**Comment by szilardszaloki** [comment]
@mario-grgic Appreciate all the info above! 👍🏻

There's likely more than one root cause at play here, as others have had this issue for quite a while now — see [here](https://community.brave.com/t/notice-unexplained-data-loss-issue/485498).

The most recent uptick in reports, however, is most probably due to https://source.chromium.org/chromium/chromium/src/+/e3f9c0f85cb27216d031a76538c83289f2f79e7e (the [login_database.cc](https://source.chromium.org/chromium/chromium/src/+/e3f9c0f85cb27216d031a76538c83289f2f79e7e:components/password_manager/core/browser/password_store/login_database.cc;dlc=a77ee839872f4ebfd5aa0635d1f8cb6454208e55) change in particular), which went into `Chromium 127.0.6483.0` — which first appeared in `Brave 1.68.128`(`Chromium 127.0.6533.73`).

Will be back with a fix soon.

**Comment by szilardszaloki** [comment]
@mario-grgic Appreciate all the info above! 👍🏻

**Comment by mario-grgic** [comment]
Thank you @szilardszaloki. Let me know if I can help test anything.

**Comment by szilardszaloki** [comment]
@mario-grgic Just wanted to double-check: with the previous version of Brave (that is, _before_ upgrading to `Brave 1.68.128`), did you actually visit and see your passwords on `brave://password-manager/passwords`? Asking because I went back to `Chromium 108.0.5323.0` (from September 2022), and it seems that Chrome never tolerated corrupted passwords on macOS, nor does it tolerate them now (mostly because the `LoginDatabase` implementation on macOS maps any `OSCrypt`/decryption-related failures to the same service-level failure, as opposed to the `LoginDatabase` implementation on Windows) — e.g. if you have at least 2 passwords and:
1. close the browser
2. open `Login Data` in [DB Browser for SQLite](https://sqlitebrowser.org)
3. execute
    ```sql
    UPDATE logins SET password_value = x'7631301f2bb0cc71024cedf754d0992d32' WHERE username_value = 'substitute your username_value value here';
    ```
    in `Execute SQL` (`F5`, `Cmd` + `S`)
4. close [DB Browser for SQLite](https://sqlitebrowser.org)
5. open the browser

you won't see any passwords showing in any of the browsers (at least on macOS).
Let me know.

**Comment by mario-grgic** [comment]
@szilardszaloki I got some interesting results. First I restored my original `Login Data` DB with undecryptable passwords that Brave 1.68.128 PWM fails to display any passwords. 

I downloaded Brave Browser Release v1.67.134 (Chromium 126.0.6478.186) and started with that original DB. PWM shows passwords just fine!

Then I closed Release v1.67.134 (Chromium 126.0.6478.186), executed the sql statement to insert `x'7631301f2bb0cc71024cedf754d0992d32'` for most passwords (username_value is not the same for each row, but I selected user name that has most rows) and launched Release v1.67.134 again. This time PWM shows no passwords.

**Comment by szilardszaloki** [comment]
@mario-grgic Nice find! 👍🏻 

I managed to narrow it down to 2 Beta versions:
- [Beta v1.68.106 (Chromium 126.0.6478.126)](https://github.com/brave/brave-browser/releases/tag/v1.68.106)
- [Beta v1.68.107 (Chromium 127.0.6533.26)](https://github.com/brave/brave-browser/releases/tag/v1.68.107)

In https://github.com/brave/brave-core/compare/v1.68.106...v1.68.107 (while going from Chromium 126 to Chromium 127) we pulled in [Remove undecryptable passwords from the login db](https://source.chromium.org/chromium/chromium/src/+/e3f9c0f85cb27216d031a76538c83289f2f79e7e) (Chromium's Windows-related bug) and at the same time removed a patch of ours (`chromium_src/components/password_manager/core/browser/password_store/login_database.cc`) that contained a change in the same exact function (`LoginDatabase::StatementToForms()`).

Culprit is the combined effect of the two — will post a fix soon.

**Comment by szilardszaloki** [comment]
Original patch was added here: https://github.com/brave/brave-core/pull/5656

Basically, the patch just attempted to mimic `SkipUndecryptablePasswords`, so I'm proposing to enable it on Linux & macOS:
```cpp
OVERRIDE_FEATURE_DEFAULT_STATES({{
#if BUILDFLAG(IS_IOS) || BUILDFLAG(IS_LINUX) || BUILDFLAG(IS_MAC) || \
    BUILDFLAG(IS_WIN)
    {kSkipUndecryptablePasswords, base::FEATURE_ENABLED_BY_DEFAULT}
#endif
}});
```

cc: @simonhong @bridiver @bsclifton

**Comment by bsclifton** [comment]
Nice investigative work 🕵️ 😄 One step further - Chromium added a new `kClearUndecryptablePasswords` feature (brave://flags/#clear-undecryptable-passwords) with https://chromium.googlesource.com/chromium/src/+/e3f9c0f85cb27216d031a76538c83289f2f79e7e

When we did rebasing with Chromium 127, we unintentionally dropped the patch from https://github.com/brave/brave-core/pull/5656 here:
https://github.com/brave/brave-core/pull/23829/commits/aabfd317e11a8422289f6888dc5886eae19f7077

You're exactly right - the old patch by @simonhong was basically setting the ITEM as failed and not the SERVICE. So then it would continue to the next one.

I think the override you have proposed would be great - it gets us back to how things used to be.

It is worth noting- Chromium also did have a regression upstream for Windows users who had Sync enabled. That is captured by https://issues.chromium.org/issues/354847250?pli=1 upstream and fixed in https://chromium.googlesource.com/chromium/src/+/641093c7627684a6c04986531209783f430fb205. We proactively pulled this fix in with https://github.com/brave/brave-core/pull/24853.

It's worth noting - in Chromium ticket for the Windows sync issue, they noted:
> We are rolling out the fix through the server side right now. In a few hours the workaround isn't needed anymore, simple Chrome restart with chrome://restart would fix the problem.

On the Chrome side, they made a Finch experiment called `Enable_UndecryptablePasswordsEmergencyFix` which specifically sets the features `ClearUndecryptablePasswordsInSync` and `SkipUndecryptablePasswords` on all release channels on Windows. You can see that here:
https://griffin.brave.com/?seed=UPSTREAM&search=UndecryptablePasswords

**Comment by zenparsing** [comment]
Nice work @szilardszaloki / @bsclifton !

**Comment by LaurenWags** [comment]
Requires `1.68.139` or higher for testing 👍🏻

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.140 Chromium: 127.0.6533.100 (Official Build) (64-bit)
-- | --
Revision | 612f5cee6491be373e8133bcda3f56522fbe621e
OS | Linux
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.141 Chromium: 127.0.6533.120 (Official Build) (x86_64)
-- | --
Revision | b3f23500b575d50584510ea1814ef440d30741a8
OS | macOS Version 13.6.9 (Build 22G830)
```

**Comment by mario-grgic** [comment]
I can confirm that the issue is fixed. Tested with Brave 1.68.141 Chromium: 127.0.6533.120 (Official Build) (arm64) and my original `Login Data` DB. All passwords are showing again.
