### ISSUE TITLE
Prompt Premium users to refresh tokens when exhausted

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33670]
When premium status is `ActiveDisconnected`, the user needs to get more tokens. They can visit https://account.brave.com/account/ and hit "Refresh".

![Image](https://github.com/brave/brave-browser/assets/741836/2185a8a8-e3b5-43b8-aff5-a1c9bff92e16)

**Comment by stephendonner** [comment]
@petemill I'll save you a nit ahead of your patch: please `s/login/log in` on the copy text and button-UI text 👍

**Comment by petemill** [comment]
> @petemill I'll save you a nit ahead of your patch: please `s/login/log in` on the copy text and button-UI text 👍

actually I'm going to change this text to "Refresh" considering the advanced functionality of accounts.brave.com now

**Comment by stephendonner** [comment]
> > @petemill I'll save you a nit ahead of your patch: please `s/login/log in` on the copy text and button-UI text 👍
> 
> actually I'm going to change this text to "Refresh" considering the advanced functionality of accounts.brave.com now

Even better, and more succinct.

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

### Steps:
1. installed `1.60.106`
2. launched Brave using `--env-leo=staging --env-ai-chat.bsg-dev --env-ai-chat-premium.bsg=dev --enable-logging=stderr --v=1`
3. clicked on `Leo` in the sidebar
4. clicked `Accept and begin`
5. purchased and loaded `Brave Leo Premium` from `account.bravesoftware.com`
6. shut Brave down
7. opened `Local State` in my user-profile directory
8. edited `valid_from` and `valid_to`date stamps to be a couple days behind: `10-28` (rather than `10-30`)
9. relaunched Brave
10. confirmed I saw the `Your Brave account session notice has expired` dialog
11. clicked `Refresh`
12. since the URL is keyed to production, I edited it to be `https://account.brave.com/?intent=recover&product=leo`

### Confirmed that after loading the above URL while logged in, my `Leo` `Premium` tokens were refreshed, and I was able to use `Premium`


example | example | example | example | example | example | example | example
---------|----------|---------|----------|---------|----------|---------|--------
