### ISSUE TITLE
Password Manager written as P&assword Manager in Shortcuts settings

### ISSUE THREAD

**Issue by Saoiray** [brave/brave-browser#33953]
## Description 
There is a typo in Brave's settings. Under Shortcuts it lists as P&assword Manager instead of Password Manager

## Steps to Reproduce

   1. Go to brave://settings/system/shortcuts
   2. Type in P&
   3. You'll see it come up with P$assword Manager

## Actual result:

![image](https://github.com/brave/brave-browser/assets/99627477/dbc8d156-57ff-4e40-adb5-4a05e741ec5f)

## Expected result:

It should show as **Password Manager**

## Reproduces how often: 
Every time

## Brave version (brave://version info)

<html>
<body>

Brave | 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | 63d57e32ce0ff0a1e380461bc394351e97d1416a
OS | Windows 11 Version 22H2 (Build 22621.2428)

</body>
</html>

<html>
<body>

Brave | 1.62.2 Chromium: 119.0.6045.33 (Official Build) nightly (64-bit)
-- | --
Revision | 1ae4cbaeb4186df008e4562ed006f2c70a9beea8
OS | Windows 11 Version 22H2 (Build 22621.2428)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

Initially shared by someone at https://community.brave.com/t/typo-in-shortcut-title-p-assword-manager/512907

**Comment by Emi-HoloGhostRevisionist88** [comment]
@rebron 
Although this was posted first... 17 hours before this duplicate issue https://github.com/brave/brave-browser/issues/33970, the duplicate will take priority.

People should avoid duplicates, including Brave staff, it's not hard to search for issues if there is an existing one and 'bump it' if necessary even for Brave team members, or close this one. But users who report issues are spending their time to try to help making Brave better, these kind of issues get ignored.
This is why there is a big problem in this Github, too many duplicates, a lot of old issues that got resolved not being closed, it's kind of messy which is proven repeated and proven easily like in this case.

**Comment by Saoiray** [comment]
Meh, I'm assuming just was a bit of miscommunication and perhaps missed the Github issue link I provided at https://community.brave.com/t/typo-in-shortcut-title-p-assword-manager/512907. At least Matt was able to get people tagged in on it and issue is being resolved. I'm going to close this issue then.

**Comment by Emi-HoloGhostRevisionist88** [comment]
You know me, I say what I say, that's why I got banned from community, and Brave has to learn that they are something because of the users.
Many people like you report bugs (for free) and when you already gave the Github link in community and all, at least what you expect Brave staff members to not create duplicates and just do something with your issue. They can't control what other users do, when they report weird stuff or create duplicates but you hope Brave staff don't do that!. It doesn't make sense why was your comment ignored, when you were clear about it.

You spent time reporting a bug, and you wasted your time in the end. What will happen when users stop reporting bugs because they got discouraged for the same reason? many users report valid issues today like you, so something has to be said about about this specific issue, even if my comment got thrown in the trash of the suggestion's box. 👍
