### ISSUE TITLE
Brave overrides styling with `display: none !important`

### ISSUE THREAD

**Issue by johanehinger** [brave/brave-browser#33965]
## Description 

I'm using React with [Styled Components](https://github.com/styled-components/styled-components) and since this is autogenerating classnames during build we have no control over what each class is called. I suspect that Brave flags some classnames as potential ads and overrides styling of the element with `display: none !important`, even though they are not ads! In this case they are vital checkboxes for our product filters.

This behaviour makes our site appear different from build to build. And each time we release a new version new classnames are generated and some might be overridden and hidden making the user experience not that great. 

Disabling `Trackers & ads blocking` solves the problem, enforcing the hypothesis. What should I do to mitigate this issue?

## Steps to Reproduce

Unfortunately there is no sure way of always reproduce the "bug" since classnames are generated at random so some builds go through without any style overrides.
   1. Build a React application with Styled Components
   2. Re-build until you get unlucky with classname generation

## Actual result:

<img width="279" alt="image" src="https://github.com/brave/brave-browser/assets/65904251/0e66f04e-dcef-43d9-a5d9-9fd0de618231">

## Expected result:
<img width="274" alt="image" src="https://github.com/brave/brave-browser/assets/65904251/34522bd5-6641-46c9-a430-128c08857e50">

## Reproduces how often: 

Ever now and again when we build a new release of the website.

## Brave version (brave://version info)

[Version 1.59.122 Chromium: 118.0.5993.96 (Official Build) (arm64)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? - Yes
- Can you reproduce this issue with the beta channel? - I don't know
- Can you reproduce this issue with the nightly channel? - Don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - Yes
- Does the issue resolve itself when disabling Brave Rewards? - I don't know
- Is the issue reproducible on the latest version of Chrome? - No

**Comment by Emi-HoloGhostRevisionist88** [comment]
1. `display: none !important` is what 'cosmetic filters' do, it is that's what hides ads and annoying elements in pages.
2. Adblocker just do what they are meant to do, hide stuff that matches any class or id, they just do it, there is no 'magic' or automatic mode to say if one website is good or not.
3. Brave uses Easylist, uBlock as main lists, and lists work like that, generic rules will apply to all websites, for exmaple, you can see here all the generic lists that are probably affecting your site https://github.com/easylist/easylist/blob/master/easylist/easylist_general_hide.txt anything that doesn't have a domain in the rule is 'generic'.
4. That means uBlock and Adguard and ABP will do the same with your side, the difference is they support cosmetic exceptions, where Brave doesn't But other adblockers like Vivaldi maybe Opera and the simple ones will probably have the same issue of creating cosmetic exceptions.
5. You have to go to the probably Easylist forums and say your website is broken by the adblocker. But also, you might be able to report it directly in Brave with Brave's menu (alt+e) -> help -> report a broken site. Easylist is usually the one that whitelists sites like that, where Generic cosmetics are in place causing issues, but also Brave does it depending on situation, but this might apply to Easylist where some sites get the $generichide exception here: https://github.com/easylist/easylist/blob/master/easylist/easylist_allowlist.txt
6. Generic Cosmetics are the Cosmetics that apply to all pages, so only an exception on your site can do the job, since Brave doesn't support the exceptions from a list like this: https://github.com/easylist/easylist/blob/master/easylist/easylist_allowlist_general_hide.txt, then generic hide that will remove all generic cosmetics for a website will look like this: `@@||site.example^$generichide`
7. Obviously you didn't provide any class name or id or website name and nobody can do much for you without that information, for obvious reasons (hint: point 5).
8. Also this is technically not the place to report this, better if you go to Community Brave, tag your post with Adblocking tag, and then give proper information about your site and all so it can be tested by Brave team in charge of that, if not [Easylist forums ](https://forums.lanik.us/)

**Comment by johanehinger** [comment]
@Emi-HoloGhostRevisionist88 Awesome 🚀 Thanks for the answer!

**Comment by rebron** [comment]
@johanehinger I'm going to ahead and close this issue. Thanks @Emi-HoloGhostRevisionist88
