### ISSUE TITLE
Portable version not updating

### ISSUE THREAD

**Issue by mrjohnr** [brave/brave-browser#33985]
Hi
i'm using [Brave portable version](https://portapps.io/app/brave-portable/)  but it doesn't auto update,same works for Opera browser

**Comment by Emi-HoloGhostRevisionist88** [comment]
You have to understand that version is not officially supported by Brave, so nobody is probably going to help you.
Brave uses OMAHA updater, and omaha updater needs registry entries and all that, it is not as simple as "this is Brave and update it" that means, it will not be portable because it needs to be written on registry, so, portable versions can't be updated.

But just so you know, you don't even need to use that Portable version, Brave already offers zipped version, and with the zipped version you can make your Portable version.

In any release like https://github.com/brave/brave-browser/releases/tag/v1.60.106 you can search for `-win32-x64.zip` and you will get [brave-v1.60.106-win32-x64.zip](https://github.com/brave/brave-browser/releases/download/v1.60.106/brave-v1.60.106-win32-x64.zip), you extract the folder anywhere you want, and all you need to do is to add a shortcut or a bat file or something next to the brave.exe with the switches `--user-data-dir="User Data"` this will create User Data folder next to the brave.exe, keeping program and user data in the same folder (if not it will use the default  %localappdata%), and done. you can obviously move the files from that portable version to User Data and continue using it that way.
As long as you dont use brave.exe and the bat, shortcut or script or whatever, you will be able to always use the same user data without issues.

Also, I don't know if this portable version is truly portable or just a standalone (like Opera or Vivaldi), that means you can't use it across computer without losing passwords and cookies, in Brave you can use the cmd switches `--disable-encryption-win` and `--disable-machine-id` and that way remove encryption (supposedly), and that way your data can be used in other computers, not too secure but it's your choice. I tested only passwords, and if there were encrypted passwords, then they will not show if you disable encryption, and if add unencrypted passwords, they are not going to show if you run Brave encrypted, so something works. but I didn't test it across computers.

**Comment by TotalImportance8529** [comment]
> Portapps is not affiliated, associated, authorized, endorsed by, or in any way officially connected with Brave™, or any of its subsidiaries or its affiliates.

Report here :
https://github.com/portapps/brave-portable/issues

**Comment by bsclifton** [comment]
Closing as this is not officially supported by Brave (as shared above). https://github.com/portapps/brave-portable/issues is the right place to report issues
