### ISSUE TITLE
Wrong omnibox leo result separator color with custom theme

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#34029]
## Description 

<img width="800" alt="Screenshot 2023-11-01 at 11 10 28 AM" src="https://github.com/brave/brave-browser/assets/6786187/d89e01eb-aa72-4c53-b352-40ad6c7d13cc">

## Steps to Reproduce

   1. Launch brave
   2. Install any custom theme (ex, https://chrome.google.com/webstore/detail/oceanic/gbbacdmgjdfajabgglpjifcedoajdimg)
   3. Type any keyword from omnibox

## Actual result:

Leo omnibox result separator is red(fallback color)

## Expected result:
Not a fallback color

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @aguscruiz to help with QA/Design QA

**Comment by aguscruiz** [comment]
The right styles are here, in case it's needed
https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=1386%3A11575&mode=design&t=5hIZzRCuc5FvhnxR-1

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.29 Chromium: 119.0.6045.105 (Official Build) nightly (x86_64)
-- | --
Revision | 722db0323f23c1aaee8a62326083bced61909279
OS | macOS Version 14.2 (Build 23C5030f)
```

### Steps:
1. installed `1.62.29`
2. launched Brave
3. installed `https://chrome.google.com/webstore/detail/oceanic/gbbacdmgjdfajabgglpjifcedoajdimg`
4. typed `brave` into the Omnibox

### Confirmed the `Leo` separator was a light color, rather than red

<img width="1519" alt="Screenshot 2023-11-06 at 1 40 57 PM" src="https://github.com/brave/brave-browser/assets/387249/195be1d0-5c1d-4d1d-9862-9ec0cc60ae8e">
