### ISSUE TITLE
Update background color for tab groups 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#34041]
## Description 

Background colors for tab groups should include the tab and not a change to text-color to make the grouped tab stand out more

## Design
Figma here:
https://www.figma.com/file/miI8vcpoJUX0OusjwbcVpT/%F0%9F%94%A5-Exploration?type=design&node-id=876-37610&mode=design

## Reproduces how often: 

easily

## Brave version (brave://version info)

tbd

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Part of the horizontal tab refresh, feedback fixes.
related: https://github.com/brave/brave-browser/issues/33824

**Comment by aguscruiz** [comment]
Figma here:
https://www.figma.com/file/miI8vcpoJUX0OusjwbcVpT/%F0%9F%94%A5-Exploration?type=design&node-id=876-37610&mode=design

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.62.35 Chromium: 119.0.6045.105 (Official Build) nightly (64-bit)
-- | --
Revision | 7fd1f70f3e886d12f40eccbd712723b1662a1f38
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

Installed 1.62.35
launched Brave
opened few tabs 
added a tab to a new group via context menu
selected a color 

Actual results:  Background color for tab groups is not shown

<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ab23902b-35da-4ad7-913f-8543ea797ad5">

**Comment by rebron** [comment]
@MadhaviSeelam 1.62.37 and higher should have the change.

**Comment by kjozwiak** [comment]
Removing `QA-Pass` as the above was merged into `1.61.x` from `1.62.x` via https://github.com/brave/brave-core/pull/21076 and will need to be re-checked via `1.61.x`. The above requires `1.61.85` or higher for `1.61.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.61.90 Chromium: 119.0.6045.163 (Official Build) beta (x86_64)
-- | --
Revision | 0e0de020c4ef9621e8a67a103299899837ce85a1
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.61.90`
2. launched Brave
3. opened few tabs 
4. selected `Add to group` `>>` `New group` 
5. entered name of the group and selected color 
6. opened `Private window`, `Private window with Tor`, & `Guest profile` windows

### Confirmed background color shown on the tab groups in the horizontal view

*_Normal window_*

Light | Dark
--- | ---
<img width="1719" alt="Screen Shot 2023-11-27 at 12 16 20 PM" src="https://github.com/brave/brave-browser/assets/387249/973a09a1-841a-4584-88c6-006b79893190"> | <img width="1722" alt="Screen Shot 2023-11-27 at 12 15 18 PM" src="https://github.com/brave/brave-browser/assets/387249/ca80362c-d2ed-4c49-87a5-e852d6b91a84">



*_Private window_*
Light|Dark
---- | ---


Light | Dark
--- | -----



*_Private window with Tor_*

Light | Dark
--- | -----


*_Guest window_*

Light | Dark
--- | -----

**Comment by locious7** [comment]
I would like to request a change here that reflects the Chrome implementation as seen in the screenshot. With the current implementation, the tab group colors are dim and not distinct, making it sub-optimal for people with color blindness or impaired vision, but also the average person.

![image](https://github.com/brave/brave-browser/assets/59851207/7c486b05-a40d-42e4-8f9b-82d1317f1ec1)

**Comment by MrKistic** [comment]
I guess nobody checked it using vertical tabs? Those group headers have no background colour.

![image](https://github.com/brave/brave-browser/assets/51582/29029b86-e0df-4fae-b6bc-e7257d7a6eaf)

Is there any reason they're not the same for vertical tabs? It doesn't make much sense at the moment. Actually I just noticed the vertical tabs are a mess with different coloured themes so perhaps this is part of a bigger issue.

I also agree with the previous two comments. I use isolated browser installs for different projects and I'm stuck using Edge for those because their vertical tab group implementation works perfectly. Their horizontal implementation works better for that matter, although mainly that's because the current tab indicator in Brave is not clear in any case.

![image](https://github.com/brave/brave-browser/assets/51582/56e8056f-06eb-49c8-8015-af4feabd0383)
![image](https://github.com/brave/brave-browser/assets/51582/463f051f-18a8-4290-b898-39e114335a0e)

I don't really want to use Edge at all but at least they're isolated, ideally I'd be using Brave for everything though.

**Comment by bsclifton** [comment]
cc: @rebron

**Comment by aguscruiz** [comment]
We'll work on some improvements for this, thanks for the feedback!
