### ISSUE TITLE
Why Does Brave insist to install VPN service?

### ISSUE THREAD

**Issue by angelog0** [brave/brave-browser#34074]
At each upgrade Brave install and enable the service regarding VPN without asking consensus to the user. Brave aims to fight against the spammer apps one meets on the WEB and behaves in the same manner.

I DO NOT WANT TO USE VPN NOR I WANT BRAVE INSTALLS SERVICES WITHOUT MY CONSENSUS.

If it will insist to do that at each upgrade, I will remove Brave from all my systems and will use another browser.

**Comment by angelog0** [comment]
As someone [wrote](https://www.theverge.com/2023/10/20/23925192/brave-browser-vpn-windows-11), this policy is not _the most transparent move from a company based on transparency..._ Really I hope you revert this...

**Comment by Emi-HoloGhostRevisionist88** [comment]
The issue hasn't even fixed by Brave, so what do you expect if you are updating Brave to a new version? the services will get reinstalled **obviously**, that's because you are giving the installer admin rights = Browser can install these services, just like the updater services.

This will be 'fixed' someday, and until it is fixed, the services will get reinstalled on any new update. Also, the 'fix' will take a while because installing stuff 'on demand' is not easy as clicking an .exe and done.

Why didn't you use the search function? you would have found the 'issue' https://github.com/brave/brave-browser/issues/33726 and also the PR https://github.com/brave/brave-core/pull/20754, where you could have gathered all the information needed, like how to convert from admin rights/all users installation to a per-user installation, so you don't get the services installed, because no admin rights = no services.

So if people used their time to fix the issue = convert to a per-user installation, instead of complaining and wasting the 3 hours saying how Brave is not 'transparent' because VPN services are getting installed, just like the updater services get installed; well, they wouldn't even notice anything being installed.
But anyway, this is not a privacy or security reason, it is just drama at this point. And for example, no nightly users who install with admin rights raised the concern to devs either in many months. It is still not their fault either, but people make the drama bigger than it should be.
So asking again in a new issue, (like if this deserved a new issue) what was already answered is just, wanting to create more drama. In fact, as you can see, only Devs can comment in the issue because people couldn't just stick to the topic of VPN.

You got 3 easy choices, fix it yourself or wait for the fix or switch browsers.

**Comment by Marko-98** [comment]
They said it will be fixed in one of the next versions.

**Comment by bsclifton** [comment]
Hi folks,

Thanks for the feedback - I am actively working on fixing this. You can follow progress here:
https://github.com/brave/brave-browser/issues/33726

I have written the code to remove the services and tray icon, essentially reverting the change. I'm now working through the portion of the change to install for people that are paid customers.

I'm going to close this as a duplicate - but I encourage you to subscribe to https://github.com/brave/brave-browser/issues/33726 for updates. Thanks!
