### ISSUE TITLE
Rewards notification timestamps reset to Dec 31 after browser restart

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#34089]
The timestamps in Rewards notifications reset to Dec 31 after a browser restart. The original timestamp should be retained until the notification is dismissed.

Notification before restart (correct timestamp):

![notification-before-restart](https://github.com/brave/brave-browser/assets/5033691/3dcab655-cff5-4348-b498-5b93a088f99b)

Notification after restart (incorrect timestamp):

![notification-after-restart](https://github.com/brave/brave-browser/assets/5033691/060f60c7-6fc6-4c25-b1b2-dcb9971ac519)

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
```
Reproduced the issue on 1.61.x

Date before browser restart | Date after browser restart
-------------------------------|------------------------------------

**Comment by GeetaSarvadnya** [comment]
Verified the issue on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.62.116`

The issue is NOT reproducible on Android, the date remained same before/after browser restart in logged out state

Date before browser restart | Date after browser restart
-------------------------------|------------------------------------
![Screenshot_20231222_205914](https://github.com/brave/brave-browser/assets/38657976/eb84f9b6-0480-47fc-8afa-7b4873fa527b) | ![Screenshot_20231222_205941](https://github.com/brave/brave-browser/assets/38657976/ddfe6acf-0be7-44da-8c7c-56f43ebf6831)
