### ISSUE TITLE
font whitelist for linux distros

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#34169]
Looking into introducing a font whitelist for specific linux flavors

**Comment by LaurenWags** [comment]
@arthuredelstein could you please add a test plan for this one? Marking as `QA/Blocked` until we have a test plan 👍🏻

**Comment by arthuredelstein** [comment]
> @arthuredelstein could you please add a test plan for this one? Marking as `QA/Blocked` until we have a test plan 👍🏻

QA test plan: 
1. Test Brave on Ubuntu 22.04.x
2. Download the Pacifico font family from https://fonts.google.com/specimen/Pacifico and install it on Ubuntu (more info on how to do that at https://linuxhint.com/manually-install-fonts-ubuntu-22-04/)
3. Visit https://arthuredelstein.net/demos/font.html
4. By examining the text, confirm that the FreeMono font is being used (because it's on the allowlist) and the Pacifico font is not being used in the page (because it's not on the allowlist).
5. Disable Brave Shield and confirm that both the FreeMono font and Pacifico font have been loaded.
6. Re-enable Brave Shield and confirm that now only the FreeMono font is used again.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.122 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | cfddebe77d394064c472fda64afcd9fbed34ceb4
OS | Ubuntu 22.04.03 LTS


Verified test plan from: https://github.com/brave/brave-browser/issues/34169#issuecomment-1847992427

Ubuntu:
![image](https://github.com/brave/brave-browser/assets/34715963/bc22bae9-fcdc-48ca-a951-c28ae8fa36e5)


Without the Pacifico font:
![image](https://github.com/brave/brave-browser/assets/34715963/ae0d641b-d0f1-47f6-b314-cac359fb9ab0)


Installed Pacifico font base on https://linuxhint.com/manually-install-fonts-ubuntu-22-04/
![image](https://github.com/brave/brave-browser/assets/34715963/778d1d11-d5bc-4508-b671-eda6f96d471d)


With Pacifico font and Shields enabled:
![image](https://github.com/brave/brave-browser/assets/34715963/8d3e4721-06fb-43c1-88ad-ad524b4b45d5)


With Pacifico font and Shields disabled:
![image](https://github.com/brave/brave-browser/assets/34715963/97228bca-0e42-4977-b5b8-41daf7ac2143)

This is due to https://github.com/brave/brave-browser/issues/34653
