### ISSUE TITLE
Brave Nightly and Beta crash on opening (mac)

### ISSUE THREAD

**Issue by Crashenterminate** [brave/brave-browser#34207]
## Description 
When I download a Brave Testing App (Nightly/Beta) it immediately crashes

## Steps to Reproduce

   1. Download a testing version of Brave like Nightly or Beta
   2. Open the app

## Actual result:
Crashes

## Expected result:
Open the app

## Reproduces how often: 
Always

## Brave version (brave://version info)
The most recent and some semi-old ones

## Version/Channel Information:
It happens on Nightly and Beta

## Miscellaneous Information:
The exception type is "EXC_BREAKPOINT (SIGTRAP)"
The Mac has an Intel CPU

**Comment by bsclifton** [comment]
Sorry for not replying to this sooner @Crashenterminate 

If you are still having a problem, you can visit brave://crashes and click the `Send report`. Then please share an ID. As there's not enough info here to debug, I'll close this out. There have been a few issues upstream in Chromium which have been fixed in recent months
