### ISSUE TITLE
[ads] Add BUILD.gn per directory

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#34266]

**Comment by tmancey** [comment]
Closing issue as wont fix

**Comment by zazou99vlc** [comment]
#SOLVED
Subject: [Persistent Issue] Right-click menu on GNOME/Wayland requires mouse movement to appear (Intel Graphics)

Hello,

I am reporting a persistent issue with the right-click context menu on Linux with GNOME/Wayland. While I understand that fixes have been implemented for similar problems in the past (like in issue #34266), my specific system configuration has always been affected, and the problem has never been solved for me without a manual workaround.

Describe the bug:
When I right-click anywhere in the browser window, the context menu does not appear immediately. It only renders and becomes visible after I move the mouse pointer slightly. This is not a freeze, but a consistent UI rendering glitch that has persisted across all recent Brave versions.

Workaround:
The issue is completely resolved when launching the browser with the --use-gl=egl flag. This has been the only way for me to get a functional context menu.

System Information:

    Brave Version: Brave Browser 138.1.80.113

    Operating System: Manjaro Linux

    Desktop Environment: GNOME Shell 48.2

    Windowing System: wayland

    Graphics Card/Driver:
    Generated code

          
    00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller (rev 09)
        DeviceName:  Onboard IGD
        Subsystem: Dell Device 0585

        
To Reproduce:

    Launch Brave without any special flags on a system with similar specs (GNOME, Wayland, integrated Intel Graphics).

    Right-click on a webpage, a tab, or any UI element.

    Observe that the context menu does not appear.

    Move the mouse pointer.

    Observe that the context menu instantly appears as soon as the mouse is moved.

This persistent behavior suggests that the default rendering path has a flaw on certain hardware, specifically older integrated Intel Graphics on Wayland. The previous fixes may not have covered this particular configuration.

Thank you for looking into this specific case.
