### ISSUE TITLE
Block trackers & ads option blocks websockets on localhost

### ISSUE THREAD

**Issue by levicki** [brave/brave-browser#34389]
This should be enough to explain what the problem is:

![image](https://github.com/brave/brave-browser/assets/16415478/44218088-6212-43ba-8444-d517597d7943)

The website needs to connect to `ws://127.0.0.1:1025/feedback` (a local instance of Visual Studio) in order to work.

Why would `Aggressively block trackers & ads` in Shields settings block `127.0.0.1`?

Is it because of `feedback` being on some blocklist?

**Comment by levicki** [comment]
I changed the title because I tested also with plain `Block trackers & ads` &mdash; it still blocks websockets:

![image](https://github.com/brave/brave-browser/assets/16415478/11be80bd-2332-4875-b5db-76fe2304d724)

**Comment by levicki** [comment]
@rebron Please take a look at this.

**Comment by levicki** [comment]
In order to reproduce this you need to have Visual Studio installed and be signed into a Microsoft account in it, and then try to submit feedback from within Visual Studio which will launch the browser as shown in the image.

**Comment by diracdeltas** [comment]
cc @ryanbr

**Comment by Emi-Emi-Emi** [comment]
@levicki
In https://github.com/brave/adblock-lists/blob/master/brave-lists/brave-specific.txt there is a rule `||127.0.0.1^$third-party,domain=~localhost|~[::1]|~[::ffff:7f00:1]` = it will block any 127.0.0.1 as a third party connection in all websites by `~localhost|~[::1]|~[::ffff:7f00:1]`, which is exactly the case here.

You should be able to easily whitelist it by adding `@@||127.0.0.1^$domain=visualstudio.com`, since Brave allows custom rules in Android and Desktop. I mean, these connections are important to you, but I don't know if they can just be globally whitelisted, so better if you fix it yourself and then wait for an update or something, you can also be more specific and add `websocket` to the rule, to specifically whitelist only the websockets.

It didn't work when you switched to Standard mode, because Brave `Standard mode` block 3p connections (and some 1p), so that's why only completely lowering the shields would work, because 127.0.0.1 is seen by the browser as an obvious 3p connection. that's why when you used Standard mode, it stopped blocking the 1p connections like `https://dc.services.visualstudio.com/v2/ track` and didn't apply cosmetics to the website.

The list can't be easily turned off since it is a Default list (it can be done but not by conventional methods), so it can't be tested fast, but that's the only rule I saw that could explain things from all Default lists, so it should work, but like you said, you need Visual Studio installed and Microsoft account, so I can't test it for you.

PS. BTW, `Fanboy Annoyances` already cover Cookies and Newsletters, so no need to enable all of them, Fanboy annoyances is enough, if you want to hide/block all those things already.

**Comment by levicki** [comment]
@Emi-Emi-Emi Thanks for the detailed response.

It is one thing to block the 3rd party domains and I totally agree with that even if it's pain in the ass to figure which ones are requred for 1st party site to work.

However, it is totally another thing to indiscriminately block localhost.

This [line](https://github.com/brave/adblock-lists/blob/e2a291351b4ca2e6a0d81150aad874e84baa3752/brave-lists/brave-specific.txt#L15) with an exception right under the block proves me right.

Blocking localhost is opening a can of worms. It will break developer tools like Visual Studio (and not just bug reporting feedback but probably also debugging web sites and services you develop), e-signing apps made by governments and banks running on locahost that need to sign online documents like tax submittal forms or approve transactions using a physical USB token and keys stored in it, etc.

It may stop some attempts at fingerprinting or even malware, but unless Brave is willing to spend time curating ever-growing list of exceptions as soon as they are reported (and let's be honest most people won't be able to figure out why their stuff isn't working) there should be an off switch somewhere in the UI for this kind of filtering.

**Comment by Emi-Emi-Emi** [comment]
Yeah, that's the risks of adblockers and how  adblockers see the logic of URL vs domain, and then in Brave you add the 1p vs 3p logic with Standard and Aggressive in Default lists.
Sometimes 'too much protection' can be bad for users, for example, look where Strict fingerprinting is going to be in the future, as a flag only, because it breaks too much stuff to use it.
But also good features might be harder to understand like Ephemeral Storage and how it 'isolates' the 3p data instead of blocking it so whitelisting the data might be needed sometimes, for the same 1p vs 3p.

Technically is not hard to troubleshoot this though, since this was a network request logged by Devtools/Shields, you could easily just whitelist it without knowing the reason or the list.

Other issues might not be as easy to stop and fix but are not too hard either, even if Brave doesn't let you turn lists off, it is still okay to find things out. Brave has all the Default lists in the same file, so it is not hard to see what rule might be the reason, even without uBlock logger.

You just go to `%localappdata%\BraveSoftware\Brave-Browser[-Nightly]\User Data\iodkpdagapdfkphljnddpjlldadblomo\1.0.XXXX\list.txt` and done.

Anyway the good thing is Brave allows custom filters with the native adblocker, and specific exceptions can be created for most things, so I am usually fixing incompatible rules or removing whatever that is not needed by me, even use Default lists as custom if needed.

**Comment by levicki** [comment]
@Emi-Emi-Emi Main issue for me is this default hidden filtering which cannot be turned off. Yes, I can whitelist it now, but to do that I need to first know it is there which I didn't.

For example, Brave was (maybe still is, not sure if the change was implemented) proxying extension downloads from Chrome Web Store and if you didn't know that and blocked their updater URL for any reason you would get a cryptic error when trying to download any extension. Worse yet, the request wasn't logged to the devtools so you had absolutely no way of knowing what's going on.

So yes, protection is good as long as it is transparent.

This `127.0.0.1` blocking isn't transparent, and please don't tell me "you could have looked at the Brave adblock extension code, found the hidden list it uses, read and understood the rules, and then just whitelisted what you need" because while I with my programming knowledge could have certainly wasted time to do it, that's what 95% of Brave users wouldn't be able to do and what shouldn't be expected of them to do.

**Comment by Emi-Emi-Emi** [comment]
The problem is that the 'transparency' of the adblockers is the filters themselves, they are open for anyone to see. Adblockers can't do more than they are told to do.

Think about this, do you trust every rule from Easylist or uAssets? You disagree with this one because it affected you, but, for example, someone last time brought he concern about how 'dangerous' was to allow third party lists to just block websites/get the warning screen that it could be dangerous.
It was until recently when uBlock Origin lists would block ublock.org in the 'badware risks' list for these [reasons](https://github.com/gorhill/uBlock/wiki/Badware-risks#ublockorg).
The main thing was how uBlock.org page asks for donations and it could make people donating thinking it is the uBlock origin extension.
So recently they removed it, but they keep some rules in place to inject `uBlock is unrelated to the well-known uBlock Origin.` in the content page, right on the top, with the :style() action operator.

Do you agree or disagree with that? so the argument could go in circles for hours. Brave default lists account for 140K Adblock rules, and while you shouldn't trust anyone, well, you can't just start questioning some rules but no others.
How do you know a site with a warning is really bad or not, has trackers or malware or is a fake one? they were blocking uBlock.org for years probably, and like someone said "it is a working extension, and apparently it is not bad because Chrome extension store hasn't removed it"

Now, they added that message, and imagine the power filter maintainers have, they can literally inject ANY text in any website, remove any element and do whatever they want for good and bad purposes.

Recently uBlock added the trusted scriptlets, in uBlock they are limited to uBlock lists and custom filters only, in Brave at the moment any list can use them. Someone wrote an issue about how it should be limited to uBlock lists and Brave and that's it.
But think, uAssets are third party lists, why should the user blindly trust them? I have seen thousands of rules that are badly made, break compatibility with other adblockers for no reason, are not efficient, inject or change things they shouldn't (like the uBlock page).

So as you can see, there will be an endless argument about 'transparency' with adblocker rules and the hundred of list maintainers that exist today.

This is why Brave having a native adblockers and offering custom rules is what complements that. What is the point of custom adblock rules if nobody use them? why should Brave create an exception or a rule for everything?
Of course, it is better to whitelist than blacklist, and that's what happens here.

A network request gets blocked, gets easily logged in Brave shields panel and Devtools, and you use `@@` to whitelist the connection in whatever way. You don't agree with 127.0.0.1? well you just type `@@||127.0.0.1` and done.

The lists for the way Brave made them, can't be individually turned off, maybe someday, they have been working towards merging everything, but for example `gkboaolpopklhgplhaaiboijnklogmbc` which contains the `list_catalog.json` and `regional_catalog.json` was suppose to make things better but was revert it because of performance reasons.
It even allowed to easily 'hack it' and add the Default lists as a regional list and easily turn them off, making it easier to load the filters as custom lists and test it better that way.

That's why getting stuck in the whole 'transparency' is just not wrong, but useless, since we can just argue about every rule and question its purpose, or how the rule was made in X way and not Y, or why they used `$from` and not `$domain` which obviously will break most compatibility with other adblockers.

Again, the way to turn it off is custom adblock rules, I have currently like 500 custom rules to fix incompatible rules, make my own rules, improve things around, I had to start over because my old computer that broke I had like 2000. I never really report issues in websites, if I get an anti-adblock message, I fix it myself, if I get some regex with issues, I fix it myself, that's what makes Brave adblocker good, it gives you the custom adblocker rules and filters, and therefore you are able to turn off these rules you disagree with, for the most part, at least when it comes to network request they are the ones that can easily break things and easily be fixed.

Like some people don't like Brave whitelists their scripts and ads, but they could easily block them too.

Brave could easily add an exception to visualstudio, that will benefit you, but it doesn't change the argument, and the hope that things will get improved someday. I don't see it as a priority, since there are real features Brave should support that are more important, but I guess a question would be, would you rather a blank canvas you have to block everything yourself or a set of rules that you can whitelist or improve if necessary so you don't start from zero?

Your power to tell the adblocker what to do is there, even if 140K default lists already exist.

**Comment by levicki** [comment]
@Emi-Emi-Emi 

> The problem is that the 'transparency' of the adblockers is the filters themselves, they are open for anyone to see.

That's simply not true, because this particular list is not visible in the user interface.

> Think about this, do you trust every rule from Easylist or uAssets?

This is not a matter of trust at all, it's a matter of discoverability. Please don't change the subject.

> Do you agree or disagree with that?

I fail to see how that is relevant to the discussion.

> well, you can't just start questioning some rules but no others.

First, what I am questioning is the way this rule is tucked in a list which is not visible in the user interface and which can't be easily enabled / disabled when you need to check if it's the one causing issues.

Second, I am not questioning the rule &mdash; I am stating with confidence of a system administrator in a medium software company who was administering dozens of PCs in a domain for the last 15 years that this `localhost` rule will do more harm than good.

Finally, you can disagree with my viewpoint, but you can't tell me what I am allowed or not allowed to question.

> So as you can see, there will be an endless argument about 'transparency' with adblocker rules and the hundred of list maintainers that exist today.

Again you are missing the point &mdash; the only transparency I am interested in is from the Brave itself. Brave adblocking list should be visible in the user interface so I can inspect it, and it should be possible to enable / disable this list just like any other list.

> Again, the way to turn it off is custom adblock rules, 

And again, that's only a viable option if you know which list is causing a problem. Since you cannot turn off the built-in Brave list and you can't open it from the user interface to check its rules because it is not exposed you can't know which rule is causing the problem for you.

That's the lack of transparency I am talking about, and it is totally pointless to argue against having an option to turn off the Brave adblocking list &mdash; the option should have been there to begin with.

I see no reason why Brave's adblocking list should have preferential treatment compared to all other lists. Same goes for both built-in adblocking extension and for the Brave Shields extension &mdash; they should be visible in the extensions page and it should be possible to fully disable both if I want to do so.

> that's what makes Brave adblocker good, it gives you the custom adblocker rules and filters, and therefore you are able to turn off these rules you disagree with

**Newsflash:** uBlock Origin has had all those same options since forever and it is even more advanced than Brave adblocker. uBlock Origin is an extension and it is playing by the rules (you can install / uninstall / enable / disable it), and with Brave adblocker you can't do any of that because for a regular user it's an opaque black box built into the browser.

> Brave could easily add an exception to visualstudio...

Brave could have as easily tested the default rules with a couple of popular sites, e-government and e-banking apps and developer tools and ensured there's no breakage instead of having to fix it by adding exceptions after the fact.

> I don't see it as a priority, **since there are real features Brave should support that are more important**

Yeah, like installing not one but two VPN services on my PC without my informed consent which brings us back to the subject of transparency.

**No transparency example:**
 - Browser gets updated and suddenly you have some VPN services and autorun entries you didn't have before and didn't ask for because Brave wants to sell you VPN access.

**Transparency example:**
 - Browser gets updated and on next launch you get prompted whether you would like to sign up for VPN and if you accept services get installed, otherwise they don't get installed. Option is added to settings where you can sign up later which will install the services if you do.

No transparency example above is simply shady behavior which erodes trust of the user audience which Brave is trying to capture with their boasting about choices and privacy.

Same goes for:
 - impossible to uninstall hidden extensions (Shields, built-in adblocker)
 - invisible implicit adblocking lists which can't be disabled
 - invisible proxying of requests for chrome web store downloads

> would you rather a blank canvas you have to block everything yourself or a set of rules that you can whitelist or improve if necessary so you don't start from zero?

I am ok with having a default list &mdash; what I am not ok with is not being able to see it in the user interface and disable it if I choose so.

> Your power to tell the adblocker what to do is there...

The thing is &mdash; I really don't want to waste time on that.

In this particular case Brave was between me and my work. I had to try submitting feedback several times while disabling lists one by one until I realized that I have to fully disable ad & tracker blocking in Shields settings for that site in order for it to work. I was not aware of the default list, I had no idea where Brave saves it, and I couldn't find the rule responsible for blocking the `localhost` just from looking at the dev tools console.

I not only wasted considerable time to investigate this (and finally relented and turned all protection off to be able to finish work making a cure worse than a disease in the process), but I also wasted additional time reporting the problem here with absolutely no effect so far, and now I am wasting even more time arguing with you about something that should be obvious to anyone who doesn't have an agenda.

Fix it, don't fix it, I don't care. There are other browsers out there and failing that I can always make a custom build based on either Chromium or Firefox. That way if I waste time at least I know why.

**Comment by asdasdada89ays89ydas89dha8s9yhda** [comment]
You have to understand that 140K rules, can't be 'transparent' someone will have the power with the adblocker to implement whatever they want because they think it is needed.
So yes, it was relevant to the discussion, you agree or disagree adblockers injecting code like that? you agree or disagree blocking 127.0.0.1? it's obvious the reason for the question, you either agree with filter maintainers having the power or not. So I don't get 'what I don't get' from you, it's like playing 'dumb' because it doesn't help your case. The job of the adblock filters is a gray area, but the adblockers just do what they are told to do. Adding toggles million toggles for 140K rules because you might agree or disagree with some, it's not something to think about.

So it's obvious why I asked it and why I showed the example, because just like you don't agree with 127.0.0.1 being blocked as a third party connection in a random website, someone thinks uBlock.org shouldn't be blocked or manipulated by uBlock Origin team, just because it doesn't 'benefit' them. 

Of course the most simple answer is: if you don't like it, you can switch adblocker or Browser, because this is the world of Browsers and Adblocking.
You can easily use uBlock, turn Brave adblocker off and don't get these issues, you will get other issues, like Anti-Brave detection, but that's easily handled by uBlock by loading the scriptlet brave-fix in uBlock and done, `##+js(brave-fix)` will apply to all websites, which is better than what Brave does since Brave doesn't allow generic scriptlet injections.

Anyway, you reported the issue, your issue got ignored, you had kind of a valid reason for a whitelist and nothing happened. My point will always be, **what are you going to do?** sit on the corner and complain about it or do something about it?
I know most people would rather wait 2 years for a feature to appear in settings than hacking it and doing it themselves, but some stuff is like you spent more time typing the original issue, than `@@||127.0.0.1` and done.

That's my point.

That's why I never report any issue with adblocker lists, and that's exactly why, not because I fix stuff myself, it is because reporting and waiting, is usually a pain in the butt, always a waste of time especially when I can fix it myself, and I don't need to beg some people that have the 'power' of the lists to do it, when I probably already make better rules than they will ever make, I have even done PRs ignored by them, so that's the point. I don't just make issues hoping for fixed, when I can make a fix I made it, but always to get ignored or an issue always to get ignored even if I give the solution, they only need to copy and paste my rules.

Anyway, it was still a mistake to write a comment in this issue like 99% of the time, people don't like learning and complain at me like if I had any power only because I am honest about things and know the reality of internet life and dealing with devs and all and filter maintainers and that's why I seriously hope when I close a gtihub account, I will never have to open a new one ever again, always regret it, and I get tired of trying to fix or even commenting like if I was getting paid or something.

Have a good day.
