### ISSUE TITLE
"extension" overlay in settings covering options

### ISSUE THREAD

**Issue by IceHacks** [brave/brave-browser#3444]
## Test plan
   1. Navigate to `brave://settings`
   2. Click on a section. Ex: `customize fonts`
   3. Scroll down
   4. Extensions area should NOT be floating over existing settings (see below for previous behavior)

## Description 
When opening any section in `brave://settings` "extensions" overlays the content.

## Steps to Reproduce

   1. Navigate to `brave://settings`
   2. Click on a section. Ex: `customize fonts`
   3. Scroll down

## Actual result:
![image](https://user-images.githubusercontent.com/38994479/53202120-cc12e600-35c9-11e9-96c8-77ee893ef67d.png)
![da5udxortt](https://user-images.githubusercontent.com/38994479/53202361-578c7700-35ca-11e9-94a7-499358a401fd.gif)

## Expected result:
The extensions category should disappear when entering a section.

## Reproduces how often: 
Easily reproduced. Happens every time for me.

## Brave version (brave://version info)
Param | Value
--|--
Brave | 0.62.5 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24356

### Reproducible on current release:
It reproduces on the latest Brave Dev I do not have anyother brave versions.

### Additional Information
It doesn't happen in the latest Chrome Dev.

**Comment by rebron** [comment]
cc: @yrliou can you take a look?

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/macos-extensions-section-of-settings-shows-in-sub-sections-where-it-doesnt-belong-when-you-scroll-down/47025?u=eljuno

**Comment by willstocks-tech** [comment]
I was just about to log another issue, but then managed to find this one! I hadn't actually gone into other areas (because I hadn't needed to). I found I could apply `<settings-brave-default-extensions-page restamp style="display: none;">` to get around this while I was in Passwords (and it applies to the rest of the settings pages as well - woo).

Copy and paste from the issue I was about to log:

## Description 

MacOS Mojave (10.14.3) running Brave Version 0.61.51 Chromium: 73.0.3683.75 - if you navigate into settings, then passwords (assuming you have a long list of passwords), scroll down a little and notice that there's an "Extensions" box overlaying the passwords.


## Steps to Reproduce


   1. Open Brave
   2. Open Settings
   3. Click on Passwords
   4. Scroll down slightly

## Actual result:

![Screenshot 2019-03-20 at 23 17 25](https://user-images.githubusercontent.com/43744514/54725355-ab0cc900-4b66-11e9-963f-7bf17fe754ed.png)

Extensions box is overlaying the password list.

## Expected result:

The extensions box should NOT overlay the password list (not sure where it comes from, so for the sake of explaining: `<settings-brave-default-extensions-page restamp style="display: none;">`).

## Reproduces how often: 
I've tried restarting Brave a couple of times and the issue persists. Because it is now my main browser, I haven't gone to the effort to reinstall and I don't have another machine to test on!

## Brave version (brave://version info)

Brave Version 0.61.51 Chromium: 73.0.3683.75

### Reproducible on current release:
I have not installed dev/beta yet, but I will give this a go. Currently seeing this behaviour in the main, public release.

**Comment by TontyTon** [comment]
+1 from me. Filed an issue before finding this. 
 https://github.com/brave/brave-browser/issues/3853

This prevents from seeing full list of passwords and search engines and edit them.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.95 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from description

**Comment by znculee** [comment]
If you just want to view or set the options overlaid, you can simply zoom out.
