### ISSUE TITLE
Non browser window also has rounded corners

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#34475]
Maybe browser window only needs rounded corders?

<img width="1779" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/799231d2-3fb5-4844-ac92-55bd83c0c34c">

**Comment by simonhong** [comment]
@rebron @zenparsing @aguscruiz  WDYT?

**Comment by aguscruiz** [comment]
Yeah I think only the browser window should have that padding and rounded corners, these can go completely full size

**Comment by Emi-Emi-Emi** [comment]
I remember I mentioned this when I reported the padding in fullscreen videos, https://github.com/brave/brave-browser/issues/33879#issuecomment-1777671596 guess I didn't mind it much since I didn't make a proper issue.

But Fullscreen mode (F11) also get this padding, so I don't know if that's a 'meant to be' or it has to be removed to be a truly full screen experience.

**Comment by kjozwiak** [comment]
The above requires `1.61.93` or higher for `1.61.x` verification 👍
