### ISSUE TITLE
Remove calls to `/promotions` endpoint

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#34610]
## Description

Given that vBAT has been sunsetted, we do not need to hit the `/promotions` endpoint any longer. All calls to that endpoint can be removed.

Apparently browsers that are attempting to hit that endpoint are getting a `426` back.

**Comment by Miyayes** [comment]
We should have a followup issue to do code cleanup. So we can just stop the calls for now.

**Comment by zenparsing** [comment]
@deeppandya  Eventually, we should remove the endpoint implementations entirely, but for now it might be best to just modify [this](https://github.com/brave/brave-core/blob/af39b0a02af610eb272f84079ef80aecc3809261/components/brave_rewards/core/rewards_engine_impl.cc#L279) so that it immediately calls the callback with an empty vector.

**Comment by deeppandya** [comment]
> @deeppandya  Eventually, we should remove the endpoint implementations entirely, but for now it might be best to just modify [this](https://github.com/brave/brave-core/blob/af39b0a02af610eb272f84079ef80aecc3809261/components/brave_rewards/core/rewards_engine_impl.cc#L279) so that it immediately calls the callback with an empty vector.

That sounds good @zenparsing . Thank you
