### ISSUE TITLE
Brave IPFS Trustless client

### ISSUE THREAD

**Issue by vadimstruts** [brave/brave-browser#34840]
## Description 

When Brave is configured to use a public gateway, enforce checking IPFS hashes automatically. 
Currently there is several direction for the IPFS Trustless client implementation:
1. Using Local node configured as offline node.
2. Using Block approach (downloading blocks from the gateway and traversing through the graph)
3. Using CAR approach (downloading whole DAG as a CAR file from the gateway and traversing through the graph)
4. May be using some third party tool for validation of the CAR file

Some additional information from the discussion and analysis details about each of the approaches, have been added to separate Google doc and opened it for commenting by the next link:
https://docs.google.com/document/d/1qkWksiSTim24sxUHraNJzHKA-_Pu8mMF-JaEvKMoIlQ/edit?usp=sharing

**Comment by vadimstruts** [comment]
According to today's meeting, I would like to summarize the information:
Described investigation of the possible ways to implement Trustless client with using third party libraries.
- The preferred way is using **Rust IPLD library**: https://github.com/ipld/libipld/tree/master/macro
- Only required function should be bridged to C++
- Downloading of the CAR file, walking through the blocks of the CAR file, content verification, extraction etc, should be implemented on C++ side (According to the review first version of the trusted client implementation, using of the Rust library: `rs-car` was denied, according to Chromium restrictions).

Proposed next steps to follow:
1. Add to Brave third party the Rust Ipld library (and all it's dependencies).  
and Provide a set of C++ helper functions which are based on Rust IPLD library. It could be interfaces for codecs etc,
2. Add interception for redirection to the IPFS gateway link, and implement the requesting of the CAR file from the IPFS gateway's.
At the same time, we need to have cache for retrieved CAR files
3. Implement on the C++ side, the block orchestrator for a CAR file, which should provide walking by the CAR without loading the block content to the memory and with an ability to define Cid of the start point to walk. It must provide verification of the blocks, when block data is requested.

Investigation notes (working notes, draft notes): https://docs.google.com/document/d/1MtKOoLSexGkE3lNMQpyyuDx3-wY6MowmMNQKRZNEtzo/edit?pli=1

**Comment by John-LittleBearLabs** [comment]
> It must provide verification of the blocks, when block data is requested.
> without loading the block content to the memory

Verifying it involves hashing the content, and I'm not sure how you'd hash something that's not in memory, so combining these two points makes me think you're anticipating CAR files containing data you're not currently using. And to verify the URL matches the data you'd need a chain of blocks coming all the way from the content root... if you're not already then I'd like to encourage you to consider using a [dag-scope](https://specs.ipfs.tech/ipips/ipip-0402/#design-rationale) that isn't `all` since some websites can contain an awful lot of data.

> define Cid of the start point to walk

I'm guessing from this that by 'walking' a CAR you don't mean iterating the blocks in the order they appear in the archive, necessarily, but pathing through the DAG (for example - is this where you would implement _redirects and symlink handling?).

> cache for retrieved CAR files

Are you planning each cache entry to be a CAR with many blocks? I'm curious what the key would be - how would you determine which CAR files might contain a block you need for your current request's DAG?

**Comment by vadimstruts** [comment]
Short update:
----------------------------
- Added Rust Ipld library to brave third party. Here is list Library + dependencies.

| # | Library | Version |
| ---- | ---- | ---- |
| 1 | libipld | 0.16.0 |
| 2 | libipld-core | 0.16.0 |
| 3 | libipld-cbor | 0.16.0 |
| 4 | libipld-pb | 0.16.0 |
| 5 | libipld-json | 0.16.0 |
| 6 | libipld-macro | 0.16.0 |
| 7 | libipld-cbor-derive | 0.16.0 |
| 8 | blake2s_simd | 1.0.2 |
| 9 | cfg-if | 1.0.0 |
| 10 | cid | 0.10.1 |
| 11 | constant_time_eq | 0.3.0 |
| 12 | multihash | 0.18.1 |
| 13 | quick-protobuf | 0.8.1 |
- Created several functions for extracting information from the CAR file blocks.
- Started to design C++ part (request interceptions and orchestrating of the blocks), then will start to implement it.

**Comment by vadimstruts** [comment]
- Finished with preparing UML-like diagram for the C++ part (It is can be changed in details, or extended later)
- started to work on CAR file requester, at the same time the support of the the mixed mode (CAR + RAW blocks) is possible.
- Work on combining and decoding blocks
![image](https://github.com/brave/brave-browser/assets/118171981/5289dfe4-9426-413b-bc66-5d61b3779722)

**Comment by John-LittleBearLabs** [comment]
I think I have to question the meaning of `Block::IsRoot()`. Being a root is not really a characteristic of the block itself but rather how the block is being treated. The root I think you'd be most interested in is the content root of the URL you have from the user (or indirectly through a subresource), that is to say the block pointed at by their URL's origin. That's the root you need to know for the sake of IPFS symlinks & _redirects. This may line up with the root you're requesting from a gateway, but it doesn't always have to. 

For example, let's say you loaded 

`ipfs://bafybeifpdohhfv34hvepjalasz7luudx62wynzfwawxipfe4ixfxakfp7y/links.html`

Perhaps you did this with a CAR request, which gave you 
* `bafybeifpdohhfv34hvepjalasz7luudx62wynzfwawxipfe4ixfxakfp7y` - the content root, which tells you links.html is `bafkreidi53io2tethdu6fcyhxeq6ncluxjxugsppj6er3z4p4slnvstehy` and old is `bafybeiehttj335tokpsdam3h7igzxlill7zndlhfovktf7pcq7gqg4g3uy`
* `bafkreidi53io2tethdu6fcyhxeq6ncluxjxugsppj6er3z4p4slnvstehy` which is the content of links.html

The roots here all line up.

Then rendering that page requests a subresource `ipfs://bafybeifpdohhfv34hvepjalasz7luudx62wynzfwawxipfe4ixfxakfp7y/old/lily.jpg`

You wouldn't want to do a CAR request rooted at `bafybeifpdohhfv34hvepjalasz7luudx62wynzfwawxipfe4ixfxakfp7y`, because you already have that block so you wouldn't re-request it. You don't have the block for old, so you start there and request

`ipfs://bafybeiehttj335tokpsdam3h7igzxlill7zndlhfovktf7pcq7gqg4g3uy/lily.jpg`

Now, to you, the content root is still bafybeifpdohhfv34hvepjalasz7luudx62wynzfwawxipfe4ixfxakfp7y, but the only root the gateway sees for this request is bafybeiehttj335tokpsdam3h7igzxlill7zndlhfovktf7pcq7gqg4g3uy.

I do acknowledge it's not super likely the same block will appear as a content root in one site and not in another. It's kinda rare for a normal-ish user to have requests for sites that contain other sites and also those other sites. The closest thing to a realistic case I can think of is someone loading a preview page for an NFT that contains an image, and then opening the image itself (raw) in a separate tab (in which case your jpeg or whatever is its own root).

Tangentially, I would encourage you not to let the information about byte offset into a particular CAR file escape the CAR reader, since nothing else should want to know and it could get confusing since its offset will be different when that block appears in different CARs and there will be no offset when it doesn't come from a CAR. And it really just shouldn't be important since you're copying the bytes into a new owning structure anyhow.

Similarly, I think it could be inconvenient down the road to require that the CID appear in contiguous memory with the block content in order to [decode it](https://github.com/brave/brave-core/blob/ipfs-trustless-client/components/ipfs/rs/src/block_decoder.rs#L45). The CID would be separate if you were doing a raw block request and (I would hope) if you're looking it up in cache. It wouldn't be difficult to have a convenience function for CAR parsing that parses out the CID from a contiguous array of bytes like this and then calls a decode function that takes the CID as a separate parameter.

> * Finished with preparing UML-like diagram for the C++ part (It is can be changed in details, or extended later)
> * started to work on CAR file requester, at the same time the support of the the mixed mode (CAR + RAW blocks) is possible.
> * Work on combining and decoding blocks
> * Branch: https://github.com/brave/brave-core/tree/ipfs-trustless-client
>   ![image](https://private-user-images.githubusercontent.com/118171981/306025063-40c4d839-2967-4f45-8e5e-f4fd8da5ffec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NjMwMTIsIm5iZiI6MTcwOTY2MjcxMiwicGF0aCI6Ii8xMTgxNzE5ODEvMzA2MDI1MDYzLTQwYzRkODM5LTI5NjctNGY0NS04ZTVlLWY0ZmQ4ZGE1ZmZlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxODE4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2E5NTBjNDllNWNlNzA4NTc0MGY0M2M4Y2M4YTI4ZTNjM2FhNzYzZDYwZjg3NTNkMjNlZTRlYzAzMTFkMzU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vl8rtmrhwsQ_aJ1jvEDX1Brr-bh7WHB-SpIrKXTwYtE)
