### ISSUE TITLE
[ads] Optimize javascript requests for non rewards users

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#35205]

**Comment by btlechowski** [comment]
Verified with

Brave | 1.63.149 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | 16509c04a66afcc00d180c0b62a887b9fc4776a2
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/21529

<details>

</details>

**Comment by bridiver** [comment]
https://github.com/brave/brave-browser/issues/34919 was closed as a duplicate of this, but this issue provides no information at all about what we're doing here and it doesn't appear to actually resolve the issues brought up in https://github.com/brave/brave-browser/issues/34919 because it's still calling `XMLSerializer` on every page
