### ISSUE TITLE
Implement seeker bar for PIP window

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#35263]
PIP window for videos should have seeker bar at the bottom.

For this we need implement

* content/browser/picture_in_picture/video_picture_in_picture_window_controller_impl.cc
  - Caches MediaSession info needed for seeker (media_position_)
  - Unfortunately, the MediaPosition propaged from this seems to be incorrect
    - this seems to be because media_session_impl Rebuild the position ignoring the passed value(which is correct) from media_session_controller.
* video_overlay_window_views should have seeker UI and time stamp based on the data

* when dragging or clicking seeker bar, media should be moved to the position
  - content/public/browser/media_session.h is would be the controller.

**Comment by TEMP-ad** [comment]
Just tested this on Windows 11 22H2 and I got some feedback for this.

Tested it on Youtube and https://googlechrome.github.io/samples/picture-in-picture/

1. The seeker bar can't be used because PiP resizing action will be triggered.
2. Even if I try to be on top of the seeker bar carefully, it doesn't scrub through videos as you shown in the PR.
3. the seeker bar doesn't go away and it is always there on the PiP, paused or playing a video. Shouldn't it be seen only on hover as other elements?
4. When video is paused, and you go PiP, it starts with 00:00 and it is only when you click play when it goes to the correct position.
5. Keyboard arrows didn't scrub videos either through the PiP, but don't know if that was part of the PR, or it might be in the future, or it is harder to implement.

It's great to see improvements in PiP, good job @sangwoo108 👍

**Comment by sangwoo108** [comment]
@TEMP-ad Thank you so much for the valuable feedback. I'll check them out.

> the seeker bar doesn't go away and it is always there on the PiP, paused or playing a video. Shouldn't it be seen only on hover as other elements?

This one is what's intended at the moment, but we're discussing it. 
https://github.com/brave/brave-core/pull/21566#discussion_r1455036911

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.134 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | cdcba6ef408b305ce19b1a9b3fabbb5e9e3b36bf
OS | Windows 11 Version 23H2 (Build 22631.3085)
```
1. Installed 1.63.134
2. launched Brave
3. opened https://googlechrome.github.io/samples/media-session/index.html in a new tab
4. clicked Video link to open in a new tab via context menu
5. play a video
6. clicked three dot menu in the player to open `PIP` window
7. clicked media control in the toolbar 

Confirmed timestamp is visible when mouseover in PIP window \
Confirmed Seeker is visible on the window regardless of mouse position
Confirmed when dragging or clicking seeker, video moved position

example | example 
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/34d60c04-e5a6-41de-b5d7-809149afe323)|![image](https://github.com/brave/brave-browser/assets/98358127/70d39c6f-2aaf-48c2-9031-3007ca97a736)


https://github.com/brave/brave-browser/assets/98358127/45715498-0851-4b5b-a744-38440e6e3292
