### ISSUE TITLE
Password popup screen shows notice about "Brave Canary"

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#35378]
## Description 
Reported by @bbondy on Android.

Besides Canary (versus Nightly) it also basically says "Brave 121"

![image](https://github.com/brave/brave-browser/assets/4733304/d8b9e24f-7f17-475b-aa90-8700946f7819)
![image](https://github.com/brave/brave-browser/assets/4733304/a9dc3cf0-e680-4095-b72e-fe1a77be5799)

**Comment by AlexeyBarabash** [comment]
will be closed when griffin pr will reach production

**Comment by AlexeyBarabash** [comment]
Steps to reproduce:
1. Get clean install of either Nightly or Beta, not Stable
2. Open any site - I used gmail.com -  which require login, login and save login with popup from password manager. 
3. Actual - migration warning.
4. Expected to have no warning.

**Comment by AlexeyBarabash** [comment]
As the [PR](https://github.com/brave/brave-variations/pull/948) to fix the issue is at `brave-variations` repository, I'll put some  details here.

Chromium allows downstream browsers to implement their own password storage [link](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/password_manager/android/java/src/org/chromium/chrome/browser/password_manager/PasswordStoreAndroidBackendFactory.java;l=13?q=chrome%2Fbrowser%2Fpassword_manager%2Fandroid%2Fjava%2Fsrc%2Forg%2Fchromium%2Fchrome%2Fbrowser%2Fpassword_manager%2FPasswordStoreAndroidBackendFactory.java&ss=chromium%2Fchromium%2Fsrc).

Google Chrome uses GMS to store the passwords at Google Account.  

The warning in the issue means that all channels besides Stable will eventually store the passwords at the Google Accout rather then in Chromium password manager. The is not applicable for Brave because we don't provide any of `PasswordManagerBackendSupportHelper`/`PasswordStoreAndroidBackendFactory`. 

The warining behaviour is manager by `kUnifiedPasswordManagerLocalPasswordsMigrationWarning` and can be removed via Griffin.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240216.010 release-keys
Brave build: 1.65.89 
Chromium: 123.0.6312.58 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Install and launch **Brave Beta** `1.64.103`
2. Go to any website that requires sign-in, for example, https://feedly.com
3. Sign in > Save login credentials > *Confirm that bottom sheet pop-up is shown*
4. Uninstall Brave > Install Brave Beta `1.65.95` or newer
5. Repeat steps 2 and 3 > *Verify that bottom sheet pop-up is not shown*

**ACTUAL RESULTS:**
- Verified that the bottom sheet pop-up message saying about saved passwords is not shown anymore

---------------------------

https://github.com/brave/brave-browser/assets/128532965/c95fe6ea-39bd-4890-a931-befeedf49ea5
