### ISSUE TITLE
Enable updated horizontal tabs design by default

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#35529]
## Description 

Enable horizontal tabs design by default.
brave://flags/#brave-horizontal-tabs-update

## Expected result:
![image_720](https://github.com/brave/brave-browser/assets/5951041/5b2ba8ee-5e8e-4a35-b284-671cbb398bb7)
![image_720-2](https://github.com/brave/brave-browser/assets/5951041/c9657bfb-20d0-435e-ab50-de7624664718)

## Reproduces how often: 

n/a

## Brave version (brave://version info)

Target 1.63.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.64.48 Chromium: 121.0.6167.139 (Official Build) nightly (64-bit)
-- | --
Revision | 741f7ee622bdfde5e10e3beda02288f3c056287e
OS | Windows 10 Version 22H2 (Build 19045.3996)
```

![image](https://github.com/brave/brave-browser/assets/387249/01aea45b-2187-40c9-9ae2-912763cd9b95)

**Comment by kjozwiak** [comment]
Removing `QA Pass` as the above will need to be re-checked via `1.63.x` as it was uplifted as per https://github.com/brave/brave-core/pull/21925#pullrequestreview-1871141132. Used https://github.com/brave/brave-browser/issues/35529#issuecomment-1928173278 as the needed verification for uplift into `1.63.x`.

The above requires `1.63.149` or higher for `1.63.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.149 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | 16509c04a66afcc00d180c0b62a887b9fc4776a2
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

1. Installed 1.63.149
2. launched Brave
3. opened brave://flags
4. confirmed brave://flags/#brave-horizontal-tabs-update is set to Enabled (default)

<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3a27ba97-4c04-45d8-b818-e895eea2e82d">


before | after 
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/a5d82570-7342-47ee-8544-adbcb974ac38)|![image](https://github.com/brave/brave-browser/assets/98358127/34be2382-71d8-4470-8dad-ea3884f7c43d)

Light theme | Dark theme
----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/1839fa77-7976-4073-9185-0525fdc785a1)|![image](https://github.com/brave/brave-browser/assets/98358127/4bf312ee-6bc9-4c48-899c-4c78cd35f247)

**Comment by devingfx** [comment]
Hi !

I disabled this flag from the begining (with `--disable-features=BraveHorizontalTabsUpdate` on CLI under linux mint), because I want my desktop browser **tabs**, look like tabs, not touch device buttons !

Over the years and updates, small detail by small detail, the design of TABS produced with this disabled flag do not respect the orignal intent, and we can see the "disgusting buttons" design overflowing the old tabs design ( especially sizing / padding ).

Look for yourself...

#### Normal tabs
`  |  active tab                   |  unactive tab over            |  unactive tab         `
<img width="639" height="84" alt="Image" src="https://github.com/user-attachments/assets/6cb17740-b929-4934-8b1c-352525de2a08" />
- [active tab]: vertical alignment is off
- [unactive tab over]: don't look like a tab / vertical alignment is off

#### Pinned tabs are not usable anymore :
=> not enough place to show the favicon

`  |1|2|  unactive tab                 |  unactive tab              `
<img width="474" height="83" alt="Image" src="https://github.com/user-attachments/assets/729a7647-3c3b-44f7-b406-fcd25733c713" />

- [1]: pinned active tab
- [2]: pinned unactive tab over

`  |5 pinned|  unactive tab                 |                  `
<img width="440" height="86" alt="Image" src="https://github.com/user-attachments/assets/d3023f3f-de92-4417-a2be-784371a2b4c1" />

=> pinned tabs are mostly not shown

Questions:   
Are we forced to adopt the disgusting button design for touchscreen on desktop ?
Is this flag implemented by Brave? Or chromium ? ( if so, please point me out where to file a issue 🙏 )

**Comment by devingfx** [comment]
As off 2026-06-06, last update does have pinned tab corrected and usable again! woooh !

<img width="537" height="81" alt="Image" src="https://github.com/user-attachments/assets/5d6e72ba-a5dc-497b-ad52-e2b9c3bc521f" />

Tabs design is still off though ...
