### ISSUE TITLE
Add search widget to the NTP

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#35535]
## Description 

Add a way for users to search from the new tab page via a search widget. 
Users should be able to hide the search widget similar to other NTP widgets.
Autocomplete should be available for Brave Search in the search widget with similar results to the omnibox which includes history and bookmark results, and `https://search.brave.com` 

## Design:
<img width="676" alt="Screenshot 2024-06-10 at 12 53 26 PM" src="https://github.com/brave/brave-browser/assets/5951041/8c7c52ad-aeca-4168-9508-fdf76cd4036b">

<img width="715" alt="Screenshot 2024-06-10 at 12 53 42 PM" src="https://github.com/brave/brave-browser/assets/5951041/d9b681d5-79b0-41af-85fc-3fa5df2bdb10">

Figma: `https://www.figma.com/file/lVTufBkl5eNrtOQjlAHxjb/Search-box-in-NTP?type=design&node-id=1-2&mode=design&t=4llye5WQz21EiJ2K-0`

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

https://www.figma.com/file/lVTufBkl5eNrtOQjlAHxjb/Search-box-in-NTP?type=design&node-id=1-2&mode=design&t=CtsGpqZJfeEELI1K-0

**Comment by fallaciousreasoning** [comment]
Closing this, as it's done (but across a number of other PRs

**Comment by kjozwiak** [comment]
As discussed via https://bravesoftware.slack.com/archives/C7VLGSR55/p1718248224714979?thread_ts=1718227636.552569&cid=C7VLGSR55, we'll wait till all the needed PR/fixes are uplifted from `1.69.x` -> `1.68.x` before QA starts running through the above feature. @fallaciousreasoning & @rebron will provide the list of issues that need to be uplifted before the above can be checked/verified.

**Comment by fallaciousreasoning** [comment]
Issues which need uplifting to 1.68 (split across a few PRs) to test this:

## Issues:
- https://github.com/brave/brave-browser/issues/38977
- https://github.com/brave/brave-browser/issues/38976
- https://github.com/brave/brave-browser/issues/38943
- https://github.com/brave/brave-browser/issues/38941
- https://github.com/brave/brave-browser/issues/38909
- https://github.com/brave/brave-browser/issues/38704
- https://github.com/brave/brave-browser/issues/38610

## Uplift PRs (some of the issues are in a single PR, and some uplifts have multiple PRs to avoid rebase conflicts)
- https://github.com/brave/brave-core/pull/24139
- https://github.com/brave/brave-core/pull/24177
- https://github.com/brave/brave-core/pull/24084
- https://github.com/brave/brave-core/pull/24140

## Test Plan

1. The feature should be enabled by default (the NTP Search box should show on the NTP)
2. Brave Search should be the default selected engine
3. It should be possible to open the search engine box while the search box is closed (by clicking on the search engine icon)
4. It should be possible to open the search engine box while the search box is open (by clicking the search engine icon)
5. It should be possible to select a search result with the mouse
6. It should be possible to select a search result with the keyboard (up/down/enter)
7. It should be possible to open search results in a new tab (with Ctrl+Click, Ctrl+Enter, middle click)
8. If you enter a URL the first result should take you directly to that URL, rather than doing a search
9. It should be possible to change search engine (by click on the search engine dropdown)
10. By default, only Brave Search should be in the dropdown
11. It should be possible to customize the list of search engines in the dropdown by clicking on `Customize list`
12. If you disable all search engines then the searchbox should disappear from the NTP
13. If you reenable after disabling all engines Brave Search should be enabled
14. The search box should remember the last search engine you used across reloads and browser relaunches
15. If you disable the last used search engines, another enabled search engine should take its place.
16. Ask Leo should appear on all searches
17. Clicking the `Ask Leo` result should open leo in the sidebar
18. Brave search should have `Search the web privately` as the placeholder text
19. Other search engines should have `Search the web` as the placeholder text
20. Clicking away from the search box when open should close it

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` per today's desktop planning mtg

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.68.106 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | 8d682ca0cb836cac019e09be7744d3852e68953e
OS | Windows 11 Version 23H2 (Build 22631.3810)
```
1. Installed 1.68.106
2. launched Brave
3. completed onboarding screens and clicked Finish 
4. confirmed Search widget is shown on NTP page by default
5. confirmed Brave icon is shown by default as search engine
6. clicked in the Search widget field
7. confirmed Search widget shown above
8. clicked Brave icon in the Search box
9. confirmed search engine list is shown via `Customize Dashboard` 
10. enter a string in the search field (`Olympics`)
11. confirmed able to select a search result with the mouse
12. confirmed able to select a search result with the keyboard (up/down/enter)
13. confirmed able to select open search results in a new tab (with Ctrl+Click, Ctrl+Enter, middle click (scroll wheel click))
14. entered bbc.com in the search field and press keyboard enter
15. confirmed the first result navigated directly to that URL (bbc.com), rather than doing a search



step 3 | step 4 | step 7 | step 9 | step 10 | step 11-12 | step 13a| step 13b | step 14 | step 15
----- | ----- | ------| ------ | ------ | ----- | -----| ----- | ------ | ----
![image](https://github.com/brave/brave-browser/assets/98358127/82951364-9585-4f5a-8c8b-e14647cc8edb)|![image](https://github.com/brave/brave-browser/assets/98358127/a3d48afd-9cf2-4925-9e95-dd46774d703e)|![image](https://github.com/brave/brave-browser/assets/98358127/9d43551f-dbfb-4d11-a41c-490aad316995)|![image](https://github.com/brave/brave-browser/assets/98358127/1ce4c7dc-ce0f-41f9-90c4-14d9cf116680)|![image](https://github.com/brave/brave-browser/assets/98358127/7f7ff493-146a-4697-9874-bed39d15abad)|![image](https://github.com/brave/brave-browser/assets/98358127/f70eedc2-762f-41bc-8e7d-0a8e1d8f89d4)|![image](https://github.com/brave/brave-browser/assets/98358127/f8ad7b39-8a8c-48a8-95d6-9aaad901d752)|![image](https://github.com/brave/brave-browser/assets/98358127/22bac006-8498-4125-b940-c137468b2881)|![image](https://github.com/brave/brave-browser/assets/98358127/e60da682-2fad-4f96-ab96-436b133df3d5)|![image](https://github.com/brave/brave-browser/assets/98358127/d50ff284-87ee-48a6-bc09-cebf24422ccf)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.68.114 Chromium: 127.0.6533.26 (Official Build) beta (x86_64)
-- | --
Revision | 1eae2f949cf44b11030e6abb82a7b72f010538b1
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.68.115 Chromium: 127.0.6533.26 (Official Build) beta (64-bit)
-- | --
Revision | eb9eb125805c393d370bb000a19164da9f344726
OS | Linux

<details>
<summary>NTP Search widget - PASSED</summary>

1. confirmed Search widget is shown on NTP page by default
2. confirmed Brave icon is shown as search engine by default 
3. confirmed if Brave search is default SE, `Search the web privately` text is shown as the placeholder text
4. entered a search term in the search widget field (eg.`Olympics`)
5. confirmed able to select search result with the mouse
6. confirmed able to select a search result with the keyboard (up/down/enter)
7. confirmed results are shown in the same tab
8. confirmed able to select open search results in a new tab (with Ctrl+Click, Ctrl+Enter, middle click)
9. entered `bbc.com` in the search field and press keyboard enter
10. confirmed the first result navigated directly to that URL (bbc.com), rather than doing a search

![image](https://github.com/brave/brave-browser/assets/34715963/049934f0-d844-485e-b60e-90509fc2d70f)|![image](https://github.com/brave/brave-browser/assets/34715963/f2c0c877-ab71-4626-b19c-046feebaa87f)|![image](https://github.com/brave/brave-browser/assets/34715963/56c1856e-9f30-4d81-92d1-dc3d4668d466)|![image](https://github.com/brave/brave-browser/assets/34715963/bc29aa96-243a-4333-bb5a-90c6b5136ab8)|![image](https://github.com/brave/brave-browser/assets/34715963/7fee2f5e-875e-45bb-85ef-2c7e846f4dad)
--|--|--|--|--






</details>

<details>
<summary>Customize search engines - PASSED</summary>

Case 1:  Keep existing search engines and `Brave` as a default in `brave://settings/search` - PASSED
<details>

1. clicked Brave icon >> Customize list in the NTP search widget
2. selected `Google` & `DuckDuckGo` search engines from Search engine window 
3. confirmed both the search engines `Google` & `DuckDuckGo` are shown in the dropdown 
4. confirmed able to pick different search engine i.e. Google, while the search box is focused by clicking `Google`
5. enter a search term `Olympics` and search results shown using Google search engine 
6. clicked `Customize list` from the dropdown to open customize dashboard 
7. unchecked all search engines and toggle for `Show search widget on the new tab page` turned off
8. confirmed the Search box disappeared from the NTP
9. clicked `Customize` at the bottom right of the screen
11. enabled toggle for `Show search widget on the new tab page`
12. confirmed Brave was selected by default  
13. confirmed Search widget is shown on NTP with Brave as a default Search engine
14. click Brave icon in the Search box and to open dropdown 



![image](https://github.com/brave/brave-browser/assets/34715963/7d2831d4-014d-42bd-ab18-3e3a5b252b71)|![image](https://github.com/brave/brave-browser/assets/34715963/abe6a6a2-917b-4170-bf85-26dd1bd72d3c)|![image](https://github.com/brave/brave-browser/assets/34715963/a7623851-e77e-4dbe-94d3-06ae9f038393)|![image](https://github.com/brave/brave-browser/assets/34715963/88699195-f593-4ea0-a4e4-91d95afc902c)|![image](https://github.com/brave/brave-browser/assets/34715963/41cd8ead-24f0-4c7f-9653-3b0715cb7ca1)
--|--|--|--|--



</details>

Case 2:  Remove some of the available SE and make `Qwant` as default - `PASSED`
<details>

1. clicked Brave icon >> Customize list in the NTP search widget
2. clicked `Customize available engines` link in the Search dashboard window 
3. verified `brave://settings/search` page opened as expected
4. deleted `Google`, `DuckDuckGo` & `Bing` search engines the page via 3 dots menu
5. clicked 3 dot menu for `Qwant` and clicked `Make default`
6. confirmed `Qwant(Default)` text shown 
7. verified Normal window in the `brave://settings/search` shown `Ecosia`
8. opened a new tab page and omnibox is shown placeholder text `Search Ecosia or type a URL` as expected
9. clicked `Customize list` in the search widget to open Search dashboard
10. confirmed `Google`, `DuckDuckGo` & `Bing` are not listed
11. selected `Qwant` and unselected `Brave` from customize list and closed the window
12. confirmed `Qwant` is shown by default in the Search widget
13. searched for `Olympics` 
14. verified `Enable search suggestions?` text is shown as expected 
15. selected `Olympics - Qwant Search` entry
16. confirmed results with `Qwant` SE shown

 
![image](https://github.com/brave/brave-browser/assets/34715963/d8442e2e-f061-4067-9f13-9f9560587cbf)|![image](https://github.com/brave/brave-browser/assets/34715963/d11fb29d-58f9-420d-b3b4-81b79b755774)|![image](https://github.com/brave/brave-browser/assets/34715963/e4872c8a-7dad-46da-9908-447ada1ec509)|![image](https://github.com/brave/brave-browser/assets/34715963/199a1443-f61c-4580-8602-88c93291eea9)
--|--|--|--


</details>
</details>

<details>
<summary>Verify all of the listed SE work as expected in NTP Search widget - PASSED</summary>

1. clicked `Brave` icon in the NTP search widget while not focused
2. clicked `Customize list` and unchecked Brave and selected other search engines (eg. Start page & Bing) via Search dashboard 
3. clicked `Brave` icon -->`Customize list`
4. confirmed both the search engines i.e. eg. Start page & Bing listed
5. selected `Start page`
7. searched for `Olympics` via `Start page` in the NTP 
8. confirmed results shown as expected 
9. confirmed the last search engine used, Start Page, persisted across reloads and browser relaunches
11. disabled `Start Page` via Search dashboard 
16. confirmed if the last used search engine, eg. `Start page` is disabled, another enabled search engine, eg.`Bing` is shown in the NTP search box
18. confirmed if other search engines are selected, eg. `Bing`, `Search the web` text is shown as the placeholder text
19. confirmed able to search with `Bing` search engine
20. clicked `Customize` >> `Search`
21. enable all search engines (Brave, Google, DuckDuckGo, Qwant & Startpage, Ecosia) and close the window
22. click SE icon (`Bing`) to pick another SE (`Qwant`)
23. confirmed able to pick a different search engine while the search box is not focused (by clicking on the search engine icon)
24. confirmed search results are returned with `Qwant` and results returned as expected with all the other search engines


![image](https://github.com/brave/brave-browser/assets/34715963/5a08ee8a-61cd-4cba-9790-270eaf7efb35)|![image](https://github.com/brave/brave-browser/assets/34715963/051e517c-c1fd-4412-811f-1a7d4e61e534)|![image](https://github.com/brave/brave-browser/assets/34715963/0f21cd1d-ed51-424f-b71e-635d755313e6)|![image](https://github.com/brave/brave-browser/assets/34715963/a5e5384a-6238-456d-9a8d-40845dd29f9a)|![image](https://github.com/brave/brave-browser/assets/34715963/2e59e4f6-e8d0-4a2e-b1a8-567925f69d97)|![image](https://github.com/brave/brave-browser/assets/34715963/ba8f518f-8cef-4971-b989-eff7bc9e18af)|![image](https://github.com/brave/brave-browser/assets/34715963/b490613c-4ba7-4263-82c8-8f2d02e2b520)|![image](https://github.com/brave/brave-browser/assets/34715963/a762e239-014f-4d0d-b178-60259aa65511)
--|--|--|--|--|--|--|--







</details>

<details>
<summary>Ask Leo - PASSED</summary>

1. entered a search term in the NTP Search widget
2. confirmed `Ask Leo` is shown in the search list
3. clicked `Ask Leo` result 
4. confirmed Leo sidepanel opened 
5. clicked `I understand`
6. confirmed Leo query results shown in the sidepanel  
7. confirmed when clicking away from the search box when focused, Ask Leo option closes as expected 

![image](https://github.com/brave/brave-browser/assets/34715963/bb3e9faf-0ece-45bb-b096-ba51de2dc6b0)|![image](https://github.com/brave/brave-browser/assets/34715963/9aea33ca-134a-41de-b978-268ac33f555f)|![image](https://github.com/brave/brave-browser/assets/34715963/c36e7028-2f27-412c-861a-fa5ce4dcb06f)
--|--|--

</details>
