### ISSUE TITLE
Widevine + Arm64 - move to Chrome Update Service

### ISSUE THREAD

**Issue by marcpems** [brave/brave-browser#35605]
## Description 
For Arm64 client Widevine is presently running emulated. With Chrome canary build now offering builds for Arm64 can this emulation workaround be removed and Widevine acquired and run native Arm64?

**Comment by rebron** [comment]
cc: @mihaiplesa

**Comment by mherrmann** [comment]
I presume this is about Windows. There, Widevine actually isn't running emulated on Arm64 Brave. It's running natively. It's only running emulated on x64 Brave (where all of Brave is running emulated, if you will).

Still, the way we obtain Arm64 Widevine on Windows is very complex, due to licensing restrictions. We should check if Widevine is now available from Google's component update server.

**Comment by mherrmann** [comment]
Resolved by https://github.com/brave/brave-core/pull/23415.
