### ISSUE TITLE
Adapt to uBO's `scriptletGlobals` change from `Map` to object

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#35679]
In https://github.com/gorhill/uBlock/commit/869a653fdf2dd4e5b0151530bd58e1059d1318d2#diff-b006827b72fe768a6cb08f3123783752a4a23ccc95c55467f24b77addac88a29R282, `scriptletGlobals` was modified to become a plain JS object instead of a `Map`.

As mentioned [here](https://github.com/brave/brave-core-crx-packager/pull/829#pullrequestreview-1849928885), we'll need to use a `Proxy` object to restore compatibility with the older `Map` methods to ensure that users can migrate gracefully to the newer resource versions when we release them.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.64.41 Chromium: 121.0.6167.139 (Official Build) nightly (64-bit)
-- | --
Revision | 1c56846eb16cec835298c09cd75ec45fc425507b
OS | Windows 10 Version 22H2 (Build 19045.3996)
```

**Comment by kjozwiak** [comment]
The above requires `1.62.159` or higher for `1.62.x` verification(s) 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.161 Chromium: 121.0.6167.139 (Official Build) (x86_64)
-- | --
Revision | 9afaacd1500fdbd60ed4500b63b9ab85597ef933
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.62.161 Chromium: 121.0.6167.139 (Official Build) (64-bit)
-- | --
Revision | 9afaacd1500fdbd60ed4500b63b9ab85597ef933
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

**_Youtube home page_**

- opened home page. 
- Navigated way and came back to youtube 
- no ads are shown

1.62.156 | 1.62.161
----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/cfaeac5b-8b0b-400f-8488-09f67c22747f)|![image](https://github.com/brave/brave-browser/assets/98358127/1b0f74b9-e060-4ceb-8cb5-292239aa3254)

No pre-roll/skip-ad buttons

- **_Not seeing ads during starting of the video or in-between seek positions 
https://www.youtube.com/watch?v=gfZWzD7COwo**

https://github.com/brave/brave-browser/assets/98358127/12df8480-f2ae-4beb-935a-40dfb20589a3

Visited several news sites. No ads are shown

CNN |BBC
---|----
![image](https://github.com/brave/brave-browser/assets/98358127/2b1b32c3-b441-436e-b42f-0aef85073493)|![image](https://github.com/brave/brave-browser/assets/98358127/6ec4a240-ef79-4a6b-b80d-18b7c6ec8076)


**_Movies & TV_** - PASSED
Confirmed no pre-roll ads, or ads in-between seek positions
example | example 
--- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/e9680366-9bd1-4ffa-a96e-fc6e16838f85)|![image](https://github.com/brave/brave-browser/assets/98358127/012acea2-fb05-45b8-8e77-edf98fc25195)

**_Searches_**

- searched for minecraft  (https://www.youtube.com/results?search_query=minecraft+)
- clicked on search results
- Confirmed no ads in or around the search results

example | example 
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/a61c2fc9-c718-4b0e-8c90-b00351b9e475)|![image](https://github.com/brave/brave-browser/assets/98358127/65269c77-2a3a-4811-99cd-ad83b8e099b3)

Shields Down/UP

- loaded youtube.com
- disabled Shields by setting them to Down
- Home page shown ads
- clicked on random videos, from different locations
- confirmed I saw various types of ads (pre-roll, interstitial, and non-video static ads on the homepage and search results)
- renabled Shields by setting them to Up
- Confirmed no further ads seen after Shields were Up

**_Ads are shown on the home page when shields are Down but no longer no when Shields Up_**

Shields Down | Shields Up
----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/e370c9d6-f961-40c0-a471-be5e55da0e50)|![image](https://github.com/brave/brave-browser/assets/98358127/6360a922-2f38-4678-8af2-86700d348ced)

**_Ads are shown at the beginning when Shields Down but no longer shown when Shields Up_**

Shields Down | Shields Up
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/b99a7cee-40d3-4ea3-97b2-1b3cd5e468b4)|![image](https://github.com/brave/brave-browser/assets/98358127/a790bfb9-4c68-4dbf-a661-4bf93ac402bc)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.62.161 Chromium: 121.0.6167.139 (Official Build) (64-bit) 
Revision	9afaacd1500fdbd60ed4500b63b9ab85597ef933
OS	Linux
```

**_Youtube home page_**

opened home page.
Navigated way and came back to youtube
no ads are shown

1.62.156  | 1.62.161
--- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/4b06dee4-083f-4647-b5bb-1ad5f66065bd)|![image](https://github.com/brave/brave-browser/assets/98358127/71938b2a-1761-442f-9d4f-a819ac4fc25c)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` running `Android 14` using the following build(s):

```
Brave | 1.62.162 Chromium: 121.0.6167.164 (Official Build) (64-bit)
--- | ---
Revision | c18c9cc62d2b4376a5ada5b98b673dfc7994f20d
OS | Android 14; Build/UP1A.231005.007; 34; REL
```

#### `YouTube.com` homepage - `PASSED`

<details>

### Steps:
1. new profile
2. load `youtube.com`
3. stay logged out
4. click around
5. return to `youtube.com`

#### Confirmed no visible ads when returning to `youtube.com` after navigating away

`1.62.156` | `1.62.161`
----------|-----------
![Screenshot_20240207_121805_Brave](https://github.com/brave/brave-browser/assets/2602313/eb0725df-86ab-4523-b678-dafbd6f90877) | ![Screenshot_20240207_121330_Brave](https://github.com/brave/brave-browser/assets/2602313/b7bcf0b8-d9ab-43f3-bab3-071430e35f3a)


</details>

#### No pre-roll/skip-ad buttons (`screencast`) - `PASSED`

<details>

https://github.com/brave/brave-browser/assets/2602313/d36107ea-fa69-413d-b06b-2e6e1154fe2f

</details>

#### Direct navigations (from URL) - `PASSED`
<details>

loaded `https://www.youtube.com/watch?v=dtp6b76pMak`

### Confirmed no pre-roll ads, or ads in-between seek positions

`1.62.156` | `1.62.161`
----------|-----------
![Screenshot_20240207_123134_Brave](https://github.com/brave/brave-browser/assets/2602313/2c0e911f-e199-4d2b-8dca-cf9ce955b8f6) | ![Screenshot_20240207_123454_Brave](https://github.com/brave/brave-browser/assets/2602313/891913b4-1b7b-4412-a449-919b3ddf5d5a)

</details>

#### Searches - `PASSED`

<details>

### Steps:

- searched for `stormgate builds`
  - `https://www.youtube.com/results?search_query=stormgate+builds`
- clicked on search results

### Confirmed no ads in or around the search results

**`Example`** | **`Example`**
----------------|---------------
![Screenshot_20240207_124501_Brave](https://github.com/brave/brave-browser/assets/2602313/fccc5b1e-d35e-4506-a5cf-29a7fa404633) | ![Screenshot_20240207_124520_Brave](https://github.com/brave/brave-browser/assets/2602313/eee27cdd-88f8-4758-b903-38d34fcba437)

</details>

#### Live - `PASSED`

<details>

### Steps:

- clicked on `Live` via `https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig`
- clicked on `[LIVE | AFC ASIAN CUP QATAR 2023™ | Semi Finals | Islamic Republic Of Iran vs Qatar]`
  - `https://www.youtube.com/watch?v=pUiAOS6xzs8`

### Confirmed no pre-roll ads 

**`Example`** | **`Example`**
----------------|--------------
![Screenshot_20240207_125029_Brave](https://github.com/brave/brave-browser/assets/2602313/edb6d634-8ce7-443b-8b15-b8743d34360f) | ![Screenshot_20240207_125036_Brave](https://github.com/brave/brave-browser/assets/2602313/db94bec3-68c3-4f7f-8bec-dfb1d6d41388)

</details>

#### Movies & TV - `PASSED`

<details>

### Steps:

- clicked on Movies & TV
- clicked on `Happily N'ever After 2: Snow White` - `https://www.youtube.com/watch?v=y5dxhCxANgY`
- clicked `Allow` to install `Widevine`

### Confirmed no pre-roll ads, or ads in-between seek positions

**`Note:`** screenshots appear blank due to Widevine (can't take screenshots of media being played using Widevine)

**`Example`** | **`Example`** | **`Example`**
----------------|---------------|----------------
![Screenshot_20240207_125438_Brave](https://github.com/brave/brave-browser/assets/2602313/ec94fcc4-1fc7-4c80-88b7-9fcd3c8afe40) | ![Screenshot_20240207_125450_Brave](https://github.com/brave/brave-browser/assets/2602313/42dec0ce-0a2e-450b-bd1e-52cf774caf14) | ![Screenshot_20240207_125457_Brave](https://github.com/brave/brave-browser/assets/2602313/334f54e1-886a-42d0-8bb9-9f2543174f97)

</details>

#### Toggle `Shields off` (and then back `on`, again) - `PASSED`

<details>

### Steps:
1. loaded `youtube.com`
2. disabled Shields by setting them to `Down`
3. clicked on random videos, from different locations
4. confirmed I saw various types of ads (pre-roll, interstitial, and non-video static ads on the homepage and search results)
5. re-enabled Shields by setting them to `Up`

### Confirmed no further ads seen after `Shields` were `Up`


**`Shields Disabled`**

**`Example`** | **`Example`**
----------------|--------------
![Screenshot_20240207_130105_Brave](https://github.com/brave/brave-browser/assets/2602313/fd7767b5-bc1f-4df8-89c7-71adbeac7bde) | ![Screenshot_20240207_130124_Brave](https://github.com/brave/brave-browser/assets/2602313/66459293-4d5d-430a-8e7c-2b1518472510)

**`Shields Enabled`**

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|---------------
![Screenshot_20240207_130432_Brave](https://github.com/brave/brave-browser/assets/2602313/56ae262b-80c8-499c-9c79-23766e876f27) | ![Screenshot_20240207_130439_Brave](https://github.com/brave/brave-browser/assets/2602313/6b01d898-0d2a-4443-a885-68dea642778b)  ![Screenshot_20240207_130456_Brave](https://github.com/brave/brave-browser/assets/2602313/09f40d1b-eece-4cf8-a878-03d18440ff1c)

</details>

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.62.162 Chromium: 121.0.6167.164 (Official Build) (64-bit) 
Revision	c18c9cc62d2b4376a5ada5b98b673dfc7994f20d
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

#### `YouTube.com` homepage - `PASSED`

<details>

### Steps:
1. new profile
2. load `youtube.com`
3. stay logged out
4. click around
5. return to `youtube.com`

#### Confirmed no visible ads when returning to `youtube.com` after navigating away

Example | Example
-|-
![Screenshot 2024-02-07 at 3 22 03 PM](https://github.com/brave/brave-browser/assets/17885425/49c04cf7-150a-445e-8c1a-d3b2e817daa6) | ![Screenshot 2024-02-07 at 3 22 29 PM](https://github.com/brave/brave-browser/assets/17885425/cc7f351c-afe6-4fa8-8556-0dc38c5da42f)

</details>

#### No pre-roll/skip-ad buttons (`screencast`) - `PASSED`

<details>

![Screenshot 2024-02-07 at 3 27 29 PM](https://github.com/brave/brave-browser/assets/17885425/42c25ccb-0285-43eb-859f-c8c11c01a943)

</details>

#### Direct navigations (from URL) - `PASSED`

<details>

loaded `https://www.youtube.com/watch?v=dtp6b76pMak`

### Confirmed no pre-roll ads, or ads in-between seek positions

Example | Example
-|-
![Screenshot 2024-02-07 at 3 31 54 PM](https://github.com/brave/brave-browser/assets/17885425/07da8392-e572-4590-86be-5e659e5ff016) | ![Screenshot 2024-02-07 at 3 32 14 PM](https://github.com/brave/brave-browser/assets/17885425/22a2cbc2-a047-43c2-aeec-37911cbc97e2)

</details>

#### Searches - `PASSED`

<details>

### Steps:

- searched for `news`
- clicked on search results

### Confirmed no ads in or around the search results

Example | Example
-|-
![Screenshot 2024-02-07 at 3 33 34 PM](https://github.com/brave/brave-browser/assets/17885425/fa159b13-a8d0-41a0-a719-1070f19eb3a7) | ![Screenshot 2024-02-07 at 3 33 48 PM](https://github.com/brave/brave-browser/assets/17885425/52a751a4-7d8e-4459-a8d6-77704480942a)

</details>

#### Live - `PASSED`

<details>

### Steps:

- Clicked on `Live` video

### Confirmed no pre-roll ads 

![Screenshot 2024-02-07 at 3 34 05 PM](https://github.com/brave/brave-browser/assets/17885425/1ad0dfa1-eef0-43ef-802e-7ae8fca1cf89)


</details>

#### Movies & TV - `PASSED`

<details>

### Steps:

- Searched for `movies`
- Played movie from search results

### Confirmed no pre-roll ads, or ads in-between seek positions

Example | Example
-|-
![Screenshot 2024-02-07 at 3 44 26 PM](https://github.com/brave/brave-browser/assets/17885425/5dc0fbab-7137-4d47-a23b-c861223bbf04) | ![Screenshot 2024-02-07 at 3 44 31 PM](https://github.com/brave/brave-browser/assets/17885425/4a27d55b-92b7-4672-8119-0ced852c5089)


</details>

#### Toggle `Shields off` (and then back `on`, again) - `PASSED`

<details>

### Steps:
1. loaded `youtube.com`
2. disabled Shields by setting them to `Down`
3. clicked on random videos, from different locations
4. confirmed I saw various types of ads (pre-roll, interstitial, and non-video static ads on the homepage and search results)
5. re-enabled Shields by setting them to `Up`

### Confirmed no further ads seen after `Shields` were `Up`

**`Shields Disabled`**

Example | Example
-|-
![Screenshot 2024-02-07 at 3 28 04 PM](https://github.com/brave/brave-browser/assets/17885425/517443e3-d3eb-4c2e-bb2b-4396ac30bc8b) | ![Screenshot 2024-02-07 at 3 28 01 PM](https://github.com/brave/brave-browser/assets/17885425/5abeb8cb-e251-44af-83c5-80cd7a7ec1af)

**`Shields Enabled`**

Example | Example
-|-
![Screenshot 2024-02-07 at 3 49 12 PM](https://github.com/brave/brave-browser/assets/17885425/6c8177dd-2cc4-44c9-a925-303f79726b3f) | ![Screenshot 2024-02-07 at 3 49 20 PM](https://github.com/brave/brave-browser/assets/17885425/1e46ee65-a187-4560-b779-4afd149d8e62)


</details>
