### ISSUE TITLE
Add import bookmarks and settings on bookmarks bar

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#3568]
## Description 
Add import bookmarks and settings on bookmarks bar.

## Steps to Reproduce
   1. New profile. 
   2. Notice Bookmarks bar is blank.
   3. Should show "Import bookmarks and settings" like in 59.x.

## Actual result:
Empty bookmarks will display just empty bookmarks bar.

## Expected result:
Should show text and link to import bookmark and settings like in 59.x. "For quick access..."

![48317348-c718c080-e5f0-11e8-88ba-f55b2ea16700](https://user-images.githubusercontent.com/5951041/54334825-67551500-45e4-11e9-9c5c-e800ce5136eb.png)

**Comment by rebron** [comment]
cc: @simonhong

**Comment by LaurenWags** [comment]
@rebron @simonhong using a fresh profile these are the default options in brave://settings/appearance for the bookmarks bar:
<img width="755" alt="Screen Shot 2020-06-16 at 9 04 54 AM" src="https://user-images.githubusercontent.com/28145373/84778104-7af1e700-afb0-11ea-9600-f3f7a51de86b.png">

However, on a fresh profile the bookmarks bar isn't shown on the NTP until a bookmark is added. I thought we intentionally did this as it looked odd since there was nothing displayed, but I can't find the issue.

Additionally, the bookmarks bar isn't shown on all pages until you toggle `Show Bookmarks` on - so this instructional text isn't displayed. 

Is it expected that we'd have to toggle `Show Bookmarks` to see this instructional text? Is it a bug that the bookmarks bar isn't shown on NTP when it doesn't have any bookmarks? Marking as `QA/Blocked` until we sort this.

Steps:
1. Clean profile 1.11.x.
2. I don't see instructional text on the bookmarks bar on the welcome screen (because `Show Bookmarks` is toggled off per default settings).

<img width="943" alt="Screen Shot 2020-06-16 at 9 09 41 AM" src="https://user-images.githubusercontent.com/28145373/84778535-226f1980-afb1-11ea-8e7c-c59e69d5f5e9.png">

3. Open NTP.
4. No bookmarks bar is displayed, so no instructional text.

<img width="942" alt="Screen Shot 2020-06-16 at 9 10 11 AM" src="https://user-images.githubusercontent.com/28145373/84778587-34e95300-afb1-11ea-884e-ef9a721c86fe.png">

5. Open settings, toggle `Show Bookmarks`.
6. Now instructional text is displayed.

<img width="944" alt="Screen Shot 2020-06-16 at 9 19 24 AM" src="https://user-images.githubusercontent.com/28145373/84779510-7cbcaa00-afb2-11ea-8124-33954232ebe7.png">

**Comment by LaurenWags** [comment]
Per discussion with @rebron logged https://github.com/brave/brave-browser/issues/10450 to show the bookmarks bar on the NTP even if there aren't any bookmarks so that this text can be shown (as `Always show bookmarks on New Tab page` is on by default for new users). 

However, we're not going to block on this logged follow up issue issue. Will confirm test plan and list here.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.78 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5621
* Per https://github.com/brave/brave-browser/issues/3568#issuecomment-649033176, confirmed that enabling `Show Bookmarks` setting shows the expected text:
<img width="1189" alt="Screen Shot 2020-06-26 at 11 17 08 AM" src="https://user-images.githubusercontent.com/28145373/85873358-ffa5e780-b79e-11ea-99f2-fdc22fe69199.png">

* Confirmed clicking on `Import bookmarks now...` link opens brave://settings/importData in a new tab
<img width="1196" alt="Screen Shot 2020-06-26 at 11 17 41 AM" src="https://user-images.githubusercontent.com/28145373/85873432-1d734c80-b79f-11ea-910a-f00b178e87c5.png">

* Confirmed importing data removes the text from bookmarks bar:
<img width="1189" alt="Screen Shot 2020-06-26 at 11 20 51 AM" src="https://user-images.githubusercontent.com/28145373/85873446-206e3d00-b79f-11ea-89b2-9d1849674f6f.png">

* Confirmed removing all bookmarks once again shows the text
