### ISSUE TITLE
fullscreen button in PIP window doesn't work from some sites.

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#35721]
Fullscreen button on PIP doesn't work from following sites:

Twitch, Bitchute, Vimeo, Rumble, and etc.

Reported from https://github.com/brave/brave-core/pull/21763#issuecomment-1917442441 by @TEMP-ad

**Comment by TEMP-ad** [comment]
@sangwoo108 Amazing work!

I have a question though, Is the Full screen button in PiP only allowed to open the 'raw' media's as full screen? instead of doing what the player does when hitting the F key?

What I mean is if you go to Youtube it will fullscreen the video with no controls or anything, same as Bitchute, then for example, Rumble and Twitch will have the basic controls, like if you opened a normal MP4 without JS in the browser.

Looking at the PIP's Timestamp and twitch timestamps makes sense to go to this version of the player instead of the JS Fullscreen.

Now, the problem is that if you fullscreen with the PiP and then hit F button to exit fullscreen, then it will/might show the real player in Full screen but without video, so it is black screen, if you hit F then it will go back to the fullscreen video and so on. Plus hitting exit, will not even go back to the PiP but attrach the video to its normal JS player.

This is something that doesn't happen in Youtube though, if you press F after being fullscreen nothing gets fullscreen, because it is using like the F11 mode, so you need to press F11 to exit it like if Browser was in fullscreen.

Anyway, just reporting the experience if something can be improved. But it is working great 👍awesome work as usual, thanks for the fix.

**Comment by sangwoo108** [comment]
Hi @TEMP-ad ! Thanks for the compliment. Unfortunately, I can't think of a way to enter fullscreen with the controls at this moment. To my knowledge, a video element for PIP is the only the browser knows. That means it's pretty hard to tell what element is proper parent of the video element containing the controls. As for the "F key" behavior, let me check if it can be improved.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.64.48 Chromium: 121.0.6167.139 (Official Build) nightly (x86_64)
-- | --
Revision | 741f7ee622bdfde5e10e3beda02288f3c056287e
OS | macOS Version 11.7.10 (Build 20G1427)
```

Twitch
Bitchute
Vimeo
Rumble
