### ISSUE TITLE
How to find stable Brave release for offline installation on Windows?

### ISSUE THREAD

**Issue by GitHubinatrix** [brave/brave-browser#35760]
I managed to find this https://github.com/brave/brave-browser/releases and am able to manually search [going back in time through all those releases] for a `This is NOT the release (stable) channel version of Brave`

But how do I find a `Release` build that is mentioned among other types in this article https://support.brave.com/hc/en-us/articles/360017916752-What-is-the-difference-between-Nightly-Dev-Beta-and-Release-builds - how do I download an x64 Windows 10 full version of Brave in form of offline installer?

**Comment by rebron** [comment]
Hi @GitHubinatrix If you keep scrolling you'll find the official `Release` builds marked like this: [Release v1.62.156 (Chromium 121.0.6167.139) ](https://github.com/brave/brave-browser/releases/tag/v1.62.156)[Latest](https://github.com/brave/brave-browser/releases/latest) with the latest label. 

You'll then want [BraveBrowserStandaloneSetup.exe](https://github.com/brave/brave-browser/releases/download/v1.62.156/BraveBrowserStandaloneSetup.exe). 

This one is for enterprise deployment [BraveBrowserStandaloneSilentSetup.exe](https://github.com/brave/brave-browser/releases/download/v1.62.156/BraveBrowserStandaloneSilentSetup.exe)

**Comment by docomputing** [comment]
so complicated...

**Comment by pv7721** [comment]
@docomputing: totally agree!

**Comment by bsclifton** [comment]
cc: @mihaiplesa 

Definitely could be handy to have a direct link to a full version. We don't have anything like this at the moment

We do have a website with our active versions:
https://versions.brave.com/

And from there, you can find the download URLs in the `Brave Versions (json)` https://versions.brave.com/latest/brave-versions.json. It wouldn't be too hard to automate scraping this JSON response and pulling out the binaries (and the SHA for verifying binary)

**Comment by mihaiplesa** [comment]
Feel free to use https://github.com/brave/brave-browser/releases/latest directly and pick the file corresponding to your OS, architecture and desired installation type.

**Comment by pv7721** [comment]
> cc: [@mihaiplesa](https://github.com/mihaiplesa)
> 
> Definitely could be handy to have a direct link to a full version. We don't have anything like this at the moment
> 
> We do have a website with our active versions: https://versions.brave.com/
> 
> And from there, you can find the download URLs in the `Brave Versions (json)` https://versions.brave.com/latest/brave-versions.json. It wouldn't be too hard to automate scraping this JSON response and pulling out the binaries (and the SHA for verifying binary)

Thank you very much and also Mihai, I think I was looking more for the 1st link, especially because it's written:

"Internal releases are published only to GitHub and are meant primarily for testing.
Public releases are published to GitHub and all repositories/stores (including Omaha for automated updates on Windows/macOS)."

If you may allow a suggestion, I was about to ask what Omaha is (but as I've managed to find it, maybe link the word to the respective repository: https://github.com/brave/omaha (as I installed Brave on Windows I noted it had the most pristine look and feel at install time (like Chrome).

I don't think I'll have such a big need to scrape the JSON version information file, I'll simply keep a look on this page https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule and try to follow the release schedule.
