### ISSUE TITLE
Hover effect on Bookmarks bar is barely visible

### ISSUE THREAD

**Issue by Skyyie** [brave/brave-browser#35832]
After the new update, if we hover the cursor over bookmarks, there is barely any hover effect. I mean, it is barely visible. It is a bit visible in light themes but it is barely there with dark mode.

You can see an example here when I have my cursor over a bookmark folder (i.e., Dashboards):

![img](https://github.com/brave/brave-browser/assets/141417720/9d76ae68-c554-49b2-a163-2bf5072b2ed8)

I am on stable channel and it is the same since v1.62.153 (I am currently in v1.62.156).

Thread on Brave Community: https://community.brave.com/t/hover-effect-on-bookmarks-bar-is-barely-visible-on-latest-update/528225

**Comment by simonhong** [comment]
checking

**Comment by sangwoo108** [comment]
Yeah, looks like the inkdrop layer is painted over the bookmark button's label. I guess the difference between chromium and ours would be the base color, which is white in Chromium, and ours is black?

Easy solution would be make bookmark buttons' label have transparent layer so that the layer can be painted atop the ink drop layer

```
BookmarkMenuButtonBase::BookmarkMenuButtonBase(PressedCallback callback,
                                               const std::u16string& title)
    : MenuButton(std::move(callback), title) {
...
  label()->SetPaintToLayer();
  label()->SetSubpixelRenderingEnabled(false);
  label()->layer()->SetFillsBoundsOpaquely(false);
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```
