### ISSUE TITLE
Use same labels on Shields global settings and panel

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3589]
## Current
![image 1](https://user-images.githubusercontent.com/639937/53845447-f8314e00-3f5d-11e9-83c4-8ba02fc3f932.png)

## Designs
Settings:
![shields settings](https://user-images.githubusercontent.com/2388823/56166255-01b0cb80-5f8a-11e9-83af-112d17dd3f99.png)

Shields panel:
![shields panel](https://user-images.githubusercontent.com/2388823/55983238-82508e80-5c4f-11e9-98f3-65310a83c6e3.png)

**Comment by tomlowenthal** [comment]
cc: @karenkliu

**Comment by tomlowenthal** [comment]
Text should be as follows:

In Shields Panel
```
- Cross-site trackers blocked [toggle]
- Connections upgraded to HTTPS [toggle]
- Scripts blocked [toggle]
- [ Cookies blocked / Cross-site cookies blocked / All cookies allowed ]
- [ Device recognition attempts blocked / Cross-site device recognition blocked / All device recognition attempts allowed ]

Change Shields global defaults [outlink]
```

In Settings
```
# Shields global defaults

- Block cross-site trackers [toggle]
- Upgrade connections to HTTPS [toggle]
- Block scripts [toggle]
- Cookies [ Block all cookies / Only block cross-site cookies / Allow all cookies ]
- Device recognition [ Block all device recognition attempts / Only block cross-site device recognition attempts / Allow all device recognition attempts ]
```

**Comment by karenkliu** [comment]
Added designs to the issue.

**Comment by petemill** [comment]
@tomlowenthal please can we keep the section title for Shields and use a sub-section title for 'Global Defaults' as per https://github.com/brave/brave-core/pull/1909? So that we can have `Shields` as a top-level menu item and then can have other sub-sections if we need them (social media blocking?).

In your latest wording, it seems to keep the section title as `Shields global defaults`

In @karenkliu 's mockup (in the Description of this issue) it seems to keep that title but omits the description stating that these are defaults and can be overriden per-site.

This is what I had and intend to merge, before the actual settings items get adjusted:
![image](https://user-images.githubusercontent.com/741836/55987111-a616d300-5c55-11e9-962b-78024639f4e1.png)

**Comment by karenkliu** [comment]
How's this:
![settings](https://user-images.githubusercontent.com/2388823/55991631-900e1000-5c5f-11e9-8ac6-4c83fa92c122.png)

**Comment by karenkliu** [comment]
Reviewed this with @tomlowenthal; we decided to go with a modified version of option B for the social media stuff. I will attach specs to #4109 . 

For this issue, here is the design with Tom's feedback:
![shields settings](https://user-images.githubusercontent.com/2388823/56166082-90711880-5f89-11e9-8c65-d1863376ec38.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.104 Chromium: 75.0.3770.100 (Official Build) dev (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the description mentioned in the issue
 -  Shield settings:
![image](https://user-images.githubusercontent.com/38657976/61527256-a0d9d900-aa39-11e9-8d09-c4bf42341c29.png)
- Global shield settings:
![image](https://user-images.githubusercontent.com/38657976/61527301-ba7b2080-aa39-11e9-8efb-0c6929e05b7d.png)
- Logged https://github.com/brave/brave-browser/issues/5293
