### ISSUE TITLE
Adapt tor daemon controller logic from browser-laptop to brave-core

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#359]
https://github.com/brave/browser-laptop/blob/8468fbb9fa0b7b3d7de8a4a377d4797c16c63758/app/tor.js (or on [master](https://github.com/brave/browser-laptop/blob/master/app/tor.js))

Should be mostly a straightforward translation from nodejs state machines to C++ Chromium state machines.

**Comment by btlechowski** [comment]
`QA/Blocked` due to doubts about one of the TCs

Verification passed on

Brave | 1.16.50 Chromium: 86.0.4240.55 (Official Build) dev (x86_64)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4802

Verified `OS-chosen port for tor`
Opened Tor Window the first time
![image](https://user-images.githubusercontent.com/34715963/95049582-539f6100-06ea-11eb-9362-3d73b28c196c.png)

Opened Tor Window the second time
![image](https://user-images.githubusercontent.com/34715963/95049650-76ca1080-06ea-11eb-80b7-89502ab0cdd6.png)

Verified `Tor initialization progress indicator`
Waiting for Tor component initialization.
![image](https://user-images.githubusercontent.com/34715963/95049803-c6a8d780-06ea-11eb-80c8-67ab1c143be8.png)
Page is opened after Tor component initialization
![image](https://user-images.githubusercontent.com/34715963/95049890-ed670e00-06ea-11eb-82ba-bb947482a772.png)

Verified `Tor process crash handling`
Killed Tor process
![image](https://user-images.githubusercontent.com/34715963/95050094-48006a00-06eb-11eb-95f9-30e389b26e34.png)
Verified Tor process was relaunched after 1s
Verified client is connected to Tor network
![image](https://user-images.githubusercontent.com/34715963/95050258-87c75180-06eb-11eb-8561-fc6c26c1ee7d.png)

Verified `Tor launcher crash handling`
Killed  Tor launcher
![image](https://user-images.githubusercontent.com/34715963/95050647-3b304600-06ec-11eb-8ea7-041fa8e2ff99.png)
Was not able to open the page after killing Tor Launcher
Verified Tor launcher was relaunched after closing and reopening Private Window with Tor.
Verified PID of Tor launcher changed
![image](https://user-images.githubusercontent.com/34715963/95051977-6c117a80-06ee-11eb-82ba-46e2c4ca1b29.png)
Verified client was connected to the Tor network

**Comment by LaurenWags** [comment]
Per discussion with @darkdh removing `release-notes/include` and adding `release-notes/exclude`. Related issue #649 will be included in the release notes instead.
