### ISSUE TITLE
[Perf] CPU regression caused by adblock unified catalog

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#35922]
We have a slight CPU usage spike on some platforms (mac-m1, win11) in the revision range https://github.com/brave/brave-core/compare/v1.64.35...v1.64.36
![image](https://github.com/brave/brave-browser/assets/45488748/25df4fe4-ce9b-41b6-a8d2-2c57d16127ca)

I believe it’s the adblock changes: https://github.com/brave/brave-core/pull/21556
I’ve checked adblock work in the traces before/after, the structure is changed and the new number are bigger:
```
Before 890ms
After: 1085ms 
```
![image](https://github.com/brave/brave-browser/assets/45488748/b961e86a-9b3e-41d8-abe2-676858b52eb9)

**Comment by antonok-edm** [comment]
As far as I'm aware, we have the following options for resolving this:

1. preload cached resources at launch followed by lazier list updates later
2. bundle lists (or a DAT) with browser builds
3. batch list updates together so they don't trigger update races

However:
- (3) will make things worse without (2), because any slow-loading lists would prevent shields from working for a long time at startup.
- (2) will not improve the measurements much without (1), because the list updates will still occur at startup.
- (1) by itself does not affect first launch, which is what the perf measurements above are for.

**Comment by ShivanKaul** [comment]
@atuchin-m is the spike in CPU usage on some platforms only on first launch?

**Comment by atuchin-m** [comment]
From the slack thread:
With 2 default extra lists (easy list cookies + mobile notifications) there is noticeable difference.
before (393ms)/after(287+306=593ms) [win-10, local Static build on 1.64.55 with/without reverted [PR](https://github.com/brave/brave-core/pull/21556)]
![image](https://github.com/brave/brave-browser/assets/45488748/0accf6a3-65c6-43ea-bb2d-94da9434b290)
![image](https://github.com/brave/brave-browser/assets/45488748/ced0ce57-d572-4900-8eaf-7abc2940c33a)

**Comment by atuchin-m** [comment]
Hm, I’ve enabled 10 extra lists.
556ms vs 2900ms :scream:
>5x slower..
I’ve double checked this, but I still hope I’m doing something wrong with my measurement.
One of the different I see is that we start to call from_filter_set more often (checked in the debugger 6 vs 10+ times) and with large set(the first arg).
@antonok-edm could you add some counters and check how many rules we process before/after the change?
![image](https://github.com/brave/brave-browser/assets/45488748/419caa24-0147-4774-b38b-229bbcec7151)
![image](https://github.com/brave/brave-browser/assets/45488748/fa3e1643-a3e4-4809-96e0-b1f98703510e)
![image](https://github.com/brave/brave-browser/assets/45488748/f884dd55-26d5-42cc-869d-4162aaa1db6b)
![image](https://github.com/brave/brave-browser/assets/45488748/8706fa2d-ede7-4411-992e-7dc2377d0544)

**Comment by kjozwiak** [comment]
The above requires `1.64.104` or higher for `1.64.x` verification 👍 @brave/qa-team please take a look at https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1710309453936669?thread_ts=1709255617.117759&cid=CHGKGMHDJ re: the plan for this one. Quick summary:

* @kjozwiak will run through https://github.com/brave/brave-core/pull/22082#issuecomment-1993571338 once again on `Win` & `Android` but this time using a YT link/video rather than a website.
* On `macOS` & `Linux`, lets just quickly spot check and make sure that ads are being blocked right after a new install
  * using various websites: install `Brave` and then quickly paste/load a website within the URL and ensure ads are being blocked

Created https://github.com/brave/brave-browser/issues/36749 which is also happening via `1.63.x`

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave	1.64.104 Chromium: 123.0.6312.46 (Official Build) (x86_64) 
Revision	0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS	macOS Version 11.7.10 (Build 20G1427)
```

<img width="1312" alt="Screen Shot 2024-03-14 at 10 58 50 AM" src="https://github.com/brave/brave-browser/assets/387249/0dbac41a-c677-4e69-b665-a7abde1de922">

**Comment by kjozwiak** [comment]
**`Quick Note:`** For each of the cases mentioned below, the following was done in terms of STR/Cases:

* ensured that `https://www.youtube.com/watch?v=OJ56MAGFPGM` was already copied/ready to paste into URL bar
* ensured that all profiles have been removed (basically ensuring you're launching using a clean profile)
* launched Brave and then quickly pasted `https://www.youtube.com/watch?v=OJ56MAGFPGM` (as quickly as possible)

If an issue was found/ads initially being displayed, compared against `1.63.169 Chromium: 122.0.6261.111` and ensured that it wasn't any worse with the above PR. Basically ensuring it was also happening via the current `release` build.

## `Pixel 6` running `Android 14` verifications throttling network

Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.65.79 Chromium: 123.0.6312.29 (Official Build) canary (64-bit)
--- | ---
Revision | 9c6d737e50d926561b759189043cf63065fe5cc6
OS | Android 14; Build/AP21.240119.009; 34; REL
```

Some quick notes/caveats:

* I originally tried throttling the network to `128kbps`, `256kbps` & `1Mbps` but it was impossible to load any website/content
* Because you need to run through several onboarding screens, the `Android` test is not as instant as the `Desktop`
  * the components/lists most likely downloaded/applied by the time you went through the onboarding screens

#### `Test Case #1` - No network throttling (base user case) - **`No ads appearing on initial launch`**

Video of verification(s) --> https://youtu.be/xjJusg90i-I

#### `Test Case #2` - Throttling network at `5MBps` - **`No ads appearing on initial launch`**

Using the `Network download rate limit` feature via the `Developer Option`, I throttled the phones network to `5Mbps` and then went through the same STR/Cases mentioned above re: loading a website right after the application has launched.

Video of verification(s) --> https://youtu.be/vRnLyxVrp6Q

#### `Test Case #3` - Throttling network at `1MBps` - **`No ads appearing on initial launch`**

Using the `Network download rate limit` feature via the `Developer Option`, I throttled the phones network to `1Mbps` and then went through the same STR/Cases mentioned above re: loading a website right after the application has launched. Even though the website barely loaded, the YT video started without any ads.

Video of verification(s) --> https://youtu.be/-15kWVtJhfQ

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave	1.64.104 Chromium: 123.0.6312.46 (Official Build) (64-bit) 
Revision	0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS	Linux
```
Encountered https://github.com/brave/brave-browser/issues/36749

Verified on following sites as a basic with loading a website right after Brave launches
Conformed No ads appearing on initial launch

Youtube:
