### ISSUE TITLE
Errors in `TimePeriodStorage::GetPeriodSumInTimeRange` result due to DST changes

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#35941]
Sums calculated by `TimePeriodStorage` will be under-counted or over-counted, if the `TimePeriodStorage` was initialized before a DST change. If the storage was initialized during daylight saving time (i.e. PDT in North America, from March to November), the sums would exclude the first day of the period, resulting in an under-count. The opposite occurs if the storage was initialized during standard time; an extra day will be included resulting in an over-count.

Any metrics that use `TimePeriodStorage` will be affected.

We noticed a drop in "7 day" results for the `Brave.Core.WeeklyUsage` metric ("How many days did you use the browser in the previous ISO week?") after the switch back to standard time in November.

cc @timchilds

**Comment by GeetaSarvadnya** [comment]
@DJAndries Could you add the test plan, please. Thanks!

**Comment by DJAndries** [comment]
@GeetaSarvadnya added, thanks

**Comment by GeetaSarvadnya** [comment]
@DJAndries I have followed the test plan from https://github.com/brave/brave-core/pull/21993. I have set the following the Time zones and verified the test plan, I am getting the results as below. 

On 4th, 5th, 6th, th and 8th Oct 2023 I am getting the metrics `Brave.Core.WeeklyUsage` response value as `0`. On 9th, 10th and 11th Oct 2023 I am getting the metrics `Brave.Core.WeeklyUsage` response value as `5` instead of `7` I am not sure it's expected or not, could you review this and let me know your thoughts? Thanks!

Time zones:
Pacific Time (US & Canada)
Mountain Time (US & Canada)
Cental Time (US & Canada)

**Comment by DJAndries** [comment]
@GeetaSarvadnya apologies, i made a mistake with the dates. please repeat the test using Oct 2 - 9, 2023

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.65.96`
