### ISSUE TITLE
Missing 'source' for empty evals in PageGraph 

### ISSUE THREAD

**Issue by FHantke** [brave/brave-browser#35970]
Hi, currently, the pagegraph misses the source attribute for eval calls that evaluate an empty string. I'm not sure if this is a little bug in pagegraph or in chromiums implementation.

Example page:
```html
<html>
   <body>
      <script nonce="foo" type="text/javascript" charset="utf-8">
         eval(""); 
         eval("1+1");
      </script>
   </body>
</html>
```

What I see in the pagegraph:

The first eval is created as a script node but misses the source key.
 ```json
{
  "node type": "script",
  "id": "262",
  "timestamp": "80",
  "script id": 14,
  "script type": "eval"
}
 ```
The second eval is created as a script node and contains the source.
```json
{
  "node type": "script",
  "id": "264",
  "timestamp": "80",
  "script id": 15,
  "script type": "eval",
  "source": "1+1"
}
 ```

**Comment by FHantke** [comment]
@pes10k It seems that I can't add the `page-graph` label myself.

**Comment by pes10k** [comment]
ah, i added the label myself. I'll take a look at this further too

**Comment by FHantke** [comment]
Yes, that's correct. My script threw an exception because it expected for every eval to have a source.

**Comment by pes10k** [comment]
i expect the issue is here in xmllib2

[if (value != NULL) {](https://github.com/ConradIrwin/libxml2/blob/b368604d9ba04fec68dbc93733e1c2737766747e/tree.c#L6750)

and so the empty string being interpreted as `NULL` (since its C++).

I'm not sure what a better option would be here, since otherwise we'd need some bottom value in pagegraph to indicate an empty string execution (which would have its own complications). I think maybe as is would be the best option. Second best, we could post-process the generated graph.  But i think probably leaving as is might be best

**Comment by FHantke** [comment]
Good point, the graphml file contains the key (d35 = source):

```xml
<node id="n302">
  <data key="d19">script</data>
  <data key="d21">302</data>
  <data key="d23">98</data>
  <data key="d31">16</data>
  <data key="d33">eval</data>
  <data key="d35"/>
  <data key="d39"/>
</node>

<node id="n304">
  <data key="d19">script</data>
  <data key="d21">304</data>
  <data key="d23">98</data>
  <data key="d31">17</data>
  <data key="d33">eval</data>
  <data key="d35">1+1</data>
  <data key="d39"/>
</node>
```

I agree, it's probably the best as is and I handle the error in my code.

**Comment by pes10k** [comment]
oh phew, that clarifies things, i was going a little crazy!

**Comment by pes10k** [comment]
might be an interesting thing to file with the networkx folks though
