### ISSUE TITLE
Inconsistent button sizes on Edit NFT and Add custom tokens screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36196]
## Description 

Inconsistent button sizes on Edit NFT and Add custom tokens screen

## Steps to Reproduce

NA

## Actual result:

![brave_gj1sHRkGqV](https://github.com/brave/brave-browser/assets/17010094/91ee8756-9280-4d41-91fb-a4b65f5e80b5) | ![brave_msGmOjnZQH](https://github.com/brave/brave-browser/assets/17010094/810e0b9b-33de-4d67-b321-edba5a98502c) | ![brave_h6ysaJZjel](https://github.com/brave/brave-browser/assets/17010094/73678bab-9511-40de-afd6-a13c11bfb40b) | ![brave_B77ng4nqwY](https://github.com/brave/brave-browser/assets/17010094/ed3cf8d1-beac-43d6-8f87-cf2a38f7cb72)
-- | -- | -- | --

## Expected result:
Buttons should be of same size?

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @kleantzogu @josheleonard @muliswilliam

**Comment by kleantzogu** [comment]
Based on latest updates on design system the button height of the Default (Medium) size button should be 44px. I think it needs to be updated on storybook too since we moved to rounded style buttons instead of pill shape we had before.

Here is the link of that screen: https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=2397-153294&mode=design&t=ilTfhKjJmidr44Gr-4
<img width="1559" alt="image" src="https://github.com/brave/brave-browser/assets/2451237/a9278279-6864-4263-896b-f55e40dbe67c">

**Comment by josheleonard** [comment]
Closing, as this is no longer valid since the add/edit NFT modal has been redesigned
