### ISSUE TITLE
Update Page Settings Button Style

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#36267]
## Description 

We need to update the `Page Settings` button style to be squared to match the new designs in figma

## Expected result:

![Screenshot 27](https://github.com/brave/brave-browser/assets/40611140/54ab177d-39a4-443e-b792-6f2cbb3b439e)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22216](https://github.com/brave/brave-core/pull/22216)
- Verified menu button is now square instead of round

https://github.com/brave/brave-browser/assets/17010094/b6ea7670-c313-4cac-aa31-0bfb85a09dff
