### ISSUE TITLE
IPNS names have dots converted to dashes.

### ISSUE THREAD

**Issue by MicahZoltu** [brave/brave-browser#36368]
May be related to #13303

## Description 
When accessing an `ipns://` URL, Brave converts it into a subname that uses dashes instead of dots, even though this isn't necessary.

## Steps to Reproduce
   1. Navigate to [ipns://2.horswap.eth](ipns://2.horswap.eth)
   2. Open browser console and type `window.location.href`
   3. Notice that the result is `http://2-horswap-eth.ipns.localhost:48084/` rather than `ipns://2.horswap.eth` (reported in #13303) but it is also not `http://2.horswap.eth.ipns.localhost:48084/` (this bug report).

## Actual result:
`http://2-horswap-eth.ipns.localhost:48084/`

## Expected result:
`http://2.horswap.eth.ipns.localhost:48084/`

## Brave version (brave://version info)
1.63.162 Chromium: 122.0.6261.69 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 👍 
- Can you reproduce this issue with the beta channel? 🤷 
- Can you reproduce this issue with the nightly channel? 🤷 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? No.

## Miscellaneous Information:
Of note: If you navigate to http://2.horswap.eth.ipns.localhost:48084/ directly, your address bar will update to display `ipns://2.horswap.eth`, but `window.location.href` will now *correctly* show http://2.horswap.eth.ipns.localhost:48084/ (without the dashes).  You can also see in the 

Looking at the network log, it appears the problem is that `ipns://2.horswap.eth` is resulting in a request to `http://localhost:48084/ipns/2.horswap.eth/`, rather than a request to `http://2.horswap.eth.ipns.localhost:48084/`, and the backing IPFS gateway then redirects to the dashed URL.  I believe the more correct thing to do here is to go directly to the subdomain origin, rather than starting with path routing and then letting the gateway redirect you to the subdomain.

**Comment by diracdeltas** [comment]
I think this is following the subdomain inlining behavior described in https://specs.ipfs.tech/http-gateways/subdomain-gateway/.

**Comment by MicahZoltu** [comment]
> I think this is following the subdomain inlining behavior described in https://specs.ipfs.tech/http-gateways/subdomain-gateway/.

I believe the rules defined in 2.1.1 are specifically for converting between IPNS-in-path to IPNS-in-subdomain.  IIUC, this is necessary because we cannot be sure that the IPNS name in the path is actually valid as a hostname.  However, in this case we are *starting* with an IPNS hostname, so there is no worry about it being an invalid hostname, thus we don't need to convert.

We can gain confidence in this by the fact that the official IPFS gateway will *not* redirect subdomains with dots to subdomains with dashes.

**Comment by cypt4** [comment]
Single-label form allows us to separate storages between different sites loaded on local node.
Since ipns.localhost is eTLD a.ipns.locahost and b.ipns.localhost don't intersect.
But x.a.ipns.locahost and y.a.ipns.locahost may intersect since site would be a.ipns.localhost.
Related changes were done [here](https://github.com/brave/brave-core/pull/7046) for example.
For this issue we should redirect http://2.horswap.eth.ipns.localhost:48084/ to http://2-horswap-eth.ipns.localhost:48084/ actually.

**Comment by lidel** [comment]
### Current behavior: `ipns://` origins do not depend on each other

My understanding is that inlining of  DNSLink names on `localhost`  is intended behavior introduced in [brave-browser#22927: Unify IPFS DNSLink behaviors for local and public gateway](https://github.com/brave/brave-browser/issues/22927).

Brave sets [Gateway.PublicGateways: InlineDNSLink](https://github.com/ipfs/kubo/blob/master/docs/config.md#gatewaypublicgateways-inlinednslink) to `true` to simplify internal security model and have `window.location.origin` constructed with the same convention on both  `localhost` and public subdomain gateways like `dweb.link`.

Inlining of DNSLink names removes dependency of `*.ipns` Origins on DNS and public suffix list.
Origin space is no longer hierarchical, it is flattened. Each content root, no matter if it is cryptographic [IPNS Record](https://specs.ipfs.tech/ipns/ipns-record/#ipns-name), or [DNSLink](https://dnslink.dev/), is in its own unique origin without any parent/sibling relationship.  

### Next step: native `ipns://` in `window.location.origin` and specs

I agree that if Brave wants to change something, it should work towards `window.location.origin` using native  `ipfs://` and `ipns://` (https://github.com/brave/brave-browser/issues/13303). 

Why? Once we are on `ipns://`, we are no longer beholden to implementing hierarchical Origins from `https://` and can decide how Origins should work. There are two paths forward, but if you've read between lines, we are already on **(B)**:
- **(A)** Still follow hierarchical Origin convention from `https://` + DNS and implement "[public suffix](https://publicsuffix.org/)" for ICANN TLDs + special ones like .eth, 
- **(B)** Or simplify things, and build Origin based on **protocol + URL authority as an opaque string** (`ipns://[opaque authority/sub-path`), which is effectively how things have been working in brave since  [InlineDNSLink:true](https://github.com/ipfs/kubo/blob/master/docs/config.md#gatewaypublicgateways-inlinednslink) was set anyway.

A specification for Origins on `ipns://` is yet to be written, but my personal opinion is that "opaque authority" **(B)** serves the decentralized ecosystem better, as it does not require implementers such as Brave to worry about the  nature of identifiers being CID or DNS, and hardcoding public suffix lists, etc to handle DNS "correctly".  Opaque authority makes Origin isolation is stronger, and implementation becomes less complex.

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
