### ISSUE TITLE
[iOS] Proceed on an iOS blocked page leads to a 404 page

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#36378]
## Steps to Reproduce 
  1. Launch the app wait to ensure all adblocking is loaded and downloaded
  2. Load the link [here](https://trk.klclick1.com/ls/click?upn=teN-2BS77Ps95NK7KObeXgrimA3t7j1Laf88ZtXwBr8M6zawHVIzdkKWtFA4WBx9-2BZ1U2IS38vmduS4B6oEomGUpK2ExwBIayFbbcenGJhmAjsp-2FXF9onbpsHq6oMYjfYT4crhBzlvFskL-2BiNpTy9MzkaywmZPqqkwE-2FzXkyw5d98bT6L-2FYfilvjZp-2B4HsSE1ncrzsE8Qth-2BflJIE1FKfFzNbQhYPeq9p0rgMVtapz7ebeRULBb-2B0PhQ3TqHz1VKCiXJulWZo3jXneyIylc1d4GXTqxnsVJlk7fFEmWGHugh5xI5PD-2FYtg1yXTySU0uzmxKFvQ_xuCGEktjWwJeE-2F8H5tQMjrufhk-2F7uVwe0rQEEX6nMLnzCMF2NxYSb5ZY8hld2U93mLmKh1h765wqMOc2TKiqQC19rO5FOVRA1l4u9d-2FfhU81j1MVDins7BltHU-2Bo5dXKkFEkGCa6mfSACYRdBMgw0t-2BDo1nLeG4sEJI4hNVEForX3WHezV-2Bdux8K5-2BYD5JleMcxCX6EK9Vtd4jTq7gaDRcqPnBBK5QBSf6xx4QkIYsl7rvkrcvvhAO-2F57tmsTHS7TWZA-2BEQjJp12rY5bh8kdMFmiimL3YFTHGgpi5yuuekHQzcIItEGw2bCbFcyP7kghbURZjAmyTpxBdVoUpg9uXafu3V1RzvdurbvFfU0IdRah5Qn3SpRgMPZHSx4EML7YiDtAG-2BWD-2FOYWB19-2F7kkuDDyChhWtigAIOFy0a2Quz71oNK6ga5tDpBIgXi20dy1pFSE4dA5BBcyTACGO4WLYRQ-3D-3D)
  3. On the blocked content page, click on "Proceed"
 
Should load amazon page

## Actual result: 
Shows a page not found page

## Expected result:
Should show an amazon page

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

## Brave Version: 
1.6.3

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
Any

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.4.1
- iPad Air / iPadOS 16.7.2
Brave build: 1.65 (96)
BraveCore: 1.65.96 (123.0.6312.86)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36378#issue-2155099415
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the issue is not reproducible and no `404` is shown

---------------------------

*iPad*

https://github.com/brave/brave-browser/assets/128532965/e4c7ca7c-2cc1-4524-a4c3-7444d1287641

*iPhone*

https://github.com/brave/brave-browser/assets/128532965/72440321-6daf-4e8d-8284-362a04398d81
