### ISSUE TITLE
Theme backgrounds not correctly displayed on tabstrip

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#36392]
## Description 

In some themes, the background of the tabstrip in horizontal mode is not painted correctly. For some themes, the background is only incorrect when the browser does not have focus.

## Steps to Reproduce

- Install one of the following themes:
  - https://chromewebstore.google.com/detail/wood-theme/echckcnbemgkhfgnoegigpojocnibjcb?hl=en
  - https://chromewebstore.google.com/detail/dark-theme-v3/djlgdeklopcjagknhlchbdjekgpgenad
  - https://chromewebstore.google.com/detail/elementary-freya-dark/lcmjgikfofdpfddimlpihnncnpdmlppl

## Actual result:

<img width="1220" alt="Screenshot 2024-02-27 at 10 34 35 AM" src="https://github.com/brave/brave-browser/assets/5995084/623ceff1-0aeb-4003-8892-40739ed37888">
<img width="1220" alt="Screenshot 2024-02-27 at 10 34 51 AM" src="https://github.com/brave/brave-browser/assets/5995084/44e14017-97cc-47a0-b51c-022b9dd06305">

## Expected result:
<img width="1220" alt="Screenshot 2024-02-27 at 10 23 36 AM" src="https://github.com/brave/brave-browser/assets/5995084/9e07f69a-b163-4ce0-b6c7-52bddbfe55d0">
<img width="1220" alt="Screenshot 2024-02-27 at 10 24 12 AM" src="https://github.com/brave/brave-browser/assets/5995084/e22b3caf-ed4b-4ae8-8b80-7bdb0f0960e0">

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

1.63.161 Chromium: 122.0.6261.57 (Official Build) (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.63.167` or higher for `1.63.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.63.168 Chromium: 122.0.6261.94 (Official Build) (x86_64)
-- | --
Revision | 08196d502fa95681adc6dd9fc06a04d0664ac538
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by Dean-Corso** [comment]
Hey guys,

depending on the set custom themes by users it brings again the big question up when you dev guys finally allow (again) to use our chosen theme in all three browser running states (Normal - Private - Tor)? I don't know how often I should ask about it and it really makes me upset because there are many user out there who want to get that feature back to use one custom theme for all. Just have a look below...
![Theme_2024-03-07_220000](https://github.com/brave/brave-browser/assets/88513086/c8d845ec-f0ce-4021-8ed5-bd46c6b07c04)
...and my custom theme I did choose in this example image is the first one on top and in Private & Tor state I get your ugly colored themes presented I don't wanna have there. So whats the point with those "MUST USE THEMES"? Is it so damn important for you guys to press your color rubber stamp on us? Or do you think it's some kind of COOL? Its not of course and its just damn stupid to force us to live with those ugly colored MUST USE themes! Just let us users decide what themes we wanna use like in earlier days where it was possible and stop forcing us. I thought after long time of complaining about that you guys would became more adult but somehow I was wrong and you are still same like before, right. 😞
