### ISSUE TITLE
[iOS] HTTPS by default feature on iOS

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#36408]
### Description: 
Currently we 2 ways of doing HTTP upgrades:
1. in iOS 14 we use a content blocklist for upgrading known hosts
2. in iOS 15 we use the built in https upgrade webkit provides us. This uses a list maintained by apple which we cannot control (or see).

Instead of using a whitelist of upgradable hosts, we want to do the opposite: Use a list of hosts that should not be upgraded. Everything else is upgraded. List of hosts that are not upgraded (same as brave-core): https://github.com/brave/adblock-lists/blob/master/brave-lists/https-upgrade-exceptions-list.txt

If an error is encountered during this upgrade, we then undo the upgrade. In essence it's a learning process.

This means that we will likely need to drop the built in https upgrade webkit provides us and spin up our own. 

More info here:
https://brave.com/privacy-updates/22-https-by-default/#how-braves-https-by-default-feature-works
https://research.mozilla.org/files/2021/03/https_only_upgrading_all_connections_to_https_in_web_browsers.pdf

FEATURE:

1. Have a global 3-way toggle in Brave Shields & Privacy: Off, Standard, Strict. Default is Standard.
2. Strict mode gives a warning interstitial before loading an HTTP website if the upgrade fails.
3. Interstitial has the following buttons: "Continue to site", "Go back" and "Continue and don't ask again" (which sets the default to be Standard instead of Strict). 
4. Turning Shields down for a site is equivalent to turning 'Upgrade Connections to HTTPS" off for that site.

### Test interstitial
1. Restart the application
2. Go to https://wikipedia.org (for our back button)
3. Enable strict mode
4. Go to http://http.badssl.com
5. Ensure there is an interstitial
6. Click "Go back" 
7. Should take you back to wikipedia
8. Press forward button
9. Ensure there is an interstitial
10. Click "Proceed"
11. http (not secure) page loads
12. Note: hitting back button at this point will take you to the interstitial (nothing that can be done about this)

### Test upgrading
1. Restart the application
2. Go to https://wikipedia.org (for our back button)
3. Go to http://example.com
4. Ensure you are taken to https://example.com
5. Press back
6. Ensure you are taken to the wikipedia page
7. Press forward button
8. Ensure you are taken to https://example.com

**Comment by bridiver** [comment]
I think what we actually want here is to just duplicate the Chrome functionality of always trying to upgrade to https on ios and showing an interstitial if we can't. @ShivanKaul ?

**Comment by ShivanKaul** [comment]
We should match brave-core here, at least for the global option. Let's lay off adding the per-site Shields toggle for now and see if folks have comments on https://github.com/brave/brave-browser/issues/36907.

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.6
- iPad Air / iPadOS 16.7.2
Brave build: 1.68 (101)
BraveCore: 1.68.101 (126.0.6478.126)
```
---------------------------
<details>
<summary> Test interstitial </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/36408#issue-2157693231
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Upgrade Connections to HTPPS` now has three options instead of a toggle switch: Strict, Standard, and Disabled
- Verified that the `interstitial` page is shown when navigating to http://http.badssl.com if `Upgrade Connections to HTPPS` is set to `Strict`

---------------------------

`iPhone`

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ff4cd888-6cad-4df9-bf2a-04a122c20b18) | ![2](https://github.com/brave/brave-browser/assets/128532965/0c889b2d-3cd1-4cdf-9c85-f555f364b7d0) | ![3](https://github.com/brave/brave-browser/assets/128532965/58c81fc2-586f-4fcd-b846-8b49a1068b60) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/f8d6a83d-021d-4bc0-bfa8-0197fe572294) | ![2](https://github.com/brave/brave-browser/assets/128532965/492ba4b5-83a7-47ac-9e42-50c31bdafdbb) | ![3](https://github.com/brave/brave-browser/assets/128532965/1ec7b43e-265c-430e-a0a0-e684a148d486) |

`iPad`

https://github.com/brave/brave-browser/assets/128532965/cbdf23f4-aade-41fc-b18b-b519c5e5722d
</details>

<details>
<summary> Test upgrading </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/36408#issue-2157693231
2. *Verify*

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
