### ISSUE TITLE
[Follow up to #36323] `Brave.AIChat.UsageDaily.2` metric exists after Brave closed and relaunched

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#36439]
## Description 

Follow-up to #36323

## Steps to reproduce 

   1. Install and launch Brave (Fresh profile)
   2. Go through onboarding
   3. Open `Leo` > Start chat and send only `one` prompt
   4. Go to `brave://local-state`
   5. Search for `Brave.AIChat.UsageDaily.2` > *Confirm it set to `1`*
   6. Ensure usage daily metric `Brave.AIChat.UsageDaily.2` is `sent`
   7. Close Brave > Advance system time by `one day`
   8. Launch Brave > Go to `brave://local-state`
   9. Search for `Brave.AIChat.UsageDaily.2` > *Observe that it's still shown*

## Actual result 

The `Brave.AIChat.UsageDaily.2` metric exists after Brave closed and relaunched.

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/38f65d07-4886-49e1-b2a5-fbdce242a864) | ![2](https://github.com/brave/brave-browser/assets/128532965/a5040457-ae0d-47d8-948d-68bcae93034f) | ![3](https://github.com/brave/brave-browser/assets/128532965/94046f2f-d868-4c0d-b284-81ade572061e) | ![4](https://github.com/brave/brave-browser/assets/128532965/797de7ee-e03b-4c2b-8404-324e965fda25) |

https://github.com/brave/brave-browser/assets/128532965/aec214dd-6a10-4aef-b1e3-aee00b70db70

## Expected result

The usage daily metric `Brave.AIChat.UsageDaily.2` must be `gone`.

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? YES
- Can you reproduce this issue with the current Play Store Beta version? YES
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): PHONE
   - Android version: ANY
   
## Brave version

```
Brave build: 1.63.164
Chromium: 122.0.6261.69 (Official Build) (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by mattmcalister** [comment]
cc @GeetaSarvadnya

**Comment by hffvld** [comment]
@DJAndries The same issue was observed for other metrics like `Brave.AIChat.ChatCount` and `Brave.AIChat.AvgPromptCount` which are not set to `0` after the system date changed to `7 days` from now.

--------------------

![2024-02-28_10-03-41](https://github.com/brave/brave-browser/assets/128532965/39b4bdb8-3e3d-4588-b3ac-5e13e8f6f3b5)

https://github.com/brave/brave-browser/assets/128532965/2f35f835-2bbd-4ce0-a69b-8274aee220dd

**Comment by mattmcalister** [comment]
is this true for Desktop as well or exclusive to Android? if so, did it exist with the previous version of the question too?

**Comment by GeetaSarvadnya** [comment]
@hffvld Verified the issue on Desktop `1.63.165`. It works as expected. On day 1 when I use Leo and send one prompt I get response value as `1` for the `Brave.AIChat.UsageDaily.2` metrics, on day 2 I don't see `Brave.AIChat.UsageDaily.2` metrics as I have not used or send Leo prompts on day 2.

When the leo prompt is made on the 1st day, the metrics `Brave.AIChat.UsageDaily.2` displayed under two buckets `logs_express` and  `logs_constellation_prep_express`. Initialy the flag is `sent:false` in both the places after sometime the flag turns `sent:true` in both the places

brave://local-state looks as below after 1st AIchat prompt on day 1:
The flag response is `sent:false`

`logs_express` | `logs_constellation_prep_express`
----------------|-----------------------------------------
![image](https://github.com/brave/brave-browser/assets/38657976/9eb71c92-21fb-42ca-a8f6-13105b7afb71) | ![image](https://github.com/brave/brave-browser/assets/38657976/60651359-5c51-4b04-ad25-a10474f22783)

After few minutes the flag turns `sent:true`

`logs_express` | `logs_constellation_prep_express`
----------------|-----------------------------------------
![image](https://github.com/brave/brave-browser/assets/38657976/c71e8a12-b6a8-486a-93d1-8c520d0a86b1) | ![image](https://github.com/brave/brave-browser/assets/38657976/75bad9e3-437d-48e4-a766-de1815ee01d8)

Once you advance the sys date by one day, relaunch browser and reload brave://local-state looks as below:

In the screenshot below, you can see that the metrics `Brave.AIChat.UsageDaily.2` is NOT displayed under the `logs_express` cadence which is because we have not done AI prompts on the next day (day 2), But you can see the metrics `Brave.AIChat.UsageDaily.2` listed under `logs_constellation_prep_express` which is because, before sending the metrics to the server all the metrics are prepared hence the  `Brave.AIChat.UsageDaily.2` is shown under this bucket which is correct as per the implemention https://github.com/brave/brave-browser/issues/33217

![image](https://github.com/brave/brave-browser/assets/38657976/490512da-4c4a-469f-8a40-2890a97c2b18)

I think you got confused because the metrics listed under `logs_constellation_prep_express` block on day 2. This is not the place we will be looking at the metrics value on the day 2, we will have to check the `logs_express` to check the metrics `Brave.AIChat.UsageDaily.2` response value display on day 2. 

Also, I have verified Android `1.63.165` it behaves same like Desktop.

cc: @DJAndries @mattmcalister

**Comment by mattmcalister** [comment]
thank you @GeetaSarvadnya

**Comment by hffvld** [comment]
@GeetaSarvadnya what about `Brave.AIChat.ChatCount` and `Brave.AIChat.AvgPromptCount` does it work for you as well?

**Comment by DJAndries** [comment]
@hffvld As @GeetaSarvadnya mentioned, we'll only want to examine the entries under the `logs` and `logs_express` prefs. These prefs are associated with the JSON P3A reporter, which we are in the process of deprecating.

The `logs_constellation_prep` and `logs_constellation_prep_express` are associated with the STAR/Constellation P3A reporter, which is a bit harder to test with since the STAR randomness server dictates when logs the rotated (or in this case, removed) rather than the system date/time. I will have to create better test harnesses for the new uploader prefs, especially as we come close to removing the JSON P3A reporter completely.

You'll notice that the `logs` pref is not available on the local state page. This is because we have deprecated JSON for typical/weekly data; monthly and daily data is not yet deprecated. I recommend that you add the following to your command line while testing: `--disable-features="BraveP3ATypicalJSONDeprecation"`. This will re-enable the JSON reporter for weekly data, which will allow you to examine the `logs` pref.

**Comment by hffvld** [comment]
Based on the comments from above, this is WAI. Thanks for clarifying @GeetaSarvadnya and @DJAndries
