### ISSUE TITLE
Excluded sites can't be viewed without having them restored

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3657]
## Description 

Excluded sites can't be viewed without having them restored 

## Steps to Reproduce

   1. Enable rewards
   2. Visit a few sites (3-4)
   3. Exclude them from a-c
   4. Feel like Bruce Willis from Sixth Sense that you think you know but you don't actually know 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/54127981-6607ca80-43e1-11e9-8ea5-85148b2ca0f2.png)

## Expected result:
There should be a way to see excluded sites without having to restore them 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by mandar-brave** [comment]
@NejcZdovc @RyanJarv to make it easy on the design, can we just have another symbol color that shows?
(excluded icon) site/contributor with a different color.

This will ensure there is no extra table and the sites that were excluded show up as part of the attention. 

Alternative option:
We have an easter egg that replaces existing attention table with table of exclusions.

My worry is the privacy focused segments may not want to have anyone be able to see what was excluded. 

cc @jenn-rhim @tomlowenthal

**Comment by tomlowenthal** [comment]
I think that an extra table is probably the right design: interact with the text at the bottom about excluded items and the table turns into the excluded items, with interactive elements to restore them one at a time, or all. But I defer to design.

**Comment by mandar-brave** [comment]
@tomlowenthal you comfy showing excluded items? please double confirm

**Comment by tomlowenthal** [comment]
No problem showing excluded items behind a click/button. Showing excluded items without a click is dicier.

**Comment by jenn-rhim** [comment]
Here is the design recommendations. 
The only new items other than the excluded site list itself is the date stamp of when the user excluded each site and the ability to restore the individual site rather than restoring the entire exclusion list. For the excluded sites prior to this change for which we don't have the date stamp, we'll indicate it with '--'.

![1-ac-list](https://user-images.githubusercontent.com/4369856/55438026-58afad00-5555-11e9-9fde-8e8334a2eca1.png)


![2-excluded](https://user-images.githubusercontent.com/4369856/55438034-5d746100-5555-11e9-94ba-05b87f6ff871.png)

**Comment by ryanml** [comment]
@jenn-rhim this looks slick! Thanks for providing.

One nit, on the Excluded Sites view, for the restore action, was the trash can icon intentional? Maybe something like this from our icon library:

<img width="109" alt="Screen Shot 2019-04-03 at 1 32 55 PM" src="https://user-images.githubusercontent.com/8732757/55511305-1fd70d00-5615-11e9-9087-7968f5f28e78.png">

**Comment by ryanml** [comment]
Though I do understand if the X icon was more meant to denote: `Remove the item from this list`

**Comment by jenn-rhim** [comment]
@ryanml  I believe that **contextually** it is appropriate to use 'x' as a notion of 'Remove' from this list. The context is _"here is the list of sites you excluded. Would you like to remove any of the sites from this exclusion list?_" I've purposefully displayed the tooltip on hover to make this clear to the user.

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/is-there-an-auto-contribute-excluded-site-list/63770/2

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2199
* Also verified that excluding a site from panel adds site to the excluded list. Toggling site to include in the panel removes from excluded list.
