### ISSUE TITLE
Leo - AI Title - Icon + Text stacking

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#36870]
## Description: 
The intro text for each AI model should be stacked with the icon, instead of them being side by side.

## Steps to Reproduce 
  1. Open Leo on iOS 
  2. See first intro card

## Actual result: 
![image](https://github.com/brave/brave-browser/assets/15734630/5c753ced-2d47-48d7-b212-42bca0a523ad)

## Expected result:
Design
https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=6511%3A108804&mode=design&t=rDHbigSNNb6UsjCo-1

![image](https://github.com/brave/brave-browser/assets/15734630/b14c175c-c772-4253-93f7-c483cae9aff8)

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by kjozwiak** [comment]
The above requires `1.65.128` or higher for `1.65.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.5
- iPad Air / iPadOS 16.7.2
Brave build: 1.66 (107)
BraveCore: 1.66.107 (125.0.6422.41)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open `Leo` > *Verfiy*

**ACTUAL RESULTS:**
- Verified that the intro text for any AI model is stacked with the icon, instead of being side by side
- Verified the same in `Portrait` & `Landscape` modes and `Dark` & `Light` themes

---------------------------

<details>
<summary> iPhone 14 </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/de9ddb4c-3aa8-4c22-93cf-3ecf9024eeac) | ![2](https://github.com/brave/brave-browser/assets/128532965/1ec4c996-36ad-4bdf-b905-0dc0ed64f7ce) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/4a419a7b-a6e4-4e59-9b28-f3ad2f991fec) | ![2](https://github.com/brave/brave-browser/assets/128532965/dc064acd-ad43-4f0a-8fdd-7359088b1195) |

</details>

<details>
<summary> iPad Air </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
