### ISSUE TITLE
Self-custody invite displays on top of TOS update notice in Rewards panel - follow up to 35977

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#37024]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35977

If a user has a self-custody invite at the same time as a TOS update notice, the self custody invite is shown first (on top) on the panel. The TOS update notice should be shown first/on top.

The NTP widget behaves correctly - TOS update is shown first/on top of the widget.

## Steps to Reproduce

1. With a new profile, enable Rewards. Whitelist paymentId so that on relaunch you will get invite for self custody.
2. Close the browser.
3. Use Charles Proxy to simulate incrementing the "tosVersion" field of the Rewards parameters endpoint.
4. Restart the browser, confirm Charles Proxy rewrite is being used.
5. ToS update notice should be displayed on the NTP, the Rewards page, and panel. On the widget and panel you shouldn't see the self custody invite --> this fails, self-custody invite is shown above TOS update notice on the panel (widget displays as expected):

NTP | brave://rewards | Panel
--- | --- | ---
<img width="315" alt="Screenshot 2024-03-22 at 3 26 12 PM" src="https://github.com/brave/brave-browser/assets/28145373/9835c8e0-2612-432e-a8be-14ee31a8dcfb"> | <img width="1187" alt="Screenshot 2024-03-22 at 3 26 28 PM" src="https://github.com/brave/brave-browser/assets/28145373/e52fd71d-d644-44f2-8329-f79ec58a7903"> | <img width="1186" alt="Screenshot 2024-03-22 at 3 26 48 PM" src="https://github.com/brave/brave-browser/assets/28145373/02def39c-c68f-47a4-918f-b674f6fc48a8">

Once the above is fixed, QA should verify that when the ToS update notice is accepted, it is no longer displayed and you can now see the self custody invite on the panel and widget.

## Actual result:

see screenshots above

## Expected result:

TOS update should have the highest z-index order

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave	1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS	macOS Version 13.6.4 (Build 22G513)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.65.95`. Logged a separate issue for Android https://github.com/brave/brave-browser/issues/37211

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.66.56 Chromium: 123.0.6312.86 (Official Build) nightly (x86_64) 
Revision	029ff6b82a6cfb16bde7c6d7ab560321a023cb8b
OS	macOS Version 13.6.6 (Build 22G630)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.66.94 Chromium: 124.0.6367.91 (Official Build) beta (64-bit)
-- | --
Revision | 1574096f9d2bcb69c3654cb4437217121ee9600b
OS | Windows 10 Version 22H2 (Build 19045.4291)

```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.66.110 Chromium: 125.0.6422.60 (Official Build) (64-bit)
-- | --
Revision | de593d76e2ca4d02faa85bf1ca27bcf3ee46793c
OS | Linux


1. With a new profile, enable Rewards. Whitelist paymentId so that on relaunch you will get invite for self custody.
2. Close the browser.
3. Use Charles Proxy to simulate incrementing the "tosVersion" field of the Rewards parameters endpoint.
4. Restart the browser, confirm Charles Proxy rewrite is being used.
5. ToS update notice should be displayed on the NTP, the Rewards page, and panel. 
6. Confirm that the ToS update covers the entire panel and cannot be dismissed (only accepted or Rewards can be reset).

NTP Widget | brave://rewards | Panel
--- | --- | ---
![image](https://github.com/brave/brave-browser/assets/34715963/c1bf8536-9dc9-4ef3-bf52-09dede5de84d)|![image](https://github.com/brave/brave-browser/assets/34715963/bb4115ba-ebcf-481c-afd0-ed519403537f)|![image](https://github.com/brave/brave-browser/assets/34715963/d03a30cc-d44a-4957-8104-671d114917a4)


7. Confirm if the ToS update notice is accepted, it is no longer displayed and you can now see the self custody invite on the panel and widget.

![image](https://github.com/brave/brave-browser/assets/34715963/2efbc983-dd97-4fc3-ae3a-d6b77c8db1b0)|![image](https://github.com/brave/brave-browser/assets/34715963/636a3493-7879-4df5-963a-cc3385dbe93c)|![image](https://github.com/brave/brave-browser/assets/34715963/ad691208-78bc-4b72-8e89-cd967e7d240e)
--|--|--
