### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by DjodyKort** [brave/brave-browser#37209]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.66.43 Chromium: 123.0.6312.86
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. When I try logging in to Microsoft.
2. When I going to the brave settings and checking for updates.
3. When get redirected to certain websites

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/0ef00600-686b-ba0b-0000-000000000000

**Comment by TEMP-ad** [comment]
> When I try logging in to Microsoft.

That sounds like what happened to me. After some testing I made an issue because I found out it was simply the #brave-ads-should-always-run-brave-ads-service flag being Enabled by Brave variations, so I disabled it and no more crashes when trying to log in to a Microsoft service.

You might want to try to go to brave://flags and disable it and test it.

**Comment by rebron** [comment]
Closing as duplicate. Should be fixed with https://github.com/brave/brave-core/pull/22842
@DjodyKort If you update to the latest the fix should be in there. 1.66.46 and higher
