### ISSUE TITLE
Break tiles when moved tabs are between tiles

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#37328]
When dragging a tab and drop it between two tabs in a tile, it doesn't break the tile. This makes things awkward. We should break the tile.

**Comment by bridiver** [comment]
break what tile? Is this a Brave issue or also a Chrome issue?

**Comment by sangwoo108** [comment]
Ours, it's sub task of https://github.com/brave/brave-browser/issues/36986 which is linked.

**Comment by bridiver** [comment]
> Ours, it's sub task of https://github.com/brave/brave-browser/issues/36986 which is linked.

I think it would be more helpful to include context in this ticket rather than working backwards to a spec. Some screenshots perhaps?

**Comment by TEMP-ad** [comment]
@sangwoo108 This is not working anymore in VT or HT. You can drop individual tabs and split view tabs inside other split view tabs which can get really weird and also like mess the order of tabs in reference with their split view if you move things around too much.

Yesterday I even broke it to a point where it was glitching and like having a seizure, the tabs were like going up and down and reordering non-stop over and over again, it was a funny glitch I caused by seeing how much I could stack and break things.
