### ISSUE TITLE
[Shortcuts]: MacOS shortcuts has a crash on startup

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#37323]
There are some Stacktraces I saw that look related to this:

https://brave.sp.backtrace.io/p/brave/debug?time=all&filters=JTVCJTVCJTIyY2FsbHN0YWNrJTIyJTJDJTIyY29udGFpbnMlMjIlMkMlMjJBY2NlbGVyYXRvclNlcnZpY2UlMjIlNUQlNUQ%3D&fingerprint=14906c668e9d274e21510464b1fde63ba99f099400a2db2678bc739f95f61624&debug=(%227047c19%22,0,13)

There seem to be a lot of MacOS related crashes here (and none on other platforms):
https://brave.sp.backtrace.io/p/brave/explore?time=(1970-01-01T12%3A00%3A01%2B12%3A00%2C2024-04-04T14%3A16%3A42%2B13%3A00)&filters=JTVCJTVCJTIydW5hbWUuc3lzbmFtZSUyMiUyQyUyMmVxdWFsJTIyJTJDJTIyTWFjJTIwT1MlMjBYJTIyJTVEJTJDJTVCJTIyX2RlbGV0ZWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjAlMjIlNUQlMkMlNUIlMjJjYWxsc3RhY2slMjIlMkMlMjJjb250YWlucyUyMiUyQyUyMkFjY2VsZXJhdG9yU2VydmljZSUyMiU1RCU1RA%3D%3D&aggregations=((callstack%2Chead))&

I'm struggling to debug this as I don't have a Mac - I was wondering if it'd be useful to record the keyboard shortcut in the crash keys so we can see what characters/modifiers are triggering this:
https://chromium.googlesource.com/chromium/src/+/master/docs/debugging_with_crash_keys.md

cc @sangwoo108 @simonhong 

**Note:** I'm not sure how to reproduce this, but if I had to guess it'd be some funky character in the keyboard shortcut text.

Looks like the likely culprit is something inside `MacKeyCodeForWindowsKeyCode` and `AccumulateAcceleratorsRecursively`

**Comment by sangwoo108** [comment]
When I press the "Debug" tab, thie line seems to be the problem. I suspect keyEquivalent is empty string.

```
  // The ui::KeybaordCode only contains the uppercase characters, we should
  // capitalize them.
  // https://source.chromium.org/chromium/chromium/src/+/main:ui/events/keycodes/keyboard_codes_win.h;l=63;drc=3e1a26c44c024d97dc9a4c09bbc6a2365398ca2c
  const unsigned short charCode =
      [[keyEquivalent uppercaseString] characterAtIndex:0];
```

**Comment by sangwoo108** [comment]
Or could it be a char that exceed BMP so charAt:0 caused crash?

**Comment by bsclifton** [comment]
I'll close this issue as fixed by https://github.com/brave/brave-core/pull/22928

[Looking at backtrace](https://brave.sp.backtrace.io/p/brave/explore?time=(1969-12-31T17%3A00%3A01-07%3A00%2C2024-04-03T18%3A16%3A42-07%3A00)&filters=JTVCJTVCJTIydW5hbWUuc3lzbmFtZSUyMiUyQyUyMmVxdWFsJTIyJTJDJTIyTWFjJTIwT1MlMjBYJTIyJTVEJTJDJTVCJTIyY2FsbHN0YWNrJTIyJTJDJTIyY29udGFpbnMlMjIlMkMlMjJBY2NlbGVyYXRvclNlcnZpY2UlMjIlNUQlNUQ%3D&aggregations=((callstack%2Chead))&), I don't see any crashes since ~March. There may be newer duplicates that were deleted, but definitely nothing recent.
