### ISSUE TITLE
Tab group names are not shown in vertical tabs, replaced with New tab button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#37352]
## Description 

Tab group names are not shown in vertical tabs, replaced with New tab button

## Steps to Reproduce

   1. Install 1.66.59 
   2. Create Tab groups 
   3. Switch to vertical tabs 
   4. Tab group name is replaced with `+` button
   5. Clicking adds a new tab in the group
   6. Only way to collapse/expand group is to click outside the `+` click area
   7. Right click on the tab group and enable `Save group` shows the icon 
   8. Disabling it causes new tab button to show up 

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/aa6c0111-9b3d-40ae-84ee-9f3c0d9e3d29)

## Expected result:
Show tab group name and no `+` button should be shown in Tab group

## Reproduces how often: 

Easy

## Brave version (brave://version info)

 
Brave | 1.66.59 Chromium: 123.0.6312.105 (Official Build) nightly (64-bit)
-- | --
Revision | 2714c7ac837e7b7693b1b56a82effdf57e04fe09
OS | Windows 11 Version 23H2 (Build 22631.3374)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @zenparsing

**Comment by stephendonner** [comment]
cc @aguscruiz @rebron

**Comment by LaurenWags** [comment]
cc @sangwoo108 - maybe related to https://github.com/brave/brave-browser/issues/28058

**Comment by sangwoo108** [comment]
@thirumurugan-git I'm curious if you're still interested in this feature. We've noticed a side effect of your previous work.

**Comment by TEMP-ad** [comment]
As a normal users I will give my feedback:

This shouldn't be seen as a side effect, the button was added to create tabs quickly within a group, if it were to be removed from minimized mode, what is the point of having a useful button? Minimized mode is useful for saving space, yes, but having to expand the vertical tab strip to get some things done, like muting tabs, already makes this mode complicated to use, which is the reason why I think Edge never added it, and always set the tabs to be either hover mode with a small width or expanded, but never a true minimized mode.

Now, I think the problem here is people who think this is 'bad behavior' and think "Tab group names are not shown" apparently don't remember Vertical Tab grouping before this change.

These is what happened before this change:
![image](https://github.com/brave/brave-browser/assets/156715894/d181321a-e7fb-422e-8e44-37687a1006dd) ![image](https://github.com/brave/brave-browser/assets/156715894/134cde94-fc27-4d3a-84f4-87a35c00ee3d)

Look at it and tell yourself, how are **2** characters or **1 and a half** (if first is capitalized) be useful for anything? You could barely know what each group was unless you had obvious groups, but the more groups, the minimized VT would become more problematic, because the information was pretty much almost useless before, there was no group names, there was literally only 2 characters and done.

The obvious problem with minimized mode is that there is no space for much, but there should be a way to fix all the issues with it, because it is clear that Horizontal names, don't work in Vertical tab strip, and less in minimized mode. For example, Horizontal tabs groups will have 17 characters until it doesn't add more width to the Group Name, which seems fine, but in VT minimized mode, what would be the solution?

Minimized mode by design is already problematic, like the fact that it only shows favicons, that means if you got 10 github tabs opened, you will only get 10 github fav icons, and then if you are playing audio, you will get audio icons, but you can't use them unless you expand VT.

Right now, the 4px line indicating tabs are in a group is pretty much all you got to find your tabs but after that not much. I know there is https://github.com/brave/brave-browser/issues/35203 this issue, but all it will add is the background to the 'name' like horizontal tabs, but the issue reminds: the more groups, the less great minimized mode is, and by the screenshots of the issue the problem will become worst, because now it only displays **B** instead of **Br** for a group named Brave.

Minimized mode is about saving space yes, but how is having an add button removed(?) in favor of, what I will say it is useless information, like the group name, be better if the name barely was visible before?

I don't even  think this could be fixed somehow. If you don't display the button in minimized mode then minimized mode will lose a great feature, if you place the button on the bottom of each group, it will be wierd to see, if you place it at the top between the name and the first tab, wierd, if you make the button smaller, then people will barely see it and understand what it is for, if you make the group name smaller then it will be hard for people to see it and we will get the complainers "I can barely see it, why the change", and so on.

There are only 40px in Minimzed mode to work with, that's what makes this complicated. Either, group name of 2 characters or 1 and a half or a new tab button.

Of course, If https://github.com/brave/brave-browser/issues/35203 was resolved, I am sure having just the button would not be seen as 'problematic' as it is now, because you would have a better indication of the groups by the colors, when a group starts and ends.
But seeing how minimized mode is far from user friendly, like only favicons and all that or audio icon, and you don't get to close the tabs unless you switch to that tab, I don't see how having only the new tab button is the biggest problem here.

Just my opinion as a Brave user, so you might understand how Tab Grouping was bad before, and removing the button is removing at least something useful from minimized mode.

**Comment by rebron** [comment]
<img width="117" alt="Screenshot 2024-04-05 at 12 28 18 PM" src="https://github.com/brave/brave-browser/assets/5951041/967822d5-7262-455c-87a9-a5f7c820b777">
Characters for the group names will help identify the group. The blank name for groups, we should fix but we can fix than separately.
<img width="261" alt="Screenshot 2024-04-05 at 12 30 11 PM" src="https://github.com/brave/brave-browser/assets/5951041/af4172f2-dee1-4623-98c5-d1a734321fb0">

I also think we should hide the "+" icon until the a Group is expanded. It's not clear that the "+" icon is for opening a new tab within a group. Users could be confused for the "+" icon to mean expand.
cc: @aguscruiz

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave	1.66.80 Chromium: 124.0.6367.29 (Official Build) beta (x86_64) 
Revision	2d822a1940c9159c1f307cd1c0a8f58fcfb50fe0
OS	macOS Version 11.7.10 (Build 20G1427)
```

### Without `tab group` names

<img width="1624" alt="Screen Shot 2024-04-16 at 6 13 58 PM" src="https://github.com/brave/brave-browser/assets/387249/f0cefa26-c296-49c2-bcb6-03135722cac1">

### With `tab group` names


<img width="1624" alt="Screen Shot 2024-04-16 at 6 14 05 PM" src="https://github.com/brave/brave-browser/assets/387249/b5397989-11ec-47d4-ac99-ba44f661cf81">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.83 Chromium: 124.0.6367.60 (Official Build) beta (64-bit)
-- | --
Revision | 05e51102638aec2f59c93a45527d6840c17cb704
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

1. installed 1.66.83
2. launched Brave
3. loaded a bunch of retail, news, cars, social media, streaming & petroleum company sites in new tabs
4. added each of the above site types to their respective tab groups (eg. news, cars etc.,)
5. context-clicked on a tab
6. chose Use Vertical Tabs


### Confirmed the tab-group names are shown in the `expanded` view (both dynamic and fixed), without the `+` buttons

#### With `tab group` names

<details>

 Expanded | Collapsed 
 ---- | ----- 
![image](https://github.com/brave/brave-browser/assets/98358127/345b50d0-2e7c-43d2-8d4e-1e9f87e4d72e)|![image](https://github.com/brave/brave-browser/assets/98358127/186e419c-5eb3-458d-8dff-ff6c820edb08)

</details>

#### Without `tab group` names
<details>

 Expanded | Collapsed 
 ---- | ----- 
![image](https://github.com/brave/brave-browser/assets/98358127/5cd8174b-75e7-4952-b3d3-391bff923e58)|![image](https://github.com/brave/brave-browser/assets/98358127/2b22a4fd-df08-4a98-acd1-87df22ab8133)
</details>

#### Horizonal tab view 

##### Confirmed the tab-group names are shown in the `expanded` view (both dynamic and fixed) as expected

<details>
![image](https://github.com/brave/brave-browser/assets/98358127/af5fbf1c-d1d1-4c97-9035-86bff9a20bc0)
</details>

**Comment by MadhaviSeelam** [comment]
Verification `in progress` using
```
Brave	1.66.90 Chromium: 124.0.6367.82 (Official Build) beta (64-bit) 
Revision	803a4c629341791205b744969c48b8da9f2cfa4d
OS	Linux
```


1. installed 1.66.83
2. launched Brave
3. loaded a bunch of retail, news, cars, social media, streaming & petroleum company sites in new tabs
4. added each of the above site types to their respective tab groups (eg. news, cars etc.,)
5. context-clicked on a tab
6. chose Use Vertical Tabs


#### Confirmed the tab-group names are shown in the `expanded` view (both dynamic and fixed), without the `+` buttons
Vertical tab view
<details>

#### With `tab group` names

 Expanded | Collapsed 
 ---- | ----- 


</details>

#### Without `tab group` names
<details>

 Expanded | Collapsed 
 ---- | ----- 

</details>

#### Horizonal tab view 
<details>

##### Confirmed the tab-group names are shown as expected


</details>
