### ISSUE TITLE
Crash report seems not uploaded even reporting option is enabled

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#37350]
There are many reports from brave://crashes on my Nightly (Win11)
Some are recently generated and old ones that generated 2w ago. Reporting is enabled.

But only one report is uploaded. It's uploaded by my manual `Send now` button clicking
I think that all reports should be uploaded in background if reporting option is enabled.
![image](https://github.com/brave/brave-browser/assets/6786187/4b53955d-e2dc-42b6-9711-b46ff33fea36)
![Screenshot 2024-04-05 102932](https://github.com/brave/brave-browser/assets/6786187/cf2b0b5b-77b1-414c-a91a-56cb2a66d6cd)

**Comment by kjozwiak** [comment]
@bsclifton QA also runs through https://github.com/brave/qa-resources/blob/master/WikiTemplate/Desktop/wikitemplate.md#crash-reporting whenever we run through a full manual pass which happens when we're pushing out major CR bumps. Let me know if there's anything that we can add to improve crash reporting checks.
