### ISSUE TITLE
De-AMP shouldn't apply for non-HTML pages

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#37406]
We shouldn't attempt to De-AMP pages that are not HTML. This was reported internally.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.67.52 Chromium: 124.0.6367.91 (Official Build) nightly (x86_64)
-- | --
Revision | a368a1ab342f0a5d4dee4db3f2699f7d02579247
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.67.52`
2. launched Brave
3. loaded `https://shivankaul.com/brave/de-amp/test-content-type-text.txt`
4. confirmed `Auto-redirect AMP pages` in `brave://settings/privacy`

## Confirmed page rendered as-is, rather than redirecting to `brave.com`

example | example
---------|---------
<img width="1312" alt="Screen Shot 2024-04-30 at 3 01 35 PM" src="https://github.com/brave/brave-browser/assets/387249/75e4de07-16eb-4077-baef-8dc385d7810f"> | <img width="1312" alt="Screen Shot 2024-04-30 at 3 04 37 PM" src="https://github.com/brave/brave-browser/assets/387249/52acdc28-6f4c-42c7-b3a4-4e02ac73b479">

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.023.B4 release-keys
Brave build: 1.67.100
Chromium: 125.0.6422.112 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave
2. Go to https://shivankaul.com/brave/de-amp/test-content-type-text.txt
3. *Verify*

**ACTUAL RESULTS:**
- Verified that the raw text is shown when navigating to https://shivankaul.com/brave/de-amp/test-content-type-text.txt and not redirected to `www.brave.com`

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/dfd35738-01d7-4ad4-b0e3-fec4f16bf9ee) | ![2](https://github.com/brave/brave-browser/assets/128532965/c6f57443-6230-4573-ab40-1c6890f6703a) | ![3](https://github.com/brave/brave-browser/assets/128532965/400a7cdf-8505-4443-b6b4-e759d6674a0e) |
