### ISSUE TITLE
Retries for unverified Publishers 

### ISSUE THREAD

**Issue by hollons** [brave/brave-browser#3741]
## Description 

**Current spec**

- keep each a/c and tips separate; convert all a/c values to tips once creator-XX is verified
- when a new publisher is verified, notify once that a publisher is verified "We will send your contributions to newly verified creator-XX" - action OK and close
- Try sending every tip based on time sequence, FIFO
- if tips fail, keep them in pending log at the browser till successful
- if tips fail due to lack of funds, notify first time ONLY when users retry that "You have pending tips due to insufficient funds" - action " Add funds" and drives to add-funds and close
- (Re) try every day

Each of the notifications ONLY the first time; one time for every verified publisher and one time only for failed retries due to lack of funds.

**Obsolete spec**
Part-2 of the unverified spec
https://docs.google.com/document/d/1y9eTyvvRkRXIDnRuCJ7SDzhK53kUnjsmuK9ZsGxnDiM/edit?usp=sharing

**Comment by mandar-brave** [comment]
prioritizing the issue for immediate nightly builds 
@NejcZdovc @davidtemkin @evq @jenn-rhim @alexwykoff 

Issue:
Currently all unverified Publisher contributions are stuck on the browser edge. However, if any of those publishers sign up, the retries for such held contributions is not retried. 

What needs to happen: Tips
Once every day, for new verified publishers, the system should automatically try paying contributions, pending wallet balance.
When unverified Publisher payments happen, a notification for contributions that are now successful needs to be presented to the user with -- "Creator" which was previous unverified is now verified and your payment for XX BAT was sent successfully.

What needs to happen: A-C
Follow the specification and add verified publishers to the current attention table.

**Comment by NejcZdovc** [comment]
@mandar-brave some adjustments:

> Against an unverified publisher, create one large TIP summing up all pending transactions
We will not merge them together as in almost all cases user will not have enough funds.


I wrote the whole thing how this could work, but at the end I got a lot of edge cases. I think we need to process every transaction separately so that things are simple. The only thing that I don't know what to do with is a notification

**Comment by mandar-brave** [comment]
Updated spec;

- keep each a/c and tips separate; convert all a/c values to tips once creator-XX is verified
- when a new publisher is verified, notify once that a publisher is verified "We will send your contributions to newly verified creator-XX" - action OK and close
- Try sending every tip based on time sequence, FIFO
- if tips fail, keep them in pending log at the browser till successful
- if tips fail due to lack of funds, notify first time ONLY when users retry that "You have pending tips due to insufficient funds" - action " Add funds" and drives to add-funds and close
- (Re) try every day 

Each of the notifications ONLY the first time; one time for every verified publisher and one time only for failed retries due to lack of funds.

cc @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.67.108 Chromium: 75.0.3770.100 (Official Build) beta (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2512 (Tested on staging env)
