### ISSUE TITLE
Exclude crypto address only sites/channels from Auto-Contribute

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#37464]
## Description

If a site/channel only has crypto addresses (Ethereum and/or Solana address) but NO custodial account address, it should NOT be added to the Auto-Contribute list.

**Comment by LaurenWags** [comment]
Added `QA/Blocked` per discussion via https://bravesoftware.slack.com/archives/CB0KCRCQN/p1716208636885399

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` as we now have the needed set up per https://bravesoftware.slack.com/archives/CB0KCRCQN/p1716301177255669?thread_ts=1716208636.885399&cid=CB0KCRCQN.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.67.90 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | 64f9eec1a854079c3e529e908ca300071afb1f32
OS | Windows 10 Version 22H2 (Build 19045.4412)

```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Samsung galaxy version 12` running `Bravemonaoarm64.apk_1.67.90`

- Verified the test plan from https://github.com/brave/brave-core/pull/23052
- Confirmed that the web3-only verified publisher `shredshark.ca` is not added to the AC table
- Confirmed that Uphold and Gemini publishers are added to the AC list (not able to add bitFlyer publisher alexvincentmusic.com as the pubs doesn't load due to redirect issue)
- Confirmed that `Attention` and  `Include in Auto-contribute` switch is not present in the BR panel for the web3-only verified publisher `shredshark.ca`
- Confirmed that AC is performed for the publishers that are added in AC table

web3-only | Gemini | Uphold | AC table
-------------|---------|----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/f9b45e03-58d0-4cf8-be6f-8621f2669f5c) | ![image](https://github.com/brave/brave-browser/assets/38657976/19d6455d-35cf-4050-8401-4f94bf95878f) | ![image](https://github.com/brave/brave-browser/assets/38657976/db472e68-021f-4658-8ec0-c690992d20e2) | ![image](https://github.com/brave/brave-browser/assets/38657976/a49ea31f-56cb-4d40-bf24-3772189ea4d5)

Example | Example | Example
----------|-----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/5a15f7d7-db32-4c01-a467-71f4e04c159b) | ![image](https://github.com/brave/brave-browser/assets/38657976/0b5e8d0c-a83b-496d-93aa-a10b9a082d68) | ![image](https://github.com/brave/brave-browser/assets/38657976/3cd52b4c-5caa-4dc6-9958-ccde4a578293)
