### ISSUE TITLE
feature request: quick commands (fast search)

### ISSUE THREAD

**Issue by edmundlaugasson** [brave/brave-browser#375]
## Description 
Basically I mean similar feature like in Vivaldi Browser - https://help.vivaldi.com/article/quick-commands/
It is especially handy when searching among opened tabs but not only - even history and all other commands in browser. Currently found searching from address bar but this search is not as flexible as in Vivaldi

## Steps to Reproduce

   1. open multiple tabs
   2. try to search among opened tabs, also in tabs history, commands etc
   3. available through address bar among opened tabs and history but not other commands

 ## Actual result:

Available through address bar among opened tabs and history but not other commands.
Would be useful to have an opportunity to use similar floating search window that allows search not only tabs and history but all other commands in Brave

## Expected result:
Would be useful to have an opportunity to use similar floating search window that allows search not only tabs and history but all other commands in Brave

## Reproduces how often: 

Permanent situation currently.

## Brave version (about:brave info)

Name | Version
Brave | 0.22.810
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 4.15.18-041518-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

### Reproducible on current release:

Yes.

**Comment by srirambv** [comment]
Request for browser-laptop but good for brave-core as well. Marking issue as suggestion. +1 on adding a keyboard shortcut for quick search using the default search engine

**Comment by agentofuser** [comment]
Oh wow, I had no idea Vivaldi already had this. I've suggested it just a couple of days ago to Brave on twitter:

https://twitter.com/agentofuser/status/1140980397569990657

The UI could be copied from/inspired by Chromium's own DevTools, where Command+Shift+P already brings up a command palette (which they call Command Menu, but it's explicitly inspired by vscode.)

This would really improve keyboard accessibility, so I would be glad to help this happen however I can ♿🙏

Here is the thread for convenience:

---

The browser address bar should generalize to a command palette, with hooks for extensions and websites to add their own (safe, restricted, sandboxed, etc.) commands, with hotkeys configurable by the user.

Command+Shift+P > 
  Copy as Markdown
  Toggle Dark Mode
  Select All
  &c

---

Imagine accessing every Redux action or event handler from your fingertips, without depending on however the creator decided to spread them on the page or put behind egregious triggers like hover.

On GitHub:
Command+Shift+P:
  Watch
  Star
  Fork
(Which for some reason aren't part of their keyboard shortcuts.)

Why does every different website have to (poorly) reimplement keybindings?

Or "I wish I could navigate this list of checkboxes like on Gmail". Easy:
`> brave install check`

---

@BrendanEich this would make Brave sooo amazing.

And if Chrome vs Everyone Else are going to diverge on extension standards anyway, might as well give those @code-loving lead users something to (b)rave about ;)

Also elegantly solves #kbda11y for tipping.

---

Less experienced users wouldn't even need to know this existed. Fuzzy find for commands would only happen on Command+Shift+P or with the `>` prefix, not on every URL completion.

---

Chromium's #TabToSearch is already a great example of websites adding a command to the address bar via a common standard (OpenSearch):

https://www.chromium.org/tab-to-search  

And a command that takes parameters, at that.

(Btw unbelievable that @Firefox still doesn't have #TabToSearch.)

---

A low-hanging fruit proof of concept that doesn't change any standard:

Enable the address bar command palette only for the commands already registered by extensions in the `commands` Chrome API: https://developer.chrome.com/extensions/commands

---

An even lower-hanging fruit that can be done on a regular extension, without changing the browser at all:

Register a keyword with the omnibox API and use it as a command palette instead of just showing search completions:

https://developer.chrome.com/extensions/omnibox

**Comment by sebastiantf** [comment]
This is so much missed in Brave at this point

**Comment by ldexterldesign** [comment]
The only reason I'm still using Vivaldi and not Brave at this point

**Comment by bsclifton** [comment]
We actually have this feature now

You can use Cmd+Shift+P on macOS or Ctrl+Space on Linux/Win

You can also customize that shortcut on brave://settings/system/shortcuts

If there are specific commands you'd like to see, let's open a new issue please. Thanks!
