### ISSUE TITLE
Remove region support for Ads as CDN now controls catalog for each region

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3752]
Remove region support for Ads including `--brave-ads-locale` command-line argument as CDN now controls catalog for each region

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.34 Chromium: 74.0.3729.40 (Official Build) beta (64-bit)
-- | --
Revision | 278d6a0d856d8314f36fb9a68b6e1d85cd0d14e7-refs/branch-heads/3729@{#470}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/1983
- Encountered https://github.com/brave/brave-browser/issues/3967

**Comment by kjozwiak** [comment]
@tmancey would it be possible to basically add something into the logging that specifies that the CDN check has failed? Right now, QA is basically reliant on the UI via #3967. However, #3967 is currently broken so there's no way for QA to check if ads are not appearing due to being in an incorrect region or something else might have regressed. If the UI breaks in future builds, QA won't be able to double check if the CDN check actually failed etc.. Having something within logging would be super helpful and useful. Thoughts?

**Comment by tmancey** [comment]
> @tmancey would it be possible to basically add something into the logging that specifies that the CDN check has failed? Right now, QA is basically reliant on the UI via #3967. However, #3967 is currently broken so there's no way for QA to check if ads are not appearing due to being in an incorrect region or something else might have regressed. If the UI breaks in future builds, QA won't be able to double check if the CDN check actually failed etc.. Having something within logging would be super helpful and useful. Thoughts?

Sure if you could raise a ticket and we can triage with Jimmy as once we generate the bundle from the catalog we can log information such as the amount of campaigns. Also we can log the IsRegionSupported call to show what region was detected.

**Comment by kjozwiak** [comment]
Thanks @tmancey 👍 For now, we can just take a look at the `catalog.json` and if it's empty, it's probably a good indicator that you're in an unsupported region.
