### ISSUE TITLE
Don't inject content picker on pages by default

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#37841]
At least from doing some pagegraph tests, i see we’re loading `./components/brave_extension/extension/brave_extension/content_element_picker.ts` [1] on every page load (along with the source map).

Its not enormous but its not nothing. Maybe a small perf benefit to remove that? (since enabling the element picker is a very very rare thing)

Like @atuchin-m suggested on Slack, would be best to only load/inject this when the user asks for the element picker

1: https://github.com/brave/brave-core/blob/5718b3ac479e473a049ae346577709e90fb2ae3c/components/brave_extension/extension/brave_extension/content_element_picker.ts

**Comment by LaurenWags** [comment]
Changed to be `QA/No` since this is verified as part of https://github.com/brave/brave-browser/issues/40821 (see https://github.com/brave/brave-browser/issues/40821#issuecomment-2352446992) and we made the other issue that is verified with this (https://github.com/brave/brave-browser/issues/40696) `QA/No` as well as per https://github.com/brave/brave-browser/issues/40696#issuecomment-2362112901.

@atuchin-m let me know if there are any concerns with this approach 👍🏻
