### ISSUE TITLE
Settings: Icons for Section Headings

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3797]
![image](https://user-images.githubusercontent.com/741836/54649207-80d3e200-4a66-11e9-82a7-bad458c18f11.png)

Each section should get the same icon as the sidebar which shows when the window is wide enough to display it.

**Comment by rossmoody** [comment]
For now I think it's best we omit the card title iconography and close this one. It makes the sections quite a bit harder to scan visually for a settings page and feels a little redundant since the icons are also in the sidebar. Updated visual: 

![Screen Shot on 2019-03-20 at 09:35:12](https://user-images.githubusercontent.com/29072694/54702110-79a6e580-4af3-11e9-8899-fe7447c479cf.png)
