### ISSUE TITLE
iOS - Display Sync code expiry when showing the pairing codes

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#38020]
It is required to implement display Sync code expiry when showing the pairing codes.

Parent issue: https://github.com/brave/brave-browser/issues/31904

Figma design:
https://www.figma.com/file/GXnHuBCVRY397UNJyvu44q/Sync-V2?node-id=307-161

This is an issue to link to the PR.

**Comment by kjozwiak** [comment]
@soner-yuksel quick question re: verifying the above. How long does it take for a sync code to expire? Is it still 24hrs? If so, is there any way we can expedite the "expiry" flow without waiting the 24hrs. Perhaps adding something into the QA Dev settings where we can set the time to less than ~24hrs to speed things up? Or does the back-end control the expiry making this hard to QA?

**Comment by soner-yuksel** [comment]
@kjozwiak I believe QR code and sync code words have different expiry time. I had to make changes inside the PR for this atfer opening because @AlexeyBarabash warned me about it. We are getting the expiry time from server. Myabe @AlexeyBarabash can remember the exact tiem frame for expiry.

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.6
- iPad Air / iPadOS 16.7.2
Brave build: 1.68 (110)
BraveCore: 1.68.110 (127.0.6533.26)
```

Filed follow-up issue #39628
---------------------------
<details>
<summary> QR code </summary>

**STEPS:**
1. Launch Brave 
2. Open `Settings` > Sync
3. Start a new Sync Chain
4. Tap `Tablet or Phone` > *Verify the string on the bottom of the QR Code*
5. Take a screenshot of the QR Code
6. Go to device settings and change the time so that the QR Code will expire > *Verify*
7. Tap `Generate New Code` > *Verify*
8. Take another `iOS` or `Android` device and scan the QR code > *Verify*

**ACTUAL RESULTS:**
- Verified that the string `This temporary code is valid for the next 0 hours 29 min 59 seconds` is shown below the QR Code and the timer is working.
- Verified that the string `Code expired. Generate a new one by clicking the button below.` shown after the CR Code expired.
- Verified that the new `QR Code` can be generated when the old one expires.
- Verified that the QR code can be successfully scanned, and a new device (`iOS` or `Android`) is added to the existing Sync chain.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/510744fb-9849-4bfd-9589-c8c838f018b3) | ![2](https://github.com/brave/brave-browser/assets/128532965/6a4163cb-1355-456b-afca-c84b413dd067) | ![3](https://github.com/brave/brave-browser/assets/128532965/751496b3-5580-420c-976e-33e202eadecc) | ![4](https://github.com/brave/brave-browser/assets/128532965/8f9755f2-b312-4276-85b6-11f96ad4dba5) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/1248f2fe-f0ba-45ab-abed-6440ab5bda8b) | ![2](https://github.com/brave/brave-browser/assets/128532965/899f3b85-89ab-4b74-8817-5dbdbbbfca55) | ![3](https://github.com/brave/brave-browser/assets/128532965/e4e9dc09-89f8-4ca8-884a-c3326cee84c7) | ![4](https://github.com/brave/brave-browser/assets/128532965/98f4ca64-d60a-4247-be2b-3c5d356b3f03) |
| ![1]() | ![2]() | ![3]() | ![4]() |


</details>

<details>
<summary> Code Words </summary>

**STEPS:**
1. Launch Brave 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
