### ISSUE TITLE
[iOS] Fix `Refresh` credentials flow for mobile users

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#38086]
Add a link to `Refresh your credentials` for both VPN and Leo. See [spec](https://docs.google.com/document/d/1Xd7aGflHnZfausse_MGVbUxvJlIf06YV9XX8LcGjLXQ/edit#heading=h.zci6nrxpifmw).
Please refer to PR for more details and visual screenshot.

Security Ticket: https://github.com/brave/reviews/issues/1616

**Comment by Uni-verse** [comment]
Did some checks on `Nightly` channel using `1.69 (110)` with `iPhone 12` running `iOS 17.5.1.`

**VPN**

- Ensured hamburger menu on the Account Site is only showing 'Support' and 'Log Out' and excluding 'Account' or 'Plans'. 
- Ensured 'Success!' notification is shown on the Account Site after using `Refresh Credentials` login flow.
- Ensured VPN profile can be installed after credentials are loaded.

Example | Example | Example | Example
-|-|-|-
![IMG_6805 2](https://github.com/user-attachments/assets/9c920f88-4134-430a-8e6d-65457f843302) | ![IMG_6802](https://github.com/user-attachments/assets/cd1af355-cc94-449b-8093-cd00d2779bc9) | ![IMG_6803](https://github.com/user-attachments/assets/d0829a11-3227-45a6-a990-9a4824d651cb) | ![IMG_6804](https://github.com/user-attachments/assets/9c40f84e-e5fe-46a9-bb12-a74ee922f292)

**Leo**

- Ensured hamburger menu on the Account Site is only showing 'Support' and 'Log Out' and excluding 'Account' or 'Plans'. 
- Ensured 'Success!' notification is shown on the Account Site after using `Refresh Credentials` login flow.
- Ensured Leo Premium status was shown and user was no longer rate limited.

Example | Example | Example | Example
-|-|-|-
![IMG_6807 2](https://github.com/user-attachments/assets/c920ab23-663a-4735-b632-10a6604af901) | ![IMG_6808 2](https://github.com/user-attachments/assets/83e3714a-44f2-443a-9832-73b49e853795) | ![IMG_6809 2](https://github.com/user-attachments/assets/9b7213e7-1a1f-4d47-ba64-66665bba08b7) | ![IMG_6810 2](https://github.com/user-attachments/assets/914ec4b6-001a-49f2-abc9-d566f7490ec0)

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.6
- iPad Air / iPadOS 16.7.2
Brave build: 1.68 (124)
BraveCore: 1.68.124 (127.0.6533.57)
```

Filed follow-up issue #
---------------------------
<details>
<summary> VPN </summary>

<details>
<summary> With existing subscription </summary>

**STEPS:**
1. Purchase a new `VPN` subscription on Desktop
2. Take `iOS` test device > Launch Brave
3. Hamburger menu > Brave VPN > *Verify new strings and the `Refresh your credentials` button is shown*
4. Tap `Refresh your credentials` > Enter your email address > Tap `Get login link` > *Verify that link is sent to an email*
5. Go to email and tap `Confirm your email` > *Verify `account.brave.com` is opened, and the `Success!` message is shown*
6. Hamburger menu > Brave VPN > Install VPN Profile > *Verify*

**ACTUAL RESULTS:**
- Verified that new text is shown below the `Monthly subscription` button
- Verified that the new `Refresh your credentials` button is shown and working
- Verified that the `restore link` is sent to email
- Verified that the `Confirm your email` link is working, `account.brave.com` opened, and the `Success!` message shown
- Verified that the VPN subscription can be linked and enabled successfully 

---------------------------

`iPhone 14`

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/2a9ffb1c-7ff5-4b1d-a422-a763223f1563) | ![2](https://github.com/user-attachments/assets/682ba27d-0cb6-401e-ab48-ef99b354c7a8) | ![3](https://github.com/user-attachments/assets/9fde8b0d-99df-44cd-ab45-b357f97fbf8f) |
| ![1](https://github.com/user-attachments/assets/e5001d16-89eb-4f12-8065-db915db7e478) | ![2](https://github.com/user-attachments/assets/e8ffcc22-828e-4317-97e5-52e918e7ae3d) | ![3](https://github.com/user-attachments/assets/f80a9f53-b4ae-4a7a-9465-e7b44afa7ec5) |
| ![1](https://github.com/user-attachments/assets/84d35e7b-5682-4082-ac07-7a3a6118f626) | ![2](https://github.com/user-attachments/assets/8cc7540f-6354-48cc-bf86-117c969916d6) | ![3](https://github.com/user-attachments/assets/c0311d77-030a-44b6-9f41-16c24129ee3e) |

`iPad Air`

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/ae022bdb-88c3-4aaa-ae70-4c7e578f6e92) | ![2](https://github.com/user-attachments/assets/c1bd1a26-952b-4c8b-9a1c-d4135a84e510) | ![3](https://github.com/user-attachments/assets/680a5a37-6ca6-4deb-880a-49cfbbda2877) |
| ![1](https://github.com/user-attachments/assets/cdf7907c-5413-4de8-b8e7-09c46b98c4ac) | ![2](https://github.com/user-attachments/assets/d5ad1a04-71f1-46a1-94fc-e3b64c55f245) | ![3](https://github.com/user-attachments/assets/153ceb26-51d3-4521-b92b-adc13fe57989) |
| ![1](https://github.com/user-attachments/assets/4999fa8e-8056-4829-99bb-4b3e56770735) | ![2](https://github.com/user-attachments/assets/8a3e37fc-20e4-42a7-9557-4c3f26123a95) | ![3](https://github.com/user-attachments/assets/b0cb5678-9990-41ab-8581-2497849845ad) |
</details>

<details>
<summary> Without existing subscription </summary>

**STEPS:**
1. Don't purchase `VPN` subscription
2. Take the `Android` test device > Launch Brave
3. Hamburger menu > Brave VPN > *Verify new strings and the `Refresh your credentials` button is shown*
4. Tap `Refresh your credentials` > Enter your email address > Tap `Get login link` > *Verify that link is sent to an email*
5. Go to email and tap `Confirm your email` > *Verify `account.brave.com` is opened, and a warning message is shown*

**ACTUAL RESULTS:**
- Verified that `We couldn't find a subscription associated with your email address.` message is shown on the `account.brave.com` page if no active `VPN` subscription is found for that account.

---------------------------

https://github.com/user-attachments/assets/9ec0c7f5-0b51-4e81-90f7-fa5c4241196b
</details>
</details>

<details>
<summary> Leo </summary>

<details>
<summary> With existing subscription </summary>

**STEPS:**
1. Purchase a new `Leo` subscription on a Desktop, iOS or Android device
2. If purchased on an iOS or Android device, link the subscription to account.brave.com
3. Take `Android` test device > Launch Brave
4. Hamburger menu > Settings
5. Leo > Go Premium > *Verify new strings and the `Refresh your credentials` button is shown*
6. Tap `Refresh your credentials` > Enter your email address > Tap `Get login link` > *Verify that link is sent to an email*
7. Go to email and tap `Confirm your email` > *Verify `account.brave.com` is opened, and the `Success!` message is shown*
8. Open `Leo` > *Verify that `Premium` account is shown*

**ACTUAL RESULTS:**
- Verified that new text is shown below the `Monthly subscription` button
- Verified that the new `Refresh your credentials` button is shown and working
- Verified that the `restore link` is sent to email
- Verified that the `Confirm your email` link is working, `account.brave.com` opened, and the `Success!` message shown
- Verified that the VPN subscription can be linked and enabled successfully 

---------------------------

`Galaxy Tab S8`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/9982f52d-d00d-4361-8d6b-8382b4ec79e6) | ![2](https://github.com/user-attachments/assets/212fa6cc-ef49-4fd8-bb8a-3643c900dd57) | ![3](https://github.com/user-attachments/assets/00f1131d-4249-44e2-86cb-f1541e315544) | ![4](https://github.com/user-attachments/assets/a8fd4059-7924-471b-8b6c-8818031db6b8) |

https://github.com/user-attachments/assets/6beb5ab8-a361-497c-9c0d-329c57e7ee5a

`Pixel 7`

https://github.com/user-attachments/assets/4214bea0-078a-4dc3-96c4-b31915aefffa
</details>

<details>
<summary> Without existing subscription </summary>

**STEPS:**
1. Don't purchase a `Leo` subscription
2. Take the `Android` test device > Launch Brave
3. Hamburger menu > Settings
4. Leo > Go Premium > *Verify new strings and the `Refresh your credentials` button is shown*
5. Tap `Refresh your credentials` > Enter your email address > Tap `Get login link` > *Verify that link is sent to an email*
6. Go to email and tap `Confirm your email` > *Verify `account.brave.com` is opened, and a warning message is shown*

**ACTUAL RESULTS:**
- Verified that `We couldn't recover your credentials for Leo Premium since the subscription is not paid.` message is shown on the `account.brave.com` page if no active `Leo` subscription is found for that account.

https://github.com/user-attachments/assets/7a189cd9-3713-4525-8607-69dc11a862e0
</details>
</details>
