### ISSUE TITLE
No longer able to choose between different modes of fingerprinting resistance. 

### ISSUE THREAD

**Issue by LiamPerson** [brave/brave-browser#38142]
## Description 

In the Brave browser the options for fingerprinting resistance are no longer available.
![image](https://github.com/brave/brave-browser/assets/34695601/4ef01fab-cfa0-41e4-9f21-87a152c093fb)

## Steps to Reproduce

   1. Open Brave browser
   2. Navigate to any website
   3. Open the Brave shield in the top right of the address bar
   4. Open the 'Advanced controls'
   5. Observe that 'Block fingerprinting' is now a toggle instead of an option select.

## Actual result:

![image](https://github.com/brave/brave-browser/assets/34695601/8dab30e7-57cb-4459-91fd-7ec4b30243c2)

## Expected result:
Expecting to see options to change the level of protection available. 

## Reproduces how often: 

Always reproduceable.

## Brave version (brave://version info)

1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tried
- Can you reproduce this issue with the nightly channel? Not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Not relevant
- Does the issue resolve itself when disabling Brave Rewards? Not relevant
- Is the issue reproducible on the latest version of Chrome? Not applicable 

## Miscellaneous Information:

I have checked through the changelogs and cannot find any change listed that would suggest this is intentional. Was this a mistake/bug or a change to how Brave will behave moving forward?

**Comment by TEMP-ad** [comment]
Strict fingerprinting didn't offer much compared to Standard while breaking too many sites because of the WebGL, which was the biggest 'factor' that strict had over Standard.
You can see it here: https://dev-pages.brave.software/fingerprinting/farbling.html

But t is clear you didn't try to search hard enough though, and you just decided to create this issue, that it is not an issue, when it was _news_ around the web when Brave team made the blog post about it, and Github Wiki talks about it too and it was on the changelog of the release 1.62.152 = since January 24th... months ago.

1. https://brave.com/privacy-updates/28-sunsetting-strict-fingerprinting-mode/

2. https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections#differences-between-standard-and-strict-protections

3. https://github.com/brave/brave-browser/releases/tag/v1.62.152 
   > Removed aggressive fingerprinting mode (being rolled out in phases using Griffin).

4. `brave://flags/#brave-show-strict-fingerprinting-mode`

**Comment by ShivanKaul** [comment]
This is intended, we announced this [change early this year](https://brave.com/privacy-updates/28-sunsetting-strict-fingerprinting-mode/) and included it in the Release Notes on [Community](https://community.brave.com/t/release-channel-1-62-153/528148/2) and [GitHub](https://github.com/brave/brave-browser/issues/35541).
