### ISSUE TITLE
[Desktop] Update UX with advanced server selection

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#38186]
With more location data and flags available now we can improve the VPN server selection UX on all platforms. 

See Figma for Desktop: https://www.figma.com/file/J4LKBMftiWhqromRWfUQLG/VPN-design?type=design&node-id=5-6843&mode=design&t=xFQ9Ux13hVU9JeSb-4

**Comment by bsclifton** [comment]
iOS tracked with https://github.com/brave/brave-browser/issues/36409
Android tracked with https://github.com/brave/brave-browser/issues/36277

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.71.101 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | 734075a5959db3e93d6def81a15e1fc6c2609fc2
OS | Windows 11 Version 23H2 (Build 22631.4249)
```

1. Installed `1.71.101`
2. launched Brave
3. opened account.bravesoftware.com with basic auth
4. subscribed to VPN as a new user
5. verified credentials successfully loaded message shown on the subscription page
6. clicked VPN button to open vpn panel 
7. confirmed the main panel shows `USA` was selected as a default and shows `Optimal` as sub label 
8. expanded server selection panel
9. clicked country `Romania` entry
10. confirmed it shows Optimal sub entry and its cities "Bucharest 10 servers"
11. hovered over and clicked connect on Optimal sub entry
12. confirmed `Romania` is displayed along `Optimal` text in the VPN panel
13. confirmed a check mark shown next to `optimal` sub label
14. confirmed VPN is connected to Romanian server via whatismyipaddress.com
15. opened VPN server panel
16. selected `France` in the panel for country selection
17. clicked down arrow 
18. hover over the city `Lille` and clicked `Connect`
19. confirmed main panel's sub label has city name "Lille" with country name `France`


step 5 | step 7 | step 9 | step 9-11 | step 12 | step 13 | step 14 | step 18 | step 19 
----- | ----- | ------ | ------ | ------ | ------ | ------ | ------ | ----- 
![image](https://github.com/user-attachments/assets/31d95fd0-02db-43e5-aac1-4f27b637834e)|![image](https://github.com/user-attachments/assets/72f4aa75-a1da-453f-b593-4919bf173dd1)|![image](https://github.com/user-attachments/assets/d1e7f122-a318-4588-a2a7-7064a75f80e7)|![image](https://github.com/user-attachments/assets/d9c2bc09-9c48-4f92-a0d1-4585649df5c5)|![image](https://github.com/user-attachments/assets/0d941eb7-1017-48d5-8dc9-940aadbe39d2)|![image](https://github.com/user-attachments/assets/1e3ef7c1-9053-4941-b159-da3b7cb6cbe0)|![image](https://github.com/user-attachments/assets/60466084-1d24-4e8c-8307-442a7824c64d)|![image](https://github.com/user-attachments/assets/62938098-2618-4dde-acff-00529d66091a)|![image](https://github.com/user-attachments/assets/7f616499-7de8-4be0-b4a5-b31abd4b2328)

**Comment by GeetaSarvadnya** [comment]
Verification `INPROGRESS` using

```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (arm64)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | macOS Version 12.5 (Build 21G72)
```
Filed: https://github.com/brave/brave-browser/issues/41395

<details>
<summary>New Install - PASSED</summary>

1. Installed `1.71.101`
2. launched Brave
3. opened account.bravesoftware.com with basic auth
4. subscribed to VPN as a new user (brave38186vpnnewuser@mailinator.com)
5. verified credentials successfully loaded message shown on the subscription page
6. clicked VPN button to open vpn panel 
7. confirmed the main panel shows `USA` was selected as a default and shows `Optimal` as sub label 
8. expanded server selection panel
9. clicked country `Romania` entry
10. confirmed it shows Optimal sub entry and its cities "Bucharest 10 servers"
11. hovered over and clicked connect on Optimal sub entry
12. confirmed `Romania` is displayed along `Optimal` text in the VPN panel
13. confirmed a check mark shown next to `optimal` sub label
14. confirmed VPN is connected to Romanian server via whatismyipaddress.com
15. opened VPN server panel
16. selected `France` in the panel for country selection
17. clicked down arrow 
18. hover over the city `Lille` and clicked `Connect`
19. confirmed main panel's sub label has city name "Lille" with country name `France`
20. selected Automatic entry on top of the server selection panel
21. When clicks it, guardian picks proper server based on current timezone's region - I got USA optimal not timezone based server.


step 5 | step 7 | step 9 | step 9-11 | step 12 | step 13 | step 14 | step 18 | step 19 | step 20 | step 21 
----- | ----- | ------ | ------ | ------ | ------ | ------ | ------ | -----  | ------- | -----
![image](https://github.com/user-attachments/assets/31d95fd0-02db-43e5-aac1-4f27b637834e)|![image](https://github.com/user-attachments/assets/72f4aa75-a1da-453f-b593-4919bf173dd1)|![image](https://github.com/user-attachments/assets/d1e7f122-a318-4588-a2a7-7064a75f80e7)|![image](https://github.com/user-attachments/assets/d9c2bc09-9c48-4f92-a0d1-4585649df5c5)|![image](https://github.com/user-attachments/assets/0d941eb7-1017-48d5-8dc9-940aadbe39d2)|![image](https://github.com/user-attachments/assets/1e3ef7c1-9053-4941-b159-da3b7cb6cbe0)|![image](https://github.com/user-attachments/assets/60466084-1d24-4e8c-8307-442a7824c64d)|![image](https://github.com/user-attachments/assets/62938098-2618-4dde-acff-00529d66091a)|![image](https://github.com/user-attachments/assets/7f616499-7de8-4be0-b4a5-b31abd4b2328)|![image](https://github.com/user-attachments/assets/04f7dec8-80ef-415c-bf59-8da64624b5c3)|![image](https://github.com/user-attachments/assets/672b0ce2-e918-4555-8732-25f58b7fe57f)


**Dark mode**

example | example | example | example | example | example | example 
------- | ----- | ------- | ------ | ---- | ------ | ------
![image](https://github.com/user-attachments/assets/0c3a1238-adf3-4d4d-b468-47f593078a8a)|![image](https://github.com/user-attachments/assets/284b1c81-9329-4837-958e-6aae66173e08)|![image](https://github.com/user-attachments/assets/452fd173-faea-4df9-bbed-82461ae63710)|![image](https://github.com/user-attachments/assets/3b51deb4-6465-443d-8b1b-db38614c1d03)|![image](https://github.com/user-attachments/assets/1946a0d3-ca34-46ba-9c02-c3e3dbc98d63)|![image](https://github.com/user-attachments/assets/d2d850ec-97c1-4a8b-8a6e-dbe92811aa9a)|![image](https://github.com/user-attachments/assets/e4095ad4-e8e7-4ebe-9b65-91f80a9540bd)
</details>

<details>
<summary>Upgrade - FAILED</summary>

1. Installed `1.70.123`
2. launched Brave
3. opened account.bravesoftware.com with basic auth
4. logged into Brave VPN as an existing (above) user (brave38186vpnnewuser@mailinator.com)
5. clicked `Refresh Firewall + VPN
6. verified VPN credentials message is shown on the subscription page
7. clicked `VPN` button
8. confirmed the VPN panel shows `USA(West)` was selected as a default 
9. expanded server selection panel and hovered over the country
10. verified `Connect` button is shown as expected
11. enabled VPN 
12. closed Brave
13. rename the profile to `Brave-Browser-Beta`
14. installed `1.71.101`
15. relaunch Brave
16. clicked VPN button
17. confirmed vpn panel has shown the country name and flag (USA) with sub label of `Optimal` 
18. expanded the VPN Panel 
19. server selection panel shows `USA 10 cities - 110 servers`
20. scrolled up and hovered over `Australia` 
21. confirmed 1 city - 8 servers` text shown with connect button
22. clicked `Connect` button
23. confirmed the panel shows `Australia` along with `Optimal` sub label
24. clicked > to open main server selection panel and hovered over Austria 
25. confirmed it shows Optimal sub entry and its city "Vienna 10 servers"
26. hovered over and clicked connect on Optimal sub entry
27. confirmed `Austria` is displayed along `Optimal` text in the VPN panel
28. confirmed a check mark shown next to `optimal` sub label
29. switched to Canada and it failed with Can`t connect to server` error

step 5 | step 6 | step 8 | step 10 | step 11 | step 17 | step 19 | step 20 | step 22 | step 23 | step 28 | step 29
------ | ------ | ------- | ------ | ------ | ------- | ------- | ------- | ------- | ------- | ------- | -----
![image](https://github.com/user-attachments/assets/dcc689df-ab4c-4fb1-9caa-4629416adc33)|![image](https://github.com/user-attachments/assets/716ba5c1-f58d-4e2e-abd4-98658b6adb5c)|![image](https://github.com/user-attachments/assets/9e7dc602-fe46-45d4-931b-56faa8bd6889)|![image](https://github.com/user-attachments/assets/504e5c3e-e70a-41b8-a8b9-6137e61623b1)|![image](https://github.com/user-attachments/assets/0f9ecbc5-a8d7-41d1-be41-82868b4654ec)|![image](https://github.com/user-attachments/assets/6b590896-9103-483a-b012-dc2d50081682)|![image](https://github.com/user-attachments/assets/3a3e057b-98d1-4dec-949f-c55dcfcf2028)|![image](https://github.com/user-attachments/assets/abe87a26-27a4-4228-a9d7-9d14b36726d2)|![image](https://github.com/user-attachments/assets/7421ed58-c745-49f1-b6ad-12bfe0f03b04)|![image](https://github.com/user-attachments/assets/14236da1-22b5-4775-9a6b-b15211d46fc5)|![image](https://github.com/user-attachments/assets/1a08c8d1-3207-47a3-8dc6-d7adb50d80fe)|![Image](https://github.com/user-attachments/assets/8e7e0909-cdb4-4690-824f-205003636295)

</details>

**Comment by simonhong** [comment]
@GeetaSarvadnya Can you test `Upgrade` scenario with https://github.com/brave/brave-browser/issues/41395#issuecomment-2409086102?

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (x86_64)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | macOS Version 14.7 (Build 23H124)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Windows 10 Version 22H2 (Build 19045.5011)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

<details>
<summary>New Install - PASSED</summary>

1. Installed `1.71.112`
2. launched Brave
3. opened account.bravesoftware.com with basic auth
4. subscribed to VPN as an existing user (brave38186vpnnewuser@mailinator.com)
5. verified credentials successfully loaded message shown on the subscription page
6. clicked VPN button to open vpn panel 
7. confirmed the main panel shows `USA` was selected as a default and shows `Optimal` as sub label 
8. expanded server selection panel
9. clicked country `Romania` entry
10. confirmed it shows Optimal sub entry and its cities "Bucharest 10 servers"
11. hovered over and clicked connect on Optimal sub entry
12. confirmed `Romania` is displayed along `Optimal` text in the VPN panel
13. confirmed a check mark shown next to `optimal` sub label
14. confirmed VPN is connected to Romanian server via whatismyipaddress.com
15. opened VPN server panel
16. selected `South Africa` in the panel for country selection
17. clicked down arrow 
18. hover over the city `Johannesburg` and clicked `Connect`
19. confirmed main panel's sub label has city name "Johannesburg" with country name `SouthAfrica`
20. loaded whatismyipaddress.com and it shows correct region
21. selected Automatic entry on top of the server selection panel
22. When clicks it, guardian picks proper server based on current timezone's region - I got USA optimal not timezone based server - This is expected behavior

step 1 | step 7 | step 9-11 | step 14 | step 18 | step 20 | step 21 | step 22
----- | ----- | ------ | ------ | ------ | ------ | ------ | ------
![Image](https://github.com/user-attachments/assets/ea37579f-5dbe-45f2-aeeb-0fcc2e7dda88)|![Image](https://github.com/user-attachments/assets/14c5e1b8-4e0f-4029-91ff-f34237618c82)|![Image](https://github.com/user-attachments/assets/b4a6ed53-b942-41d6-aadf-fc69bc739e3a)|![Image](https://github.com/user-attachments/assets/c498f74c-b8f0-453c-96be-c33a3a113e8c)
![Image](https://github.com/user-attachments/assets/09378620-df21-452a-bd25-61bc8ef14eac)|![Image](https://github.com/user-attachments/assets/daf52b36-9125-4d8b-bb05-aa9995c1ccd2)|![Image](https://github.com/user-attachments/assets/84971c74-32d3-412a-8a9a-777037d46611)|![Image](https://github.com/user-attachments/assets/c7c18226-c0dc-4a9b-86e7-2cdfec25b4a8)

</details>

<details>
<summary>Upgrade - PASSED</summary>

1. Installed `1.70.123`
2. launched Brave
3. opened account.bravesoftware.com with basic auth
4. logged into Brave VPN as an existing (above) user (brave38186vpnnewuser@mailinator.com)
5. clicked `Refresh Firewall + VPN
6. verified VPN credentials message is shown on the subscription page
7. clicked `VPN` button
8. confirmed the VPN panel shows `USA(West)` was selected as a default 
9. enabled VPN 
10. installed `1.71.112`
11. upgraded via brave://settings/help
12. clicked VPN button
13. confirmed vpn panel has shown the country name and flag (USA) with sub label of `Optimal` 
14. enabled and expanded the VPN Panel 
15. server selection panel shows `USA 10 cities - 110 servers`
16. scrolled up and hovered over `Australia` 
17. confirmed 1 city - 8 servers` text shown with connect button
18. opened whatismyipaddress.com and correct region is shown
19. switched to Canada and it failed with Can`t connect to server` error

step 1 | step 5 | step 6 | step 8-9 | step 10 -11 | step 12-13 | step 15 | step 18| step 19 
------ | ------ | ------- | ------ | ------ | ------- | ------- | ------- | ------- 
![Image](https://github.com/user-attachments/assets/6c73a2f7-3a0c-44f4-a555-9fdea7bea6d9)|![Image](https://github.com/user-attachments/assets/4f35e247-2202-498b-a567-9ddce1f81270)|![Image](https://github.com/user-attachments/assets/8be53673-986f-4bcb-a068-8e0f1aba9352)|![Image](https://github.com/user-attachments/assets/66b10cda-dfab-4354-a912-8bb3b68e6fa0)|![Image](https://github.com/user-attachments/assets/60e66d96-9dd6-4da3-bf54-878a8684416a)|![Image](https://github.com/user-attachments/assets/a45c4892-4970-460d-b055-5257f59aaa43)|![Image](https://github.com/user-attachments/assets/a6f3b5aa-3196-46d8-a35a-f31f0d22eff5)|![Image](https://github.com/user-attachments/assets/40624fc6-09ed-4d75-87be-ca466988c230)|![Image](https://github.com/user-attachments/assets/d556a632-c739-4be4-a2ba-c8a0e31ddda5)






</details>
