### ISSUE TITLE
[iOS] Update User Agent to 17.5

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#38322]

**Comment by kjozwiak** [comment]
The above requires `1.67.93` or higher for `1.67.x` verification 👍 @Uni-verse @hffvld can use the template from https://github.com/brave/brave-core/pull/23652#issuecomment-2127740753 but we should also keep an eye on `1.67.x` in general when running through verifications to ensure websites are loading without any issues due to the UA change.

**Comment by kjozwiak** [comment]
The above requires `1.66.120` or higher for `1.66.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66.1 (120)
BraveCore: 1.66.120 (125.0.6422.165)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Follow the steps from https://github.com/brave/brave-core/pull/23652#issue-2296271425 and https://github.com/brave/brave-core/pull/23652#issuecomment-2127740753
3. *Verify*

**ACTUAL RESULTS:**
- Verified that `Brave` and `Safari` user agent are the same on `iOS 17.5`

---------------------------

|Brave|Safari|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/5cde6ad7-6543-4d38-b20d-3041a564bdbd) | ![2](https://github.com/brave/brave-browser/assets/128532965/8bcf4e90-8139-4d0f-9848-c9ec91f8fb64) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/3e7413df-f9ec-4c8d-8795-2d97f8c97e44) | ![2](https://github.com/brave/brave-browser/assets/128532965/4a89f307-7b49-4f3f-a5bd-0154e2b3a799) |
