### ISSUE TITLE
URL should be easier to edit in address bar

### ISSUE THREAD

**Issue by tathastu871** [brave/brave-browser#38395]
## Steps to reproduce 

   1. Write query/keyword in omnibox
   2. Search
   3. Click on Omnibox to edit query. It presents with whole search engine url instead of Just query to edit.
ALL CHROME AND CHROMIUM BASED BROWSERS ON ANDROID HAS ALDREADY IMPLEMENTED THIS FEATUTE EXCEPT THIRD CLASS BRAVE  BROWSER

## Actual result 

![Screenshot_20240517-120249_Brave](https://github.com/brave/brave-browser/assets/65007212/e825a0a8-7e7f-4a58-844e-19da58b73bfa)

ABOVE IN BRAVE ANDROID
## Expected result
![Screenshot_20240517-120307_Kiwi Browser](https://github.com/brave/brave-browser/assets/65007212/e0de1621-863d-47fb-8d2b-7627ad4135d8)

ABOVE IN KIWI

https://github.com/brave/brave-browser/assets/65007212/eeb8067f-c3b4-4328-aaaa-cb96e558ff86

ABOVE IN CHROME

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): arm
   - Device type (Phone, Tablet, Phablet): Phome
   - Android version: 10
   
## Brave version
 Brave 1.66.110, Chromium 125.0.6422.60
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by hairycactus** [comment]
>  ALL CHROME AND CHROMIUM BASED BROWSERS ON ANDROID HAS ALDREADY IMPLEMENTED THIS FEATUTE EXCEPT THIRD CLASS BRAVE  BROWSER

I'm experiencing the same issue. That being said, previous versions of Brave Android did have the said function -- ie. tapping the URL address bar will show the `Share | Copy | Edit Link` icons.

The above function suddenly disappeared from **Brave Android v1.66.110**, even though I did not make any changes to the browser or system settings on my device.

### Observed Behaviour in Brave Android v1.66.110:

#### Trying to Copy URL:
1. Tap URL bar showing hyperlink.
2. Whole URL gets highlighted.
3. Empty translucent space is displayed below URL bar -- ie. the `Share | Copy | Edit Link` icons are missing.
4. Tap empty translucent space to remove it, or else webpage below is not accessible.

#### Trying to Paste URL/Text String:
1. Copy URL/text from Brave Android -- using alternative method as workaround (eg. long-press URL to trigger Copy-Paste context menu) -- or from another app.
2. Tap Brave Android's URL bar.
3. Whole URL (if any) gets highlighted.
4. Empty translucent space appears below URL bar -- ie.  `Link/Text you copied` text row below URL bar is missing.

### Expected/ Normal Behaviour:

#### To Copy URL:
1. Tap URL bar showing hyperlink.
2. Whole URL gets highlighted.
3. To copy URL, tap `Copy` icon (2 overlapping rectangles) below URL bar.
4. `URL copied` floating message is briefly shown at bottom of browser window.

#### To Paste Copied URL/Text String in Current/New Tab:
1. Tap URL bar.
2. Tap `Link/Text you copied` text row that appears below URL bar.
3. Browser instantly loads the pasted URL, or the search results for the pasted text string.

#### Screenshots of Expected/ Normal Behaviour (collated from various sources):
![Screenshot: Brave Android v1.66.110 URL Bar Copy-Paste Bug](https://github.com/brave/brave-browser/assets/9943769/40e4f938-ea26-4d03-8397-29232837a797)

- **Brave Version:** v1.66.110 x64 (16 May 2024 stable release, Google Play Store)
- **Chromium Version:** v125.0.6422.60
- **Extensions Installed:** Nil
- **Problem seen with Brave Shields Disabled:** Yes
- **Problem seen with Brave Rewards Disabled:** Yes
- **Other Browsers Installed:** Nil

* **Device Type:** Mobile Phone
* **Android Version:** v12

**Comment by tathastu871** [comment]
Clicking edit pendil should show query to edit instead of whole search engine url

**Comment by hairycactus** [comment]
> @bsclifton: I think the big issue we have is that the URL bar is not cleared when omnibox is focused
> For example, in Chrome I can search Mercedes and pick a result. When refocusing the omnibox, it clears the box and then shows the current URL as a history entry directly below it (with a copy button).

Isn't the above the usual behaviour both in Chrome/Chromium & Brave ? Tapping to focus the URL bar did/does select whatever is CURRENTLY shown in the URL bar.

When tapped, the focussed URL bar with current text did/does *not* get cleared.

> @tathastu871: Clicking edit pendil should show query to edit instead of whole search engine url

From what I recall from using previous Brave Android versions, the row of `Share | Copy | Edit Link` icons (including the pencil `Edit` icon) on the right side below the URL bar has always pertained to what is shown within the URL bar itself -- not whatever history URL is on the icons' immediate left side.

If user is still on the search results webpage (as depicted by the search engine or magnifier favicon on extreme left of URL bar), tapping the URL bar did/does select the **search engine results** URL itself  -- be it for copying, editing or sharing.

Only If user then taps on & loads -- for instance -- the Wikipedia result for XYZ in the search result, then tapping on the URL bar would select the Wikipedia URL for XYZ.

Maybe the close placement of the `Share | Copy | Edit Link` icons row with the related results/ history row gives rise to misunderstanding amongst some users that these 2 might be related under certain circumstances ...

Personally, since I don't store search history results below the URL bar, I have never misunderstood the actual function & behaviour of the row of `Share | Copy | Edit Link` icons under the URL bar.

**Comment by hairycactus** [comment]
Note: Although @tathastu871's Brave Android's screenshot (under **Actual Result**) does show the issue I'm facing (missing `Share | Copy | Edit Link` icons when the URL bar is tapped, I think @tathastu871 might be talking about something else.

As such, I've moved the missing `Share | Copy | Edit` icons bug/ problem to a new separate Issue at #38507.

**Comment by tathastu871** [comment]
Clicking edit pencil should show query to edit instead of whole search engine urlI am 


When we perform a search query on omnibox address bar shows whole searxh engine urls

i search wikipedia on omnibox it takes me to google search query for wikipedia

now i want to change query to wiki if i click on google search bar it very slow and untesponsive and **** brave always crashes.

so  when we click edit icom omnibox shows long **** gooogle string ,
instead in other browsers like kiwi it shoes seqrxh query itself not searxh enhine url

so ease of edit the query

**Comment by Brave-Matt** [comment]
User here on Community notes that the issue does not occur on Android 9:
https://community.brave.com/t/option-to-copy-link-from-address-bar/549704/4?u=mattches

**Comment by hairycactus** [comment]
> @Brave-Matt: User here on Community notes that the issue does not occur on Android 9:
https://community.brave.com/t/option-to-copy-link-from-address-bar/549704/4?u=mattches

For clarity, user isTroopyciuu at Brave Community forum is describing the same problem (missing `Share | Copy | Edit Link` icons upon tapping URL bar) that I am encountering. As mentioned earlier, I had separately posted this as a new issue:
- #38507

As such, solving the above bug is unlikely to address what user @tathastu871 appears to talking about:

- Unhappiness that the functionality/ workflow of Brave Android's `Share | Copy | Edit Link` icons is *not identical to Kiwi Browser & Google Chrome Android browser*.

- Apparent [lag & crash when tapping Google search engine's omnibox](https://github.com/brave/brave-browser/issues/38395#issuecomment-2126948792) in their current copy of Brave Android.

**Comment by hairycactus** [comment]
> @tathastu871: now i want to change query to wiki if i click on google search bar it very slow and unresponsive and **** brave always crashes.

Interesting ... tapping on Google Search's omnibox/ search bar should NOT cause Brave to lag or crash. As far as possible, I have repeated your mentioned steps on my Brave Android (current v1.66.113 Stable), & I have not faced any problems.

Since you can *always* reproduce the crash, you might wish to submit a screen recording of your Brave Android, Crash ID(s) (from: `brave://crashes`), & a report for Brave developers to investigate ?

When your Brave Android lagged/ crashed:
- How tabs/ windows are open ?
- Is your autofill service enabled & what is it set to ?

(Your screen recording only shows your preferred workflow for Google Search result's omnibox contents in your Google Chrome Android browser.)

In the Brave Community forum, there are mentions of Brave crashing, when user tries to search using the default/ Google/ any search engine's "search bar". They all seem to be related to user setting the autofill to anything except Google's.

- Brave Android v1.64.113 (01 Apr 2024): https://community.brave.com/t/brave-crashes-when-i-click-on-search-bar/540739

Same issue dating to 2023:
- https://community.brave.com/t/brave-crash-after-when-trying-new-google-search/462608/15
- https://community.brave.com/t/brave-crashes-when-search-bar-is-clicked-round-two/484607/14
- https://community.brave.com/t/brave-crashes-when-search-bar-is-clicked/463700/16
- https://community.brave.com/t/brave-keeps-crashing-when-tapping-on-search-bar-from-any-search-engine/503320

**Comment by hairycactus** [comment]
> @tathastu871: Clicking edit pencil should show query to edit instead of whole search engine url

Personally, I very much prefer Brave Android's current workflow/ functionality of the `Share | Copy | Edit Link` icons to quickly *manipulate the existing URL/text inside URL bar*.

Out of curiosity, I searched past requests in various Brave forums about the above, & the current functionality/ workflow is what various users previously requested.

It seems that you might be requesting to totally change the workflow to instead *manipulate the Search Term query inside Google Search engine's omnibox* -- as shown in your screen recording of Google Chrome Android.

I don't know if it is practical for Brave developers to create a new config/ flag setting just to allow users like you to choose to make Brave Android behave identically to Google Chrome/ Kiwi Browser in this aspect.

Below is what happens when I try editing the Search Term Query itself -- eg. from `wikipedia` to `wiki` -- using 2 methods, both of which are super easy.

### Method A:
1. Tap on search engine's omnibox containing search query `wikipedia`.
2. `wikipedia` appears as a text row (prefixed with `←` blue arrow) below URL bar.
   - To return to the original `wikipedia` search results listing instead, tap `←` blue arrow.
4. Tap keypad's `Backspace` to edit/ change search query term to `wiki`.
   - OR: Tap on `wiki` related-term suggestion, which is likely to appear in listing below URL bar.
5. Tap keypad's `Magifier` key to start searching for `wiki`.

Not sure if you can reproduce this method, since you mentioned lagging/ crashing when you tap Google Search's omnibox.

Screenshots:
![Brave1.66.113-Android12-SearchEngineBox-QueryEdit-24May24](https://github.com/brave/brave-browser/assets/9943769/0256eb1b-5704-491c-91cc-7e8c954e9b4f)


### Method B:
1. Tap URL bar.
2. Whole search engine results URL gets highlighted.
3. Tap `X` in URL bar, or tap keypad's `Backspace` to delete URL bar's contents.
4. Use keypad to type in `wiki`.
7. Tap keypad's `Magifier` key to start searching `wiki`


None of the above 2 methods causes unresponsiveness or crash in my Brave Android.

Tested in Brave Android v1.66.113 Stable with:
- Single tab open
- Multiple tabs (3 nos.) open & loaded
- Brave Shields enabled
- Autofill service disabled (never enabled, & don't intend to enable this)

**Comment by tathastu871** [comment]
Just  because your browser doesnt crash when editing google search bar that doesnt means it doesny happen with others there are many such reports  if you have actually read past open issues

FOR A CASUAL PERSON IT MAY NOT CRASH.
BUT FOR PERSONS WHO ARE HEAVY BROWSER SURFERS WHO HAVE 100s of TABS OPENED AS WELL AS THEY BROWSE QUICKLY WHO SEARCH QUERY AND THEN QUICKLY TRY TO CHANGE BRAVE BROWSER DOESNT KEEP UP. 
READ OPEN ISSUES ON SEARCH+CRASH YOU WILL SEE MANY PEOPLES HAVE REPORTED AND COMMENTED THAT THOSE PEOPLE WHO ARE PERSISTENTLY USING BROWSER FOR ALL DAY LONG SURFING HAS MULTIPLE TABS OPENED THEY FREQUENTLY ENCOUNTER CRASH WHEN EDITING GOOGLE SEARCH BAR AND **NOT ONLY GOOGLE ON ANY SITE FOR EG GITHUB IF YOU TRY TO EDIT SEARCH QUERY IN SEARCH BAR ELEMENT/FORM BRAVE CRASHES.**

AFTER CRASH JUST HAPPENED BRAVE CLOSED HOW CAN I GIVE SCREENSHOT

PLUS WHEN CRASH HAPPENS ONLY FEW TIMES THERE ARE PROMPTS TO SEND FEEDBACK THAT BRAVE PRESENT I HAVE CLICKED ON SEND REPORT MANY TIMES WITH COMMENT AND SCREENSHOT. BUT DEVS ARE JUST IGNORING OR BRAVE IS NOT NOTIFYING THEM

ALSO AFTER CRASH I OPEN BRAVE AND VISIT BRAVE://CRASHES BUT THERE ARE NO LOG


PERSONALLY DUE TO NEGLECTING AND RELUCTANT DEVS I HAVE ALREADY STOPPED USING BRAVE ANYMORE SINCE 2YEARS. 

NOW I HAVE SHIFTED TO KIWI. EVEN THER USERS HAVE COMMENTED IN BRAVE ISSUES THAT THEY HAVE SWITCHED TO DIFFERENT BROWSERS

KIWI IS BEST. AS FOR AD BLOCKING CAPABILITIES OF BRAVE I CAN MIMIC IT WITH KIWI EXTENSIONS AND ADGUARD


**BRAVE IS A BROWSER WHO DOESNT EVEN SERVE THE BASIC PURPOSE OF BEING BROWSER. IT LACKS FEATURES THAT MAKES BROWSER A BROWSER. A BROWSER MUST ALLOW QUICK BROWSING OF MULTIPLE SITES/TABS. IT MUST ALLOW FOR BOOKMARKING IMP TABS. BUT BRAVE DOESNT. I HAVE LOST 100s Of tab over brave synchain and also it doesnt *** allow exporting bookmarks. IT DOESNT ALLOW TO USE EXTERNAL DOWNLOAD MANAGER APPS FOR QUICK DOWNLOADING BUT KIWI DOES. KIWI ALLOWS FOR FINAL FILE DOWNLAOD LINK TO BE INTERCEPTED AND SEND TO DIFFERNT EXTERNAL APP FOR DOWNLOAD.**

**Comment by tathastu871** [comment]
> > @tathastu871: Clicking edit pencil should show query to edit instead of whole search engine url
> 
> Personally, I very much prefer Brave Android's current workflow/ functionality of the `Share | Copy | Edit Link` icons to quickly *manipulate the existing URL/text inside URL bar*.
> 
> Out of curiosity, I searched past requests in various Brave forums about the above, & the current functionality/ workflow is what various users previously requested.
> 
> It seems that you might be requesting to totally change the workflow to instead *manipulate the Search Term query inside Google Search engine's omnibox* -- as shown in your screen recording of Google Chrome Android.
> 
> I don't know if it is practical for Brave developers to create a new config/ flag setting just to allow users like you to choose to make Brave Android behave identically to Google Chrome/ Kiwi Browser in this aspect.
> 
> Below is what happens when I try editing the Search Term Query itself -- eg. from `wikipedia` to `wiki` -- using 2 methods, both of which are super easy.
> 
> ### Method A:
> 1. Tap on search engine's omnibox containing search query `wikipedia`.
> 2. `wikipedia` appears as a text row (prefixed with `←` blue arrow) below URL bar.
>    - To return to the original `wikipedia` search results listing instead, tap `←` blue arrow.
> 4. Tap keypad's `Backspace` to edit/ change search query term to `wiki`.
>    - OR: Tap on `wiki` related-term suggestion, which is likely to appear in listing below URL bar.
> 5. Tap keypad's `Magifier` key to start searching for `wiki`.
> 
> Not sure if you can reproduce this method, since you mentioned lagging/ crashing when you tap Google Search's omnibox.
> 
> Screenshots:
> ![Brave1.66.113-Android12-SearchEngineBox-QueryEdit-24May24](https://github.com/brave/brave-browser/assets/9943769/0256eb1b-5704-491c-91cc-7e8c954e9b4f)
> 
> 
> ### Method B:
> 1. Tap URL bar.
> 2. Whole search engine results URL gets highlighted.
> 3. Tap `X` in URL bar, or tap keypad's `Backspace` to delete URL bar's contents.
> 4. Use keypad to type in `wiki`.
> 7. Tap keypad's `Magifier` key to start searching `wiki`
> 
> 
> None of the above 2 methods causes unresponsiveness or crash in my Brave Android.
> 
> Tested in Brave Android v1.66.113 Stable with:
> - Single tab open
> - Multiple tabs (3 nos.) open & loaded
> - Brave Shields enabled
> - Autofill service disabled (never enabled, & don't intend to enable this)

OPEN >100 TABS AND THEN SAY WHETHER IT CRASHES OR NOT.

ON KIWI I HAVE 450 TABS OPENED AND STILL IT NEVER CRASHED BECAUSE IT ALLOWS FOR EASILY EDITING QUERY DIRECTLY IN OMNIBOX RATHER THAN IN WEBPAGE SEARCH  BAR. + IT HAS SEVERAL EXTENSIONS RUNNING STILL NEVER CRASH(MAY OCCASSIONALY ONCE IN WEEK THAT TOO UNDER EXTREME MEMORY CONSUMPTION + IT ALLOWS FOR IMPORT EXPORT BOOKMARKS + EXTENSION + DEVTOOLS ITSELF, OVER THE TOP THIS BROWSER IS MADE BY SINGLE DEV AND VERY FEW CONTRIBUTORS UNLIKE

**Comment by tathastu871** [comment]
ANYONE READING !!!
ITS NOT ABOUT EDITING URL , ITS ABOUT EDITING THE QUERY KEYWORDS THAT WERE PASSED TO SEARCH ENGINE.

i searched some word, browser will append keywords to ?s=query to respective selected search engine,
then i need to edit my query just some word or letter

All other browsers allow

**Comment by rafrafek** [comment]
How can I edit a Google search results URL as a URL (not keywords) in Brave on iOS?

**Comment by c933103** [comment]
Who on earth advocate and implemented this regression

When ine edit url instead of the search box on url, the key is trying to edit the url directly, not search query

for example, by adding parameters like &hl=en to specifically request English Google


The changes requested by this as implemented make such operation impossible to be carried out.

**Comment by p-mcgowan** [comment]
this "feature" is insanely annoying - please add the ability to fix this in settings. 
google search already has a search term query box you can edit at the top of the page.

i've switched search engines until hopefully a fix is available, but annoyingly custom search engines cant be set it private tabs (eg noai.duckduckgo).
i love brave and have been using it for as long as i can remember, but the last few updates have just been really bad in my opinion.

edit:
found a workaround - custom google search:
`https://www.google.com/search?q=-ai+%s&udm=web` 
personally `udm=web` (web results without the crap) and `-ai` (waste of verticle space), but maybe works without those.
and custom search works in private, just takes a bit before you can select it.

edit2: scratch that, doesnt work - still edits the query and not the url, and the issue is reproducible with other search engines.
what does work is copy url, edit url, ctrl+a ctrl+v then edit. i have a fullsize soft keyboard so at least thats easyish.
it doesnt help that clicking the address bar no longer autmatically highlights the url, but thats been broken for years so ive given up hope on that front
