### ISSUE TITLE
Bundle Brave Search favicon with the browser

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#38503]
At the moment, the browser will trigger a request to cdn.search.brave.com at startup because of the new search widget on the newtab page: https://github.com/brave/brave-core/pull/23752#discussion_r1607615853

We should ideally bundle this favicon with the browser so that this request does not take place in a default installation of Brave.

**Comment by fmarier** [comment]
@fallaciousreasoning Is the set of search engines in the newtab widget fixed? If so, I think it would be reasonable to bundle all of their favicons.

If it's possible for users to add a new search engine manually, then I think it would be fine for those custom ones to be requested on-demand at startup.

In any case, I would say that removing the startup request in the default case (i.e. Brave Search) would be worthwhile from the point of view of minimizing the number of hostnames that a new installation of Brave connects to. Some users perceive this as "phoning home" and are annoyed to see requests which aren't necessary.

**Comment by fallaciousreasoning** [comment]
It's the set of search engines from brave://settings/searchEngines - so I think it varies slightly in different regions. We can definitely add a few of the common ones, and if the users change things I guess it's on them (and no unexpected).

**Comment by fmarier** [comment]
> We can definitely add a few of the common ones, and if the users change things I guess it's on them (and no unexpected).

Sounds like a good plan.

**Comment by fallaciousreasoning** [comment]
Hey @fmarier - I'm not sure what the best approach for QA would be here

**Comment by LaurenWags** [comment]
@fallaciousreasoning @fmarier would an acceptable test plan for QA be:
1. Start up Fiddler (or similar program)
2. Launch clean profile, if search widget is not enabled on the channel, enable the flag and relaunch (don't open NTP, open brave://flags while on brave://welcome tab)
3. Open NTP
4. Confirm no call to `cdn.search.brave.com` (due to bundling icon)
5. Change search engine to one of the following from https://github.com/brave/brave-core/pull/23821/files#diff-e8276c81c90562f4034addac6fb819edfc453809c99809c87caeaf0bf0cd3bdaR14
6. Confirm no call being made to fetch favicon for selected search engine

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.68.86 Chromium: 126.0.6478.56 (Official Build) beta (64-bit)
-- | --
Revision | b4eadb4942277a3eb455fc7c3c8569185bd745af
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

![image](https://github.com/brave/brave-browser/assets/387249/467555a1-9eea-4ad3-9757-593094be2c6c)

**Comment by fallaciousreasoning** [comment]
The Ecosia one should be fixed in latest nightly :smile:
