### ISSUE TITLE
Unable to view cookies - blank page

### ISSUE THREAD

**Issue by Mejato** [brave/brave-browser#38578]
### Description

I'm unable to view cookie information under 'Site and shield settings'

### Steps to reproduce

1. View the permissions and data stored across sites  under 'Site and shield settings'
2. Select a site that has cookies.
3. Select all cookies and locally stored data for this site

### Actual result

When viewing cookies, a blank page is displayed.

![image](https://github.com/brave/brave-browser/assets/41669982/ad265a99-4872-4a3d-bf98-7ab857178676)
![image](https://github.com/brave/brave-browser/assets/41669982/872cde20-5a64-4f7e-b3ca-a40146fb70a6)

### Expected result

I expect to see the cookies.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

[Version 1.66.115 Chromium: 125.0.6422.112 (Official Build) (arm64)](https://brave.com/latest/)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by ShivanKaul** [comment]
Thanks for reporting, I can repro easily by going to brave://settings/cookies/detail?site=github.com. I know we've had similar issues in the past recently that we fixed: https://github.com/brave/brave-browser/issues/37030. 

I get a console error on the cookies pages. 

![image](https://github.com/brave/brave-browser/assets/5284154/f0b88663-9a8e-4a9d-9a9f-f3cc74cbf393)

**Comment by ShivanKaul** [comment]
@Mejato we are likely going to get rid of these pages since upstream Chromium has gotten rid of them and they are a lot of work to maintain. As a workaround, you should be able to see cookies for a site by going to DevTools > Applications and selecting the Cookies tab on the left.

<img width="847" alt="image" src="https://github.com/brave/brave-browser/assets/5284154/18815154-a190-42e1-93b8-dbef4838975f">
