### ISSUE TITLE
Install Omaha v1.3.361.151 for existing users

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#38602]
### Description

Our automatic update mechanism on Windows is implemented via a fork of Google's "Omaha" technology. Google have released several new versions. We want to pull in those improvements by releasing a new version of our copy of Omaha with the new changes.

Omaha runs as a separate application on users' systems. It gets installed when the user first installs Brave. It does *not* get updated for existing users via new versions of the browser. Instead, we need to upload a new version of Omaha to the update server. The purpose of this issue is to document and capture QA efforts for testing that everything works as expected before we do this.

This issue is a follow-up to #38597, where Omaha gets updated for *new* users. Once #38597 has hit Release and works there as expected, we should also roll out Omaha to existing users (this issue).

# Test Plan

Please follow the steps in [this document](https://docs.google.com/document/d/1GpkF7d5-kGDvofkFV3Fuupc1SAEvrL8sJF8RZ7JZU8U/edit?usp=sharing).

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit)
-- | --
Revision | fc7619ef621fe4e6a0fa8b16c718f78ffc97a861
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit)
-- | --
Revision | fc7619ef621fe4e6a0fa8b16c718f78ffc97a861
OS | Windows 10 Version 22H2 (Build 19045.4651)
```

## Case 1: Win10-x64 - machine-wide installation - `PENDING`
<details>

</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64)
-- | --
Revision | fc7619ef621fe4e6a0fa8b16c718f78ffc97a861
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

<details>
<Summary>Case 1: Win 11 x64- Machine-wide verification - PASSED</Summary>

1. Uninstall all copies of Brave and Omaha from your system. The easiest way to do this is with [Brave Manager](https://github.com/brave/brave-manager/).

2. Download an offline (“standalone”) installer for an old version of Brave on the release channel you want to test. The important point is that it should not be the latest public version. For example, at the time of this writing, the latest public Release version is `1.67.123`.  So you can for instance install version `1.67.119`. - `https://github.com/brave/brave-browser/releases/download/v1.67.123/BraveBrowserStandaloneSetupArm64.exe`

3. Disconnect from the internet to prevent accidental automatic updates.

4.  Installed Brave after clicking `Yes` at the UAC prompt with admin privileges and closed Brave

5. Check that the registry value `BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}\pv` is lower than the new Omaha version we want to test updating to. For example, it could be 1.3.361.149 when we want to test updating to `1.3.361.151`. - `1.3.361.149`

6. Write down the registry value BraveSoftware\Update\ClientState\{release channel ID}\ap. Typical values are “nightly”, “beta” and “release”. - `release`

7. Change the registry value in step 6. to “non-existent” (without the quotation marks). This assigns the browser to a non-existent channel, which prevents it from getting updated in the next steps.

8. Create the registry value `BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}\ap` and set it to `beta`. This changes the update channel for Omaha itself.

9. Connect to the internet.

10. Delete the registry value `BraveSoftware\Update\LastChecked` if it exists. - `None`

11. Run the “UA” task `BraveSoftwareUpdateTaskMachineUA{42F34154-CE97-4294-9B5C-A655A2456B2D}` in the Windows Task Scheduler. This can take 2-3 minutes. Refresh with F5 until the task status has switched back from Running to Ready.

12. Check the registry value `BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}\pv`. It should have increased to the new Omaha version. This means that Omaha was successfully updated. - `1.3.361.151`

13. Check that BraveUpdate.exe in the new version subdirectory of Omaha’s installation directory ("C:\Program Files (x86)\BraveSoftware\Update\1.3.361.151\BraveUpdate.exe") has a valid digital SHA256 signature with an expiration date not in the past and not before August 2027. (Right click -> Properties -> Digital Signatures -> sha256 -> Details -> View Certificate -> Valid from … to.) - `5/27/2024 to 8/6/2027`

The most critical thing we want to check is that the updater is not left in a broken state by the update. To do this, we will now simulate another update of the updater.

14. Change the registry value `BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}\ap` to `nightly`. 

15. Repeat steps 10. and 11. to simulate another background update cycle.

16. Check the registry value `BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}\pv`. It should have increased further. This means that Omaha was successfully updated again. (No need to check the code signing signature this time.)- `1.3.361.153`

Now we want to check that on-demand updates of the browser still work. We’ll trust that background updates work, because we just performed two of them.

17. Restore BraveSoftware\Update\ClientState\{release channel ID}\ap to its original value.

18. Open Brave.

19. Navigate to brave://settings/help. Check that this updates Brave to the latest public version. - `1.67.123`


step 2 | step 5 | step 6 | step 7 | step 8 | step 10 | step 11 | step 12 | step 13
-------- | ------- | -------- | -------- | --------- | ------ | ------- | ----- | -----
![2024-07-16_16h11_04](https://github.com/user-attachments/assets/ef912b19-a638-4abc-b409-a041426b90f4)|![2024-07-16_16h17_51](https://github.com/user-attachments/assets/02179183-3109-405d-9cd0-b864b0480357)|![2024-07-16_16h18_13](https://github.com/user-attachments/assets/005978a1-9e95-48c0-aa84-38b553c7bd91)|![2024-07-16_16h20_03](https://github.com/user-attachments/assets/99a8b267-d7a4-4d17-abcc-bcb393883a83)|![2024-07-16_16h18_34](https://github.com/user-attachments/assets/b0fe5a71-27e1-45ef-b22c-8163405ce960)|![2024-07-16_16h18_34](https://github.com/user-attachments/assets/1bfdaaa3-f4c0-43f7-bcab-a01f696241a7)|![2024-07-16_16h20_03](https://github.com/user-attachments/assets/8135162c-d733-45f2-8358-6b6205d61858)|![2024-07-16_16h20_03](https://github.com/user-attachments/assets/d4ce8780-6104-4b86-9573-c68fe220fe3d)|![2024-07-16_16h20_03](https://github.com/user-attachments/assets/3986fb0c-4f9b-47a2-b64e-1710b594f3f5)


step 14 | step 15a| step 15 b | step 16 | step 17 | step 19a | step 19b 
---- | ----- | ----- | ------ | ----| ---- | -----
![2024-07-16_17h27_11](https://github.com/user-attachments/assets/bc5da4e9-8dec-43f3-b1b4-e20c0cb28938)|![2024-07-16_17h27_11](https://github.com/user-attachments/assets/09125eee-24b6-459b-8900-5d50ef972c33)|![2024-07-16_17h27_11](https://github.com/user-attachments/assets/93995e08-2725-46d0-8455-b427625a8f32)|![2024-07-16_17h27_11](https://github.com/user-attachments/assets/9f6296a3-2892-4076-b22d-018e0b36f9e1)|![2024-07-16_17h27_11](https://github.com/user-attachments/assets/0f726067-11e4-4590-aa8d-2653b4011ada)|![2024-07-16_17h27_11](https://github.com/user-attachments/assets/839327a2-856e-47a9-ba5d-49215adbc173)|![2024-07-16_17h27_27](https://github.com/user-attachments/assets/8ecf1448-0690-4448-9a0e-11c0ba7d83fc)


</details>

<details>
<Summary>Case 2: Win 11 x64 - Per-user installation verification - Pending</Summary>

1. Uninstall all copies of Brave and Omaha from your system. The easiest way to do this is with [Brave Manager](https://github.com/brave/brave-manager/).

2. Download an offline (“standalone”) installer for an old version of Brave on the release channel you want to test - This has been tested on `1.63.174` which is the previous release to current release `1.64.x`  -  https://github.com/brave/brave-browser/releases/download/v1.63.174/BraveBrowserStandaloneSetup.exe. 

3. Disconnect from the internet to prevent accidental automatic updates.

4. Installed Brave without administrative privileges after clicked `No` at the UAC prompt and closed Brave

5. Check that the registry value `HKEY_CURRENT_USER\Software\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}\pv` is lower than the new Omaha version we want to test updating to. For example, it could be `1.3.361.147` when we want to test updating to `1.3.361.149`.  - `omaha version is 1.3.361.145` 

6. Write down the registry value `HKEY_CURRENT_USER\Software\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}\ap`. Typical values are “nightly”, “beta” and “release”.  
 -- `release` 

7. Change the registry value in step 6. to “non-existent” (without the quotation marks). This assigns the browser to a non-existent channel, which prevents it from getting updated in the next steps.

8. Create the registry value `BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}\ap` and set it to beta. This changes the update channel for Omaha itself. - `**beta**`

9. Connect to the internet.

10. Delete the registry value `BraveSoftware\Update\LastChecked` if it exists. - `none`

11. Run the “UA” task in the Windows Task Scheduler. This can take 2-3 minutes. Refresh with F5 until the task status has switched back from Running to Ready. - `BraveSoftwareUpdateTaskUserS-1-5-21-1508676441-1305706014-1385038079-1001UA{A410F257-E3B6-4EC9-A669-D00E34DB0366}`

12. Check the registry value `HKEY_CURRENT_USER\Software\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}\pv`. It should have increased to the new Omaha version. This means that Omaha was successfully updated.  - `1.3.361.151`

13. Check that BraveUpdate.exe in the new version subdirectory of Omaha’s installation directory ("C:\Program Files (x86)\BraveSoftware\Update\1.3.361.151\BraveUpdate.exe") has a valid digital SHA256 signature with an expiration date not in the past and not before August 2027. (Rightlick -> Properties -> Digital Signatures -> sha256 -> Details -> View Certificate -> Valid from … to.) - `5/27/2024 to 8/6/2027`

The most critical thing we want to check is that the updater is not left in a broken state by the update. To do this, we will now simulate another update of the updater.

14. Change the registry value `HKEY_CURRENT_USER\Software\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}\ap` to `nightly`. 

15. Repeat steps 10. and 11. to simulate another background update cycle.

16. Check the registry value `HKEY_CURRENT_USER\Software\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}\pv`. It should have increased further. This means that Omaha was successfully updated again. -`1.3.361.153`

Now we want to check that on-demand updates of the browser still work. We’ll trust that background updates work, because we just performed two of them.

17. Restore `HKEY_CURRENT_USER\Software\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}\ap` to its original value. - `release`

18. Open Brave.

19. Navigate to `brave://settings/help`. Check that this updates Brave to the latest public version. - `1.64.123`


step 2a | step 2b | step 5 | step 6 | step 7 | step 8 | step 10 | step 11 | step 12 | step 13 
----- | ----- | ------ | ------ | ------ | ------ | ------- | ----- | ----- | -----



step 14 | step 15a | step 15b|step 16 | step 17 | step 19
---- | ----- | ----- | ----- | ----- | ----

**Comment by kjozwiak** [comment]
## `Win x86` verification(s)

### `Test Case #1` - `Machine-wide` - `PASSED`

<details>

STR/Cases used for verification:

* installed `1.67.123 Chromium: 126.0.6478.126` using the standalone installer via `BraveBrowserStandaloneSetup32.exe` (ensured that the internet/network was disconnected)
* once installed, checked `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}` and ensured that `pv` was set as `1.3.361.149`
* noted that `ap` is set as `release` via `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
* changed `ap` from `release` -> `non-existent` via `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
* created a new `String Value` named `ap` and assigned it `beta` via `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}`
* once all of the above was completed, enabled the network on the VM machine
* ran `BraveSoftwareUpdateTaskMachineUA{CC393C1C-331B-454A-957A-44FE52EC6D18}` via the `Task Scheduler`
* checked `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}` and ensured that `pv` was set as `1.3.361.151`
* ensured that `BraveUpdate.exe` via `C:\Program Files\BraveSoftware\Update` has an expiry of `August 2027`
* changed `ap` to `nightly` via `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}`
* removed `LastChecked` from `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update`
* ran `BraveSoftwareUpdateTaskMachineUA{CC393C1C-331B-454A-957A-44FE52EC6D18}` via the `Task Scheduler`
* ensured that `pv` was set as `1.3.361.153` under `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}`
* restored `ap` to `release` via `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
* opened Brave and navigated to `brave://settings/help` and ensured Brave was updated to `1.61.77 Chromium: 119.0.6045.163`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|-----------------
![image](https://github.com/user-attachments/assets/dd1ab1ad-8e96-4637-86a3-b95ed841c8f4) | ![image](https://github.com/user-attachments/assets/c7db3225-a971-4bf9-a473-31b9e21366bb) | ![image](https://github.com/user-attachments/assets/c51cc3d1-163a-4d6b-a9e0-0cdb7f480f45) | ![image](https://github.com/user-attachments/assets/a59e57c8-326b-4906-9899-04b37e2be19b) | ![image](https://github.com/user-attachments/assets/62148a8b-63e5-47b8-b13d-7f04e30a6747)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|-----------------|----------------
![image](https://github.com/user-attachments/assets/199e0784-0cf5-486c-bbf3-5f0a1367d47c) | ![image](https://github.com/user-attachments/assets/a01803db-284c-4fb7-abac-4c76ed35a14d) | ![image](https://github.com/user-attachments/assets/b1689683-77db-43c0-b779-77e089127220) | ![image](https://github.com/user-attachments/assets/8eff470c-af8a-4ce0-9163-9854d5622c9b) | ![image](https://github.com/user-attachments/assets/71b1db9e-0110-4dc3-986d-1f5ce981848c) | ![image](https://github.com/user-attachments/assets/37528a9b-cd95-49aa-8629-e510cf93fb6e) | ![image](https://github.com/user-attachments/assets/f8424694-ea68-4560-ab3f-7f700cfd9561)
</details>

**Comment by mherrmann** [comment]
This is done. The new version of Omaha is being rolled out to users now. Thank you @stephendonner @MadhaviSeelam @kjozwiak!
