### ISSUE TITLE
Introduce BYOM (Bring Your Own Model) to Leo

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#38646]
### Platforms

all

### Description

> The BYOM (Bring Your Own Model) feature is a new Setting that allows users to connect their self-hosted/third-party hosted LLM(s) to Leo.

- Allow users to add custom models in settings
- Support OAI API protocol
- Show the custom model in the model selector list

Designs: https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/Leo?node-id=3237-14009

**Comment by aosdj09ad09asjda9js9** [comment]
@nullhook 

It's working okay, the only problem I can see is that you can't use Brave BYOM from another computer in a local network, you only allow `http` to be used with `127.0.0.1` and not with another local network address like: `http://192.168.1.22`.

You can't use `https` with it (Using terminal  in WIndows 11 23h2):

```
curl https://192.168.1.22:11434 
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid
```

```
curl https://192.168.1.22:11434 
Ollama is running
```

So all I could do was to open Preferences in VSCode and modify it there  to be able to use BYOM in a local network from another computer.

So the only way to do it with https and then open Preferences file and modify the "endpoint_url":  to http to make it work.

So, hope that gets improved. 

I will delete this message so hope someone got it in an email to fix the issue, because the idea is cool but running it in the same computer running Brave is not as nice as being able to have a central computer at home to do it.

Thank you and have a good day.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.69.89 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | f446f85ae826780dfae5356eeec4480c0415670c
OS | Windows 10 Version 22H2 (Build 19045.4598)
```

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.69.128 Chromium: 127.0.6533.73 (Official Build) beta (x86_64)
-- | --
Revision | 715445841b1da480bcc24c12077a6dc926951996
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.69.128 Chromium: 127.0.6533.73 (Official Build) beta (x86_64)
-- | --
Revision | 715445841b1da480bcc24c12077a6dc926951996
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```

```
