### ISSUE TITLE
Brave Shields 'Block trackers & ads' option causes weird behavior on StackOverflow

### ISSUE THREAD

**Issue by pauvictorio** [brave/brave-browser#38664]
### Description

Choosing the 'Block trackers & ads' option in Brave Shields Advanced Control menu puts a `display: none !important` CSS on the question body of StackOverflow questions

### Steps to reproduce

1. Choose 'Block trackers & ads' in the Brave Shields Advanced Control menu
2. Visit StackOverflow website
3. Click on any question

### Actual result

A `display: none !important` CSS is applied to the question body.

![image](https://github.com/brave/brave-browser/assets/79038125/86e3dafe-a146-44e7-98c7-70ef32866073)

### Expected result

`display: none !important` should not be applied to the question body.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.66.115 Chromium: 125.0.6422.112 (Official Build) (64-bit)
Revision: a168513c9c84b6ba793d5eac01c725982187aeb4
OS: Windows 11 Version 23H2 (Build 22631.3593)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by TEMP-ad** [comment]
1. go to `brave://settings/shields/filters` and check you didn't accidentally create a custom adblock rule or disable any custom list you added.
2. when you report adblocking issues, it is good that you say all regional lists you enabled, and you properly give link of the site causing issues. I searched and found this question and it said it was removed by the author for example.
3. I searched for this rule in all the lists and there is no sign of anything like that, as you can see the `.post-layout--right .s-prose, .post-layout--right > p` would be the rule being made, because that's what the browser used to select the element to apply the cosmetic filter, and it is too specific for anyone to add it unless it was intended, so it is caused by an extension or a custom list because it would be easy to spot. But it is not reproducible on my side and I have 1500+ custom rules and a custom list enabled at the moment and some regional ones... But yes, cosmetic rules add `display: none !important;` to any element being blocked.
4. Also, it would be better if you made posts about adblocking in https://community.brave.com/c/support-and-troubleshooting/ad-blocking/ rather than github anyway, you can get more help there and I doubt many people are checking issues in Github for any adblocking related issue, since it is issues about anything.
5. If anything Brave team rules are minimal so Brave usually might not break things, that means issues should be reported to Easylist or uBlock lists, and I have seen in community and adblocking category, sometimes fanboynz reports to other filter list groups for a fix.
6. Hope you get this, if you do, don't at me because I just want to help but without 'recording it' in my account, just follow the steps, checking custom lists and disable anything until you find the issue, and depending what list it is, you report it or remove it, but no default list is causing this issue, so it is not Brave, Easylist or uBlock lists.

**Comment by pauvictorio** [comment]
1. It's my absolute first time tinkering with the Brave Shields filter, and now I found what's causing the behavior. It had this custom filter `stackoverflow.com##.postcell.post-layout--right > .s-prose.js-post-body > p`. Now what's bugging me is how it got there in the first place since you have to be very deliberate, clicking very specific buttons, in order to add that very custom filter (Right click > Brave > Block element > Locate the element > Click Create).
2. The behavior was occurring in all Stack Overflow questions, so I thought a screenshot would suffice.
3. Indeed I thought too that it was too specific, so I asked first on Meta Stack Exchange [(post here)](https://meta.stackexchange.com/questions/400305/question-body-not-displayed-on-so-when-viewing-a-question-with-the-brave-browser) thinking it was about Stack Overflow's issue, and someone suggested to report it here so I followed suit, not knowing any better.
4. ^
5. Gotcha, thanks.
