### ISSUE TITLE
What are the advantages in privacy of Brave browser over ungoogled-chromium project?

### ISSUE THREAD

**Issue by lluke777** [brave/brave-browser#3866]
What are the advantages in privacy of `Brave browser` over `ungoogled-chromium project`?

**Comment by Techguyprivate** [comment]
I am gonna write just one, but big. Updated frequently, fast, early & quickly.

**Comment by lluke777** [comment]
OK. Thank you for clarifying.

**Comment by Techguyprivate** [comment]
Also it is completely open source just like ungoogled chromium . Great for both privacy and security.  It has sync feature just like in Mozilla, end to end encrypted, so that brave can't see your passwords, bookmarks, history, tabs etc. It is founded by former Mozilla CEO & founder , who created JavaScript too. So a lot of credibility, experience, trust , whatnot. Most importantly , it respects privacy at the same time saving& serving the internet. Brave advertisements are secure &private. That means no adware, malware, clickbait hijacking hidden under ads. It gives the power to you as said by in brave's homepage , you are the product. So brave gives you BAT for your time & attention.


More about BAT.




https://basicattentiontoken.org/

https://brave.com/faq/#new-system

**Comment by bsclifton** [comment]
@Techguyprivate definitely interested to see what you put together - please ping me or another Brave employee

@lluke777 we have a page here which needs to be updated, but it basically captures a chunk of the ways we deviate from Chromium. Any core services (something that would reach out, like safe browsing, etc) we intend to proxy in a way that preserves anonymity. 
https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)

As @Techguyprivate said, we also have a fairly aggressive release schedule which you can check out here:
https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule

**Comment by rebron** [comment]
Closing. Not a product issue.
