### ISSUE TITLE
Telegram unresponsive on Brave

### ISSUE THREAD

**Issue by littleboy0k** [brave/brave-browser#3874]
A user on r/BATProject reported that he is facing issues using telegram web on Brave Browser.

> I have started to use Brave as my default browser for about a week now, and I just love it, although I have some problems while using telegram, when I try to open telegram links of groups I want to join, it doesn't open, the page turns unresponsive. I can open telegram chat page and enter chats I am already a part of, but I can't view new groups... and it is frustrating. Anyway around this?

> https://www.reddit.com/r/BATProject/comments/b4icqz/brave_browser_and_telegram/

**Comment by ryanbr** [comment]
Okay, I'm trying to reproduce this.  From what I see, the tg:// links need an Application to bind too?

`Firefox doesn’t know how to open this address, because one of the following protocols (tg) isn’t associated with any program or is not allowed in this context.`

Which allows brave and firefox to open the windows client. I'm not sure how to open group messsage via the website.  https://t.me/joinchat/AAAAADzgf1Apzuxhk50ogA points to tg://join?invite=AAAAADzgf1Apzuxhk50ogA

Just need some guidance on how someone would pass a "tg://join?invite=AAAAADzgf1Apzuxhk50ogA" link into the web client.

**Comment by ryanbr** [comment]
Just tested this, 

1. Installed Telegram desktop app (windows)
2. Refresh the page
3. Brave suggested to open link in Telegram
4. Telegram launches and opens into chat.

Seems to be okay / resolved? I'll try to reach out the orginal poster.

**Comment by ryanbr** [comment]
Works for me, no response from orginal poster. We can re-open if its an issue.
