### ISSUE TITLE
Migrate channel from dev to beta / release

### ISSUE THREAD

**Issue by scottf007** [brave/brave-browser#3875]
Hello, 

I have been using this version of brave for what seems like a year. I am currently on Dev - but it seems as though I have not had major problems for a very long time. I would like to change my channel to Beta while keeping all my browsing history / open tabs etc. 

Is there this ability?Can we make it? 

Not that it should matter, but I am on windows and love your product.

**Comment by bsclifton** [comment]
@scottf007 there's not an official way to do it- but I can offer a work-around that you may try

On Windows, your profile data for the DEV channel should be at:
`%PROFILEDIR%\AppData\Local\BraveSoftware\Brave-Browser-Dev`

You can make a copy of that folder (so that you don't lose anything) and rename the copied folder as `Brave-Browser-Beta`

This *should* work most of the time. There can  be problems when DEV is on a different Chromium version than BETA is.  Please let us know how this works if you give it a try 😄 

cc: @Brave-Matt
