### ISSUE TITLE
[trusted-]replace-node-text scriptlets operate on themselves first

### ISSUE THREAD

**Issue by Yuki2718** [brave/brave-browser#39116]
https://github.com/gorhill/uBlock/wiki/Resources-Library#trusted-rpntjs-
And thus new rules for yt's SSAP ads don't work on Brave. Probably other varargs and tokens should be checked to ensure compatibility with uBlock filters.

Edit (@ShivanKaul): we investigated and found the real reason why `sedCount, 1` doesn't work: https://github.com/brave/brave-browser/issues/39116#issuecomment-2174408736.

**Comment by antonok-edm** [comment]
After some investigation, it appears that the `script` tag in the DOM that was injected to execute the scriptlet logic is being replaced by the scriptlet logic. i.e. the scriptlet is replacing itself.

It's unclear how uBO doesn't run into this issue, since they also use the same injection method of creating a `script` tag, appending to the `head`, and immediately removing it. I assume it's because Brave can inject at an even earlier stage than uBO on Chromium. We probably don't want to change that since it does improve our reliability in many cases.

There's no immediately obvious fix for this. A check for `document.currentScript` in the `trusted-rpnt` scriptlet itself might be helpful, but can we get it accepted upstream? As a workaround, having no `sedCount` (or setting it to 0) will avoid the issue by applying to every script on the page, or otherwise incrementing it by 1 will cause it to deal with the injected scriptlet before proceeding with the normal iteration count.

**Comment by gorhill** [comment]
> +        if (node === document.currentScript) {
> +            return true;
> +        }

This doesn't work for when `handleNode` is called from within the mutation observer, does it?

**Comment by antonok-edm** [comment]
Should be fixed as of `Brave Ad Block Resources Library - Version: 1.0.91` in `brave://components` as of https://github.com/gorhill/uBlock/commit/cb0f65e035e4cd40b0127079ff1fca76ee964fa0.

Thanks again for reporting! Let me know if y'all see any other issues with this.
