### ISSUE TITLE
Youtube showing incomplete webpages

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#39296]
### Description

Recently we've seen increased reports of Youtube not properly rendering the webpage, only showing video with no other Youtube elements (comments/ratings etc)

### Steps to reproduce

1. On IOS, opening m.youtube.com
2. Expect whole page to render, just only video
3. Missing elements showing

### Actual result

![image_from_ios (5)](https://github.com/brave/brave-browser/assets/1659004/b63867e7-dd5a-4830-8ec7-05de6de49bfc)

### Expected result

Show Youtube proper including comments etc.

### Reproduces how often

Intermittent issue

### Brave version

Brave 1.66.2 (iphone)

### Device/iOS version

iphone 15 or any?

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Probably related to Playlist.  Multiple refreshes may get past this issue. We have seen an increase of user reports over this and community posts.

https://community.brave.com/t/brave-updated-youtube-issues/554761
https://old.reddit.com/r/brave/comments/1dmc497/youtube_glitch/l9uti37/

**Comment by ShivanKaul** [comment]
It seems like there was a server-side YouTube change in the last two weeks that interacted badly with our [Request Blocking Script](https://github.com/brave/brave-core/blob/master/ios/brave-ios/Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/RequestBlockingScript.js) on iOS and caused YouTube to start spamming network requests.

While watching a video on [m.youtube.com](http://m.youtube.com/), the page writes a log event to LogsRequestStore IndexedDB. Separately, the page tries to read all the events from LogsRequestStore and makes network requests to https://m.youtube.com/youtubei/v1/log_event and when it gets back a result, removes the event from the IndexedDB. We have been blocking that https://m.youtube.com/youtubei/v1/log_event request for a long time with the filter rule ||[youtube.com/youtubei/v1/log_event](http://youtube.com/youtubei/v1/log_event) in the [Request Blocking Script](https://github.com/brave/brave-core/blob/master/ios/brave-ios/Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/RequestBlockingScript.js) by monkey-patching XMLHttpRequest.prototype.send and dispatching an error ProgressEvent [when we want to cancel a network request](https://github.com/brave/brave-core/blob/master/ios/brave-ios/Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/RequestBlockingScript.js#L100-L106). It looks like YouTube’s JS (now) only handles loadend ProgressEvents and not error events and because our script never emits the loadend ProgressEvent, YT’s JS never receives a response for that XHR and so it never clears the event from the DB. This causes the DB to keep filling up with log events. On refreshing the page, YT goes through the entire DB and tries to execute all the network requests. This is why the issue gets worse and worse with time. Once we figured this out, [we were able to ship the exception rule](https://github.com/brave/adblock-lists/pull/1839/files) that disabled that adblock rule and stopped blocking the spammy network request.

There’s a few follow-ups here:
1. Fix the Request Blocking Script to be able to emit error events for all possible event handlers.
2. See if we can get rid of Request Blocking Script on [m.youtube.com](http://m.youtube.com/). I don’t think we can get rid of the script entirely since we would miss ads & trackers but we can perhaps drop it on youtube and instead rely solely on content blockers there.
3. Cache request blocking calls. [This is done already](https://github.com/brave/brave-core/pull/24334) and will ride the trains from Nightly -> Beta -> Release.
4. Have an easy way for users to update all filter lists in iOS once we fix an issue, like we do on Android/Desktop: https://github.com/brave/brave-browser/issues/35982
