### ISSUE TITLE
Add an X to close this VPN informational screen

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#39333]
### Description

Please add an X to the top right of this screen to provide users with a visual cue on how to close the screen.

<img width="347" alt="Screenshot 2024-06-24 at 4 14 11 PM" src="https://github.com/brave/brave-browser/assets/7606853/6d6a8d50-f24a-47db-bbee-9c901a35dc1d">

### Steps to reproduce

1. NA
2. 
3. 

### Actual result

NA

### Expected result

NA

### Reproduces how often

Easily reproduced

### Brave version

NA

### Device/iOS version

NA

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.70 (123)
BraveCore: 1.70.123 (129.0.6668.89)
```
---------------------------
<details>
<summary> "Help make Brave better." message </summary>

**STEPS:**
1. Install Brave > Don't launch it yet
2. Open `X` app or `Reddit` > Share any post via `Brave`
3. Close Brave
4. Share another post via `Brave` > *Verify *
5. Tap `X` button > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Help make Brave better.` pop-up message with the `X` button is shown.
- Verified that `X` button works as expected and closes the pop-up message.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/1328650b-ec54-4f51-b9c6-24e9d8715a23) | ![2](https://github.com/user-attachments/assets/d36e64eb-3286-4ffe-855d-32eb654dcf50) |
</details>

<details>
<summary> "Brave Firewall + VPN" message </summary>

**STEPS:**
1. Install and launch Brave
2. Go through onboarding > Close Brave
3. Change the device date to 4 days since Brave installation
4. Launch Brave > Open any website > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Brave Firewall + VPN` pop-up message with the `X` button is shown.
- Verified that `X` button works as expected and closes the pop-up message.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/ad176301-8286-43d8-80d9-5641d37c1a0d) | ![2](https://github.com/user-attachments/assets/04d59f4d-dc5c-429e-bb9b-1ebe7f479a24) |
</details>
