### ISSUE TITLE
`--variations-server-url` switch not working (always pointing to `production`)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#39400]
### Description

The `--variations-server-url` switch has stopped working recently, You'll notice when launching `Brave` using `--variations-server-url=https://variations.bravesoftware.com/seed`, it will still pull the `production` seed/variation list rather than `staging`. A good way of checking this is pointing `Brave` to `--variations-server-url=https://variations.bravesoftware.com/seedFake` and you'll notice that `brave://version` is still listing a list of studies/variations even though you're pointing to an incorrect end-point. Good indicator that the switch has regressed/isn't working as expected.

Reproduced on `Linux`, `macOS` & `Windows`.

### Steps to reproduce

1. download/install https://github.com/brave/brave-browser/releases/download/v1.69.55/BraveBrowserStandaloneNightlySetup.exe
2. once `Brave` launches/close the application and remove `AppData\Local\BraveSoftware\Brave-Browser-Nightly`
3. re-launch `Brave` using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seedFake` and then close the browser
4. restart once more using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seedFake`
5. check `brave://version` and notice that the variation studies from `production` are being listed/displayed

Nothing should be displayed due to `--variations-server-url=https://variations.bravesoftware.com/seedFake` pointing into an incorrect end point. Same issue happens when pointing to `staging` via `--variations-server-url=https://variations.bravesoftware.com/seed`

### Actual result

As mentioned above, `Brave` will always use the `production` variation list even though `--variations-server-url=https://variations.bravesoftware.com/seed` is being used.

### Expected result

Using `--variations-server-url=https://variations.bravesoftware.com/seed` should pull/download the `staging` variation list rather than always using `production`. This makes it impossible to verify Griffin on `staging` before we push into `production`.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.69.51 Chromium: 127.0.6533.17 (Official Build) nightly (64-bit)
-- | --
Revision | 8f43b9af539c59840245a61887d5447733d76af5
OS | Windows 11 Version 23H2 (Build 22631.3810)
```

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.68.109` or higher for `1.68.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.114 Chromium: 127.0.6533.26 (Official Build) beta (x86_64)
-- | --
Revision | 1eae2f949cf44b11030e6abb82a7b72f010538b1
OS | macOS Version 13.6.7 (Build 22G720)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.68.114 Chromium: 127.0.6533.26 (Official Build) beta (64-bit)
-- | --
Revision | 1eae2f949cf44b11030e6abb82a7b72f010538b1
OS | Windows 11 Version 23H2 (Build 22631.3810)
```

##### `Test Case #1` - Using `standalone` executable (`production`)

* installed `1.68.114 Chromium: 127.0.6533.26` and ensured that there's no studies being displayed via `brave://version`
* restarted `1.68.114 Chromium: 127.0.6533.26` and ensured that the variations/studies are being listed under `brave://version`

**`First Launch`** | **`After Restart`**
----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/98358127/9bdbdb22-683e-4d3d-8093-52456f2f779a)|![image](https://github.com/brave/brave-browser/assets/98358127/52cf0323-b5b5-40d1-89a8-8f495c53fd4a)


##### `Test Case #2` - Using `standalone` executable via `--variations-server-url=https://variations.bravesoftware.com/seedFake`

* launched ``1.68.114 Chromium: 127.0.6533.26`` using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seedFake`
* ensured that there's no variations/studies being listed under `brave://version`
* restarted ``1.68.114 Chromium: 127.0.6533.26`` via `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seedFake`
* ensured that there's no variation/studies being listed under `brave://version` due to using an incorrect end point

**`First Launch`** | **`After Restart`**
----------------|-----------------

**Comment by btlechowski** [comment]
Verified with

Brave | 1.68.115 Chromium: 127.0.6533.26 (Official Build) beta (64-bit)
-- | --
Revision | eb9eb125805c393d370bb000a19164da9f344726
OS | Linux


#### staging

Verified staging seed is used:

![image](https://github.com/brave/brave-browser/assets/34715963/9af2dff4-607b-4861-ab9b-2212e38d7fc8)|![image](https://github.com/brave/brave-browser/assets/34715963/9507b089-43fe-42e3-8e65-cc813e73865f)
--|--



#### production

Verified production seed is used:

![image](https://github.com/brave/brave-browser/assets/34715963/3be8b6ae-3194-4bb9-bce9-37ae78a38b7d)|![image](https://github.com/brave/brave-browser/assets/34715963/2a03ce30-ca73-4cfc-b080-067b0ebf93fe)
--|--

#### invalid

Verified no seed is used

![image](https://github.com/brave/brave-browser/assets/34715963/627f0bbd-cc28-4e73-84b5-0861d6996a4d)|![image](https://github.com/brave/brave-browser/assets/34715963/e1504756-d8ba-4206-bd96-a39821df7503)
--|--
