### ISSUE TITLE
Leo Header - Change settings icon

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#39460]
### Description

I'm changing the settings icon cog to use the 3 horizontal dots, so it matches more of the OS level menues.

Design:
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=4492-37463&t=61gqSMJDJE77LUQg-1

### Steps to reproduce

---

### Actual result

<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/f792cbac-e874-4e83-9da3-b708f0983888">

### Expected result

<img width="506" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/454aca3e-961e-4846-ae9e-4d317574e384">

### Reproduces how often

Easily reproduced

### Brave version

----

### Device/iOS version

---

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.68.112` or higher for `1.68.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` and `iPad (7th Gen)` running iOS 17.5.1 using version 1.68.115

- Ensured that settings icon is changed to 3 horizontal dots instead of the cog.
- Ensured menu opens/closes when tapping on the dot icon. 
- Ensured that menu opens in different orientations and app switcher can be used with the Leo menu open. 

Example | Example 
-|-
![IMG_6707](https://github.com/brave/brave-browser/assets/17885425/27d2b6e1-d023-44e5-a4be-8c50ad89ffbc) | ![IMG_1492](https://github.com/brave/brave-browser/assets/17885425/5fca0702-4290-4ce3-9412-cfbb82c65b72)
![IMG_6734](https://github.com/brave/brave-browser/assets/17885425/8423782c-b760-476e-8d70-b5d3b13449f2) | ![IMG_1491](https://github.com/brave/brave-browser/assets/17885425/41ac49d7-f6a2-4e3b-9dc5-e16c9ba25e27)
