### ISSUE TITLE
The resolution of favorite websites' icon istoo low

### ISSUE THREAD

**Issue by 7aRanchi** [brave/brave-browser#39751]
### Description

The resolution of favorite websites' icon istoo low,looking so bad.
duckduckgo browser does better.
Is there any way to solve this problem?
![屏幕截图 2024-07-15 170824](https://github.com/user-attachments/assets/a5f3334f-2dcc-4048-b114-9d802ef64ea7)
![屏幕截图 2024-07-15 170839](https://github.com/user-attachments/assets/9a506107-f14a-4b61-a07f-eec1aaff0948)

### Steps to reproduce

1. open the browser
2. add any website to favorite
3. go to home page to check out the ugly icons
4.

### Actual result

icons' resolution are too low

### Expected result

make it more beautiful

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.123 Chromium: 126.0.6478.126 (正式版本) （64 位） 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
@7aRanchi Dupe and we have a fix for this here: https://github.com/brave/brave-browser/issues/38183
The fix is in beta https://brave.com/download-beta/ and will show up in a couple weeks in Stable/Release channel with version 1.68.x 

If you want to give it a test run in beta, let us know what you think. You Stable/Release channel and Beta run on separate profiles and you can use them independently.

**Comment by rebron** [comment]
Closing as dupe.
