### ISSUE TITLE
General sync issues / Cross - platform

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#3978]
## Description 

Creating an issue where we can link to reviews or feedback from users that have sync issues. 

Often users don't provide too much info so it will be hard to troubleshoot. 

---

> I'm having issues Syncing all my devices. I have two Windows 10 PC's which refuse to Sync unless they start the sync chain. Two Android devices and a third Windows 10 PC have no issues syncing. Update: Same issue after update, but now bookmark shortcut changed

https://appfigures.com/reviews/266342430751LzMqRLxy4v3w4SZOpoIRpow

**Comment by rebron** [comment]
@srirambv can you take a look? lots of devices btw. 
@anthonypkeane in future we need reproducible steps, easier for QA.

**Comment by anthonypkeane** [comment]
Another one here: https://community.brave.com/t/sync-has-stopped-and-no-longer-syncs/49651/2
As I mentioned ^^, users won't provide that detailed info @rebron

**Comment by Brave-Matt** [comment]
Some more reports:
https://community.brave.com/t/desktop-sync-error-couldn-t-contact-sync-servers/50543
https://community.brave.com/t/brave-sync-is-really-buggy/48125
https://community.brave.com/t/desktop-sync-error-couldnt-contact-sync-servers/44272/16
https://www.reddit.com/r/brave_browser/comments/bb9vg8/android_sync_keeps_disappearing/
https://www.reddit.com/r/brave_browser/comments/bcdej5/sync_windowsmacos/

**Comment by rebron** [comment]
I'm not sure what we're doing with this particular ticket. Any issues that we file should be reproducible/actionable. A tally of positive/negative feedback we can track elsewhere? 

What's the next step when we compile a long list of unreproducible feedback issues? Those individual reports should be handled via support, investigated further to be filed as separate issues, or duped against existing issues. If we can't get any further information from the user, don't have any next steps, only a tally of feedback. 

https://github.com/brave/brave-browser/projects/14

**Comment by Gaeger** [comment]
I also have a similar issue. Syncing between my private devices works fine. If I add a device in my company to the sync chain, the sync only works for initial. After that new changes (adding/removing bookmarks) do not sync. I also can't remove the device from the sync-chain! It just shows the endless loading windows:
![image](https://user-images.githubusercontent.com/49043555/56197839-fae19180-6039-11e9-9867-9dea3c3694dc.png)
So I have to completely remove brave from my device for disabling sync. But other devices still think that the faulty device is connected and can't be removed because the remove request isn't processed/accepted by the faulty device.

Suspect reason: The proxy server by the company
And I don't have access to this part of the network. So I can't check what is blocked or different to the initial sync.

**Comment by Gaeger** [comment]
Updates to the last post:
After a while the faulty device has been removed from the sync chain (by removing on my Android). But the faulty device still thinks it is part oft the chain.

**Comment by HennyBro** [comment]
I have 2 Windows 10 PCs and one first-gen Pixel XL running Android 10.0 Q BETA 2. When I was on Pie I had the same error: Every time I try to create a new Sync chain with my new Windows 10 laptop it fails. It will either not show me the encryption/decryption code or it just won't do anything after I scan the bar code with my phone or type in the correct code text...

So, to bring this on point: I had successfully created a sync chain to my Pixel XL with my old Windows 10 PC when it was still running Android 9.0 Pie. But also back then it failed to create a sync connection with my Windows 10 laptop. I think that is, because it only allows me to add new devices from the "mother ship device" (in this case my old Windows 10 PC), but doesn't allow my Pixel XL to add another device. I'll try to verify this theory later this day.

Hope this helped :)

**Comment by LaurenWags** [comment]
Info being gathered in this thread: https://twitter.com/dkxkee/status/1149352270942887937

**Comment by Jaydon2908** [comment]
I am trying to sync my android phone to my windows 10 browser but entire folders are missing and the support isn't helping me, I was told to come here to get help, is that true?
