### ISSUE TITLE
Try both RFC and Chromium URL parsing in Debouncer

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#39866]
### Description

When checking that the destination URL is valid, we currently use the Chromium URL parser. We should use both the Chromium parser (following the WHATWG spec) and a URL parser which follows the RFC spec.

If the resulting URL has a different hostname depending on the parser, then we can reject the URL.

### Steps to reproduce

See https://hackerone.com/reports/2610290 for a sample test case.

### Actual result

See above.

### Expected result

Edge cases should not be debounced.

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

```
Brave	1.68.117 Chromium: 127.0.6533.26 (Official Build) beta (64-bit) 
Revision	80857ef16345e7959abe655afdebf9521f5109aa
OS	Linux
```

### Android device

(not tested)

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by thypon** [comment]
It should be enough to test for the `host` be the same, to block wrong redirects here

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.54 Chromium: 127.0.6533.100 (Official Build) nightly (x86_64)
-- | --
Revision | 30140ea3aefda98e32ddd4daa2309ca5eb273f64
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.70.54`
2. launched Brave
3. restarted (to pick up component updates and Griffin-seed updates)
4. opened `Developer Tools`
5. loaded `https://go.redirectingat.com/?url=http%3A%2F%2Fevil.com%5C%5C%40apps.apple.com`
6. waited

### Confirmed `https://www.apple.com/app-store/` loaded instead of `evil.com`

example | example
---------|---------
<img width="1798" alt="Screen Shot 2024-08-07 at 6 10 19 PM" src="https://github.com/user-attachments/assets/df2abfeb-db8b-40f9-90b1-735170e1d70c"> | <img width="1798" alt="Screen Shot 2024-08-07 at 6 12 40 PM" src="https://github.com/user-attachments/assets/f3e19911-4748-4cd8-bb48-766f1fc22952">

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.70.100 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | c30694e8a60583be9d1784e4d42b4a0b94c70ab5
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave	1.70.110 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	7dec99ca278e09ce2087e9f04914f0aa2507ea4c
OS	Linux
```
Verified the test plan from https://github.com/brave/brave-core/pull/24964

Confirmed that `https://go.redirectingat.com/?url=http%3A%2F%2Fevil.com%5C%5C%40apps.apple.com` redirects to `https://www.apple.com/app-store/` instead of evil.com
![image](https://github.com/user-attachments/assets/2fc7a075-16db-4d37-b9a9-38eeb19a225e)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` running `Android 13` using version `1.70.113`

- Verified test plan in https://github.com/brave/brave-core/pull/24964
- Ensured that URL is redirected to `https://www.apple.com/app-store/`

![Screenshot 2024-09-16 at 11 08 07 AM](https://github.com/user-attachments/assets/3542c438-1b8c-48e4-8603-eb53ac7dbd6f)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` running `Android 13` using version `1.70.113`

- Verified test plan in https://github.com/brave/brave-core/pull/24964
- Ensured that URL is redirected to `https://www.apple.com/app-store/`

![Screenshot 2024-09-16 at 11 44 46 AM](https://github.com/user-attachments/assets/0cdf1b2c-ddd9-4c7b-895e-d94ba6627f71)

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7
- iPad Air / iPadOS 16.7.2
Brave build: 1.70 (115)
BraveCore: 1.70.115 (129.0.6668.59)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/24964#issue-2442657481
2. *Verify*

**ACTUAL RESULTS:**
- Verified that opening https://go.redirectingat.com/?url=http%3A%2F%2Fevil.com%5C%5C%40apple.com redirects to `apple.com`

---------------------------

`iPhone 14`

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/631cbf45-e557-4942-a3fe-3a7ae195fdff) | ![2](https://github.com/user-attachments/assets/1be4c305-df80-471a-80b1-ba5f19d29817) |

`iPad Air`

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/8734e28d-7047-46eb-b033-6afeb37a5eab) | ![2](https://github.com/user-attachments/assets/465dbc2c-b5de-45a6-8a65-393762e75e03) |
