### ISSUE TITLE
Ads Rewards grants should trigger BAT icon badge (Rewards notification badge)

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#3989]
If an Ads user (Ads ON) receives their ads rewards payment, the BAT logo should show the notification logo so user know ads rewards payment is available to be made, and needs to be claimed.

@jsecretan @NejcZdovc

**Comment by ryanml** [comment]
Posting my comment from the issue I originally made: 

Really, this is occurring because no checks are happening while the user is idly browsing. (Currently it will happen if the user opens the Rewards Settings page or the Rewards panel)

Grants should be fetched inside the existing 24 hour notification interval inside `rewards_service_impl.cc` here: https://github.com/brave/brave-core/blob/master/components/brave_rewards/browser/rewards_service_impl.cc#L2414

In this case then, the longest the user can go without seeing the notification bubble if they don't open any Rewards features at all would be 24 hours.

**Comment by mandar-brave** [comment]
@ryanml point taken.
However, there is a significant different in grants and ads rewards. Ads rewards needs to be more proactive than accepting grants since the users have earned them.
Would love to see a change that enables a scenario - ok for a few hours, 24 sounds extremely long.

cc @jsecretan @NejcZdovc

**Comment by ryanml** [comment]
Per the above ^ grants are now set to check every 3 hours

**Comment by mandar-brave** [comment]
@ryanml if the 3 hour check is all the time vs. when the ads rewards claims are expected, i would move it back to 24 hours -- it will be too often, too aggressive. 

cc @NejcZdovc

**Comment by mandar-brave** [comment]
Lets revert this back to original 24 hour check.
cc @ryanml @NejcZdovc

**Comment by ryanml** [comment]
@mandar-brave - The PR has been reverted back to the 24 hour check

**Comment by ryanml** [comment]
The above fix has been merged in to `0.65.x, 0.64.x, and 0.63.x`

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2156 (caught the notification in the 30s after browser opened)
![Screen Shot 2019-04-18 at 7 22 50 PM](https://user-images.githubusercontent.com/28145373/56397863-0dafbe00-6214-11e9-8635-11db0f562cce.png)
