### ISSUE TITLE
Request for clean url chrome extension like feature to implemented in brave browser

### ISSUE THREAD

**Issue by subham8907** [brave/brave-browser#40254]
### Platforms

all

### Description

Dear brave browser team please implement clean url chrome extension feature in brave browser after full implemention of mv3 cleanurl will not work in brave browser requested your team to implement clean url like feature implemented in brave browser 
https://github.com/ClearURLs/Addon

**Comment by subham8907** [comment]
https://github.com/ClearURLs/Addon

**Comment by kenherbert** [comment]
Brave already does strip many known tracking parameters from URLs, and is the reason why when you right-click a link there is an option to copy the link, or copy the clean link.

**Comment by subham8907** [comment]
But we clean urls extension allowed to use coustom rules

**Comment by fmarier** [comment]
As @kenherbert said, this is already built-in in two ways:
- parameters which track users are removed automatically: https://github.com/brave/brave-browser/wiki/Query-String-Filter
- unnecessary parameters are removed when copied to the clipboard: https://github.com/brave/brave-browser/wiki/Copy-clean-link

If you find any URLs with parameters that are missing from our lists, you can file an issue for us to add to our lists. We don't copy blindly from other lists since many of them have outdated entries, but we grateful for reports from our users of URLs they have seen in the wild with extra unnecessary parameters.

In addition, users who want more control over what gets removed can add a custom list such as the [AdGuard URL tracking filter](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt) to `brave://settings/shields/filters`.
