### ISSUE TITLE
Opening vizzy.io will generate errors in Brave

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#40440]
### Description

2 issues, Fingerprinting and Anti-Brave messaging

### Steps to reproduce

1. Open https://vizzy.io/editor?project=OwKSRJGW4LQua7adLAtHk
2.  Get past Brave warning
3.  Play Music. Only comes out of one speaker.

### Actual result

Mono audio playback

### Expected result

Allow audio to play correctly in stereo

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

affects all

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Disabling `Audio `fingerprinting helps.

**Comment by ryanbr** [comment]
Leaving open until this is live in Brave release

**Comment by iGerman00** [comment]
One of the Vizzy developers chiming in here. We have received many reports about Brave not being functional with our site, including one today of a Brave user who was confused as to why their audio was broken. We have received dozens of such reports in the past, alongside reports of other parts of the site being broken due to Shields.

Given Brave's strong emphasis on privacy, which is warranted through selective blocking of various site parts, and the complex number of dependencies and variables on our site, we do not offer dedicated support for Brave users and simply advise them to use something else. We expect Brave users to be aware of these potential issues and know how to resolve them given their choice of a browser. Evidently, this expectation is not always met.

To clarify, our site includes a clear and direct option in the warning message that allows users to dismiss it. This warning does not prevent access to our site but does serve to inform users about the issues.

We must also note that the latest changes to the ad-blocker list have _already_ disabled the Brave warning, but in our testing, have not rectified the problem mentioned in said warning. This has already led to confusion among users, I suspect since the proposed Audio 'fingerprinting' opt-out changes are either not live yet or not functioning as intended. Please be careful about pushing these changes out of sync.

Regardless, thank you for the issue report and effort to rectify the situation. We will remove the Brave warning completely if we can verifiably test that no issues arise using the default settings.

**Comment by ryanbr** [comment]
The fix will roll out in the next few days, once confirmed fix. Will be safe to remove the anti-Brave message

**Comment by ryanbr** [comment]
Now fixed, audio is in stereo on playback.

**Comment by iGerman00** [comment]
Another user reported issues with Brave today while using Vizzy, audio reaction simply didn’t work. We might return documentation or other messaging discouraging users from using Brave (or at least Shields) with our sit, as this is not the first time even since this fix was pushed.
