### ISSUE TITLE
help users understand that fingerprinting protections manu does not imply a fingerprinting attack

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#40488]
### Platforms

Linux, macOS, Windows

### Description

Two changes:
1. Change number next to "Block fingerprinting" to an arrow
2. Add text like "Use of these features does not necessarily indicate fingerprinting."
3. Make sure text on https://support.brave.com/hc/en-us/articles/360022806212-How-do-I-use-Shields-while-browsing#h_01HXSZ8JPHR8YMBEZCT5M0VZTR correctly reflects the message in (2)

**Comment by arthuredelstein** [comment]
QA testing:

- There should be a "right arrow" not an integer, displayed next to Block fingerprinting in the advanced shields menu
- There should be some new text in the fingerprint webcompat side menu, looking something like this: 
![image](https://github.com/user-attachments/assets/46a9a64e-1866-4310-94f2-ab8c29929dfa)

**Comment by LaurenWags** [comment]
@brave/qa-team please ensure this one gets checked on Windows 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

New Install

1. Installed 1.71.112
2. launched Brave
3. relaunched Brave to pull in griffin
4. visited browserleaks.com in a new tab
5. clicked Shields icon >> Advanced controls
6. confirmed arrow is displayed instead of number to `Block fingerprinting`
7. confirmed integer is displayed when hovered over the arrow
8. confirmed new header label and new text below is displayed and matched to the mockup 
      - 8 anti-fingerprinting protections applied
      - Applied protections do not necessarily indicate that this web page is attempting to fingerprint your browser.
9. disabled and enabled the `font` toggle    - Confirmed webcompat toggle sidepanel show ` 1 anti-fingerprinting protections applied`
10. Confirmed webcompat toggle works as expected

step 6a (1.70.x)| step 6b(`1.71.x) | step 9
-----  | ------ | ------ 
![Image](https://github.com/user-attachments/assets/d5be40de-f494-4b91-b722-da69ea66fcba)|![Image](https://github.com/user-attachments/assets/c6616b73-40f8-4361-8c46-d2d6c64bf433)|![Image](https://github.com/user-attachments/assets/c9ead6b7-1287-4762-a193-1ff5f1bd0b2b)
