### ISSUE TITLE
Ship default-disabled Omaha 4 with Brave on macOS (per-user)

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#40528]
We're switching to a new auto-update implementation on macOS. At the moment, we are using the Sparkle Framework. In the future, we want to instead use upstream's new Omaha 4 (aka. Chromium Updater).

The goal of this issue is to embed Omaha 4 in Brave with a default-disabled Griffin flag. When the flag isn't set, then Brave should behave exactly as before, particularly when it comes to updating. But when the flag is enabled on the command line via `--enable-features=BraveUseOmaha4`, then Brave should install and check for updates with Omaha 4.

This issue is about per-user installations of Brave. That's the typical case when Brave was installed from the DMG file. To check whether it's a per-user or a system-wide installation, you can check the ownership of the installation directory. For example:

```
michael@Michaels-iMac-Pro ~ % ls -alh /Applications/Brave\ Browser.app 
total 0
drwxr-xr-x@  3 michael  admin    96B Aug  7 08:13 .
drwxrwxr-x   9 root     admin   288B Aug 19 13:04 ..
drwxr-xr-x@ 11 michael  admin   352B Jul 31 10:24 Contents
```

The `michael` parts, where `michael` is my username, indicate that this is a per-user installation.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (arm64) 
Revision	5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS	macOS Version 15.1 (Build 24B82)
```


Verified test plan from https://github.com/brave/brave-core/pull/25190#issue-2473176320.

<details>
<summary>Existing functionality with Sparkle - InProgress</summary>

Note, per discussion with Michael confirmed that we don't need to test updating from every permutation (universal dmg, universal pkg, architecture specific dmg, architecture specific pkg) in each case. We can use different combinations for each case to cover the different installer types. This is reflected in my notes below.

<details>
<summary>1. Check background updates - InProgress</summary>

<details>
<summary>a. Check background updates using universal DMG - InProgress</summary>

1. Install 1.72.x via the universal DMG file from GH (I used a version that was 1-2 days old so that it wasn't the latest on the update server)
2. Launch, confirm expected version (via brave://version) and close. Note, you can launch with `--update-feed-url=https://updates-panel.brave.com/sparkle/Brave-Browser/nothanks/appcast.xml` to avoid picking up an update before we're ready if desired.
3. Do one of the following:
a. Advance computer clock 4 hours
OR
b. Delete `com.brave.Browser.nightly` folder from `~/Library/Caches`, `delete com.brave.Browser.nightly.plist` file from `~/Library/Preferences`, and restart your computer 
4. Relaunch 1.72.x without dummy update URL
5. Don't visit brave://settings/help, watch logs for update
6. Wait for update to be found

```

```
 
7. Close and relaunch browser, confirm update occurred as expected

SS

8. Confirm directories not created by running the below from https://github.com/brave/brave-core/pull/25190#issue-2473176320 as directed:

```
ls "/Library/Application Support/BraveSoftware/BraveUpdater"
ls "~/Library/Application Support/BraveSoftware/BraveUpdater"
```

SS

</details>

<details>
<summary>b. Check background updates using architecture specific PKG - TBD</summary>

1. Install 1.72.x via the architecture specific (x64 in this case) PKG file from GH (I used a version that was 1-2 days old so that it wasn't the latest on the update server). Follow all prompts on the pkg installer as directed.
2. Launch, confirm expected version (via brave://version) and close. Note, you can launch with `--update-feed-url=https://updates-panel.brave.com/sparkle/Brave-Browser/nothanks/appcast.xml` to avoid picking up an update before we're ready if desired.
3. Do one of the following:
a. Advance computer clock 4 hours
OR
b. Delete `com.brave.Browser.nightly` folder from `~/Library/Caches`, `delete com.brave.Browser.nightly.plist` file from `~/Library/Preferences`, and restart your computer 

Note, depending on which option you chose (a or b), you may get slightly different prompts from the pkg installer/sparkle when you continue testing.

4. Relaunch 1.72.x without dummy update URL
5. Don't visit brave://settings/help, wait for update
6. Wait for update to be found - follow any prompts you get due to installing via PKG

Example | Example | Example
--- | --- | ---

7. Close and relaunch browser, confirm update occurred as expected

SS

8. Confirm directories not created by running the below from https://github.com/brave/brave-core/pull/25190#issue-2473176320 as directed:

```
ls "/Library/Application Support/BraveSoftware/BraveUpdater"
ls "~/Library/Application Support/BraveSoftware/BraveUpdater"
```

SS

</details>

</details>
