### ISSUE TITLE
Inject scriptlets in about:blank frames

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#40703]
Similar to https://github.com/brave/brave-browser/issues/40649, scriptlets are not injected and executed in `about:blank` frames on desktop and Android, but they should be.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.90 Chromium: 129.0.6668.59 (Official Build) beta (64-bit)
-- | --
Revision | 1f5f0d1b8a45a4c60a78c15df081751e39184b97
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

Reproduced the issue in `1.70.117`

![image](https://github.com/user-attachments/assets/02c03699-f858-4306-bdd8-1a2d0342ea01)

1. Installed 1.70.117
2. launched Brave
3. opened `brave://settings/shields/filters`
4. added below rules to the custom filters box 

- scriptlet.localframes.xyz##+js(set, sval, 1)
- scriptlet.localframetesting.xyz##+js(set, sval, 42)

5. clicked Save
6. opened scriptlet.localframes.xyz in a new tab


#### Confirmed that the `first-party local frames` reports a value of `1` instead of `undefined`, and the `third-party local frame` reports a value of `42` instead of `undefined`

step 4 | step 6
----- | -----
![image](https://github.com/user-attachments/assets/a5803985-d14a-45ec-a8d5-0736e2fc7e5d)|![image](https://github.com/user-attachments/assets/a44dc7d5-903d-45b8-923c-2a590e332f82)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.91 Chromium: 129.0.6668.59 (Official Build) beta (arm64)
-- | --
Revision | 221dba1a47a2b38858844411284e5bda1de8dd13
OS | macOS Version 14.6.1 (Build 23G93)
```


1. Installed 1.71.91
2. launched Brave
3. opened `brave://settings/shields/filters`
4. added below rules to the custom filters box 

- scriptlet.localframes.xyz##+js(set, sval, 1)
- scriptlet.localframetesting.xyz##+js(set, sval, 42)

5. clicked Save
6. opened scriptlet.localframes.xyz in a new tab


#### Confirmed that the `first-party local frames` reports a value of `1` instead of `undefined`, and the `third-party local frame` reports a value of `42` instead of `undefined`

step 4 | step 6
----- | -----
![Screenshot at Sep 20 13-45-22](https://github.com/user-attachments/assets/11722b59-3eaf-4e03-a4e6-050a24d8b2e4)|![Screenshot at Sep 20 13-46-00](https://github.com/user-attachments/assets/a833b402-b206-484a-a184-79faf47a600c)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 15` using the following build(s):

```
Brave | 1.71.110 Chromium: 129.0.6668.100 (Official Build) beta (64-bit)
--- | ---
Revision | 46cd0b1af7127687895fcaceff93dd80e29e6f2b
OS | Android 15; Build/AP41.240823.009; 35; REL
```

* added the following rules into via `Settings` -> `Brave Shields & privacy` -> `Content Filtering` -> `Create custom filters`

```
scriptlet.localframes.xyz##+js(set, sval, 1)
scriptlet.localframetesting.xyz##+js(set, sval, 42)
```

Once the above was added into `Create custom filters`, ensured that:

* `first-party local frames` is displaying `1` rather than `undefined`
* `third-party local frame` is displaying `42` rather than `undefined`

**`Example`** | **`Example`**
----------------|----------------
![Image](https://github.com/user-attachments/assets/b7cee9d6-845a-4e27-a752-4025ae119eb3) | ![Image](https://github.com/user-attachments/assets/a54e005c-5736-4fea-9fa3-94c9f26c922c)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy S8 Ultra` running `Android 14` using the following build(s):

```
Brave | 1.71.110 Chromium: 129.0.6668.100 (Official Build) beta (64-bit)
--- | ---
Revision | 46cd0b1af7127687895fcaceff93dd80e29e6f2b
OS | Android 14; Build/UP1A.231005.007; 34; REL
```

* added the following rules into via `Settings` -> `Brave Shields & privacy` -> `Content Filtering` -> `Create custom filters`

```
scriptlet.localframes.xyz##+js(set, sval, 1)
scriptlet.localframetesting.xyz##+js(set, sval, 42)
```

Once the above was added into `Create custom filters`, ensured that:

* `first-party local frames` is displaying `1` rather than `undefined`
* `third-party local frame` is displaying `42` rather than `undefined`

**`Example`** | **`Example`**
----------------|----------------
![Image](https://github.com/user-attachments/assets/8a3a5f47-f8df-4de1-a5d2-3ce6a3d82c53) | ![Image](https://github.com/user-attachments/assets/55e320d7-ae71-415b-bbc2-420152e47472)
