### ISSUE TITLE
[Suggestion] Global Settings being applied globally

### ISSUE THREAD

**Issue by GraOrigin** [brave/brave-browser#4098]
When editing global settings via Global Shield Standardvalues it should be applied globally.
Just noticed that those settings are not being applied when in TOR-Modus - had to set it all again.

Version 0.62.51 Chromium: 73.0.3683.103 (Offizieller Build) (64-Bit)

**Comment by srirambv** [comment]
Tor windows doesn't inhert shields settings from normal window. Tor window has its own global shield settings that you can change only for Tor windows. This is the expected behaviour as Tor windows are guest windows they don't inherit any setting from normal window.

cc: @tomlowenthal @riastradh-brave
