### ISSUE TITLE
VPN seletion panel plural issue - `city` should be used for 1 city

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#40987]
### Description

<img width="337" alt="image" src="https://github.com/user-attachments/assets/db67c95a-cd62-4802-9652-0d7f0d87bb27">

### Steps to reproduce

1. Setup VPN
2. Go to region selet panel
3. 

### Actual result

`1 cities`

### Expected result

It should be `1 city`

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.78 Chromium: 128.0.6613.120 (Official Build) nightly (x86_64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @bsclifton

**Comment by kjozwiak** [comment]
The above requires `1.71.88` or higher for `1.71.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.96 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | 6dc1837bd07e6dacd8b6b7b5d9f27e7bb09b5eb5
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

1. Installed 1.71.96
2. launched Brave
3. logged into account.bravesoftware.com with existing VPN credentials
4. clicked `Refresh VPN + Firewall` 
5. clicked VPN button and enabled VPN via VPN panel

Confirmed correct text displayed as expected

- "city" should be used for single city otherwise "cities" is used.
- "server" should be used for single server otherwise "servers" is used.

example | example | example 
------ | ------ | -----
![image](https://github.com/user-attachments/assets/a7534ad2-a358-45e8-97bc-2171f5fc48e0)|![image](https://github.com/user-attachments/assets/645b8afb-180b-4b83-88b1-589dd8bffb1b)|![image](https://github.com/user-attachments/assets/c17085f9-fd8b-4202-8cdc-ad8a4cacc628)
