### ISSUE TITLE
Insufficient funds notification when there is no site in a-c list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4104]
## Description 

Insufficient funds notification when there is no site in a-c list

## Steps to Reproduce

   1. Enable rewrads
   2. Do not claim any grants
   3. Do not add any sites to a-c list
   4. Trigger reconcile
   5. Insufficient funds notification shown

## Actual result:

Insufficient funds notification when there is no site in a-c list

## Expected result:
Should not show insufficient funds message when there is no site added to a-c list

## Reproduces how often: 

Easy

### Additional Information

cc: @NejcZdovc

**Comment by jasonrsadler** [comment]
@srirambv Can you see if this is still an issue (at least on nightly). I do get one 'Insufficient' notification in the panel but that is before reconciliation starts and is fixed in brave/brave-core#2208 (pending). Can you check by:
* running with term with reconcile-interval in clean profile, 
* dismissing grant, 
* waiting a minute or two and dismissing 'Insufficient' (before reconcile triggers[you may have to click off and back on the panel to get notifications]) 
* and then viewing terminal and waiting for `Auto contribution table is empty` and then see if notification still appears at that point?

**Comment by srirambv** [comment]
@jasonrsadler Tried the following on `0.67.31 Chromium: 75.0.3770.27 (Official Build) nightly (64-bit)`

* Launch browser with `brave-browser-nightly --enable-logging=stderr --rewards=staging=true,reconcile_interval=2 --vmodule=*rewards*=2`
* Enable rewards and not claim grant
* Wait for 2 mins for `reconcile_interval` to do its magic
* No notification shown for insufficient funds
* Didn't see any console message for `Auto contribution table is empty` as well

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.108 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2208 and STR from description
