### ISSUE TITLE
Media stops playing via playlist when sidebar is closed

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#41118]
### Description

When playing certain media in the playlist and then closing the sidebar, the media stops playing. The media should still be active when sidebar is closed.

Add https://podcasts.apple.com/us/podcast/the-things-engineers-are-desperate-for-pms-to/id1627920305?i=1000669592151 to the playlist

### Steps to reproduce

1. Open playlist.
2. Select media item to play (the one above)
3. Close sidebar and notice that media stops playing.

### Actual result

See STR.

### Expected result

Media continues to play and is stopped when users press pause and when users play through the media item(s) in the list. 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.x

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
cc: @szilardszaloki When you get a chance, it's specifically this media type/podcast.

**Comment by szilardszaloki** [comment]
It's because of this check: https://github.com/brave/brave-core/blob/034c9184fb5387379cf5bd6ff4e3eac47a1a3eee/browser/ui/views/side_panel/playlist/playlist_side_panel_coordinator.cc#L120

Chromium doesn't maintain `WebContentsImpl::currently_playing_video_count_` for media where `MediaPlayerInfo::has_video` is `false` (see [here](https://source.chromium.org/chromium/chromium/src/+/d32516a5b4df613bf95946d64bf921275fba60c9:content/browser/web_contents/web_contents_impl.cc;l=10371) and [here](https://source.chromium.org/chromium/chromium/src/+/d32516a5b4df613bf95946d64bf921275fba60c9:content/browser/web_contents/web_contents_impl.cc;l=10384)) — which is exactly what the case is with the podcast.

As an alternative, we could keep the `WebContents` in the Playlist sidepanel alive (and let the media play in the background) if there's audible media playing in the `WebContents`.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | 5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

1. Installed 1.72.93
2. launched Brave
3. opened `brave://flags` in a new tab
4. enabled #playlist flag 
5. loaded https://podcasts.apple.com/us/podcast/the-things-engineers-are-desperate-for-pms-to/id1627920305?i=1000669592151
6. clicked `Allow` in the Google Widevine notification
7. clicked `Play` button
8. added to the playlist via playlist button in the URL bar
9. opened playlist
10. played the media item in the playlist panel 
11. close sidebar by clicking playlist icon in the sidebar and toolbar 
12. added couple of youtube media files (eg. https://www.youtube.com/watch?v=uu7j_xljCRY)

#### Confirmed media played when sidebar is closed

https://github.com/user-attachments/assets/3d10966b-a109-4a0c-a0df-60e9b78e5b56
