### ISSUE TITLE
Brave Intaller installed 32bit version instead of 64 bit

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [brave/brave-browser#4116]
## Description 

I downloaded Brave Browser for windows (64 bit version) from the site and the 32 bit version got installed 

## Steps to Reproduce

   1. Go To brave.com
   2. Click Download
   3.Install Brave

## Actual result:

![image](https://user-images.githubusercontent.com/38154154/56183372-ef8b6780-6033-11e9-98e3-ae8604705023.png)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Don't Know
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 
No
### Additional Information

I think i got the 32 bit version because brave got installed in C:\Program Files (x86)

**Comment by srirambv** [comment]
Please check the platform in task manager to see if you have 64bit or 32bit. Just because its installed in `Program Files (x86)` doesn't mean its a 32bit application that is installed. 

![image](https://user-images.githubusercontent.com/17010094/56213998-0f6a5d80-602b-11e9-857c-de0c7651cd95.png)

**Comment by YanAndrew** [comment]
OK Everybody, a couple of things:
1. Referring to the image of the Task Manager from @srirambv above, I do not understand why I do not have the Platform column in the Details tab of my Task Manager like @srirambv does (please refer to the image of my Task Manager below:

![image](https://user-images.githubusercontent.com/47048793/80919993-8e017c80-8d9f-11ea-8021-3d5ab34686f3.png)
[https://i.postimg.cc/Hk09kq9G/My-Task-Manager.jpg](url)
Any thoughts anyone?

2. If a user made sure that he downloaded the 64-bit installer, why on Earth would the browser be installed in the (x86) folder? If the installation is going to do as it pleases, then everything 'Custom' becomes irrelevant, don't you think?

Also, if Brave is aware that its 64-bit installer favours the (x86) folder more, why did they not  do something to rectify it, instead of just leaving it be causing confusion amongst its users?

**My question:**
If I were to reinstall the Brave browser, would it cause any issue if at the installation stage I specified my preferred location?


Regards,
Andrew
