### ISSUE TITLE
Update verified icons globally inside Rewards

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#4162]
Partner issue to https://github.com/brave/brave-browser/issues/4043

In parallel to updating the address bar icon, we need to make a global verified icon update across Rewards for continuity. This is mainly switching from a hexagon to a circle in the Auto-Contribute table and dropdown panel. A few additional parity updates upon inspection should probably also take place.

- Update the term `Publisher` to `Creator`
- Group the "Check again" button functionality with the site status instead of floated right. Should probably update phrasing to something more universal like `Refresh Status`. 

@bradleyrichter @rebron @mandar-brave @jenn-rhim

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2491
* Verified panel now says 'Refresh Status' instead of 'Check again...'
* Verified 'Refresh Status' is grouped with site status instead of floating right
![Screen Shot 2019-07-10 at 4 35 10 PM](https://user-images.githubusercontent.com/28145373/61003124-2c17e800-a331-11e9-87a1-92de383fb6fe.png)
* Verified round verified icon shows on AC table and tips table
![Screen Shot 2019-07-10 at 4 38 12 PM](https://user-images.githubusercontent.com/28145373/61003134-320dc900-a331-11e9-826d-14d346e8a3ba.png)
* Verified round icon displays on panel.
* Verified when pub/creator is verified, text reads 'Brave Verified Creator' on panel instead of previous 'Brave Verified Publisher'
![Screen Shot 2019-07-10 at 4 35 30 PM](https://user-images.githubusercontent.com/28145373/61003272-81ec9000-a331-11e9-90d9-79d5c6b1eb40.png)
