### ISSUE TITLE
"Brave Ads paused" Pop-up

### ISSUE THREAD

**Issue by balaji303** [brave/brave-browser#41742]
### Description

![Image](https://github.com/user-attachments/assets/6091e939-cf6d-441b-8429-8ea2dd30787c)
I get his pop-up often in the latest release [Version 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)](https://brave.com/latest/)

I have disabled Brave's rewards and wallet, not using them for nearly 3years.

Please remove this pop-up feature or guide me todo so.

### Steps to reproduce

1. Use Lastest Brave browser as you do
2. 
3. 

### Actual result

![Image](https://github.com/user-attachments/assets/c3956fb2-edc7-4379-8cb6-ccb4aad0bc9e)

### Expected result

![Image](https://github.com/user-attachments/assets/c7e49be0-4cb5-49b8-ae35-03fc7be6a40d)
This should be removed

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave is up to date
[Version 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)](https://brave.com/latest/)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by Miyayes** [comment]
Hi @balaji303, if you press "Solve", what happens? It should show a window that allows you to solve the CAPTCHA.

You also mentioned you disabled Rewards / Wallet for a couple years now. I think these would only show if you have those enabled. If you go to brave://rewards, do you see the Rewards interface? In order to actually disable it, you should "Reset" Rewards, which will return Rewards to a pre-enabled state.

**Comment by sp2ed2** [comment]
Happening to me also for the past two days.

Brave Rewards disabled for years.

Pressing "Solve" closes the popup, but does not show a captcha. The popup reopens after a few minutes.

This has started happening to all of my browser profiles at the same time (I have 30 or so).

**Comment by Miyayes** [comment]
Hi @sp2ed2 I suspect that when you press "Solve", the captcha is showing up in some other workspace, or in some other browser profile of yours that's minimized. 

That said, we have a pull request to allow users to repeatedly defer / hide the CAPTCHA notice.

**Comment by bsclifton** [comment]
Interesting it happens for both folks who had Rewards disabled for years

If you are comfortable losing the rewards data, please try the what @Miyayes mentioned:
1. Visit brave://rewards
2. In the middle top area, there's a gear icon and `Reset`
3. Click this, check the box and click `Reset`

After this steps Rewards should be truly disabled

**Comment by sp2ed2** [comment]
> Interesting it happens for both folks who had Rewards disabled for years
> 
> If you are comfortable losing the rewards data, please try the what [@Miyayes](https://github.com/Miyayes) mentioned:
> 
> 1. Visit brave://rewards
> 2. In the middle top area, there's a gear icon and `Reset`
> 3. Click this, check the box and click `Reset`
> 
> After this steps Rewards should be truly disabled

Tried this yesterday in my main browser profile, and I want to say that it continued to popup but not sure because multiple browser profiles. 

I have now solved the captcha in one of my browser profiles, and it seems to have stopped the popups in all profiles.

I'd hit the solve button in my main profile 50 times in the last 2 days and it never showed the captcha.

**Comment by bsclifton** [comment]
cc: @tmancey

**Comment by tmancey** [comment]
@balaji303 thank you for reporting this issue, the Rewards team are working on fixes, please see https://github.com/brave/brave-browser/issues/41760#issuecomment-2429323362. cc @Miyayes
