### ISSUE TITLE
Bookmarks and history are duplicating and scrambling in bookmarks manager / history manager

### ISSUE THREAD

**Issue by hollons** [brave/brave-browser#41763]
### Description

User's on Windows (+1 Linux user) are reporting that bookmarks are duplicating and scrambling within bookmarks manager. 

It appears to be related to an upstream Chromium bug https://issues.chromium.org/issues/374007459?pli=1

Community reports: 
https://community.brave.com/t/major-bug-with-bookmarks-duplicating-and-scrambling-in-bookmarks-manager/576179
https://community.brave.com/t/restore-bookmarks/576125
https://community.brave.com/t/bookmarks-scrambled-after-update/575914
https://community.brave.com/t/my-bookmarks-are-bugged/576115
https://community.brave.com/t/bookmarks-completely-scrambled/576185
https://community.brave.com/t/bookmarks-manager-issues/576184

### Steps to reproduce

1. Users report that as you scroll, bookmarks are duplicating
2. Clicking onto a duplicated item changes the file name
3. Can't delete as they're not really duplicate files, just appearing as duplicates

### Actual result

Duplicate file names appearing in bookmarks manager. 

### Expected result

Bookmark manager appears as normal without duplicates listed. 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.114

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by bsclifton** [comment]
We're also seeing this with history - more information in https://github.com/brave/brave-browser/issues/41781

Folks experiencing this can work-around the issue temporarily by launching Brave with the command-line flag `--disable-features=CCSlimming`. 

Upstream, this is captured with https://issues.chromium.org/issues/373874326 and it was fixed with https://chromium-review.googlesource.com/c/chromium/src/+/5941735. 

We have a build going now for Brave and will be releasing an update which will have this fix. On our side, the Chromium update was done with https://github.com/brave/brave-core/pull/26158 and you can see the patch above in the diff here:
https://chromium.googlesource.com/chromium/src/+log/130.0.6723.58..130.0.6723.70/?pretty=fuller&n=10000

I'll assign the milestone so that QA can check this tomorrow. Thanks for your patience 😄

**Comment by bsclifton** [comment]
For QA: one way I can consistently reproduce the bugs w/ history is to visit a bunch of sites, verify they show in history. Then visit Google maps and click on a bunch of locations, go to street view, etc. Then visit history page (Ctrl + H). You should see the dates mixed up in the old build.

I haven't looked at steps for bookmarks manager personally

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.71.118 Chromium: 130.0.6723.70 (Official Build) (64-bit)
-- | --
Revision | d29310b051bde8ba041cd7b4edcb41ce951be12c
OS | Windows 10 Version 22H2 (Build 19045.5011)
```

The issue (history date mixed up) mentioned via https://github.com/brave/brave-browser/issues/41763#issuecomment-2430969758 is reproducible on `1.71.114`
![Image](https://github.com/user-attachments/assets/21ea17c4-8351-4093-8fbc-8413d129774a)
Verified the history date mixed up issue on `1.71.118` and ensured that brave history is shown/filtered correctly with date and time
![Image](https://github.com/user-attachments/assets/3b0caf0d-50e7-4374-844b-ea9fcae630be)
