### ISSUE TITLE
Add VPN widget to NTP

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#41778]
Captured some images from below figma

<img src="https://github.com/user-attachments/assets/4cc36444-90e5-40f8-ba22-49711789629d" alt="vpn purchased" width="300"/>
<img src="https://github.com/user-attachments/assets/4691d1a6-4909-439b-a412-a32e7029043a" alt="vpn purchased" width="300"/>

figma - https://www.figma.com/design/cpUWWHUsMtyQHWAES24Kjx/VPN-Widget-BT24?node-id=0-1&node-type=canvas&t=dMgPpDsUQTUb90PY-0

demo code at BT24 - https://github.com/brave/brave-core/tree/brave_vpn_ntp_widget_demo

cc @rebron @bsclifton @w0ts0n @AlanBreck

**Comment by LaurenWags** [comment]
Updated labels on this one. While widget testing needs to be completed on Windows and macOS, Linux needs to be checked to confirm that the widget does not display at all.

cc @rebron @kjozwiak @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.73.98` or higher for `1.73.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.73.99 Chromium: 131.0.6778.108 (Official Build) (x86_64)
-- | --
Revision | 273b36438521dd91cbab7a047e6d90deabf59d56
OS | macOS Version 14.7.1 (Build 23H222)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.73.99 Chromium: 131.0.6778.108 (Official Build) (64-bit)
-- | --
Revision | 273b36438521dd91cbab7a047e6d90deabf59d56
OS | Windows 10 Version 22H2 (Build 19045.5131)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.73.99 Chromium: 131.0.6778.108 (Official Build) (64-bit)
-- | --
Revision | 273b36438521dd91cbab7a047e6d90deabf59d56
OS | Windows 11 Version 24H2 (Build 26100.2314)
```


<details>
<summary>Case 1: Initial sell screen/ NOT Subscribed state - Passed</summary>

1. confirmed `Brave VPN` card widget is shown in the NTP 
2. confirmed Brave VPN widget is displayed in the foreground with Rewards and Talk widgets in the background
3. confirmed the card widget named `Brave VPN` and the design matched to the screenshot 
4. confirmed when clicked `Start free trial`, button, it navigated to check out page - https://account.brave.com/intent=checkout&product=vpn 
5. confirmed when clicked `Already purchased Brave VPN?` link, it navigated to recover page - https://account.brave.com/?intent=recover&product=vpn
6. confirmed when clicked on 3-dot menu, `Hide Brave VPN` option is shown and able toggle on/off
7. confirmed new Brave VPN icon is shown in the toolbar

step 1 - 3 | step 4 | step 5 | step 6 | step 7 
--- | ------- | -------| --------|-------- 
![Image](https://github.com/user-attachments/assets/265125ff-ef87-45a3-9666-b6b2c45fd3b3)|![Image](https://github.com/user-attachments/assets/6d8e7142-e61b-47af-8a97-4b61846ccac5)|![Image](https://github.com/user-attachments/assets/d680b4a5-9de2-4f05-b08e-9da4572b19f6)|![Image](https://github.com/user-attachments/assets/3e7f344c-b4ea-42b9-837b-9be7dda0f14a)|![Image](https://github.com/user-attachments/assets/76d8e100-172c-47b9-b5a8-1f5868f8acda)

</details>


<details>
<summary>Case 2:  Sign up/Subscribe to Brave VPN via NTP widget as a New user - Passed</summary>

1. continued from Case 1
     -`Brave VPN` widget is shown in NTP
2. clicked Start free trial
3. verified checkout page is loaded
4. for this testing purposes, logged into account.bravesoftware.com
5. entered brave6vpnwidget@mailinator.com the email field
6. completed purchase for Brave VPN
7. confirmed green `CREDENTIALS LOADED` message shown 
8. opened a new tab page (refresh the page or open a new tab page here to show correct state due to staging site testing)
9. confirmed Brave VPN widget is shown in disconnected state with toggle off in the NTP
10. confirmed Brave VPN card matches to Figma designs in the disconnected state
11. confirmed default locale (USA) is shown on the card as expected.
12. confirmed new VPN button in the tool bar shown in disconnected state (VPN button shown instead of VPN icon)
13. confirmed when clicked on VPN icon in the toolbar, VPN panel shows disconnected state

step 1 | step 2 | step 7 | step 9-11 | step 12- 13 
----- | ----- | ----- | ----- | -----  | ------
![Image](https://github.com/user-attachments/assets/7cb4ba79-8b09-492d-8201-77e2b6e42403)|![Image](https://github.com/user-attachments/assets/9da5ebf7-79ea-47e1-a1e6-5da80f655e14)|![Image](https://github.com/user-attachments/assets/dd8b4464-15df-4527-a023-d62aaee79b0e)|![Image](https://github.com/user-attachments/assets/45fdeb68-5e98-4909-ba3d-12fa4f5fd044)|![Image](https://github.com/user-attachments/assets/16b15e28-7707-486f-a9a6-6c1be14a388b)

</details>


<details>
<summary>Case 3: Connect/Disconnect Brave VPN via NTP card widget in the NTP - Passed</summary>

1. Continue from Case 2: 
    - Subscribed to Brave VPN
    - Not enabled yet
2. toggled `On` in the Brave VPN card widget
3. confirmed `Connecting` state shown when toggled `On`
4. confirmed Brave VPN successfully connected.
5. confirmed Brave VPN icon shown connected state in the Card
6. confirmed Brave VPN button in the toolbar shown green checkmark for connected status
7. clicked hamburger menu >Brave VPN
8. confirmed connected status is shown
9. clicked Taskbar to view Brave VPN icon  
10. confirmed Brave VPN icon in the toolbar is shown green checkmark for connected status (failed)
11. confirmed Brave VPN wireguard protocol is enabled in `brave://settings/system`
12. disconnected VPN via VPN card widget
13. confirmed the toggle was `off` in the VPN card widget
14. confirmed VPN connect/disconnect functionality working as expected via VPN button and hamburger menu 

step 1 | step 3 | step 4-5 | step 8 | step 10 | step 11 | step 13 
------ | ------- | ------- | ----- | ------ | ---- | ------
![Image](https://github.com/user-attachments/assets/c187af85-9de0-4cb5-92e0-ae83b821d163)|![Image](https://github.com/user-attachments/assets/869a3377-ecec-412a-a5ec-e521458055a0)|![Image](https://github.com/user-attachments/assets/98c1dbe4-a504-48cd-b472-b66326568299)|![Image](https://github.com/user-attachments/assets/38a685ac-b6e2-41f3-8ec1-67844a943b97)|![Image](https://github.com/user-attachments/assets/ba858868-ee14-42f1-a0fc-58bf783f4a4d)|![Image](https://github.com/user-attachments/assets/0f65af30-3b1d-4930-81bc-43a52c92a4c2)|![Image](https://github.com/user-attachments/assets/a7d2d6ba-bb1a-4b30-811f-9e4efd020da5)
</details>

<details>
<summary>Case 4 - Server Selection - Passed </summary>

1. continue from Case 3: 
    - verified VPN region shown as default region `USA` (optimal) VPN card widget 
2. visited whatismyipaddress.com
3. confirmed USA region (`Atlanta`) is shown 
4. clicked `Change` link in the VPN card widget 
5. hover over `Spain` and clicked `Connect` button 
6. connected to Spain region
7. confirmed `VPN card` widget shows correct `Spain` region
8. reloaded whatismyipaddress.com page
9. confirmed correct region `Spain` shown
10. switched to different region `South Africa` and hover over and clicked  `Johannesburg`
11. confirmed correct region `South Africa` - Johannesburg server is shown on the `VPN card` widget
12. reloaded whatismyipaddress.com page and confirmed correct region shown - `South Africa`


step 1 | step 3 | step 5 | step 6 | step 9 | step 10 | step 12
------ | ----- | ----- | ------ | ------ | ---- | -----
![Image](https://github.com/user-attachments/assets/c6579329-7192-4867-8fb3-d0dfe12ae5f2)|![Image](https://github.com/user-attachments/assets/5b99ae60-d3eb-4037-85d5-d81170fa9bb6)|![Image](https://github.com/user-attachments/assets/819affa3-0283-4f8a-a948-f31c12548f77)|![Image](https://github.com/user-attachments/assets/1e3c142d-6adc-49b5-a8e5-ac18d4d1bce0)|![Image](https://github.com/user-attachments/assets/d6f2ff0c-f277-4fb2-a1ee-2374affcb7ef)|![Image](https://github.com/user-attachments/assets/60d8dc13-8165-42d7-8e7f-7efb06ed3b77)|![Image](https://github.com/user-attachments/assets/8aabeca5-0b6c-40b7-aa35-dc71fa2c3689)|![Image](https://github.com/user-attachments/assets/f9407d82-a26f-4eec-9e88-471352b80996)

</details>

<details>
<summary>Case 5 - Can't connect to server UI - Pending</summary

1. continue from Case 4
    - Connected to VPN with South Africa region
2. disabled VPN 
3. unplugged your network cable (or disable Wi-Fi)
4. toggled `ON` via VPN card widget
5. waited until it errors out with a red icon on the toolbar VPN icon 
6. switched to different server (USA) via Change server link in VPN card widget
7. confirmed `Can't connect to server` message is shown
8. plugged network cable back in OR enable Wi-Fi (disabled in step 6)
9. clicked the `Try again` button
10. Confirm successfully connected to VPN 

step 1 | step 2 | example | example 
----- | -----  | ----- | -----
![Image](https://github.com/user-attachments/assets/d9a28ec4-5dd7-41d2-a5f6-b5eff965e3ff)|![Image](https://github.com/user-attachments/assets/1b3dec40-d148-46cb-8bdf-c5d0c17bda90)|![Image](https://github.com/user-attachments/assets/5130ef38-745b-4c3f-9e59-b47ac768a932)|![Image](https://github.com/user-attachments/assets/b23a142e-f82d-44f8-b39e-0e29a130ad70)


</details>


<details>
<summary>Case 6: Customize Dashboard - Card functionality - Passed</summary>

1. continued from Case 5
    - `Brave VPN` card widget is shown in NTP
2. Clicked `Customize` in the NTP
3. clicked `Cards` 
4. confirmed `Brave VPN` card widget is shown
5. clicked `Hide` button 
6. confirmed `Brave VPN` card widget is hidden in the NTP
8. clicked `Add` button via `Customize`
9. confirmed `Brave VPN` card widget is shown in the NTP 
10. click `Clock` in the Dashboard
11. enable `Show Clock` 
12. confirmed `Clock` is shown above the Talk card and Brave VPN positioned as expected.
13. turned `Off` `Cards` toggle, 
14. Hide and Add functionality for Talk, Rewards & Brave VPN worked as expected

step 5 | step 6 | step 7 | step 9 | step 11 | step 12 | step 13 
----- | ----- | ------- | ------ | ------ | ------- | -------
![Image](https://github.com/user-attachments/assets/7492e73c-5dcc-412f-aa06-adf1bd23dd5f)|![Image](https://github.com/user-attachments/assets/e940fe24-7d32-46bc-9268-2ed26415c443)|![Image](https://github.com/user-attachments/assets/af32243e-7c8e-4321-b5b9-aafaf62f425f)|![Image](https://github.com/user-attachments/assets/bbd35847-1770-4b6a-9acf-947de7f4ae2f)|![Image](https://github.com/user-attachments/assets/0c721e6a-ad0e-4d78-afa4-0b29fc92b6b3)|![Image](https://github.com/user-attachments/assets/330b617c-4306-470f-9237-e99ae1cda4b1)|![Image](https://github.com/user-attachments/assets/3027927e-9607-4f7c-abf5-571488d55bd0)

</details>


</details>

<details>
<summary>Case 7:  Default WireGuard and fallback to IKEv2 connections - Pending</summary>

1. New profile
2. opened brave://settings/system
3. verified `Use Wireguard protocol in Brave VPN` is disabled
4. logged into Brave VPN as an existing user and refreshed VPN
5. enabled VPN connection via Brave VPN card widget
6. confirmed Wireguard protocol is enabled
7. disabled VPN via VPN icon in the toolbar 
8. toggle `off` Wireguard protocol in brave://settings/system
9. enabled VPN connection via Brave VPN card widget 
10. confirmed VPN connected successfully with IKEv2 fallback

step 4 | step 5 | step 6 | step 7 | step 8 | step 9 | step 10 
------- | ------- | ------ | ------- | ------- | ------- | -------

</details>

<details>
<summary>Case 8 - Multiple Profiles - Pending</summary>

1. New profile 
2. click Microsoft Edge >>Import (3 Profiles) >>Import Profiles  >>Finish
3. added another profile with `Citron` theme via hamburger menu 
4. logged into VPN as an existing user bravevpn26@mailinator.com
5. clicked to `Refresh Firewall + VPN`
6. confirmed Profile 1 shows  `Brave VPN card widget` in disconnected state
7. opened rest of MS Edge profiles and Profile 2
8. enabled VPN for profile 1.
9. confirmed when VPN enabled,  rest of the profiles as well
10. confirmed when VPN disabled,  rest of the profiles as well

</details>



<details>
<summary>Case 10 Upgrade - Pending</summary>

1. Installed 1.75.7 
2. launched Brave
3. logged into account.bravesoftware.com as an existing user (brave2vpn@mailinator.com)
4. clicked `Refresh Firewall + VPN`
5. connected to VPN via toolbar VPN panel
6. upgraded to latest nightly 1.75.59 via brave://settings/help
7. clicked new tab page
8. confirmed `Brave VPN` card widget is shown on NTP
9. confirmed VPN is still toggled on
10. disconnected VPN via VPN card widget on NTP
11. confirmed able to connect to VPN via card widget, hamburger menu, toolbar VPN panel


</details>

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave	1.73.99 Chromium: 131.0.6778.108 (Official Build) (64-bit) 
Revision	273b36438521dd91cbab7a047e6d90deabf59d56
OS	Linux
```

New Install 
<details>

1. Installed 1.73.99
2. launched Brave
3. completed onboarding
4. confirmed Brave VPN card widget is not shown in the NTP 
5. verified  Talk, Rewards card widgets have shown as expected in the NTP
6. confirmed Brave VPN card is not shown in the Customize Dashboard >>Cards


step 4 - 5 | step 6
---- | -----
![Image](https://github.com/user-attachments/assets/ec982cba-c1fe-42b3-a937-4a7eab5e48dd)|![Image](https://github.com/user-attachments/assets/8914173f-95f0-4486-a12a-becd60765ff2)
</details>

Upgrade:
<details>

1. Installed 1.73.97
2. launched Brave
3. completed onboarding
4. verified  Talk, Rewards card widgets have shown as expected in the NTP
5. installed 1.73.99
6. upgraded via brave://settings/help
7. confirmed Brave VPN card widget is not shown in the NTP


step 1 | step 4 | step 5 | step 6 | step 7
----------- | ------ | -------- | ------- | -------
![Image](https://github.com/user-attachments/assets/980b706c-3613-402f-884e-a74bedc56f71)|![Image](https://github.com/user-attachments/assets/7741c3bd-f24a-43f2-a785-408fc232c7b2)|![Image](https://github.com/user-attachments/assets/155147a7-6cb2-4488-a623-b84d629e60c0)|![Image](https://github.com/user-attachments/assets/bd17fc30-5d7f-454b-be67-b639f3989fe3)|![Image](https://github.com/user-attachments/assets/68fbd19f-ebc1-44ca-8ccd-2ff0fcb35715)

</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.73.99 Chromium: 131.0.6778.108 (Official Build) (arm64)
-- | --
Revision | 273b36438521dd91cbab7a047e6d90deabf59d56
OS | macOS Version 14.6.1 (Build 23G93)
```
