### ISSUE TITLE
Omaha 4 in per-user installation on macOS incorrectly displays "Brave may not be able to keep itself updated"

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#41821]
### Description

When Omaha 4 is enabled, Brave displays an overlay "Brave may not be able to keep itself updated":

![Image](https://github.com/user-attachments/assets/8191500c-2b69-476b-b30d-cdf357228447)

Such an overlay is expected when it is a system-wide installation. Because in that case, the button in the overlay launches an elevation prompt that installs the updater. The problem is that the overlay is shown even for a per-user installation.

### Steps to reproduce

1. Install Brave from the DMG.
2. Launch it with the command-line parameter `--enable-features=BraveUseOmaha4Alpha`.

### Actual result

The overlay above is shown.

### Expected result

The overlay should not be shown.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.73.21

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.75.21 Chromium: 131.0.6778.69 (Official Build) nightly (x86_64)
-- | --
Revision | 77b46ded5480ad3885206464169d6969dfc65abd
OS | macOS Version 14.7.1 (Build 23H222)
```

**Comment by LaurenWags** [comment]
Verified with

```
Brave	1.74.5 Chromium: 131.0.6778.69 (Official Build) beta (arm64) 
Revision	fbd7c390a7daa54f1aac2c769076d3fecf7c7fc7
OS	macOS Version 15.2 (Build 24C5073e)
```

Verified test plan from https://github.com/brave/brave-core/pull/26164#issue-2607600726.

<details>
<summary>Case 2 - confirm background updates still work - InProgress</summary>

<details>
<summary>a. Check background updates using universal DMG - InProgress</summary>

1. Install 1.74.x via the universal DMG file from GH (I used a version that was 1-2 days old so that it wasn't the latest on the update server)
2. Launch, confirm expected version (via brave://version) and close. Note, you can launch with `--update-feed-url=https://updates-panel.brave.com/sparkle/Brave-Browser/nothanks/appcast.xml` to avoid picking up an update before we're ready if desired.
3. Do one of the following:
a. Advance computer clock 4 hours
OR
b. Delete `com.brave.Browser.beta` folder from `~/Library/Caches`, delete `com.brave.Browser.beta.plist` file from `~/Library/Preferences`, and restart your computer 
4. Relaunch 1.74.x without dummy update URL
5. Don't visit brave://settings/help just watch logs for update
6. Wait for update to be found

```

```
 
7. Close and relaunch browser, confirm update occurred as expected

SS

8. Run the below lines in terminal to confirm that no Omaha4 directories were created:

```
ls "/Library/Application Support/BraveSoftware/BraveUpdater"
ls "~/Library/Application Support/BraveSoftware/BraveUpdater"
```

SS

</details>
