### ISSUE TITLE
Make sure Sparkle and Omaha 4 never update Brave at the same time

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#42365]
We are in the process of migrating Brave's auto-update mechanism on macOS from the Sparkle update framework to Omaha 4 (a.k.a. "Chromium Updater").

The rollout of the new implementation will proceed gradually. We are controlling with a feature flag which percentage of users should use Omaha 4 vs. Sparkle.

This means that, until the transition to Omaha 4 is complete, Brave will include both Sparkle and Omaha 4.

The goal of this issue is to prevent Sparkle and Omaha 4 from trying to update Brave at the same time. As of this writing, the implementation does not do this. Once the user has been switched to Omaha 4, Omaha 4 forevermore checks for updates in the background. If the feature flag gets switched off to use the Sparkle implementation again, then both Sparkle and Omaha 4 will check for updates. This should be prevented.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.75.163 Chromium: 132.0.6834.83 (Official Build) beta (x86_64)
-- | --
Revision | a4d69c2206a1f966f445934ef36333914b912ba3
OS | macOS Version 14.7.2 (Build 23H311)
```

**Comment by LaurenWags** [comment]
Per discussion with @mherrmann, have marked this one `QA/No` instead of `QA/Yes`. https://github.com/brave/brave-browser/issues/43502 needs to be resolved first. Once https://github.com/brave/brave-browser/issues/43502 is resolved, that and this issue can be tested together to ensure they're both working properly.

cc @kjozwiak @rebron
