### ISSUE TITLE
Data from a website doesn't get fully cleaned with "forget me when I close this site"

### ISSUE THREAD

**Issue by captainepoch** [brave/brave-browser#42363]
### Description

A website with the "Olvidarme al cerrar este sitio" toggle doesn't get fully cleaned. This happened me when visiting stackoverflow.com or aliexpress.com, for example.

This is how I have Brave Shields set up for StackOverflow (and the defaults in the browser).

![Image](https://github.com/user-attachments/assets/5be7245d-559e-44ed-bb76-e94850f94e5b)

And, after closing all the tabs with the same domain:

![Image](https://github.com/user-attachments/assets/9a3432b5-e373-453a-bbdb-0996b89c72c9)

Shouldn't even just 1 cookie get deleted?

### Steps to reproduce

1. Setup the defaults to forget any website you visit.
2. Go to stackoverflow.com, for example, browse a couple of posts.
3. Close all the stackoverflow tabs.
4. After a few seconds, or even minutes, check if the data is fully deleted.

### Actual result

The result is that not all the data is deleted.

![Image](https://github.com/user-attachments/assets/9a3432b5-e373-453a-bbdb-0996b89c72c9)

### Expected result

Fully delete everything, included a single cookie.

![Image](https://github.com/user-attachments/assets/22b1be25-09e7-4bc1-8e43-35e822659740)

(The screenshot is after I delete manually the stackoverflow.com entry).

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

**Brave** - 1.73.89 Chromium: 131.0.6778.69 (Build oficial) (x86_64)
**Revisión** - 199634819b22eaa58d8efc35430bc8853b178074
**OS** - macOS Versión 13.7 (Compilación 22H123)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
cc: @ShivanKaul

**Comment by ShivanKaul** [comment]
I can't repro the issue. I took a screen recording of my doing the following:
1. Enabling "forget me when I close this site" in brave://settings/shields
2. Going to stackoverflow.com
3. Going to Settings to check for data stored for SO: brave://settings/content/all?searchSubpage=stackoverflow
4. Closing the tab for stackoverflow.com (only have 1 tab open)
5. Wait for 30 seconds (in the video I waited for longer because was making a cup of tea, but you should only need to wait for 30 seconds)
6. Refresh the Settings page: brave://settings/content/all?searchSubpage=stackoverflow
7. Check that no data is stored for that website.

Can you confirm you don't have any extensions enabled that could be interfering? Or you missed closing a tab open to stackoverflow.com in your test?

https://github.com/user-attachments/assets/93d783a2-06f9-4aac-b7bc-04dc12e459af

**Comment by ShivanKaul** [comment]
I'm not entirely sure what the cookie-related extensions do but I would try without them. You shouldn't need "I still don't care about cookies" extension since Brave blocks cookie notices by default as well. 

If this issue happens again with the extensions disabled, please reopen the issue.
