### ISSUE TITLE
Username is missing on the BR panel for YouTube creators

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#42461]
### Description

username is shown on the BR panel for YouTube creators

### Steps to reproduce

1. Clean profile `1.74.10`
2. Enable rewards and connect to a custodian
3. Open YouTube creator 
4. Username isn't shown on the BR panel

### Actual result

username is not shown on the BR panel, the name is displayed as `on YouTube`

![Image](https://github.com/user-attachments/assets/f9bc0dd2-e332-4835-b647-14c71170011b)

### Expected result

The username should be displayed on the BR panel for YT creators

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.74.10 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | bdff9e7d7314280ddbce1c3ada3abee4ce4a3b32
OS | Windows 10 Version 22H2 (Build 19045.5131)

### Channel information

- [ ] release (stable)
- [x] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/legacy_qa @Miyayes @zenparsing @LaurenWags

**Comment by LaurenWags** [comment]
fwiw, I also experienced https://github.com/brave/brave-browser/issues/42458 when investigating this one:

Example | Example
--- | ---
![Image](https://github.com/user-attachments/assets/0eeff354-8243-4110-87ff-a4c1de7f4091) | ![Image](https://github.com/user-attachments/assets/30d280ef-064f-4ce0-abe7-0299297430bd)

Additionally, it looks like Rewards 3.0 has the same problem (missing creator name in panel):

![Image](https://github.com/user-attachments/assets/ea86790f-d2bc-443a-8996-812edc90c367)

Another data point, not sure if it's helpful but when I switched from Rewards 3.0 UI back to current implementation and visited the page again (in a new tab due to https://github.com/brave/brave-browser/issues/42454), I got _something_ for creator name, although I was expecting something more like `Lauren` or `Lauren Rees`, not `laurenrees3719`. So switching between the two UIs triggered something it seems:

![Image](https://github.com/user-attachments/assets/bfd0b9e9-9589-4299-bc82-9ad3d07d2bcf)

**Comment by kjozwiak** [comment]
The above requires `1.74.14` or higher for `1.74.x` verification 👍
