### ISSUE TITLE
Add VPN widget metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#42515]
Add the following weekly metrics:

If you used the VPN NTP widget in the past week, how many actions did you perform within the widget in the past week?
`Brave.VPN.WidgetUsage`

0. 1
1. 2-10
2. 11-20
3. 21+

Did you hide the VPN widget this week?
`Brave.VPN.HideWidget`

1. Yes

cc @rebron

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.75.86 Chromium: 132.0.6834.33 (Official Build) nightly (64-bit)
-- | --
Revision | 0e6fd65d499de588288c231ca0aba711876f5022
OS | Windows 10 Version 22H2 (Build 19045.5131)
```

**Comment by GeetaSarvadnya** [comment]
@DJAndries: When Brave VPN widget is hidden via NTP the metrics `Brave.VPN.HideWidget` response is `1` as expected, but If we add the card again (unhide) the Brave VPN widget via NTP then the response is still `1` instead of `0`. Is this correct? the metrics will consider only the 1st event response (hide)?

**Comment by DJAndries** [comment]
> [@DJAndries](https://github.com/DJAndries): When Brave VPN widget is hidden via NTP the metrics `Brave.VPN.HideWidget` response is `1` as expected, but If we add the card again (unhide) the Brave VPN widget via NTP then the response is still `1` instead of `0`. Is this correct? the metrics will consider only the 1st event response (hide)?

Hey @GeetaSarvadnya , responded in https://github.com/brave/brave-browser/issues/43041#issuecomment-2568424050. thanks
