### ISSUE TITLE
improve font appearance with non-english characters

### ISSUE THREAD

**Issue by ademaro** [brave/brave-browser#4309]
## Description 
Why you do not use utf-8 fonts for UI? https://yadi.sk/i/LgsPsXybFLfUqQ — no good!
https://yadi.sk/i/9Z-U76fYU4VkEg — cyrillic no good!!

## Steps to Reproduce

   1. Open browser
   2. 
   3. 

## Actual result:

Bad font rendering.

## Expected result:
Good font rendering.

## Brave version (brave://version info)

Brave | 0.63.48 Chromium: 74.0.3729.108 (Официальная сборка) (64 бит)
-- | --
Версия | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
ОС | Mac OS X

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
cc: @rossmoody

**Comment by alshenetsky** [comment]
I am so tired of this :(
![image](https://user-images.githubusercontent.com/8052634/126400265-62ffb686-c1e9-4f58-a327-19dfaf97c7d9.png)

Is there any progress guys?

**Comment by bsclifton** [comment]
cc: @karenkliu @rebron

**Comment by iamalexei** [comment]
The Poppins font used for the UI doesn't support Cyrillic symbols
![brave 2021-11-05 005704](https://user-images.githubusercontent.com/29608963/140427655-d1fb5c39-618b-4568-98a9-7913aa897cbe.png)
![brave-browser-shield-settings](https://user-images.githubusercontent.com/29608963/140427687-483d712b-b95e-4d69-af2d-5d981355dae4.png)

**Comment by iefremov** [comment]
People on the Russian blog also ask to fix this. Can you please triage @bradleyrichter ? Thanks

**Comment by bradleyrichter** [comment]
@jenn-rhim for a Cyrillic compatible Poppins alternative...

**Comment by ademaro** [comment]
Is it really so difficult to connect a second font for Cyrillic? Add at least Open Sans as a second font. Issue has been open for many years...

**Comment by jenn-rhim** [comment]
Have determined a font replacement of Poppins to support Cyrillic alphabets to be 'Manrope'.  
Evaluation and screen testing is located here:
https://www.figma.com/file/y2jrcOMPbctWsPCI8UY8fP/Cyrillic-Font-tests?node-id=11%3A2

Thanks to @aguscruiz.  cc: @rebron @petemill

**Comment by iefremov** [comment]
@jenn-rhim do I understand correctly we completely replace Poppins with Manrope across the browser? I've seen in Figma that texts in bolds are pretty different with Poppins vs Manrope.

**Comment by LaurenWags** [comment]
@petemill could you please provide a test plan for this one? Marking as `QA/Blocked` for now 👍🏻 

cc @rebron @kjozwiak

**Comment by boocmp** [comment]
@LaurenWags 

Launch the browser in Cyrillic (by passing --lang=ru_RU in the command line or by changing the system language)

In the settings, check DevTools resources/fonts/poppins.css. It should actually refer to the manrope font instead of poppins.
![Manrope](https://user-images.githubusercontent.com/73575789/200461590-d8801f6b-2e9d-4baa-aa26-8dd5fd803ef3.png)

Check the screenshots, they should look the same.
![Settings_get_started](https://user-images.githubusercontent.com/73575789/200461595-7326ab79-249c-44f3-80b7-286e3a1993e6.png)
![Brave_history](https://user-images.githubusercontent.com/73575789/200461579-7151cd28-113a-453e-a9a0-239a46629b4c.png)
![Brave_rewards](https://user-images.githubusercontent.com/73575789/200461583-9c16c2b9-11e1-494c-8ec6-1fcfc4cdecf3.png)
![Brave_wallet](https://user-images.githubusercontent.com/73575789/200461585-2a41491a-df95-46a3-9823-509552a95b86.png)
![Incognito](https://user-images.githubusercontent.com/73575789/200461589-d49735c8-b393-421d-9b89-8915106bda6a.png)
![NTP](https://user-images.githubusercontent.com/73575789/200461593-613a0d64-1ab2-45af-9510-9e8081461fd9.png)

**Comment by LaurenWags** [comment]
great, thanks @boocmp! we will look on this one shortly 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.46.102 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```
