### ISSUE TITLE
Proxy sb-ssl.google.com through sb-ssl.brave.com

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#4328]
Test Plan specified here: https://github.com/brave/brave-core/pull/2377

**Comment by gadfsgagfaq435** [comment]
(sorry if this is the wrong place to ask just delete the comment)

i just saw this by pure chance and was shocked and instantly disabled safebrowsing in brave
my question: if this is fixed will safebrowsing be completely "contact-free" from google in brave ?
so will my ip-adress and/or the websites i visit ever reach google if i use safe-browsing in brave ?
(i know right now it definitly does once i download an .exe according to this "bug" but i mean once this issue is fixed)

thanks.

**Comment by diracdeltas** [comment]
@gadfsgagfaq435 Google Safebrowsing for URLs doesn't send the website to Google, only a hash prefix if there is a potential match: https://developers.google.com/safe-browsing/v4/urls-hashing. In most cases it won't need to send anything.

For downloads, it appears to send more info (which we weren't aware of til now): https://cs.chromium.org/chromium/src/components/safe_browsing/proto/csd.proto?sq=package:chromium&dr=CSs&g=0&l=443-718

We are going to make sure all these requests are proxied so Google at least does not get IP. For downloads, we are going to at least disable SB in Tor mode and maybe also in normal mode, not sure yet.

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.64.75 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523



- Verified test plan from https://github.com/brave/brave-core/pull/2377


![image](https://user-images.githubusercontent.com/38657976/57624164-ff548800-75ae-11e9-9a80-2b648a3f345e.png)
