### ISSUE TITLE
Payment "receipts" cashed in between the 1st and 5th of the month do not appear in ad totals

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#4330]
## Description 

Take the following case:

1.  A user signs up for Brave Ads on 4/25.
2. Every day until 4/30 (6 days), they see 4 ads, at 0.25BAT/each
3. Payment tokens/receipts are cashed in 5/2.
4. Every day from 5/1 until EOD 5/4 (4 days), he sees 4 ads, at 0.25BAT/each
5. The user wakes up and logs in on 5/5.

Because the user is supposed to get paid for payment tokens cashed in from 4/1 to EOD 4/30, he will not have anything coming to him for the payout on 5/5.  Because of this, his settings view should have 4 * 6 + 4 * 4 = 40 views, 40 * 0.25 = 10 BAT on the morning of 5/5.  The user is not seeing the BAT from 4/25 to 4/30 in the totals because those were “cashed in” before 5/5.

## Steps to Reproduce

   1. Roll clock to 4/25
   2. View ads
   3. Roll forward a week to cash in
   4. Roll clock to 5th

## Actual result:
The user is not seeing total views and BAT accumulated from ads seen 4/25 to 4/30.

## Expected result:
The user is not seeing total views and BAT accumulated from ads seen 4/25 to 4/30 if those are not going to be included in his next payout on 5/5.

## Brave version (brave://version info)
0.63.55.

## Version/Channel Information:
All channels

**Comment by tmancey** [comment]
**Proposed Ads Serve Solution:**

Update `POST /confirmation/payment/{paymentId}` Ads Serve call to return `earnings` in the JSON response if the returned `status` was `ok`, i.e:

```
{
  "status": {
    "status": "ok"
  },
  "adsEarnings": {
    "currentCycle": {
      "estimatedRedemptionValue": "0.55",
      "transactionCount": "11"
    },
    "due": {
      "redemptionValue": "7.25",
      "transactionCount": "145"
    }
  }
}
```

`currentCycle` are tokens redeemed between the 1st of the current month and present day.

`due` are tokens redeemed on or before the last day of the previous month which will be paid out in an Ads grant on the 5th of the month.

**Proposed Client-Side Solution**

`Estimated earnings this cycle` which can be calculated with: `estimatedRedemptionValue` from the `currentCycle` + `Transaction history since last successful redemption (with redemption value > 0.00)`

Between the 1st and 5th of the month show `Ads grant of 1.25 BAT is due for payment on the 5th` which can be calculated with: `due/redemptionValue`

Between the 6th and the last day of the month show `Payment date Monthly, 5th`

`Ad notifications received` which can be calculated with `transactionCount` from the `currentCycle` + `Count of transaction history since last successful redemption (with redemption value > 0.00)`

_Pros_:
- Users will see the Ads grant due for payment on the 5th (highly requested by the community)
- Users will see accurate `Estimated earnings for this cycle` and `Ad notifications received` even if tokens were redeemed after the end of month cut off date
- Reduces the size of Confirmations local data cache which we need to consider for mobile devices

_Cons_:
- After a user upgrades the Ads UI panel will still exhibit the issue until the next token redemption which is made every ~7 days, however if it is agreed we could force a one off redemption within ~1 day or less

**Comment by jsecretan** [comment]
The alternative here is to cache the the timestamp of cashing in payment receipts within the confirmations object and using that to determine the starting timestamp.  The downside is that for anybody already affected, nobody's balance will pop back into view.

**Comment by tmancey** [comment]
*Proposed Client-Side Solution:"

Add `redemption_date_in_seconds` key-value pair to `transactions` key to persist the current time in seconds when tokens are successfully redeemed with the Ads Serve.

```
{
  "transaction_history": {
    "transactions": [
      {
        "confirmation_type": "view",
        "estimated_redemption_value": 0.05,
        "timestamp_in_seconds": "13200508360",
        "redemption_date_in_seconds": "13200512000"
      },
      {
        "confirmation_type": "click",
        "estimated_redemption_value": 0,
        "timestamp_in_seconds": "13200508380",
        "redemption_date_in_seconds": "13200512000"
      }
    ]
  }
}
```

`Estimated earnings this cycle` which can be calculated with `Estimated redemption value of unredeemed tokens` + `Transaction history for tokens redeemed between the 1st of the current month and present day`.

Payment date can be contextual in that between the 1st and 5th of the month show `Ads grant of 1.25 BAT is due for payment on the 5th` which can be calculated with `Transaction history for tokens redeemed for the previous month`, then between the 6th and the last day of the month show `Payment date Monthly, 5th`.

`Ad notifications received` which can be calculated with count of unredeemed tokens + `Count of transaction history for tokens redeemed between the 1st of the current month and present day (if estimated redemption value is greater than 0)`.

_Pros_:
- Users will see the Ads grant total due for payment on the 5th (highly requested by the community)
- Users will see `Estimated earnings for this cycle` and `Ad notifications received` even if tokens were redeemed after the end of month cut off date

_Cons_:
- After upgrading, the Ads panel UI will not reflect the correct values for legacy transactions
- If a user deletes `Defaults/rewards_service/confirmations.json` (or their user profile) transaction history will be lost and the Ads panel UI will be reset to 0

**Comment by jsecretan** [comment]
So, per @davidtemkin, the "fix" here will also involve modifying the way the display conveys what has been paid so far and what will be paid in the future:

1. "Current earnings this month" becomes "Estimated pending earnings".
2. "Payment date" makes an actual date, and becomes aware of what's been cashed in in time.
3. "Ad notifications received" becomes "Ad notifications pending payment" or something else to be confirmed.

**Comment by jsecretan** [comment]
Calculating the next payment date should look as follows.  When the browser calls to get total redeemed payment tokens, it will have that broken out by month.  So, depending on the time of the month:

1st-5th (23:59): If last month had cashed in tokens > 0, then show next payment date as this month.
6th-end of month: If this month has any cashed in payment tokens, then show next payout date as next month.
Else if this month has no cashed in payment tokens, but calculated next cash in date is still this month, then show next payout date as next month.
Else if this month has no cashed in payment tokens, and calculated next cash in date is not in this month, then next payment date is month *after* next.

So example if it is the 15th of May, and no cashed in tokens, and next cash in date is May 22nd, next payment date is 5th of June.
But if it is the 28th of May, no cashed in tokens and next cash in date is 5th of June, next payment date would say 5th of July.

**Comment by jenn-rhim** [comment]
Here is the UI reflecting the changes. Please note that the 'ads earnings' are to be 'ads rewards'. @mandar-brave 

![Screen Shot 2019-05-29 at 11 54 22 AM](https://user-images.githubusercontent.com/4369856/58583384-bafcf500-8208-11e9-94f5-0ddd2c731934.png)

**Comment by jsecretan** [comment]
So @jenn-rhim just as a note, we are going to leave off the "Ad pages viewed this month" for another story.  We had left that off originally to save time and complexity, and want to make sure this story is as focused as possible.

**Comment by srirambv** [comment]
* Verification passed on 

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux

* Verified test plan from https://github.com/brave/brave-core/pull/2609
