### ISSUE TITLE
Document in the FAQ why Firefox or its forks are not used as a base for Brave instead of Chromium

### ISSUE THREAD

**Issue by KOLANICH** [brave/brave-browser#4477]
## Description 
It is completely unclear why Chromium was preferred against Firefox. Firefox currently is one of the most privacy-friendly browsers: it has prefs to disable features used for tracking and it has prefs enchancing privacy. Its forks, especially Tor Browser, are even more privacy-friendly. So if you based your work on them you would had got these features already implemented.

Also in my experience (2 GiB of RAM on my PC) FF (and even Chrome) consumes less RAM than Brave and is much less laggy.

**So it is completely unclear why Chromium is preferred over Firefox and it would be nice to have the rationale for it being placed into the FAQ.**

## Steps to Reproduce
Visit https://brave.com/faq/

## Actual result:
Brave is based on Chromium. Rationale for that is missing from the FAQ.

## Expected result:
Rationale for the choice of the base is available in the FAQ.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Any

## Version/Channel Information:
Any

- Yes.
- Yes.
- Yes.
- Yes.

## Other Additional Information:

- No.
- No.
- N/A

## Miscellaneous Information:
N/A

**Comment by bsclifton** [comment]
Looks like we DID have info about this previously... but it was fairly limited:
https://web.archive.org/web/20180320170224/https://www.brave.com/faq/
> **Why aren’t you using Mozilla’s Gecko engine on laptops?**
We were, under a partially sandboxed, multi-process architecture called Graphene. But we did a careful head-to-head comparison and by every measure, Electron/chromium won.

This was removed when we went from Muon (fork of Electron) to Brave Core. It has been answered on Reddit, but we could use help capturing this for our FAQ:
https://www.reddit.com/r/brave_browser/comments/9l0gnx/if_founder_of_brave_is_originated_from_mozilla/e74fcuo/

**Comment by Brave-Matt** [comment]
Is this article still desired/up for grabs? I'd actually started drafting something similar to this in HC already -- would be happy to finish it :)

**Comment by bsclifton** [comment]
@Brave-Matt absolutely- all yours! 😄

**Comment by KOLANICH** [comment]
Any progress on this?

**Comment by WeaponXII** [comment]
@bsclifton Is this content still desired? If so, I'd like to contribute a short and to the point "Why is Brave Built on Chromium?" section for the faq.

**Comment by bsclifton** [comment]
@WeaponXII sure - that would be great 😄

**Comment by WeaponXII** [comment]
# Why is Brave Built on Chromium?
In 2015, before it was released Brave was actually built on Gecko. However it lacked important product features and we ultimately chose not to release this version. Our first release of Brave was built on Electron, but due to how Electron was built, developing updates was slow and led to broken features. We then developed [Brave Core](https://github.com/brave/brave-core), a Chromium fork for Brave with fewer bugs, full extension support, quicker Chromium upgrades and better code-sharing with Android. There are currently no benefits to rebasing Brave on an alternative engine.

**Comment by WeaponXII** [comment]
@bsclifton  I hope submitting it here is appropriate, the website doesn't seem to have a public repo. I summarized a few of Brendan Eich's answers to this question from Twitter over the years to make it informative while still being concise.

**Comment by KOLANICH** [comment]
>However it lacked important product features

Which ones exactly, and why were it not possible to implement them above Firefox.

>There are currently no benefits to rebasing Brave on an alternative engine.

Brave has given identical fingerprints to Chrome. Brave lacks RFP features available in Firefox under about:config pref `privacy.resistFingerprinting`, i.e. Brave surrenders the list of sound devices. Brave has no such a rich configuration as Firefox, where I can disable most of WebMalware (WASM, WebGL, Service Workers, other inherently harmful specs pushed by Googlag) antifeatures.

**Comment by WeaponXII** [comment]
> Which ones exactly, and why were it not possible to implement them above Firefox.

@KOLANICH In 2015 the most impactful features Gecko lacked were a DRM-solution and web compatibility. Now in 2021 Gecko's web compatibility issues have grown which turns away users, leading to a vicious cycle of fewer developers testing new features on Gecko because there are fewer users, which leads to more web compatibility issues and turns away more users. Rebasing on Gecko today would make Brave unusable for many current Brave users.

If you're interested in reading more about the early days of Brave,  [this blog post](https://brave.com/the-road-to-brave-one-dot-zero/) covers it in more detail. 

>Brave has given identical fingerprints to Chrome. Brave lacks RFP features available in Firefox under about:config pref `privacy.resistFingerprinting`, i.e. Brave surrenders the list of sound devices. Brave has no such a rich configuration as Firefox, where I can disable most of WebMalware (WASM, WebGL, Service Workers, other inherently harmful specs pushed by Googlag) antifeatures.

This may be out of scope for this issue. If you have suggestions for Brave features, [Brave Community](https://community.brave.com) is a better fit to discuss them. Do keep in mind Brave is unlikely to rebase on an alternative engine at this time.

**Comment by KOLANICH** [comment]
Thanks for the info.

**Comment by bsclifton** [comment]
Closing as this is basically addressed above. If we find a good way to incorporate in our website, we'll try to do so! Thanks 😄

**Comment by bsclifton** [comment]
@aocorporation thanks for raising - I worked with @rmcfadden3 to get that updated on our site 😄 

Please see https://brave.com/faq/#chromium-gecko
