### ISSUE TITLE
Tweet is missing hashtag

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4555]
The current tweet is missing hashtag "#TipWithBrave" is missing from the tweet-string. Please add. 

cc @emerick @NejcZdovc @bradleyrichter

**Comment by mandar-brave** [comment]
Lets fix ahead of the developer builds. Thank you!

**Comment by emerick** [comment]
@mandar-brave Can we get that added to the spec? I don't think I ever saw it mentioned, but could be I just missed it!

**Comment by mandar-brave** [comment]
Done!

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.107 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2495
Tweet generated with tipping Twitter user from panel:
![Screen Shot 2019-07-11 at 11 31 26 AM](https://user-images.githubusercontent.com/28145373/61071074-29bf9780-a3de-11e9-8e52-fd123d3d09de.png)

Tweet generated when tipping a specific tweet using inline tip button:
![Screen Shot 2019-07-11 at 11 32 01 AM](https://user-images.githubusercontent.com/28145373/61071092-35ab5980-a3de-11e9-9520-5dea29078da5.png)

Tweet generated when tipping a YT video from panel (unable to check YT channel due to #5217):
![Screen Shot 2019-07-11 at 1 06 44 PM](https://user-images.githubusercontent.com/28145373/61071117-45c33900-a3de-11e9-81c3-f8bfe148fda2.png)

Tweet generated when tipping a Twitch channel from panel:
![Screen Shot 2019-07-11 at 1 07 12 PM](https://user-images.githubusercontent.com/28145373/61071133-4eb40a80-a3de-11e9-9c3f-07ae2eccf290.png)

Tweet generated when tipping a Twitch video from panel:
![Screen Shot 2019-07-11 at 1 07 33 PM](https://user-images.githubusercontent.com/28145373/61071142-55428200-a3de-11e9-8921-223d864dd033.png)

Tweet generated when tipping a regular site from panel:
![Screen Shot 2019-07-11 at 1 08 02 PM](https://user-images.githubusercontent.com/28145373/61071174-68ede880-a3de-11e9-8563-9767ef69afc2.png)
