### ISSUE TITLE
Verified pubs image is not displayed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4557]
## Description 

Verified pubs image is not displayed in BR panel

## Steps to Reproduce

   1. Enable rewards on `0.67.14`
   2. Upgrade to `0.67.55`
   3. Open verified twitter pubs in new tab
   4. Click on BR panel

## Actual result:

Verified pubs image is not displayed in BR panel

![image](https://user-images.githubusercontent.com/38657976/58272822-f9c82080-7dac-11e9-8175-1918a4e7cb7f.png)

Verified pubs image is not displayed in the rewards banner

![image](https://user-images.githubusercontent.com/38657976/58273141-abffe800-7dad-11e9-8486-3285549273f4.png)

Verified pubs image is not displayed in the Tips panel

![image](https://user-images.githubusercontent.com/38657976/58274311-39dcd280-7db0-11e9-9367-68501b2c840d.png)

## Expected result:
verified pubs image should be displayed in BR panel

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc : @brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment]
I was able to reproduce this in the following way:
Install Nightly, Enable Rewards.
Navigate to twitter page for user who is not yet verified. (I used myself)
I verified my twitter acct, and waited a few hours. Later, I clicked on 'check again...'.
When the publisher list which contained my acct was pulled, I got my verified check mark but not my favicon - I still see the generic twitter one. Even after refreshing the page, opening a new tab and navigating again - I still retain the generic twitter favicon on panel and brave://rewards page.
Note - @kjozwiak was already verified when I first installed the build and got my list - so I see his favicon instead of the generic one.
![Screen Shot 2019-05-23 at 4 47 03 PM](https://user-images.githubusercontent.com/28145373/58285322-87d6e380-7d7a-11e9-9b08-8b3a1b97547f.png)
![Screen Shot 2019-05-23 at 4 47 13 PM](https://user-images.githubusercontent.com/28145373/58285328-89a0a700-7d7a-11e9-8132-ef2497eb9544.png)

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya could you reproduce this one clean profile? I think this one only happens if publisher is already in the database and then they become verified

**Comment by NejcZdovc** [comment]
Problem with this one is that once site is in the DB we don't try to pull publisher image. What we need to do here is check if verified status changed and if so we need to pull the image

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc On the clean/upgraded profile, it works fine I am unable to reproduce the issue in 0.69.128
 ![image](https://user-images.githubusercontent.com/38657976/65504486-bc9fa680-dee4-11e9-8bcd-72feb1913c8f.png)

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible in `Windows 10 x64 -1.16.x`

```

Brave | 1.16.23 Chromium: 86.0.4240.30 (Official Build) nightly (64-bit)
-- | --
Revision | 09f50eb5535879364cf00e72653462a509ef6bdc-refs/branch-heads/4240@{#552}
OS | Windows 10 OS Version 1903 (Build 18362.1016)


```
![image](https://user-images.githubusercontent.com/38657976/93561499-ebd6df80-f9a1-11ea-803f-df2451c440ba.png)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.34 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified that on a clean profile with 1.17.x the verified Twitter publisher's favicon displays in the panel if the publisher does not have a custom favicon:
<img width="1198" alt="Screen Shot 2020-10-15 at 12 42 55 PM" src="https://user-images.githubusercontent.com/28145373/96160532-17d37b00-0ee4-11eb-9342-73e05f05d337.png">

If the verified Twitter publisher has a custom favicon for their tipping banner, that displays in the panel instead of the Twitter favicon. Per internal discussions this is expected.
<img width="1194" alt="Screen Shot 2020-10-15 at 12 43 29 PM" src="https://user-images.githubusercontent.com/28145373/96160660-405b7500-0ee4-11eb-9b23-83a263f12b21.png">
<img width="1196" alt="Screen Shot 2020-10-15 at 12 43 38 PM" src="https://user-images.githubusercontent.com/28145373/96160663-418ca200-0ee4-11eb-8946-d13a0e7c505d.png">

Confirmed non-verified Twitter publishers still show generic Twitter icon:
<img width="1193" alt="Screen Shot 2020-10-15 at 12 45 48 PM" src="https://user-images.githubusercontent.com/28145373/96160738-5d904380-0ee4-11eb-8fb1-f912544fd4ef.png">

Also, if you experienced this issue prior to 1.17.x, meaning you visited a verified Twitter publisher with 1.16.x or before, you will still see the generic twitter icon in the panel as the panel cache does not expire. Per internal discussions this will be resolved with https://github.com/brave/brave-browser/issues/6059:
<img width="1195" alt="Screen Shot 2020-10-15 at 12 39 23 PM" src="https://user-images.githubusercontent.com/28145373/96160882-8dd7e200-0ee4-11eb-89f7-8d034cacac86.png">
