### ISSUE TITLE
Tweet on tip from panel uses name instead of Twitter handle

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4597]
Currently when the user tweets out, we are using the profile-name instead of using the twitter handle. See error image: 
![image](https://user-images.githubusercontent.com/35932307/58344830-9b7e5a80-7e0b-11e9-98b3-3f026dc71437.png)

should be @brave (handle)  instead of Brave Software (text)

cc @emerick @davidtemkin

**Comment by mandar-brave** [comment]
STR: this issue happens only via the panel!
So go to any verified twitter account on the panel, tip via BAT panel.
Go through the process and then tweet; the tweet should use a handle @ vs. using the profile name.

@NejcZdovc

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.107 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2502
* Encountered already logged issue https://github.com/brave/brave-browser/issues/4586 when checking that tweeting about YT and Twitch tips still works.
* Verified that I am able to tweet about regular site tips as well.
Tipping Twitter user from Panel and selecting tweet button from Thank You banner, this is the tweet that's generated:
![Screen Shot 2019-07-11 at 11 31 26 AM](https://user-images.githubusercontent.com/28145373/61070676-45766e00-a3dd-11e9-977c-a0d5aa0ce373.png)

Tipping Twitter user from in-line tip button and selecting tweet button from Thank You banner, this is the tweet that's generated:
![Screen Shot 2019-07-11 at 11 32 01 AM](https://user-images.githubusercontent.com/28145373/61070705-51623000-a3dd-11e9-9fee-d07946a62b4d.png)

Tipping YT video from panel (unable to tip YT channel correctly due to #5217) and selecting tweet button from Thank You banner, this is the tweet that's generated:
![Screen Shot 2019-07-11 at 1 06 44 PM](https://user-images.githubusercontent.com/28145373/61070737-63dc6980-a3dd-11e9-9f97-8cb1fe3088b5.png)

Tipping Twitch channel from panel and selecting tweet button from Thank You banner, this is the tweet that's generated:
![Screen Shot 2019-07-11 at 1 07 12 PM](https://user-images.githubusercontent.com/28145373/61070756-6b9c0e00-a3dd-11e9-9ae1-66a8f184e37c.png)

Tipping Twitch video from panel and selecting tweet button from Thank You banner, this is the tweet that's generated:
![Screen Shot 2019-07-11 at 1 07 33 PM](https://user-images.githubusercontent.com/28145373/61070786-79ea2a00-a3dd-11e9-859c-15a58d039ad6.png)

Tipping regular site from panel and selecting tweet button from Thank You banner, this is the tweet that's generated:
![Screen Shot 2019-07-11 at 1 08 02 PM](https://user-images.githubusercontent.com/28145373/61070798-81a9ce80-a3dd-11e9-94df-496c81508ca2.png)
