### ISSUE TITLE
Update welcome experience layout

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#4657]
Need to open up the Welcome Experience layout and break it out of the modal cards. This will help with dark mode adoption, responsiveness, larger communication and gives us more room to breathe on smaller screens. 

![Welcome Light](https://user-images.githubusercontent.com/29072694/58682028-d3156700-8323-11e9-82f8-4ed1630e0281.jpg)
![Welcome Dark](https://user-images.githubusercontent.com/29072694/58682029-d3156700-8323-11e9-90d7-92104d370aca.jpg)

**Comment by srirambv** [comment]
Personally I feel the dark mode looks really harsh on screen.There are way too many dark elements and the orange button on dark background looks really harsh. Instead of black background we can probably go with softer gray colour which would still give the dark feel but not as bad as it looks in the screenshot.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/2909
