### ISSUE TITLE
User wallet: Uphold Connect

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4774]
Build a browser side user claim wallet using existing Uphold Connect functionality on Brave Rewards.

States:
- Brave Rewards default state (uni directional wallet)
- Uphold Connected + Unverified state (Uphold wallet but no KYC)
- Uphold Connect + Verified state (Uphold wallet but KYC)
- Uphold Disconnected - wallet token expired or was manually disconnected
- Uphold Re-Authorize - wallet token needs re-auth to reset BAT limits for transfer

@alexwykoff 
@jenn-rhim please update UI/UX for these states.

**Comment by mandar-brave** [comment]
![image](https://user-images.githubusercontent.com/35932307/59899698-8533d200-93aa-11e9-9e85-f8cf07e0cd67.png)

The three operating states are defined above.
There are two states where Uphold will show disconnected;

a) when the auth_token has expired
b) when the BAT limits per transaction have been hit

When this happens;
![image](https://user-images.githubusercontent.com/35932307/59899756-bca27e80-93aa-11e9-9075-00ea0fa0067b.png)

Edit: considering the last state of the wallet when disconnected is irrelevant, the bottom area should be gray (like the default BR state)

**Comment by srirambv** [comment]
@mandar-brave @jenn-rhim  Can we use `Re-authenticate` instead of `Reconnect`? Reconnect would mean that the Uphold wallet is removed and needs to be readded which might be confusing. Re-authenticate is what is happening in the step not reconnecting

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2696
* Verified manually Disconnecting from Uphold resulted in the 'Disconnected' state. Was unable to test the transaction limit due to #5884 
* Verified the scenarios below:

1a. **PASS** Clean profile - Unconnected (never connected) - With 1a/1b, verified that if a user never follows the Verify Wallet flow to uphold and signs up or connects any account, they can still do the following:
- Verified able to one time tip verified pubs, monthly tip verified pubs, and auto contribute to verified pubs. 
- Verified able to claim UGP grant by completing captcha.
- Verified can claim ads earnings grant by completing captcha.
- Verified unable to access old add funds UI.
- Note, clean install had restored a previous anon wallet with BAT.

1b. **PASS** Upgrade profile - Unconnected (never connected):
- Verified able to one time tip verified pubs, monthly tip verified pubs, and auto contribute to verified pubs. 
- Verified able to claim UGP grant by completing captcha.
- Verified can claim ads earnings grant by completing captcha.
- Verified unable to access old add funds UI.
- Note - upgrade profile had BAT in anon wallet prior to "upgrade".

2a. **PASS** Clean profile - Connected, but not KYC'd - With 2a/2b, verify the following when a user follows Verify Wallet flow and signs up with Uphold but never kyc's or logs in to uphold with an account that is not KYC'd:
- Verified any BAT in brave://rewards prior to connecting a non-KYC'd uphold account is NOT moved to your Brave Browser card in Uphold.
- Verified able to add crypto only (not fund in any other way) in Uphold and balance updates accordingly in brave://rewards.
- Verified tips, ac, etc are taken from the anon card (your existing BAT) before your Uphold BAT (Brave Browser card).
- Verified able to one time tip verified pubs, monthly tip verified pubs, and auto contribute.
- Verified able to claim UGP grant by completing captcha. UGP grant does not move to Brave Browser card.
- Verified can claim ads earnings grant by completing captcha. Ad grant does not move to Brave Browser card.
- Note, clean install had restored a previous anon wallet with BAT.

2b. **PASS** Upgrade profile - Connected, but not KYC'd:
- Verified any BAT in brave://rewards prior to connecting a non-KYC'd uphold account is NOT moved to your Brave Browser card in Uphold.
- Verified able to add crypto only (not fund in any other way) in Uphold and balance updates accordingly in brave://rewards.
- Verified tips, ac, etc are taken from the anon card (your existing BAT) before your Uphold BAT (Brave Browser card).
- Verified able to one time tip verified pubs, monthly tip verified pubs, and auto contribute.
- Verified able to claim UGP grant by completing captcha. UGP grant does not move to Brave Browser card.
- Verified can claim ads earnings grant by completing captcha. Ad grant does not move to Brave Browser card.
- Note - upgrade profile had BAT in anon wallet prior to "upgrade".

3a. **PASS** Clean profile - Fully Verified/KYC'd - With 3a/3b, verify the following items when a user follows the Verify Wallet flow and KYC's with uphold/signs in with verified uphold account:
- Verified any BAT in brave://rewards prior to connecting a KYC'd uphold account is moved to your Brave Browser card in Uphold.
- Verified able to add funds in Uphold and balance updates in brave://rewards .
- Verified able to one time tip verified pubs, monthly tip verified pubs, and auto contribute.
- Verified able to claim UGP grant by completing captcha. UGP grant does not move to Brave Browser card.
- Verified can claim ads earnings grant by completing captcha. Ad grant does not move to Brave Browser card (will in the future if you are KYC'd).
- Note, clean install had restored a previous anon wallet with BAT.

3b. **PASS** Upgrade profile - Fully Verified/KYC'd:
- Verified any BAT in brave://rewards prior to connecting a KYC'd uphold account is moved to your Brave Browser card in Uphold.
- Verified able to add funds in Uphold and balance updates in brave://rewards .
- Verified able to one time tip verified pubs, monthly tip verified pubs, and auto contribute.
- Verified able to claim UGP grant by completing captcha. UGP grant does not move to Brave Browser card.
- Verified can claim ads earnings grant by completing captcha. Ad grant does not move to Brave Browser card (will in the future if you are KYC'd).
- Note - upgrade profile had BAT in anon wallet prior to "upgrade".


Verified UI for the various states:
Brave Rewards default state (uni directional wallet)
![Screen Shot 2019-09-03 at 9 22 04 PM](https://user-images.githubusercontent.com/28145373/64220031-e3466080-ce95-11e9-8c94-059d618cf53e.png)

Uphold Connected + Unverified state (Uphold wallet but no KYC)
![Screen Shot 2019-09-03 at 9 22 32 PM](https://user-images.githubusercontent.com/28145373/64220036-e8a3ab00-ce95-11e9-9a57-8c205e8cc1b9.png)

Uphold Connect + Verified state (Uphold wallet but KYC)
![Screen Shot 2019-09-03 at 9 21 21 PM](https://user-images.githubusercontent.com/28145373/64220041-ed685f00-ce95-11e9-8c73-47c2b08d9685.png)

Uphold Disconnected - wallet token expired or was manually disconnected
![Screen Shot 2019-09-03 at 9 24 01 PM](https://user-images.githubusercontent.com/28145373/64220043-f22d1300-ce95-11e9-920e-0cc2f8436fc0.png)
