### ISSUE TITLE
Ping server for update check stat

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4835]
We need to check such edge cases when app is backgrounded and etc

**Comment by emerick** [comment]
In browser-android-tabs:

- The stats updater is called every 5 minutes to perform a stats update check
- In addition to this periodic update, the stats updater is called in the following scenarios:
   - on application startup (in `ChromeBrowserInitializer.java`)
   - on application update (in `PackageReplacedBroadcastReceiver.java`, but this is commented out)
   - on application resume (in `ChromeActivity.java`)

In brave-core:

- The stats updater is also called every 5 minutes to perform a stats update check, so doesn't seem like this setting needs to change for Android
- Since our service handles the startup and periodic 5-minute pings (and since the application update ping is commented out in browser-android-tabs), the only additional event we need to handle in brave-core is application resume. We'll do this by making a JNI call in `BraveActivity.java` to start and stop the stats updater service, since the stats updater service sends the ping immediately on startup.

cc: @SergeyZhukovsky @bbondy

**Comment by SergeyZhukovsky** [comment]
Sounds good as to me. @bbondy do you have any comments about the above?
