### ISSUE TITLE
Crash in brave_browser_tests in linux debug build

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#486]
Most of debug build browser tests in linux are crashed due to below.

```
[22219:22219:0705/094946.074225:FATAL:notification_platform_bridge_linux.cc(376)] Check failed: clean_up_on_task_runner_called_.
```

**Comment by garrettr** [comment]
I was unable to reproduce on Ubuntu 16.04; instead, I encountered a different set of `brave_browser_tests` crashes and filed #572. It is possible that this issue is resolved, or it may be obscured by the different set of crashing browser tests. Once #572 is resolved I will return to this issue and verify.

**Comment by garrettr** [comment]
All browser tests are passing on Linux now that #572 is resolved. Closing because I cannot reproduce the original issue.
