### ISSUE TITLE
Dark mode for new tabs page settings

### ISSUE THREAD

**Issue by imptrx** [brave/brave-browser#5014]
## Description 
New tabs page's settings menu should adjust itself based on the user's currently set theme, whether it be `Light`, `Dark` or the theme set on the OS level. 
Currently, the settings menu will look the same no matter what. 

## Design
The Dashboard Settings menu should support dark theme set at the OS level:
![r0 background images dark theme](https://user-images.githubusercontent.com/2388823/58124541-52d46080-7bc3-11e9-88b4-47ee2b40e8e9.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.97 Chromium: 77.0.3865.65 (Official Build) beta (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3115

**Comment by btlechowski** [comment]
This issue is still reproducible on 0.69.128

![image](https://user-images.githubusercontent.com/34715963/65335715-383be380-dbc5-11e9-8ecc-0a72be798968.png)

It is not reproducible on 0.70.99
![image](https://user-images.githubusercontent.com/34715963/65335785-5c97c000-dbc5-11e9-9ad7-eb822304f55a.png)

Tested Windows and Linux.

@kjozwiak I suggest we move the milestone to 0.70.x

**Comment by kjozwiak** [comment]
Seeing the same thing as @btlechowski as per https://github.com/brave/brave-browser/issues/5014#issuecomment-533581546. @rebron @bsclifton do know if this landed in `0.69.x`? As @btlechowski mentioned, the fix seems to be working under `0.70.99 CR: 77.0.3865.90` but not under `0.69.128 CR: 77.0.3865.75`. Example:

Using `0.69.128 CR: 77.0.3865.75`:

![NTPtheme](https://user-images.githubusercontent.com/2602313/65346709-51d03180-dbab-11e9-9202-09352d65c760.gif)

Using `0.70.99 CR: 77.0.3865.90`:

![NTPthemeWorking](https://user-images.githubusercontent.com/2602313/65347112-47626780-dbac-11e9-861c-25d47ce7b3b2.gif)

**Comment by cezaraugusto** [comment]
changing milestones as this work landed only in 0.70.x cc @kjozwiak

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.110 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/3115 on High Sierra (no OS level dark mode)
* gifs in https://github.com/brave/brave-browser/issues/5014#issuecomment-533647022 show the fix for this issue on Mojave from @kjozwiak
