### ISSUE TITLE
Switch engine to Firefox

### ISSUE THREAD

**Issue by filips123** [brave/brave-browser#5030]
Please switch Brave's engine from Chromium to Firefox.

---

First, Firefox has improved a lot in the last years. With Quantum release, it became faster and with WebRender, it will use GPU-based rendering. It has also improved a lot on mobile. It will soon use completely new UI for mobile (Fenix). It's also a lot more customizable than Chrome and other browsers.
I understand that when Brave was first made, Firefox wasn't so good. But now, it is as good as Chromium or even better. So this should not be an excuse.

Also, even if you said that it is "independent browser", it is not. It's based on Chromium which is made and controlled by the probably biggest company in the world. And Google and privacy is not something that does not belong together.

Even if you fixed all privacy issues with Chromium, you still won't support real open web. With recent Edge's switch to Chromium, Firefox is now only independent browser who cares about the web. Almost all other browsers are based on Chromium. And this is another place where Google has a monopoly.

An example why this is bad is recent Google's ad block ban. Because Google's decision to block ad blockers, almost all browsers and users on the world now won't be able to block ads.
And this is only one example. They can also make even the worst decision which will have an impact on the whole web. Google is now able to control the whole web.

I also saw that you didn't use Firefox because of some "compatibility problems". With the usage of Chromium, you will only support incompatibilities with independent browsers, because developers will develop website only with Chromium APIs. Why do we then have W3C?

---

I think that only a good solution for this is that you switch to Firefox as Brave's engine.

Of course, you could fork Chromium and develop is as you want, but maintaining the whole browser engine would be really hard.
I know that switching the engine would require an almost complete rewrite of Brave's core. But in the long term, this would be better for you and open web. You won't have to maintain separate engine (in case of the fork) because you would be able to use privacy ready engine almost out-of-box.
And, if Firefox is good for Tor Browser, which is really anonymous and private browser, it would also be good for Brave.

---

I saw that Firefox and Gecko are not very embedding-friendly, so it is hard to make a browser that is based on them. Because of that, I created [Bugzilla suggestion](https://bugzilla.mozilla.org/show_bug.cgi?id=1549199) for supporting the easier making of custom Firefox bundles. If it will be implemented properly, it probably won't be so hard to switch Brave to it.

And you can also look to [Servo browser engine](https://github.com/servo/servo). It is a prototype web browser engine written in the Rust language and Firefox is getting some parts from it. It should also be more modular so it would be probably easier to embed it.

---

So, please make Brave decision for the open web as switch browser engine!

**Comment by nhantrn** [comment]
I would only be in favor of this if they also resurrect XUL and XPCOM. Else it wouldn't make much sense because Firefox itself is already slowly becoming Chrome. Firefox abandoned its own extension engine to adopt Chrome's web extension. Maintaining a browser take a lot of works. Just look at Microsoft, they have the expertise to continue to maintain Edge but gave up playing catch up. I'd give Mozilla few more years until they too  gave up and adopt Webkit or Blink.

Also I don't buy the opinion that adopting Chromium is somehow killing web standards. Chrome's Blink is a fork of Safari's Webkit. I still remember when Webkit was the evil du-jour and people were screaming about Apple taking over the web etc etc. Look how that turned out. There's no reason for Mozilla, if they want to, to fork Blink or Webkit and maintain it in a way they see fit.

The web standard is joinly maintained by WHATWG. Any deviation from that is going to be held up in its committees for criticism and punishment.

**Comment by tomlowenthal** [comment]
We appreciate the passion, but this isn't going to happen.

**Comment by bsclifton** [comment]
While this won't happen, we do have an issue captured as to why (tracked with https://github.com/brave/brave-browser/issues/4477). I believe @Brave-Matt will be putting together an entry for our FAQ that addresses this

**Comment by filips123** [comment]
I understand that you *had* good reasons to use Chromium when you first made Brave.
But I also want to know why you can't switch to Firefox *now* or in *the future*. I know that this would require a lot of work, but I think that it would be better in the long-term.
