### ISSUE TITLE
Add dark mode for ethereum-remote-client extension pages

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5106]
Other pages in the header when in dark mode will be dark mode, so we need it for this as well.

**Comment by bbondy** [comment]
Reverted here due to screenshots here:
https://github.com/brave/ethereum-remote-client/pull/75

Please re-land once that's fixed. Thanks!

**Comment by kjozwiak** [comment]
@ryanbr looks like dark themes are not working when using https://github.com/brave/ethereum-remote-client/releases/tag/1.0.10. Could this because we're side loading the extension and it's not picking up the themes? It doesn't matter if you you try using dark theme via `Same as macOS` or switching it to dark within `brave://settings`, you'll always get the following:

<img width="1275" alt="Screen Shot 2019-10-07 at 7 19 41 PM" src="https://user-images.githubusercontent.com/2602313/66356046-8d9f2100-e937-11e9-9eb4-f0e2ab38eb88.png">

<img width="1227" alt="Screen Shot 2019-10-07 at 7 20 30 PM" src="https://user-images.githubusercontent.com/2602313/66356049-90017b00-e937-11e9-931f-3b688d0c9a07.png">

**Comment by ryanbr** [comment]
@kjozwiak probably not my request :)

**Comment by kjozwiak** [comment]
> @kjozwiak probably not my request :)

Apologies :) Started typing "Rya" and just tabbed but picked the wrong name from the selection dropdown!

**Comment by bbondy** [comment]
re-opening because reverted

**Comment by kjozwiak** [comment]
@srirambv created https://github.com/brave/brave-browser/issues/6381 which shows several of the theming issues when using dark mode.

**Comment by bbondy** [comment]
Closing this in favor of https://github.com/brave/brave-browser/issues/6381
