### ISSUE TITLE
When navigating back new tab page doesn't load

### ISSUE THREAD

**Issue by corymcdonald** [brave/brave-browser#5249]
## Description 

On the nightly version of Chrome
Version 0.69.44 Chromium: 75.0.3770.100 (Official Build) nightly (64-bit)

## Steps to Reproduce
   0. Open multiple new tab pages
   1. go to one of the NTP tabs
   2. search
   3. press back
   4. page like this is shown

## Actual result:
![image](https://user-images.githubusercontent.com/5459225/61237011-1161bc80-a6ff-11e9-9410-94d1ecd08f00.png)

## Expected result:
![image](https://user-images.githubusercontent.com/5459225/61237024-1cb4e800-a6ff-11e9-9067-2d1ed973fb6b.png)

## Reproduces how often: 
pretty much every time

## Brave version (brave://version info)

Brave | 0.69.44 Chromium: 75.0.3770.100 (Official Build)nightly (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X
JavaScript | V8 7.5.288.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
Command Line | /Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,DesktopPWAWindowing,SimplifyHttpsIndicator --disable-features=AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication,NetworkService,UnifiedConsent --flag-switches-begin --allow-insecure-localhost --load-media-router-component-extension=1 --enable-features=NewExtensionUpdaterService,DesktopPWAWindowing,SimplifyHttpsIndicator,CastAllowAllIPs,ViewsCastDialog --flag-switches-end
Executable Path | /Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly
Profile Path | /Users/cory/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/Default

## Version/Channel Information:
Nightly

- Can you reproduce this issue with the current release?
no
- Can you reproduce this issue with the beta channel?
no
- Can you reproduce this issue with the dev channel?
no
- Can you reproduce this issue with the nightly channel?
yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by imptrx** [comment]
Looked into reproducing the issue and it seems non-deterministic in terms of when I get the "blank" menu versus "last known state of NTP." However, it does require a multiple NTPs to be open at the same time.

Just from a glance it looks some conflict/race-condition is causing our `initialize` function not called properly when we press the back button and thus we rendering solely based on the default values in redux. 

cc: @petemill @cezaraugusto

**Comment by petemill** [comment]
From what you're saying that'll most likely be caused by calling initialize only on `DOMContentLoaded`. When the JS runs, `DOMContentLoaded` may have already fired, so we would need to check if the document is ready first. Something like:

```
if (document.readyState === 'interactive') {
   initialize()
} else {
	document.addEventListener('DOMContentLoaded', initialize)
}
```

**Comment by imptrx** [comment]
@petemill I dug around a but further and it doesn't seem like it isn't a problem with initialize function as thought previously. It's defaulting our NTP settings to `false` because `chrome.getVariableValue(key)` is giving us `""` rather than true/false in the `PreferencesAPI`. Perhaps it's a race condition where we are requesting the preferences object from chrome before it exists?

**Comment by petemill** [comment]
@imptrx good find, we may have to convert to using the more-common way of setting properties on the webui, using loadTimeData, rather than setVariable. That will require a c++ change.

**Comment by imptrx** [comment]
I don't think I have the required depth to make that change 😞 - would you mind taking this over?

**Comment by petemill** [comment]
Verified that when navigating back, the page doens't initially have access to anything set via `SetWebUIProperty`. This is because we don't get the `RenderViewReady` event, since it's reused (but apparent not the WebUIProperties).

However, the page _does_ have access to properties set via `loadTimeData`, so I do suggest we refactor to using that method:

![image](https://user-images.githubusercontent.com/741836/61419629-ea002080-a8b3-11e9-9fcf-92945e165076.png)

This screenshot is some logging I added taken of a page after navigating 'back'. It shows that the page does not have access to the `adsBlockedStat` variable value at page load. If we force that to be set after some JS request for it, then the variable is accessible again. However, the page _did_ have access to the `textDirection` property of `loadTimeData` (set via `DataSource->AddString` in c++) when the navigation back occured.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.96 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Verified STR from the description

![image](https://user-images.githubusercontent.com/34715963/65101802-7ec4ee80-d9c9-11e9-88d8-aa8255d5849c.png)
