### ISSUE TITLE
Accessibility tab in DevTools doesn't show content

### ISSUE THREAD

**Issue by Muhnad** [brave/brave-browser#5267]
## Description 

Accessibility tab in DevTools doesn't show content, just show blink tab.

## Steps to Reproduce

   1. open DevTools
   2. select any HTML element
   3. select Accessibility tab in right sidebar.

## Actual result:

<img width="1664" alt="Screen Shot 2019-07-17 at 2 48 16 PM" src="https://user-images.githubusercontent.com/13405108/61377508-a4d3f280-a8a3-11e9-946c-84652b84b34d.png">

## Expected result:
<img width="1673" alt="Screen Shot 2019-07-17 at 3 01 32 PM" src="https://user-images.githubusercontent.com/13405108/61377587-cb922900-a8a3-11e9-9af4-fadf1eaf2c5e.png">

## Brave version (brave://version info)

Version 0.66.100 Chromium: 75.0.3770.142 (Official Build) (64-bit)

**Comment by pilgrim-brave** [comment]
Some brief notes:

https://cs.chromium.org/chromium/src/out/Debug/gen/devtools/accessibility/ shows the actual Javascript that runs the "Accessibility" tab in developer tools. Brave doesn't output that directory at all. (The tab itself is defined in another file, which is why it still appears in the tab bar.) Source files are in https://cs.chromium.org/chromium/src/third_party/devtools-frontend/src/front_end/accessibility/ which I do not have in my local build. I think we need to add something to brave-browser/.gclient_entries. I don't know enough about how we get npm to tell depot_tools to tell gclient to fetch things from upstream, but we are most definitely not fetching third_party/devtools-frontend/src/ and we probably should be.

**Comment by JoaoTMDias** [comment]
Is there some development on this?
I'm also facing the same issue.
I'm on version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit) (macOS Catalina)

**Comment by malcalevak** [comment]
I stumbled across this today, and I have to confess that I find it really disappointing that this is **still** not resolved.

**Comment by JoaoTMDias** [comment]
> I stumbled across this today, and I have to confess that I find it really disappointing that this is **still** not resolved.

Yeah, I went back to Chrome because of this.
@Muhnad also went back to Chrome (I emailed him and he told me the same).

**Comment by malcalevak** [comment]
I don't see anything in the changelog about it, but I happened to look the other day, and the Accessibility panel is now working in Brave!

**Comment by bsclifton** [comment]
Looks like this is resolved now- with latest release `1.3.118`. Thanks for confirming, @malcalevak 😄 
cc: @JoaoTMDias 
<img width="1067" alt="Screen Shot 2020-02-22 at 9 59 28 PM" src="https://user-images.githubusercontent.com/4733304/75103882-a47ca200-55be-11ea-80a0-34e6a7ed5eb1.png">
