### ISSUE TITLE
Chromium 76 upgrade broke Clear Browsing Data dialog

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#5277]
## Description 
Clicking on clear browsing data in the settings results in no action.

## Steps to Reproduce

   1. Open Brave
   2. Navigate to chrome://settings/privacy
   3. Click on "Clear browsing data"

## Actual result:

Nothing happens.

## Expected result:
Clear browsing data dialog pops up.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Nightly (0.69.x)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 0.67.112 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the STR from the description.
- The issue was reproducible in 0.69.77
- Verified all the items under chrome://settings/
