### ISSUE TITLE
Do not show the same ad more than once every hour

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#5281]
## Description 
Even though we now have the capability for user level frequency capping, and there are coming improvements to evening out the pacing of ad delivery, there can still be cases where either limited inventory in certain categories can make it feel like ads are repeated too often.  To help this, I am proposing that we limit repeating a campaign id to no more than once an hour.  This is not a setting transmitted in the catalog, but a hard coded browser setting.

**Comment by LaurenWags** [comment]
Confirmed with @srirambv that this was tested on mobile. Only desktop needs to be tested by QA.

**Comment by LaurenWags** [comment]
Still seeing ads for same `campaign_id` in the same hour. Will work with @tmancey when he's available. Marking as `QA/Blocked` until that is sorted.

**Comment by LaurenWags** [comment]
Per discussion in Slack, changing this to `QA/No` and `release-notes/exclude` since I'm still getting the same ad twice in a row. Per discussion with @tmancey this is most likely related to https://github.com/brave/brave-browser/issues/4207.

I have logged a follow up issue https://github.com/brave/brave-browser/issues/6447 and have a profile/logs which I can share if they'd be helpful.
