### ISSUE TITLE
Include a random delay between sending fee and tips for p2p contributions

### ISSUE THREAD

**Issue by evq** [brave/brave-browser#5334]
## Description 
Once the publishers API parts of https://github.com/brave-intl/publishers/issues/2048 are rolled out we should add a random delay between sending the fee and tip

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Can you please include the test plan?

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya added

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Verified the test plan from https://github.com/brave/brave-core/pull/3388. After tipping a verified pub in staging env there's just 3 to 4 secs of delay to reflect the 5% fee in the brave card. The delay is not Noticeable (by the time I navigate from brave://rewards to ledgers sandbox tab 3 secs will over) step 3 in the test plan says to wait until 5% fee card reflect. Is 3 to 4 sec is the expected delay?

5% fee card before tipping a verified 
![image](https://user-images.githubusercontent.com/38657976/65592717-c260bf00-dfac-11e9-98e9-f75f2410de1b.png)

5% fee card after tipping a verified pub

**Comment by NejcZdovc** [comment]
delay is random, so yeah could be 4sec as well

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3388
- https://github.com/brave/brave-browser/issues/5334#issuecomment-534961164

**Comment by kjozwiak** [comment]
@NejcZdovc did this land in `0.69.x? I'm just about to start the approval process for https://github.com/brave/brave-core/pull/3543 which has yet to uplifted so assuming the above verification for window is invalid and needs to be rechecked once https://github.com/brave/brave-core/pull/3543 lands. Clearing `QA Pass-Win64`.

@NejcZdovc please let me know if I'm wrong or have missed something 👍

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/3388 using staging env
* Verified 95% was sent first, and remaining 5% was sent with a delay instead of simultaneously as before
* Verified the 5% was displayed in the staging card as expected
<img width="1194" alt="Screen Shot 2019-10-01 at 9 25 09 AM" src="https://user-images.githubusercontent.com/28145373/65966256-d7ff3a00-e42d-11e9-9ae1-a57801f63487.png">
