### ISSUE TITLE
Mageia ISO crashes webtorrent

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#5372]
#403  Description 

Webtorrent consistently crashes while downloading a Mageia ISO.

## Steps to Reproduce

   1. Open <http://mirror.math.princeton.edu/pub/mageia/iso/7.1/torrents/Mageia-7.1-x86_64.torrent>.
   2. Start Torrent.

## Actual result:
At some point before the download has finished, the tab crashes:

![Screenshot from 2019-07-24 10-56-16](https://user-images.githubusercontent.com/167821/61816675-bc5e2e80-ae01-11e9-8272-7f4550997c34.png)

## Expected result:

Download finishes without crashing.

## Reproduces how often: 

I tried it three times on release and it failed the same way each time.

## Brave version (brave://version info)

```
Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Linux
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?

Yes

- Can you reproduce this issue with the beta channel?

No, I tried once on Beta and it worked.

- Can you reproduce this issue with the dev channel?

Yes:
![Screenshot from 2019-07-24 11-13-05](https://user-images.githubusercontent.com/167821/61817794-38597600-ae04-11e9-8dc5-adb1be67ed10.png)

- Can you reproduce this issue with the nightly channel?

No, I tried once on Nightly and it worked.

**Comment by kjozwiak** [comment]
Adding this into the `WebTorrent Revamp` board. @feross please remove if it doesn't belong in there 👍

**Comment by feross** [comment]
WebTorrent seems to be keeping the entire torrent in memory as the file is downloaded. I can see the RAM usage of the "Brave Browser Helper" process increase along with the amount of the torrent that is downloaded, which should not happen. It appears that it is being initialed with the in-memory storage mode instead of the filesystem mode.

@fmarier Can you answer the following questions to help me debug this issue:

- How much RAM does the computer where you experienced the crash have?
- Can you confirm that you are indeed using a 64-bit version of Brave?
- What OS and version are you using?
- Is your OS 32-bit or 64-bit?
- Can you re-download the Mageia Linux ISO torrent and watch the RAM usage of Brave? Does one "Brave Browser Helper" process consume up to 4 GB+ (the size of the torrent) over time, until the download completes or the browser crashes?
- If the browser crashes before the download completes, at what point does it crash? How much RAM is used by the "Brave Browser Helper" process at the time the tab crashes?

Thanks for your help!

**Comment by fmarier** [comment]
> How much RAM does the computer where you experienced the crash have?

32GB
> Can you confirm that you are indeed using a 64-bit version of Brave?

Yes, we don't have 32-bit builds of Brave for Linux.
> What OS and version are you using?
> Is your OS 32-bit or 64-bit?

Ubuntu 18.04, 64-bit

**Comment by kjozwiak** [comment]
Possibly a dupe of https://github.com/brave/brave-browser/issues/1199?

**Comment by fmarier** [comment]
> Possibly a dupe of https://github.com/brave/brave-browser/issues/1199?

No because in my case, the download never actually completes. The tab crashes before that.

**Comment by kjozwiak** [comment]
> > Possibly a dupe of #1199?
> 
> No because in my case, the download never actually completes. The tab crashes before that.

Sounds good 👍 Figured it might have been a dupe due to @feross mentioned the following above:

> WebTorrent seems to be keeping the entire torrent in memory as the file is downloaded. I can see the RAM usage of the "Brave Browser Helper" process increase along with the amount of the torrent that is downloaded, which should not happen.

**Comment by feross** [comment]
> 32GB

Okay, so running out of RAM is probably not the issue.

> Yes, we don't have 32-bit builds of Brave for Linux.

Good to know. So the 4GB address limit for 32-bit processes is not the issue.

> Ubuntu 18.04, 64-bit

I'll see if I can reproduce the issue on Ubuntu. Though it doesn't seem like it reproduces reliably.

**Comment by btlechowski** [comment]
Dupe of https://github.com/brave/brave-browser/issues/5563?

**Comment by iefremov** [comment]
I wasn't able to reproduce on Mac. @fmarier do you think this is still an issue?

**Comment by fmarier** [comment]
I tried it again and I can't reproduce the crash anymore.
