### ISSUE TITLE
"Always use Private Browsing" setting

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#540]
A user should be able to decide that they always want to use Brave in private browsing mode.

Replaces brave/browser-laptop#5132

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/default-to-open-private-window/39455?u=eljuno

**Comment by JikkuJose** [comment]
Don't understand how this wasn't thought it the very first release itself! Hope to see this soon!

**Comment by jonathansampson** [comment]
Recently requested [on Twitter](https://twitter.com/_mauriciorubio/status/1119126631644188673):

> can you please add the bookmark bar on Private window with Tor? And can you also add the option to startup the browser on Private window with Tor? #new #brave #improvement

![image](https://user-images.githubusercontent.com/815158/56415422-52a71500-6253-11e9-925e-3036c32f9d90.png)

**Comment by nmccrea** [comment]
Hi. Newcomer here.

I'm not an expert but it seems the main privacy goals of this feature (as described in brave/browser-laptop#8963) can be accomplished by going to `Settings > Privacy and Security > Clear browsing data > On exit` and selecting everything.

I think it would still be useful to have a single toggle setting that controls whether the browser launches in Private Mode or not. If I understand correctly, the above-mentioned settings actually control the behavior of non-Private Mode tabs so that they are effectively Private Mode as well, meaning the user has no access to any non-private tabs at this point without unchecking all of the above-mentioned options. This makes makes it cumbersome to switch between private and non-private browsing for contexts where one or the other is most appropriate (e.g. connecting to a trusted service).

A toggle for which mode the browser launches in would allow the user to default to Private Mode while still having the option of quickly opening a non-private tab.

---

Also, to improve the discoverability of this issue, it might be useful to add a reference to it in the following old `browser-laptop` issues, which are predecessors of this one, and showed up higher in search results for me:
 
brave/browser-laptop#8963
brave/browser-laptop#8785
brave/browser-laptop#434

**Comment by bsclifton** [comment]
Closing as a duplicate in favor of https://github.com/brave/brave-browser/issues/7564

This is already possible to implement via group policy- but there isn't a discrete setting for it (yet). See comment at https://github.com/brave/brave-browser/issues/7564#issuecomment-593776989 for more info 😄
