### ISSUE TITLE
Allow an option for 1st party blocking (ads/tracking)

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#5425]
We should have an config option (maybe not default) where we a user can toggle 1st-party tracking and/or 1st-party ads.

Would enhance the user experience for those who really don't want to be tracked or see any ads.

**Comment by BrendanEich** [comment]
Our position is we block 3rd party tracking (both scripts and storage) and ads that rely on it. We do not block 1st party ads such as on search engine result pages or in social feeds. Obviously the line is blurred due to superpowers that are both 1st and 3rd party; also cooperative copying of high entropy identifiers from 3rd party widgets (via postMessage) into 1st party cookies. But we fight these threats separately from 1st party ads, which we try to leave alone by default. So start with an option.

**Comment by cliffordp** [comment]
Example of reddit promoted post (1st party ad), which I'd prefer not to see:
![image](https://user-images.githubusercontent.com/1812179/65346076-79ba9780-dba1-11e9-9983-60cc7d62c434.png)

**Comment by BrendanEich** [comment]
https://twitter.com/BrendanEich/status/1234547752240988160 for lulz.

**Comment by cryptojennie** [comment]
+1 from r/brave_browser: 
https://www.reddit.com/r/brave_browser/comments/g6ku7o/when_will_brave_1st_party_ads_from_random/

**Comment by pes10k** [comment]
Any argument if I close this in favor of https://github.com/brave/brave-browser/issues/8475 ?

**Comment by ryanbr** [comment]
I'm fine closing this.
