### ISSUE TITLE
There is no ads enable alert, ads are enabled by default when upgrading build from 0.62.51 to 0.67.119

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5434]
## Description 

There is no ads enable alert, ads are enabled by default when upgrading build from 0.62.51 to 0.67.119

## Steps to Reproduce

Pre-requisites: VPN is connected to US region and language is set to English(US)
   1. clean profile 0.62.51
   2. enable rewards
   3. upgrade to 0.67.119

## Actual result:

There is no ads enable alert, ads are enabled by default when upgrading build from 0.62.51 to 0.67.119

## Expected result:

Ads enable alert should be shown on BAT logo and ads should not be enabled by default

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.67.119 Chromium: 76.0.3809.72 (Official Build) (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @tmancey

**Comment by LaurenWags** [comment]
Reproduces on macOS.

Brave | 0.67.119 Chromium: 76.0.3809.72 (Official Build) (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Mac OS X

Reproduces for US, UK (probably also Canada, France, Germany). 
Does NOT reproduce for Australia, New Zealand, Ireland (https://github.com/brave/brave-browser/issues/5153#issuecomment-515466207).

**Comment by LaurenWags** [comment]
Using US and UK regions:
0.62.51 enable Rewards. Upgrade —> 0.66.101, prompted about ads on BAT logo. Ads not enabled by default. Works as expected.
0.62.51 enable Rewards. Upgrade —> 0.67.119 (on `test` channel), not prompted about ads on BAT logo. Ads enabled by default. **Not working as expected**
0.62.51 enable Rewards. Upgrade —> 0.66.101, do not enable Ads. Upgrade to 0.67.119 on `test` channel. Ads still OFF. Works as expected.
0.62.51 enable Rewards. Upgrade —> 0.66.101, enable Ads. Upgrade to 0.67.119 on `test` channel. Ads are still ON. Works as expected.
Note: My expectation is that Canada, France, Germany all behave as US/UK do.

Using US region only:
0.62.51 enable Rewards. Upgrade —> 0.67.117 (on `test` channel), not prompted about ads on BAT logo. Ads enabled by default. **Not working as expected**

Using Italy region:
0.62.51 enable Rewards. Upgrade —> 0.67.119 see “Sorry” message on Ads panel. Works as expected.
0.62.51 enable Rewards. Upgrade —> 0.66.101 see “Sorry” message on Ads panel. Upgrade to 0.67.119 on `test` channel. Still see “Sorry” message. Works as expected.

Testing for Australia, NZ, Ireland is outlined here: https://github.com/brave/brave-browser/issues/5153#issuecomment-515466207

**Comment by LaurenWags** [comment]
Additional tests done - all working as expected:

1. On Windows (CAN region by @kjozwiak ) and macOS (US region by @LaurenWags ):
   * Using 0.66.101 enable Rewards. Leave Ads on. Upgrade to on `test` channel to 0.67.119. Verified Rewards still on, Ads still on. Works as expected.
   * Using 0.66.101 enable Rewards. Toggle Ads off. Upgrade on `test` channel to 0.67.119. Verified Rewards still on, Ads still off. Works as expected.
   * Using 0.66.101 enable Rewards. Toggle Rewards off. Upgrade on `test` channel to 0.67.119. Verified Rewards still off. Works as expected.
   * Using 0.66.101 Don't enable Rewards. Upgrade on `test` channel to 0.67.119. Verified Rewards still off. Works as expected.

2. On macOS (US region):
   * Using 0.62.51 don't enable Rewards. Upgrade on `test` channel to 0.67.119. Verified Rewards still off. Works as expected.

**Comment by kjozwiak** [comment]
Thanks for all the hard work on this @LaurenWags & @GeetaSarvadnya. I'm going to remove the `release/blocking` label as this is no longer blocking the `0.67.x` release. Also removing it from the `0.67.x - Release` milestone.

CCing @rebron @bsclifton & @jsecretan as this will need to get reprioritized for the next release/HF.

**Comment by bsclifton** [comment]
Is this something we should even fix? Since we've already released something which introduces this problem (requiring manual intervention), I don't think there would be enough users on the old 0.62.x version

**Comment by tmancey** [comment]
@bsclifton I would say we should fix as the changes that were required0 to fix this PR will make migration easier for future versions too.

**Comment by bsclifton** [comment]
@tmancey perfect - let's do it then 😄

**Comment by tmancey** [comment]
@LaurenWags Will be in nightly 0.70.30 or above, if we could test asap that would be great

**Comment by LaurenWags** [comment]
@tmancey I can't test on Nightly, we didn't have Nightly versions for 0.62.x. I believe the first official Nightly version was 0.64.5 and Ads were at least in Dev by that point.

**Comment by tmancey** [comment]
@LaurenWags Could we copy a 0.62.x profile from Dev/Release?

**Comment by LaurenWags** [comment]
@tmancey I can try that. I don't think it's quite the same, but it might be the closest testing that can be done in Nightly. Will check and post results.

**Comment by LaurenWags** [comment]
@tmancey Seems as though there are some issues. Specifically, some cases which were working before are now not working. Please see results below:

A. Using US and UK regions:
1. **FAILED** 0.62.51 enable Rewards. Upgrade —> 0.70.30 (copy profile from Release, rename to Nightly).
   * not prompted about ads on BAT logo but was expecting a BAT logo notification. This part is not working as expected. 
   * Ads are not enabled by default but are available to be enabled. This part is working as expected.
Note - I anticipate that Canada, France, Germany work this way as well.

B. Using Australia region:
1. **FAILED** 0.62.51 enable Rewards. Upgrade —> 0.70.30 (copy profile from Release, rename to Nightly).
   * not prompted about ads on BAT logo but was expecting a BAT logo notification. This part is not working as expected. 
   * Ads are not enabled by default but are available to be enabled. This part is working as expected.
Note - I anticipate that New Zealand and Ireland work this way as well.

C. Using Italy region:
1. 0.62.51 enable Rewards. Upgrade —> 0.70.30 (copy profile from Release, rename to Nightly).
   * see “Sorry” message on Ads panel. Ads are not available to be enabled. Works as expected.
Note - I anticipate that all non-ads enabled regions work this way as well.

D. Using US region only:
1. **FAILED** 0.66.101 enable Rewards, Ads enabled by default. Upgrade —> 0.70.30 (copy profile from Release, rename to Nightly).
   * Ads are OFF after upgrade. This is not working as expected. Ads should still be on after upgrade. This probably affects upgrades from multiple versions, not just 0.66.x
2. 0.66.101 enable Rewards, disable Ads only. Upgrade —> 0.70.30 (copy profile from Release, rename to Nightly).
   * Ads are still off after upgrade and Rewards are on. This is working as expected.
3. 0.66.101 enable Rewards, disable Rewards. Upgrade —> 0.70.30 (copy profile from Release, rename to Nightly).
   * Rewards are still off after upgrade. This is working as expected.
4. 0.66.101 do not enable Rewards. Upgrade —> 0.70.30 (copy profile from Release, rename to Nightly).
   * Rewards are still off after upgrade. This is working as expected.

**Comment by tmancey** [comment]
@LaurenWags I have created https://github.com/brave/brave-browser/issues/5531 to resolve the above issues. I now have profiles for 0.62.x and 0.63.x if that helps with testing.

**Comment by LaurenWags** [comment]
@tmancey please look at this scenario which failed from https://github.com/brave/brave-browser/issues/5434#issuecomment-517806000 as well, I don't think https://github.com/brave/brave-browser/issues/5531 covers it:



D. Using US region only:
1. **FAILED** 0.66.101 enable Rewards, Ads enabled by default. Upgrade —> 0.70.30 (copy profile from Release, rename to Nightly).
   * Ads are OFF after upgrade. This is not working as expected. Ads should still be on after upgrade. This probably affects upgrades from multiple versions, not just 0.66.x

**Comment by tmancey** [comment]
@LaurenWags I have tested the above with #5531 and now working as expected. I am awaiting approval so I can merge with nightly

**Comment by GeetaSarvadnya** [comment]
@tmancey Verified the issue against version 0.69.128. Now ads enable alert is shown in 0.69.128 after upgrading build from 0.62.51 to 0.69.128 but Ads are enabled by default in brave://rewards page which is not expected.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description, after upgrade Ads enable alert should be shown on BAT logo
and Ads are disabled by default in brave://rewards

**Comment by GeetaSarvadnya** [comment]
Blocked due to https://github.com/brave/brave-browser/issues/6148

**Comment by LaurenWags** [comment]
Verified passed with


Brave | 0.69.131 Chromium: 77.0.3865.90 (Build ufficiale) (a 64 bit)
-- | --
Revisione | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
Sistema operativo | macOS Versione 10.13.6 (Build 17G5019)

* Used test plan from PR and test scenarios from https://github.com/brave/brave-browser/issues/5434#issuecomment-517806000 as a guide for testing.

1. **PASS** Upgrade 0.62.51 --> 0.69.131 on `test` channel: US region
   * Prompted about ads on BAT logo with notification. This is working as expected.
   * Ads are not enabled by default but are available to be enabled. This is working as expected

2. **PASS** Upgrade 0.62.51 --> 0.69.131 on `test` channel: UK region
   * Prompted about ads on BAT logo with notification. This is working as expected.
   * Ads are not enabled by default but are available to be enabled. This is working as expected

3. **PASS** Upgrade 0.62.51 --> 0.69.131 on `test` channel: AUS region
   * Prompted about ads on BAT logo with notification. This is working as expected.
   * Ads are not enabled by default but are available to be enabled. This is working as expected

4. **PASS** Upgrade 0.62.51 --> 0.69.131 on `test` channel: Italy region
   * Not prompted about ads on BAT logo with notification. This is working as expected since Italy is not an ads enabled region.
   * Ads are not available to be enabled and Sorry message is displayed. This is working as expected since Italy is not an ads enabled region.

5. **PASS** Upgrade 0.63.55 --> 0.69.131 on `test` channel: US region
A. Ads On before upgrade
   * Not prompted about ads on BAT logo with notification. This is working as expected since Rewards were ON before upgrade.
   * Ads are still on after upgrade. Working as expected.

B. Ads Off before upgrade
   * Prompted about ads on BAT logo with notification. This is unexpected - logged #6270.
   * Ads are still off after upgrade. Working as expected.

6. **PASS** Upgrade 0.63.55 --> 0.69.131 on `test` channel: AUS region
   * Prompted about ads on BAT logo with notification. This is working as expected since "Sorry" message was displayed prior to upgrade.
   * Ads are not enabled by default but are available to be enabled. This is working as expected.

7. **PASS** Upgrade 0.63.55 --> 0.69.131 on `test` channel: Italy region
   * Not prompted about ads on BAT logo with notification. This is working as expected since Italy is not an ads enabled region.
   * Ads are not available to be enabled and Sorry message is displayed. This is working as expected since Italy is not an ads enabled region.

8. **PASS** Upgrade 0.66.101 --> 0.69.131 on `test` channel: US region
A. Ads On before upgrade
   * Not prompted about ads on BAT logo with notification. This is working as expected since Rewards were ON before upgrade.
   * Ads are still on after upgrade. Working as expected.

B. Ads Off before upgrade
   * Prompted about ads on BAT logo with notification. This is unexpected - logged #6270.
   * Ads are still off after upgrade. Working as expected.

9. **PASS** Upgrade 0.66.101 --> 0.69.131 on `test` channel: AUS region
   * Prompted about ads on BAT logo with notification. This is working as expected since "Sorry" message was displayed prior to upgrade.
   * Ads are not enabled by default but are available to be enabled. This is working as expected.

10. **PASS** Upgrade 0.66.101 --> 0.69.131 on `test` channel: Italy region
   * Not prompted about ads on BAT logo with notification. This is working as expected since Italy is not an ads enabled region.
   * Ads are not available to be enabled and Sorry message is displayed. This is working as expected since Italy is not an ads enabled region.

11. **PASS** Upgrade 0.68.142 --> 0.69.131 on `test` channel: US region
A. Ads On before upgrade
   * Not prompted about ads on BAT logo with notification. This is working as expected since Rewards were ON before upgrade.
   * Ads are still on after upgrade. Working as expected.

B. Ads Off before upgrade
   * Not prompted about ads on BAT logo with notification. This is working as expected.
   * Ads are still off after upgrade. Working as expected.

12. **PASS** Upgrade 0.68.142 --> 0.69.131 on `test` channel: AUS region
A. Ads On before upgrade
   * Not prompted about ads on BAT logo with notification. This is working as expected since Rewards were ON before upgrade.
   * Ads are still on after upgrade. Working as expected.

B. Ads Off before upgrade
   * Not prompted about ads on BAT logo with notification. This is working as expected.
   * Ads are still off after upgrade. Working as expected.

13. **PASS** Upgrade 0.68.142 --> 0.69.131 on `test` channel: Italy region
   * Not prompted about ads on BAT logo with notification. This is working as expected since Italy is not an ads enabled region.
   * Ads are not available to be enabled and Sorry message is displayed. This is working as expected since Italy is not an ads enabled region.
