### ISSUE TITLE
New on boarding for wallet verification

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#5518]
We would like to simplify verify screen.

Things to do:
- remove on boarding in the panel. Clicking on the button should open rewards page and open on boarding dialog
- move panel overlay into modal which should look like this:

![image](https://user-images.githubusercontent.com/9574457/62386906-791a6300-b559-11e9-8c05-0de1de46b782.png)

**Comment by bsclifton** [comment]
Looking at this - it's a little bit confusing and also regresses on past capability (2 way wallet regresses capability, not this text change)

For example, if I want to add funds without "verifying"... that isn't possible. The closest I can do is:
1. Go to brave://rewards
2. Click `Add funds`
3. Click `Verify Wallet` (even though I don't intend to verify)
4. Create an Uphold account
5. Don't complete the KYC process
6. Get the address inside Uphold
7. Send the funds there

The previous flow was:
1. Go to brave://rewards
2. Click `Add funds`
3. Addresses are shown where you can send Eth, BAT, etc
4. Send the funds there

It would be nice if the addresses were shown on the screen above, for people that don't even want to click `Verify Wallet` (because they have no intention of verifying and don't even want to create an Uphold account)

**Comment by bradleyrichter** [comment]
@bsclifton Can you expand on the confusing aspect? 

Regarding adding crypto via wallet addresses, this now requires an uphold account (not KYC) but there isn't currently a separated logical flow that can be linked to from our ad-funds button.

**Comment by bsclifton** [comment]
@bradleyrichter quick example - I have an account with BAT already where I can load up my wallet. Let's say I have 0 interest in signing up for Uphold; I purely want a one-way wallet where I put the funds, they can be dispersed. We don't really offer that

Instead, you now (even to get your address) need to create an Uphold account. In our text, we say "Verify" even though you can use the Uphold account without finishing KYC (and then you have a 1 way Uphold wallet). I'd imagine some folks (as users) have no interest in verifying

Publishers can be required to do KYC because they are getting incoming tokens. But for you to disperse tokens, it seems a little odd (to me) to have messaging requiring the KYC

Example use-case:
1. I have a CoinBase account with 1,000 BAT
2. Every month or so, I put 100 BAT into my Brave one-way wallet. I get the address by clicking add funds.
3. 0.69.x arrives
4. I click add funds; address is not shown
5. I am shown above modal and only button present is `Verify Wallet`. I have 0 interest in verifying, let alone creating an Uphold account
6. I'm stuck now, not being able to transfer my BAT

**Comment by bradleyrichter** [comment]
@NejcZdovc I had a typo in that screen above. Please use "necessary" instead of "necessarry".

![image](https://user-images.githubusercontent.com/13509546/62403467-297c6d00-b542-11e9-8745-311dff023d0f.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.113 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/3081
- Verified that verify modal displayed in a new tab when `Verify Wallet` button is clicked from BR panel
![image](https://user-images.githubusercontent.com/38657976/63523038-0b89a300-c517-11e9-8702-60687f5faca7.png)
- Verified that verify modal displayed again when `Verify Wallet` button is clicked from brave://rewards page
- Verified that uphold page is opened when `VERIFY WALLET` button is clicked on verify modal
