### ISSUE TITLE
Huge security concern over camera access

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [brave/brave-browser#5526]
Upon visitation of trello.com and eBay, my phone's camera is activated for a split second. I don't know if this is some new fingerprinting technique but it has been doing this since more than six months already. I could not find anything online so, this is something uncovered. The way I noticed it was that my phone lens makes noise when it's activated. 

Please spread some awareness about this.

**Comment by caycek** [comment]
Just to ask this question. Since you have noticed it for 6 months are these the only 2 sites that do this? Or are you seeing it on any other sites?

The more sites that you could list could help determine if this is a wider issue or localized to how those specific sites are interacting with the device.

I'm also assuming this is an iPhone since I don't think there is a solid build of Android yet. What iPhone do you have?

**Comment by hp8wvvvgnj6asjm7** [comment]
> 
> 
> Just to ask this question. Since you have noticed it for 6 months are these the only 2 sites that do this? Or are you seeing it on any other sites?
> 
> The more sites that you could list could help determine if this is a wider issue or localized to how those specific sites are interacting with the device.
> 
> I'm also assuming this is an iPhone since I don't think there is a solid build of Android yet. What iPhone do you have?

android + afwall + xposed + xprivacy

**Comment by bsclifton** [comment]
cc: @SergeyZhukovsky @samartnik @AlexeyBarabash

**Comment by hp8wvvvgnj6asjm7** [comment]
It is real, something is going on here. Anyone who needs a video please comment here.

**Comment by hp8wvvvgnj6asjm7** [comment]
Clear your whole cache and history before visiting that site, and it will turn on the camera for one time.

**Comment by hp8wvvvgnj6asjm7** [comment]
https://heathenharvest.org

This site too
