### ISSUE TITLE
Issue with Ads Payments (August 5)

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5548]
## Description 

There is an issue with collecting ads confirmations leaving the browser in some cases not being paid;

First issue: the browser currently only retries sending a failed confirmation per session 

Second issue: potential for a race condition; poor interleaving of http responses and multiple confirmations due to network latency, etc may cause r the same token to be re-used for multiple confirmations which will always fail when sent to the server (causes 404).

## Steps to Reproduce

   1. See test cases in PR

## Actual result:

Failed Ad confirmations do not retry and fail due to a race condition where the same token is used when creating confirmations

## Expected result:
Failed Ad confirmations should retry until successful

## Reproduces how often: 

Intermitten issue

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
able to reproduce 400/404's using 

Brave | 0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

1. **PASS** Verified no 404s observed in logs when clicking to view ads notifications.
2. **PASS** Used Charles Proxy to emulate failed confirmations. Verified that when the failed confirmations were retried, no 400s were observed in the logs.
3. **PASS** Emulated failed confirmations on 0.67.124 (current release build) with Charles Proxy. Upgraded on `test` channel to 0.67.125 rc1. Verified The existing failed confirmations were retried every ~5min. Additionally, `Estimated pending rewards` and `Ad notifications received this month` totals were updated as the failed confirmations succeeded (where applicable). Verified that failed confirmations for `view`, `click`, `dismiss`, and `landed` were each retried and processed successfully.
4. **PASS** Verified that failed confirmations were retried every 5 minutes (+jitter) until the queue was empty. Additionally, if the retry failed, it was added back to the queue and retried again in ~5 min.
5. **PASS** Using 0.67.125rc1, viewed some ads and emulated some failed confirmations (using Charles Proxy) - so that I had a mix of successful and failed confirmations in my confirmations.json file. Without restarting Brave, verified that the failed confirmations were added to the queue and retried. Verified `Estimated pending rewards` and `Ad notifications received this month` totals were updated as the failed confirmations succeeded.
6. **PASS** Using 0.67.125rc1, emulated some failed confirmations using Charles Proxy. Opened confirmations.json and duplicated the failed confirmations. Verified that the duplicate failed confirmations did not cause `Estimated pending rewards` and `Ad notifications received this month` totals to increase. Note - the dupes were removed from my failed_confirmations list as they were retried and failed as expected. Did see `Duplicate unblinded payment token` message in the logs.
7. **PASS** Verified the queue was empty (in confirmations.json) once all failed transactions were processed.

NOTE - there were server issues during testing (503s were experienced). Due to this I encountered https://github.com/brave/brave-browser/issues/5599 while testing.
