### ISSUE TITLE
Brave Ads not showing as landed / sustained in logs in certain cases

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5607]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/4798

Ads are not always showing as sustained / landed in the logs. Per discussion with @tmancey this is due 'to a recent change where if an ad has the same URL as an already opened tab. We now focus on the previously opened tab instead of creating a new tab so that we do not open duplicate tabs for the same ads.'

## Steps to Reproduce

Generally,
   1. View an ad and sustain the ad interaction for 10s.
   2. Keep this tab open.
   3. Browse around and when you get the same ad, click on it.
   4. Instead of a new tab opening to show you the same ad, you are redirected to the already opened tab.

## Actual result:
Landed confirmation is not triggered since we shifted focus to an already opened tab and the tab is not reloaded. Per @tmancey 'We cannot begin sustaining from when a user clicked an ad as the page content could take longer than 10 seconds to appear.'

## Expected result:
Landed confirmation is triggered (assuming ad interaction is sustained for 10s).

## Reproduces how often: 
unsure

## Brave version (brave://version info)

Brave | 0.68.120 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure, but probably yes
- Can you reproduce this issue with the nightly channel? unsure, but probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by tmancey** [comment]
After some investigation, I tracked the reason down to a recent change where if an ad has the same URL as an already opened tab. We now focus on the previously opened tab instead of creating a new tab so that we do not open duplicate tabs for the same ads.

So here goes.

If a user clicks an ad for www.brave.com and views this ad for 10 or more seconds, then a landed confirmation is triggered.

If the user then clicks another ad with the same URL as the previously opened tab, then focus is shifted to that tab, and a landed confirmation is NOT triggered.

The root cause for this issue is that if we focus on a tab that already exists the page content for that tab is not reloaded.

We cannot begin sustaining from when a user clicked an ad as the page content could take longer than 10 seconds to appear.

**Comment by tmancey** [comment]
@LaurenWags This is a duplicate of https://github.com/brave/brave-browser/issues/4026, can you please check and if so, can you close and link this ticket

**Comment by LaurenWags** [comment]
@tmancey can loop back to this after testing user wallets 👍

**Comment by LaurenWags** [comment]
@tmancey apologies for the late reply. I don't know if this is a duplicate of https://github.com/brave/brave-browser/issues/4026 but it may be a duplicate of https://github.com/brave/brave-browser/issues/5949.

**Comment by tmancey** [comment]
@LaurenWags Do you agree this is a duplicate of https://github.com/brave/brave-browser/issues/5949? thank you

**Comment by LaurenWags** [comment]
@tmancey yes, agree this is a dupe of https://github.com/brave/brave-browser/issues/5949
