### ISSUE TITLE
save argon2 parameters in localstorage for crypto wallet

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#5633]
came up in review of https://github.com/brave/KeyringController/pull/1; we should store the argon2 parameters in localstorage (or simply a version number) in case we change them in the future

**Comment by riastradh-brave** [comment]
There are two reasons we should store explicit parameters:

1. So that we can calibrate them to the user's available resources -- CPU speed, memory, parallelism.
2. So that we can write known-answer test vectors for the logic that hashes passwords and derives keys from them, using very small parameters to avoid enormous costs to running automatic tests.
