### ISSUE TITLE
Device recognition preventing uphold.com from verifying documents.

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#5712]
When verifying customer documents with Sheilds up on 0.67.125 and a US driver’s license, we get a “Sorry, this file type is not supported” error. 

`Signup is ok, this is the (also-important) identity verification piece.`

With some troubleshooting, I confirmed that allowing all device recognition fixed the verifying issue.

Can we whitelist uphold.com (specifically Device recognition)

**Comment by kjozwiak** [comment]
@ryanbr can you recheck using https://github.com/brave/brave-browser/releases/tag/v0.68.130? I believe the above has been fixed in `nightly` and `dev` as I've gone through several account creations in the last few days without issues. Haven't checked `0.68.x` though. If it's working on `0.68.x`, we can probably close this off as it's being released on Wednesday.
