### ISSUE TITLE
point browser to dev environment

### ISSUE THREAD

**Issue by maikelmclauflin** [brave/brave-browser#5722]
### feature request
ability to point browser to dev envrionment `--rewards=staging=true` (need dev version of this and others like it)

## Expected result:
points urls to provided dev environments @hspencer77 , @bkero , @amirsaber , and i have relevant domains

**Comment by maikelmclauflin** [comment]
domains known so far are
```ads: http://ads-alb-1745180096.us-west-2.elb.amazonaws.com/
balance: https://bat-balance-dev.herokuapp.com/ -> mercury -> https://balance-dev.mercury.basicattentiontoken.org
ledger: https://bat-ledger-dev.herokuapp.com/ -> mercury -> https://ledger-dev.mercury.basicattentiontoken.org```
are there others that are needed? these may also change if we can get a domain for ads-dev

**Comment by NejcZdovc** [comment]
yes we need `https://publishers.basicattentiontoken.org` and `https://publishers-distro.basicattentiontoken.org` as well

**Comment by LaurenWags** [comment]
@NejcZdovc @tmancey Could one of you provide a test plan for this issue please?

**Comment by tmancey** [comment]
@LaurenWags Test plan added to https://github.com/brave/brave-core/pull/3294

**Comment by btlechowski** [comment]
Verified passed with

Brave | 1.2.11 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3294

`--brave-ads-development`
Verified enabling of rewards
Verified wallet was created successfully
Verified that ads urls points to dummy `ads-serve.brave.software.com` server
Verified that ads grant is shown by default
![image](https://user-images.githubusercontent.com/34715963/69695453-bee8d180-10dc-11ea-8f65-085c54ebf3da.png)
Was unable to claim the grant
![image](https://user-images.githubusercontent.com/34715963/69695488-dcb63680-10dc-11ea-84d5-77a70329dddc.png)
Verified that ads catalog was not downloaded, because it points to dummy `https://ads-serve.brave.software.com/v1/catalog`

`--brave-ads-staging`
Verified enabling of rewards
Verified wallet was created successfully
Verified that UGP grant is shown by default
![image](https://user-images.githubusercontent.com/34715963/69696299-957d7500-10df-11ea-9523-be87843ce050.png)
Verified that I was able to claim the grant
![image](https://user-images.githubusercontent.com/34715963/69696352-bd6cd880-10df-11ea-8abd-3cdf6b49347d.png)
![image](https://user-images.githubusercontent.com/34715963/69696369-c8276d80-10df-11ea-9245-cb7037b47024.png)
Verified that got staging ads catalog
Verified that was able to tip a verified creator
Verified that wallet was updated after tipping
Verified that I got an ad

`production`
Verified enabling of rewards
Verified wallet was created successfully
Verified that got staging ads catalog
Verified that was able to tip a verified creator
Verified that wallet was updated after tipping
Verified that I got an ad
