### ISSUE TITLE
Sync use fetch-sync-records for devices

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#5755]
## Description 

Currently devices are queried with `fetch-sync-devices` command. This makes additional load on S3. We need to use `fetch-sync-records` to use SQS. 
Related PR https://github.com/brave/sync/pull/331 

## Steps to Reproduce

   1. Establish sync chain between two devices
   2. Open brave://inspect/#extensions choose Brave Sync => inspect => Console. Enable timestamps for console in settings

## Actual result:

   3. See `fetch-sync-devices` each minute

## Expected result:
   3. See messages like ```"fetch-sync-records" category_names=["PREFERENCES"] start_at=<some not zero time>``` 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Any desktop version

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?
yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Talked to @AlexeyBarabash and having multiple `"fetch-sync-records" category_names=["PREFERENCES"] start_at=<some not zero time>` is expected behavior
![image](https://user-images.githubusercontent.com/34715963/65902137-f75c7f80-e3b9-11e9-9bfe-70a1e5fafd20.png)

Verified that `send-sync-records` is NOT sent every minute
![image](https://user-images.githubusercontent.com/34715963/65902102-e14ebf00-e3b9-11e9-94a0-56ddac989f58.png)
