### ISSUE TITLE
Click `Add funds` in the panel is redirecting to brave settings page when Brave rewards is turned OFF

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5779]
## Description 

Click `Add funds` in the panel is redirecting to brave settings page when Brave rewards is turned OFF

## Steps to Reproduce

   1. Clean profile 0.69.114
   2. Join rewards
   3. Turn OFF brave rewards
   4. Click on BR panel
   5. Click on `Add funds` in BR panel
   6. Add funds redirected to brave rewards settings page

## Actual result:

Click `Add funds` in the panel is redirecting to brave settings page when Brave rewards is turned OFF
![image](https://user-images.githubusercontent.com/38657976/63594261-9cbe4f80-c5d3-11e9-9958-f2975f166660.png)

## Expected result:
 make it behave as it behaves in the brave rewards settings page - Not sure about expected behavior

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.69.114 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc @mandar-brave

**Comment by btlechowski** [comment]
@GeetaSarvadnya @NejcZdovc What is expected behavior here?

**Rewards are off**
Clicking `Add funds` in Rewards Panel opens `brave://rewards` page in a new tab.
![image](https://user-images.githubusercontent.com/34715963/66441166-ff5d9480-ea35-11e9-94fe-e9a344e475d0.png)
Clicking `Add funds` in Rewards Page opens wallet verify modal
![image](https://user-images.githubusercontent.com/34715963/66441215-24520780-ea36-11e9-9683-78a5f38d2587.png)
**Rewards are on**
Clicking `Add funds` in Rewards Panel opens `brave://rewards/#verify` page in a new tab.
![image](https://user-images.githubusercontent.com/34715963/66441267-55cad300-ea36-11e9-8959-691e7d8d939f.png)
Clicking `Add funds` in Rewards Page opens wallet verify modal
![image](https://user-images.githubusercontent.com/34715963/66441273-62e7c200-ea36-11e9-965f-169c153dba9f.png)

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

**Comment by NejcZdovc** [comment]
@btlechowski that is a bug for rewards off that will be fixed with https://github.com/brave/brave-core/pull/3631

**Comment by LaurenWags** [comment]
`QA/Blocked` until we determine if https://github.com/brave/brave-core/pull/3631 needs to be uplifted.

**Comment by NejcZdovc** [comment]
@LaurenWags 3631 will go into 0.70

**Comment by LaurenWags** [comment]
thanks @NejcZdovc - will unblock this one once PR has been merged and we have a build to test with.

**Comment by LaurenWags** [comment]
Unblocking now that needed PR has been uplifted to 0.70.x

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.118 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description (verified both clean and upgraded profile)
- Verified click on `Add funds` in BR panel is redirecting to `ADD FUNDS` page in Uphold, If the wallet is connected to uphold account
- Verified click on `Add funds` in Settings page is redirecting to `ADD FUNDS` page in Uphold, If the wallet is connected to uphold account
- Verified click on `Add funds` in BR panel is redirecting to `Verify wallet` modal if the brave wallet is NOT connected to uphold account
- Verified click on `Add funds` in settings page is redirecting to `Verify wallet` modal if the brave wallet is NOT connected to uphold account
