### ISSUE TITLE
[Desktop] Profile Manager popup window avatars should be circle

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#5832]
## Description 

As requested by @bradleyrichter , the profile manager popup window should not have square avatars, but rounded.

## Designs
- Have a visual indicator on the profile currently being used
- Make cards more compact so more profiles can be shown at at time
- Remove a step in the profile deletion process and use a lightbox modal treatment to highlight what data is being deleted
![manage profile 1](https://user-images.githubusercontent.com/2388823/74572154-86b29b80-4f33-11ea-8f61-2e81c1a7d3b3.png)
Cards respond to being hovered over; click to open that profile:
![manage profile 2 - hover](https://user-images.githubusercontent.com/2388823/74286520-c764a780-4cdc-11ea-99f6-0191a8be92c5.png)
Click delete icon to show delete profile confirmation message with >0 data in bold:
![manage profile 3 - delete](https://user-images.githubusercontent.com/2388823/74286524-c92e6b00-4cdc-11ea-835f-f8250beaa048.png)
No hover effect/click disabled on the current profile card (because you can't open the same profile again); it can only be deleted:
![manage profile 4 - hover current](https://user-images.githubusercontent.com/2388823/74286525-c9c70180-4cdc-11ea-9478-3a87e30a78cc.png)

### Dark Theme
Dark theme is supported:
![manage profile 5 - dark](https://user-images.githubusercontent.com/2388823/74571276-7221d380-4f32-11ea-95fd-f428d331072f.png)
![manage profile 6 - dark 2](https://user-images.githubusercontent.com/2388823/74571278-72ba6a00-4f32-11ea-8b2d-855b1c050214.png)

### Assets
Figma: https://www.figma.com/file/FqIaMf0xBK8uz4wysqJpm4/Manage-profiles?node-id=1%3A257

Icons and logotypes: [assets.zip](https://github.com/brave/brave-browser/files/4207044/assets.zip)

**Comment by petemill** [comment]
![image](https://user-images.githubusercontent.com/741836/63893631-87fd0580-c99f-11e9-8869-3d8c4c42a0d8.png)

**Comment by rebron** [comment]
cc: @karenkliu @bradleyrichter Need new mock-ups for this one. 
Wha it currently looks like:
<img width="802" alt="Screen Shot 2020-02-04 at 10 38 13 PM" src="https://user-images.githubusercontent.com/5951041/73817122-0f487380-479f-11ea-8a2c-786d9921b86a.png">
![Uploading Screen Shot 2020-02-04 at 10.38.00 PM.png…]()

**Comment by karenkliu** [comment]
A simple solution would be to simply shrink the profile icons a bit and use Brave branded buttons:
![shrink profiles](https://user-images.githubusercontent.com/2388823/74286354-6e950f00-4cdc-11ea-9d0d-da8495dbac68.png)

A nicer solution would be to:

- Have a visual indicator on the profile currently being used
- Make cards more compact so more profiles can be shown at at time
- Remove a step in the profile deletion process and use a lightbox modal treatment to highlight what data is being deleted
![manage profile 1](https://user-images.githubusercontent.com/2388823/74286511-c59ae400-4cdc-11ea-8b8a-9ae37a7ba7cb.png)
Cards respond to being hovered over; click to open that profile:
![manage profile 2 - hover](https://user-images.githubusercontent.com/2388823/74286520-c764a780-4cdc-11ea-99f6-0191a8be92c5.png)
Click delete icon to show delete profile confirmation message with >0 data in bold:
![manage profile 3 - delete](https://user-images.githubusercontent.com/2388823/74286524-c92e6b00-4cdc-11ea-835f-f8250beaa048.png)
No hover effect/click disabled on the current profile card (because you can't open the same profile again); it can only be deleted:
![manage profile 4 - hover current](https://user-images.githubusercontent.com/2388823/74286525-c9c70180-4cdc-11ea-9478-3a87e30a78cc.png)

**Comment by simonhong** [comment]
Above design is final one? If so, I'll start implement with it.

**Comment by karenkliu** [comment]
@simonhong yep! I just attached the designs and specs for you in the original post.

**Comment by karenkliu** [comment]
@rebron Maybe we should close this issue? We seem to be following Chrome's profile manager fairly closely and don't seem to be working on our own for awhile.

**Comment by rebron** [comment]
Closing as invalid/stale.
