### ISSUE TITLE
Ad notifications are not delivered on Android unless browser enters the background and then becomes active

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5879]
## Description 

Ad notifications are not delivered on Android unless browser enters the background and then becomes active

## Steps to Reproduce

   1. Launch browser
   2. Enable Brave ads
   2. Visit brave.com
   3. Wait 30 minutes

## Actual result:

An ad is not shown

## Expected result:
An ad should be shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.3.1

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.111 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified ad notifications were served
* Verified ad notifications were served according to setting in Ads panel (# per hour)
* Verified sites were categorized 
* Verified `view`, `click`, `dismiss` notifications were logged in `confirmations.json` (could not check `landed` due to redirect issue)
