### ISSUE TITLE
Console outputs  [Deprecation] note on console. 

### ISSUE THREAD

**Issue by nikahmadz** [brave/brave-browser#5899]
## Description

Console outputs  `[Deprecation]` note on console. Happens on any page including the "_blank" new tab.

> [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.

## Steps to Reproduce

1. Open new tab.
2. Open the dev console.

## Expected result:

No debug messages. This is an official build.

## Brave version (brave://version info)

Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
Thanks for the report, @nikahmadz! This happens on all of the internal pages (even in Chrome). It has to do with the Polymer code used for chrome://settings / chrome://newtab and associated pages. There's nothing here for us to fix - we should get the fix for free from upstream Chromium when they fix it

Closing as `wontfix`
