### ISSUE TITLE
Replace `localStorage` with a mock API which doesn't create permanent state

### ISSUE THREAD

**Issue by arodic** [brave/brave-browser#5935]
With cookies disabled, visiting websites that use `window.localStorage` and similar APIs throws an error sometimes completely breaking existing websites.

Consider replacing localStorage etc with a mock API that stores no data and allow rest of the js code to run normally.

**Comment by snyderp** [comment]
@rebron we don't mock the API currently, we report storage blocked (which is a case web devs should handle, but don't).  It would be a neat / fine idea to mock the API instead of blocking though.

@jumde @fmarier @diracdeltas wdyt?

**Comment by fmarier** [comment]
Aside from checking whether or not storage is blocked, sites are likely to also check if they can read back what they just put in local storage. Maybe we should stash any such data into an in-memory data structure that gets cleared once the page is navigated away?

**Comment by snyderp** [comment]
yea, was discussing with @jumde .  Maybe the best way forward would be the following?

1) Replace `window.{local,session}Storage` with a proxy that evals to something false-y (so that sites that correctly check to see if they have access to storage work correctly)
2) responds to all object set/get/delete operations as if it was just an empty `{}` (so that websites that assume they have access can read / write in / out)?

**Comment by darrylyeo** [comment]
Any plans on implementing this? I'd love to be able to disable cookies across the board without breaking websites that use Web Storage. Maybe Web Storage could be a separate shield toggle from the cookies toggle?

**Comment by darrylyeo** [comment]
Any plans on implementing this? I'd love to be able to disable cookies across the board without breaking websites that use Web Storage. In the meantime, maybe Web Storage could be a separate shield toggle from the cookies toggle?

**Comment by fmarier** [comment]
@darrylyeo Can you talk more about your use case? For example, if you were to disable cookies across the board, how would you log into websites?

I personally use [uMatrix](https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf) to block cookies by default and then whitelist sites I want to log into.

**Comment by darrylyeo** [comment]
@fmarier I'm using two separate browser profiles - one for general browsing where I turn on every Brave shield and privacy feature available to the most extreme setting, and a second profile with cookies allowed for sites that I need to log into. For the first profile, I have the default cookies shield set to "Cookies blocked", but currently I have to manually set it to "Cross-site cookies blocked" for some sites that break because of the Web Storage issue described.

**Comment by darrylyeo** [comment]
@fmarier I'm using two separate browser profiles - one for general browsing where I turn on every Brave shield and privacy feature available to their most extreme settings, and a second profile with cookies allowed for sites that I need to log into. For the first profile, I have the default cookies shield set to "Cookies blocked", but currently I have to manually set it to "Cross-site cookies blocked" for some sites that break because of the Web Storage issue described.

**Comment by pes10k** [comment]
Closed in favor of https://github.com/brave/brave-browser/issues/8514, which includes this functionality
