### ISSUE TITLE
Welcome Screens are too tall for small screens

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#5950]
Remove top margin on the right place to reduce stackup height.

![image](https://user-images.githubusercontent.com/13509546/64557521-91b72f00-d2f6-11e9-9396-e9aff5fd1972.png)

**Comment by btlechowski** [comment]
This is very annoying issue which prevents using `brave://welcome` page on small screens. The reason is that bottom navbar is not visible.

![image](https://user-images.githubusercontent.com/34715963/65337433-6c64d380-dbc8-11e9-89cb-0a6bb1f7f916.png)

Tested on 

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Ubuntu 18.04 LTS

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.110 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

welcome page fits small screen
![image](https://user-images.githubusercontent.com/34715963/66442113-c3c4c980-ea39-11e9-80ad-e8ef57985461.png)
Scrollbar is shown when needed
![image](https://user-images.githubusercontent.com/34715963/66442159-e9ea6980-ea39-11e9-8119-a237dcbd7ef0.png)
