### ISSUE TITLE
Muting the a site on a tab also mutes the same site on other tab

### ISSUE THREAD

**Issue by ranjithpmankada** [brave/brave-browser#6113]
## Steps to Reproduce

   1. Open a site which plays sound
   2. Open the same site on other tab
   3. Mute one of the tab
   4. The other site also mutes. This is the issue

## Expected result:
The muting of one tab should not affect the other tab if the site opened in tabs are same.

## Reproduces how often: 

Always

## Version/Channel Information:
Version 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)

- Can you reproduce this issue with the current release? Don't Know
- Can you reproduce this issue with the beta channel? Don't Know
- Can you reproduce this issue with the dev channel? Don't Know
- Can you reproduce this issue with the nightly channel? Don't Know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Don't Know

**Comment by Ravendwyr** [comment]
Sadly this is the default behaviour in Chrome/Chromium.

Up until a recent Chromium update, it was possible to mute individual tabs rather than entire sites. This feature was moved to `about://flags` for a while but has recently been removed from Chromium entirely, affecting Chrome and Brave, however there are Chrome extensions that can restore this behaviour.

**Comment by rebron** [comment]
@ranjithpmankada We fixed this issue in 69.x where if you click the icon you can mute the tab only and not affect other tabs? Can you upgrade to 69.x and let us know what you think?

**Comment by rebron** [comment]
closing as wontfix as it's expected behavior when using the context menu.
