### ISSUE TITLE
The ' clear all cookies and site data when you quit brave' toggle reverts back to default after closing the window .

### ISSUE THREAD

**Issue by ShockRocky** [brave/brave-browser#6119]
## Description 

The ' clear all cookies and site data when you quit brave' toggle when turned on in chrome://settings/content/cookies, revert back to it's default state[off] when the window is closed. 

## Steps to Reproduce

   1. Go to chrome://settings/content/cookies
   2. Toggle on 'clear all cookies and site data when you quit brave', exit the tab.
   3. The toggle is back to its off state, thus not persisting with the user's decision.

## Reproduces how often: 
Encountered the bug on a fresh install of brave[ Version 0.68.139 Chromium: 77.0.3865.90] on a windows 10 laptop, also persists on a fresh profile .

## Brave version (brave://version info)

Brave | 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)

OS | Windows 10 OS Version 1903 (Build 18362.356)

## Version/Channel Information:
Haven't tried to reproduce the issue on other builds of the browser, except the aforementioned one .

- Can you reproduce this issue with the current release?
Yes .
- Can you reproduce this issue with the beta channel?
Haven't tried.
- Can you reproduce this issue with the dev channel?
Haven't tried.
- Can you reproduce this issue with the nightly channel?
Haven't tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome? 
I don't use chrome.

**Comment by jwsp1** [comment]
same here. Hope this privacy bug gets fixed soon.

**Comment by bsclifton** [comment]
cc: @mkarolin

**Comment by Brave-Matt** [comment]
Chiming in here with a few notes -- Recently helped several users in these threads:
https://community.brave.com/t/clear-cookies-and-site-data-when-you-quit-brave-deactivates-itself/85751/20
https://community.brave.com/t/clear-cookies-and-site-data-when-you-quit-brave-deactivates-itself-2/87394

**A bit of clarity surrounding this behavior:**
* As the title of this issue suggests, the `Clear cookies and site data when you quit Brave` toggle resets itself after Brave is relaunched.
![image](https://user-images.githubusercontent.com/3299098/66706193-a49d9480-ece4-11e9-9498-23bf9a59cdc3.png)
 
* When/if that toggle **works**, users are able to add site exceptions (`brave://settings/content --> Allow`) such that they are **not** cleared after quitting the browser. 
* If users instead use the `[On exit]` window (`brave://settings/clearBrowserData --> [On exit]`), data is cleared on exit and the data checked to be cleared is not reset. However, this function **clears all browsing data, regardless of whether or not there are exceptions added**.
![image](https://user-images.githubusercontent.com/3299098/66706245-1bd32880-ece5-11e9-96df-a718089e2c31.png)




**Suggestion:**
I don't see any reason we need to have _both_ of these options. Seems to lead to a lot of confusion and  produces "mixed" results because of it. Instead, we should remove the toggle in `brave://settings/content` and rework the `[On exit]` option so that it doesn't clear or alter manually added (or blocked) site exceptions. 

cc @rebron @bsclifton

**Comment by LaurenWags** [comment]
`QA/Blocked` until we get a new build. Will be available in 0.71.107` and above.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` label as build `0.71.107` is available.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.108 Chromium: 78.0.3904.87 (Official Build) beta (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Verified that the cookies are cleared when turn ON the `clear all cookies and site data when you quit brave` option under `chrome://settings/content/cookies` and quit the browser
- Verified that the state of `clear all cookies and site data when you quit brave` option is ON after the browser restart
- Verified the clear `Cookies and othe rsite data` on exit works as expected
