### ISSUE TITLE
Crypto Wallets setting: text & functionality

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#6172]
The switch to enable/disable Crypto Wallets in settings currently reads "Brave Wallet", but it should be "Crypto Wallets".

When the toggle is unchecked (disabled), the Crypto Wallets item continues to show up in the header, but is hidden in the hamburger menu. But clicking on the header item leads to a broken page.

<img width="781" alt="Screen Shot 2019-09-25 at 13 43 26" src="https://user-images.githubusercontent.com/639937/65638287-a3f1c800-df9a-11e9-9cad-fe85f3dd1ef4.png">

Instead, the header item should be hidden, while the hamburger menu item is greyed out.

**Comment by bbondy** [comment]
I believe the header item is tracked separately and @ryanml knows about it. Using this issue to correct the text though.

**Comment by GeetaSarvadnya** [comment]
@bbondy As per the PR https://github.com/brave/brave-core/pull/3587/files - text change from `Brave Wallet` to `Crypto Wallets` is fixed. When the Crypto Wallets toggle is unchecked (disabled), the crypto wallet menu item is hidden from the hamburger menu should it be greyed out? As per the description https://github.com/brave/brave-browser/issues/6172#issue-498514943 it should be greyed out.

Will it be covered/fixed in the issue https://github.com/brave/brave-browser/issues/6393? If so, this needs to be added mentioned in the issue.

**Comment by bbondy** [comment]
I'm ok with hidden

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.1.1 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the description mentioned in the issue
- Verified that `Brave Wallet` is renamed to `Crypto Wallet` under `chrome://settings/extensions`
- Verified that the `Crypto Wallets` menu item is hidden from the hamburger menu when crypto wallets toggle is unchecked (disabled) in settings
- Verified that header item `Crypto Wallets` is still not hidden or removed when crypto wallets toggle is unchecked (disabled) in settings - This will be fixed/addressed in the issue #6393 as per the https://github.com/brave/brave-browser/issues/6172#issuecomment-537701620
