### ISSUE TITLE
Update search engine defaults for DE / AU / NZ / IE

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#6187]
## Description 
Update search engine defaults for Germany (DE), Australia (AU), New Zealand (NZ), and IE (Ireland)

## Test plan
See brave/internal#647

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/internal/issues/647

**New Users US**
Verified the search string
![image](https://user-images.githubusercontent.com/34715963/66602607-c5fa6580-ebaa-11e9-9b88-b2af49ec83e4.png)

**New Users PL**
Verified the search string
![image](https://user-images.githubusercontent.com/34715963/66602814-2c7f8380-ebab-11e9-9e89-ec440b95bd3c.png)

**New Users De**
Verified the search string
Verified duckduckgo set as default search engine
![image](https://user-images.githubusercontent.com/34715963/66603024-97c95580-ebab-11e9-8f9a-624b9e12ef2b.png)

**New Users AU**
Verified the search string
Verified duckduckgo set as default search engine
![image](https://user-images.githubusercontent.com/34715963/66691745-d6890980-ec98-11e9-9003-2dbf3348f8fa.png)

**Upgraded Users De**
Default search engine `qwant` was replaced by `duckduckgo`. Expected per https://github.com/brave/internal/issues/647#issuecomment-540854051
Search string is replaced for duckduckgo. Logged https://github.com/brave/brave-browser/issues/6424

**Upgraded Users De, custom default search engine (`google`)**
Verified `google` remained default search engine
Search string is replaced for duckduckgo. Logged https://github.com/brave/brave-browser/issues/6424
![image](https://user-images.githubusercontent.com/34715963/66691497-2ff03900-ec97-11e9-8675-6c3059eb328d.png)

**Upgraded Users De, custom default search engine (`qwant`)**
Verified `qwant` remained default search engine
Search string is replaced for duckduckgo. Logged https://github.com/brave/brave-browser/issues/6424
![image](https://user-images.githubusercontent.com/34715963/66691613-efdd8600-ec97-11e9-9a9a-7dfcb9f150d8.png)

**Upgraded Users AU**
Default search engine `google` was replaced by `duckduckgo`. Expected per https://github.com/brave/internal/issues/647#issuecomment-540854051
Search string is replaced for duckduckgo. Logged https://github.com/brave/brave-browser/issues/6424
![image](https://user-images.githubusercontent.com/34715963/66691800-38497380-ec99-11e9-9dd8-fc64610acaa5.png)

**Upgraded Users AU, custom default search engine (`google`)**
Verified `google` remained default search engine
Search string is replaced for duckduckgo. Logged https://github.com/brave/brave-browser/issues/6424
![image](https://user-images.githubusercontent.com/34715963/66691877-d89f9800-ec99-11e9-829a-77de80303168.png)

**Upgraded Users AU, custom default search engine (`duckduckgo`)**
Verified `duckduckgo` remained default search engine
Another instance of DuckDuckGo is added to search engines. Logged https://github.com/brave/brave-browser/issues/6453
![image](https://user-images.githubusercontent.com/34715963/66691970-83b05180-ec9a-11e9-9ab8-98013e35a9db.png)

I was unable to test NZ and IE, because Ubuntu 18.04 does not support them. Setting regional formats does not work.
![image](https://user-images.githubusercontent.com/34715963/66692278-31bcfb00-ec9d-11e9-8f4f-24112d5d2161.png)
