### ISSUE TITLE
Automatically limit unwanted Brave Ads delivery

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#6253]
## Description 
While we currently have a feedback tool for ads which will limit delivery of downvoted ads, there have been many requests to limit delivery of repetitive ads so that the out of the box user experience is better.  Eventually this will be handled by contextual "bandits" but in the mean time, we need some simple rules to help improve the situation.

The proposed rules are as follows

1. If a user has a "landed" event on a page, do not show anything from that same campaign for another 48 hours.
2. If a user has "dismissed" an ad twice in a row without clicking, also do not show anything from that same campaign for 48 hours.

**Comment by tmancey** [comment]
@jsecretan Is this change still required? Thanks

**Comment by jsecretan** [comment]
Ok, I think we can do this now that we can monitor the channel associated with ads.  No rush on it but merge at will.

**Comment by btlechowski** [comment]
`QA/Blocked` because asked @tmancey for assistance.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.14.75 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Ubuntu 18.04 LTS

This issue is still reproducible. Per our process logged a follow up: https://github.com/brave/brave-browser/issues/11617

**Comment by btlechowski** [comment]
After internal discussion changed to `QA/No` cc @rebron @LaurenWags
