### ISSUE TITLE
Provide Windows ARM64 binary

### ISSUE THREAD

**Issue by ethankhall** [brave/brave-browser#6319]
## Description 
Provide binary download for Windows 10 on ARM.

With the launch of a new tablet by Microsoft that runs on ARM, it would be nice to have a binary available for ARM processors. The x86 version can be used in it's place (I believe) but a true 64 bit experience would be nice.

## Actual result:
Windows has winia32 and winx64 as download options.

## Expected result:
Windows has winia32, winarm64, winx64 as download options.

**Comment by srirambv** [comment]
cc: @rebron @bsclifton @bbondy

**Comment by bsclifton** [comment]
@ethankhall do you have more information on the new Surface? ex: does it still force you to install from the store? (ex: appx format)

If so, that is likely why Chrome hasn't submitted. We tried with the Muon based version of the browser and were told that is not supported:
https://github.com/brave/browser-laptop/issues/1679#issuecomment-323654065

**Comment by szaimen** [comment]
![Screenshot_20191007-093010_Chrome Beta](https://user-images.githubusercontent.com/42591237/66292649-18a2fb80-e8e5-11e9-80fc-70def05822c7.png)

**Comment by mihaiplesa** [comment]
Related https://community.brave.com/t/windows-10-arm64-build/98783
@snickler has a guide at https://sinclairinat0r.com/2019/04/29/building-chromium-on-windows-from-source

**Comment by snickler** [comment]
> Related https://community.brave.com/t/windows-10-arm64-build/98783
> @snickler has a guide at https://sinclairinat0r.com/2019/04/29/building-chromium-on-windows-from-source

Those steps worked for solely Chromium builds. There's extra steps that have to be done for Brave. They likely since changed from the steps I sent to @jonathansampson since the build I made was on Chromium 80.X

**Comment by JayBeavers** [comment]
Any progress here @mihaiplesa?

**Comment by mihaiplesa** [comment]
@JayBeavers no update yet but you can expect support to come probably after Windows 11 stable is released.

**Comment by snickler** [comment]
> @JayBeavers no update yet but you can expect support to come probably after Windows 11 stable is released.

Hmm. May I ask why the effort relies on Windows 11 stable being released before the availability of an official arm64 Windows binary? 🤔

**Comment by alanjclark** [comment]
@snickler I concur. @mihaiplesa Can you please elaborate on this? Windows 10 on ARM has existed in Stable for a solid two years. Windows 11 on ARM is available in Windows Insider. I'm not sure I understand the timescale relying on Windows 11 Stable.

**Comment by Poopooracoocoo** [comment]
@mihaiplesa Any updates on the priority of this issue now that Windows 11 has been released?

**Comment by snickler** [comment]
@mihaiplesa @mherrmann - *BUMP*

**Comment by mherrmann** [comment]
Note to self and others: MS Azure offer ARM 64 Windows VMs.

**Comment by mihaiplesa** [comment]
@snickler any luck getting a build with Widevine?

**Comment by snickler** [comment]
> @snickler any luck getting a build with Widevine? Same blocker as for Linux arm64.

There is no native Arm64 Widevine available, but with Windows 11 you can do what Edge/Firefox have done:
- Offload the widevine decryption, etc to a proxy dll/exe. This is what Edge and Firefox do for Windows Arm64. They're piping the commands through an x86 executable that loads the x86 widevine_cdm dll, then have an Arm64 proxy wrapper (this may be more geared towards what Edge does, but Mozilla does something very similar with loading an x86 plugin host if widevine is loaded). Since you're able to run x86, x64 executables, this can work.  

It may be worth finding a contact from the Edge or Mozilla team for more understanding of how they pulled it off, as I don't know how widevine is currently being loaded in Brave.

**Comment by mihaiplesa** [comment]
@snickler many thanks for that, will see if someone from our team can help investigate.

**Comment by Alovchin91** [comment]
Just read the article on XDA. Is there x64 Widevine? If so, maybe an ARM64EC calling binary would work? 🤔

**Comment by mihaiplesa** [comment]
And we're live with Windows arm64 at https://github.com/brave/brave-browser/releases/tag/v1.47.9

**Comment by bsclifton** [comment]
Nice work all 😄 🎉

**Comment by jrockwar** [comment]
Incredibly exciting news!

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.47.152 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 22H2 (Build 22621.963)
```
- Verified the test plan from https://github.com/brave/brave-core/pull/11096

### Windows 11 x64

<details>

<summary>Pre-requisite steps</summary>
(Please note these steps are described in the "Cleaning up after a test" in https://github.com/brave/brave-core/pull/11096 with additional details)

1. Uninstall all the brave version (all channels Dev, Release, Beta and Nightly) via Control panel
2. Remove all the local profile folders from `%LOCALAPPDATA%\BraveSoftware`
3. Go to `C:\Program Files (x86)\BraveSoftware\update` path and observe that `Update` folder is still available and updater version `1.3.361.113` is still shown
4. Open RegEdit and navigate to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update` and ensure Omaha updater version is `1.3.361.135` 
5. Open command prompt with Admin privileges and run the command `"C:\Program Files (x86)\BraveSoftware\Update\BraveUpdate.exe" /uninstall`
6. Go to C:\Program Files (x86)\BraveSoftware path and observe that the `update` folder is removed
7. Open RegEdit and navigate to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update` and ensure Omaha updater version `1.3.361.135` is removed from the registry
8. If the registry key isn't empty in steps 6 and 7 then kill all instances of `BraveUpdate.exe`, `BraveCrashHandler.exe`, `BraveCrashHandler64.exe` in the Task Manager
9. Steps 6 and 7 indicate that the Omaha updater is completely uninstalled

</details>

**_Test Case 1. Verify installers and auto-updater work on a clean profile_**

<details>
<summary>Case 1: Verify Omaha updater version when 1.47.x is installed with standalone installer with admin privileges_PASSED</summary>

`StandaloneSetup.exe`

**Steps:**

1. Did not run from `Pre-requisite steps` as this issue is tested on a new laptop and there were no prior Brave installers installed
2. Download `BraveBrowserStandaloneBetaSetup.exe` and install the standalone binary 1.47.x (`1.47.115`) with admin privileges and ensured that standalone installer installed successfully
3. Confirmed that the new Omaha updater `1.3.361.135` is shown in the registry as expected
4. Confirmed new Omaha updater version `1.3.361.135` is shown in `C:\Program Files (x86)\BraveSoftware\Update`
5. Uninstall the `1.47.115` from control panel and remove the profile folder from the `%LOCALAPPDATA%\BraveSoftware`
6. Install the `1.47.115` again and confirmed that the brave installed successfully
7. Go to brave://settings/help and wait for the update and and click on the `Relaunch` 
8. Confirmed that `brave `is upgraded to latest public version `1.47.149`
9. Verified updater's `pv` value to be `1.3.361.135` in the registry at `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}`


Step 2|Step 3|Step 4|Step 6|Step 7|Step 8|Step 9a|Step 9b
------|------|------|------|------|------|-------|------
<img width="676" alt="image" src="https://user-images.githubusercontent.com/98358127/210021582-7361114c-f4f0-4ce5-b64a-7ecac20386ef.png">|<img width="739" alt="image" src="https://user-images.githubusercontent.com/98358127/210021685-a7e6b1d5-7abb-40b5-bb93-1e1eb7018c92.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/210021751-10d08851-af53-4136-a51f-b2748a2d2db5.png">|<img width="736" alt="image" src="https://user-images.githubusercontent.com/98358127/210021955-63053fb4-9830-438f-a18d-b3a66d70a100.png">|<img width="744" alt="image" src="https://user-images.githubusercontent.com/98358127/210022057-0ade7250-1f3d-4726-a0e4-c7100333b6c9.png">|<img width="642" alt="image" src="https://user-images.githubusercontent.com/98358127/210022095-bfcaf2c0-8a18-447b-8853-3005ff4586ce.png">|<img width="739" alt="image" src="https://user-images.githubusercontent.com/98358127/210022140-c0959c3d-9833-434d-94ad-e4d768fa4fba.png">|<img width="743" alt="image" src="https://user-images.githubusercontent.com/98358127/210022163-28ce0f51-7292-46f3-ad24-f778f1c6dcf6.png">

</details>

**_Test Case 2. Verify installers and auto-updater work on a clean profile_**

<details>
<summary>Case 1: Verify Omaha updater version when 1.47.x is installed with standalone installer with admin privileges_latest Installer - PASSED</summary>

`StandaloneSetup.exe`

**Steps:**

1. Removed previous versions via `Pre-requisite steps` 
2. Download `BraveBrowserStandaloneBetaSetup.exe` and install the standalone binary 1.47.x (`1.47.152`) with admin privileges and ensured that standalone installer installed successfully
3. Confirmed that the new Omaha updater `1.3.36.135` is shown in the registry as expected
4. Confirmed new Omaha updater version `1.3.36.135` is shown in `C:\Program Files (x86)\BraveSoftware\Update`
5. Uninstall the `1.47.152` from control panel and remove the profile folder from the `%LOCALAPPDATA%\BraveSoftware`
6. Install the `1.47.152` again and confirmed that the brave installed successfully
7. Go to brave://settings/help and wait for the update and and click on the `Relaunch` 
8. Confirmed that `brave `is upgraded to latest public version `1.47.152`
9. Verified updater's `pv` value to be `1.3.361.131` in the registry at 'Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}'

Step 2|Step 4|Step 3|Step 6|Step7|Step8|Step9a
------|------|------|------|------|------|-------
<img width="516" alt="image" src="https://user-images.githubusercontent.com/98358127/210014660-718eaf9d-833d-43af-aad3-30228d229b11.png">|<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/210014838-ac5d83b0-8782-4d3d-97bd-c526355c89ee.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/210014886-5010225c-5c9a-46ed-919b-a9a318acd7fe.png">|<img width="723" alt="image" src="https://user-images.githubusercontent.com/98358127/210015171-e0a83485-41e0-4dac-befe-fb77f789f308.png">|<img width="722" alt="image" src="https://user-images.githubusercontent.com/98358127/210015518-134ccfa7-54c7-4322-ae2c-25918846b87b.png">|<img width="734" alt="image" src="https://user-images.githubusercontent.com/98358127/210015573-33ba8487-ce5d-4d7c-8a79-c13661c3f9a2.png">|<img width="737" alt="image" src="https://user-images.githubusercontent.com/98358127/210015585-e02b6b0e-c535-48fa-9519-044fc3937ea7.png">
</details>

**Comment by Alovchin91** [comment]
@mihaiplesa There are no `win32-arm64` artifacts in latest builds anymore. Looks like this issue needs to be re-opened?

**Comment by mihaiplesa** [comment]
@Alovchin91 we don't build it for every version.

**Comment by LaurenWags** [comment]
Changed from `release-notes/include` to `release-notes/exclude` after consulting with @kjozwiak @rebron

**Comment by nsait-linaro** [comment]
Great to see the release happening!

I still don't see a download link on the official website - https://brave.com/download/

The installer seems to be available at https://laptop-updates.brave.com/latest/winarm64, similar to other platforms but there is no link provided on the brave download page.

Could we add the windows arm64 link please ?

**Comment by mihaiplesa** [comment]
@nsait-linaro we found some issues and looking into them before we launch all the way.

**Comment by nsait-linaro** [comment]
Thanks, @mihaiplesa for the quick response! 

If you have any timeline/estimates etc. that you can provide that be helpful.

What would be the best way to track progress on this? Any other issues/channels/mailing lists etc. to follow beyond this issue for updates on windows arm64 platform support?

**Comment by mihaiplesa** [comment]
@nsait-linaro we only have some internal issues for tracking but I'll post here.

It will take a few weeks to iron out what we've discovered.

**Comment by marcpems** [comment]
any plans to implement a Widevine/DRM solution? 
Edge uses an isolated process for running the X64 code emulated on Win11. I think Firefox is doing the same.

**Comment by mihaiplesa** [comment]
@marcpems that is one of the big challenges but we're looking into it as we speak.

**Comment by mherrmann** [comment]
@marcpems I think the best place to discuss Widevine on Arm64 Windows is #28318.

**Comment by jaroslav-kavalec** [comment]
Hi, is there no progress here?

This is the one thing, keeping me on using Edge, as it has perfectly working Windows on ARM version.

**Comment by mihaiplesa** [comment]
@jaroslav-kavalec we've been working on this and are on the last stretch before releasing through all the channels.

For now you can try it by installing from GitHub or Microsoft Store.

**Comment by Fritomaster** [comment]
> @jaroslav-kavalec we've been working on this and are on the last stretch before releasing through all the channels.
> 
> For now you can try it by installing from GitHub or Microsoft Store.

Awesome! Keep up the good work.
