### ISSUE TITLE
Rewards : Verified creators in pending table are not being paid

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#6365]
## Steps to Reproduce
   1.  Tip a creator who is not yet verified
   2.  Wait a month until they verify
   3.  Check the pending contributions table

## Actual result:
Verified creators are in the pending contributions table

## Expected result:
Verified creators should not be in the pending contributions table, they should be paid. 
Prior builds would even give a BAT panel alert after a list update showed they were newly verified.

## Reproduces how often: 
Unknown

## Brave version (brave://version info)
Version 0.72.79 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Unknown
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the dev channel? Unknown
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? Unsure
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Example of verified creators in pending contributions table.
<img width="923" alt="Screen Shot 2019-10-08 at 6 11 10 PM" src="https://user-images.githubusercontent.com/1434040/66442428-59436780-ea00-11e9-8b53-1d08fb47c4b3.png">

**Comment by kjozwiak** [comment]
@LaurenWags have you seen this happen? We should try reproducing in `0.70.x` as this is pretty bad and basically breaks the entire pending mechanism. CCing @rebron for visibility.

**Comment by LaurenWags** [comment]
If you're tipping from a Verified/KYC'd user wallet and the publisher is "connected" (Verified with Brave but not KYC'd with Uphold) I believe it is expected that these publishers will go to pending. @NejcZdovc can you confirm?

@alexwykoff are you tipping from a Verified/KYC'd user wallet?

Also, I can't be sure, since there aren't any URLs, but if the two publishers from the screenshot are:
https://twitter.com/adambroach
https://twitter.com/dreamwisp
Then they are "connected" publishers as far as I can tell:
<img width="1201" alt="Screen Shot 2019-10-09 at 8 58 35 AM" src="https://user-images.githubusercontent.com/28145373/66483652-82e9a680-ea73-11e9-9065-3f8da2fe0515.png">
<img width="1194" alt="Screen Shot 2019-10-09 at 9 00 10 AM" src="https://user-images.githubusercontent.com/28145373/66483666-8715c400-ea73-11e9-9b55-f4355f9b51cc.png">

**Comment by NejcZdovc** [comment]
that is correct, it you are tipping connected it will have check, but it will not go through if you have uphold wallet. So if @alexwykoff this is the case then what you see is expected
