### ISSUE TITLE
Loading crypto wallet extension shows error 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6392]
## Description 

Side loading crypto wallet extension shows error 

## Steps to Reproduce

   1. Clean browser profile
   2. Sideload crypto wallet extension by enabling developer mode
   3. Extension shows errors 
   4. Clicking on CW, adds another error for chrome://wallet

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/66521442-2a3cfc80-eab9-11e9-9cd4-ba93cf03fec3.png)

## Expected result:
No errors

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

cc: @bbondy @ryanml @kjozwiak

**Comment by kjozwiak** [comment]
@bbondy @ryanml seeing the same behaviour with the following builds:

• https://github.com/brave/ethereum-remote-client/releases/tag/0.1.14 - same result
• https://github.com/brave/ethereum-remote-client/releases/tag/0.1.15 - same result
• https://github.com/brave/ethereum-remote-client/releases/tag/0.1.16 - same result

We've been going through most of the issues with the above builds and everything seemed to be working. So I'm not sure if this is due to side loading or it's a legitiment issue.

Labelled as `release/blocking` till we have more information.

**Comment by srirambv** [comment]
Seem to be a problem with installing component as well so issue not limited to sideloading the extension
![image](https://user-images.githubusercontent.com/17010094/66522492-899c0c00-eabb-11e9-8ad8-5dd9adb8a376.png)

**Comment by srirambv** [comment]
moving out of 1.0.10 milestone

**Comment by bbondy** [comment]
We're going to start testing via a staging server instead of side loading, so I think we can close this now.
