### ISSUE TITLE
Do not show the same Brave Ad more than once every hour - follow up to 5281

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6447]
## Description 
Follow up to #5281 

While testing the above issue I noticed that I got the same ad 2x in a row. Per discussion with @tmancey it is likely due to https://github.com/brave/brave-browser/issues/4207.

Happy to share logs/a profile if needed (Have already shared these items with @tmancey ).

## Steps to Reproduce

   1. Clean profile
   2. Enable Rewards
   3. Set ads to 5 per hour
   4. Visit a site that will be classified so an ad notification can be generated.
   5. Browse so that you continue to get ads (if you need additional details here - DM me)

## Actual result:
First and second Ad are from the same campaign_id which has a dailyCap of 1.

## Expected result:
Shouldn't see the same ad 2x in a row - especially since the dailyCap is 1.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.70.113 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @tmancey @jsecretan @rebron @brave/legacy_qa

**Comment by NumDeP** [comment]
Same here but on Linux (OpenSuse) `Version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)`

Set 5 ads per hour - Auto-contribute off (I'm not stingy I just prefer to Tip and I miss the Muon version which was better, particularly the centre console part, without the few bugs of course) 

I received the same ad twice; I think it was within the space of five minutes. I was using tor or private tab at the time, when I clicked on the ad I didn't immediately go over to see it open in the normal window tab. Naturally I closed the second ad because it was the same one.

**Comment by tmancey** [comment]
@NumDeP Further improvements to not show the same ads less frequently are going through testing and will be rolled out in a future general release

**Comment by tmancey** [comment]
@LaurenWags Can you please retest this on the latest nightly build

**Comment by tmancey** [comment]
Won't fix as already fixed on latest nightly

**Comment by bsclifton** [comment]
Closing  (looks like we had just forgot to close)
