### ISSUE TITLE
Sync cannot enable chain sometimes 

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#6504]
## Steps to Reproduce

1. Prepare clear profiles deviceA and deviceB
2. Launch profile A, create new sync chain, ensure sync code is shown, but don't copy the code. Close deviceA.
3. Launch profile B, create new sync chain, copy sync code, don't close.

## Actual result:

4. It is possible to launch profile A, enter sync code and nothing will happen

## Expected result:
4 Launch profile A. Profile A will have sync enabled with only one self device. It will either display the list of one device or propose to add another device by show the codephrase 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 0.73.1 Chromium: 78.0.3904.50 (Developer Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}

## Version/Channel Information:

- Can you reproduce this issue with the current release? not sure
- Can you reproduce this issue with the beta channel? not sure
- Can you reproduce this issue with the dev channel? Yes 
- Can you reproduce this issue with the nightly channel? Yes 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bridiver** [comment]
This ticket doesn't make sense to me. After step 2 there is no longer an option to enter a sync code for Profile A because it has already created a new sync chain

**Comment by btlechowski** [comment]
Added `QA/Blocked` as testing is blocked due to https://github.com/brave/brave-browser/issues/6941

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as both https://github.com/brave/brave-core/pull/4407 & https://github.com/brave/brave-core/pull/4408 have been merged. Once a new `1.3.x` build is created, QA should be able to run through this issue.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.111 Chromium: 80.0.3987.85 (Official Build) (64-bit)
-- | --
Revision | 583b05dfa4ffc657f0f7c5cc13f53aa17c9a5bcf-refs/branch-heads/3987@{#791}
OS | Ubuntu 18.04 LTS

Talked to @AlexeyBarabash, The point of this issue is to use custom profiles for the same device. This can be achieved though flag `--user-data-dir=[PATH]`
Example:
Profile A: `--user-data-dir=/home/bartlomiej/.config/BraveSoftware/TEST/A`
Profile B: `--user-data-dir=/home/bartlomiej/.config/BraveSoftware/TEST/B`

Verified test plan from https://github.com/brave/brave-core/pull/3988#issuecomment-554018675

Verified - I. Check how works reset with `Leave Sync Chain` button
![image](https://user-images.githubusercontent.com/34715963/73884842-fb684480-4866-11ea-91c2-0b40a41d2980.png)

Verified - II. Check how works reset over pressing cross near `this device`
![image](https://user-images.githubusercontent.com/34715963/73885106-7df10400-4867-11ea-80eb-54994a51aa42.png)

Verified - III. Check how works `Reset` over pressing cross near opposite device
![image](https://user-images.githubusercontent.com/34715963/73885325-da542380-4867-11ea-97f7-4d3295e18135.png)

Verified - IV. Check the original STR from https://github.com/brave/brave-browser/issues/6504 becomes not applicable
![image](https://user-images.githubusercontent.com/34715963/73885546-48004f80-4868-11ea-8431-5d86348ac1c2.png)

Verified - V. Check this PR build works with <disordered profile> from old version by STR at brave-browser#6504
Used Brave Beta at step 4:
`/usr/bin/brave-browser-beta --user-data-dir=/home/bartlomiej/.config/BraveSoftware/TEST/A`
![image](https://user-images.githubusercontent.com/34715963/73886273-8fd3a680-4869-11ea-817c-b3f8ca72486b.png)

Verified - VI. Check we send bookmarks as soon as sync is enabled even if there are one device in chain
![image](https://user-images.githubusercontent.com/34715963/73886670-52234d80-486a-11ea-9587-bd41abb2f35d.png)
