### ISSUE TITLE
Ad ethics - Don't over promote the same type of product from the same company

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#6543]
This isn't a criticism @tmancey but a genuine question and statement. Is it technically alright under Brave rules to over promote the same product, so it may not be every hour but after several hours or several days? 
 
I typed this under #6447 but felt it deserved to be separate and though it was related to frequency of a product, it was less so about the annoyance factor and more of an ethical one if I may say so.

As mentioned, it's not necessarily related to **...more than once every hour**, this was actually initially in reference to a CDN and couple of VPN providers that I've seen far to often, they're okay principally, however, similarly to quite a few web hosting solutions they seem to dominate the market when there are quite a number of similarly good products that have exactly the same functionality and more stronger features.

In my opinion, there is no such thing as a top 3, 5 or 10 (product type) and every other blog and comparison site references it as so, rather terribly undermining really good alternatives and not to mention really good local alternatives. 

I got a feeling in the not to distant future Brave is going to promote Web/Cloud Hosting solutions and I can almost guarantee that it would follow the poor reference protocol of the aforementioned top 3 or 5 blog and comparison sites and display what is referenced in the following screenshot.

![Screenshot_20191018_082334](https://user-images.githubusercontent.com/31957540/67074343-d1d4c180-f180-11e9-8141-55c78036d6de.png)

God help me, I'm not criticising that any of the employees from the above companies (though technically just two) are awful at what they do, far from it. That's why I titled it as Ad ethics to see if you think my statement has any merit and perhaps consider developing a better structured and more principled approach to the display/promotion of Ads.

Thanks for reading.

**Comment by lukemulks** [comment]
Hello @NumDeP 
I am Director of BD at Brave, and have been working to bring the ad platform to market. I'd like to put some context and clarity to the statement above, which I hope proves helpful. 

1. There's an important differentiation between Brave promoting a product and/or service (for example, a partnership, or product natively offered to people in the browser), and advertising a product or service. 

We are open to accepting advertising from VPN and cloud service providers that are interested in paying to advertise on the platform. Currently, the providers you observe are those that are paying to advertise. We are open to advertise, additional providers. 

Regarding frequency: We are working on improving this within the product, but additionally, if a brand has a sizeable advertising buy, they are likely to appear more often as the platform aims to deliver the target amount of ads to fulfill the ad buy. 

We have ad guidelines that we provide to buyers, and manually review every ad for quality control. Brave does not take a position regarding the ethics of the software providers mentioned, as this can be rather subjective. 

There are also features in the product that will help provide people with more control and feedback options around the ads that they see in the browser. Our Ads History feature (which I believe lands in our Release channel soon, and is currently available in the Nightly/Dev/Beta channels) provides people with a 7 day ad history, and options to thumbs up/down each ad, and the option to "like" or "opt-out" of the associated matching category from the ad catalog. 

This feature will help provide control for people to opt out of ads or categories that they would rather not see, provide additional feedback (anonymous, of course) to Brave to help us get a better read on negative feedback, which may prove to help influence our guidelines over time. 

To be candid, as we are a company that collects no personal data or information about the people that use the platform, it can be a bit of a balancing act between providing an ad platform and brands (and revenue), while also knowing (or not knowing) exactly what our user base has an affinity or dislike for. These features will help us learn more about that over time. 

We also don't want to necessarily reject one company over another from advertising because they have grown to a certain size. That is a difficult position to defend in the market, when we are providing a platform for brands to advertise. We have a lot of people from the community that have mentioned being Godaddy customers, and like their services. 

This is all different from Brave partnering with a product, brand or service, and integrating that product or service in Brave. Those decisions and positions are different than providing brands an equal opportunity to advertise in our opt-in ad platform. 

What I'll also mention is that within the past 30 days we have hired a head of sales and sales team that is working in earnest to bring additional brands to advertise on the platform. This will help bring more variety, which should hopefully help with the concerns stated in the initial post. 

I hope this helps, and that there's some understanding of how we are trying to strike a balance here between fairness, ethics and commercial advertising vs partnerships or endorsements. 

I am happy to follow up here to any additional questions you have.

**Comment by lukemulks** [comment]
Just an FYI - I'm going to close the issue, but you can still follow up here and I'll be sure to address any questions as they come in. Thanks.

**Comment by NumDeP** [comment]
Hi @lukemulks the first section of this is in reply to the features you mention and the second is in reference to the main point about ethics.

**First section**
> Regarding frequency: We are working on improving this within the product, but additionally, if a brand has a sizeable advertising buy, they are likely to appear more often as the platform aims to deliver the target amount of ads to fulfill the ad buy.

This seems like in the long run it will impact users in a negative way, especially considering the way ads are currently presented. To be honest, since it's roll out, I've only ever been pleased to have received three advertisements. Despite this, it's difficult to admit but being presented with practically ever other ad was a huge annoyance. I actually started thinking what is the difference between those ads and popups, which are surprisingly rare these days. 

Did the team go through several iterations of UI/UX of the displaying ads before you settled for the popup on the bottom right corner? I say because I may have a really good idea of one that will be less annoying but can still present the same ads, if not more without coming across as annoying.

I also like your description of the Ads History feature - some time ago I actually wanted to suggest something similar. Do remember when Microsoft's Hotmail when it came out? It used to give their users a multitude of advertisement options, being young I didn't realise what it was then and I used to randomly click things left, right and centre superficially, not knowing those were commercials based on user choice and a revenue stream for the so-called free Hotmail. Well, since Brave rolled out the bottom left popup ads, I thought about Hotmail's original registration stage and figured wouldn't that be a good idea for Brave, not exactly of course but Food for thought. 

> This feature will help provide control for people to opt out of ads or categories that they would rather not see,

Don't you think a caveat to this would be that a particular product, though a user opted out of its category would make the user miss something good?

**Second section**

> We also don't want to necessarily reject one company over another from advertising because they have grown to a certain size.That is a difficult position to defend in the market, when we are providing a platform for brands to advertise. 

I can understand that, however, I was just concerned about the fact that in situations like this, there's a terrible proclivity and greater chance of being approached and advertising a commercially monopolistic brand.  

I respect the fact you gave a succinct answer to my statements but I have to say parts of your comments I was sort of taken aback by. Such as:

> We have ad guidelines that we provide to buyers, and manually review every ad for quality control. Brave does not take a position regarding the ethics of the software providers mentioned, as this can be rather subjective.

Just to give you a couple of examples and not to come across as rude.

If Google and Microsoft approached Brave, Inc tomorrow and each of them said, we want you to advertise Chrome and Edge throughout a 24-hour period (I understand - not in the same hour because of the rules) with integrated k.im and we'll give you a million dollars every month, surely you wouldn't say yes. Would you? 

Without a doubt you'd hesitate, the whole team would hesitate, I mean why wouldn't you? You'd have an hour-long plus conversation speaking precisely about competition, conflict of interest and corruption just to throw an additional spanner in the works.

Another example - If a user watches porn, regrettably, like the many statistics present and several books that describe the shocking psychological effects of long term usage. Would the Brave team gladly allow the conglomerate, vile porn industry to advertise subscriptions to its many platforms as well as presenting users with locations of the nearest escort service, for want of a better expression? I really hope not.

To me, Brave literally presenting this on the platform would be a symbol of you not only promoting it, though you'd disagree but also condoning it because if you had any morals you wouldn't. 
>  how we are trying to strike a balance here between fairness, ethics and commercial advertising vs partnerships or endorsements.

I think in this context you will have strike-d out ethics and from what I've seen so far you haven't though I can't speak for other users but I hope my concern of it applies a modicum of pressure in the team.
