### ISSUE TITLE
Update order for onboarding flow

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#6562]
## Description 

New order for onboarding flow:
1. Welcome - Let's Go page
2. Import bookmarks and Settings
3. Manage your Shields 
4. Brave Rewards (1-click enable)
5. Search engine setting
6. Done

This removes the theme step from the onboarding flow as well as moving the search engine step last. This requires allowing users to enable Brave Rewards from step 4 and not kicking off to brave://rewards

## Actual result/Current flow:
1. Welcome - Let's Go page
2. Import bookmarks and Settings
3. Search engine
4. Theme
5. Shields
6. Rewards
7. Done

**Comment by srirambv** [comment]
@bradleyrichter @rebron can we plan on having all the steps done in one page rather than having new pages for each step? We should have something similar to what Opera does with cards. Gives us the option to have more things done on onboarding
![image](https://user-images.githubusercontent.com/17010094/67203944-68e88600-f3da-11e9-8715-39edc5c609c7.png)

**Comment by kjozwiak** [comment]
Agree with @srirambv that something like the above is more intuitive and gives the user a better overview of what can be enabled/imported when launching the browser for the first time. It might also improve engagement with the onboarding as users wouldn't need to navigate through several screens to make decisions.

**Comment by rebron** [comment]
Closing as invalid and stale. 

Current onboarding flow is intro, import, p3a notification, search engine settings, and rewards.
We'll create separate issues if there's new thinking around onboarding.
