### ISSUE TITLE
Port old repo shields settings

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#6639]
Basically we need to read through the old file which stores all shields settings and port it to a new brave-core's way.

**Comment by emerick** [comment]
Spoke with @SergeyZhukovsky and the approach we should take is to run this in `PackageReplacedBroadcastReceiver.java`, taking care to execute it via a service since long-running tasks will be killed there. Can use the approach taken by `UpgradeIntentService.startMigrationIfNecessary` (will need to be reinstated to some extent, as it was removed here https://chromium-review.googlesource.com/c/chromium/src/+/1627670).

**Comment by srirambv** [comment]
Marking as QA/No. Follow up issues #7902 &  #7903 are marked for release
