### ISSUE TITLE
Using webpack-bundle-analyzer results in strange text rendering

### ISSUE THREAD

**Issue by muuvmuuv** [brave/brave-browser#6667]
## Description 

Using webpack and the plugin `webpack-bundle-analyzer` results in strange behaviour of the font size in the foamtree grid.

## Steps to Reproduce

   1. create a webpack project
   2. use the mentioned plugin
   3. let it open the http analyzer server

## Actual result:

![67867011-128dec80-fb2a-11e9-938b-95d5b6b53618](https://user-images.githubusercontent.com/11534760/67874068-b381a500-fb34-11e9-8cda-a5a95b52e98f.png)

## Expected result:

Normal text 

## Reproduces how often: 

Every time. Seems like someone had this issue before.
https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/318

## Brave version (brave://version info)

Brave | 0.70.121 Chromium: 78.0.3904.70 (Offizieller Build) (64-Bit)
Überarbeitung | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
Betriebssystem | macOS Version 10.15 (Build 19A602)
JavaScript | V8 7.8.279.17

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? where can I download them?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no, there it works, and in all other browsers

## Miscellaneous Information:

Related issue: https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/325

**Comment by rebron** [comment]
@cezaraugusto Are you seeing this too? Can you give some context on this issue?

**Comment by cpboyd** [comment]
The issue seems to be related to setting "Block fingerprinting" to Strict

**Comment by pes10k** [comment]
Closing this out since "block fingerprinting" strict is going away, and we generally don't try to fix compat issues for "block fingerprinting" = "strict" in the first place (its why we encourage users to use the default setting). 

FWIW, "block fingerprinting=strict" is going away bc 1. most users are better served and more private in the default setting anyway, 2. having "block fingerprinting=strict" as a setting at bc a fingerprinting input itself, and 3. having these "wont fix" compat issues isn't good for anyone
