### ISSUE TITLE
A question, discussion, feature request about extensions

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#6721]
Have you searched for similar issues? Yes.

## 1) Description 

I couldn't find another place or label for it as it is more of a **question**, **discussion** as well as a **feature request** - issue about Brave/Chrome Webstore from either your own UI/UX design as well as from the view point of the distribution of extensions.

Does Brave expect to always utilise Chrome's Webstore?

Understandably Brave is doing everything possible to remove Google's branding away from Brave-Core, it makes sense seeing as you're predominantly in it for the Chromium code base. However, I was wondering whether over time as Brave becomes more and more successful if this will annoy Google and you're growing users for that matter because it gives the impression that you're sort of relying on Google, though you've removed some or still in the process of un-googling google out of Brave-Core.
 
## 2) chrome://extensions/

There has to be better manageability and organising of the brave://extensions page and not leave it the way it is currently in Chromium/Chrome and Brave-Core.

I will likely have in the range of 30 extensions - I can’t give a proper explanation as to how I personally want it to look and function but it would be nice to have it some how better organised and manageable and loadable if that makes sense, in that bit of chrome://extensions/ and within the bar where it is loaded.

Who has the most extensions installed the company? Get input from them as well as the community as the development of this side expands as well as this issue, if left open that is.

Thanks

**Comment by bsclifton** [comment]
cc: @rebron

**Comment by rebron** [comment]
Hi @NumDeP 

For question 1, we will likely always link out to Chrome Web Store as they have an extremely large library of extensions and want to give Brave users access to those Extensions (since they're compatible). We do make some modifications to the Chrome Web Store so that it does show 'Add to Brave' instead of 'Add to Chrome' for the installation as well as providing additional information during install of extensions. 

In the future, we are planning on showcasing specific extensions we've reviewed, partnered with, or otherwise really like. 

For question 2, thanks for the feedback on that. Extension management is an area that we will improve. We recognize advanced users who have tens to hundreds of extensions (as well as people with 100s of tabs open) and the current brave://extensions can be improved to help those users. Would invite you to go community.brave.com where we can discuss further, much better to discuss in community site than in github where we focus on implementation. 

Going to close out this issue. I'll reopen if you have a follow-up.
