### ISSUE TITLE
Blank command prompt keeps popping up when running from source

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#674]
## Description 

Blank command prompt keeps popping up when running from source

## Steps to Reproduce

   1. Build release from source
   2. Launch browser
   3. Blank command prompt keeps popping up and some doesn't close on its own

## Actual result:
![image](https://user-images.githubusercontent.com/17010094/43590555-3ca01d5a-963f-11e8-9ddf-9df7a29340e6.png)

## Expected result:
Should not be shown ideally but if it has to be shown should close automatically

## Reproduces how often: 

100%

## Brave version (about:brave info) 

1532e5100cd29a1be7257cab653f7cdd00784f59

### Reproducible on current release:

N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

@emerick confirmed seeing similar popup windows as well

**Comment by emerick** [comment]
The window pops up and disappears quickly. When running in the debugger, it remains a little longer and has some logging data in it. The few times I was able to catch it, it mentioned something about "field trials". Seems like something we'd want to disable, in order to provide a consistent user experience.

**Comment by srirambv** [comment]
For me running with `npm run start Release` I get the popup but it doesn't show anything when it remains like that for a long time
