### ISSUE TITLE
Brave is hanging or not responsive (macOS Catalina)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#6743]
## Description 
Browser hanging / unresponsive / using all CPU on macOS Catalina

## Steps to Reproduce

   1. Be on macOS Catalina
   2. ??? (unsure if this is a specific config? or affects all users?)
   3. Launch Brave

## Actual result:
Browser hangs, is unresponsive. May be unusable.

## Expected result:
Browser should be responsive, shouldn't hang. Processes should clean up when user quits browser

## Known incident reports
- https://community.brave.com/t/brave-not-responding-on-catalina/86757
- https://community.brave.com/t/mac-catalina-brave-crashes-after-10-seconds/90264
- https://community.brave.com/t/i-cant-launch-brave-on-macos-catalina/89724/13 (stopped working for user after 3 days)
- https://community.brave.com/t/brave-stops-after-booting-mac/89808
- https://community.brave.com/t/kernel-panic-on-mac-using-high-sierra-10-13-6/82404/2 (last person commenting on thread saw crash on Catalina)
- https://community.brave.com/t/brave-is-locking-using-macos-catalina/87858/8
- https://community.brave.com/t/brave-using-around-1-5go-memory-on-mac-os-catalina/87402 (might be a case of processes not cleaning up? user only has 3 tabs)

**Comment by bsclifton** [comment]
Happened to @kjozwiak - but then it went away 🤔

**Comment by kjozwiak** [comment]
> Happened to @kjozwiak directly after upgrade - but then issue went away 🤔 (even for new profiles)

Here's some notes of what I experienced when I updated from `Mojave` -> `Catalina`. Once macOS finished updating, I got prompted several permission requests from various applications. Once I accepted the permissions, I launched `0.73.55 CR: 78.0.3904.87` and within ~2-3 minutes my MBP was at 100% CPU. I tried closing the browser but the process was still running in the background and needed to be killed via the `Activity Monitor`.

* happened on all current versions of Brave (`Release`, `Beta`, `Dev`, `Nightly`)
* even with new profiles without enabling anything nor loading any websites, the CPU would reach 100%
* restarted the MBP and the issue was still occurring
* disabled and enabled notifications for Brave via `Notifications` under  macOS's `System Preferences` but the CPU kept reaching 100%

After about ~30-40mins of the above, the issue basically stopped happening. The only thing that changed was enabling `Record Screen` for Zoom but I don't think that was related. Maybe some type of permission finally got access?

Anyone who runs into the above issue won't be able to use Brave as it will basically use all the available resources and slow down the entire machine.

**Comment by Brave-Matt** [comment]
@bsclifton -- more user reports of Catalina crashing. I initially assumed it was Sync related but that doesn't seem to be the case. May be extension related but still worth looking into:
https://community.brave.com/t/latest-brave-on-mac-continuously-crashing/89657/25

**Comment by Brave-Matt** [comment]
Another user -- still waiting on more info from them:
https://www.reddit.com/r/brave_browser/comments/douppk/brave_crashing_a_lot_on_macos_version_070121/

**Comment by rebron** [comment]
Closing. @Brave-Matt reopen if we're still getting additional reports with Catalina.
