### ISSUE TITLE
Rename placeholder text for URL bar

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#682]
## Description 

Rename placeholder text for URL bar

## Actual result:
![image](https://user-images.githubusercontent.com/17010094/43643668-073b511e-96fa-11e8-842b-7c61ad102fba.png)

## Expected result:
Should be replaced to `Enter a URL or a search term`

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Release build on master

### Reproducible on current release:

N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
I think this is fine actually because the search engine is Google. If you change your search engine to DuckDuckGo for example it will say DuckDuckGo instead. The extra information here I think is a net positive. The Design team can post an issue though to override this decision but not sure about prioritization in any case given that it is sound as is.
