### ISSUE TITLE
Add to GNOME app center

### ISSUE THREAD

**Issue by SephReed** [brave/brave-browser#6865]
## Description 

It would be nice if it was easier to install Brave on GNOME based OSes

https://wiki.gnome.org/Apps/Software

Currently the instructions are very easy, but it would still be nice if was just that tiny bit easier.

**Comment by fmarier** [comment]
Are you referring to having Brave included in the official repositories of a specific Linux distribution, or is there a generic GNOME "app store" somewhere?

**Comment by SephReed** [comment]
https://wiki.gnome.org/Apps/Software

While many distros have made their own repos, Ubuntu is moving over to this one.  Also, it's pretty easy to install the repo on anything debian (I think).

**Comment by fmarier** [comment]
> https://wiki.gnome.org/Apps/Software

Apologies if I'm overlooking something obvious, but that looks like an interface to browse a package repository. Is there a link to the GNOME package repo? I didn't see one on that page.

If there is such a repo, how do we package software for it and how do submit a package for inclusion?

**Comment by SephReed** [comment]
I'm sorry, I don't fully know.  I had been using a fork of Ubuntu (Elementary), and it was suggested to add the GNOME app center on top.  I found some instructions here:

https://askubuntu.com/questions/524984/how-do-you-install-gnome-software-center

Perhaps I had mistakenly taken some bad advice and this software center is not really very widely used.  Reading up on Ubuntu history, it appears they backtracked on their decision to make it the defacto software center.

Overall, it isn't hard at all to install brave on Linux devices, certainly no harder than using one in general.  But I really like you guys and (for some reason) think that it would be really cool if installing Brave was as easy as humanly possible.

**Comment by fmarier** [comment]
Ok, so I think that the way it works is that GNOME Software is an interface to display the apps available in the OS repository. So for Ubuntu and its derivatives that means the Ubuntu official package repository.

So in order for Brave to show up on there, we'd need to file for inclusion of our packages in their official repository (or in Debian's since Ubuntu is itself a derivative of Debian). That's also the request that was made in #4786 and so I will close this issue as a duplicate.

Another way, which would require less work, to make Brave easy to install on Ubuntu would be to provide an officially-supported snap package (#1007).

**Comment by SephReed** [comment]
Both of these are great solutions.  Thanks for hearing me out.
