### ISSUE TITLE
Update error on windows from 0.53.0 to 0.53.1

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#687]
## Description 

Autoupdater doesn't inform to restart to apply updates

## Steps to Reproduce

   1. Install `0.53.0` build 
   2. Go to `chrome://settings/help` to check for update
   3. Once update is found it starts downloading
   ![image](https://user-images.githubusercontent.com/17010094/43691923-e56221aa-98f0-11e8-9af9-e3cc6d9a77ea.png)
   4. Once updated is downloaded doesn't prompt to restart to apply the update, instead shows download error and the `Learn more` page points to [Google support page](https://support.google.com/chrome?p=update_error)
    ![image](https://user-images.githubusercontent.com/17010094/43691931-0a205048-98f1-11e8-8936-e26ef7477bb0.png)
   5. Restart browser, updates are applied and its upgraded to `0.53.1`

## Actual result:

Autoupdater doesn't inform to restart to apply updates

## Expected result:
Once update is downloaded should prompt to restart the browser to apply changes

## Reproduces how often: 

100%

## Brave version (about:brave info) 

0.53.0 -> 0.53.1

### Reproducible on current release:

N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @RyanJarv @mbacchi @simonhong @bbondy

**Comment by RyanJarv** [comment]
The fact it's not restarting here is due to some issue during windows updates from 0.50.0 to 0.50.1. It's just that it appears to happen after the update is more or less finished and restarting the browser  manually launches the new version.

Displaying the error message is likely correct behavior, and we need to dig into what is throwing the error. Which is made somewhat difficult due to https://github.com/brave/brave-browser/issues/688.

Don't have a ticket open on this already so going to go ahead and change the title to reflect it's an error with the updater.

**Comment by bbondy** [comment]
still an issue?

**Comment by srirambv** [comment]
moving to 1.x backlog until stub installer is able to point to a specific release to test upgrade scenarios

**Comment by srirambv** [comment]
Couldn't reproduce the issue on my Windows install. Looks fixed. Would be good to have a second set of eyes test this. @GeetaSarvadnya or @btlechowski could you guys give it a test on your Windows and see if the issue still happens? Please go ahead and close the issue if you can't reproduce the error.

**Comment by btlechowski** [comment]
I was unable to reproduce the issue.
