### ISSUE TITLE
Disabling Brave Wallet requires a browser restart

### ISSUE THREAD

**Issue by dpazdan** [brave/brave-browser#6902]
## Description 

Currently if the buit-in Brave wallet is disabled, other wallets such as MetaMask will still not work unless the browser is closed and re-opened.

## Expected result:
Most users expect to be able to immediately use other solutions once the Brave wallet is disabled.  

## Other Additional Information:
At a minimum, providing clear information via a prompt or next to the wallet toggle, stating a restart is necessary would suffice.  Ideally preventing a restart all-together would be best.

Related to #6301

**Comment by SCBuergel** [comment]
I just want to highlight that IMO this issue is severe. To the naive user like myself it seems more logical that disabling the Brave wallet does not work. Having to restart the browser is not intuitive. As a consequence users might change back to Firefox or Chrome and import their seed phrase which is a significant risk as the unencrypted seed phrase is passed around.

**Comment by bbondy** [comment]
This will be deprecated with this work, so I'm closing this issue:
https://github.com/brave/brave-browser/issues/7503
