### ISSUE TITLE
changing default UI theme color (from orange)

### ISSUE THREAD

**Issue by kyangEPS** [brave/brave-browser#6911]
Pretty simple questions: how do/can I change the default UI accent color (as seen in the URL bar when highlighted or the loading circle animation) from orange to some other color?

I would prefer not to use a chrome theme extension, but if that is the only way could you point me to a good one to use?

Thanks!

**Comment by bsclifton** [comment]
@kyangEPS good question- there isn't a super easy way to do this, unfortunately. We edited the code to change those colors. @petemill and @mkarolin are the most familiar with that area of the code. For example, the focus ring that's around the omnibox is set here:
https://github.com/brave/brave-core/blob/22a8916ad4aeef3e8e054ca9f5b319a459bc2e5e/chromium_src/ui/views/controls/focus_ring.cc

You might be able to change the theme via an extension... but I'm not familiar with one. It's also possible our code overrides that value too (and forces it to be orange).

I'm going to close the issue... but I would recommend trying to change the theme using an extension and let us know what works / doesn't work. We can then create an issue to properly override the values so that user-provided theme values are respected 😄

**Comment by kyangEPS** [comment]
Alright 👍 Thank you for your help and input! After some time I had just gotten used to the colors and stuck with it. I'll keep my eyes out for stuff in the future!

**Comment by rudyjb24** [comment]
Regarding @bsclifton response, I tried changing the theme using an extension but it didn't change for example the orange accent around the URL bar. Has this been addressed somewhere else?

**Comment by dpthegrey** [comment]
I would love for omnibox, search result or button colours highlight to adapt to system accent on macOS, chrome changes omnibox border and looks nice. I believe brave should allow that on users what accent they want.
