### ISSUE TITLE
Diff icons for diff build channels

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#7041]
We need to have diff app icons for diff channels https://github.com/brave/brave-core/tree/master/app/theme/brave/android. Currently only `res_brave_default` and `res_brave` have correct icons.
Please pick the same icons as desktop has https://github.com/brave/brave-core/tree/master/app/theme/brave and put it under appropriate folders with diff resolutions such as
https://github.com/brave/brave-core/tree/master/app/theme/brave/android/res_brave_beta/mipmap-hdpi
https://github.com/brave/brave-core/tree/master/app/theme/brave/android/res_brave_beta/mipmap-mdpi
https://github.com/brave/brave-core/tree/master/app/theme/brave/android/res_brave_beta/mipmap-xhdpi
https://github.com/brave/brave-core/tree/master/app/theme/brave/android/res_brave_beta/mipmap-xxhdpi
https://github.com/brave/brave-core/tree/master/app/theme/brave/android/res_brave_beta/mipmap-xxxhdpi

**Comment by jamesmudgett** [comment]
[brave android.zip](https://github.com/brave/brave-browser/files/3872825/brave.android.zip)

**Comment by yrliou** [comment]
@jamesmudgett From our previous discussion, we're going to use the same file for both `res_brave_beta/drawable-hdpi/fre_product_logo.png` and `res_brave_beta/mipmap-hdpi/app_icon.png` (same for other folders).
It turns out chromium doesn't allow it (failed at android lint), I'll get 
```
chrome/android/java/res_chromium/mipmap-hdpi/app_icon.png The following unrelated icon files have identical contents: fre_product_logo.png, app_icon.png: IconDuplicates [warning]
```
Could you provide dev/beta/nightly icons for drawable-* folders, maybe use the same size as in `res_brave_default` and `res_brave`? Thanks.
You could found the drawable-* folders under each res_brave* folders under https://github.com/brave/brave-core/tree/master/app/theme/brave/android.

**Comment by jamesmudgett** [comment]
[android.zip](https://github.com/brave/brave-browser/files/3923991/android.zip)
