### ISSUE TITLE
C79 bump breaks bottom toolbar on Android

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#7051]
With c79 bump the bottom toolbar is not visible on Android.

The following Chromium could be the cause: https://chromium.googlesource.com/chromium/src/+/404ca6f

**Comment by yrliou** [comment]
I think it's because of this being removed https://github.com/brave/brave-core/pull/4043/commits/fd53b08cb8cc745d851b9d31ee1d752505a73f00#diff-b10ff3d189e1d10c485d3ea766c0caca because it cannot be applied anymore.
I think a possible solution is to comment out this line https://cs.chromium.org/chromium/src/chrome/android/java/src/org/chromium/chrome/browser/flags/FeatureUtilities.java?type=cs&q=isBottomToolbarEnabled&sq=package:chromium&g=0&l=110, but I don't have C79 at hand for testing it at the moment.

**Comment by yrliou** [comment]
Also, currently we let ChromePreferenceManager extends BravePreferenceManager and provide `isBottomToolbarEnabled` from BravePreferenceManager, which was used to override the chromium behavior by calling `ChromePreferenceManager.getInstance().isBottomToolbarEnabled()` in `FeatureUtilities.java`.

**Comment by mkarolin** [comment]
Ok, I think I just looked at a wrong place since they moved the file and it's showing a much different history on cs.chromium.org. The actual change is https://chromium.googlesource.com/chromium/src/+/09c5916 and is much less impactful. They just moved all those statics into a map. Will update the original patch.
