### ISSUE TITLE
Uphold pending user problem

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7122]
## Description 

Users are stuck in verify wallet flow. Examples: https://community.brave.com/t/unable-to-verify-wallet/92672/2 and https://www.reddit.com/r/BATProject/comments/dzw87k/browser_bat_not_syncing_with_uphold_wallet/f8arzg0/?context=3

## Steps to Reproduce

   1. Start browser
   2. Enable rewards
   3. Click on Verify wallet
   4. Close uphold tab
   5. Close browser 
   5. Open `Preferences` file and modify `brave->rewards->external_wallets->uphold->status` to `5`
   6. Start browser
   7. Open uphold page and log in with KYC account
   7. Open panel and click verify wallet

## Actual result:

You are redirected to uphold page where it says Congratulations.

## Expected result:
You should be redirected to authorize page

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan mentioned in https://github.com/brave/brave-core/pull/4085
- Verified that the original issue is reproducible in 1.0.1
- Verified that the issue is fixed and working as expected in 1.1.18 used test plan mentioned https://github.com/brave/brave-core/pull/4085
- Verified that the issue is working fine in upgraded profile, Click on Verify wallet in the panel is redirected to `brave://rewards/#verify modal` and again click on verify in modal is redirected to authorize page as expected.
