### ISSUE TITLE
Normal window hamburger option settings are displayed in TOR window

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7224]
## Description 

Normal window hamburger option settings are displayed in TOR window

## Steps to Reproduce

   1. Clean profile 1.1.18
   2. Open a tor window
   3. Normal window hamburger option settings are displayed in TOR window

## Actual result:

Normal window hamburger option settings are displayed in TOR window
![image](https://user-images.githubusercontent.com/38657976/70261621-d0a33680-17b8-11ea-9273-7a789164cb8e.png)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/70260697-d7c94500-17b6-11ea-8634-943811cc477b.png)

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bsclifton @yrliou

**Comment by LaurenWags** [comment]
@GeetaSarvadnya I think this is expected per https://github.com/brave/brave-core/pull/3813#issue-333822010

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Agreed it's as expected as per https://github.com/brave/brave-core/pull/3813#issue-333822010. Highlighted the items which are regressed.

**Comment by LaurenWags** [comment]
Thanks @GeetaSarvadnya.

I can see these options in 1.1.17 - the build before C79 was added. So this is not a C79 regression, but possibly related to the PR noted in above comments. cc @yrliou as well.

<img width="1196" alt="Screen Shot 2019-12-05 at 2 02 32 PM" src="https://user-images.githubusercontent.com/28145373/70265214-f05e3e80-1767-11ea-82a2-8600e6897a1c.png">

**Comment by yrliou** [comment]
I think it's our expected behavior to be align with private windows, from 1.1, Tor window is now a private window and not a guest window anymore.
Clicking on those items in Tor window will open the pages in the normal window like private windows do.

Below are the screenshots for hamburger menus in private window and private window with Tor on mac using nightly, which is basically the same, only difference is that Tor has an extra for opening new Tor connection.

<img width="370" alt="Screen Shot 2019-12-06 at 6 01 20 AM" src="https://user-images.githubusercontent.com/4730197/70277966-51305a00-17ee-11ea-97bf-574e4066f92a.png">
<img width="379" alt="Screen Shot 2019-12-06 at 6 01 07 AM" src="https://user-images.githubusercontent.com/4730197/70277970-52fa1d80-17ee-11ea-9ba5-f16c7446076e.png">

**Comment by yrliou** [comment]
Adding to above comment, I don't think it's a regression, but an outcome of being a private window.
If we would like to hide some items, from my point of view, we should probably fix it on private windows, and Tor window will just get the updated behavior from that.

cc @tomlowenthal

**Comment by tomlowenthal** [comment]
Agreed — working as intended.
