### ISSUE TITLE
After clicking update, my tabs and recent history was lost!

### ISSUE THREAD

**Issue by nlune** [brave/brave-browser#7265]
I clicked update on brave browser because i had problems installing an extension. I didn't expect that my recent open tabs would all be gone! 

After clicking the restore tabs button, it only restored the tabs and history from 3 days ago. I checked the history and all the most recent history is gone. It was only from Dec. 4th. I am using the latest version Ubuntu (xubuntu desktop). 

I am so frustrated about this that I think I will go back to using Chrome if there is no fix...

**Comment by TheShanMan** [comment]
I had this happen a while back (perhaps around the same time but not sure), and I just had it happen again today. The first time, I _eventually_ got my tabs back (after restarting brave once or twice and/or updating brave they just seemed to come back). Hoping they'll come back this time too because I had a bunch! It's becoming pretty annoying. I also found this open issue: https://github.com/brave/brave-browser/issues/4416

**Comment by bsclifton** [comment]
Closing as stale / duplicate of https://github.com/brave/brave-browser/issues/4416
