### ISSUE TITLE
Support unattended-upgrade under linux

### ISSUE THREAD

**Issue by palortoff** [brave/brave-browser#7445]
Please provide support for `unattended-upgrade` under Linux.

`unattended-upgrade` is configured using `Unattended-Upgrade::Origins-Pattern` in the apt configuration. Brave does not provide the necessary properties like `origin` and `label`.

Running `apt-cache policy` provides this output for brave:
```
500 https://brave-browser-apt-release.s3.brave.com buster/main amd64 Packages
     release o=. buster,a=buster,n=buster,l=. buster,c=main,b=amd64
```

Values like `o=. buster` and `l=. buster` are very generic and do not allow to configure `unattended-upgrade` for brave separately.

I am running brave on Debian buster.

This is my `/etc/apt/sources.list.d/brave.list`:
```
deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ buster main
```

**Comment by fmarier** [comment]
This is [now fixed](https://github.com/brave/brave-core/pull/4072) but only if you change your source line to:

    deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main

(`stable` instead of `buster`).

We couldn't update the old ones without triggering security warnings and breaking updates for existing users and so we took advantage of the fact that we have migrated to a single `stable` distro for all of our packages.

This is now the preferred way to pull down the packages and you no longer need to update the distro version when upgrading to a new OS version.

**Comment by fmarier** [comment]
For reference, this is what I have in my `/etc/apt/apt.conf.d/50unattended-upgrades`:
```
Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}";
	"${distro_id}:${distro_codename}-security";
	// Extended Security Maintenance; doesn't necessarily exist for
	// every release and this system may not have it installed, but if
	// available, the policy for updates is such that unattended-upgrades
	// should also install from here by default.
	"${distro_id}ESM:${distro_codename}";
//	"${distro_id}:${distro_codename}-updates";
//	"${distro_id}:${distro_codename}-proposed";
//	"${distro_id}:${distro_codename}-backports";
	"Google LLC:stable";
	"Brave Software:stable";
	"LP-PPA-fmarier:bionic";
};
```

**Comment by palortoff** [comment]
Great, thanks! 

Happy new year!
