### ISSUE TITLE
Stats not visible on NTP

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7543]
## Description 

Stats not visible on NTP

## Steps to Reproduce

   1. Install beta build
   2. Open a new tab, stats values are not shown
   3. Visit `https://theverge.com`, open a second new tab, stats still not shown

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/71589589-62ba0880-2af3-11ea-8a61-4d0d214853a1.png)

## Expected result:
Show stats 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Android-Core Beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @SergeyZhukovsky @samartnik added Android-core-release label as this should be fixed

**Comment by srirambv** [comment]
Looks even horrible when theme is set to dark
![image](https://user-images.githubusercontent.com/17010094/71590071-33a49680-2af5-11ea-9fdf-cfcf65c60826.png)

**Comment by yrliou** [comment]
Our stats were implemented by replacing NewTabPageView with our own subclass, which doesn't work anymore after https://chromium.googlesource.com/chromium/src/+/300b7ec03bcfccf170aeb84affe165f2aa07617c is merged in Chromium 79.0.3923, which enabled `InterestFeedContentSuggestions` feature by default because it will use FeedNewTabPage which won't use NewTabPageView.

For reference, browser-android-tabs disables this feature to fix this  https://github.com/brave/browser-android-tabs/commit/65a0e8649b2e8e7362f517631e73bb6cda3d6210

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running x64 build
- Verified stats visible on light theme
![image](https://user-images.githubusercontent.com/17010094/73098778-1080c300-3eb8-11ea-8641-f156172ecca5.png)
- Verified stats visible on dark theme
![image](https://user-images.githubusercontent.com/17010094/73098790-15457700-3eb8-11ea-8c17-533d1c69f39b.png)
--------
Verification passed on Samsung Tab A with Android 9 running x64 build
- Verified stats visible on light theme
![image](https://user-images.githubusercontent.com/17010094/73098792-1a0a2b00-3eb8-11ea-832e-e5b5cfbc30e5.png)
- Verified stats visible on dark theme
![image](https://user-images.githubusercontent.com/17010094/73098801-2098a280-3eb8-11ea-8071-aa6514a0062d.png)
