### ISSUE TITLE
AC with virtual grants flow with uphold funds

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7595]
If user has user funds (uphold) we need to have a way to covert this BAT into unblinded tokens. We will be using new SKU flow to accommodate that.

**Comment by LaurenWags** [comment]
@NejcZdovc does this issue also cover the AC notification on the BAT logo? Meaning, if I do an auto contribute with an Uphold KYC'd wallet using 1.3.97, the AC appears to go thru (my wallet balance is decreased), but I don't get a notification on my BAT logo.
<img width="1192" alt="4133-KYCdwallet" src="https://user-images.githubusercontent.com/28145373/72810926-9983ca00-3c2c-11ea-8983-54cd2b52b2e7.png">
(note - the AC also isn't listed in the summary, this is covered with #7526)

**Comment by NejcZdovc** [comment]
@LaurenWags this is a separate issue. Can you please double check if everything is ok on 1.2? Please log if you can reproduce this. Thank you

**Comment by LaurenWags** [comment]
Does not reproduce in 1.2.x. 

Additionally, found a second scenario in which there's no AC notification. 

Logged https://github.com/brave/brave-browser/issues/7836 to cover both cases. If they should be separate lmk - happy to log another issue if needed.

**Comment by 05K4R** [comment]
Is this one confirmed to fix the Bat Ledger Service CPU issue, or do we need to wait for https://github.com/brave/brave-core/pull/5568 as suggested in https://github.com/brave/brave-browser/issues/8846?

**Comment by GeetaSarvadnya** [comment]
This issue will be tested once https://github.com/brave/brave-browser/issues/10058 is fixed, as AC needs to be tested with multiple publishers.

**Comment by GeetaSarvadnya** [comment]
Verification is in progress

```

Brave | 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Windows 10 OS Version 1803 (Build 17134.1006)


```
- Verified the test plan from https://github.com/brave/brave-core/pull/4869

**1. Uphold funds AC**

**Comment by LaurenWags** [comment]
Verified the following cases using below build and staging env:

```
Brave	1.10.82 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	macOS Version 10.14.6 (Build 18G3020)
```

### Uphold AC SKU TCs (single funding source)

#### VG only (ex. UGP grant):
2. [PASS] Verify a one time tip only can be performed using a wallet funded only with virtual grants.
3. [PASS] Verify a monthly recurring contribution only can be performed using a wallet funded only with virtual grants. Note - AC was not explicitly toggled off with this check, but the list was empty prior to reconcile. AC toggled off was checked via #10006.
6. [PASS] Verify a one time tip and a monthly recurring contribution can be performed using a wallet funded only with virtual grants. Note - AC was not explicitly toggled off with this check, but the list was empty prior to reconcile.

#### User Funds only (restored wallet funded anonymously from when this was allowed in UI):
9. [PASS] Verify a one time tip only can be performed using a wallet funded only with user funds.
10. [PASS] Verify a monthly recurring contribution only can be performed using a wallet funded only with user funds. Note - AC was not explicitly toggled off with this check, but the list was empty prior to reconcile.
13. [PASS] Verify a one time tip and a monthly recurring contribution can be performed using a wallet funded only with user funds. Note - AC was not explicitly toggled off with this check, but the list was empty prior to reconcile.

#### Uphold only (KYC'd user wallet):
16. [PASS] Verify a one time tip only can be performed using a KYC'd user wallet funded only with BAT from Uphold

Verified the following cases using below build and staging env:

```
Brave	1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
Revision	94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS	macOS Version 10.14.6 (Build 18G3020)
```

#### Uphold only (KYC'd user wallet):
17. [PASS] Verify a monthly recurring contribution only can be performed using a KYC'd user wallet funded only with BAT from Uphold
20. [PASS] Verify a one time tip and a monthly recurring contribution can be performed using a KYC'd user wallet funded only with BAT from Uphold

Verified the following cases using below build and staging env:

```
Brave	1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
Revision	326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS	macOS Version 10.14.6 (Build 18G3020)
```

#### VG only (ex. UGP grant):
1. [PASS] Verify auto contribute only can be performed using a wallet funded only with virtual grants. Restart the browser, confirm nothing contributes unexpectedly.
4. [PASS] Verify a one time tip and auto contribute can be performed using a wallet funded only with virtual grants. Restart the browser, confirm nothing contributes unexpectedly.
5. [PASS] Verify a monthly recurring contribution and auto contribute can be performed using a wallet funded only with virtual grants. Restart the browser, confirm nothing contributes unexpectedly.
7. [PASS] Verify a one time tip, a monthly recurring contribution, and auto contribute can be performed using a wallet funded only with virtual grants. Restart the browser, confirm nothing contributes unexpectedly. 

#### User Funds only (restored wallet funded anonymously):
8. [PASS] Verify auto contribute only can be performed using a wallet funded only with user funds. Restart the browser, confirm nothing contributes unexpectedly.
11. [PASS] Verify a one time tip and auto contribute can be performed using a wallet funded only with user funds. Restart the browser, confirm nothing contributes unexpectedly.
12. [PASS] Verify a monthly recurring contribution and auto contribute can be performed using a wallet funded only with user funds. Restart the browser, confirm nothing contributes unexpectedly.
14. [PASS] Verify a one time tip, a monthly recurring contribution, and auto contribute can be performed using a wallet funded only with user funds. Restart the browser, confirm nothing contributes unexpectedly.

#### Uphold only (KYC'd user wallet):
15. [PASS] Verify auto contribute only can be performed using a KYC'd user wallet funded only with BAT from Uphold
18. [PASS] Verify a one time tip and auto contribute can be performed using a KYC'd user wallet funded only with BAT from Uphold
19. [PASS] Verify a monthly recurring contribution and auto contribute can be performed using a KYC'd user wallet funded only with BAT from Uphold. Restart the browser, confirm nothing contributes unexpectedly.
21. [PASS] Verify a one time tip, a monthly recurring contribution, and auto contribute can be performed using a KYC'd user wallet funded only with BAT from Uphold. Restart the browser, confirm nothing contributes unexpectedly.

#### VG/User Funds Split:
22. [PASS] Have a wallet with VG BAT and BAT from a restored user wallet. Set AC budget so all VG will be used and remaining amount will come from user funds. Perform AC and confirm it is completed as expected without errors. Verify this is displayed in monthly statement and sources for BAT are correct. 
23. [PASS] Have a wallet with VG BAT and BAT from a restored user wallet. Tip a verified publisher so that all VG will be used and remaining amount will come from user funds. Confirm tip is completed as expected without errors. Verify this is displayed in monthly statement. Restart browser. Confirm nothing is contributed unexpectedly.
24. [PASS] Have a wallet with VG BAT and BAT from a restored user wallet. Set up a monthly contribution to a verified publisher so that all VG will be used and remaining amount will come from user funds. Confirm monthly contribution is completed as expected without errors. Verify this is displayed in monthly statement. Restart browser. Confirm nothing is contributed unexpectedly.

#### User Funds/Uphold Split:
25. [FAIL - #10224] Have a KYC'd Uphold user wallet and BAT from a restored user wallet. Set AC budget so all restored BAT will be used and remaining amount will come from KYC'd wallet. Perform AC and confirm it is completed as expected without errors. Verify this is displayed in monthly statement. Restart the browser, confirm nothing contributes unexpectedly.

#### VG/Uphold Split
28. [PASS] Have a KYC'd Uphold user wallet and VG BAT. Set AC budget so all VG BAT will be used and remaining amount will come from KYC'd wallet. Perform AC and confirm it is completed as expected without errors. Verify this is displayed in monthly statement and sources for BAT are correct. Restart the browser, confirm nothing contributes unexpectedly.
29. [PASS] Have a KYC'd Uphold user wallet and VG BAT. Tip a KYC'd publisher so that all VG BAT will be used and remaining amount will come from KYC'd wallet. Confirm tip is completed as expected without errors. Verify this is displayed in monthly statement. Restart the browser, confirm nothing contributes unexpectedly.
30. [PASS] Have a KYC'd Uphold user wallet and VG BAT. Set up a monthly contribution to a KYC'd publisher so that all VG BAT will be used and remaining amount will come from KYC'd wallet. Confirm monthly contribution is completed as expected without errors. Verify this is displayed in monthly statement. Restart the browser, confirm nothing contributes unexpectedly.

Verified the following cases using below build and staging env:

```
Brave	1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
Revision	326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS	macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/4869
* For each scenario in the test plan, 
   * Confirmed AC, recurring, and one time tips were contributed as expected
   * Confirmed they displayed in the UI as expected (summary panel and Monthly Summary)
   * Confirmed there were calls to `/v1/votes` in the logs as expected



Note - the following test cases were skipped due to internal discussions (low use case scenarios, can revisit these as needed): https://bravesoftware.slack.com/archives/C7VLGSR55/p1591893693140700?thread_ts=1591889666.135600&cid=C7VLGSR55

#### User Funds/Uphold Split:
26. [SKIPPED] Have a KYC'd Uphold user wallet and BAT from a restored user wallet. Tip a KYC'd publisher so that all restored BAT will be used and remaining amount will come from KYC'd wallet. Confirm tip is completed as expected without errors. Restart the browser, confirm nothing contributes unexpectedly.
27. [SKIPPED] Have a KYC'd Uphold user wallet and BAT from a restored user wallet. Set up a monthly contribution to a KYC'd publisher so that all restored BAT will be used and remaining amount will come from KYC'd wallet. Confirm monthly contribution is completed as expected without errors. Restart the browser, confirm nothing contributes unexpectedly.

#### VG/User Funds/Uphold Split
31. [SKIPPED] Have a wallet with 20 BAT from VG, 20 BAT from a restored user wallet, and 10 BAT from KYC'd Uphold user wallet (total 50 BAT). Set AC to 50 BAT. Perform AC and confirm it is completed as expected without errors. Verify this is displayed in monthly statement and sources for BAT are correct.
32. [SKIPPED] Have a wallet with 20 BAT from VG, 20 BAT from a restored user wallet, and 10 BAT from KYC'd Uphold user wallet (total 50 BAT). Tip a KYC'd publisher 50 BAT. Confirm tip is completed as expected without errors. Verify this is displayed in monthly statement.
33. [SKIPPED] Have a wallet with 20 BAT from VG, 20 BAT from a restored user wallet, and 10 BAT from KYC'd Uphold user wallet (total 50 BAT). Do a monthly contribution to a KYC'd publisher for 50 BAT. Confirm monthly contribution is completed as expected without errors. Verify this is displayed in monthly statement.
