### ISSUE TITLE
Fix P3A metrics reporting wallet state

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#7633]
```
Brave.Rewards.WalletBalance
Brave.Rewards.AutoContributionsState
Brave.Rewards.TipsState
Brave.Rewards.AdsState
```
These metrics should have "Brave Rewards is off" as the first answer, instead of "No wallet created". Definitions on https://github.com/brave/brave-browser/wiki/P3A also should be fixed.

**Comment by iefremov** [comment]
@davidtemkin

**Comment by bsclifton** [comment]
See https://github.com/brave/brave-browser/issues/7679 for more details by @davidtemkin

**Comment by mattmcalister** [comment]
Confirming the revised question more specifically:

```
What is the state of Brave Rewards? 
0) Never enabled
1) Disabled
2) Enabled
```

**Comment by iefremov** [comment]
@mattmcalister is it supposed to be a new question?

**Comment by mattmcalister** [comment]
This serves two functions: 

1. reframing of the standard questions used for Brave.Rewards.WalletBalance, Brave.Rewards.AutoContributionsState, Brave.Rewards.TipsState, Brave.Rewards.AdsState, and 
2. revised Q11 which was never implemented (See: https://github.com/brave/brave-browser/wiki/P3A)

eg. Q12 would be rewritten as:

How much BAT, excluding grants, is in your wallet?
(Brave.Rewards.WalletBalance)

0) BR never enabled
1) BR disabled
2) Less than 10 BAT (0-9), excluding grants
3) 10-50 BAT, excluding grants
4) Over 50 BAT, excluding grants

**Comment by iefremov** [comment]
```
Brave.Rewards.WalletBalance
Brave.Rewards.AutoContributionsState
Brave.Rewards.TipsState
Brave.Rewards.AdsState
```
renamed to 
```
Brave.Rewards.WalletBalance.2
Brave.Rewards.AutoContributionsState.2
Brave.Rewards.TipsState.2
Brave.Rewards.AdsState.2
```

**Comment by kjozwiak** [comment]
@iefremov mind adding some cases into either https://github.com/brave/brave-browser/issues/7633#issue-546334103 or https://github.com/brave/brave-core/pull/4414 that QA can use to verify this?

**Comment by iefremov** [comment]
For QA:

On existing profile:
1) Open `chrome://local-state`, find `p3a` values
2) `Brave.Rewards.WalletBalance` and friends should be replaced by `Brave.Rewards.WalletBalance.2`

On a new profile:
After a startup, after a while all mentioned metrics should be contain `0` value at `chrome://local-state`. After enabling/disabling rewards, all of them should be set to `1`. Other values should be set as expected before this change (note that there is a known bug regarding wrong `WalletBalance`)

**Comment by GeetaSarvadnya** [comment]
@iefremov  Wiki page needs to be updated. Still, I could see `No wallet created` instead of "Brave Rewards is off". Please update the Q.12 Q.13 Q.14 and Q.17

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress


Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified https://github.com/brave/brave-browser/issues/7633#issuecomment-584577515
```
- Verified that `Brave.Rewards.WalletBalance` is renamed to `Brave.Rewards.WalletBalance.2`
- Verified that the response value is displayed as expected when Brave wallet is not created
![image](https://user-images.githubusercontent.com/38657976/74734951-afa99800-5275-11ea-9942-ca791e0e9deb.png)
- Encountered https://github.com/brave/brave-browser/issues/7235
```

**Comment by srirambv** [comment]
Verification passed on 
#### `Brave.Rewards.WalletBalance.2` 
- Verified `Brave.Rewards.WalletBalance.2` is set to 0 on clean profile when rewards is not enabled
![image](https://user-images.githubusercontent.com/17010094/74729474-88010280-526a-11ea-9ec9-7f5311127bd2.png)
- `Brave.Rewards.WalletBalance.2` is set to `2` after enabling Rewards (#8296)
- Verified `Brave.Rewards.WalletBalance.2` is updated to `3` based on wallet balance
![image](https://user-images.githubusercontent.com/17010094/74730130-9bf93400-526b-11ea-9419-818786c210eb.png)
- Verified `Brave.Rewards.WalletBalance.2` is updated to `1` when rewards is turned off 
![image](https://user-images.githubusercontent.com/17010094/74730222-bcc18980-526b-11ea-8401-1e222c6829c8.png)

#### `Brave.Rewards.TipsState.2`
- Verified `Brave.Rewards.TipState` is set to `2` when wallet is created and no tip is sent to any pub
![image](https://user-images.githubusercontent.com/17010094/74746851-0fab3900-528c-11ea-9105-ee14c3bb4f97.png)
- Verified `Brave.Rewards.TipState` is set to `3` when a one time tip is sent
![image](https://user-images.githubusercontent.com/17010094/74730425-1a55d600-526c-11ea-80e2-f3217bb546b5.png)
- Verified `Brave.Rewards.TipState` is set to `4` when a recurring tip is set
![image](https://user-images.githubusercontent.com/17010094/74749629-73cffc00-5290-11ea-93b9-d17a1a4f2130.png)
- Verified `Brave.Rewards.TipState` is set to `5` when a one time tip and a recurring tip is set
![image](https://user-images.githubusercontent.com/17010094/74747524-17b7a880-528d-11ea-84c3-2eb4bd23e9e7.png)

#### `Brave.Rewards.AutoContributionsState`
- Verified `Brave.Rewards.AutoContributionsState` is set to `0` when rewards is not enabled
![image](https://user-images.githubusercontent.com/17010094/74755340-0d9ba700-5299-11ea-8a28-bbe05ee27af1.png)
- Verified `Brave.Rewards.AutoContributionsState` is set to `1` when Rewards is turned off
![image](https://user-images.githubusercontent.com/17010094/74755574-610df500-5299-11ea-9501-0a8acfdd2e1c.png)
- Verified `Brave.Rewards.AutoContributionsState` is set to `2` when AC is turned off
![image](https://user-images.githubusercontent.com/17010094/74755487-49cf0780-5299-11ea-858c-fbddde56963a.png)
- Verified `Brave.Rewards.AutoContributionsState` is set to `3` when there is no contribution done
![image](https://user-images.githubusercontent.com/17010094/74754043-05db0300-5297-11ea-91e4-cbe912f1e949.png)
- Verified `Brave.Rewards.AutoContributionsState` is set to `4` when there is one contribution done
![image](https://user-images.githubusercontent.com/17010094/74755947-e42f4b00-5299-11ea-86ea-dc0afd7e08aa.png)
- Verified `Brave.Rewards.AutoContributionsState` is set to `5` when there is multiple contribution done
![image](https://user-images.githubusercontent.com/17010094/74756244-42f4c480-529a-11ea-8a4c-7faf925dc705.png)

#### `Brave.Rewards.AdsState`
- Verified `Brave.Rewards.AdsState` is set to `0` when rewards is not enabled
![image](https://user-images.githubusercontent.com/17010094/74756358-6a4b9180-529a-11ea-9845-56ba73c16d47.png)
- Verified `Brave.Rewards.AdsState` is set to `3` when ads is turned on 
[image](https://user-images.githubusercontent.com/17010094/74756527-b4cd0e00-529a-11ea-97b9-2a20d2a34ee8.png)
- Verified `Brave.Rewards.AdsState` is set to `4` when ads is enabled and disabled but rewards is on
![image](https://user-images.githubusercontent.com/17010094/74756592-cc0bfb80-529a-11ea-9fbf-68801d0afd78.png)
- Verified `Brave.Rewards.AdsState` is set to `5` when ads is turned off and then rewards is turned off
![image](https://user-images.githubusercontent.com/17010094/74756627-db8b4480-529a-11ea-8d67-2d321cb1ff0d.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-browser/issues/7633#issuecomment-586205442

* For Upgrade profile, `Brave.Rewards.WalletBalance`, `Brave.Rewards.AutoContributionsState`, `Brave.Rewards.TipsState`, and `Brave.Rewards.AdsState` were replaced by `Brave.Rewards.WalletBalance.2`, `Brave.Rewards.AutoContributionsState.2`, `Brave.Rewards.TipsState.2`, and `Brave.Rewards.AdsState.2`. (There are some differences in response values as responses were updated a bit once v2 of the questions were added. See wiki for more info)

1.3.115:
<img width="344" alt="1 3 115 brave rewards items" src="https://user-images.githubusercontent.com/28145373/74782531-a0285000-5271-11ea-93d8-b58bc893619e.png">

1.3.116:
<img width="347" alt="1 3 116 updated" src="https://user-images.githubusercontent.com/28145373/74782536-a3234080-5271-11ea-97ce-3dabec51151d.png">


* For Clean profile, `Brave.Rewards.WalletBalance.2`, `Brave.Rewards.AutoContributionsState.2`, `Brave.Rewards.TipsState.2`, and Brave.Rewards.AdsState.2` were all set to 0.

<img width="303" alt="0 - clean profile, BR never enabled" src="https://user-images.githubusercontent.com/28145373/74782548-a9192180-5271-11ea-80a0-01d1a63b03d3.png">


Then I enabled Rewards, and toggled it back off. `Brave.Rewards.WalletBalance.2`, `Brave.Rewards.AutoContributionsState.2`, `Brave.Rewards.TipsState.2`, and Brave.Rewards.AdsState.2` were all set to 1.

<img width="307" alt="1 - BR enabled then disabled" src="https://user-images.githubusercontent.com/28145373/74782557-acaca880-5271-11ea-873e-f6d7e1cd8566.png">


* Encountered https://github.com/brave/brave-browser/issues/8296 when testing the Q12 `Brave.Rewards.WalletBalance.2` response values, was only able to correctly verify values of 0 and 1, the remaining values of 2, 3, 4 cannot be tested until the issue is resolved.

* For Q13 `Brave.Rewards.AutoContributionsState.2`, response values of 0 and 1 were verified above. 
Confirmed response value 2 for `Wallet created, Auto-Contribute off`
<img width="302" alt="brave rewards autocontributionsstate 2 value 2" src="https://user-images.githubusercontent.com/28145373/74782570-b59d7a00-5271-11ea-90c6-d83e94356248.png">

Confirmed response value 3 for `Auto-contribute enabled, no contribution so far`
<img width="293" alt="brave rewards autocontributionsstate 2 value 3" src="https://user-images.githubusercontent.com/28145373/74782583-b9c99780-5271-11ea-95df-3df7afe753d0.png">

Confirmed response value 4 for `Auto-contribute enabled, one successful contribution so far`
<img width="309" alt="brave rewards autocontributionsstate 2 value 4" src="https://user-images.githubusercontent.com/28145373/74782590-bd5d1e80-5271-11ea-8798-e454ddf58427.png">

Confirmed response value 5 for `Auto-contribute enabled, more than one successful contribution so far`
<img width="294" alt="brave rewards autocontributionsstate 2 value 5" src="https://user-images.githubusercontent.com/28145373/74782604-c0f0a580-5271-11ea-8e5c-a2be9a784994.png">


* For Q14 `Brave.Rewards.TipsState.2`, response values of 0 and 1 were verified above. 
Confirmed response value 2 for `Wallet created, no tips sent`
<img width="262" alt="brave rewards tipsstate 2 value 2" src="https://user-images.githubusercontent.com/28145373/74782615-c5b55980-5271-11ea-85ef-bc95e38c75f2.png">

Confirmed response value 3 for `Wallet created, one-time tip sent`
<img width="227" alt="brave rewards tipsstate 2 value 3" src="https://user-images.githubusercontent.com/28145373/74782624-c9e17700-5271-11ea-8873-5530c2268bc1.png">

Confirmed response value 4 for `Wallet created, at least one monthly tip queued up or sent`
<img width="248" alt="brave rewards tipsstate 2 value 4" src="https://user-images.githubusercontent.com/28145373/74782636-ccdc6780-5271-11ea-9c38-279940452d9b.png">

Confirmed response value 5 for `Wallet created, one-time sent and at least one monthly tip queued up or sent`
<img width="238" alt="brave rewards tipsstate 2 value 5" src="https://user-images.githubusercontent.com/28145373/74782641-d06fee80-5271-11ea-92bc-3ee3007c76d8.png">


* For Q17 `Brave.Rewards.AdsState.2`, response values of 0 and 1 were verified above. 
Confirmed response value 2 for `Wallet created, ads not enabled`
<img width="253" alt="brave rewards adsstate 2 value 2" src="https://user-images.githubusercontent.com/28145373/74782650-d5cd3900-5271-11ea-93e2-95e5cc6a342c.png">

Confirmed response value 3 for `Wallet created and ads enabled`
<img width="231" alt="brave rewards adsstate 2 value 3" src="https://user-images.githubusercontent.com/28145373/74782655-d8c82980-5271-11ea-9752-a22e31f208e8.png">

Confirmed response value 4 for `Wallet created, ads enabled, then disabled, while Brave Rewards remains on`
<img width="237" alt="brave rewards adsstate 2 value 4" src="https://user-images.githubusercontent.com/28145373/74782661-dbc31a00-5271-11ea-8bf7-2c64d53c5f37.png">

Confirmed response value 5 for `Wallet created, ads enabled, then disabled, Brave Rewards disabled`
<img width="228" alt="brave rewards adsstate 2 value 5" src="https://user-images.githubusercontent.com/28145373/74782668-df56a100-5271-11ea-9de1-5c562078a59b.png">

**Comment by LaurenWags** [comment]
Discussed with @iefremov and the part of the description which states 
```
These metrics should have "Brave Rewards is off" as the first answer, instead of "No wallet created".
```
is out of date. As of now, the wiki (https://github.com/brave/brave-browser/wiki/P3A) is up to date.
