### ISSUE TITLE
[Android] U2F NFC keys not working on Android  

### ISSUE THREAD

**Issue by mKoonrad** [brave/brave-browser#7756]
Description:
I can't use U2F NFC keys (like YubiKey NEO) with Brave on Android. There is missing any FIDO U2F code/library in the Brave Android browser.

Steps to Reproduce:
1. Open Brave Android browser
2. Log in to any service with U2F support as 2 factor authentication like Google, GitHub etc.
3. Try to tap to phone NFC U2F key

Actual result:
Nothing. Page/service is waiting to use U2F key.

Expected result:
Tap to phone NFC U2F key and log in to service.

Issue reproduces how often:
Every time

Issue happens on:
current Playstore version and official build

Device Details:
phone OnePlus 5T
ARM version
Android 9

Brave version:
Brave 1.0.77, Chromium 71.0.3578.99

Website problems only:  
Issue doesn't resolve itself with disabling Brave Shields 
Issue isn't reproducible on the latest version of Google Chrome browser. On Brave you probably delete/not attach any code to support FIDO U2F protocol.

Additional Information
On Windows, PC version of Brave I don't have this issue. I have this issue only with Android.

**Comment by theretohere** [comment]
Any update? Having the same issue. Will come back to Brave when its ready.

**Comment by bdimcheff** [comment]
Is there a workaround for this? I have other 2fa methods (authenticator, push) but it just spins on waiting for my yubikey and never gives me an alternative method. Is there some way to force auth to use a different 2fa method?

**Comment by actuallymentor** [comment]
> Is there a workaround for this? I have other 2fa methods ... Is there some way to force auth to use a different 2fa method?

Depends on the service. Usually there is a button with something like 'try another method'.

**Comment by kurtisnelson** [comment]
This is a major blocker for users of Google Advanced Protection as that mandates a hardware key.

**Comment by bdimcheff** [comment]
> Depends on the service 

Oh sorry yeah I mean specifically for google sign-in. It doesn't seem to fall back to other methods, it just tries forever. I still haven't been able to figure out how to sign into google from brave 🤷‍♂.

**Comment by FelschR** [comment]
This is a huge for me. I have dozens of 2FA logins setup with no alternative login method, because that would compromise security.
I sure hope no Brave users are setting up an alternative login method just to be able to use Brave.

**Comment by baldimir** [comment]
This is currently a blocker for me for using Brave as my default browser on my phone. Is this planned to be fixed? As others mentioned, it is not possible to log in to a Google account with e.g. a Yubikey. I personally don't want to change my Google account setup just because of a bug in my mobile browser.

**Comment by eliecharra** [comment]
As an "workaround" you could use vanilla chromium `84.0.xx`, when logging to a google account, it skip U2F check and allow you to select another 2FA method. You can download it there : https://chromium.woolyss.com/#android

![image](https://user-images.githubusercontent.com/6154987/80985055-fc415000-8e2e-11ea-82e6-794a78499458.png)

I know that's not brave but at least it's not google chrome either ...

**Comment by theretohere** [comment]
> As an "workaround" you could use vanilla chromium `84.0.xx`, when logging to a google account, it skip U2F check and allow you to select another 2FA method. You can download it there : https://chromium.woolyss.com/#android

This defeats the purpose. We WANT to use U2f.

**Comment by bsclifton** [comment]
cc: @jumde

**Comment by notspecified** [comment]
I've the same Issues!
Running Brave 1.9.80 /chromium 81.0.40.44.138) on android 10 (H8324 Built 52.1.A.2.1) and i can't login via NFC to accounts.google.com, either i can't skip the screen to use another 2FA.
But with firefox 68.9.0 on the same phone even the U2F with NFC works. 

So what is the problem that we can't use it with brave?

**Comment by MaximilianAst** [comment]
With the recent update I can at least switch to a different 2FA auth for the google login. Still no U2F working 

Brave 1.10.94, Chromium 83.0.4103.106

**Comment by din0s** [comment]
I can confirm this is still an issue. Can't use my YubiKey with Brave for Android, even though the current Chrome build has full support for it.

Could we possibly get an official update on whether this is somewhere in the devs' backlog?

**Comment by szaimen** [comment]
Is there any update here?

**Comment by rbairwell** [comment]
I'm having increasing difficulties logging on to "Google Login" powered services using Brave on my Android phone. This is because I'm enrolled in Google's "Advanced Protection Program" ( https://support.google.com/accounts/answer/7539956?hl=en-GB ) which requires usage of a security key (such as Yubico Keys) or a security device - such as the Titan M security chip which is prebuilt into Pixel 3 devices ( https://www.blog.google/products/pixel/titan-m-makes-pixel-3-our-most-secure-phone-yet/ ).

Once I've entered my email address and password, I'm taken to the "2-step Verification" page but get "2-Step Verification: There was a problem. Try using your security key again or try another way to verify that it's you". Clicking "Try again" just briefly reattempts trying to access the security device and "Try another way" provides me with "Use your security key" (again), "Get a one-time security-code" or "Get help - takes 3-5 days". Trying a one-time security code tells me to go to https://g.co/sc : doing this from Brave prompts me to login again, takes me to "Verify that it's you" and get the "We couldn't find your Security Key in time" prompt. I cannot therefore login without using Chrome on my phone (or desktop).

**Comment by fomod-in** [comment]
following the topic

**Comment by 4n0nym0u53** [comment]
Is there any update on this? I cannot use my YubiKey with NFC either (tried USB too), running latest version of Brave on a OnePlus 8T with latest OxygenOS. Chrome works though, but I don't want to use Chrome due to privacy concerns. I understand that Chrome makes use of Google Authenticator to achieve U2F authentication, and that this may not be appropriate for Brave, but maybe the team could look into other solutions? Perhaps the one suggested by @dschuermann:
> We could provide a FIDO implementation if the Brave team is interested: https://hwsecurity.dev/fido/

**Comment by bigcurefan** [comment]
U2F NFC failure here also for Yubikey 5C NFC and Samsung Note10+ (Android 10) using latest version of Brave (1.18.75)  Works with Chrome (87.0.4280.101).  Would appreciate knowing if a fix is anywhere in the pipeline.  Seems like this has been a known issue for a couple years.

**Comment by mkarebski** [comment]
Here on Huawei P Smart 2019 and Brave 1.20.x Security Key NFC fails. On Chrome it's working like a charm.

**Comment by sramek5** [comment]
Same issue here! 
I have Samsung Galaxy S9 - Android 10; Brave 1.20.108, Chromium 88.0.4324.182 and GoTrust Idem USB/NFC Key.
I cannot use the key on my phone (nothing happen) on different websites and accounts (nor via NFC or via USB).
Brave on Laptop has no problem at all.

In Google Chrome for mobile it works though. 

Would it be fixed? I would really appreciate that!

**Comment by ygoe** [comment]
WebAuthn doesn't seem to be there at all in Brave on Android. I just tried to register my device for login with Nextcloud. When I did that on my Windows PC with Firefox, Windows 10 asked me for my PIN and I was done. Easy. In Brave however nothing happens. Considering this feature is now at least a year old and the issue here is even older, is there any continuing interest in maintaining the Brave browser on Android? I just found it as a perfect Firefox replacement (at least on Android where Firefox really sucks). I'd need to restart my search for a usable Android web browser if this feature isn't available. :-(

**Comment by 4n0nym0u53** [comment]
@ygoe the issue isn't that Brave doesn't have FIDO functionality on Android. The issue is that any browser besides Chrome doesn't have FIDO functionality on Android. Chrome does this using Google Play Services and Google Authenticator as backend, which is a proprietary solution.

**Comment by ygoe** [comment]
Oh, okay, thanks for the explanation. Now I'm no longer interested in FIDO because it just isn't available where it's needed the most (on mobile devices). So I'll just stick with my password manager. Saves me a lot of work to figure out how to add FIDO to my web apps.

**Comment by franco** [comment]
@4n0nym0u53 do you know by any chance what the difference is compared to Brave on desktop? There they managed to support FIDO just fine. Do they leverage something provided by the underlaying platform or why is it easier to have it on desktop but not on mobile?

**Comment by 4n0nym0u53** [comment]
@franco it's because Android's system-wide FIDO implementation is made by Google and it's proprietary, thus only present in Chrome. It's kinda like Windows Hello, but on Android third party apps aren't allowed to use it. However, third party apps CAN have their own or others implementation, such as [COTECH's implementation](https://hwsecurity.dev/) which is for example used in the Nextcloud app. AFAIK there's no browser out there for Android other than Chrome with FIDO support, and I don't know if it's possible to have it in third party browser at all.

**Comment by dschuermann** [comment]
Dominik of COTECH here. We have a sample where our implementation is integrated in a browser: https://play.google.com/store/apps/details?id=de.cotech.hw.fido.browser
I don't recommend this browser as a daily driver, it's move a sample project.

**Comment by ygoe** [comment]
@dschuermann Does that implementation also support using the Android device itself as authenticator, without any external security hardware? Much like I can use Windows as authenticator, too, by entering my Windows Hello PIN or using the computer's fingerprint sensor.

**Comment by rbairwell** [comment]
> Dominik of COTECH here. We have a sample where our implementation is integrated in a browser: https://play.google.com/store/apps/details?id=de.cotech.hw.fido.browser
> I don't recommend this browser as a daily driver, it's more like a sample project.

It doesn't seem to work with the "Titan" chip in Google Pixel devices.

**Comment by dschuermann** [comment]
Nope, it currently works only with external NFC or USB hardware.

**Comment by christophediprima** [comment]
Hello there! What is the state of this issue? I would like to use Brave Android to authenticate on the Internet Computer, but it is not possible because 2FA authentication is required.

**Comment by tsallou** [comment]
There is currently no way in the FOSS community to use U2F in an android browser ( [Browser for FIDO2](https://play.google.com/store/apps/details?id=de.cotech.hw.fido.browser) is more a POC). I think the Brave team should really team up with @dschuermann and COTECHDE. They did a really great job for [implementing U2F in the android nextcloud app](https://github.com/nextcloud/android/pull/4286)!

**Comment by eecoston** [comment]
I'm having this issue as well

**Comment by DeltaLaboratory** [comment]
even in 2021, it is not workinf

**Comment by x390** [comment]
Firefox has U2F working through play service, not the best option but at least they didn't ignore the issue for years.

**Comment by KaloyanTanev** [comment]
A bit disappointing for a browser with such values, not fully supporting Yubikeys.

**Comment by KaloyanTanev** [comment]
@jumde I have some experience with setting up applications to work with YubiKeys, would gladly help with bringing this feature to life!

**Comment by k3nsei** [comment]
In Chrome it works but not in Brave :/

**Comment by b0rrA** [comment]
i have read 3 years on comments for this issue and not even a reply, sadness

**Comment by undg** [comment]
Is there any progress with that issue? It seems like the problem is ignored. 

Security is as important as privacy! I love to see support for u2f on the road map for brave for android. In the meantime, I'm forced to go back to chrome :'(

**Comment by marqsbla** [comment]
> In Chrome it works but not in Brave :/

the same on Xiaomi Poco F3. Working on Chrome, not working in Brave.

**Comment by worekarolis** [comment]
Is there any progress with that? I wont be able to use it as a default browser.

**Comment by brianddk** [comment]
Since we are now in the [U2F deprecation window](https://developer.chrome.com/blog/deps-rems-95/), it should be noted that efforts moving forward should be WebAuthn based (supports FIDO2 and FIDO keys) not U2F based (only supports FIDO keys).

**Comment by DeltaLaboratory** [comment]
It seems working through Google Play Service on 1.35.103  which downloaded from play store now.

**Comment by gurnec** [comment]
@DeltaLaboratory It works for me too!

I just tried logging into GitHub on Brave (same version as you) and it worked via both NFC and USB.

**Comment by Otard95** [comment]
Sure does! Great to see 🎉

**Comment by brianddk** [comment]
@DeltaLaboratory since there is no mention of it in the [release notes](https://github.com/brave/brave-browser/releases/tag/v1.35.103), perhaps it is something to do with this mention:

> Upgraded Chromium to 98.0.4758.102

**Comment by DKhalil** [comment]
Can confirm, works for me too! This is awesome.

**Comment by NoskaOff** [comment]
I confirm too! Works perfectly with Yubikey Security Key through NFC 🥳

**Comment by DeltaLaboratory** [comment]
> @DeltaLaboratory since there is no mention of it in the [release notes](https://github.com/brave/brave-browser/releases/tag/v1.35.103), perhaps it is something to do with this mention:
> 
> > Upgraded Chromium to 98.0.4758.102

There are [several commits](https://github.com/chromium/chromium/compare/98.0.4758.87...98.0.4758.102) at chromium about UAF, so it seems you might be true.

**Comment by marqsbla** [comment]
works for me too.

**Comment by KaloyanTanev** [comment]
I can confirm it also works for iOS, version 1.35.1. Hooray!

**Comment by Mansarde** [comment]
Turns out all we had to do was wait three years. 😆 *hide the pain harold*

**Comment by ygoe** [comment]
Do software authenticators also work now or is this just for hardware tokens?

**Comment by SergeyZhukovsky** [comment]
hey, folks, sorry for the long wait, so does it work ok for everybody and we can close that issue?

**Comment by bsclifton** [comment]
Closing as this was resolved in March 2022 - huge thanks to Andrew Whalley for getting us the access needed and thanks to @jumde for starting that conversation 😄
