### ISSUE TITLE
Notifications bridging

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#7759]
Currently we broadcast ads notifications to all devices(a particular problem with smart watches). On most devices there is nothing to do with the notifications. That's why we need to limit and show them only on a device itself. A solution described here should help https://developer.android.com/training/wearables/notifications/bridger.html

**Comment by gdregalo** [comment]
The solution provided in the description applicable only to Wear OS (former Android Wear) based watches.
On watches based on other OSes the notification bridging mechanism is implemented by companion application installed on the paired phone. 
It listens and transfers posted notifications to the paired watch. The application usually has settings which allows to block messages from a particular application installed on the phone to be sent to the watch.
The Wear OS based devices also have this settings app which allows to block the notifications. 
But if the notifications were not blocked explicitly, all of them appear on the watch automatically. 
Since there is nothing to do with them on the watch, we can block them by applying `setLocalOnly(true)` when building the notification.
