### ISSUE TITLE
add setting for "when opening a link in a new tab, switch to it immediately"

### ISSUE THREAD

**Issue by PierBover** [brave/brave-browser#7802]
I understand changing the default behavior to not focus on new tabs would be intrusive to current users, but it would be great to add a setting to change this behavior without having to rely on extensions.

**Comment by rebron** [comment]
@PierBover We need some more information. Not sure what you're asking.

**Comment by PierBover** [comment]
When clicking on a link that opens a new tab (or if clicking on a link with CMD in macOS) by default that new tab is not focused and opens in the background.

I'm asking for a setting that changes this behavior so that new tabs get focused.

I'm using an extension to solve this but it would be nicer if it was a setting in Brave.

**Comment by rebron** [comment]
@PierBover What extension are you using? 

And it's basically this setting in Firefox. 
<img width="459" alt="Screen Shot 2020-03-06 at 11 32 32 AM" src="https://user-images.githubusercontent.com/5951041/76116112-3eb8ee80-5f9e-11ea-8521-935f0955aeaa.png">

So on ctrl or command click on a link, the page opens in that new tab with focus instead of opening in the background. The same behavior with clicking on links from a pinned tab, the link will open in a new tab with focus.

**Comment by PierBover** [comment]
This is the extension: https://chrome.google.com/webstore/detail/switch-to-new-tab/lfpdoeknpnclenhlmblmenpafkbcgdbg?hl=en

> So on ctrl or command click on a link, the page opens in that new tab with focus instead of opening in the background. The same behavior with clicking on links from a pinned tab, the link will open in a new tab with focus.

Yes, that's the idea. Also when a link has `target="_blank"`.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/14733 which has some more information
