### ISSUE TITLE
Brave browser doesn't imports data from MetaMask and even corrupts it

### ISSUE THREAD

**Issue by DaniellMesquita** [brave/brave-browser#7860]
Data in MetaMask was reset and extension corrupted after the update adding CryptoWallets.
![brave corrupts metamask without importing its data](https://user-images.githubusercontent.com/6765277/72858455-b0173900-3c9f-11ea-8db6-0586f1017cf2.png)

**Comment by DaniellMesquita** [comment]
There was no responsibility when releasing this update.

**Comment by srirambv** [comment]
@DaniellMesquita I've requested in almost every issue you have opened to please use the template but you ignore it. It's impossible to debug if you just say data is corrupted. Please edit the issue and add the details that are part of the template so that we can figure out whats the issue. Will have to close the issue for lack of information (already mentioned in the template header)

**Comment by DaniellMesquita** [comment]
To reproduce:
1. I had a previous version with MetaMask
2. It was automatically updated to version 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
3. I'd noticed it came with its own fork of MetaMask (CryptoWallets) and the two were conflicting when web3 sites did requests. Then MetaMask got corrupted with its data.

**Comment by srirambv** [comment]
Will be fixed with https://github.com/brave/brave-browser/issues/7503

**Comment by DaniellMesquita** [comment]
> I've requested in almost every issue you have opened to please use the template but you ignore it

About ignoring, re-open this issue.

> Will be fixed with #7503

But isn't yet. Also, will this fix recover corrupted data from MetaMask? Nope.
A browser update corrupting data is a immature and irresponsible act from a development team. We should talk instead of attacks.
