### ISSUE TITLE
Branded Wallpaper Feature (desktop)

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#7883]
New Feature: implement branded wallpapers

## Test plan
On https://github.com/brave/brave-core/pull/4075

**Comment by kjozwiak** [comment]
Adding the `QA Pass` label as QA has been going through this since it landed. We've basically verified anything that was left opened. This was also initially checked on Nightly as per the following:

* `macOS` - https://github.com/brave/brave-core/pull/4075#issuecomment-579028986
* `Linux` - https://github.com/brave/brave-core/pull/4075#issuecomment-579222031
* `Windows` - https://github.com/brave/brave-core/pull/4075#issuecomment-579046248

**Comment by JTCozart** [comment]
This kinda goes against what brave is for... It is a shame that it was not announced and there is not an easy way to turn it off for the average user. 

Tips for everyone looking to turn this off: 

- Go to chrome://flags/ 
- Search for "Branded"
- Turn off the two feature flags there and relaunch brave. (chrome://flags/#brave-ntp-branded-wallpaper and chrome://flags/#brave-ntp-branded-wallpaper-demo). 

Ads on the new tab screen should not be a thing. Especially in a browser that allows selective ads / ad blocking.

**Comment by petemill** [comment]
Hi @JTCozart The feature was announced with this detailed post https://brave.com/introducing-sponsored-images-in-brave/

Sponsored Images is part of Brave Rewards - enabling you to get rewarded for viewing non-intrusive branded background images on the New Tab Page.

You can disable sponsored images much more easily via the "hide sponsored images" link that pops up the first time an image like this is viewed, or by using the New Tab Page settings panel.

![image](https://user-images.githubusercontent.com/741836/74173176-7d999580-4be6-11ea-8c5e-087be158f158.png)

![image](https://user-images.githubusercontent.com/741836/74173152-73779700-4be6-11ea-8906-d3ec70c38f35.png)
