### ISSUE TITLE
Round-robin Brave Ads campaign advertisers to reduce the frequency of showing the same ad

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7888]
We currently round-robin Brave Ads based upon creatives (using the catalogs `creativeInstanceId` node). 

To reduce the frequency of showing the same ad we should round-robin Brave Ads based upon both the advertiser (using the catalogs `advertiserId` node) and the creatives (based upon the `creativeInstanceId`).

Use cases:

- As a user, I do not want to see duplicate ads from a catalog creative until all eligible ads have been shown (already implemented, but here for clarity)
- As a user, I do not want to see duplicate advertisers from a catalog campaign until all eligible advertisers have been shown

**Comment by btlechowski** [comment]
**Test plan**

`General test case`:
1. Overwrite the catalog with Charles 
2. Run Brave with command line: `/usr/bin/brave-browser --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
3. Enable Rewards
4. Open `cars.com`
5. Trigger ad -> This is Ad1.
6. Wait an hour
7. Trigger ad -> This is Ad2.
8. Wait an hour
9. Trigger ad -> This is Ad3.
10. Wait an hour
11. Repeat 2x steps 5-10

Expected result
Duplicate Ad is not shown till all other ads are shown.

Example of expected behavior:
Ad1
Ad2
Ad3

Ad3
Ad2
Ad1

Ad2
Ad1
Ad3


Example of broken behavior:
Ad1
Ad2
Ad3

Ad1
Ad1  - same ad shown twice
Ad3

Ad2
Ad3
Ad2 - same ad shown twice

**Test case 1**: Ads in the same child category
1. Go through `General test case` using catalog: [advertisers - same child category.txt](https://github.com/brave/brave-browser/files/4452313/advertisers.-.same.child.category.txt)


**Test case 2**: Ads in the same parent category
1. Go through `General test case` using catalog: [advertisers - same parent category.txt](https://github.com/brave/brave-browser/files/4452314/advertisers.-.same.parent.category.txt)

**Test case 3**: Ads in different categories (child, parent, untargeted) - triggered every 1 hour
1. Go through `General test case` using catalog:  [advertisers - different categories.txt](https://github.com/brave/brave-browser/files/4452317/advertisers.-.different.categories.txt)


Expected behavior:
Only Ad with child category is shown
Ad1
Ad1
Ad1

**Test case 4**: Ads in different categories (child, parent, untargeted) - triggered every 20 minutes
1. Overwrite the catalog with Charles [advertisers - different categories.txt](https://github.com/brave/brave-browser/files/4452317/advertisers.-.different.categories.txt)
2. Run Brave with command line: `/usr/bin/brave-browser --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
3. Enable Rewards
4. Change Ads frequency to 5 per hour
5. Open `cars.com`
6. Trigger ad
7. Wait 20 minutes
8. Trigger ad
9. Wait 20 minutes
10. Trigger ad
11. Wait 20 minutes
12. Repeat 2x steps 6-11

Expected behavior:
The ads are not random, but are shown in order:
Ad AAA
Ad BBB
Ad CCC

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.86 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-browser/issues/7888#issuecomment-611135323


**Verified Test case 1**
Screenshot of 6 first ads
![image](https://user-images.githubusercontent.com/34715963/78817733-e1b4bc00-79d3-11ea-8bc2-b8159bb0c375.png)

Ad AAA
Ad CCC
Ad BBB

Ad AAA
Ad BBB
Ad CCC

Ad BBB
Ad AAA
Ad CCC

**Verified Test case 2**
Screenshot of 6 first ads
![image](https://user-images.githubusercontent.com/34715963/78819684-e4fd7700-79d6-11ea-8efc-981305a8766b.png)

Ad BBB
Ad CCC
Ad AAA

Ad CCC
Ad BBB
Ad AAA

Ad CCC
Ad AAA
Ad BBB

**Verified Test case 3**
Screenshot of 6 first ads
![image](https://user-images.githubusercontent.com/34715963/78820947-ec258480-79d8-11ea-8014-2bda01d059df.png)


**Failed Test case 4** 
![image](https://user-images.githubusercontent.com/34715963/78822419-50e1de80-79db-11ea-8d74-0511ead3758f.png)

Encountered https://github.com/brave/brave-browser/issues/8971

Hour 1
Add AAA
Add BBB
Add CCC

Hour 2 - fail, AD BBB not shown
Add AAA
Add CCC

Hour 3 - fail, AD BBB not shown
Add AAA
Add CCC
