### ISSUE TITLE
Please add a registry key to disable clearing browser history

### ISSUE THREAD

**Issue by Daemach** [brave/brave-browser#7954]
I need to disable the ability to clear browsing history using the registry or group policy so it can't be modified by the local user.  You've provided a way to disable private browsing.  Please do the same for browser history.  Internet explorer is the only browser that allows this, so I cannot allow firefox, brave or chrome on my network at the moment.  Keep honest people honest.

And if you can push this into the chromium build so that it works in chrome, edge, brave and any other chromium powered browser I'll make brave our default browser via domain group policy ;)

**Comment by Daemach** [comment]
It would also be good to ensure the user cannot lower the history storage to 0 days, or adjust it in any way for that matter.

Thanks in advance for your great work!

**Comment by Prowler2** [comment]
@Daemach 

Brave release 1.2 and older
`HKLM\SOFTWARE\Policies\Chromium`

Brave release 1.3 and newer
`HKLM\SOFTWARE\Policies\BraveSoftware\Brave`

Since Brave is based upon Chromium, find the chromium policy you need on this page and apply the associated registry key in the appropriate area (above) for your version of Brave.
https://cloud.google.com/docs/chrome-enterprise/policies/

The one you are interested in is `AllowDeletingBrowserHistory` set to `0`. 

If you have a version of Windows that has group policy capability, see my github page at the link below. Now that 1.3 has been released, I have been testing some ADMX templates to ease applying policy to Brave in an enterprise environment. It is still a work in progress.
https://github.com/Prowler2/Brave-Browser-GPO-Policy

**Comment by rebron** [comment]
@Prowler2 Thanks for the assist!
