### ISSUE TITLE
C80 followup: patches/build-config-chrome_build.gni.patch is no longer needed.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#7957]
Followup to brave/brave-core#4374

https://github.com/brave/brave-core/pull/4374#discussion_r371991679

this patch is no longer needed, we can now just set branding_path_component directly in config.js

**Comment by mariospr** [comment]
Just opened my first two PRs for brave-browser and brave-core as an attempt to fix this issue in here:
  * https://github.com/brave/brave-browser/pull/10758
  * https://github.com/brave/brave-core/pull/6091

I tried to follow the process outlined in https://github.com/brave/brave-browser/blob/master/CONTRIBUTING.md#pull-requests and I think I did everything except assigning the "Asignee" and the "Reviewers", which I think I can't due to permissions.

PTAL and let me know what you think, thanks!

**Comment by mariospr** [comment]
Updated the PRs based on review comments, and also moved them to branches in Brave's own repositories (vs my forks).

New PRs are here:
  * https://github.com/brave/brave-browser/pull/10858
  * https://github.com/brave/brave-core/pull/6172

@mkarolin Also, please consider renaming this issue since in the end we won't be dropping the patch entirely to prevent having to add an import in other patch files, thanks!
