### ISSUE TITLE
Implement Purchase Intent Classifier for Brave Ads

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#8047]
For requirements search "Purchase Intent MiniSpec" on shared drive.

**Comment by btlechowski** [comment]
**Test plan**

**Test case 1**: Check for `conversions` item in ads catalog
1. Connect to US
2. Open `https://ads-serve.bravesoftware.com/v2/catalog`
3. Search for `purchase intent`. 

Expected behavior:
Able to find a segment with `purchase intent`

**Test case 2**: record purchase intent from live catalog on staging
1. Connect to US
2. Run Brave with command line: `/usr/bin/brave-browser-dev --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
3. Enable Rewards
4. Search for `Audi a5` in the URL bar
5. Check `Default/ads_service/client.json` for `automotive purchase intent by make-audi`

Expected behavior:
`automotive purchase intent by make-audi` is not empty and contains one element
```
{
	"timestamp_in_seconds": ,
	"weight": 
}
```

**Test case 3**: show purchase intent ad
1. Overwrite the catalog with Charles
Catalog: [purchase_intent_1set.txt](https://github.com/brave/brave-browser/files/4412286/purchase_intent_1set.txt)
2. Run Brave with command line: `/usr/bin/brave-browser-dev --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
3. Enable Rewards
4. Search for `Audi a5` in the URL bar
5. Reload the page 9 times
6. Trigger an ad

Expected behavior:
Ad associated with `automotive purchase intent by make-audi` is shown (Audi ad)
`automotive purchase intent by make-audi` in `Default/ads_service/client.json` is not empty and contains 10 elements
Search logs for `Serving ad from categories` and check if `automotive purchase intent by make-audi` is listed

**Test Case 4**: keywords to funnel stage
1. Connect to US
2. Run Brave with command line: `/usr/bin/brave-browser-dev --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
3. Enable Rewards
4. Search for `audi a5 dealer opening times` in the URL bar

Note: you can use any `keywords to funnel stage` from the `Purchase Intent Taxonomy` spreadsheet

Expected behavior:
`automotive purchase intent by make-audi` in `Default/ads_service/client.json` is not empty and contains 1 element.
The element has weight of 3
`automotive purchase intent by category-entry luxury car` in `Default/ads_service/client.json` is not empty and contains 1 element.
The element has weight of 3

**Test Case 5**: site
1. Connect to US
2. Run Brave with command line: `/usr/bin/brave-browser-dev --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
3. Enable Rewards
4. Open `http://buyatoyota.com` in the URL bar

Note: you can use any `automotive - low funnel sites` from the `Purchase Intent Taxonomy` spreadsheet

Expected behavior:
`purchaseIntentSignalHistory` in `Default/ads_service/client.json` contains many elements (over 20).

**Test case 6**: Round robin
1. Overwrite the catalog with Charles
Catalog: [purchase_intent_2automotive.txt](https://github.com/brave/brave-browser/files/4412258/purchase_intent_2automotive.txt)
2. Run Brave with command line: `/usr/bin/brave-browser-dev --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
3. Enable Rewards
4. Search 4 times for `audi a4 in stock` (should give 12 weight in total)
5. Open `cars.com` (should trigger `automotive` category)
6. Trigger ad -> Remember which ad was shown. This is Ad1.
7. Trigger ad -> another ad is shown than 1st ad. This is Ad2.
8. Trigger ad -> Ad1 is shown
9. Trigger ad -> Ad2 is shown
10. Trigger ad -> Ad1 is shown
11. Trigger ad -> Ad2 is shown

Note: single ad can not be shown more frequently than once per hour.

Expected behavior:
Same ad is not shown twice in a raw.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-browser/issues/8047#issuecomment-606974784 and https://github.com/brave/brave-core/pull/4607#

**Test case 1**
Verified able to find a segment with `purchase intent`
```
"segments": [{
		"code": "RuHxHavV2",
		"name": "automotive purchase intent by category-mid luxury car",
		"parentCode": "5W5gsHA15"
	}, {
		"code": "mqiPIYccl",
		"name": "automotive purchase intent by make-audi",
		"parentCode": "rRWCQL4-i"
	}
]
```

**Test case 2**
Verified `automotive purchase intent by make-audi` is not empty and contains one element
```
"automotive purchase intent by make-audi": [{
		"timestamp_in_seconds": 1585701815,
		"weight": 1
	}
]
```
**Test case 3**
Verified Ad associated with `automotive purchase intent by make-audi` is shown (Audi ad)
![image](https://user-images.githubusercontent.com/34715963/77976080-397c6480-72fc-11ea-855a-8fa7c62d0021.png)
Verified `automotive purchase intent by make-audi` in `Default/ads_service/client.json` is not empty and contains 10 elements
Needed to reload 10 times (11 in weight). Logged https://github.com/brave/brave-browser/issues/8941
```
"automotive purchase intent by make-audi": [{
		"timestamp_in_seconds": 1585613989,
		"weight": 1
	}, {
		"timestamp_in_seconds": 1585614444,
		"weight": 1
	}, {
		"timestamp_in_seconds": 1585614708,
		"weight": 1
	}, {
		"timestamp_in_seconds": 1585615063,
		"weight": 1
	}, {
		"timestamp_in_seconds": 1585615477,
		"weight": 1
	}, {
		"timestamp_in_seconds": 1585615480,
		"weight": 1
	}, {
		"timestamp_in_seconds": 1585615486,
		"weight": 1
	}, {
		"timestamp_in_seconds": 1585615492,
		"weight": 1
	}, {
		"timestamp_in_seconds": 1585615498,
		"weight": 1
	}, {
		"timestamp_in_seconds": 1585615542,
		"weight": 1
	}, {
		"timestamp_in_seconds": 1585615805,
		"weight": 1
	}
]
```
Search logs for `Serving ad from categories` and check if `automotive purchase intent by make-audi` is listed
```
[16633:1:0331/030309.784666:INFO:ads_impl.cc(1177)] Serving ad from categories:
[16633:1:0331/030309.784772:INFO:ads_impl.cc(1179)]   automotive-car brands
[16633:1:0331/030309.784861:INFO:ads_impl.cc(1179)]   automotive-automotive
[16633:1:0331/030309.784929:INFO:ads_impl.cc(1179)]   automotive-motorcycles
[16633:1:0331/030309.784993:INFO:ads_impl.cc(1179)]   automotive purchase intent by make-audi
[16633:1:0331/030309.786854:INFO:client.cc(668)] Successfully saved client state
[16633:1:0331/030309.787981:INFO:ads_impl.cc(1285)] Found 1 eligible ads
[16633:1:0331/030309.788540:INFO:ads_impl.cc(1534)] Ad notification shown:
  uuid: f2980c48-a97d-4956-b3aa-ffafc4121077
  parentUuid: 7483c3d7-9247-496c-a0bb-17652acffce3
  creativeInstanceId: d9dc0028-8f86-4c92-b25d-981bc1bdb903
  creativeSetId: dea8df38-27b6-4b53-a699-77629934db80
  category: automotive purchase intent by make-audi
  title: Audi
  body: Check out the best models of the year 2020
  targetUrl: https://brave.com/purchase-intent-test
```

**Test case 4**
Verified `automotive purchase intent by make-audi` in `Default/ads_service/client.json` is not empty and contains 1 element.
Verified The element has weight of 3
Verified `automotive purchase intent by category-entry luxury car` in `Default/ads_service/client.json` is not empty and contains 1 element.
Verified The element has weight of 3
```
"automotive purchase intent by category-entry luxury car": [{
		"timestamp_in_seconds": 1585686239,
		"weight": 3
	}
],
"automotive purchase intent by make-audi": [{
		"timestamp_in_seconds": 1585686239,
		"weight": 3
	}
]
```

**Test case 5**
Verified `purchaseIntentSignalHistory` in `Default/ads_service/client.json` contains many elements (over 20).
[purchase_intent_list_for_site.txt](https://github.com/brave/brave-browser/files/4412332/purchase_intent_list_for_site.txt)

**Test case 6** Round robin
Verified same ad is not shown twice in a row.
