### ISSUE TITLE
Handle .onions in all contexts

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#806]
## Description

It seems generally unlikely that anyone entering a `.onion` address into the address bar means to browse to that site without Tor or to make DNS requests regarding it. When someone does so, we should probably treat it as an oversight. At the very least, we should not tell anyone else about it (no DNS lookups, for instance). But perhaps we should do more and provide a useful notification or even smoothly redirect them to a Private Window with Tor?

## Design
Show a "Open in Tor" button in the URL bar when user enters a .onion address or address with .onion available.

![image](https://user-images.githubusercontent.com/2388823/94495461-af2b9500-01a6-11eb-9c44-56295e4697e9.png)

### Dark Theme
Dark theme is supported:
![image](https://user-images.githubusercontent.com/2388823/94495404-86a39b00-01a6-11eb-9773-61201fc7d8b4.png)

## Assets
Figma: https://www.figma.com/file/5THkuEtO2Ewn9LfqrHZP9a/?node-id=0%3A1

**Comment by Mikaela** [comment]
The RFC on .onions agrees with you.

```
   2.  Application Software: Applications (including proxies) that
       implement the Tor protocol MUST recognize .onion names as special
       by either accessing them directly or using a proxy (e.g., SOCKS
       [RFC1928]) to do so.  Applications that do not implement the Tor
       protocol SHOULD generate an error upon the use of .onion and
       SHOULD NOT perform a DNS lookup.
```

From [RFC 7686 - The ".onion" Special-Use Domain Name](https://tools.ietf.org/html/rfc7686)

**Comment by srirambv** [comment]
+1  from #1460 for auto switch for .onion domains

**Comment by asddsaz** [comment]
Since .onion domains have very high levels of anonymity in the first place. You should be able to just send it to 127.0.0.1:9050 if TOR is running. For I2p/Tor many people utilize [Foxy Proxy ](https://getfoxyproxy.org/) to auto-utilize I2p/Tor for .i2p/.onion domains. Something similar could be done for Brave. This would be an awesome feature to have by default.

**Comment by librarymd** [comment]
Supporting .onion addresses in all contexts would be a game-changer for Brave as a browser. There is no browser doing that yet. To be honest, having a separate private Tor window is too much hassle. There is already TorBrowser as a separate window. 
Navigating privacy friendly .onion addresses should be as easy as navigating normal web, not harder.

**Comment by agentofuser** [comment]
I second @librarymd here and I'm excited that @tomlowenthal thinks this is a good idea!

Combined with #148 / #1121, this would be a huge on-ramp for mainstream users onto a more network privacy preserving Web.

It would also be a great incentive for publishers to have onion addresses, since it suddenly opens them to a much wider audience and makes the investment more worthwhile.

Is there a timeline for this landing?

---
P.S.: We can even dream that at some point the UX can follow the transition from HTTP to HTTPS where the encrypted version was at first a "bonus security enhancement" that had flashy positive signage, and later became the default, with _negative_ signage for when it's lacking (unencrypted HTTP).

So first a flashy green onion saying "this website is amazing" and later "you're trying to visit a non-onion website, which is terrible for privacy, are you sure?" But first things first.

**Comment by bsclifton** [comment]
+1 from @Merith-TK via https://github.com/brave/brave-browser/issues/7078
> ## Description
> So the idea kinda follows along the lines of this
> when you click on a tornet link,  (`.onion`), or enter a .onion address in your browser, have a small popup that asks if you want to actually go to this adress, and if the user clicks "Yes" open a tortab with that URL
>
> Or maybe set a default page or persistance book marks

**Comment by karenkliu** [comment]
Designs added!

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.17.65 Chromium: 87.0.4280.49 (Official Build) unknown (x86_64)
Revision	f77f85899646b42a1d3c8ff36794e00becab9171-refs/branch-heads/4280@{#1115}
OS	macOS Version 10.14.6 (Build 18G6032)
```

Verified test plan from https://github.com/brave/brave-core/pull/6762

Logged the following issues:
 - https://github.com/brave/brave-browser/issues/12610
Encountered the following issues:
 - https://github.com/brave/brave-browser/issues/4299 / https://github.com/brave/brave-browser/issues/11611

`onion-location` header:

<details>
<summary>Non Tor window</summary>

Checked for both Normal, Private, Guest windows:

<img width="1227" alt="Tor SS 1" src="https://user-images.githubusercontent.com/28145373/98724033-21c09080-2361-11eb-8155-bc47c48bdcb6.png">
<img width="1225" alt="Tor SS 3" src="https://user-images.githubusercontent.com/28145373/98724039-2422ea80-2361-11eb-9667-9f47c15ae6e6.png">
<img width="1224" alt="Tor SS4" src="https://user-images.githubusercontent.com/28145373/98724043-25541780-2361-11eb-9690-049b4a3683be.png">

</details>

<details>
<summary>Tor window</summary>

Checked for both Tor window:

<img width="1223" alt="Tor SS 2" src="https://user-images.githubusercontent.com/28145373/98724058-284f0800-2361-11eb-831e-474fe6ff2993.png">

</details>

<details>
<summary>Tor disabled</summary>

Checked for both Normal, Private, Guest windows:

<img width="1224" alt="Tor SS 5" src="https://user-images.githubusercontent.com/28145373/98724074-2d13bc00-2361-11eb-851b-ba2acab5a1e6.png">
<img width="1225" alt="Tor SS 6" src="https://user-images.githubusercontent.com/28145373/98724078-2e44e900-2361-11eb-8251-ab73c8282017.png">
<img width="1226" alt="Tor SS 7" src="https://user-images.githubusercontent.com/28145373/98724081-2edd7f80-2361-11eb-9c54-900c42052a97.png">

</details>

**Comment by Madis0** [comment]
> address with .onion available

Why is this icon needed when the user is _not_ in a Tor window and _not_ typing `.onion`, just browsing a site that has one?
