### ISSUE TITLE
How to enable auto-updates? (not working on macOS + Brave Browser Dev)

### ISSUE THREAD

**Issue by felixakiragreen** [brave/brave-browser#8098]
I have searched for issues and google results for weeks. Posting this issue here on Github is my last resort. 

## Description 
I'm on Brave Browser Dev. Every few days I get this pop-up to update the browser. I've tried to find out how to turn it off (turn on auto-updates) and I can't find out how. Do I need to download the normal Brave Browser?

(I've been using Brave Browser Dev for ~9 months, but it noticed it happening after I migrated computers with a clean install)

## Steps to Reproduce & Results

   1. 
<img width="620" alt="Screen Shot 2020-01-10 at 09 18 39" src="https://user-images.githubusercontent.com/1843672/73952056-8af40e80-48cc-11ea-8ce6-e2a9418fb7d0.png">

   2. 
![Screen Shot 2020-01-13 at 10 12 06](https://user-images.githubusercontent.com/1843672/73952062-8e879580-48cc-11ea-9719-7c1b9d23cd5d.png)

   3. 
<img width="620" alt="Screen Shot 2020-02-06 at 10 32 54" src="https://user-images.githubusercontent.com/1843672/73952071-934c4980-48cc-11ea-9db4-652d251b29b2.png">

## Expected result:
It used to appear in the hamburger icon in the top right that there was an update, and it was usually already downloaded. How to do I fix this?

**Comment by bsclifton** [comment]
@felixakiragreen sorry for the crazy long response time here ☹️ 

If you're still using Brave and still experiencing above, please try uninstalling Brave and re-installing. If you're on dev, you can download new dev version here:
https://brave.com/download-dev

Although- you may try moving to Beta as dev is bring deprecated. 
https://brave.com/download-beta

Using Beta will require you to move your profile directory from `~/Library/Application Settings/BraveSoftware/Brave-Browser-Dev` to `~/Library/Application Settings/BraveSoftware/Brave-Browser-Beta`

If a reinstall doesn't solve the problem, then it's likely due to not being an admin. If your user account is an admin on the machine, you can check permissions using:
`ls -alh /Applications` and then `chown` as needed

Please let me know 😄 Thanks!

**Comment by felixakiragreen** [comment]
Reinstalling directly from website fixed it. I figured out replication - it resulted from installing Brave using brew cask. Thanks.
