### ISSUE TITLE
Support for custom filter lists in Shields

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#8107]
## Description
Some popular adblocking extensions help users create filter lists to supplement the default ones. This can for example allow someone to hide parts of a website that are not deemed useful or desirable but that would otherwise be out of scope for EasyList/EasyPrivacy.

This is an advanced use case for sure, and we should focus on shipping the best default-on adblocker, but I thought I'd mention it since it might allow some users to avoid installing an additional extension and have everything they need built-in.

## Designs
Add functionality to subscribe to filter lists via URL on `brave://adblock`

![image](https://user-images.githubusercontent.com/2388823/91350060-051daf00-e79b-11ea-92f5-9c230cc502fa.png)

Insert the following designs below “Additional Filters” and above “Custom Filters”:

![image](https://user-images.githubusercontent.com/2388823/117079060-e68b9280-acef-11eb-8826-64d3b59fc150.png)

After the user clicks on "Add filter list via URL", a form field appears with "Submit" and "Cancel":

![image](https://user-images.githubusercontent.com/2388823/117079076-ed1a0a00-acef-11eb-9cfd-c9fb2491c4d1.png)

Built-in error validation for the field specifies entry must start with `https://`

![image](https://user-images.githubusercontent.com/2388823/117079084-f1debe00-acef-11eb-8848-94660e807ceb.png)

Submitting the filter list URL will add the filter list to a table with a toggle to enable/disable and available actions:
- Update now
- View website
- View source
- Unsubscribe

![image](https://user-images.githubusercontent.com/2388823/117079099-f6a37200-acef-11eb-8469-fadbfd1b6eca.png)

If the user enters a filter list that is invalid or unavailable, the table entry shows the filter as `Download failure` with no toggle available:

![image](https://user-images.githubusercontent.com/2388823/117079103-fa36f900-acef-11eb-960a-d4d1092082fe.png)

## Assets
Figma: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=49%3A2359

**Comment by rebron** [comment]
cc: @pes10k @ryanbr Is this a dupe?

**Comment by pes10k** [comment]
No, this is different.  Currently Brave users can add additional rules in the text box on brave://adblock (soon to be brave://shields/filter-rules I think).  Whats being asked for here, I believe, is the ability to subscribe to new lists, by URL.

**Comment by ryanbr** [comment]
Another way could be added, via ahref `abp:subscribe?` to streamline custom filter additions (supported by ABP and uBO)

Used on https://www.filterlists.com/  and on my own site https://secure.fanboy.co.nz/
**Sample:**
`abp:subscribe?location=https://secure.fanboy.co.nz/fanboy-problematic-sites.txt&title=Fanboy Problematic Sites`

If this is out of the scope of this, I can create separate report.

**Comment by pes10k** [comment]
I think that would be better to open as an issue in brave-core, and note in it that it would need to come after this issue is closed

**Comment by karenkliu** [comment]
Designs added!

**Comment by intrnl** [comment]
I think the next thing would be the ability to disable/enable some of the default filter lists as well :+1:

**Comment by antonok-edm** [comment]
@intrnl if you don't mind sharing, it'd be great to hear your use-case (although, probably in a separate issue).

If there's something in our default lists causing breakage then we'd like to get the lists fixed upstream as much as possible.

**Comment by Furax-31** [comment]
This feature is still not available?

**Comment by PaperCutBad** [comment]
It would be great feature if we could add our other filter list on Brave Android just like Vivaldi allow tp its users.

**Comment by antonok-edm** [comment]
Custom filter list subscriptions has just been merged into 1.31.x Nightly! There are some followup improvements to be made, primarily reading and respecting the list metadata (name, non-default update intervals, etc.) and supporting `abp:subscribe` links, but otherwise it's ready for real-world use.

**Comment by stephendonner** [comment]
**Verified `PASSED`** using 


Brave | 1.31.25 Chromium: 93.0.4577.63 (Official Build) nightly (x86_64)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | macOS Version 11.5.2 (Build 20G95)

### Steps:
1. Visited `brave://adblock`
2. Verified that a "Subscribe to filter lists" section exists between the "Additonal Filters" and "Custom Filters" sections, including an "Add  filter list via URL" button.
3. Clicked on the button to create a new subscription. A textbox appeared, along with a disabled "Submit" button and a "Cancel" button.
4. Confirmed the "Submit" button remains disabled as long as the text box does not include a valid URL. Pressing enter from the textbox also has no effect whenever the button is disabled.
5. Entered `http://failed.url` and confirmed it has `Update Now` and `Unsubscribe` buttons.  Pressing `Update Now` yields a `Download failure` error message, with a timestamp on hover.
6. Entered `https://austinhuang.me/0131-block-list/list.txt` and confirmed it has `Update now`, `View source`, and `Unsubscribe` buttons.  Pressing `Update Now` updated teh list with a new timestamp.  `View source` opens the filter-list source code in a new tab.  And pressing `Unsubscribe` removes the filter URL from the list.
7. Confirmed the information in the table remained consistent across different `brave://adblock` tab instances, and also across browser restarts.
8. Confirmed I'm unable to add duplicate filter-list URL entries (the `Submit` button is disabled).
9. visited `https://example.com` after subscribing to https://antonok.com/tmp/list.txt, and confirmed `https://example.com` is mostly red now, changed by the filter list.
10. I was **not** able to reproduce the `Download failure since...` behavior.
11. Any subscriptions that have *not* been toggled OFF should be  subject to automatic updates. A list whose last update attempt was  successful, whether manual or automatic, should be automatically updated once it is at least 7 days old[4]. A list whose last update attempt was *not* successful should be automatically retried hourly until  success. Update checks for all lists always occur ~1 minute after  launching the browser and subsequently every hour.



`604800000000` microseconds, so subtracting `604800000000` from both numbers will make the browser think the last download for that subscription occurred 1 week before it actually did

**Comment by stephendonner** [comment]
@antonok-edm I verified this issue because the rest worked, but I was unable to get two things working at the time:
1) unable to produce the `Download failure since...` condition
2) unable to see auto-refresh of the timestamp, on relaunch/clock changes

Can you take a look and clarify if I've done something -- or haven't -- to make those two not reproducible?  Thanks!

**Comment by antonok-edm** [comment]
1. I tried this locally and discovered that the download remains pending if the network is not available at all. I think that's _fine_, but sadly it makes it more difficult to test this behavior! I think we need to actually simulate a server that becomes unavailable for a second download attempt. You could try setting up a local server with a filter list (URLs on e.g. `http://localhost:8000` should work fine here), or potentially muck around with `/etc/hosts` to trick the browser into thinking some valid domain actually resolves to 127.0.0.1. Or, worst case we can coordinate testing on my own server, I'll just remove the file for the second download attempt.
2. The brave://adblock UI should show `About 7 days ago` immediately at launch if the timestamps were updated correctly in `Local State`. If not, there's a few things that might have gone wrong:
- I assume you edited the correct `Local State` file, given that you found the list subscriptions in the first place.
- Did you close the browser before editing `Local State`? I believe it may get rewritten before the browser is closed, otherwise.

  Even then, it may take more than a minute to update, depending on how loaded the computer is, whether or not you're on a metered network, battery status - but from what I can see in your screenshots I think it shouldn't be more than 5 minutes.

**Comment by antonok-edm** [comment]
@stephendonner correct, the last successful download should be cached and used even if more recent downloads are unsuccessful (you should still be able to see that source using the `View source` button in the triple dot menu). That appears to be working correctly from your screenshot :tada:

**Comment by tortino** [comment]
does custom lists automatically update?

**Comment by bridiver** [comment]
@tortino the default is weekly unless you manually update

**Comment by tortino** [comment]
thank you for the info. 
I know some lists are updated daily, so it seems to me that a week is a little to long.
maybe this settings could be user configurable?

**Comment by stephendonner** [comment]
> thank you for the info.
> I know some lists are updated daily, so it seems to me that a week is a little to long.
> maybe this settings could be user configurable?

Yes; that would be the "non-default update intervals" mentioned in https://github.com/brave/brave-browser/issues/8107#issuecomment-910450429

**Comment by ryanbr** [comment]
Ideally adhering to `Expires` / `Expiring` rather than non-default intervals. Server/BW load is real. Weekly is fine as a stopgap

**Comment by GeetaSarvadnya** [comment]
@antonok-edm When I add/update any valid URL to filter list, I get some `Timestamp` displayed in the `Last updated` column. Any idea what timestamp should be displayed in the Last updated column? It's not showing up system time (IST), not UTC also.
![image](https://user-images.githubusercontent.com/38657976/135493490-bf8bc666-5c14-4dea-968b-e6dba0dba664.png)

**Comment by antonok-edm** [comment]
@GeetaSarvadnya to be honest, I'm not sure what timezone that's supposed to be - I would have assumed UTC? At any rate, it's the default serialization for the `base::Time` structure in Chromium, and I wouldn't worry too much about that being incorrect. Should be fine as long as it's consistent relative to other downloads and across browser restarts.
