### ISSUE TITLE
brave://settings/braveSync not opening

### ISSUE THREAD

**Issue by matiastucci** [brave/brave-browser#8254]
## Description 

Can't access the sync options in the settings

## Steps to Reproduce

   1. Go to "Settings"
   2. Click "Sync" in the left menu

## Actual result:

I'm seeing the URL change to `brave://settings/braveSync`. But no changes in the view:

![2020-02-14 18-21-17 2020-02-14 18_28_30](https://user-images.githubusercontent.com/3856355/74544212-d1dea580-4f57-11ea-98d3-d2bf6439fd4c.gif)

## Expected result:

Should see the Sync setup

## Reproduces how often: 

 At least in my case, I can always reproduce it

## Brave version (brave://version info)

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.15.3 (Build 19D76)
JavaScript | V8 8.0.426.16
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --disable-sync --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,WebXR,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/mati/Library/Application Support/BraveSoftware/Brave-Browser/Default

**Comment by skellam** [comment]
Version 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
Sync is greyed out in setting menu for me on Linux Mint installation of Brave.  Also not able to access sync from menu on my Mac OS installation.

**Comment by kjozwiak** [comment]
@matiastucci sync was temporarily disabled due to a few crashes and stability issues that we ran into when we released `1.3.113 CR: 80.0.3987.87`.  When we pushed `1.3.115 CR: 80.0.3987.87` and disabled sync, there was a few UI elements that weren't removed.

We're going to be releasing another version next week that will add a user flag so users will have the ability to turn on sync if they weren't experiencing crashes and will be cleaning up the UI when sync is disabled (which is the default right now). Following issue will address the bug that you mentioned:

* sync still shows as an option in settings #8159

You can find some more information regarding sync being disabled via the following community post:

* https://community.brave.com/t/brave-sync-temporarily-disabled-on-desktop/106837.

Going to close this off as a duplicate 👍 Expect to see a fix sometime Wednesday.
