### ISSUE TITLE
Enable Do Not Track (DNT) by default?

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#826]
Carried over from https://github.com/brave/browser-laptop/issues/7119
(original issue has a good discussion)

**Comment by tomlowenthal** [comment]
Current plan of record:

Brave is a privacy-focused browser designed to prevent online tracking. Turning it on by default is an accurate reflection of the user's intent when they installed Brave. But turning it on by default would only let us hide in the (smaller) fraction of Chrome users who have turned it on rather than the (larger) fraction who haven't. That's probably a worse privacy outcome.

So: we'll leave it as a user-configured switch in settings until we stop hiding among Chrome users by enabling the Brave UA on a platform-by-platform basis. The setting notes that DNT requests are rarely followed by sites and that there's some additional distinctiveness from having the setting on.

**Comment by scottgearyau** [comment]
Why is this still not an option in mobile version?

**Comment by scottgearyau** [comment]
FYI: Chrome (Android) enables this by default. Brave doesn't even implement it.

**Comment by tomlowenthal** [comment]
The benefits are very limited — most sites ignore the DNT signal completely. On the other hand, making Brave more distinctive causes direct harm as people are tracked across the web.

**Comment by Peacock365** [comment]
@tomlowenthal is right. Like, 99% of all websites ignore this setting anyway. But if you enable the "Do not track" header, it might raise entropy, making you (somewhat ironically) more easily trackable. This issue can be closed, if you ask me.

**Comment by bsclifton** [comment]
Since great points have been made and no movement has been made, I'll close this for now as a `wontfix`
