### ISSUE TITLE
Upgrade to Chromium 81.0.4044.62

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#8308]
## Description 
Upgrade from Chromium 80.0.x.x to Chromium 81.0.4044.62

## QA tests:

**This is a major Chromium version bump, please do full passes.**

Affected areas:
1. Themes (specifically, correct themes for private/tor/guest, theme switching, multiple profiles).
2. Top site suggestions.
3. Profile menu/avatar.
4. History UI.
5. Google messaging (setting is preserved on upgrade, en/disabling functions).
6. Ads notifications on Mac OS 10.15.[1-2] and 10.15.3+.
7. Settings UI: privacy page.
8. Shields Settings migration:
  - check that shields settings are migrated on upgrade (all settings should remain, except no settings should retain protocol or port, e.g. if there was a setting blocking cookies on http://brave.com:8080 it should become just brave.com).
  - check that shields work properly (after upgrade or non-upgrade scenarios).

**Comment by LaurenWags** [comment]
Removing `QA/Yes` and `release-notes/include` labels as this issue is superseded by https://github.com/brave/brave-browser/issues/9000.

Added extra note to test plan in https://github.com/brave/brave-browser/issues/9000 for QA to pay special attention to items noted in https://github.com/brave/brave-browser/issues/8308#issue-567112654 for this chromium upgrade.
