### ISSUE TITLE
No "Brave sync" option on Ubuntu

### ISSUE THREAD

**Issue by hanibhat** [brave/brave-browser#8328]
## Description 
I just installed Brave browser on my Android and my Ubuntu 18. I am able to find "Sync" option under "Settings on my Android. However, I am not able to find any option for syncing on my Ubuntu client. I tried [this tutorial](https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync-).

## Steps to Reproduce
I followed the steps on the Brave download page (Release 14.04+) to download and install Brave on Ubuntu:
https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

## Brave version (brave://version info)
1.3.118

**Comment by GuardedAirplane** [comment]
Same issue here on Pop_OS

**Comment by lukaszklis** [comment]
Same issue on macOS 10.15.2.

**Comment by lukaszklis** [comment]
@hanibhat I’ve tracked down on what’s the problem there. The Brave team has recently disabled Brave Sync by default due to quite a lot of crash reports ([more info](https://community.brave.com/t/brave-sync-temporarily-disabled-on-desktop/106837)). Based on the release notes of the latest version (V3.1.118), there is a flag which allows you to re-enable Brave Sync on your desktop browser - #8187. 

Going to `brave://flags` to enable the option ”Brave Sync” followed by restarting the browser should help.

**Comment by hanibhat** [comment]
@lukaszklis your solution works perfectly for me. 
Closing this issue.

**Comment by berkiyo** [comment]
Thanks for the solution @lukaszklis, but I feel this should be in the settings with a toggle switch, it wasn't that obvious but maybe with Sync v2, this will change.
