### ISSUE TITLE
Brave Ad notifications do not persist round-robin state after a browser restart introduced with #8294

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8345]
## Description 

Ad notifications do not round-robin introduced with #8294

## Steps to Reproduce

   1. View an ad

## Actual result:

Duplicate eligible ads can be shown

## Expected result:
Duplicate ads should not be shown until all other eligible ads have been shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.7.4 and above

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by btlechowski** [comment]
**Test Plan**

Important: all ads are from `Technology & Computing` category

`General test case`:
1. Overwrite the catalog with Charles 
2. Run Brave with command line: `/usr/bin/brave-browser --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
3. Enable Rewards
6. Trigger ad -> Remember which ad was shown. This is Ad1.
7. Wait an hour then restart Browser
8. Trigger ad -> another ad is shown than 1st ad. This is Ad2.
9. Wait an hour then restart Browser
10. Repeat 3x steps 6-9

Expected result
Duplicate Ad is not shown till all other ads are shown.

Example of expected behavior:
Ad1
Ad2

Ad2
Ad1

Ad2
Ad1

Ad1
Ad2

Example of broken behavior:
Ad1
Ad2

Ad1
Ad1  - same ad shown twice, Ad2 should be shown


**Test case 1**: Ads in the same creative set
1. Go through `General test case` using catalog: [same set.txt](https://github.com/brave/brave-browser/files/4447554/same.set.txt)

**Test case 2:** Ads in the different creative sets
1. Go through `General test case` using catalog: [different set.txt](https://github.com/brave/brave-browser/files/4447724/different.set.txt)

**Test case 3**: Ads in the different advertisers
1. Go through `General test case` using catalog: [different advertisers.txt](https://github.com/brave/brave-browser/files/4447725/different.advertisers.txt)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.86 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-browser/issues/8345#issuecomment-610702535

Test case 1: Ads in the same creative set
Screen shot of first 4 ads
![image](https://user-images.githubusercontent.com/34715963/78732952-57714700-7944-11ea-9332-6d5ef0970e12.png)

Ad BBB
Ad AAA

Ad AAA
Ad BBB

Ad AAA
Ad BBB

Ad AAA
Ad BBB

Test case 2: Ads in the different creative sets

Ad BBB
Ad AAA

Ad BBB
Ad AAA

Ad AAA
Ad BBB

Ad BBB
Ad AAA

Test case 3: Ads in the different advertisers
Screen shot of first 4 ads
![image](https://user-images.githubusercontent.com/34715963/78734747-58f13e00-7949-11ea-84fd-b434644182a1.png)

Ad BBB
Ad AAA

Ad BBB
Ad AAA

Ad AAA
Ad BBB

Ad BBB
Ad AAA
