### ISSUE TITLE
Consider integrating with Google sync (bookmark / extension settings)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#839]
Carried over from https://github.com/brave/browser-laptop/issues/8279

For users that want to opt-in specifically to Google's sync, should we allow / support this? A given user could potentially share the same sync profile between Chrome and Brave

**Comment by netroby** [comment]
+1 if provided us sync with google(You may turn it off default. user can choose to setup it by hand)

**Comment by netroby** [comment]
With Google sync, I will full replace chrome , set brave as my primary browser.

**Comment by tomlowenthal** [comment]
I don't think that we should aim to support Google sync. There are many reasons why I think that this would be a headache, and here are a few of them.

It's a proprietary service which isn't guaranteed to have a stable API. As we make changes and tinker, we'll probably end up with state that isn't compatible with Chrome's and perhaps even being incompatible with Chrome's state. We'd only want to support the bring-your-own-passphrase/key option, which further limits our compatibility, and would require a bunch of edge-case handling for Google users who don't use that sync setting. This would also create a complex case when someone has multiple Chrome browsers and multiple Brave browsers trying to sync using both the Chrome and Brave sync processes.

This is a recipe for a confusing experience, and probably a fragile one.

**Comment by tomlowenthal** [comment]
I should add: Brave has implement an always-end-to-end-encrypted zero-knowledge no-account-needed sync service which will be available in Brave 1.0. You'll be able to sync all the browser info you want between Brave on all your devices. The tracker issue for that task is #29 .

**Comment by JhonnyJason** [comment]
Hello, isn't the google sync implemented in the chromium and brave is based on chromium?
Wouldn't that make it quite easy to use that functionality?
That way it also is possible to pull in the updates in API which essentially require Chromium to update anyways.

I also don't advocate for complex solution when it is really complex and full of edge cases.

But isn't there a possibility to have a simple multi account solution? Like separate instances, plus the possibility of one-time inter-account sync. Or similar do able cases, to not have to manually sync every password?

I'm also at the point where I would use brave over chromium then. 

I really love that it is based on chromium. Hope it will be completely compatible for all it's lifetime so that it might ultimativly merge to one again.
