### ISSUE TITLE
uBO mode

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#8478]
Some users have asked for a uBO mode, Brave applies all the same protections as uBO, and can enable them with a single button / toggle.

Right now Brave has all the same capabilities as uBO, with the following excpetions:

- [ ] top level URL blocking (https://github.com/brave/brave-browser/issues/8559, in pod queue)
- [x] unconstrained / 1p cosmetic filtering (https://github.com/brave/brave-browser/issues/8475)
- [x] procedural cosmetic blocking (e.g. block things on the page, that can't be described with CSS selectors)

**Comment by Yuki2718** [comment]
Hi, I had a question to your comment as it seemed contracting to the filter compatibility wiki so I tested some of the most important function not mentioned here on Brave Nightly 1.8.11 running on Win10 64 bit.

1. [CSS style injection](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#style) is not supported, or at least its syntax is different from uBO's one. Not only it is necessary to get scroll functioning after hiding some sort of modal overlay, it can also be used to address some of anti-adblock [example](https://github.com/AdguardTeam/AdguardFilters/issues/49015).

2. Obviously not all scriptlets of uBO is supported, or at least don't work in the same way as uBO. For example, nostif doesn't work at all. It's expected as I see no such strings in [here](https://github.com/brave/adblock-rust/blob/master/src/resources/scriptlet_resource_storage.rs) or [here](https://github.com/brave/adblock-rust/tree/master/data/test/fake-uBO-files/web_accessible_resources). Moreover, even supposedly-supported aopr doesn't work e.g. gigaho.com##+js(aopr, onload) doesn't work on the site.

3. It seems $inline-script modifier doesn't work. No wonder given $csp is not supported according to the wiki, but not mentioned in the wiki.

4. As stated in the wiki, $ping is not supported.

5. As stated in the wiki, $popup is not supported.

6. As stated in the wiki, $generichide is not supported. I think this should be prioritized as well as the above scriptlets issue because the introduction of cosmetic filtering, even only for third-party, without support of those will cause a jump of rates that users come across anti-adblock messages.

It's not meant to be an exhaustive list, but there seems to be really many things to be done.

Finding: nice to see regex filter is now supported, please update the wiki.

It's personal opinion, but I think what should be done ASAP over all the above is to allow user to freely choose subscription filter from anywhere - uBO has been doing this from the beginning.

**Comment by pes10k** [comment]
@Yuki2718 thank you for the comments and findings.  We also want to get all these things done, but it's a matter of competing priorities.  Some of these things are useful, but (in my best guess) just less useful than the other privacy-preserving things we're working on.

That being said, again, thank you for this.  I'm going to share it internally and see where things stand.

**Comment by pes10k** [comment]
One note, as @ryanbr reminded me, the `$ping` attribute isn't supported because Brave doesn't include ping-functionality (https://github.com/brave/brave-browser/issues/7640)

**Comment by Yuki2718** [comment]
@pes10k Thank you for clarification and positive answer, I understand you have a priority for various features. My comment was meant to be potential FYI.

**Comment by antonok-edm** [comment]
@Yuki2718 Style injection should already be supported in exactly the same capacity as uBlock Origin.

![2020-03-18-120621_936x513_scrot](https://user-images.githubusercontent.com/22821309/76981720-5c2c7780-6911-11ea-9f1b-edadf63125bc.png)

Did you find a particular example of a rule whose syntax isn't supported?

**Comment by Yuki2718** [comment]
> 
> Did you find a particular example of a rule whose syntax isn't supported?

Applying
`google.*##.mn-dwn-arw:style(top: 27px !important;)`
to Google search results in move of arrow icons as
![google1](https://user-images.githubusercontent.com/58900598/77020835-68bfd700-69c8-11ea-9c3d-7ad381bae542.png)
on uBO - for this screenshot I disabled uBO's other filters but keeping them enabled didn't change the results, only changed other appearance such that URL was shown in grey the same as the last screenshot below.

But the same rule on Brave Nightly 1.8.22
![brave](https://user-images.githubusercontent.com/58900598/77020966-bd635200-69c8-11ea-9a8d-330c51c877e4.png)
didn't
![google2](https://user-images.githubusercontent.com/58900598/77020980-ca804100-69c8-11ea-8963-887bd15dbc23.png)
and changing the wildcard to "com" `google.com##.mn-dwn-arw:style(top: 27px !important;)` didn't make a difference.

**Comment by Yuki2718** [comment]
This is when uBO's other filters are enabled:
![google3](https://user-images.githubusercontent.com/58900598/77021327-bd178680-69c9-11ea-9fdb-cdb29d15e0ce.png)

**Comment by pes10k** [comment]
@antonok-edm is this because custom rules are still going through the 1p vs 3p distinction (which i think is good for now)?  That might explain what you're seeing @Yuki2718 (see https://brave.com/whats-brave-done-for-my-privacy-lately-episode2/ for more details)

**Comment by ryanbr** [comment]
Supporting $generichide would be helpful (used by uBo and EL)

**Comment by RobertH1999** [comment]
Is it possible for Brave to implement a feature such as

**Comment by RobertH1999** [comment]
Is it possible to implement something like this in the future? 
![ublock](https://user-images.githubusercontent.com/32373877/90552082-d2176200-e181-11ea-81e5-bafaad9023d6.PNG)
@pes10k 

Like an "This is for advanced users" more granule blocking

**Comment by pes10k** [comment]
Hi @RobertH1999, we're interested in adding more debugging information like this, but I dont think we'll be able to get to it soon so I'll close this (this issue is more for matching uBO capabilities than debugging information / UI).  I'm going to close this issue now, but I've added a seperate issue to track here: https://github.com/brave/brave-browser/issues/11426

**Comment by pes10k** [comment]
(marking this as duplicate since there is just one related open issue, already being tracked in https://github.com/brave/brave-browser/issues/8559)
