### ISSUE TITLE
whitespace characters are too wide

### ISSUE THREAD

**Issue by g-thome** [brave/brave-browser#8482]
## Description 

whitespace characters' width are rendered at least twice as wide as they should be. that doesn't happen on every website tho. i could only reproduce it on github.com 

## Steps to Reproduce

   1. go to github.com

## Actual result:

![actual result](https://i.imgur.com/0BTJ1ax.png)

## Expected result:
![expected result](https://i.imgur.com/OJgoIUV.png)

## Reproduces how often: 
everytime i visit github.com

## Brave version (brave://version info)

Brave : 1.4.95 Chromium: 80.0.3987.122 (Official Build) unknown (64-bit)
Revision : cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS : Linux

## Version/Channel Information:
currently reproducible on all channels.

## Other Additional Information:
i couldn't reproduce it on the latest version of chrome and neither could i fix it by disabling shields and rewards.

**Comment by rebron** [comment]
cc: @srirambv Seen this one?

@g-thome Can you tell us more about the distribution that you're using?

**Comment by bsclifton** [comment]
Closing as stale - no additional information has been provided. If this is still happening, please share more about the distro that you're using. There is a similar report of fonts having a problem reported with https://github.com/brave/brave-browser/issues/3991 - which is due to wine fonts. Removing that fixed the issue
