### ISSUE TITLE
Install location is different for stub and offline installer

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#851]
## Description 

Install location is different for stub and offline installer

## Steps to Reproduce

   1. Running `brave_installer-x64.exe`, installs Application and User Data profile on `%appdata%\local`.  2 
   2. Both application and user data profile are installed in `AppData\Local\BraveSoftware\Brave-Browser`. 
   3. This installs the release version (Orange Lion logo, if you open about Brave it gives update error) 
   4. Running `BraveBrowserDevSetup.exe` installs Dev build in `C:\Program Files (x86)\BraveSoftware\Brave-Browser-Dev\Application` but User Data profile is installed in `AppData\Local\BraveSoftware\Brave-Browser-Dev\User Data`. 
   5. It creates CrashReports folder in both of the above locations.  

## Actual result:

Install location is different for stub and offline installer

## Expected result:
Irrespective of which installer is used, setup should be done in same location

## Reproduces how often: 

100%

## Brave version (about:brave info) 

All

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

This is blocked on #688 but should be ideally fixed before 0.55x
cc: @RyanJarv @mbacchi @bbondy @simonhong

**Comment by simonhong** [comment]
When we run silent installer(`brave_installer-x64.exe`) w/o command line, it will always install user mode stable version. Please check https://github.com/brave/brave-browser/wiki/Brave-omaha#test-silent-intaller-brave_intallerexe

**Comment by simonhong** [comment]
I think this is not an issue.

**Comment by Neustradamus** [comment]
Dear @brave team,

This issue is more linked to the bad folder of user profile.

Currently, user profile is saved in the bad folder.

%LOCALAPPDATA% must be replaced by %APPDATA%.

But attention, for example, Mozilla Firefox has:
- Install folder: %PROGRAMFILES%\Mozilla Firefox
- Profile folder: %APPDATA%\Mozilla\Firefox
- Cache folder: %LOCALAPPDATA%\Mozilla\Firefox

Linked to:
- https://github.com/brave/brave-browser/issues/1473
- https://github.com/brave/brave-browser/issues/4609

Thanks in advance.
