### ISSUE TITLE
Implement User wallets (Uphold) on Android

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#8511]
## Description 

Please implement User wallets (Uphold) on Android

We'll need a design for this @jamesmudgett

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.10.92.apk`
- Verified the user wallet scenarios on both clean and upgraded profile
Clean profile
- Verified that `Verify Wallet` button in greyed out in BR panel when anon wallet balance is 0.0BAT
- Verified that anon wallet cannot be linked to uphold if the wallet balance is less than 25BAT
- Verified that anon wallet with balance 10 BAT cannot be connected to uphold (as the balance is less than 25 BAT)
- Verified that `Verify Wallet` button color changed to blue when wallet balance is 25 or greater than 25 BAT
-	Verified that anon wallet with balance 25 BAT can be connected to KYC’d uphold account (as the balance equals to 25 BAT)
- Verified that anon wallet with balance 30 BAT can be connected to KYC’d uphold account (as the balance equals to 25 BAT)
- Verified that `Wallet Verified` button is shown in BR panel once the KYC’d uphold account is connected 
- Verified that `Disconnected` button is shown in BR panel once the wallet is disconnected
- Verified that reconnect the KYC’d uphold wallet works fine
- Verified that KYC’d wallet disconnect and reconnects works fine when anon wallet balance is 25 BAT
- Verified that KYC Account disconnect/reconnect with lower than threshold balance works fine (claim UGP grants of 30 BAT and connect KYC’d account and Tips 30 BAT to a verified pub, disconnect and reconnect to uphold works fine even when anon wallet balance is zero)
- Verified that non-KYC’d uphold account can be connected to an anon wallet, also verified disconnect and reconnect works as expected
- Verified that when non-KYC’d uphold account is connected to an anon wallet, verify wallet doesn’t show `Add Funds` option instead it shows complete verification message
- Claim UGP grants of 30 BAT, verify wallet with non KYC’d account. Verified that the `Verify Wallet` button has `Complete wallet verification`, `Go to my uphold account`, and `Disconnect from Brave Rewards` options. Send one-time tip of 10 BAT to verified pubs and make the wallet balance as 20 BAT and disconnect and reconnect wallet works as expected
- Claim UGP grants of 30 BAT and connect to a KYC’d uphold account, send a tip of 10 BAT to a verified pub and balance becomes 20 BAT, disconnect and reconnect wallet works as expected.
- Claim UGP grants of 30 BAT and click on Verify wallet and open uphold account creation page, open a new tab and visit a verified pub and send 5 BAT and again send 1 BAT, wallet balance becomes 24 BAT, complete the uphold account creation. After creating non-KYC'd account verified that uphold is connected to an anon wallet which is having balance of 24 BAT

Upgrade scenarios:
- Install GPS version and claim UGP grants of 30 BAT and send a tip of 6 BAT to a verified publisher so that the wallet balance becomes 24 BAT, then Upgrade the profile to `1.10.92` and click on `Verify Wallet` and verify that the message is displayed as `A minimum balance of 25 BAT is required to verify` 
- Install GPS version and claim UGP grants of 30 BAT and send a tip of 5 BAT to a verified publisher so that the wallet balance becomes 25 BAT, then upgrade profile to `1.10.92` and click on `Verify Wallet` and verified that user can connect to KYC’d uphold account
