### ISSUE TITLE
[Desktop] Improve contrast among tabs

### ISSUE THREAD

**Issue by Tectract** [brave/brave-browser#8576]
## Description
There is almost no alpha gradient between selected tab and non-selected tab.

There should be STRONG CONTRAST applied to the tab that is selected, so I can tell which one I am on, always.

## Designs
Increase contrast between active and inactive tabs with these updates:
- Don’t show ‘X’ button on inactive tabs until hover or focus
- Inactive tab title has 70% opacity; on hover or focus show title at 100% opacity
- Decrease contrast of tab separator: light theme `#BEBEBF`,  dark theme `#393838`, no color changes at this time for private window / with tor tab separator
- Make active tab font Semibold

![image](https://user-images.githubusercontent.com/2388823/92970712-f9d1b100-f433-11ea-9ad3-70209f0c109c.png)
![image](https://user-images.githubusercontent.com/2388823/92970727-ffc79200-f433-11ea-8163-21f2df282dbb.png)
![image](https://user-images.githubusercontent.com/2388823/92970737-048c4600-f434-11ea-9e49-a5126c897822.png)
![image](https://user-images.githubusercontent.com/2388823/92970753-0950fa00-f434-11ea-96cd-8b4e7dace4f8.png)

## Assets
Figma link: https://www.figma.com/file/sS3l8tqUFxt54MEiBTalUI/Desktop-toolbar-and-menu?node-id=59%3A2868

**Comment by Brave-Matt** [comment]
While I apologize for the inconvenience, this isn't something we hear that often -- although we did have an open issue a while back regarding private window tabs (specifically) being hard to tell which was in focus.

![image](https://user-images.githubusercontent.com/3299098/76116608-2b5a5300-5f9f-11ea-92f5-4eb668c2612f.png)

The contrast seems pretty strong to me, especially since there's absolutely no border of any kind surrounding the tabs that are not selected. 
cc @petemill

**Comment by Tectract** [comment]
A border around the tab that IS selected would be super-nice, the option for a border. It's *sort of*, *mostly* clear. An alpha inversion of the tab color would make it really clear :)

**Comment by rebron** [comment]
This might be a dupe as I know @bradleyrichter was looking into this.

**Comment by bsclifton** [comment]
cc: @bradleyrichter @karenkliu

**Comment by karenkliu** [comment]
I feel like if we did this other issue https://github.com/brave/brave-browser/issues/788 it would partly address this one.

The other update that @bradleyrichter wanted to make was to decrease the opacity of inactive tab titles+favicons so there would be more contrast. Brad - could you attach the design? Not sure where you've left it.

**Comment by bradleyrichter** [comment]
This is only a problem in dark-theme. It is partially caused by our background color being too light. We can darken it slightly to get pst the threshold, and also fade the non-selected titles just enough to achieve the threshold. I would also like to hide the close buttons on non-selected tabs. They would appear only on tab-hover. (the entire tab for hover detection)


preview:
![image](https://user-images.githubusercontent.com/13509546/91760031-7b4d5780-eb87-11ea-8f73-0034b612dfc8.png)

**Comment by karenkliu** [comment]
@rebron @bsclifton Designs added!

**Comment by rebron** [comment]
@brave/legacy_qa pull in @karenkliu for QA on this one if any questions.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.18.68 Chromium: 87.0.4280.67 (Official Build) dev (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the description and design mentioned in https://github.com/brave/brave-browser/issues/8576#issue-577110479

**Light Theme:**
- Verified that the `X` icon is not present on the inactive tabs
- Verified that the `X` icon is present only in the active tab
- Verified that mouse hover or focus show title at 100% opacity for the active tab
- Verified that inactive tab title shows 70% opacity
- Verified that active tab font is Semibold

**_Normal Tab:_**
![image](https://user-images.githubusercontent.com/38657976/100999398-c14cf980-3582-11eb-857e-9f83c8cb05fc.png)
**_PT:_**
![image](https://user-images.githubusercontent.com/38657976/101000592-20f7d480-3584-11eb-9776-c5cb452553a9.png)
**_TOR:_**
![image](https://user-images.githubusercontent.com/38657976/101000672-3c62df80-3584-11eb-8ffd-bd60accfa4a2.png)

**Dark Theme**
**_Normal Tab:_**
![image](https://user-images.githubusercontent.com/38657976/101000284-ae86f480-3583-11eb-9bae-c0617e7cdd06.png)

**_PT_**
![image](https://user-images.githubusercontent.com/38657976/101000955-8e0b6a00-3584-11eb-8693-d4c8392e0249.png)

**_TOR_**
![image](https://user-images.githubusercontent.com/38657976/101001131-b8f5be00-3584-11eb-8043-67a4e9a8a713.png)
