### ISSUE TITLE
What is Brave browser's relation to Google?

### ISSUE THREAD

**Issue by oivinds** [brave/brave-browser#8598]
I am asking because when I go to window > extensions to add an extension to Brave, I am logged in with my Google account. 
I'm pretty sure I was not already logged in to some of Googles services .

**Comment by rebron** [comment]
Hi @oivinds 

You're likely logged into a Google service because we're simply linking to https://chrome.google.com/webstore/category/extensions -- all of the Chrome extensions there are available in Brave. We're linking to the Chrome Web store for convenience, login not required (nor recommended).

Sign out of Google completely and you'll be able to install extensions from: https://chrome.google.com/webstore/category/extensions
