### ISSUE TITLE
Youtube videos not playing when shield is active

### ISSUE THREAD

**Issue by jakeherp** [brave/brave-browser#8614]
## Description 

On Youtube I keep getting the following error when the shield is activated:
```
An error occurred. Please try again later. (Playback ID: xX3JC0-oJDw3LOi4)
```

Reloading the page sometimes fixes the error, sometimes certain videos do not play at all. Disabling the shield on Youtube is causing other problems, where only the ad plays, but the actual video never plays.

## Steps to Reproduce

   1. visit Youtube, make sure the Shield is active
   2. open any video from the home page

## Actual result:
Video fails opening with error message `An error occurred. Please try again later. (Playback ID: xX3JC0-oJDw3LOi4)`

## Expected result:
Video plays as expected

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.15.3 (Build 19D76)
JavaScript | V8 8.0.426.26
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,SimplifyHttpsIndicator,WebUIDarkMode --disable-features=AutofillServerCommunication,WebXrGamepadModule,VideoPlaybackQuality,AudioServiceOutOfProcess,SmsReceiver,NotificationTriggers,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,WebXR --flag-switches-begin --enable-devtools-experiments --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | ~/Library/Application Support/BraveSoftware/Brave-Browser/Default

**Comment by Wodann** [comment]
Running into the same issue on PC (Windows), but for me it doesn't seem to matter whether shield is on or off.

**Comment by rebron** [comment]
Might be a dupe. cc: @Miyayes and @ryanbr 

@jakeherp Do you have a specific youtube url you mind sharing? Also, are you signed in?

**Comment by ryanbr** [comment]
This has been reported by a few browsers (not just brave). Just an example from Adguard:

https://github.com/AdguardTeam/AdguardFilters/issues?q=youtube.com

It seems to be a youtube issue.

**Comment by rebron** [comment]
Closing per last comment from @ryanbr

**Comment by ner00** [comment]
I suppose the end game is for people to move away from browsers that fail at loading videos using some privacy features, by not looking into this more deeply and simply chalking it up to a "youtube issue" will result in a loss of users over time.

**Comment by bsclifton** [comment]
@ner00 we are always looking to find/fix problems with YouTube and if you search our issue log, you'll notice we have quite a few. In order to really take any action though we need some help identifying the problem

We can re-open this issue - but we need some help identifying specific steps that break for everybody (so that we can debug)

**Comment by ner00** [comment]
@bsclifton I understand. This issue seems particularly hard to repeat at will, there doesn't seem to be a consistency beside being related to ad-blocking. 

My previous comment was also born out of frustration from seeing this case almost always being treated as a Youtube issue when there is an abundance of anecdotes pointing quite clearly towards the involvement of ad-blocking software or techniques. 

Unfortunately I am in no position to help, only that you should take these reports seriously, even though you can't quite act on the information (or lack thereof).
