### ISSUE TITLE
Refactor timers

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8676]
Timers right now are not in a good place. We should brainstorm how to fix it. Timer should have weak pointer as a callback so that you don't need things like `OnTimer`. Also I think we should handle them in shared lib and not in client.

**Comment by NejcZdovc** [comment]
take a look at https://github.com/brave/brave-core/pull/5197 and copy timer into rewards

**Comment by zenparsing** [comment]
Timers are currently used in the following files:


- `api_parameters.cc`
  - `retry_timer_id_`
- `contribution.cc`
  - `refresh_timers_`
  - `last_reconcile_timer_id_`
  - `queue_timer_id_`
  - `unverified_publishers_timer_id_`
- `publisher_server_list.cc`
  - `server_list_timer_id_` (This will be going away with publishers v4)
- `uphold.cc`
  - Stored in `ledger::TransferFee`, sent to ledger client and stored in prefs (`kRewardsExternalWallets` / `"brave.rewards.external_wallets"`)
- `unverified.cc`
  - `unverified_publishers_timer_id_`

All usage sites other than `uphold.cc` can be replaced fairly easily with `base::OneShotTimer`. (I would prefer not to wrap base timer classes, since that will create an additional abstraction to learn without really making it easier to use.) We might want to add a couple of utility methods for calculating randomized delays, though.

For `uphold.cc`, we can likely use `base::BindOnce` to perform partial application of the `TransferFee`, although we'll have to think about copy/move issues carefully.

**Comment by zenparsing** [comment]
The following is a brief analysis of how timers are started, and restarted on browser startup:

- `api_parameters.cc`
  - Started after fetch completion, with different intervals depending on whether the fetch was successful.
  - Fetch is performed on intialization.
- `contribution.cc`
  - Retry timers
    - Ultimately restarted on browser start by `CheckNotCompletedContributions`, called from `Initialized`.
  - Last reconcile timer
    - Next reconcile time stored using `ledger_->SetReconcileStamp()`, which ultimately uses `braveledger_ledger::_reconcile_default_interval` (30 days) and `ledger::kStateNextReconcileStamp`.
    - Triggered by `StartMonthlyContribution`.
    - **Open question:** What calls `StartMonthlyContribution`?
  - Queue timer
    - Started from `CheckContributionQueue` for 15 seconds, which is called on `Initialized`.
- `promotion.cc`
  - Retry timer
    - Started for 5 seconds when `credentials_->Start(...)` returns a `RETRY` result.
    - Triggered on browser restart in `Initialize`, where the list of promotions are gathered from the database and resumed.
  - Refresh timer
    - Started on wallet initialization, and after fetching promotions.
    - Interval calculated from `ledger::kStatePromotionLastFetchStamp`, which is set after receiving a response from the server.
    - Possible existing bug: since a timestamp is set even on failed refreshes, if the browser is restarted after a failed refresh it will use a "successful" refresh interval (24 hours) instead of the error retry interval (300 seconds).
- `publisher_server_list.cc`
  - Calculates next interval from `ledger::kStateServerPublisherListStamp`.
- `uphold.cc`
  - Started on browser restart in `Initialize`, where all transfer fees are pulled out of prefs and timers are started for each one.
- `unverified.cc`
  - Started after processing a pending "unverified" contribution, in order to process the next pending "unverified" contribution.
  - Ultimately initiated by `Unverified::Contribute`, which is triggered when the publisher list is downloaded and successfully parsed.
  - Possible existing bug: if the process is shut down while there is a flush in progress, the flush will not be resumed until the publisher list is refreshed (which could take several days). A simple fix will be to start a flush operation on browser startup.
