### ISSUE TITLE
Brave crashes when brave sync option is enabled in windows

### ISSUE THREAD

**Issue by fizify** [brave/brave-browser#8678]
Because brave sync was disabled by default, and I saw a flag which had an option to re-enable it, I tried it and since turning it on, my brave doesn't even open. It is basically dead. Help? Version is 1.4.96

**Comment by mikestaub** [comment]
Where did you learn that brave disabled sync and where did you find the flag to re-enable it?

**Comment by fizify** [comment]
@mikestaub https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync-
The first line says "Brave Sync has been temporarily disabled for all version v1.3 and higher"
And also, I verified I couldn't find any option for brave sync visible in my client either.

And I found the flag to re-enable it in brave://flags. Can't give you the exact name of the flag rn because I can't open my brave but if you search for "brave sync" you'll find it

**Comment by bsclifton** [comment]
Sorry for the super long turn-around time @fizify ☹️ We should have a fix for a few more cases coming in the 1.7 release

@fizify you can edit the shortcut (on Windows) or open Brave via the command line and basically add `--disable-sync` to get past the crash you were experiencing

I'm going to close this as it should be fixed with https://github.com/brave/brave-core/pull/5139 (which will be in 1.7 release next week). But please try the above if you're still using Brave @fizify and let us know if it works
