### ISSUE TITLE
Fuzzy Touch Bar icons

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#868]
The back and forward icons in the Touch Bar on new MacBook Pros are fuzzy, while the other buttons are crisp. This issue is also present in Chrome. Maybe we can ship full-res icons without needing an upsteam fix?

Our icons:
![brave-browser_touchbar-icons](https://user-images.githubusercontent.com/639937/44744203-6aaa0880-aab9-11e8-987f-28adf35dd3b4.JPG)

Chrome's:
![chrome-touchbar-icons](https://user-images.githubusercontent.com/639937/44744204-6b429f00-aab9-11e8-9713-459a404fd217.JPG)

**Comment by petemill** [comment]
Note: Touchbar can be tested on non-touchbar macs with https://sindresorhus.com/touch-bar-simulator/ (macOS 10.14 or later required)

**Comment by rossmoody** [comment]
<img width="1132" alt="screen shot 2018-12-07 at 12 38 15 pm" src="https://user-images.githubusercontent.com/29072694/49671589-45645900-fa1d-11e8-8a5c-08f0730f787b.png">
These icons have gotten a pretty considerable amount of attention in both Retina and 1x sizes. Given their shape I think they are about as pixel perfect as they can get. Any remaining aliasing fuzziness would be due to the diagonal direction of the strokes in the arrows and I don't think that's fixable. Just a matter of pixels. Gonna close this one.
