### ISSUE TITLE
Add publisher proof support for our CRX3 files

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#873]
Inside this file: 
chromium_src/components/component_updater/component_installer.cc

Landed in this PR:
https://github.com/brave/brave-core/pull/369/files

Revert from CRX3 back to using CRX3_WITH_PUBLISHER_PROOF once our CRX files include a publisher proof.... whatever that is :)

**Comment by atuchin-m** [comment]
The code to generate proof is merged to Nightly. Now we need to support it in [brave-core-crx-packager](https://github.com/brave/brave-core-crx-packager)

**Comment by bbondy** [comment]
won't this fail all component downloads on Nightly if we don't do the component updates first? Maybe we should revert until we do those first?

**Comment by atuchin-m** [comment]
@bbondy Nightly is still can install CRX without publisher proof. I've only added the code to generate it.

We enforce using publisher proof only after releasing all components with it.

**Comment by bbondy** [comment]
Ok thx! 🙌

**Comment by atuchin-m** [comment]
Now all brave CRXs released with a publisher proof. A PR to enforce publisher proof verification (https://github.com/brave/brave-core/pull/12551) just have merged to brave-core.

**Comment by atuchin-m** [comment]
For QA: we need to check that all components are correctly installing on browser new profile.

**Comment by LaurenWags** [comment]
@brave/qa-team this originally caused a regression with Ads classification, so also confirm that all Ad components are installed correctly as well, version numbers are listed, no duplicates/errors, etc.

**Comment by bbondy** [comment]
@brave/qa-team could you also test that enabling this flag:
brave://flags/#ethereum_remote-client_new-installs

And changing your setting to brave://settings/wallet to Crypto Wallets (deprecated) works when you load brave://wallet to load your old wallet?

**Comment by stephendonner** [comment]
Case 2: Widevine
1. new profile
2. launch Brave
3. load `netflix.com`
4. log in
5. click `Allow` on the `Install and run Google Widevine` prompt
6. play any title
7. load `brave://components`
8. confirm the following:
  * streaming content plays
  * `Widevine` module name
  * version #
  * Status is `Component not updated` or `Component updated` (i.e. no errors)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.106 Chromium: 101.0.4951.41 (Official Build) (64-bit) 
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS

<summary>Case 1: new installs, core components</summary>
<details>

1. new profile
2. launched Brave
3. loaded `brave://components/`
4. waited 8 minutes
5. confirmed all listed components have the following:
  * correct name
  * version #
  * Status - `Component not updated` or `Component Updated`

`brave://components` | `brave://components` (after 8 minutes)
----------------------|-----------------------------------------
![image](https://user-images.githubusercontent.com/34715963/165196940-c5e5c1d2-2c50-41dd-830f-836260b9109a.png)|![image](https://user-images.githubusercontent.com/34715963/165196790-3832b1f0-24fd-47be-9cc0-241be566b894.png)



</details>

<summary>Case 2: Widevine</summary>
<details>

1. new profile
2. launched Brave
3. loaded `https://bitmovin.com/demos/drm`
5. clicked `Allow` on the `Install and run Google Widevine` prompt
6. played a title
7. loaded `brave://components`
8. confirmed the following:
  * streaming content plays (unable to screenshot due to DRM)
  * `Widevine` module name
  * `Version: 4.10.2391.0`
  * `Status` is `Updated` (i.e. no errors)


![image](https://user-images.githubusercontent.com/34715963/165197097-4b86d760-f932-49eb-a0de-ae126c94227e.png)

</details>

<summary>Case 3: Ads</summary>
<details>

1. new profile
2. launched Brave
3. loaded `components`
4. confirmed no `Ads` components
5. clicked on the BAT icon and `Start using Rewards`
6. refreshed `brave://components`
7. confirmed two (2) new resources are loaded:
   * `Brave Ads Resources (en)` - `Version: 1.0.41`
   * `Brave Ads Resources (US)` - `Version: 1.0.47`
8. loaded `cnn.com`
9. confirmed page classification works
10. triggered an ad and confirmed notifications work
11. confirmed I was rewarded for the ad

![image](https://user-images.githubusercontent.com/34715963/165197261-ac2158e2-01ef-4916-b574-022312016f59.png)
![image](https://user-images.githubusercontent.com/34715963/165197336-6cc93f66-8b06-4a2c-80f8-482f47cbcd3c.png)
![image](https://user-images.githubusercontent.com/34715963/165197648-3cc35f99-eaa4-469e-8920-afb1dc2254e1.png)
![image](https://user-images.githubusercontent.com/34715963/165197699-3e8f5660-0508-4fea-b780-3f32d7603378.png)


</details>


<summary>Case 4: on-demand spot-check (IPFS)</summary>
<details>

1. new profile
2. launched Brave
3. loaded `brave://components/`
4. in a new tab, loaded `ipfs://bafybeiaysi4s6lnjev27ln5icwm6tueaw2vdykrtjkwiphwekaywqhcjze`
5. clicked on `Use a Brave local IPFS node`
6. refreshed `brave://components`
7. confirmed one (1) new component was added (`Brave IPFS Client Updater (Linux)`)
8. waited 8 minutes
9. confirmed status is `Component not updated` (i.e. no errors)
10. confirmed `Brave IPFS Client Updater (Linux)` is at `Version 1.0.15`

![image](https://user-images.githubusercontent.com/34715963/165198375-e4f53739-9487-4ff1-aeff-c796209ef247.png)
![image](https://user-images.githubusercontent.com/34715963/165198398-aa84f13c-c510-40af-8867-3eaf28bb2b7c.png)
![image](https://user-images.githubusercontent.com/34715963/165198446-483a51a7-b9a3-48b5-8c79-42bc9f44ab14.png)
![image](https://user-images.githubusercontent.com/34715963/165198488-862afcfd-375e-43aa-920c-2bb02432be1e.png)


</details>

<summary>Case 5: Legacy Crypto Wallet</summary>
<details>

1. install `1.31.91`
2. set up a legacy Crypto Wallet
3. get 1 or more `ETH` from a testnet, such as Ropsten: `https://faucet.metamask.io/`
4. upgrade to `1.38.x`
5. launched Brave
6. set `brave://flags/#ethereum_remote-client_new-installs` to `Enabled`
7. set `Default cryptocurrency wallet` in `brave://settings/wallet` to `Crypto Wallets (Deprecated)`
8. relaunched Brave
9. checked `brave://wallet`
10. confirmed my `2 ETH` was present from my legacy Crypto Wallet

![image](https://user-images.githubusercontent.com/34715963/165199141-421553ce-24d1-48c3-8520-aaa63772a969.png)
![image](https://user-images.githubusercontent.com/34715963/165199204-d58b1446-2180-46ff-97ac-0f942127f4b8.png)
![image](https://user-images.githubusercontent.com/34715963/165199692-e3fb7a15-75ae-40ca-891e-5a3edeca794f.png)
![image](https://user-images.githubusercontent.com/34715963/165199990-b0537846-5ea0-4c70-90b4-e9a956c707dc.png)
![image](https://user-images.githubusercontent.com/34715963/165200015-9242c3f1-9f1b-491e-99ae-e1b69e6ac265.png)
![image](https://user-images.githubusercontent.com/34715963/165200104-61e9b632-5f00-4f6a-893d-02c7164ef612.png)


</details>

<summary>Case 6: Updates</summary>
<details>

1. install `1.37.114`
11. launched Brave
12. enabled Rewards via `Start using Brave Rewards` on `brave://rewards/`
13. loaded `brave://components`
15. updated to `1.38.x`
16. loaded `brave://components`
17. ensured the same or higher version numbers listed for all default/first-launch components
18. waited 8 minutes
19. confirmed status is `Component not updated` or `Component updated` (i.e. no errors)

`brave://components` (1.37.114, after 8 minutes) | `brave://components` (1.38.x)
--------------------------------|--------------------------------
![image](https://user-images.githubusercontent.com/34715963/165201034-c1d94778-c634-41e9-8ccd-21cf6050c489.png)|![image](https://user-images.githubusercontent.com/34715963/165201159-a2547a3a-c82c-498a-953c-f1fad56b1d71.png)



</details>

**Comment by kjozwiak** [comment]
Verification **`PASSED`** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (32-bit)
--- | ---
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Android 12; Build/SP1A.210812.016
```

<summary>Case 1: new installs, core components</summary>
<details>

1. new profile
2. launched Brave
3. loaded `brave://components/`
4. waited 8 minutes
5. confirmed all listed components have the following:
  * correct name
  * version #
  * Status - `Component not updated` or `Component Updated`

`brave://components` | `brave://components` (after 8 minutes)
----------------------|-----------------------------------------
![Screenshot_20220426-210649_Brave](https://user-images.githubusercontent.com/2602313/165418698-109f5801-6e4c-4129-a9ab-4ea904e980e7.jpg) | ![Screenshot_20220426-210813_Brave](https://user-images.githubusercontent.com/2602313/165418720-e3a1c4da-58c2-4cee-ba59-1c6dc1eeddfe.jpg)

</details>

<summary>Case 2: Ads</summary>
<details>

1. new profile
2. launched Brave
3. loaded `components`
4. confirmed no `Ads` components
5. clicked on the BAT icon and `Start using Rewards`
6. refreshed `brave://components`
7. confirmed two (2) new resources are loaded:
   * `Brave Ads Resources (en)` - `Version: 1.0.41`
   * `Brave Ads Resources (CA)` - `Version: 1.0.47`
8. loaded `cnn.com`, `imdb.com` and `business.cnn.com`
9. confirmed page classification works
10. triggered an ad and confirmed notifications work
11. confirmed I was rewarded for the ad

`brave://components` (before) | `brave://components` (after) | `Ad notification` | `brave://rewards`
----------------------------------|--------------------------------|-------------------|---------------------
![Screenshot_20220426-222015_Brave](https://user-images.githubusercontent.com/2602313/165426957-837ea703-3fbe-496e-9373-489191220c04.jpg) | ![Screenshot_20220426-222034_Brave](https://user-images.githubusercontent.com/2602313/165426976-c2b34802-4fda-44ae-a2a0-bbd5c72831d5.jpg) | ![image](https://user-images.githubusercontent.com/2602313/165427012-bc01ae26-aeb8-4f14-8e0c-b74cb7b69900.png) | ![Screenshot_20220426-222718_Brave](https://user-images.githubusercontent.com/2602313/165427108-f64615f4-36a4-4505-a221-680f0af34f6b.jpg)


```
2022-04-26 22:21:52.082 32070-32070/? V/chromium: [VERBOSE1:text_classification_resource.cc(50)] Successfully loaded feibnmjhecfbjpeciancnchbmlobenjn text classification resource
2022-04-26 22:21:52.552 32070-32070/? V/chromium: [VERBOSE1:text_classification_resource.cc(59)] Successfully initialized feibnmjhecfbjpeciancnchbmlobenjn text classification resource
2022-04-26 22:21:52.562 32070-32070/? V/chromium: [VERBOSE1:features.cc(51)] Text classification feature is enabled
2022-04-26 22:22:15.972 32070-32070/? V/chromium: [VERBOSE1:text_classification_processor.cc(63)] Classified text with the top segment as personal finance-personal finance
2022-04-26 22:22:37.929 32070-32070/? V/chromium: [VERBOSE1:text_classification_processor.cc(63)] Classified text with the top segment as science-economics
2022-04-26 22:23:00.327 32070-32070/? V/chromium: [VERBOSE1:text_classification_processor.cc(63)] Classified text with the top segment as personal finance-personal finance
2022-04-26 22:23:17.439 32070-32070/? V/chromium: [VERBOSE1:text_classification_processor.cc(63)] Classified text with the top segment as arts & entertainment-film
```

</details>

<summary>Case 3: Updates</summary>
<details>

1. install `1.37.116 Chromium: 100.0.4896.127`
11. launched Brave
12. enabled Rewards via `Start using Brave Rewards` on `brave://rewards/`
13. loaded `brave://components`
14. noted the versions for Brave Ads Resources: (en) and (CA)
15. updated to `1.38.x`
16. loaded `brave://components`
17. ensured the same or higher version numbers listed for default/first-launch components
18. waited 8 minutes
19. confirmed status is `Component not updated` or `Component updated` (i.e. no errors)

`brave://components` (1.37.116 after 8 minutes) | `brave://components` (1.38.107 after 8 minutes)
--------------------------------|--------------------------------
![Screenshot_20220426-223831_Brave](https://user-images.githubusercontent.com/2602313/165429294-eef5c44c-8820-4cce-a040-24a950813bf2.jpg) | ![Screenshot_20220426-224037_Brave](https://user-images.githubusercontent.com/2602313/165429303-dc672acd-ab44-4ded-ba19-4a7c5d5afdf2.jpg)

</details>
