### ISSUE TITLE
Security/Privacy Slider UI paradigm

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#876]
We have — conservatively — a metric heckton of different privacy settings and switches. We also have a whole bunch powerful features which come with some privacy tradeoffs — reasonable ones, but tradeoffs nonetheless. Expecting users to learn and understand this constellation of functionality and privacy is a big ask. What if we reduced it to a single-dimensional choice: on one end is "more privacy" and on the other, there's "more functionality".

Behold: the concept of the **Privacy Slider**.

What functionality is available where on the slider? How do users discover the slider? How are the notches along the slider labeled? These are questions for another day. All that matters here and now is: a slider.

**Comment by tomlowenthal** [comment]
Some features which might be controlled by **The Slider**:
- Shields defaults (fingerprinting, cookies, scripts…)
- HTTPS-only mode
- Widevine/plugins
- webtorrent
- third-party extensions
- URL-bar autocomplete
- Brave Rewards
- autofill
- password manager

[This is not a complete list, and suggestions are welcome for now.]

**Comment by Brave-Matt** [comment]
I just had a user suggest something like this (link below).
He referenced the way Tor has `Low - Medium - High` settings to pick from.
I think something that looks like this (security slider/preset levels of protection) is a good idea overall. The problem that comes to mind is what happens when **Shields blocks or prevents something from a website that ultimately breaks it (or some functionality it serves). Would there need to be site-level Shields state for both (or all) security levels?**

**Example**: My "security slider" is set to "High". I visit some sites that are fine but it breaks this one site I use a lot. If I go into Shields and fix the site by [lets say] allowing cookies, does this the site in question now have persistent Shields config for both "high" and "low" states of the slider? Additionally, if I don't want to use the slider (I assume it's an "opt-in" thing) or I disable it, is there now a third configuration for that site that would need to be saved?

https://www.reddit.com/r/brave_browser/comments/aaonoh/feature_request_easy_preset_security_adscript/

**Comment by siric1** [comment]
There's a nice extension named "Privacy Settings" (open source), that does exactly this. There's "full privacy" and "enhanced privacy" and these buttons act nothing more as presets for the various options provided. And I believe this is what the Reddit user meant, the slider would be nothing more than Shield presets so he doesn't have to use the dropdowns to set each setting individually.

The "Privacy Settings" extension uses the `chrome.privacy` API: https://developer.chrome.com/extensions/privacy 

Screenshot of the "Privacy Settings" extension:
<img width="613" alt="privacy-settings" src="https://user-images.githubusercontent.com/31568598/50572397-396f7b00-0dc0-11e9-951e-7cf74277e799.png">
