### ISSUE TITLE
Brave is promoting blockhain programs and making a fortune from its users who will likely lose their money.

### ISSUE THREAD

**Issue by JamesTheHacker** [brave/brave-browser#8793]
Blockchain advertising is one of the most lucrative. Affiliate commissions are insane. In the corner of the brave browser is a link to etoro. A blockchain trading platform.

Brave is promoting it on their home page when you click a new tab. It's in the corner.

Why is this bad?

Because the owners of Brave are making an absolute fortune from folks who will lose their money. Brave has an affiliate link. You can see it when you hover the etoro link: [https://partners.etoro.com/B12165\_A84346\_TClick\_SUK.aspx](https://partners.etoro.com/B12165_A84346_TClick_SUK.aspx)

You can see what etoro pays per signup here:  [https://www.affiliateprograms.com/p/etoro-partners/](https://www.affiliateprograms.com/p/etoro-partners/)

>Up to $200 CPA, 25% Revenue Share

So, when a user signs up Brave are getting up to $200 per user, and a share of etoro's profits from that user.

For a project that is meant to promote an internet free advertising I think this is kind of shady. If you click the affiliate link right at the bottom of brave the etoro page says this:

>CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. 62% of retail investor accounts lose money when trading CFDs with this provider. You should consider whether you understand how CFDs work, and whether you can **afford to take the high risk of losing your money.**

Anyone agree this is not right?

**Comment by JamesTheHacker** [comment]
I see admins removed the reddit post: https://www.reddit.com/r/brave_browser/comments/fm3i5g/brave_is_promoting_blockhain_programs_and_making/

**Comment by Miyayes** [comment]
> I see admins removed the reddit post: https://www.reddit.com/r/brave_browser/comments/fm3i5g/brave_is_promoting_blockhain_programs_and_making/
> 
> So basically you don't want people seeing this? You're closing it for discussion? Something stinks about this.

Please don't be disingenuous, here. You _know_ that you double-posted. Your second post (which you linked above) was removed because it was a duplicate. You have since deleted your first post, which I still have a permalink to (as evidence), here: https://www.reddit.com/r/brave_browser/comments/fm3czv/brave_is_promoting_blockhain_programs_and_making/  You deleting your own first post gives the appearance of "closing down discussion", even though your second post was removed only because it was believed to be a duplicate.

**Comment by lukemulks** [comment]
Brave announced Sponsored Images in January 2020: 
https://brave.com/introducing-sponsored-images-in-brave/

Followed up with another announcement about the unit in Feb 2020: 
https://brave.com/sponsored-images-now-available-on-all-brave-platforms/

The unit includes an option to disable, directly in the UI. 

- eToro provided the link that was used in the Sponsored Image banner. False assumption being made re: rev per user in the issue. 
- eToro is an established company in the space, advertises on popular platforms, and has been the subject of a Twitter Marketing case study: https://marketing.twitter.com/emea/en_gb/success-stories/fintech-innovator-etoro-builds-its-brand-image-with-first-view

Brave promotes itself as a privacy-focused browser with the first global private ad and rewards platform. This is on our website, marketing and community. 

If you have issue with the media, please raise in the Community. Closing the issue, as the Community is the proper channel for this type of discussion.

**Comment by JamesTheHacker** [comment]
I made the post. Deleted it, and posted it here, then reposted on Reddit with a link to this instead. As - like you said - it was duplicate. The first I deleted, the second your team locked. Why have you closed this discussion and not addressed the issue of promoting a high risk bitcoin platform to your users? 

That needs discussing, and if not here I'll write it up on a blog post and spin it around the places where it will get noticed. Because frankly what you're doing here is disingenuous.

**Comment by JamesTheHacker** [comment]
@lukemulks That's not true, because etoro is a high risk trading platform who openly admit to most people losing money. How is that honest? You have an affiliate link, and you generate commissions from it. Are users aware of this in any of the privacy or terms of use documents?

**Comment by JamesTheHacker** [comment]
And this effects your users, and they should be aware of this. So yes, it needs discussing here. Some of your developers may feel this practice disingenuous. If you're using an affiliate link and not declaring it to users btw, that's a lawsuit. I don't see why you would freely promote etoro without earning a commission. Don't lie.

**Comment by vagrantjo** [comment]
Brave promoted an "internet free advertising?" If you mean they promote an internet free of advertising, they don't. You get brave rewards for viewing ads. 

I think the average brave user is somewhat computer savvy, so I don't think people are just blindly clicking links and signing up things just because they are on the home page. You've done more to draw attention to this exchange than the home page has, I had to look for the link you're talking about. I generally don't pay too much attention to the home page.

You could argue that having an affiliate link without disclosing it is a little dishonest. But nobody is being forced into joining this exchange. If they add an "affiliate link" disclaimer. Would that solve this issue?

**Comment by JamesTheHacker** [comment]
An affiliate disclaimer is required. If it's not it's a potential lawsuit. If they produce an affiliate disclaimer then Brave are making high profits promoting **high risk bitcoin trading platforms where by the majority will lose**. Not to mention it's the wrong niche to be promoting etoro. They have the worst reviews so it's absolutely not in the interest of the users. It's in the interest of the owners of brave who are shaving off healthy affiliate commissions.

Your "think" requires statistics. You can't assume that at all.

**Comment by JamesTheHacker** [comment]
As the officers are located in the USA (and London) then by law it's required to disclose: https://www.privacypolicies.com/blog/ftc-affiliate-disclosure/

So, already breaking the law if there's no disclaimer.

**Comment by vagrantjo** [comment]
I think it is a pretty fair assumption to say that Brave users are at least somewhat computer savvy. It is a cryptocurrency based browser. And my own thoughts don't require statistics. Something isn't true because there are statistics to back it up. Statistics by definition have to come after the fact. They can prove something is true, they don't make it true.

And I do think it is fairly save to assume a novice user isn't going to stumble upon Brave and start using it over Chrome, Safari, or god forbid, Microsoft Edge. 

You should have started off your post with that last link you posted. That seems like a pretty strong piece of evidence supporting your argument. It does appear, based on that link, that they are in violation of the law. And I do agree that having an affiliate link for someone who is already paying to advertise on your platform does seem like bad practice, and I think it goes against what many users believe Brave stands for. At least they should add that it is an affiliate link in the disclaimer.

**Comment by Shadow-of-Colossus** [comment]
Most websites and software companies are criminal to the nth degree.. fact of life!

**Comment by markdreyer** [comment]
@JamesTheHacker Didn't you opt in to view ads? Aren't you getting paid BAT to view them? There is a solution here and it's simply to opt out.

**Comment by JamesTheHacker** [comment]
Nope. I didn't opt in to see those ads.

**Comment by lukeswitz** [comment]
Can we get clarification as to why the ads/backgrounds are displayed to those of us who have opted out of your monetizing/BAT? 

Concerning to see this issue closed so quickly & without any clarification. Brave, how to we eradicate etoro from your software? Your provided methods don’t accomplish the above, and your response here has many scratching their heads as to the legality of it all.

**Comment by Miyayes** [comment]
> Can we get clarification as to why the ads/backgrounds are displayed to those of us who have opted out of your monetizing/BAT?

As linked above, you can read more about the Sponsored Images here, in our original announcement post from January 2020: https://brave.com/introducing-sponsored-images-in-brave/

You can easily disable them by clicking the settings on the bottom right of the new tab page: 
![image](https://user-images.githubusercontent.com/11497541/77298627-96a36500-6cc1-11ea-8d32-5ab4262e8a85.png)

> Concerning to see this issue closed so quickly & without any clarification. Brave, how to we eradicate etoro from your software? Your provided methods don’t accomplish the above, and your response here has many scratching their heads as to the legality of it all.

eToro itself is not bundled with the software; these are just temporary background images that are updated every so often. The eToro ad campaign has already completed, so they are no longer displaying. (eToro paid for the advertising space for a specific period of time. That period of time has expired.) In fact, right now, a BlockFi campaign is active, so users who still have new tab page sponsorship images enabled will see BlockFi background images on the new tab page, as of March 23, 2020.

**Comment by lukeswitz** [comment]
> > You can easily disable them by clicking the settings on the bottom right of the new tab page:
> ![image](https://user-images.githubusercontent.com/11497541/77298627-96a36500-6cc1-11ea-8d32-5ab4262e8a85.png)
> 

No, on mobile that’s not possible. Yeah, so etoro is done and now I’m inundated with sofi ads now. Peddling BAT shouldn’t be the priority here, I think that’s where the disconnect lies in this discussion.

**Comment by JamesTheHacker** [comment]
@Miyayes so what you're saying is you listened to the community and removed it over ethical issues This is good news, but instead of making out I was lying about this and brushing it under the rug you could have acknowledge the mistake.

**Comment by luminoso** [comment]
> Can we get clarification as to why the ads/backgrounds are displayed to those of us who have opted out of your monetizing/BAT?

Choosing when to enable sponsored images is is straightforward: If a user didn't join rewards, then sponsored images should be **OFF by default.** I just tried a clean profile and sponsored images are ON even if you didn't joined rewards.

For users that didn't join rewards, they earn nothing with this abusive full-page ad in their browser. For those who are looking for rewards it should be fine though (but still optional, since it is a third way of getting ads to sum to notification and webpage ads)

**Comment by Miyayes** [comment]
> so what you're saying is you listened to the community and removed it over ethical issues This is good news, but instead of making out I was lying about this and brushing it under the rug you could have acknowledged the mistake.

That is **not** what I am saying, because that is **not** what happened. The campaign ended because eToro paid for an ad campaign between `START` and `END_DATE`, and it is past the `END_DATE`. (The end date was 03/20/2020.) As of now, the current ad campaign is BlockFi. After BlockFi, there will be another one. And before eToro, there were images sponsored by Lokai, Crypto.com and Western Digital. 

On a human note, the immediate presumption of deceitful intent is discouraging, to say the least. It's doubtful you would be so accusatory to me in person, but sadly the internet enables such casual indifference.

At this point, even if I were at liberty to send you a screenshot of the Excel spreadsheet containing the normal end date, you would still disbelieve me. So, you will just have to take _me_, at least, at my word. 

>@luminoso Choosing when to enable sponsored images is straightforward: If a user didn't join rewards, then sponsored images should be OFF by default.

We made the choice for it not to be off by default, which we openly talk about in the original Sponsored Images announcement post from January, which I shall link again: https://brave.com/introducing-sponsored-images-in-brave/

All users, however, should see this message upon first seeing a new tab page sponsored image: 

![image](https://user-images.githubusercontent.com/11497541/77356298-69d06b80-6d1c-11ea-95d8-87bf9d6d8c45.png)

**Comment by JamesTheHacker** [comment]
I'm not accusing, I reported what I seen and it's evident the community agreed. Nothing I said was a lie, you was blatantly using an affiliate link, had no affiliate disclaimer, and as a result had to remove it. Maybe you will not admit to this because doing so publicly may make you liable to a lawsuit. I've worked in affiliate marketing for over 15 years; I have people in our Telegram marketing group that are pushing etoro (which I don't condone). I know how this works. For the average Joe they don't. That's why I made people aware to this.

**Comment by JamesTheHacker** [comment]
> We made the choice for it not to be off by default

Well that's not right. The user should opt in to see the advertisements otherwise many suckers out there will get duped into this and likely lose their money.

**Comment by bsclifton** [comment]
@JamesTheHacker @luminoso and others - thanks for the feedback! I've shared with the relevant folks and actions will be taken

As GitHub is specifically for tracking issues with the software and I believe all the important input is captured here already, I'm going to lock this issue. Thanks again for the input!

Please feel free to take up the issue more on https://community.brave.com/
