### ISSUE TITLE
[Desktop] Different private profile button style

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8807]
From current master build(`Version 1.8.31 Chromium: 81.0.4044.69 (Developer Build) (64-bit)`):
![image](https://user-images.githubusercontent.com/6786187/77282322-ef4c1f80-6d0c-11ea-8341-b5fb708f19b6.png)

From current beta build(`Version 1.7.67 Chromium: 80.0.3987.149 (Official Build) beta (64-bit)`):
![image](https://user-images.githubusercontent.com/6786187/77282433-4225d700-6d0d-11ea-8406-e825650f1afc.png)

**Comment by rebron** [comment]
cc: @tomlowenthal
Button being selected is wrong but placement of [icon-text] vs [text-icon] looks better?

**Comment by rebron** [comment]
cc: @karenkliu can you take a look? This is on the latest nightly https://github.com/brave/brave-browser/releases/tag/v1.8.32

**Comment by tomlowenthal** [comment]
No opinion on the order of the elements. But this is the first time I learned that this was a button rather than a badge. As far as I know, this was never specified as a button, and I’d prefer if it went back to being a badge.

**Comment by karenkliu** [comment]
☝️ what @tomlowenthal said. 

This order [icon-text] is correct:

![Screen Shot 2020-03-24 at 3 33 40 PM](https://user-images.githubusercontent.com/2388823/77483214-d747cf00-6de4-11ea-86d2-269e900a9020.png)


But it should have the same background color as the toolbar and should not be clickable.

**Comment by rebron** [comment]
cc: @mkarolin @petemill

**Comment by mkarolin** [comment]
The additional functionality from Chromium here is for when multiple Private windows were open. Then you have the window count in the button and the menu option to exit would exit them all at once. Not sure if we care for such functionality.
![image](https://user-images.githubusercontent.com/41635752/81446162-53edfd00-9148-11ea-996f-59803a7d9b48.png)

**Comment by bsclifton** [comment]
This is a nice feature; what action should we take with this ticket? Is the problem that it looks like a button?

**Comment by karenkliu** [comment]
@mkarolin I see - thanks for pointing this out. 

@bsclifton I suspect that the "Private" label became clickable after Chrome added some additional functionality and we inherited it. For private windows the issue is styling. This is what I recommend:

Style the "Private" button like a Brave button so users know there is functionality there
![private window 1](https://user-images.githubusercontent.com/2388823/83467173-ffc7f700-a42d-11ea-9c1f-0cf39bc7bb22.png)

On hover, show a hover state:
![private window 2 -hover](https://user-images.githubusercontent.com/2388823/83467183-05254180-a42e-11ea-9908-20c32b65cbbd.png)

On click, show a panel tweaked so the Private icon doesn't look like another button and with Brave styling + icons:
![private window 3 - panel](https://user-images.githubusercontent.com/2388823/83467188-08b8c880-a42e-11ea-9f98-9d9a72d08363.png)

When multiple windows are open, show this text treatment:
![private window 4 - multiple windows](https://user-images.githubusercontent.com/2388823/83467191-0f474000-a42e-11ea-89d6-e9b7e1d5389c.png)

We should support dark theme for the panel:
![dark theme panel](https://user-images.githubusercontent.com/2388823/83467592-32262400-a42f-11ea-81b0-466dd38e70f7.png)


TOR windows also inherits this functionality from Chrome but it doesn't really work:

- TOR panel doesn't show the number of TOR windows open
- Clicking "Exit Tor" doesn't close the window(s)

<img width="309" alt="Screen Shot 2020-06-01 at 5 01 28 PM" src="https://user-images.githubusercontent.com/2388823/83465682-8af2be00-a429-11ea-9e85-ce81dc5427c7.png">

Should we file a separate issue to fix this in Tor? I would recommend doing the same treatment as our Private windows to keep interactions consistent:
![tor window 1](https://user-images.githubusercontent.com/2388823/83467438-bf1cad80-a42e-11ea-9b7c-111a05e8bf5b.png)
![tor window 2 -hover](https://user-images.githubusercontent.com/2388823/83467444-c2b03480-a42e-11ea-9009-4148870f53c8.png)
![tor window 3 - panel](https://user-images.githubusercontent.com/2388823/83467446-c348cb00-a42e-11ea-9742-a7775b64bb1b.png)
![tor window 4 - multiple windows](https://user-images.githubusercontent.com/2388823/83467449-c3e16180-a42e-11ea-98c7-01ac472c963b.png)

Figma link for reference: https://www.figma.com/file/5THkuEtO2Ewn9LfqrHZP9a/Desktop-Private-Tabs-and-TOR?node-id=4%3A4737
