### ISSUE TITLE
[Android] Crash on attempting to open some settings after cr 81 rebase

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#8814]
## Description 
There is crash on the latest master on opening `Settings>Privacy>Clear data` and `Sync` settings. Needs to be fixed.

## Steps to reproduce 

   1. Go to mentioned settings and see crash

## Issue happens on 
   - Current Play Store version? no
   - Beta build? no

**Comment by srirambv** [comment]
@samartnik we should move this issue into 1.7.x once https://github.com/brave/brave-core/pull/5340 is uplifted. 

cc: @kjozwiak @SergeyZhukovsky

**Comment by srirambv** [comment]
Moving the issue to 1.7.x milestone as the closing PR is marked for 1.7.x but issue isn't moved

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.7.102 x64 stable build
- Verified clearing data from Privacy settings don't cause crash
- Verified clearing data from history page doesn't cause crash
- Unable to verify sync screen. Logged #9483 
-------
Verification passed on Samsung Tab A with Android 9 running 1.7.102 x64 stable build
- Verified clearing data from Privacy settings don't cause crash
- Verified clearing data from history page doesn't cause crash
- Unable to verify sync screen due to #9483
