### ISSUE TITLE
Youtube video does not play

### ISSUE THREAD

**Issue by debiasi** [brave/brave-browser#8824]
## Description 
When I try to play a youtube video it shows an error and didn't play. If I disable Shields it play (with ads)

## Steps to Reproduce

1. Enter youtube site https://www.youtube.com/ (I am logged in with my google account)
2. Choose any video like https://www.youtube.com/watch?v=7TcCIcE1hr8
3. Click play 

## Actual result:

"An error occurred, please try again later. (Playback ID:....)"

![Screen Shot 2020-03-23 at 19 57 59](https://user-images.githubusercontent.com/19234/77371761-d3637080-6d42-11ea-8ed7-b2b0b29a1816.png)

## Expected result:
Video played normally

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave	1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
Revision	5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS	macOS Version 10.15.3 (Build 19D76)
JavaScript	V8 8.0.426.27
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AllowPopupsDuringPageUnload,AudioServiceOutOfProcess,SmsReceiver,WebXR,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/debiasi/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No, worked on crome and I use two adblocks (on chrome) - uBlock Origin and Adblock

**Comment by scottrbaxter** [comment]
Since updating Brave to `1.5.115`, I am also experiencing this. Shields down (and Ublock disabled) and I still have this issue. I don't have Chrome installed to check against. If I open youtube.com everything seems fine. Click on any video and it attempts to load for a long time, then i get "If playback doesn’t begin shortly try restarting your device" and the macOS beach ball cursor. I can sometimes close the tab, but the entirety of Brave is still unresponsive and I have to force quit the app.

```
Brave | 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.15.3 (Build 19D76)
```

**Comment by kjozwiak** [comment]
I've been running into something similar but it usually happens when I leave a TY tab idling in another tab for an extended period of time. Also happens when I restart the browser and my session loads with several YT tabs that have been left opened. When I switch over, I run into the same error. Refreshing the tab usually works.

@debiasi @scottrbaxter when you run into the above, does refreshing the tab work? Are you seeing this appear in the middle of your video while watching? Or when you switch back to a previously opened YT tab?

Example:

<img width="1367" alt="Screen Shot 2020-03-25 at 2 35 44 PM" src="https://user-images.githubusercontent.com/2602313/77576553-c4e49880-6eab-11ea-8713-fd5c75d3fa7d.png">

Using the following build when I ran into the above a few times:

```
Brave | 1.8.40 Chromium: 81.0.4044.69 (Official Build) nightly (64-bit)
-- | --
Revision | 6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}
OS | macOS Version 10.15.3 (Build 19D76)
```

**Comment by scottrbaxter** [comment]
@kjozwiak that was not my experience, however your message does look related to the original post, and mine feels like a red herring at this point. I also confirmed with another that has been experiencing your same issue for the past few days. Here's their `chrome://version`

```
Google Chrome	80.0.3987.149 (Official Build) (64-bit)
Revision	5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS	macOS Version 10.15.3 (Build 19D76)
```

I feel this issue is upstream, sadly i'm not experiencing it myself, so not sure how to reproduce it.

**Comment by kjozwiak** [comment]
@scottrbaxter assuming it's upstream as well or a general issue with YT right now. Appreciate the information though! We'll keep an eye on this in case it gets worse but we've been seeing more reports. I'm going to logout/login out of my Gmail/Google accounts to see if it's possible related to some type of session issue on their end.

**Comment by rebron** [comment]
Maybe related to Youtube reducing their streaming quality, first in Europe and now globally due to the spike in usage. I was able to view this video fine: `https://www.youtube.com/watch?v=7TcCIcE1hr8` with shields up in 1.5.115 in logged in state.

**Comment by kjozwiak** [comment]
> I was able to view this video fine: https://www.youtube.com/watch?v=7TcCIcE1hr8 with shields up in 1.5.115 in logged in state.

This error happens intermittently. Videos work fine for me as well but you'll get that error when switching to a video that has been paused for a while or a tab that's lazy loaded. Seems some uers hit it more often. Could definitely be related to traffic/performance issues with YT.

**Comment by Huuuze** [comment]
A redditor may have [solved this issue](https://www.reddit.com/r/brave_browser/comments/fno7hn/cant_watch_embedded_youtube_videos_anymore/flapagt/). It's a bug with uBlock Origin, not Brave.

**Comment by damassi** [comment]
Seems related to adblocking? Testing on chrome with Adblock enabled and no go there either.

**Comment by rebron** [comment]
cc: @ryanbr To keep an eye on. Intermittent issue, could be on YT's side.

**Comment by panchalkalpesh** [comment]
@debiasi I had similar problems and after doing some research I found the following setting fixed this for me. 

Settings > Additional Settings > System > **(disable) Use hardware acceleration when available**

![Screenshot 2020-04-04 at 5 52 01 PM](https://user-images.githubusercontent.com/1808686/78462143-579be900-769d-11ea-8349-c2b0f3ffe8dc.png)


@rebron @ryanbr 
_Source: https://windowsreport.com/an-error-occurred-please-try-again-later-youtube/#4_

**Comment by ryanbr** [comment]
Which GPU do you have @panchalkalpesh ?  Does a re-install of the drivers help?

**Comment by panchalkalpesh** [comment]
Intel HD Graphics 6000 1536 MB
Currently, disabling hardware acceleration in the settings fixes the youtube playback error for me.

> Which GPU do you have @panchalkalpesh ? Does a re-install of the drivers help?

**Comment by ryanbr** [comment]
I would suspect some GPU drivers are more buggy than others, which is why we saw issues on the other browsers. So not a Brave-specific issue

**Comment by debiasi** [comment]
A few days ago it started working again. I still updated to version 1.5.123.
