### ISSUE TITLE
Reserve tokens

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8887]
Right now two contribution could use same tokens as we don't marked them as reserved or in progress.

**Comment by LaurenWags** [comment]
Labeling `QA/Blocked` until additional information is obtained on the test plan item `Make a one-time contribution and force it to fail all retries` from https://github.com/brave/brave-core/pull/5552

**Comment by emerick** [comment]
@LaurenWags I think the simplest thing to do would be to start the contribution and close the browser and manually update the `retry_count` to `3` in the `contribution_info` table. I believe this would simulate the case we're trying to demonstrate.

**Comment by LaurenWags** [comment]
Thanks @emerick - I'll give that a try!

**Comment by LaurenWags** [comment]
@emerick seems like my tips are going thru too quickly - any suggestions?

**Comment by emerick** [comment]
@LaurenWags I wonder if going off the network would convince it to retry?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/5552
Confirmed `version` in `meta` table is at least 27:
<img width="321" alt="Meta" src="https://user-images.githubusercontent.com/28145373/89548494-1cd5c900-d7d5-11ea-8385-42a8c5330691.png">

Confirmed successful 1 time tips have an appropriate `reserved_at` field value:
<img width="940" alt="successful 1 time tip" src="https://user-images.githubusercontent.com/28145373/89548394-fa43b000-d7d4-11ea-9f8f-63cd1a41e6e1.png">

To check that `reserved_at` field is cleared in case of retry failure, I did the following:
   - navigated to a page, opened tip banner, selected a value
   - disabled wifi
   - selected Send tip on the banner
   - closed the browser
   - opened the DB and modified the `step` in `contribution_info` to be 4, modified the `retry_count` in same table to be 3
<img width="584" alt="Screen Shot 2020-08-06 at 11 07 00 AM" src="https://user-images.githubusercontent.com/28145373/89548406-fe6fcd80-d7d4-11ea-8f70-6f9ffa2aadd7.png">

   - confirmed no `redeemed_at` value for the tip in `unblinded_tokens` but there is a `reserved_at` value:
<img width="955" alt="Screen Shot 2020-08-06 at 11 00 50 AM" src="https://user-images.githubusercontent.com/28145373/89548478-17787e80-d7d5-11ea-9be3-9b8300142514.png">

   - saved DB changes
   - re-enabled wifi & relaunched
   - saw `[1304:775:0806/110949.478548:INFO:contribution.cc(713)] Contribution failed after 3 retries` in my logs
   - confirmed tip not deducted from balance or on brave://rewards page
   - confirmed `reserved_at` field is cleared on `unblinded_tokens`
<img width="945" alt="Screen Shot 2020-08-06 at 11 10 43 AM" src="https://user-images.githubusercontent.com/28145373/89548884-9e2d5b80-d7d5-11ea-8129-c60deb60b786.png">

   - repeated above except used 5 for `step` value instead of 4
<img width="586" alt="Screen Shot 2020-08-06 at 11 12 49 AM" src="https://user-images.githubusercontent.com/28145373/89549227-0ed47800-d7d6-11ea-9c9c-3b4220305d5b.png">
<img width="958" alt="Screen Shot 2020-08-06 at 11 13 01 AM" src="https://user-images.githubusercontent.com/28145373/89549232-109e3b80-d7d6-11ea-8434-92636b61e859.png">

   - confirmed `reserved_at` field was cleared as expected:
<img width="947" alt="Screen Shot 2020-08-06 at 11 15 50 AM" src="https://user-images.githubusercontent.com/28145373/89549357-33305480-d7d6-11ea-99ae-292d8d8a81ac.png">
<img width="622" alt="Screen Shot 2020-08-06 at 11 16 05 AM" src="https://user-images.githubusercontent.com/28145373/89549390-3cb9bc80-d7d6-11ea-9afe-9fff1decf529.png">

   - confirmed able to successfully tip after tokens are no longer reserved:
<img width="828" alt="Screen Shot 2020-08-06 at 11 18 06 AM" src="https://user-images.githubusercontent.com/28145373/89549615-86a2a280-d7d6-11ea-9b5e-169f8dea0b6d.png">
<img width="607" alt="Screen Shot 2020-08-06 at 11 18 13 AM" src="https://user-images.githubusercontent.com/28145373/89549618-8904fc80-d7d6-11ea-8650-5dff4a7821b2.png">

----------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.112 x64 build 
- Verified that database is migrated and version is above v27
![image](https://user-images.githubusercontent.com/17010094/90046880-f9c18280-dcc8-11ea-85b1-74f3aafce14e.png)
- Verified `reserved_at` defaults to `0` in migrated unblinded_tokens table
![image](https://user-images.githubusercontent.com/17010094/90047750-57a29a00-dcca-11ea-88bb-7520f48516d5.png)
- Verified for a successful one-time tip `reserved_at` and `redeemed_at` is set correctly 
![image](https://user-images.githubusercontent.com/17010094/90047217-73f20700-dcc9-11ea-96e0-8013a4a9f25a.png)

**Make a one-time contribution and verify that tip gets an appropriate `reserved_at` timestamp**
-  navigated to a page, opened tip banner, selected a value
   - disabled wifi
   - selected Send tip on the banner
   - closed the browser
   - opened the DB and modified the step in `contribution_info` to be 4, modified the `retry_count` in same table to be 3
![image](https://user-images.githubusercontent.com/17010094/90042284-62593100-dcc2-11ea-8040-8a3298749b2a.png)
 - confirmed no redeemed_at value for the tip in `unblinded_tokens` but there is a reserved_at value:
![image](https://user-images.githubusercontent.com/17010094/90042473-a5b39f80-dcc2-11ea-8779-339052cf3a83.png)
- saved DB changes
   - re-enabled wifi & relaunched
   - saw `[1304:775:0806/110949.478548:INFO:contribution.cc(713)] Contribution failed after 3 retries in my logs`
![image](https://user-images.githubusercontent.com/17010094/90045437-f4633880-dcc6-11ea-8f4a-56b66845a7d2.png)
   - confirmed tip not deducted from balance or on brave://rewards page
   - confirmed reserved_at field is cleared on unblinded_tokens
![image](https://user-images.githubusercontent.com/17010094/90044754-04c6e380-dcc6-11ea-8257-6695367b1664.png)

**Verified making a one-time contribution and force it to fail all retries, `reserved_at` field is cleared**
- navigated to a page, opened tip banner, selected a value
   - disabled wifi
   - selected Send tip on the banner
   - closed the browser
   - opened the DB and modified the step in `contribution_info` to be 5, modified the `retry_count` in same table to be 3
![image](https://user-images.githubusercontent.com/17010094/90046183-042f4c80-dcc8-11ea-8c9d-fa12f72bc3a9.png)
- confirmed no redeemed_at value for the tip in `unblinded_tokens` but there is a `reserved_at` value:
![image](https://user-images.githubusercontent.com/17010094/90046225-17dab300-dcc8-11ea-849f-8540a99e548f.png)
- saved DB changes
   - re-enabled wifi & relaunched
   - saw `[1304:775:0806/110949.478548:INFO:contribution.cc(713)] Contribution failed after 3 retries in my logs`
![image](https://user-images.githubusercontent.com/17010094/90046519-80299480-dcc8-11ea-89a7-a0d0e55ee015.png)
   - confirmed tip not deducted from balance or on brave://rewards page
   - confirmed reserved_at field is cleared on `unblinded_tokens`
![image](https://user-images.githubusercontent.com/17010094/90046616-9e8f9000-dcc8-11ea-8d33-62c84f4a69c6.png)
