### ISSUE TITLE
Error when trying to upgrade Brave via brave://settings/help

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#8906]
## Description 
There have been two reports so far on Windows where upgrading doesn't work. You can trigger a check for updates by visiting brave://settings/help and an error message is shown

- One report from @kjozwiak
- One report from community user [Ryan_Firrow](https://community.brave.com/u/ryan_firrow/summary)

## Steps to Reproduce
Steps unknown at this time

## Actual result:
`An error occurred while checking for updates: Unable to connect to the Internet. If you use a firewall, please whitelist BraveUpdate.exe. (error code 7: 0x80040880 -- system level).`
![image](https://user-images.githubusercontent.com/4733304/77844001-38f69900-7157-11ea-8d81-f361f1499382.png)

## Expected result:
Update check should be successful; should either say no update available OR should find update and start download.

## Reproduces how often: 
For affected users, 100%. Does not resolve itself

## Brave version (brave://version info)
Known incidents:
1. `1.2.41` using `x64-rel-full` update channel. Current suspected cause is from installing the 7zip installer from GitHub release (which has been since removed)
2. `1.1.23` using unknown update channel (other details unknown)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N
- Can you reproduce this issue with the beta channel? N
- Can you reproduce this issue with the dev channel? N
- Can you reproduce this issue with the nightly channel? N

**Comment by bsclifton** [comment]
Related https://github.com/brave/brave-browser/issues/2221, https://github.com/brave/devops/issues/920

**Comment by rebron** [comment]
Let's get stats for this from Omaha to assess severity. @mihaiplesa

**Comment by bsclifton** [comment]
@mbacchi put together a great help article which we can edit and put on support.brave.com 😄 We're working with @Brave-Matt to make this happen. Will close issue when we have an article ready

**Comment by mbacchi** [comment]
This has been posted: https://support.brave.com/hc/en-us/articles/360042816611-Why-isn-t-Brave-updating-automatically-on-Windows-

Closing issue, reopen or comment if you still see problems.

**Comment by JimBreton** [comment]
FYI this may be happening to me now, with a slightly different result than what's been logged above.  In my case no error is shown, it just says "Brave is up to date" and I appear to be stuck on 1.29.76.  It **did** thrown an error when I first attempted the update a couple days ago, unfortunately I did not save the text, but it's probably similar to above.  But anytime since then it just says I'm already up to date.

I haven't made any system/installation changes yet, I read the article and I notice the 'ap' key value is 'x64-rel-full' which seems consistent with the above even though the failure mode is different.

If this seems like the same issue I will just proceed with the re-install, but I can hold off if it would help to gather any data before doing so.

**Comment by JimBreton** [comment]
Update: strangely, it now finally did upgrade itself, and the Registry key value mentioned in the support article now is 'x64-rel' so whatever was going on, seems to have self-resolved.  Weird.

If there's any justification for a re-install at this point plz LMK, otherwise I guess I'll just leave it alone.
