### ISSUE TITLE
"404 Sorry, that page is missing." banner shows up when the server returns 'Internal Server Error'

### ISSUE THREAD

**Issue by domdfcoding** [brave/brave-browser#8959]
## Description 
A minority of users are confused by the 404 graphic displayed in the Wayback Machine banner because it doesn't match up to the actual error code (410, 502, etc.). Replace the graphic with a generic one that works for all error codes. 

Original issue described:

> The (new?) "404 Sorry, that page is missing." banner, which shows up when the user navigates to a page that doesn't exist and the server returns HTTP Status Code 404 (Not Found), also shows up when the server returns code 500 (Internal Server Error). 
> 
> I can see the logic in showing the user a prompt to see if the page is available in the Wayback Machine, but the image on the left of the banner that shows "404" is inconsistent with the actual status code returned by the server. 
> 
> The banner also shows up for code 410 (Gone), 502 (Bad Gateway), 503 (Service Unavailable) and 504 (Gateway Timeout), which all make sense for showing the banner for, but the image in the banner is still inconsistent.
> 
> This inconsistency may be confusing to the user if the website displays the HTTP Status Code as part of their custom error page.

## Designs
For all states, replace the '404' image with the new image. Update body text to Poppins and remove other icons from the body copy.

![image](https://user-images.githubusercontent.com/2388823/84422874-8325dd00-abd2-11ea-9c2d-03beff3b144a.png)

After the user clicks to check if a saved version is available, show this state if there's no saved version:

![image](https://user-images.githubusercontent.com/2388823/84422948-9e90e800-abd2-11ea-81e9-9c61ed014243.png)

### Edge case
The Wayback Machine shows a fallback full-page error if the webpage doesn't have its own error page

![image](https://user-images.githubusercontent.com/2388823/84423205-f596bd00-abd2-11ea-9dc1-8de22e6afbb6.png)

![image](https://user-images.githubusercontent.com/2388823/84422557-127ec080-abd2-11ea-89bd-b3d068365979.png)

### Dark theme

Dark theme is supported:

![image](https://user-images.githubusercontent.com/2388823/84423051-c54f1e80-abd2-11ea-95c6-401a5f867287.png)

![image](https://user-images.githubusercontent.com/2388823/84423071-cb44ff80-abd2-11ea-888b-cd37e77bde7e.png)

Figma: https://www.figma.com/file/rz5shvMAAzqjWkfCN8dmAE/Desktop-404-Wayback-Machine?node-id=1%3A1805

**Comment by NejcZdovc** [comment]
I guess we would need static image with number being a text

**Comment by billyc** [comment]
This new feature pops up even when some sites load correctly.

See for example: https://matsim-vsp.github.io/covid-sim/v5

This is because many Github Pages sites use a common "trick" to redirect after a 404 page. For these sites, the Brave 404 error bar shows up even though the page loads correctly (from the user's perspective). This site behavior is possibly in error depending on your point of view, but it is common.

Github Pages does not support server-side redirects, so SPA apps don't work with browser history. Many sites use a custom 404 page which immediately redirects to the SPA home page in order to get around this. 

Many pages online describe the hack, since Github Pages is a popular static site host nowadays:
- https://duckduckgo.com/?t=ffab&q=github+pages+spa+404+hack&ia=web

I am agnostic on whether this hack to get around Pages limitations is "correct", but Brave users are going to see a lot of error bars on sites that otherwise appear to be working.

**Comment by jsekamane** [comment]
I like the idea, but **the design of the banner is confusing**. I've seeing the banner show up maybe 50 times in the last week and *only today* did I realised what it was – and that it was part of the browser and not something the webpages had rendered. It looks like a header on a webpage and not as something that is part of the browser UI. This is because it follows a familiar look with a "logo" in top-left corner and a bar across width of page, as seen below:

<img width="1106" alt="Screenshot 2020-04-17 at 13 40 16" src="https://user-images.githubusercontent.com/1207156/79566020-1dc1de00-80b2-11ea-97d8-a40dec8172ac.png">
<img width="1119" alt="Screenshot 2020-04-17 at 13 41 38" src="https://user-images.githubusercontent.com/1207156/79566046-29150980-80b2-11ea-8cc4-cbdc00c55f5a.png">
<img width="1138" alt="Screenshot 2020-04-17 at 13 41 19" src="https://user-images.githubusercontent.com/1207156/79566038-261a1900-80b2-11ea-9555-7f14dfad48a4.png">
<img width="1124" alt="Screenshot 2020-04-17 at 13 40 53" src="https://user-images.githubusercontent.com/1207156/79566029-231f2880-80b2-11ea-8ac6-d045fe7b1da4.png">

I hope you'll consider updating the design, so it more closely resembles the browser UI. I suggest removing the image, removing the orange-purple colours, and placing the banner at the bottom of the page instead. A good example is the banner that shows up when you download a file, as seen below:

<img width="1029" alt="Screenshot 2020-04-17 at 14 00 54" src="https://user-images.githubusercontent.com/1207156/79567183-0b48a400-80b4-11ea-9c8a-f30efce84d46.png">

**Comment by rebron** [comment]
cc: @karenkliu @jonathansampson

**Comment by rebron** [comment]
@karenkliu Probably better if we make the image not say 404 to avoid confusion and make it a more archive-y/generic image. Trying to sub-brand this as the 404 service and including all the the error codes is confusing folks, especially web devs. Let's not do separate images per error code, e.g. a 502, 503 image.

**Comment by rebron** [comment]
cc: @simonhong

**Comment by radounet-fr** [comment]
similar result here with a page describing a RESTful API definition (that returns an HTTP 200 code):

![image](https://user-images.githubusercontent.com/60200018/81237781-bcca5d80-9000-11ea-8e27-be79b51892ff.png)

**Comment by karenkliu** [comment]
Designs added!

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.101 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5840

Light mode:
![image](https://user-images.githubusercontent.com/38657976/88568314-6ba59500-d056-11ea-9f5a-6688facbbbe7.png)

Dark mode:
![image](https://user-images.githubusercontent.com/38657976/88568369-81b35580-d056-11ea-894b-a639ca9a8be4.png)

Private tab:
![image](https://user-images.githubusercontent.com/38657976/88568532-bfb07980-d056-11ea-926e-7ec2c81692ac.png)

Tor tab:
![image](https://user-images.githubusercontent.com/38657976/88568564-c9d27800-d056-11ea-9e6a-13331135b356.png)

Guest window:
![image](https://user-images.githubusercontent.com/38657976/88568646-ed95be00-d056-11ea-93db-07a80cf4148d.png)
