### ISSUE TITLE
Option to show tabs in page theme color

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#905]
In the live `browser-laptop` code-base, there is a setting (defaulted to enabled) where tabs have a "theme color" which is determined at load time (color is basically coming from sampling the favicon colors, if I remember correctly).

Here's an example showing the tab color for GitHub. It helps the page blend into the tab:
![screen shot 2018-08-31 at 10 35 25 pm](https://user-images.githubusercontent.com/4733304/44942771-2f842f80-ad6e-11e8-9937-133d83be8b2b.png)

In `browser-laptop`, the setting is put into the `tabs` section
![screen shot 2018-08-31 at 10 32 44 pm](https://user-images.githubusercontent.com/4733304/44942776-3b6ff180-ad6e-11e8-9ac8-2319ca8b1275.png)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/features-search-engine-go-keys-missing-colored-tabs-bookmarks-bar/33485?u=eljuno

**Comment by srirambv** [comment]
Personally i'd down vote this as sometime the tab colour is too distracting and harsh. Favicons with same theme colour doesnt look distinguishable. Looks like enitre tab is filled with the tab colour. Example is Twitter icon is blue and page theme is blue so entire tab becomes blue

**Comment by Jacalz** [comment]
I agree with @srirambv on this and it doesn't really fit with tabs on the top 😓

**Comment by LesterCovax** [comment]
I would greatly appreciate this feature, as when you have many tabs open, it can be hard to quickly distinguish which one is active.  My suggestion would be to have the tab highlighted with the opposite color of the theme though, as it would be less distracting.

![image](https://user-images.githubusercontent.com/34850610/72231892-dba56f80-358b-11ea-82fe-acbfe52d621f.png)

To those that don't like the idea, or wouldn't use it, that's why things like feature flags / options exist.  Not sure why you'd thwart the addition of something some would find useful, and could even be disabled by default :suspect:
