### ISSUE TITLE
Add grant check

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#917]
Grant should be checked in the background every 24h

**Comment by NejcZdovc** [comment]
you can see publisher list for an example

**Comment by LaurenWags** [comment]
@NejcZdovc @jasonrsadler just to confirm, QA can't see the UGP grant checks without verbose mode flag, correct? @GeetaSarvadnya and myself tried looking in the terminal for the checks described in the test plan from https://github.com/brave/brave-core/pull/751 but we don't see them. cc @kjozwiak

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/751 (non-verbose test plan) by checking the `last_grant_fetch_stamp` value instead of seeing calls in terminal.
