### ISSUE TITLE
Uphold widget

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#923]
Add uphold widget for add funds and withdrawal flows.

**Comment by NejcZdovc** [comment]
blocked, waiting for uphold

**Comment by mandar-brave** [comment]
Feature (Brief Description); The Uphold widget is meant to support a 2-way wallet allowing existing Brave Rewards users to be able to claim their wallet (moving it out of anon state), add funds (ability to use CC to add funds to BAT cards), and Withdraw funds (right now this will push user to the Uphold site)

Test Site is built to be able to drive the Add Funds use case - however, due to the plug points needed to be able to set BAT card, etc. this test site stops working
Site Link: https://uphold-widget-uhocggaamg.now.sh/

Product Spec (Uphold owned): 
https://docs.google.com/document/d/1Kz5wH9A231snmj6VleqW-_odh4_lAbixoBDjvZb5HoU/edit

Link for developer API (Uphold)
https://uphold.com/en/developer/api/documentation/

Documentation; see attached PDFs (one for flow, one for API call workflow)
[uphold-pay-flows.pdf](https://github.com/brave/brave-browser/files/2507589/uphold-pay-flows.pdf)
[Claim Card Funds API Flow.pdf](https://github.com/brave/brave-browser/files/2507590/Claim.Card.Funds.API.Flow.pdf)

**Comment by diracdeltas** [comment]
please make sure to open a security review issue for this when it's ready for review, thanks.

**Comment by mandar-brave** [comment]
@tomlowenthal i am closing these issues that needed to be addressed for security approvals for this feature
https://github.com/brave/brave-browser/issues/1807
https://github.com/brave/brave-browser/issues/1806
https://github.com/brave/brave-browser/issues/1804

@mkarolin listing the needs here after closing issue.

a) Uphold will be setting a cookie as part of the Brave Rewards claim-wallet functionality - we need to ensure the cookie is whitelisted so accounts can stay current and withdraw deeplink will also need Cookie to be persisted.
b) Netverify.com is the API that is being used for verifying KYC and is getting script blocked. That needs to be whitelisted
c) Netverify KYC process also needs access to user camera for capturing documents, thats getting blocked as well and needs to either (a) ask user for camera permission or (b) should be given permission for camera

**Comment by NejcZdovc** [comment]
closing as we landed it
