### ISSUE TITLE
All asset deposit addresses should be shown in the Binance Widget

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9250]
## Description 
With current widget behavior, only deposit addresses for assets which users have holdings for are available. Binance recently updated their Oauth API to take the default network as a parameter for deposit info, allowing all addresses to be fetched. Networks are provided here: 

https://www.binance.com/gateway-api/v1/public/capital/getNetworkCoinAll

## Steps to Reproduce

   1. Connect the Binance widget
   2. Go to "Deposit"
   3. Click in to the detail view of an asset which you have no holdings for.

## Actual result:
![image (13)](https://user-images.githubusercontent.com/8732757/79409707-6fa02200-7f53-11ea-8869-43207661f86b.png)

## Expected result:
An ETH deposit address to be shown, along with a QR code for the address.

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@ryanml I don't think this was resolved via https://github.com/brave/brave-core/pull/5267. I can still reproduce it on `1.10.24 CR: 81.0.4044.129` which includes the above PR. This is what I'm seeing now:

<img width="371" alt="Screen Shot 2020-05-03 at 12 41 39 PM" src="https://user-images.githubusercontent.com/2602313/80920137-d71fe500-8d3b-11ea-824c-177a4df8838c.png">

Rather than displaying `Address Not Available` as we do in `1.8.86 CR: 81.0.4044.129` which is the current release, I see `Info Not Available` being displayed. I double checked via Binance to make sure that I have a generated address so I'm assuming I should see it being listed.

Mind taking a look? Let me know if there's something that I might be missing.

**Comment by kjozwiak** [comment]
@ryanml @bbondy so looks like the above happens when you have no assets in Binance. If a new user creates an account and starts using the widget, they'll see `Info Not Available`. However, once you transfer a single asset in your account, the `deposit` info will start appearing for all the assets. Example:

* Create a brand new Binance account and connect it to Brave via the NTP widget
* Even though there's address generated under Binance, they won't appear in the `Deposit` section of the NTP widget
* Send ~10-15 BAT to your Binance BAT card
* Once you've received the funds, you'll start noticing the addresses being listed under the `deposit` section of the NTP widget.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.4 x64 Catalina` using the following build:

```
Brave | 1.8.89 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.15.4 (Build 19E287)
```

* ensured that the cases outlined under both https://github.com/brave/brave-browser/issues/9250#issue-600710839 & https://github.com/brave/brave-core/pull/5267#issuecomment-623149001 passed without any issues
* ensured that the `Rewards` widget is the default widget on a clean install
* ensured that the `Address` & `QR Code` are being displayed for all tokens
   * ensured `Address` & `QR Code` is being displayed for tokens with a balance
   * ensured `Address` & `QR Code` is being displayed for tokens without a balance
* ensured that clicking on `Copy` correctly copies the tokens address
* ensured that clicking on the `QR Code` displays the code without any issues
* ensured that the `Address` & `QR Code` are being displayed for tokens without balances when upgrading from the following:
   * `1.8.86 CR: 81.0.4044.129` --> `1.8.89 CR: 81.0.4044.129`
   * `1.10.19 CR: 81.0.4044.129` --> `1.10.24 CR: 81.0.4044.129`

Ran into https://github.com/brave/brave-browser/issues/9600 with an account without any deposits.

| Address| QR Code|
| ------- |:---------:|
| <img width="347" alt="Screen Shot 2020-05-04 at 12 56 41 AM" src="https://user-images.githubusercontent.com/2602313/80937231-49c3ab80-8da2-11ea-889e-f41c97ff5e4e.png"> | <img width="382" alt="Screen Shot 2020-05-04 at 12 56 46 AM" src="https://user-images.githubusercontent.com/2602313/80937236-4fb98c80-8da2-11ea-9c87-e3fc3c992769.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.8.89 Chromium: 81.0.4044.129 (Official Build) (64-bit)
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{# 979}
OS | Windows 10 OS Version 1809 (Build 17763.1158)

- Verified with holding in one of the coins, all coins show their deposit address
- Verified QR code matches the address when available
- Verified Copy button copies the address into clipboard
- Verified upgrading from `1.8.86` to `1.8.89` shows all deposit address 
- Encountered #9600 on a new Binance account with no holdings 
--------
 Verification passed on 

Brave | 1.8.89 Chromium: 81.0.4044.129 (Official Build) (64-bit)
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{# 979}
OS | Linux

- Verified with holding in one of the coins, all coins show their deposit address
- Verified QR code matches the address when available
- Verified Copy button copies the address into clipboard
- Verified upgrading from `1.8.86` to `1.8.89` shows all deposit address 
- Encountered #9600 on a new Binance account with no holdings
