### ISSUE TITLE
Allow users to show Brave Ads in full screen mode if they choose

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#9264]
## Description 
As a follow up to #9209, we should consider introducing a setting, defaulted to off, that allows users to see ads even while in full screen mode.

**Comment by jaredready** [comment]
FWIW I went a _very_ (embarrassingly) long time just thinking ads on Mac were broken because I never received them. One day I actually just noticed a coworker using his browser not in fullscreen mode (its my default for everything) and saw an ad pop up. That's when it clicked for me and I created #9209.

I can't imagine I'm the only person who has ran into that. If the goal is to get ads and BAT into as many hands as possible I think it makes a lot of sense to either a) provide a little bit more control around this, or b) at least make it more clear that fullscreen on Mac (a very common thing for people) will stop ads from showing up.

Thanks for the hard work you folks you do! I am a huge fan of Brave and the BAT model for monetization on the web.

**Comment by Xyncgas** [comment]
yay let's detect if it's a mac and start showing ads @ full screen, allowing both the windows and mac user to turn it off, fun.

**Comment by theoneandonly4** [comment]
Same here - Installed Brave on my brand new MacBook Air after using it on Windows and Linux for a while and got 1 ad in the last month before actively looking for a solution and finding the community topic below that brought me here.

https://community.brave.com/t/not-recieving-any-ads-on-macos/121430

For a regular user using Brave in Full Screen all the time it may just seem like the ads are just not working on Mac which does not look so good. I'm glad I found this solution though I'd be happier if I could use Brave in Full Screen again.

**Comment by MentheFraiche** [comment]
I think it may be a good solution to let the user decide if he wants to receive ads when using Brave in full screen mode.
Since this is a default feature in macOS to extend windows to full screen, many users could report it as a bug.

Also, in my opinion, full screen mode and presentation mode are two separate behaviours.

**Comment by phlyk** [comment]
Been using Brave for almost a month now with no Ads, even with troubleshooting using the HTML5 Notification generator and looking at the logs I couldn't figure out why "notifications were not allowed". I only just found out that this is "by design".

The argument that fullscreen mode == DND is completely dependent on the User's way of working. Definitely should be an option and also clearly documented (until the feature is implemented) that Ads won't be displayed if you fullscreen Brave.

**Comment by PrateekArora03** [comment]
Even I am also facing the same problem when I am using Brave in the Full-Screen mode, then I am not receiving ads on Latest MacOS.

**Comment by ebrainte** [comment]
Ive been using brave for 4 month until now, and ive received just 5 ads in those months, i couldnt figure out why that was happening (when I use Windows ads works well, but not on my mac) until i figured out it was because of "full screen", then i get here.

Please, brave should have an option to allow ads even if you are in this "full screen" mode, because macos full screen mode is really different from Windows full screen mode. In macos, pretty much everyone makes the apps full screen, because its easier to move thru apps (by swiping the trackpad).

**Comment by esmusssosein** [comment]
Please Brave fix this issue. 
I work 95 % in Fullscreen mode on Mac!

**Comment by chetanpm** [comment]
Notification centre would push other notifications while brave is in the full screen mode, so I didn't think the browser disables ads notification when in full screen. It should've existed even without a setting to toggle ON while in full screen.

**Comment by cgarren** [comment]
Yes please! I almost never use any browser in windowed mode, so I thought this was broken for the longest time. A toggle for showing ads in fullscreen would be awesome to have. In addition, if the purpose of this feature is to prevent ads from showing during movies/gaming, maybe have a feature that detects if either of those actions are taking place (if it's not a privacy violation)

**Comment by lina-kram** [comment]
I was wondering the same thing! I use a wide monitor, so I constantly have the full screen mode on (with tabs splitting the screen in half), and since it’s a working computer I’d never watch Netflix on it and wouldn’t be “disturbed” by an ad when in full screen mode. I wish I could change the default and see push ads :(

**Comment by tmancey** [comment]
Close as wont fix
