### ISSUE TITLE
Do not clear favicons

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#927]
Now when you clear images, we lose icons on rewards page. We need to persist them.

![image](https://user-images.githubusercontent.com/9574457/44955026-b2ab9f80-aeac-11e8-8d09-ce374afcd47f.png)

One temp proposal is that we detect onerror when loading images and if that happens we load faviconUrl and trigger re-cache.

**Comment by rebron** [comment]
Fix should be in Rewards, people would perceive this as an issue.

**Comment by NejcZdovc** [comment]
@reborn why was this one closed?

**Comment by bsclifton** [comment]
@NejcZdovc during a mini-triage, a few of us discussed and basically if a user picks to delete icons/files/etc, they expect EVERYTHING to be deleted

Keeping something just because we use it for Rewards is just like how Google Chrome clears all the cookies... except your Google account ones (something that folks were vocally opposed to). You can hit up @bbondy and @rebron over Slack if you'd like more information

**Comment by bsclifton** [comment]
@NejcZdovc awesome- I'd like to propose whatever the solution is as something that shows in here too (ex: `Brave Rewards` would show as something you can clear under `Clear browsing data`) 😄
