### ISSUE TITLE
[Desktop] "Learn more" is not the first option for Rewards or Binance widgets

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9391]
## Description 

Per screenshots in https://github.com/brave/brave-browser/issues/8883#issue-588818266 I was expecting "Learn more" to be the first option for Rewards and Binance widgets, it is not.

@karenkliu if this is expected, please close this issue.

## Steps to Reproduce

   1. Open NTP
   2. Click on ... icon on either Rewards or Binance widget

## Actual result:

<img width="302" alt="Screen Shot 2020-04-22 at 11 54 04 AM" src="https://user-images.githubusercontent.com/28145373/80004499-66054580-8490-11ea-958b-1ac61ca65324.png">

## Expected result:
Learn more to be first option per https://github.com/brave/brave-browser/issues/8883

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @ryanml

**Comment by karenkliu** [comment]
@LaurenWags Yeah, "Learn More" should come first. In general we should keep the most destructive action at the bottom of the widget menu if there are multiple actions provided.

**Comment by rebron** [comment]
@karenkliu Understand what you're saying. Usual convention is actual functions first and help links towards the bottom. I get that this might work for the widget stack now but would it apply to other widgets like top sites as they change or even with the widget stack as they add more options.

Inclined to do wontfix here.

**Comment by karenkliu** [comment]
@rebron Yep, most destructive action  "Hide" would also apply to other widgets as we add more options. 

The convention for UX design is to keep the most destructive action at the bottom - whether it's log out, delete account, delete X, or put something in trash. But this convention also carries over to other browsers. Here's some examples:

Firefox
<img width="370" alt="Screen Shot 2020-06-12 at 11 02 00 AM" src="https://user-images.githubusercontent.com/2388823/84533222-87b6c800-ac9c-11ea-9d72-980b540defe1.png">

Safari
<img width="276" alt="Screen Shot 2020-06-12 at 11 03 55 AM" src="https://user-images.githubusercontent.com/2388823/84533227-8ab1b880-ac9c-11ea-8d50-58d7aa14f208.png">

<img width="241" alt="Screen Shot 2020-06-12 at 11 14 54 AM" src="https://user-images.githubusercontent.com/2388823/84533959-fa747300-ac9d-11ea-9a54-4de93f42c12f.png">

Opera
<img width="384" alt="Screen Shot 2020-06-12 at 11 04 00 AM" src="https://user-images.githubusercontent.com/2388823/84533239-91d8c680-ac9c-11ea-9b21-000b07342ef4.png">

Microsoft Edge
<img width="259" alt="Screen Shot 2020-06-12 at 11 05 34 AM" src="https://user-images.githubusercontent.com/2388823/84533279-a74df080-ac9c-11ea-9cba-e057c709d790.png">

<img width="327" alt="Screen Shot 2020-06-12 at 11 06 00 AM" src="https://user-images.githubusercontent.com/2388823/84533295-b3d24900-ac9c-11ea-8567-3cb9743355d9.png">

Vivaldi
<img width="259" alt="Screen Shot 2020-06-12 at 11 05 34 AM" src="https://user-images.githubusercontent.com/2388823/84533359-d5cbcb80-ac9c-11ea-93dc-cbbaa943586b.png">

<img width="255" alt="Screen Shot 2020-06-12 at 11 06 56 AM" src="https://user-images.githubusercontent.com/2388823/84533361-d6fcf880-ac9c-11ea-8ba3-e11431042c36.png">


## Some non-browser examples

Spotify
<img width="212" alt="Screen Shot 2020-06-12 at 11 11 02 AM" src="https://user-images.githubusercontent.com/2388823/84533669-74582c80-ac9d-11ea-826f-2b3a7f28e38b.png">

Medium
<img width="213" alt="Screen Shot 2020-06-12 at 11 11 07 AM" src="https://user-images.githubusercontent.com/2388823/84533677-76ba8680-ac9d-11ea-9d44-679a1fbbf3d1.png">

Airbnb
<img width="285" alt="Screen Shot 2020-06-12 at 11 11 37 AM" src="https://user-images.githubusercontent.com/2388823/84533727-95208200-ac9d-11ea-8158-b6612fe5c437.png">

Linkedin
<img width="301" alt="Screen Shot 2020-06-12 at 11 13 03 AM" src="https://user-images.githubusercontent.com/2388823/84533830-c4cf8a00-ac9d-11ea-908f-f4a66f0d9dcd.png">
<img width="256" alt="Screen Shot 2020-06-12 at 11 13 15 AM" src="https://user-images.githubusercontent.com/2388823/84533832-c600b700-ac9d-11ea-8797-eb37fdbaef73.png">
![Screen Shot 2020-06-12 at 11 18 11 AM](https://user-images.githubusercontent.com/2388823/84534302-89818b00-ac9e-11ea-9adb-9e768b2ccc5b.png)


The original designs for the widget menu had the most destructive action at the bottom due to this pervasive UX convention. It wasn't built per design spec so Lauren is correct to file the bug. Let's try to fix this issue.

BTW, I'm not saying that destructive actions are never put at the top of menus - sometimes they are, because it's farthest from the user's thumb and the accessibility of least-used options is de-prioritized over more important actions (e.g. some iOS apps) but this widget menu is on desktop so that doesn't apply here. Also it's our browser so if we strongly prefer having destructive actions at the top of menus, we can do so. However it wouldn't follow users' mental models of where the most destructive action goes, which would detract from usability.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.53 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified STR from description

<img width="308" alt="Screen Shot 2020-10-28 at 1 54 41 PM" src="https://user-images.githubusercontent.com/28145373/97476871-4fe7ae80-1925-11eb-8dab-c52644001529.png">
<img width="308" alt="Screen Shot 2020-10-28 at 1 54 53 PM" src="https://user-images.githubusercontent.com/28145373/97476875-5118db80-1925-11eb-9799-e4e781662741.png">

------------
