### ISSUE TITLE
can you turn off the ability to tear off tabs and how would i run the software if i download it?

### ISSUE THREAD

**Issue by tarbear123** [brave/brave-browser#942]
can you turn off the ability to tear off tabs and how would i run the software if i download it?

**Comment by srirambv** [comment]
Is this for the current release version or brave-core?

**Comment by bbondy** [comment]
There is no ability to not tear off tabs, but I suspect also you might be using the current version of Brave and not the version of brave offered in the github release page here which is the next one.

**Comment by neutraali** [comment]
What I understand by "tearing off tabs" is the current behaviour of dragging and dropping a tab to create a new Brave window (whether you want to or not...).

This is extremely annoying when all I want to do is (safely) arrange / reorder a few tabs. I rarely actually succeed at this because the Brave UI is extremely strict at where it allows tabs to be dragged to. The visual cues about where I'm about to drop the tabs aren't exactly the best either.

**Comment by srirambv** [comment]
@neutraali i assume you talking about `0.23.105` version which is muon browser. The new brave-core will have the same mechanisms as Chrome so you won't have the same behaviour as the current released version. Hope this makes it clear.

**Comment by bsclifton** [comment]
@neutraali can you download / try this version?
https://brave.com/download-dev

Behavior should be much improved 😄 You can also import your existing Brave settings. Brave Payments (which has been reworked as `Brave Rewards`) is not working yet
