### ISSUE TITLE
Fix broken unit tests caused by 8535

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9448]
Fix broken unit tests caused by 8535

**Comment by kjozwiak** [comment]
@bsclifton moving this into `1.9.x` but this was merged into `1.8.x` due to Android needing this fix for their `1.8.x` release. If we have another `1.8.x HF` for desktop, this will need to be moved into that milestone. Moving this into `1.9.x` for desktop.

Created https://github.com/brave/brave-browser/issues/9628
