### ISSUE TITLE
Remove drop shadows from brave://rewards/

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#9450]
## Description 
[A user on Twitter](https://twitter.com/imfuat/status/1253704155501387780) recently shared the Settings page cards lack drop shadows seen on the Rewards page, even though the two pages share many other style elements.

## Steps to Reproduce
Navigate to about:rewards
Navigate to about:settings

## Actual result:
Drop shadows present on Rewards page, but not Settings page.

## Expected result:
Drop shadows removed from Rewards page.

## Reproduces how often: 
Always

## Brave version (brave://version info)
1.7.98

**Comment by karenkliu** [comment]
The issue here is not to add drop shadows to the Settings page; it's to _remove_ drop shadows from the Brave Rewards page. 

The design team has standardized our drop shadow treatment so that only UI elements sitting on top of the page, such as menus and modals, will get the drop shadows. In this case the cards on the Brave Rewards page is "Layer 0 Content" so they do not get a drop shadow.

Drop shadows per UI layer defined: 
![image](https://user-images.githubusercontent.com/2388823/80828812-c8e69300-8b9a-11ea-9375-7ae7efe2156c.png)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.28 Chromium: 86.0.4240.75 (Official Build) nightly (x86_64)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Confirmed no shadows on brave://rewards page with 1.17.x

<details>
<summary>1.16.x shadows exist</summary>

<img width="941" alt="1 16 x 1" src="https://user-images.githubusercontent.com/28145373/95761732-bc528480-0c7a-11eb-9720-fce74bed0f13.png">
<img width="889" alt="1 16 x 2" src="https://user-images.githubusercontent.com/28145373/95761739-be1c4800-0c7a-11eb-887b-6633af1e4b18.png">

</details>

<details>
<summary>1.17.x no shadows</summary>

<img width="923" alt="1 17 x 1" src="https://user-images.githubusercontent.com/28145373/95761743-bfe60b80-0c7a-11eb-8fdc-96a4f85e9e73.png">
<img width="881" alt="1 17 x 2" src="https://user-images.githubusercontent.com/28145373/95761748-c1afcf00-0c7a-11eb-8381-f6c96244fc49.png">

</details>

--------------
