### ISSUE TITLE
[Android] Publisher list improvements

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#9456]
## Description
This is a duplicate issue tracking Android implementation of 3 existing Desktop issues
- Improve publisher list insert time/memory/cpu #9376
- Query is not correct if social links are empty #9440
- Optimize timers for publisher lists #9441

## Test plan
See steps:
1. https://github.com/brave/brave-core/pull/5301
2. https://github.com/brave/brave-core/pull/5355
3. https://github.com/brave/brave-core/pull/5356

**Comment by bsclifton** [comment]
Closing as https://github.com/brave/brave-core/pull/5322 is merged 🎉

**Comment by kjozwiak** [comment]
**`Improve publisher list insert time/memory/cpu #9376`**

Verification **PASSED** on `Samsung S10+` with `Android 10` using https://github.com/brave/brave-browser/releases/tag/v1.7.102

* ensured that the `Publisher List` isn't being downloaded when initially launching Brave while rewards is disabled
* ensured that the `Publisher List` is downloaded without any issues once rewards has been enabled as per the following example:

```
    [ RESPONSE - OnDownload ]
    > time: 1588138224
    > result: Success
    > http code: 200
    > response: Publisher list
    > headers accept-ranges: bytes
    > headers access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
    > headers access-control-allow-methods: GET
    > headers access-control-allow-origin: https://rewards.bravesoftware.com
    > headers access-control-request-method: GET
    > headers age: 2254
    > headers cache-control: max-age=3600, public
    > headers content-encoding: gzip
    > headers content-length: 19042981
    > headers content-type: application/json; charset=utf-8
    > headers date: Wed, 29 Apr 2020 05:30:23 GMT
    > headers etag: W/"ee53adbbe92dfdd94206e2a3a3e42f1b"
    > headers server: Cowboy
    > headers status: 200
    > headers strict-transport-security: max-age=31536000; includeSubDomains
    > headers vary: Accept-Encoding
    > headers via: 1.1 varnish
    > headers x-cache: HIT
    > headers x-cache-hits: 0
    > headers x-frame-options: deny
    > headers x-request-id: 0e75a547-1af6-4e75-8257-2ac645f46d85
    > headers x-runtime: 2.544231
    > headers x-served-by: cache-yyz4541-YYZ
    [ END RESPONSE ]
```

Unfortunately `Android` currently doesn't display custom banners. This will be addressed via https://github.com/brave/brave-browser/issues/7766 so that particular part of the test plan can't be checked/verified.

However, ensured that the following websites appeared as verified and displayed the checkmark via the BAT panel as expected:
* `https://www.chess.com`, `https://brave.com`, `https://www.khanacademy.org`

Also went through the following case several times and ensured that enabling rewards while browsing a website that has a lot of content doesn't cause any performance issues while the publisher list is being downloaded:

* installed `1.7.102 CR: 81.0.4044.112` and skipped onboarding (rewards stays disabled)
* loaded https://giphy.com and while swiping/loading content, enabled rewards and ensured that the `publisher list` was being downloaded

**Comment by kjozwiak** [comment]
Also went through the above cases using the following:

Verification **PASSED** on `Samsung Tablet A` with `Android 9` using https://github.com/brave/brave-browser/releases/tag/v1.7.102

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.7.102 x64 stable build

- Verified `Publisher List` is not downloaded when rewards is disabled/turned off
- Verified `Publisher List` is downloaded when rewards is enabled
``` 
  [ RESPONSE - OnDownload ]
    > time: 1588155648
    > result: Success
    > http code: 200
    > response: Publisher list
    > headers accept-ranges: bytes
    > headers access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
    > headers access-control-allow-methods: GET
    > headers access-control-allow-origin: https://rewards.bravesoftware.com
    > headers access-control-request-method: GET
    > headers age: 2981
    > headers cache-control: max-age=3600, public
    > headers content-encoding: gzip
    > headers content-length: 19148172
    > headers content-type: application/json; charset=utf-8
    > headers date: Wed, 29 Apr 2020 10:20:43 GMT
    > headers etag: W/"051eb47c9031c73f1a8726ee012c9226"
    > headers server: Cowboy
    > headers status: 200
    > headers strict-transport-security: max-age=31536000; includeSubDomains
    > headers vary: Accept-Encoding
    > headers via: 1.1 varnish
    > headers x-cache: HIT
    > headers x-cache-hits: 0
    > headers x-frame-options: deny
    > headers x-request-id: e15b65c2-cdaa-42c1-9f39-418444626f1b
    > headers x-runtime: 3.729647
    > headers x-served-by: cache-bom18221-BOM
    [ END RESPONSE ]
```
- Verified moving device date ahead by 7 and relaunching triggers download of `Publisher List`
```
   [ RESPONSE - OnDownload ]
    > time: 1588760936
    > result: Success
    > http code: 200
    > response: Publisher list
    > headers accept-ranges: bytes
    > headers access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
    > headers access-control-allow-methods: GET
    > headers access-control-allow-origin: https://rewards.bravesoftware.com
    > headers access-control-request-method: GET
    > headers age: 2981
    > headers cache-control: max-age=3600, public
    > headers content-encoding: gzip
    > headers content-length: 19148172
    > headers content-type: application/json; charset=utf-8
    > headers date: Wed, 29 Apr 2020 10:28:57 GMT
    > headers etag: W/"051eb47c9031c73f1a8726ee012c9226"
    > headers server: Cowboy
    > headers status: 304
    > headers vary: Accept-Encoding
    > headers via: 1.1 varnish
    > headers x-cache: HIT
    > headers x-cache-hits: 0
    > headers x-frame-options: deny
    > headers x-request-id: e15b65c2-cdaa-42c1-9f39-418444626f1b
    > headers x-runtime: 3.729647
    > headers x-served-by: cache-bom18221-BOM
    [ END RESPONSE ]
```
- Verified removing browser from memory and relaunching doesn't start downloading the `Publisher List`
- Verified enabling rewards via panel on a clean install does the same 
- Verified no browser hang when `Publisher List` is being downloaded while using a image heavy site like giphy.com
