### ISSUE TITLE
New publisher list (v4)

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9502]

**Comment by LaurenWags** [comment]
Android specific issue logged with https://github.com/brave/brave-browser/issues/10836

**Comment by LaurenWags** [comment]
Verified cases below using a mix of

```
Brave	1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
Revision	19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS	macOS Version 10.14.6 (Build 18G3020)
```

```
Brave	1.12.99 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
Revision	19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS	macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5568, confirmed publisher status was as expected.

In addition to the test plan above, also checked the various publisher statuses and how they display with the various wallet types as below:

1. Using a restored anon wallet (with deposited user funds) confirm various publisher statuses:
 - **PASSED** Visit an unverified publisher. 
   - Confirm pub status in panel, tip banners. 
   - Confirm panel and tip banners show expected messaging about unverified publisher. 
   - Confirm publisher can be added to AC table (if applicable, not all publisher types are part of AC). 
   - Do a recurring tip. Confirm recurring tip shows in monthly contributions panel on rewards page. 
   - Do a one time tip. Confirm one time tip goes to pending list immediately. 
   - Confirm correct pub status is displayed on brave://rewards page. 
   - Confirm when recurring tip is contributed it goes to pending list. 
   - Confirm AC does not occur for this publisher. 
   - Confirm this publisher does not show in monthly statement on any section.

 - **PASSED** Visit a connected (not KYC'd) publisher. 
   - Confirm pub status in panel, both tip banners, including custom banner if applicable.
   - Confirm publisher can be added to AC table (if applicable, not all publisher types are part of AC). 
   - Do a recurring tip. Confirm recurring tip shows in monthly contributions table on rewards page. 
   - Do a one time tip. Confirm one time tip displays in tips table on rewards page, on summary and monthly statement.
   - Confirm correct pub status is displayed on brave://rewards page. 
   - Confirm when recurring tip is contributed it shows in summary and monthly statement. 
   - Confirm when AC is contributed it shows in summary and monthly statement. 
   - Confirm this publisher is shown correctly in monthly statement on all applicable sections.

 - **PASSED** Visit a KYC'd publisher. 
   - Confirm pub status in panel, both tip banners, including custom banner if applicable.
   - Confirm publisher can be added to AC table (if applicable, not all publisher types are part of AC). 
   - Do a recurring tip. Confirm recurring tip shows in monthly contributions table on rewards page. 
   - Do a one time tip. Confirm one time tip displays in tips table on rewards page. 
   - Confirm correct pub status is displayed on brave://rewards page. 
   - Confirm when recurring tip is contributed it shows in summary and monthly statement. 
   - Confirm when AC is contributed it shows in summary and monthly statement. 
   - Confirm this publisher is shown correctly in monthly statement on all applicable sections.


2. Using a wallet with VG funds confirm various publisher statuses:
 - **PASSED** Visit an unverified publisher. 
   - Confirm pub status in panel, tip banners. 
   - Confirm panel and tip banners show expected messaging about unverified publisher. 
   - Confirm publisher can be added to AC table (if applicable, not all publisher types are part of AC). 
   - Do a recurring tip. Confirm recurring tip shows in monthly contributions panel on rewards page. 
   - Do a one time tip. Confirm one time tip goes to pending list immediately. 
   - Confirm correct pub status is displayed on brave://rewards page. 
   - Confirm when recurring tip is contributed it goes to pending list. 
   - Confirm AC does not occur for this publisher. 
   - Confirm this publisher does not show in monthly statement on any section.

 - **PASSED** Visit a connected (not KYC'd) publisher. 
   - Confirm pub status in panel, both tip banners, including custom banner if applicable.
   - Confirm publisher can be added to AC table (if applicable, not all publisher types are part of AC). 
   - Do a recurring tip. Confirm recurring tip shows in monthly contributions table on rewards page. 
   - Do a one time tip. Confirm one time tip displays in tips table on rewards page, on summary and monthly statement.
   - Confirm correct pub status is displayed on brave://rewards page. 
   - Confirm when recurring tip is contributed it shows in summary and monthly statement. 
   - Confirm when AC is contributed it shows in summary and monthly statement. 
   - Confirm this publisher is shown correctly in monthly statement on all applicable sections.

 - **PASSED** Visit a KYC'd publisher. 
   - Confirm pub status in panel, both tip banners, including custom banner if applicable.
   - Confirm publisher can be added to AC table (if applicable, not all publisher types are part of AC). 
   - Do a recurring tip. Confirm recurring tip shows in monthly contributions table on rewards page. 
   - Do a one time tip. Confirm one time tip displays in tips table on rewards page. 
   - Confirm correct pub status is displayed on brave://rewards page. 
   - Confirm when recurring tip is contributed it shows in summary and monthly statement. 
   - Confirm when AC is contributed it shows in summary and monthly statement. 
   - Confirm this publisher is shown correctly in monthly statement on all applicable sections.

3. Using a KYC'd Uphold wallet confirm various publisher statuses:
 - **PASSED** Visit an unverified publisher. 
   - Confirm pub status in panel, tip banners. 
   - Confirm panel and tip banners show expected messaging about unverified publisher. 
   - Confirm publisher can be added to AC table (if applicable, not all publisher types are part of AC). 
   - Do a recurring tip. Confirm recurring tip shows in monthly contributions panel on rewards page. 
   - Do a one time tip. Confirm one time tip goes to pending list immediately. 
   - Confirm correct pub status is displayed on brave://rewards page. 
   - Confirm when recurring tip is contributed it goes to pending list. 
   - Confirm AC does not occur for this publisher. 
   - Confirm this publisher does not show in monthly statement on any section.

 - **PASSED** Visit a connected (not KYC'd) publisher. 
   - Confirm pub status in panel, both tip banners, including custom banner if applicable.
   - Confirm panel and tip banners show expected messaging about publisher who has not configured their account to receive tips/contributions. 
   - Confirm publisher can be added to AC table (if applicable, not all publisher types are part of AC). 
   - Do a recurring tip. Confirm recurring tip shows in monthly contributions table on rewards page. 
   - Do a one time tip. Confirm one time tip goes to pending list immediately. 
   - Confirm correct pub status is displayed on brave://rewards page. 
   - Confirm when recurring tip is contributed it goes to pending list. 
   - Confirm when AC is contributed it shows in summary and monthly statement. 
   - Confirm this publisher is shown correctly in monthly statement on all applicable sections.

 - **PASSED** Visit a KYC'd publisher. 
   - Confirm pub status in panel, both tip banners, including custom banner if applicable.
   - Confirm publisher can be added to AC table (if applicable, not all publisher types are part of AC). 
   - Do a recurring tip. Confirm recurring tip shows in monthly contributions table on rewards page. 
   - Do a one time tip. Confirm one time tip displays in tips table on rewards page. 
   - Confirm correct pub status is displayed on brave://rewards page. 
   - Confirm when recurring tip is contributed it shows in summary and monthly statement. 
   - Confirm when AC is contributed it shows in summary and monthly statement. 
   - Confirm this publisher is shown correctly in monthly statement on all applicable sections.

Verified the below using

```
Brave	1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
Revision	a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS	macOS Version 10.14.6 (Build 18G3020)
```


4. Confirm that each type of publisher (website, YT, etc) pulls info for banners correctly:
   - **PASSED** Clean profile, enable rewards. Visit a verified website. Confirm it gets the correct status in panel and on banners. Confirm custom banner info is displayed.
   - **PASSED** Clean profile, enable rewards. Visit a verified YT channel. Confirm it gets the correct status in panel and on banners. Confirm custom banner info is displayed.
   - **PASSED** Clean profile, enable rewards. Close and restart browser due to existing issue. Visit a verified Twitch channel. Confirm it gets the correct status in panel and on banners. Confirm custom banner info is displayed. (Note, existing Twitch issues encountered were: https://github.com/brave/brave-browser/issues/5848, https://github.com/brave/brave-browser/issues/6851, https://github.com/brave/brave-browser/issues/7826)
   - **PASSED** Clean profile, enable rewards. Visit a verified Vimeo channel. Confirm it gets the correct status in panel and on banners. Confirm custom banner info is displayed.
   - **PASSED** Clean profile, enable rewards. Visit a verified Twitter channel. Confirm it gets the correct status in panel and on banners. Click on in-line tip button. Confirm it gets the correct status in the banner. Confirm custom banner info is displayed.
   - **PASSED** Clean profile, enable rewards. Visit a verified Reddit channel. Confirm it gets the correct status in panel and on banners. Click on in-line tip button. Confirm it gets the correct status in the banner. Confirm custom banner info is displayed.
   - **PASSED** Clean profile, enable rewards. Visit a verified GitHub channel. Confirm it gets the correct status in panel and on banners. Click on in-line tip button (need to be signed in). Confirm it gets the correct status in the banner. Confirm custom banner info is displayed.

5. **PASSED** Upgrade case A
   - Install 1.11.x (current release channel version), enable Rewards, confirm entire publisher list is downloaded, close browser.
   - Confirm server_publisher_info and other server_publisher_* tables are populated.
   - Upgrade to 1.12.x, launch browser. Confirm inserting records into publisher prefix table is complete.
   - Open publisher DB.
   - Confirm server_publisher_info and other server_publisher_* tables are now empty.
   - Confirm publisher_prefix_list is populated (each row should contain one field with raw binary data).

6. **PASSED** Upgrade case B
   - Install 1.11.x (current release channel version), enable Rewards, confirm entire publisher list is downloaded, close browser.
   - Remove a publisher from the DB (I removed all associated information from all server_publisher* tables)
   - Run 1.11.x and visit the publisher you removed, confirm they do not show as verified in UI. Close tab with this page.
   - Close browser.
   - Upgrade to 1.12.x. 
   - Launch. Confirm inserting records into publisher prefix table is complete. Visit the publisher you removed.
   - Confirm publisher shows correct status on panel and banners.
   - Open DB and confirm publisher info is correct for this publisher (info will be added to server_publisher_* tables as you browse to verified/connected sites).

7. **PASSED** Upgrade case C
   - Install 1.11.x (current release channel version), enable Rewards, connect KYC'd Uphold account, confirm entire publisher list is downloaded, close browser.
   - Open DB and modify a KYC'd publisher to be connected (change status field in server_publisher_info from 2 to 1 and I deleted the address field contents also).
   - Run 1.11.x and visit the publisher you removed.
   - Confirm this publisher shows the messaging about how this user has not configured their account to receive tips. Close this page.
   - Close browser.
   - Upgrade to 1.12.x. 
   - Launch. Confirm inserting records into publisher prefix table is complete. Visit the publisher you removed.
   - Confirm the publisher shows as fully verified (no messaging about unable to receive tips) on panel and banners.
   - Open DB and confirm publisher info is correct for this publisher (info will be added to server_publisher_* tables as you browse to verified/connected sites).

8. **PASSED** Upgrade case D
   - Install 1.11.x (current release channel version), enable Rewards, confirm entire publisher list is downloaded.
   - Visit some sites (mix of verified and unverified) to populate your AC table
   - Set up a couple recurring tips to verified/non verified sites
   - Send a couple of tips to verified sites
   - Upgrade to 1.12.x
   - Confirm AC list is still populated and all sites in the AC list still show the correct status (verified/not verified as applicable)
   - Confirm recurring tips list still shows the correct status for sites (verified/not verified as applicable)
   - Confirm tips list still shows the correct status for sites (verified)

Additional notes - confirmed there is no more "auto-exclude" list with v4.

------------------
