### ISSUE TITLE
Use global top navigation bar for settings, rewards, history, bookmarks, downloads

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#956]
## Description 
Use global top navigation bar for:
chrome://settings
chrome://rewards
chrome://history
chrome://bookmarks/
chrome://downloads

Search widget should invoke the inline search function for the specific page i.e. if on Settings should search settings, if on Bookmarks should search Bookmarks.

Labels should be: "Search Settings", "Search History", "Search Bookmarks", "Search Downloads"

## Design
![](https://user-images.githubusercontent.com/5951041/45058482-b0cd1200-b04d-11e8-943d-d08053594a0b.png)

**Comment by petemill** [comment]
In lieu of a design which explains how this behaves with different width (tranlated) text and on different window sizes, I'm going to make the following assumptions in the implementation unless I hear otherwise:

- The search box is a static width as shown in the mockup
- We'll add the kebab to the right of the search box, as is currently on Bookmarks and History, and again fixed width
- The titles take up the remaining width, up until the toolbar meets the window width, at which point the text will become truncated with `...`

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.63.20 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

Navigation Bar URL's
![image](https://user-images.githubusercontent.com/17010094/54940401-080ad500-4f01-11e9-819e-d0bf60607f74.png)

Custom checkboxes 
![image](https://user-images.githubusercontent.com/17010094/54940464-253fa380-4f01-11e9-97d4-5c92d8fefc6b.png)

Custom buttons
![image](https://user-images.githubusercontent.com/17010094/54940493-35578300-4f01-11e9-9ec5-6b8208e6ce43.png)

Typograpohy
![image](https://user-images.githubusercontent.com/17010094/54940662-941cfc80-4f01-11e9-82d0-7a4c04b90477.png)

Bookmarks (narrow Nav Bar)
![image](https://user-images.githubusercontent.com/17010094/54940690-a4cd7280-4f01-11e9-9bf6-ca49b1af94f0.png)

Downloads (wide Nav Bar)
![image](https://user-images.githubusercontent.com/17010094/54940738-b6af1580-4f01-11e9-84f1-83c6d11f26dc.png)

Extensions Nav Bar (with 'Developer Mode' submenu)
![image](https://user-images.githubusercontent.com/17010094/54940767-c890b880-4f01-11e9-93c3-8c6fdbf557a7.png)
