### ISSUE TITLE
[Android] no notification when wallet is disconnected

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9576]
## Description 
On desktop if you manually disconnect your Uphold wallet or you need to reauthorize Brave Browser, a notification displays on the panel. Android gets the little red bubble, but there's no notification text.

## Steps to reproduce 

   1. Install uphold wallet capable version
   2. Enable Rewards, connect KYC'd uphold account
   3. Confirm uphold account is connected
   4. Close Brave on Android.
   5. On another device (laptop) login to Uphold account, navigate to authorized applications and remove Brave Browser.
   6. Reopen Android.
   7. No notification on panel.
   8. Navigate to chrome://rewards page
--> see notification red bubble on panel
   9. Open panel
---> no notification displays

## Actual result 
No notification/text displays

note - wallet status (upper left corner) does show `Disconnected` as expected.

## Expected result
something like what displays on desktop
<img width="402" alt="Screen Shot 2020-05-01 at 1 01 57 PM" src="https://user-images.githubusercontent.com/28145373/80835258-63a59880-8bc0-11ea-9a67-3bdc02c04b04.png">

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? Nightly

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
```

Brave | 1.10.22 Chromium: 81.0.4044.129 (Official Build) canary (32-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Android 5.1; Nexus 5 Build/LMY47D

```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by jenn-rhim** [comment]
We won't treat auth key expiration as an error case. We display instead this message to guide the user to reestablish the auth key, which simply require user to re-login to Uphold. Upon successful auth, user should be redirected to the browser wallet in the connected state, restoring the balance.

<img width="439" alt="Screen Shot 2020-06-26 at 10 09 22 AM" src="https://user-images.githubusercontent.com/4369856/85883669-362b3480-b796-11ea-937a-33ceb3fbacad.png">

*Please be sure that this is not caused by our server issues. For that case, it tends to be temporary and no remedy that the user can perform is advisable, other than wait.

<img width="892" alt="Screen Shot 2020-06-26 at 10 08 34 AM" src="https://user-images.githubusercontent.com/4369856/85883906-9d48e900-b796-11ea-8240-5e7eeaccc3b2.png">


@NejcZdovc @anthonypkeane @mandar-brave

**Comment by mandar-brave** [comment]
Thank you @jenn-rhim - i will put some other everyday cases that can do better; sending your way.
These look good.

**Comment by LaurenWags** [comment]
@Miyayes this is still applicable to Android.

I just reproduced with the following:

pre-req: have device set to Japanese
1. Clean install 1.35.62
2. Navigate QA Preferences
3. Enable staging environment, relaunch as necessary
4. Enable Rewards
5. Select Verify Wallet and login with bitFlyer account
6. Confirm balance is shown in UI
7. Wait at least 7 minutes
8. Attempt to tip a verified bitFlyer creator
9. Confirm tip does not go through
10. Confirm UI now shows the "Disconnected" (Logged out) state
---> There is no message on the UI (panel or chrome://rewards) alerting the user that they need to log back in

**Comment by Miyayes** [comment]
Per "Token Expiration due to Tipping - Partially PASSED" test case in https://github.com/brave/internal/issues/838#issuecomment-999633411: the notification should look like this:

![image](https://user-images.githubusercontent.com/11497541/147706049-a511e4bf-c0a0-4159-99db-6fbe336a4a85.png)

**Comment by Miyayes** [comment]
Will be using this newly refiled issue to track this: https://github.com/brave/brave-browser/issues/20603 Thanks all.
