### ISSUE TITLE
Single Window,  without Tab => Open in Single window and not in Tab (Disable Tab's)

### ISSUE THREAD

**Issue by blackcrack** [brave/brave-browser#9598]
## Description  
in the past times of FF was it possible to open a new Link in a Single Window open ,  
this is possible but the Tab is already to show .

## Steps to Reproduce  
   1.  open Google
   2. search "test"
   3. open an link in a new Window and you see the Tab and not a clean Window without Tab.

## Actual result:  
Tab not able to disable.

## Expected result:
a clean window without a Tab,
only the Buttons and Adressbar
A possible to 
[X] disable the Tab

## Reproduces how often: 
~

## Brave version (brave://version info)

Brave ist auf dem neuesten Stand
Version 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)

best regards
Blacky

**Comment by rebron** [comment]
@blackcrack That feature to disable the tabs bar in Firefox was from a long time ago when tabs were underneath the url bar. The UI you're looking for I guess matches what's in Safari now which still has tabs underneath the url bar.

Because we have tabs on top, and the UE benefits of tab browsing in general, this is something I don't see us fixing.

**Comment by blackcrack** [comment]
well, under FF works with css .. and want you say Safari is more better as Brave ?

best regards
Blacky
