### ISSUE TITLE
Linux dark mode is still light

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#965]
Linux color properties likely come from a theme related to a native mode.

![image](https://user-images.githubusercontent.com/741836/45064248-97d15a80-b067-11e8-8573-24f65366a5b1.png)

**Comment by bbondy** [comment]
cc @simonhong

**Comment by simonhong** [comment]
Hmm, it's strange. color options work well on my local machine(ubuntu 17.10, gnome-shell).
@petemill Can you check `BraveThemeService::GetDefaultColor()` is called?

**Comment by maikelmclauflin** [comment]
same thing happens on mac. I found that if after changing the `brave colors` dropdown, you toggle the `disable home button` the color seems to update.

**Comment by AlexeyBarabash** [comment]
I can also see it on my Linux Ubuntu 16.04 LTS.

**Comment by btlechowski** [comment]
Still reproducible on

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/57395353-35b59000-71c8-11e9-95c7-aca297e9d10f.png)

https://github.com/brave/brave-browser/issues/3894 needs to be re-verified when this issue is fixed.

**Comment by bsclifton** [comment]
Dupe of https://github.com/brave/brave-browser/issues/5098
