### ISSUE TITLE
Audit server responses

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9666]
We should audit all server responses.

- Create response folder and move all parsing of responses into this folder
- Create per feature files (like we have them in requests
- We need to make sure that every param is validated accordingly (meaning can it be empty or not, is it correct format, etc)

**Comment by emerick** [comment]
@husobee will provide info on HTTP response codes (thank you!)

**Comment by LaurenWags** [comment]
Marked as `QA/Blocked` pending additional test plan information (requested from @NejcZdovc )

**Comment by GeetaSarvadnya** [comment]
Verification is in progress

```

Brave | 1.13.77 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
`Wallet funded via UGP grants`

- Verified checkmark is shown in BR panel as well as in Tipping banner for verified pubs
- Verified one-time tips and monthly tips processed successfully
- Verified AC is working fine for verified pubs (added more than 3 pubs in AC table)
- Verified wallet summary is displayed correctly
- Verified wallet summary and monthly statement are showing the correct stats for One-time tip, monthly tip and AC 
- Verified brave://rewards-internals data is shown as expected for `Contributions`, `General info` and `Promotions`
- Encountered https://github.com/brave/brave-browser/issues/10238#issuecomment-677747881

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.81 x64 build

- Verified the following scenarios:  

  <details>
  <summary><b>Wallet funded via UGP grants alone</b></summary>

  - [x]  Verified wallet status is Not connected in brave://rewards-internals
  - [x]  Verified checkmark is shown in BR panel as well as in Tipping banner for verified pubs
  - [x]  Verified checkmark is shown in AC table, Monthly contribution table and One-time tips panel for verified pubs
  - [x]  Verified checkmark is shown in Monthly statement for AC, Monthly contributions and One-time tips for verified pubs
  - [x]  Verified one-time tips and monthly tips processed successfully
  - [x]  Verified AC is working fine for verified pubs (added more than 3 pubs in AC table)
  - [x]  Verified wallet summary is displayed correctly
  - [x]  Verified wallet summary is showing the correct stats for One-time tip, monthly tip and AC
  - [x]  Verified brave://rewards-internals data is shown as expected for Contributions, General info and Promotions
  - [x]  Verified rewards summary isn't lost after browser restart
  - [x]  Verified able to tip verified pubs when AC is turned off

  </details>

  <details>
  <summary><b>Wallet funded via KYC'd uphold alone</b></summary>

  - [x] Verified wallet status is Verified in brave://rewards-internals
  - [x] Verified checkmark is shown in BR panel as well as in Tipping banner for verified pubs
  - [x] Verified checkmark is shown in AC table, Monthly contribution table and One-time tips panel for verified pubs
  - [x] Verified checkmark is shown in Monthly contributions and One-time tips for verified pubs
  - [x] Verified one-time tips and monthly tips processed successfully
  - [x] Verified AC is working fine for verified pubs (added more than 3 pubs in AC table)
  - [x] Verified AC is triggered for connected pubs (e.g DDG)
  - [x] Verified one-time tips sent for connected pubs isn't displayed in tips panel as expected
  - [x] Verified one time tips and recurring tips for a connected publisher is going into pending contribution list after AC 
  - [x] Verified wallet summary is displayed correctly
  - [x] Verified wallet summary and monthly statement are showing the correct stats for One-time tip, monthly tip and AC
  - [x] Verified brave://rewards-internals data is shown as expected for Contributions, General info and Promotions
  - [x] Verified transactions are listed correctly in Uphold Recent Activity section
  - [x] Verified rewards summary isn't lost after browser restart
  - [x] Verified able to tip verified pubs when AC is turned off
  
  </details>

  <details>
  <summary><b>Wallet balance =(Ad grants+KYC'd uphold)</b></summary>

  - [x]  Blocked due to #11298

  </details>

  <details>
  <summary><b>Wallet balance =(UGP+KYC'd uphold)</b></summary>

  - [x]  Verified wallet status is Verified in brave://rewards-internals
  - [x]  Verified checkmark is shown in AC table, Monthly contribution table and One-time tips panel for verified pubs
  - [x]  Verified checkmark is shown in Monthly contributions and One-time tips for verified pubs
  - [x]  Verified one-time tips and monthly tips processed successfully
  - [x]  Verified AC is working fine for verified pubs (added more than 3 pubs in AC table)
  - [x]  Verified wallet summary is displayed correctly
  - [x]  Verified wallet summary is showing the correct stats for One-time tip, monthly tip and AC
  - [x]  Verified brave://rewards-internals data is shown as expected for Contributions, General info and Promotions
  - [x]  Verified BAT distributed to verified pubs after AC is shown correctly in brave://rewards-internals page
  - [x]  Verified BAT distributed for AC from Rewards (UGP) and Uphold is shown correctly
    <img width=300 src=https://user-images.githubusercontent.com/17010094/91712270-50f79c00-eb7f-11ea-97a5-0f4a6774151b.png>
  - [x]  Verified transactions are listed correctly in Uphold Recent Activity section
  - [x]  Verified GH, Vimeo, YT, general verified pubs can be added to AC table
  - [x]  Verified rewards summary isn't lost after browser restart
  - [x]  Verified able to tip verified pubs when AC is turned off

  </details>

  <details>
  <summary><b>Wallet balance =(UGP+Deposited BAT)</b></summary>

   - Not supported for Android
  </details>

  <details>
   <summary><b>Wallet balance =(Deposited BAT+KYC'd Uphold wallet )</b></summary>

   - Not supported for Android
  </details>
