### ISSUE TITLE
NTP SI images are visible for every NTP after terminating SR component

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#9716]
## Description 

When SR campaign is ended, SI images are visible for every NTP.
However, NTP should show SI images for every 4th NTP.
This behavior is fixed after restarting or SI component is updated.

## Steps to Reproduce

   1. Launch Browser with SR code
   2. Check NTP shows SR images
   3. Terminate current SR campaign
   4. Update SR component via brave://components
   5. Check how often SI images are visible

## Actual result:

SI images are visible for every tab

## Expected result:
SI images are visible for every 4th tab

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Labeling as `QA/No` after discussing with @bsclifton. Because of the time constraints and needing to get `1.10.x` out the door ASAP, we'll be skipping QA as this will take time and coordination.

However, this was already QA'd on Nightly when it was first merged by both @bsclifton and @LaurenWags so some QA was completed as per https://github.com/brave/brave-core/pull/5510#pullrequestreview-413803147 and https://github.com/brave/brave-core/pull/5510#issuecomment-635530331.
