### ISSUE TITLE
Continuous crash of the browser

### ISSUE THREAD

**Issue by gabriel-coelho** [brave/brave-browser#9727]
## Description 
The browser crashes every time it is open. It usually takes 20sec to 2min for it to crash

## Steps to Reproduce
   1. Open the browser
   2. Type anything
   3. Browser crashes

## Actual result:
Crash

## Expected result:
Normal use of the browser

## Reproduces how often: 
Everytime

## Brave version (brave://version info)
1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
macOS: macOS Version 10.15.4 (Build 19E287)
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome?
No

**Comment by bsclifton** [comment]
@gabriel-coelho do you notice it crashing when you do anything in particular? Like clicking the URL bar and trying to type?

You can try launch from the command line to see if you get more output. Launching would look like:
`/Applications/Brave Browser.app/Contents/MacOS/Brave Browser`

And then you'd start to get some output which might be helpful. If you're able to use it for long enough, you can try navigating to brave://settings/privacy and then enable `Help improve Brave's features and performance`, so that we can get a crash report. Any previous crashes will also show under `brave://crashes` and will have a submit report button (having the report ID would be helpful for us)

**Comment by bsclifton** [comment]
Looks like you've already sent at least one crash report - thanks! 😄 
https://github.com/brave/brave-browser/issues/7581#issuecomment-627026631

**Comment by gabriel-coelho** [comment]
Hey, I already solved the problem, but it required some drastic measures.
I deleted EVERY FILE I had on my mac that was related to brave. After that, I reinstalled the browser, and everything worked fine.
I hope you can dive deep into this thanks to my previous bug reports because I'm not the only user who is having problems with this.
