### ISSUE TITLE
Do not allow closing of pinned tabs.

### ISSUE THREAD

**Issue by yuujay** [brave/brave-browser#9793]
## Description 
If a browser tab is pinned, do not allow it to be closed when `cmd+W` is clicked. This feature already exisits in FireFox.

## Steps to Reproduce

   1. Right click on an opened tab and select `Pin`
   2. Go to the pinned tab. 
   3. Press `cmd+W` on Mac or `ctrl+W` on windows. 

## Actual result:
This closes the tab. 

## Expected result:
Shouldn't close the tab. The whole purpose of pinning a tab is not to close it accidentally. 

## Reproduces how often: 
Easy to reproduce

## Brave version (brave://version info)
Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Other Additional Information:
- Is the issue reproducible on the latest version of Chrome?  Yes.

**Comment by bsclifton** [comment]
This is expected behavior... but we do have an issue you might want to +1 😄 
https://github.com/brave/brave-browser/issues/4963

This is a feature request to require the shortcut hotkeys be held down for a few seconds alongside a message, to prevent accidental closure. I think you can still bring back pinned tabs with Ctrl + Shift + T (or Cmd+Shift+T)

**Comment by gustavotrott** [comment]
I created an extension as a workaround to prevent pinned tabs from being closed accidentally:

https://github.com/gustavotrott/brave-lock-pinned-tabs

Feel free to use if it can help you guys to tackle this issue!

**Comment by inkihh** [comment]
Why is this closed as won't fix because it's "expected behavior"? It's clearly a feature request, and a good one!
