### ISSUE TITLE
Is there a way to hide the GPUCache folder from the home directory?

### ISSUE THREAD

**Issue by wildcard-f8** [brave/brave-browser#9801]
At seemingly random times a folder called GPUCache appears in my home directory. I've deleted it and I've tried hiding it but it always comes back. In the case of hiding it, it creates another folder that's not hidden. I've asked around and another user told that it's being created by chrome or chromium. I don't have either but I do have Brave. Is there anything that can be done?

![Screenshot from 2020-05-16 17-24-07](https://user-images.githubusercontent.com/51791246/82116215-9c399a80-979a-11ea-8968-504b6cc61f32.png)

Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux

**Comment by bsclifton** [comment]
@wildcard-f8 I'm not aware of a way to stop this - it's expected behavior. Brave is using Chromium code, which inherits that default behavior. There might be a way to debug using brave://gpu - for example disabling hardware acceleration. I wouldn't do that though - this should be a beneficial thing

Were you more concerned what it is? Or just wanting to get rid of it?

**Comment by borisjoffe** [comment]
I second moving this directory somewhere it makes more sense like $XDG_CACHE_HOME or at least $XDG_DATA_HOME or $XDG_CONFIG_HOME.

Cache files shouldn't be clogging up a user's home directory and if other programs behaved this badly, the home directory would be unusable.

If it's not fixed upstream in Chromium, Brave should do it itself (similar to how Brave kept "Reopen closed tab" in the tab context menu after Chromium made the dumb decision to remove it).
