### ISSUE TITLE
Rendering issues with google.com ads

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#9954]
## Description 
Clicking on google text ads will cause rendering issues.

## Steps to Reproduce

   1. With shields enabled (standard blocking), Open `www.google.com`
   2. search  `samsung galaxy tab`
   3. Click on text advert

## Actual result:

2 issues possibly occurs, rendering of the page breaks, or the title-bar of the advert disappears.

![image (1)](https://user-images.githubusercontent.com/1659004/82965062-37dccd80-a01b-11ea-92c7-5cd5bd6cec37.png)

## Expected result:
Allow the user to see advert/interact with advert.

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)
`Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Disabling all shield options, while still having shields enabled shows this also.

![console](https://user-images.githubusercontent.com/1659004/82965114-5cd14080-a01b-11ea-96de-10b53f1aef8c.png)

**Comment by kjozwiak** [comment]
@pes10k @AndriusA are you still experiencing this?

**Comment by pes10k** [comment]
Nope!  And this should be solved with https://github.com/brave/brave-core/pull/6013

**Comment by pes10k** [comment]
I think this is good to close, if you agree @kjozwiak

**Comment by rebron** [comment]
Closing. Looks good with latest RC. I noticed @ryanbr mentioned intermittent and could be due to the privacy reminder dialog that was inserted into the page in his mock. I didn't get that dialog. 

Brave | 1.11.94 Chromium: 84.0.4147.85 (Official Build) (64-bit)
-- | --
Revision | e20c13e958edc3707db3d26d513780a7f6331a4b-refs/branch-heads/4147@{#837}


![Screen Shot 2020-07-10 at 9 45 42 AM](https://user-images.githubusercontent.com/5951041/87178538-23365b00-c292-11ea-89e7-6b94014eceab.png)
